erDiagram
    release_phase {
        text id PK
        text release_id FK
        text created_at
        jsonb description_attachment
        text description_body
        text description_created_at
        text description_id
        text duration_source
        text end_on
        text name
        text progress
        text progress_source
        text start_on
        text type
        text updated_at
    }
    release_integration_field {
        text id PK
        text release_id PK
        text created_at
        text integration_id
        text name
        text service_name
        text value
    }
    release_initiative {
        text initiative_id PK
        text release_id PK
    }
    release_goal {
        text goal_id PK
        text release_id PK
    }
    release_custom_field_score_fact {
        text id PK
        text release_custom_field_id PK
        text release_id PK
        text name
        text value
    }
    release_custom_field {
        text id PK
        text release_id PK
        jsonb attachments
        text body
        text created_at
        text email_value
        text key
        text name
        text type
        text updated_at
        jsonb value
    }
    release {
        text id PK
        text owner_id FK
        text parent_id FK
        text product_id FK
        text workflow_status_id FK
        text comments_count
        text created_at
        text created_by_user_id
        text development_started_on
        text duration_source
        text end_date
        text external_date_resolution
        text external_release_date
        text external_release_date_description
        text master_release
        text name
        text original_estimate
        text parking_lot
        text position
        text progress
        text progress_source
        text project_created_at
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_workspace_type
        text reference_num
        text release_date
        text released
        text released_on
        text remaining_estimate
        text resource
        text start_date
        text status_changed_on
        jsonb theme_attachments
        text theme_body
        text theme_created_at
        text theme_id
        text theme_updated_at
        text updated_at
        text url
        text work_done
        text work_units
        jsonb workflow_status_times
    }
    strategic_model_component {
        text id PK
        text strategic_model_id PK
        text description
        text name
    }
    strategic_model {
        text id PK
        text kind
        text name
        text project_created_at
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_workspace_type
        text resource
        text url
    }
    persona {
        text id PK
        text product_id FK
        text created_at
        text name
    }
    goal_parent {
        text goal_id PK
        text id PK
        text name
    }
    goal_attachment {
        text id PK
        text goal_id PK
        text content_type
        text created_at
        text download_url
        text file_name
        text file_size
        text original_file_size
        text updated_at
    }
    goal_integration_field {
        text id PK
        text goal_id PK
        text goal_initiative_id PK
        text created_at
        text integration_id
        text name
        text service_name
        text value
    }
    goal_initiative {
        text goal_id PK
        text id PK
    }
    goal_feature {
        text goal_id PK
        text id PK
    }
    goal_release {
        text goal_id PK
        text id PK
    }
    goal_custom_field {
        text id PK
        text goal_id PK
        text key
        text name
        text type
        text updated_at
        text value
    }
    goal_workflow_status_time {
        text status_id PK
        text goal_id PK
        text ended_at
        text started_at
        text status_name
    }
    goal {
        text id PK
        text product_id FK
        text success_metric_workflow_status_id FK
        text comments_count
        text created_at
        text description_body
        text description_created_at
        text description_id
        text effort
        text name
        text position
        text progress
        text progress_source
        text project_created_at
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_workspace_type
        text reference_num
        text resource
        jsonb success_metric_description_attachment
        text success_metric_description_body
        text success_metric_description_created_at
        text success_metric_description_id
        text success_metric_name
        text updated_at
        text url
        text value
    }
    workflow_status {
        text id PK
        text workflow_id PK
        text color
        text complete
        text name
        text position
    }
    workflow_kind {
        text id PK
        text workflow_id PK
        text name
    }
    workflow {
        text id PK
        text product_id FK
        text name
        text statusable_type
        text transitions_only
    }
    epic_custom_field_score_fact {
        text id PK
        text epic_custom_field_id PK
        text epic_id PK
        text name
        text value
    }
    epic_custom_field {
        text id PK
        text epic_id PK
        jsonb attachments
        text body
        text created_at
        text email_value
        text key
        text name
        text type
        text updated_at
        text value
    }
    epic_workflow_status_time {
        text id PK
        text epic_id PK
        text ended_at
        text started_at
        text status_name
    }
    epic {
        text id PK
        text created_by_user_id FK
        text owner_id FK
        text product_id FK
        text release_id FK
        text workflow_status_id FK
        text assigned_to_user
        jsonb attachments
        text comments_count
        text created_at
        jsonb description_attachments
        text description_body
        text description_created_at
        text description_id
        text description_updated_at
        text due_date
        text duration_source
        jsonb epic_links
        text epic_only_original_estimate
        text epic_only_remaining_estimate
        text epic_only_work_done
        jsonb features
        jsonb full_tags
        jsonb goals
        text initial_estimate
        text initiative_reference_num
        jsonb integration_fields
        text master_feature_only_original_estimate
        text master_feature_only_remaining_estimate
        text master_feature_only_work_done
        text name
        text original_estimate
        text owner_created_at
        text owner_email
        text owner_name
        text owner_updated_at
        text position
        text progress
        text progress_source
        text project_created_at
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_url
        text project_workspace_type
        text reference_num
        text release_created_at
        jsonb release_integration_fields
        text release_name
        text release_parking_lot
        text release_product_id
        text release_reference_num
        text release_resource
        text release_url
        text remaining_estimate
        text resource
        text score
        jsonb score_facts
        text start_date
        text status_changed_on
        jsonb tags
        jsonb time_tracking_events
        text updated_at
        text url
        text use_feature_estimates
        text work_done
        text work_units
        text workflow_status_color
        text workflow_status_complete
        text workflow_status_name
        text workflow_status_position
    }
    record_link {
        text id PK
        text child_record_id FK
        text feature_id FK
        text parent_record_id FK
        text child_record_created_at
        text child_record_name
        text child_record_product_id
        text child_record_reference_num
        text child_record_resource
        text child_record_type
        text child_record_url
        text created_at
        text link_type
        text link_type_id
        text parent
        text parent_record_created_at
        text parent_record_name
        text parent_record_product_id
        text parent_record_reference_num
        text parent_record_resource
        text parent_record_type
        text parent_record_url
    }
    user_product_role {
        text product_id PK
        text users_id PK
        text product_name
        text role
        text role_description
    }
    user_role {
        text role_id PK
        text users_id PK
        text name
        text scope_id
        text scope_name
        text scope_type
    }
    users {
        text id PK
        text accessed_at
        text administer_account
        text administer_billing
        text administer_configuration
        text administrator
        text created_at
        text email
        text enabled
        text identity_provider_name
        text identity_provider_type
        text name
        text paid_seat
        text paid_seat_group_id
        text paid_seat_group_name
        text updated_at
    }
    task_assigned_to_user {
        text id PK
        text task_id PK
        text user_id FK
        text status
    }
    task_attachment {
        text id PK
        text task_id PK
        text content_type
        text created_at
        text download_url
        text file_name
        text file_size
        text original_file_size
        text updated_at
    }
    task {
        text id PK
        text created_by_user_id FK
        text product_id FK
        text body
        text comments_count
        text created_at
        text due_date
        text name
        text position
        text resource
        text status
        text taskable_id
        text taskable_name
        text taskable_reference_num
        text taskable_resource
        text taskable_type
        text taskable_url
        text updated_at
        text url
    }
    strategic_vision_component {
        text id PK
        text strategic_vision_id PK
        text name
        text title
    }
    strategic_vision {
        text id PK
        text created_at
        text description
        text name
        text project_created_at
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_workspace_type
        text resource
        text updated_at
        text url
    }
    integration {
        text id PK
        text created_at
        text name
        text service_name
    }
    idea_custom_field {
        text id PK
        text idea_id PK
        text attachments
        text body
        text created_at
        text editor_version
        text email_value
        text key
        text name
        text type
        text updated_at
        text value
    }
    idea_workflow_status_time {
        text status_id PK
        text idea_id PK
        text ended_at
        text started_at
        text status_name
    }
    idea {
        text id PK
        text created_by_user_id FK
        text product_id FK
        text workflow_status_id FK
        text assigned_to_user
        jsonb categories
        text created_at
        text created_by_user_created_at
        text created_by_user_email
        text created_by_user_name
        text created_by_user_updated_at
        jsonb description_attachments
        text description_body
        text description_created_at
        text description_editor_version
        text description_id
        text description_notable_id
        text description_notable_type
        text description_updated_at
        text endorsements_count
        jsonb full_tags
        text initial_votes
        jsonb integration_fields
        text name
        text reference_num
        text resource
        text score
        jsonb score_facts
        text status_changed_at
        jsonb tags
        text updated_at
        text url
        text visibility
    }
    idea_user_organizations {
        text index PK
        text idea_user_id PK
        text id FK
    }
    idea_user {
        text id PK
        text created_at
        jsonb custom_fields
        text discovery_interview_count
        text discovery_last_interview
        text discovery_last_invite
        text discovery_next_interview
        text email
        jsonb integration_fields
        text name
    }
    strategic_component {
        text id PK
        text strategic_position_id PK
        text description
        text name
    }
    strategic_position {
        text id PK
        text kind
        text name
        text project_created_at
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_workspace_type
        text resource
        text url
    }
    idea_subscription {
        text id PK
        text idea_id FK
        text workflow_status_id FK
        text created_at
        jsonb description_attachments
        text description_body
        text description_created_at
        text description_editor_version
        text description_id
        text description_notable_id
        text description_notable_type
        text description_updated_at
        text portal_user_created_at
        text portal_user_email
        text portal_user_id
        text portal_user_name
    }
    feature_custom_field {
        text id PK
        text feature_id PK
        text key
        text name
        text type
        text updated_at
        text value
    }
    feature {
        text id PK
        text product_id FK
        text release_id FK
        text workflow_id FK
        text created_at
        text created_by_user_id
        jsonb description_attachment
        text description_body
        text description_created_at
        text description_id
        text description_updated_at
        text due_date
        text epic_reference_num
        text feature_only_original_estimate
        text feature_only_remaining_estimate
        text feature_only_work_done
        text goal_id
        text initial_estimate
        text initiative_id
        text initiative_reference_num
        text name
        text original_estimate
        text position
        text progress
        text progress_source
        text reference_num
        text release_reference_num
        text remaining_estimate
        text requirement_id
        text resource
        text score
        text start_date
        text status_changed_on
        text updated_at
        text url
        text use_requirements_estimates
        text work_done
        text work_units
    }
    release_feature {
        text feature_id PK
        text product_id FK
        text release_id FK
    }
    competitor {
        text id PK
        text product_id FK
        text created_at
        text name
    }
    idea_comment {
        text id PK
        text idea_commenter_idea_user_id FK
        text idea_commenter_user_id FK
        text idea_id FK
        text workflow_status_id FK
        jsonb attachments
        text body
        text created_at
        jsonb description_attachments
        text description_body
        text description_created_at
        text description_editor_version
        text description_id
        text description_updated_at
        text idea_commenter_portal_user_created_at
        text idea_commenter_portal_user_email
        text idea_commenter_portal_user_id
        text idea_commenter_portal_user_name
        text parent_idea_comment_id
        text visibility
    }
    idea_category {
        text id PK
        text product_id PK
        text created_at
        text name
        text parent_id
        text project_id
    }
    idea_organization {
        text id PK
        text created_by_user_id FK
        text created_at
        jsonb custom_fields
        jsonb description_attachments
        text description_body
        text description_created_at
        text description_editor_version
        text description_id
        text description_notable_id
        text description_notable_type
        text description_updated_at
        text email_domains
        text endorsements_count
        jsonb integration_fields
        text name
        text reference_num
        text revenue
        text updated_at
        text url
    }
    creative_brief {
        text id PK
        text product_id FK
        text created_at
        text name
    }
    product {
        text id PK
        text parent_id FK
        text capacity_planning_enabled
        jsonb children
        text created_at
        text default_capacity_units
        jsonb description_attachments
        text description_body
        text description_created_at
        text description_id
        text description_updated_at
        text enhanced_capacity_planning_enabled
        text has_epics
        text has_ideas
        text has_master_features
        text name
        text product_line
        text product_line_type
        text reference_prefix
        text resource
        text updated_at
        text url
        text workspace_type
    }
    initiative_custom_field_score_fact {
        text id PK
        text initiative_custom_field_id PK
        text initiative_id PK
        text name
        text value
    }
    initiative_custom_field {
        text id PK
        text initiative_id PK
        jsonb attachments
        text body
        text created_at
        text email_value
        text key
        text name
        text type
        text updated_at
        jsonb value
    }
    initiative_epic {
        text epic_id PK
        text initiative_id PK
    }
    attachment {
        text id PK
        text initiative_id PK
        text content_type
        text created_at
        text download_url
        text file_name
        text file_size
        text original_file_size
        text updated_at
    }
    master_feature {
        text id PK
        text initiative_id PK
    }
    initiative_feature {
        text id PK
        text initiative_id PK
        text product_id FK
        text created_at
        text name
        text reference_num
        text resource
        text url
    }
    workflow_status_time {
        text initiative_id PK
        text status_id PK
        text ended_at
        text started_at
        text status_name
    }
    initiative_integration_field {
        text id PK
        text initiative_id PK
        text created_at
        text integration_id
        text name
        text service_name
        text value
    }
    initiative {
        text id PK
        text assigned_to_user_id FK
        text created_by_user_id FK
        text product_id FK
        text workflow_status_id FK
        jsonb attachment
        text color
        text comments_count
        text created_at
        text description_body
        text description_created_at
        text description_id
        text duration_source
        text effort
        text end_date
        text initial_estimate
        text name
        text original_estimate
        text position
        text presented
        text progress
        text progress_source
        text project_created_at
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_workspace_type
        text reference_num
        text remaining_estimate
        text resource
        text score
        jsonb score_facts
        text start_date
        text status
        text time_frame_id
        text time_frame_name
        jsonb time_tracking_events
        text updated_at
        text url
        text value
        text work_done
        text work_units
    }
    idea_vote {
        text id PK
        text endorsed_by_idea_user_id FK
        text idea_id FK
        text idea_organization_id FK
        text workflow_status_id FK
        text created_at
        jsonb custom_fields
        text description_attachments
        text description_body
        text description_created_at
        text description_editor_version
        text description_id
        text description_notable_id
        text description_notable_type
        text description_updated_at
        text endorsed_by_portal_user_created_at
        text endorsed_by_portal_user_email
        text endorsed_by_portal_user_id
        text endorsed_by_portal_user_name
        text endorsed_by_portal_user_updated_at
        text idea_organization_id_id
        jsonb integration_fields
        text link
        text updated_at
        text value
        text weight
    }
    release_epic {
        text epic_id PK
        text release_id FK
    }
    requirement_custom_field {
        text id PK
        text requirement_id PK
        text key
        text name
        text type
        text updated_at
        text value
    }
    requirement_integration_field {
        text id PK
        text requirement_id PK
        text created_at
        text integration_id
        text name
        text service_name
        text value
    }
    requirement {
        text id PK
        text assigned_to_user_id FK
        text created_by_user_id FK
        text feature_id FK
        text release_id FK
        text workflow_status_id FK
        jsonb attachment
        text comments_count
        text created_at
        jsonb description_attachment
        text description_body
        text description_created_at
        text description_id
        jsonb full_tags
        text name
        text position
        text reference_num
        text resource
        jsonb tags
        text updated_at
        text url
    }
    team {
        text id PK
        text automatically_calculate_team_members_count
        text capacity
        text color
        jsonb custom_fieldo
        text end_date
        text hourly_rate
        text name
        text project_id
        text project_name
        text project_product_line
        text project_reference_prefix
        text project_workspace_type
        text schedule_hours_per_day
        text schedule_id
        text schedule_name
        text schedule_story_points_per_day
        text schedule_velocity
        text start_date
        text team_members_count
        text team_members_email
        text team_members_id
        text team_members_name
        text team_members_user_id
        text team_members_virtual
    }
    release_phase }o--|| release : "fk"
    release_integration_field }o--|| release : "fk"
    release_initiative }o--|| initiative : "fk"
    release_initiative }o--|| release : "fk"
    release_goal }o--|| goal : "fk"
    release_goal }o--|| release : "fk"
    release_custom_field_score_fact }o--|| release_custom_field : "fk"
    release_custom_field_score_fact }o--|| release_custom_field : "fk"
    release_custom_field }o--|| release : "fk"
    release }o--|| product : "fk"
    release }o--|| users : "fk"
    release }o--|| release : "fk"
    release }o--|| workflow_status : "fk"
    strategic_model_component }o--|| strategic_model : "fk"
    persona }o--|| product : "fk"
    goal_parent }o--|| goal : "fk"
    goal_parent }o--|| goal : "fk"
    goal_attachment }o--|| goal : "fk"
    goal_integration_field }o--|| goal : "fk"
    goal_integration_field }o--|| goal_initiative : "fk"
    goal_initiative }o--|| initiative : "fk"
    goal_initiative }o--|| goal : "fk"
    goal_feature }o--|| feature : "fk"
    goal_feature }o--|| goal : "fk"
    goal_release }o--|| release : "fk"
    goal_release }o--|| goal : "fk"
    goal_custom_field }o--|| goal : "fk"
    goal_workflow_status_time }o--|| goal : "fk"
    goal }o--|| product : "fk"
    goal }o--|| workflow_status : "fk"
    workflow_status }o--|| workflow : "fk"
    workflow_kind }o--|| workflow : "fk"
    workflow }o--|| product : "fk"
    epic_custom_field_score_fact }o--|| epic_custom_field : "fk"
    epic_custom_field_score_fact }o--|| epic_custom_field : "fk"
    epic_custom_field }o--|| epic : "fk"
    epic_workflow_status_time }o--|| epic : "fk"
    epic }o--|| product : "fk"
    epic }o--|| users : "fk"
    epic }o--|| workflow_status : "fk"
    epic }o--|| release : "fk"
    epic }o--|| users : "fk"
    record_link }o--|| record_link : "fk"
    record_link }o--|| record_link : "fk"
    record_link }o--|| feature : "fk"
    user_product_role }o--|| product : "fk"
    user_product_role }o--|| users : "fk"
    user_role }o--|| users : "fk"
    task_assigned_to_user }o--|| users : "fk"
    task_assigned_to_user }o--|| task : "fk"
    task_attachment }o--|| task : "fk"
    task }o--|| product : "fk"
    task }o--|| users : "fk"
    strategic_vision_component }o--|| strategic_vision : "fk"
    idea_custom_field }o--|| idea : "fk"
    idea_workflow_status_time }o--|| idea : "fk"
    idea }o--|| product : "fk"
    idea }o--|| workflow_status : "fk"
    idea }o--|| users : "fk"
    idea_user_organizations }o--|| idea_organization : "fk"
    idea_user_organizations }o--|| idea_user : "fk"
    strategic_component }o--|| strategic_position : "fk"
    idea_subscription }o--|| idea : "fk"
    idea_subscription }o--|| workflow_status : "fk"
    feature_custom_field }o--|| feature : "fk"
    feature }o--|| product : "fk"
    feature }o--|| release : "fk"
    feature }o--|| workflow : "fk"
    release_feature }o--|| feature : "fk"
    release_feature }o--|| product : "fk"
    release_feature }o--|| release : "fk"
    competitor }o--|| product : "fk"
    idea_comment }o--|| idea : "fk"
    idea_comment }o--|| users : "fk"
    idea_comment }o--|| idea_user : "fk"
    idea_comment }o--|| workflow_status : "fk"
    idea_category }o--|| product : "fk"
    idea_organization }o--|| users : "fk"
    creative_brief }o--|| product : "fk"
    product }o--|| product : "fk"
    initiative_custom_field_score_fact }o--|| initiative_custom_field : "fk"
    initiative_custom_field_score_fact }o--|| initiative_custom_field : "fk"
    initiative_custom_field }o--|| initiative : "fk"
    initiative_epic }o--|| epic : "fk"
    initiative_epic }o--|| initiative : "fk"
    attachment }o--|| initiative : "fk"
    master_feature }o--|| initiative : "fk"
    initiative_feature }o--|| product : "fk"
    initiative_feature }o--|| initiative : "fk"
    workflow_status_time }o--|| workflow_status : "fk"
    workflow_status_time }o--|| initiative : "fk"
    initiative_integration_field }o--|| integration : "fk"
    initiative_integration_field }o--|| initiative : "fk"
    initiative }o--|| product : "fk"
    initiative }o--|| users : "fk"
    initiative }o--|| users : "fk"
    initiative }o--|| workflow_status : "fk"
    idea_vote }o--|| idea : "fk"
    idea_vote }o--|| idea_user : "fk"
    idea_vote }o--|| workflow_status : "fk"
    idea_vote }o--|| idea_organization : "fk"
    release_epic }o--|| epic : "fk"
    release_epic }o--|| release : "fk"
    requirement_custom_field }o--|| requirement : "fk"
    requirement_integration_field }o--|| integration : "fk"
    requirement_integration_field }o--|| requirement : "fk"
    requirement }o--|| users : "fk"
    requirement }o--|| release : "fk"
    requirement }o--|| feature : "fk"
    requirement }o--|| users : "fk"
    requirement }o--|| workflow_status : "fk"
