erDiagram
    entity_optins {
        text id PK
        text entity_id PK
        text entity_uuid PK
        text optin_creation_date
        text optin_id
        text optin_status
    }
    entity_post_login {
        text id PK
        text entity_id PK
        text entity_uuid PK
        text privacy_policy_accepted_date
        text privacy_policy_id
        text screen_name
    }
    entity_client {
        text id PK
        text entity_id PK
        text entity_uuid PK
        text client_id
        text first_login
        text last_login
    }
    entity {
        text id PK
        text uuid PK
        text about_me
        text birthday
        text children
        text company
        text consumer_id
        text created
        text current_location
        text deactivate_account
        text display
        text display_name
        text drupal_roles
        text email
        text email_verified
        text family_name
        text gender
        text given_name
        text graduation_year
        text last_login
        text last_updated
        text licensing_state
        text match_type
        text middle_name
        text optin_user
        text originating_brand
        text password_created
        text password_type
        text practice_name
        text primary_address_address_1
        text primary_address_address_2
        text primary_address_address_type
        text primary_address_city
        text primary_address_company
        text primary_address_country
        text primary_address_mobile
        text primary_address_phone
        text primary_address_phone_type
        text primary_address_state_abbreviation
        text primary_address_unit
        text primary_address_zip
        text primary_address_zip_plus_4
        text privacy_policy_id
        text product_1
        text profession
        text professional_status
        text promo_1
        text promo_code
        text promotion_source
        text reason_code
        text sample_ability
        text source_id
        text specialty
        text state_license_number
        text tracking_campaign
        text tracking_medium
        text tracking_source
        text type_name
    }
    entity_optins }o--|| entity : "fk"
    entity_optins }o--|| entity : "fk"
    entity_post_login }o--|| entity : "fk"
    entity_post_login }o--|| entity : "fk"
    entity_client }o--|| entity : "fk"
    entity_client }o--|| entity : "fk"
