erDiagram
    publisher_report {
        text _fivetran_id PK
        text ad_type
        text clicks
        text country
        text ctr
        text day
        text device_type
        text impressions
        text placement_type
        text platform
        text size
    }
    ska_report {
        text _fivetran_id PK
        text ad
        text ad_creative_type
        text ad_id
        text ad_type
        text average_cpa
        text average_cpc
        text campaign
        text campaign_ad_type
        text campaign_bid_goal
        text campaign_id_external
        text campaign_package_name
        text campaign_roas_goal
        text campaign_store_id
        text campaign_type
        text clicks
        text conversion_rate
        text conversions
        text cost
        text country
        text creative_set
        text creative_set_id
        text ctr
        text custom_page_id
        text day
        text device_type
        text external_placement_id
        text first_purchase
        text impressions
        text optimization_day_target
        text placement_type
        text platform
        text sales
        text size
        text target_event
        text traffic_source
    }
    probabilistic_report {
        text _fivetran_id PK
        text ad
        text ad_creative_type
        text ad_id
        text ad_type
        text average_cpa
        text average_cpc
        text campaign
        text campaign_ad_type
        text campaign_bid_goal
        text campaign_id_external
        text campaign_package_name
        text campaign_roas_goal
        text campaign_store_id
        text campaign_type
        text clicks
        text conversion_rate
        text conversions
        text cost
        text country
        text creative_set
        text creative_set_id
        text ctr
        text custom_page_id
        text day
        text device_type
        text external_placement_id
        text first_purchase
        text impressions
        text optimization_day_target
        text placement_type
        text platform
        text sales
        text size
        text target_event
        text traffic_source
    }
    advertiser_report {
        text _fivetran_id PK
        text ad
        text ad_creative_type
        text ad_id
        text ad_type
        text average_cpa
        text average_cpc
        text campaign
        text campaign_ad_type
        text campaign_bid_goal
        text campaign_id_external
        text campaign_package_name
        text campaign_roas_goal
        text campaign_store_id
        text campaign_type
        text clicks
        text conversion_rate
        text conversions
        text cost
        text country
        text creative_set
        text creative_set_id
        text ctr
        text custom_page_id
        text day
        text device_type
        text external_placement_id
        text first_purchase
        text impressions
        text installs
        text optimization_day_target
        text placement_type
        text platform
        text redownloads
        text sales
        text size
        text target_event
        text traffic_source
    }
