erDiagram
    creative_performance_resource {
        text date PK
        text id PK
        text affiliate_usage
        text click_through_rate
        text clicks
        text commission
        text earnings_per_click
        text end_date
        text impressions
        text items
        text name
        text sales
        text start_date
        text transactions
        text type
    }
    transaction_details_resource {
        text id PK
        text click_date
        text click_id
        text commission
        text commission_publisher
        text commission_site
        text company
        text coupons
        text creative_id
        text device_type
        text end_date
        text link_type
        text new_to_file
        text order_id
        text publisher
        text publisher_id
        text publisher_referral_url
        text publisher_type
        text referrer_url
        text sale_amount
        text sale_date
        text start_date
        text status
        text type
    }
    transaction_history_resource {
        text _fivetran_id PK
        text commission
        text company
        text end_date
        text item_id
        text link_type
        text order_id
        text process_date
        text publisher
        text publisher_commission
        text publisher_id
        text publisher_type
        text revision
        text sale_amount
        text sale_date
        text site_commission
        text start_date
        text status
        text transaction_id
        text transaction_type
        text website_url
    }
