erDiagram
    query_statistics {
        text _fivetran_id PK
        text avg_click_position
        text avg_impression_position
        text clicks
        text date
        text impressions
        text query
        text type
        text url
    }
    keyword_statistics {
        text _fivetran_id PK
        text broad_impressions
        text date
        text impressions
        text query
        text type
    }
    page_statistics {
        text _fivetran_id PK
        text avg_click_position
        text avg_impression_position
        text clicks
        text date
        text impressions
        text query
        text type
        text url
    }
