erDiagram
    company_property {
        text id PK
        timestamp created_at
        text description
        text integration
        text kind
        timestamp last_seen_at
        text name
        text prop
        jsonb types
        timestamp updated_at
        jsonb values
    }
    domain {
        text id PK
        text url_group_id_ FK
        timestamp archived_at
        timestamp created_at
        text domain
        text enabled
        timestamp first_seen_at
        text host
        timestamp installed_at
        timestamp last_seen_at
        timestamp updated_at
        text url_group_id
    }
    environment {
        text id PK
        timestamp archived_at
        timestamp created_at
        text description
        text name
        text short_name
        text style_short_name_color
        timestamp updated_at
    }
    micro_survey_response {
        text id PK
        text profile_company_id FK
        text profile_id FK
        text survey_id FK
        text button_id
        text button_order
        text button_text
        text comment_step_button_selected
        text comment_step_button_selected_2
        text comment_step_dropdown_item
        text comment_step_dropdown_item_2
        text comment_step_input_text
        text comment_step_input_text_2
        text comment_step_other_text
        text comment_step_other_text_2
        timestamp created_at
        text dropdown_items
        timestamp finished_at
        text href
        text input_text
        text input_text_2
        text other_text
        text profile_company_uid
        text profile_uid
        timestamp updated_at
    }
    tour_interaction {
        text id PK
        text profile_company_id FK
        text profile_id FK
        text tour_id FK
        timestamp created_at
        text defer_count
        text defer_until
        timestamp goal_at
        text group_id
        text group_kind
        text profile_company_uid
        text profile_uid
        text state
        timestamp updated_at
    }
    rate_limit_group_campaign {
        text campaign_id PK
        text rate_limit_group_id PK
    }
    rate_limit_group_tag {
        text rate_limit_group_id PK
        text tag_id PK
    }
    rate_limit_group {
        text id PK
        timestamp created_at
        text kind
        text name
        text rate_limit_kind
        text rate_limit_size
        timestamp updated_at
    }
    webhook {
        text _fivetran_id PK
        text id
        timestamp last_item_at
        text last_item_error
        text last_item_state
        text name
        text uid
    }
    profile_property {
        text id PK
        timestamp created_at
        text description
        text integration
        text kind
        timestamp last_seen_at
        text name
        text prop
        jsonb types
        timestamp updated_at
        jsonb values
    }
    experience_delivery {
        text id PK
        text interaction_id FK
        text profile_id FK
        timestamp at
        text at_href
        timestamp created_at
        text delivery_ids_at_limit
        text delivery_ids_limit
        text delivery_ids_position
        timestamp from_date
        text group_kind
        text idempotency_key
        text model_id
        text model_kind
        boolean once
        text options
        boolean skip_triggers
        boolean skip_url_match
        timestamp until
        timestamp updated_at
        boolean use_segmentation
    }
    segment_item {
        text id PK
        text segment_id FK
        timestamp created_at
        text kind
        text mod
        text op
        text prop
        text range
        timestamp updated_at
        text value
    }
    segment {
        text id PK
        timestamp created_at
        text name
        timestamp updated_at
    }
    launcher_item {
        text id PK
        text segment_id FK
        text campaign_id
        timestamp created_at
        text description
        boolean hide
        text kind
        text script
        text title
        timestamp updated_at
        text url
    }
    launcher_tag {
        text launcher_id PK
        text tag_id PK
    }
    launcher {
        text id PK
        text segment_id FK
        text blocked_domains
        timestamp created_at
        text description
        text empty_state_content
        text icon_size
        text list_type
        text name
        text position_type
        text preset
        timestamp published_at
        text quantifier_url
        jsonb quantifier_urls
        text screen_position
        text search_placeholder
        text stats_completed_count
        text stats_exited_count
        timestamp stats_last_completed_at
        timestamp stats_last_exited_at
        timestamp stats_last_started_at
        text stats_started_count
        text title
        text trigger
        text trigger_text
        text trigger_type
        timestamp updated_at
    }
    zapier_hook {
        text _fivetran_id PK
        text id
        timestamp last_item_at
        text last_item_error
        text last_item_state
        text name
        text uid
    }
    user_profile {
        text id PK
        text company_id FK
        text browser_k
        text browser_l
        text browser_n
        text browser_tz
        text browser_x
        jsonb company
        timestamp created_at
        jsonb delivery_ids
        text email
        text first_name
        text invited_users_count
        timestamp last_import_at
        timestamp last_seen_at
        text last_seen_session_count
        text percents
        text role
        text uid
        timestamp updated_at
    }
    user_profile_segment {
        text id PK
        text user_profile_temp_segment_id
    }
    company {
        text id PK
        text clv
        timestamp created_at
        text domain
        timestamp last_action_at
        text name
        text plan
        text uid
        timestamp updated_at
    }
    data_import_property {
        text _fivetran_id PK
        text data_import_id FK
        text name
        text prop
    }
    data_import_head_column {
        text _fivetran_id PK
        text data_import_id FK
        text name
        jsonb values
    }
    data_import {
        text id PK
        timestamp created_at
        timestamp import_at
        text kind
        text model_kind
        text name
        text on_model_missing
        timestamp stats_last_import_at
        text stats_last_import_state
        bigint stats_last_row
        bigint stats_rows_count
        text tag_import_id
        timestamp updated_at
    }
    tooltip_tag {
        text tag_id PK
        text tooltip_id PK
    }
    tooltip {
        text id PK
        timestamp created_at
        text name
        text position
        timestamp published_at
        timestamp updated_at
    }
    alert_group_campaign {
        text campaign_id PK
        text alert_group_id PK
    }
    alert_group_experience {
        text id PK
        text alert_group_id FK
        text name
    }
    alert_group_tag {
        text alert_group_id PK
        text tag_id PK
    }
    alert_group {
        text id PK
        timestamp created_at
        jsonb emails
        text interval
        text kind
        timestamp last_notified_at
        text name
        timestamp opt_in_email_at
        timestamp opt_in_slack_at
        timestamp published_at
        text slack_uid
        text style
        timestamp updated_at
    }
    micro_survey_tag {
        text micro_survey_id PK
        text tag_id PK
    }
    micro_survey {
        text id PK
        text segment_id FK
        timestamp created_at
        text last_dropdown_items
        text name
        text position
        timestamp published_at
        text rate_unlimit_at
        text stats_completed_count
        text stats_exited_count
        timestamp stats_last_completed_at
        timestamp stats_last_exited_at
        timestamp stats_last_started_at
        text stats_started_count
        timestamp updated_at
    }
    tags {
        text id PK
        timestamp created_at
        text description
        timestamp disabled_at
        timestamp last_seen_at
        text models_count
        text name
        text uid
        timestamp updated_at
    }
    tour_tag {
        text tag_id PK
        text tour_id PK
    }
    tour {
        text id PK
        text segment_id FK
        timestamp archived_at
        timestamp created_at
        timestamp experiment_at
        text experiment_range
        text name
        text position
        timestamp published_at
        timestamp rate_unlimit_at
        text stats_completed_count
        text stats_exited_count
        timestamp stats_last_completed_at
        timestamp stats_last_exited_at
        timestamp stats_last_started_at
        text stats_started_count
        text style
        text tour_link_url
        timestamp updated_at
    }
    domain }o--|| environment : "fk"
    micro_survey_response }o--|| user_profile : "fk"
    micro_survey_response }o--|| micro_survey : "fk"
    micro_survey_response }o--|| company : "fk"
    tour_interaction }o--|| user_profile : "fk"
    tour_interaction }o--|| tour : "fk"
    tour_interaction }o--|| company : "fk"
    rate_limit_group_campaign }o--|| rate_limit_group : "fk"
    rate_limit_group_tag }o--|| tags : "fk"
    rate_limit_group_tag }o--|| rate_limit_group : "fk"
    experience_delivery }o--|| user_profile : "fk"
    experience_delivery }o--|| tour_interaction : "fk"
    segment_item }o--|| segment : "fk"
    launcher_item }o--|| segment : "fk"
    launcher_tag }o--|| tags : "fk"
    launcher_tag }o--|| launcher : "fk"
    launcher }o--|| segment : "fk"
    user_profile }o--|| company : "fk"
    data_import_property }o--|| data_import : "fk"
    data_import_head_column }o--|| data_import : "fk"
    tooltip_tag }o--|| tags : "fk"
    tooltip_tag }o--|| tooltip : "fk"
    alert_group_campaign }o--|| alert_group : "fk"
    alert_group_experience }o--|| alert_group : "fk"
    alert_group_tag }o--|| tags : "fk"
    alert_group_tag }o--|| alert_group : "fk"
    micro_survey_tag }o--|| tags : "fk"
    micro_survey_tag }o--|| micro_survey : "fk"
    micro_survey }o--|| segment : "fk"
    tour_tag }o--|| tags : "fk"
    tour_tag }o--|| tour : "fk"
    tour }o--|| segment : "fk"
