erDiagram
    contact_email {
        text email PK
        text contact_id PK
        text type
    }
    contact_phone {
        text phone PK
        text contact_id PK
        text country
        text phone_formatted
        text type
    }
    contact {
        text id PK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text date_created
        text date_updated
        text display_name
        jsonb integration_links
        text name
        text organization_id
        text title
    }
    group_member {
        text group_id PK
        text user_id PK
    }
    groups {
        text id PK
        text name
        text organization_id
    }
    lead_status {
        text id PK
        text label
        text organization_id
    }
    opportunity_status_change_activity {
        text id PK
        text created_by FK
        text new_status_id FK
        text old_status_id FK
        text opportunity_id FK
        text updated_by FK
        text user_id FK
        text contact_id
        text date_created
        text date_updated
        text lead_id
        text organization_id
        text type
    }
    send_as {
        text id PK
        text allowed_user_id FK
        text allowing_user_id FK
        text organization_id
    }
    lead_custom_field {
        text id PK
        text created_by FK
        text updated_by FK
        text accepts_multiple_values
        text back_reference_is_visible
        jsonb choices
        text date_created
        text date_updated
        text description
        jsonb editable_with_roles
        text is_shared
        text name
        text organization_id
        text referenced_custom_type_id
        text type
    }
    bulk_email {
        text id PK
        text created_by FK
        text template_id FK
        text updated_by FK
        text contact_preference
        text date_created
        text date_updated
        text n_leads
        text n_leads_processed
        text organization_id
        text query
        text send_done_email
        text status
    }
    bulk_edit {
        text id PK
        text created_by FK
        text lead_status_id FK
        text updated_by FK
        text date_created
        text date_updated
        text n_leads
        text n_leads_processed
        text organization_id
        text query
        text send_done_email
        text status
        text type
    }
    email_thread_participant {
        text email PK
        text email_thread_activity_id PK
        text name
    }
    email_thread_activity {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text user_id FK
        text activity_at
        text date_created
        text date_updated
        text latest_normalized_subject
        text n_emails
        text organization_id
        text type
        jsonb users
    }
    lead_status_change_activity {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text new_status_id FK
        text old_status_id FK
        text updated_by FK
        text user_id FK
        text activity_at
        text date_created
        text date_updated
        text organization_id
        jsonb users
    }
    activity_custom_field {
        text id PK
        text created_by FK
        text updated_by FK
        text accepts_multiple_values
        jsonb choices
        text custom_activity_type_id
        text date_created
        text date_updated
        text description
        jsonb editable_with_roles
        text name
        text organization_id
        text referenced_custom_type_id
        text type
    }
    task_email {
        text email PK
        text task_id PK
    }
    task {
        text id PK
        text assigned_to FK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text date
        text date_created
        text date_updated
        text is_complete
        text object_id
        text object_type
        text opportunity_note
        text opportunity_value
        text opportunity_value_formatted
        text opportunity_value_period
        text organization_id
        text type
        text view
    }
    bulk_sequence_subscription {
        text id PK
        text created_by FK
        text sequence_id FK
        text updated_by FK
        text action_type
        text contact_preference
        text date_created
        text date_updated
        text n_leads
        text n_leads_processed
        text organization_id
        text query
        text send_done_email
        text sender_account_id
        text sender_email
        text sender_name
        text status
    }
    dialer_user {
        text dialer_id PK
        text user_id PK
        text is_active
        text state
    }
    dialer {
        text id PK
        text caller_id
        text date_created
        text date_updated
        text is_user_dependent
        text music_preference
        text organization_id
        text ring_mode
        text source_type
        text source_value
        text status
        text type
    }
    phone_number {
        text id PK
        text user_id FK
        text date_created
        text date_updated
        text forward_to
        text forward_to_enabled
        text forward_to_formatted
        text is_group_number
        text label
        text number
        text number_formatted
        text organization_id
        jsonb participants
        jsonb phone_numbers
        jsonb phone_numbers_formatted
        text sms_enabled
        jsonb supports_sms_to_countries
        text type
        text voicemail_greeting_url
    }
    users {
        text id PK
        text date_created
        text date_updated
        text email
        text email_verification_token_generated_at
        text email_verified_at
        text first_name
        text image
        text last_name
        text last_used_timezone
        jsonb organizations
    }
    call_activity {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text sequence_id FK
        text sequence_subscription_id FK
        text transferred_from_user_id FK
        text transferred_to_user_id FK
        text updated_by FK
        text user_id FK
        text activity_at
        text call_method
        jsonb coach_legs
        double_precision cost
        text date_answered
        text date_created
        text date_updated
        text dialer_id
        text dialer_saved_search_id
        text direction
        text disposition
        text duration
        text forwarded_to
        text has_recording
        text is_forwarded
        text is_joinable
        text is_to_group_number
        text local_country_iso
        text local_phone
        text local_phone_formatted
        text note
        text organization_id
        text phone
        text recording_expires_at
        text recording_url
        text remote_country_iso
        text remote_phone
        text remote_phone_formatted
        text source
        text status
        text type
        jsonb users
        text voicemail_duration
        text voicemail_url
    }
    integration_link {
        text id PK
        text created_by FK
        text updated_by FK
        text date_created
        text date_updated
        text name
        text organization_id
        text type
        text url
    }
    email_template {
        text id PK
        text created_by FK
        text updated_by FK
        jsonb attachments
        text body
        text date_created
        text date_updated
        text is_archived
        text is_shared
        text name
        text organization_id
        text subject
    }
    custom_activity_field {
        text id PK
        text custom_activity_id FK
        text accepts_multiple_values
        text back_reference_is_visible
        text converting_to_type
        text description
        jsonb editable_with_roles
        text is_shared
        text name
        text referenced_custom_type_id
        text required
        text type
    }
    custom_activity {
        text id PK
        text created_by FK
        text updated_by FK
        text api_create_only
        text date_created
        text date_updated
        text description
        jsonb editable_with_roles
        text name
        text organization_id
    }
    connected_account_identity {
        text email PK
        text connected_account_id PK
        text name
    }
    connected_account {
        text id PK
        text user_id PK
        text imap
        text organization_id
        text smtp_host
        text smtp_port
        text smtp_use_ssl
        text smtp_username
        jsonb synced_calendars
        text type
    }
    role {
        text id PK
        text date_created
        text date_updated
        text editable
        text name
        text organization_id
        jsonb permission
    }
    email_activity_attachment {
        text _fivetran_id PK
        text email_activity_id FK
        text content_type
        text filename
        text size
        text url
    }
    email_activity_to {
        text receiver PK
        text email_activity_id PK
    }
    email_body_text {
        text _fivetran_id PK
        text email_activity_id FK
        text expand
        text text
    }
    email_envelope_sender {
        text email PK
        text email_activity_id PK
        text name
    }
    email_envelope_to {
        text email PK
        text email_activity_id PK
        text name
    }
    email_envelope_from {
        text email PK
        text email_activity_id PK
        text name
    }
    email_activity {
        text id PK
        text contact_id FK
        text created_by FK
        text followup_sequence_id FK
        text lead_id FK
        text sequence_id FK
        text sequence_subscription_id FK
        text template_id FK
        text thread_id FK
        text updated_by FK
        text user_id FK
        text activity_at
        jsonb attachments
        jsonb bcc
        text bulk_email_action_id
        jsonb cc
        text date_created
        text date_scheduled
        text date_sent
        text date_updated
        text direction
        text email_account_id
        jsonb envelope_bcc
        jsonb envelope_cc
        text envelope_date
        text envelope_in_reply_to
        text envelope_is_autoreply
        text envelope_message_id
        text envelope_subject
        text followup_sequence_delay
        text has_reply
        text in_reply_to_id
        jsonb message_ids
        text need_smtp_credentials
        jsonb opens
        text opens_summary
        text organization_id
        jsonb reference
        text send_as_id
        jsonb send_attempts
        text sender
        text status
        text subject
        text type
        jsonb users
    }
    note_activity {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text user_id FK
        text activity_at
        jsonb attachment
        text date_created
        text date_updated
        text note
        jsonb note_mention
        text organization_id
        text type
        text user_name
        jsonb users
    }
    sequence_step {
        text id PK
        text created_by_id FK
        text email_template_id FK
        text sequence_id FK
        text updated_by_id FK
        text date_created
        text date_updated
        text delay
        text required
        text step_allowed_delay
        text step_type
        text threading
    }
    sequence {
        text id PK
        text created_by_id FK
        text updated_by_id FK
        text date_created
        text date_updated
        text name
        text organization_id
        text schedule_id
        text status
        text timezone
    }
    opportunity_custom_field {
        text id PK
        text created_by FK
        text updated_by FK
        text accepts_multiple_values
        jsonb choices
        text date_created
        text date_updated
        text description
        jsonb editable_with_roles
        text name
        text organization_id
        text type
    }
    pipline_status {
        text id PK
        text pipeline_id FK
        text label
        text type
    }
    pipeline {
        text id PK
        text created_by FK
        text updated_by FK
        text date_created
        text date_updated
        text name
        text organization_id
    }
    custom_activity_instance {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text user_id FK
        text activity_at
        text custom_activity_type_id
        text date_created
        text date_updated
        text organization_id
        text status
        text type
        text user_name
        jsonb users
    }
    sms_attachment {
        text index PK
        text sms_activity_id PK
        text content_type
        text filename
        text media_id
        text size
        text url
    }
    sms_activity {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text user_id FK
        text cost
        text date_created
        text date_sent
        text date_updated
        text direction
        text local_country_iso
        text local_phone
        text organization_id
        text remote_country_iso
        text remote_phone
        text remote_phone_formatted
        text status
        text text
        text type
    }
    meeting_attendee {
        text index PK
        text meeting_activity_id PK
        text contact_id FK
        text user_id FK
        text is_organizer
        text status
    }
    meeting_activity {
        text id PK
        text connected_account_id FK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text user_id FK
        text calendar_event_link
        text date_created
        text date_updated
        text duration
        text ends_at
        text is_recurring
        text location
        text note
        text organization_id
        text source
        text starts_at
        text status
        text title
        jsonb users
    }
    opportunity_status {
        text id PK
        text pipeline_id FK
        text label
        text organization_id
        text type
    }
    contact_custom_field {
        text id PK
        text created_by FK
        text updated_by FK
        text accepts_multiple_values
        jsonb choices
        text date_created
        text date_updated
        text description
        jsonb editable_with_roles
        text name
        text organization_id
        text type
    }
    task_completed_activity {
        text id PK
        text created_by FK
        text lead_id FK
        text task_id FK
        text updated_by FK
        text user_id FK
        text date_created
        text date_updated
        text organization_id
        text task_text
        text type
    }
    created_activity {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text updated_by FK
        text user_id FK
        text activity_at
        text date_created
        text date_updated
        text import_id
        text organization_id
        text source
        jsonb users
    }
    bulk_delete {
        text id PK
        text created_by FK
        text updated_by FK
        text date_created
        text date_updated
        text n_leads
        text n_leads_processed
        text organization_id
        text query
        text send_done_email
        text status
    }
    shared_association {
        text object_type PK
        text shared_custom_field_id FK
        text custom_activity_type_id
        jsonb editable_with_roles
        text required
    }
    shared_custom_field {
        text id PK
        text created_by FK
        text updated_by FK
        text accepts_multiple_values
        jsonb choices
        text date_created
        text date_updated
        text description
        jsonb editable_with_roles
        text name
        text organization_id
        text type
    }
    opportunity {
        text id PK
        text contact_id FK
        text created_by FK
        text lead_id FK
        text status_id FK
        text updated_by FK
        text user_id FK
        text annualized_expected_value
        text annualized_value
        text confidence
        text date_created
        text date_lost
        timestamp date_updated
        text date_won
        text expected_value
        jsonb integration_links
        text note
        text organization_id
        text status_display_name
        text value
        text value_currency
        text value_formatted
        text value_period
    }
    lead_address {
        text _fivetran_id PK
        text lead_id FK
        text address_1
        text address_2
        text city
        text country
        text label
        text state
        text zipcode
    }
    lead {
        text id PK
        text created_by FK
        text first_communication_user_id FK
        text last_activity_user_id FK
        text last_communication_user_id FK
        text next_task_user_id FK
        text primary_opportunity_pipeline_id FK
        text primary_opportunity_status FK
        text primary_opportunity_user_id FK
        text status_id FK
        text updated_by FK
        text active_opportunity_value_summary
        text contacts_summary
        text date_created
        text date_updated
        text description
        text display_name
        text first_call_created
        text first_call_note
        text first_communication_date
        text first_communication_summary
        text first_communication_type
        text first_source
        text html_url
        jsonb integration_links
        text last_activity_date
        text last_activity_type
        text last_call_created
        text last_call_duration
        text last_call_note
        text last_communication_date
        text last_communication_summary
        text last_communication_type
        text last_email_date
        text last_email_subject
        text last_incoming_email_date
        text last_lead_status_change_date
        text last_note_created
        text last_outgoing_call_date
        text local_time
        text name
        text next_task_date
        text next_task_due_date
        text next_task_text
        text organization_id
        text primary_address_summary
        text primary_email
        text primary_email_type
        text primary_phone
        text primary_phone_country
        text primary_phone_formatted
        text primary_phone_type
        text times_communicated
        text url
        text won_opportunity_value_summary
    }
    contact_email }o--|| contact : "fk"
    contact_phone }o--|| contact : "fk"
    contact }o--|| lead : "fk"
    contact }o--|| users : "fk"
    contact }o--|| users : "fk"
    group_member }o--|| users : "fk"
    group_member }o--|| groups : "fk"
    opportunity_status_change_activity }o--|| opportunity : "fk"
    opportunity_status_change_activity }o--|| users : "fk"
    opportunity_status_change_activity }o--|| opportunity_status : "fk"
    opportunity_status_change_activity }o--|| users : "fk"
    opportunity_status_change_activity }o--|| users : "fk"
    opportunity_status_change_activity }o--|| opportunity_status : "fk"
    send_as }o--|| users : "fk"
    send_as }o--|| users : "fk"
    lead_custom_field }o--|| users : "fk"
    lead_custom_field }o--|| users : "fk"
    bulk_email }o--|| email_template : "fk"
    bulk_email }o--|| users : "fk"
    bulk_email }o--|| users : "fk"
    bulk_edit }o--|| lead_status : "fk"
    bulk_edit }o--|| users : "fk"
    bulk_edit }o--|| users : "fk"
    email_thread_participant }o--|| email_thread_activity : "fk"
    email_thread_activity }o--|| users : "fk"
    email_thread_activity }o--|| lead : "fk"
    email_thread_activity }o--|| users : "fk"
    email_thread_activity }o--|| users : "fk"
    email_thread_activity }o--|| contact : "fk"
    lead_status_change_activity }o--|| users : "fk"
    lead_status_change_activity }o--|| lead_status : "fk"
    lead_status_change_activity }o--|| lead : "fk"
    lead_status_change_activity }o--|| users : "fk"
    lead_status_change_activity }o--|| users : "fk"
    lead_status_change_activity }o--|| lead_status : "fk"
    lead_status_change_activity }o--|| contact : "fk"
    activity_custom_field }o--|| users : "fk"
    activity_custom_field }o--|| users : "fk"
    task_email }o--|| task : "fk"
    task }o--|| users : "fk"
    task }o--|| lead : "fk"
    task }o--|| users : "fk"
    task }o--|| users : "fk"
    task }o--|| contact : "fk"
    bulk_sequence_subscription }o--|| sequence : "fk"
    bulk_sequence_subscription }o--|| users : "fk"
    bulk_sequence_subscription }o--|| users : "fk"
    dialer_user }o--|| users : "fk"
    dialer_user }o--|| dialer : "fk"
    phone_number }o--|| users : "fk"
    call_activity }o--|| users : "fk"
    call_activity }o--|| sequence : "fk"
    call_activity }o--|| lead : "fk"
    call_activity }o--|| users : "fk"
    call_activity }o--|| bulk_sequence_subscription : "fk"
    call_activity }o--|| users : "fk"
    call_activity }o--|| users : "fk"
    call_activity }o--|| users : "fk"
    call_activity }o--|| contact : "fk"
    integration_link }o--|| users : "fk"
    integration_link }o--|| users : "fk"
    email_template }o--|| users : "fk"
    email_template }o--|| users : "fk"
    custom_activity_field }o--|| custom_activity : "fk"
    custom_activity }o--|| users : "fk"
    custom_activity }o--|| users : "fk"
    connected_account_identity }o--|| connected_account : "fk"
    connected_account }o--|| users : "fk"
    email_activity_attachment }o--|| email_activity : "fk"
    email_activity_to }o--|| email_activity : "fk"
    email_body_text }o--|| email_activity : "fk"
    email_envelope_sender }o--|| email_activity : "fk"
    email_envelope_to }o--|| email_activity : "fk"
    email_envelope_from }o--|| email_activity : "fk"
    email_activity }o--|| email_template : "fk"
    email_activity }o--|| users : "fk"
    email_activity }o--|| sequence : "fk"
    email_activity }o--|| lead : "fk"
    email_activity }o--|| users : "fk"
    email_activity }o--|| email_thread_activity : "fk"
    email_activity }o--|| bulk_sequence_subscription : "fk"
    email_activity }o--|| sequence : "fk"
    email_activity }o--|| users : "fk"
    email_activity }o--|| contact : "fk"
    note_activity }o--|| users : "fk"
    note_activity }o--|| lead : "fk"
    note_activity }o--|| users : "fk"
    note_activity }o--|| users : "fk"
    note_activity }o--|| contact : "fk"
    sequence_step }o--|| users : "fk"
    sequence_step }o--|| users : "fk"
    sequence_step }o--|| email_template : "fk"
    sequence_step }o--|| sequence : "fk"
    sequence }o--|| users : "fk"
    sequence }o--|| users : "fk"
    opportunity_custom_field }o--|| users : "fk"
    opportunity_custom_field }o--|| users : "fk"
    pipline_status }o--|| opportunity_status : "fk"
    pipline_status }o--|| pipeline : "fk"
    pipeline }o--|| users : "fk"
    pipeline }o--|| users : "fk"
    custom_activity_instance }o--|| users : "fk"
    custom_activity_instance }o--|| lead : "fk"
    custom_activity_instance }o--|| users : "fk"
    custom_activity_instance }o--|| users : "fk"
    custom_activity_instance }o--|| contact : "fk"
    sms_attachment }o--|| sms_activity : "fk"
    sms_activity }o--|| users : "fk"
    sms_activity }o--|| lead : "fk"
    sms_activity }o--|| users : "fk"
    sms_activity }o--|| users : "fk"
    sms_activity }o--|| contact : "fk"
    meeting_attendee }o--|| users : "fk"
    meeting_attendee }o--|| contact : "fk"
    meeting_attendee }o--|| meeting_activity : "fk"
    meeting_activity }o--|| users : "fk"
    meeting_activity }o--|| lead : "fk"
    meeting_activity }o--|| users : "fk"
    meeting_activity }o--|| connected_account : "fk"
    meeting_activity }o--|| users : "fk"
    meeting_activity }o--|| contact : "fk"
    opportunity_status }o--|| pipeline : "fk"
    contact_custom_field }o--|| users : "fk"
    contact_custom_field }o--|| users : "fk"
    task_completed_activity }o--|| users : "fk"
    task_completed_activity }o--|| task : "fk"
    task_completed_activity }o--|| lead : "fk"
    task_completed_activity }o--|| users : "fk"
    task_completed_activity }o--|| users : "fk"
    created_activity }o--|| users : "fk"
    created_activity }o--|| lead : "fk"
    created_activity }o--|| users : "fk"
    created_activity }o--|| users : "fk"
    created_activity }o--|| contact : "fk"
    bulk_delete }o--|| users : "fk"
    bulk_delete }o--|| users : "fk"
    shared_association }o--|| shared_custom_field : "fk"
    shared_custom_field }o--|| users : "fk"
    shared_custom_field }o--|| users : "fk"
    opportunity }o--|| users : "fk"
    opportunity }o--|| lead : "fk"
    opportunity }o--|| users : "fk"
    opportunity }o--|| opportunity_status : "fk"
    opportunity }o--|| users : "fk"
    opportunity }o--|| contact : "fk"
    lead_address }o--|| lead : "fk"
    lead }o--|| users : "fk"
    lead }o--|| users : "fk"
    lead }o--|| users : "fk"
    lead }o--|| pipeline : "fk"
    lead }o--|| users : "fk"
    lead }o--|| users : "fk"
    lead }o--|| lead_status : "fk"
    lead }o--|| opportunity_status : "fk"
    lead }o--|| users : "fk"
    lead }o--|| users : "fk"
