erDiagram
    cpu_time {
        text date PK
        text zone_id PK
        text total_cpu_time
    }
    request_group {
        text client_country_name PK
        text date PK
        text zone_id PK
        text byte
        text request
    }
    cache_reserve {
        text bucket_hash PK
        text date_time_fifteen_minute PK
        text zone_id PK
        text bucket_prefix
        text max_stored_byte
    }
    bytes_by_hostname {
        text client_country_name PK
        text client_request_http_host PK
        text client_request_path PK
        text date_time_hour PK
        text zone_id PK
        text edge_response_byte_sum
    }
    zone_name_server {
        text index PK
        text zone_id PK
        text name_server
    }
    zone_original_name_server {
        text index PK
        text zone_id PK
        text original_name_server
    }
    zone_vanity_name_server {
        text index PK
        text zone_id PK
        text vanity_name_server
    }
    zone {
        text id PK
        text account_id
        text account_name
        text activated_on
        text created_on
        text development_mode
        text meta_cdn_only
        text meta_custom_certificate_quota
        text meta_dns_only
        text meta_foundation_dns
        text meta_page_rule_quota
        text meta_phishing_detected
        text meta_step
        text modified_on
        text name
        text original_dnshost
        text original_registrar
        text owner_id
        text owner_name
        text owner_type
        text paused
        text plan_can_subscribe
        text plan_currency
        text plan_externally_managed
        text plan_frequency
        text plan_id
        text plan_is_subscribed
        text plan_legacy_discount
        text plan_legacy_id
        text plan_name
        text plan_price
        text status
        text tenant_id
        text tenant_name
        text tenant_unit_id
        text type
        jsonb vanity_name_servers_ips
    }
    image_resize_request {
        text content_type PK
        text date PK
        text zone_id PK
        text sum_original_byte
        text sum_request
        text sum_resized_byte
    }
    cpu_time }o--|| zone : "fk"
    zone_name_server }o--|| zone : "fk"
    zone_original_name_server }o--|| zone : "fk"
    zone_vanity_name_server }o--|| zone : "fk"
    image_resize_request }o--|| zone : "fk"
