erDiagram
    custom_field {
        text id PK
        text created_at
        text label
        text name
        text type
        text updated_at
    }
    email_campaign_summary_report {
        text campaign_type PK
        text last_sent_date PK
        text campaign_id PK
        text unique_counts_abuse
        text unique_counts_bounces
        text unique_counts_clicks
        text unique_counts_forwards
        text unique_counts_not_opened
        text unique_counts_opens
        text unique_counts_optouts
        text unique_counts_sends
    }
    segment {
        text id PK
        text created_at
        text criteria
        text edited_at
        text name
    }
    contact_tag {
        text id PK
        text contacts_count
        text created_at
        text name
        text tag_source
        text updated_at
    }
    contact_list {
        text id PK
        text created_at
        text deleted_at
        text description
        text favorite
        text membership_count
        text name
        text updated_at
    }
    contact_custom {
        text contact_id PK
        text custom_field_id PK
        text value
    }
    contact_phone_number {
        text id PK
        text contact_id PK
        text create_source
        text created_at
        text kind
        text phone_number
        text update_source
        text updated_at
    }
    contact_street_address {
        text id PK
        text contact_id PK
        text city
        text country
        text created_at
        text kind
        text postal_code
        text state
        text street
        text updated_at
    }
    contact_membership {
        text contact_id PK
        text list_id PK
    }
    contact_tagging {
        text contact_id PK
        text tag_id PK
    }
    contact_note {
        text id PK
        text contact_id PK
        text content
        text created_at
    }
    contact_sms_channel_consent {
        text index PK
        text contact_id PK
        text advertised_frequency
        text advertised_interval
        text consent_type
        text created_at
        text opt_in_date
        text opt_out_date
        text sms_consent_permission
        text updated_at
    }
    contact {
        text id PK
        text anniversary
        text birthday_day
        text birthday_month
        text company_name
        text create_source
        text created_at
        text deleted_at
        text email_address
        text email_confirm_status
        text email_created_at
        text email_opt_in_date
        text email_opt_in_source
        text email_opt_out_date
        text email_opt_out_reason
        text email_opt_out_source
        text email_permission_to_send
        text email_updated_at
        text first_name
        text job_title
        text last_name
        text sms_channel_address
        text sms_channel_country_code
        text sms_channel_create_source
        text sms_channel_dial_code
        text sms_channel_id
        text sms_channel_update_source
        text update_source
        text updated_at
    }
    contact_sms_engagement_history {
        text insert_time PK
        text sms_channel_history_id PK
        text sms_channel_id PK
        text contact_id PK
        text history_details_advertised_frequency
        text history_details_advertised_interval
        text history_details_consent_action_time
        text history_details_consent_action_type
        text history_details_consent_medium_type
        text history_details_consent_type
        text history_details_source
        text history_details_source_consent_timestamp
        text history_details_source_ip
        text history_details_source_sms_number
        text history_details_state
    }
    email_campaign_stat_report {
        text last_refresh_time PK
        text campaign_id PK
        text percents_bounce
        text percents_click
        text percents_desktop_click
        text percents_desktop_open
        text percents_did_not_open
        text percents_mobile_click
        text percents_mobile_open
        text percents_open
        text percents_unsubscribe
        text stats_em_bounces
        text stats_em_clicks
        text stats_em_clicks_all
        text stats_em_clicks_all_computer
        text stats_em_clicks_all_mobile
        text stats_em_clicks_all_none
        text stats_em_clicks_all_other
        text stats_em_clicks_all_tablet
        text stats_em_forwards
        text stats_em_not_opened
        text stats_em_opens
        text stats_em_opens_all
        text stats_em_opens_all_computer
        text stats_em_opens_all_mobile
        text stats_em_opens_all_none
        text stats_em_opens_all_other
        text stats_em_opens_all_tablet
        text stats_em_optouts
        text stats_em_sends
    }
    email_campaign {
        text id PK
        text created_at
        text current_status
        text name
        text type
        text type_code
        text updated_at
    }
    email_bounce_report {
        text campaign_activity_id PK
        text contact_id PK
        text bounce_code
        text created_time
        text current_email_address
        text deleted_at
        text tracking_activity_type
    }
    campaign_activity_segment {
        text campaign_activity_id PK
        text segment_id PK
    }
    campaign_activity_contact_list {
        text campaign_activity_id PK
        text contact_list_id PK
    }
    campaign_activity {
        text id PK
        text campaign_id FK
        text address_line_1
        text address_line_2
        text address_line_3
        text address_optional
        text city
        text country_code
        text country_name
        text current_status
        text format_type
        text forward_email_link_enabled
        text forward_email_link_name
        text from_email
        text from_name
        text greeting_name_type
        text greeting_salutation
        text greeting_secondary
        text html_content
        text letter_format
        text organization_name
        text permalink_url
        text permission_reminder
        text permission_reminder_enabled
        text postal_code
        text preheader
        text reply_to_email
        text role
        text state_code
        text state_name
        text state_non_us_name
        text style_content
        text subject
        text subscribe_link_enabled
        text subscribe_link_name
        text template_id
        text text_content
        text view_as_webpage_enabled
        text view_as_webpage_link_name
        text view_as_webpage_text
    }
    email_forward_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text device_type
        text tracking_activity_type
    }
    email_opt_out_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text device_type
        text opt_out_reason
        text tracking_activity_type
    }
    email_campaign_activity_stat_report {
        text last_refresh_time PK
        text campaign_activity_id PK
        text campaign_id PK
        text stats_em_abuse
        text stats_em_bounces
        text stats_em_bounces_blocked
        text stats_em_bounces_mailbox_full
        text stats_em_bounces_nonexistent_address
        text stats_em_bounces_other
        text stats_em_bounces_suspended
        text stats_em_bounces_undeliverable
        text stats_em_bounces_vacation
        text stats_em_clicks
        text stats_em_clicks_all
        text stats_em_clicks_all_computer
        text stats_em_clicks_all_mobile
        text stats_em_clicks_all_none
        text stats_em_clicks_all_other
        text stats_em_clicks_all_tablet
        text stats_em_forwards
        text stats_em_not_opened
        text stats_em_opens
        text stats_em_opens_all
        text stats_em_opens_all_computer
        text stats_em_opens_all_mobile
        text stats_em_opens_all_none
        text stats_em_opens_all_other
        text stats_em_opens_all_tablet
        text stats_em_optouts
        text stats_em_sends
    }
    unique_contact_add_landing_page_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text sms_channel_country_code
        text sms_channel_formatted_international
        text sms_channel_formatted_national
        text sms_channel_state
        text tracking_activity_type
    }
    email_click_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text device_type
        text link_url
        text tracking_activity_type
        text url_id
    }
    email_send_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text tracking_activity_type
    }
    email_open_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text device_type
        text tracking_activity_type
    }
    email_unique_open_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text device_type
        text tracking_activity_type
    }
    send_history_contact_list {
        text contact_list_id PK
        text send_id PK
    }
    send_history_segment {
        text segment_id PK
        text send_id PK
    }
    send_history {
        text send_id PK
        text campaign_activity_id PK
        text count
        text reason_code
        text run_date
        text send_status
    }
    unique_contact_click_landing_page_report {
        text url_id PK
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text device_type
        text link_url
        text sms_channel_country_code
        text sms_channel_formatted_international
        text sms_channel_formatted_national
        text sms_channel_state
        text tracking_activity_type
    }
    unique_contact_sms_opt_in_landing_page_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text sms_channel_country_code
        text sms_channel_formatted_international
        text sms_channel_formatted_national
        text sms_channel_state
        text tracking_activity_type
    }
    html_preview_email_campaign_activity {
        text campaign_activity_id PK
        text from_email
        text from_name
        text preheader
        text preview_html_content
        text preview_text_content
        text reply_to_email
        text subject
    }
    unique_contact_open_landing_page_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text device_type
        text sms_channel_country_code
        text sms_channel_formatted_international
        text sms_channel_formatted_national
        text sms_channel_state
        text tracking_activity_type
    }
    contact_open_landing_page_report {
        text created_time PK
        text campaign_activity_id PK
        text contact_id PK
        text deleted_at
        text device_type
        text sms_channel_country_code
        text sms_channel_formatted_international
        text sms_channel_formatted_national
        text sms_channel_state
        text tracking_activity_type
    }
    unique_contact_update_landing_page_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text sms_channel_country_code
        text sms_channel_formatted_international
        text sms_channel_formatted_national
        text sms_channel_state
        text tracking_activity_type
    }
    email_link_report {
        text url_id PK
        text campaign_activity_id PK
        text list_id FK
        text link_tag
        text link_url
        text list_action
        text unique_clicks
    }
    non_opener_resend_campaign_activity {
        text resend_date PK
        text resend_request_id PK
        text campaign_activity_id PK
        text delay_days
        text delay_minutes
        text resend_status
        text resend_subject
    }
    email_did_not_open_report {
        text campaign_activity_id PK
        text contact_id PK
        text created_time
        text deleted_at
        text tracking_activity_type
    }
    email_campaign_summary_report }o--|| email_campaign : "fk"
    contact_custom }o--|| custom_field : "fk"
    contact_custom }o--|| contact : "fk"
    contact_phone_number }o--|| contact : "fk"
    contact_street_address }o--|| contact : "fk"
    contact_membership }o--|| contact_list : "fk"
    contact_membership }o--|| contact : "fk"
    contact_tagging }o--|| contact_tag : "fk"
    contact_tagging }o--|| contact : "fk"
    contact_note }o--|| contact : "fk"
    contact_sms_channel_consent }o--|| contact : "fk"
    contact_sms_engagement_history }o--|| contact : "fk"
    email_campaign_stat_report }o--|| email_campaign : "fk"
    email_bounce_report }o--|| contact : "fk"
    email_bounce_report }o--|| campaign_activity : "fk"
    campaign_activity_segment }o--|| segment : "fk"
    campaign_activity_segment }o--|| campaign_activity : "fk"
    campaign_activity_contact_list }o--|| contact_list : "fk"
    campaign_activity_contact_list }o--|| campaign_activity : "fk"
    campaign_activity }o--|| email_campaign : "fk"
    email_forward_report }o--|| contact : "fk"
    email_forward_report }o--|| campaign_activity : "fk"
    email_opt_out_report }o--|| contact : "fk"
    email_opt_out_report }o--|| campaign_activity : "fk"
    email_campaign_activity_stat_report }o--|| email_campaign : "fk"
    email_campaign_activity_stat_report }o--|| campaign_activity : "fk"
    unique_contact_add_landing_page_report }o--|| contact : "fk"
    unique_contact_add_landing_page_report }o--|| campaign_activity : "fk"
    email_click_report }o--|| contact : "fk"
    email_click_report }o--|| campaign_activity : "fk"
    email_send_report }o--|| contact : "fk"
    email_send_report }o--|| campaign_activity : "fk"
    email_open_report }o--|| contact : "fk"
    email_open_report }o--|| campaign_activity : "fk"
    email_unique_open_report }o--|| contact : "fk"
    email_unique_open_report }o--|| campaign_activity : "fk"
    send_history_contact_list }o--|| contact_list : "fk"
    send_history_contact_list }o--|| send_history : "fk"
    send_history_segment }o--|| segment : "fk"
    send_history_segment }o--|| send_history : "fk"
    send_history }o--|| campaign_activity : "fk"
    unique_contact_click_landing_page_report }o--|| contact : "fk"
    unique_contact_click_landing_page_report }o--|| campaign_activity : "fk"
    unique_contact_sms_opt_in_landing_page_report }o--|| contact : "fk"
    unique_contact_sms_opt_in_landing_page_report }o--|| campaign_activity : "fk"
    html_preview_email_campaign_activity }o--|| campaign_activity : "fk"
    unique_contact_open_landing_page_report }o--|| contact : "fk"
    unique_contact_open_landing_page_report }o--|| campaign_activity : "fk"
    contact_open_landing_page_report }o--|| contact : "fk"
    contact_open_landing_page_report }o--|| campaign_activity : "fk"
    unique_contact_update_landing_page_report }o--|| contact : "fk"
    unique_contact_update_landing_page_report }o--|| campaign_activity : "fk"
    email_link_report }o--|| contact_list : "fk"
    email_link_report }o--|| campaign_activity : "fk"
    non_opener_resend_campaign_activity }o--|| campaign_activity : "fk"
    email_did_not_open_report }o--|| contact : "fk"
    email_did_not_open_report }o--|| campaign_activity : "fk"
