erDiagram
    product {
        text gtin PK
        text category
        text description
        text family
        text name
        text timestamps
        text upc
    }
    timestamps {
        text _fivetran_id PK
        text timestamps
    }
