erDiagram
    display_setting {
        text _fivetran_id PK
        text event_id FK
        text show_end_date
        text show_facebook_friends_going
        text show_map
        text show_organizer_facebook
        text show_organizer_twitter
        text show_remaining
        text show_start_date
        text show_start_end_time
        text show_timezone
        text terminology
    }
    discount_hold {
        text discount_id PK
        text hold_id PK
    }
    discount_ticket_class {
        text discount_id PK
        text ticket_class_id PK
    }
    discount {
        text id PK
        text event_id FK
        text organization_id FK
        text amount_off
        text code
        text discount_type
        text end_date
        text end_date_relative
        text event
        text percent_off
        text quantity_available
        text quantity_sold
        text start_date
        text start_date_relative
        text ticket_group_id
        text ticket_ids
        text type
    }
    custom_question_ticket_class {
        text id PK
        text custom_question_id PK
        text name
    }
    custom_question_choice {
        text id PK
        text custom_question_id PK
        text answer_text
        text low_stock
        text quantity_available
        text quantity_sold
        jsonb subquestion_ids
    }
    custom_question {
        text id PK
        text event_id FK
        text display_answer_on_order
        text parent_choice_id
        text parent_id
        text question_text
        text required
        text respondent
        text sorting
        text type
    }
    format {
        text id PK
        text name
        text name_localized
        text short_name
        text short_name_localized
    }
    user_request {
        text email PK
        text user_id PK
        text is_primary
        text verified
    }
    users {
        text id PK
        text first_name
        text is_public
        text last_name
        text name
    }
    seat_map {
        text id PK
        text event_id FK
        text organization_id FK
        text venue_id FK
        text capacity
        text name
        text thumbnail_url
    }
    structure_content_working_module {
        text id PK
        text event_id PK
        text data_body_alignment
        text data_body_text
        text layout
        text semantic_purpose
        text type
    }
    structure_content_working_widget_tab_slot_host {
        text name PK
        text event_id PK
        text widget_tab_name PK
        text widget_type PK
    }
    structure_content_working_widget_tab_slot {
        text _fivetran_id PK
        text event_id PK
        text widget_tab_name PK
        text widget_type PK
        text description
        text end_time
        text start_time
        text title
    }
    structure_content_working_widget_tab {
        text name PK
        text widget_type PK
        text event_id PK
    }
    structure_content_working {
        text _fivetran_id PK
        text event_id FK
        text access_type
        text has_autogenerated_content
        text hide_virtual_venue_content
        text page_version_number
        text purpose
    }
    ticket_class_confirmation_setting {
        text _fivetran_id PK
        text event_id FK
        text order_id FK
        text ticket_class_id FK
    }
    orders {
        text id PK
        text organization_id FK
        text base_price_currency
        text base_price_display
        text base_price_major_value
        text base_price_value
        text changed
        text cost_discount_type
        text cost_has_gts_tax
        text cost_tax_name
        text created
        text discount_amount_currency
        text discount_amount_display
        text discount_amount_major_value
        text discount_amount_value
        text display_fee_currency
        text display_fee_display
        text display_fee_major_value
        text display_fee_value
        text display_price_currency
        text display_price_display
        text display_price_major_value
        text display_price_value
        text display_tax_currency
        text display_tax_display
        text display_tax_major_value
        text display_tax_value
        text event_id
        text eventbrite_fee_currency
        text eventbrite_fee_display
        text eventbrite_fee_major_value
        text eventbrite_fee_value
        text gross_currency
        text gross_display
        text gross_major_value
        text gross_value
        text owner_email
        text owner_first_name
        text owner_last_name
        text owner_name
        text payment_fee_currency
        text payment_fee_display
        text payment_fee_major_value
        text payment_fee_value
        text price_before_discount_currency
        text price_before_discount_display
        text price_before_discount_major_value
        text price_before_discount_value
        text status
        text tax_currency
        text tax_display
        text tax_major_value
        text tax_value
        text ticket_buyer_confirmation_message_text
        text ticket_buyer_instructions_text
        text ticket_buyer_settings_event_id
        text ticket_buyer_settings_refund_request_enabled
        text time_remaining
    }
    code_component {
        text _fivetran_id PK
        text base
        text bucket
        text discount_currency
        text discount_display
        text discount_major_value
        text discount_reason
        text discount_value
        text group_name
        text intermediate
        text internal_name
        text name
        text payer
        text recipient
        text rule_id
        text type
        text value
    }
    organization_role {
        text id PK
        text organization_id FK
        text deletable
        text description
        text grantable
        text immutable
        text name
        jsonb permission
        text permission_type
    }
    ticket_delivery_method {
        text delivery_method PK
        text event_id PK
        text ticket_class_id PK
    }
    ticket_delivery_sales_channel {
        text sales_channel PK
        text event_id PK
        text ticket_class_id PK
    }
    ticket_class {
        text id PK
        text event_id FK
        text inventory_tier_id FK
        text actual_cost_currency
        text actual_cost_display
        text actual_cost_major_value
        text actual_cost_value
        text actual_fee_currency
        text actual_fee_display
        text actual_fee_major_value
        text actual_fee_value
        text auto_hide
        text auto_hide_after
        text auto_hide_before
        text capacity
        text cost_currency
        text cost_display
        text cost_major_value
        text cost_value
        text description
        text display_name
        text donation
        text fee_currency
        text fee_display
        text fee_major_value
        text fee_value
        text free
        text has_pdf_ticket
        text hidden
        text hidden_currently
        text hide_description
        text hide_sale_dates
        text include_fee
        text maximum_quantity
        text maximum_quantity_per_order
        text minimum_quantity
        text name
        text on_sale_status
        text order_confirmation_message
        jsonb payment_constraints
        text quantity_sold
        text quantity_total
        text sales_channels
        text sales_end
        text sales_end_relative
        text sales_start
        text sales_start_after
        text secondary_assignment_enabled
        text sorting
        text split_fee
        text tax_currency
        text tax_display
        text tax_major_value
        text tax_value
    }
    venue {
        text id PK
        text organization_id FK
        text address_address_1
        text address_address_2
        text address_city
        text address_country
        text address_latitude
        text address_localized_address_display
        text address_localized_area_display
        jsonb address_localized_multi_line_address_display
        text address_longitude
        text address_postal_code
        text address_region
        text age_restriction
        text capacity
        text latitude
        text longitude
        text name
    }
    default_question_ticket_class {
        text id PK
        text default_question_id PK
        text name
    }
    default_question_choice {
        text id PK
        text default_question_id PK
        text answer_text
        text low_stock
        text quantity_available
        text quantity_sold
        jsonb subquestion_ids
    }
    default_question {
        text id PK
        text event_id FK
        text default_value
        text editable
        text group_display_header
        text group_id
        text include
        text question_text
        text required
        text respondent
        text type
    }
    event_checkout_offline_setting {
        text _fivetran_id PK
        text event_id FK
        text instructions
        text payment_method
    }
    event_subcategory {
        text id PK
        text event_id PK
        text name
        jsonb parent_category
    }
    event {
        text id PK
        text category_id FK
        text format_id FK
        text organization_id FK
        text organizer_id FK
        text subcategory_id FK
        text venue_id FK
        text capacity
        text capacity_is_custom
        text category_name
        text category_name_localized
        text category_short_name
        text category_short_name_localized
        text changed
        text checkout_settings_changed
        text checkout_settings_checkout_method
        text checkout_settings_country_code
        text checkout_settings_created
        text checkout_settings_currency_code
        text checkout_settings_user_instrument_vault_id
        timestamp created
        text currency
        text description_text
        text end_local
        text end_timezone
        text end_utc
        text event_sales_start_date_local
        text event_sales_start_date_timezone
        text event_sales_start_date_utc
        text event_sales_status
        text external_ticketing_external_url
        text external_ticketing_is_free
        text external_ticketing_sales_end
        text external_ticketing_sales_start
        text external_ticketing_ticketing_provider_name
        text facebook_event_id
        text format_name
        text format_name_localized
        text format_short_name
        text format_short_name_localized
        text hide_end_date
        text hide_start_date
        text inventory_type
        text invite_only
        text is_externally_ticketed
        text is_free
        text is_locked
        text is_reserved_seating
        text is_series
        text is_series_parent
        text listed
        text locale
        text logo_aspect_ratio
        text logo_crop_mask_height
        text logo_crop_mask_top_left_x
        text logo_crop_mask_top_left_y
        text logo_crop_mask_width
        text logo_edge_color
        text logo_edge_color_set
        text logo_id
        text logo_original_height
        text logo_original_url
        text logo_original_width
        text logo_url
        text max_ticket_price_currency
        text max_ticket_price_display
        text max_ticket_price_major_value
        text max_ticket_price_value
        text min_ticket_price_currency
        text min_ticket_price_display
        text min_ticket_price_major_value
        text min_ticket_price_value
        text music_properties_age_restriction
        text music_properties_door_time
        text music_properties_presented_by
        text name_text
        text online_event
        text organizer_description
        text organizer_facebook
        text organizer_logo_aspect_ratio
        text organizer_logo_crop_mask_height
        text organizer_logo_crop_mask_top_left_x
        text organizer_logo_crop_mask_top_left_y
        text organizer_logo_crop_mask_width
        text organizer_logo_edge_color
        text organizer_logo_edge_color_set
        text organizer_logo_id
        text organizer_logo_original_height
        text organizer_logo_original_url
        text organizer_logo_original_width
        text organizer_logo_url
        text organizer_long_description
        text organizer_name
        text organizer_num_future_events
        text organizer_num_past_events
        text organizer_twitter
        text organizer_url
        text privacy_setting
        text published
        text series_id
        text shareable
        text show_colors_in_seatmap_thumbnail
        text show_pick_a_seat
        text show_remaining
        text show_seatmap_thumbnail
        text source
        text start_local
        text start_timezone
        text start_utc
        text status
        text subcategory_name
        text subcategory_parent_category_id
        text subcategory_parent_category_name
        text subcategory_parent_category_name_localized
        text subcategory_parent_category_short_name
        text subcategory_parent_category_short_name_localized
        text subcategory_parent_category_subcategories
        text ticket_availability_has_available_tickets
        text ticket_availability_is_sold_out
        text ticket_availability_max_ticket_price_currency
        text ticket_availability_max_ticket_price_display
        text ticket_availability_max_ticket_price_major_value
        text ticket_availability_max_ticket_price_value
        text ticket_availability_min_ticket_price_currency
        text ticket_availability_min_ticket_price_display
        text ticket_availability_min_ticket_price_major_value
        text ticket_availability_min_ticket_price_value
        text ticket_availability_start_sales_date_local
        text ticket_availability_start_sales_date_timezone
        text ticket_availability_start_sales_date_utc
        text ticket_availability_waitlist_available
        text tx_time_limit
        text url
        text vanity_url
        text venue_address_1
        text venue_address_2
        text venue_age_restriction
        text venue_capacity
        text venue_city
        text venue_country
        text venue_latitude
        text venue_longitude
        text venue_name
        text venue_postal_code
        text venue_region
        text version
    }
    event_hold {
        text id PK
        text event_id FK
        text abbreviation
        text color
        text name
        text quantity_pending
        text quantity_sold
        text quantity_total
        text sort_order
    }
    event_capacity {
        text event_id PK
        text capacity_is_custom
        text capacity_pending
        text capacity_sold
        text capacity_total
        text quantity_pending
        text quantity_sold
        text quantity_total
    }
    attendee_barcode {
        text barcode PK
        text attendee_id FK
        text changed
        text checkin_type
        text created
        text is_printed
        text status
    }
    attendee_answer {
        text attendee_id PK
        text question_id PK
        text answer
        text question
        text type
    }
    attendee_question {
        text id PK
        text attendee_id PK
        text label
        text required
        text type
    }
    attendee {
        text id PK
        text event_id FK
        text invited_by FK
        text order_id FK
        text organization_id FK
        text ticket_class_id FK
        text affiliate
        text assigned_unit_description
        text assigned_unit_id
        jsonb assigned_unit_labels
        jsonb assigned_unit_titles
        text base_price_currency
        text base_price_display
        text base_price_major_value
        text base_price_value
        text cancelled
        text changed
        text checked_in
        text contact_list_preferences_has_contact_list
        text contact_list_preferences_has_opted_in
        text contact_list_preferences_type
        text created
        text delivery_method
        text eventbrite_fee_currency
        text eventbrite_fee_display
        text eventbrite_fee_major_value
        text eventbrite_fee_value
        text gross_currency
        text gross_display
        text gross_major_value
        text gross_value
        text guestlist_id
        text payment_fee_currency
        text payment_fee_display
        text payment_fee_major_value
        text payment_fee_value
        text profile_addresses_bill_address_1
        text profile_addresses_bill_address_2
        text profile_addresses_bill_city
        text profile_addresses_bill_country
        text profile_addresses_bill_latitude
        text profile_addresses_bill_localized_address_display
        text profile_addresses_bill_localized_area_display
        jsonb profile_addresses_bill_localized_multi_line_address_display
        text profile_addresses_bill_longitude
        text profile_addresses_bill_postal_code
        text profile_addresses_bill_region
        text profile_addresses_home_address_1
        text profile_addresses_home_address_2
        text profile_addresses_home_city
        text profile_addresses_home_country
        text profile_addresses_home_latitude
        text profile_addresses_home_localized_address_display
        text profile_addresses_home_localized_area_display
        jsonb profile_addresses_home_localized_multi_line_address_display
        text profile_addresses_home_longitude
        text profile_addresses_home_postal_code
        text profile_addresses_home_region
        text profile_addresses_ship_address_1
        text profile_addresses_ship_address_2
        text profile_addresses_ship_city
        text profile_addresses_ship_country
        text profile_addresses_ship_latitude
        text profile_addresses_ship_localized_address_display
        text profile_addresses_ship_localized_area_display
        jsonb profile_addresses_ship_localized_multi_line_address_display
        text profile_addresses_ship_longitude
        text profile_addresses_ship_postal_code
        text profile_addresses_ship_region
        text profile_addresses_work_address_1
        text profile_addresses_work_address_2
        text profile_addresses_work_city
        text profile_addresses_work_country
        text profile_addresses_work_latitude
        text profile_addresses_work_localized_address_display
        text profile_addresses_work_localized_area_display
        jsonb profile_addresses_work_localized_multi_line_address_display
        text profile_addresses_work_longitude
        text profile_addresses_work_postal_code
        text profile_addresses_work_region
        text profile_age
        text profile_birth_date
        text profile_blog
        text profile_cell_phone
        text profile_company
        text profile_email
        text profile_first_name
        text profile_gender
        text profile_job_title
        text profile_last_name
        text profile_name
        text profile_prefix
        text profile_suffix
        text profile_website
        text profile_work_phone
        text refunded
        text status
        text tax_currency
        text tax_display
        text tax_major_value
        text tax_value
        text team_date_joined
        text team_event_id
        text team_id
        text team_name
        text variant_id
    }
    inventory_tier_ticket_class {
        text ticket_class_id PK
        text inventory_tier_id PK
    }
    inventory_tier_hold {
        text id PK
        text inventory_tier_id PK
        text event_hold_id FK
        text event_id FK
    }
    inventory_tier {
        text id PK
        text event_id FK
        text capacity_total
        text color
        text count_against_event_capacity
        text name
        text quantity_held
        text quantity_pending
        text quantity_sold
        text quantity_total
        text seatmap_number
        text sort_order
        text tier
    }
    buyer_ticket_class {
        text survey_ticket_class_id PK
        text ticket_buyer_event_id PK
    }
    ticket_buyer {
        text event_id PK
        text allow_attendee_update
        text confirmation_message_text
        text instructions_text
        text redirect_url
        text refund_request_enabled
        text sales_ended_message_text
        text survey_info_text
        text survey_name
        text survey_respondent
        text survey_time_limit
    }
    organization_member {
        text user_id PK
        text organization_id FK
        text immutable
        text role_summary
        text type
    }
    organization {
        text id PK
        text created
        text locale
        text name
        text parent_id
        text type
        text vertical
    }
    ticket_group {
        text _fivetran_id PK
        text organization_id FK
        jsonb event_ticket_ids
        text name
        text status
        jsonb tickets
    }
    sub_category {
        text id PK
        text category_id PK
        text name
        jsonb parent_category
    }
    category {
        text id PK
        text name
        text name_localized
        text short_name
        text short_name_localized
    }
    pricing {
        text _fivetran_id PK
        text channel FK
        text payment_type FK
        text country
        text currency
        text fee_name
        text fixed_currency
        text fixed_display
        text fixed_major_value
        text fixed_value
        text item_type
        text maximum_currency
        text maximum_display
        text maximum_major_value
        text maximum_value
        text minimum_currency
        text minimum_display
        text minimum_major_value
        text minimum_value
        text payment_fee
        text percentage
        text plan
    }
    display_setting }o--|| event : "fk"
    discount_hold }o--|| event_hold : "fk"
    discount_hold }o--|| discount : "fk"
    discount_ticket_class }o--|| ticket_class : "fk"
    discount_ticket_class }o--|| discount : "fk"
    discount }o--|| event : "fk"
    discount }o--|| organization : "fk"
    custom_question_ticket_class }o--|| custom_question : "fk"
    custom_question_choice }o--|| custom_question : "fk"
    custom_question }o--|| event : "fk"
    user_request }o--|| users : "fk"
    users }o--|| organization_member : "fk"
    seat_map }o--|| event : "fk"
    seat_map }o--|| venue : "fk"
    seat_map }o--|| organization : "fk"
    structure_content_working_module }o--|| structure_content_working : "fk"
    structure_content_working_widget_tab_slot_host }o--|| structure_content_working_widget_tab_slot : "fk"
    structure_content_working_widget_tab_slot_host }o--|| structure_content_working_widget_tab : "fk"
    structure_content_working_widget_tab_slot_host }o--|| structure_content_working_widget_tab : "fk"
    structure_content_working_widget_tab_slot }o--|| structure_content_working_widget_tab : "fk"
    structure_content_working_widget_tab_slot }o--|| structure_content_working_widget_tab : "fk"
    structure_content_working_widget_tab_slot }o--|| structure_content_working_widget_tab : "fk"
    structure_content_working_widget_tab }o--|| structure_content_working : "fk"
    structure_content_working }o--|| event : "fk"
    ticket_class_confirmation_setting }o--|| ticket_class : "fk"
    ticket_class_confirmation_setting }o--|| event : "fk"
    ticket_class_confirmation_setting }o--|| orders : "fk"
    orders }o--|| event : "fk"
    orders }o--|| organization : "fk"
    organization_role }o--|| organization : "fk"
    ticket_delivery_method }o--|| ticket_class : "fk"
    ticket_delivery_method }o--|| event : "fk"
    ticket_delivery_sales_channel }o--|| ticket_class : "fk"
    ticket_delivery_sales_channel }o--|| event : "fk"
    ticket_class }o--|| inventory_tier : "fk"
    ticket_class }o--|| event : "fk"
    venue }o--|| organization : "fk"
    default_question_ticket_class }o--|| default_question : "fk"
    default_question_choice }o--|| default_question : "fk"
    default_question }o--|| event : "fk"
    event_checkout_offline_setting }o--|| event : "fk"
    event_subcategory }o--|| event : "fk"
    event }o--|| category : "fk"
    event }o--|| sub_category : "fk"
    event }o--|| venue : "fk"
    event }o--|| organization : "fk"
    event }o--|| organization_member : "fk"
    event }o--|| format : "fk"
    event_hold }o--|| event : "fk"
    event_capacity }o--|| event : "fk"
    attendee_barcode }o--|| attendee : "fk"
    attendee_answer }o--|| attendee_question : "fk"
    attendee_answer }o--|| attendee : "fk"
    attendee_question }o--|| attendee : "fk"
    attendee }o--|| event : "fk"
    attendee }o--|| ticket_class : "fk"
    attendee }o--|| organization_member : "fk"
    attendee }o--|| orders : "fk"
    attendee }o--|| organization : "fk"
    inventory_tier_ticket_class }o--|| inventory_tier : "fk"
    inventory_tier_hold }o--|| event_hold : "fk"
    inventory_tier_hold }o--|| event : "fk"
    inventory_tier_hold }o--|| inventory_tier : "fk"
    inventory_tier }o--|| event : "fk"
    buyer_ticket_class }o--|| ticket_buyer : "fk"
    ticket_buyer }o--|| event : "fk"
    organization_member }o--|| organization : "fk"
    ticket_group }o--|| organization : "fk"
    sub_category }o--|| category : "fk"
    pricing }o--|| event_checkout_offline_setting : "fk"
    pricing }o--|| ticket_delivery_sales_channel : "fk"
