erDiagram
    reporting_balance {
        text id PK
        text division FK
        text amount
        text amount_credit
        text amount_debit
        text balance_type
        text cost_center_code
        text cost_center_description
        text cost_unit_code
        text cost_unit_description
        text count
        text gl_account
        text gl_account_code
        text gl_account_description
        text reporting_period
        text reporting_year
        text status
        text type
    }
    gl_account_classification_mapping {
        text id PK
        text classification FK
        text division_id FK
        text classification_code
        text classification_description
        text gl_account
        text gl_account_code
        text gl_account_description
        text gl_scheme_code
        text gl_scheme_description
        text gl_scheme_id
    }
    transaction_line {
        text id PK
        text account
        text account_code
        text account_name
        text amount_dc
        text amount_fc
        text amount_vat_base_fc
        text amount_vat_fc
        text asset
        text asset_code
        text asset_description
        text cost_center
        text cost_center_description
        text cost_unit
        text cost_unit_description
        text created
        text creator
        text creator_full_name
        text currency
        text custom_field
        text date
        text description
        text division
        text document
        text document_number
        text document_subject
        text due_date
        text entry_id
        text entry_number
        text exchange_rate
        text external_link_description
        text external_link_reference
        text extra_duty_amount_fc
        text extra_duty_percentage
        text financial_period
        text financial_year
        text gl_account
        text gl_account_code
        text gl_account_description
        text invoice_number
        text item
        text item_code
        text item_description
        text journal_code
        text journal_description
        text line_number
        text line_type
        text modified
        text modifier
        text modifier_full_name
        text notes
        text offset_id
        text order_number
        text payment_discount_amount
        text payment_reference
        text project
        text project_code
        text project_description
        text quantity
        text serial_number
        text shop_order
        text status
        text subscription
        text subscription_description
        text system_division_id
        text tracking_number
        text tracking_number_description
        text type
        text vat_code
        text vat_code_description
        text vat_percentage
        text vat_type
        text your_ref
    }
    profit_loss_overview {
        text _fivetran_id PK
        text costs_current_period
        text costs_current_year
        text costs_previous_year
        text costs_previous_year_period
        text currency_code
        text current_period
        text current_year
        text metadata_type
        text metadata_uri
        text previous_year
        text previous_year_period
        text result_current_period
        text result_current_year
        text result_previous_year
        text result_previous_year_period
        text revenue_current_period
        text revenue_current_year
        text revenue_previous_year
        text revenue_previous_year_period
        text system_division_id
    }
    subscription {
        text id PK
        text division FK
        text block_entry
        text cancellation_date
        text classification
        text classification_code
        text classification_description
        text created
        text creator
        text creator_full_name
        text currency
        text customer_po_number
        text description
        text end_date
        text invoice_day
        text invoice_to
        text invoice_to_contact_person
        text invoice_to_contact_person_full_name
        text invoice_to_name
        text invoiced_to
        text invoicing_start_date
        text modified
        text modifier
        text modifier_full_name
        text note
        text number
        text ordered_by
        text ordered_by_contact_person
        text ordered_by_contact_person_full_name
        text ordered_by_name
        text payment_condition
        text payment_condition_description
        text printed
        text project
        text reason_cancelled
        text reason_cancelled_code
        text reason_cancelled_description
        text start_date
        text subscription_type
        text subscription_type_code
        text subscription_type_description
        text timestamps
    }
    sales_invoice_line {
        text id PK
        text amount_dc
        text amount_fc
        text cost_center
        text cost_center_description
        text cost_unit
        text cost_unit_description
        text custom_field
        text customer_item_code
        text delivery_date
        text description
        text discount
        text division
        text employee
        text employee_full_name
        text end_time
        text extra_duty_amount_fc
        text extra_duty_percentage
        text gl_account
        text gl_account_description
        text invoice_id
        text item
        text item_code
        text item_description
        text line_number
        text net_price
        text notes
        text pricelist
        text pricelist_description
        text project
        text project_description
        text project_wbs
        text project_wbs_description
        text quantity
        text sales_order
        text sales_order_line
        text sales_order_line_number
        text sales_order_number
        text start_time
        text subscription
        text subscription_description
        text system_division_id
        text tax_schedule
        text tax_schedule_code
        text tax_schedule_description
        text unit_code
        text unit_description
        text unit_price
        text vat_amount_dc
        text vat_amount_fc
        text vat_code
        text vat_code_description
        text vat_percentage
    }
    users {
        text id PK
        text division_id FK
        text account
        text account_city
        text account_code
        text account_is_supplier
        text account_logo_thumbnail_url
        text account_name
        text account_status
        text created
        text created_utc
        text creator
        text creator_full_name
        text division_company_coc_number
        text division_company_iban_number
        text division_company_name
        text division_company_rsin_number
        text division_company_vat_number
        text division_company_wage_tax_number
        text division_label
        text division_name
        text division_owner_company_name
        text division_owner_company_number
        text division_short_name
        text involved_user_role
        text involved_user_role_description
        text is_main_contact
        text modified
        text modified_utc
        text modifier
        text modifier_full_name
        text person_email
        text person_phone
        text person_phone_extension
        text person_picture_thumbnail_url
        text user_full_name
        text users
    }
    division {
        text id PK
        text accounting_division
        text customer_code
        text division_customer
        text division_customer_code
        text division_customer_name
        text division_customer_siret_number
        text division_customer_vat_number
        text dossier_division
        text email
        text employee_id
        text first_name
        text full_name
        text gender
        text initials
        text is_client_user
        text is_employee_self_service_user
        text is_my_firm_lite_user
        text is_my_firm_portal_user
        text is_starter_user
        text language_code
        text languages
        text last_name
        text legislation
        text middle_name
        text mobile
        text nationality
        text phone
        text phone_extension
        text picture_url
        text server_time
        text server_utc_offset
        text thumbnail_picture
        text thumbnail_picture_format
        text title
        text user_id
        text user_name
    }
    revenue_list {
        text period PK
        text year PK
        text amount
        text system_division_id
    }
    bank {
        text id PK
        text bank_name
        text bic_code
        text country
        text created
        text description
        text format
        text home_page_address
        text modified
        text status
        text system_division_id
    }
    subscription_line {
        text id PK
        text division FK
        text amount_dc
        text amount_fc
        text cost_center
        text costunit
        text custom_field
        text description
        text discount
        text entry_id
        text from_date
        text item
        text item_description
        text line_number
        text line_type
        text line_type_description
        text modified
        text net_price
        text note
        text quantity
        text subscription_number
        text timestamps
        text to_date
        text unit_code
        text unit_description
        text unit_price
        text vat_amount_fc
        text vat_code
        text vat_code_description
    }
    contact {
        text id PK
        text account_id FK
        text division_id FK
        text account_is_customer
        text account_is_supplier
        text account_main_contact
        text account_name
        text address_line_2
        text address_street
        text address_street_number_suffix
        text allow_mailing
        text birth_date
        text birth_name
        text birth_name_prefix
        text birth_place
        text business_email
        text business_fax
        text business_mobile
        text business_phone
        text business_phone_extension
        text city
        text code
        text country
        text created
        text creator
        text creator_full_name
        text custom_field
        text email
        text end_date
        text first_name
        text full_name
        text gender
        text hid
        text identification_date
        text identification_document
        text identification_user
        text initials
        text is_anonymised
        text is_mailing_excluded
        text is_main_contact
        text job_title_description
        text languages
        text last_name
        text lead_purpose
        text lead_source
        text marketing_notes
        text middle_name
        text mobile
        text modified
        text modifier
        text modifier_full_name
        text nationality
        text notes
        text partner_name
        text partner_name_prefix
        text person
        text phone
        text phone_extension
        text picture
        text picture_name
        text picture_thumbnail_url
        text picture_url
        text postcode
        text start_date
        text state
        text timestamps
        text title
        text title_abbreviation
        text title_description
    }
    gl_classification {
        text id PK
        text division_id FK
        text abstract
        text balance
        text code
        text created
        text creator
        text creator_full_name
        text description
        text is_tuple_sub_element
        text modified
        text modifier
        text modifier_full_name
        text name
        text nillable
        text parent
        text period_type
        text substitution_group
        text taxonomy_namespace
        text taxonomy_namespace_description
        text timestamps
        text type
    }
    account_classification {
        text id PK
        text division_id FK
        text account_classification_name
        text account_classification_name_description
        text code
        text created
        text created_utc
        text creator
        text creator_full_name
        text description
        text division_company_coc_number
        text division_company_iban_number
        text division_company_name
        text division_company_rsin_number
        text division_company_vat_number
        text division_company_wage_tax_number
        text division_label
        text division_name
        text division_owner_company_name
        text division_owner_company_number
        text division_short_name
        text modified
        text modified_utc
        text modifier
        text modifier_full_name
    }
    system_division {
        text id PK
        text address_line_1
        text address_line_2
        text address_line_3
        text archive_date
        text blocking_status
        text business_type_code
        text business_type_description
        text chamber_of_commerce_establishment
        text chamber_of_commerce_number
        text city
        text class_01
        text class_02
        text class_03
        text class_04
        text class_05
        text company_size_code
        text company_size_description
        text country
        text created
        text creator
        text creator_full_name
        text currency
        text current
        text customer
        text customer_code
        text customer_name
        text date_v_accountant_number
        text date_v_client_number
        text description
        text division_hr_link_unlink_date
        text division_move_date
        text email
        text fax
        text hid
        text is_dossier_division
        text is_hr_division
        text is_main_division
        text is_practice_division
        text legislation
        text modified
        text modifier
        text modifier_full_name
        text ob_number
        text phone
        text postcode
        text sbi_code
        text sbi_description
        text sector_code
        text sector_description
        text share_capital
        text siret_number
        text start_date
        text state
        text status
        text subsector_code
        text subsector_description
        text tax_office_number
        text tax_reference_number
        text template_code
        text vat_number
        text website
    }
    lead_purpose {
        text id PK
        text division_id FK
        text code
        text description
        text division_company_coc_number
        text division_company_iban_number
        text division_company_name
        text division_company_rsin_number
        text division_company_vat_number
        text division_company_wage_tax_number
        text division_label
        text division_name
        text division_owner_company_name
        text division_owner_company_number
        text division_short_name
    }
    gl_account {
        text id PK
        text division_id FK
        text allow_costs_in_sales
        text assimilated_vatbox
        text balance_side
        text balance_type
        text belcotax_type
        text code
        text compress
        text cost_center
        text cost_center_description
        text costunit
        text costunit_description
        text created
        text creator
        text creator_fullname
        text custom_field
        text deductibility_percentages_deferred_uri
        text description
        text description_term_id
        text exclude_vat_listing
        text expense_non_deductible_percentage
        text is_blocked
        text matching
        text modified
        text modifier
        text modifier_full_name
        text private_gl_account
        text private_percentage
        text reporting_code
        text revalue_currency
        text search_code
        text timestamps
        text type
        text type_description
        text use_cost_center
        text use_costunit
        text vat_code
        text vat_description
        text vat_gl_account_type
        text vat_non_deductible_gl_account
        text vat_non_deductible_percentage
        text vat_system
        text year_end_cost_gl_account
        text year_end_reflection_gl_account
    }
    return {
        text document_id PK
        text amount
        text created
        text currency
        text description
        text document_view_url
        text due_date
        text frequency
        text metadata_type
        text metadata_uri
        text payroll_declaration_type
        text period
        text period_description
        text request
        text status
        text subject
        text system_division_id
        text type
        text year
    }
    account {
        text id PK
        text division_id FK
        text account_manager
        text account_manager_full_name
        text account_manager_hid
        text accountant
        text activity_sector
        text activity_sub_sector
        text address_line_1
        text address_line_2
        text address_line_3
        text address_source
        text bankaccounts_deferred_uri
        text blocked
        text brin
        text bsn
        text business_type
        text can_drop_ship
        text chamber_of_commerce
        text city
        text classification
        text classification_1
        text classification_2
        text classification_3
        text classification_4
        text classification_5
        text classification_6
        text classification_7
        text classification_8
        text classification_description
        text code
        text code_at_supplier
        text company_size
        text consolidation_scenario
        text controlled_date
        text cost_center
        text cost_center_description
        text cost_paid
        text country
        text country_name
        text created
        text creator
        text creator_full_name
        text credit_line_purchase
        text credit_line_sales
        text currency
        text custom_field
        text customer_since
        text datev_creditor_code
        text datev_debtor_code
        text delivery_advice
        text discount_purchase
        text discount_sales
        text document
        text duns_number
        text email
        text enable_sales_payment_link
        text end_date
        text eori_number
        text established_date
        text fax
        text gl_account_purchase
        text gl_account_sales
        text glap
        text glar
        text gln_number
        text has_withholding_tax_sales
        text ignore_datev_warning_message
        text incoterm_address_purchase
        text incoterm_address_sales
        text incoterm_code_purchase
        text incoterm_code_sales
        text incoterm_version_purchase
        text incoterm_version_sales
        text intra_stat_area
        text intra_stat_delivery_term
        text intra_stat_system
        text intra_stat_transaction_a
        text intra_stat_transaction_b
        text intra_stat_transport_method
        text invoice_account
        text invoice_account_code
        text invoice_account_name
        text invoice_attachment_type
        text invoicing_method
        text is_accountant
        text is_agency
        text is_anonymised
        text is_bank
        text is_competitor
        text is_extra_duty
        text is_mailing
        text is_member
        text is_pilot
        text is_purchase
        text is_reseller
        text is_sales
        text is_supplier
        text language_description
        text languages
        text latitude
        text lead_purpose
        text lead_source
        text logo
        text logo_file_name
        text logo_thumbnail_url
        text logo_url
        text longitude
        text main_contact
        text modified
        text modifier
        text modifier_full_name
        text name
        text oin_number
        text parent
        text pay_as_you_earn
        text payment_condition_purchase
        text payment_condition_purchase_description
        text payment_condition_sales
        text payment_condition_sales_description
        text phone
        text phone_extension
        text postcode
        text price_list
        text purchase_currency
        text purchase_currency_description
        text purchase_lead_days
        text purchase_v_a_t_code
        text purchase_v_a_t_code_description
        text recepient_of_commissions
        text remarks
        text reseller
        text reseller_code
        text reseller_name
        text rsin
        text sales_currency
        text sales_currency_description
        text sales_tax_schedule
        text sales_tax_schedule_code
        text sales_tax_schedule_description
        text sales_v_a_t_code
        text sales_v_a_t_code_description
        text search_code
        text security_level
        text separate_inv_per_project
        text separate_inv_per_subscription
        text shipping_lead_days
        text shipping_method
        text show_remark_for_sales
        text source
        text start_date
        text state
        text state_name
        text status
        text status_since
        text timestamps
        text trade_name
        text type
        text unique_taxpayer_reference
        text vat_liability
        text vat_number
        text website
    }
    sales_invoice {
        text id PK
        text amount_dc
        text amount_discount
        text amount_discount_excl_vat
        text amount_fc
        text amount_fc_excl_vat
        text created
        text creator
        text creator_full_name
        text currency
        text deliver_to
        text deliver_to_address
        text deliver_to_contact_person
        text deliver_to_contact_person_full_name
        text deliver_to_name
        text description
        text discount
        text discount_type
        text division
        text document
        text document_number
        text document_subject
        text due_date
        text extra_duty_amount_fc
        text g_account_amount_fc
        text incoterm_address
        text incoterm_code
        text incoterm_version
        text invoice_date
        text invoice_number
        text invoice_to
        text invoice_to_contact_person
        text invoice_to_contact_person_full_name
        text invoice_to_name
        text is_extra_duty
        text journal
        text journal_description
        text modified
        text modifier
        text modifier_full_name
        text order_date
        text order_number
        text ordered_by
        text ordered_by_contact_person
        text ordered_by_contact_person_full_name
        text ordered_by_name
        text payment_condition
        text payment_condition_description
        text payment_reference
        text remarks
        text sales_channel
        text sales_channel_code
        text sales_channel_description
        text sales_invoice_lines
        text salesperson
        text salesperson_full_name
        text selection_code
        text selection_code_code
        text selection_code_description
        text shipping_method
        text shipping_method_code
        text shipping_method_description
        text starter_sales_invoice_status
        text starter_sales_invoice_status_description
        text status
        text status_description
        text system_division_id
        text tax_schedule
        text tax_schedule_code
        text tax_schedule_description
        text type
        text type_description
        text vat_amount_dc
        text vat_amount_fc
        text warehouse
        text withholding_tax_amount_fc
        text withholding_tax_base_amount
        text withholding_tax_percentage
        text your_ref
    }
    bank_account {
        text id PK
        text division_id FK
        text account
        text account_name
        text bank
        text bank_account
        text bank_account_holder_name
        text bank_description
        text bank_name
        text bic_code
        text blocked
        text created
        text creator
        text creator_full_name
        text description
        text format
        text iban
        text main
        text modified
        text modifier
        text modifier_full_name
        text payment_service_account
        text type
        text type_description
    }
    reporting_balance }o--|| division : "fk"
    gl_account_classification_mapping }o--|| system_division : "fk"
    gl_account_classification_mapping }o--|| gl_classification : "fk"
    subscription }o--|| division : "fk"
    users }o--|| division : "fk"
    subscription_line }o--|| division : "fk"
    contact }o--|| system_division : "fk"
    contact }o--|| account : "fk"
    gl_classification }o--|| system_division : "fk"
    account_classification }o--|| system_division : "fk"
    system_division }o--|| division : "fk"
    lead_purpose }o--|| division : "fk"
    gl_account }o--|| division : "fk"
    account }o--|| system_division : "fk"
    bank_account }o--|| division : "fk"
