erDiagram
    document {
        text id PK
        text employee_id FK
        text folder_id FK
        text author_id
        text company_id
        text content_type
        text created_at
        text deleted_at
        text extension
        text file_size
        text filename
        text is_company_document
        text is_management_document
        text is_pending_assignment
        text leave_id
        text public
        text signature_status
        jsonb signees
        text space
        text updated_at
    }
    policies {
        text id PK
        text company_id
        text description
        text main
        text name
    }
    shift_management {
        text id PK
        text employee_id FK
        text location_id FK
        text company_id
        text default_shift_title
        text end_at
        text extra_hours
        text local_end_at
        text local_start_at
        text locations_work_area_id
        text name
        text notes
        text start_at
        text state
        text timezone
    }
    taxonomy {
        text id PK
        text legal_entity_id FK
        text archived
        text defaults
        text name
    }
    employee {
        text id PK
        text legal_entity_id FK
        text location_id FK
        text manager_id FK
        text timeoff_manager_id FK
        text access_id
        text active
        text address_line_1
        text address_line_2
        text age_number
        text attendable
        text bank_number
        text bank_number_format
        text birth_name
        text birthday_on
        text birthplace
        text city
        text company_id
        text company_identifier
        text contact_name
        text contact_number
        text country
        text country_of_birth
        text created_at
        text disability_percentage_cents
        text email
        text first_name
        text full_name
        text gender
        text identifier
        text identifier_expiration_date
        text identifier_type
        text is_terminating
        text last_name
        text login_email
        text nationality
        text personal_email
        text phone_number
        text postal_code
        text preferred_name
        text pronouns
        text seniority_calculation_date
        text social_security_number
        text state
        text swift_bic
        text terminated_on
        text termination_observations
        text termination_reason
        text termination_reason_type
        text termination_type_description
        text updated_at
    }
    ats_job_posting_id {
        text ats_job_posting_id PK
        text candidate_id PK
    }
    candidate {
        text id PK
        text company_id
        text consent_expiration_date
        text consent_given_at
        text consent_to_talent_pool
        text created_at
        text email
        text first_name
        text full_name
        text gender
        text inactive_since
        text last_name
        text medium
        text personal_url
        text phone_number
        text score
        text source_id
        text talent_pool
        text updated_at
    }
    post {
        text id PK
        text allow_comments_and_reactions
        text comments_count
        text cover_image_url
        text created_at
        text description
        text posts_group_id
        text published_at
        text title
        text updated_at
        text visits_count
    }
    leave {
        text id PK
        text employee_id FK
        text leave_type_id FK
        text approved
        text company_id
        text created_at
        text description
        text employee_full_name
        text finish_on
        text half_day
        text hours_amount_in_cents
        text leave_type_name
        text reason
        text start_on
        text start_time
        text updated_at
    }
    contract {
        text id PK
        text employee_id FK
        text annual_working_time_distribution
        text bank_holiday_treatment
        text company_id
        text contracts_es_tariff_group_id
        text country
        text created_at
        text de_contract_type_id
        text effective_on
        text ends_on
        text es_contract_observations
        text es_contract_type_id
        text es_cotization_group
        text es_education_level_id
        text es_has_teleworking_contract
        text es_job_description
        text es_professional_category_id
        text es_working_day_type_id
        text fr_coefficient
        text fr_contract_type_id
        text fr_employee_type
        text fr_forfait_jours
        text fr_jours_par_an
        text fr_level_id
        text fr_mutual_id
        text fr_professional_category_id
        text fr_step_id
        text fr_work_type_id
        text has_payroll
        text has_trial_period
        text job_catalog_level_id
        text job_title
        text max_legal_yearly_hours
        text max_work_days_in_row
        text max_work_minutes_per_day
        text maximum_weekly_hours
        text min_rest_hours_in_row
        text min_rest_minutes_between_days
        text pt_contract_type_id
        text salary_amount
        text salary_frequency
        text starts_on
        text trial_period_ends_on
        text updated_at
        text working_hours
        text working_hours_frequency
        text working_time_percentage_in_cents
        text working_week_days
    }
    team_lead {
        text lead_id PK
        text team_id PK
    }
    team_employee {
        text employee_id PK
        text team_id PK
    }
    team {
        text id PK
        text avatar
        text company_id
        text description
        text name
    }
    company_holiday {
        text id PK
        text location_id FK
        text date
        text description
        text half_day
        text summary
    }
    folder {
        text id PK
        text parent_folder_id FK
        text active
        text company_id
        text name
        text space
    }
    task_assignee {
        text employee_id PK
        text task_id PK
    }
    task {
        text id PK
        text author_employee_id
        text company_id
        text completed_at
        text completed_by_id
        text content
        text created_at
        text due_on
        text name
        text status
        text updated_at
    }
    task_file {
        text id PK
        text task_id FK
        text content_type
        text created_at
        text filename
        text path
    }
    leave_type_allowance {
        text allowance_id PK
        text leave_type_id FK
    }
    leave_type {
        text id PK
        text accrues
        text active
        text allow_endless
        text approval_required
        text attachment
        text color
        text company_id
        text description
        text details_required
        text editable
        text half_days_units_enabled
        text identifier
        text is_attachment_mandatory
        text max_days_in_cents
        text min_days_in_cents
        text name
        text payable
        text restricted
        text translated_name
        text visibility
        text workable
    }
    supplement_employee_observation {
        text employee_observation PK
        text supplement_id PK
    }
    supplement {
        text id PK
        text contracts_compensation_id FK
        text contracts_taxonomy_id FK
        text employee_id FK
        text amount_in_cents
        text company_id
        text created_at
        text currency
        text description
        text effective_on
        text equivalent_minutes_in_cents
        text legal_entity_id
        text minutes_in_cents
        text payroll_policy_period_id
        text raw_minutes_in_cents
        text unit
        text updated_at
    }
    compensation {
        text id PK
        text contract_version_id FK
        text contracts_taxonomy_id FK
        text payroll_policy_id FK
        text amount
        text calculation
        text compensation_type
        text currency
        text description
        text first_payment_on
        text minimum_amount_of_hours
        text minimum_amount_of_hours_in_cents
        text recurrence
        text recurrence_count
        text starts_on
        text sync_with_supplements
        text time_condition
        text unit
    }
    location {
        text id PK
        text address_line_1
        text address_line_2
        text city
        text company_id
        text country
        text latitude
        text longitude
        text main
        text name
        text phone_number
        text postal_code
        text radius
        text siret
        text state
        text timezone
    }
    job_posting {
        text id PK
        text legal_entity_id FK
        text location_id FK
        text team_id FK
        text ats_company_id
        text company_id
        text contract_type
        text cover_letter_requirement
        text created_at
        text cv_requirement
        text description
        text hide_salary
        text phone_requirement
        text photo_requirement
        text preview_token
        text published_at
        text remote
        text salary_format
        text salary_from_amount_in_cents
        text salary_period
        text salary_to_amount_in_cents
        text schedule_type
        text status
        text title
        text url
        text workplace_type
    }
    workplace {
        text id PK
        text location_id FK
        text archived_at
        text name
    }
    legal_entities {
        text id PK
        text address_line_1
        text address_line_2
        text city
        text company_id
        text country
        text currency
        text legal_name
        text postal_code
        text state
        text tin
    }
    attendance {
        text id PK
        text employee_id FK
        text workplace_id FK
        text clock_in
        text clock_in_with_second
        text clock_out
        text company_id
        text created_at
        text date
        text half_day
        text in_location_accuracy
        text in_location_latitude
        text in_location_longitude
        text in_source
        text location_type
        text minutes
        text observation
        text out_location_accuracy
        text out_location_latitude
        text out_location_longitude
        text out_source
        text reference_date
        text time_settings_break_configuration_id
        text updated_at
        text workable
    }
    document }o--|| folder : "fk"
    document }o--|| employee : "fk"
    shift_management }o--|| employee : "fk"
    shift_management }o--|| location : "fk"
    taxonomy }o--|| legal_entities : "fk"
    employee }o--|| legal_entities : "fk"
    employee }o--|| employee : "fk"
    employee }o--|| employee : "fk"
    employee }o--|| location : "fk"
    ats_job_posting_id }o--|| candidate : "fk"
    leave }o--|| leave_type : "fk"
    leave }o--|| employee : "fk"
    contract }o--|| employee : "fk"
    team_lead }o--|| employee : "fk"
    team_lead }o--|| team : "fk"
    team_employee }o--|| employee : "fk"
    team_employee }o--|| team : "fk"
    company_holiday }o--|| location : "fk"
    folder }o--|| folder : "fk"
    task_assignee }o--|| employee : "fk"
    task_assignee }o--|| task : "fk"
    task_file }o--|| task : "fk"
    leave_type_allowance }o--|| leave_type : "fk"
    supplement_employee_observation }o--|| supplement : "fk"
    supplement }o--|| taxonomy : "fk"
    supplement }o--|| compensation : "fk"
    supplement }o--|| employee : "fk"
    compensation }o--|| taxonomy : "fk"
    compensation }o--|| contract : "fk"
    compensation }o--|| policies : "fk"
    job_posting }o--|| team : "fk"
    job_posting }o--|| legal_entities : "fk"
    job_posting }o--|| location : "fk"
    workplace }o--|| location : "fk"
    attendance }o--|| workplace : "fk"
    attendance }o--|| employee : "fk"
