erDiagram
    user_activity_sms_reply {
        text id PK
        text member_id FK
        text receiver_id FK
        text comment_type
        text content
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_type
    }
    group_field_option {
        text option PK
        text group_field_id PK
        text group_id PK
    }
    group_field {
        text id PK
        text group_id PK
        text editable
        text name
        text other_option_flag
        text placeholder
        text required
        text type
        text unique_name
    }
    group_member_posting_permission {
        text permission PK
        text group_id PK
    }
    groups {
        text id PK
        text parent_group FK
        text primary_admin_user_id FK
        text created_at
        text default_emails_frequency
        text email
        text email_comments_to_all
        text hidden_email
        text logo_url
        text members_count
        text members_visible
        text mini_thumb_url
        text name
        text posts_moderation
        text privacy
        text requires_approval
        text small_thumb_url
        text thumb_url
        text updated_at
        text url
    }
    user_activity_view {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_type
    }
    user_activity_pending_post {
        text id PK
        text group_id FK
        text receiver_id FK
        text created_at
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_name
        text target_type
    }
    user_activity_vote {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text created_at
        text deleted
        text feed_type
        text poll_name
        text post_id
        text post_type
    }
    user_activity_rsvp {
        text id PK
        text group_id FK
        text member_id FK
        text created_at
        text deleted
        text event_id
        text event_name
        text feed_type
        text post_id
        text post_type
        text status
        text target_id
        text target_type
    }
    user_activity_reaction {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text content
        text created_at
        text deleted
        text feed_type
        text item_id
        text item_type
        text post_id
        text post_name
        text post_type
    }
    user_activity_comment {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text comment_type
        text content
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
    }
    user_activity {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text conversation_id
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_name
        text target_type
        text type
    }
    user_activity_mention {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text content
        text created_at
        text deleted
        text feed_type
        text mention_object
        text mentioned
        text post_id
        text post_name
        text post_type
    }
    user_activity_add_member {
        text id PK
        text group_id FK
        text member_id FK
        text created_at
        text deleted
        text members_count
    }
    user_activity_post_approved {
        text id PK
        text group_id FK
        text receiver_id FK
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_name
        text target_type
    }
    user_activity_join_group {
        text id PK
        text group_id FK
        text member_id FK
        text created_at
        text deleted
    }
    user_activity_conversation {
        text id PK
        text initiator_id FK
        text member_id FK
        text participant_id FK
        text conversation_id
        text created_at
        text deleted
    }
    user_activity_pending_applicant {
        text id PK
        text group_id FK
        text member_id FK
        text created_at
        text deleted
    }
    user_activity_post_message {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text comment_type
        text content
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_type
    }
    user_activity_post {
        text id PK
        text group_id FK
        text member_id FK
        text receiver_id FK
        text content
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_name
        text target_type
    }
    user_activity_comment_reply {
        text id PK
        text group_id FK
        text member_id FK
        text comment_type
        text content
        text created_at
        text deleted
        text feed_type
        text post_id
        text post_name
        text post_type
        text target_id
        text target_type
    }
    user_group {
        text id PK
        text user_id PK
        text is_admin
        text last_invited_in
        text status
    }
    user_custom_field {
        text name PK
        text users_id PK
        text value
    }
    users {
        text id PK
        text avatar_mini_thumb_url
        text avatar_small_thumb_url
        text avatar_thumb_url
        text avatar_url
        text created_at
        text email
        text first_name
        text is_registered
        text last_name
        text name
        text updated_at
    }
    user_activity_sms_reply }o--|| users : "fk"
    user_activity_sms_reply }o--|| users : "fk"
    group_field_option }o--|| group_field : "fk"
    group_field_option }o--|| group_field : "fk"
    group_field }o--|| groups : "fk"
    group_member_posting_permission }o--|| groups : "fk"
    groups }o--|| users : "fk"
    groups }o--|| groups : "fk"
    user_activity_view }o--|| users : "fk"
    user_activity_view }o--|| groups : "fk"
    user_activity_view }o--|| users : "fk"
    user_activity_pending_post }o--|| groups : "fk"
    user_activity_pending_post }o--|| users : "fk"
    user_activity_vote }o--|| users : "fk"
    user_activity_vote }o--|| groups : "fk"
    user_activity_vote }o--|| users : "fk"
    user_activity_rsvp }o--|| groups : "fk"
    user_activity_rsvp }o--|| users : "fk"
    user_activity_reaction }o--|| users : "fk"
    user_activity_reaction }o--|| groups : "fk"
    user_activity_reaction }o--|| users : "fk"
    user_activity_comment }o--|| users : "fk"
    user_activity_comment }o--|| groups : "fk"
    user_activity_comment }o--|| users : "fk"
    user_activity }o--|| users : "fk"
    user_activity }o--|| groups : "fk"
    user_activity }o--|| users : "fk"
    user_activity_mention }o--|| users : "fk"
    user_activity_mention }o--|| groups : "fk"
    user_activity_mention }o--|| users : "fk"
    user_activity_add_member }o--|| groups : "fk"
    user_activity_add_member }o--|| users : "fk"
    user_activity_post_approved }o--|| users : "fk"
    user_activity_post_approved }o--|| groups : "fk"
    user_activity_join_group }o--|| users : "fk"
    user_activity_join_group }o--|| groups : "fk"
    user_activity_conversation }o--|| users : "fk"
    user_activity_conversation }o--|| users : "fk"
    user_activity_conversation }o--|| users : "fk"
    user_activity_pending_applicant }o--|| groups : "fk"
    user_activity_pending_applicant }o--|| users : "fk"
    user_activity_post_message }o--|| users : "fk"
    user_activity_post_message }o--|| groups : "fk"
    user_activity_post_message }o--|| users : "fk"
    user_activity_post }o--|| users : "fk"
    user_activity_post }o--|| groups : "fk"
    user_activity_post }o--|| users : "fk"
    user_activity_comment_reply }o--|| groups : "fk"
    user_activity_comment_reply }o--|| users : "fk"
    user_group }o--|| groups : "fk"
    user_group }o--|| users : "fk"
    user_custom_field }o--|| users : "fk"
