erDiagram
    keyword_site_report_by_site {
        text country PK
        text date PK
        text device PK
        text query PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    keyword_page_report {
        text country PK
        text date PK
        text device PK
        text page PK
        text query PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    page_report {
        text country PK
        text date PK
        text device PK
        text page PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    hourly_keyword_site_report_by_site {
        text country PK
        text device PK
        timestamp hour PK
        text query PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    sitemap {
        timestamp last_downloaded PK
        timestamp last_submitted PK
        text path PK
        text site PK
        text type PK
        bigint indexed
        bigint submitted
    }
    hourly_keyword_site_report_by_page {
        text country PK
        text device PK
        timestamp hour PK
        text query PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    hourly_site_report_by_site {
        text country PK
        text device PK
        timestamp hour PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    hourly_keyword_page_report {
        text country PK
        text device PK
        timestamp hour PK
        text page PK
        text query PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    hourly_page_report {
        text country PK
        text device PK
        timestamp hour PK
        text page PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    site_report_by_site {
        text country PK
        text date PK
        text device PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    hourly_site_report_by_page {
        text country PK
        text device PK
        timestamp hour PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    keyword_site_report_by_page {
        text country PK
        text date PK
        text device PK
        text query PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
    site_report_by_page {
        text country PK
        text date PK
        text device PK
        text search_type PK
        text site PK
        double_precision clicks
        double_precision ctr
        double_precision impressions
        double_precision position
    }
