erDiagram
    section_faq {
        text faq_id PK
        text section_id PK
    }
    section {
        text id PK
        text app_id FK
        text created_at
        text icon
        text image
        text title
    }
    platform {
        text id PK
        text app_id FK
        text type
    }
    app {
        text id PK
        text logo
        text publish_id
        text title
    }
    analytic_faq {
        text _fivetran_id PK
        text app_id FK
        text section_id FK
        text dislike
        text id
        text languages
        text last_updated_at
        text likes
        text platform_type
        text row_id
        text section_title
        text time
        text title
        text view
    }
    data_portability {
        text hs_request_id PK
        text encrypted_zip
        text eta
        text external_request_id
        text hs_data_url
        text reason
        text request_app_publish_id
        text request_external_request_id
        text request_property
        text request_value
        text status
        text url_valid_until
    }
    agent {
        text id PK
        text avatar
        text email
        text last_login_at
        text name
        text nickname
        text role
        text team_name
    }
    issue_tag {
        text tag_name PK
        text issue_id PK
    }
    private_note_email {
        text email PK
        text issue_id PK
        text private_note_author_id PK
    }
    private_note {
        text author_id PK
        text issue_id PK
        text author_name
        text body
        text created_at
        text phone_number
    }
    message_author_email {
        text email PK
        text message_author_id PK
        text message_id PK
    }
    message_intent_label {
        text label_id PK
        text message_author_id PK
        text message_id PK
    }
    message_attachment {
        text _fivetran_id PK
        text message_author_id FK
        text message_id FK
        text content_type
        text file_name
        text size
        text url
    }
    message {
        text author_id PK
        text id PK
        text issue_id FK
        text attachment_content_type
        text attachment_file_name
        text attachment_size
        text attachment_url
        text author_name
        text author_phone_number
        text body
        text created_at
        text origin
    }
    issue {
        text id PK
        text app_publish_id FK
        text assignee_id FK
        text queue_id FK
        text app_id
        text author_email
        text author_name
        text changed_at
        text created_at
        text current_predict_label
        text domain
        text feedback_comment
        text feedback_rating
        text hs_user_id
        text intent_group_id
        text intent_group_name
        text intent_id
        text intent_name
        text original_predict_label
        text redacted
        text state
        text title
        text updated_at
    }
    analytic_custom_bot {
        text id PK
        text agent_interruption
        text automation_interruption
        text avg_completion_time
        text cifs_mapped
        text completion
        text inbound_messages
        text invocation
        text issues_rejected
        text issues_reopened
        text issues_resolved
        text name
        text outbound_message
        text row_id
        text status
        text time
    }
    queue {
        text id PK
        text active
        text auto_assignment_enabled
        text name
    }
    analytic_open_issue {
        text _fivetran_id PK
        text app_id FK
        text languages
        text open_issues
        text platform_type
        text row_id
        text time
    }
    analytic_agent_group {
        text type PK
        text analytic_agent_id PK
        text analytic_agent_time PK
    }
    analytic_agent {
        text id PK
        text time PK
        text accepted_resolution
        text available_time
        text avg_csat
        text avg_outbound_messages_per_resolved
        text avg_tter
        text avg_ttfr
        text avg_ttr
        text csat_1_count
        text csat_2_count
        text csat_3_count
        text csat_4_count
        text csat_5_count
        text csat_count
        text duplicates_marked
        text email
        text inbound_phone_call
        text issue_assign
        text issue_reject
        text issue_resolve
        text loggedin_time
        text name
        text online_time
        text outbound_message
        text outbound_phone_call
        text rejected_resolution
        text reopen
        text row_id
        text team_id
        text team_name
        text tter_count
        text ttfr_count
        text ttr_count
    }
    analytic_custom_bot_step {
        text id PK
        text custom_bot_id
        text custom_bot_name
        text invocation
        text name
        text row_id
        text skip
        text time
        text type
    }
    analytic_support {
        text _fivetran_id PK
        text app_id FK
        text avg_csat
        text avg_tter
        text avg_ttfr
        text avg_ttr
        text conversations_started
        text csat_1_count
        text csat_2_count
        text csat_3_count
        text csat_4_count
        text csat_5_count
        text csat_count
        text inbound_message
        text issue_assign
        text issues_created
        text issues_first_responded
        text languages
        text outbound_message
        text platform_type
        text rejects_by_agent
        text rejects_by_automation
        text reopen
        text resolves_by_agent
        text resolves_by_automation
        text row_id
        text time
        text tter_count
        text ttfr_count
        text ttr_count
        text widget_load
        text widget_opens_existing_issue
        text widget_opens_no_existing_issue
    }
    translation_lg_stag {
        text stag PK
        text faq_id PK
    }
    faq_issue_tag {
        text tag_name PK
        text faq_id PK
    }
    platform_type {
        text type PK
        text faq_id PK
    }
    linked_faq {
        text id PK
        text faq_id PK
    }
    faq {
        text id PK
        text app_id FK
        text publish_id FK
        text section_id FK
        text created_at
        text last_updated_by
        text published
        text slug
        text updated_at
    }
    translation_lg {
        text _fivetran_id PK
        text faq_id FK
        text body
        text content_updated_at
        text title
        text translation_type
    }
    analytic_issue_tag {
        text tag_name PK
        text analytic_issue_id PK
    }
    analytic_issue {
        text id PK
        text assignee_id FK
        text accepted_resolution
        text agent_outbound_message
        text app_id
        text automation_category_by_outbound_message
        text automation_subcategory_by_outbound_message
        text avg_tter
        text created_at
        text current_queue_id
        text current_queue_name
        text custombot_outbound_message
        text email
        text external_user_id
        text feedback_at
        text feedback_comment
        text feedback_rating
        text first_assigned_at
        text first_responded_at
        text handling_time
        text holding_time
        text inbound_message
        text inbound_phone_call
        text initial_queue_id
        text initial_queue_name
        text is_from_phone_deflection
        text languages
        text last_resolved_at
        text original_issue_id
        text other_outbound_message
        text outbound_message
        text outbound_phone_call
        text phone_escalation
        text platform_type
        text rejected_resolution
        text reopen
        text row_id
        text state
        text tter_count
        text tter_sum
        text ttfa
        text ttfr
        text ttr
        text updated_at
    }
    section_faq }o--|| section : "fk"
    section }o--|| app : "fk"
    platform }o--|| app : "fk"
    analytic_faq }o--|| section : "fk"
    analytic_faq }o--|| app : "fk"
    issue_tag }o--|| issue : "fk"
    private_note_email }o--|| private_note : "fk"
    private_note_email }o--|| issue : "fk"
    private_note }o--|| issue : "fk"
    message_author_email }o--|| message : "fk"
    message_author_email }o--|| message : "fk"
    message_intent_label }o--|| message : "fk"
    message_intent_label }o--|| message : "fk"
    message_attachment }o--|| message : "fk"
    message_attachment }o--|| message : "fk"
    message }o--|| issue : "fk"
    issue }o--|| app : "fk"
    issue }o--|| queue : "fk"
    issue }o--|| agent : "fk"
    analytic_open_issue }o--|| app : "fk"
    analytic_agent_group }o--|| analytic_agent : "fk"
    analytic_agent_group }o--|| analytic_agent : "fk"
    analytic_custom_bot_step }o--|| analytic_custom_bot : "fk"
    analytic_support }o--|| app : "fk"
    translation_lg_stag }o--|| faq : "fk"
    faq_issue_tag }o--|| faq : "fk"
    platform_type }o--|| faq : "fk"
    linked_faq }o--|| faq : "fk"
    faq }o--|| section : "fk"
    faq }o--|| app : "fk"
    faq }o--|| app : "fk"
    translation_lg }o--|| faq : "fk"
    analytic_issue_tag }o--|| analytic_issue : "fk"
    analytic_issue }o--|| agent : "fk"
