erDiagram
    employee_work_history {
        text id PK
        text employee_id PK
        text reports_to_id FK
        text active_effective_date
        text can_be_deleted
        text change_changed_by
        text change_changed_by_id
        text change_reason
        text creation_date
        jsonb custom_columns
        text department
        text effective_date
        text end_effective_date
        text is_current
        text modification_date
        text reports_to_display_name
        text reports_to_email
        text reports_to_first_name
        text reports_to_surname
        text site
        text site_id
        text title
        text work_change_type
    }
    employee {
        text id PK
        text manager FK
        text reports_to_id_in_company FK
        text second_level_manager FK
        text about
        text actual_working_pattern
        text address_1
        text address_2
        text adress_active_effective_date
        text age
        text age_risk_indicator
        text at_risk_counter
        text avatar
        text avatar_url
        text birth_date
        text city
        text company_car_amount
        text company_id
        text contract
        text country
        text cover_image_url
        text creation_date_time
        text current_active_status_start_date
        text days_of_previous_service
        text department
        text direct_report
        text display_name
        text duration_of_employment
        text email
        text employee_id_in_company
        text employment_active_effective_date
        text entitlement_lunch_voucher_amount
        text ethnicity
        text family_status
        text financial_bank_name
        text first_name
        text food_preferences
        text fte
        text full_address
        text full_name
        jsonb hobbies
        text honorific
        text hours_in_day_not_worked
        text indirect_report
        text is_manager
        text is_manager_risk_indicator
        text kids_risk_indicator
        text legal_gender
        text legal_sex
        text lifecycle_status
        text line_1
        text line_2
        text low_risk_counter
        text manager_tenure_risk_indicator
        text mobile_phone
        text monthly_payment
        text nationality
        text num_of_direct_reports_risk_indicator
        text num_with_same_title_risk_indicator
        text number_of_kid
        text original_start_date
        text pay_frequency
        text pay_period
        text payment_currency
        text post_code
        text postal_code
        text private_email
        text probation_end_date
        text recent_manager_change_risk_indicator
        text reports_to
        text salary_active_effective_date
        text season_ticket_loan_amount
        text second_name
        text short_birth_date
        text short_start_date
        text site
        text site_city
        text site_country
        text site_id
        text site_state
        text site_working_pattern
        text some_risk_counter
        text spouse_birth_date
        text spouse_first_name
        text spouse_gender
        text spouse_short_birth_date
        text spouse_surname
        text ssn
        text ssn_serial_number
        text start_date
        text status
        text superpowers
        text surname
        text team_recent_turnover_risk_indicator
        text team_size_risk_indicator
        text tenure_duration
        text tenure_duration_year
        text tenure_rank_risk_indicator
        text tenure_year
        text time_off_frequency_risk_indicator
        text time_since_last_salary_change
        text title
        text usa_state
        text veteran_status
        text weekly_hour
        text work_active_effective_date
        text work_mobile
        text work_phone
        text yearly_payment
        text years_of_service
        text years_with_current_title_risk_indicator
        text years_with_recent_salary_risk_indicator
    }
    employee_life_cycle_history {
        text id PK
        text employee_id PK
        text can_be_deleted
        text change_changed_by
        text change_changed_by_id
        text change_reason
        text creation_date
        jsonb custom_columns
        text effective_date
        text employee_status
        text end_effective_date
        text is_current
        text leave_reason
        text modification_date
        text reason_type
        text status
    }
    employee_variable_payment {
        text id PK
        text employee_id PK
        text amount_currency
        double_precision amount_value
        double_precision company_percent
        double_precision department_percent
        text effective_date
        text individual_percent
        text payment_period
        text reason
        text type
    }
    custom_table_column {
        text id PK
        text custom_table_id PK
        text list_id FK
        text description
        text mandatory
        text name
        text type
    }
    custom_table {
        text id PK
        text category
        text description
        text name
    }
    employee_salary_history {
        text id PK
        text employee_id PK
        text active_effective_date
        text base_currency
        double_precision base_value
        text can_be_deleted
        text change_changed_by
        text change_changed_by_id
        text change_reason
        text creation_date
        jsonb custom_columns
        text effective_date
        text end_effective_date
        text is_current
        text modification_date
        text pay_frequency
        text pay_period
    }
    task {
        text id PK
        text description
        text set
        text title
    }
    employee_training {
        text id PK
        text employee_id PK
        text cost_currency
        double_precision cost_value
        text description
        text document_id
        text effective_date
        text end_date
        text frequency
        text name
        text reason
        text start_date
        text status
    }
    employee_out_of_office {
        text request_id PK
        text employee_id PK
        text date
        text end_date
        text end_portion
        text hours_on_date
        text minutes
        text policy_type
        text policy_type_display_name
        text start_date
        text start_portion
        text status
        text type
    }
    employee_equity_grant {
        text id PK
        text employee_id PK
        text consent_number
        text effective_date
        text equity_type
        text exercise_price_currency
        double_precision exercise_price_value
        text grant_date
        text grant_number
        text grant_status
        text grant_type
        text option_expiration
        text quantity
        text reason
        text vesting_commencement_date
        text vesting_schedule
        text vesting_term
    }
    company_field {
        text id PK
        text list_id FK
        text category
        text description
        text historical
        text json_path
        text name
        text type
    }
    company_list {
        text name PK
    }
    company {
        text id PK
        text company_list_name PK
        text archived
        jsonb children
        text name
        text type
        text value
    }
    employment_history {
        text id PK
        text employee_id PK
        text active_effective_date
        text calendar_id
        text calendar_name
        text can_be_deleted
        text change_changed_by
        text change_changed_by_id
        text change_reason
        text contract
        text creation_date
        jsonb custom_columns
        text effective_date
        text end_effective_date
        text flsa_code
        text fte
        text is_current
        text modification_date
        text salary_pay_type
        text site_working_pattern_friday
        text site_working_pattern_hours_per_day
        text site_working_pattern_monday
        text site_working_pattern_saturday
        text site_working_pattern_sunday
        text site_working_pattern_thursday
        text site_working_pattern_tuesday
        text site_working_pattern_wednesday
        text site_working_pattern_working_pattern_type
        text type
        text weekly_hours
        text working_pattern
    }
    employee_work_history }o--|| employee : "fk"
    employee_work_history }o--|| employee : "fk"
    employee }o--|| employee : "fk"
    employee }o--|| employee : "fk"
    employee }o--|| employee : "fk"
    employee_life_cycle_history }o--|| employee : "fk"
    employee_variable_payment }o--|| employee : "fk"
    custom_table_column }o--|| company_list : "fk"
    custom_table_column }o--|| custom_table : "fk"
    employee_salary_history }o--|| employee : "fk"
    employee_training }o--|| employee : "fk"
    employee_out_of_office }o--|| employee : "fk"
    employee_equity_grant }o--|| employee : "fk"
    company_field }o--|| company_list : "fk"
    company }o--|| company_list : "fk"
    employment_history }o--|| employee : "fk"
