erDiagram
    team {
        text id PK
        text name
        text status
    }
    placement {
        text id PK
        text placement
        text total_imp
    }
    media_partner {
        text partner_id PK
        text id FK
        text media_partner
        text total_imp
    }
    campaign {
        text id PK
        text campaign
        text total_imp
    }
    report {
        text date PK
        text team_id PK
        text campaign_id PK
        text placement_id PK
        text id FK
        text ad_distribution_measured_rate
        text ad_distribution_net_measured_rate
        text ad_distribution_net_unmeasured_rate
        text ad_distribution_not_viewable_rate
        text ad_distribution_unmeasured_rate
        text ad_distribution_viewable_rate
        text ad_server_placement_id
        text adult_ads
        text alcohol_ads
        text auto_play_ads
        text block_rate
        text blocked_ads
        text blocked_invalid_traffic
        text blocking_status
        text bots_ads
        text bots_rate
        text brand_safety_risk_
        text brand_safety_risk_ads
        text brand_suitability_fail_
        text brand_suitability_failed_ads
        text click_to_play_ads
        text completed_ads
        text completion_rate
        text custom_keywords_exclusion_list_ads
        text custom_keywords_exclusion_list_rate
        text custom_url_app_exclusion_list_ads
        text custom_url_exclusion_list_rate
        text domain_spoofing_ads
        text domain_spoofing_rate
        text drugs_ads
        text eligible_ads_for_invalid_traffic_detection
        text eligible_ads_for_quality_impressions
        text eligible_ads_for_viewability_measurement
        text eligible_impressions_for_viewability
        text eligible_rate_for_invalid_traffic_detection
        text eligible_rate_for_quality_impressions
        text fail_rate
        text failed_ads
        text failed_brand_safety_ads
        text first_quartile_ads
        text first_quartile_rate
        text general_invalid_traffic_ads
        text general_invalid_traffic_rate
        text gross_eligible_ads
        text gross_eligible_impressions
        text gross_measured_ads
        text gross_measured_impressions
        text gross_measured_rate
        text gross_measured_rate_impressions
        text gross_unmeasured_ads
        text gross_unmeasured_impressions
        text gross_unmeasured_rate_impressions
        text hate_speech_ads
        text hidden_ads
        text hidden_ads_rate
        text illegal_downloads_ads
        text impression_distribution_measured_rate
        text impression_distribution_net_measured_rate
        text impression_distribution_net_not_viewable_rate
        text impression_distribution_net_unmeasured_rate
        text impression_distribution_net_viewable_rate
        text impression_distribution_not_viewable_rate
        text impression_distribution_unmeasured_rate
        text impression_distribution_viewable_rate
        text incentivized_browsing_ads
        text incentivized_browsing_rate
        text invalid_traffic
        text invalid_traffic_ads
        text invalid_traffic_rate
        text invisible_url_
        text invisible_url_ads
        text measured_ads
        text measured_impressions
        text measured_rate
        text net_ad_distribution_not_viewable_rate
        text net_ad_distribution_viewable_rate
        text net_eligible_ads_for_viewability_measurement
        text net_eligible_impressions_for_viewability_measurement
        text net_impressions
        text net_measured_ads
        text net_measured_impressions
        text net_measured_rate
        text net_measured_rate_impressions
        text net_not_viewable_ads
        text net_not_viewable_impressions
        text net_not_viewable_rate
        text net_not_viewable_rate_impressions
        text net_unmeasured_ads
        text net_unmeasured_impressions
        text net_unmeasured_rate
        text net_unmeasured_rate_impressions
        text net_viewable_impressions
        text net_viewable_rate
        text net_viewable_rate_impressions
        text non_quality_ads
        text non_quality_blocked_ads
        text non_quality_failed_brand_safety
        text non_quality_ivt
        text non_quality_not_viewable
        text non_quality_out_of_geo
        text non_quality_rate
        text not_viewable_ads
        text not_viewable_impressions
        text not_viewable_rate
        text not_viewable_rate_impressions
        text of_adult_ads
        text of_alcohol_ads
        text of_drugs_ads
        text of_hate_speech_ads
        text of_illegal_downloads_ads
        text of_invalid_traffic_blocked
        text of_invalid_traffic_unblocked
        text of_offensive_language_ads
        text of_violence
        text offensive_language_ads
        text out_of_geo_
        text out_of_geo_ads
        text pass_rate
        text passed_ads
        text placement_description
        text proxy_server_ads
        text proxy_servers_rate
        text quality_impressions
        text quality_impressions_rate
        text reduced_value_inventory_ads
        text reduced_value_inventory_rate
        text second_quartile_ads
        text second_quartile_rate
        text see_through_ads
        text see_through_rate
        text sophisticated_invalid_traffic_ads
        text sophisticated_invalid_traffic_rate
        text target_language_mismatch_
        text target_language_mismatch_ads
        text third_quartile_ads
        text third_quartile_rate
        text total_eligible_ads_for_brand_safety
        text total_net_impressions
        text total_rendered_impressions
        text total_tracked_ads
        text unblocked_invalid_traffic
        text unknown_player_state_ads
        text unmeasured_ads
        text unmeasured_impressions
        text unmeasured_rate
        text valid_traffic
        text valid_traffic_rate
        text valid_video_ads
        text valid_viewable_video_ads
        text viewable_completed_impressions
        text viewable_completion_rate
        text viewable_first_quartile_impressions
        text viewable_first_quartile_rate
        text viewable_impressions
        text viewable_rate
        text viewable_rate_impressions
        text viewable_second_quartile_impressions
        text viewable_second_quartile_rate
        text viewable_third_quartile_impressions
        text viewable_third_quartile_rate
        text violence_ads
    }
    placement }o--|| team : "fk"
    media_partner }o--|| team : "fk"
    campaign }o--|| team : "fk"
    report }o--|| campaign : "fk"
    report }o--|| placement : "fk"
    report }o--|| team : "fk"
