erDiagram
    app_store_app_version_review {
        text app_version_id PK
        text review_id PK
    }
    app_store_discovery_and_engagement_detailed_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text campaign
        integer counts
        text device
        text engagement_type
        text event
        text page_title
        text page_type
        text platform_version
        text source_info
        text source_type
        text territory
        integer unique_counts
    }
    sales_first_annual_detailed {
        text _fivetran_id PK
        integer vendor_number PK
        bigint app_id PK
        text app_name
        text channel
        integer first_annual_installs
        text install_type
        text os_version
        text requested_report_date
        text territory
        integer total_installs
    }
    sales_subscription_offer_code_redemption {
        text _fivetran_id PK
        integer vendor_number PK
        bigint app_apple_id PK
        text app_name
        text date
        text offer_code
        text offer_reference_name
        integer redemptions
        text requested_report_date
        bigint subscription_apple_id
        text subscription_name
        text territory
    }
    app_store_app {
        bigint id PK
        text content_rights_declaration
        text name
        text primary_locale
        text subscription_status_url
        text subscription_status_url_for_sandbox
        text subscription_status_url_version
        text subscription_status_url_version_for_sandbox
        boolean was_made_for_kids
    }
    app_session_standard_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_download_date
        text app_version
        text device
        text page_type
        text platform_version
        integer sessions
        text source_type
        text territory
        integer total_session_duration
        integer unique_devices
    }
    app_store_purchase_standard_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_download_date
        text content_apple_identifier
        text content_name
        text device
        text page_type
        integer paying_users
        text payment_method
        text platform_version
        text pre_order
        double_precision proceeds_in_usd
        text purchase_type
        integer purchases
        double_precision sales_in_usd
        text source_type
        text territory
    }
    app_store_download_standard_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_version
        integer counts
        text device
        text download_type
        text page_type
        text platform_version
        text pre_order
        text source_type
        text territory
    }
    sales_subscription_event_summary {
        text _fivetran_id PK
        integer vendor_number PK
        bigint app_apple_id
        text app_name
        text cancellation_reason
        text client
        integer consecutive_paid_periods
        text country
        integer days_before_canceling
        integer days_canceled
        text device
        text event
        text event_date
        text marketing_opt_in
        text marketing_opt_in_duration
        text original_start_date
        integer paid_service_days_recovered
        text preserved_pricing
        bigint previous_subscription_apple_id
        text previous_subscription_name
        text proceeds_reason
        text promotional_offer_id
        text promotional_offer_name
        integer quantity
        text requested_report_date
        text standard_subscription_duration
        text state
        bigint subscription_apple_id
        bigint subscription_group_id
        text subscription_name
        text subscription_offer_duration
        text subscription_offer_type
    }
    financial_detail {
        text _fivetran_id PK
        text country_code PK
        integer vendor_number PK
        bigint app_id PK
        text country_of_sale
        text customer_currency
        double_precision customer_price
        text developer_name
        text end_date
        double_precision extended_partner_share
        text filename
        text order_type
        double_precision partner_share
        text partner_share_currency
        text product_type_identifier
        text promo_code
        integer quantity
        text region
        text requested_report_date
        text sale_or_return
        text settlement_date
        text sku
        text start_date
        text title
        text transaction_date
    }
    app_store_installation_and_deletion_detailed_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_download_date
        text app_version
        text campaign
        integer counts
        text device
        text download_type
        text event
        text page_title
        text page_type
        text platform_version
        text source_info
        text source_type
        text territory
        integer unique_devices
    }
    sales_summary_daily {
        text _fivetran_id PK
        integer vendor_number PK
        bigint app_id PK
        text begin_date
        text category
        text client
        text cmb
        text country_code
        text currency_of_proceeds
        text customer_currency
        double_precision customer_price
        text developer
        double_precision developer_proceeds
        text device
        text end_date
        text order_type
        text parent_identifier
        text period
        text preserved_pricing
        text proceeds_reason
        text product_type_identifier
        text promo_code
        text provider
        text provider_country
        text requested_report_date
        text sku
        text subscription
        text supported_platforms
        text title
        double_precision units
        text version
    }
    sales_subscription_summary {
        text _fivetran_id PK
        integer vendor_number PK
        integer active_free_trial_introductory_offer_subscriptions
        integer active_pay_as_you_go_introductory_offer_subscriptions
        integer active_pay_up_front_introductory_offer_subscriptions
        integer active_standard_price_subscriptions
        bigint app_apple_id
        text app_name
        integer billing_retry
        text client
        text country
        text customer_currency
        double_precision customer_price
        text date
        double_precision developer_proceeds
        text device
        integer free_trial_offer_code_subscriptions
        integer free_trial_promotional_offer_subscriptions
        integer free_trial_win_back_offers
        integer grace_period
        integer marketing_opt_ins
        integer pay_as_you_go_offer_code_subscriptions
        integer pay_as_you_go_promotional_offer_subscriptions
        integer pay_as_you_go_win_back_offers
        integer pay_up_front_offer_code_subscriptions
        integer pay_up_front_promotional_offer_subscriptions
        integer pay_up_front_win_back_offers
        text preserved_pricing
        text proceeds_currency
        text proceeds_reason
        text promotional_offer_id
        text requested_report_date
        text standard_subscription_duration
        text state
        integer subscribers
        bigint subscription_apple_id
        bigint subscription_group_id
        text subscription_name
        text subscription_offer_name
    }
    app_session_detailed_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_download_date
        text app_version
        text campaign
        text device
        text page_title
        text page_type
        text platform_version
        integer sessions
        text source_info
        text source_type
        text territory
        integer total_session_duration
        integer unique_devices
    }
    sales_win_back_eligibility {
        text _fivetran_id PK
        integer vendor_number PK
        bigint app_apple_id PK
        text app_name
        integer churned_subscription_count
        text has_previously_redeemed_win_back_offer
        integer paid_subscription_tenure
        text requested_report_date
        text standard_subscription_duration
        bigint subscription_apple_id
        bigint subscription_group_id
        text subscription_name
        text territory
        integer time_since_last_subscribed
        integer time_since_last_win_back_offer
    }
    app_store_download_detailed_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_version
        text campaign
        integer counts
        text device
        text download_type
        text page_title
        text page_type
        text platform_version
        text pre_order
        text source_info
        text source_type
        text territory
    }
    app_store_installation_and_deletion_standard_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_download_date
        text app_version
        integer counts
        text device
        text download_type
        text event
        text page_type
        text platform_version
        text source_type
        text territory
        integer unique_devices
    }
    app_store_purchase_detailed_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_download_date
        text campaign
        text content_apple_identifier
        text content_name
        text device
        text page_title
        text page_type
        integer paying_users
        text payment_method
        text platform_version
        text pre_order
        double_precision proceeds_in_usd
        text purchase_type
        integer purchases
        double_precision sales_in_usd
        text source_info
        text source_type
        text territory
    }
    sales_pre_order_summary {
        text _fivetran_id PK
        integer vendor_number PK
        bigint app_id PK
        double_precision canceled
        text category
        text client
        text country_code
        double_precision cumulative_canceled
        double_precision cumulative_ordered
        text developer
        text device
        text end_date
        double_precision ordered
        text pre_order_end_date
        text pre_order_start_date
        text provider
        text provider_country
        text requested_report_date
        text sku
        text start_date
        text supported_platforms
        text title
    }
    app_store_browser_choice_screen_engagement_report {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        integer counts
        text device
        text event
        text platform_version
        text territory
        integer unique_devices
    }
    financial {
        text _fivetran_id PK
        text country_code PK
        integer vendor_number PK
        bigint app_id PK
        text artist_show_developer_author
        text country_of_sale
        text customer_currency
        double_precision customer_price
        text end_date
        double_precision extended_partner_share
        text filename
        text grid
        text isan_other_identifier
        text isrc_isbn
        text label_studio_network_developer_publisher
        double_precision partner_share
        text partner_share_currency
        text pre_order_flag
        text product_type_identifier
        text promo_code
        integer quantity
        text requested_report_date
        text sale_or_return
        text start_date
        text title
        text upc
        text vendor_identifier
    }
    app_store_review {
        text id PK
        bigint app_id PK
        text body
        timestamp created_date
        integer rating
        text reviewer_nickname
        text territory
        text title
    }
    app_store_app_version {
        text id PK
        bigint app_id FK
        text app_store_state
        text app_version_state
        text copyright
        timestamp created_date
        boolean downloadable
        timestamp earliest_release_date
        text platform
        text release_type
        text review_type
        text uses_idfa
        text version_string
    }
    app_store_discovery_and_engagement_standard_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        integer counts
        text device
        text engagement_type
        text event
        text page_type
        text platform_version
        text source_type
        text territory
        integer unique_counts
    }
    app_crash_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text app_version
        integer crashes
        text device
        text platform_version
        integer unique_devices
    }
    app_store_pre_order_detailed_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text campaign
        text device
        text page_title
        text page_type
        text platform_version
        integer pre_order_canceled
        text pre_order_end_date
        integer pre_order_placed
        text pre_order_start_date
        text source_info
        text source_type
        text territory
    }
    sales_subscriber_detailed {
        text _fivetran_id PK
        integer vendor_number PK
        bigint app_apple_id
        text app_name
        text client
        text country
        text customer_currency
        double_precision customer_price
        double_precision developer_proceeds
        text device
        text event_date
        text introductory_price_type
        text marketing_opt_in_duration
        text preserved_pricing
        text proceeds_currency
        text proceeds_reason
        text promotional_offer_id
        text purchase_date
        text refund
        text requested_report_date
        text standard_subscription_duration
        bigint subscriber_id
        text subscriber_id_reset
        bigint subscription_apple_id
        bigint subscription_group_id
        text subscription_name
        text subscription_offer_duration
        text subscription_offer_name
        integer units
    }
    app_store_pre_order_standard_daily {
        text _fivetran_id PK
        text date PK
        bigint app_id PK
        text device
        text page_type
        text platform_version
        integer pre_order_canceled
        text pre_order_end_date
        integer pre_order_placed
        text pre_order_start_date
        text source_type
        text territory
    }
    app_store_app_version_review }o--|| app_store_app_version : "fk"
    app_store_app_version_review }o--|| app_store_review : "fk"
    app_store_discovery_and_engagement_detailed_daily }o--|| app_store_app : "fk"
    sales_first_annual_detailed }o--|| app_store_app : "fk"
    sales_subscription_offer_code_redemption }o--|| app_store_app : "fk"
    app_session_standard_daily }o--|| app_store_app : "fk"
    app_store_purchase_standard_daily }o--|| app_store_app : "fk"
    app_store_download_standard_daily }o--|| app_store_app : "fk"
    financial_detail }o--|| app_store_app : "fk"
    app_store_installation_and_deletion_detailed_daily }o--|| app_store_app : "fk"
    sales_summary_daily }o--|| app_store_app : "fk"
    app_session_detailed_daily }o--|| app_store_app : "fk"
    sales_win_back_eligibility }o--|| app_store_app : "fk"
    app_store_download_detailed_daily }o--|| app_store_app : "fk"
    app_store_installation_and_deletion_standard_daily }o--|| app_store_app : "fk"
    app_store_purchase_detailed_daily }o--|| app_store_app : "fk"
    sales_pre_order_summary }o--|| app_store_app : "fk"
    app_store_browser_choice_screen_engagement_report }o--|| app_store_app : "fk"
    financial }o--|| app_store_app : "fk"
    app_store_review }o--|| app_store_app : "fk"
    app_store_app_version }o--|| app_store_app : "fk"
    app_store_discovery_and_engagement_standard_daily }o--|| app_store_app : "fk"
    app_crash_daily }o--|| app_store_app : "fk"
    app_store_pre_order_detailed_daily }o--|| app_store_app : "fk"
    app_store_pre_order_standard_daily }o--|| app_store_app : "fk"
