erDiagram
    contact_owner {
        text id PK
        text contact_id PK
    }
    contact {
        text id PK
        text actual_time
        text address_line_1
        text address_line_2
        text approved_estimate_total
        text approved_invoice_due
        text approved_invoice_total
        text attachment_count
        text city
        text class_id
        text class_name
        text color
        text color_shade
        text company
        text country_name
        text created_by
        text created_by_name
        text customer
        text date_created
        text date_end
        text date_start
        text date_status_change
        timestamp date_updated
        text description
        text disable_auto_text
        text display_name
        text email
        text estimated_time
        text external_id
        text fax_number
        jsonb field_assist
        text first_name
        text home_phone
        text image_id
        text is_active
        text is_archived
        text is_closed
        text is_lead
        text is_sub_contractor
        text is_user
        text last_budget_gross_margin
        text last_budget_gross_profit
        text last_budget_revenue
        text last_estimate
        text last_estimate_date_created
        text last_estimate_date_estimate
        text last_estimate_jnid
        text last_estimate_number
        text last_invoice
        text last_invoice_date_created
        text last_invoice_date_invoice
        text last_invoice_jnid
        text last_invoice_number
        text last_name
        text latitude
        text location_id
        text location_name
        text location_parent_id
        text longitude
        text merged
        text mobile_phone
        text number
        text open_edge_id
        text recid
        text record_type
        text record_type_name
        jsonb related
        jsonb rules
        text sales_rep
        text sales_rep_name
        text source
        text source_name
        text state_text
        text status
        text status_name
        jsonb subcontractors
        text sunlight_event
        text sunlight_status_and_id
        jsonb tags
        text task_count
        text type
        text website
        text work_phone
        text zip
    }
    task_owner {
        text id PK
        text task_id PK
    }
    task_related {
        text id PK
        text task_id PK
        text name
        text subject
    }
    task {
        text id PK
        text actual_time
        text all_day
        text all_day_end_date
        text all_day_start_date
        text created_by
        text created_by_name
        text customer
        text date_created
        text date_end
        text date_sort
        text date_start
        timestamp date_updated
        text description
        text estimated_time
        text external_id
        text hide_from_calendarview
        text hide_from_tasklist
        text is_active
        text is_archived
        text is_completed
        text location_id
        text merged
        text number
        text priority
        text recid
        text record_type
        text record_type_name
        jsonb rules
        jsonb subcontractors
        jsonb tags
        text title
        text type
    }
    file_owner {
        text id PK
        text file_id PK
    }
    file_related {
        text file_id PK
        text id PK
        text name
    }
    file {
        text id PK
        text content_type
        text created_by
        text created_by_name
        text customer
        text date_created
        text date_file_created
        timestamp date_updated
        text description
        text file_name
        text is_active
        text is_archived
        text is_private
        text record_type
        text record_type_name
        text sales_rep
        text size
        text sub_type
        text type
    }
    job_owner {
        text id PK
        text job_id PK
    }
    job_related {
        text id PK
        text job_id PK
        text name
        text subject
    }
    job {
        text id PK
        text actual_time
        text address_line_1
        text address_line_2
        text all_day
        text all_day_end_date
        text all_day_start_date
        text approved_estimate_total
        text approved_invoice_due
        text approved_invoice_total
        text attachment_count
        text city
        text class_id
        text class_name
        text country_name
        text created_by
        text created_by_name
        text customer
        text date_created
        text date_end
        text date_start
        text date_status_change
        timestamp date_updated
        text description
        text estimated_time
        text external_id
        jsonb field_assist
        text image_id
        text is_active
        text is_archived
        text is_closed
        text is_lead
        text last_budget_gross_margin
        text last_budget_gross_profit
        text last_budget_revenue
        text last_estimate
        text last_estimate_date_created
        text last_estimate_date_estimate
        text last_estimate_jnid
        text last_estimate_number
        text last_invoice
        text last_invoice_date_created
        text last_invoice_date_invoice
        text last_invoice_jnid
        text last_invoice_number
        text latitude
        text location_id
        text location_parent_id
        text longitude
        text merged
        text name
        text number
        text open_edge_id
        text parent_approved_estimate_total
        text parent_approved_invoice_due
        text parent_approved_invoice_total
        text parent_fax_number
        text parent_home_phone
        text parent_last_estimate
        text parent_last_invoice
        text parent_mobile_phone
        text parent_work_phone
        text recid
        text record_type
        text record_type_name
        jsonb rules
        text sales_rep
        text sales_rep_name
        text source
        text source_name
        text state_text
        text status
        text status_name
        jsonb subcontractors
        text sunlight_events
        text sunlight_status_and_id
        jsonb tags
        text task_count
        text type
        text zip
    }
    activity_owner {
        text id PK
        text activity_id PK
    }
    activity_related {
        text activity_id PK
        text id PK
        text name
        text subject
    }
    activity {
        text id PK
        text created_by
        text created_by_name
        text customer
        text date_created
        text date_updated
        text email_status
        text external_id
        text is_active
        text is_archived
        text is_editable
        text is_private
        text is_status_change
        text location_id
        text location_parent_id
        text merged
        text note
        text record_type
        text record_type_name
        jsonb rules
        text sales_rep
        text sales_rep_name
        text source
        text stack
        text type
    }
    contact_owner }o--|| contact : "fk"
    task_owner }o--|| task : "fk"
    task_related }o--|| contact : "fk"
    task_related }o--|| task : "fk"
    file_owner }o--|| file : "fk"
    file_related }o--|| contact : "fk"
    file_related }o--|| file : "fk"
    job_owner }o--|| job : "fk"
    job_related }o--|| contact : "fk"
    job_related }o--|| job : "fk"
    activity_owner }o--|| activity : "fk"
    activity_related }o--|| contact : "fk"
    activity_related }o--|| activity : "fk"
