erDiagram
    team {
        text id PK
        text description
        text name
        text number_of_members
        text uuid
    }
    response_report {
        text _fivetran_id PK
        text conversation_id FK
        text responding_agent_display_id FK
        text agent_response_order
        text assistant_rht
        text auto_tag
        text bot_response_order
        text date_claimed
        text expert_rht
        text external_response_id
        text handle_time_approving_agent
        text handle_time_other_agent
        text handle_time_responding_agent
        text handle_time_total_response
        text lsw_conversation_link
        text lsw_responded_post_in_business_hour
        text lsw_responded_to_external_post_id
        text lsw_responded_to_post_author_uuid
        text lsw_responded_to_post_content
        text lsw_responded_to_post_published_time
        text lsw_responded_to_post_received_time
        text manual_tag
        text responding_agent_email
        text response_content
        text response_handle
        text response_language
        text response_location
        text response_order
        text response_provider
        text response_published_date
        text response_sentiment
        text response_tag
        text response_tar
        text response_type
        text sentiment_conversion
        text source_tag
        text unique_id
    }
    combined_report {
        text _fivetran_id PK
        text assignee_author_display_id FK
        text conversation_id FK
        text approver_response_handle_time
        text assignee_author_email
        text assignee_team
        text assistant_response_handle_time
        text author_tag
        text author_uuid
        text average_tar_minutes
        text close_note
        text closed_date
        text closer_wrap_or_close_handle_time
        text content
        text conversation_post_tag
        text conversation_response_handle_time
        text created_date
        text date_claimed
        text expert_response_handle_time
        text external_id
        text languages
        text other_wrap_or_close_handle_time
        text published_date
        text received_during_business_hour
        text responder_response_handle_time
        text sentiment
        text source
        text status
        text survey_comment
        text survey_completed_time
        text survey_response
        text survey_sent_time
        text survey_type
        text total_in_progress_time
        text total_posts_order_in_convo
        text total_posts_post_order
        text total_responses_response_order
        text total_wrap_or_close_handle_time
        text type
        text unique_id
    }
    team_performance_report {
        text _fivetran_id PK
        text agent_display_id FK
        text team_name FK
        text agent_activities_active_time_in_focus
        text agent_activities_active_time_out_of_focus
        text agent_activities_avg_responder_rht
        text agent_activities_idle_time_in_focus
        text agent_activities_idle_time_out_of_focus
        text agent_activities_in_app_time_in_focus
        text agent_activities_in_app_time_out_of_focus
        text agent_activities_inactive_time_in_focus
        text agent_activities_inactive_time_out_of_focus
        text agent_activities_non_agent_time_in_focus
        text agent_activities_non_agent_time_out_of_focus
        text agent_activities_total_approval_sent
        text agent_activities_total_approver_rht
        text agent_activities_total_assistant_rht
        text agent_activities_total_case_note_added
        text agent_activities_total_close_ht
        text agent_activities_total_closer_close_ht
        text agent_activities_total_closer_wrap_ht
        text agent_activities_total_expert_rht
        text agent_activities_total_in_progress_time
        text agent_activities_total_other_close_ht
        text agent_activities_total_other_wrap_ht
        text agent_activities_total_responder_rht
        text agent_activities_total_response_ht
        text agent_activities_total_review_closed_time
        text agent_activities_total_wrap_ht
        text agent_reroute
        text agent_unassign
        text agent_utilization
        text average_conversation_handle_time
        text average_first_response_tar
        text average_response_handle_time
        text average_subsequent_response_tar
        text average_tar
        text average_time_in_available_queue
        text claim
        text conversation_closed
        text conversation_closed_with_engagement
        text conversation_closed_without_engagement
        text conversations_acted_on
        text conversations_handled
        text conversations_in_assigned
        text conversations_in_pending
        text conversations_pushed
        text conversations_responded_to
        text conversations_snoozed
        text email
        text first_response
        text interval_end_date
        text interval_start_date
        text median_tar
        text other_unassign
        text primary_responder_csat_score
        text primary_responder_csat_survey
        text primary_responder_nps_score
        text primary_responder_nps_survey
        text re_opened
        text reassign
        text responded_to_avg_case_handle_time
        text responded_to_avg_response_handle_time
        text response
        text responses_handled
        text subsequent_responses
        text total_assigned
        text total_first_claim
        text total_handle_time
        text total_snooze_action
        text total_time_logged_in
    }
    conversation_action_history_report {
        text _fivetran_id PK
        text conversation_id FK
        text acting_agent
        text acting_agent_email
        text acting_agent_sso_id
        text acting_agent_state
        text action_performed
        text action_performed_date
        text author
        text cc_email
        text comment
        text community_response
        text content_filter
        text current_disposition
        text current_priority
        text history_action
        text merged_conversation_id
        text note
        text post
        text post_date
        text response
        text snooze_duration
        text snooze_duration_unit
        text source
        text tags
        text to_email
        text workqueue_current
    }
    incoming_post_report {
        text _fivetran_id PK
        text conversation_id FK
        text all_author_tags
        text all_post_tags
        text author_auto_tags
        text author_handle
        text author_manual_tags
        text author_uuid
        text auto_tag_num_tags
        text auto_tag_tags
        text conversation_priority
        text conversation_work_queue
        text date_post_published
        text date_post_received
        text external_author_handle_id
        text external_post_id
        text lsw_conversation_link
        text manual_tag_num_tags
        text manual_tag_tags
        text post_content
        text post_language
        text post_location
        text post_order
        text post_permalink
        text post_provider
        text post_sentiment
        text post_source_tag
        text post_type
        text received_during_business_hours
        text unique_id
        text work_queue_at_time_of_event
    }
    conversation_report {
        text _fivetran_id PK
        text assigned_agent_display_id FK
        text all_author_tag
        text all_custom_tag
        text approver_rht
        text assigned_agent_email
        text assistant_rht
        text author
        text author_handle
        text author_responded
        text author_uuid
        text auto_tag
        text close_note
        text closed_date
        text conversation_id
        text conversation_other_wcht
        text conversation_source
        text conversation_wcht
        text created_date
        text expert_rht
        text handle_time_average_conversation_approval
        text handle_time_average_conversation_response
        text handle_time_conversation_assigned_agent
        text handle_time_conversation_total
        text handle_time_conversation_wrap_up
        text language_tag
        text location_tag
        text manual_tag
        text num_negative_post
        text num_neutral_post
        text num_positive_post
        text num_private_post
        text num_private_response
        text responder_rht
        text response_handles_used
        text response_ht
        text sentiment_conversion
        text source_tag
        text status
        text survey_comment
        text survey_completed_time
        text survey_response
        text survey_sent_time
        text survey_type
        text system_tag
        text total_in_progress_time
        text total_post
        text total_response
        text work_queue_at_time_of_event
    }
    response_approval_report {
        text _fivetran_id PK
        text approver_display_id FK
        text conversation_id FK
        text submitter_display_id FK
        text approval_date
        text approval_decision
        text approval_disposition
        text approval_edited_response
        text approval_handle_time
        text approval_note
        text approver_email
        text approver_team
        text response_draft_id
        text submission_content
        text submission_date
        text submitter_email
        text submitter_response_handle_time
        text submitter_team
        text total_approval_time
    }
    help_request_report {
        text _fivetran_id PK
        text conversation_id FK
        text help_requester_display_id FK
        text responding_expert_display_id FK
        text available_expert
        text help_request_end_reason
        text help_requester_comment
        text help_requester_email
        text help_requester_team
        text link_to_conversation
        text link_to_response
        text responding_expert_comment
        text responding_expert_email
        text responding_expert_team
        text response_content
        text time_awaiting_help_min
        text time_of_expert_response
        text time_of_help_request
        text total_response_handle_time_min
    }
    user_report {
        text _fivetran_id PK
        text team_name FK
        text agent_display_id
        text email
        text last_login_time
        text total_console_logged_in_time
        text total_green_state_time
        text total_mobile_time
        text total_red_state_time
        text total_yellow_state_time
        text user_type
    }
    team_performance_interval {
        text _fivetran_id PK
        text agent_display_id FK
        text team_name FK
        text agent_activities_total_review_closed_time
        text agent_activities_v_2_active_time_in_focus
        text agent_activities_v_2_active_time_out_of_focus
        text agent_activities_v_2_avg_responder_rht
        text agent_activities_v_2_idle_time_in_focus
        text agent_activities_v_2_idle_time_out_of_focus
        text agent_activities_v_2_in_app_time_in_focus
        text agent_activities_v_2_in_app_time_out_of_focus
        text agent_activities_v_2_inactive_time_in_focus
        text agent_activities_v_2_inactive_time_out_of_focus
        text agent_activities_v_2_non_agent_time_in_focus
        text agent_activities_v_2_non_agent_time_out_of_focus
        text agent_activities_v_2_total_in_progress
        text agent_activities_v_2_total_response_ht
        text agent_reroute
        text agent_unassign
        text agent_utilization
        text average_conversation_handle_time
        text average_first_response_tar
        text average_response_handle_time
        text average_subsequent_response_tar
        text average_tar
        text average_time_in_available_queue
        text claim
        text conversation_closed
        text conversation_closed_with_engagement
        text conversation_closed_without_engagement
        text conversation_pushed
        text conversations_acted_on
        text conversations_handled
        text conversations_in_assigned
        text conversations_in_pending
        text conversations_responded_to
        text conversations_snoozed
        text email
        text first_response
        text interval_end_date
        text interval_start_date
        text median_tar
        text other_unassign
        text primary_responder_csat_score
        text primary_responder_csat_survey
        text re_opened
        text reassign
        text responded_to_avg_case_handle_time
        text responded_to_avg_response_handle_time
        text response
        text responses_handled
        text subsequent_response
        text total_assigned
        text total_first_claim
        text total_handle_time
        text total_snooze_action
        text total_time_logged_in
    }
    response_report }o--|| conversation_report : "fk"
    response_report }o--|| user_report : "fk"
    combined_report }o--|| user_report : "fk"
    combined_report }o--|| conversation_report : "fk"
    team_performance_report }o--|| team : "fk"
    team_performance_report }o--|| user_report : "fk"
    conversation_action_history_report }o--|| conversation_report : "fk"
    incoming_post_report }o--|| conversation_report : "fk"
    conversation_report }o--|| user_report : "fk"
    response_approval_report }o--|| user_report : "fk"
    response_approval_report }o--|| conversation_report : "fk"
    response_approval_report }o--|| user_report : "fk"
    help_request_report }o--|| conversation_report : "fk"
    help_request_report }o--|| user_report : "fk"
    help_request_report }o--|| user_report : "fk"
    user_report }o--|| team : "fk"
    team_performance_interval }o--|| team : "fk"
    team_performance_interval }o--|| user_report : "fk"
