erDiagram
    event_guest_registration_answer {
        text id PK
        text event_guest_id PK
        text answer
        text label
        text question_type
    }
    event_guest {
        text id PK
        text event_id PK
        text user_api_id FK
        text approval_status
        text check_in_qr_code
        text checked_in_at
        text created_at
        text invited_at
        text joined_at
        text registered_at
        text user_email
        text user_name
    }
    event {
        text id PK
        text cover_url
        text description
        text duration_interval
        text end_at
        text event_type
        text geo_address_json
        text geo_latitude
        text geo_longitude
        text name
        text series_api_id
        text social_image_url
        text start_at
        text timezone
        text url
        text user_api_id
        text visibility
    }
    event_host {
        text event_id PK
        text id PK
        text avatar_url
        text email
        text name
    }
    event_guest_registration_answer }o--|| event_guest : "fk"
    event_guest }o--|| event : "fk"
    event_guest }o--|| event : "fk"
    event_host }o--|| event : "fk"
    event_host }o--|| event : "fk"
