erDiagram
    register {
        text id PK
        text chargify_register
        text committed_invoice_number_prefix
        text currency_code
        text default_qb_ar_account
        text do_not_sync
        text do_not_sync_associated_customers
        text generated_invoice_number_prefix
        text modified
        text name
    }
    payment_term {
        text id PK
        text intacct_id
        text intacct_modified
        text intacct_record_no
        text is_active
        text name
        text netsuite_id
        text num_days
        text num_months
    }
    contract {
        text id PK
        text billing_profile_payment_term_id FK
        text customer_id FK
        text register_id FK
        text billing_profile_account_number
        text billing_profile_address_1
        text billing_profile_address_2
        text billing_profile_address_3
        text billing_profile_alt_contact
        text billing_profile_alt_phone
        text billing_profile_city
        text billing_profile_company_name
        text billing_profile_contact
        text billing_profile_country
        text billing_profile_currency
        text billing_profile_customer_type_ref_fullname
        text billing_profile_default_credit_memo_template
        text billing_profile_default_invoice_template
        text billing_profile_edit_sequence
        text billing_profile_email
        text billing_profile_entity_use_code
        text billing_profile_fax
        text billing_profile_first_name
        text billing_profile_full_name
        text billing_profile_invoice_email_preference
        text billing_profile_invoice_print_preference
        text billing_profile_is_active
        text billing_profile_job_description
        text billing_profile_job_end_date
        text billing_profile_job_projected_end_date
        text billing_profile_job_start_date
        text billing_profile_job_status
        text billing_profile_job_type
        text billing_profile_last_name
        text billing_profile_name
        text billing_profile_parent_id
        text billing_profile_phone
        text billing_profile_resale_number
        text billing_profile_sales_rep
        text billing_profile_salutation
        text billing_profile_shipping_address_1
        text billing_profile_shipping_address_2
        text billing_profile_shipping_address_3
        text billing_profile_shipping_city
        text billing_profile_shipping_country
        text billing_profile_shipping_state
        text billing_profile_shipping_zip_code
        text billing_profile_state
        text billing_profile_zip_code
        text channel
        text created
        text created_by
        text created_by_name
        text email
        text entry_date
        text is_job
        text lead_date
        text lead_source
        text modified
        text modified_by
        text modified_by_name
        text notes
        text number
        text number_field_1
        text number_field_2
        text qb_job_id
        text sf_id
        text text_field_1
        text text_field_2
        text unbalanced_revenue_exception
    }
    transaction_renewal_of_set {
        text index PK
        text transaction_id PK
        text renewal_of_set
    }
    transaction {
        text id PK
        text autorenewal_profile_id FK
        text billing_method_id FK
        text contract_id FK
        text item_id FK
        text renew_using_item_id FK
        text renewal_billing_method_id FK
        text advanced_billing_subscription_id
        text advanced_billing_subscription_line_id
        text always_use_amount_as_normalized_amount
        text auditentry_created
        text auditentry_created_by
        text auditentry_created_by_name
        text auditentry_modified
        text auditentry_modified_by
        text auditentry_modified_by_name
        text automatically_update_revenue
        text c_primary_persona
        text c_proactive
        text c_renewal_opportunities
        text cancelled
        text conversion
        text crm_opportunity_id
        text crm_opportunity_line_item_id
        text different_invoice_item_permitted
        text duration
        text end_date
        text flagged
        text foreign_exchange_rate
        text home_amount
        text home_arr_amount
        text home_normalized_amount
        text home_normalized_rate
        text home_rate
        text hubspot_renewal_deal_rule
        text ili_qb_class
        text invoice_description
        text is_autorenewal
        text item_class
        text local_amount
        text local_arr_amount
        text local_normalized_amount
        text local_normalized_rate
        text local_rate
        text modified
        text notes
        text number
        text number_field_1
        text number_field_2
        text order_date
        text order_number
        text project
        text quantity
        text recognize
        text reconcile_required
        text renewal_amount
        text renewal_amount_percentage
        text renewal_amount_value
        text renewal_duration
        text renewal_factor
        text renewal_probability
        text renewal_quantity
        text revenue_amount
        text revenue_notes
        text sales_manager
        text sales_rep
        text sf_group_id
        text sf_id
        text sf_opportunity_id
        text sf_opportunity_line_item_id
        text sf_renewal_opportunity_id
        text sf_renewal_opportunity_line_item_id
        text sf_renewal_opportunity_rule
        text start_date
        text term_number
        text text_field_1
        text text_field_2
        text unbalanced_revenue_exception
    }
    billing_description {
        text id PK
        text content
        text name
        text notes
    }
    invoice_line_item {
        text id PK
        text invoice_id PK
        text item_id FK
        text transaction_id FK
        text created
        text created_by
        text created_by_name
        text deleted_in_qb
        text exported_date
        text external_id
        text home_amount
        text local_amount
        text modified
        text modified_by
        text modified_by_name
        text no_transaction_permitted
        text notes
        text qb_class
        text qb_time_modified
        text qb_txn_line_id
        text quantity
        text recurly_id
        text refund_of
        text refund_of_stripe_id
        text sf_id
        text stripe_id
        text sync_date
    }
    invoice_tax_line {
        text id PK
        text invoice_id PK
        text description
        text local_amount
        text rate
    }
    invoice {
        text id PK
        text contract_id FK
        text applied_amount
        text auditentry_created
        text auditentry_created_by
        text auditentry_created_by_name
        text auditentry_modified
        text auditentry_modified_by
        text auditentry_modified_by_name
        text auditentry_qb_created
        text auditentry_qb_modified
        text avatax_commit_timestamp
        text avatax_id
        text avatax_modify_timestamp
        text avatax_reconciliation_status
        text avatax_status
        text balance
        text billing_address_1
        text billing_address_2
        text billing_address_3
        text billing_city
        text billing_country
        text billing_state
        text billing_zip_code
        text committed
        text committed_timestamp
        text date
        text deleted_in_qb
        text do_not_sync
        text due_date
        text ei_theme
        text einvoicing_url
        text einvoicing_url_no_click_tracking
        text email_from_so
        text enable_ach_payment
        text enable_cc_payment
        text exported_date
        text external_id
        text foreign_exchange_rate
        text home_amount
        text ignore_date_when_syncing
        text is_paid
        text last_clicked
        text last_emailed
        text last_opened
        text local_amount
        text memo
        text number
        text other
        text po_number
        text qb_ar_account
        text qb_class
        text qb_currency
        text qb_customer_message
        text qb_number
        text qb_payment_terms
        text qb_sales_rep
        text qb_template
        text qb_txn_id
        text recurly_id
        text refund_of
        text sales_tax
        text sales_tax_percentage
        text sf_id
        text ship_date
        text shipping_address_1
        text shipping_address_2
        text shipping_address_3
        text shipping_city
        text shipping_country
        text shipping_state
        text shipping_zip_code
        text stripe_id
        text stripe_refund_id
        text subtotal
        text sync_date
        text to_be_emailed
        text to_be_printed
        text type
    }
    currency_code {
        text code PK
        text name
    }
    revenue_recognition_method {
        text id PK
        text name
    }
    billing_method {
        text id PK
        text name
    }
    item {
        text id PK
        text asset_account_id FK
        text billing_method_id FK
        text income_account_id FK
        text liability_account_id FK
        text revenue_recognition_method_id FK
        text avatax_id
        text avatax_sales_tax_code
        text billing_description
        text chargify_component_kind
        text chargify_family_id
        text chargify_id
        text chargify_modified
        text code
        text commodity_code
        text create_revenue
        text created
        text created_by
        text created_by_name
        text default_duration
        text description
        text do_not_sync
        text edit_sequence
        text enable_create_transaction
        text enforce_start_date_after_end_date
        text gl_created
        text gl_description
        text gl_is_active
        text gl_modified
        text gl_name
        text gl_tax_rate
        text intacct_id
        text intacct_modified
        text intacct_record_no
        text is_active
        text is_discount
        text is_sales_tax
        text is_taxable
        text long_term_liability_account
        text modified
        text modified_by
        text modified_by_name
        text name
        text needs_so_profile
        text netsuite_id
        text netsuite_modified
        text normalized_term
        text product_family
        text qb_account
        text qb_id
        text qb_only
        text qb_sales_tax_code
        text recurly_id
        text recurring
        text renew_all_open_transactions
        text renew_using_same_item
        text sf_do_not_sync
        text source_system
        text stripe_id
        text sync_invoice
        text transaction_end_date
        text transaction_start_date
        text unit_name
        text use_chargify_start_and_end_dates
        text wizard_enabled
        text xero_code
        text xero_id
        text xero_modified
    }
    account {
        text id PK
        text account_type
        text gl_number
        text intacct_id
        text intacct_modified
        text intacct_record_no
        text name
        text netsuite_id
        text source_system
    }
    sales_order_line_item {
        text id PK
        text sales_order_id PK
        text affected_transaction
        text created
        text created_by_username
        text invoice_billing_address_1
        text invoice_billing_address_2
        text invoice_billing_address_3
        text invoice_billing_city
        text invoice_billing_country
        text invoice_billing_state
        text invoice_billing_zip_code
        text invoice_cadence_template
        text invoice_date
        text invoice_do_not_sync
        text invoice_ei_combine_all_description
        text invoice_ei_combine_lines
        text invoice_ei_theme
        text invoice_email_from_so
        text invoice_enable_ach_payment
        text invoice_enable_cc_payment
        text invoice_ignore_date_when_syncing
        text invoice_memo
        text invoice_other
        text invoice_payment_terms
        text invoice_qb_class
        text invoice_qb_customer_message
        text invoice_qb_sales_rep
        text invoice_qb_template
        text invoice_ship_date
        text invoice_shipping_address_1
        text invoice_shipping_address_2
        text invoice_shipping_address_3
        text invoice_shipping_city
        text invoice_shipping_country
        text invoice_shipping_state
        text invoice_shipping_zip_code
        text invoice_suppress_zero_value_line_items
        text invoice_to_be_emailed
        text invoice_to_be_printed
        text line_item_id
        text processed
        text renewed_transaction
        text sfdc_object_type
        text transaction_action
        text transaction_amount
        text transaction_amount_after_discount
        text transaction_arr_amount
        text transaction_billing_method
        text transaction_c_primary_persona
        text transaction_c_proactive
        text transaction_c_renewal_opportunities
        text transaction_conversion
        text transaction_crm_opportunity_id
        text transaction_crm_opportunity_line_item_id
        text transaction_discount_amount
        text transaction_duration
        text transaction_effective_change_date
        text transaction_effective_end_date
        text transaction_end_date
        text transaction_flagged
        text transaction_foreign_exchange_rate
        text transaction_generate_invoices
        text transaction_generate_revenue
        text transaction_ili_description
        text transaction_ili_qb_class
        text transaction_invoice_end_date
        text transaction_invoice_quantity
        text transaction_invoice_start_date
        text transaction_item_class_name
        text transaction_item_code
        text transaction_item_name
        text transaction_monthly_rate
        text transaction_normalized_amount
        text transaction_normalized_term
        text transaction_notes
        text transaction_number_field_1
        text transaction_number_field_2
        text transaction_order_date
        text transaction_quantity
        text transaction_recognize
        text transaction_renew_using_item
        text transaction_renewal_amount
        text transaction_renewal_amount_percentage
        text transaction_renewal_billing_method
        text transaction_renewal_duration
        text transaction_renewal_factor
        text transaction_renewal_probability
        text transaction_renewal_quantity
        text transaction_revenue_amount
        text transaction_revenue_end_date
        text transaction_revenue_recognition_method
        text transaction_revenue_start_date
        text transaction_sales_manager
        text transaction_sales_rep
        text transaction_sf_group_id
        text transaction_sf_id
        text transaction_sf_renewal_opportunitiy_rule
        text transaction_start_date
        text transaction_text_field_1
        text transaction_text_field_2
        text transaction_unbalanced_revenue_exception
    }
    sales_order {
        text id PK
        text close_date
        text contract_channel
        text contract_email
        text contract_entry_date
        text contract_is_job
        text contract_lead_date
        text contract_lead_source
        text contract_notes
        text contract_number
        text contract_number_field_1
        text contract_number_field_2
        text contract_register_name
        text contract_sf_id
        text contract_text_field_1
        text contract_text_field_2
        text contract_unbalanced_revenue_exception
        text created
        text created_by_username
        text customer_account_number
        text customer_alt_contact
        text customer_alt_phone
        text customer_autopay_enrollment
        text customer_billing_address_3
        text customer_billing_city
        text customer_billing_country
        text customer_billing_state
        text customer_billing_street
        text customer_billing_zip_code
        text customer_c_concierge_hot_platform
        text customer_c_concierge_inferno_platform
        text customer_c_concierge_spicy_platform
        text customer_c_concierge_user_license
        text customer_c_crm
        text customer_c_cs_owner
        text customer_c_drop_down_field_1
        text customer_c_instant_booker_hot_user_licenses
        text customer_c_instant_booker_spicy_user_licenses
        text customer_c_non_renewable_customer
        text customer_c_optout_clause
        text customer_c_q_4_22_am_text_field
        text customer_c_ultimate_parent_id
        text customer_chargify_id
        text customer_city
        text customer_code
        text customer_contact
        text customer_country
        text customer_crm_id
        text customer_currency
        text customer_default_autorenewal_profile
        text customer_default_cadence_template
        text customer_default_email_from_so
        text customer_default_enable_ach_payment
        text customer_default_enable_cc_payment
        text customer_default_invoice_template
        text customer_default_payment_method
        text customer_default_theme
        text customer_do_not_sync
        text customer_email
        text customer_entity_use_code
        text customer_fax
        text customer_first_name
        text customer_gl_tax_rate
        text customer_industry
        text customer_invoice_email_preference
        text customer_invoice_print_preference
        text customer_item_sales_tax
        text customer_last_name
        text customer_market
        text customer_name
        text customer_notes
        text customer_number
        text customer_number_field_1
        text customer_number_field_2
        text customer_number_field_3
        text customer_parent
        text customer_payment_term
        text customer_phone
        text customer_resale_number
        text customer_sales_rep
        text customer_sales_tax_code
        text customer_salutation
        text customer_segment
        text customer_sf_default_renewal_opportunity_rule
        text customer_sf_opportunity_price_book_id
        text customer_sf_owner_id
        text customer_sfdc_object_id
        text customer_shipping_address_3
        text customer_shipping_city
        text customer_shipping_country
        text customer_shipping_state
        text customer_shipping_street
        text customer_shipping_zip_code
        text customer_state
        text customer_subsegment
        text customer_text_field_1
        text customer_text_field_2
        text customer_text_field_3
        text customer_type
        text customer_unbalanced_revenue_exception
        text name
        text order_notes
        text order_total
        text project_name
        text project_template
        text quickbooks_job_account_number
        text quickbooks_job_address_1
        text quickbooks_job_address_2
        text quickbooks_job_address_3
        text quickbooks_job_alt_contact
        text quickbooks_job_alt_phone
        text quickbooks_job_city
        text quickbooks_job_company_name
        text quickbooks_job_contact
        text quickbooks_job_country
        text quickbooks_job_default_credit_memo_template
        text quickbooks_job_default_invoice_template
        text quickbooks_job_description
        text quickbooks_job_email
        text quickbooks_job_end_date
        text quickbooks_job_fax
        text quickbooks_job_first_name
        text quickbooks_job_invoice_email_preference
        text quickbooks_job_invoice_print_preference
        text quickbooks_job_is_active
        text quickbooks_job_last_name
        text quickbooks_job_name
        text quickbooks_job_payment_term
        text quickbooks_job_payment_terms
        text quickbooks_job_phone
        text quickbooks_job_projected_end_date
        text quickbooks_job_resale_number
        text quickbooks_job_sales_rep
        text quickbooks_job_salutation
        text quickbooks_job_shipping_address_1
        text quickbooks_job_shipping_address_2
        text quickbooks_job_shipping_address_3
        text quickbooks_job_shipping_city
        text quickbooks_job_shipping_country
        text quickbooks_job_shipping_state
        text quickbooks_job_shipping_zip_code
        text quickbooks_job_start_date
        text quickbooks_job_state
        text quickbooks_job_status
        text quickbooks_job_type
        text quickbooks_job_zip_code
        text sales_order_id
        text stage_name
        text transaction_renwal_quantity
        text transaction_sf_renewal_opportunity_rule
        text transaction_term_number
        text transaction_unbalanced_revenue_exemption
        text type
    }
    auto_renewal_profile {
        text id PK
        text days
        text generate_revenue
        text months
        text name
        text new_contract
        text recognize
    }
    customer {
        text id PK
        text billing_profile_currency_code FK
        text billing_profile_payment_term_id FK
        text auditentry_created
        text auditentry_created_by
        text auditentry_created_by_name
        text auditentry_modified
        text auditentry_modified_by
        text auditentry_modified_by_name
        text autopay_enrollment
        text billing_profile_account_number
        text billing_profile_address_1
        text billing_profile_address_2
        text billing_profile_address_3
        text billing_profile_alt_contact
        text billing_profile_alt_phone
        text billing_profile_avatax_address_validation_timestamp
        text billing_profile_city
        text billing_profile_company_name
        text billing_profile_contact
        text billing_profile_country
        text billing_profile_customer_type
        text billing_profile_default_class
        text billing_profile_default_credit_memo_template
        text billing_profile_default_invoice_template
        text billing_profile_edit_sequence
        text billing_profile_email
        text billing_profile_entity_use_code
        text billing_profile_fax
        text billing_profile_first_name
        text billing_profile_invoice_email_preference
        text billing_profile_invoice_print_preference
        text billing_profile_is_active
        text billing_profile_item_sales_tax
        text billing_profile_last_name
        text billing_profile_last_updated_by_qb
        text billing_profile_name
        text billing_profile_payment_method
        text billing_profile_phone
        text billing_profile_resale_number
        text billing_profile_sales_rep
        text billing_profile_sales_rep_full_name
        text billing_profile_sales_tax_code
        text billing_profile_salutation
        text billing_profile_shipping_address_1
        text billing_profile_shipping_address_2
        text billing_profile_shipping_address_3
        text billing_profile_shipping_city
        text billing_profile_shipping_country
        text billing_profile_shipping_state
        text billing_profile_shipping_zip_code
        text billing_profile_state
        text billing_profile_zip_code
        text c_concierge_hot_platform
        text c_concierge_inferno_platform
        text c_concierge_spicy_platform
        text c_concierge_user_licenses
        text c_crm
        text c_cs_owner
        text c_drop_down_field_1
        text c_instant_booker_hot_user_licenses
        text c_instant_booker_spicy_user_licenses
        text c_non_renewable_customer
        text c_optout_clause
        text c_q_4_22_am_text_field
        text c_ultimate_parent_id
        text cc_email
        text code
        text crm_id
        text default_autorenewal_profile
        text default_email_from_so
        text default_enable_ach_payment
        text default_enable_cc_payment
        text default_theme
        text do_not_sync
        text domain
        text einvoicing_id
        text email
        text enable_autopay
        text escalation_email
        text industry
        text is_active
        text market
        text modified
        text name
        text notes
        text number
        text number_field_1
        text number_field_2
        text number_field_3
        text parent
        text qb_id
        text recurly_id
        text segment
        text sf_default_renewal_opportunity_rule
        text sf_id
        text sf_opportunity_price_book_id
        text sf_owner_id
        text stripe_id
        text subsegment
        text text_field_1
        text text_field_2
        text text_field_3
        text unbalanced_revenue_exception
    }
    revenue_entry {
        text id PK
        text transaction_id FK
        text end_date
        text home_amount
        text local_amount
        text modified
        text start_date
    }
    country_code {
        text id PK
        text code
        text name
    }
    contract }o--|| customer : "fk"
    contract }o--|| register : "fk"
    contract }o--|| payment_term : "fk"
    transaction_renewal_of_set }o--|| transaction : "fk"
    transaction }o--|| billing_method : "fk"
    transaction }o--|| item : "fk"
    transaction }o--|| billing_method : "fk"
    transaction }o--|| contract : "fk"
    transaction }o--|| item : "fk"
    transaction }o--|| auto_renewal_profile : "fk"
    invoice_line_item }o--|| item : "fk"
    invoice_line_item }o--|| transaction : "fk"
    invoice_line_item }o--|| invoice : "fk"
    invoice_tax_line }o--|| invoice : "fk"
    invoice }o--|| contract : "fk"
    item }o--|| billing_method : "fk"
    item }o--|| account : "fk"
    item }o--|| account : "fk"
    item }o--|| account : "fk"
    item }o--|| revenue_recognition_method : "fk"
    sales_order_line_item }o--|| sales_order : "fk"
    customer }o--|| currency_code : "fk"
    customer }o--|| payment_term : "fk"
    revenue_entry }o--|| transaction : "fk"
