erDiagram
    project_phase_attachment_id {
        text id PK
        text project_phase_id PK
    }
    project_phase {
        text id PK
        text customer_id FK
        text project_id FK
        text calculated_finish
        text calculated_start
        text created
        text currency
        text default_category_on_phase
        text default_category_on_phase_1
        text default_category_on_phase_2
        text default_category_on_phase_3
        text default_category_on_phase_4
        text default_category_on_phase_5
        text external_id
        text id_number
        text is_closed
        text is_ready_for_recognition
        text name
        text note
        text originating_id
        text parent_id
        text percent_complete
        text planned_hour
        text predecessor
        text predecessor_lag
        text predecessors_type
        text priority
        text seq
        text updated
    }
    project_phase_attachment {
        text id PK
        text parent_id FK
        text uploaded_by FK
        text attachment_category_id
        text created
        text file_name
        text file_type
        text has_thumbnail
        text is_excluded_from_alert
        text is_folder
        text is_locked
        text is_viewable
        text locked_by
        text name
        text note
        text size
        text updated
        text workspace_id
    }
    project_milestone_attachment {
        text id PK
        text parent_id FK
        text uploaded_by FK
        text attachment_category_id
        text created
        text file_name
        text file_type
        text has_thumbnail
        text is_excluded_from_alert
        text is_folder
        text is_locked
        text is_viewable
        text locked_by
        text name
        text note
        text size
        text updated
        text workspace_id
    }
    project_milestone_attachment_id {
        text id PK
        text project_milestone_id PK
    }
    project_milestone {
        text id PK
        text customer_id FK
        text project_id FK
        text calculated_starts
        text created
        text currency
        text default_category
        text default_category_1
        text default_category_2
        text default_category_3
        text default_category_4
        text default_category_5
        text external_id
        text id_number
        text is_closed
        text is_non_billable
        text name
        text note
        text originating_id
        text parent_id
        text predecessor
        text predecessor_lag
        text predecessor_type
        text priority
        text project_task_type_id
        text seq
        text start_date
        text updated
        text use_all_can_assign
    }
    contact {
        text id PK
        text customer_id FK
        text accounting_code
        text address_1
        text address_2
        text address_3
        text address_4
        text can_bill
        text can_sell
        text can_ship
        text city
        text country
        text created
        text email
        text external_id
        text fax
        text first_name
        text is_active
        text job_title
        text last_name
        text mobile
        text nickname
        text note
        text phone
        text state
        text title
        text updated
        text zip
    }
    job_code {
        text id PK
        text accounting_code
        text created
        text currency
        text external_id
        text generic_resource_id
        text is_active
        text loaded_cost
        text name
        text note
        text updated
    }
    project_attachment {
        text id PK
        text parent_id FK
        text uploaded_by FK
        text attachment_category_id
        text created
        text file_name
        text file_type
        text has_thumbnail
        text is_excluded_from_alert
        text is_folder
        text is_locked
        text is_viewable
        text locked_by
        text name
        text note
        text size
        text updated
        text workspace_id
    }
    project_hierarchy_node {
        text id PK
        text project_id PK
    }
    project_attachment_id {
        text id PK
        text project_id PK
    }
    project_filter_set {
        text id PK
        text project_id PK
    }
    project {
        text id PK
        text billing_contact_id FK
        text contact_id FK
        text customer_id FK
        text project_approver_1 FK
        text project_approver_2 FK
        text project_approver_3 FK
        text shipping_contact_id FK
        text sold_to_contact_id FK
        text user_id FK
        text accounting_code
        text auto_bill_cap_value
        text billing_code
        text booking_approval_process
        text booking_approver
        text booking_request_approval_process
        text booking_request_approver
        text budget
        text budget_approval_process
        text budget_approver
        text budget_cost
        text budget_time
        text category_filter
        text copy_approver
        text copy_booking
        text copy_cp_exclude_filter
        text copy_custom_field
        text copy_dashboard_setting
        text copy_expense_policy
        text copy_invoice_layout_setting
        text copy_issue
        text copy_loaded_cost
        text copy_notification_setting
        text copy_project_assignment_profile
        text copy_project_billing_auto_setting
        text copy_project_billing_rule
        text copy_project_budget_group
        text copy_project_pricing
        text copy_revenue_recognition_auto_setting
        text copy_revenue_recognition_rule
        text cost_center_id
        text created
        text credit_invoice_layout_id
        text currency
        text dashboard_from
        text dashboard_message
        text discussion_message_count
        text expense_allowance_approval_process
        text expense_allowance_approver
        text expense_approval_process
        text expense_approver
        text expense_authorization_approval_process
        text expense_authorization_approver
        text external_id
        text finish_date
        text invoice_approval_process
        text invoice_approver
        text invoice_layout_id
        text invoice_text
        text is_active
        text is_auto_bill
        text is_auto_bill_cap
        text is_auto_bill_overriden
        text is_dashboard_enabled
        text is_portfolio_project
        text msp_link_type
        text name
        text news_feed_id
        text note
        text notify_assignees
        text notify_assignment_cc
        text notify_issue_assigned_to
        text notify_issue_closed_assigned_to
        text notify_issue_closed_customer_owner
        text notify_issue_closed_project_owner
        text notify_issue_created_customer_owner
        text notify_issue_created_project_owner
        text notify_owner
        text notify_sr_submitted_project_owner
        text only_owner_can_edit
        text originating_id
        text payroll_type_filter
        text portfolio_project_id
        text project_location_id
        text project_stage_id
        text purchase_order_approval_process
        text purchase_order_approver
        text purchase_request_approval_process
        text purchase_request_approver
        text rate
        text rate_card_id
        text revenue_approval_process
        text revenue_approver
        text sga_labor
        text start_date
        text sync_workspace
        text task_budget_cost
        text task_budget_revenue
        text tax_location_id
        text tax_rate_federal
        text tax_rate_state
        text template_project_id
        text timesheet_approval_process
        text timesheet_approver
        text timetype_filter
        text updated
        text user_filter
    }
    time_entry {
        text id PK
        text customer_id FK
        text job_code_id FK
        text project_id FK
        text project_task_id FK
        text user_id FK
        text accounting_date
        text category_1_id
        text category_2_id
        text category_3_id
        text category_4_id
        text category_5_id
        text category_id
        text cost_center_id
        text created
        text date
        text decimal_hour
        text description
        text end_time
        text exported
        text hour
        text hours_remaining
        text minute
        text note
        text payroll_type_id
        text project_task_type_id
        text schedule_request_item_id
        text slip_id
        text start_time
        text thin_client_id
        text time_type_id
        text timesheet_id
        text updated
    }
    users {
        text id PK
        text customer_id FK
        text job_code_id FK
        text line_manager_id FK
        text accounting_code
        text address_1
        text address_2
        text address_3
        text address_4
        jsonb attachments
        text bcc_self
        text booking_approval_process
        text booking_approver
        text booking_request_approval_process
        text booking_request_approver
        text budget_approval_process
        text budget_approver
        text city
        text cost_center_id
        text country
        text created
        text currency
        text deal_booking_request_approval_process
        text deal_booking_request_approver
        text default_saml_settings_name
        text department_id
        text display_name
        text email
        text expense_allowance_approval_process
        text expense_allowance_approver
        text expense_approval_process
        text expense_approver
        text expense_authorization_approval_process
        text expense_authorization_approver
        text expenses_filter_set
        text external_id
        text fax
        text first_name
        text generic
        text invoice_filter_set
        text is_active
        text is_guest
        text is_locked
        text is_password_forced_change
        text last_name
        text mfa_setup_date
        text mfa_status
        text middle_name
        text mobile
        text my_account_filter_set
        text name
        text nickname
        text opportunties_filter_set
        text payroll_code
        text phone
        text primary_filter_set
        text project_access_node
        text project_filter_set
        text proposal_approval_process
        text proposal_approver
        text purchase_filter_set
        text purchase_order_approval_process
        text purchase_order_approver
        text purchase_request_approval_process
        text purchase_request_approver
        text rate
        text report_filter_set
        text resource_filter_set
        text resource_profile_approval_process
        text resource_profile_approver
        text role_id
        text rpc_api_updated
        text rpc_updated_by
        text rpc_user_updated
        text salutation
        text schedule_request_approval_process
        text schedule_request_approver
        text ssn
        text state
        text territory_id
        text timesheet_approval_process
        text timesheet_approver
        text timesheets_filter_set
        text timezone
        text updated
        text user_location_id
        text week_start
        text work_schedule_id
        text workspace_filter_set
        text zip
    }
    project_task_attachment {
        text id PK
        text parent_id FK
        text uploaded_by FK
        text attachment_category_id
        text created
        text file_name
        text file_type
        text has_thumbnail
        text is_excluded_from_alert
        text is_folder
        text is_locked
        text is_viewable
        text locked_by
        text name
        text note
        text size
        text updated
        text workspace_id
    }
    project_task_time_type_filter {
        text id PK
        text project_task_id PK
    }
    project_task_assigned_user {
        text id PK
        text project_task_id PK
    }
    project_task_assigned_group {
        text id PK
        text project_task_id PK
    }
    project_task_attachment_id {
        text id PK
        text project_task_id PK
    }
    project_task_task_split {
        text id PK
        text project_task_id PK
    }
    project_task_user_assignment {
        text id PK
        text project_task_id PK
    }
    project_task {
        text id PK
        text customer_id FK
        text parent_id FK
        text project_id FK
        text assignment_cc
        text assignment_cc_email
        text calculated_finish
        text calculated_start
        text cost_center_id
        text created
        text currency
        text default_category
        text default_category_1
        text default_category_2
        text default_category_3
        text default_category_4
        text default_category_5
        text external_id
        text fn_lt_date
        jsonb hours_remaining_estimate
        text id_number
        text is_closed
        text is_non_billable
        text is_ready_for_recognition
        text is_sign_off_required
        text is_using_project_assignment
        text name
        text note
        text originating_id
        text percent_complete
        text planned_hour
        text predecessor
        text predecessor_lag
        text predecessor_type
        text priority
        text project_task_type_id
        text seq
        text start_date
        text task_budget_cost
        text task_budget_revenue
        text updated
        text use_all_can_assign
        text use_manual_task_budget
    }
    booking_attachment {
        text id PK
        text parent_id FK
        text uploaded_by FK
        text attachment_category_id
        text created
        text file_name
        text file_type
        text has_thumbnail
        text is_excluded_from_alert
        text is_folder
        text is_locked
        text is_viewable
        text locked_by
        text name
        text note
        text size
        text updated
        text workspace_id
    }
    booking_attachment_id {
        text booking_id PK
        text id PK
    }
    booking {
        text id PK
        text customer_id FK
        text job_code_id FK
        text project_id FK
        text project_task_id FK
        text user_id FK
        text approval_status
        text as_percentage
        text booking_request_id
        text booking_type_id
        text created
        text date_approved
        text date_rejected
        text date_submitted
        text end_date
        text end_time
        text external_id
        text hour
        text location_id
        text match_score
        text note
        text notify_owner
        text owner_id
        text percentage
        text preferred
        text priority
        text project_assignment_profile_id
        text repeat_id
        text resource_request_queue_id
        text rm_approver_1
        text rm_approver_2
        text rm_approver_3
        text schedule_request_item_id
        text source_booking_id
        text start_date
        text start_time
        text updated
    }
    customer {
        text id PK
        text billing_contact_id FK
        text primary_contact_id FK
        text shipping_contact_id FK
        text sold_to_contact_id FK
        text user_id FK
        text accounting_code
        text address_1
        text address_2
        text address_3
        text address_4
        text billing_code
        text business_type_id
        text city
        text company
        text company_size_id
        text cost_center_id
        text country
        text created
        text credit_invoice_layout_id
        text currency
        text customer_location_id
        text customer_source_id
        text email
        text external_id
        text fax
        text invoice_approval_process
        text invoice_approver
        text invoice_email_text
        text invoice_layout_id
        text invoice_prefix
        text invoice_text
        text is_active
        text name
        text note
        text phone
        text rate
        text state
        text statement
        text sync_workspace
        text term
        text territory_id
        text type
        text updated
        text web
        text zip
    }
    project_phase_attachment_id }o--|| project_phase_attachment : "fk"
    project_phase_attachment_id }o--|| project_phase : "fk"
    project_phase }o--|| customer : "fk"
    project_phase }o--|| project : "fk"
    project_phase_attachment }o--|| project_phase_attachment : "fk"
    project_phase_attachment }o--|| users : "fk"
    project_milestone_attachment }o--|| project_milestone_attachment : "fk"
    project_milestone_attachment }o--|| users : "fk"
    project_milestone_attachment_id }o--|| project_milestone_attachment : "fk"
    project_milestone_attachment_id }o--|| project_milestone : "fk"
    project_milestone }o--|| customer : "fk"
    project_milestone }o--|| project : "fk"
    contact }o--|| customer : "fk"
    project_attachment }o--|| project_attachment : "fk"
    project_attachment }o--|| users : "fk"
    project_hierarchy_node }o--|| project : "fk"
    project_attachment_id }o--|| project_attachment : "fk"
    project_attachment_id }o--|| project : "fk"
    project_filter_set }o--|| project : "fk"
    project }o--|| users : "fk"
    project }o--|| contact : "fk"
    project }o--|| users : "fk"
    project }o--|| users : "fk"
    project }o--|| contact : "fk"
    project }o--|| contact : "fk"
    project }o--|| customer : "fk"
    project }o--|| users : "fk"
    project }o--|| contact : "fk"
    time_entry }o--|| users : "fk"
    time_entry }o--|| project_task : "fk"
    time_entry }o--|| job_code : "fk"
    time_entry }o--|| customer : "fk"
    time_entry }o--|| project : "fk"
    users }o--|| users : "fk"
    users }o--|| job_code : "fk"
    users }o--|| customer : "fk"
    project_task_attachment }o--|| project_task_attachment : "fk"
    project_task_attachment }o--|| users : "fk"
    project_task_time_type_filter }o--|| project_task : "fk"
    project_task_assigned_user }o--|| users : "fk"
    project_task_assigned_user }o--|| project_task : "fk"
    project_task_assigned_group }o--|| project_task : "fk"
    project_task_attachment_id }o--|| project_task_attachment : "fk"
    project_task_attachment_id }o--|| project_task : "fk"
    project_task_task_split }o--|| project_task : "fk"
    project_task_user_assignment }o--|| project_task : "fk"
    project_task }o--|| customer : "fk"
    project_task }o--|| project : "fk"
    project_task }o--|| project_task : "fk"
    booking_attachment }o--|| booking_attachment : "fk"
    booking_attachment }o--|| users : "fk"
    booking_attachment_id }o--|| booking_attachment : "fk"
    booking_attachment_id }o--|| booking : "fk"
    booking }o--|| users : "fk"
    booking }o--|| project_task : "fk"
    booking }o--|| job_code : "fk"
    booking }o--|| customer : "fk"
    booking }o--|| project : "fk"
    customer }o--|| users : "fk"
    customer }o--|| contact : "fk"
    customer }o--|| contact : "fk"
    customer }o--|| contact : "fk"
    customer }o--|| contact : "fk"
