erDiagram
    deal {
        text _fivetran_id PK
        text campaign_id FK
        text active
        text advertiser_reference
        text category
        text country_iso
        text coupon_code
        text description
        text destination
        text end_date_time
        text offer_type
        text offer_value
        text start_date_time
        text terms
        text title
    }
    state_history {
        text transaction_query_state_id PK
        text transaction_query_id PK
        text conversion_expected_commission
        text conversion_item_id
        text created_at
        text notes
        text state
        text user_id
    }
    action_available {
        text index PK
        text campaign_transaction_transaction_query_id PK
        text actions_available
    }
    campaign_transaction {
        text transaction_query_id PK
        text advertiser_id FK
        text campaign_id FK
        text publisher_id FK
        text agreed_to_latest_network_terms
        text camref
        text conversion_currency
        text conversion_date_time
        text conversion_id
        text conversion_reference
        text conversion_value
        text created
        text created_at
        text created_by
        text current_state
        text default_override
        text expected_commission
        text hidden_campaign
        text ignore_cookie_period_rejection
        text last_modified
        text name
        text network_fee
        text network_id
        text network_status
        text note
        text payment_date
        text publisher_created_by
        text publisher_reference
        text publisher_reporting_timezone
        text ref_terms_and_conditions_locale_id
        text reporting_timezone
        text signup_ip
        text status
        text title
        text transaction_query_type
        text type
        text updated_at
        text vertical_id
        text week_start
    }
    impression_explode {
        text _fivetran_id PK
        text campaign_id FK
        text advertiser_reference
        text browser_family
        text browser_major
        text browser_minor
        text browser_patch
        text campaign_name
        text creative_advertiser_reference
        text creative_descriptio
        text creative_id
        text date_time
        text device_id
        text device_name
        text os_family
        text os_major
        text os_minor
        text os_patch
        text partner_id
        text partner_name
        text partnership_model_id
        text partnership_model_name
        text sku
        text traffic_source_id
        text traffic_source_name
        text user_context_id
        text user_context_name
    }
    promotional_commission_publisher {
        text id PK
        text promotional_commission_id PK
        text name
    }
    groups {
        text id PK
        text promotional_commission_id PK
        text name
    }
    promotional_commission {
        text id PK
        text campaign_id PK
        text commission_based_on_field
        text cookie_period
        text description
        text end_date
        text last_modified
        text last_modified_by
        text performance_model
        text performance_value
        text start_date
        text status
    }
    transaction_query {
        text transaction_query_reason_id PK
        text campaign_id PK
        text created_at
        text reason
    }
    voucher_code_commission_group {
        text commission_group_id PK
        text voucher_code_id PK
    }
    voucher_code {
        text id PK
        text campaign_id FK
        text active
        text description
        text end_date_time
        text on_expiry
        text on_invalid_user
        text start_date_time
        text voucher_code
    }
    network {
        text id PK
        text auto_approve_publisher
        text cm_client_id
        text default_campaign_id
        text network_application_id
        text network_contact_email
        text network_description
        text network_locale
        text network_name
        text network_note
    }
    partner_commission_group_publisher {
        text id PK
        text partner_commission_group_commission_group_id PK
        text added
        text publisher_name
    }
    partner_commission_group {
        text commission_group_id PK
        text campaign_id PK
        text active
        text description
        text end_date_time
        text last_modified
        text name
        text start_date_time
    }
    preferred_partner {
        text id PK
        text created
        text end_date
        text partner_id
        text partner_name
        text partner_status
        text start_date
        text status
    }
    click_explode {
        text _fivetran_id PK
        text campaign_id FK
        text device_id FK
        text advertiser_reference
        text browser_family
        text browser_major
        text browser_minor
        text browser_patch
        text campaign_name
        text click_conversion_rate
        text country
        text country_name
        text creative_advertiser_reference
        text creative_description
        text creative_id
        text date_time
        text device_name
        text os_family
        text os_major
        text os_minor
        text os_patch
        text partner_id
        text partner_name
        text partnership_model_id
        text partnership_model_name
        text total_clicks
        text total_clicks_converted
        text total_unique_clicks
        text traffic_source_id
        text traffic_source_name
        text type
        text user_context_id
        text user_context_name
    }
    brand_campaign {
        text advertiser_id PK
        text campaign_id PK
        text allow_deep_linking
        text allow_third_party_pixel
        text app_android_fingerprint
        text app_ios_bundle
        text app_ios_prefix
        text app_tracking_integration_mapping
        text app_tracking_provider
        text app_tracking_provider_tracking_link
        text append_url_parameters
        text associated_campaigns
        text auto_approve_publisher
        text auto_rejected_ips
        text automated_invoicing_date
        text automated_invoicing_po_number
        text basket_value_cap
        text budget_summary_interval
        text budget_summary_start_time
        text campaign_icon
        text campaign_invoice_locale
        text campaign_languages
        text campaign_logo
        text campaign_notes
        text commission_by_meta
        text commission_by_meta_label
        text consolidate_invoices
        text conversion_hiatus_period
        text conversion_type
        text cookie_period
        text cookie_status
        text created
        text created_by
        text creative_prepend
        text deeplink_method
        text default_currency
        text default_mobile_destination
        text default_override
        text deferred_lead_submission
        text description
        text destination_url
        text dont_consolidate
        text dont_invoice
        text finance_contact_email
        text force_approve_period
        text hash_ip_addresses
        text hidden_campaign
        text ignore_cookie_period_rejections
        text invalid_voucher_conversion_metric_id
        text invoice_address_1
        text invoice_address_2
        text invoice_address_3
        text invoice_address_4
        text invoice_address_country
        text invoice_address_postcode
        text invoice_company
        text invoice_contact
        text invoice_only
        text ip_tracking_time
        text is_cpc
        text is_cpc_default
        text last_modified
        text lead_confirmation_url_fail
        text lead_confirmation_url_success
        text meta_field_values_field_limit
        text meta_field_values_total_limit
        text multiple_conversions_per_click
        text network_fee
        text pay_publisher_directly
        text payment_date
        text prepend_url_string
        text recurring_payment_setup
        text reporting_timezone
        text secure_tracking
        text short_link_subdomain
        text status
        text test_mode
        text title
        text tq_auto_approve
        text tq_enabled
        text tracking_method
        text tracking_subdomain
        text unique_conversion_refs
        text vertical_id
        text week_start
    }
    platform_communication {
        text id PK
        jsonb conditions
        text disabled
        text event_id
        text from_name
        text name
        text reply_to_email
        text subject
        text updated_at
    }
    product_feed {
        text id PK
        text campaign_id PK
        text active
        text dynamic
        text fetch_frequency
        text filesize
        text last_processed
        text location
        text location_local
        text name
        text updated
    }
    communication_campaign {
        text index PK
        text communication_id PK
        text campaign
    }
    communication {
        text id PK
        text from_email
        text from_name
        text last_updated
        text name
        text preview_url
        text recipient_count
        text reply_to_email
        text send_date
        text status
        text subject
        text timezone
        text type
    }
    brand {
        text advertiser_id PK
        text account_name
        text address_1
        text address_2
        text address_3
        text address_4
        text advertiser_icon
        text allowed_deep_linking_domain
        text budget_summary_interval
        text budget_summary_start_time
        text company_name
        text contact_email
        text country
        text current_balance
        text default_currency
        text description
        text display_name
        text payment_currency
        text phone
        text postcode
        text pre_payment
        text signup_ip
        text status
        text vat_number
    }
    conversion_item {
        text id PK
        text campaign_id PK
        text conversion_id PK
        text invoice_id FK
        text approved_at
        text category
        text display_to_publisher
        text item_commission
        text item_publisher_commission
        text item_status
        text item_status_id
        text item_value
        text last_update
        text meta_data_gclid
        text reject_reason
        text sku
        jsonb voucher_codes
    }
    conversion {
        text campaign_id PK
        text id PK
        text device_id FK
        text publisher_id FK
        text ref_device_id FK
        text advertiser_reference
        text campaign_title
        text click_id
        text click_last_ip
        text click_last_used
        text click_set_ip
        text click_set_time
        text click_status
        text click_type
        text clickref
        text conversion_lag
        text conversion_reference
        text conversion_time
        text conversion_type
        text conversion_value_commission
        text conversion_value_conversion_status
        text conversion_value_id
        text conversion_value_publisher_commission
        text conversion_value_value
        text country
        text creative_id
        text creative_type
        text currency
        text currency_conversion_rate
        text currency_original
        text customer_reference
        text customer_type
        text end_date
        text last_modified
        text meta_data_commission_category
        text meta_data_customer_country
        text meta_data_dispute_date
        text meta_data_event_date
        text meta_data_event_name
        text meta_data_event_organizer
        text meta_data_event_series
        text meta_data_tuid
        text publisher_name
        text ref_conversion_metric
        text ref_conversion_metric_id
        text ref_device
        text ref_partnership_model
        text ref_partnership_model_id
        text ref_traffic_source
        text ref_traffic_source_id
        text ref_user_context
        text ref_user_context_id
        text referer_ip
        text source_referer
        text specific_creative_id
        text start_date
        text was_disputed
    }
    publisher_participating_partner_website {
        text website_id PK
        text campaign_id PK
        text publisher_id PK
        text active
        text created
        text created_by
        text description
        jsonb meta
        text primaries
        text website_country
        text website_name
        text website_type
        text website_type_name
        text website_url
        text website_vertical
        text website_vertical_name
    }
    publisher_participating_partner_database {
        text id PK
        text publisher_participating_partner_publisher_id PK
        text active
        text creation_method
        text database_name
        text female
        text male
        text max_age
        text min_age
        text size
    }
    publisher_participating_partner_legal_entity {
        text publisher_id PK
        text ref_legal_entity_id PK
        text publisher_participating_partner_publisher_id PK
        text associated_date
        text publisher_contract_id
    }
    publisher_participating_partner_group {
        text index PK
        text publisher_participating_partner_publisher_id PK
        text groups
    }
    publisher_participating_partner {
        text publisher_id PK
        text campaign_id PK
        text network_id FK
        text abn
        text account_name
        text campaign_approved
        text campaign_custom_terms_and_conditions_id
        text campaign_custom_terms_and_conditions_title
        jsonb campaign_overload
        text campaign_select
        text campaign_status
        text camref
        text company_division
        text company_logo
        text company_name
        text contact_email
        text contact_locale
        text contact_name
        text created
        text created_by
        text default_currency
        text description
        text foreign_identifier
        text gst_registered
        text im_provider
        text im_username
        text is_affiliate_user
        text is_company
        text is_foreign_network
        text is_lead_user
        text is_us_registered
        jsonb meta
        jsonb network_meta_data
        text network_note
        text network_status
        text operating_country
        text opt_in
        text phone
        text phone_area
        text promotional_method
        text promotional_method_name
        text reference_id
        text reporting_identifier
        text reporting_timezone
        text signup_ip
        text terms_and_conditions_id
        text tin_number
        text tracking_link
        text uk_vat_registered
        text us_tax_state
        text vat_number
        text vertical
        text vertical_name
        text week_start
    }
    conversation_explode {
        text _fivetran_id PK
        text campaign_id FK
        text advertiser_reference
        text average_commission
        text average_order_size
        text average_order_value
        text average_partner_commission
        text average_roas
        text browser_family
        text browser_major
        text browser_minor
        text browser_patch
        text campaign_name
        text category
        text conversion_metric_id
        text conversion_rejection_rate
        text conversion_type_name
        text country
        text country_name
        text creative_advertiser_reference
        text creative_descriptio
        text creative_id
        text currency
        text customer_reference
        text customer_type
        text date_time
        text device_id
        text device_name
        text e_cpa
        text os_family
        text os_major
        text os_minor
        text os_patch
        text partner_id
        text partner_name
        text partnership_model_id
        text partnership_model_name
        text percentage_average_partner_commission
        text percentage_commission
        text percentage_order_value
        text percentage_partner_commission
        text sku
        text total_commission
        text total_conversion_items
        text total_conversions
        text total_order_value
        text total_partner_commission
        text total_roas
        text traffic_source_id
        text traffic_source_name
        text type
        text user_context_id
        text user_context_name
        text voucher_code
        text voucher_status
        text voucher_status_name
    }
    metric {
        text id PK
        text campaign_id PK
        text count
        text last_raised_at
        text metric
        text type
    }
    campaign_promotional_country {
        text index PK
        text campaign_id PK
        text iso
        text name
    }
    campaign_commission {
        text commission_id PK
        text campaign_id PK
        text active
        text advertiser_reference
        text category
        text commission_category
        text commission_rate
        text commission_value
        text conversion_type
        text cookie_period
        text cookie_status
        text country
        text customer_reference
        text customer_type
        text end_date_time
        text event_date
        text event_name
        text event_organizer
        text event_series
        text last_modified
        text last_modified_by
        text override
        text override_type
        text promotion
        text reference_id
        text reference_type
        text sale_type
        text sku
        text start_date_time
        text update_description
        text vertical
    }
    campaign_overload {
        text index PK
        text publisher_id PK
        text campaign_id PK
        text is_cpc
    }
    campaign_currency_conversion {
        text index PK
        text campaign_id PK
        text active
        text created
        text created_by
        text from_currency
        text to_currency
    }
    campaign {
        text id PK
        text advertiser_id FK
        text advertiser_name
        text allow_deep_linking
        text allow_third_party_pixel
        text app_android_fingerprint
        text app_ios_bundle
        text app_ios_prefix
        text app_tracking_integration_mapping
        text app_tracking_provider
        text app_tracking_provider_tracking_link
        text append_url_parameter
        text associated_campaign
        text auto_approve_publisher
        text auto_rejected_ips
        text automated_invoicing_date
        text automated_invoicing_po_number
        text basket_value_cap
        text budget_summary_interval
        text budget_summary_start_time
        text campaign_currency_conversions
        text campaign_icon
        text campaign_invoice_locale
        text campaign_language
        text campaign_logo
        text campaign_notes
        text campaign_overload
        text commission_by_meta
        text commission_by_meta_label
        text consolidate_invoice
        text conversion_hiatus_period
        text conversion_type
        text cookie_period
        text cookie_status
        text created
        text created_by
        text creative_prepend
        text deeplink_method
        text default_commission_rate
        text default_commission_value
        text default_currency
        text default_mobile_destination
        text default_override
        text deferred_lead_submission
        text destination_url
        text dont_consolidate
        text dont_invoice
        text finance_contact_email
        text force_approve_period
        text hash_ip_address
        text hidden_campaign
        text ignore_cookie_period_rejection
        text invalid_voucher_conversion_metric_id
        text invoice_address_1
        text invoice_address_2
        text invoice_address_3
        text invoice_address_4
        text invoice_address_country
        text invoice_address_postcode
        text invoice_company
        text invoice_contact
        text invoice_only
        text ip_tracking_time
        text is_cpc
        text is_cpc_default
        text last_modified
        text lead_confirmation_url_fail
        text lead_confirmation_url_success
        text meta_field_values_field_limit
        text meta_field_values_total_limit
        text multiple_conversions_per_click
        text network_fee
        text pay_publisher_directly
        text payment_date
        text prepend_url_string
        text recurring_payment_setup
        text reporting_timezone
        text secure_tracking
        text short_link_subdomain
        text status
        text test_mode
        text title
        text tq_auto_approve
        text tq_enabled
        text tracking_method
        text tracking_subdomain
        text unique_conversion_ref
        text vertical_id
        text vertical_name
        text week_start
    }
    invoice {
        text id PK
        text campaign_id FK
        text average_conversion_age
        text creation_date
        text currency
        text download
        text invoice_net_value
        text invoice_reference
        text invoice_total_value
        text invoice_vat_value
        text invoiced
        text item_download
        text merchant_invoice_id
        text paid_currency
        text payment_date
        text payment_due_by_date
        text payment_reference
        text pdf_generated
        text publisher_commission
        text publisher_override
        text report_generated
        text set_end_date
        text set_start_date
        text set_timezone
        text status
        text vat_rate
    }
    voucher_commission_groups {
        text id PK
        text name
    }
    voucher_commission {
        text id PK
        text description
        text end_date
        text group_limit_id
        text group_limit_name
        text last_modified
        text last_modified_by
        jsonb meta_fields
        text performance_model
        text performance_value
        text start_date
        text status
    }
    device {
        text ref_device_id PK
        text description
        text key
        text skip_invoice
        text skip_override
        text skip_selfbill
        text title
    }
    incident {
        text id PK
        text campaign_id PK
        text deleted_at
        text metric
        text occurred_at
        text partner_id
        text partner_name
        text status
        text time_window
        text type
    }
    deal }o--|| campaign : "fk"
    state_history }o--|| campaign_transaction : "fk"
    action_available }o--|| campaign_transaction : "fk"
    campaign_transaction }o--|| campaign : "fk"
    campaign_transaction }o--|| publisher_participating_partner : "fk"
    campaign_transaction }o--|| brand : "fk"
    impression_explode }o--|| campaign : "fk"
    promotional_commission_publisher }o--|| promotional_commission : "fk"
    groups }o--|| promotional_commission : "fk"
    promotional_commission }o--|| campaign : "fk"
    transaction_query }o--|| campaign : "fk"
    voucher_code_commission_group }o--|| partner_commission_group : "fk"
    voucher_code_commission_group }o--|| voucher_code : "fk"
    voucher_code }o--|| campaign : "fk"
    partner_commission_group_publisher }o--|| partner_commission_group : "fk"
    partner_commission_group }o--|| campaign : "fk"
    click_explode }o--|| campaign : "fk"
    click_explode }o--|| device : "fk"
    brand_campaign }o--|| brand : "fk"
    brand_campaign }o--|| campaign : "fk"
    product_feed }o--|| campaign : "fk"
    communication_campaign }o--|| communication : "fk"
    conversion_item }o--|| invoice : "fk"
    conversion_item }o--|| conversion : "fk"
    conversion_item }o--|| conversion : "fk"
    conversion }o--|| publisher_participating_partner : "fk"
    conversion }o--|| device : "fk"
    conversion }o--|| device : "fk"
    publisher_participating_partner_website }o--|| publisher_participating_partner : "fk"
    publisher_participating_partner_website }o--|| publisher_participating_partner : "fk"
    publisher_participating_partner_database }o--|| publisher_participating_partner : "fk"
    publisher_participating_partner_legal_entity }o--|| publisher_participating_partner : "fk"
    publisher_participating_partner_group }o--|| publisher_participating_partner : "fk"
    publisher_participating_partner }o--|| network : "fk"
    publisher_participating_partner }o--|| campaign : "fk"
    conversation_explode }o--|| campaign : "fk"
    metric }o--|| campaign : "fk"
    campaign_promotional_country }o--|| campaign : "fk"
    campaign_commission }o--|| campaign : "fk"
    campaign_overload }o--|| campaign : "fk"
    campaign_currency_conversion }o--|| campaign : "fk"
    campaign }o--|| brand : "fk"
    invoice }o--|| campaign : "fk"
    incident }o--|| campaign : "fk"
