erDiagram
    user_account_top_pin_analytics {
        text _fivetran_id PK
        text pin_id FK
        text clickthrough
        text clickthrough_rate
        text closeup
        text closeup_rate
        text engagement
        text engagement_rate
        text full_screen_play
        text full_screen_playtime
        text impression
        text metrics_clickthrough
        text metrics_clickthrough_rate
        text metrics_closeup
        text metrics_closeup_rate
        text metrics_engagement
        text metrics_engagement_rate
        text metrics_full_screen_play
        text metrics_full_screen_playtime
        text metrics_impression
        text metrics_outbound_click
        text metrics_outbound_click_rate
        text metrics_pin_click
        text metrics_pin_click_rate
        text metrics_quartile_95_percent_view
        text metrics_save
        text metrics_save_rate
        text metrics_video_10_s_view
        text metrics_video_avg_watch_time
        text metrics_video_mrc_view
        text metrics_video_start
        text metrics_video_v_50_watch_time
        text outbound_click
        text outbound_click_rate
        text pin_click
        text pin_click_rate
        text quartile_95_percent_view
        text save
        text save_rate
        text sort_by
        text video_10_s_view
        text video_avg_watch_time
        text video_mrc_view
        text video_start
        text video_v_50_watch_time
    }
    pin_analytic_web_daily_metric {
        text date PK
        text end_date PK
        text pin_id PK
        text start_date PK
        text app_types
        text data_status
        text metrics_clickthrough
        text metrics_clickthrough_rate
        text metrics_closeup
        text metrics_full_screen_play
        text metrics_full_screen_playtime
        text metrics_impression
        text metrics_outbound_click
        text metrics_pin_click
        text metrics_profile_visit
        text metrics_quartile_95_percent_view
        text metrics_save
        text metrics_save_rate
        text metrics_user_follow
        text metrics_video_10_s_view
        text metrics_video_avg_watch_time
        text metrics_video_mrc_view
        text metrics_video_start
        text metrics_video_v_50_watch_time
    }
    pin_analytics_web {
        text end_date PK
        text start_date PK
        text pin_id PK
        text app_types
        text lifetime_metrics_total_comments
        text lifetime_metrics_total_reactions
        text summary_metrics_clickthrough
        text summary_metrics_clickthrough_rate
        text summary_metrics_closeup
        text summary_metrics_full_screen_play
        text summary_metrics_full_screen_playtime
        text summary_metrics_impression
        text summary_metrics_outbound_click
        text summary_metrics_pin_click
        text summary_metrics_profile_visit
        text summary_metrics_quartile_95_percent_view
        text summary_metrics_save
        text summary_metrics_save_rate
        text summary_metrics_user_follow
        text summary_metrics_video_10_s_view
        text summary_metrics_video_avg_watch_time
        text summary_metrics_video_mrc_view
        text summary_metrics_video_start
        text summary_metrics_video_v_50_watch_time
    }
    pin_analytic_tablet_daily_metric {
        text date PK
        text end_date PK
        text pin_id PK
        text start_date PK
        text app_types
        text data_status
        text metrics_clickthrough
        text metrics_clickthrough_rate
        text metrics_closeup
        text metrics_full_screen_play
        text metrics_full_screen_playtime
        text metrics_impression
        text metrics_outbound_click
        text metrics_pin_click
        text metrics_profile_visit
        text metrics_quartile_95_percent_view
        text metrics_save
        text metrics_save_rate
        text metrics_user_follow
        text metrics_video_10_s_view
        text metrics_video_avg_watch_time
        text metrics_video_mrc_view
        text metrics_video_start
        text metrics_video_v_50_watch_time
    }
    pin_analytics_tablet {
        text end_date PK
        text start_date PK
        text pin_id PK
        text app_type
        text lifetime_metrics_total_comments
        text lifetime_metrics_total_reactions
        text summary_metrics_clickthrough
        text summary_metrics_clickthrough_rate
        text summary_metrics_closeup
        text summary_metrics_full_screen_play
        text summary_metrics_full_screen_playtime
        text summary_metrics_impression
        text summary_metrics_outbound_click
        text summary_metrics_pin_click
        text summary_metrics_profile_visit
        text summary_metrics_quartile_95_percent_view
        text summary_metrics_save
        text summary_metrics_save_rate
        text summary_metrics_user_follow
        text summary_metrics_video_10_s_view
        text summary_metrics_video_avg_watch_time
        text summary_metrics_video_mrc_view
        text summary_metrics_video_start
        text summary_metrics_video_v_50_watch_time
    }
    user_account_analytic_daily_metric {
        text date PK
        text end_date PK
        text start_date PK
        text user_account_id PK
        text data_status
        text metrics_clickthrough
        text metrics_clickthrough_rate
        text metrics_closeup
        text metrics_closeup_rate
        text metrics_engagement
        text metrics_engagement_rate
        text metrics_full_screen_play
        text metrics_full_screen_playtime
        text metrics_impression
        text metrics_outbound_click
        text metrics_outbound_click_rate
        text metrics_pin_click
        text metrics_pin_click_rate
        text metrics_quartile_95_percent_view
        text metrics_save
        text metrics_save_rate
        text metrics_video_10_s_view
        text metrics_video_avg_watch_time
        text metrics_video_mrc_view
        text metrics_video_start
        text metrics_video_v_50_watch_time
    }
    user_account_analytics_organic {
        text end_date PK
        text start_date PK
        text user_account_id PK
        text summary_metrics_clickthrough
        text summary_metrics_clickthrough_rate
        text summary_metrics_closeup
        text summary_metrics_closeup_rate
        text summary_metrics_engagement
        text summary_metrics_engagement_rate
        text summary_metrics_full_screen_play
        text summary_metrics_full_screen_playtime
        text summary_metrics_impression
        text summary_metrics_outbound_click
        text summary_metrics_outbound_click_rate
        text summary_metrics_pin_click
        text summary_metrics_pin_click_rate
        text summary_metrics_quartile_95_percent_view
        text summary_metrics_save
        text summary_metrics_save_rate
        text summary_metrics_video_10_s_view
        text summary_metrics_video_avg_watch_time
        text summary_metrics_video_mrc_view
        text summary_metrics_video_start
        text summary_metrics_video_v_50_watch_time
    }
    pin_analytic_mobile_daily_metric {
        text date PK
        text end_date PK
        text pin_id PK
        text start_date PK
        text app_types
        text data_status
        text metrics_clickthrough
        text metrics_clickthrough_rate
        text metrics_closeup
        text metrics_full_screen_play
        text metrics_full_screen_playtime
        text metrics_impression
        text metrics_outbound_click
        text metrics_pin_click
        text metrics_profile_visit
        text metrics_quartile_95_percent_view
        text metrics_save
        text metrics_save_rate
        text metrics_user_follow
        text metrics_video_10_s_view
        text metrics_video_avg_watch_time
        text metrics_video_mrc_view
        text metrics_video_start
        text metrics_video_v_50_watch_time
    }
    pin_analytics_mobile {
        text end_date PK
        text start_date PK
        text pin_id PK
        text app_types
        text lifetime_metrics_total_comments
        text lifetime_metrics_total_reactions
        text summary_metrics_clickthrough
        text summary_metrics_clickthrough_rate
        text summary_metrics_closeup
        text summary_metrics_full_screen_play
        text summary_metrics_full_screen_playtime
        text summary_metrics_impression
        text summary_metrics_outbound_click
        text summary_metrics_pin_click
        text summary_metrics_profile_visit
        text summary_metrics_quartile_95_percent_view
        text summary_metrics_save
        text summary_metrics_save_rate
        text summary_metrics_user_follow
        text summary_metrics_video_10_s_view
        text summary_metrics_video_avg_watch_time
        text summary_metrics_video_mrc_view
        text summary_metrics_video_start
        text summary_metrics_video_v_50_watch_time
    }
    pin {
        text id PK
        text parent_pin_id FK
        text alt_text
        text board_id
        text board_owner_username
        text board_section_id
        text created_at
        text creative_type
        text description
        text dominant_color
        text has_been_promoted
        text is_owner
        text is_standard
        text link
        jsonb media_images
        text media_type
        text note
        jsonb pin_metrics
        jsonb product_tags
        text title
    }
    user_account_top_video_pin_analytics {
        text _fivetran_id PK
        text pin_id FK
        text metrics_impression
        text metrics_outbound_click
        text metrics_quartile_95_percent_view
        text metrics_save
        text metrics_video_10_s_view
        text metrics_video_avg_watch_time
        text metrics_video_mrc_view
        text metrics_video_start
        text metrics_video_v_50_watch_time
    }
    user_account {
        text id PK
        text about
        text account_type
        text board_count
        text business_name
        text follower_count
        text following_count
        text monthly_views
        text pin_count
        text profile_image
        text username
        text website_url
    }
    user_account_analytic_daily_metric_paid {
        text date PK
        text end_date PK
        text start_date PK
        text user_account_id PK
        text data_status
        text metrics_clickthrough
        text metrics_clickthrough_rate
        text metrics_closeup
        text metrics_closeup_rate
        text metrics_engagement
        text metrics_engagement_rate
        text metrics_full_screen_play
        text metrics_full_screen_playtime
        text metrics_impression
        text metrics_outbound_click
        text metrics_outbound_click_rate
        text metrics_pin_click
        text metrics_pin_click_rate
        text metrics_quartile_95_percent_view
        text metrics_save
        text metrics_save_rate
        text metrics_video_10_s_view
        text metrics_video_avg_watch_time
        text metrics_video_mrc_view
        text metrics_video_start
        text metrics_video_v_50_watch_time
    }
    user_account_analytics_paid {
        text end_date PK
        text start_date PK
        text user_account_id PK
        text summary_metrics_clickthrough
        text summary_metrics_clickthrough_rate
        text summary_metrics_closeup
        text summary_metrics_closeup_rate
        text summary_metrics_engagement
        text summary_metrics_engagement_rate
        text summary_metrics_full_screen_play
        text summary_metrics_full_screen_playtime
        text summary_metrics_impression
        text summary_metrics_outbound_click
        text summary_metrics_outbound_click_rate
        text summary_metrics_pin_click
        text summary_metrics_pin_click_rate
        text summary_metrics_quartile_95_percent_view
        text summary_metrics_save
        text summary_metrics_save_rate
        text summary_metrics_video_10_s_view
        text summary_metrics_video_avg_watch_time
        text summary_metrics_video_mrc_view
        text summary_metrics_video_start
        text summary_metrics_video_v_50_watch_time
    }
    user_account_top_pin_analytics }o--|| pin : "fk"
    pin_analytic_web_daily_metric }o--|| pin_analytics_web : "fk"
    pin_analytic_web_daily_metric }o--|| pin_analytics_web : "fk"
    pin_analytic_web_daily_metric }o--|| pin_analytics_web : "fk"
    pin_analytics_web }o--|| pin : "fk"
    pin_analytic_tablet_daily_metric }o--|| pin_analytics_tablet : "fk"
    pin_analytic_tablet_daily_metric }o--|| pin_analytics_tablet : "fk"
    pin_analytic_tablet_daily_metric }o--|| pin_analytics_tablet : "fk"
    pin_analytics_tablet }o--|| pin : "fk"
    user_account_analytic_daily_metric }o--|| user_account_analytics_organic : "fk"
    user_account_analytic_daily_metric }o--|| user_account_analytics_organic : "fk"
    user_account_analytic_daily_metric }o--|| user_account_analytics_organic : "fk"
    user_account_analytics_organic }o--|| user_account : "fk"
    pin_analytic_mobile_daily_metric }o--|| pin_analytics_mobile : "fk"
    pin_analytic_mobile_daily_metric }o--|| pin_analytics_mobile : "fk"
    pin_analytic_mobile_daily_metric }o--|| pin_analytics_mobile : "fk"
    pin_analytics_mobile }o--|| pin : "fk"
    pin }o--|| pin : "fk"
    user_account_top_video_pin_analytics }o--|| pin : "fk"
    user_account_analytic_daily_metric_paid }o--|| user_account_analytics_paid : "fk"
    user_account_analytic_daily_metric_paid }o--|| user_account_analytics_paid : "fk"
    user_account_analytic_daily_metric_paid }o--|| user_account_analytics_paid : "fk"
    user_account_analytics_paid }o--|| user_account : "fk"
