erDiagram
    app_site_query_param {
        text index PK
        text app_id PK
        text query_param
    }
    app_site_category_param {
        text index PK
        text app_id PK
        text category_param
    }
    app_excluded_url_param {
        text index PK
        text app_id PK
        text excluded_url_param
    }
    app_excluded_ip {
        text index PK
        text app_id PK
        text excluded_ip
    }
    app_excluded_user_agent {
        text index PK
        text app_id PK
        text excluded_user_agent
    }
    app_url {
        text index PK
        text app_id PK
        text url
    }
    app_privacy_coookie_domain {
        text index PK
        text app_id PK
        text privacy_cookie_domain
    }
    app {
        text id PK
        text added_at
        text app_type
        text cnil
        text currency
        text delay
        text e_commerce_tracking
        text exclude_unknown_url
        text gdpr
        text gdpr_data_anonymization
        text gdpr_data_anonymization_mode
        text gdpr_location_recognition
        text gdpr_usermode_enabled
        text keep_url_fragment
        text name
        text organization
        text privacy_cookie_domains_enabled
        text privacy_cookie_expiration_period
        text privacy_use_cookies
        text privacy_use_finger_printing
        text session_id_strict_privacy_mode
        text sharepoint_integration
        text site_search_tracking
        text timezone
        text type
        text updated_at
    }
    event {
        text event_id PK
        text session_id FK
        text website_id FK
        text content_name
        text content_piece
        text content_target
        text custom_event_name
        text download_url
        text event_index
        text goal_id
        text goal_id_label
        text goal_revenue
        text goal_uuid_id
        text goal_uuid_label
        text item_count
        text lost_revenue
        text next_event_title
        text next_event_url
        text order_id
        text outlink_url
        text page_generation_time
        text page_view_index
        text previous_event_title
        text previous_event_url
        text revenue
        text revenue_discount
        text revenue_shipping
        text revenue_subtotal
        text revenue_tax
        text search_category
        text search_keyword
        text search_results_count
        text time_on_page
        text timestamps
        text title
        text type_id
        text type_label
        text url
        text visitor_id
    }
    session_location {
        text session_id PK
        text website_id FK
        text city_name_id
        text city_name_label
        text continent_iso_code_id
        text continent_iso_code_label
        text country_name_id
        text country_name_label
        text latitude
        text longitude
        text metro_code_id
        text metro_code_label
        text organization
        text provider
        text subdivision_1_name_id
        text subdivision_1_name_label
        text subdivision_2_name_id
        text subdivision_2_name_label
        text timestamps
        text visitor_id
    }
    event_custom_variable {
        text event_id PK
        text session_id FK
        text website_id FK
        text dimension_1
        text dimension_2
        text dimension_3
        text dimension_4
        text dimension_5
        text key_1
        text key_2
        text key_3
        text key_4
        text key_5
        text timestamps
        text value_1
        text value_2
        text value_3
        text value_4
        text value_5
        text visitor_id
    }
    session_custom_variables {
        text session_id PK
        text website_id FK
        text dimension_1
        text dimension_2
        text dimension_3
        text dimension_4
        text dimension_5
        text key_1
        text key_2
        text key_3
        text key_4
        text key_5
        text timestamps
        text value_1
        text value_2
        text value_3
        text value_4
        text value_5
        text visitor_id
    }
    session_users {
        text session_id PK
        text website_id FK
        text cookie_id
        text timestamps
        text visitor_days_since_first_session
        text visitor_days_since_last_session
        text visitor_days_since_order
        text visitor_id
        text visitor_returning_id
        text visitor_returning_label
        text visitor_session_number
        text website_name_id
        text website_name_label
    }
    event_consent {
        text event_id PK
        text session_id FK
        text website_id FK
        text action_id
        text action_label
        text form_button_id
        text form_button_label
        text scope_id
        text scope_label
        text source_id
        text source_label
        text timestamps
        text type_ab_testing_personalization
        text type_analytics
        text type_conversion_tracking
        text type_custom_1
        text type_marketing_automation
        text type_remarketing
        text type_user_feedback
        text visitor_id
    }
    session_device_and_platform {
        text session_id PK
        text website_id FK
        text browser_engine
        text browser_fingerprint
        text browser_language_iso_639_id
        text browser_language_iso_639_label
        text browser_name_id
        text browser_name_label
        text browser_version
        text device_brand_id
        text device_brand_label
        text device_model
        text device_type_id
        text device_type_label
        text ipv_4_address
        text ipv_6_address
        text operating_system_id
        text operating_system_label
        text operating_system_version
        text plugin_cookie
        text plugin_director
        text plugin_flash
        text plugin_gear
        text plugin_java
        text plugin_pdf
        text plugin_quicktime
        text plugin_realplayer
        text plugin_silverlight
        text plugin_windowsmedia
        text resolution
        text resolution_height
        text resolution_width
        text timestamps
        text visitor_id
    }
    session_traffic {
        text session_id PK
        text website_id FK
        text campaign_content
        text campaign_id
        text campaign_name
        text keyword
        text medium
        text referrer_type_id
        text referrer_type_label
        text referrer_url
        text source
        text source_medium
        text timestamps
        text visitor_id
    }
    event_website_performance {
        text event_id PK
        text session_id FK
        text website_id FK
        text domain_lookup_time
        text is_entry
        text is_exit
        text page_rendering_time
        text redirections_time
        text server_connection_time
        text server_response_time
        text timestamps
        text timing_dom_interactive
        text timing_event_end
        text visitor_id
    }
    session_goal {
        text index PK
        text session_id PK
        text session_goals
    }
    session_goal_id {
        text index PK
        text session_id PK
        text session_goal_id
    }
    session {
        text session_id PK
        text website_id FK
        text campaign_gclid
        text ecommerce_status_id
        text ecommerce_status_label
        text entry_title
        text entry_url
        text exit_title
        text exit_url
        text is_bounce
        text local_hour
        text second_title
        text second_url
        text timestamps
        text total_abandoned_cart
        text total_cart_addition
        text total_cart_removal
        text total_content_impression
        text total_content_interaction
        text total_custom_event
        text total_download
        text total_ecommerce_conversion
        text total_event
        text total_goal_conversion
        text total_outlink
        text total_page_view
        text total_product_detail_view
        text total_site_search
        text total_time
        text unique_content_impression
        text unique_content_interaction
        text unique_custom_event
        text unique_download
        text unique_outlink
        text unique_page_view
        text unique_searche
        text user_id
        text visitor_id
    }
    product_name {
        text index PK
        text event_id PK
        text product_name
    }
    product_sku {
        text index PK
        text event_id PK
        text product_sku
    }
    product_brand {
        text index PK
        text event_id PK
        text product_sku
    }
    product_price {
        text index PK
        text event_id PK
        text product_price
    }
    product_quantity {
        text index PK
        text event_id PK
        text product_quantity
    }
    product_revenue {
        text index PK
        text event_id PK
        text product_revenue
    }
    product_variant {
        text index PK
        text event_id PK
        text product_variant
    }
    product_category {
        text index PK
        text event_id PK
        text product_category
    }
    product_category_1 {
        text index PK
        text event_id PK
        text product_category_1
    }
    product_category_2 {
        text index PK
        text event_id PK
        text product_category_2
    }
    product_category_3 {
        text index PK
        text event_id PK
        text product_category_3
    }
    product_category_4 {
        text index PK
        text event_id PK
        text product_category_4
    }
    product_category_5 {
        text index PK
        text event_id PK
        text product_category_5
    }
    product_dimension_1 {
        text index PK
        text event_id PK
        text product_dimension_1
    }
    product_dimension_2 {
        text index PK
        text event_id PK
        text product_dimension_2
    }
    product_dimension_3 {
        text index PK
        text event_id PK
        text product_dimension_3
    }
    product_dimension_4 {
        text index PK
        text event_id PK
        text product_dimension_4
    }
    product_dimension_5 {
        text index PK
        text event_id PK
        text product_dimension_5
    }
    product_dimension_6 {
        text index PK
        text event_id PK
        text product_dimension_6
    }
    product_dimension_7 {
        text index PK
        text event_id PK
        text product_dimension_7
    }
    product_dimension_8 {
        text index PK
        text event_id PK
        text product_dimension_8
    }
    product_dimension_9 {
        text index PK
        text event_id PK
        text product_dimension_9
    }
    product_dimension_10 {
        text index PK
        text event_id PK
        text product_dimension_10
    }
    product_dimension_11 {
        text index PK
        text event_id PK
        text product_dimension_11
    }
    product_dimension_12 {
        text index PK
        text event_id PK
        text product_dimension_12
    }
    product_dimension_13 {
        text index PK
        text event_id PK
        text product_dimension_13
    }
    product_dimension_14 {
        text index PK
        text event_id PK
        text product_dimension_14
    }
    product_dimension_15 {
        text index PK
        text event_id PK
        text product_dimension_15
    }
    product_dimension_16 {
        text index PK
        text event_id PK
        text product_dimension_16
    }
    product_dimension_17 {
        text index PK
        text event_id PK
        text product_dimension_17
    }
    product_dimension_18 {
        text index PK
        text event_id PK
        text product_dimension_18
    }
    product_dimension_19 {
        text index PK
        text event_id PK
        text product_dimension_19
    }
    product_dimension_20 {
        text index PK
        text event_id PK
        text product_dimension_20
    }
    event_product {
        text event_id PK
        text session_id FK
        text website_id FK
        text product_count
        text timestamps
        text visitor_id
    }
    event_custom_events {
        text event_id PK
        text session_id FK
        text website_id FK
        text action
        text category
        text name
        text timestamps
        text value
        text visitor_id
    }
    app_site_query_param }o--|| app : "fk"
    app_site_category_param }o--|| app : "fk"
    app_excluded_url_param }o--|| app : "fk"
    app_excluded_ip }o--|| app : "fk"
    app_excluded_user_agent }o--|| app : "fk"
    app_url }o--|| app : "fk"
    app_privacy_coookie_domain }o--|| app : "fk"
    event }o--|| session : "fk"
    event }o--|| app : "fk"
    session_location }o--|| app : "fk"
    event_custom_variable }o--|| session : "fk"
    event_custom_variable }o--|| app : "fk"
    session_custom_variables }o--|| app : "fk"
    session_users }o--|| app : "fk"
    event_consent }o--|| session : "fk"
    event_consent }o--|| app : "fk"
    session_device_and_platform }o--|| app : "fk"
    session_traffic }o--|| app : "fk"
    event_website_performance }o--|| session : "fk"
    event_website_performance }o--|| app : "fk"
    session_goal }o--|| session : "fk"
    session_goal_id }o--|| session : "fk"
    session }o--|| app : "fk"
    product_name }o--|| event_product : "fk"
    product_sku }o--|| event_product : "fk"
    product_brand }o--|| event_product : "fk"
    product_price }o--|| event_product : "fk"
    product_quantity }o--|| event_product : "fk"
    product_revenue }o--|| event_product : "fk"
    product_variant }o--|| event_product : "fk"
    product_category }o--|| event_product : "fk"
    product_category_1 }o--|| event_product : "fk"
    product_category_2 }o--|| event_product : "fk"
    product_category_3 }o--|| event_product : "fk"
    product_category_4 }o--|| event_product : "fk"
    product_category_5 }o--|| event_product : "fk"
    product_dimension_1 }o--|| event_product : "fk"
    product_dimension_2 }o--|| event_product : "fk"
    product_dimension_3 }o--|| event_product : "fk"
    product_dimension_4 }o--|| event_product : "fk"
    product_dimension_5 }o--|| event_product : "fk"
    product_dimension_6 }o--|| event_product : "fk"
    product_dimension_7 }o--|| event_product : "fk"
    product_dimension_8 }o--|| event_product : "fk"
    product_dimension_9 }o--|| event_product : "fk"
    product_dimension_10 }o--|| event_product : "fk"
    product_dimension_11 }o--|| event_product : "fk"
    product_dimension_12 }o--|| event_product : "fk"
    product_dimension_13 }o--|| event_product : "fk"
    product_dimension_14 }o--|| event_product : "fk"
    product_dimension_15 }o--|| event_product : "fk"
    product_dimension_16 }o--|| event_product : "fk"
    product_dimension_17 }o--|| event_product : "fk"
    product_dimension_18 }o--|| event_product : "fk"
    product_dimension_19 }o--|| event_product : "fk"
    product_dimension_20 }o--|| event_product : "fk"
    event_product }o--|| session : "fk"
    event_product }o--|| app : "fk"
    event_custom_events }o--|| session : "fk"
    event_custom_events }o--|| app : "fk"
