erDiagram
    gl_data {
        text _fivetran_id PK
        text fiscal_month
        text fiscal_year
        text month_name
        text mtd_amount
        text qtd_amount
        text reporting
        text scenario
        text segment_1
        text segment_2
        text segment_3
        text segment_4
        text segment_5
        text segment_6
        text segment_7
        text segment_8
        text ytd_amount
    }
    segment_3_data_rollup_level {
        text index PK
        text segment_3_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_3_data {
        text member_id PK
        text active_status
        text attributes
        text code
        text member_type
        text name
        text parent_code
        text parent_id
        text rollup_operator
        text sort
    }
    segment_7_data_rollup_level {
        text index PK
        text segment_7_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_7_data {
        text member_id PK
        text active_status
        text attributes
        text code
        text member_type
        text name
        text parent_code
        text parent_id
        text rollup_operator
        text sort
    }
    segment_5_data_rollup_level {
        text index PK
        text segment_5_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_5_data {
        text member_id PK
        text active_status
        text attributes
        text code
        text member_type
        text name
        text parent_code
        text parent_id
        text rollup_operator
        text sort
    }
    segment_2_data_rollup_level {
        text index PK
        text segment_2_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_2_data {
        text member_id PK
        text active_status
        text attributes
        text code
        text currency_code
        text currency_name
        text member_type
        text name
        text parent_code
        text parent_id
        text rollup_operator
        text sort
    }
    rule_gl {
        text id PK
        text load_item
        text name
    }
    segment_1_data_rollup_level {
        text index PK
        text segment_1_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_1_data {
        text member_id PK
        text account_group
        text account_type
        text active_status
        text attributes
        text code
        text credit_debit
        text currency_type_code
        text currency_type_name
        text member_type
        text name
        text normal_data_input
        text parent_code
        text parent_member_code
        text parent_member_id
        text parent_member_label
        text parent_member_name
        text report_category_name
        text rollup_operator
        text sort
        text trial_balance_account
        text variance
    }
    segment_8_data_rollup_level {
        text index PK
        text segment_8_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_8_data {
        text member_id PK
        text active_status
        text attributes
        text code
        text member_type
        text name
        text parent_code
        text parent_id
        text rollup_operator
        text sort
    }
    segment_4_data_rollup_level {
        text index PK
        text segment_4_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_4_data {
        text member_id PK
        text active_status
        text attributes
        text code
        text member_type
        text name
        text parent_code
        text parent_id
        text rollup_operator
        text sort
    }
    segment_6_data_rollup_level {
        text index PK
        text segment_6_data_member_id PK
        text code
        text id
        text level
        text name
    }
    segment_6_data {
        text member_id PK
        text active_status
        text attributes
        text code
        text member_type
        text name
        text parent_code
        text parent_id
        text rollup_operator
        text sort
    }
    segment_3_data_rollup_level }o--|| segment_3_data : "fk"
    segment_7_data_rollup_level }o--|| segment_7_data : "fk"
    segment_5_data_rollup_level }o--|| segment_5_data : "fk"
    segment_2_data_rollup_level }o--|| segment_2_data : "fk"
    segment_1_data_rollup_level }o--|| segment_1_data : "fk"
    segment_8_data_rollup_level }o--|| segment_8_data : "fk"
    segment_4_data_rollup_level }o--|| segment_4_data : "fk"
    segment_6_data_rollup_level }o--|| segment_6_data : "fk"
