erDiagram
    browser_usage {
        text _fivetran_id PK
        text server_id FK
        text date
        text from_date
        text google_chorme
        text safari
        text safari_mobile
        text to_date
    }
    domain {
        text id PK
        text dkim_host
        text dkim_pending_host
        text dkim_pending_text_value
        text dkim_revoked_host
        text dkim_revoked_text_value
        text dkim_text_value
        text dkim_update_status
        text dkim_verified
        text name
        text return_path_domain
        text return_path_domain_cname_value
        text return_path_domain_verified
        text safe_to_remove_revoked_key_from_dns
        text spf_host
        text spf_text_value
        text weak_dkim
    }
    sender_signature {
        text id PK
        text confirmation_personal_note
        text confirmed
        text dkim_host
        text dkim_pending_host
        text dkim_pending_text_value
        text dkim_revoked_host
        text dkim_revoked_text_value
        text dkim_text_value
        text dkim_update_status
        text dkim_verified
        text domain
        text email_address
        text name
        text reply_to_email_address
        text return_path_domain
        text return_path_domain_cname_value
        text return_path_domain_verified
        text safe_to_remove_revoked_key_from_dns
        text spf_host
        text spf_text_value
        text weak_dkim
    }
    browser_usage_platform {
        text _fivetran_id PK
        text server_id FK
        text date
        text desktop
        text from_date
        text mobile
        text to_date
        text unknown
    }
    message_inbound_to {
        text email PK
        text message_inbound_id PK
        text server_id PK
        text name
    }
    message_inbound_cc {
        text email PK
        text message_inbound_id PK
        text server_id PK
        text name
    }
    message_inbound_header {
        text index PK
        text message_inbound_id PK
        text server_id PK
        text name
        text value
    }
    message_inbound_attachment {
        text index PK
        text message_inbound_id PK
        text server_id PK
        text content_id
        text content_length
        text content_type
        text name
    }
    message_inbound {
        text id PK
        text blocked_reason
        text date
        text from_email
        text from_name
        text html_body
        text mailbox_hash
        text original_recipient
        text reply_to
        text server_id
        text status
        text subject
        text tags
        text text_body
    }
    server {
        text id PK
        text bounce_hook_url
        text click_hook_url
        text color
        text delivery_hook_url
        text delivery_type
        text enable_smtp_api_error_hook
        text inbound_address
        text inbound_domain
        text inbound_hash
        text inbound_hook_url
        text inbound_spam_threshold
        text include_bounce_content_in_hook
        text name
        text open_hook_url
        text post_first_open_only
        text raw_email_enabled
        text server_link
        text smtp_api_activated
        text track_link
        text track_open
    }
    template {
        text id PK
        text associated_server_id PK
        text active
        text alias
        text html_body
        text layout
        text name
        text subject
        text text_body
        text type
    }
    outbound_statistics {
        text _fivetran_id PK
        text server_id FK
        text bounce_rate
        text bounced
        text from_date
        text opens
        text sent
        text smtp_api_error
        text spam_complaint
        text spam_complaint_rate
        text to_date
        text total_click
        text total_tracked_link_sent
        text tracked
        text unique_link_clicked
        text unique_open
        text with_client_recorded
        text with_link_tracking
        text with_open_tracking
        text with_platform_recorded
        text with_read_time_recorded
    }
    message_outbound_to {
        text email PK
        text message_outbound_id PK
        text server_id PK
        text name
    }
    message_outbound_recipient {
        text index PK
        text message_outbound_id PK
        text server_id PK
        text recipient
    }
    message_outbound_cc {
        text email PK
        text message_outbound_id PK
        text server_id PK
        text name
    }
    message_outbound_bcc {
        text email PK
        text message_outbound_id PK
        text server_id PK
        text name
    }
    message_outbound_attachment {
        text index PK
        text message_outbound_id PK
        text server_id PK
        text attachment
    }
    message_outbound_event {
        text index PK
        text message_outbound_id PK
        text server_id PK
        text delivery_message
        text destination_ip
        text destination_server
        text received_at
        text recipient
        text summary
        text type
    }
    message_outbound {
        text id PK
        text body
        text html_body
        text received_at
        text received_from
        text sandboxed
        text server_id
        text status
        text subject
        text track_links
        text track_open
    }
    message_outbound_click {
        text id PK
        text server_id PK
        text click_location
        text client_company
        text client_family
        text client_name
        text geo_coords
        text geo_country
        text geo_country_iso_code
        text geo_ip
        text original_link
        text os_company
        text os_family
        text os_name
        text platform
        text received_at
        text recipient
        text record_type
        text tags
        text user_agent
    }
    bounce {
        text id PK
        text server_id PK
        text message_id FK
        text bounced_at
        text can_activate
        text description
        text detail
        text dump_available
        text email
        text inactive
        text name
        text received_from
        text record_type
        text subject
        text tags
        text type
        text type_code
    }
    message_outbound_open {
        text id PK
        text server_id PK
        text client_company
        text client_family
        text client_name
        text geo_coords
        text geo_country
        text geo_country_iso_code
        text geo_ip
        text os_company
        text os_family
        text os_name
        text platform
        text read_seconds
        text received_at
        text recipient
        text record_type
        text stream
        text tags
        text user_agent
    }
    email_client_usage {
        text _fivetran_id PK
        text server_id FK
        text apple_mail
        text date
        text from_date
        text gmail
        text outlook
        text to_date
    }
    platform_usage {
        text _fivetran_id PK
        text server_id FK
        text date
        text desktop
        text from_date
        text mobile
        text to_date
        text unknown
        text web_mail
    }
    suppression {
        text _fivetran_id PK
        text message_stream_id FK
        text server_id FK
        text created_at
        text email_address
        text origin
        text suppression_reason
    }
    bounce_count {
        text _fivetran_id PK
        text server_id FK
        text date
        text from_date
        text hard_bounce
        text smtp_api_error
        text soft_bounce
        text to_date
        text transient
    }
    message_stream {
        text id PK
        text server_id PK
        text archived_at
        text created_at
        text description
        text expected_purge_date
        text name
        text subscription_management_configuration_unsubscribe_handling_type
        text type
        text updated_at
    }
    click_location {
        text _fivetran_id PK
        text server_id FK
        text date
        text from_date
        text html
        text text
        text to_date
    }
    browser_usage }o--|| server : "fk"
    browser_usage_platform }o--|| server : "fk"
    message_inbound_to }o--|| message_inbound : "fk"
    message_inbound_to }o--|| message_inbound : "fk"
    message_inbound_cc }o--|| message_inbound : "fk"
    message_inbound_cc }o--|| message_inbound : "fk"
    message_inbound_header }o--|| message_inbound : "fk"
    message_inbound_header }o--|| message_inbound : "fk"
    message_inbound_attachment }o--|| message_inbound : "fk"
    message_inbound_attachment }o--|| message_inbound : "fk"
    template }o--|| server : "fk"
    outbound_statistics }o--|| server : "fk"
    message_outbound_to }o--|| message_outbound : "fk"
    message_outbound_to }o--|| message_outbound : "fk"
    message_outbound_recipient }o--|| message_outbound : "fk"
    message_outbound_recipient }o--|| message_outbound : "fk"
    message_outbound_cc }o--|| message_outbound : "fk"
    message_outbound_cc }o--|| message_outbound : "fk"
    message_outbound_bcc }o--|| message_outbound : "fk"
    message_outbound_bcc }o--|| message_outbound : "fk"
    message_outbound_attachment }o--|| message_outbound : "fk"
    message_outbound_attachment }o--|| message_outbound : "fk"
    message_outbound_event }o--|| message_outbound : "fk"
    message_outbound_event }o--|| message_outbound : "fk"
    message_outbound_click }o--|| message_outbound : "fk"
    message_outbound_click }o--|| server : "fk"
    bounce }o--|| server : "fk"
    bounce }o--|| message_outbound : "fk"
    message_outbound_open }o--|| message_outbound : "fk"
    message_outbound_open }o--|| server : "fk"
    email_client_usage }o--|| server : "fk"
    platform_usage }o--|| server : "fk"
    suppression }o--|| server : "fk"
    suppression }o--|| message_stream : "fk"
    bounce_count }o--|| server : "fk"
    message_stream }o--|| server : "fk"
    click_location }o--|| server : "fk"
