erDiagram
    visit_customer {
        text id PK
        text visit_key FK
        text customer_id
    }
    feedback_result {
        text id PK
        text answer_key FK
        text branch_key FK
        text question_key FK
        text question_type_key FK
        text visit_key FK
        text date_key
        text event_timestamp
        text text_answer
        text time_key
        text time_seconds
    }
    visit_call_type {
        text id PK
        text name
    }
    device_time {
        text id PK
        text agent_key FK
        text branch_key FK
        text date_key FK
        text device_key FK
        text unit_key FK
        text asf_device_status_key
        text device_connect_duration
        text device_disconnect_duration
        text device_num_disconnects
        text no_data
    }
    mark_transaction_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    appointment_start_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    feedback_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    call_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    entry_point {
        text id PK
        text name
        text origin_id
    }
    end_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    appointment {
        text id PK
        text appointment_status_key FK
        text arrival_status_key FK
        text branch_key FK
        text origin_id FK
        text resource_key FK
        text service_key FK
        text cancelled_date_key
        text client_key
        text count_service
        text created_date_key
        text created_time_key
        text date_key
        text days_cancelled_before
        text days_to_appointment
        text duration
        text end_time_key
        text lateness
        text start_time_key
        text tardiness
        text transaction_time
        text updated_count
        text waiting_time
        text walking_time
        text wrapup_time
    }
    agent_device_controller_status {
        text id PK
        text agent_key FK
        text branch_key FK
        text device_controller_key FK
        text device_controller_status_key FK
        text last_device_controller_event_type_key FK
        text last_event_time
        text last_status_time
        text origin_id
    }
    service {
        text id PK
        text name
        text origin_id
    }
    visit_transaction_outcome {
        text id PK
        text name
    }
    device_controller_event_type {
        text id PK
        text name
    }
    daemon_status {
        text id PK
        text status
    }
    staff_session_end_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    device_status {
        text id PK
        text status
    }
    feedback_answer {
        text id PK
        text numeric_answer
        text text_answer
    }
    delivered_service {
        text id PK
        text branch_key FK
        text outcome_key FK
        text queue_key FK
        text queue_type_key FK
        text service_key FK
        text service_point_key FK
        text staff_key FK
        text visit_key FK
        text date_key
        text delivered_service_key
        text time_key
        text time_seconds
        text transaction_time
        text waiting_time
    }
    service_delivereds {
        text id PK
        text origin_id
        text service_delivered
    }
    device_event_type {
        text id PK
        text name
    }
    mark_transaction {
        text id PK
        text branch_key FK
        text mark_key FK
        text mark_type_key FK
        text queue_key FK
        text queue_type_key FK
        text service_key FK
        text service_point_key FK
        text staff_key FK
        text visit_key FK
        text date_key
        text time_key
        text time_seconds
        text transaction_time
        text waiting_time
    }
    jiql_event_type {
        text id PK
        text name
    }
    appointment_status {
        text id PK
        text status
    }
    mark_type {
        text id PK
        text name
        text origin_id
    }
    daemon_event_type {
        text id PK
        text name
    }
    fact_agent_jiql_event {
        text id PK
        text agent_key FK
        text date_key FK
        text jiql_event_type_key FK
        text time_key FK
        text asf_agent_status_key
        text event_timestamp
        text time_seconds
    }
    service_point {
        text id PK
        text name
        text origin_id
    }
    staff_session {
        text id PK
        text branch_key FK
        text session_outcome_key FK
        text staff_key FK
        text date_key
        text end_time_key
        text end_timestamp
        text idle_time
        text served_count
        text serving_time
        text start_timestamp
        text store_next_time
        text time_key
        text time_seconds
        text total_time
        text visits_served
        text wrapup_time
    }
    agent_device_status {
        text id PK
        text agent_key FK
        text branch_key FK
        text device_key FK
        text device_status_key FK
        text last_device_event_type_key FK
        text unit_key FK
        text device_event_time
        text device_status_time
        text origin_id
    }
    dim_unit_type {
        text id PK
        text name
    }
    appointment_service {
        text id PK
        text appointment_id FK
        text service_key FK
        text served
    }
    daemon_version {
        text id PK
        text version
    }
    staff_session_start_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    dim_device_type {
        text id PK
        text name
    }
    appointment_customer {
        text id PK
        text appointment_id FK
        text customer_id FK
        text booked
        text served
    }
    appointment_end_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    delivered_service_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    resource {
        text id PK
        text branch_origin_id
        text name
        text origin_id
    }
    branch {
        text id PK
        text city
        text country
        text latitude
        text longitude
        text name
        text origin_id
        text time_zone
    }
    question_type {
        text id PK
        text name
    }
    appointment_created_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    staff_session_outcome {
        text id PK
        text name
    }
    jiql_status {
        text id PK
        text status
    }
    time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    queue {
        text id PK
        text name
        text origin_id
    }
    mark {
        text id PK
        text mark_type_key FK
        text name
        text origin_id
    }
    queue_type {
        text id PK
        text name
    }
    device_controller_time {
        text id PK
        text agent_key FK
        text branch_key FK
        text date_key FK
        text device_controller_key FK
        text asf_dc_status_key
        text connect_duration
        text disconnect_duration
        text no_data
        text num_disconnects
    }
    entered_queue_time {
        text id PK
        text am_pm
        text hour
        text hour_24
        text interval_10_min
        text interval_10_min_24
        text interval_15_min
        text interval_15_min_24
        text interval_30_min
        text interval_30_min_24
        text interval_5_min
        text interval_5_min_24
        text minute
        text time
    }
    staff {
        text id PK
        text first_name
        text full_name
        text last_name
        text origin_id
        text user_name
    }
    appointment_arrival_status {
        text id PK
        text arrival_status
    }
    device_controller_status {
        text id PK
        text status
    }
    jiql_version {
        text id PK
        text version
    }
    feedback_question {
        text id PK
        text question
        text start_date
    }
    appointment_cancelled_date {
        text id PK
        text day_of_month
        text day_of_week
        text day_of_week_name
        text day_of_week_name_en
        text full_date
        text month
        text month_name
        text month_name_en
        text quarter
        text week_number
        text week_number_iso
        text year
    }
    agent_daemon_event {
        text id PK
        text agent_key FK
        text daemon_event_type_key FK
        text date_key FK
        text time_key FK
        text asf_agent_status_key
        text event_timestamp
        text time_seconds
    }
    mark_transaction_date {
        text id PK
        text day_of_month
        text day_of_week
        text day_of_week_name
        text day_of_week_name_en
        text full_date
        text month
        text month_name
        text month_name_en
        text quarter
        text week_number_iso
        text year
    }
    device_controller_event {
        text id PK
        text agent_key FK
        text branch_key FK
        text date_key FK
        text dc_event_type_key FK
        text device_controller_key FK
        text time_key FK
        text asf_dc_status_key
        text event_timestamp
        text time_seconds
    }
    unit {
        text id PK
        text branch_key
        text device_controller_key
        text end_date
        text logic_id
        text name
        text origin_id
        text start_date
        text unit_id
        text unit_template
        text unit_type_key
    }
    device {
        text id PK
        text unit_key FK
        text device_type_key
        text end_date
        text firmware_version
        text ip
        text logic_id
        text name
        text origin_id
        text start_date
    }
    date {
        text id PK
        text day_of_month
        text day_of_week
        text day_of_week_name
        text day_of_week_name_en
        text full_date
        text month
        text month_name
        text month_name_en
        text quarter
        text week_number_iso
        text year
    }
    work_profile {
        text id PK
        text branch_origin_id
        text client_key
        text end_date
        text name
        text origin_id
        text start_date
    }
    appointment_created_date {
        text id PK
        text day_of_month
        text day_of_week
        text day_of_week_name
        text day_of_week_name_en
        text full_date
        text month
        text month_name
        text month_name_en
        text quarter
        text week_number
        text week_number_iso
        text year
    }
    device_event {
        text id PK
        text agent_key FK
        text branch_key FK
        text date_key FK
        text device_event_type_key FK
        text device_key FK
        text time_key FK
        text unit_key FK
        text asf_device_status_key
        text event_timestamp
        text time_seconds
    }
    visit_transaction {
        text id PK
        text branch_key FK
        text entry_point_key FK
        text outcome_key FK
        text queue_key FK
        text queue_type_key FK
        text service_key FK
        text service_point_key FK
        text staff_key FK
        text visit_call_type_key FK
        text visit_key FK
        text visit_outcome_key FK
        text work_profile_key FK
        text call_time_key
        text call_time_of_day
        text call_timestamp
        text date_key
        text end_time_key
        text end_time_of_day
        text enter_queue_time_of_day
        text entered_queue_time_key
        text entered_queue_timestamp
        text is_appointment
        text recycle_count
        text service_transaction_time_level
        text staff_transaction_time
        text time_seconds
        text transaction_time
        text transaction_time_vs_service_level
        text vertical_message_key
        text waiting_time
        text waiting_time_service_level
        text waiting_time_vs_service_level
        text walking_time
        text wrapup_time
    }
    agent {
        text id PK
        text daemon_version_key FK
        text jiql_version_key FK
        text end_date
        text host
        text name
        text original_id
        text start_date
    }
    outcome {
        text id PK
        text branch_origin_id
        text client_key
        text end_date
        text name
        text origin_id
        text start_date
    }
    feedback_date {
        text id PK
        text day_of_month
        text day_of_week
        text day_of_week_name
        text day_of_week_name_en
        text full_date
        text month
        text month_name
        text month_name_en
        text quarter
        text week_number_iso
        text year
    }
    device_controller {
        text id PK
        text branch_key FK
        text end_date
        text name
        text origin_id
        text start_date
        text unit_id
        text unit_template
    }
    visit {
        text id PK
        text appointment_id FK
        text created_timestamp
        text custom_1
        text custom_2
        text custom_3
        text custom_4
        text custom_5
        text ticket_id
        text vip_level
        text visit_type
    }
    visit_customer }o--|| visit : "fk"
    feedback_result }o--|| question_type : "fk"
    feedback_result }o--|| feedback_question : "fk"
    feedback_result }o--|| visit : "fk"
    feedback_result }o--|| feedback_answer : "fk"
    feedback_result }o--|| branch : "fk"
    device_time }o--|| device : "fk"
    device_time }o--|| unit : "fk"
    device_time }o--|| agent : "fk"
    device_time }o--|| date : "fk"
    device_time }o--|| branch : "fk"
    appointment }o--|| resource : "fk"
    appointment }o--|| service : "fk"
    appointment }o--|| appointment_status : "fk"
    appointment }o--|| appointment : "fk"
    appointment }o--|| branch : "fk"
    appointment }o--|| appointment_arrival_status : "fk"
    agent_device_controller_status }o--|| device_controller_event_type : "fk"
    agent_device_controller_status }o--|| agent : "fk"
    agent_device_controller_status }o--|| device_controller_status : "fk"
    agent_device_controller_status }o--|| branch : "fk"
    agent_device_controller_status }o--|| device_controller : "fk"
    delivered_service }o--|| service_point : "fk"
    delivered_service }o--|| service : "fk"
    delivered_service }o--|| outcome : "fk"
    delivered_service }o--|| visit : "fk"
    delivered_service }o--|| staff : "fk"
    delivered_service }o--|| queue : "fk"
    delivered_service }o--|| branch : "fk"
    delivered_service }o--|| queue_type : "fk"
    mark_transaction }o--|| service_point : "fk"
    mark_transaction }o--|| mark : "fk"
    mark_transaction }o--|| service : "fk"
    mark_transaction }o--|| visit : "fk"
    mark_transaction }o--|| staff : "fk"
    mark_transaction }o--|| queue : "fk"
    mark_transaction }o--|| branch : "fk"
    mark_transaction }o--|| mark_type : "fk"
    mark_transaction }o--|| queue_type : "fk"
    fact_agent_jiql_event }o--|| jiql_event_type : "fk"
    fact_agent_jiql_event }o--|| date : "fk"
    fact_agent_jiql_event }o--|| agent : "fk"
    fact_agent_jiql_event }o--|| time : "fk"
    staff_session }o--|| staff_session_outcome : "fk"
    staff_session }o--|| staff : "fk"
    staff_session }o--|| branch : "fk"
    agent_device_status }o--|| device_event_type : "fk"
    agent_device_status }o--|| device_status : "fk"
    agent_device_status }o--|| device : "fk"
    agent_device_status }o--|| unit : "fk"
    agent_device_status }o--|| agent : "fk"
    agent_device_status }o--|| branch : "fk"
    appointment_service }o--|| appointment : "fk"
    appointment_service }o--|| service : "fk"
    appointment_customer }o--|| appointment : "fk"
    appointment_customer }o--|| visit_customer : "fk"
    mark }o--|| mark_type : "fk"
    device_controller_time }o--|| agent : "fk"
    device_controller_time }o--|| date : "fk"
    device_controller_time }o--|| branch : "fk"
    device_controller_time }o--|| device_controller : "fk"
    agent_daemon_event }o--|| daemon_event_type : "fk"
    agent_daemon_event }o--|| date : "fk"
    agent_daemon_event }o--|| agent : "fk"
    agent_daemon_event }o--|| time : "fk"
    device_controller_event }o--|| device_event_type : "fk"
    device_controller_event }o--|| agent : "fk"
    device_controller_event }o--|| date : "fk"
    device_controller_event }o--|| branch : "fk"
    device_controller_event }o--|| device_controller : "fk"
    device_controller_event }o--|| time : "fk"
    device }o--|| unit : "fk"
    device_event }o--|| device : "fk"
    device_event }o--|| unit : "fk"
    device_event }o--|| agent : "fk"
    device_event }o--|| date : "fk"
    device_event }o--|| branch : "fk"
    device_event }o--|| time : "fk"
    device_event }o--|| device_event_type : "fk"
    visit_transaction }o--|| entry_point : "fk"
    visit_transaction }o--|| service_point : "fk"
    visit_transaction }o--|| visit_transaction_outcome : "fk"
    visit_transaction }o--|| service : "fk"
    visit_transaction }o--|| visit_call_type : "fk"
    visit_transaction }o--|| work_profile : "fk"
    visit_transaction }o--|| outcome : "fk"
    visit_transaction }o--|| visit : "fk"
    visit_transaction }o--|| staff : "fk"
    visit_transaction }o--|| queue : "fk"
    visit_transaction }o--|| branch : "fk"
    visit_transaction }o--|| queue_type : "fk"
    agent }o--|| jiql_version : "fk"
    agent }o--|| daemon_version : "fk"
    device_controller }o--|| branch : "fk"
    visit }o--|| appointment : "fk"
