erDiagram
    survey_response_answered_question {
        text question_id PK
        text response_id PK
        text answer
        text comment
        text question_title
        text question_type
        text selected_option_id
    }
    survey_response {
        text id PK
        text anon_visitor_id
        text identities
        text ip_address
        text nps_category
        text nps_reason
        text nps_respondent_id
        text nps_response_uri
        text nps_score
        text nps_time
        text nudge_id
        text nudge_name
        text page
        text referrer
        text time
        text token
        text user_agent
    }
    survey_response_answered_question }o--|| survey_response : "fk"
