erDiagram
    custom_field_limited_to_team {
        text team_id PK
        text custom_field_id PK
    }
    custom_field {
        text id PK
        text group_id FK
        text organization_id FK
        text archived
        text conditional_boolean_value
        jsonb conditional_list_value
        text conditional_parent_custom_field
        text conditional_string_value
        text created
        text creator
        text default_boolean_value
        jsonb default_multi_value
        text default_string_value
        text default_value
        text description
        text display_null_value
        text display_on_create_page
        text display_on_filter
        text display_on_profile
        text external_description
        text external_name
        jsonb extra
        text is_editable
        text is_hyperlinkable
        text is_required
        text name
        jsonb option
        text option_display_type
        jsonb options_new
        text precedence
        text slug
        text tag_owner
        text tag_type
        text updated
        text used_to_generate_outbox_email_list
    }
    issue_management_search_term {
        text index PK
        text issue_management_id PK
        text term
    }
    issue_management_category {
        text index PK
        text issue_management_id PK
        text category
    }
    issue_management_magic_board {
        text index PK
        text issue_management_id PK
        text magic_board
    }
    issue_management_team {
        text issue_management_id PK
        text team_id PK
    }
    issue_management_organization {
        text issue_management_id PK
        text oragnization_id PK
    }
    issue_management_participant {
        text participant_id PK
        text issue_management_id PK
    }
    issue_management {
        text id PK
        text creator_id FK
        text archived
        text can_be_tagged_to_interaction
        jsonb category
        text converted
        text cost
        text creator_edit_only
        text creator_username
        text deadline
        text defaults
        text due_date
        jsonb extra
        text grassroots_order
        text grassroots_page_layout_type
        text grassroots_vanity_url_slug
        text icon
        text image_url
        text is_carryover
        text is_grassroots_issue
        text is_issue
        text is_limited_to_creator
        text is_visible_to_partner
        text issue_expert
        text long_description
        jsonb management_statistics
        text name
        text number_of_campaign
        text number_of_campaign_action
        text number_of_interaction
        text parent
        text priority
        text project_type
        text region_tag
        text related_region
        text remove_with_stance
        text resource_uri
        text short_description
        text shown_in_table
        text year
    }
    bulk_email_search_param_dehydrate {
        text index PK
        text _fivetran_id PK
        text bulk_email_data_id PK
        text bulk_email_id PK
        text name
    }
    bulk_email_search_param_most_recent {
        text index PK
        text _fivetran_id PK
        text bulk_email_data_id PK
        text bulk_email_id PK
        text param
    }
    bulk_email_search_param_minor_role {
        text index PK
        text _fivetran_id PK
        text bulk_email_data_id PK
        text bulk_email_id PK
        text id
    }
    bulk_email_search_param_staffer_chamber {
        text index PK
        text _fivetran_id PK
        text bulk_email_data_id PK
        text bulk_email_id PK
        text id
    }
    bulk_email_search_param_added_id {
        text index PK
        text _fivetran_id PK
        text bulk_email_data_id PK
        text bulk_email_id PK
        text id
    }
    bulk_email_search_param {
        text _fivetran_id PK
        text bulk_email_data_id PK
        text bulk_email_id PK
        text for_outbox
        text hygiene_staffer_type
        text ph_current
        text show_in_quicksearch
        text staffer_tittle_deleted_id
        text staffer_tittle_query_set_list
        text staffer_tittle_searchify_count
    }
    bulk_email_region {
        text index PK
        text bulk_email_data_id PK
        text bulk_email_id PK
        text region
    }
    bulk_email_data {
        text id PK
        text bulk_email_id PK
        jsonb added_id
        text data_type
        jsonb deleted_id
        text name
        text quorum_dat_type
        text reference_hash
        text selection_type
        text text
    }
    bulk_email {
        text id PK
        text user_id FK
        text ab_test
        text action
        text aggregate_click
        text aggregate_open
        text aggregate_unsubscribe
        jsonb ai_suggestion
        text archived
        text attachment
        text attempted_resend_count
        jsonb bcc_rcpt
        text bounce
        text campaign
        jsonb cc_rcpts
        text click
        text click_rate
        text compose_tool
        text content_version
        text created
        text current_status
        text custom_event
        text email_count
        text excluded_email_count
        text excluded_person_count
        text excluded_press_count
        text excluded_supporter_count
        jsonb excludes_json_data
        jsonb excludes_json_old
        text external_id
        jsonb extra
        jsonb failed_recipient
        text from_address
        text from_name
        text from_user
        text html_content
        text initial_open
        text is_abtest
        text is_custom_unsubscribe
        text is_draft
        text is_moved
        text is_scheduled
        text is_updating
        jsonb json_content
        text last_updated
        text must_send_as_creator
        text open_rate
        text opens
        text percent_opened
        text person_count
        text press_count
        text reply_count
        text reply_to_address
        text reply_to_assignments
        text reply_to_name
        text reply_to_user
        text root_bulk_email
        text saved_by_user
        text scheduled_send_time
        jsonb selection_json_data
        jsonb selection_json_old
        text send_from_assignment
        text sent_datetime
        text should_cc_all
        text should_stagger_send
        text subject
        text supporter_bounce
        text supporter_count
        text unsubscribe
        text unsubscribe_enabled
        text updated
        text use_personal_email
        jsonb variant
        text variant_of
        text was_imported
        text winner
        text winner_of
    }
    message_event {
        text id PK
        text bulk_email_id FK
        text archived
        text event_id
        text event_name
        text event_timestamp
        text event_type
        jsonb extra
        text send_email
    }
    bill_amendment_sponsor {
        text bill_amendment_id PK
        text sponsor PK
    }
    bill_amendment_text {
        text text PK
        text bill_amendment_id PK
    }
    bill_amendment {
        text id PK
        text bill FK
        jsonb action
        jsonb alert_cache
        text amendment_type
        text bill_id
        text congress_number
        text created
        text description
        text dms_id
        jsonb extra
        text fts_strip_level
        text house_number
        text label
        text last_action_text
        text number
        text number_of_cosponsor
        text offered_date
        text primary_party
        text region
        text resource_uri
        text rules_number
        text rules_status
        text snippet
        text source
        text status
        text status_date
        text text
        text title
        text updated
        text word_count
    }
    users_current_region {
        text index PK
        text users_id PK
        text current_region
    }
    users_other_persona {
        text index PK
        text users_id PK
        text other_personas
    }
    users_permissioned_region {
        text index PK
        text users_id PK
        text permissioned_region
    }
    users_search_data_type_order {
        text index PK
        text users_id PK
        text search_data_type_order
    }
    users_sidebar_setting_list {
        text index PK
        text users_id PK
        text sidebar_settings_list
    }
    users {
        text id PK
        text user_info_organization_id FK
        text date_joined
        text email
        jsonb extra
        text first_name
        text is_active
        text last_name
        text name
        text user_info_accepted_terms_and_condition
        text user_info_alert_default_search_filter
        text user_info_amendment_default_search_filter
        text user_info_article_default_search_filter
        text user_info_attachment_default_search_filter
        text user_info_bill_default_search_filter
        text user_info_bulk_action_max_size
        text user_info_campaign_columns_list
        text user_info_can_access_all_org_region
        text user_info_can_access_campaign_finance
        text user_info_can_access_custom_fields_management
        text user_info_can_access_grassroot
        text user_info_can_access_issue_management
        text user_info_can_access_media_monitoring
        text user_info_can_access_media_relation
        text user_info_can_access_mobile_developer_tool
        text user_info_can_access_note
        text user_info_can_access_outbox
        text user_info_can_access_pac
        text user_info_can_change_action_center_setting
        text user_info_can_only_create_single_user_issue
        text user_info_can_see_all_campaign
        text user_info_can_see_all_event
        text user_info_can_see_all_file
        text user_info_can_see_all_user
        text user_info_can_see_any_previous_outbox_email
        text user_info_can_see_supporters_and_custom_org
        text user_info_can_see_supporters_based_on_region
        text user_info_can_send_from_any_outbox
        text user_info_can_use_mobile_app
        text user_info_current_preset_name
        text user_info_current_project
        text user_info_date_accepted_terms_and_condition
        jsonb user_info_default_limited_to_team
        text user_info_default_search_data_type
        text user_info_document_default_search_filter
        text user_info_email_signature
        text user_info_employee_id
        text user_info_event_default_search_filter
        jsonb user_info_extra
        text user_info_feature_cache_1_1
        text user_info_feature_cache_1_6
        text user_info_full_name
        text user_info_id
        text user_info_initial
        text user_info_legislator_default_search_filter
        text user_info_limit_from_default_project
        text user_info_note_default_search_filter
        text user_info_org_admin
        text user_info_pacc_user_id
        text user_info_pacc_version
        jsonb user_info_permanent_mobile_login_token
        text user_info_person_default_search_filter
        text user_info_persona
        text user_info_phone_number
        text user_info_preset_region
        text user_info_press_contact_default_search_filter
        text user_info_public_organization_default_search_filter
        text user_info_push_notification_unseen_count
        text user_info_related_username
        text user_info_search_is_table_view
        text user_info_search_should_hide_filter
        text user_info_should_hide_team_permissionining_in_form
        text user_info_single_login
        text user_info_staffer_default_search_filter
        text user_info_supporter_default_search_filter
        text user_info_two_factor_status
        text user_info_user_persona
        text user_info_user_role
        jsonb user_info_visited_feature_cache
        text user_info_vote_default_search_filter
        text username
    }
    organization_allowed_user_domain {
        text index PK
        text organization_id FK
        text allowed_user_domain
    }
    organization_allowed_domain {
        text index PK
        text organization_id PK
        text domain
    }
    organization_interaction_type {
        text index PK
        text organization_id PK
        text internal_interaction_type
    }
    organization_relationship_type {
        text index PK
        text organization_id PK
        text internal_relationship_type
    }
    organization_qp_executive {
        text index PK
        text organization_id PK
        text qp_executive
    }
    organization_qp_legislative_data {
        text index PK
        text organization_id PK
        text qp_legislative_data
    }
    organization_qp_legislative_profile {
        text index PK
        text organization_id PK
        text qp_legislative_profile
    }
    organization_qp_legislative {
        text index PK
        text organization_id PK
        text qp_legislative
    }
    organization_qp_official_document {
        text index PK
        text organization_id PK
        text qp_official_document
    }
    organization_qp_regulation {
        text index PK
        text organization_id PK
        text qp_regulation
    }
    organization_qp_staffer {
        text index PK
        text organization_id PK
        text qp_staffer
    }
    organization_qp_state {
        text index PK
        text organization_id PK
        text qp_state
    }
    organization_ip_address {
        text index PK
        text organization_id PK
        text ip_address
    }
    organization_qp_grassroot {
        text index PK
        text organization_id PK
        text qp_grassroot
    }
    organization_qp_international {
        text index PK
        text organization_id PK
        text qp_international
    }
    organization_qp_local {
        text index PK
        text organization_id PK
        text qp_local
    }
    organization_qp_media {
        text index PK
        text organization_id PK
        text qp_media
    }
    organization_qp_media_relation {
        text index PK
        text organization_id PK
        text qp_media_relaton
    }
    organization_cs_manager {
        text index PK
        text organization_id PK
        text id
    }
    organization_partner {
        text index PK
        text organization_id PK
        text partner_id
    }
    organization {
        text id PK
        text account_type
        text active_client
        text administrator
        text agreed_to_texting_user
        text archived
        text auto_enrich_supporter
        text can_see_partners_user
        text can_use_independent_campaign
        text created
        text cs_managers_username
        jsonb custom_alert_ordering
        text custom_session_timeout
        text date_archived
        text datetime_agreed_to_texting
        text default_domain
        text default_forward_recipient
        text deliver_supporter_message
        text deliver_supporter_messages
        text email_limit
        text email_limit_percentage
        text i_360_organization
        text i_360_organization_and_quorum_client
        text is_approved
        text limit_to_cs_manager
        jsonb log_interaction_json
        text lower_tier_bound
        text max_contact
        text max_csv_size
        text max_email_alert
        text max_member
        text max_project
        text max_social_account
        text name
        text onboarding_type
        jsonb outbox_domain_dict
        text pacc_company_id
        text pad_unique_identifier
        text partner_name
        text phone_number
        text qp_action_center
        text qp_campaign_finance
        text qp_consultant
        text qp_contacts_document
        text qp_custom_contact
        text qp_custom_data
        text qp_custom_event
        text qp_custom_outbox
        text qp_custom_permission
        text qp_eu
        text qp_external_interaction
        text qp_external_relationship
        text qp_federal
        jsonb qp_grass_root
        text qp_internal_relationship
        jsonb qp_international
        text qp_legislation_page
        text qp_live_chat
        jsonb qp_local
        text qp_local_agenda
        jsonb qp_media_monitoring
        jsonb qp_media_relation
        text qp_officials_outbox
        text qp_pac
        text qp_project_management
        text qp_stakeholder
        text qp_unique_ids_in_download
        text require_issue_on_interaction
        text require_issue_on_outbox
        text share_all_custom_region
        text should_display_grassroots_registration_action
        text should_limit_editing_notes_to_admins_and_creator
        text should_org_admin_see_all_org_data
        text should_share_with_partners_by_default
        text should_show_only_users_on_team
        text sms_limit
        text sms_messages_toward_limit
        text sso_enabled_for_all_user
        text sso_profile
        text subdomain
        text trial_expiration
        text unsubscribe_link_text
        text updated
        text upper_tier_bound
        text zapier_token
    }
    custom_field_group {
        text id PK
        text organization_id FK
        text user_id FK
        text created
        text creator
        text data_type
        jsonb extra
        text name
        text organization
        text precedence
        text resource_uri
        text updated
        text users
    }
    committee_keyword {
        text keyword_id PK
        text committee_id PK
    }
    committee {
        text id PK
        text abbrev
        text address
        text chairs_string
        text code
        text committee
        text created
        jsonb facebook_url_array
        text fax
        text icon
        text kw_abbrev
        text meeting_document
        text name
        text num_dem_member
        text num_female_member
        text num_ind_member
        text num_male_member
        text num_member
        text num_rep_member
        text parent_committee_abbrev
        text parent_committee_name
        text ph_ie_id
        text ph_lc_org_id
        text ph_ls_core_organization_id
        text phone
        text rank
        text ranking_members_string
        text region
        text search_name
        text state_name
        text type
        text updated
        text url
        text url_minority
        text witnesses
        text wiw_name
    }
    supporter_action_project {
        text project PK
        text supporter_action_id PK
    }
    supporter_action_region {
        text index PK
        text supporter_action_id PK
        text region
    }
    supporter_action {
        text id PK
        text bulk_email_id FK
        text organization_id FK
        text person_id FK
        text supporter_id FK
        text action_center
        text amount
        text archived
        jsonb audit_trail
        jsonb cache_json
        text call_duration
        text campaign_id
        text click
        text confirmed
        text created
        text date
        text delivered
        text delivered_timestamp
        text delivery_id
        jsonb extra
        text failed_delivery
        text first_open
        text from_grassroot
        text http_referer
        text humanized_text
        text interaction_type
        jsonb link_dict
        text message_status
        text note_type
        text num_attempt
        text opens
        text payroll_frequency_type
        text person
        text points_earned
        text raw_content
        text searchable_date
        text social_media_type
        text source_type
        text subject
        text submitting_org_name
        text supporter
        text text
        jsonb time_stamp
        text transaction_method_type
        text type
        text unique_identifier
        text updated
        text utm_campaign
        text utm_content
        text utm_medium
        text utm_source
        text utm_term
    }
    municipality {
        text id PK
        jsonb extra
        text fips_code
        text full_fips_string
        text geojson
        text legislator
        text name
        text number
        text number_string
        text population
        text state_abbrev
    }
    team_member {
        text index PK
        text team_id PK
        text member
    }
    team {
        text id PK
        text organization_id FK
        text archived
        text defaults
        text name
        text organization
        text resource_uri
    }
    contact {
        text id PK
        text public_organization FK
        text user_id FK
        text activated
        text active
        text address
        text address_geocoded
        text alert_cache_override_datetime
        jsonb alert_cached_data_tag_dict
        text alert_cached_field_override_tag_dict
        text alternate_address
        text archived
        text birth_date
        text bulk_email_unsubscribe_key
        text cached_limited_to_team
        text calculated_unsubscribed_from_texting
        text city
        text coordinate
        text country_name
        text county_name
        text created
        text date_unsubscribed_from_bulk_email
        text date_unsubscribed_from_texting
        text email
        text email_related_person
        text email_related_person_id
        text employer
        text extension
        jsonb extra
        jsonb facebook_array
        jsonb facebook_url_array
        text fax
        text fb_id
        text formatted_primary_phone
        text formatted_secondary_phone
        text has_ever_received_email_dn
        text has_participated_in_any_campaign_dn
        text has_shared_campaign_on_social_dn
        text http_referer
        text icon
        text image_url
        text input_address
        jsonb instagram_array
        text is_grassroots_supporter
        text is_recently_active_email_recipient
        text is_stakeholder_supporter
        text last_action_date
        text last_activated_at
        text last_kind_action
        text last_user_id
        text latitude
        jsonb limited_to_team
        text longitude
        text major_organization_type
        jsonb medium_array
        text middle_name
        text name
        text num_action
        text num_campaigns_interacted
        text occupation
        jsonb pac_eligibility
        text pacc_individual_id
        text pacc_organization_id
        text phone_number
        text postal_code
        text postal_code_ext
        text preferred_name
        text prefix
        text public_organization_id
        text region
        text registered_with_text_keyword
        text secondary_email
        text secondary_extension
        text secondary_phone
        text should_display_in_external_logger
        text source_type
        text state_abbreviation
        text state_name
        text street_address
        text street_address_2
        text stripe_customer_id
        text suffix
        text supporter_type
        jsonb tag_dict
        text title
        jsonb twitter_array
        text unique_identifier
        text unsubscribed_from_bulk_email
        text unsubscribed_from_texting
        text updated
        text utm_campaign
        text utm_content
        text utm_medium
        text utm_source
        text utm_term
        text valid_email
        text waiting_to_be_created_by_user
        text website
        text work_fax
        text work_phone
        jsonb youtube_array
    }
    email_cached_limited_to_team {
        text index PK
        text email_id PK
        text cached_limited_to_team
    }
    email {
        text id PK
        text bulk_email_id FK
        text person_id FK
        text supporter_id FK
        jsonb alert_cache
        text archived
        text bounce
        text click
        text contact_organization
        text created
        text did_reply
        text email_address
        text email_alert
        text external_id
        jsonb extra
        text first_click
        text first_open
        text initial_open
        text instant
        jsonb link_dict
        text medium
        text opens
        text person_primary_organization
        text person_type
        text push_notification_error_enum
        text push_notification_error_info
        text push_notification_error_status_code
        jsonb push_notification_extra
        text rcpt_dict_address_email
        text rcpt_dict_address_name
        text rcpt_dict_has_gr_link
        jsonb rcpt_dict_substitution_data
        text recipient_name
        text sent
        text sent_datetime
        text sparkpost_id
        text sparkpost_reject_reason
        text sparkpost_status
        text staffer_id
        text text
        text title
        text transmission_id
        text updated
        text view_in_browser_id
        text was_imported
    }
    bill_summary {
        text id PK
        text bill_id FK
        text content
        jsonb extra
        text resource_uri
    }
    event {
        text id PK
        text organization_id FK
        text source_committee_id FK
        text address
        jsonb alert_cache
        jsonb amendment_mention
        text archived
        text availability
        jsonb bill_mention
        text chamber
        text committee_mention
        text created
        text cspan_channel
        text cspan_id
        text description
        text duration
        text end_time
        text event_subtype
        text event_type
        text expected_number_of_transcript
        jsonb extra
        jsonb extra_info
        text fact_squared_meeting_status
        text fact_squared_slug
        text full_transcript_url
        text is_cancelled
        text is_custom_all_day_event
        jsonb issue_mention
        text local_video_path
        text location
        text meeting_video_pipeline_status
        text occured_date
        text original_content
        text original_number_of_transcript
        jsonb person_mention
        text plain_subject
        text point_person
        text point_person_name
        text region
        jsonb related_document
        text revai_job_id
        text search_date
        text sequence_time_cache
        text source_url
        text source_video_url
        text sponsoring_organization
        text sponsoring_organization_name
        text status
        text status_text
        text subject
        text transcript_s_3_file_name
        jsonb transcription_pipeline_history_download_ended
        jsonb transcription_pipeline_history_download_error
        jsonb transcription_pipeline_history_no_source_video_url
        jsonb transcription_pipeline_history_parsing_transcription_ended
        jsonb transcription_pipeline_history_parsing_transcription_error
        jsonb transcription_pipeline_history_source_video_url_added
        jsonb transcription_pipeline_history_transcription_ended
        jsonb transcription_pipeline_history_transcription_error
        jsonb transcription_pipeline_history_transcription_in_progress
        jsonb transcription_pipeline_history_transcription_sending_error
        jsonb transcription_pipeline_history_transcription_sending_started
        text updated
        text user_id
        text video_url
        jsonb vote_mention
        jsonb witness
    }
    person_role {
        text id PK
        text adascore
        text address
        text aflscore
        text appointed_by_type
        text ccusscore
        text cfgscore
        text comstaffer_type
        text created
        text current
        text district
        text district_char
        text district_obj
        text electcode
        text end_date
        jsonb extra
        text intrado_preferred_distribution_mode
        jsonb intrado_tag
        text is_primary_from_source
        text lastelection
        text leadership_title
        text lower_district_obj
        text major_person_type
        text minor_person_type
        text office
        text office_building
        text office_city
        text office_country
        text office_room
        text office_state
        text office_street_1
        text office_street_2
        text office_zipcode
        text party
        text party_name
        text pay_scale_type
        text person_id
        text ph_intrado_last_updated
        text ph_lc_position_id
        text ph_ls_state_legislator_staff_history_id
        text ph_nominated_date
        text ph_nomination_confirmed_date
        text ph_public_organization_desc
        text ph_region_represented
        text ph_term_number
        text phone
        text reelection_year
        text region
        text resource_uri
        text role_type
        text senator_class
        text senator_rank
        text specific_person_type
        text start_date
        text state_obj
        text status
        text updated
        text upper_district_obj
        text website
    }
    bill_sponsor {
        text id PK
        text bill_id FK
        text committee_id FK
        text amendment
        text created
        jsonb extra
        text joined
        text party
        text person
        text sponsor_icon
        text sponsor_image_url
        text sponsor_name
        text sponsor_type
        text sponsor_url
        text state_name
        text updated
        text withdrawn
    }
    county {
        text id PK
        text executive
        jsonb extra
        text fips_code
        text full_fips_string
        text geojson
        text legislator
        text name
        text number
        text number_string
        text population
        text state_abbrev
    }
    all_vote {
        text id PK
        text vote_id PK
    }
    yea_vote {
        text id PK
        text vote_id PK
    }
    missed_vote {
        text id PK
        text vote_id PK
    }
    nay_vote {
        text id PK
        text vote_id PK
    }
    other_vote {
        text id PK
        text vote_id PK
    }
    present_vote {
        text id PK
        text vote_id PK
    }
    vote {
        text id PK
        text related_bill_id FK
        jsonb alert_cache
        text category
        text chamber
        text congress_number
        text created
        text democrat_result
        text display_name
        jsonb extra
        text fts_index
        text icon
        text majority_result
        text missing_data
        text newly_index
        text number
        text openstates_id
        text original_question
        text question
        text question_details
        text region
        text region_session
        text related_amendment
        text republican_result
        text required
        text result
        text result_type
        text session
        text source
        text source_link
        text total_abstain
        text total_all
        text total_dem_abstain
        text total_dem_all
        text total_dem_minus
        text total_dem_other
        text total_dem_plus
        text total_minus
        text total_other
        text total_plus
        text total_rep_abstain
        text total_rep_all
        text total_rep_minus
        text total_rep_other
        text total_rep_plus
        text type
        text voted_against_majority
    }
    note_article {
        text index PK
        text note_id PK
        text article
    }
    note_region {
        text index PK
        text note_id PK
        text region
    }
    note_cache_vote {
        text note_id PK
        text vote_id PK
    }
    note_project {
        text note_id PK
        text project_id PK
    }
    note_limited_team {
        text index PK
        text note_id PK
        text team
    }
    note_cache_bill {
        text id PK
        text note_id PK
        text region
        text title
    }
    note_team_member {
        text id PK
        text note_id PK
        text email
        text first_name
        text last_name
        text name
    }
    note {
        text id PK
        text amendment_id FK
        text bill_id FK
        text bulk_email_id FK
        text event_id FK
        text organization_id FK
        text person_id FK
        text project_id FK
        text supporter_id FK
        text user_id FK
        text vote_id FK
        jsonb alert_cache
        text amendment
        text amount
        text archived
        text attachemnt_id
        jsonb audit_trail
        text auto_created
        text bill
        text bulk_email
        jsonb cache_json_amendment
        jsonb cache_json_article
        jsonb cache_json_attachment
        jsonb cache_json_campaign
        text cache_json_comment_type
        text cache_json_comment_type_string
        text cache_json_date
        text cache_json_date_with_tz
        jsonb cache_json_document
        text cache_json_from_grassroot
        text cache_json_id
        text cache_json_initial
        text cache_json_is_comment
        text cache_json_is_interaction
        text cache_json_is_private
        text cache_json_is_relationship
        jsonb cache_json_member
        jsonb cache_json_mention
        text cache_json_note_type
        text cache_json_object_description
        text cache_json_object_id
        text cache_json_object_title
        text cache_json_organization_id
        text cache_json_privacy
        jsonb cache_json_project
        jsonb cache_json_public_organization
        jsonb cache_json_regulation
        text cache_json_social_media_type
        jsonb cache_json_supporter
        jsonb cache_json_team
        text cache_json_user_id
        jsonb cache_json_vote
        text campaign
        text check_number
        text click
        text comment_type
        text confirmed
        text created
        text custom_interaction_type
        text data_type
        text date
        text delivered
        text delivery_id
        text doument_id
        text duration
        jsonb extra
        text failed_delivery
        text first_open
        text from_grassroot
        text from_note
        text from_parser
        text from_qnote
        jsonb frozen_cache_json
        text http_referer
        text humanized_text
        text ical_id
        text icon
        text interaction_type
        text is_ical
        text is_visible_to_partner
        jsonb link_dict
        text members_count
        text message
        text message_status
        text note_type
        text num_attempt
        text opens
        text person
        text privacy
        text public_organizations_count
        text raw_content
        text relationship_status
        text relationship_type
        text searchable_date
        text social_media_type
        text source_type
        text subject
        text submitting_org_name
        text supporter_action_type
        text supporters_count
        jsonb tag_dict
        text team_members_count
        text text
        text text_with_html
        jsonb time_stamp
        text unique_identifier
        text updated
        text utm_campaign
        text utm_content
        text utm_medium
        text utm_source
        text utm_term
    }
    people_ph_region {
        text index PK
        text official_staffer_id PK
        text region_code
    }
    people_ph_major_role {
        text index PK
        text official_staffer_id PK
        text major_role
    }
    people_ph_meta_role {
        text index PK
        text official_staffer_id PK
        text meta_role
    }
    people_ph_minor_role {
        text index PK
        text official_staffer_id PK
        text minor_role
    }
    people_ph_language {
        text index PK
        text official_staffer_id PK
        text language_code
    }
    people_ph_tag {
        text index PK
        text official_staffer_id PK
        text tag_id
    }
    people_ph_source_url {
        text index PK
        text official_staffer_id PK
        text source_url
    }
    people_dn_type {
        text index PK
        text official_staffer_id PK
        text type
    }
    people_dn_scale_type {
        text index PK
        text official_staffer_id PK
        text scale_type
    }
    people_major_type {
        text index PK
        text official_staffer_id PK
        text type
    }
    people_minor_type {
        text index PK
        text official_staffer_id PK
        text type
    }
    people_recent_region {
        text index PK
        text official_staffer_id PK
        text region
    }
    people_specific_type {
        text index PK
        text official_staffer_id PK
        text type
    }
    people_staffer_type {
        text index PK
        text official_staffer_id PK
        text type
    }
    official_staffer {
        text id PK
        text committee_id FK
        text most_recent_role_id FK
        text address
        text age
        text birthday
        text committee_string
        text comstaffertype
        text congressional_district_kw_id
        text cook_pvi
        text current
        text email
        jsonb extra
        text facebook_url
        text firstname
        text freshman_legislator
        text gender
        text has_been_legislator
        text high_quality_image_url
        text image_url
        text intrado_other_email
        text is_cwc
        text lastname
        text legislator_id
        text linkedin_username
        text location
        text lower_district_kw_id
        text member_name
        text most_recent_country
        text most_recent_executive_role
        text most_recent_party
        text most_recent_person_type
        text most_recent_role_address
        text most_recent_role_building
        text most_recent_role_city
        text most_recent_role_phone
        text most_recent_role_room
        text most_recent_role_state
        text most_recent_role_street_1
        text most_recent_role_street_2
        text most_recent_role_type
        text most_recent_role_zipcode
        text name
        text new_legislator
        text num_term
        text office_code
        text party_string
        text person
        text ph_dn_intrado_preferred_distribution_mode
        text ph_intrado_last_updated
        text ph_intrado_person_id
        text ph_lc_person_id
        text ph_ls_core_person_id
        text ph_should_flush_next_run
        text precedence_local
        text precedence_state
        text precedence_state_and_local
        text prefix
        text primary_organization
        text pronunciation
        text public_organization_descriptor
        text region_represented
        text resource_uri
        text responsibilities_string
        text should_deliver_via_fill_form
        text show_in_quicksearch
        text staffer_name
        text status
        text title
        text titlecode_order
        text twitter_id
        text upper_district_kw_id
        text valid_email
        text wikipedia_url
    }
    bill_achieved_status {
        text index PK
        text bill_id PK
        text id
    }
    bill {
        text id PK
        text achieved_general_statuses
        text committee
        text current_general_status
        text current_status
        text current_status_date
        text current_status_text
        text draft_number
        text executive
        jsonb extra
        text introduced_date
        text is_approp
        text label
        text last_action_text
        jsonb major_action
        text most_recent_action_date
        text num_democrat_co_sponsor
        text num_female_co_sponsor
        text num_independent_co_sponsor
        text num_male_co_sponsor
        text num_repubilican_co_sponsor
        text number
        text procedure_code
        text public_law_number
        text region
        text session
        text slug
        jsonb snippet
        text source_link
        text sponsor
        text title
        text type
    }
    custom_field_limited_to_team }o--|| custom_field : "fk"
    custom_field }o--|| custom_field_group : "fk"
    custom_field }o--|| organization : "fk"
    issue_management_search_term }o--|| issue_management : "fk"
    issue_management_category }o--|| issue_management : "fk"
    issue_management_magic_board }o--|| issue_management : "fk"
    issue_management_team }o--|| team : "fk"
    issue_management_team }o--|| issue_management : "fk"
    issue_management_organization }o--|| organization : "fk"
    issue_management_organization }o--|| issue_management : "fk"
    issue_management_participant }o--|| issue_management : "fk"
    issue_management }o--|| users : "fk"
    bulk_email_search_param_dehydrate }o--|| bulk_email : "fk"
    bulk_email_search_param_dehydrate }o--|| bulk_email_data : "fk"
    bulk_email_search_param_dehydrate }o--|| bulk_email_search_param : "fk"
    bulk_email_search_param_most_recent }o--|| bulk_email : "fk"
    bulk_email_search_param_most_recent }o--|| bulk_email_data : "fk"
    bulk_email_search_param_most_recent }o--|| bulk_email_search_param : "fk"
    bulk_email_search_param_minor_role }o--|| bulk_email : "fk"
    bulk_email_search_param_minor_role }o--|| bulk_email_data : "fk"
    bulk_email_search_param_minor_role }o--|| bulk_email_search_param : "fk"
    bulk_email_search_param_staffer_chamber }o--|| bulk_email : "fk"
    bulk_email_search_param_staffer_chamber }o--|| bulk_email_data : "fk"
    bulk_email_search_param_staffer_chamber }o--|| bulk_email_search_param : "fk"
    bulk_email_search_param_added_id }o--|| bulk_email : "fk"
    bulk_email_search_param_added_id }o--|| bulk_email_data : "fk"
    bulk_email_search_param_added_id }o--|| bulk_email_search_param : "fk"
    bulk_email_search_param }o--|| bulk_email : "fk"
    bulk_email_search_param }o--|| bulk_email_data : "fk"
    bulk_email_region }o--|| bulk_email : "fk"
    bulk_email_region }o--|| bulk_email_data : "fk"
    bulk_email_data }o--|| bulk_email : "fk"
    bulk_email }o--|| users : "fk"
    message_event }o--|| bulk_email : "fk"
    bill_amendment_sponsor }o--|| bill_sponsor : "fk"
    bill_amendment_sponsor }o--|| bill_amendment : "fk"
    bill_amendment_text }o--|| bill_amendment : "fk"
    bill_amendment }o--|| bill : "fk"
    users_current_region }o--|| users : "fk"
    users_other_persona }o--|| users : "fk"
    users_permissioned_region }o--|| users : "fk"
    users_search_data_type_order }o--|| users : "fk"
    users_sidebar_setting_list }o--|| users : "fk"
    users }o--|| organization : "fk"
    organization_allowed_user_domain }o--|| organization : "fk"
    organization_allowed_domain }o--|| organization : "fk"
    organization_interaction_type }o--|| organization : "fk"
    organization_relationship_type }o--|| organization : "fk"
    organization_qp_executive }o--|| organization : "fk"
    organization_qp_legislative_data }o--|| organization : "fk"
    organization_qp_legislative_profile }o--|| organization : "fk"
    organization_qp_legislative }o--|| organization : "fk"
    organization_qp_official_document }o--|| organization : "fk"
    organization_qp_regulation }o--|| organization : "fk"
    organization_qp_staffer }o--|| organization : "fk"
    organization_qp_state }o--|| organization : "fk"
    organization_ip_address }o--|| organization : "fk"
    organization_qp_grassroot }o--|| organization : "fk"
    organization_qp_international }o--|| organization : "fk"
    organization_qp_local }o--|| organization : "fk"
    organization_qp_media }o--|| organization : "fk"
    organization_qp_media_relation }o--|| organization : "fk"
    organization_cs_manager }o--|| organization : "fk"
    organization_partner }o--|| organization : "fk"
    custom_field_group }o--|| users : "fk"
    custom_field_group }o--|| organization : "fk"
    committee_keyword }o--|| committee : "fk"
    supporter_action_project }o--|| issue_management : "fk"
    supporter_action_project }o--|| supporter_action : "fk"
    supporter_action_region }o--|| supporter_action : "fk"
    supporter_action }o--|| bulk_email : "fk"
    supporter_action }o--|| official_staffer : "fk"
    supporter_action }o--|| organization : "fk"
    supporter_action }o--|| contact : "fk"
    team_member }o--|| team : "fk"
    team }o--|| organization : "fk"
    contact }o--|| users : "fk"
    contact }o--|| organization : "fk"
    email_cached_limited_to_team }o--|| email : "fk"
    email }o--|| contact : "fk"
    email }o--|| bulk_email : "fk"
    email }o--|| official_staffer : "fk"
    bill_summary }o--|| bill : "fk"
    event }o--|| organization : "fk"
    event }o--|| committee : "fk"
    bill_sponsor }o--|| committee : "fk"
    bill_sponsor }o--|| bill : "fk"
    all_vote }o--|| official_staffer : "fk"
    all_vote }o--|| vote : "fk"
    yea_vote }o--|| official_staffer : "fk"
    yea_vote }o--|| vote : "fk"
    missed_vote }o--|| official_staffer : "fk"
    missed_vote }o--|| vote : "fk"
    nay_vote }o--|| official_staffer : "fk"
    nay_vote }o--|| vote : "fk"
    other_vote }o--|| official_staffer : "fk"
    other_vote }o--|| vote : "fk"
    present_vote }o--|| official_staffer : "fk"
    present_vote }o--|| vote : "fk"
    vote }o--|| bill : "fk"
    note_article }o--|| note : "fk"
    note_region }o--|| note : "fk"
    note_cache_vote }o--|| vote : "fk"
    note_cache_vote }o--|| note : "fk"
    note_project }o--|| issue_management : "fk"
    note_project }o--|| note : "fk"
    note_limited_team }o--|| note : "fk"
    note_cache_bill }o--|| bill : "fk"
    note_cache_bill }o--|| note : "fk"
    note_team_member }o--|| users : "fk"
    note_team_member }o--|| note : "fk"
    note }o--|| event : "fk"
    note }o--|| users : "fk"
    note }o--|| contact : "fk"
    note }o--|| bill_amendment : "fk"
    note }o--|| vote : "fk"
    note }o--|| bill : "fk"
    note }o--|| bulk_email : "fk"
    note }o--|| official_staffer : "fk"
    note }o--|| organization : "fk"
    note }o--|| issue_management : "fk"
    people_ph_region }o--|| official_staffer : "fk"
    people_ph_major_role }o--|| official_staffer : "fk"
    people_ph_meta_role }o--|| official_staffer : "fk"
    people_ph_minor_role }o--|| official_staffer : "fk"
    people_ph_language }o--|| official_staffer : "fk"
    people_ph_tag }o--|| official_staffer : "fk"
    people_ph_source_url }o--|| official_staffer : "fk"
    people_dn_type }o--|| official_staffer : "fk"
    people_dn_scale_type }o--|| official_staffer : "fk"
    people_major_type }o--|| official_staffer : "fk"
    people_minor_type }o--|| official_staffer : "fk"
    people_recent_region }o--|| official_staffer : "fk"
    people_specific_type }o--|| official_staffer : "fk"
    people_staffer_type }o--|| official_staffer : "fk"
    official_staffer }o--|| committee : "fk"
    official_staffer }o--|| person_role : "fk"
    bill_achieved_status }o--|| bill : "fk"
