erDiagram
    report {
        text _fivetran_id PK
        text average_item_value
        text average_order_value
        text click_position
        text click_through_rate
        text commission_type
        text estimated_commissions
        text link_type
        text net_items_per_order
        text no_of_cancelled_items
        text no_of_clicks
        text no_of_impressions
        text no_of_items
        text no_of_net_items
        text no_of_orders
        text no_of_orders_or_clicks
        text offer_group_id
        text offer_name
        text order_id
        text process_date
        text product_name
        text publisher_id
        text publisher_name
        text report_name
        text sales
        text sku
        text total_commission
        text transaction_date
        text transaction_time
        text transaction_week_begin_date
        text transaction_week_end_date
    }
