erDiagram
    order_item {
        text id PK
        text order_id FK
        text product_id FK
        text profile_id FK
        text gift_price
        text gift_tax_price
        text is_bundle
        text quantity
        text recycling_fee
        text shipping_price
        text shipping_tax_price
        text site_id
        text site_listing_id
        text site_order_item_id
        text sku
        text tax_price
        text title
        text unit_estimated_shipping_cost
        text unit_price
    }
    product_bundle_component {
        text component_id PK
        text product_id PK
        text profile_id FK
        text component_sku
        text quantity
    }
    distribution_center {
        text id PK
        text address_1
        text address_2
        text alt_phone
        text business_description
        text city
        text code
        text contact_email
        text contact_name
        text contact_phone
        text country
        text delivery_available
        text district
        text email
        text fulfillment_partner_name
        text handling_time_minute
        text home_page
        text is_externally_managed
        text latitude
        text longitude
        text main_phone
        text name
        text pickup_location
        text pickup_order_hold_minute
        text postal_code
        text ship_location
        text state_or_province
        text store_categories
        text throughput_limit_number
        text throughput_limit_unit
        text time_zone
        text type
    }
    distributed_center_operating_hour {
        text id PK
        text distribution_center_id FK
        text close_time
        text day_id
        text open_time
    }
    shipping_label_partner_account {
        text id PK
        text profile_id PK
        text account_name
        text partner_name
    }
    site_account {
        text id PK
        text site_id PK
        text profile_id FK
        text enabled
        text name
        text site_name
    }
    profile {
        text id PK
        text account_name
        text company_name
        text currency_code
        text default_distribution_center_id
        text time_zone_description
        text time_zone_region
    }
    package {
        text id PK
        text profile_id FK
        text description
        text name
        text shipping_carrier
    }
    buyer_initiated_return_adjustment {
        text id PK
        text order_id FK
        text order_item_id FK
        text profile_id FK
        text comment
        text created_date
        text gift_wrap_adjustment
        text gift_wrap_tax_adjustment
        text is_restock
        text item_adjustment
        text public_note
        text quantity
        text reason
        text recycling_fee_adjustment
        text request_status
        text restock_status
        text restocking_fee
        text return_shipping_fee
        text return_shipping_method
        text return_tracking_number_or_url
        text rma_number
        text seller_adjustment_id
        text shipping_adjustment
        text shipping_tax_adjustment
        text tax_adjustment
        text type
    }
    buyer_initiated_return {
        text id PK
        text order_id FK
        text product_id FK
        text profile_id FK
        text gift_message
        text gift_notes
        text gift_price
        text gift_tax_price
        text is_bundle
        text item_url
        text quantity
        text recycling_fee
        text shipping_price
        text shipping_tax_price
        text site_listing_id
        text site_order_item_id
        text sku
        text tax_price
        text title
        text unit_price
    }
    product {
        text id PK
        text profile_id FK
        text asin
        text block_comment
        text blocked_date
        text brand
        text bundle_type
        text buy_it_now_price
        text classification
        text condition
        text cost
        text description
        text ean
        text flag
        text flag_description
        text harmonized_code
        text is_available_in_store
        text is_blocked
        text is_display_in_store
        text is_external_quantity_blocked
        text is_in_relationship
        text is_parent
        text isbn
        text manufacturer
        text margin
        text mpn
        text open_allocated_quantity
        text open_allocated_quantity_pooled
        text parent_product_id
        text pending_checkout_quantity
        text pending_checkout_quantity_pooled
        text pending_payment_quantity
        text pending_payment_quantity_pooled
        text pending_shipment_quantity
        text pending_shipment_quantity_pooled
        text received_date
        text relationship_name
        text reserve_price
        text retail_price
        text second_chance_price
        text short_description
        text sku
        text starting_price
        text store_description
        text store_price
        text store_title
        text subtitle
        text supplier_code
        text supplier_name
        text supplier_po
        text tax_product_code
        text title
        text total_available_quantity
        text total_quantity
        text total_quantity_pooled
        text upc
        text warehouse_location
        text warranty
    }
    fulfillment {
        text id PK
        text distribution_center_id FK
        text order_id FK
        text profile_id FK
        text channel_return_label_format
        text created_date
        text delivery_status
        text estimated_ship_date
        text external_fulfillment_center_code
        text external_fulfillment_number
        text external_fulfillment_reference_number
        text external_fulfillment_status
        text has_channel_packing_slip
        text has_channel_return_label
        text has_return_label
        text has_shipping_label
        text insurance_cost
        text label_format
        text return_label_format
        text seller_fulfillment_id
        text shipped_date
        text shipping_carrier
        text shipping_class
        text shipping_cost
        text shipping_label_request_id
        text staging_location
        text tax_cost
        text tracking_number
        text type
        text updated_date
    }
    orders {
        text id PK
        text profile_id FK
        text site_id FK
        text additional_cost_or_discount
        text billing_address_line_1
        text billing_address_line_2
        text billing_city
        text billing_company_job_title
        text billing_company_name
        text billing_country
        text billing_daytime_phone
        text billing_evening_phone
        text billing_first_name
        text billing_last_name
        text billing_postal_code
        text billing_state_or_province
        text billing_suffix
        text billing_title
        text buyer_email_address
        text buyer_email_opt_in
        text buyer_user_id
        text checkout_date
        text checkout_source_id
        text checkout_status
        text created_date
        text deliver_by_date
        text distribution_center_type_rollup
        text estimated_ship_date
        text flag_description
        text flag_id
        text gift_options_tax_type
        text import_date
        text order_tag
        text order_tax_type
        text payment_credit_card_last_4
        text payment_date
        text payment_merchant_reference_number
        text payment_method
        text payment_paypal_account_id
        text payment_status
        text payment_transaction_id
        text private_note
        text promotion_amount
        text promotion_code
        text public_note
        text reseller_id
        text secondary_site_order_id
        text seller_order_id
        text shipping_address_line_1
        text shipping_address_line_2
        text shipping_city
        text shipping_company_job_title
        text shipping_company_name
        text shipping_country
        text shipping_date
        text shipping_daytime_phone
        text shipping_evening_phone
        text shipping_first_name
        text shipping_last_name
        text shipping_postal_code
        text shipping_state_or_province
        text shipping_status
        text shipping_suffix
        text shipping_tax_type
        text shipping_title
        text site_order_id
        text special_instruction
        text total_gift_option_price
        text total_gift_option_tax_price
        text total_insurance_price
        text total_price
        text total_shipping_price
        text total_shipping_tax_price
        text total_tax_price
        text updated_date
    }
    channel_document {
        text id PK
        text order_id FK
        text profile_id FK
        text adjustment_id
        text contents
        text create_date
        text document_key
        text document_type
        text invoice_number
        text status
        text total_amount
        text update_date
    }
    product_attribute {
        text product_id PK
        text value
    }
    order_item }o--|| product : "fk"
    order_item }o--|| orders : "fk"
    order_item }o--|| profile : "fk"
    product_bundle_component }o--|| product : "fk"
    product_bundle_component }o--|| profile : "fk"
    distributed_center_operating_hour }o--|| distribution_center : "fk"
    shipping_label_partner_account }o--|| profile : "fk"
    site_account }o--|| profile : "fk"
    package }o--|| profile : "fk"
    buyer_initiated_return_adjustment }o--|| orders : "fk"
    buyer_initiated_return_adjustment }o--|| profile : "fk"
    buyer_initiated_return_adjustment }o--|| order_item : "fk"
    buyer_initiated_return }o--|| product : "fk"
    buyer_initiated_return }o--|| orders : "fk"
    buyer_initiated_return }o--|| profile : "fk"
    product }o--|| profile : "fk"
    fulfillment }o--|| distribution_center : "fk"
    fulfillment }o--|| orders : "fk"
    fulfillment }o--|| profile : "fk"
    orders }o--|| profile : "fk"
    orders }o--|| site_account : "fk"
    channel_document }o--|| orders : "fk"
    channel_document }o--|| profile : "fk"
    product_attribute }o--|| product : "fk"
