erDiagram
    incident_type_slack_channel {
        text id PK
        text incident_type_id PK
        text name
    }
    incident_type_slack_alias {
        text id PK
        text incident_type_id PK
        text name
    }
    incident_type_notify_email {
        text notify_email PK
        text incident_type_id PK
    }
    incident_type {
        text id PK
        text created_at
        text description
        text name
        text position
        text slug
        text updated_at
    }
    audit {
        text id PK
        text user_id FK
        timestamp created_at
        text event
        text item_id
        text item_type
        text object
        text object_changes
        timestamp updated_at
    }
    post_mortem {
        text id PK
        text incident_id FK
        text cancelled_at
        text content
        text created_at
        text mitigated_at
        text published_at
        text resolved_at
        text short_url
        text show_action_items
        text show_alerts_attached
        text show_functionalities_impacted
        text show_groups_impacted
        text show_services_impacted
        text show_timeline
        text show_timeline_action_items
        text show_timeline_genius
        text show_timeline_order
        text show_timeline_starred_only
        text show_timeline_tasks
        text show_timeline_trail
        text started_at
        text status
        text title
        text updated_at
        text url
    }
    form_field_option {
        text id PK
        text form_field_id FK
        text color
        text created_at
        text is_default
        text position
        timestamp updated_at
        text value
    }
    incident_role {
        text incident_id PK
        text role_id PK
    }
    incident_environment {
        text environment_id PK
        text incident_id PK
    }
    incident_type_data {
        text incident_id PK
        text incident_type_id PK
    }
    incident_service {
        text incident_id PK
        text service_id PK
    }
    incident_functionality {
        text functionality_id PK
        text incident_id PK
    }
    incident_team {
        text incident_id PK
        text team_id PK
    }
    incident_event {
        text event_id PK
        text incident_id PK
    }
    incident_action_item {
        text action_item_id PK
        text incident_id PK
    }
    incident_feedback {
        text feedback_id PK
        text incident_id PK
    }
    incident_post_mortem {
        text incident_id PK
        text post_mortem_id PK
    }
    incident {
        text id PK
        text cancelled_by FK
        text mitigated_by FK
        text parent_incident_id FK
        text resolved_by FK
        text severity_id FK
        text started_by_id FK
        text user_id FK
        text acknowledged_at
        text airtable_base_key
        text airtable_record_id
        text airtable_record_url
        text airtable_table_name
        text asana_task_id
        text asana_task_url
        text cancellation_message
        text cancelled_at
        text confluence_page_id
        text confluence_page_url
        text created_at
        text datadog_notebook_id
        text datadog_notebook_url
        text detected_at
        text duplicate_incident_id
        text freshservice_task_id
        text freshservice_task_url
        text freshservice_ticket_id
        text freshservice_ticket_url
        text github_issue_id
        text github_issue_url
        text google_drive_id
        text google_drive_url
        text google_meeting_id
        text google_meeting_url
        text jira_issue_id
        text jira_issue_key
        text jira_issue_url
        text kind
        jsonb labels
        text linear_issue_id
        text linear_issue_url
        text mattermost_channel_id
        text mattermost_channel_name
        text mattermost_channel_url
        text mitigated_at
        text mitigation_message
        text opsgenie_alert_id
        text opsgenie_alert_url
        text opsgenie_incident_id
        text opsgenie_incident_url
        text pagerduty_incident_id
        text pagerduty_incident_url
        text private
        text public_title
        text quip_page_id
        text quip_page_url
        text resolution_message
        text resolved_at
        text scheduled_for
        text scheduled_until
        text sequential_id
        text service_now_incident_id
        text service_now_incident_key
        text service_now_incident_url
        text short_url
        text shortcut_story_id
        text shortcut_story_url
        text shortcut_task_id
        text shortcut_task_url
        text slack_channel_id
        text slack_channel_name
        text slack_channel_short_url
        text slack_channel_url
        text slug
        text source
        text started_at
        text status
        text summary
        text title
        text trello_card_id
        text trello_card_url
        timestamp updated_at
        text url
        text victor_ops_incident_id
        text victor_ops_incident_url
        text zendesk_ticket_id
        text zendesk_ticket_url
        text zoom_meeting_id
        text zoom_meeting_join_url
        text zoom_meeting_start_url
    }
    cause {
        text id PK
        timestamp created_at
        text description
        text name
        text position
        text slug
        timestamp updated_at
    }
    action_item_team {
        text action_item_id PK
        text team_id PK
    }
    action_item_administrating_team {
        text action_item_id PK
        text administrating_team_id PK
    }
    action_item_notify_email {
        text notify_email PK
        text action_item_id PK
    }
    action_item {
        text id PK
        text airtable_record_id FK
        text asana_task_id FK
        text assignee_id FK
        text freshservice_task_id FK
        text freshservice_ticket_id FK
        text github_issue_id FK
        text incident_id FK
        text jira_issue_id FK
        text linear_issue_id FK
        text shortcut_story_id FK
        text shortcut_task_id FK
        text trello_card_id FK
        text zendesk_ticket_id FK
        text assignee_accept_marketing
        text assignee_accept_terms
        text assignee_created_through_sso
        text assignee_current_team_id
        text assignee_incidents_backfilled_count
        text assignee_incidents_count
        text assignee_incidents_example_count
        text assignee_incidents_normal_count
        text assignee_incidents_scheduled_count
        text assignee_incidents_test_count
        text assignee_last_notification_email_sent_at
        text assignee_last_seen_at
        text assignee_onboarding_completed
        text assignee_profile_photo_id
        text assignee_scim_uid
        text assignee_service_user
        text assignee_session_token
        text assignee_teams_count
        text assignee_theme
        text assignee_time_zone
        text created_at
        text deleted_at
        text description
        text due_date
        text kind
        text priority
        text short_url
        text status
        text summary
        text updated_at
        text url
    }
    retrospective_process {
        text id PK
        text created_at
        text description
        text is_default
        jsonb matching_criteria
        text name
        timestamp updated_at
    }
    event {
        text id PK
        text incident_id FK
        text created_at
        text event
        text event_raw
        text kind
        text occurred_at
        text source
        text starred_at
        text updated_at
        text user_display_name
        text visibility
    }
    retrospective {
        text id PK
        text incident_role_id FK
        text retrospective_process_id FK
        text canceled_at
        text created_at
        text description
        text due_after_days
        text position
        text skippable
        text slug
        text title
        timestamp updated_at
    }
    functionality_slack_channel {
        text id PK
        text functionality_id PK
        text name
    }
    functionality_slack_alias {
        text id PK
        text functionality_id PK
        text name
    }
    functionality_notify_email {
        text notify_email PK
        text functionality_id PK
    }
    functionality_owner_user {
        text functionality_id PK
        text user_id PK
    }
    functionality_owner_team {
        text functionality_id PK
        text team_id PK
    }
    functionality_service_id {
        text functionality_id PK
        text service_id PK
    }
    functionality_environment {
        text environment_id PK
        text functionality_id PK
    }
    functionality {
        text id PK
        text created_at
        text description
        text name
        text opsgenie_id
        text pagerduty_id
        text position
        text public_description
        text show_uptime
        text show_uptime_last_days
        text slug
        text status
        text updated_at
    }
    service_slack_channel {
        text id PK
        text service_id PK
        text name
    }
    service_slack_alias {
        text id PK
        text service_id PK
        text name
    }
    service_owner_user {
        text service_id PK
        text user_id PK
    }
    service_owner_team {
        text service_id PK
        text team_id PK
    }
    service_dependent_id {
        text dependent_service_id PK
        text service_id PK
    }
    service_environment {
        text environment_id PK
        text service_id PK
    }
    service_notify_email {
        text notify_email PK
        text service_id PK
    }
    service {
        text id PK
        text backstage_id
        text created_at
        text description
        text github_repository_branch
        text github_repository_name
        text gitlab_repository_branch
        text gitlab_repository_name
        text name
        text opsgenie_id
        text pagerduty_id
        text position
        text public_description
        text show_uptime
        text show_uptime_last_days
        text slug
        text status
        text updated_at
    }
    form_field_selection_user {
        text user_id PK
        text form_field_selection_id PK
    }
    form_field_selection_option {
        text index PK
        text form_field_selection_id PK
        text color
        text created_at
        text form_field_id
        text id
        text is_default
        text position
        text updated_at
        text value
    }
    form_field_selection {
        text id PK
        text form_field_id FK
        text incident_id FK
        text custom_field_id
        text description
        text value
    }
    post_mortem_template {
        text id PK
        text content
        text created_at
        text format
        text is_default
        text name
        text updated_at
    }
    dashboard_panel_dataset_operation_rule {
        text index PK
        text dashboard_panel_dataset_index PK
        text dashboard_panel_id PK
        text condition
        text key
        text operation
        text value
    }
    dashboard_panel_dataset {
        text index PK
        text dashboard_panel_id PK
        text aggregate_cumulative
        text aggregate_key
        text aggregate_operation
        text collection
        text group_by
        text name
    }
    dashboard_panel {
        text id PK
        text dashboard_id FK
        text created_at
        jsonb data
        text name
        text params_display
        jsonb params_legend
        text position_h
        text position_w
        text position_x
        text position_y
        text updated_at
    }
    form_field_shown {
        text index PK
        text form_field_id PK
        text shown
    }
    form_field_required {
        text index PK
        text form_field_id PK
        text required
    }
    form_field {
        text id PK
        timestamp created_at
        jsonb default_values
        text description
        text enabled
        text input_kind
        text kind
        text name
        text show_on_incident_details
        text slug
        text team_id
        timestamp updated_at
    }
    playbook_task {
        text id PK
        text playbook_id FK
        text created_at
        text description
        text position
        text task
        text updated_at
    }
    playbook_severity {
        text playbook_id PK
        text severity_id PK
    }
    playbook_environment {
        text environment_id PK
        text playbook_id PK
    }
    playbook_functionality {
        text functionality_id PK
        text playbook_id PK
    }
    playbook_service {
        text playbook_id PK
        text service_id PK
    }
    playbook_team {
        text playbook_id PK
        text team_id PK
    }
    playbook_incident_type {
        text incident_type_id PK
        text playbook_id PK
    }
    playbook {
        text id PK
        text user_id FK
        text created_at
        text external_url
        text summary
        text title
        text updated_at
    }
    users {
        text id PK
        text created_at
        text email
        text full_name
        text full_name_with_team
        text name
        text phone
        text phone_2
        text slack_id
        text updated_at
    }
    severity_slack_channel {
        text id PK
        text severity_id PK
        text name
    }
    severity_slack_alias {
        text id PK
        text severity_id PK
        text name
    }
    severity_notify_email {
        text notify_email PK
        text severity_id PK
    }
    severity {
        text id PK
        text created_at
        text description
        text name
        text position
        text severity
        text slug
        text updated_at
    }
    secret {
        text id PK
        text created_at
        text hashicorp_vault_mount
        text hashicorp_vault_path
        text hashicorp_vault_version
        text name
        text secret
        text updated_at
    }
    feedback {
        text id PK
        text incident_id FK
        text anonymous
        text created_at
        text feedback
        text rating
        text rating_humanized
        text updated_at
    }
    environment_slack_channel {
        text id PK
        text environment_id PK
        text name
    }
    environment_slack_alias {
        text id PK
        text environment_id PK
        text name
    }
    environment_notify_email {
        text notify_email PK
        text environment_id PK
    }
    environment {
        text id PK
        text created_at
        text description
        text name
        text position
        text slug
        text updated_at
    }
    role {
        text id PK
        text allow_multi_user_assignment
        timestamp created_at
        text description
        text enabled
        text name
        text optional
        text position
        text slug
        text summary
        timestamp updated_at
    }
    dashboard {
        text id PK
        text user_id FK
        text auto_refresh
        text color
        text created_at
        text description
        text icon
        text name
        text owner
        text period
        text public
        text range
        text slug
        text team_id
        text updated_at
    }
    workflow_group {
        text id PK
        text expanded
        text kind
        text name
        text position
        text slug
    }
    form_field_position {
        text id PK
        text form_field_id FK
        text form
        text position
    }
    team_slack_channel {
        text id PK
        text team_id PK
        text name
    }
    team_slack_alias {
        text id PK
        text team_id PK
        text name
    }
    team_notify_email {
        text notify_email PK
        text team_id PK
    }
    team {
        text id PK
        text created_at
        text description
        text name
        text opsgenie_id
        text pagerduty_id
        text position
        text slug
        text updated_at
    }
    workflow_task_run_output {
        text index PK
        text workflow_id PK
        text workflow_run_id PK
        text workflow_task_run_id PK
        text event
        text timestamps
    }
    workflow_task_run {
        text id PK
        text workflow_id PK
        text workflow_run_id PK
        text canceled_at
        text completed_at
        text created_at
        text failed_at
        text position
        text skip_on_failure
        text started_at
        text status
        text triggered_by
        text updated_at
    }
    workflow_run {
        text id PK
        text workflow_id PK
        text action_item_id FK
        text incident_id FK
        text post_mortem_id FK
        text user_id FK
        text alert_id
        text canceled_at
        text completed_at
        text created_at
        text failed_at
        text kind
        text pulse_id
        text queued_at
        text started_at
        text status
        text status_message
        text triggered_by
        text updated_at
    }
    workflow_environment {
        text environment_id PK
        text workflow_id PK
    }
    workflow_severity {
        text severity_id PK
        text workflow_id PK
    }
    workflow_incident_type {
        text incident_type_id PK
        text workflow_id PK
    }
    workflow_role {
        text role_id PK
        text workflow_id PK
    }
    workflow_service {
        text service_id PK
        text workflow_id PK
    }
    workflow_functionality {
        text functionality_id PK
        text workflow_id PK
    }
    workflow {
        text id PK
        text workflow_group_id FK
        text command
        text command_feedback_enabled
        timestamp created_at
        text description
        text enabled
        text expanded
        text incident_condition
        text incident_condition_acknowledged_at
        text incident_condition_detected_at
        text incident_condition_environment
        text incident_condition_functionality
        text incident_condition_group
        text incident_condition_incident_roles
        text incident_condition_incident_type
        text incident_condition_kind
        text incident_condition_mitigated_at
        text incident_condition_resolved_at
        text incident_condition_service
        text incident_condition_severity
        text incident_condition_started_at
        text incident_condition_status
        text incident_condition_summary
        text incident_condition_visibility
        text incident_conditional_inactivity
        text incident_inactivity_duration
        text name
        text position
        text repeat_every_duration
        text slug
        text trigger_type
        timestamp updated_at
        text wait
    }
    incident_type_slack_channel }o--|| incident_type : "fk"
    incident_type_slack_alias }o--|| incident_type : "fk"
    incident_type_notify_email }o--|| incident_type : "fk"
    audit }o--|| users : "fk"
    post_mortem }o--|| incident : "fk"
    form_field_option }o--|| form_field : "fk"
    incident_role }o--|| role : "fk"
    incident_role }o--|| incident : "fk"
    incident_environment }o--|| environment : "fk"
    incident_environment }o--|| incident : "fk"
    incident_type_data }o--|| incident_type : "fk"
    incident_type_data }o--|| incident : "fk"
    incident_service }o--|| service : "fk"
    incident_service }o--|| incident : "fk"
    incident_functionality }o--|| functionality : "fk"
    incident_functionality }o--|| incident : "fk"
    incident_team }o--|| team : "fk"
    incident_team }o--|| incident : "fk"
    incident_event }o--|| event : "fk"
    incident_event }o--|| incident : "fk"
    incident_action_item }o--|| action_item : "fk"
    incident_action_item }o--|| incident : "fk"
    incident_feedback }o--|| feedback : "fk"
    incident_feedback }o--|| incident : "fk"
    incident_post_mortem }o--|| post_mortem : "fk"
    incident_post_mortem }o--|| incident : "fk"
    incident }o--|| users : "fk"
    incident }o--|| users : "fk"
    incident }o--|| incident : "fk"
    incident }o--|| users : "fk"
    incident }o--|| users : "fk"
    incident }o--|| users : "fk"
    incident }o--|| severity : "fk"
    action_item_team }o--|| team : "fk"
    action_item_team }o--|| action_item : "fk"
    action_item_administrating_team }o--|| team : "fk"
    action_item_administrating_team }o--|| action_item : "fk"
    action_item_notify_email }o--|| action_item : "fk"
    action_item }o--|| users : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    action_item }o--|| incident : "fk"
    event }o--|| incident : "fk"
    retrospective }o--|| retrospective_process : "fk"
    retrospective }o--|| role : "fk"
    functionality_slack_channel }o--|| functionality : "fk"
    functionality_slack_alias }o--|| functionality : "fk"
    functionality_notify_email }o--|| functionality : "fk"
    functionality_owner_user }o--|| users : "fk"
    functionality_owner_user }o--|| functionality : "fk"
    functionality_owner_team }o--|| team : "fk"
    functionality_owner_team }o--|| functionality : "fk"
    functionality_service_id }o--|| service : "fk"
    functionality_service_id }o--|| functionality : "fk"
    functionality_environment }o--|| environment : "fk"
    functionality_environment }o--|| functionality : "fk"
    service_slack_channel }o--|| service : "fk"
    service_slack_alias }o--|| service : "fk"
    service_owner_user }o--|| users : "fk"
    service_owner_user }o--|| service : "fk"
    service_owner_team }o--|| team : "fk"
    service_owner_team }o--|| service : "fk"
    service_dependent_id }o--|| service : "fk"
    service_dependent_id }o--|| service : "fk"
    service_environment }o--|| environment : "fk"
    service_environment }o--|| service : "fk"
    service_notify_email }o--|| service : "fk"
    form_field_selection_user }o--|| form_field_selection : "fk"
    form_field_selection_option }o--|| form_field_selection : "fk"
    form_field_selection }o--|| incident : "fk"
    form_field_selection }o--|| form_field : "fk"
    dashboard_panel_dataset_operation_rule }o--|| dashboard_panel_dataset : "fk"
    dashboard_panel_dataset_operation_rule }o--|| dashboard_panel_dataset : "fk"
    dashboard_panel_dataset }o--|| dashboard_panel : "fk"
    dashboard_panel }o--|| dashboard : "fk"
    form_field_shown }o--|| form_field : "fk"
    form_field_required }o--|| form_field : "fk"
    playbook_task }o--|| playbook : "fk"
    playbook_severity }o--|| severity : "fk"
    playbook_severity }o--|| playbook : "fk"
    playbook_environment }o--|| environment : "fk"
    playbook_environment }o--|| playbook : "fk"
    playbook_functionality }o--|| functionality : "fk"
    playbook_functionality }o--|| playbook : "fk"
    playbook_service }o--|| service : "fk"
    playbook_service }o--|| playbook : "fk"
    playbook_team }o--|| team : "fk"
    playbook_team }o--|| playbook : "fk"
    playbook_incident_type }o--|| incident_type : "fk"
    playbook_incident_type }o--|| playbook : "fk"
    playbook }o--|| users : "fk"
    severity_slack_channel }o--|| severity : "fk"
    severity_slack_alias }o--|| severity : "fk"
    severity_notify_email }o--|| severity : "fk"
    feedback }o--|| incident : "fk"
    environment_slack_channel }o--|| environment : "fk"
    environment_slack_alias }o--|| environment : "fk"
    environment_notify_email }o--|| environment : "fk"
    dashboard }o--|| users : "fk"
    form_field_position }o--|| form_field : "fk"
    team_slack_channel }o--|| team : "fk"
    team_slack_alias }o--|| team : "fk"
    team_notify_email }o--|| team : "fk"
    workflow_task_run_output }o--|| workflow_task_run : "fk"
    workflow_task_run_output }o--|| workflow_task_run : "fk"
    workflow_task_run_output }o--|| workflow_task_run : "fk"
    workflow_task_run }o--|| workflow_run : "fk"
    workflow_task_run }o--|| workflow_run : "fk"
    workflow_run }o--|| users : "fk"
    workflow_run }o--|| action_item : "fk"
    workflow_run }o--|| post_mortem : "fk"
    workflow_run }o--|| incident : "fk"
    workflow_run }o--|| workflow : "fk"
    workflow_environment }o--|| environment : "fk"
    workflow_environment }o--|| workflow : "fk"
    workflow_severity }o--|| severity : "fk"
    workflow_severity }o--|| workflow : "fk"
    workflow_incident_type }o--|| incident_type : "fk"
    workflow_incident_type }o--|| workflow : "fk"
    workflow_role }o--|| role : "fk"
    workflow_role }o--|| workflow : "fk"
    workflow_service }o--|| service : "fk"
    workflow_service }o--|| workflow : "fk"
    workflow_functionality }o--|| functionality : "fk"
    workflow_functionality }o--|| workflow : "fk"
    workflow }o--|| workflow_group : "fk"
