erDiagram
    time_collector {
        text id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        timestamp booking_date
        text change_value
        text collector_value
        timestamp created_date_time
        timestamp end_date
        timestamp last_modified_date_time
        timestamp start_date
        text system_record_status
        text time_collector_type
    }
    candidate_background_education {
        text background_element_id PK
        text candidate_id FK
        text background_order_position
        text degree
        timestamp degree_date
        timestamp end_date
        timestamp last_modified_date_time
        text major
        text present_student
        text school
        text school_address
        text school_city
        text school_country
        text school_phone
        text school_state
        text school_type
        text school_zip
        timestamp start_date
    }
    background_memberships {
        text background_element_id PK
        text user_id PK
        text background_order_position
        timestamp end_date
        timestamp last_modified_date
        text organization
        text role
        timestamp start_date
    }
    background_community {
        text background_element_id PK
        text user_id PK
        text background_order_position
        timestamp end_date
        timestamp last_modified_date
        text name
        text role
        timestamp start_date
    }
    employee_compensation {
        timestamp start_date PK
        text user_id PK
        text created_by FK
        text last_modified_by FK
        double_precision benefits_rate
        double_precision bonus_target
        timestamp created_date_time
        timestamp end_date
        text event
        text event_reason
        boolean is_eligible_for_benefits
        boolean is_eligible_for_car
        boolean is_highly_compensated_employee
        boolean is_insider
        timestamp last_modified_date_time
        text pay_grade
        text pay_group
        text payroll_system_id
    }
    admin_reassign_offer_approver {
        text application_id PK
        text offer_detail_id PK
        text user_id PK
        text job_req_id FK
        text target_user_id FK
        text candidate_name
        text job_req_title
    }
    candidate_tags {
        text id PK
        text candidate_id FK
        text label
        text locale
    }
    employee_pay_comp_non_recurring {
        text pay_component_code PK
        timestamp pay_date PK
        text user_id PK
        text created_by FK
        text last_modified_by FK
        text alternative_cost_center
        timestamp created_date_time
        text currency_code
        timestamp last_modified_date_time
        text notes
        text operation
        double_precision value
    }
    per_person {
        text person_id_external PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        text birth_name
        text country_of_birth
        timestamp created_date_time
        timestamp created_on
        text date_of_birth
        text include_all_record
        timestamp last_modified_date_time
        timestamp last_modified_on
        text per_person_uuid
        text person_id
        text region_of_birth
    }
    emp_cost_distribution_item {
        timestamp emp_cost_distribution_effective_start_date PK
        text external_code PK
        text emp_cost_distribution_users_sys_id PK
        text created_by FK
        text last_modified_by FK
        text cost_center
        timestamp created_date_time
        timestamp last_modified_date_time
        text mdf_system_created_by
        timestamp mdf_system_created_date
        timestamp mdf_system_effective_end_date
        timestamp mdf_system_effective_start_date
        text mdf_system_entity_id
        text mdf_system_last_modified_by
        timestamp mdf_system_last_modified_date
        text mdf_system_last_modified_date_with_tz
        text mdf_system_object_type
        text mdf_system_record_id
        text mdf_system_record_status
        text mdf_system_status
        text mdf_system_transaction_sequence
        text mdf_system_version_id
        text percentage
    }
    job_application_question_response {
        text order_id PK
        text application_id PK
        text answer
        text expected_answer
        double_precision expected_answer_value
        text high_low
        double_precision max_length
        text question
        text question_response
        text type
    }
    fo_job_function {
        text external_code PK
        timestamp start_date PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp created_on
        text description
        text description_de_de
        text description_default_value
        text description_en_debug
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        timestamp end_date
        text job_function_type
        timestamp last_modified_date_time
        timestamp last_modified_on
        text mdf_system_record_id
        text name
        text name_de_de
        text name_default_value
        text name_en_debug
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        text parent_function_code
        text status
        text type
    }
    job_requisition_screening_question {
        text locale PK
        text order_id PK
        text job_req_id PK
        text question_id FK
        text question_parent_id FK
        boolean disqualifier
        double_precision expected_answer_value
        text expected_dir
        text job_req_content
        text max_length
        text question_description
        text question_parent_response
        double_precision question_weight
        text rating_scale
        boolean required
        boolean score
    }
    form_user_rating_comment {
        text form_content_id PK
        text form_data_id PK
        text item_id PK
        text rating_type PK
        integer section_index PK
        text user_id PK
        text comment
        text comment_key
        text comment_label
        text comment_permission
        text first_name
        text full_name
        text last_name
        text rating
        text rating_key
        text rating_label
        text rating_permission
        text text_rating
    }
    background_inside_work_experience {
        text background_element_id PK
        text user_id PK
        text background_order_position
        text department
        timestamp end_date
        timestamp last_modified_date
        timestamp start_date
        text title
    }
    work_order {
        timestamp effective_start_date PK
        text user_id PK
        text work_order_id PK
        text created_by FK
        text last_modified_by FK
        text vendor FK
        double_precision billing_amount
        text billing_rate
        timestamp created_date
        timestamp created_date_time
        text currency
        timestamp effective_end_date
        text effective_status
        timestamp end_date
        timestamp last_modified_date_time
        timestamp start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
        text work_order_name
        text work_order_owner_id
        text worker_type
    }
    background_check_result {
        text id PK
        text background_check_request_request_id FK
        timestamp created_date_time
        boolean final_step
        text report_url
        text step_message
        text step_name
        text step_status
        text vendor_code
        text vendor_order_no
    }
    fo_company {
        text external_code PK
        timestamp start_date PK
        text created_by FK
        text last_modified_by FK
        text country
        timestamp created_date_time
        timestamp created_on
        text currency
        text default_location
        text default_pay_group
        text description
        text description_de_de
        text description_default_value
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        timestamp end_date
        text entity_oid
        timestamp last_modified_date_time
        timestamp last_modified_on
        text mdf_system_record_id
        text name
        text name_de_de
        text name_default_value
        text name_en_debug
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        double_precision standard_hours
        text status
    }
    background_education {
        text background_element_id PK
        text user_id PK
        text degree FK
        text major FK
        text school_country FK
        text school_state FK
        text background_order_position
        timestamp degree_date
        timestamp end_date
        timestamp last_modified_date
        text school
        text school_address
        text school_city
        text school_type
        text school_zip
        timestamp start_date
    }
    fo_department {
        text external_code PK
        timestamp start_date PK
        text cost_center_nav_external_code FK
        text created_by FK
        text last_modified_by FK
        text address_address_1
        text address_address_2
        text address_address_3
        text address_address_4
        text address_address_5
        text address_city
        text address_country
        text address_county
        text address_province
        text address_state
        text address_zip_code
        text company_flx
        text cost_center
        text created_date_time
        timestamp created_on
        text cust_to_legal_entity_prop
        text description
        text description_de_de
        text description_default_value
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        text division_flx
        timestamp end_date
        text geozone_flx
        text head_of_unit
        text last_modified_date_time
        timestamp last_modified_on
        text location_group
        text name
        text name_de_de
        text name_default_value
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        text parent
        text standard_hours
        text status
        text timezone
    }
    candidate_background_inside_work_experience {
        text background_element_id PK
        text candidate_id FK
        text background_order_position
        text department
        timestamp end_date
        timestamp last_modified_date_time
        timestamp start_date
        text title
    }
    job_application_onboarding_status {
        text id PK
        text onboarding_id FK
        timestamp created_date
        timestamp last_modified_date
        text message
        text name
        text status
        text status_type
        text type
        text url
    }
    background_var_pay_employee_hist_data {
        text background_element_id PK
        double_precision basis
        text business_goal_code
        text country
        text currency_code
        text department
        text division
        timestamp end_date
        text incentive_plan_code
        text job_title
        timestamp last_modified_date
        text location
        text pay_grade
        text salary
        timestamp start_date
        double_precision tgt_pct
        text user_id
        text var_pay_program_name
    }
    employment_termination {
        timestamp end_date PK
        text id PK
        text user_id PK
        text created_by FK
        text last_modified_by FK
        timestamp benefits_end_date
        timestamp bonus_pay_expiration_date
        timestamp created_date_time
        boolean eligible_for_sal_continuation
        text event_reason
        text last_date_worked
        timestamp last_modified_date_time
        text new_main_employment_id
        text notes
        boolean ok_to_rehire
        timestamp payroll_end_date
        boolean regret_termination
        timestamp salary_end_date
        timestamp stock_end_date
    }
    employee_workflow_request {
        text id PK
        text wf_request_id FK
        text action_type
        timestamp effective_date
        text entity_type
        text event_reason
        text request_type
        text subject_id
        text wf_config
    }
    job_requisition_posting {
        text job_posting_id PK
        text job_req_id PK
        text last_modified_by FK
        text posted_by FK
        text agency_comments
        text board_name
        text channel_id
        text external_partner_account_id
        timestamp last_modified_date_time
        timestamp post_end_date
        timestamp post_end_date_offset
        timestamp post_start_date
        timestamp post_start_date_offset
        text status
    }
    work_schedule {
        text id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        text average_hours_per_day
        text average_hours_per_month
        text average_hours_per_week
        text average_hours_per_year
        text average_working_days_per_week
        text country
        timestamp created_date
        timestamp created_date_time
        text external_name_default_value
        text external_name_localized
        boolean flexible_requesting_allowed
        boolean individual_work_schedule
        timestamp last_modified_date_time
        text model_category
        text period_model
        text period_model_nav
        text search_string
        text shift_classification
        timestamp starting_date
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
        text time_recording_variant
    }
    background_award {
        text background_element_id PK
        text user_id PK
        text background_order_position
        text description
        text institution
        timestamp issue_date
        timestamp last_modified_date
        text name
    }
    offer_letter {
        text id PK
        text application_id FK
        text created_by FK
        text last_modified_by FK
        text body
        text body_locale
        text body_template_id
        text bonus_payout_freq
        text cand_response_comments
        timestamp cand_response_date
        text comment
        text country_code
        text country_name
        timestamp create_date
        text currency_code
        timestamp job_start_date
        text job_title
        timestamp last_modified_date
        text locale
        text locale_code
        text mailboxes
        timestamp offer_expiration_date
        text offer_letter
        timestamp offer_sent_date
        text overtime_rate
        text salary_rate
        text salary_rate_type
        text send_mode
        text status
        text stock_grant
        text stock_option
        text subject
        double_precision target_bonus_amount
        text target_bonus_percent
        text template_id
        text template_name
        text tokens
    }
    onboarding_process {
        text process_id PK
        text created_by FK
        text last_modified_by FK
        text activities_config
        text activities_status
        text bpe_process_instance_id
        text cancel_event_reason
        text cancel_offboarding_reason
        text cancel_onboarding_reason
        text cancellation_comment
        timestamp cancellation_date
        text cancellation_source
        boolean cancelled_due_to_restart
        timestamp created_date_time
        text employee_person_id
        timestamp end_date
        timestamp last_modified_date_time
        text locale
        text manager
        text manager_person_id
        text mdf_system_record_status
        text offboarding_activities_config
        text onb_2_master_id
        text onboarding_auto_hire_status
        text onboarding_hire_status
        timestamp onboarding_hired_date
        boolean onboarding_internal_hire
        boolean process_restart_needed
        boolean process_restarted
        text process_status
        text process_trigger
        text process_type
        text process_variant
        text stable_id
        timestamp start_date
        timestamp target_date
        text target_system
        text user
    }
    workflow_request {
        text id PK
        text created_by FK
        text last_modified_by FK
        text parent_id FK
        timestamp created_date_time
        text current_step_num
        timestamp last_modified_date_time
        text module
        text parent_wf_request_nav
        timestamp reminder_sent_date
        text status
        text total_steps
        text url
    }
    holiday {
        text id PK
        text country FK
        text created_by FK
        text last_modified_by FK
        timestamp created_date
        timestamp created_date_time
        timestamp last_modified_date_time
        text name_default_value
        text name_localized
        text old_name
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    external_time_record {
        text id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        timestamp created_date
        timestamp created_date_time
        timestamp date
        boolean delete_external_time
        timestamp last_modified_date_time
        text status
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    background_talent_pool {
        text background_element_id PK
        text user_id PK
        text talent_poolitem FK
        text background_order_position
        timestamp last_modified_date
        timestamp start_date
        text talent_pool_comments
        text talent_pool_item
        text talent_pool_status
    }
    work_opportunity_tax_credit {
        text id PK
        text wotc_forms_url
        text wotc_id
        text wotc_screening_url
        text wotc_status
    }
    per_personal {
        text person_id_external PK
        text created_by FK
        text last_modified_by FK
        text attachment_id
        text business_first_name
        text business_last_name
        timestamp created_date_time
        timestamp created_on
        text display_name
        text end_date
        text first_name
        text gender
        text include_all_records
        text initials
        timestamp last_modified_date_time
        timestamp last_modified_on
        text last_name
        text marital_status
        text middle_name
        text nationality
        text native_preferred_lang
        text operation
        text person_nav_birth_name
        text person_nav_country_of_birth
        text person_nav_created_by
        text person_nav_created_date_time
        text person_nav_created_on
        text person_nav_date_of_birth
        text person_nav_include_all_records
        text person_nav_last_modified_by
        text person_nav_last_modified_date_time
        text person_nav_last_modified_on
        text person_nav_per_person_uuid
        text person_nav_person_id
        text person_nav_person_id_external
        text person_nav_region_of_birth
        text person_nav_user_id
        text preferred_name
        text salutation
        text script
        text since
        text start_date
        text title
    }
    currency_conversion {
        timestamp effective_start_date PK
        text id PK
        text created_by FK
        text last_modified_by FK
        text to_currency FK
        text base_currency
        text conversion_rate
        timestamp created_date_time
        timestamp effective_end_date
        text effective_status
        text exchange_rate_type
        text external_name_default_value
        text external_name_localized
        timestamp last_modified_date_time
        text system_created_by
        timestamp system_created_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
    }
    employee_pay_comp_recurring {
        text pay_component PK
        text seq_number PK
        timestamp start_date PK
        text user_id PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        text currency_code
        timestamp end_date
        text frequency
        timestamp last_modified_date_time
        text notes
        text operation
        double_precision paycompvalue
    }
    currency {
        text code PK
        timestamp effective_start_date PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        text default_decimals
        text description_default_value
        text description_localized
        timestamp effective_end_date
        text external_name_default_value
        text external_name_localized
        timestamp last_modified_date_time
        text status
        text symbol
        text system_created_by
        timestamp system_created_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
    }
    job_application_status_label {
        text id PK
        text candidate_label
        text locale
        text status_label
    }
    per_global_info_usa {
        text country PK
        timestamp start_date PK
        text person_id_external PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp created_on
        timestamp end_date
        timestamp generic_date_1
        timestamp generic_date_10
        timestamp generic_date_2
        timestamp generic_date_3
        timestamp generic_date_4
        timestamp generic_date_5
        timestamp generic_date_6
        timestamp generic_date_7
        text generic_number_1
        text generic_number_10
        text generic_number_11
        text generic_number_12
        text generic_number_13
        text generic_number_14
        text generic_number_15
        text generic_number_16
        text generic_number_2
        text generic_number_3
        text generic_number_4
        text generic_number_5
        text generic_number_6
        text generic_number_7
        text generic_number_8
        text generic_number_9
        text generic_string_1
        text generic_string_10
        text generic_string_11
        text generic_string_12
        text generic_string_13
        text generic_string_14
        text generic_string_15
        text generic_string_16
        text generic_string_2
        text generic_string_3
        text generic_string_4
        text generic_string_5
        text generic_string_6
        text generic_string_7
        text generic_string_8
        text generic_string_9
        timestamp last_modified_date_time
        timestamp last_modified_on
    }
    candidate_background_talent_pool_corp {
        text background_element_id PK
        text background_order_position PK
        text candidate_id PK
        text talent_pool_item_corp FK
        text talent_pool_status FK
        timestamp last_modified_date_time
        timestamp start_date
        text talent_pool_comments
    }
    fo_translation {
        text external_code PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date
        timestamp created_date_time
        text fo_field
        text fo_objectid
        text fo_type
        timestamp last_modified_date
        timestamp last_modified_date_time
        timestamp last_modified_date_with_tz
        timestamp mdf_system_effective_end_date
        timestamp mdf_system_effective_start_date
        text mdf_system_entity_id
        text mdf_system_object_type
        text mdf_system_record_id
        text mdf_system_record_status
        text mdf_system_status
        text mdf_system_transaction_sequence
        text mdf_system_version_id
        text value_de_de
        text value_default_value
        text value_en_debug
        text value_en_gb
        text value_en_us
        text value_es_es
        text value_fr_fr
        text value_ja_jp
        text value_ko_kr
        text value_localized
        text value_nl_nl
        text value_pt_br
        text value_pt_pt
        text value_ru_ru
        text value_zh_cn
        text value_zh_tw
    }
    external_personal_info {
        text id PK
        text first_name
        timestamp last_modified_date_time
        text last_name
        text middle_name
    }
    job_requisition_operator {
        text operator_role_id PK
        text job_req_id PK
        text user_id FK
        boolean admin_selected_user_to_be_removed
        text email
        text fax
        text first_name
        boolean is_admin_selected
        text last_name
        text phone
        text user_name
    }
    background_promotability {
        text background_element_id PK
        text user_id PK
        text background_order_position
        text comment
        text function
        timestamp last_modified_date
        text level
        text timeframe
    }
    job_application_audit {
        text field_order_position PK
        text rev_number PK
        text changed_by FK
        text job_posting_id FK
        text last_modified_by FK
        text clob_field_ref
        text clob_new_value
        text clob_old_value
        text date_new_value
        text date_old_value
        text field_id
        text field_type
        timestamp job_post_end_date
        timestamp job_post_start_date
        timestamp last_modified_date
        text last_modified_external_id
        text merged_from
        text new_value
        text old_value
        text ref_type
        text rev_type
        text source
    }
    form_template {
        text id PK
        text name
        text type
    }
    job_application_interview {
        text id PK
        text application_id FK
        text cand_slot_map_id
        timestamp end_date
        integer is_time_set
        text notes
        text recruit_event_staff_id
        text source
        timestamp start_date
        text status
        text template_type
    }
    background_certificates {
        text background_element_id PK
        text user_id PK
        text license_country FK
        text license_state FK
        text background_order_position
        text description
        timestamp end_date
        text institution
        timestamp last_modified_date
        text license_name
        text license_number
        text name
        timestamp start_date
    }
    position_matrix_relationship {
        text matrix_relationship_type PK
        timestamp position_effective_start_date PK
        text position_id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        timestamp created_date_time
        timestamp last_modified_date_time
        text related_position
        text system_created_by
        timestamp system_created_date
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    job_application {
        text id PK
        text app_status_set_id FK
        text candidate_id FK
        text country_code FK
        text job_code FK
        text job_req_id FK
        text last_modified_by FK
        text referred_by FK
        text user_id FK
        text address
        text address_2
        text agency_info
        text app_locale
        text app_status_set_item_id
        text average_rating
        text base_salary
        text cand_conversion_processed
        text cand_just
        text cand_type_when_hired
        text cell_phone
        text city
        text conf_number
        text contact_email
        text conviction_details
        text country
        text criminal_conviction_instructions
        text criminal_conviction_label
        text current_location
        text current_title
        text cust_ref_check_first_name
        text cust_ref_check_last_name
        text cust_ref_check_org
        text cust_ref_check_phone
        text cust_ref_check_title
        text data_source
        text date_avail
        timestamp date_of_birth
        text duplicate_profile
        text exported_on
        text external_title
        text first_name
        boolean former_employee
        text gender
        text have_you_been_convicted
        timestamp hire_date
        text hired_on
        text home_phone
        text induction_add
        timestamp induction_date
        text instr_additional_documents
        text instr_app_additional_info
        text instr_app_advice
        text instr_app_return
        text instr_cand_app_details
        text instr_cand_approval
        text instr_cand_assess
        text instr_cand_fields
        text instr_cand_pers_info
        text instr_cand_screen
        text instr_eeoinstructions
        text instr_eeolable
        text instr_wotc
        text job_app_guid
        text job_offer_date
        text job_rate_of_pay
        timestamp job_start_date
        text known_as
        text last_modified_by_proxy
        timestamp last_modified_date_time
        text last_name
        timestamp med_date
        text med_loc
        text med_time
        text middle_name
        text non_applicant_status
        text owner
        timestamp ownership_date
        timestamp phone_screen_date
        text phone_screen_details
        text please_select
        text pos_title
        text profile_updated
        text psych_test_date
        text psych_test_time
        text rating
        text reasonable_accomodation
        text reference
        text reference_comments
        timestamp resume_upload_date
        text screen_date
        timestamp snap_shot_date
        text source
        text source_label
        text ssn
        timestamp start_date
        text state_other
        text status
        text status_comments
        double_precision time_to_hire
        text title
        text user_system_id
        text visa_num
        text zip
    }
    external_time_data {
        text id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        text category
        text cost_center
        timestamp created_date_time
        boolean delete_external_time
        timestamp end_date
        text end_time
        text hours
        timestamp last_modified_date_time
        timestamp logical_date
        timestamp start_date
        text start_time
        text status
        text system_record_status
        text time_type
    }
    job_requisition_locale {
        text id PK
        text job_req_id FK
        text external_job_desc_footer
        text external_job_desc_header
        text external_job_description
        text external_title
        text internal_job_desc_footer
        text internal_job_desc_header
        text job_description
        text job_title
        text locale
        text status
        text template_header_footer
    }
    job_offer_approver {
        text id PK
        text created_by FK
        text last_modified_by FK
        text offer_approval_id FK
        text offer_approver_id FK
        text approval_step_id
        text approver_action
        timestamp approver_action_date
        text approver_first_name
        text approver_last_name
        text approver_order
        text comment
        timestamp created_date
        timestamp last_modified_date
        text username
    }
    fo_division {
        text external_code PK
        timestamp start_date PK
        text created_by FK
        text last_modified_by FK
        text business_unit_flx
        timestamp created_date_time
        timestamp created_on
        text description
        text description_de_de
        text description_default_value
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        timestamp end_date
        text head_of_unit
        timestamp last_modified_date_time
        timestamp last_modified_on
        text name
        text name_de_de
        text name_default_value
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        text parent
        text status
    }
    employee_time_calendar {
        text employee_time_id PK
        text id PK
        text created_by FK
        text last_modified_by FK
        text work_schedule_internal_id FK
        timestamp created_date
        timestamp created_date_time
        timestamp date
        text deduction_quantity
        text end_time
        timestamp last_modified_date_time
        text quantity_in_days
        text quantity_in_hours
        text start_time
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    pick_list_value {
        text id PK
        timestamp pick_list_v_2_effective_start_date PK
        text pick_list_v_2_id PK
        text created_by FK
        text last_modified_by FK
        text parent_pick_list_value FK
        timestamp created_date
        timestamp created_date_time
        text l_value
        text label_default_value
        text label_localized
        timestamp last_modified_date_time
        text legacy_status
        text max_val
        text min_val
        text non_unique_external_code
        text opt_value
        text option_id
        text r_value
        text status
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
    }
    holiday_calendar {
        text id PK
        text created_by FK
        text last_modified_by FK
        text nominee_user_id FK
        text country
        timestamp created_date
        timestamp created_date_time
        timestamp last_modified_date_time
        text name_default_value
        text name_localized
        text old_name
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    country {
        timestamp effective_start_date PK
        text id PK
        text created_by FK
        text currency FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp effective_end_date
        text external_name_default_value
        text external_name_localized
        boolean is_drm_enabled
        boolean is_set_by_migrate
        timestamp last_modified_date_time
        text numeric_country_code
        text status
        text system_created_by
        timestamp system_created_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
        text territory_id
        text two_char_country_code
    }
    background_languages {
        text background_element_id PK
        text user_id PK
        text background_order_position
        text language_id
        timestamp last_modified_date
        text reading_prof
        text speaking_prof
        text variant
        text writing_prof
    }
    job_application_onboarding {
        text id PK
        text application_id FK
        text submitted_by FK
        text status
        timestamp submitted_on
    }
    form_route_step {
        text form_data_id PK
        integer step_order PK
        boolean completed
        boolean current
        text due_date
        boolean over_due
        text stage_name
        text stage_type
        text step_description
        text step_name
        text user_full_name
        text user_role
    }
    team_goal_owner {
        text id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        timestamp created_date_time
        timestamp last_modified_date_time
        text obj_id
        text owner_type
        text system_created_by
        timestamp system_created_date
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    candidate_comments {
        text id PK
        text candidate_id FK
        text associated_comment_id
        text associated_id
        text commentator
        text content
        text has_associated_comment
        text migrated_commentator_user_name
        text ref_type
    }
    background_check_request {
        text id PK
        text application_id FK
        text created_by FK
        timestamp created_date_time
        timestamp last_modified_date_time
        text order_status
        text response_code
        text response_detail
        text vendor_code
        text vendor_order_no
    }
    position_right_to_return {
        text id PK
        text created_by FK
        text position FK
        text user_id FK
        timestamp created_date_time
        text effective_status
        timestamp end_date
        text ga_end_job_info_id
        text ga_event_reason
        text ga_start_job_info_id
        text last_modified_by
        timestamp last_modified_date_time
        text loa_time_type
        text pos_tbhend_row_id
        text pos_tbhstart_row_id
        text reason
        text root_object_id
        timestamp start_date
        text system_record_status
    }
    employee_beneficiary {
        text user_id PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp end_date
        timestamp last_modified_date_time
        timestamp payroll_end_date
        text person_id_external
        timestamp planned_end_date
        timestamp start_date
    }
    employee_pension_payout {
        text user_id PK
        text created_by FK
        text last_modified_by FK
        text person_id_external FK
        timestamp created_date_time
        timestamp end_date
        timestamp last_modified_date_time
        timestamp payroll_end_date
        timestamp planned_end_date
        timestamp start_date
    }
    onboarding_process_task {
        text task_id PK
        text process_id PK
        text created_by FK
        text last_modified_by FK
        text comment
        text completed_by
        timestamp created_date_time
        timestamp end_date
        text extension_task_ref_id
        timestamp last_modified_date_time
        text mdf_system_record_status
        text responsibility_config
        timestamp start_date
        text status
        timestamp task_due_date
        text type
    }
    employee_time_sheet_entry {
        text id PK
        text employee_time_sheet_id PK
        text created_by FK
        text last_modified_by FK
        text cost_center
        timestamp created_date
        timestamp created_date_time
        text employee_time
        text end_time
        timestamp last_modified_date_time
        text quantity_in_hours
        timestamp start_date
        text start_time
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
        text time_type_name
    }
    pick_list {
        text _fivetran_id PK
        text created_by FK
        text last_modified_by FK
        text parent_pick_list_nav FK
        timestamp created_date
        timestamp created_date_time
        text display_order
        timestamp effective_end_date
        timestamp effective_start_date
        text id
        timestamp last_modified_date_time
        text legacy_pick_list_id
        text name
        text parent_pick_list
        text picklist_creation_source
        text status
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
    }
    candidate_background_talent_pool {
        text background_element_id PK
        text background_order_position PK
        text candidate_id PK
        timestamp last_modified_date_time
        timestamp start_date
        text talent_pool_comments
        text talent_pool_item
        text talent_pool_status
    }
    employee_time {
        text id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        text workflow_request_id FK
        text approval_status
        text cancellation_workflow_request_id
        text comment
        timestamp created_date
        timestamp created_date_time
        text cust_deliverytype
        text cust_expectedweek
        text cust_notificationdate
        text deduction_quantity
        boolean editable
        timestamp end_date
        text end_time
        boolean flexible_requesting
        text fraction_quantity
        timestamp last_modified_date_time
        timestamp loa_actual_return_date
        text loa_end_job_info_id
        timestamp loa_expected_return_date
        text loa_start_job_info_id
        text original_quantity_in_days
        text quantity_in_days
        text quantity_in_hours
        text recurrence_group
        timestamp start_date
        text start_time
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
        text time_record_origin
        text time_type
        boolean undetermined_end_date
        boolean workflow_initiated_by_admin
    }
    job_requisition {
        text id PK
        text job_code FK
        text last_modified_by FK
        text status_set_id FK
        text accommodation_cost
        text age
        text agency_fee
        text annual_cash_pay
        text annual_fb
        text annual_gratuity
        text annual_pf
        text annual_retirals
        text annual_sa
        text app_template_id
        text assess_rating_scale_name
        text candidate_progress
        text city
        text classification_time
        text classification_type
        timestamp closed_date_time
        text comment
        text comment_equip
        text commission
        boolean corporate_posting
        text cost_center_id
        text cost_of_hire
        text country
        timestamp created_date_time
        text currency
        text default_language
        text deleted
        text department
        text division
        double_precision erp_amount
        text facility
        text form_data_id
        timestamp form_due_date
        text function
        text hiring_manager_note
        text industry
        text instr_cost_hire
        text instr_equest
        text instr_equipment
        text instr_ers
        text instr_interview
        text instr_involved_parties
        text instr_managernote
        text instr_overall_comments
        text instr_pd
        text instr_rec_cost
        text instr_req
        text instr_req_dates
        text instr_req_details
        text instr_req_justify
        text instr_req_require
        text instr_salary
        text internal_status
        boolean intranet_posting
        boolean is_draft
        text job_req_guid
        text job_role
        timestamp job_start_date
        timestamp last_modified_date_time
        text last_modified_proxy_user_id
        text legentity
        text location
        text misc_cost
        text monthly_cash_pay
        text monthly_fb
        text monthly_gratuity
        text monthly_pf
        text monthly_retirals
        text monthly_sa
        text monthly_salary
        text number_openings
        text openings_filled
        text other_bonus
        text other_comms
        text other_compensation
        text other_equip
        text overall_scale_name
        text position_number
        text postalcode
        text rated_applicant_count
        text recruit_just
        text replacement_for_whom
        boolean restore_hiring_manager_team_admin_defaults
        boolean restore_recruiter_team_admin_defaults
        boolean restore_sourcer_team_admin_defaults
        boolean restore_vp_of_staffing_team_admin_defaults
        text reverse_scale
        text sal_rate_type
        text salary_base
        text salary_comment
        text salary_max
        text salary_min
        text state_province
        text stock_package
        double_precision target_bonus_amount
        timestamp temp_date
        text template_id
        text template_type
        text time_to_fill
        text total_earnings
        text total_fixed_pay
        text total_hire_cost
        text travel_cost
        text work_hours
    }
    employee_job {
        text seq_number PK
        timestamp start_date PK
        text user_id PK
        text created_by FK
        text last_modified_by FK
        text manager_id FK
        text assedic_cert_initial_state_num
        text assedic_cert_object_num
        text business_unit
        text company
        text contract_reference_for_aed
        text contract_type
        text cost_center
        text country_of_company
        timestamp created_date_time
        text default_overtime_compensation_variant
        text department
        text division
        text eeo_1_job_category
        text eeo_4_job_category
        text eeo_5_job_category
        text eeo_6_job_category
        text eeo_class
        text electoral_college_for_workers_representatives
        text electoral_college_for_works_council
        text emp_relationship
        text empl_status
        text employee_class
        text employee_workgroup_membership
        text employment_type
        timestamp end_date
        text event
        text event_reason
        boolean excl_executive_sector
        text family_relationship_with_employer
        timestamp fgts_date
        double_precision fgts_percent
        text flsa_status
        double_precision fte
        text harmful_agent_exposure
        boolean health_risk
        text holiday_calendar_code
        boolean is_competition_clause_active
        boolean is_fulltime_employee
        boolean is_side_line_job_allowed
        text job_code
        text job_title
        boolean labor_protection
        timestamp last_modified_date_time
        text location
        text municipal_insee_code
        text notes
        text pay_grade
        text pay_scale_area
        text pay_scale_group
        text pay_scale_level
        text pay_scale_type
        text position
        timestamp position_entry_date
        timestamp probation_period_end_date
        text regular_temp
        boolean resident_vote
        text sick_pay_supplement
        double_precision standard_hours
        boolean teachers_pension
        text time_recording_admissibility_code
        text time_recording_profile_code
        text time_recording_variant
        text time_type_profile_code
        text timezone
        double_precision travel_distance
        text work_location
        text worker_category
        double_precision working_days_per_week
        text workschedule_code
    }
    users {
        text id PK
        double_precision competency FK
        text country FK
        text emp_id FK
        text hr_id FK
        text job_code FK
        text manager_id FK
        text onboarding_id FK
        text address_line_1
        text address_line_2
        text address_line_3
        text assignment_uuid
        text bench_strength
        double_precision bonus_budget_amount
        double_precision bonus_target
        text business_phone
        text business_segment
        text cell_phone
        text citizenship
        text city
        text critical_talent_comments
        timestamp date_of_birth
        text date_of_current_position
        text date_of_position
        text default_full_name
        text default_locale
        text department
        text display_name
        text division
        text email
        text employee_class
        text ethnicity
        text fax
        text final_job_code
        text final_job_family
        text final_job_role
        text first_name
        boolean future_leader
        text gender
        timestamp hire_date
        text home_phone
        text impact_of_loss
        text impact_of_loss_comments
        text issue_comments
        text job_family
        text job_level
        text job_role
        text job_title
        boolean key_position
        timestamp last_modified_date_time
        text last_name
        timestamp last_review_date
        text level
        text local_currency_code
        text location
        double_precision lumpsum_2_target
        double_precision lumpsum_target
        boolean married
        text matrix_1_label
        text matrix_2_label
        boolean matrix_managed
        timestamp merit_effective_date
        text merit_target
        text mi
        boolean minority
        text nationality
        boolean new_to_position
        text nickname
        double_precision objective
        timestamp orig_hire_date
        text pay_grade
        double_precision performance
        double_precision potential
        double_precision promotion_amount
        double_precision raise_prorating
        text reason_for_leaving
        text relo_comments
        text relo_location
        text relo_willing
        text review_freq
        text risk_of_loss
        double_precision salary
        double_precision salary_budget_extra_2_percentage
        double_precision salary_budget_extra_percentage
        double_precision salary_budget_final_salary_percentage
        double_precision salary_budget_lumpsum_percentage
        double_precision salary_budget_merit_percentage
        double_precision salary_budget_promotion_percentage
        double_precision salary_budget_total_raise_percentage
        double_precision salary_local
        double_precision salary_prorating
        text salutation
        timestamp sci_last_modified
        text seating_chart
        timestamp service_date
        text ssn
        text state
        text status
        double_precision stock_budget_option_amount
        double_precision stock_budget_other_1_amount
        double_precision stock_budget_other_2_amount
        double_precision stock_budget_other_3_amount
        double_precision stock_budget_stock_amount
        double_precision stock_budget_unit_amount
        text suffix
        double_precision system_cost_of_source
        text system_source
        double_precision system_starting_salary
        text time_zone
        text title
        text username
        boolean veteran_disabled
        boolean veteran_medal
        boolean veteran_protected
        boolean veteran_separated
        text zip_code
    }
    fo_business_unit {
        text external_code PK
        timestamp start_date PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp created_on
        text description
        text description_de_de
        text description_default_value
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        timestamp end_date
        text head_of_unit
        timestamp last_modified_date_time
        timestamp last_modified_on
        text name
        text name_de_de
        text name_default_value
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        text status
    }
    interview_individual_assessment {
        text id PK
        text interview_overall_assessment_id FK
        text comment
        text is_deleted
        text rating
        text ref_id
        text type
    }
    job_application_status {
        text id PK
        text app_status_id FK
        text app_status_name
    }
    position {
        timestamp effective_start_date PK
        text id PK
        text created_by FK
        text job_code FK
        text last_modified_by FK
        text legacy_position_id FK
        text business_unit
        text change_reason
        text comment
        text company
        text cost_center
        timestamp created_date
        timestamp created_date_time
        text creation_source
        text criticality
        text department
        text description
        text division
        timestamp effective_end_date
        text effective_status
        text employee_class
        text external_name_default_value
        text external_name_localized
        text incumbent
        text job_level
        text job_title
        timestamp last_modified_date_time
        text location
        boolean multiple_incumbents_allowed
        text parent_position
        text pay_grade
        text pay_range
        boolean position_controlled
        text position_criticality
        text position_title
        text regular_temporary
        text standard_hours
        text system_entity_id
        text system_object_type
        text system_optimistic_lock_uuid
        text system_record_id
        text system_record_status
        text system_version_id
        text target_fte
        text technical_parameters
        text transaction_sequence
        text type
        boolean vacant
    }
    background_compensation {
        text background_element_id PK
        text user_id PK
        text background_order_position
        double_precision comparison_ratio
        text cur_salary
        text fin_salary
        text job_title
        timestamp last_modified_date
        double_precision lump_sum
        text merit
        text options
        text pm_rating
        text stock
        text system_comp_template_name
        timestamp system_review_end_date
        timestamp system_review_start_date
        text total_comp
    }
    candidate_background_certificate {
        text background_element_id PK
        text candidate_id FK
        text background_order_position
        text description
        timestamp end_date
        text institution
        timestamp last_modified_date_time
        text license_country
        text license_name
        text license_number
        text license_state
        text license_type
        text name
        timestamp start_date
    }
    background_talent_pool_corp {
        text background_element_id PK
        text user_id PK
        text talent_pool_item_corp FK
        text talent_pool_status FK
        text background_order_position
        timestamp last_modified_date
        timestamp start_date
        text talent_pool_comments
    }
    fo_location {
        text external_code PK
        text start_date PK
        text created_by FK
        text last_modified_by FK
        text created_date_time
        text created_on
        text description
        text description_de_de
        text description_default_value
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        text end_date
        text head_of_unit
        text last_modified_date_time
        text last_modified_on
        text name
        text name_de_de
        text name_default_value
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        text status
    }
    vendor_info {
        timestamp effective_start_date PK
        text id PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        text description_default_value
        text description_localized
        text effective_status
        timestamp last_modified_date_time
        text system_created_by
        timestamp system_created_date
        timestamp system_effective_end_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
        text vendor_name
    }
    fo_pay_grade {
        text external_code PK
        timestamp start_date PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp created_on
        text description
        timestamp end_date
        text internal_code
        timestamp last_modified_date_time
        timestamp last_modified_on
        text name
        text object_id
        text paygrade_level
        text status
    }
    job_requisition_question {
        text id PK
        text question_category
        text question_name
        text question_source
        text question_type
    }
    per_global_info_fra {
        text country PK
        timestamp start_date PK
        text person_id_external PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp created_on
        timestamp end_date
        timestamp generic_date_1
        timestamp generic_date_10
        timestamp generic_date_2
        timestamp generic_date_3
        timestamp generic_date_4
        timestamp generic_date_5
        timestamp generic_date_6
        timestamp generic_date_7
        text generic_number_1
        text generic_number_10
        text generic_number_11
        text generic_number_12
        text generic_number_13
        text generic_number_14
        text generic_number_15
        text generic_number_16
        text generic_number_2
        text generic_number_3
        text generic_number_4
        text generic_number_5
        text generic_number_6
        text generic_number_7
        text generic_number_8
        text generic_number_9
        text generic_string_1
        text generic_string_10
        text generic_string_11
        text generic_string_12
        text generic_string_13
        text generic_string_14
        text generic_string_15
        text generic_string_16
        text generic_string_17
        text generic_string_18
        text generic_string_19
        text generic_string_2
        text generic_string_20
        text generic_string_21
        text generic_string_22
        text generic_string_3
        text generic_string_4
        text generic_string_5
        text generic_string_6
        text generic_string_7
        text generic_string_8
        text generic_string_9
        timestamp last_modified_date_time
        timestamp last_modified_on
        text operation
    }
    background_courses {
        text background_element_id PK
        text user_id PK
        text instruction_type FK
        text background_order_position
        text course
        timestamp end_date
        text institution
        timestamp last_modified_date
        text length
    }
    job_requisition_group_operator {
        text operator_role PK
        text user_group_id PK
        text job_req_id PK
        boolean admin_selected_group_to_be_removed
        boolean is_admin_selected
        boolean is_disabled
        text user_group_name
    }
    candidate {
        text id PK
        text user_id FK
        text address
        text address_2
        text agree_to_privacy_statement
        text anonymized
        timestamp anonymized_date_time
        text candidate_locale
        text cell_phone
        text city
        text contact_email
        text country
        timestamp creation_date_time
        text current_title
        text data_privacy_id
        text dateof_availability
        boolean external_candidate
        text first_name
        text home_phone
        timestamp last_login_date_time
        timestamp last_modified_date_time
        text last_name
        text middle_name
        text partner_member_id
        text partner_source
        text password
        text primary_email
        timestamp privacy_accept_date_time
        boolean public_intranet
        text share_profile
        boolean visibility_option
        text zip
    }
    candidate_profile_extension {
        text id PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp last_modified_date_time
        text system_record_status
    }
    candidate_background_outside_work_experience {
        text background_element_id PK
        text candidate_id FK
        text employer_state FK
        text background_order_position
        text business_type
        text employer
        text employer_address
        text employer_city
        text employer_contact
        text employer_country
        text employer_email
        text employer_phone
        text employer_zip
        timestamp end_date
        timestamp last_modified_date_time
        text present_employer
        timestamp start_date
        text start_title
    }
    external_time_segment {
        text id PK
        text external_time_record_id PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date
        timestamp created_date_time
        text hours
        timestamp last_modified_date_time
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    per_email {
        text email_type PK
        text person_id_external PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp created_on
        text email_address
        boolean include_all_records
        boolean is_primary
        timestamp last_modified_date_time
        timestamp last_modified_on
        text operation
    }
    background_special_assign {
        text background_element_id PK
        text user_id PK
        text background_order_position
        text description
        timestamp end_date
        timestamp last_modified_date
        text project
        timestamp start_date
    }
    job_application_comments {
        text id PK
        text application_id FK
        text associated_comment_id FK
        text last_modified_by FK
        text user_id FK
        text associated_id
        text commentator
        text content
        text has_associated_comment
        text migrated_commentator_user_name
        text ref_type
    }
    job_offer {
        text id PK
        text created_by FK
        text last_modified_by FK
        text annual_cash_pay
        text annual_fb
        text annual_gratuity
        text annual_pf
        text annual_retirals
        text annual_sa
        timestamp anonymized_date
        text anonymized_flag
        text application_id
        text cand_just
        text candidate_name
        text commission
        timestamp created_date
        text currency
        text current_location
        text form_data_id
        text form_template_id
        text initial_comment
        text internal_status
        text job_rate_of_pay
        timestamp last_modified_date
        text location
        text monthly_cash_pay
        text monthly_fb
        text monthly_gratuity
        text monthly_pf
        text monthly_retirals
        text monthly_sa
        text monthly_salary
        boolean redefine_template_approvers
        text salary_base
        text stock_package
        double_precision target_bonus_amount
        timestamp temp_date
        text template_id
        text total_earnings
        text total_fixed_pay
        text version
    }
    holiday_category {
        text id PK
        text created_by FK
        text last_modified_by FK
        text amount
        timestamp created_date
        timestamp created_date_time
        text employee_payroll_run_results_external_code
        timestamp employee_payroll_run_results_system_effective_start_date
        timestamp end_date_when_earned
        text external_name
        text grouping_reason
        timestamp last_modified_date_time
        text payroll_provider_grouping_reason
        text payroll_provider_grouping_value
        text payroll_provider_unit_of_measurement
        text payroll_provider_wage_type
        text quantity
        timestamp start_date_when_earned
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
        text unit_of_measurement
        text wage_type
    }
    payment_information_detail {
        timestamp effective_start_date PK
        text external_code PK
        text worker_id PK
        text created_by FK
        text last_modified_by FK
        text account_number
        text account_owner
        text amount
        text bank
        text bank_country
        text business_identifier_code
        timestamp created_date
        timestamp created_date_time
        text currency
        text iban
        timestamp last_modified_date
        timestamp last_modified_date_time
        timestamp last_modified_date_with_tz
        timestamp mdf_system_effective_end_date
        timestamp mdf_system_effective_start_date
        text mdf_system_entity_id
        text mdf_system_object_type
        text mdf_system_record_id
        text mdf_system_record_status
        text mdf_system_status
        text mdf_system_transaction_sequence
        text mdf_system_version_id
        text pay_sequence
        text pay_type
        text payment_method
        text percent
        text purpose
        text routing_number
    }
    fo_cost_center {
        text external_code PK
        text start_date PK
        text created_by FK
        text last_modified_by FK
        text cost_center_external_object_id
        text cost_center_manager
        text created_date_time
        text created_on
        text cust_legal_entity_prop
        text description
        text description_de_de
        text description_default_value
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        text end_date
        text gl_statement_code
        text last_modified_date_time
        text last_modified_on
        text name
        text name_de_de
        text name_default_value
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        text parent
        text status
    }
    employee_time_sheet {
        text id PK
        text created_by FK
        text last_modified_by FK
        text user_id FK
        text workflow_request_id FK
        text approval_status
        text comment
        timestamp created_date
        timestamp created_date_time
        boolean editable
        timestamp end_date
        timestamp last_modified_date_time
        text planned_working_time
        text recorded_working_time
        text replaced_by
        text replaced_by_nav
        text replaces
        text replaces_nav
        timestamp start_date
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
        text workflow_action
        text working_time_account
    }
    background_preferred_next_move {
        text background_element_id PK
        text user_id PK
        text last_modified_by FK
        text to_currency FK
        text background_order_position
        text comments
        text function
        timestamp last_modified_date
        text level
        text timeframe
        text title
    }
    interview_overall_assessment {
        text id PK
        text interview_ref_id FK
        double_precision average_rating
        text comments
        text overall_rating
        text type
    }
    payroll_run_results_item {
        text external_id PK
        timestamp payroll_run_results_system_effective_start_date PK
        text payroll_run_results_external_id PK
        text created_by FK
        text last_modified_by FK
        double_precision amount
        timestamp created_date
        timestamp created_date_time
        timestamp end_date_when_earned
        text external_name
        text grouping_reason
        timestamp last_modified_date_time
        text payroll_provider_grouping_reason
        text payroll_provider_grouping_value
        text payroll_provider_unit_of_measurement
        text payroll_provider_wage_type
        text quantity
        timestamp start_date_when_earned
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
        text unit_of_measurement
        text wage_type
    }
    candidate_background_language {
        text background_element_id PK
        text candidate_id FK
        text background_order_position
        text languages
        timestamp last_modified_date_time
        text reading_prof
        text speaking_prof
        text writing_prof
    }
    payroll_run_results {
        text id PK
        timestamp system_effective_start_date PK
        text created_by FK
        text employment_id FK
        text last_modified_by FK
        text person_id FK
        text user_id FK
        text client_id
        text company_id
        timestamp created_date
        timestamp created_date_time
        text currency
        timestamp end_date_when_paid
        text external_name
        boolean is_void
        timestamp last_modified_date_time
        timestamp pay_date
        text payroll_id
        text payroll_provider_id
        text payroll_provider_payroll_run_type
        text payroll_run_type
        text sequence_number
        timestamp start_date_when_paid
        timestamp system_effective_end_date
        text system_entity_id
        text system_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
    }
    employment {
        text id PK
        text person_id PK
        text user_id PK
        text created_by FK
        text job_number FK
        text last_modified_by FK
        text assignment_class
        timestamp benefits_eligibility_start_date
        timestamp benefits_end_date
        timestamp bonus_pay_expiration_date
        timestamp created_date_time
        boolean eligible_for_sal_continuation
        boolean eligible_for_stock
        boolean employee_first_employment
        timestamp end_date
        timestamp first_date_worked
        boolean include_all_records
        double_precision initial_option_grant
        double_precision initial_stock_grant
        boolean is_contingent_worker
        boolean is_ecrecord
        text last_date_worked
        timestamp last_modified_date_time
        boolean ok_to_rehire
        timestamp original_start_date
        timestamp payroll_end_date
        text prev_employee_id
        timestamp professional_service_date
        boolean regret_termination
        timestamp salary_end_date
        timestamp seniority_date
        timestamp service_date
        timestamp start_date
        timestamp stock_end_date
    }
    background_mobility {
        text background_element_id PK
        text user_id PK
        text willingness FK
        text background_order_position
        timestamp last_modified_date
        text location
    }
    time_zone {
        timestamp effective_start_date PK
        text id PK
        text country FK
        text created_by FK
        text last_modified_by FK
        text comment
        timestamp created_date_time
        text effective_status
        timestamp last_modified_date_time
        text name_default_value
        text name_localized
        boolean supported
        text system_created_by
        timestamp system_created_date
        timestamp system_effective_end_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_transaction_sequence
        text system_version_id
        text utc_dst_offset
        text utc_offset
    }
    fo_job_code {
        text external_code PK
        timestamp start_date PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp created_on
        text cust_bonus_plan
        text cust_eng_non
        text cust_global_jobgrade
        text default_employee_class
        text default_job_level
        text default_supervisor_level
        text description
        text description_de_de
        text description_default_value
        text description_en_debug
        text description_en_gb
        text description_en_us
        text description_es_es
        text description_fr_fr
        text description_ja_jp
        text description_ko_kr
        text description_localized
        text description_nl_nl
        text description_pt_br
        text description_pt_pt
        text description_ru_ru
        text description_zh_cn
        text description_zh_tw
        text employee_class
        timestamp end_date
        text entity_oid
        text entity_uuid
        text grade
        boolean is_fulltime_employee
        text is_regular
        text job_function
        text job_level
        timestamp last_modified_date_time
        timestamp last_modified_on
        text mdf_system_record_id
        text name
        text name_de_de
        text name_default_value
        text name_en_debug
        text name_en_gb
        text name_en_us
        text name_es_es
        text name_fr_fr
        text name_ja_jp
        text name_ko_kr
        text name_localized
        text name_nl_nl
        text name_pt_br
        text name_pt_pt
        text name_ru_ru
        text name_zh_cn
        text name_zh_tw
        text parent_job_code
        text regular_temporary
        double_precision standard_hours
        text status
        text supervisor_level
        text worker_comp_code
    }
    job_application_status_audit_trail {
        text rev_number PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        timestamp last_modified_date_time
        text last_modified_proxy_user
        integer rev_type
        text skipped_status
        text status_comment
    }
    employee_time_valuation_result {
        text id PK
        text employee_time_sheet_id PK
        text created_by FK
        text last_modified_by FK
        text allowance_type
        text approval_status
        timestamp booking_date
        text cost_center
        timestamp created_date
        timestamp created_date_time
        text hours
        timestamp last_modified_date_time
        text pay_type_external_name
        text pay_type_name
        text posting_target
        timestamp system_effective_end_date
        timestamp system_effective_start_date
        text system_entity_id
        text system_object_type
        text system_record_id
        text system_record_status
        text system_status
        text system_transaction_sequence
        text system_version_id
        text time_type_group
    }
    successor {
        text id PK
        text created_by FK
        text last_modified_by FK
        text nominee_user_id FK
        timestamp last_modified_date_time
        text note
        double_precision readiness
        text readiness_label
        text status
        text status_label
    }
    talent_pool {
        timestamp effective_start_date PK
        text id PK
        text created_by FK
        text last_modified_by FK
        timestamp created_date_time
        text description_default_value
        text description_localized
        timestamp effective_end_date
        text effective_status
        boolean enable_readiness
        timestamp last_modified_date_time
        text name_default_value
        text name_localized
        text owner
        text system_created_by
        timestamp system_created_date
        text system_entity_id
        text system_last_modified_by
        timestamp system_last_modified_date
        text system_object_type
        text system_record_id
        text system_record_status
        text system_version_id
        text transaction_sequence
        text type
    }
    competency_rating {
        text id PK
        text user_id FK
        text form_content_id
        text form_data_id
        text guid
        timestamp last_modified
        timestamp last_modified_date_time
        integer module
        text rater
        text rater_category
        double_precision rating
        text scale_max
        text scale_min
        integer source
        text status
        integer type
        timestamp valid_from
        timestamp valid_to
    }
    pick_list_option {
        text id PK
        text parent_picklist_option FK
        text picklist_id FK
        text external_code
        double_precision max_value
        double_precision min_value
        double_precision option_value
        integer sort_order
        text status
    }
    employee_work_permit {
        text document_number PK
        timestamp issue_date PK
        text country PK
        text document_type PK
        text user_id PK
        text created_by FK
        text last_modified_by FK
        text attachment
        text attachment_file_name
        text attachment_file_size
        text attachment_file_type
        text attachment_id
        text attachment_mime_type
        text attachment_status
        timestamp created_date_time
        text document_title
        timestamp expiration_date
        boolean is_validated
        text issue_place
        text issuing_authority
        timestamp last_modified_date_time
        text notes
    }
    position_requisition_status {
        text id PK
        text created_by FK
        text last_modified_by FK
        text position_id FK
        text requisition_id FK
        timestamp created_date_time
        timestamp last_modified_date_time
        text processing_status
        text system_record_status
    }
    time_collector }o--|| users : "fk"
    time_collector }o--|| users : "fk"
    time_collector }o--|| users : "fk"
    candidate_background_education }o--|| candidate : "fk"
    background_memberships }o--|| users : "fk"
    background_community }o--|| users : "fk"
    employee_compensation }o--|| users : "fk"
    employee_compensation }o--|| users : "fk"
    employee_compensation }o--|| users : "fk"
    admin_reassign_offer_approver }o--|| job_application : "fk"
    admin_reassign_offer_approver }o--|| users : "fk"
    admin_reassign_offer_approver }o--|| job_requisition : "fk"
    admin_reassign_offer_approver }o--|| job_offer : "fk"
    admin_reassign_offer_approver }o--|| users : "fk"
    candidate_tags }o--|| candidate : "fk"
    employee_pay_comp_non_recurring }o--|| users : "fk"
    employee_pay_comp_non_recurring }o--|| users : "fk"
    employee_pay_comp_non_recurring }o--|| users : "fk"
    per_person }o--|| users : "fk"
    per_person }o--|| users : "fk"
    per_person }o--|| users : "fk"
    emp_cost_distribution_item }o--|| users : "fk"
    emp_cost_distribution_item }o--|| users : "fk"
    emp_cost_distribution_item }o--|| users : "fk"
    job_application_question_response }o--|| job_application : "fk"
    fo_job_function }o--|| users : "fk"
    fo_job_function }o--|| users : "fk"
    job_requisition_screening_question }o--|| job_requisition_question : "fk"
    job_requisition_screening_question }o--|| job_requisition_question : "fk"
    job_requisition_screening_question }o--|| job_requisition : "fk"
    form_user_rating_comment }o--|| users : "fk"
    background_inside_work_experience }o--|| users : "fk"
    work_order }o--|| vendor_info : "fk"
    work_order }o--|| users : "fk"
    work_order }o--|| users : "fk"
    background_check_result }o--|| background_check_request : "fk"
    fo_company }o--|| users : "fk"
    fo_company }o--|| users : "fk"
    background_education }o--|| users : "fk"
    background_education }o--|| pick_list_option : "fk"
    background_education }o--|| pick_list_option : "fk"
    background_education }o--|| pick_list_option : "fk"
    background_education }o--|| pick_list_option : "fk"
    fo_department }o--|| users : "fk"
    fo_department }o--|| users : "fk"
    fo_department }o--|| fo_cost_center : "fk"
    candidate_background_inside_work_experience }o--|| candidate : "fk"
    job_application_onboarding_status }o--|| job_application_onboarding : "fk"
    employment_termination }o--|| users : "fk"
    employment_termination }o--|| users : "fk"
    employment_termination }o--|| users : "fk"
    employee_workflow_request }o--|| workflow_request : "fk"
    job_requisition_posting }o--|| users : "fk"
    job_requisition_posting }o--|| users : "fk"
    job_requisition_posting }o--|| job_requisition : "fk"
    work_schedule }o--|| users : "fk"
    work_schedule }o--|| users : "fk"
    work_schedule }o--|| users : "fk"
    background_award }o--|| users : "fk"
    offer_letter }o--|| job_application : "fk"
    offer_letter }o--|| users : "fk"
    offer_letter }o--|| users : "fk"
    onboarding_process }o--|| users : "fk"
    onboarding_process }o--|| users : "fk"
    workflow_request }o--|| users : "fk"
    workflow_request }o--|| users : "fk"
    workflow_request }o--|| workflow_request : "fk"
    holiday }o--|| country : "fk"
    holiday }o--|| users : "fk"
    holiday }o--|| users : "fk"
    external_time_record }o--|| users : "fk"
    external_time_record }o--|| users : "fk"
    external_time_record }o--|| users : "fk"
    background_talent_pool }o--|| users : "fk"
    background_talent_pool }o--|| pick_list_option : "fk"
    work_opportunity_tax_credit }o--|| job_application : "fk"
    per_personal }o--|| users : "fk"
    per_personal }o--|| users : "fk"
    currency_conversion }o--|| users : "fk"
    currency_conversion }o--|| users : "fk"
    currency_conversion }o--|| currency : "fk"
    employee_pay_comp_recurring }o--|| users : "fk"
    employee_pay_comp_recurring }o--|| users : "fk"
    employee_pay_comp_recurring }o--|| users : "fk"
    currency }o--|| users : "fk"
    currency }o--|| users : "fk"
    job_application_status_label }o--|| job_application_status : "fk"
    per_global_info_usa }o--|| users : "fk"
    per_global_info_usa }o--|| per_person : "fk"
    per_global_info_usa }o--|| users : "fk"
    candidate_background_talent_pool_corp }o--|| candidate : "fk"
    candidate_background_talent_pool_corp }o--|| pick_list_option : "fk"
    candidate_background_talent_pool_corp }o--|| pick_list_option : "fk"
    fo_translation }o--|| users : "fk"
    fo_translation }o--|| users : "fk"
    job_requisition_operator }o--|| pick_list_option : "fk"
    job_requisition_operator }o--|| job_requisition : "fk"
    background_promotability }o--|| users : "fk"
    job_application_audit }o--|| job_requisition_posting : "fk"
    job_application_audit }o--|| users : "fk"
    job_application_audit }o--|| users : "fk"
    job_application_interview }o--|| job_application : "fk"
    background_certificates }o--|| users : "fk"
    background_certificates }o--|| pick_list_option : "fk"
    background_certificates }o--|| pick_list_option : "fk"
    position_matrix_relationship }o--|| position : "fk"
    position_matrix_relationship }o--|| users : "fk"
    position_matrix_relationship }o--|| users : "fk"
    position_matrix_relationship }o--|| users : "fk"
    job_application }o--|| users : "fk"
    job_application }o--|| employee_job : "fk"
    job_application }o--|| country : "fk"
    job_application }o--|| candidate : "fk"
    job_application }o--|| users : "fk"
    job_application }o--|| job_requisition : "fk"
    job_application }o--|| job_application_status : "fk"
    job_application }o--|| users : "fk"
    external_time_data }o--|| users : "fk"
    external_time_data }o--|| users : "fk"
    external_time_data }o--|| users : "fk"
    job_requisition_locale }o--|| job_requisition : "fk"
    job_offer_approver }o--|| job_offer : "fk"
    job_offer_approver }o--|| users : "fk"
    job_offer_approver }o--|| users : "fk"
    job_offer_approver }o--|| users : "fk"
    fo_division }o--|| users : "fk"
    fo_division }o--|| users : "fk"
    employee_time_calendar }o--|| users : "fk"
    employee_time_calendar }o--|| users : "fk"
    employee_time_calendar }o--|| work_schedule : "fk"
    pick_list_value }o--|| job_application : "fk"
    pick_list_value }o--|| job_application : "fk"
    pick_list_value }o--|| pick_list_value : "fk"
    holiday_calendar }o--|| users : "fk"
    holiday_calendar }o--|| users : "fk"
    holiday_calendar }o--|| users : "fk"
    country }o--|| users : "fk"
    country }o--|| currency : "fk"
    country }o--|| users : "fk"
    background_languages }o--|| users : "fk"
    job_application_onboarding }o--|| job_application : "fk"
    job_application_onboarding }o--|| users : "fk"
    team_goal_owner }o--|| users : "fk"
    team_goal_owner }o--|| users : "fk"
    team_goal_owner }o--|| users : "fk"
    candidate_comments }o--|| candidate : "fk"
    background_check_request }o--|| job_application : "fk"
    background_check_request }o--|| users : "fk"
    position_right_to_return }o--|| users : "fk"
    position_right_to_return }o--|| users : "fk"
    position_right_to_return }o--|| position : "fk"
    employee_beneficiary }o--|| users : "fk"
    employee_beneficiary }o--|| users : "fk"
    employee_beneficiary }o--|| users : "fk"
    employee_pension_payout }o--|| users : "fk"
    employee_pension_payout }o--|| users : "fk"
    employee_pension_payout }o--|| external_personal_info : "fk"
    employee_pension_payout }o--|| users : "fk"
    onboarding_process_task }o--|| onboarding_process : "fk"
    onboarding_process_task }o--|| users : "fk"
    onboarding_process_task }o--|| users : "fk"
    employee_time_sheet_entry }o--|| users : "fk"
    employee_time_sheet_entry }o--|| employee_time_sheet : "fk"
    employee_time_sheet_entry }o--|| users : "fk"
    pick_list }o--|| users : "fk"
    pick_list }o--|| users : "fk"
    pick_list }o--|| pick_list : "fk"
    candidate_background_talent_pool }o--|| candidate : "fk"
    employee_time }o--|| users : "fk"
    employee_time }o--|| users : "fk"
    employee_time }o--|| workflow_request : "fk"
    employee_time }o--|| users : "fk"
    job_requisition }o--|| job_application_status : "fk"
    job_requisition }o--|| candidate : "fk"
    job_requisition }o--|| employee_job : "fk"
    employee_job }o--|| users : "fk"
    employee_job }o--|| users : "fk"
    employee_job }o--|| users : "fk"
    employee_job }o--|| users : "fk"
    users }o--|| country : "fk"
    users }o--|| job_application_onboarding : "fk"
    users }o--|| employee_job : "fk"
    users }o--|| competency_rating : "fk"
    users }o--|| employment : "fk"
    users }o--|| users : "fk"
    users }o--|| users : "fk"
    fo_business_unit }o--|| users : "fk"
    fo_business_unit }o--|| users : "fk"
    interview_individual_assessment }o--|| interview_overall_assessment : "fk"
    job_application_status }o--|| job_application_status_label : "fk"
    position }o--|| users : "fk"
    position }o--|| employee_job : "fk"
    position }o--|| users : "fk"
    position }o--|| position : "fk"
    background_compensation }o--|| users : "fk"
    candidate_background_certificate }o--|| candidate : "fk"
    background_talent_pool_corp }o--|| pick_list_option : "fk"
    background_talent_pool_corp }o--|| pick_list_option : "fk"
    background_talent_pool_corp }o--|| users : "fk"
    fo_location }o--|| users : "fk"
    fo_location }o--|| users : "fk"
    vendor_info }o--|| users : "fk"
    vendor_info }o--|| users : "fk"
    fo_pay_grade }o--|| users : "fk"
    fo_pay_grade }o--|| users : "fk"
    per_global_info_fra }o--|| users : "fk"
    per_global_info_fra }o--|| per_person : "fk"
    per_global_info_fra }o--|| users : "fk"
    background_courses }o--|| users : "fk"
    background_courses }o--|| pick_list_option : "fk"
    job_requisition_group_operator }o--|| job_requisition : "fk"
    candidate }o--|| users : "fk"
    candidate_profile_extension }o--|| candidate : "fk"
    candidate_profile_extension }o--|| users : "fk"
    candidate_profile_extension }o--|| users : "fk"
    candidate_background_outside_work_experience }o--|| candidate : "fk"
    candidate_background_outside_work_experience }o--|| pick_list_option : "fk"
    external_time_segment }o--|| users : "fk"
    external_time_segment }o--|| users : "fk"
    external_time_segment }o--|| external_time_record : "fk"
    per_email }o--|| users : "fk"
    per_email }o--|| per_person : "fk"
    per_email }o--|| users : "fk"
    background_special_assign }o--|| pick_list_option : "fk"
    job_application_comments }o--|| job_application : "fk"
    job_application_comments }o--|| job_application_comments : "fk"
    job_application_comments }o--|| users : "fk"
    job_application_comments }o--|| users : "fk"
    job_offer }o--|| users : "fk"
    job_offer }o--|| users : "fk"
    holiday_category }o--|| users : "fk"
    holiday_category }o--|| users : "fk"
    payment_information_detail }o--|| users : "fk"
    payment_information_detail }o--|| users : "fk"
    payment_information_detail }o--|| employment : "fk"
    fo_cost_center }o--|| users : "fk"
    fo_cost_center }o--|| users : "fk"
    employee_time_sheet }o--|| users : "fk"
    employee_time_sheet }o--|| users : "fk"
    employee_time_sheet }o--|| workflow_request : "fk"
    employee_time_sheet }o--|| users : "fk"
    background_preferred_next_move }o--|| users : "fk"
    background_preferred_next_move }o--|| users : "fk"
    background_preferred_next_move }o--|| currency : "fk"
    interview_overall_assessment }o--|| job_application_interview : "fk"
    payroll_run_results_item }o--|| users : "fk"
    payroll_run_results_item }o--|| users : "fk"
    payroll_run_results_item }o--|| payroll_run_results : "fk"
    candidate_background_language }o--|| candidate : "fk"
    payroll_run_results }o--|| users : "fk"
    payroll_run_results }o--|| users : "fk"
    payroll_run_results }o--|| users : "fk"
    payroll_run_results }o--|| external_personal_info : "fk"
    payroll_run_results }o--|| employment : "fk"
    employment }o--|| users : "fk"
    employment }o--|| employee_job : "fk"
    employment }o--|| users : "fk"
    employment }o--|| users : "fk"
    background_mobility }o--|| users : "fk"
    background_mobility }o--|| pick_list_option : "fk"
    time_zone }o--|| country : "fk"
    time_zone }o--|| users : "fk"
    time_zone }o--|| users : "fk"
    fo_job_code }o--|| users : "fk"
    fo_job_code }o--|| users : "fk"
    job_application_status_audit_trail }o--|| users : "fk"
    job_application_status_audit_trail }o--|| users : "fk"
    employee_time_valuation_result }o--|| users : "fk"
    employee_time_valuation_result }o--|| employee_time_sheet : "fk"
    employee_time_valuation_result }o--|| users : "fk"
    successor }o--|| users : "fk"
    successor }o--|| users : "fk"
    successor }o--|| users : "fk"
    talent_pool }o--|| users : "fk"
    talent_pool }o--|| users : "fk"
    competency_rating }o--|| users : "fk"
    pick_list_option }o--|| pick_list_option : "fk"
    pick_list_option }o--|| pick_list : "fk"
    employee_work_permit }o--|| users : "fk"
    employee_work_permit }o--|| country : "fk"
    employee_work_permit }o--|| pick_list_option : "fk"
    employee_work_permit }o--|| users : "fk"
    employee_work_permit }o--|| users : "fk"
    position_requisition_status }o--|| position : "fk"
    position_requisition_status }o--|| users : "fk"
    position_requisition_status }o--|| users : "fk"
    position_requisition_status }o--|| job_requisition : "fk"
