erDiagram
    advance_shipping_notice_item {
        text index PK
        text advance_shipping_notice_id PK
        text description
        text expected_quantity
        text purchase_order_number
        text received_quantity
        text stock_keeping_unit
        text tracking_number
    }
    advance_shipping_notice {
        text id PK
        text arrival_date
        text client_advanced_shipment_notice
        text estimated_delivery_date
        text warehouse_name
    }
    hs_code {
        text id PK
        text code
        text long_description
        text short_description
    }
    item_available_inventory_lot_detail {
        text index PK
        text _fivetran_id PK
        text item_available_inventory_index PK
        text lot_number
        text quantity
    }
    item_available_inventory {
        text index PK
        text _fivetran_id PK
        text available_inventory_quantity
        text warehouse_name
    }
    item_lot_number {
        text index PK
        text _fivetran_id PK
        text expiration_date
        text lot_number
        text quantity
    }
    item {
        text _fivetran_id PK
        text hs_code_id FK
        text barcode
        text category
        text declared_value
        text description
        text haz_mat_type
        text height
        text is_expiration_tracked
        text is_haz_mat
        text is_label_only
        text is_lot_tracked
        text is_serial_tracked
        text length
        text origin_country
        text stock_keeping_unit
        text weight
        text width
    }
    order_business_stock_keeping_unit_item_lot {
        text index PK
        text order_business_stock_keeping_unit_index PK
        text order_business_stock_keeping_unit_order_business_id PK
        text expiration_date
        text lot_number
        text quantity
    }
    order_business_stock_keeping_unit_serial_number {
        text index PK
        text order_business_stock_keeping_unit_index PK
        text order_business_stock_keeping_unit_order_business_id PK
        text serial_number
    }
    order_business_stock_keeping_unit {
        text index PK
        text order_business_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    order_business {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_phone_number
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text reference_number
        text shipping_method
        text status_description
        text type
        text warehouse_name
    }
    backorder_dropship_stock_keeping_unit_item_lot {
        text index PK
        text backorder_dropship_stock_keeping_unit_backorder_dropship_id PK
        text backorder_dropship_stock_keeping_unit_index PK
        text expiration_date
        text lot_number
        text quantity
    }
    backorder_dropship_stock_keeping_unit_serial_number {
        text index PK
        text backorder_dropship_stock_keeping_unit_backorder_dropship_id PK
        text backorder_dropship_stock_keeping_unit_index PK
        text serial_number
    }
    backorder_dropship_stock_keeping_unit {
        text index PK
        text backorder_dropship_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    backorder_dropship {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_phone_number
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text reference_number
        text shipping_method
        text type
        text warehouse_name
    }
    order_dropship_stock_keeping_unit_item_lot {
        text index PK
        text order_dropship_stock_keeping_unit_index PK
        text order_dropship_stock_keeping_unit_order_dropship_id PK
        text expiration_date
        text lot_number
        text quantity
    }
    order_dropship_stock_keeping_unit_serial_number {
        text index PK
        text order_dropship_stock_keeping_unit_index PK
        text order_dropship_stock_keeping_unit_order_dropship_id PK
        text serial_number
    }
    order_dropship_stock_keeping_unit {
        text index PK
        text order_dropship_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    order_dropship {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_phone_number
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text reference_number
        text shipping_method
        text status_description
        text type
        text warehouse_name
    }
    order_consumer_stock_keeping_unit_item_lot {
        text index PK
        text order_consumer_stock_keeping_unit_index PK
        text order_consumer_stock_keeping_unit_order_consumer_id PK
        text expiration_date
        text lot_number
        text quantity
    }
    order_consumer_stock_keeping_unit_serial_number {
        text index PK
        text order_consumer_stock_keeping_unit_index PK
        text order_consumer_stock_keeping_unit_order_consumer_id PK
        text serial_number
    }
    order_consumer_stock_keeping_unit {
        text index PK
        text order_consumer_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    order_consumer {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_phone_number
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text reference_number
        text shipping_method
        text status_description
        text type
        text warehouse_name
    }
    backorder_consumer_stock_keeping_unit_item_lot {
        text index PK
        text backorder_consumer_stock_keeping_unit_backorder_consumer_id PK
        text backorder_consumer_stock_keeping_unit_index PK
        text expiration_date
        text lot_number
        text quantity
    }
    backorder_consumer_stock_keeping_unit_serial_number {
        text index PK
        text backorder_consumer_stock_keeping_unit_backorder_consumer_id PK
        text backorder_consumer_stock_keeping_unit_index PK
        text serial_number
    }
    backorder_consumer_stock_keeping_unit {
        text index PK
        text backorder_consumer_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    backorder_consumer {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_phone_number
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text reference_number
        text shipping_method
        text type
        text warehouse_name
    }
    backorder_wholesale_stock_keeping_unit_item_lot {
        text index PK
        text backorder_wholesale_stock_keeping_unit_backorder_wholesale_id PK
        text backorder_wholesale_stock_keeping_unit_index PK
        text expiration_date
        text lot_number
        text quantity
    }
    backorder_wholesale_stock_keeping_unit_serial_number {
        text index PK
        text backorder_wholesale_stock_keeping_unit_backorder_wholesale_id PK
        text backorder_wholesale_stock_keeping_unit_index PK
        text serial_number
    }
    backorder_wholesale_stock_keeping_unit {
        text index PK
        text backorder_wholesale_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    backorder_wholesale {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_phone_number
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text reference_number
        text shipping_method
        text type
        text warehouse_name
    }
    order_wholesale_stock_keeping_unit_item_lot {
        text index PK
        text order_wholesale_stock_keeping_unit_index PK
        text order_wholesale_stock_keeping_unit_order_wholesale_id PK
        text expiration_date
        text lot_number
        text quantity
    }
    order_wholesale_stock_keeping_unit_serial_number {
        text index PK
        text order_wholesale_stock_keeping_unit_index PK
        text order_wholesale_stock_keeping_unit_order_wholesale_id PK
        text serial_number
    }
    order_wholesale_stock_keeping_unit {
        text index PK
        text order_wholesale_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    order_wholesale {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text phone_number
        text reference_number
        text shipping_method
        text status_description
        text type
        text warehouse_name
    }
    backorder_business_stock_keeping_unit_item_lot {
        text index PK
        text backorder_business_stock_keeping_unit_backorder_business_id PK
        text backorder_business_stock_keeping_unit_index PK
        text expiration_date
        text lot_number
        text quantity
    }
    backorder_business_stock_keeping_unit_serial_number {
        text index PK
        text backorder_business_stock_keeping_unit_backorder_business_id PK
        text backorder_business_stock_keeping_unit_index PK
        text serial_number
    }
    backorder_business_stock_keeping_unit {
        text index PK
        text backorder_business_id PK
        text description
        text quantity
        text stock_keeping_unit
    }
    backorder_business {
        text id PK
        text comment
        text customer_address_1
        text customer_address_2
        text customer_address_3
        text customer_city
        text customer_company
        text customer_country
        text customer_email
        text customer_name
        text customer_phone_number
        text customer_postal_code
        text customer_state_or_province
        text date_backordered
        text date_created
        text reference_number
        text shipping_method
        text type
        text warehouse_name
    }
    advance_shipping_notice_item }o--|| advance_shipping_notice : "fk"
    item_available_inventory_lot_detail }o--|| item_available_inventory : "fk"
    item_available_inventory_lot_detail }o--|| item_available_inventory : "fk"
    item_available_inventory }o--|| item : "fk"
    item_lot_number }o--|| item : "fk"
    item }o--|| hs_code : "fk"
    order_business_stock_keeping_unit_item_lot }o--|| order_business_stock_keeping_unit : "fk"
    order_business_stock_keeping_unit_item_lot }o--|| order_business_stock_keeping_unit : "fk"
    order_business_stock_keeping_unit_serial_number }o--|| order_business_stock_keeping_unit : "fk"
    order_business_stock_keeping_unit_serial_number }o--|| order_business_stock_keeping_unit : "fk"
    order_business_stock_keeping_unit }o--|| order_business : "fk"
    backorder_dropship_stock_keeping_unit_item_lot }o--|| backorder_dropship_stock_keeping_unit : "fk"
    backorder_dropship_stock_keeping_unit_item_lot }o--|| backorder_dropship_stock_keeping_unit : "fk"
    backorder_dropship_stock_keeping_unit_serial_number }o--|| backorder_dropship_stock_keeping_unit : "fk"
    backorder_dropship_stock_keeping_unit_serial_number }o--|| backorder_dropship_stock_keeping_unit : "fk"
    backorder_dropship_stock_keeping_unit }o--|| backorder_dropship : "fk"
    order_dropship_stock_keeping_unit_item_lot }o--|| order_dropship_stock_keeping_unit : "fk"
    order_dropship_stock_keeping_unit_item_lot }o--|| order_dropship_stock_keeping_unit : "fk"
    order_dropship_stock_keeping_unit_serial_number }o--|| order_dropship_stock_keeping_unit : "fk"
    order_dropship_stock_keeping_unit_serial_number }o--|| order_dropship_stock_keeping_unit : "fk"
    order_dropship_stock_keeping_unit }o--|| order_dropship : "fk"
    order_consumer_stock_keeping_unit_item_lot }o--|| order_consumer_stock_keeping_unit : "fk"
    order_consumer_stock_keeping_unit_item_lot }o--|| order_consumer_stock_keeping_unit : "fk"
    order_consumer_stock_keeping_unit_serial_number }o--|| order_consumer_stock_keeping_unit : "fk"
    order_consumer_stock_keeping_unit_serial_number }o--|| order_consumer_stock_keeping_unit : "fk"
    order_consumer_stock_keeping_unit }o--|| order_consumer : "fk"
    backorder_consumer_stock_keeping_unit_item_lot }o--|| backorder_consumer_stock_keeping_unit : "fk"
    backorder_consumer_stock_keeping_unit_item_lot }o--|| backorder_consumer_stock_keeping_unit : "fk"
    backorder_consumer_stock_keeping_unit_serial_number }o--|| backorder_consumer_stock_keeping_unit : "fk"
    backorder_consumer_stock_keeping_unit_serial_number }o--|| backorder_consumer_stock_keeping_unit : "fk"
    backorder_consumer_stock_keeping_unit }o--|| backorder_consumer : "fk"
    backorder_wholesale_stock_keeping_unit_item_lot }o--|| backorder_wholesale_stock_keeping_unit : "fk"
    backorder_wholesale_stock_keeping_unit_item_lot }o--|| backorder_wholesale_stock_keeping_unit : "fk"
    backorder_wholesale_stock_keeping_unit_serial_number }o--|| backorder_wholesale_stock_keeping_unit : "fk"
    backorder_wholesale_stock_keeping_unit_serial_number }o--|| backorder_wholesale_stock_keeping_unit : "fk"
    backorder_wholesale_stock_keeping_unit }o--|| backorder_wholesale : "fk"
    order_wholesale_stock_keeping_unit_item_lot }o--|| order_wholesale_stock_keeping_unit : "fk"
    order_wholesale_stock_keeping_unit_item_lot }o--|| order_wholesale_stock_keeping_unit : "fk"
    order_wholesale_stock_keeping_unit_serial_number }o--|| order_wholesale_stock_keeping_unit : "fk"
    order_wholesale_stock_keeping_unit_serial_number }o--|| order_wholesale_stock_keeping_unit : "fk"
    order_wholesale_stock_keeping_unit }o--|| order_wholesale : "fk"
    backorder_business_stock_keeping_unit_item_lot }o--|| backorder_business_stock_keeping_unit : "fk"
    backorder_business_stock_keeping_unit_item_lot }o--|| backorder_business_stock_keeping_unit : "fk"
    backorder_business_stock_keeping_unit_serial_number }o--|| backorder_business_stock_keeping_unit : "fk"
    backorder_business_stock_keeping_unit_serial_number }o--|| backorder_business_stock_keeping_unit : "fk"
    backorder_business_stock_keeping_unit }o--|| backorder_business : "fk"
