erDiagram
    location {
        text _fivetran_id PK
        text episode_id FK
        text rank
        text starts_percent
        text starts_total
        text url
    }
    browser {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    application {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    author {
        text id PK
        text podcast_author_id FK
        text email
        text facebook_handle
        text facebook_link
        text href
        text instagram_handle
        text instagram_link
        text name
        text remove
        text twitter_handle
        text twitter_link
        text update
        text updated_at
        text user_id
        text website_domain
        text website_link
        text youtube_handle
        text youtube_link
    }
    last_seven {
        text podcast_id PK
        text href
        text total
    }
    speed {
        text _fivetran_id PK
        text episode_id FK
        text percentage
        text speed
    }
    hours_listened {
        text podcast_id PK
        text href
        text total
    }
    listener_analytics {
        text interval PK
        text podcast_id PK
        text percents
        text total
    }
    time_of_week {
        text _fivetran_id PK
        text podcast_id FK
        text count
        text day_of_week
        text hour_of_day
        text hour_of_week
        text rank
    }
    listener {
        text id PK
        text podcast_id FK
        text href
        text listeners_total
        text number
        text published_at
        text season_href
        text season_number
        text title
        text type
    }
    category_subcategories_collection {
        text index PK
        text _fivetran_id PK
        text label
        text rss_label
        text value
    }
    category {
        text _fivetran_id PK
        text label
        text rss_label
        text value
    }
    listening_method {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    analytics_download {
        text interval PK
        text podcast_episode_id PK
        text downloads_percent
        text downloads_total
    }
    analytics_download_collection {
        text id PK
        text podcast_episode_id PK
        text is_primary
        text name
        text published_at
        text scheduled_for
        text status
    }
    podcast_keyword {
        text id PK
        text podcast_id FK
        text delete
        text href
        text value
    }
    operating_system {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    listen {
        text episode_id PK
        text interval PK
        text downloads_percent
        text downloads_total
    }
    timezone {
        text _fivetran_id PK
        text common
        text label
        text offsets
        text value
    }
    average_completion {
        text id PK
        text episode_id FK
        text avg_completion
        text href
        text seconds_played
    }
    top_ten {
        text id PK
        text podcast_id FK
        text season_id FK
        text count
        text legacy_id
        text number
        text published_at
        text rank
        text season_number
        text title
        text type
    }
    podcast_category_collection {
        text _fivetran_id PK
        text podcast_category_id FK
        text href
        text label
        text value
    }
    podcast_category {
        text id PK
        text podcast_id FK
        text created_at
        text href
        text label
        text value
    }
    device_class {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    podcast_season {
        text _fivetran_id PK
        text podcast_id FK
        text href
        text number
    }
    listener_podcast {
        text end_date PK
        text start_date PK
        text podcast_id PK
        text href
        text total
    }
    marker {
        text id PK
        text episode_id FK
        text ad_limit
        text ad_type
        text href
        text max_duration_millisecond
        text name
        text offset_millisecond
        text offset_second
    }
    episode_keyword {
        text id PK
        text episode_id FK
        text delete
        text href
        text value
    }
    episode_feed {
        text id PK
        text episode_id FK
        text ad_free_feed_url
        text delete
        text description
        text enable_episode_number
        text enabled
        text enclosure_url
        text expires_at
        text external_feed_url
        text feed_url
        text has_ad_free_variant
        text href
        text image_url
        text is_ad_free
        text is_explicit
        text is_primary
        text name
        text no_index
        text preferred_bitrate
        text publish
        text published_at
        text redirect_url
        text regenerate_ad_free
        text reimport
        text rss_limit
        text schedule
        text scheduled_for
        text status
        text title
        text unexpire
        text unpublish
        text unschedule
        text update
    }
    episode_marker {
        text id PK
        text episode_id FK
        text ad_limit
        text ad_type
        text href
        text max_duration_millisecond
        text name
        text offset_millisecond
    }
    episode_author {
        text id PK
        text episode_id FK
        text href
        text name
        text remove
    }
    episode {
        text id PK
        text podcast_id FK
        text ad_free_audio_file_url
        text analytics_href
        text audio_content_type
        text audio_file_ad_free_url
        text audio_file_delete
        text audio_file_href
        text audio_file_name
        text audio_file_path
        text audio_file_path_tc
        text audio_file_size
        text audio_file_url
        text audio_href
        text audio_status
        text campaign_preview_href
        text created_at
        text custom_url
        text dashboard_link
        text days_since_release
        text delete
        text description
        text duration
        text enclosure_url
        text episode_url
        text guid
        text href
        text image_path
        text image_url
        text is_explicit
        text is_hidden
        text is_published
        text long_description
        text number
        text publish
        text published_at
        text recast_color
        text recast_image
        text recast_image_url
        text schedule
        text scheduled_for
        text season_href
        text season_number
        text sign_url
        text slug
        text sponsor_href
        text status
        text title
        text token
        text transcription
        text type
        text unschedule
        text update
        text updated_at
        text upload_complete
        jsonb warning
        text waveform_json
        text waveform_pack
    }
    device {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    location_analytics {
        text id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text name
        text rank
        text state
        text states_href
    }
    embed_episode {
        text id PK
        text podcast_id FK
        text avg_completion_href
        text href
        text number
        text published_at
        text rank
        text season_href
        text season_number
        text start
        text stream
        text title
        text type
    }
    average_download {
        text podcast_id PK
        text href
        text total
    }
    network_type {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    podcast_distribution_channel {
        text id PK
        text podcast_id FK
        text distribution_channel_href
        text distribution_channel_id
        text distribution_channel_name
        text href
        text url
    }
    podcast_author {
        text id PK
        text podcast_id FK
        text href
        text name
        text remove
    }
    provider {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text end_date
        text name
        text rank
        text start_date
    }
    web_player {
        text _fivetran_id PK
        text podcast_id FK
        text downloads_percent
        text downloads_total
        text name
        text rank
    }
    podcast_current_user_permission_label {
        text index PK
        text podcast_id PK
        text label_name
    }
    podcast_current_user_permission_app_key {
        text index PK
        text podcast_id PK
        text app_key_name
    }
    podcast_account {
        text id PK
        text podcast_id PK
        text podcast_account_id FK
        text account_owner_email
        text account_owner_id
        text account_owner_image_url
        text account_owner_name
        text href
        text is_custom_plan
        text is_default
        text name
    }
    podcast {
        text id PK
        text account_id
        text current_user_permission_app_key
        text current_user_permission_can_create_episode
        text current_user_permission_can_delete
        text current_user_permission_can_edit
        text current_user_permission_can_edit_ad_creative
        text current_user_permission_can_edit_admin_permission
        text current_user_permission_can_edit_advanced
        text current_user_permission_can_edit_marker
        text current_user_permission_can_edit_permission
        text current_user_permission_can_publish
        text current_user_permission_can_upload
        text current_user_permission_can_view
        text current_user_permission_can_view_ad_creative
        text current_user_permission_can_view_analytics
        text current_user_permission_can_view_episode
        text current_user_permission_label
        text current_user_permission_name
        text current_user_permission_rank
        text display_owner_email
        text episode_count
        text href
        text image_url
        text import
        text is_migration
        text is_pending_invitation
        text permission_app_key
        jsonb permission_app_keys
        text permission_can_create_episode
        text permission_can_delete
        text permission_can_edit
        text permission_can_edit_ad_creative
        text permission_can_edit_admin_permission
        text permission_can_edit_advanced
        text permission_can_edit_marker
        text permission_can_edit_permission
        text permission_can_publish
        text permission_can_upload
        text permission_can_view
        text permission_can_view_ad_creative
        text permission_can_view_analytics
        text permission_can_view_episode
        text permission_id
        text permission_label
        jsonb permission_labels
        text permission_name
        text permission_rank
        text status
        text title
    }
    location }o--|| episode : "fk"
    browser }o--|| podcast : "fk"
    application }o--|| podcast : "fk"
    author }o--|| podcast_author : "fk"
    last_seven }o--|| podcast : "fk"
    speed }o--|| episode : "fk"
    hours_listened }o--|| podcast : "fk"
    listener_analytics }o--|| podcast : "fk"
    time_of_week }o--|| podcast : "fk"
    listener }o--|| podcast : "fk"
    category_subcategories_collection }o--|| category : "fk"
    listening_method }o--|| podcast : "fk"
    podcast_keyword }o--|| podcast : "fk"
    operating_system }o--|| podcast : "fk"
    average_completion }o--|| episode : "fk"
    top_ten }o--|| podcast_season : "fk"
    top_ten }o--|| podcast : "fk"
    podcast_category_collection }o--|| podcast_category : "fk"
    podcast_category }o--|| podcast : "fk"
    device_class }o--|| podcast : "fk"
    podcast_season }o--|| podcast : "fk"
    listener_podcast }o--|| podcast : "fk"
    marker }o--|| episode : "fk"
    episode_keyword }o--|| episode : "fk"
    episode_feed }o--|| episode : "fk"
    episode_marker }o--|| episode : "fk"
    episode_author }o--|| episode : "fk"
    episode }o--|| podcast : "fk"
    device }o--|| podcast : "fk"
    location_analytics }o--|| podcast : "fk"
    embed_episode }o--|| podcast : "fk"
    average_download }o--|| podcast : "fk"
    network_type }o--|| podcast : "fk"
    podcast_distribution_channel }o--|| podcast : "fk"
    podcast_author }o--|| podcast : "fk"
    provider }o--|| podcast : "fk"
    web_player }o--|| podcast : "fk"
    podcast_current_user_permission_label }o--|| podcast : "fk"
    podcast_current_user_permission_app_key }o--|| podcast : "fk"
    podcast_account }o--|| podcast : "fk"
    podcast_account }o--|| podcast : "fk"
