erDiagram
    case_message {
        text cases_id PK
        text message_guid PK
        text anchor
        text case_message_direction
    }
    case_tag {
        text cases_id PK
        text tag_id PK
        text updated_by
        text updated_on
    }
    cases {
        text id PK
        text assigned_by
        text assignees
        text closed_time
        text created_by
        text created_time
        text group_id
        text priority
        text queue_id
        text status
        text type
        text updated_time
    }
    instagram_profile_analytic {
        text _fivetran_id PK
        integer comments_count
        text customer_id
        bigint customer_profile_id
        text date
        integer email_contacts
        integer followers_count
        integer followers_gained
        integer followers_lost
        integer get_directions_clicks
        integer impressions
        integer impressions_unique
        integer likes
        integer net_follower_growth
        integer phone_call_clicks
        jsonb posts_sent_by_content_type
        jsonb posts_sent_by_post_type
        integer posts_sent_count
        integer profile_views_unique
        bigint reactions
        integer saves
        integer shares_count
        integer story_replies
        integer text_message_clicks
        bigint video_views
        integer website_clicks
    }
    facebook_profile_analytic {
        text _fivetran_id PK
        integer comments_count
        integer cta_clicks_login
        text customer_id
        bigint customer_profile_id
        text date
        integer event_rsvps
        integer followers_count
        integer followers_gained
        integer followers_gained_organic
        integer followers_gained_paid
        integer followers_lost
        integer impressions
        integer impressions_nonviral
        integer impressions_nonviral_unique
        integer impressions_organic
        integer impressions_organic_unique
        integer impressions_paid
        integer impressions_paid_unique
        integer impressions_unique
        integer impressions_viral
        integer impressions_viral_unique
        integer likes
        integer negative_feedback
        integer net_follower_growth
        integer offer_claims
        integer place_checkins
        integer positive_feedback_other
        integer post_content_clicks_other
        integer post_engagements
        integer post_impressions
        integer post_impressions_nonviral
        integer post_impressions_organic
        integer post_impressions_paid
        integer post_impressions_viral
        integer post_link_clicks
        integer post_photo_view_clicks
        integer post_video_play_clicks
        jsonb posts_sent_by_content_type
        jsonb posts_sent_by_post_type
        integer posts_sent_count
        integer profile_actions
        integer profile_views
        jsonb question_answers
        integer reactions
        integer reactions_angry
        integer reactions_haha
        integer reactions_love
        integer reactions_sad
        integer reactions_wow
        integer shares_count
        integer tab_views
        integer tab_views_login
        integer tab_views_logout
        double_precision video_view_time
        bigint video_views
        bigint video_views_10_s
        bigint video_views_10_s_autoplay
        bigint video_views_10_s_click_to_play
        bigint video_views_10_s_organic
        bigint video_views_10_s_paid
        bigint video_views_10_s_repeat
        bigint video_views_10_s_unique
        bigint video_views_30_s_complete
        bigint video_views_30_s_complete_autoplay
        bigint video_views_30_s_complete_click_to_play
        bigint video_views_30_s_complete_organic
        bigint video_views_30_s_complete_paid
        bigint video_views_30_s_complete_repeat
        bigint video_views_30_s_complete_unique
        bigint video_views_autoplay
        bigint video_views_click_to_play
        bigint video_views_organic
        bigint video_views_paid
        bigint video_views_partial
        bigint video_views_partial_autoplay
        bigint video_views_partial_click_to_play
        bigint video_views_partial_organic
        bigint video_views_partial_paid
        bigint video_views_partial_repeat
        bigint video_views_repeat
        bigint video_views_unique
    }
    tiktok_profile_analytic {
        text _fivetran_id PK
        integer comments_count_total
        text customer_id
        bigint customer_profile_id
        text date
        jsonb followers_by_gender
        integer followers_count
        integer followers_online
        integer likes_total
        integer net_follower_growth
        jsonb posts_sent_by_post_type
        integer posts_sent_count
        integer profile_views_total
        integer shares_count_total
        bigint video_views_total
    }
    tiktok_profile_post {
        text _fivetran_id PK
        jsonb clickthrough_link
        integer comments_count
        text content_category
        timestamp created_time
        text customer_id
        bigint customer_profile_id
        jsonb from
        text guid
        integer impression_source_follow
        integer impression_source_for_you
        integer impression_source_hashtag
        integer impression_source_personal_profile
        integer impression_source_sound
        integer impression_source_unspecified
        integer impressions_unique
        jsonb internal
        integer likes
        text perma_link
        text post_category
        text post_type
        integer reactions
        boolean sent
        integer shares_count
        text text
        bigint video_length
        double_precision video_view_time
        double_precision video_view_time_per_view
        bigint video_views
        text video_views_p_100_per_view
        jsonb visual_media
    }
    instagram_profile_post {
        text _fivetran_id PK
        jsonb clickthrough_link
        integer comments_count
        text content_category
        timestamp created_time
        text customer_id
        bigint customer_profile_id
        jsonb from
        text guid
        jsonb hashtags
        integer impressions
        integer impressions_unique
        jsonb internal
        integer likes
        text perma_link
        text post_category
        text post_type
        text profile_guid
        integer reactions
        integer saves
        boolean sent
        integer shares_count
        integer story_exits
        integer story_taps_back
        integer story_taps_forward
        text text
        bigint video_views
        jsonb visual_media
    }
    pinterest_profile_analytic {
        text _fivetran_id PK
        text customer_id
        bigint customer_profile_id
        text date
        integer followers_count
        integer followers_gained
        integer followers_lost
        jsonb inbox_counts_sent
        jsonb inbox_received_sent
        integer net_follower_growth
        integer net_following_growth
        integer pin_count
    }
    twitter_profile_post {
        text _fivetran_id PK
        jsonb clickthrough_link
        integer comments_count
        text content_category
        timestamp created_time
        text customer_id
        bigint customer_profile_id
        integer engagements_other
        jsonb from
        text guid
        jsonb hashtags
        integer impressions
        jsonb internal
        integer likes
        text perma_link
        integer post_app_engagements
        integer post_app_installs
        integer post_app_opens
        text post_category
        integer post_content_clicks
        integer post_content_clicks_other
        integer post_detail_expand_clicks
        integer post_followers_gained
        integer post_followers_lost
        integer post_hashtag_clicks
        integer post_link_clicks
        integer post_media_clicks
        integer post_media_views
        integer post_profile_clicks
        text post_type
        text profile_guid
        integer reactions
        boolean sent
        integer shares_count
        text text
        text title
        bigint video_views
        jsonb visual_media
    }
    tag_group {
        integer id PK
        integer tag_id PK
    }
    tag {
        integer customer_id PK
        integer id PK
        boolean active
        boolean any_group
        text text
    }
    group {
        integer customer_id PK
        integer id PK
        text name
    }
    linkedin_profile_post {
        text _fivetran_id PK
        jsonb clickthrough_link
        integer comments_count
        text content_category
        timestamp created_time
        text customer_id
        bigint customer_profile_id
        jsonb from
        text guid
        integer impressions
        jsonb internal
        text perma_link
        text post_category
        integer post_content_clicks
        text post_type
        text profile_guid
        integer reactions
        boolean sent
        integer shares_count
        text text
        text title
        bigint video_views
        jsonb visual_media
    }
    pinterest_profile_post {
        text _fivetran_id PK
        text board_name
        jsonb clickthrough_link
        integer comments_count
        text content_category
        timestamp created_time
        text customer_id
        bigint customer_profile_id
        jsonb from
        text guid
        jsonb internal
        text perma_link
        text post_category
        text post_type
        integer saves
        jsonb visual_media
    }
    profile_group {
        integer id PK
        integer customer_id PK
        integer profile_id PK
    }
    profile {
        integer customer_id PK
        integer id PK
        text name
        text native_id
        text native_name
        text network_type
    }
    twitter_profile_analytic {
        text _fivetran_id PK
        integer comments_count
        text customer_id
        bigint customer_profile_id
        text date
        integer engagements_other
        integer followers_count
        integer impressions
        integer likes
        integer net_follower_growth
        integer post_app_engagements
        integer post_app_installs
        integer post_app_opens
        integer post_content_clicks
        integer post_content_clicks_other
        integer post_detail_expand_clicks
        integer post_hashtag_clicks
        integer post_link_clicks
        integer post_media_clicks
        integer post_media_views
        integer post_profile_clicks
        jsonb posts_sent_by_content_type
        jsonb posts_sent_by_post_type
        integer posts_sent_count
        integer reactions
        integer shares_count
        bigint video_views
    }
    message {
        text guid PK
        text case_id
        text clickthrough_link_long
        text clickthrough_link_name
        text clickthrough_link_short
        text content_category
        text created_time
        text customer_profile_id
        text from_guid
        text from_name
        text from_profile_picture
        text from_screen_name
        text hashtags
        text inbox_permalink
        text internal_tags
        text network
        text perma_link
        text post_category
        text post_type
        text profile_guid
        text sent
        text sent_by_email
        text sent_by_first_name
        text sent_by_id
        text sent_by_image
        text sent_by_last_name
        text text
        text title
        text visual_media
    }
    youtube_profile_post {
        text _fivetran_id PK
        integer annotation_click_through_rate
        integer annotation_clickable_impressions
        integer annotation_clicks
        integer annotation_closable_impressions
        integer annotation_close_rate
        integer annotation_closes
        integer annotation_impressions
        integer card_click_rate
        integer card_clicks
        integer card_impressions
        integer card_teaser_click_rate
        integer card_teaser_clicks
        integer card_teaser_impressions
        jsonb clickthrough_link
        integer comments_count
        text content_category
        timestamp created_time
        text customer_id
        bigint customer_profile_id
        integer dislikes
        integer estimated_minutes_watched
        integer estimated_red_minutes_watched
        jsonb from
        text guid
        jsonb internal
        integer likes
        text perma_link
        text post_category
        integer post_content_clicks_other
        text post_type
        text profile_guid
        integer reactions
        bigint red_video_views
        boolean sent
        integer shares_count
        integer subscribers_gained
        integer subscribers_lost
        text text
        text title
        integer video_view_percentage
        double_precision video_view_time_per_view
        bigint video_views
        integer videos_added_to_playlist
        integer videos_removed_from_playlist
        jsonb visual_media
    }
    facebook_profile_post {
        text _fivetran_id PK
        jsonb clickthrough_link
        integer comments_count
        text content_category
        timestamp created_time
        text customer_id
        bigint customer_profile_id
        integer engagements_follower_unique
        integer engagements_unique
        jsonb from
        text guid
        jsonb hashtags
        integer impressions
        integer impressions_follower
        integer impressions_follower_unique
        integer impressions_nonfollower
        integer impressions_nonviral
        integer impressions_nonviral_unique
        integer impressions_organic_unique
        integer impressions_paid
        integer impressions_paid_unique
        integer impressions_unique
        integer impressions_viral
        integer impressions_viral_unique
        jsonb internal
        integer likes
        integer negative_feedback
        integer negative_feedback_unique
        text perma_link
        text post_category
        integer post_content_clicks
        integer post_content_clicks_other
        integer post_content_clicks_unique
        integer post_link_clicks
        integer post_link_clicks_unique
        integer post_other_clicks_unique
        integer post_photo_view_clicks
        integer post_photo_view_clicks_unique
        text post_type
        bigint post_video_play_clicks
        bigint post_video_play_clicks_unique
        text profile_guid
        jsonb question_answers
        integer reactions
        integer reactions_angry
        integer reactions_haha
        integer reactions_love
        integer reactions_sad
        integer reactions_wow
        boolean sent
        integer shares_count
        text text
        text title
        integer video_ad_break_cost_per_impression
        integer video_ad_break_earnings
        integer video_ad_break_impressions
        bigint video_length
        double_precision video_view_time
        bigint video_view_time_organic
        bigint video_view_time_paid
        double_precision video_view_time_per_view
        bigint video_views
        bigint video_views_10_s
        bigint video_views_10_s_autoplay
        bigint video_views_10_s_click_to_play
        bigint video_views_10_s_organic
        bigint video_views_10_s_paid
        bigint video_views_10_s_sound_off
        bigint video_views_10_s_sound_on
        bigint video_views_10_s_unique
        bigint video_views_30_s_complete
        bigint video_views_30_s_complete_autoplay
        bigint video_views_30_s_complete_click_to_play
        bigint video_views_30_s_complete_organic
        bigint video_views_30_s_complete_paid
        bigint video_views_30_s_complete_unique
        bigint video_views_autoplay
        bigint video_views_click_to_play
        bigint video_views_organic
        bigint video_views_organic_unique
        bigint video_views_p_95
        bigint video_views_p_95_organic
        bigint video_views_p_95_organic_unique
        bigint video_views_p_95_paid
        bigint video_views_p_95_paid_unique
        bigint video_views_paid
        bigint video_views_paid_unique
        bigint video_views_partial
        bigint video_views_partial_autoplay
        bigint video_views_partial_click_to_play
        bigint video_views_partial_organic
        bigint video_views_partial_paid
        bigint video_views_sound_off
        bigint video_views_sound_on
        bigint video_views_unique
        jsonb visual_media
    }
    linkedin_profile_analytic {
        text _fivetran_id PK
        integer comments_count
        text customer_id
        bigint customer_profile_id
        text date
        integer followers_count
        integer followers_gained
        integer followers_gained_organic
        integer followers_gained_paid
        integer followers_lost
        integer impressions
        integer impressions_unique
        integer net_follower_growth
        integer post_content_clicks
        jsonb posts_sent_by_content_type
        jsonb posts_sent_by_post_type
        integer posts_sent_count
        integer reactions
        integer shares_count
    }
    user {
        integer customer_id PK
        integer id PK
        text name
    }
    youtube_profile_analytic {
        text _fivetran_id PK
        text customer_id
        bigint customer_profile_id
        text date
        integer followers_count
        integer followers_gained
        integer followers_lost
        integer net_follower_growth
    }
    case_message }o--|| message : "fk"
    case_message }o--|| cases : "fk"
    case_tag }o--|| tag : "fk"
    case_tag }o--|| cases : "fk"
    tag_group }o--|| tag : "fk"
    profile_group }o--|| profile : "fk"
    profile_group }o--|| profile : "fk"
