erDiagram
    click_and_commission_report {
        text _fivetran_id PK
        text currency
        text date
        text device_type
        text ppc_clickout_count
        text ppc_commission
        text vertical
    }
