erDiagram
    business_snapshot_cost_stat {
        text period_key PK
        double_precision cogs
        double_precision marketing
        double_precision sales
    }
    business_snapshot_revenue_stat {
        text period_key PK
        double_precision amount_renewed_that_was_up_gross
        double_precision amount_renewed_that_was_up_net
        double_precision bookings
        double_precision churn
        double_precision downsell
        double_precision existing
        double_precision influx
        double_precision metered
        double_precision new_bookings
        double_precision new_count
        double_precision non_recurring
        double_precision non_renewal_upsell
        double_precision percent_recurring
        double_precision reactivated_bookings
        double_precision recurring_period_growth
        double_precision recurring_revenue_with_rolling_metered
        double_precision renewal_bookings
        double_precision rolling_metered
        double_precision total
        double_precision total_period_growth
        double_precision total_period_revenue
        double_precision up_for_renewal
        double_precision upsell
        double_precision upsell_bookings
    }
    business_snapshot_seat_stat {
        text period_key PK
        double_precision churn
        double_precision downsell
        double_precision existing
        double_precision influx
        double_precision influx_movement
        double_precision new_count
        double_precision total
        double_precision upsell
    }
    business_snapshot_saas_stat {
        text period_key PK
        double_precision all_cac_cost_marketing
        double_precision all_cac_cost_sales
        double_precision all_cac_customer_stats_new_all_customers
        double_precision all_cac_ttm_cost_marketing
        double_precision all_cac_ttm_cost_sales
        double_precision all_cac_ttm_customer_stats_new_all_customers
        double_precision all_cac_ttm_value
        double_precision all_cac_value
        double_precision arpa_customer_stats_total
        double_precision arpa_revenue_stats_total
        double_precision arpa_ttm_customer_stats_total
        double_precision arpa_ttm_revenue_stats_total
        double_precision arpa_ttm_value
        double_precision arpa_value
        double_precision burn_multiple_net_new_revenue
        double_precision burn_multiple_ttm_net_new_revenue
        double_precision burn_multiple_ttm_net_profit
        double_precision burn_multiple_ttm_value
        double_precision burn_multiple_value
        double_precision gross_customer_retention_churn_amount
        double_precision gross_customer_retention_churned_customers
        double_precision gross_customer_retention_customers_previous_total
        double_precision gross_customer_retention_downsell_amount
        double_precision gross_customer_retention_downsell_customers
        double_precision gross_customer_retention_existing_amount
        double_precision gross_customer_retention_existing_customers
        double_precision gross_customer_retention_new_amount
        double_precision gross_customer_retention_new_customers
        double_precision gross_customer_retention_ttm_churn_amount
        double_precision gross_customer_retention_ttm_churned_customers
        double_precision gross_customer_retention_ttm_customers_previous_total
        double_precision gross_customer_retention_ttm_downsell_amount
        double_precision gross_customer_retention_ttm_downsell_customers
        double_precision gross_customer_retention_ttm_existing_amount
        double_precision gross_customer_retention_ttm_existing_customers
        double_precision gross_customer_retention_ttm_new_amount
        double_precision gross_customer_retention_ttm_new_customers
        double_precision gross_customer_retention_ttm_upsell_amount
        double_precision gross_customer_retention_ttm_upsell_customers
        double_precision gross_customer_retention_ttm_value
        double_precision gross_customer_retention_upsell_amount
        double_precision gross_customer_retention_upsell_customers
        double_precision gross_customer_retention_value
        double_precision gross_margin_cost_cogs
        double_precision gross_margin_revenue_total_period
        double_precision gross_margin_value
        double_precision gross_revenue_churn_rate_gross_revenue_retention
        double_precision gross_revenue_churn_rate_ttm_gross_revenue_retention
        double_precision gross_revenue_churn_rate_ttm_value
        double_precision gross_revenue_churn_rate_value
        double_precision gross_revenue_retention_revenue_previous_total
        double_precision gross_revenue_retention_revenue_renewed
        double_precision gross_revenue_retention_ttm_revenue_previous_total
        double_precision gross_revenue_retention_ttm_revenue_renewed
        double_precision gross_revenue_retention_ttm_value
        double_precision gross_revenue_retention_value
        double_precision gross_up_for_renewal_retention_amount_renewed_that_was_up_gross
        double_precision gross_up_for_renewal_retention_up_for_renewal
        double_precision gross_up_for_renewal_retention_value
        double_precision ltv_arpa
        double_precision ltv_gross_customer_retention
        double_precision ltv_ttm_arpa_avg
        double_precision ltv_ttm_gross_customer_retention
        double_precision ltv_ttm_value
        double_precision ltv_value
        double_precision ltvcac_ratio_cac
        double_precision ltvcac_ratio_ltv
        double_precision ltvcac_ratio_ttm_cac
        double_precision ltvcac_ratio_ttm_ltv
        double_precision ltvcac_ratio_ttm_value
        double_precision ltvcac_ratio_value
        double_precision ltvgm_laden_arpa
        double_precision ltvgm_laden_gross_customer_retention
        double_precision ltvgm_laden_gross_margin
        double_precision ltvgm_laden_ttm_arpa_avg
        double_precision ltvgm_laden_ttm_gross_customer_retention
        double_precision ltvgm_laden_ttm_gross_margin
        double_precision ltvgm_laden_ttm_value
        double_precision ltvgm_laden_value
        double_precision net_new_revenue_churn_revenue
        double_precision net_new_revenue_downsell_revenue
        double_precision net_new_revenue_new_revenue
        double_precision net_new_revenue_upsell_revenue
        double_precision net_new_revenue_value
        double_precision net_revenue_retention_ending_revenue_from_starting
        double_precision net_revenue_retention_revenue_previous_total
        double_precision net_revenue_retention_ttm_ending_revenue_from_starting
        double_precision net_revenue_retention_ttm_revenue_previous_total
        double_precision net_revenue_retention_ttm_value
        double_precision net_revenue_retention_value
        double_precision net_up_for_renewal_retention_amount_renewed_that_was_up_net
        double_precision net_up_for_renewal_retention_non_renewal_upsell
        double_precision net_up_for_renewal_retention_up_for_renewal
        double_precision net_up_for_renewal_retention_value
        double_precision new_arpa_customer_stats_new
        double_precision new_arpa_revenue_stats_new
        double_precision new_arpa_ttm_customer_stats_new
        double_precision new_arpa_ttm_revenue_stats_new
        double_precision new_arpa_ttm_value
        double_precision new_arpa_value
        double_precision new_revenue_to_costs_ratio_cost_marketing
        double_precision new_revenue_to_costs_ratio_cost_sales
        double_precision new_revenue_to_costs_ratio_new_revenue
        double_precision new_revenue_to_costs_ratio_value
        double_precision payback_period_cost_marketing
        double_precision payback_period_cost_sales
        double_precision payback_period_gross_margin
        double_precision payback_period_revenue_stats_new
        double_precision payback_period_value
        double_precision recurring_arpu_recurring_revenue_total
        double_precision recurring_arpu_total_seats
        double_precision recurring_arpu_value
        double_precision recurring_cac_cost_marketing
        double_precision recurring_cac_cost_sales
        double_precision recurring_cac_customer_stats_new
        double_precision recurring_cac_ttm_cost_marketing
        double_precision recurring_cac_ttm_cost_sales
        double_precision recurring_cac_ttm_customer_stats_new
        double_precision recurring_cac_ttm_value
        double_precision recurring_cac_value
        double_precision rule_of_40_ttm_net_profit
        double_precision rule_of_40_ttm_recurring_period_growth
        double_precision rule_of_40_ttm_total_period_revenue
        double_precision rule_of_40_ttm_value
    }
    business_snapshot_customer_stat {
        text period_key PK
        double_precision all_customers
        double_precision all_recurring_customers
        double_precision churn
        double_precision customers_renewed
        double_precision customers_up_for_renewal
        double_precision customers_with_open_contracts
        double_precision downsell
        double_precision existing
        double_precision influx
        double_precision influx_movement
        double_precision new_all_customers
        double_precision new_count
        double_precision total
        double_precision upsell
    }
    business_snapshot_summary_stat {
        text period_key PK
        double_precision all_arpa_customer_stats_total
        double_precision all_arpa_revenue_stats_total
        double_precision all_arpa_ttm_customer_stats_total
        double_precision all_arpa_ttm_revenue_stats_total
        double_precision all_arpa_ttm_value
        double_precision all_arpa_value
        double_precision all_cac_cost_marketing
        double_precision all_cac_cost_sales
        double_precision all_cac_customer_stats_new_all_customers
        double_precision all_cac_ttm_cost_marketing
        double_precision all_cac_ttm_cost_sales
        double_precision all_cac_ttm_customer_stats_new_all_customers
        double_precision all_cac_ttm_value
        double_precision all_cac_value
        double_precision all_customers
        double_precision amount_renewed_that_was_up_gross
        double_precision amount_renewed_that_was_up_net
        double_precision bookings
        double_precision burn_multiple_net_new_revenue
        double_precision burn_multiple_net_profit
        double_precision burn_multiple_ttm_net_new_revenue
        double_precision burn_multiple_ttm_net_profit
        double_precision burn_multiple_ttm_value
        double_precision burn_multiple_value
        double_precision committed_customer_count
        double_precision committed_recurring
        double_precision customers_renewed
        double_precision customers_up_for_renewal
        double_precision customers_with_open_contracts
        double_precision gross_customer_retention_churn_amount
        double_precision gross_customer_retention_churned_customers
        double_precision gross_customer_retention_customers_previous_total
        double_precision gross_customer_retention_downsell_amount
        double_precision gross_customer_retention_downsell_customers
        double_precision gross_customer_retention_existing_amount
        double_precision gross_customer_retention_existing_customers
        double_precision gross_customer_retention_new_amount
        double_precision gross_customer_retention_new_customers
        double_precision gross_customer_retention_ttm_churn_amount
        double_precision gross_customer_retention_ttm_churned_customers
        double_precision gross_customer_retention_ttm_customers_previous_total
        double_precision gross_customer_retention_ttm_downsell_amount
        double_precision gross_customer_retention_ttm_downsell_customers
        double_precision gross_customer_retention_ttm_existing_amount
        double_precision gross_customer_retention_ttm_existing_customers
        double_precision gross_customer_retention_ttm_new_amount
        double_precision gross_customer_retention_ttm_new_customers
        double_precision gross_customer_retention_ttm_upsell_amount
        double_precision gross_customer_retention_ttm_upsell_customers
        double_precision gross_customer_retention_ttm_value
        double_precision gross_customer_retention_upsell_amount
        double_precision gross_customer_retention_upsell_customers
        double_precision gross_customer_retention_value
        double_precision gross_margin_cost_cogs
        double_precision gross_margin_revenue_total_period
        double_precision gross_margin_value
        double_precision gross_revenue_churn_rate_gross_revenue_retention
        double_precision gross_revenue_churn_rate_ttm_gross_revenue_retention
        double_precision gross_revenue_churn_rate_ttm_value
        double_precision gross_revenue_churn_rate_value
        double_precision gross_revenue_retention_revenue_previous_total
        double_precision gross_revenue_retention_revenue_renewed
        double_precision gross_revenue_retention_ttm_revenue_previous_total
        double_precision gross_revenue_retention_ttm_revenue_renewed
        double_precision gross_revenue_retention_ttm_value
        double_precision gross_revenue_retention_value
        double_precision gross_up_for_renewal_retention_amount_renewed_that_was_up_gross
        double_precision gross_up_for_renewal_retention_up_for_renewal
        double_precision gross_up_for_renewal_retention_value
        double_precision ltv_arpa_avg
        double_precision ltv_gross_customer_retention
        double_precision ltv_ttm_arpa_avg
        double_precision ltv_ttm_gross_customer_retention
        double_precision ltv_ttm_value
        double_precision ltv_value
        double_precision ltvcac_ratio_cac
        double_precision ltvcac_ratio_ltv
        double_precision ltvcac_ratio_ttm_cac
        double_precision ltvcac_ratio_ttm_ltv
        double_precision ltvcac_ratio_ttm_value
        double_precision ltvcac_ratio_value
        double_precision ltvgm_laden_arpa_avg
        double_precision ltvgm_laden_gross_customer_retention
        double_precision ltvgm_laden_gross_margin
        double_precision ltvgm_laden_ttm_arpa_avg
        double_precision ltvgm_laden_ttm_gross_customer_retention
        double_precision ltvgm_laden_ttm_gross_margin
        double_precision ltvgm_laden_ttm_value
        double_precision ltvgm_laden_value
        double_precision magic_number_cost_marketing_last_quarter
        double_precision magic_number_cost_sales_last_quarter
        double_precision magic_number_growth_in_arr
        double_precision magic_number_value
        double_precision metered
        double_precision net_new_revenue_churn_revenue
        double_precision net_new_revenue_downsell_revenue
        double_precision net_new_revenue_new_revenue
        double_precision net_new_revenue_upsell_revenue
        double_precision net_new_revenue_value
        double_precision net_revenue_retention_ending_revenue_from_starting
        double_precision net_revenue_retention_revenue_previous_total
        double_precision net_revenue_retention_ttm_ending_revenue_from_starting
        double_precision net_revenue_retention_ttm_revenue_previous_total
        double_precision net_revenue_retention_ttm_value
        double_precision net_revenue_retention_value
        double_precision net_up_for_renewal_retention_amount_renewed_that_was_up_net
        double_precision net_up_for_renewal_retention_non_renewal_upsell
        double_precision net_up_for_renewal_retention_up_for_renewal
        double_precision net_up_for_renewal_retention_value
        double_precision new_arpa_customer_stats_new
        double_precision new_arpa_revenue_stats_new
        double_precision new_arpa_ttm_customer_stats_new
        double_precision new_arpa_ttm_revenue_stats_new
        double_precision new_arpa_ttm_value
        double_precision new_arpa_value
        double_precision new_bookings
        double_precision new_count
        double_precision new_revenue_to_costs_ratio_cost_marketing
        double_precision new_revenue_to_costs_ratio_cost_sales
        double_precision new_revenue_to_costs_ratio_new_revenue
        double_precision new_revenue_to_costs_ratio_value
        double_precision non_recurring
        double_precision non_renewal_upsell
        double_precision payback_period_cost_marketing
        double_precision payback_period_cost_sales
        double_precision payback_period_gross_margin
        double_precision payback_period_revenue_stats_new
        double_precision payback_period_value
        double_precision percent_recurring
        double_precision reactivated_bookings
        double_precision recurring_arpu_recurring_revenue_total
        double_precision recurring_arpu_total_seats
        double_precision recurring_arpu_value
        double_precision recurring_cac_cost_marketing
        double_precision recurring_cac_cost_sales
        double_precision recurring_cac_customer_stats_new
        double_precision recurring_cac_ttm_cost_marketing
        double_precision recurring_cac_ttm_cost_sales
        double_precision recurring_cac_ttm_customer_stats_new
        double_precision recurring_cac_ttm_value
        double_precision recurring_cac_value
        double_precision recurring_customers
        double_precision recurring_period_growth
        double_precision recurring_revenue_total
        double_precision recurring_revenue_with_rolling_metered
        double_precision renewal_bookings
        double_precision rolling_metered
        double_precision rule_of_40_ttm_net_profit
        double_precision rule_of_40_ttm_recurring_period_growth
        double_precision rule_of_40_ttm_total_period_revenue
        double_precision rule_of_40_ttm_value
        double_precision sales_efficiency_ratio_cost_marketing_this_quarter
        double_precision sales_efficiency_ratio_cost_sales_this_quarter
        double_precision sales_efficiency_ratio_growth_in_arr
        double_precision sales_efficiency_ratio_value
        double_precision total_period_growth
        double_precision total_period_revenue
        double_precision total_seats
        double_precision up_for_renewal
        double_precision upsell_bookings
    }
    waterfall_revenue_stat {
        text period_key PK
        double_precision churn
        double_precision downsell
        double_precision existing
        double_precision influx
        double_precision influx_movement
        double_precision new_count
        double_precision total
        double_precision upsell
    }
    waterfall_customer_stat {
        text period_key PK
        double_precision churn
        double_precision downsell
        double_precision existing
        double_precision influx
        double_precision influx_movement
        double_precision new_count
        double_precision total
        double_precision upsell
    }
    spread {
        text _fivetran_id PK
        text amount
        text created_at
        text customer_external_id
        text customer_id
        text date
        text id
        text seats
        text spread_external_id
        text status
        text transaction_external_id
        text transaction_id
        text type
        text updated_at
    }
