erDiagram
    orders_journey {
        text index PK
        text order_id PK
        text event
        text path
        text product_id
        text time
    }
    orders {
        text order_id PK
        text created_at
        text currency
        text customer_id
        text order_name
        text total_price
    }
    orders_attribution {
        text index PK
        text type PK
        text order_id PK
        text ad_id
        text adset_id
        text campaign_id
        text click_date
        text source
    }
    summary_page_service {
        text index PK
        text summary_page_id PK
        text service
    }
    summary_page {
        text id PK
        text deltas
        text metric_id
        text tip
        text title
        text type
        text values_current
        text values_previous
    }
    summary_page_chart {
        text index PK
        text type PK
        text summary_page_id PK
        text x
        text y
    }
    orders_journey }o--|| orders : "fk"
    orders_attribution }o--|| orders : "fk"
    summary_page_service }o--|| summary_page : "fk"
    summary_page_chart }o--|| summary_page : "fk"
