erDiagram
    referral {
        text id PK
        text affiliate_id FK
        text commission
        text commission_adjustment
        text commission_amount
        text commission_type
        text created_at
        text customer_id
        text order_id
        text order_number
        text quantity
        text refund_id
        text status
        text total_sales
        text tracking_type
    }
    coupon {
        text id PK
        text affiliate_id FK
        text coupon
        text created_timestamp
        text description
    }
    affiliate_custom_field {
        text index PK
        text affiliate_id PK
        text key
        text label
        text value
    }
    affiliate {
        text id PK
        text address
        text affiliate_link
        text city
        text company
        text country
        text created_at_timestamp
        text email
        text email_verified
        text facebook
        text first_name
        text instagram
        text last_name
        text phone
        text program_id
        text program_name
        text state
        text status
        text twitter
        text youtube
        text zip_code
    }
    referral }o--|| affiliate : "fk"
    coupon }o--|| affiliate : "fk"
    affiliate_custom_field }o--|| affiliate : "fk"
