erDiagram
    view {
        text id PK
        text name
    }
    contact {
        text id PK
        text create_date
        text email
        text first_click_campaign
        text first_click_content
        text first_click_date
        text first_click_medium
        text first_click_source
        text first_click_term
        text first_name
        text first_optin_campaign
        text first_optin_content
        text first_optin_date
        text first_optin_medium
        text first_optin_source
        text first_optin_term
        text from_date
        text last_name
        text ltv
        text reoptin_campaign
        text reoptin_content
        text reoptin_date
        text reoptin_medium
        text reoptin_source
        text reoptin_term
        text source_id
        text source_system
        text to_date
        text url_wicked
    }
    order_product {
        text index PK
        text order_id PK
        text id
        text name
        text ppu
        text quantity
    }
    order_payment {
        text index PK
        text order_id PK
        text amount
        text date
        text status
    }
    orders {
        text id PK
        text contact_id FK
        text amount
        text currency
        text date
        text first_click_campaign
        text first_click_content
        text first_click_date
        text first_click_medium
        text first_click_source
        text first_click_term
        text first_optin_campaign
        text first_optin_content
        text first_optin_date
        text first_optin_medium
        text first_optin_source
        text first_optin_term
        text last_click_campaign
        text last_click_content
        text last_click_date
        text last_click_medium
        text last_click_source
        text last_click_term
        text reoptin_campaign
        text reoptin_content
        text reoptin_date
        text reoptin_medium
        text reoptin_source
        text reoptin_term
        text source_id
        text source_system
        text subscription_id
    }
    click {
        text date PK
        text contact_id PK
        text contact_source_id
        text email
        text is_first_click
        text is_first_optin
        text is_last_click
        text is_re_optin
        text source
        text tracking_url
        text utms_campaign
        text utms_content
        text utms_medium
        text utms_source
        text utms_term
        text wicked_id
        text wicked_source
    }
    funnel_vision_grid {
        text _fivetran_id PK
        text view_id FK
        text average_order_value
        text bottom_of_funnel_revenue
        text bottom_of_funnel_sales
        text bottom_of_funnel_wicked_attributed_revenue
        text bottom_of_funnel_wicked_attributed_sales
        text campaign
        text channel
        text clicks
        text content
        text cost_per_lead
        text costs
        text custom_conversions_0
        text custom_conversions_1
        text custom_conversions_2
        text custom_conversions_cost_per_0
        text custom_conversions_cost_per_1
        text custom_conversions_cost_per_2
        text customers
        text dataset
        text date
        text facebook_cost_per_add_to_cart
        text facebook_cost_per_outbound_click
        text facebook_date_created
        text facebook_impressions
        text facebook_meta_add_to_cart
        text facebook_meta_purchase_conversion
        text facebook_meta_purchases
        text facebook_outbound_clicks
        text facebook_status
        text facebook_view_through_conversions
        text facebook_view_through_revenue
        text facebook_website_add_to_cart
        text facebook_website_purchase_conversion
        text facebook_website_purchases
        text grid_first_click_date
        text grid_last_click_date
        text leads
        text medium
        text middle_of_funnel_revenue
        text middle_of_funnel_sales
        text new_average_order_value
        text new_customer_acquisition_cost
        text new_customers
        text new_leads
        text new_revenue
        text new_subscription_revenue
        text new_subscription_sales
        text new_visits
        text re_engaged_leads
        text recurring_subscription_revenue
        text recurring_subscription_sales
        text repeat_average_order_value
        text repeat_customers
        text repeat_revenue
        text source
        text term
        text top_of_funnel_revenue
        text top_of_funnel_sales
        text wicked_attributed_revenue
        text wicked_attributed_sales
    }
    funnel_vision_summary {
        text _fivetran_id PK
        text view_id FK
        text dataset
        text date
        text summary_attribution_coverage_percent
        text summary_clicks
        text summary_cost_per_lead
        text summary_costs
        text summary_customers
        text summary_facebook_meta_purchase_conversion
        text summary_facebook_meta_purchases
        text summary_facebook_view_through_conversions
        text summary_facebook_view_through_revenue
        text summary_first_click_date
        text summary_future_revenue
        text summary_future_sales
        text summary_last_click_date
        text summary_last_click_revenue
        text summary_last_click_sales
        text summary_leads
        text summary_new_customer_acquisition_cost
        text summary_new_customers
        text summary_new_leads
        text summary_new_marketing_efficiency_ratio
        text summary_new_marketing_efficiency_ratio_percent
        text summary_new_sales_count
        text summary_new_sales_revenue
        text summary_new_subscription_revenue
        text summary_new_subscription_sales
        text summary_new_visits
        text summary_non_subscription_revenue
        text summary_non_subscription_sales
        text summary_pre_wicked_revenue
        text summary_pre_wicked_sales
        text summary_re_engaged_leads
        text summary_recurring_subscription_revenue
        text summary_recurring_subscription_sales
        text summary_repeat_customers
        text summary_repeat_sales_count
        text summary_repeat_sales_revenue
        text summary_total_revenue
        text summary_total_sales
        text summary_totals_return_on_ad_spend
        text summary_totals_return_on_investment
        text summary_totals_revenue
        text summary_totals_sales
        text summary_unattributed_leads
        text summary_unattributed_revenue
        text summary_unattributed_sales
        text summary_wicked_attributed_revenue
        text summary_wicked_attributed_sales
    }
    order_product }o--|| orders : "fk"
    order_payment }o--|| orders : "fk"
    orders }o--|| contact : "fk"
    click }o--|| contact : "fk"
    funnel_vision_grid }o--|| view : "fk"
    funnel_vision_summary }o--|| view : "fk"
