erDiagram
    conversion_tracker {
        text id PK
        text account_id PK
        text advanced_matching_enabled
        text all_conversion
        text all_conversion_value
        text app_conversion_app_id
        text app_conversion_platform
        text base_account_id
        text category
        text compare_operator
        text conversion
        text conversion_value
        text conversion_value_via_ad_click
        text conversions_via_ad_click
        text counting_type
        text cross_device_conversion
        text exclude_from_bidding
        text is_previous_conversion
        text measurement_period
        text measurement_period_view
        text most_recent_conversion_date
        text name
        text rule_type
        text snippet_id
        text status
        text type
        text url
        text user_revenue_value
        text view_through_conversion
        jsonb web_conversion
    }
    conversion_group_conversion {
        text index PK
        text account_id PK
        text conversion_group_id PK
        text conversion_tracker_id FK
        text status
        text tag_id
        text tag_name
        text tracker_id
    }
    conversion_group {
        text id PK
        text account_id PK
        text base_account_id
        text name
    }
    ad_group_ad_label {
        text index PK
        text account_id PK
        text ad_group_ad_id PK
        text color
        text description
        text id
        text name
    }
    ad_group_ad {
        text id PK
        text account_id PK
        text ad_group_id FK
        text campaign_id FK
        text ad_type
        text approval_status
        jsonb banner_ad
        text base_account_id
        jsonb carousel_ad
        jsonb carousel_gain_friends_ad
        text created_date
        jsonb custom_parameters
        text disapproval_reason_codes
        text disapproval_reason_description
        text display_url
        text display_url_level
        jsonb dynamic_display_ad
        text final_url
        jsonb impression_beacon_urls
        text is_remove_impression_beacon_url
        text is_remove_smartphone_final_url
        text is_remove_third_party_tracking_script_url
        text is_remove_tracking_url
        text is_remove_viewable_impression_beacon_url
        text main_media_format
        text media_id
        text name
        jsonb responsive_ad
        jsonb responsive_gain_friends_ad
        text smartphone_final_url
        jsonb text_ad
        text third_party_tracking_script_url
        text third_party_tracking_vendor
        text tracking_url
        text updated_date
        text user_status
        jsonb viewable_impression_beacon_urls
    }
    campaign_label {
        text index PK
        text account_id PK
        text campaign_id PK
        text color
        text description
        text id
        text name
    }
    campaign {
        text id PK
        text account_id PK
        text ad_group_id FK
        text conversion_tracker_id FK
        text app_id
        text app_name
        text app_os_type
        text base_account_id
        text bidding_strategy_type
        text budget_amount
        text budget_id
        text budget_name
        text cpc_bidding_scheme
        text cpf_bidding_scheme
        text cpv_bidding_scheme
        text created_date
        jsonb custom_parameters
        text delivery_type
        text end_date
        text end_time
        text enhanced_cpc_enabled
        text feed_id
        text frequency_level
        text frequency_time_unit
        text goal
        text is_remove_tracking_url
        text maximize_conversion_target_roas
        text maximize_conversions_target_cpa
        text maximize_gaining_target_cpf
        text name
        text optimization_score
        text optimizer_training_status
        text serving_status
        text skan_optimaize_ad_delivery_enabled
        text skan_tcpa_target_type
        text start_date
        text start_time
        text tracking_url
        text updated_date
        text user_status
        text v_imps
        text vcpm_bidding_scheme
        text vendor_name
    }
    ad_group_label {
        text index PK
        text account_id PK
        text ad_group_id PK
        text color
        text description
        text id
        text name
    }
    ad_group {
        text id PK
        text account_id PK
        text base_account_id FK
        text campaign_id FK
        text cpc
        text cpf
        text cpv
        text created_date
        jsonb custom_parameters
        jsonb device
        jsonb device_app
        jsonb device_os
        text device_os_version
        text enhanced_cpc_enabled
        text exclude_line_oa_friend_audience_list_id
        text feed_set_id
        text is_remove_cpc
        text is_remove_cpf
        text is_remove_cpv
        text is_remove_target_cpa
        text is_remove_target_cpf
        text is_remove_target_roas
        text is_remove_tracking_url
        text is_remove_vcpm
        text name
        text smart_targeting_enabled
        text target_cpa
        text target_cpf
        text target_roas
        text tracking_url
        text updated_date
        text user_status
        text vcpm
    }
    account {
        text id PK
        text auto_tagging_enabled
        text base_account_id
        text contact_biz_id
        text delivery_status
        text end_date
        text is_mcc_account
        text is_test_account
        text name
        text optimization_score
        text start_date
        text status
        text type
    }
    ad {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text ad_id FK
        text campaign_id FK
        text account_name
        text ad_group_labels
        text ad_group_name
        text ad_group_user_status
        text ad_labels
        text ad_name
        text ad_type
        text ad_user_status
        text age
        text app
        text app_id
        text app_name
        text app_os
        text avg_cpc
        text avg_cpm
        text avg_cpv
        text avg_duration_of_video_viewed
        text avg_position
        text avg_vcpm
        text avg_video_view_rate
        text campaign_buying_type
        text campaign_delivery_type
        text campaign_goals
        text campaign_labels
        text campaign_name
        text campaign_type
        text campaign_user_status
        text city
        text city_id
        text clicks
        text content_keyword
        text content_keyword_id
        text conv_rate
        text conv_rate_all
        text conv_rate_via_click
        text conv_value
        text conv_value_all
        text conv_value_all_per_conv_all
        text conv_value_all_per_cost
        text conv_value_per_conv
        text conv_value_per_cost
        text conv_value_via_click
        text conv_value_via_click_per_conv_via_click
        text conv_value_via_click_per_cost
        text conversions
        text conversions_all
        text conversions_via_click
        text cost
        text cost_per_conv
        text cost_per_conv_all
        text cost_per_conv_via_click
        text cross_device_conv
        text ctr
        text day
        text description_1
        text description_2
        text destination_url_campaign_banner
        text device
        text display_url
        text file_name
        text final_url
        text gender
        text hour_of_day
        text impressions
        text layout
        text lifetime_budget
        text main_media_format
        text measured_impression_rate
        text measured_impressions
        text media_id
        text media_name
        text month
        text os
        text package_name
        text paid_video_view_rate_cpv
        text paid_video_views_cpv
        text pixel_size
        text prefecture_id
        text prefectures
        text responsive_ads_type
        text search_keyword
        text search_keyword_id
        text title
        text tracking_url
        text video_view_through_rate
        text video_views
        text video_views_to_100_percentage
        text video_views_to_10_sec
        text video_views_to_25_percentage
        text video_views_to_3_sec
        text video_views_to_50_percentage
        text video_views_to_75_percentage
        text video_views_to_95_percentage
        text view_through_conversions
        text viewable_clicks
        text viewable_ctr
        text viewable_ctr_per_panel
        text viewable_impression_rate
        text viewable_impressions
        text viewable_impressions_per_panel
        text ward
        text ward_id
        text week
    }
    reach {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text ad_id FK
        text campaign_id FK
        text account_name
        text ad_group_name
        text ad_group_user_status
        text ad_name
        text ad_user_status
        text avg_cpc
        text avg_cpm
        text avg_cpv
        text avg_duration_of_video_viewed
        text avg_frequency
        text avg_vcpm
        text avg_video_view_rate
        text campaign_buying_type
        text campaign_delivery_type
        text campaign_end_date
        text campaign_goals
        text campaign_name
        text campaign_start_date
        text campaign_user_status
        text clicks
        text conv_rate
        text conv_rate_all
        text conv_rate_via_click
        text conv_value_via_view_through
        text conversions
        text conversions_all
        text conversions_via_click
        text cost
        text cost_per_conv
        text cost_per_conv_all
        text cost_per_conv_via_click
        text cross_device_conv
        text ctr
        text day
        text impressions
        text lifetime_budget
        text measured_impression_rate
        text measured_impressions
        text package_name
        text paid_video_view_rate_cpv
        text paid_video_views_cpv
        text reaches
        text video_view_through_rate
        text video_views
        text video_views_to_100_percentage
        text video_views_to_10_sec
        text video_views_to_25_percentage
        text video_views_to_3_sec
        text video_views_to_50_percentage
        text video_views_to_75_percentage
        text video_views_to_95_percentage
        text viewable_clicks
        text viewable_ctr
        text viewable_impression_rate
        text viewable_impressions
    }
    conversion_tracker }o--|| account : "fk"
    conversion_group_conversion }o--|| conversion_group : "fk"
    conversion_group_conversion }o--|| conversion_group : "fk"
    conversion_group_conversion }o--|| conversion_tracker : "fk"
    conversion_group }o--|| account : "fk"
    ad_group_ad_label }o--|| ad_group_ad : "fk"
    ad_group_ad_label }o--|| ad_group_ad : "fk"
    ad_group_ad }o--|| campaign : "fk"
    ad_group_ad }o--|| ad_group : "fk"
    ad_group_ad }o--|| account : "fk"
    campaign_label }o--|| campaign : "fk"
    campaign_label }o--|| campaign : "fk"
    campaign }o--|| conversion_tracker : "fk"
    campaign }o--|| account : "fk"
    campaign }o--|| ad_group : "fk"
    ad_group_label }o--|| ad_group : "fk"
    ad_group_label }o--|| ad_group : "fk"
    ad_group }o--|| campaign : "fk"
    ad_group }o--|| account : "fk"
    ad_group }o--|| account : "fk"
    ad }o--|| campaign : "fk"
    ad }o--|| ad_group_ad : "fk"
    ad }o--|| ad_group : "fk"
    ad }o--|| account : "fk"
    reach }o--|| campaign : "fk"
    reach }o--|| ad_group_ad : "fk"
    reach }o--|| ad_group : "fk"
    reach }o--|| account : "fk"
