erDiagram
    beacon_condition {
        integer index PK
        integer beacon_id PK
        text beacon_updated_at PK
        text key
        text operator
        text value
    }
    beacon_history {
        integer id PK
        text updated_at PK
        integer account_id FK
        integer pixel_id FK
        integer seat_id FK
        text app_id
        text app_locale
        text app_url
        text conversion_category
        double_precision conversion_default_value
        text created_at
        text destination_url
        text destination_url_operator
        text mobile_measurement_partner
        text name
        text rule_type
    }
    campaign_history {
        integer id PK
        timestamp updated_at PK
        integer account_id FK
        text budget_type
        timestamp created_at
        text currency
        text demo_vendor
        text frequency_cap_period_type
        bigint frequency_cap_value
        text goal_type
        bigint goal_value
        text name
        boolean package_enabled
        text status
        text time_zone
    }
    package_schedule {
        integer id PK
        integer package_id PK
        double_precision budget
        double_precision daily_budget
        text daily_budget_type
        timestamp end_date
        bigint imp_budget
        double_precision imp_daily_budget
        text name
        text package_language
        timestamp start_date
    }
    ad_countdown_history {
        integer id PK
        integer ad_id PK
        timestamp ad_updated_at PK
        integer countdown_prefix_id
        timestamp end_date
        text time_zone
    }
    advertiser_contact {
        integer account_id PK
        text address_line_1
        text address_line_2
        text city
        text country
        text email
        text first_name
        text last_name
        text postal_code
        text region
        text telephone
    }
    creative_details_media {
        integer id PK
        integer creative_id PK
        integer bit_rate
        integer frame_rate
        integer height
        text media_mime_type
        text media_url
        integer width
    }
    audience_poi_targeting_rule_chain {
        integer location_id PK
        integer audience_poi_id PK
        boolean is_excluded
    }
    deal_account {
        integer account_id PK
        integer deal_id PK
    }
    audience_poi {
        integer id PK
        integer account_id FK
        integer seat_id FK
        text name
        integer number_of_visits
        text retention_days
        text status
    }
    contextual_category_by_taxonomy_type {
        integer id PK
        text taxonomy_type PK
        integer parent_category_id FK
        text description
        integer level
    }
    audience_ip_address_history {
        text id PK
        integer audience_ip_address_id PK
        timestamp created_date
        double_precision fail_percentage
        text status
        text type
    }
    audience_srt_included_keyword {
        text value PK
        integer audience_srt_id PK
    }
    deal {
        integer id PK
        integer account_group_id FK
        integer exchange_id FK
        boolean account_is_excluded
        text description
        text exchange_deal_id
        text name
        double_precision reserve_price
        text status
    }
    creative_impression_tracking {
        text tracking_event_type PK
        integer creative_id PK
        text imp_tracker_url
    }
    audience_poi_targeting_rule_gid {
        integer gid_id PK
        integer audience_poi_id PK
        boolean is_excluded
    }
    targeting_ab_testing {
        integer id PK
        integer line_id PK
        integer user_group_id FK
        integer lower_bound
        text name
        integer traffic_percent
        integer upper_bound
    }
    creative_details {
        integer creative_id PK
        text call_to_action
        text company_name
        text description
        integer duration
        text title
    }
    line_fee_list {
        integer id PK
        integer line_id PK
        double_precision fee
        text name
        text type_name
    }
    creative_expand_direction {
        text direction PK
        integer creative_id PK
    }
    ad_schedule_history {
        integer id PK
        integer ad_id PK
        timestamp ad_updated_at PK
        timestamp end_date
        timestamp start_date
    }
    audience_mail_event {
        integer id PK
        integer account_id FK
        integer seat_id FK
        text created_at
        text even_type
        integer frequency
        text name
        text status
    }
    audience_mail_event_time_attribute {
        integer index PK
        integer audience_mail_event_id PK
        text from_date
        text key
        text name
        text num_days
        text range_type
        text to_date
    }
    targeting_frequency_capping {
        integer line_id PK
        text cap_period
        text cap_value
        boolean enable_viewability_freq_cap
        boolean serve_unknown_user
    }
    creative_companion_banner {
        integer id PK
        integer creative_id PK
        text mime_type
        text name
    }
    targeting_demographic {
        integer line_id PK
        double_precision threshold
    }
    targeting_segment {
        integer id PK
        integer line_id PK
        text audience_type
        text created_at
        boolean is_excluded
        text name
        bigint reach_count
        integer recency
        text segment_type
    }
    audience_mail_domain {
        integer id PK
        integer account_id FK
        integer seat_id FK
        text created_at
        text name
        integer retention_days
        text status
    }
    audience_email_address {
        integer id PK
        integer account_id FK
        text created_at
        text name
        text status
    }
    targeting_deal {
        text id PK
        integer line_id PK
        text exchange_deal_id FK
        integer exchange_id FK
        boolean account_is_excluded
        text description
        boolean is_excluded
        text name
        double_precision reserve_price
        text status
    }
    beacon_instrumentation_code {
        integer beacon_id PK
        integer pixel_id FK
        text custom_event_script
        text url_secure_multiple
        text url_secure_single
    }
    contextual_history {
        integer id PK
        timestamp updated_at PK
        integer account_id FK
        integer seat_id FK
        text name
        text owner_type
        text taxonomy_type
    }
    audience_email_address_history {
        text id PK
        integer audience_email_address_id PK
        timestamp created_date
        integer duplicated
        text error_message
        double_precision fail_percentage
        text status
        integer total_failed
        integer total_ids
        text type
    }
    targeting_weather_temperature {
        integer line_id PK
        boolean all_temperatures
        boolean is_fahrenheit
        integer max_temp
        integer min_temp
    }
    audience_profile_size {
        integer id PK
        timestamp profile_timestamp PK
        bigint count
    }
    audience_profile_gender {
        integer id PK
        text name PK
        bigint count
        bigint unique_count
    }
    pixel {
        integer id PK
        integer account_id PK
        text name
    }
    targeting_dooh_screen_owner {
        integer id PK
        integer line_id PK
        text name
    }
    audience_mail_domain_excluded_domains {
        text domain PK
        integer audience_mail_domain PK
    }
    audience_srt {
        integer id PK
        integer account_id FK
        integer seat_id FK
        text broad_optimization_type
        text created_at
        text match_type
        text name
        integer retention_days
        text status
    }
    audience_poi_targeting_rule_woeid {
        integer woe_id PK
        integer audience_poi_id PK
        boolean is_excluded
    }
    targeting_weather_humidity {
        integer line_id PK
        boolean all_humidities
        integer max_humidity
        integer min_humidity
    }
    targeting_type {
        text name PK
        integer line_id PK
        integer id
        boolean is_targeted
    }
    ad_history {
        integer id PK
        timestamp updated_at PK
        integer line_id PK
        integer creative_id FK
        text media_type
        text name
        text status
    }
    creative_history {
        integer id PK
        timestamp updated_at PK
        integer account_id FK
        text ad_choice_icon_location
        boolean ad_choices_enabled
        text ad_type
        text creative_language
        text creative_tag_url
        text creative_type
        boolean is_third_party_code_secure
        text landing_page_domain
        text landing_page_url
        text layout
        text mime_type
        text name
        text status
        text third_party_code
    }
    line_conversion_list {
        integer id PK
        integer line_id PK
        boolean accept_view_through
        integer beacon_id
        double_precision beacon_value_pc
        integer click_window
        text click_window_unit_type
        text name
        double_precision view_beacon_value_discount
        integer view_window
        text view_window_unit_type
    }
    creative_adx_categories {
        text category PK
        integer creative_id PK
    }
    audience_mail_event_text_attribute {
        integer index PK
        integer audience_mail_event_id PK
        text group_type
        text key
        text match_type
        text name
        text operator_type
        text value
    }
    targeting_geo {
        text id PK
        integer line_id PK
        text code
        text description
        boolean excluded
        text key
        text level
        text name
        text woeid
    }
    targeting_publisher {
        text id PK
        integer line_id PK
        boolean is_excluded
        text name
    }
    audience_conversion_rule {
        integer id PK
        integer account_id FK
        text name
        integer pixel_rule_id
        text pixel_rule_name
        bigint pixel_rule_size
        text status
    }
    audience_poi_custom_date_range {
        integer index PK
        integer audience_poi_id PK
        text end_date
        text start_date
    }
    audience_composite_exclude_segment {
        integer id PK
        integer composite_audience_id PK
        text name
        bigint reach_count
        text segment_type
        text status
    }
    audience_mail_domain_categories {
        integer audience_mail_domain_id PK
        integer id PK
    }
    audience_lookalike_country {
        text country PK
        integer audience_lookalike_id PK
    }
    audience_composite_include_segment {
        integer id PK
        integer composite_audience_id PK
        text name
        bigint reach_count
        text segment_type
        text status
    }
    line {
        integer id PK
        integer order_id FK
        integer package_id FK
        text app_id
        text app_locale
        text app_marketing_objective
        text app_url
        double_precision bid_price
        text billing_method_type
        double_precision billing_price
        text budget_type
        integer completion_threshold
        double_precision goal_amount
        text goal_mode_type
        text goal_type
        boolean is_native_enabled
        double_precision margin_goal
        text margin_type
        double_precision max_goal
        text media_type
        text name
        integer pacing_acceleration
        text pacing_mode_type
        text status
    }
    order_frequency_cap {
        timestamp campaign_updated_at PK
        integer order_id PK
        text pacing_type
        integer period_multi_hour
        integer value_day
        integer value_hour
        integer value_minute
        integer value_month
        integer value_multi_hour
        integer value_week
    }
    advertiser_history {
        integer id PK
        timestamp updated_at PK
        integer seat_id FK
        text billing_price
        text currency
        integer iab_category_id
        integer iab_secondary_category_id
        boolean is_crossdevice_off
        text landing_page_url
        text name
        text status
        text time_zone
    }
    audience_lookalike {
        integer id PK
        integer account_id FK
        text created_at
        text device_type
        bigint expected_size
        text name
        integer seed_audience_id
        text seed_audience_name
        text seed_audience_type
        text status
    }
    seat {
        integer id PK
        text currency
        text name
        text time_zone
    }
    audience_srt_excluded_keyword {
        text value PK
        integer audience_srt_id PK
    }
    targeting_day_parting {
        text day PK
        integer line_id PK
        text hours
        boolean is_whole_day
    }
    pixel_codes {
        integer index PK
        integer pixel_id PK
        text instrumentation_code
        text protocol
        text type
    }
    deal_account_group {
        integer account_group_id PK
        integer deal_id PK
    }
    audience_device_id_history {
        text id PK
        integer audience_device_id PK
        timestamp created_date
        integer duplicated
        text error_message
        double_precision fail_percentage
        text status
        integer total_failed
        integer total_ids
        text type
    }
    targeting_contextuals_history {
        integer id PK
        timestamp updated_at PK
        integer account_id PK
        integer line_id PK
        boolean is_excluded
        text name
        text taxonomy_type
    }
    audience_profile_location {
        text continent PK
        text country_name PK
        integer id PK
        bigint count
        bigint unique_count
    }
    audience_composite_list {
        integer id PK
        integer account_id FK
        integer seat_id FK
        boolean clear_all_exclude
        text name
        bigint people_count
        text status
        bigint total_count
    }
    audience_ip_address {
        integer id PK
        integer account_id FK
        text created_at
        text name
        integer retention_days
        text status
    }
    audience_device_id {
        integer id PK
        integer account_id FK
        text created_at
        boolean is_device_only
        text name
        text status
    }
    targeting_native_lists {
        integer id PK
        integer line_id PK
        timestamp created_at
        boolean is_excluded
        text name
        timestamp updated_at
    }
    audience_profile_age {
        integer id PK
        text name PK
        bigint count
        bigint unique_count
    }
    bid_multiplier_cap {
        integer id PK
        integer line_id PK
        boolean bm_ad_learn_override
        double_precision multiplier_cap
    }
    line_schedule {
        integer id PK
        integer line_id PK
        double_precision budget
        double_precision daily_budget
        text daily_budget_type
        timestamp end_date_str
        integer imp_budget
        double_precision imp_daily_budget
        text name
        timestamp start_date_str
    }
    audience_poi_location_breadcrumb {
        integer id PK
        integer audience_poi_location_id PK
        text name
    }
    creative_user_interaction {
        text action PK
        integer creative_id PK
    }
    user_group {
        integer id PK
        integer account_id PK
        text name
    }
    audience_poi_location {
        integer id PK
        boolean has_children
        text name
        text type
    }
    account_group {
        integer id PK
        integer seat_id FK
        text code
        text name
    }
    audience_poi_targeting_rule_category {
        integer category_id PK
        integer audience_poi_id PK
        boolean is_excluded
    }
    site_list_item {
        integer id PK
        integer site_list_id PK
        timestamp site_list_updated_at PK
        text item_name
    }
    audience_mail_domain_domains {
        text domain PK
        integer audience_mail_domain_id PK
    }
    targeting_site_list {
        integer id PK
        integer line_id PK
        timestamp created_at
        boolean is_excluded
        text name
        integer total_sites
        text type
        timestamp updated_at
    }
    targeting_dooh_venue_type {
        integer id PK
        integer line_id PK
        text label
    }
    budget_schedule_history {
        integer id PK
        integer campaign_id PK
        timestamp campaign_updated_at PK
        text budget_type
        text daily_budget
        timestamp end_date
        integer imp_budget
        integer imp_daily_budget
        text schedule_budget
        text schedule_name
        timestamp start_date
    }
    exchange {
        integer id PK
        text name
    }
    creative_custom_identifier {
        integer id PK
        integer creative_id PK
        text identifier_value
    }
    package {
        integer id PK
        integer order_id FK
        text billing_method_type
        boolean budget_distributor_enabled
        text budget_type
        text channel_type
        bigint completion_threshold
        boolean flighting_enabled
        text goal_mode_type
        text goal_type
        text margin_type
        text media_type
        text name
        text objective
        text pacing_mode_type
        text package_language
        text status
        text supply_type
    }
    site_list_history {
        integer id PK
        timestamp updated_at PK
        integer account_id FK
        integer seat_id FK
        boolean is_shared
        text name
        text status
        text type
    }
    user_group_entity {
        integer id PK
        integer user_group_id PK
        integer lower_bound
        text name
        integer traffic_percent
        integer upper_bound
    }
    audience_mail_domain_all_categories {
        integer id PK
        text category
    }
    audience_profile_device {
        integer id PK
        text name PK
        bigint count
        bigint unique_count
    }
    contextual_category {
        integer category_id PK
        integer id PK
        integer contextual_id PK
        timestamp contextual_updated_at PK
    }
    audience_composite_fees {
        text currency PK
        text fee_media_type PK
        integer composite_audience_id PK
        double_precision fee
    }
    bid_multiplier {
        integer id PK
        integer line_id PK
        boolean is_app_name
        double_precision multiplier
        text target_domain
        text target_type
        text target_value_city
        text target_value_country
        text target_value_day
        text target_value_dma_code
        integer target_value_hour
        integer target_value_id
        text target_value_locality
        text target_value_major_metro_area
        text target_value_postal_code
        text target_value_postal_code_prefix
        text target_value_region
        text target_value_sub_locality
        text target_value_text
    }
    package_user_frequency_cap {
        integer package_id PK
        bigint period_multi_hour
        bigint value_day
        bigint value_hour
        bigint value_minute
        bigint value_month
        bigint value_multi_hour
        bigint value_week
    }
    advertiser_billing_contact {
        integer account_id PK
        text address_line_1
        text address_line_2
        text address_line_3
        text city
        text country
        text email
        text first_name
        text last_name
        text legal_mandate_confirmation
        text postal_code
        text region
        text telephone
        text vat_number
    }
    package_household_frequency_cap {
        integer package_id PK
        boolean enabled
        bigint period_multi_hour
        bigint value_day
        bigint value_hour
        bigint value_minute
        bigint value_month
        bigint value_multi_hour
        bigint value_week
    }
    beacon_condition }o--|| beacon_history : "fk"
    beacon_condition }o--|| beacon_history : "fk"
    beacon_history }o--|| advertiser_history : "fk"
    beacon_history }o--|| pixel : "fk"
    beacon_history }o--|| seat : "fk"
    campaign_history }o--|| advertiser_history : "fk"
    package_schedule }o--|| package : "fk"
    ad_countdown_history }o--|| ad_history : "fk"
    ad_countdown_history }o--|| ad_history : "fk"
    advertiser_contact }o--|| advertiser_history : "fk"
    creative_details_media }o--|| creative_history : "fk"
    audience_poi_targeting_rule_chain }o--|| audience_poi : "fk"
    deal_account }o--|| deal : "fk"
    deal_account }o--|| advertiser_history : "fk"
    audience_poi }o--|| advertiser_history : "fk"
    audience_poi }o--|| seat : "fk"
    contextual_category_by_taxonomy_type }o--|| contextual_category_by_taxonomy_type : "fk"
    audience_ip_address_history }o--|| audience_ip_address : "fk"
    audience_srt_included_keyword }o--|| audience_srt : "fk"
    deal }o--|| exchange : "fk"
    deal }o--|| account_group : "fk"
    creative_impression_tracking }o--|| creative_history : "fk"
    audience_poi_targeting_rule_gid }o--|| audience_poi : "fk"
    targeting_ab_testing }o--|| line : "fk"
    targeting_ab_testing }o--|| user_group : "fk"
    creative_details }o--|| creative_history : "fk"
    line_fee_list }o--|| line : "fk"
    creative_expand_direction }o--|| creative_history : "fk"
    ad_schedule_history }o--|| ad_history : "fk"
    ad_schedule_history }o--|| ad_history : "fk"
    audience_mail_event }o--|| advertiser_history : "fk"
    audience_mail_event }o--|| seat : "fk"
    audience_mail_event_time_attribute }o--|| audience_mail_event : "fk"
    targeting_frequency_capping }o--|| line : "fk"
    creative_companion_banner }o--|| creative_history : "fk"
    targeting_demographic }o--|| line : "fk"
    targeting_segment }o--|| line : "fk"
    audience_mail_domain }o--|| seat : "fk"
    audience_mail_domain }o--|| advertiser_history : "fk"
    audience_email_address }o--|| advertiser_history : "fk"
    targeting_deal }o--|| line : "fk"
    targeting_deal }o--|| exchange : "fk"
    targeting_deal }o--|| deal : "fk"
    beacon_instrumentation_code }o--|| beacon_history : "fk"
    beacon_instrumentation_code }o--|| pixel : "fk"
    contextual_history }o--|| advertiser_history : "fk"
    contextual_history }o--|| seat : "fk"
    audience_email_address_history }o--|| audience_email_address : "fk"
    targeting_weather_temperature }o--|| line : "fk"
    pixel }o--|| advertiser_history : "fk"
    targeting_dooh_screen_owner }o--|| line : "fk"
    audience_mail_domain_excluded_domains }o--|| audience_mail_domain : "fk"
    audience_srt }o--|| seat : "fk"
    audience_srt }o--|| advertiser_history : "fk"
    audience_poi_targeting_rule_woeid }o--|| audience_poi : "fk"
    targeting_weather_humidity }o--|| line : "fk"
    targeting_type }o--|| line : "fk"
    ad_history }o--|| line : "fk"
    ad_history }o--|| creative_history : "fk"
    creative_history }o--|| advertiser_history : "fk"
    line_conversion_list }o--|| line : "fk"
    creative_adx_categories }o--|| creative_history : "fk"
    audience_mail_event_text_attribute }o--|| audience_mail_event : "fk"
    targeting_geo }o--|| line : "fk"
    targeting_publisher }o--|| line : "fk"
    audience_conversion_rule }o--|| advertiser_history : "fk"
    audience_poi_custom_date_range }o--|| audience_poi : "fk"
    audience_composite_exclude_segment }o--|| audience_composite_list : "fk"
    audience_mail_domain_categories }o--|| audience_mail_domain_all_categories : "fk"
    audience_mail_domain_categories }o--|| audience_mail_domain : "fk"
    audience_lookalike_country }o--|| audience_lookalike : "fk"
    audience_composite_include_segment }o--|| audience_composite_list : "fk"
    line }o--|| campaign_history : "fk"
    line }o--|| package : "fk"
    order_frequency_cap }o--|| campaign_history : "fk"
    order_frequency_cap }o--|| campaign_history : "fk"
    advertiser_history }o--|| seat : "fk"
    audience_lookalike }o--|| advertiser_history : "fk"
    audience_srt_excluded_keyword }o--|| audience_srt : "fk"
    targeting_day_parting }o--|| line : "fk"
    pixel_codes }o--|| pixel : "fk"
    deal_account_group }o--|| deal : "fk"
    deal_account_group }o--|| account_group : "fk"
    audience_device_id_history }o--|| audience_device_id : "fk"
    targeting_contextuals_history }o--|| line : "fk"
    targeting_contextuals_history }o--|| advertiser_history : "fk"
    audience_composite_list }o--|| advertiser_history : "fk"
    audience_composite_list }o--|| seat : "fk"
    audience_ip_address }o--|| advertiser_history : "fk"
    audience_device_id }o--|| advertiser_history : "fk"
    targeting_native_lists }o--|| line : "fk"
    bid_multiplier_cap }o--|| line : "fk"
    line_schedule }o--|| line : "fk"
    audience_poi_location_breadcrumb }o--|| audience_poi_location : "fk"
    creative_user_interaction }o--|| creative_history : "fk"
    user_group }o--|| advertiser_history : "fk"
    account_group }o--|| seat : "fk"
    audience_poi_targeting_rule_category }o--|| audience_poi : "fk"
    site_list_item }o--|| site_list_history : "fk"
    site_list_item }o--|| site_list_history : "fk"
    audience_mail_domain_domains }o--|| audience_mail_domain : "fk"
    targeting_site_list }o--|| line : "fk"
    targeting_dooh_venue_type }o--|| line : "fk"
    budget_schedule_history }o--|| campaign_history : "fk"
    budget_schedule_history }o--|| campaign_history : "fk"
    creative_custom_identifier }o--|| creative_history : "fk"
    package }o--|| campaign_history : "fk"
    site_list_history }o--|| advertiser_history : "fk"
    site_list_history }o--|| seat : "fk"
    user_group_entity }o--|| user_group : "fk"
    contextual_category }o--|| contextual_history : "fk"
    contextual_category }o--|| contextual_history : "fk"
    audience_composite_fees }o--|| audience_composite_list : "fk"
    bid_multiplier }o--|| line : "fk"
    package_user_frequency_cap }o--|| package : "fk"
    advertiser_billing_contact }o--|| advertiser_history : "fk"
    package_household_frequency_cap }o--|| package : "fk"
