erDiagram
    campaign_target_list {
        text _fivetran_id PK
        text account_id FK
        text campaign_id FK
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_adjustment_percentage
        text campaign_tracking_id
        text click_type
        text clicks
        text conv
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text ctr
        text day
        text device
        text id
        text impressions
        text name
        text per
        text reach_status
        text show_ads_on
        text target_list_tracking_id
        text value_per_all_conv
        text value_per_conv
    }
    ad {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text ad_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text campaign_tracking_id
        text click_type
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversion_name
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text custom_parameters
        text day
        text description_1
        text description_1_asset
        text description_2
        text description_2_asset
        text description_3_asset
        text description_4_asset
        text destination_url
        text device
        text directory_1
        text directory_2
        text display_url
        text distribution_settings
        text editorial_status
        text final_url
        text focus_device
        text id
        text impressions
        text label
        text name
        text objective_of_conversion_tracking
        text search_absolute_top_impression_rate
        text search_top_impression_rate
        text show_ads_on
        text smartphone_final_url
        text title_1
        text title_10_asset
        text title_11_asset
        text title_12_asset
        text title_13_asset
        text title_14_asset
        text title_15_asset
        text title_1_asset
        text title_2
        text title_2_asset
        text title_3
        text title_3_asset
        text title_4_asset
        text title_5_asset
        text title_6_asset
        text title_7_asset
        text title_8_asset
        text title_9_asset
        text tracking_url
        text type
        text value_per_all_conv
        text value_per_conv
    }
    search_query {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text keyword_id FK
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text campaign_tracking_id
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text device
        text final_url
        text impressions
        text keyword_negative_keyword
        text keyword_tracking_id
        text search_absolute_top_impression_rate
        text search_query
        text search_query_match_type
        text search_top_impression_rate
        text show_ads_on
        text tracking_url
        text value_per_all_conv
        text value_per_conv
    }
    keyword {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text ad_relevance
        text ad_relevance_hist
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_jpy
        text campaign_tracking_id
        text click_type
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text custom_parameters
        text custom_url
        text day
        text device
        text distribution_settings
        text editorial_status
        text exact_match_impression_share
        text expected_ctr
        text expected_ctr_hist
        text final_url
        text first_page_bid_estimate
        text id
        text impression_share
        text impressions
        text keyword
        text label
        text landing_page_experience
        text landing_page_experience_hist
        text match_type
        text negative_keywords
        text quality_index
        text quality_index_hist
        text quality_lost_impression_share
        text search_absolute_top_impression_rate
        text search_absolute_top_impression_share
        text search_lost_absolute_top_impression_share_budget
        text search_lost_absolute_top_impression_share_rank
        text search_lost_top_impression_share_budget
        text search_lost_top_impression_share_rank
        text search_top_impression_rate
        text search_top_impression_share
        text show_ads_on
        text smartphone_final_url
        text status
        text top_of_page_bid_estimate
        text tracking_id
        text tracking_url
        text value_per_all_conv
        text value_per_conv
    }
    schedule_target {
        text _fivetran_id PK
        text account_id FK
        text campaign_id FK
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_adjustment_percentage
        text campaign_tracking_id
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text impressions
        text query_targeting_status
        text target_schedule
        text target_schedule_id
        text value_per_all_conv
        text value_per_conv
    }
    adgroup_target_list {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_adjustment_percentage
        text campaign_tracking_id
        text click_type
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text device
        text id
        text impressions
        text name
        text reach_status
        text show_ads_on
        text target_list_tracking_id
        text value_per_all_conv
        text value_per_conv
    }
    geo {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text campaign_tracking_id
        text city
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text country_territory
        text ctr
        text day
        text device
        text impressions
        text location
        text location_type
        text metro_area
        text prefecture
        text show_ads_on
        text value_per_all_conv
        text value_per_conv
    }
    campaign_asset {
        text _fivetran_id PK
        text account_id FK
        text campaign_id FK
        text ad_display_option_id
        text ad_display_option_tracking_id
        text ad_display_option_type
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text callout
        text campaign_tracking_id
        text category
        text click_type
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text custom_parameters
        text day
        text device
        text editorial_status
        text end_date
        text final_url
        text impressions
        text phone_number
        text quick_link_description_1
        text quick_link_description_2
        text quick_link_text
        text show_ads_on
        text smartphone_final_url
        text start_date
        text text
        text tracking_url
        text value_per_all_conv
        text value_per_conv
    }
    adgroup {
        text _fivetran_id PK
        text account_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid
        text campaign_tracking_id
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text custom_parameters
        text day
        text device
        text exact_match_impression_share
        text id
        text impression_share
        text impressions
        text label
        text name
        text objective_of_conversion_tracking
        text quality_lost_impression_share
        text search_absolute_top_impression_rate
        text search_absolute_top_impression_share
        text search_lost_absolute_top_impression_share_budget
        text search_lost_absolute_top_impression_share_rank
        text search_lost_top_impression_share_budget
        text search_lost_top_impression_share_rank
        text search_top_impression_rate
        text search_top_impression_share
        text show_ads_on
        text tracking_url
        text value_per_all_conv
        text value_per_conv
    }
    geo_target {
        text _fivetran_id PK
        text account_id FK
        text campaign_id FK
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_adjustment_percentage
        text campaign_tracking_id
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text impressions
        text target_location_id
        text target_location_name
        text value_per_all_conv
        text value_per_conv
    }
    webpage_criterion {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_adjustment_percentage
        text campaign_tracking_id
        text click_type
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text device
        text impressions
        text search_absolute_top_impression_rate
        text search_top_impression_rate
        text show_ads_on
        text target_page_id
        text target_page_tracking_id
        text value_per_all_conv
        text value_per_conv
    }
    account {
        text _fivetran_id PK
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text budget_lost_impression_share
        text click_type
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text device
        text exact_match_impression_share
        text id
        text impression_share
        text impressions
        text invalid_click_rate
        text invalid_clicks
        text name
        text objective_of_conversion_tracking
        text quality_lost_impression_share
        text show_ads_on
        text tracking_url
        text value_per_all_conv
        text value_per_conv
    }
    responsive_ads_search_asset {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text ad_id FK
        text campaign_id FK
        text asset
        text asset_type
        text day
        text impressions
        text performance_rating
        text position_pinning
        text show_ads_on
    }
    landing_page_url {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text campaign_tracking_id
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversion_name
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text device
        text expanded_landing_page_url
        text impressions
        text landing_page_url
        text objective_of_conversion_tracking
        text show_ads_on
        text value_per_all_conv
        text value_per_conv
    }
    bid_strategy {
        text _fivetran_id PK
        text account_id FK
        text campaign_id FK
        text ad_position
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_adjustment_percentage
        text bid_limit
        text bid_limit_cpa
        text bid_limit_maximize_clicks
        text bid_limit_roas
        text bid_strategy
        text bidding_adjustment
        text bidding_adjustment_method
        text campaign
        text campaign_tracking_id
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text impressions
        text limit_by_campaign_budget
        text low_quality_keyword
        text lower_bid_limit_cpa
        text lower_bid_limit_roas
        text portfolio_bidding_id
        text portfolio_bidding_name
        text target_cpa
        text target_roas
        text target_schedule_id
        text value_per_all_conv
        text value_per_conv
    }
    bid_modifier {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text bid_adjustment_percentage
        text device
        text level
    }
    adgroup_asset {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_display_option_id
        text ad_display_option_tracking_id
        text ad_display_option_type
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text callout
        text campaign_tracking_id
        text category
        text click_type
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversion_name
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text custom_parameters
        text day
        text device
        text editorial_status
        text end_date
        text final_url
        text impressions
        text objective_of_conversion_tracking
        text phone_number
        text quick_link_description_1
        text quick_link_description_2
        text quick_link_text
        text show_ads_on
        text smartphone_final_url
        text start_date
        text text
        text tracking_url
        text value_per_all_conv
        text value_per_conv
    }
    keywordless_query {
        text _fivetran_id PK
        text account_id FK
        text ad_group_id FK
        text campaign_id FK
        text ad_group_tracking_id
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text campaign_tracking_id
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text conversions_across_devices
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text ctr
        text day
        text impressions
        text search_query
        text title_auto_created
        text url
        text value_per_all_conv
        text value_per_conv
    }
    campaign {
        text _fivetran_id PK
        text account_id FK
        text absolute_top_impression_percentage
        text all_conv
        text all_conv_rate
        text all_conv_value
        text all_conv_value_per_cost
        text avg_cpc
        text bid_strategy_id
        text budget_lost_impression_share
        text campaign_end_date
        text campaign_start_date
        text campaign_tracking_id
        text campaign_type
        text click_rate
        text clicks
        text conv_rate
        text conv_value
        text conv_value_per_cost
        text conversions
        text cost
        text cost_per_all_conv
        text cost_per_conv
        text cross_device_conversions
        text custom_parameters
        text daily_spending_limit
        text day
        text device
        text distribution_settings
        text distribution_status
        text enhanced_cpc_enabled
        text exact_match_impression_share
        text id
        text impression_share
        text imps
        text label
        text name
        text network
        text quality_lost_impression_share
        text search_absolute_top_impression_share
        text search_budget_lost_absolute_top_impression_share
        text search_budget_lost_top_impression_share
        text search_rank_lost_absolute_top_impression_share
        text search_rank_lost_top_impression_share
        text search_top_impression_share
        text top_impression_percentage
        text tracking_url
        text value_per_all_conv
        text value_per_conv
    }
    campaign_target_list }o--|| campaign : "fk"
    campaign_target_list }o--|| account : "fk"
    ad }o--|| campaign : "fk"
    ad }o--|| adgroup : "fk"
    ad }o--|| account : "fk"
    search_query }o--|| campaign : "fk"
    search_query }o--|| adgroup : "fk"
    search_query }o--|| keyword : "fk"
    search_query }o--|| account : "fk"
    keyword }o--|| campaign : "fk"
    keyword }o--|| adgroup : "fk"
    keyword }o--|| account : "fk"
    schedule_target }o--|| campaign : "fk"
    schedule_target }o--|| account : "fk"
    adgroup_target_list }o--|| campaign : "fk"
    adgroup_target_list }o--|| adgroup : "fk"
    adgroup_target_list }o--|| account : "fk"
    geo }o--|| campaign : "fk"
    geo }o--|| adgroup : "fk"
    geo }o--|| account : "fk"
    campaign_asset }o--|| campaign : "fk"
    campaign_asset }o--|| account : "fk"
    adgroup }o--|| campaign : "fk"
    adgroup }o--|| account : "fk"
    geo_target }o--|| campaign : "fk"
    geo_target }o--|| account : "fk"
    webpage_criterion }o--|| campaign : "fk"
    webpage_criterion }o--|| adgroup : "fk"
    webpage_criterion }o--|| account : "fk"
    responsive_ads_search_asset }o--|| campaign : "fk"
    responsive_ads_search_asset }o--|| ad : "fk"
    responsive_ads_search_asset }o--|| adgroup : "fk"
    responsive_ads_search_asset }o--|| account : "fk"
    landing_page_url }o--|| campaign : "fk"
    landing_page_url }o--|| adgroup : "fk"
    landing_page_url }o--|| account : "fk"
    bid_strategy }o--|| campaign : "fk"
    bid_strategy }o--|| account : "fk"
    bid_modifier }o--|| account : "fk"
    bid_modifier }o--|| adgroup : "fk"
    bid_modifier }o--|| campaign : "fk"
    adgroup_asset }o--|| campaign : "fk"
    adgroup_asset }o--|| adgroup : "fk"
    adgroup_asset }o--|| account : "fk"
    keywordless_query }o--|| campaign : "fk"
    keywordless_query }o--|| adgroup : "fk"
    keywordless_query }o--|| account : "fk"
    campaign }o--|| account : "fk"
