erDiagram
    product {
        text product_id PK
        text product_name
    }
    workflow {
        text _fivetran_id PK
        text created_time
        text trigger_key
        text workflow_key
        text workflow_name
    }
    recent_campaign {
        text campaign_key PK
        text campaign_name
        text campaign_preview
        text campaign_status
        text campaign_type
        text created_date_string
        text created_time
        text created_time_gmt
        text folder_id
        text from_email
        text is_hybrid
        text reply_to
        text sent_date_string
        text sent_time
        text sent_time_gmt
        text sent_time_zone
        text subject
        text updated_date_string
        text updated_time
        text updated_time_gmt
        text zu_id
    }
    contact_field {
        text field_id PK
        text block_label
        text block_sequence
        text display_name
        text field_display_name
        text field_name
        text is_mandatory
        text is_otheruser_field
        text max_length
        text sequence
        text type
        text ui_type
        text values
    }
    contact_count {
        text _fivetran_id PK
        text mailing_list_list_key FK
        text no_of_contacts
    }
    advanced_campaign_detail {
        text campaign_key PK
        text campaignid
        text cmp_status
        text date
        text is_deleted
        text schedule_date
        text scheduled_time
        text service_type
    }
    list_advanced_detail {
        text _fivetran_id PK
        text listkey FK
        text brower_type_chrome
        text brower_type_firefox
        text brower_type_internet_explorer
        text brower_type_opera
        text brower_type_others
        text brower_type_safari
        text contact_details_created_time_gmt
        text contact_details_date
        text contact_details_is_public
        text contact_details_list_name
        text contact_details_no_of_contacts
        text contact_details_owner_email
        text contact_details_owner_name
        jsonb contact_details_segments
        text contact_details_zu_id
        text contact_stats_no_of_active
        text contact_stats_no_of_bounce
        text contact_stats_no_of_unsub
        text contact_stats_schedule_count
        text contact_stats_sent_count
        text device_type_computer
        text device_type_mobile
        text device_type_others
        text device_type_tablet
        text email_client_apple_mail
        text email_client_lotus_notes
        text email_client_others
        text email_client_outlook
        text email_client_thunderbird
        text localsubscribers_city_count
        text localsubscribers_country_count
        text localsubscribers_region_count
        text mobile_devices_android
        text mobile_devices_blackberry
        text mobile_devices_ios
        text mobile_devices_others
        jsonb open_subscribers_location
        text operating_system_linux
        text operating_system_ma_os_x
        text operating_system_others
        text operating_system_windows
        text status
        text tablet_devices_android
        text tablet_devices_blackberry
        text tablet_devices_ios
        text tablet_devices_others
        text web_client_aol_webmail
        text web_client_gmail
        text web_client_hotmail
        text web_client_others
        text web_client_yahoo_mail
        text web_client_zoho_mail
    }
    mailing_list {
        text list_key PK
        text created_time
        text created_time_gmt
        text date
        text deletable
        text editable
        text is_public
        text is_smart
        text list_campaigns_count
        text list_created_date
        text list_created_time
        text list_desc
        text list_dgs
        text list_name
        text list_notifications
        text list_type
        text list_uni_no
        text lock_status
        text no_of_bounce_count
        text no_of_contacts
        text no_of_unsubcnt
        text others_list
        text owner
        text s_no
        jsonb segments
        text sent_count
        text service_type
        text updated_time_gmt
        text zu_id
        text zx
    }
    contact {
        text _fivetran_id PK
        text mailing_list_list_key FK
        text added_time
        text company_name
        text contact_email
        text first_name
        text last_name
        text phone
        text zu_id
    }
    campaign_recipient_data {
        text contact_id PK
        text campaign_key FK
        text address
        text beta_keys
        text city
        text company_name
        text contact_email_address
        text contact_first_name
        text contact_last_name
        text contact_status
        text country
        text facebook_handle
        text import_file_name
        text job_title
        text linkedin_handle
        text mobile
        text note
        text opted_in_at
        text phone
        text secondary_email
        text sent_date
        text sent_time
        text state
        text tags
        text time_zone
        text title
        text twitter_handle
        text website
        text zip_code
    }
    campaign_detail {
        text index PK
        text campaign_key PK
        text advance_type_string
        text campaign_name
        text campaign_preview
        text campaign_type
        text created_date_string
        text created_time
        text created_time_gmt
        text email_options
        text email_subject
        text email_type
        text encode_name
        text folder_id
        text is_advance
        text is_g_a_config
        text is_hybrid
        text is_reply_tracking_enabled
        text is_to_name_config
        text is_wistia
        text modified_date
        text modified_time
        text modified_time_gmt
        text preheader
        text reply_to
        text schedule_type
        text sender_name
        text sent_date_string
        text sent_time
        text sent_time_gmt
        text sent_time_zone
        text sent_time_zone_short
        text topic_id
        text topic_name
        text updated_date_string
        text updated_time
        text updated_time_gmt
        text web_auto_status
        text zu_id
    }
    associated_mailing_list {
        text campaign_key PK
        text list_key PK
        text contacts_count
        text list_name
        text list_status
        text no_of_bounce
        text no_of_unsubcontacts
    }
    campaign_report {
        text _fivetran_id PK
        text campaign_key FK
        text autoreply_count
        text bounce_percent
        text bounces_count
        text clicks_per_openrate
        text complaints_count
        text complaints_percent
        text delivered_count
        text delivered_percent
        text emails_sent_count
        text forward_percent
        text forwards_count
        text hardbounce_count
        text open_percent
        text opens_count
        text softbounce_count
        text spam_percent
        text spams_count
        text unique_clicked_percent
        text unique_clicks_count
        text unopened
        text unopened_percent
        text unsent_count
        text unsent_percent
        text unsub_count
        text unsubscribe_percent
    }
    campaign_reach {
        text _fivetran_id PK
        text campaign_key FK
        text emails
        text facebook
        text gplus
        text linkedin
        text other
        text pinterest
        text total
        text tumblr
        text twitter
    }
    segment {
        text cvid PK
        text segment_zuid FK
        text category
        text created_date
        text created_zuid
        jsonb seg_criteira
        text segment_id
        text segment_name
        text segment_owner
        text segment_status
    }
    segment_info {
        text list_zuid PK
        text campaign_key PK
        text current_zuid
        text list_name
    }
    campaign_location {
        text name PK
        text campaign_campaign_key PK
        text value
    }
    campaign {
        text campaign_key PK
        text campaign_status
        text status
        text total_subscribers_count
        text useragentstats_browsers_percent_chrome
        text useragentstats_browsers_percent_firefox
        text useragentstats_browsers_percent_internet_explorer
        text useragentstats_browsers_percent_opera
        text useragentstats_browsers_percent_others
        text useragentstats_browsers_percent_safari
        text useragentstats_computer_percent_apple
        text useragentstats_computer_percent_linux
        text useragentstats_computer_percent_others
        text useragentstats_computer_percent_windows
        text useragentstats_emailclients_percent_apple_mail
        text useragentstats_emailclients_percent_lotus_notes
        text useragentstats_emailclients_percent_others
        text useragentstats_emailclients_percent_outlook
        text useragentstats_emailclients_percent_thunderbird
        text useragentstats_mobile_percent_android
        text useragentstats_mobile_percent_blackberry
        text useragentstats_mobile_percent_i_o_s
        text useragentstats_mobile_percent_others
        text useragentstats_tablets_percent_android
        text useragentstats_tablets_percent_blackberry
        text useragentstats_tablets_percent_i_o_s
        text useragentstats_tablets_percent_others
    }
    topic {
        text id PK
        text primary_list
        text topic_desc
        text topic_name
    }
    contact_count }o--|| mailing_list : "fk"
    advanced_campaign_detail }o--|| campaign_detail : "fk"
    list_advanced_detail }o--|| mailing_list : "fk"
    contact }o--|| mailing_list : "fk"
    campaign_recipient_data }o--|| recent_campaign : "fk"
    campaign_detail }o--|| campaign : "fk"
    associated_mailing_list }o--|| mailing_list : "fk"
    associated_mailing_list }o--|| campaign : "fk"
    campaign_report }o--|| campaign : "fk"
    campaign_reach }o--|| campaign : "fk"
    segment }o--|| segment_info : "fk"
    segment_info }o--|| campaign : "fk"
    campaign_location }o--|| campaign : "fk"
    campaign }o--|| recent_campaign : "fk"
