CREATE TABLE branding (
    id text,
    group_id text,
    admin_template_css text,
    admin_template_css_backup text,
    admin_template_htm text,
    admin_template_htm_backup text,
    copyright text,
    favicon text,
    footer_html_value text,
    footer_text_value text,
    header_html_value text,
    header_text_value text,
    help text,
    license text,
    links text,
    public_template_css text,
    public_template_htm text,
    site_logo text,
    site_logo_small text,
    site_name text,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE account_contact (
    account_contact text,
    contact_id text,
    PRIMARY KEY (account_contact, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id)
);

CREATE TABLE contact (
    id text,
    a_date text,
    anonymized text,
    bounced_date text,
    bounced_hard text,
    bounced_soft text,
    c_date text,
    created_by text,
    created_timestamp text,
    created_utc_timestamp text,
    deleted text,
    deleted_at text,
    e_date text,
    email text,
    email_domain text,
    email_local text,
    first_name text,
    gravatar text,
    hash text,
    ip text,
    last_name text,
    mpp_tracking text,
    org_name text,
    organization text,
    phone text,
    rating_tstamp text,
    score_value jsonb,
    segmentio_id text,
    sentcnt text,
    socialdata_lastcheck text,
    u_date text,
    ua text,
    updated_by text,
    updated_timestamp text,
    updated_utc_timestamp text,
    PRIMARY KEY (id)
);

CREATE TABLE contact_tag (
    id text,
    contact text,
    c_date text,
    created_by text,
    created_timestamp text,
    tags text,
    updated_by text,
    updated_timestamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact) REFERENCES contact(id)
);

CREATE TABLE contact_list (
    id text,
    contact_id text,
    list text,
    automation text,
    autosync_log text,
    campaign text,
    created_by text,
    created_timestamp text,
    first_name text,
    form text,
    ip_4_last text,
    ip_4_sub text,
    ip_4_unsub text,
    last_name text,
    links_automation text,
    links_autosync_log text,
    links_campaign text,
    links_contact text,
    links_form text,
    links_list text,
    links_message text,
    links_unsubscribe_automation text,
    message text,
    responder text,
    s_date text,
    series_id text,
    source_id text,
    "status" text,
    sync text,
    u_date text,
    unsubreason text,
    unsubscribe_automation text,
    updated_by text,
    updated_timestamp text,
    PRIMARY KEY (id, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (list) REFERENCES list(id)
);

CREATE TABLE contact_custom_field_value (
    id text,
    contact text,
    custom_field_id text,
    c_date text,
    u_date text,
    "value" text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact) REFERENCES contact(id),
    FOREIGN KEY (custom_field_id) REFERENCES contact_custom_field(id)
);

CREATE TABLE score (
    id text,
    c_date text,
    descript text,
    links jsonb,
    m_date text,
    "name" text,
    rel_type text,
    "status" text,
    PRIMARY KEY (id)
);

CREATE TABLE automation (
    id text,
    user_id text,
    c_date text,
    default_screenshot text,
    entered text,
    entitlements_violation text,
    exited text,
    hidden text,
    m_date text,
    "name" text,
    screenshot text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE segment (
    id text,
    created_by text,
    created_timestamp text,
    hidden text,
    logic text,
    "name" text,
    segment_id_v_2 text,
    series_id text,
    updated_by text,
    updated_timestamp text,
    PRIMARY KEY (id)
);

CREATE TABLE deal_custom_field_option (
    field_option text,
    deal_custom_field_id text,
    PRIMARY KEY (field_option, deal_custom_field_id),
    FOREIGN KEY (deal_custom_field_id) REFERENCES deal_custom_field(id)
);

CREATE TABLE deal_custom_field (
    id text,
    created_timestamp text,
    display_order text,
    field_default text,
    field_default_currency text,
    field_label text,
    field_type text,
    hide_field_flag text,
    is_form_visible text,
    is_required text,
    known_field_id text,
    personalization text,
    updated_timestamp text,
    PRIMARY KEY (id)
);

CREATE TABLE connection (
    id text,
    c_date text,
    external_id text,
    is_internal text,
    last_sync text,
    link_url text,
    logo_url text,
    "name" text,
    service text,
    "status" text,
    sync_status text,
    u_date text,
    PRIMARY KEY (id)
);

CREATE TABLE deal_activity (
    id text,
    deal_id text,
    deal_stage_id text,
    user_id text,
    automation text,
    c_date text,
    data_action text,
    data_id text,
    data_oldval text,
    data_type text,
    deleted text,
    is_add_task text,
    series_id text,
    sort_date text,
    stage text,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (deal_stage_id) REFERENCES stage(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_group (
    id text,
    group_id text,
    user_id text,
    c_date text,
    u_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE list (
    id text,
    user_id text,
    analytics_domains text,
    analytics_source text,
    analytics_ua text,
    c_date text,
    carbon_copy text,
    created_by text,
    created_timestamp text,
    delete_stamp text,
    facebook_session text,
    full_address text,
    get_unsubscribe_reason text,
    "name" text,
    optin_message_id text,
    optin_optout text,
    optout_conf text,
    p_embed_image text,
    p_use_analytics_link text,
    p_use_analytics_read text,
    p_use_captcha text,
    p_use_facebook text,
    p_use_tracking text,
    p_use_twitter text,
    private text,
    require_name text,
    send_last_broadcast text,
    sender_addr_1 text,
    sender_addr_2 text,
    sender_city text,
    sender_country text,
    sender_name text,
    sender_phone text,
    sender_reminder text,
    sender_state text,
    sender_url text,
    sender_zip text,
    stringid text,
    subscription_notify text,
    to_name text,
    twitter_token text,
    twitter_token_secret text,
    u_date text,
    unsubscription_notify text,
    updated_by text,
    updated_timestamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    c_date text,
    email text,
    first_name text,
    lang text,
    last_name text,
    local_zone_id text,
    mfa_enabled text,
    phone text,
    signature text,
    u_date text,
    username text,
    PRIMARY KEY (id)
);

CREATE TABLE tags (
    id text,
    c_date text,
    created_by text,
    created_timestamp text,
    description text,
    subscriber_count text,
    tag_type text,
    tags text,
    updated_by text,
    updated_timestamp text,
    PRIMARY KEY (id)
);

CREATE TABLE order_product (
    id text,
    connection_id text,
    e_com_order text,
    category text,
    created_date text,
    description text,
    external_id text,
    image_url text,
    "name" text,
    order_id text,
    price text,
    product_url text,
    quantity text,
    sku text,
    tstamp text,
    updated_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (connection_id) REFERENCES connection(id),
    FOREIGN KEY (e_com_order) REFERENCES e_com_order(id)
);

CREATE TABLE task (
    id text,
    owner_id text,
    user_id text,
    assigned_date text,
    assignee text,
    automation text,
    c_date text,
    created_utc_timestamp text,
    deal_task_type text,
    done_automation text,
    done_by text,
    done_date text,
    done_utc_timestamp text,
    due_date text,
    duration text,
    e_date text,
    note text,
    outcome_id text,
    outcome_info text,
    owner_type text,
    rel_id text,
    rel_title text,
    rel_type text,
    "status" text,
    title text,
    trigger_automation_on_create text,
    u_date text,
    updated_by text,
    updated_utc_timestamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES contact(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE custom_account_field_value (
    id text,
    account_id text,
    custom_field_id text,
    account_custom_field_metum_id text,
    created_timestamp text,
    field_value text,
    updated_timestamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (custom_field_id) REFERENCES custom_account_field(id)
);

CREATE TABLE campaign (
    id text,
    address_id text,
    user_id text,
    activerss_interval text,
    activerss_items text,
    activerss_url text,
    analytics_campaign_name text,
    automation text,
    base_message_id text,
    base_template_id text,
    bounce_id text,
    c_date text,
    campaign_message_id text,
    can_skip_approval text,
    created_by text,
    created_timestamp text,
    delete_stamp text,
    ed_version text,
    embed_images text,
    facebook text,
    form_id text,
    forwards text,
    hard_bounces text,
    has_predictive_content text,
    html_un_sub text,
    html_un_sub_data text,
    ip text,
    ip_4 text,
    l_date text,
    last_step text,
    link_clicks text,
    m_date text,
    mail_cleanup text,
    mail_send text,
    mail_transfer text,
    mailer_log_file text,
    manage_text text,
    message_id text,
    "name" text,
    opens text,
    public text,
    realc_id text,
    recurring text,
    reminder_field text,
    reminder_format text,
    reminder_last_cron_run text,
    reminder_offset text,
    reminder_offset_sign text,
    reminder_offset_type text,
    reminder_type text,
    replies text,
    replysys text,
    responder_existing text,
    responder_offset text,
    responder_type text,
    s_date text,
    schedule text,
    scheduled_date text,
    screenshot text,
    segment_id text,
    segment_name text,
    send_amt text,
    send_id text,
    series_id text,
    series_send_lock_time text,
    social_shares text,
    soft_bounces text,
    "source" text,
    split_content text,
    split_offset text,
    split_offset_type text,
    split_type text,
    split_winner_awaiting text,
    split_winner_messageid text,
    "status" text,
    subscriber_clicks text,
    survey text,
    text_unsub text,
    text_unsub_data text,
    thread_id text,
    total_amt text,
    track_links text,
    track_links_analytics text,
    track_reads text,
    track_reads_analytics text,
    tweet text,
    "type" text,
    unique_forwards text,
    unique_link_clicks text,
    unique_opens text,
    unique_replies text,
    unsub_reasons text,
    unsubscribes text,
    updated_by text,
    updated_timestamp text,
    updates text,
    use_quartz_scheduler text,
    wait_preview text,
    will_recur text,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE e_com_order_product (
    _fivetran_id text,
    e_com_order_id text,
    product_id text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (e_com_order_id) REFERENCES e_com_order(id)
);

CREATE TABLE e_com_order (
    id text,
    connection text,
    customer_id text,
    created_date text,
    currency text,
    discount_amount text,
    email text,
    external_created_date text,
    external_id text,
    order_date text,
    order_url text,
    shipping_amount text,
    shipping_method text,
    "source" text,
    "state" text,
    tax_amount text,
    total_price text,
    total_products text,
    tstamp text,
    updated_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (connection) REFERENCES connection(id),
    FOREIGN KEY (customer_id) REFERENCES e_com_customer(id)
);

CREATE TABLE deal_custom_field_value (
    id text,
    custom_field_id text,
    deal_id text,
    created_timestamp text,
    deal_custom_field_metum_id text,
    field_value text,
    updated_timestamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (custom_field_id) REFERENCES deal_custom_field(id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE group_limit (
    id text,
    group_id text,
    abuse_ratio text,
    force_sender_info text,
    limit_attachment text,
    limit_campaign text,
    limit_campaign_type text,
    limit_contact text,
    limit_list text,
    limit_mail text,
    limit_mail_type text,
    limit_user text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE e_com_customer (
    id text,
    connection_id text,
    avg_product_category text,
    avg_revenue_perorder text,
    email text,
    external_id text,
    time_stamp text,
    total_orders text,
    total_products text,
    total_revenue text,
    PRIMARY KEY (id),
    FOREIGN KEY (connection_id) REFERENCES connection(id)
);

CREATE TABLE schema_field (
    id text,
    schema_id text,
    labels_plural text,
    labels_singular text,
    required boolean,
    scale text,
    "type" text,
    PRIMARY KEY (id, schema_id),
    FOREIGN KEY (schema_id) REFERENCES "schema"(id)
);

CREATE TABLE schema_relationship (
    id text,
    schema_id text,
    description text,
    has_many text,
    labels_plural text,
    labels_singular text,
    namespace text,
    PRIMARY KEY (id, schema_id),
    FOREIGN KEY (schema_id) REFERENCES "schema"(id)
);

CREATE TABLE "schema" (
    id text,
    created_timestamp text,
    description text,
    icons_default text,
    labels_plural text,
    labels_singular text,
    slug text,
    updated_timestamp text,
    visibility text,
    PRIMARY KEY (id)
);

CREATE TABLE note (
    id text,
    owner_id text,
    user_id text,
    c_date text,
    is_draft text,
    m_date text,
    note text,
    owner_type text,
    rel_id text,
    rel_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES contact(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE deal (
    id text,
    account text,
    contact text,
    next_deal_id text,
    next_task_id text,
    owner text,
    activity_count text,
    c_date text,
    currency text,
    customer_account text,
    description text,
    e_date text,
    groups text,
    hash text,
    is_disabled boolean,
    m_date text,
    next_date text,
    organization text,
    percentage text,
    stage text,
    "status" text,
    title text,
    "value" text,
    win_probability text,
    win_probability_mdate text,
    PRIMARY KEY (id),
    FOREIGN KEY (account) REFERENCES account(id),
    FOREIGN KEY (contact) REFERENCES contact(id),
    FOREIGN KEY (next_deal_id) REFERENCES deal(id),
    FOREIGN KEY (next_task_id) REFERENCES task(id),
    FOREIGN KEY (owner) REFERENCES users(id)
);

CREATE TABLE contact_custom_field (
    id text,
    c_date text,
    cols text,
    defval text,
    descript text,
    is_required text,
    options jsonb,
    order_num text,
    perstag text,
    relations jsonb,
    "rows" text,
    service text,
    show_in_list text,
    title text,
    "type" text,
    u_date text,
    visible text,
    PRIMARY KEY (id)
);

CREATE TABLE task_outcome (
    id text,
    created_by text,
    created_utc_timestamp text,
    deal_tasktype_ids jsonb,
    disabled text,
    sentiment text,
    title text,
    updated_by text,
    updated_utc_timestamp text,
    PRIMARY KEY (id)
);

CREATE TABLE "role" (
    id text,
    created_timestamp text,
    title text,
    updated_timestamp text,
    PRIMARY KEY (id)
);

CREATE TABLE email_activity (
    id text,
    connection_id text,
    contact_id text,
    deal_id text,
    message_id text,
    rel_id text,
    user_id text,
    account text,
    automation_name text,
    cc_address text,
    file text,
    from_address text,
    from_name text,
    message text,
    series_id text,
    service_provider text,
    subject text,
    subscriber_series_id text,
    to_address text,
    tstamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (connection_id) REFERENCES connection(id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (message_id) REFERENCES message(id),
    FOREIGN KEY (rel_id) REFERENCES contact_tracking_log(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE saved_response (
    id text,
    last_sent_user_id text,
    body text,
    c_date text,
    l_date text,
    m_date text,
    subject text,
    title text,
    PRIMARY KEY (id),
    FOREIGN KEY (last_sent_user_id) REFERENCES users(id)
);

CREATE TABLE custom_field_option (
    field_option text,
    custom_account_field_id text,
    PRIMARY KEY (field_option, custom_account_field_id),
    FOREIGN KEY (custom_account_field_id) REFERENCES custom_account_field(id)
);

CREATE TABLE custom_account_field (
    id text,
    created_by text,
    created_timestamp text,
    display_order text,
    field_default text,
    field_default_currency text,
    field_label text,
    field_type text,
    hide_field_flag text,
    is_form_visible text,
    is_required text,
    known_field_id text,
    personalization text,
    updated_by text,
    updated_timestamp text,
    PRIMARY KEY (id)
);

CREATE TABLE secondary_contact (
    id text,
    contact text,
    deal text,
    c_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact) REFERENCES contact(id),
    FOREIGN KEY (deal) REFERENCES deal(id)
);

CREATE TABLE calendar (
    id text,
    user_id text,
    c_date text,
    m_date text,
    notification text,
    title text,
    token text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE address (
    id text,
    address_1 text,
    address_2 text,
    allgroup text,
    city text,
    company_name text,
    country text,
    created_by text,
    created_timestamp text,
    district text,
    is_default text,
    sms_name text,
    "state" text,
    updated_by text,
    updated_timestamp text,
    zip text,
    PRIMARY KEY (id)
);

CREATE TABLE campaign_list (
    id text,
    campaign_id text,
    list_id text,
    user_id text,
    c_date text,
    campaign text,
    links_campaign text,
    links_list text,
    links_user text,
    list text,
    list_amt text,
    "name" text,
    u_date text,
    users text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (list_id) REFERENCES list(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE groups (
    id text,
    descript text,
    optin_confirm text,
    p_admin text,
    pg_account_add text,
    pg_account_delete text,
    pg_account_edit text,
    pg_account_export text,
    pg_account_import text,
    pg_account_manage_custom_field text,
    pg_account_note_add text,
    pg_account_note_delete text,
    pg_account_note_edit text,
    pg_automation_manage text,
    pg_contact_actions text,
    pg_contact_add text,
    pg_contact_approve text,
    pg_contact_delete text,
    pg_contact_edit text,
    pg_contact_export text,
    pg_contact_fields text,
    pg_contact_filters text,
    pg_contact_import text,
    pg_contact_merge text,
    pg_contact_resubscribe text,
    pg_contact_sync text,
    pg_deal text,
    pg_deal_delete text,
    pg_deal_export text,
    pg_deal_fields text,
    pg_deal_group_add text,
    pg_deal_group_delete text,
    pg_deal_group_edit text,
    pg_deal_import text,
    pg_deal_list_all text,
    pg_deal_manage_roles text,
    pg_deal_note_add text,
    pg_deal_note_delete text,
    pg_deal_note_edit text,
    pg_deal_reassign text,
    pg_form_edit text,
    pg_group_add text,
    pg_group_delete text,
    pg_group_edit text,
    pg_landing_pages_access text,
    pg_list_add text,
    pg_list_bounce text,
    pg_list_delete text,
    pg_list_edit text,
    pg_list_email_account text,
    pg_list_headers text,
    pg_message_add text,
    pg_message_delete text,
    pg_message_edit text,
    pg_message_send text,
    pg_mfa_admin text,
    pg_personalization_add text,
    pg_personalization_delete text,
    pg_personalization_edit text,
    pg_reports_campaign text,
    pg_reports_deal text,
    pg_reports_list text,
    pg_reports_trend text,
    pg_reports_user text,
    pg_saved_responses_manage text,
    pg_startup_getting_started text,
    pg_startup_reports text,
    pg_tag_manage text,
    pg_template_add text,
    pg_template_delete text,
    pg_template_edit text,
    pg_user_add text,
    pg_user_delete text,
    pg_user_edit text,
    pg_web_personalization_manage text,
    req_approval text,
    req_approval_1_st text,
    req_approval_notify text,
    s_date text,
    social_data text,
    title text,
    unsubscribe_link text,
    PRIMARY KEY (id)
);

CREATE TABLE message (
    id text,
    user_id text,
    c_date text,
    charset text,
    ed_instance_id text,
    ed_version text,
    encoding text,
    format text,
    from_email text,
    from_name text,
    has_predictive_content text,
    hidden text,
    html text,
    html_fetch text,
    m_date text,
    "name" text,
    preheader_text text,
    preview_data text,
    preview_mime text,
    priority text,
    reply_2 text,
    subject text,
    text text,
    text_fetch text,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE contact_tracking_log (
    id text,
    contact_id text,
    hash text,
    tstamp text,
    "type" text,
    "value" text,
    PRIMARY KEY (id, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id)
);

CREATE TABLE pipeline_deal_stage (
    deal_stage_id text,
    deal_group_id text,
    PRIMARY KEY (deal_stage_id, deal_group_id),
    FOREIGN KEY (deal_group_id) REFERENCES pipeline(id)
);

CREATE TABLE pipeline (
    id text,
    all_groups text,
    all_users text,
    auto_assign text,
    c_date text,
    currency text,
    title text,
    u_date text,
    win_probability_initialize_date text,
    PRIMARY KEY (id)
);

CREATE TABLE form_action_data (
    _fivetran_id text,
    form_id text,
    email text,
    list text,
    "type" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (form_id) REFERENCES form(id)
);

CREATE TABLE form_c_field (
    _fivetran_id text,
    form_id text,
    class text,
    default_text text,
    header text,
    required text,
    "type" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (form_id) REFERENCES form(id)
);

CREATE TABLE form (
    id text,
    address_id text,
    user_id text,
    ac_branding text,
    "action" text,
    address text,
    aid text,
    body text,
    button text,
    c_date text,
    contacts text,
    deals text,
    default_screenshot text,
    entries text,
    layout text,
    "name" text,
    options_blanks_overwrite boolean,
    options_confaction text,
    options_confform text,
    options_optin_created boolean,
    options_optin_id text,
    options_sendoptin boolean,
    parent_form_id text,
    recent jsonb,
    style_ac_branding boolean,
    style_background text,
    style_border_color text,
    style_border_radius text,
    style_border_style text,
    style_border_width text,
    style_button_background text,
    style_button_border_color text,
    style_button_border_radius text,
    style_button_border_style text,
    style_button_border_width text,
    style_button_fontcolor text,
    style_button_padding text,
    style_dark boolean,
    style_font_color text,
    style_layout text,
    style_width text,
    submit text,
    submit_data_url text,
    thanks text,
    title text,
    u_date text,
    url text,
    width text,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE stage (
    id text,
    "group" text,
    c_date text,
    card_region_1 text,
    card_region_2 text,
    card_region_3 text,
    card_region_4 text,
    card_region_5 text,
    color text,
    deal_order text,
    groups text,
    orders text,
    title text,
    u_date text,
    width text,
    PRIMARY KEY (id),
    FOREIGN KEY ("group") REFERENCES pipeline(id)
);

CREATE TABLE task_type (
    id text,
    c_date text,
    def_duration text,
    "status" text,
    title text,
    u_date text,
    PRIMARY KEY (id)
);

CREATE TABLE account (
    id text,
    owner text,
    account_url text,
    contact_count text,
    created_timestamp text,
    deal_count text,
    "name" text,
    updated_timestamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (owner) REFERENCES users(id)
);

CREATE TABLE account_association (
    id text,
    account text,
    contact text,
    created_timestamp text,
    job_title text,
    updated_timestamp text,
    PRIMARY KEY (id),
    FOREIGN KEY (account) REFERENCES account(id),
    FOREIGN KEY (contact) REFERENCES contact(id)
);
