CREATE TABLE sales_order_detail (
    id text,
    sales_order_id text,
    sales_order_uuid text,
    account_cd text,
    alternate_id text,
    amount text,
    auto_create_issue text,
    average_cost text,
    branch text,
    calculate_discounts_on_import text,
    completed text,
    customer_order_nbr text,
    discount_amount text,
    discount_code text,
    discount_percent text,
    discounted_unit_price text,
    extended_price text,
    free_item text,
    inventory_id text,
    last_modified_date text,
    line_description text,
    line_nbr text,
    line_type text,
    location text,
    manual_discount text,
    mark_for_po text,
    note text,
    open_qty text,
    operation text,
    order_qty text,
    overship_threshold text,
    po_source text,
    project_task text,
    qty_on_shipment text,
    reason_code text,
    requested_on text,
    salesperson_id text,
    sched_order_date text,
    ship_on text,
    ship_to_location text,
    shipping_rule text,
    tax_category text,
    tax_zone text,
    unbilled_amount text,
    undership_threshold text,
    unit_cost text,
    unit_price text,
    uom text,
    warehouse_id text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, sales_order_id, sales_order_uuid),
    FOREIGN KEY (sales_order_id) REFERENCES sales_order(id),
    FOREIGN KEY (sales_order_uuid) REFERENCES sales_order(uuid),
    FOREIGN KEY (account_cd) REFERENCES account(account_cd)
);

CREATE TABLE sales_order (
    id text,
    uuid text,
    contact_id text,
    currency_id text,
    customer_id text,
    approved text,
    base_currency_id text,
    bill_to_address_override text,
    bill_to_contact_override text,
    cash_account text,
    control_total text,
    credit_hold text,
    currency_rate text,
    currency_rate_type_id text,
    customer_order text,
    "date" text,
    description text,
    destination_warehouse_id text,
    disable_automatic_discount_update text,
    effective_date text,
    external_ref text,
    hold text,
    is_tax_valid text,
    last_modified text,
    last_modified_datetime timestamp,
    line_total text,
    location_id text,
    note text,
    order_total text,
    order_type text,
    ordered_qty text,
    payment_method text,
    preferred_warehouse_id text,
    project text,
    reciprocal_rate text,
    requested_on text,
    ship_to_address_override text,
    ship_to_contact_override text,
    ship_via text,
    "status" text,
    tax_total text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, uuid),
    FOREIGN KEY (contact_id) REFERENCES customer(main_contact_contact_id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE stockitem_warehouse_detail (
    id text,
    stockitem_id text,
    default_issue_location text,
    default_receipt_location text,
    inventory_account text,
    inventory_subaccount text,
    is_default text,
    note text,
    override text,
    override_preferred_vendor text,
    override_std_cost text,
    preferred_vendor text,
    price_override text,
    product_manager text,
    product_workgroup text,
    qty_on_hand text,
    service_level text,
    "status" text,
    warehouse_id text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, stockitem_id),
    FOREIGN KEY (stockitem_id) REFERENCES stockitem(id)
);

CREATE TABLE stockitem (
    id text,
    abc_code text,
    auto_incremental_value text,
    average_cost text,
    base_uom text,
    cogs_account text,
    cogs_subaccount text,
    content text,
    default_issue_location text,
    default_price text,
    default_receipt_location text,
    default_warehouse text,
    description text,
    dimension_volume text,
    dimension_weight text,
    discount_account text,
    discount_subaccount text,
    image_url text,
    inventory_account text,
    inventory_id text,
    inventory_subaccount text,
    is_a_kit text,
    item_class text,
    item_status text,
    item_type text,
    landed_cost_variance_account text,
    landed_cost_variance_subaccount text,
    last_cost text,
    last_modified text,
    last_modified_datetime timestamp,
    last_std_cost text,
    lot_serial_class text,
    markup text,
    max_cost text,
    min_cost text,
    min_markup text,
    msrp text,
    note text,
    pending_std_cost text,
    po_accrual_account text,
    po_accrual_subaccount text,
    posting_class text,
    price_class text,
    price_manager text,
    price_workgroup text,
    product_manager text,
    product_workgroup text,
    purchase_price_variance_account text,
    purchase_price_variance_subaccount text,
    purchase_uom text,
    reason_code_subaccount text,
    sales_account text,
    sales_subaccount text,
    sales_uom text,
    standard_cost_revaluation_account text,
    standard_cost_revaluation_subaccount text,
    standard_cost_variance_account text,
    standard_cost_variance_subaccount text,
    tax_category text,
    valuation_method text,
    volume_uom text,
    weight_uom text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE currency (
    id text,
    uuid text,
    active text,
    created_date_time text,
    currency_symbol text,
    decimal_precision text,
    description text,
    last_modified_datetime timestamp,
    note text,
    use_for_accounting text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, uuid)
);

CREATE TABLE journal_transaction_detail (
    id text,
    journal_transaction_id text,
    account_cd text,
    branch text,
    credit_amount text,
    debit_amount text,
    description text,
    is_non_pm text,
    line_nbr text,
    non_billable text,
    note text,
    project text,
    project_task text,
    project_transaction_id text,
    qty text,
    reference_nbr text,
    subaccount text,
    transaction_description text,
    uom text,
    vendor_or_customer text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, journal_transaction_id),
    FOREIGN KEY (journal_transaction_id) REFERENCES journal_transaction(id),
    FOREIGN KEY (account_cd) REFERENCES account(account_cd)
);

CREATE TABLE journal_transaction (
    id text,
    currency_id text,
    batch_nbr text,
    branch_id text,
    created_date_time text,
    description text,
    hold text,
    last_modified_datetime timestamp,
    ledger_id text,
    module text,
    note text,
    post_period text,
    "status" text,
    transaction_date text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id)
);

CREATE TABLE payment (
    id text,
    currency_id text,
    customer_id text,
    application_date text,
    applied_to_document text,
    branch text,
    card_account_nbr text,
    cash_account text,
    description text,
    hold text,
    last_modified_datetime timestamp,
    note text,
    payment_amount text,
    payment_method text,
    payment_ref text,
    processing_center_id text,
    reference_nbr text,
    save_card text,
    "status" text,
    "type" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE invoice_detail (
    id text,
    account_cd text,
    invoice_id text,
    amount text,
    branch text,
    calculate_discounts_on_import text,
    discount_amount text,
    extended_price text,
    inventory_id text,
    last_modified_datetime timestamp,
    line_nbr text,
    note text,
    project_task text,
    qty text,
    subaccount text,
    transaction_description text,
    unit_price text,
    uom text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_cd) REFERENCES account(account_cd),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice (
    id text,
    customer_id text,
    amount text,
    balance text,
    bill_to_contact_override text,
    billing_printed text,
    created_date_time text,
    customer_order text,
    description text,
    due_date text,
    hold text,
    is_tax_valid text,
    last_modified_datetime timestamp,
    link_ar_account text,
    link_branch text,
    location_id text,
    note text,
    post_period text,
    project text,
    reference_nbr text,
    ship_to_contact_override text,
    "status" text,
    tax_total text,
    term text,
    "type" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE financial_period (
    id text,
    created_date_time text,
    financial_year text,
    last_modified_datetime timestamp,
    nbr_of_period text,
    note text,
    start_date text,
    user_defined_period text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE account (
    id text,
    uuid text,
    currency_id text,
    account_cd text,
    account_class text,
    account_group text,
    active text,
    cash_account text,
    chart_of_accounts_order text,
    created_date_time text,
    description text,
    last_modified_datetime timestamp,
    note text,
    post_option text,
    require_unit text,
    revaluation_rate_type text,
    secured text,
    "type" text,
    use_default_subaccount text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, uuid),
    FOREIGN KEY (currency_id) REFERENCES currency(id)
);

CREATE TABLE purchase_order_detail (
    id text,
    purchase_order_id text,
    purchase_order_uuid text,
    account_cd text,
    alternate_id text,
    branch_id text,
    calculate_discounts_on_import text,
    cancelled text,
    complete_on text,
    completed text,
    description text,
    extended_cost text,
    inventory_id text,
    line_description text,
    line_nbr text,
    line_type text,
    max_receipt_percent text,
    min_receipt_percent text,
    note text,
    order_nbr text,
    order_qty text,
    order_type text,
    orig_po_nbr text,
    orig_po_type text,
    project text,
    project_task text,
    promised text,
    qty_on_receipt text,
    receipt_action text,
    received_amount text,
    requested text,
    subaccount text,
    tax_category text,
    unit_cost text,
    uom text,
    warehouse_id text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, purchase_order_id, purchase_order_uuid),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (purchase_order_uuid) REFERENCES purchase_order(uuid),
    FOREIGN KEY (account_cd) REFERENCES account(account_cd)
);

CREATE TABLE purchase_order (
    id text,
    uuid text,
    currency_id text,
    vendor_id text,
    base_currency_id text,
    branch text,
    control_total text,
    currency_effective_date text,
    currency_rate text,
    currency_rate_type_id text,
    currency_reciprocal_rate text,
    "date" text,
    description text,
    hold text,
    last_modified_datetime timestamp,
    line_total text,
    location text,
    note text,
    order_total text,
    owner text,
    project text,
    promised_on text,
    "status" text,
    tax_total text,
    terms text,
    "type" text,
    vendor_ref text,
    vendor_tax_zone text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, uuid),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE bill_payment (
    id text,
    currency_id text,
    vendor_id text,
    application_date text,
    cash_account text,
    description text,
    detail jsonb,
    hold text,
    last_modified_datetime timestamp,
    note text,
    payment_amount text,
    payment_method text,
    payment_ref text,
    reference_nbr text,
    "status" text,
    "type" text,
    unapplied_balance text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE bill_detail (
    id text,
    bill_id text,
    account_cd text,
    amount text,
    branch text,
    calculate_discount_on_import text,
    description text,
    extended_cost text,
    inventory_id text,
    non_billable text,
    note text,
    po_line text,
    po_order_nbr text,
    po_order_type text,
    po_receipt_line text,
    po_receipt_nbr text,
    po_receipt_type text,
    project text,
    project_task text,
    qty text,
    subaccount text,
    tax_category text,
    transaction_description text,
    unit_cost text,
    uom text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, bill_id),
    FOREIGN KEY (bill_id) REFERENCES bill(id),
    FOREIGN KEY (account_cd) REFERENCES account(account_cd)
);

CREATE TABLE bill (
    id text,
    currency_id text,
    amount text,
    approved_for_payment text,
    balance text,
    branch_id text,
    cash_account text,
    "date" text,
    description text,
    due_date text,
    hold text,
    is_tax_valid text,
    last_modified_datetime timestamp,
    location_id text,
    note text,
    post_period text,
    project text,
    reference_nbr text,
    "status" text,
    tax_total text,
    term text,
    "type" text,
    vendor text,
    vendor_ref text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id)
);

CREATE TABLE vendor (
    id text,
    uuid text,
    currency_id text,
    account_ref text,
    ap_account text,
    ap_subaccount text,
    cash_account text,
    created_date_time text,
    currency_rate_type text,
    enable_currency_override text,
    enable_rate_override text,
    f_1099_box text,
    f_1099_vendor text,
    fatca text,
    fob_point text,
    foreign_entity text,
    landed_cost_vendor text,
    last_modified_datetime timestamp,
    lead_time_day text,
    location_name text,
    max_receipt text,
    min_receipt text,
    note text,
    parent_account text,
    pay_separately text,
    payment_by text,
    payment_lead_time_day text,
    payment_method text,
    print_order text,
    receipt_action text,
    receiving_branch text,
    remittance_address_override text,
    remittance_contact_override text,
    send_orders_by_email text,
    ship_via text,
    shipping_address_override text,
    shipping_contact_override text,
    shipping_terms text,
    "status" text,
    tax_registration_id text,
    tax_zone text,
    term text,
    threshold_receipt text,
    vendor_class text,
    vendor_is_labor_union text,
    vendor_is_tax_agency text,
    vendor_name text,
    warehouse text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, uuid),
    FOREIGN KEY (currency_id) REFERENCES currency(id)
);

CREATE TABLE customer (
    id text,
    uuid text,
    currency_id text,
    account_ref text,
    auto_apply_payment text,
    billing_address_override text,
    billing_contact_override text,
    created_date_time text,
    currency_rate_type text,
    customer_class text,
    customer_name text,
    enable_currency_override text,
    enable_rate_override text,
    enable_write_off text,
    fob_point text,
    last_modified_datetime timestamp,
    lead_timeday text,
    location_name text,
    main_contact_address_address_line_1 text,
    main_contact_address_address_line_2 text,
    main_contact_address_city text,
    main_contact_address_country text,
    main_contact_address_first_name text,
    main_contact_address_id text,
    main_contact_address_job_title text,
    main_contact_address_last_name text,
    main_contact_address_middle_name text,
    main_contact_address_note text,
    main_contact_address_phone_1 text,
    main_contact_address_phone_1_type text,
    main_contact_address_phone_2 text,
    main_contact_address_phone_2_type text,
    main_contact_address_postal_code text,
    main_contact_address_state text,
    main_contact_address_title text,
    main_contact_address_web_site text,
    main_contact_attention text,
    main_contact_company_name text,
    main_contact_contact_id text,
    main_contact_display_name text,
    main_contact_email text,
    main_contact_fax text,
    main_contact_first_name text,
    main_contact_job_title text,
    main_contact_last_name text,
    main_contact_middle_name text,
    main_contact_note text,
    main_contact_phone_1 text,
    main_contact_phone_1_type text,
    main_contact_phone_2 text,
    main_contact_phone_2_type text,
    main_contact_title text,
    main_contact_uuid text,
    main_contact_website text,
    multi_currency_statement text,
    note text,
    order_priority text,
    parent_record text,
    price_class_id text,
    print_invoice text,
    print_statement text,
    residential_delivery text,
    saturday_delivery text,
    send_invoice_by_email text,
    send_statement_by_email text,
    ship_via text,
    shipping_address_override text,
    shipping_branch text,
    shipping_contact_override text,
    shipping_rule text,
    shipping_term text,
    shipping_zone_id text,
    statement_cycle_id text,
    statement_type text,
    "status" text,
    tax_registration_id text,
    tax_zone text,
    term text,
    warehouse_id text,
    write_off_limit text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, uuid),
    FOREIGN KEY (currency_id) REFERENCES currency(id)
);
