CREATE TABLE message_quick_reply (
    target text,
    message_id text,
    button_type text,
    label text,
    PRIMARY KEY (target, message_id),
    FOREIGN KEY (message_id) REFERENCES message(id)
);

CREATE TABLE message_select_table (
    choose_prompt text,
    message_id text,
    PRIMARY KEY (choose_prompt, message_id),
    FOREIGN KEY (message_id) REFERENCES message(id)
);

CREATE TABLE message_selected (
    selected text,
    message_id text,
    PRIMARY KEY (selected, message_id),
    FOREIGN KEY (message_id) REFERENCES message(id)
);

CREATE TABLE message (
    id text,
    conversation_id text,
    agent_info_default_image text,
    agent_info_external_id text,
    agent_info_image_url text,
    agent_info_internal_id text,
    agent_info_name text,
    alt_text text,
    amount bigint,
    answer_id text,
    answer_title text,
    body text,
    button_type text,
    by text,
    chatter_id text,
    date_created timestamp,
    event text,
    external_chat_id text,
    external_id text,
    generate_link_preview boolean,
    has_forced_quick_replies boolean,
    has_variable boolean,
    header text,
    in_response_to text,
    is_expired boolean,
    is_forced boolean,
    is_handoff boolean,
    is_positive boolean,
    link_description text,
    link_icon text,
    link_text text,
    link_was_clicked boolean,
    locked boolean,
    meta_data_agent_id text,
    meta_data_department_id text,
    meta_data_display_name text,
    meta_data_event_type text,
    meta_data_id text,
    meta_data_name text,
    meta_data_new_value text,
    meta_data_old_value text,
    meta_data_response_id text,
    meta_data_scope text,
    meta_data_subtype text,
    meta_data_triggered_by text,
    meta_data_type text,
    meta_message_type text,
    multiple boolean,
    new_window boolean,
    pic_url text,
    prompt text,
    raw_url text,
    recipient text,
    record_last_updated text,
    review bigint,
    reviewable_message boolean,
    score bigint,
    sender text,
    style text,
    survey_type text,
    temp_message_uuid text,
    title text,
    tos text,
    "type" text,
    unit text,
    url text,
    window_button_label text,
    window_height bigint,
    window_title text,
    window_url text,
    window_width bigint,
    PRIMARY KEY (id),
    FOREIGN KEY (conversation_id) REFERENCES conversation(id)
);

CREATE TABLE conversation_feedback (
    feedback_message text,
    conversation_id text,
    PRIMARY KEY (feedback_message, conversation_id),
    FOREIGN KEY (conversation_id) REFERENCES conversation(id)
);

CREATE TABLE conversation (
    id text,
    agent_handle_time text,
    agent_id jsonb,
    agent_name jsonb,
    automated_resolution_classification text,
    automated_resolution_classification_reason text,
    bot_handle_time text,
    browser text,
    browser_version text,
    chatter_id text,
    csat_ces_max text,
    csat_comment text,
    csat_customer_effort_score text,
    csat_is_positive boolean,
    csat_net_promoter_score text,
    csat_resolved boolean,
    csat_score bigint,
    csat_style text,
    csat_survey_type text,
    date_created timestamp,
    date_updated timestamp,
    device text,
    end_user_id text,
    generated_topic_id text,
    generated_topic_label text,
    generated_topic_v_2_desc text,
    generated_topic_v_2_id text,
    generated_topic_v_2_parent_id text,
    generated_topic_v_2_title text,
    inquiry_summary text,
    is_engaged boolean,
    is_escalated boolean,
    is_test_user boolean,
    languages text,
    oauth_channel text,
    platform text,
    record_last_updated text,
    -- metavariable_* (dynamic column),
    -- variable_* (dynamic column),
    PRIMARY KEY (id)
);
