CREATE TABLE cart_item_discount (
    "index" text,
    cart_item_cart_id text,
    cart_item_item_id text,
    discount_data text,
    rule_id text,
    rule_label text,
    PRIMARY KEY ("index", cart_item_cart_id, cart_item_item_id),
    FOREIGN KEY (cart_item_cart_id) REFERENCES cart_item(cart_id),
    FOREIGN KEY (cart_item_item_id) REFERENCES cart_item(item_id)
);

CREATE TABLE cart_item (
    item_id text,
    cart_id text,
    "name" text,
    negotiable_quote_item_item_id text,
    negotiable_quote_item_original_discount_amount text,
    negotiable_quote_item_original_price text,
    negotiable_quote_item_original_tax_amount text,
    price text,
    product_type text,
    qty text,
    quote_id text,
    sku text,
    PRIMARY KEY (item_id, cart_id),
    FOREIGN KEY (cart_id) REFERENCES cart(id)
);

CREATE TABLE cart_shipping_address (
    "index" text,
    cart_id text,
    customer_address_id text,
    city text,
    company text,
    country_id text,
    custom_attribute text,
    customer_id text,
    email text,
    fax text,
    first_name text,
    id text,
    last_name text,
    middle_name text,
    post_code text,
    prefix text,
    region text,
    region_code text,
    region_id text,
    same_as_billing text,
    save_in_address_book text,
    street text,
    suffix text,
    telephone text,
    vat_id text,
    PRIMARY KEY ("index", cart_id),
    FOREIGN KEY (cart_id) REFERENCES cart(id),
    FOREIGN KEY (customer_address_id) REFERENCES customer_address(id)
);

CREATE TABLE cart (
    id text,
    billing_address_customer_address_id text,
    customer_id text,
    orig_order_id text,
    reserved_order_id text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country_id text,
    billing_address_custom_attribute text,
    billing_address_customer_id text,
    billing_address_email text,
    billing_address_fax text,
    billing_address_first_name text,
    billing_address_id text,
    billing_address_last_name text,
    billing_address_middle_name text,
    billing_address_post_code text,
    billing_address_prefix text,
    billing_address_region text,
    billing_address_region_code text,
    billing_address_region_id text,
    billing_address_same_as_billing text,
    billing_address_save_in_address_book text,
    billing_address_street text,
    billing_address_suffix text,
    billing_address_telephone text,
    billing_address_vat_id text,
    converted_at text,
    created_at text,
    currency_base_currency_code text,
    currency_base_to_global_rate text,
    currency_base_to_quote_rate text,
    currency_global_currency_code text,
    currency_quote_currency_code text,
    currency_store_currency_code text,
    currency_store_to_base_rate text,
    currency_store_to_quote_rate text,
    customer_is_guest text,
    customer_note text,
    customer_note_notify text,
    customer_tax_class_id text,
    is_active text,
    is_virtual text,
    items_count text,
    items_qty text,
    negotiable_quote_applied_rule_ids text,
    negotiable_quote_base_negotiated_total_price text,
    negotiable_quote_base_original_total_price text,
    negotiable_quote_creator_id text,
    negotiable_quote_creator_type text,
    negotiable_quote_deleted_sku text,
    negotiable_quote_email_notification_status text,
    negotiable_quote_expiration_period text,
    negotiable_quote_has_unconfirmed_changes text,
    negotiable_quote_is_address_draft text,
    negotiable_quote_is_customer_price_changed text,
    negotiable_quote_is_regular_quote text,
    negotiable_quote_is_shipping_tax_changed text,
    negotiable_quote_negotiated_price_type text,
    negotiable_quote_negotiated_price_value text,
    negotiable_quote_negotiated_total_price text,
    negotiable_quote_notifications text,
    negotiable_quote_original_total_price text,
    negotiable_quote_quote_id text,
    negotiable_quote_quote_name text,
    negotiable_quote_shipping_price text,
    negotiable_quote_status text,
    store_id text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_address_customer_address_id) REFERENCES customer_address(id),
    FOREIGN KEY (customer_id) REFERENCES customer_address(customer_id),
    FOREIGN KEY (orig_order_id) REFERENCES orders(entity_id),
    FOREIGN KEY (reserved_order_id) REFERENCES orders(entity_id)
);

CREATE TABLE tax_rate_title (
    "index" text,
    tax_rate_id text,
    store_id text,
    "value" text,
    PRIMARY KEY ("index", tax_rate_id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE tax_rate (
    id text,
    code text,
    rate text,
    region_name text,
    tax_country_id text,
    tax_postcode text,
    tax_region_id text,
    zip_from text,
    zip_is_range text,
    zip_to text,
    PRIMARY KEY (id)
);

CREATE TABLE configurable_products (
    id text,
    product_id text,
    attribute_set_id text,
    created_at text,
    "name" text,
    price text,
    sku text,
    "status" text,
    type_id text,
    updated_at text,
    visibility text,
    weight text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE gift_wrapping (
    wrapping_id text,
    base_currency_code text,
    base_price text,
    design text,
    image_base_64_content text,
    image_name text,
    image_url text,
    "status" text,
    website_ids text,
    PRIMARY KEY (wrapping_id)
);

CREATE TABLE sales_rule_store_labels (
    sales_rule_rule_id text,
    store_id text,
    store_label text,
    PRIMARY KEY (sales_rule_rule_id, store_id),
    FOREIGN KEY (sales_rule_rule_id) REFERENCES sales_rule(rule_id),
    FOREIGN KEY (store_id) REFERENCES store(id)
);

CREATE TABLE sales_rule (
    rule_id text,
    action_condition_aggregator_type text,
    action_condition_attribute_name text,
    action_condition_condition_type text,
    action_condition_conditions text,
    action_condition_operator text,
    action_condition_value text,
    apply_to_shipping text,
    condition_aggregator_type text,
    condition_attribute_name text,
    condition_condition_type text,
    condition_conditions text,
    condition_operator text,
    condition_value text,
    coupon_type text,
    customer_group_ids text,
    description text,
    discount_amount text,
    discount_qty text,
    discount_step text,
    extension_attributes_reward_points_delta text,
    from_date text,
    is_active text,
    is_advanced text,
    is_rss text,
    "name" text,
    product_ids text,
    simple_action text,
    simple_free_shipping text,
    sort_order text,
    stop_rules_processing text,
    times_used text,
    to_date text,
    use_auto_generation text,
    uses_per_coupon text,
    uses_per_customer text,
    website_ids text,
    PRIMARY KEY (rule_id)
);

CREATE TABLE shipment_item (
    entity_id text,
    shipment_entity_id text,
    order_item_id text,
    parent_id text,
    product_id text,
    additional_data text,
    description text,
    "name" text,
    price text,
    qty text,
    row_total text,
    sku text,
    weight text,
    PRIMARY KEY (entity_id, shipment_entity_id),
    FOREIGN KEY (shipment_entity_id) REFERENCES shipment(entity_id),
    FOREIGN KEY (order_item_id) REFERENCES order_item(item_id),
    FOREIGN KEY (parent_id) REFERENCES shipment_item(entity_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE shipment_track (
    entity_id text,
    shipment_entity_id text,
    parent_id text,
    carrier_code text,
    created_at text,
    description text,
    qty text,
    title text,
    track_number text,
    updated_at text,
    weight text,
    PRIMARY KEY (entity_id, shipment_entity_id),
    FOREIGN KEY (shipment_entity_id) REFERENCES shipment(entity_id),
    FOREIGN KEY (parent_id) REFERENCES shipment_track(entity_id)
);

CREATE TABLE shipment_comment (
    entity_id text,
    shipment_entity_id text,
    parent_id text,
    "comment" text,
    created_at text,
    is_customer_notified text,
    is_visible_on_front text,
    PRIMARY KEY (entity_id, shipment_entity_id),
    FOREIGN KEY (shipment_entity_id) REFERENCES shipment(entity_id),
    FOREIGN KEY (parent_id) REFERENCES shipment_comment(entity_id)
);

CREATE TABLE shipment (
    entity_id text,
    customer_id text,
    order_id text,
    store_id text,
    billing_address_id text,
    created_at text,
    email_sent text,
    extension_attributes_source_code text,
    increment_id text,
    shipment_status text,
    shipping_address_id text,
    shipping_label text,
    total_qty text,
    total_weight text,
    updated_at text,
    PRIMARY KEY (entity_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (order_id) REFERENCES orders(entity_id),
    FOREIGN KEY (store_id) REFERENCES store(id)
);

CREATE TABLE directory_country_available_region (
    id text,
    directory_country_id text,
    code text,
    "name" text,
    PRIMARY KEY (id, directory_country_id),
    FOREIGN KEY (directory_country_id) REFERENCES directory_country(id)
);

CREATE TABLE directory_country (
    id text,
    full_name_english text,
    full_name_locale text,
    three_letter_abbreviation text,
    two_letter_abbreviation text,
    PRIMARY KEY (id)
);

CREATE TABLE credit_memo_item (
    entity_id text,
    credit_memo_entity_id text,
    parent_id text,
    additional_data text,
    base_cost text,
    base_discount_amount text,
    base_discount_tax_compensation_amount text,
    base_price text,
    base_price_incl_tax text,
    base_row_total text,
    base_row_total_incl_tax text,
    base_tax_amount text,
    base_weee_tax_applied_amount text,
    base_weee_tax_applied_row_amnt text,
    base_weee_tax_disposition text,
    base_weee_tax_row_disposition text,
    description text,
    discount_amount text,
    discount_tax_compensation_amount text,
    "name" text,
    order_item_id text,
    price text,
    price_incl_tax text,
    product_id text,
    qty text,
    row_total text,
    row_total_incl_tax text,
    sku text,
    tax_amount text,
    weee_tax_applied text,
    weee_tax_applied_amount text,
    weee_tax_applied_row_amount text,
    weee_tax_disposition text,
    weee_tax_row_disposition text,
    PRIMARY KEY (entity_id, credit_memo_entity_id),
    FOREIGN KEY (credit_memo_entity_id) REFERENCES credit_memo(entity_id),
    FOREIGN KEY (parent_id) REFERENCES credit_memo_item(entity_id)
);

CREATE TABLE credit_memo_comment (
    entity_id text,
    credit_memo_entity_id text,
    parent_id text,
    "comment" text,
    created_at text,
    is_customer_notified text,
    is_visible_on_front text,
    PRIMARY KEY (entity_id, credit_memo_entity_id),
    FOREIGN KEY (credit_memo_entity_id) REFERENCES credit_memo(entity_id),
    FOREIGN KEY (parent_id) REFERENCES credit_memo_comment(entity_id)
);

CREATE TABLE credit_memo (
    entity_id text,
    invoice_id text,
    order_id text,
    store_id text,
    transaction_id text,
    adjustment text,
    adjustment_negative text,
    adjustment_positive text,
    base_adjustment text,
    base_adjustment_negative text,
    base_adjustment_positive text,
    base_currency_code text,
    base_customer_balance_amount text,
    base_discount_amount text,
    base_discount_tax_compensation_amount text,
    base_gift_cards_amount text,
    base_grand_total text,
    base_shipping_amount text,
    base_shipping_discount_tax_compensation_amnt text,
    base_shipping_incl_tax text,
    base_shipping_tax_amount text,
    base_subtotal text,
    base_subtotal_incl_tax text,
    base_tax_amount text,
    base_to_global_rate text,
    base_to_order_rate text,
    billing_address_id text,
    created_at text,
    creditmemo_status text,
    customer_balance_amount text,
    discount_amount text,
    discount_description text,
    discount_tax_compensation_amount text,
    email_sent text,
    gift_cards_amount text,
    global_currency_code text,
    grand_total text,
    gw_base_price text,
    gw_base_tax_amount text,
    gw_card_base_price text,
    gw_card_price text,
    gw_items_base_price text,
    gw_items_price text,
    gw_price text,
    increment_id text,
    order_currency_code text,
    shipping_address_id text,
    shipping_amount text,
    shipping_discount_tax_compensation_amount text,
    shipping_incl_tax text,
    shipping_tax_amount text,
    "state" text,
    store_currency_code text,
    store_to_base_rate text,
    store_to_order_rate text,
    subtotal text,
    subtotal_incl_tax text,
    tax_amount text,
    updated_at text,
    PRIMARY KEY (entity_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(entity_id),
    FOREIGN KEY (order_id) REFERENCES orders(entity_id),
    FOREIGN KEY (store_id) REFERENCES store(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE customer_group (
    id text,
    code text,
    extension_attributes_exclude_website_ids text,
    tax_class_id text,
    tax_class_name text,
    PRIMARY KEY (id)
);

CREATE TABLE order_status_history (
    entity_id text,
    orders_entity_id text,
    parent_id text,
    "comment" text,
    created_at text,
    entity_name text,
    is_customer_notified text,
    is_visible_on_front text,
    "status" text,
    PRIMARY KEY (entity_id, orders_entity_id),
    FOREIGN KEY (orders_entity_id) REFERENCES orders(entity_id),
    FOREIGN KEY (parent_id) REFERENCES order_status_history(entity_id)
);

CREATE TABLE order_shipping_address (
    "index" text,
    order_entity_id text,
    customer_address_id text,
    address_type text,
    base_shipping_amount text,
    base_shipping_discount_amount text,
    base_shipping_discount_tax_compensation_amnt text,
    base_shipping_incl_tax text,
    base_shipping_invoiced text,
    base_shipping_tax_amount text,
    city text,
    country_id text,
    email text,
    entity_id text,
    firstname text,
    lastname text,
    method text,
    parent_id text,
    postcode text,
    region text,
    region_code text,
    region_id text,
    shipping_amount text,
    shipping_discount_amount text,
    shipping_discount_tax_compensation_amount text,
    shipping_incl_tax text,
    shipping_invoiced text,
    shipping_tax_amount text,
    street jsonb,
    telephone text,
    PRIMARY KEY ("index", order_entity_id),
    FOREIGN KEY (order_entity_id) REFERENCES orders(entity_id),
    FOREIGN KEY (customer_address_id) REFERENCES customer_address(id)
);

CREATE TABLE order_item (
    item_id text,
    orders_entity_id text,
    product_id text,
    additional_data text,
    amount_refunded text,
    applied_rule_ids text,
    base_amount_refunded text,
    base_cost text,
    base_discount_amount text,
    base_discount_invoiced text,
    base_discount_refunded text,
    base_discount_tax_compensation_amount text,
    base_discount_tax_compensation_invoiced text,
    base_discount_tax_compensation_refunded text,
    base_original_price text,
    base_price text,
    base_price_incl_tax text,
    base_row_invoiced text,
    base_row_total text,
    base_row_total_incl_tax text,
    base_tax_amount text,
    base_tax_before_discount text,
    base_tax_invoiced text,
    base_tax_refunded text,
    base_weee_tax_applied_amount text,
    base_weee_tax_applied_row_amnt text,
    base_weee_tax_disposition text,
    base_weee_tax_row_disposition text,
    created_at text,
    description text,
    discount_amount text,
    discount_invoiced text,
    discount_percent text,
    discount_refunded text,
    discount_tax_compensation_amount text,
    discount_tax_compensation_canceled text,
    discount_tax_compensation_invoiced text,
    discount_tax_compensation_refunded text,
    event_id text,
    ext_order_item_id text,
    free_shipping text,
    gw_base_price text,
    gw_base_price_invoiced text,
    gw_base_price_refunded text,
    gw_base_tax_amount text,
    gw_base_tax_amount_invoiced text,
    gw_base_tax_amount_refunded text,
    gw_id text,
    gw_price text,
    gw_price_invoiced text,
    gw_price_refunded text,
    gw_tax_amount text,
    gw_tax_amount_invoiced text,
    gw_tax_amount_refunded text,
    is_qty_decimal text,
    is_virtual text,
    locked_do_invoice text,
    locked_do_ship text,
    "name" text,
    no_discount text,
    order_id text,
    original_price text,
    parent_item_id text,
    price text,
    price_incl_tax text,
    product_type text,
    qty_backordered text,
    qty_canceled text,
    qty_invoiced text,
    qty_ordered text,
    qty_refunded text,
    qty_returned text,
    qty_shipped text,
    quote_item_id text,
    row_invoiced text,
    row_total text,
    row_total_incl_tax text,
    row_weight text,
    sku text,
    store_id text,
    tax_amount text,
    tax_before_discount text,
    tax_canceled text,
    tax_invoiced text,
    tax_percent text,
    tax_refunded text,
    updated_at text,
    weee_tax_applied text,
    weee_tax_applied_amount text,
    weee_tax_applied_row_amount text,
    weee_tax_disposition text,
    weee_tax_row_disposition text,
    weight text,
    PRIMARY KEY (item_id, orders_entity_id),
    FOREIGN KEY (orders_entity_id) REFERENCES orders(entity_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE orders (
    entity_id text,
    customer_id text,
    store_id text,
    adjustment_negative text,
    adjustment_positive text,
    applied_rule_ids text,
    base_adjustment_negative text,
    base_adjustment_positive text,
    base_currency_code text,
    base_discount_amount text,
    base_discount_canceled text,
    base_discount_invoiced text,
    base_discount_refunded text,
    base_discount_tax_compensation_invoiced text,
    base_discount_tax_compensation_refunded text,
    base_grand_total text,
    base_shipping_amount text,
    base_shipping_canceled text,
    base_shipping_discount_amount text,
    base_shipping_discount_tax_compensation_amnt text,
    base_shipping_incl_tax text,
    base_shipping_invoiced text,
    base_shipping_refunded text,
    base_shipping_tax_amount text,
    base_shipping_tax_refunded text,
    base_subtotal text,
    base_subtotal_canceled text,
    base_subtotal_incl_tax text,
    base_subtotal_invoiced text,
    base_subtotal_refunded text,
    base_tax_amount text,
    base_tax_canceled text,
    base_tax_invoiced text,
    base_tax_refunded text,
    base_to_global_rate text,
    base_to_order_rate text,
    base_total_canceled text,
    base_total_due text,
    base_total_invoiced text,
    base_total_invoiced_cost text,
    base_total_offline_refunded text,
    base_total_online_refunded text,
    base_total_paid text,
    base_total_refunded text,
    billing_address_address_type text,
    billing_address_city text,
    billing_address_country_id text,
    billing_address_email text,
    billing_address_entity_id text,
    billing_address_firstname text,
    billing_address_lastname text,
    billing_address_parent_id text,
    billing_address_postcode text,
    billing_address_region text,
    billing_address_region_code text,
    billing_address_region_id text,
    billing_address_street jsonb,
    billing_address_telephone text,
    can_ship_partially text,
    can_ship_partially_item text,
    coupon_code text,
    created_at text,
    customer_email text,
    discount_amount text,
    discount_canceled text,
    discount_description text,
    discount_invoiced text,
    discount_refunded text,
    discount_tax_compensation_amount text,
    discount_tax_compensation_invoiced text,
    discount_tax_compensation_refunded text,
    edit_increment text,
    email_sent text,
    ext_customer_id text,
    ext_order_id text,
    extension_attributes_base_customer_balance_amount text,
    extension_attributes_base_customer_balance_invoiced text,
    extension_attributes_base_customer_balance_refunded text,
    extension_attributes_base_customer_balance_total_refunded text,
    extension_attributes_base_gift_cards_amount text,
    extension_attributes_base_gift_cards_invoiced text,
    extension_attributes_base_gift_cards_refunded text,
    extension_attributes_base_reward_currency_amount text,
    extension_attributes_company_order_attributes_company_id text,
    extension_attributes_company_order_attributes_company_name text,
    extension_attributes_company_order_attributes_order_id text,
    extension_attributes_converting_from_quote text,
    extension_attributes_customer_balance_amount text,
    extension_attributes_customer_balance_invoiced text,
    extension_attributes_customer_balance_refunded text,
    extension_attributes_customer_balance_total_refunded text,
    extension_attributes_gift_cards_amount text,
    extension_attributes_gift_cards_invoiced text,
    extension_attributes_gift_cards_refunded text,
    extension_attributes_gw_add_card text,
    extension_attributes_gw_allow_gift_receipt text,
    extension_attributes_gw_base_price text,
    extension_attributes_gw_base_price_incl_tax text,
    extension_attributes_gw_base_price_invoiced text,
    extension_attributes_gw_base_price_refunded text,
    extension_attributes_gw_base_tax_amount text,
    extension_attributes_gw_base_tax_amount_invoiced text,
    extension_attributes_gw_base_tax_amount_refunded text,
    extension_attributes_gw_card_base_price text,
    extension_attributes_gw_card_base_price_incl_tax text,
    extension_attributes_gw_card_base_price_invoiced text,
    extension_attributes_gw_card_base_price_refunded text,
    extension_attributes_gw_card_base_tax_amount text,
    extension_attributes_gw_card_base_tax_invoiced text,
    extension_attributes_gw_card_base_tax_refunded text,
    extension_attributes_gw_card_price text,
    extension_attributes_gw_card_price_incl_tax text,
    extension_attributes_gw_card_price_invoiced text,
    extension_attributes_gw_card_price_refunded text,
    extension_attributes_gw_card_tax_amount text,
    extension_attributes_gw_card_tax_invoiced text,
    extension_attributes_gw_card_tax_refunded text,
    extension_attributes_gw_id text,
    extension_attributes_gw_items_base_price text,
    extension_attributes_gw_items_base_price_incl_tax text,
    extension_attributes_gw_items_base_price_invoiced text,
    extension_attributes_gw_items_base_price_refunded text,
    extension_attributes_gw_items_base_tax_amount text,
    extension_attributes_gw_items_base_tax_invoiced text,
    extension_attributes_gw_items_base_tax_refunded text,
    extension_attributes_gw_items_price text,
    extension_attributes_gw_items_price_incl_tax text,
    extension_attributes_gw_items_price_invoiced text,
    extension_attributes_gw_items_price_refunded text,
    extension_attributes_gw_items_tax_amount text,
    extension_attributes_gw_items_tax_invoiced text,
    extension_attributes_gw_items_tax_refunded text,
    extension_attributes_gw_price text,
    extension_attributes_gw_price_incl_tax text,
    extension_attributes_gw_price_invoiced text,
    extension_attributes_gw_price_refunded text,
    extension_attributes_gw_tax_amount text,
    extension_attributes_gw_tax_amount_invoiced text,
    extension_attributes_gw_tax_amount_refunded text,
    extension_attributes_notification_sent text,
    extension_attributes_pickup_location_code text,
    extension_attributes_reward_currency_amount text,
    extension_attributes_reward_points_balance text,
    extension_attributes_send_notification text,
    forced_shipment_with_invoice text,
    global_currency_code text,
    grand_total text,
    hold_before_state text,
    hold_before_status text,
    increment_id text,
    is_virtual text,
    order_currency_code text,
    original_increment_id text,
    payment_account_status text,
    payment_additional_data text,
    payment_additional_information text,
    payment_address_status text,
    payment_amount_authorized text,
    payment_amount_canceled text,
    payment_amount_ordered text,
    payment_amount_paid text,
    payment_amount_refunded text,
    payment_anet_trans_method text,
    payment_auth_expiration text,
    payment_authorization_amount text,
    payment_base_amount_authorized text,
    payment_base_amount_canceled text,
    payment_base_amount_ordered text,
    payment_base_amount_paid text,
    payment_base_amount_paid_online text,
    payment_base_amount_refunded text,
    payment_base_amount_refunded_online text,
    payment_base_shipping_amount text,
    payment_base_shipping_captured text,
    payment_base_shipping_refunded text,
    payment_cc_approval text,
    payment_cc_avs_status text,
    payment_cc_cid_status text,
    payment_cc_debug_request_body text,
    payment_cc_debug_response_body text,
    payment_cc_debug_response_serialized text,
    payment_cc_exp_month text,
    payment_cc_exp_year text,
    payment_cc_last_4 text,
    payment_cc_number_enc text,
    payment_cc_owner text,
    payment_cc_secure_verify text,
    payment_cc_ss_issue text,
    payment_cc_ss_start_month text,
    payment_cc_ss_start_year text,
    payment_cc_status text,
    payment_cc_status_description text,
    payment_cc_trans_id text,
    payment_cc_type text,
    payment_echeck_account_name text,
    payment_echeck_account_type text,
    payment_echeck_bank_name text,
    payment_echeck_routing_number text,
    payment_echeck_type text,
    payment_entity_id text,
    payment_extension_attributes_notification_message text,
    payment_extension_attributes_vault_payment_token_created_at text,
    payment_extension_attributes_vault_payment_token_customer_id text,
    payment_extension_attributes_vault_payment_token_entity_id text,
    payment_extension_attributes_vault_payment_token_expires_at text,
    payment_extension_attributes_vault_payment_token_gateway_token text,
    payment_extension_attributes_vault_payment_token_is_active text,
    payment_extension_attributes_vault_payment_token_is_visible text,
    payment_extension_attributes_vault_payment_token_payment_method_code text,
    payment_extension_attributes_vault_payment_token_public_hash text,
    payment_extension_attributes_vault_payment_token_token_details text,
    payment_extension_attributes_vault_payment_token_type text,
    payment_last_trans_id text,
    payment_method text,
    payment_parent_id text,
    payment_po_number text,
    payment_protection_eligibility text,
    payment_quote_payment_id text,
    payment_shipping_amount text,
    payment_shipping_captured text,
    payment_shipping_refunded text,
    protect_code text,
    quote_address_id text,
    quote_id text,
    relation_child_id text,
    relation_child_real_id text,
    relation_parent_id text,
    relation_parent_real_id text,
    remote_ip text,
    shipping_amount text,
    shipping_canceled text,
    shipping_description text,
    shipping_discount_amount text,
    shipping_discount_tax_compensation_amount text,
    shipping_incl_tax text,
    shipping_invoiced text,
    shipping_refunded text,
    shipping_tax_amount text,
    shipping_tax_refunded text,
    "state" text,
    "status" text,
    store_currency_code text,
    store_to_base_rate text,
    store_to_order_rate text,
    subtotal text,
    subtotal_canceled text,
    subtotal_incl_tax text,
    subtotal_invoiced text,
    subtotal_refunded text,
    tax_amount text,
    tax_canceled text,
    tax_invoiced text,
    tax_refunded text,
    total_canceled text,
    total_due text,
    total_invoiced text,
    total_item_count text,
    total_offline_refunded text,
    total_online_refunded text,
    total_paid text,
    total_qty_ordered text,
    total_refunded text,
    updated_at text,
    weight text,
    x_forwarded_for text,
    PRIMARY KEY (entity_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (store_id) REFERENCES store(id)
);

CREATE TABLE company_credit (
    id text,
    company_id text,
    available_limit text,
    balance text,
    credit_limit text,
    currency_code text,
    exceed_limit text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE adobestock (
    id text,
    category_id text,
    category_name text,
    creation_date text,
    creator_id text,
    creator_name text,
    is_licensed text,
    media_gallery_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE inventory (
    _fivetran_id text,
    quantity text,
    sku text,
    source_code text,
    "status" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE company (
    id text,
    country_id text,
    customer_group_id text,
    region_id text,
    applicable_payment_method text,
    applicable_shipping_method text,
    available_payment_methods text,
    available_shipping_methods text,
    city text,
    "comment" text,
    company_email text,
    company_name text,
    is_purchase_order_enabled text,
    legal_name text,
    postcode text,
    quote_config_company_id text,
    quote_config_is_quote_enabled text,
    region text,
    reject_reason text,
    rejected_at text,
    reseller_id text,
    sales_representative_id text,
    "status" text,
    street text,
    super_user_id text,
    telephone text,
    use_config_settings text,
    use_config_settings_shipping text,
    vat_tax_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (country_id) REFERENCES directory_country_available_region(directory_country_id),
    FOREIGN KEY (customer_group_id) REFERENCES customer_group(id),
    FOREIGN KEY (region_id) REFERENCES directory_country_available_region(id)
);

CREATE TABLE product_link (
    "index" text,
    product_id text,
    extension_attributes_qty text,
    link_type text,
    linked_product_sku text,
    linked_product_type text,
    "position" text,
    sku text,
    PRIMARY KEY ("index", product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_option_value (
    "index" text,
    product_option_option_id text,
    product_option_product_id text,
    option_type_id text,
    price text,
    price_type text,
    sku text,
    sort_order text,
    title text,
    PRIMARY KEY ("index", product_option_option_id, product_option_product_id),
    FOREIGN KEY (product_option_option_id) REFERENCES product_option(option_id),
    FOREIGN KEY (product_option_product_id) REFERENCES product_option(product_id)
);

CREATE TABLE product_option (
    option_id text,
    product_id text,
    file_extension text,
    image_size_x text,
    image_size_y text,
    is_require text,
    max_characters text,
    price text,
    price_type text,
    product_sku text,
    sku text,
    sort_order text,
    title text,
    "type" text,
    PRIMARY KEY (option_id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_media_gallery_entry (
    id text,
    product_id text,
    content_base_64_encoded_data text,
    content_name text,
    content_type text,
    disabled text,
    extension_attributes_video_content_media_type text,
    extension_attributes_video_content_video_description text,
    extension_attributes_video_content_video_metadata text,
    extension_attributes_video_content_video_provider text,
    extension_attributes_video_content_video_title text,
    extension_attributes_video_content_video_url text,
    file text,
    label text,
    media_type text,
    "position" text,
    types text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_tier_price (
    "index" text,
    product_id text,
    customer_group_id text,
    extension_attributes_percentage_value text,
    extension_attributes_website_id text,
    qty text,
    "value" text,
    PRIMARY KEY ("index", product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_bundle_product_option (
    option_id text,
    product_id text,
    "position" text,
    required text,
    sku text,
    title text,
    "type" text,
    PRIMARY KEY (option_id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    attribute_set_id text,
    created_at text,
    "name" text,
    price text,
    sku text,
    "status" text,
    type_id text,
    updated_at text,
    visibility text,
    weight text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE coupon (
    coupon_id text,
    code text,
    created_at text,
    expiration_date text,
    is_primary text,
    rule_id text,
    times_used text,
    "type" text,
    usage_limit text,
    usage_per_customer text,
    PRIMARY KEY (coupon_id)
);

CREATE TABLE tax_rule_tax_rate (
    tax_rate_id text,
    tax_rule_id text,
    PRIMARY KEY (tax_rate_id, tax_rule_id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id),
    FOREIGN KEY (tax_rule_id) REFERENCES tax_rule(id)
);

CREATE TABLE tax_rule (
    id text,
    calculate_subtotal text,
    code text,
    customer_tax_class_ids text,
    "position" text,
    priority text,
    product_tax_class_ids text,
    PRIMARY KEY (id)
);

CREATE TABLE team (
    id text,
    description text,
    "name" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE store (
    id text,
    code text,
    is_active text,
    "name" text,
    store_group_id text,
    website_id text,
    PRIMARY KEY (id)
);

CREATE TABLE product_bundle_products (
    id text,
    product_id text,
    option_id text,
    can_change_quantity text,
    is_default text,
    "position" text,
    price text,
    price_type text,
    qty text,
    sku text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (option_id) REFERENCES product_option(option_id)
);

CREATE TABLE invoice_item (
    "index" text,
    invoice_entity_id text,
    parent_id text,
    additional_data text,
    base_cost text,
    base_discount_amount text,
    base_discount_tax_compensation_amount text,
    base_price text,
    base_price_incl_tax text,
    base_row_total text,
    base_row_total_incl_tax text,
    base_tax_amount text,
    description text,
    discount_amount text,
    discount_tax_compensation_amount text,
    entity_id text,
    "name" text,
    order_item_id text,
    price text,
    price_incl_tax text,
    product_id text,
    qty text,
    row_total text,
    row_total_incl_tax text,
    sku text,
    tax_amount text,
    PRIMARY KEY ("index", invoice_entity_id),
    FOREIGN KEY (invoice_entity_id) REFERENCES invoice(entity_id),
    FOREIGN KEY (parent_id) REFERENCES invoice_item(invoice_entity_id)
);

CREATE TABLE invoice_comment (
    "index" text,
    invoice_entity_id text,
    parent_id text,
    "comment" text,
    created_at text,
    entity_id text,
    is_customer_notified text,
    is_visible_on_front text,
    PRIMARY KEY ("index", invoice_entity_id),
    FOREIGN KEY (invoice_entity_id) REFERENCES invoice(entity_id),
    FOREIGN KEY (parent_id) REFERENCES invoice_comment(invoice_entity_id)
);

CREATE TABLE invoice (
    entity_id text,
    order_id text,
    store_id text,
    transaction_id text,
    base_currency_code text,
    base_discount_amount text,
    base_discount_tax_compensation_amount text,
    base_grand_total text,
    base_shipping_amount text,
    base_shipping_discount_tax_compensation_amnt text,
    base_shipping_incl_tax text,
    base_shipping_tax_amount text,
    base_subtotal text,
    base_subtotal_incl_tax text,
    base_tax_amount text,
    base_to_global_rate text,
    base_to_order_rate text,
    base_total_refunded text,
    billing_address_id text,
    can_void_flag text,
    created_at text,
    discount_amount text,
    discount_description text,
    discount_tax_compensation_amount text,
    email_sent text,
    extension_attributes_base_customer_balance_amount text,
    extension_attributes_base_gift_cards_amount text,
    extension_attributes_customer_balance_amount text,
    extension_attributes_gift_cards_amount text,
    extension_attributes_gw_base_price text,
    extension_attributes_gw_base_tax_amount text,
    extension_attributes_gw_card_base_price text,
    extension_attributes_gw_card_base_tax_amount text,
    extension_attributes_gw_card_price text,
    extension_attributes_gw_card_tax_amount text,
    extension_attributes_gw_items_base_price text,
    extension_attributes_gw_items_base_tax_amount text,
    extension_attributes_gw_items_price text,
    extension_attributes_gw_items_tax_amount text,
    extension_attributes_gw_price text,
    extension_attributes_gw_tax_amount text,
    global_currency_code text,
    grand_total text,
    increment_id text,
    is_used_for_refund text,
    order_currency_code text,
    shipping_address_id text,
    shipping_amount text,
    shipping_discount_tax_compensation_amount text,
    shipping_incl_tax text,
    shipping_tax_amount text,
    "state" text,
    store_currency_code text,
    store_to_base_rate text,
    store_to_order_rate text,
    subtotal text,
    subtotal_incl_tax text,
    tax_amount text,
    total_qty text,
    updated_at text,
    PRIMARY KEY (entity_id),
    FOREIGN KEY (order_id) REFERENCES orders(entity_id),
    FOREIGN KEY (store_id) REFERENCES store(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE category (
    id text,
    parent_id text,
    available_sort_by text,
    children text,
    created_at text,
    include_in_menu text,
    is_active text,
    "level" text,
    "name" text,
    "path" text,
    "position" text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES category(id)
);

CREATE TABLE "transaction" (
    id text,
    order_id text,
    parent_id text,
    additional_information text,
    created_at text,
    is_closed text,
    parent_txn_id text,
    payment_id text,
    txn_id text,
    txn_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(entity_id),
    FOREIGN KEY (parent_id) REFERENCES "transaction"(id)
);

CREATE TABLE return_item (
    entity_id text,
    return_entity_id text,
    "condition" text,
    order_item_id text,
    qty_approved text,
    qty_authorized text,
    qty_requested text,
    qty_returned text,
    reason text,
    resolution text,
    rma_entity_id text,
    "status" text,
    PRIMARY KEY (entity_id, return_entity_id),
    FOREIGN KEY (return_entity_id) REFERENCES "return"(entity_id)
);

CREATE TABLE return_comment (
    entity_id text,
    return_entity_id text,
    "admin" text,
    "comment" text,
    created_at text,
    customer_notified text,
    rma_entity_id text,
    visible_on_front text,
    -- custom_* (dynamic column),
    PRIMARY KEY (entity_id, return_entity_id),
    FOREIGN KEY (return_entity_id) REFERENCES "return"(entity_id)
);

CREATE TABLE return_track (
    entity_id text,
    return_entity_id text,
    carrier_code text,
    carrier_title text,
    qty_approved text,
    rma_entity_id text,
    track_number text,
    PRIMARY KEY (entity_id, return_entity_id),
    FOREIGN KEY (return_entity_id) REFERENCES "return"(entity_id)
);

CREATE TABLE "return" (
    entity_id text,
    customer_id text,
    order_id text,
    store_id text,
    customer_custom_email text,
    date_requested text,
    increment_id text,
    order_increment_id text,
    "status" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (entity_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (order_id) REFERENCES orders(entity_id),
    FOREIGN KEY (store_id) REFERENCES store(id)
);

CREATE TABLE customer_address (
    id text,
    customer_id text,
    country_id text,
    region_id text,
    city text,
    company text,
    default_billing text,
    default_shipping text,
    fax text,
    first_name text,
    last_name text,
    middle_name text,
    postcode text,
    prefix text,
    street text,
    suffix text,
    telephone text,
    vat_id text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (country_id) REFERENCES directory_country_available_region(directory_country_id),
    FOREIGN KEY (region_id) REFERENCES directory_country_available_region(id)
);

CREATE TABLE customer (
    id text,
    group_id text,
    store_id text,
    assistance_allowed text,
    company_attributes_company_id text,
    company_attributes_customer_id text,
    company_attributes_job_title text,
    company_attributes_status text,
    company_attributes_telephone text,
    confirmation text,
    created_at text,
    created_in text,
    default_billing text,
    default_shipping text,
    disable_auto_group_change text,
    dob text,
    email text,
    first_name text,
    gender text,
    is_subscribed text,
    last_name text,
    middle_name text,
    prefix text,
    suffix text,
    tax_vat text,
    updated_at text,
    website_id text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES customer_group(id),
    FOREIGN KEY (store_id) REFERENCES store(id)
);
