CREATE TABLE platform_margins_report (
    _fivetran_id text,
    company_account text,
    costs double precision,
    margin double precision,
    merchant_account text,
    "month" text,
    pricing_plan text,
    pricing_type text,
    product_or_service text,
    revenue double precision,
    statement_currency text,
    statement_number integer,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE exchange_rate_report (
    _fivetran_id text,
    base_currency text,
    currency_description text,
    exchange_rate double precision,
    exchange_rate_platform_settlement double precision,
    exponent integer,
    symbol text,
    target_currency text,
    valid_from timestamp,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE referral_list_report (
    _fivetran_id text,
    account_name text,
    active_account_name text,
    active_user_name text,
    begindate text,
    block boolean,
    enddate text,
    reason text,
    referral text,
    referral_type text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE threedsecure_authentication_report (
    _fivetran_id text,
    acquirer text,
    acquirer_response text,
    acs_challenge_mandated text,
    acs_operator_id text,
    acs_reference_number text,
    acs_trans_id text,
    acs_url text,
    amount double precision,
    ares_authentication_type text,
    authentication_mid text,
    authentication_only text,
    authorisation_mid text,
    avs_response text,
    bin text,
    card_holder_info text,
    challenge_cancel text,
    company text,
    creation_date text,
    currency text,
    cvc_response_code text,
    cvc_supplied text,
    data_only text,
    device_channel text,
    directory_server text,
    dstransid text,
    eci text,
    error_code text,
    error_component text,
    error_description text,
    error_detail text,
    error_message_type text,
    interaction_counter text,
    issuer_country_code text,
    issuer_name text,
    liability_shift text,
    merchant text,
    merchant_reference text,
    message_category text,
    metadata text,
    payment_method text,
    pspreference text,
    raw_acquirer_response text,
    recurring_processing_model text,
    results_status text,
    risk_score double precision,
    rreq_authentication_type text,
    sca_exemption_requested text,
    sca_retry text,
    shopper_country text,
    shopper_email text,
    shopper_interaction text,
    shopper_ip text,
    shopper_name text,
    shopper_reference text,
    three_ds_2_redirect text,
    three_dsversion text,
    threed_authentication_response text,
    threed_directory_response text,
    threeds_2_fallback text,
    threeds_2_fallback_directory_response text,
    threeds_completion_indicator text,
    threeds_requestor_challenge_indicator text,
    threeds_requestor_name text,
    threeds_server_transaction_id text,
    time_zone text,
    trans_status_reason text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE manual_review_report (
    _fivetran_id text,
    company_account text,
    manual_review_psp_reference text,
    merchant_account text,
    merchant_reference text,
    note text,
    payment_amount double precision,
    payment_currency text,
    payment_date text,
    payment_date_time_zone text,
    payment_method text,
    psp_reference text,
    reason text,
    record_date text,
    record_date_time_zone text,
    record_type text,
    risk_scoring double precision,
    shopper_email text,
    shopper_reference text,
    user_name text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE payments_accounting_report (
    _fivetran_id text,
    acquirer text,
    acquirer_account text,
    acquirer_auth_code text,
    acquirer_reference text,
    advanced_pc double precision,
    advancement_batch text,
    advancement_code text,
    advancement_fee_percentage text,
    arn text,
    authorised_pc double precision,
    booking_date text,
    booking_date_ams text,
    booking_type text,
    captured_pc double precision,
    card_number text,
    commission_sc double precision,
    company_account text,
    creation_date text,
    creation_date_ams text,
    dcc_markup_sc double precision,
    exchange_rate double precision,
    funding_source text,
    global_card_brand text,
    gratuity_amount double precision,
    icsf_details text,
    installments text,
    installments_pc double precision,
    interchange_sc double precision,
    issuer_country text,
    issuer_name text,
    main_amount double precision,
    main_currency text,
    markup_sc double precision,
    merchant_account text,
    merchant_order_reference text,
    merchant_reference text,
    metadata text,
    mid text,
    modification_merchant_reference text,
    modification_psp_reference text,
    network_token_available text,
    network_token_used text,
    original_amount double precision,
    payable_batch integer,
    payable_sc double precision,
    payment_account_reference text,
    payment_currency text,
    payment_method text,
    payment_method_variant text,
    payment_requester_type text,
    payout_date text,
    processing_fee_currency text,
    processing_fee_fc double precision,
    psp_reference text,
    received_pc double precision,
    record_type text,
    risk_premium boolean,
    scheme_fees_sc double precision,
    settlement_currency text,
    shopper_country text,
    shopper_name text,
    shopper_reference text,
    split_payment_data text,
    store text,
    surcharge_amount double precision,
    tender_reference text,
    time_zone text,
    unique_terminal_id text,
    user_name text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE pos_authorized_amount (
    _fivetran_id text,
    authorized_amount double precision,
    currency text,
    store_id text,
    terminal_country text,
    terminal_model text,
    transaction_count integer,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE threedsecure_conversion_report (
    _fivetran_id text,
    acquirer text,
    acquirer_response text,
    amount double precision,
    avs_response text,
    bin text,
    company text,
    creation_date text,
    currency text,
    cvc_response_code text,
    cvc_supplied text,
    merchant text,
    merchant_reference text,
    metadata text,
    payment_method text,
    pspreference text,
    raw_acquirer_response text,
    risk_score double precision,
    sent_for_auth integer,
    shopper_country text,
    shopper_email text,
    shopper_interaction text,
    shopper_ip text,
    shopper_name text,
    three_dsversion text,
    threed_2_ares_transstatus text,
    threed_2_rreq_transstatus text,
    threed_authentication_response text,
    threed_directory_response text,
    time_zone text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE received_payments_report (
    _fivetran_id text,
    a_res_trans_status text,
    acquirer text,
    acquirer_account text,
    acquirer_reference text,
    acquirer_response text,
    airlinedata text,
    alternative_acquirer_reference text,
    amount double precision,
    authorisation_code text,
    avs_response text,
    bcmc_iban_or_bic text,
    billing_city text,
    billing_country text,
    billing_house_number_or_name text,
    billing_postal_code_or_zip text,
    billing_state_or_province text,
    billing_street text,
    bin_funding_source text,
    browser text,
    card_number text,
    cash_register_name text,
    cashback_amount double precision,
    company_account text,
    creation_date text,
    currency text,
    cvc_2_response text,
    cvm_performed text,
    dcc text,
    delivery_city text,
    delivery_country text,
    delivery_house_number_or_name text,
    delivery_postal_code_or_zip text,
    delivery_state_or_province text,
    delivery_street text,
    device text,
    device_fingerprint text,
    global_card_brand text,
    installments text,
    issuer_city text,
    issuer_country text,
    issuer_id text,
    issuer_name text,
    liability_shift boolean,
    library_implementation text,
    library_version text,
    mcc text,
    merchant_account text,
    merchant_order_reference text,
    merchant_reference text,
    metadata text,
    network_token_available text,
    network_token_used text,
    network_transaction_reference text,
    original_amount double precision,
    original_card_bin text,
    payment_device text,
    payment_method text,
    payment_method_variant text,
    payment_requester_type text,
    pos_cashback_amount double precision,
    pos_charity_amount double precision,
    pos_discount_amount double precision,
    pos_entry_mode text,
    pos_gratuity_amount double precision,
    pos_store_and_forward_indicator boolean,
    pos_tender_reference text,
    pos_transaction_date text,
    psp_reference text,
    r_req_trans_status text,
    raw_acquirer_response text,
    realtime_account_updater_status text,
    recurring_detail_reference text,
    retry_json text,
    risk_profile text,
    risk_profile_id integer,
    risk_profile_reference text,
    risk_scoring double precision,
    shopper_country text,
    shopper_email text,
    shopper_interaction text,
    shopper_ip text,
    shopper_name text,
    shopper_pan text,
    shopper_phone_number text,
    shopper_reference text,
    split_payment_data text,
    store text,
    surcharge_amount double precision,
    terminal_app_version text,
    three_dauthentication_response text,
    three_ddirectory_response text,
    three_dsversion text,
    time_zone text,
    "type" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE tap_to_pay_on_iphone (
    _fivetran_id text,
    authorized_amount double precision,
    country text,
    currency text,
    store_id text,
    transaction_count integer,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE dispute_report (
    _fivetran_id text,
    acquirer text,
    acquirer_account text,
    avs_response text,
    bic text,
    capture_acquirer_reference text,
    capture_modification_merchant_reference text,
    cb_reason_code text,
    cb_scheme_code text,
    company_account text,
    cvc_2_response text,
    data_ed text,
    dispute_amount double precision,
    dispute_arn text,
    dispute_auto_defended boolean,
    dispute_currency text,
    dispute_date text,
    dispute_date_time_zone text,
    dispute_end_date text,
    dispute_end_date_time_zone text,
    dispute_psp_reference text,
    dispute_reason text,
    global_card_brand text,
    gross_amount double precision,
    iban text,
    issuer_bin text,
    issuer_country text,
    issuer_id text,
    issuer_name text,
    issuer_region_program text,
    liability_shift boolean,
    merchant_account text,
    merchant_reference text,
    merchant_store_code text,
    metadata text,
    no_freason_code text,
    no_fscheme_code text,
    payment_amount double precision,
    payment_currency text,
    payment_date text,
    payment_date_time_zone text,
    payment_method text,
    psp_reference text,
    rdr boolean,
    record_date text,
    record_date_time_zone text,
    record_type text,
    rfi_reason_code text,
    rfi_scheme_code text,
    risk_scoring double precision,
    second_chargeback boolean,
    shopper_country text,
    shopper_email text,
    shopper_interaction text,
    shopper_ip text,
    shopper_name text,
    shopper_pan text,
    shopper_phone_number text,
    shopper_reference text,
    shopper_statement text,
    "status" text,
    three_dauthentication_response text,
    three_ddirectory_response text,
    user_name text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE external_settlement_detail_report (
    _fivetran_id text,
    acquirer text,
    acquirer_auth_code text,
    acquirer_reference text,
    arn text,
    card_bin text,
    card_number_summary text,
    commission_nc double precision,
    company_account text,
    creation_date text,
    exchange_rate double precision,
    gross_credit_gc double precision,
    gross_currency text,
    gross_debit_gc double precision,
    interchange_nc double precision,
    markup_nc double precision,
    merchant_account text,
    merchant_order_reference text,
    merchant_reference text,
    metadata text,
    mid text,
    modification_merchant_reference text,
    modification_reference text,
    net_credit_nc double precision,
    net_currency text,
    net_debit_nc double precision,
    payment_method text,
    payment_method_variant text,
    psp_reference text,
    scheme_fees_nc double precision,
    store_code text,
    submerchant_identifier text,
    time_zone text,
    "type" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE settlement_detail_report (
    _fivetran_id text,
    acquirer text,
    additional_type text,
    advanced_nc double precision,
    advancement_batch text,
    advancement_code text,
    arn text,
    authorisation_code text,
    authorised_date text,
    authorised_date_time_zone text,
    balance_currency text,
    balance_platform_credit double precision,
    balance_platform_debit double precision,
    batch_number integer,
    booking_date text,
    booking_date_ams text,
    booking_date_time_zone text,
    booking_type text,
    card_number text,
    clearing_network text,
    commission_nc double precision,
    company_account text,
    creation_date text,
    creation_date_ams text,
    dcc_markup_nc double precision,
    dispute_reference text,
    exchange_rate double precision,
    funds_destination text,
    global_card_brand text,
    gratuity_amount double precision,
    gross_credit_gc double precision,
    gross_currency text,
    gross_debit_gc double precision,
    installments text,
    interchange_nc double precision,
    issuer_country text,
    markup_nc double precision,
    merchant_account text,
    merchant_order_reference text,
    merchant_reference text,
    metadata text,
    modification_merchant_reference text,
    modification_reference text,
    net_credit_bc double precision,
    net_credit_nc double precision,
    net_currency text,
    net_debit_bc double precision,
    net_debit_nc double precision,
    payment_fees_nc double precision,
    payment_method text,
    payment_method_variant text,
    payment_transaction_group text,
    pos_transaction_date text,
    pos_transaction_date_time_zone text,
    psp_reference text,
    scheme_fees_nc double precision,
    settlement_flow text,
    shopper_country text,
    shopper_reference text,
    split_payment_data text,
    split_settlement text,
    store text,
    surcharge_amount double precision,
    tender_reference text,
    terminal_id text,
    time_zone text,
    "type" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE accountconfig_report (
    _fivetran_id text,
    acquirer_account_name text,
    acquirer_name text,
    company_account_name text,
    merchant_account_capture_delay text,
    merchant_account_merchant_name text,
    merchant_account_name text,
    merchant_account_status text,
    payment_method_action_code text,
    payment_method_active text,
    payment_method_allowed_application_id text,
    payment_method_allowed_cvmlimit text,
    payment_method_allowed_posentry_mode text,
    payment_method_authorisation_type text,
    payment_method_available_countries text,
    payment_method_currency_codes text,
    payment_method_custom_routing_flag text,
    payment_method_installments text,
    payment_method_issuer_country_codes text,
    payment_method_max_delivery text,
    payment_method_merchant_category_code integer,
    payment_method_merchant_category_code_override_configuration integer,
    payment_method_merchant_name text,
    payment_method_midnumber text,
    payment_method_min_delivery text,
    payment_method_priority integer,
    payment_method_routing_binconfig_name text,
    payment_method_settlement_type text,
    payment_method_shopper_interaction text,
    payment_method_type text,
    payment_method_weight integer,
    store_code text,
    store_description text,
    store_status text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE non_transactional_scheme_fees_report (
    _fivetran_id text,
    acquirer text,
    billing_month text,
    company text,
    currency_code text,
    details text,
    fee_amount text,
    fee_end_date text,
    fee_name text,
    fee_start_date text,
    frequency text,
    merchant text,
    scheme text,
    PRIMARY KEY (_fivetran_id)
);
