CREATE TABLE domain (
    id text,
    created text,
    customer_id text,
    domain text,
    estatus text,
    redirect text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE answer_value (
    answers_value text,
    rule_id text,
    PRIMARY KEY (answers_value, rule_id),
    FOREIGN KEY (rule_id) REFERENCES rule(id)
);

CREATE TABLE rule (
    id text,
    groups_id text,
    answers_type text,
    input_value text,
    next_operator text,
    operator text,
    rule_percentage text,
    PRIMARY KEY (id, groups_id),
    FOREIGN KEY (groups_id) REFERENCES groups(id)
);

CREATE TABLE groups (
    id text,
    quota_id text,
    PRIMARY KEY (id, quota_id),
    FOREIGN KEY (quota_id) REFERENCES quota(id)
);

CREATE TABLE quota (
    id text,
    survey_id text,
    description text,
    distributed text,
    limits text,
    "name" text,
    responses text,
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE survey_campaign_email_message (
    id text,
    survey_campaign_id text,
    survey_id text,
    body_html text,
    body_text text,
    date_created text,
    date_modified text,
    disable_styles text,
    embed_question text,
    footer text,
    from_email text,
    from_name text,
    invite_identity text,
    medium text,
    message_type text,
    "status" text,
    subject text,
    subtype text,
    PRIMARY KEY (id, survey_campaign_id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE user_data (
    id text,
    account_user_id text,
    description text,
    "name" text,
    "value" text,
    PRIMARY KEY (id, account_user_id),
    FOREIGN KEY (account_user_id) REFERENCES account_user(id)
);

CREATE TABLE account_user (
    id text,
    "admin" text,
    default_team text,
    email text,
    last_login text,
    license text,
    phone_support text,
    "status" text,
    username text,
    PRIMARY KEY (id)
);

CREATE TABLE account (
    id text,
    contact_phone text,
    date_created text,
    login_link text,
    organization text,
    reseller text,
    reseller_uuid text,
    resellers_customer_id text,
    sso jsonb,
    PRIMARY KEY (id)
);

CREATE TABLE survey_contact (
    id text,
    survey_campaign_id text,
    survey_id text,
    business_phone text,
    customfield_1 text,
    customfield_10 text,
    customfield_2 text,
    customfield_3 text,
    customfield_4 text,
    customfield_5 text,
    customfield_6 text,
    customfield_7 text,
    customfield_8 text,
    customfield_9 text,
    date_last_sent text,
    department text,
    division text,
    email_address text,
    fax_phone text,
    first_name text,
    groups text,
    home_phone text,
    last_name text,
    mailing_address text,
    mailing_address_2 text,
    mailing_address_city text,
    mailing_address_country text,
    mailing_address_postal text,
    mailing_address_state text,
    mobilephone text,
    organization text,
    "role" text,
    "status" text,
    subscriber_status text,
    team text,
    test text,
    test_2 text,
    test_3 text,
    test_4 text,
    test_5 text,
    title text,
    url text,
    PRIMARY KEY (id, survey_campaign_id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE survey_report (
    _fivetran_id text,
    survey_id text,
    id text,
    last_run text,
    "name" text,
    publish_link text,
    responses text,
    "status" text,
    "type" text,
    version text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE survey_campaign (
    _fivetran_id text,
    survey_id text,
    close_message text,
    date_created text,
    date_modified text,
    id text,
    invite_id text,
    languages text,
    limit_responses text,
    link_close_date text,
    link_open_date text,
    link_type text,
    "name" text,
    primary_theme_content text,
    primary_theme_options text,
    ssl text,
    "status" text,
    sub_type text,
    token_variables text,
    "type" text,
    uri text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE survey_data (
    id text,
    survey_id text,
    survey_response_id text,
    answer text,
    answer_id text,
    options jsonb,
    original_answer text,
    question text,
    section_id text,
    shown text,
    subquestions jsonb,
    "type" text,
    PRIMARY KEY (id, survey_id, survey_response_id),
    FOREIGN KEY (survey_id) REFERENCES survey_response(survey_id),
    FOREIGN KEY (survey_response_id) REFERENCES survey_response(id)
);

CREATE TABLE survey_response (
    id text,
    survey_id text,
    city text,
    comments text,
    contact_id text,
    country text,
    data_quality jsonb,
    date_started text,
    date_submitted text,
    dma text,
    ip_address text,
    is_test_data text,
    languages text,
    latitude text,
    link_id text,
    longitude text,
    postal text,
    referer text,
    region text,
    response_time text,
    session_id text,
    "status" text,
    url_variables jsonb,
    user_agent text,
    PRIMARY KEY (id, survey_id)
);

CREATE TABLE account_team (
    id text,
    default_role text,
    description text,
    "status" text,
    team_name text,
    PRIMARY KEY (id)
);

CREATE TABLE survey_theme (
    id text,
    accent text,
    accent_checked text,
    accent_text text,
    accent_text_checked text,
    auto_mobile text,
    auto_mobile_checked text,
    back_button text,
    back_button_checked text,
    background_grad_orient text,
    background_grad_orient_checked text,
    background_gradient text,
    background_image text,
    background_image_style text,
    background_image_style_checked text,
    base_font_color text,
    base_font_color_checked text,
    base_font_family text,
    base_font_family_checked text,
    base_font_size text,
    base_font_size_checked text,
    base_font_weight text,
    base_font_weight_checked text,
    base_web_font_name text,
    base_web_font_url text,
    body text,
    body_background_color text,
    body_background_color_checked text,
    body_background_opacity text,
    body_background_opacity_checked text,
    column_width text,
    comment_width text,
    created text,
    css text,
    custom_head text,
    custom_head_checked text,
    header_background_color text,
    header_background_color_checked text,
    header_background_opacity text,
    header_background_opacity_checked text,
    header_image_url text,
    header_image_url_checked text,
    header_text_color text,
    header_text_color_checked text,
    image_align text,
    image_align_checked text,
    img_width text,
    img_width_checked text,
    img_width_max text,
    img_width_max_checked text,
    "name" text,
    page_background_color text,
    page_background_color_checked text,
    page_background_opacity text,
    page_description text,
    page_description_checked text,
    page_title text,
    page_title_align text,
    page_title_align_checked text,
    page_title_checked text,
    page_top_margin text,
    page_width text,
    page_width_checked text,
    page_width_number text,
    page_width_number_checked text,
    page_width_unit text,
    page_width_unit_checked text,
    powered_by text,
    powered_by_checked text,
    progress_bar text,
    progress_bar_checked text,
    question_border text,
    question_border_checked text,
    question_number text,
    question_number_checked text,
    question_title text,
    question_title_checked text,
    replace_icons text,
    replace_icons_checked text,
    required_ast text,
    required_ast_checked text,
    so_masthead_image_show text,
    so_masthead_image_show_checked text,
    "status" text,
    style_mode text,
    survey_round_corner_number text,
    survey_round_corner_number_checked text,
    survey_title text,
    survey_title_checked text,
    survey_width text,
    survey_width_checked text,
    survey_width_number text,
    survey_width_number_checked text,
    survey_width_unit text,
    survey_width_unit_checked text,
    table_header_width text,
    theme_id text,
    theme_upgraded text,
    theme_version text,
    theme_version_checked text,
    title_align text,
    title_align_checked text,
    title_font_family text,
    title_font_family_checked text,
    title_font_size text,
    title_font_size_checked text,
    title_font_weight text,
    title_font_weight_checked text,
    title_web_font_name text,
    title_web_font_url text,
    PRIMARY KEY (id)
);

CREATE TABLE breakdown (
    _fivetran_id text,
    survey_statistic_id text,
    count text,
    label text,
    percentage text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (survey_statistic_id) REFERENCES survey_statistic(id)
);

CREATE TABLE survey_statistic (
    id text,
    survey_id text,
    average text,
    max text,
    min text,
    std_dev text,
    sum text,
    total_responses text,
    "type" text,
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE contact_custom_field (
    id text,
    "name" text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE survey (
    id text,
    created_on text,
    links_default text,
    links_edit text,
    links_publish text,
    modified_on text,
    statistics_complete text,
    "status" text,
    team text,
    title text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE sso_attribute (
    attribute text,
    sso_id text,
    PRIMARY KEY (attribute, sso_id),
    FOREIGN KEY (sso_id) REFERENCES sso(id)
);

CREATE TABLE sso (
    id text,
    cert_domain text,
    cert_fingerprint text,
    creat_users text,
    created text,
    customer_id text,
    d_modified text,
    deleted text,
    disable_users text,
    email_notification text,
    entity_id text,
    force_sso_login text,
    i_user_id_created text,
    login text,
    logout text,
    "name" text,
    sp_login text,
    sp_metadata text,
    "status" text,
    "type" text,
    user_last_modified text,
    user_license text,
    user_role text,
    user_solo text,
    user_team text,
    weeks_to_disable text,
    PRIMARY KEY (id)
);

CREATE TABLE "option" (
    id text,
    question_id text,
    survey_id text,
    survey_page_id text,
    properties_all text,
    properties_checked text,
    properties_dependent text,
    properties_disabled text,
    properties_fixed text,
    properties_na text,
    properties_none text,
    properties_other text,
    properties_other_required text,
    properties_show_rules jsonb,
    title_english text,
    "value" text,
    PRIMARY KEY (id, question_id, survey_id, survey_page_id),
    FOREIGN KEY (question_id) REFERENCES question(id),
    FOREIGN KEY (survey_id) REFERENCES question(survey_id),
    FOREIGN KEY (survey_page_id) REFERENCES question(survey_page_id)
);

CREATE TABLE sub_question_option (
    id text,
    question_id text,
    sub_question_index text,
    survey_id text,
    survey_page_id text,
    properties_all text,
    properties_checked text,
    properties_dependent text,
    properties_disabled text,
    properties_fixed text,
    properties_na text,
    properties_none text,
    properties_other text,
    properties_other_required text,
    properties_show_rules jsonb,
    title_english text,
    "value" text,
    PRIMARY KEY (id, question_id, sub_question_index, survey_id, survey_page_id),
    FOREIGN KEY (question_id) REFERENCES sub_question(question_id),
    FOREIGN KEY (sub_question_index) REFERENCES sub_question("index"),
    FOREIGN KEY (survey_id) REFERENCES sub_question(survey_id),
    FOREIGN KEY (survey_page_id) REFERENCES sub_question(survey_page_id)
);

CREATE TABLE sub_question (
    "index" text,
    question_id text,
    survey_id text,
    survey_page_id text,
    base_type text,
    "comment" text,
    description jsonb,
    has_showhide_deps text,
    id text,
    properties_hidden text,
    properties_minimum_response text,
    properties_required text,
    shortname text,
    title_english text,
    "type" text,
    varname jsonb,
    PRIMARY KEY ("index", question_id, survey_id, survey_page_id),
    FOREIGN KEY (question_id) REFERENCES question(id),
    FOREIGN KEY (survey_id) REFERENCES question(survey_id),
    FOREIGN KEY (survey_page_id) REFERENCES question(survey_page_id)
);

CREATE TABLE question (
    id text,
    survey_id text,
    survey_page_id text,
    base_type text,
    break_after text,
    center_label jsonb,
    "comment" text,
    conjoint_best_label jsonb,
    conjoint_card_label jsonb,
    conjoint_error_label jsonb,
    conjoint_none_label jsonb,
    conjoint_worst_label jsonb,
    custom_css text,
    description jsonb,
    disabled text,
    exclude_number text,
    force_currency text,
    force_numeric text,
    force_percent text,
    has_showhide_deps text,
    hidden text,
    hide_after_response text,
    inputmask jsonb,
    l_extreme_label jsonb,
    labels_right text,
    left_label jsonb,
    limits text,
    map_key text,
    max_number text,
    maxdiff_attribute_label jsonb,
    maxdiff_best_label jsonb,
    maxdiff_of jsonb,
    maxdiff_sets_message jsonb,
    maxdiff_worst_label jsonb,
    min_answers_per_row text,
    min_number text,
    minimum_response text,
    na_text_english text,
    only_whole_num text,
    option_sort text,
    orientation text,
    question_description_above text,
    question_description_english text,
    r_extreme_label jsonb,
    required text,
    right_label jsonb,
    shortname text,
    show_title text,
    soft_required text,
    subtype text,
    th_content jsonb,
    title_english text,
    "type" text,
    url text,
    varname jsonb,
    PRIMARY KEY (id, survey_id, survey_page_id),
    FOREIGN KEY (survey_id) REFERENCES survey_page(survey_id),
    FOREIGN KEY (survey_page_id) REFERENCES survey_page(id)
);

CREATE TABLE survey_page (
    id text,
    survey_id text,
    description jsonb,
    properties_hidden text,
    properties_piped_from text,
    title_english text,
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE contact_list (
    id text,
    date_created text,
    date_modifed text,
    list_name text,
    user_id_created text,
    user_id_modified text,
    PRIMARY KEY (id)
);

CREATE TABLE contact_list_contact (
    id text,
    contact_list_id text,
    business_phone text,
    department text,
    division text,
    email_address text,
    fax_phone text,
    first_name text,
    groups text,
    home_phone text,
    is_manager text,
    last_name text,
    mailing_address text,
    mailing_address_2 text,
    mailing_address_city text,
    mailing_address_country text,
    mailing_address_postal text,
    mailing_address_state text,
    organization text,
    "role" text,
    "status" text,
    team text,
    title text,
    url text,
    PRIMARY KEY (id, contact_list_id),
    FOREIGN KEY (contact_list_id) REFERENCES contact_list(id)
);
