CREATE TABLE performance_report_by_campaign (
    _fivetran_id text,
    advertiser_id text,
    advertiser_name text,
    attributed_add_to_cart_clicks_14_d text,
    attributed_detail_page_views_clicks_14_d text,
    attributed_purchases_14_d text,
    attributed_sales_14_d text,
    attributed_total_add_to_cart_clicks_14_d text,
    attributed_total_detail_page_views_clicks_14_d text,
    attributed_total_purchases_14_d text,
    brb_bonus_amount text,
    campaign_id text,
    click_throughs text,
    "date" text,
    kindle_edition_normalized_pages_read_14_d text,
    kindle_edition_normalized_pages_royalties_14_d text,
    total_attributed_sales_14_d text,
    total_units_sold_14_d text,
    units_sold_14_d text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE performance_report_by_adgroup (
    _fivetran_id text,
    ad_group_id text,
    advertiser_id text,
    campaign_id text,
    advertiser_name text,
    attributed_add_to_cart_clicks_14_d text,
    attributed_detail_page_views_clicks_14_d text,
    attributed_purchases_14_d text,
    attributed_sales_14_d text,
    attributed_total_add_to_cart_clicks_14_d text,
    attributed_total_detail_page_views_clicks_14_d text,
    attributed_total_purchases_14_d text,
    brb_bonus_amount text,
    click_throughs text,
    "date" text,
    kindle_edition_normalized_pages_read_14_d text,
    kindle_edition_normalized_pages_royalties_14_d text,
    publisher text,
    total_attributed_sales_14_d text,
    total_units_sold_14_d text,
    units_sold_14_d text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (ad_group_id) REFERENCES performance_report_by_creative(ad_group_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES performance_report_by_campaign(campaign_id)
);

CREATE TABLE product_report (
    _fivetran_id text,
    ad_group_id text,
    advertiser_id text,
    campaign_id text,
    advertiser_name text,
    attributed_add_to_cart_clicks_14_d text,
    attributed_detail_page_views_clicks_14_d text,
    attributed_new_to_brand_purchases_14_d text,
    attributed_new_to_brand_sales_14_d text,
    attributed_new_to_brand_units_sold_14_d text,
    attributed_purchases_14_d text,
    attributed_sales_14_d text,
    brand_halo_attributed_add_to_cart_clicks_14_d text,
    brand_halo_attributed_purchases_14_d text,
    brand_halo_attributed_sales_14_d text,
    brand_halo_detail_page_views_clicks_14_d text,
    brand_halo_new_to_brand_purchases_14_d text,
    brand_halo_new_to_brand_sales_14_d text,
    brand_halo_new_to_brand_units_sold_14_d text,
    brand_halo_units_sold_14_d text,
    brand_name text,
    "date" text,
    kindle_edition_normalized_pages_read_14_d text,
    kindle_edition_normalized_pages_royalties_14_d text,
    marketplace text,
    product_asin text,
    product_category text,
    product_conversion_type text,
    product_group text,
    product_name text,
    product_subcategory text,
    publisher text,
    units_sold_14_d text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (ad_group_id) REFERENCES performance_report_by_adgroup(ad_group_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES performance_report_by_campaign(campaign_id)
);

CREATE TABLE profile (
    id text,
    account_id text,
    account_marketplace_string_id text,
    account_name text,
    account_type text,
    account_valid_payment_method text,
    country_code text,
    currency_code text,
    daily_budget text,
    timezone text,
    PRIMARY KEY (id)
);

CREATE TABLE advertiser (
    id text,
    profile_id text,
    advertiser_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (profile_id) REFERENCES profile(id)
);

CREATE TABLE performance_report_by_creative (
    _fivetran_id text,
    advertiser_id text,
    campaign_id text,
    ad_group_id text,
    advertiser_name text,
    attributed_add_to_cart_clicks_14_d text,
    attributed_detail_page_views_clicks_14_d text,
    attributed_purchases_14_d text,
    attributed_sales_14_d text,
    attributed_total_add_to_cart_clicks_14_d text,
    attributed_total_detail_page_views_clicks_14_d text,
    attributed_total_purchases_14_d text,
    click_throughs text,
    creative_id text,
    "date" text,
    kindle_edition_normalized_pages_read_14_d text,
    kindle_edition_normalized_pages_royalties_14_d text,
    publisher text,
    total_attributed_sales_14_d text,
    total_units_sold_14_d text,
    units_sold_14_d text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES performance_report_by_campaign(campaign_id)
);
