CREATE TABLE event (
    device_id text,
    id bigint,
    server_upload_time timestamp,
    event_type_id bigint,
    _insert_id text,
    ad_id text,
    amplitude_event_type text,
    amplitude_id bigint,
    app text,
    city text,
    client_event_time timestamp,
    client_upload_time timestamp,
    country text,
    data jsonb,
    device_brand text,
    device_carrier text,
    device_family text,
    device_manufacturer text,
    device_model text,
    device_type text,
    dma text,
    event_properties jsonb,
    event_time timestamp,
    event_type text,
    group_properties jsonb,
    groups jsonb,
    idfa text,
    ip_address text,
    is_attribution_event boolean,
    language text,
    library text,
    location_lat text,
    location_lng text,
    os_name text,
    os_version text,
    paying boolean,
    platform text,
    processed_time timestamp,
    project_name text,
    region text,
    sample_rate integer,
    "schema" integer,
    server_received_time timestamp,
    session_id bigint,
    start_version text,
    user_creation_time timestamp,
    user_id text,
    user_properties jsonb,
    uuid text,
    version_name text,
    PRIMARY KEY (device_id, id, server_upload_time),
    FOREIGN KEY (event_type_id) REFERENCES event_type(id)
);

CREATE TABLE event_type (
    id bigint,
    project_name text,
    autohidden boolean,
    deleted boolean,
    display text,
    flow_hidden boolean,
    hidden boolean,
    in_waitroom boolean,
    "name" text,
    non_active boolean,
    timeline_hidden boolean,
    totals integer,
    totals_delta bigint,
    "value" text,
    waitroom_approved text,
    PRIMARY KEY (id, project_name)
);

CREATE TABLE event_amplitude_attribution_id (
    amplitude_attribution_id text,
    device_id text,
    event_id bigint,
    server_upload_time timestamp,
    client_event_time timestamp,
    PRIMARY KEY (amplitude_attribution_id, device_id, event_id, server_upload_time),
    FOREIGN KEY (device_id) REFERENCES event(device_id),
    FOREIGN KEY (event_id) REFERENCES event(device_id),
    FOREIGN KEY (server_upload_time) REFERENCES event(device_id)
);
