CREATE TABLE advertiser_report (
    _fivetran_id text,
    age text,
    app_name text,
    campaign_id text,
    campaign_name text,
    campaign_segment_id text,
    campaign_segment_name text,
    city text,
    clicks text,
    completions text,
    cost_model text,
    country text,
    "day" text,
    device_manufacturer text,
    device_model text,
    gender text,
    impressions text,
    installs text,
    languages text,
    launches text,
    os text,
    package_name text,
    publisher_id text,
    publisher_name text,
    sim_operator text,
    spend text,
    "state" text,
    PRIMARY KEY (_fivetran_id)
);
