CREATE TABLE event (
    event_id text,
    additional_event_data jsonb,
    api_version text,
    aws_region text,
    baseline_average double precision,
    error_code text,
    error_message text,
    event_category text,
    event_name text,
    event_source text,
    event_time timestamp,
    event_type text,
    event_version text,
    hash_raw bigint,
    insight_average double precision,
    insight_duration integer,
    insight_type text,
    raw jsonb,
    read_only boolean,
    recipient_account_id text,
    request_id text,
    request_parameters jsonb,
    resources jsonb,
    service_event_details jsonb,
    shared_event_id text,
    source_ip_address text,
    "state" text,
    user_agent text,
    vpc_endpoint_id text,
    -- user_identity_* (dynamic column),
    PRIMARY KEY (event_id)
);
