CREATE TABLE review_client_response (
    "index" text,
    review_id text,
    "date" text,
    department text,
    "name" text,
    response text,
    "source" text,
    source_client_name text,
    "type" text,
    PRIMARY KEY ("index", review_id),
    FOREIGN KEY (review_id) REFERENCES review(id)
);

CREATE TABLE review (
    id text,
    product_id text,
    additional_fields jsonb,
    additional_fields_order jsonb,
    author_id text,
    badges jsonb,
    badges_order jsonb,
    campaign_id text,
    cid text,
    comment_ids jsonb,
    cons text,
    content_locale text,
    context_data_values jsonb,
    context_data_values_order jsonb,
    helpfulness text,
    inappropriate_feedback_list jsonb,
    is_featured text,
    is_ratings_only text,
    is_recommended text,
    is_syndicated text,
    last_moderated_time text,
    last_modification_time timestamp,
    moderation_status text,
    original_product_name text,
    photos jsonb,
    product_recommendation_ids text,
    pros text,
    rating text,
    rating_range text,
    review_text text,
    secondary_ratings jsonb,
    secondary_ratings_order jsonb,
    source_client text,
    submission_id text,
    submission_time text,
    tag_dimensions jsonb,
    tag_dimensions_order jsonb,
    title text,
    total_client_response_count text,
    total_comment_count text,
    total_feedback_count text,
    total_inappropriate_feedback_count text,
    total_negative_feedback_count text,
    total_positive_feedback_count text,
    user_location text,
    user_nickname text,
    videos jsonb,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    category_id text,
    active text,
    attributes jsonb,
    attributes_order jsonb,
    brand jsonb,
    brand_external_id jsonb,
    description text,
    disabled text,
    eans jsonb,
    family_ids jsonb,
    image_url text,
    isbns jsonb,
    manufacturer_part_numbers jsonb,
    model_numbers jsonb,
    "name" text,
    product_page_url jsonb,
    question_ids jsonb,
    story_ids jsonb,
    upcs jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES product_category(id)
);

CREATE TABLE product_category (
    id text,
    active text,
    attributes jsonb,
    attributes_order jsonb,
    category_page_url text,
    disabled text,
    image_url text,
    "name" text,
    parent_id text,
    product_ids jsonb,
    question_ids jsonb,
    story_ids jsonb,
    PRIMARY KEY (id)
);
