CREATE TABLE call_tag (
    id text,
    call_id text,
    color_code text,
    "name" text,
    PRIMARY KEY (id, call_id),
    FOREIGN KEY (call_id) REFERENCES "call"(id)
);

CREATE TABLE "call" (
    id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    agenda text,
    calendar_booking_call text,
    caller_id text,
    created_time text,
    currency_symbol text,
    description text,
    dialled_number text,
    duration text,
    duration_in_seconds text,
    editable text,
    field_states text,
    followed text,
    followers text,
    modified_time timestamp,
    reminder text,
    se_module text,
    sharing_permission text,
    start_time text,
    "status" text,
    subject text,
    telephony_call text,
    "type" text,
    what_id text,
    what_id_name text,
    who_id text,
    who_id_name text,
    zia_visions text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE contact_tag (
    id text,
    contact_id text,
    color_code text,
    "name" text,
    PRIMARY KEY (id, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id)
);

CREATE TABLE contact (
    id text,
    account_id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    approval_state text,
    created_time text,
    currency_symbol text,
    date_of_birth text,
    department text,
    description text,
    editable text,
    email text,
    email_opt_out text,
    field_states text,
    first_name text,
    followed text,
    followers text,
    full_name text,
    home_phone text,
    last_activity_time text,
    last_name text,
    locked_for_me text,
    mailing_city text,
    mailing_country text,
    mailing_state text,
    mailing_street text,
    mailing_zip text,
    mobile text,
    modified_time timestamp,
    phone text,
    record_image text,
    reporting_to_id text,
    reporting_to_name text,
    "role" text,
    sharing_permission text,
    title text,
    unsubscribed_mode text,
    unsubscribed_time text,
    zia_owner_assignment text,
    zia_visions text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE task_tag (
    id text,
    task_id text,
    color_code text,
    "name" text,
    PRIMARY KEY (id, task_id),
    FOREIGN KEY (task_id) REFERENCES task(id)
);

CREATE TABLE task (
    id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    related_to_id text,
    approval_state text,
    closed_time text,
    contact text,
    created_time text,
    currency_symbol text,
    description text,
    due_date text,
    editable text,
    field_states text,
    followed text,
    followers text,
    locked_for_me text,
    modified_time timestamp,
    priority text,
    recurring_activity text,
    related_module text,
    remind_at text,
    sharing_permission text,
    "status" text,
    subject text,
    u_id text,
    zia_owner_assignment text,
    zia_visions text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (related_to_id) REFERENCES account(id)
);

CREATE TABLE event_tag (
    id text,
    event_id text,
    color_code text,
    "name" text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_participant (
    id text,
    event_id text,
    email text,
    invited text,
    "name" text,
    number text,
    "status" text,
    "type" text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    related_to_id text,
    all_day text,
    approval_state text,
    calendar_booking_event text,
    cancelled text,
    check_in_time text,
    colour_code text,
    created_time text,
    currency_symbol text,
    description text,
    editable text,
    end_date_time text,
    field_states text,
    followed text,
    followers text,
    meeting_details text,
    modified_time timestamp,
    recurrence_id text,
    recurring_activity text,
    related_module text,
    remind_at text,
    send_notification text,
    sharing_permission text,
    start_date_time text,
    title text,
    u_id text,
    venue text,
    zia_visions text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (related_to_id) REFERENCES account(id)
);

CREATE TABLE account_tag (
    id text,
    account_id text,
    color_code text,
    "name" text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account_partner_type (
    "index" text,
    account_id text,
    "type" text,
    PRIMARY KEY ("index", account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    annual_revenue text,
    approval_state text,
    billing_city text,
    billing_code text,
    billing_country text,
    billing_state text,
    billing_street text,
    buyer text,
    champion text,
    competitors jsonb,
    created_time text,
    crm text,
    currency_symbol text,
    description text,
    editable text,
    field_states text,
    followed text,
    followers text,
    last_activity_time text,
    live_date text,
    locked_for_me text,
    modified_time timestamp,
    "name" text,
    onboarding_lead text,
    ownership text,
    parent_account text,
    phone text,
    property_count text,
    record_image text,
    sharing_permission text,
    stage text,
    "type" text,
    unit_count text,
    website text,
    zia_owner_assignment text,
    zia_visions text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE product_tag (
    id text,
    product_id text,
    color_code text,
    "name" text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    approval_state text,
    category text,
    code text,
    created_time text,
    currency_symbol text,
    description text,
    editable text,
    field_states text,
    followed text,
    followers text,
    is_active text,
    locked_for_me text,
    modified_time timestamp,
    "name" text,
    record_image text,
    sharing_permission text,
    taxable text,
    unit_price text,
    zia_visions text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE pipeline_tag (
    id text,
    pipeline_id text,
    color_code text,
    "name" text,
    PRIMARY KEY (id, pipeline_id),
    FOREIGN KEY (pipeline_id) REFERENCES pipeline(id)
);

CREATE TABLE pipeline_market (
    "index" text,
    pipeline_id text,
    market text,
    PRIMARY KEY ("index", pipeline_id),
    FOREIGN KEY (pipeline_id) REFERENCES pipeline(id)
);

CREATE TABLE pipeline_partner_type (
    "index" text,
    pipeline_id text,
    "type" text,
    PRIMARY KEY ("index", pipeline_id),
    FOREIGN KEY (pipeline_id) REFERENCES pipeline(id)
);

CREATE TABLE pipeline_property_management_system (
    "index" text,
    pipeline_id text,
    management_system text,
    PRIMARY KEY ("index", pipeline_id),
    FOREIGN KEY (pipeline_id) REFERENCES pipeline(id)
);

CREATE TABLE pipeline_prospect_pain_point (
    "index" text,
    pipeline_id text,
    pain_point text,
    PRIMARY KEY ("index", pipeline_id),
    FOREIGN KEY (pipeline_id) REFERENCES pipeline(id)
);

CREATE TABLE pipeline (
    id text,
    account_id text,
    contact_id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    approval_state text,
    closing_date text,
    created_time text,
    currency_symbol text,
    deal_name text,
    description text,
    editable text,
    field_states text,
    followed text,
    followers text,
    last_activity_time text,
    lead_source text,
    locked_for_me text,
    modified_time timestamp,
    "name" text,
    next_step text,
    onboarding_poc text,
    opportunity_type text,
    partner_success_manager text,
    pipeline_number text,
    priority text,
    probability text,
    property_count text,
    segment text,
    sharing_permission text,
    stage text,
    sub_pipeline text,
    total_arr_opportunity text,
    total_revenue_opportunity text,
    total_unit_count text,
    unit_count text,
    zia_owner_assignment text,
    zia_visions text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    created_by_id text,
    modified_by_id text,
    profile_id text,
    alias text,
    category text,
    city text,
    confirm text,
    country text,
    country_locale text,
    created_time text,
    current_shift text,
    date_format text,
    decimal_separator text,
    default_tab_group text,
    dob text,
    email text,
    fax text,
    first_name text,
    full_name text,
    is_on_line text,
    languages text,
    last_name text,
    locale text,
    microsoft text,
    mobile text,
    modified_time text,
    name_format text,
    next_shift text,
    normal_tab_background text,
    normal_tab_font_color text,
    number_separator text,
    offsets text,
    personal_account text,
    phone text,
    role_id text,
    role_name text,
    sandbox_developer text,
    selected_tab_background text,
    selected_tab_font_color text,
    shift_effective_from text,
    signature text,
    sort_order_preference text,
    "state" text,
    "status" text,
    status_reason_s text,
    street text,
    theme_background text,
    theme_new_background text,
    theme_screen text,
    theme_type text,
    time_format text,
    time_zone text,
    website text,
    zip text,
    zuid text,
    -- custom_fields_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (profile_id) REFERENCES users(id)
);
