CREATE TABLE conference_on_demand (
    conference_attedence_id text,
    conference_id text,
    PRIMARY KEY (conference_attedence_id, conference_id),
    FOREIGN KEY (conference_attedence_id) REFERENCES conference_attedence(id),
    FOREIGN KEY (conference_id) REFERENCES conference(id)
);

CREATE TABLE conference_attedence (
    id text,
    conference_id text,
    active_consent text,
    attended text,
    bmid text,
    browser text,
    chats text,
    "comment" text,
    country text,
    downloaded text,
    duration text,
    email text,
    engaged text,
    enter_time text,
    exit_time text,
    first_name text,
    handout_name jsonb,
    last_name text,
    live_duration text,
    offers_info jsonb,
    on_demand_duration text,
    os text,
    polls text,
    polls_info jsonb,
    qa text,
    rating text,
    recording_duration text,
    referral_domain text,
    registration_date text,
    time_zone text,
    tracking_code text,
    traffic_source text,
    view_start_time text,
    watched text,
    -- custom_fields_* (dynamic column),
    PRIMARY KEY (id, conference_id),
    FOREIGN KEY (conference_id) REFERENCES conference(id)
);

CREATE TABLE conference_registrant_with_custom_field (
    id text,
    conference_id text,
    bmid text,
    country text,
    coupon_used text,
    custom_fields jsonb,
    custom_user_id text,
    earned_certificate text,
    email text,
    enter_url text,
    first_name text,
    last_name text,
    qualified_for_certificate text,
    referral_domain text,
    registered_at text,
    "source" text,
    start_time text,
    time_zone text,
    tracking_code text,
    PRIMARY KEY (id, conference_id),
    FOREIGN KEY (conference_id) REFERENCES conference(id)
);

CREATE TABLE conference_registration (
    id text,
    conference_id text,
    active_consent text,
    attended text,
    banned text,
    bmid text,
    browser text,
    chats text,
    "comment" text,
    country text,
    coupon text,
    downloaded text,
    email text,
    engaged text,
    enter_time text,
    exit_time text,
    first_name text,
    handout_name jsonb,
    last_name text,
    live_duration text,
    os text,
    polls text,
    polls_info jsonb,
    qa text,
    rating text,
    recording_duration text,
    referral_domain text,
    registration_date text,
    time_zone text,
    tracking_code text,
    traffic_source text,
    view_start_time text,
    watched text,
    watched_on_demand text,
    -- custom_fields_* (dynamic column),
    PRIMARY KEY (id, conference_id),
    FOREIGN KEY (conference_id) REFERENCES conference(id)
);

CREATE TABLE subchannel (
    id text,
    channel_id text,
    channel_url text,
    "name" text,
    overview text,
    PRIMARY KEY (id, channel_id),
    FOREIGN KEY (channel_id) REFERENCES channel(id)
);

CREATE TABLE conference_no_show (
    conference_id text,
    conference_registration_id text,
    PRIMARY KEY (conference_id, conference_registration_id),
    FOREIGN KEY (conference_id) REFERENCES conference(id),
    FOREIGN KEY (conference_registration_id) REFERENCES conference_registration(id)
);

CREATE TABLE channel_host (
    "index" text,
    channel_id text,
    host text,
    PRIMARY KEY ("index", channel_id),
    FOREIGN KEY (channel_id) REFERENCES channel(id)
);

CREATE TABLE channel (
    id text,
    custom_billing_tier text,
    description text,
    "name" text,
    overview text,
    url text,
    PRIMARY KEY (id)
);

CREATE TABLE conference_agenda_topic (
    "index" text,
    conference_id text,
    topic text,
    PRIMARY KEY ("index", conference_id),
    FOREIGN KEY (conference_id) REFERENCES conference(id)
);

CREATE TABLE conference_presenter (
    id text,
    conference_id text,
    bio text,
    can_manage text,
    display_name text,
    display_on_landing_page text,
    email text,
    facebook text,
    first_name text,
    is_moderator text,
    last_name text,
    linkedin text,
    member_id text,
    presenter_dial_in_id text,
    presenter_dial_in_number text,
    presenter_dial_in_passcode text,
    presenter_url text,
    title text,
    twitter text,
    website text,
    PRIMARY KEY (id, conference_id),
    FOREIGN KEY (conference_id) REFERENCES conference(id)
);

CREATE TABLE conference (
    id text,
    channel_id text,
    associated_series jsonb,
    audience_open_time text,
    auto_invite_all_channel_members text,
    auto_publish_time text,
    auto_unpublish_time text,
    background_image_url text,
    banner_filter_percentage text,
    can_view_poll_results text,
    conference_address text,
    copy_webinar_id text,
    custom_event_id text,
    dial_in_information_id text,
    dial_in_information_number text,
    dial_in_information_passcode text,
    dial_in_information_presenter_id text,
    dial_in_information_presenter_number text,
    dial_in_information_presenter_passcode text,
    disclaimer text,
    duration text,
    enable_ie_safari text,
    enable_knock_to_enter text,
    enable_registration_email text,
    enable_review_emails text,
    enable_twitter text,
    end_time text,
    event_type text,
    exit_url text,
    fb_open_graph_image_url text,
    first_admin_enter_time text,
    is_recording_published text,
    languages text,
    last_publish_time text,
    last_unpublish_time text,
    manual_end_time text,
    master_webinar_id text,
    max_attendance text,
    meeting_mode text,
    moderator_open_time text,
    polls jsonb,
    preload_files jsonb,
    presenter_exit_url text,
    privacy text,
    purpose text,
    recorded text,
    recording_iframe text,
    recording_url text,
    registration_required_to_view_recording text,
    send_cancellation_email text,
    send_reminder_emails_to_presenters text,
    show_handout_on_page text,
    show_reviews text,
    start_time text,
    tags jsonb,
    time_zone text,
    title text,
    "type" text,
    webcast_mode text,
    webhook_url text,
    webinar_stats_invited text,
    webinar_stats_page_views text,
    webinar_stats_registrants text,
    webinar_stats_revenue text,
    webinar_stats_total_attendees text,
    who_can_watch_recording text,
    PRIMARY KEY (id),
    FOREIGN KEY (channel_id) REFERENCES channel(id)
);

CREATE TABLE event_summary (
    _fivetran_id text,
    conference_id text,
    total_live_minutes_watched text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (conference_id) REFERENCES conference(id)
);

CREATE TABLE subscriber (
    id text,
    channel_id text,
    email text,
    first_name text,
    last_name text,
    PRIMARY KEY (id, channel_id),
    FOREIGN KEY (channel_id) REFERENCES channel(id)
);
