CREATE TABLE payment (
    id text,
    billing_profile_id text,
    creator_id text,
    invoice_display_id text,
    updater_id text,
    allocation_strategy text,
    amount text,
    auto_allocate text,
    created text,
    credit_card_transaction_message text,
    credit_card_transaction_status text,
    ecom_transaction_id text,
    ecom_transaction_response_id text,
    gateway_profile_id text,
    gateway_transaction_id text,
    note text,
    payment_date text,
    pending_amount text,
    pre_surcharge_amount text,
    "type" text,
    unallocated_amount text,
    updated text,
    void_flag text,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_profile_id) REFERENCES billing_profile(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (invoice_display_id) REFERENCES invoice(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE activity_collector (
    id text,
    account_id text,
    creator_id text,
    time_zone_id text,
    updater_id text,
    activity_collector_name text,
    billable_activity_flag text,
    consolidation_mode text,
    create_after_process_directory_flag text,
    created text,
    delimiter text,
    field_included_char text,
    rate_activity_flag text,
    record_format text,
    reject_closed_flag text,
    skip_rows text,
    "status" text,
    "type" text,
    updated text,
    vendor_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (time_zone_id) REFERENCES time_zone(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE contract_currency (
    id text,
    contract_id text,
    creator_id text,
    created text,
    currency_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE contract (
    id text,
    account_id text,
    creator_id text,
    contract_number text,
    contract_status text,
    created text,
    end_date text,
    on_end_date text,
    start_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE dunning_interval (
    id text,
    created text,
    dunning_interval_name text,
    "status" text,
    PRIMARY KEY (id)
);

CREATE TABLE billing_profile (
    id text,
    account_id text,
    dunning_interval text,
    invoice_template_id text,
    time_zone_id text,
    updater_id text,
    account_balance text,
    account_balance_number text,
    ach_bank_acct_type text,
    address_1 text,
    attention text,
    bill_to text,
    billing_cycle text,
    billing_entity text,
    billing_method text,
    city text,
    country text,
    created text,
    currency_code text,
    email text,
    fax text,
    hosted_payment_page_external_id text,
    invoice_approval_flag text,
    invoice_delivery_method text,
    invoice_file_format text,
    manual_close_flag text,
    monthly_billing_date text,
    payment_term_days text,
    period_cutoff_date text,
    phone text,
    quarterly_billing_month text,
    "state" text,
    statement_approval_flag text,
    statement_cycle text,
    statement_delivery_method text,
    statement_template_id text,
    "status" text,
    updated text,
    weekly_billing_date text,
    yearly_billing_month text,
    zip text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (dunning_interval) REFERENCES dunning_interval(id),
    FOREIGN KEY (invoice_template_id) REFERENCES invoice_template(id),
    FOREIGN KEY (time_zone_id) REFERENCES time_zone(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE invoice (
    id text,
    billing_profile_id text,
    creator_id text,
    updater_id text,
    activity_end_date text,
    activity_start_date text,
    aging_interval text,
    approval_status text,
    billable_flag text,
    billing_cycle_end_date text,
    billing_cycle_start_date text,
    closed_date text,
    created text,
    credit_amount text,
    due_amount text,
    due_date text,
    file_name text,
    grand_total_amount text,
    manual_close_approved_flag text,
    mass_update_error text,
    payment_amount text,
    payment_status text,
    pdf_created_date text,
    pdf_file text,
    "status" text,
    tax_total_amount_unrounded text,
    total_amount_unrounded text,
    updated text,
    xml_file text,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_profile_id) REFERENCES billing_profile(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE collector_field (
    id text,
    activity_collector_id text,
    billing_identifier text,
    activity_collector_history_id text,
    activity_date text,
    activity_date_ts text,
    charge_type text,
    consolidation_exempt text,
    created text,
    process_status text,
    quantity text,
    record_number text,
    usage_product text,
    PRIMARY KEY (id),
    FOREIGN KEY (activity_collector_id) REFERENCES activity_collector(id),
    FOREIGN KEY (billing_identifier) REFERENCES billing_identifier(billing_identifier)
);

CREATE TABLE account (
    id text,
    billable_account_id text,
    billable_billing_profile_id text,
    creator_id text,
    parent_account_id text,
    updater_id text,
    account_type_id text,
    allow_pricing_in_different_currency text,
    created text,
    date_display_format text,
    invoice_at_this_level text,
    "name" text,
    rate_hierarchy text,
    "status" text,
    updated text,
    PRIMARY KEY (id),
    FOREIGN KEY (billable_account_id) REFERENCES account(id),
    FOREIGN KEY (billable_billing_profile_id) REFERENCES billing_profile(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (parent_account_id) REFERENCES account(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE billing_identifier (
    id text,
    creator_id text,
    updater_id text,
    active_from text,
    billing_identifier text,
    created text,
    "status" text,
    updated text,
    vendor_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE revrec_contract (
    id text,
    account_id text,
    creator_id text,
    updater_id text,
    created text,
    current_active_contract text,
    "name" text,
    original_contract text,
    "status" text,
    total_expected_billings text,
    total_ssp text,
    updated text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE time_zone (
    id text,
    creator_id text,
    created text,
    default_flag text,
    display_flag text,
    tz_name text,
    utc_offset text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE account_product (
    id text,
    account_id text,
    creator_id text,
    updater_id text,
    created text,
    end_date text,
    "name" text,
    product_id text,
    quantity text,
    rate text,
    rate_min_charge text,
    rate_override text,
    rating_method_id text,
    renewal_date text,
    start_date text,
    "status" text,
    updated text,
    upgrade_downgrade_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE account_package (
    id text,
    account_id text,
    creator_id text,
    updater_id text,
    created text,
    end_date text,
    package_id text,
    start_date text,
    updated text,
    upgrade_downgrade_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE contract_rate (
    id text,
    contract_id text,
    creator_id text,
    updater_id text,
    contract_rate_label text,
    created text,
    "name" text,
    product_id text,
    rate text,
    rating_method_id text,
    updated text,
    PRIMARY KEY (id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE invoice_template (
    id text,
    account_id text,
    creator_id text,
    updater_id text,
    created text,
    date_format text,
    default_flag text,
    email_template_id text,
    invoice_file_format text,
    invoice_xsl_id text,
    language_code text,
    "name" text,
    show_aging text,
    show_credit_adj_detail text,
    show_past_due_statements text,
    show_tax_fee_detail text,
    "status" text,
    support_message text,
    support_message_1 text,
    support_number text,
    "type" text,
    updated text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    account_id text,
    creator_id text,
    time_zone_id text,
    updater_id text,
    addr_1 text,
    collections_flag text,
    convert_time_zone text,
    created text,
    email text,
    first_name text,
    forbid_internal_auth text,
    language_code text,
    last_name text,
    reset_password_flag text,
    role_id text,
    role_name text,
    role_status text,
    root_account_id text,
    "status" text,
    theme_id text,
    title text,
    "type" text,
    updated text,
    user_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (time_zone_id) REFERENCES time_zone(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE activity (
    id text,
    account_id text,
    account_product_id text,
    creator_id text,
    invoice_id text,
    updater_id text,
    activity_date text,
    cost_unrounded text,
    created text,
    currency_code text,
    estimated text,
    feature text,
    min_charge_flag text,
    pricing_currency_code text,
    pricing_currency_cost text,
    pricing_id text,
    pro_rate_factor text,
    process_status text,
    product_id text,
    quantity text,
    rate text,
    rate_source text,
    rated_amount text,
    rating_date text,
    rating_method_id text,
    standard_cost_unrounded text,
    standard_rate text,
    subscription_from_date text,
    subscription_to_date text,
    tax_cost_unrounded text,
    tiered_group text,
    total_cost text,
    updated text,
    upper_band text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (account_product_id) REFERENCES account_product(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);
