CREATE TABLE event (
    id text,
    attributed boolean,
    content_items jsonb,
    customer_event_alias text,
    datasource text,
    days_from_last_attributed_touch_to_event integer,
    days_from_last_cta_view_to_event integer,
    deep_linked boolean,
    di_match_click_token bigint,
    event_timestamp bigint,
    existing_user boolean,
    first_event_for_user boolean,
    hours_from_last_attributed_touch_to_event integer,
    install_activity_timestamp integer,
    last_attributed_touch_timestamp bigint,
    last_attributed_touch_type text,
    last_cta_view_timestamp bigint,
    minutes_from_last_attributed_touch_to_event integer,
    "name" text,
    organization_id bigint,
    organization_name text,
    origin text,
    persona_identifiers jsonb,
    referrer_click_timestamp bigint,
    seconds_from_last_attributed_touch_to_event integer,
    server_timestamp bigint,
    store_install_begin_timestamp bigint,
    tune_site_event_id integer,
    tune_site_id integer,
    tune_site_name text,
    webhook_request_headers jsonb,
    webhook_request_url text,
    webhook_response_code integer,
    -- event_data_* (dynamic column),
    -- last_attributed_touch_data_* (dynamic column),
    -- last_cta_view_data_* (dynamic column),
    -- user_data_* (dynamic column),
    PRIMARY KEY (id)
);
