CREATE TABLE location_event (
    id text,
    device_id text,
    user_id text,
    alt_accuracy text,
    altitude text,
    app_id text,
    event_type text,
    external_user_id text,
    latitude text,
    ll_accuracy text,
    longitude text,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE session_event (
    id text,
    device_id text,
    user_id text,
    app_id text,
    duration text,
    event_type text,
    external_user_id text,
    session_id text,
    "time" text,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE push_notification_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_message_variation_id text,
    canvas_step_message_variation_updated_at timestamp,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    device_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    app_group_id text,
    app_id text,
    dispatch_id text,
    event_type text,
    external_user_id text,
    message_extras jsonb,
    send_id text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE segment_tag (
    tag text,
    segment_id text,
    PRIMARY KEY (tag, segment_id),
    FOREIGN KEY (segment_id) REFERENCES segment(id)
);

CREATE TABLE canvas_exit_event (
    id text,
    canvas_id text,
    canvas_step_id text,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    user_id text,
    app_group_id text,
    event_type text,
    external_user_id text,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE subscription_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    app_group_id text,
    app_id text,
    channel text,
    email_address text,
    event_type text,
    external_user_id text,
    phone_number text,
    send_id text,
    state_change_source text,
    subscription_group_id text,
    subscription_status text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE uninstall_event (
    id text,
    user_id text,
    app_id text,
    event_type text,
    external_user_id text,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE campaign_conversion_event (
    id text,
    campaign_conversion_behavior_id text,
    campaign_id text,
    campaign_updated_at timestamp,
    user_id text,
    app_id text,
    conversion_behavior_index text,
    event_type text,
    external_user_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    send_id text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_conversion_behavior_id) REFERENCES campaign_conversion_behavior(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE campaign_enrollment_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    user_id text,
    event_type text,
    external_user_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    send_id text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE campaign_tag (
    tag text,
    campaign_id text,
    campaign_updated_at timestamp,
    PRIMARY KEY (tag, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id)
);

CREATE TABLE canvas_experiment_step_conversion_event (
    id text,
    canvas_conversion_behavior_id text,
    canvas_id text,
    canvas_step_id text,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    user_id text,
    app_id text,
    event_type text,
    experiment_split_id text,
    experiment_split_name text,
    experiment_step_id text,
    external_user_id text,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (canvas_conversion_behavior_id) REFERENCES canvas_conversion_behavior(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE "user" (
    id text,
    attributed_ad text,
    attributed_adgroup text,
    attributed_campaign text,
    attributed_source text,
    country text,
    created_at timestamp,
    dob timestamp,
    email text,
    email_subscribe text,
    external_id text,
    first_name text,
    gender text,
    home_city text,
    language text,
    last_name text,
    phone text,
    push_subscribe text,
    time_zone text,
    total_revenue text,
    PRIMARY KEY (id)
);

CREATE TABLE canvas_variation (
    canvas_id text,
    id text,
    "name" text,
    canvas_updated_at timestamp,
    PRIMARY KEY (canvas_id, id, "name"),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id)
);

CREATE TABLE random_bucket_number_event (
    id text,
    user_id text,
    app_group_id text,
    event_type text,
    external_user_id text,
    prev_random_bucket_number integer,
    random_bucket_number integer,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE newsfeed_impression_event (
    id text,
    device_id text,
    user_id text,
    app_id text,
    event_type text,
    external_user_id text,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE attribution_event (
    id text,
    user_id text,
    event_type text,
    external_user_id text,
    "source" text,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE canvas_step_seq (
    canvas_step_seq text,
    canvas_id text,
    canvas_updated_at timestamp,
    PRIMARY KEY (canvas_step_seq, canvas_id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id)
);

CREATE TABLE banner_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    device_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    ad_id text,
    ad_id_type text,
    ad_tracking_enabled boolean,
    app_group_id text,
    app_id text,
    banner_placement_id text,
    browser text,
    button_id text,
    carrier text,
    country text,
    device_model text,
    event_type text,
    external_user_id text,
    gender text,
    language text,
    os_version text,
    platform text,
    resolution text,
    sdk_version text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE content_card_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_message_variation_id text,
    canvas_step_message_variation_updated_at timestamp,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    device_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    app_group_id text,
    app_id text,
    content_card_id text,
    dispatch_id text,
    event_type text,
    external_user_id text,
    message_extras jsonb,
    send_id text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE purchase_event (
    id text,
    device_id text,
    user_id text,
    app_id text,
    currency text,
    event_type text,
    external_user_id text,
    price text,
    product_id text,
    properties text,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE webhook_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_message_variation_id text,
    canvas_step_message_variation_updated_at timestamp,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    device_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    app_group_id text,
    content_length integer,
    dispatch_id text,
    endpoint_url text,
    event_type text,
    external_user_id text,
    host text,
    http_status_code integer,
    is_terminal boolean,
    message_extras jsonb,
    raw_response text,
    retry_count integer,
    send_id text,
    "time" timestamp,
    timezone text,
    url_path text,
    webhook_duration integer,
    webhook_failure_source text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE canvas_conversion_behavior (
    id text,
    canvas_id text,
    canvas_updated_at timestamp,
    conversion_behavior text,
    conversion_behavior_index integer,
    PRIMARY KEY (id, canvas_id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id)
);

CREATE TABLE segment (
    id text,
    updated_at timestamp,
    analytics_tracking_enabled boolean,
    created_at timestamp,
    description text,
    error boolean,
    message text,
    "name" text,
    text_description text,
    PRIMARY KEY (id, updated_at)
);

CREATE TABLE card_tag (
    card_id text,
    tag text,
    card_updated_at timestamp,
    PRIMARY KEY (card_id, tag),
    FOREIGN KEY (card_updated_at) REFERENCES card(id)
);

CREATE TABLE canvas_conversion_event (
    id text,
    canvas_conversion_behavior_id text,
    canvas_id text,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    user_id text,
    app_id text,
    canvas_step_id text,
    canvas_step_updated_at timestamp,
    event_type text,
    external_user_id text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (canvas_conversion_behavior_id) REFERENCES canvas_conversion_behavior(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE canvas_entry_event (
    id text,
    canvas_id text,
    canvas_step_id text,
    canvas_step_updated_at text,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    user_id text,
    event_type text,
    external_user_id text,
    in_control_group text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE whatsapp_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_message_variation_id text,
    canvas_step_message_variation_updated_at timestamp,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    device_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    "action" text,
    app_group_id text,
    dispatch_id text,
    event_type text,
    external_user_id text,
    from_phone_number text,
    inbound_phone_number text,
    media_urls jsonb,
    message_body text,
    message_extras text,
    provider_error_code text,
    provider_error_title text,
    quick_reply_text text,
    send_id text,
    short_url text,
    subscription_group_id text,
    "time" timestamp,
    timezone text,
    to_phone_number text,
    url text,
    user_agent text,
    user_phone_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE message_variation (
    id text,
    updated_at timestamp,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_step_id text,
    canvas_step_updated_at timestamp,
    alert text,
    body text,
    channel text,
    extras jsonb,
    "from" text,
    headers text,
    method text,
    "name" text,
    preheader text,
    reply_to text,
    subject text,
    title text,
    "type" text,
    url text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id)
);

CREATE TABLE canvas_tag (
    canvas_id text,
    tag text,
    canvas_updated_at timestamp,
    PRIMARY KEY (canvas_id, tag),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id)
);

CREATE TABLE card (
    id text,
    updated_at timestamp,
    archived boolean,
    created_at timestamp,
    description text,
    draft boolean,
    end_at timestamp,
    error boolean,
    image_url text,
    message text,
    "name" text,
    publish_at text,
    title text,
    PRIMARY KEY (id, updated_at)
);

CREATE TABLE campaign_conversion_behavior (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    conversion_behavior text,
    conversion_behavior_index text,
    updated_at timestamp,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id)
);

CREATE TABLE canvas (
    id text,
    updated_at timestamp,
    archived boolean,
    channel_android_push boolean,
    channel_content_cards boolean,
    channel_email boolean,
    channel_in_app_message boolean,
    channel_ios_push boolean,
    channel_sms boolean,
    channel_web_push boolean,
    channel_webhook boolean,
    created_at timestamp,
    draft boolean,
    enabled boolean,
    error boolean,
    first_entry timestamp,
    last_entry timestamp,
    message text,
    "name" text,
    schedule_type text,
    PRIMARY KEY (id, updated_at)
);

CREATE TABLE canvas_step (
    id text,
    canvas_id text,
    canvas_updated_at timestamp,
    channel_android_push boolean,
    channel_content_cards boolean,
    channel_email boolean,
    channel_in_app_message boolean,
    channel_ios_push boolean,
    channel_sms boolean,
    channel_web_push boolean,
    channel_webhook boolean,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id)
);

CREATE TABLE canvas_experiment_step_entry_event (
    id text,
    canvas_id text,
    canvas_step_id text,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    user_id text,
    event_type text,
    experiment_split_id text,
    experiment_split_name text,
    experiment_step_id text,
    external_user_id text,
    in_control_group boolean,
    "time" timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE newsfeed_card_event (
    id text,
    card_id text,
    card_updated_at timestamp,
    device_id text,
    user_id text,
    abort_log text,
    abort_type text,
    app_group_id text,
    app_id text,
    browser text,
    carrier text,
    event_type text,
    external_user_id text,
    resolution text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (card_id) REFERENCES card(id),
    FOREIGN KEY (card_updated_at) REFERENCES card(id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE custom_event (
    id text,
    device_id text,
    user_id text,
    app_id text,
    event_type text,
    external_user_id text,
    "name" text,
    properties text,
    "time" timestamp,
    timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE segment_member (
    segment_id text,
    user_id text,
    PRIMARY KEY (segment_id, user_id),
    FOREIGN KEY (segment_id) REFERENCES segment(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE sms_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_message_variation_id text,
    canvas_step_message_variation_updated_at timestamp,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    "action" text,
    app_group_id text,
    dispatch_id text,
    error text,
    event_type text,
    external_user_id text,
    from_phone_number text,
    inbound_phone_number text,
    is_suspected_bot_click boolean,
    message_body text,
    message_extras jsonb,
    provider_error_code text,
    short_url text,
    subscription_group_api_id text,
    subscription_group_id text,
    suspected_bot_click_reason jsonb,
    "time" timestamp,
    timezone text,
    to_phone_number text,
    url text,
    user_agent text,
    user_phone_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE device (
    id text,
    device_model text,
    os_version text,
    platform text,
    PRIMARY KEY (id)
);

CREATE TABLE in_app_message_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_message_variation_id text,
    canvas_step_message_variation_updated_at timestamp,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    device_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    ad_id text,
    ad_id_type text,
    ad_tracking_enabled boolean,
    app_group_id text,
    app_id text,
    browser text,
    button_id text,
    card_id text,
    card_updated_at timestamp,
    carrier text,
    dispatch_id text,
    event_type text,
    external_user_id text,
    resolution text,
    send_id text,
    "time" timestamp,
    timezone text,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE user_push_token (
    "index" integer,
    user_id text,
    app text,
    device_id text,
    notifications_enabled boolean,
    platform text,
    token text,
    PRIMARY KEY ("index", user_id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE campaign (
    id text,
    updated_at timestamp,
    archived boolean,
    channel_android_push boolean,
    channel_content_cards boolean,
    channel_email boolean,
    channel_in_app_message boolean,
    channel_ios_push boolean,
    channel_sms boolean,
    channel_web_push boolean,
    channel_webhook boolean,
    created_at timestamp,
    draft boolean,
    enabled boolean,
    error boolean,
    first_sent text,
    is_api_campaign boolean,
    last_sent text,
    message text,
    "name" text,
    schedule_type text,
    PRIMARY KEY (id, updated_at)
);

CREATE TABLE card_extra (
    card_id text,
    "key" text,
    card_updated_at timestamp,
    error boolean,
    message text,
    "value" text,
    PRIMARY KEY (card_id, "key"),
    FOREIGN KEY (card_updated_at) REFERENCES card(id)
);

CREATE TABLE user_alias (
    label text,
    "name" text,
    user_id text,
    PRIMARY KEY (label, "name"),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE email_event (
    id text,
    campaign_id text,
    campaign_updated_at timestamp,
    canvas_id text,
    canvas_step_id text,
    canvas_step_message_variation_id text,
    canvas_step_message_variation_updated_at timestamp,
    canvas_step_updated_at timestamp,
    canvas_updated_at timestamp,
    canvas_variation_id text,
    device_id text,
    message_variation_id text,
    message_variation_updated_at timestamp,
    user_id text,
    abort_log text,
    abort_type text,
    app_group_id text,
    bounce_reason text,
    dispatch_id text,
    email_address text,
    esp text,
    event_type text,
    external_user_id text,
    from_domain text,
    ip_pool text,
    is_amp boolean,
    is_drop boolean,
    is_suspected_bot_click boolean,
    link_alias text,
    link_id text,
    machine_open text,
    message_extras jsonb,
    send_id text,
    sending_ip text,
    suspected_bot_click_reason jsonb,
    "time" timestamp,
    timezone text,
    url text,
    user_agent text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_updated_at) REFERENCES campaign(id),
    FOREIGN KEY (canvas_id) REFERENCES canvas(id),
    FOREIGN KEY (canvas_step_id) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_step_message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (canvas_step_updated_at) REFERENCES canvas_step(id),
    FOREIGN KEY (canvas_updated_at) REFERENCES canvas(id),
    FOREIGN KEY (canvas_variation_id) REFERENCES canvas_variation(canvas_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (message_variation_id) REFERENCES message_variation(id),
    FOREIGN KEY (message_variation_updated_at) REFERENCES message_variation(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id)
);
