CREATE TABLE episode (
    id text,
    podcast_id text,
    artist text,
    artwork_url text,
    audio_url text,
    custom_url text,
    description text,
    duration text,
    episode_number text,
    episode_type text,
    explicit text,
    guid text,
    hq text,
    inactive_at text,
    magic_mastering text,
    private text,
    published_at text,
    season_number text,
    summary text,
    tag text,
    title text,
    total_plays text,
    PRIMARY KEY (id),
    FOREIGN KEY (podcast_id) REFERENCES podcast(id)
);

CREATE TABLE podcast (
    id text,
    artwork_url text,
    author text,
    background_url text,
    contact_email text,
    description text,
    explicit text,
    keyword text,
    language text,
    main_category text,
    main_category_2 text,
    main_category_3 text,
    sub_category text,
    sub_category_2 text,
    sub_category_3 text,
    timezone text,
    title text,
    website_address text,
    PRIMARY KEY (id)
);
