CREATE TABLE user_account_association (
    id text,
    account_id text,
    user_id text,
    created_at text,
    depth text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE content_tag (
    id text,
    context_module_id text,
    learning_outcome_id text,
    associated_asset_id text,
    associated_asset_type text,
    comments text,
    content_id text,
    content_type text,
    context_code text,
    context_id text,
    context_type text,
    created_at text,
    link_settings jsonb,
    mastery_score text,
    migration_id text,
    new_tab text,
    "position" text,
    rubric_association_id text,
    tag_type text,
    title text,
    updated_at text,
    url text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (context_module_id) REFERENCES context_module(id),
    FOREIGN KEY (learning_outcome_id) REFERENCES learning_outcome(id)
);

CREATE TABLE learning_outcome_group (
    id text,
    context_id text,
    context_type text,
    created_at text,
    description text,
    learning_outcome_group_id text,
    migration_id text,
    outcome_import_id text,
    root_learning_outcome_group_id text,
    source_outcome_group_id text,
    title text,
    updated_at text,
    vendor_guid text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE learning_outcome_result (
    id text,
    content_tag_id text,
    learning_outcome_id text,
    user_id text,
    artifact_id text,
    artifact_type text,
    assessed_at text,
    associated_asset_id text,
    associated_asset_type text,
    association_id text,
    association_type text,
    attempt text,
    context_code text,
    context_id text,
    context_type text,
    created_at text,
    hidden text,
    hide_points text,
    mastery text,
    original_mastery text,
    original_possible text,
    original_score text,
    percentage text,
    possible text,
    score text,
    submitted_at text,
    title text,
    updated_at text,
    user_uuid text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (content_tag_id) REFERENCES assessment_question(id),
    FOREIGN KEY (learning_outcome_id) REFERENCES learning_outcome(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE score (
    id text,
    assignment_group_id text,
    enrollment_id text,
    grading_period_id text,
    course_score text,
    created_at text,
    current_points text,
    current_score text,
    final_points text,
    final_score text,
    override_score text,
    unposted_current_points text,
    unposted_current_score text,
    unposted_final_points text,
    unposted_final_score text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_group_id) REFERENCES assignment_group(id),
    FOREIGN KEY (enrollment_id) REFERENCES enrollment(id),
    FOREIGN KEY (grading_period_id) REFERENCES grading_period(id)
);

CREATE TABLE course_account_association (
    id text,
    account_id text,
    course_id text,
    course_section_id text,
    created_at text,
    depth text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (course_section_id) REFERENCES course_section(id)
);

CREATE TABLE context_module (
    id text,
    completion_events text,
    completion_requirements jsonb,
    context_id text,
    context_type text,
    created_at text,
    deleted_at text,
    migration_id text,
    "name" text,
    "position" text,
    prerequisites jsonb,
    require_sequential_progress text,
    requirement_count text,
    unlock_at text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE grading_period (
    id text,
    grading_period_group_id text,
    close_date text,
    created_at text,
    end_date text,
    start_date text,
    title text,
    updated_at text,
    weight text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (grading_period_group_id) REFERENCES grading_period_group(id)
);

CREATE TABLE grading_standard (
    id text,
    user_id text,
    context_code text,
    context_id text,
    context_type text,
    created_at text,
    data text,
    migration_id text,
    title text,
    updated_at text,
    version text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE assessment_question_bank (
    id text,
    context_id text,
    context_type text,
    created_at text,
    deleted_at text,
    migration_id text,
    title text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE quiz_question (
    id text,
    assessment_question_id text,
    quiz_group_id text,
    quiz_id text,
    assessment_question_version text,
    created_at text,
    migration_id text,
    "position" text,
    question_data_answers text,
    question_data_correct_comment text,
    question_data_incorrect_comment text,
    question_data_name text,
    question_data_points_possible text,
    question_data_question_text text,
    question_data_question_type text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assessment_question_id) REFERENCES assessment_question(id),
    FOREIGN KEY (quiz_group_id) REFERENCES quiz_group(id),
    FOREIGN KEY (quiz_id) REFERENCES quiz(id)
);

CREATE TABLE lti_result (
    id text,
    lti_line_item_id text,
    submission_id text,
    user_id text,
    activity_progress text,
    "comment" text,
    created_at text,
    extensions text,
    grading_progress text,
    result_maximum text,
    result_score text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (lti_line_item_id) REFERENCES lti_line_item(id),
    FOREIGN KEY (submission_id) REFERENCES submission(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    merged_into_user_id text,
    avatar_image_source text,
    avatar_image_updated_at text,
    avatar_image_url text,
    created_at text,
    deleted_at text,
    last_logged_out text,
    locale text,
    lti_context_id text,
    "name" text,
    pronouns text,
    public text,
    school_name text,
    school_position text,
    short_name text,
    sortable_name text,
    storage_quota text,
    time_zone text,
    updated_at text,
    uuid text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (merged_into_user_id) REFERENCES users(id)
);

CREATE TABLE group_membership (
    id text,
    group_id text,
    user_id text,
    created_at text,
    moderator text,
    sis_batch_id text,
    updated_at text,
    uuid text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE assignment_override_student (
    id text,
    assignment_id text,
    assignment_override_id text,
    quiz_id text,
    user_id text,
    created_at text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id),
    FOREIGN KEY (assignment_override_id) REFERENCES assignment_override(id),
    FOREIGN KEY (quiz_id) REFERENCES quiz(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE context_module_progression (
    id text,
    context_module_id text,
    user_id text,
    collapsed text,
    completed_at text,
    created_at text,
    "current" text,
    current_position text,
    evaluated_at text,
    incomplete_requirements jsonb,
    lock_version text,
    requirements_met jsonb,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (context_module_id) REFERENCES context_module(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE enrollment_term (
    id text,
    grading_period_group_id text,
    created_at text,
    end_at text,
    integration_id text,
    "name" text,
    sis_batch_id text,
    sis_source_id text,
    start_at text,
    term_code text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (grading_period_group_id) REFERENCES grading_period_group(id)
);

CREATE TABLE assessment_question (
    id text,
    assessment_question_bank_id text,
    context_id text,
    context_type text,
    created_at text,
    deleted_at text,
    migration_id text,
    "name" text,
    "position" text,
    question_data text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assessment_question_bank_id) REFERENCES assessment_question_bank(id)
);

CREATE TABLE submission_comment (
    id text,
    author_id text,
    submission_id text,
    anonymous text,
    assessment_request_id text,
    attachment_ids jsonb,
    attempt text,
    author_name text,
    "comment" text,
    context_id text,
    context_type text,
    created_at text,
    draft text,
    edited_at text,
    group_comment_id text,
    hidden text,
    media_comment_id text,
    media_comment_type text,
    provisional_grade_id text,
    teacher_only_comment text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES users(id),
    FOREIGN KEY (submission_id) REFERENCES submission(id)
);

CREATE TABLE wiki_pages (
    id text,
    assignment_id text,
    old_assignment_id text,
    user_id text,
    body text,
    context_id text,
    context_type text,
    could_be_locked text,
    created_at text,
    editing_roles text,
    migration_id text,
    protected_editing text,
    revised_at text,
    title text,
    todo_date text,
    updated_at text,
    url text,
    wiki_id text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id),
    FOREIGN KEY (old_assignment_id) REFERENCES assignment(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE communication_channel (
    id text,
    pseudonym_id text,
    user_id text,
    bounce_count text,
    confirmation_code_expires_at text,
    confirmation_sent_count text,
    created_at text,
    "path" text,
    path_type text,
    "position" text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (pseudonym_id) REFERENCES pseudonym(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE calendar_event (
    id text,
    parent_calendar_event_id text,
    all_day text,
    all_day_date text,
    comments text,
    context_code text,
    context_id text,
    context_type text,
    created_at text,
    deleted_at text,
    description text,
    effective_context_code text,
    end_at text,
    important_dates text,
    location_address text,
    location_name text,
    migration_id text,
    participants_per_appointment text,
    start_at text,
    time_zone_edited text,
    title text,
    updated_at text,
    user_id text,
    web_conference_id text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (parent_calendar_event_id) REFERENCES calendar_event(id)
);

CREATE TABLE lti_resource_link (
    id text,
    context_external_tool_id text,
    context_id text,
    context_type text,
    created_at text,
    custom text,
    lookup_uuid text,
    resource_link_uuid text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE quiz_submission (
    id text,
    quiz_id text,
    submission_id text,
    user_id text,
    attempt text,
    created_at text,
    end_at text,
    extra_time text,
    finished_at text,
    fudge_points text,
    has_seen_results text,
    kept_score text,
    manually_scored text,
    manually_unlocked text,
    migration_id text,
    quiz_points_possible text,
    quiz_version text,
    score text,
    score_before_regrade text,
    started_at text,
    submission_data jsonb,
    temporary_user_code text,
    updated_at text,
    was_preview text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (quiz_id) REFERENCES quiz(id),
    FOREIGN KEY (submission_id) REFERENCES submission(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE assignment_group (
    id text,
    context_id text,
    context_type text,
    created_at text,
    default_assignment_name text,
    group_weight text,
    migration_id text,
    "name" text,
    "position" text,
    rules text,
    sis_source_id text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE score_statistics (
    id text,
    assignment_id text,
    count text,
    created_at text,
    maximum text,
    mean text,
    minimum text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id)
);

CREATE TABLE submission_version (
    id text,
    assignment_id text,
    user_id text,
    context_id text,
    context_type text,
    version_id text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE content_participation_count (
    id text,
    user_id text,
    content_type text,
    context_id text,
    context_type text,
    created_at text,
    unread_count text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE assignment_override (
    id text,
    assignment_id text,
    quiz_id text,
    set_id text,
    all_day text,
    all_day_date text,
    assignment_version text,
    created_at text,
    due_at text,
    due_at_overridden text,
    lock_at text,
    lock_at_overridden text,
    quiz_version text,
    set_type text,
    title text,
    unlock_at text,
    unlock_at_overridden text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id),
    FOREIGN KEY (quiz_id) REFERENCES quiz(id),
    FOREIGN KEY (set_id) REFERENCES groups(id)
);

CREATE TABLE pseudonym (
    id text,
    account_id text,
    user_id text,
    authentication_provider_id text,
    created_at text,
    current_login_at text,
    current_login_ip text,
    deleted_at text,
    failed_login_count text,
    integration_id text,
    last_login_at text,
    last_login_ip text,
    last_request_at text,
    login_count text,
    "position" text,
    sis_batch_id text,
    sis_user_id text,
    unique_id text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE grading_period_group (
    id text,
    account_id text,
    course_id text,
    created_at text,
    display_totals_for_all_grading_periods text,
    title text,
    updated_at text,
    weighted text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (course_id) REFERENCES course(id)
);

CREATE TABLE quiz_group (
    id text,
    assessment_question_bank_id text,
    quiz_id text,
    created_at text,
    migration_id text,
    "name" text,
    pick_count text,
    "position" text,
    question_points text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assessment_question_bank_id) REFERENCES assessment_question_bank(id),
    FOREIGN KEY (quiz_id) REFERENCES quiz(id)
);

CREATE TABLE course_section (
    id text,
    course_id text,
    enrollment_term_id text,
    nonxlist_course_id text,
    accepting_enrollments text,
    created_at text,
    default_section text,
    end_at text,
    integration_id text,
    "name" text,
    restrict_enrollments_to_section_dates text,
    sis_batch_id text,
    sis_source_id text,
    start_at text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (enrollment_term_id) REFERENCES enrollment_term(id),
    FOREIGN KEY (nonxlist_course_id) REFERENCES course(id)
);

CREATE TABLE course (
    id text,
    account_id text,
    enrollment_term_id text,
    grading_standard_id text,
    homeroom_course_id text,
    replacement_course_id text,
    template_course_id text,
    abstract_course_id text,
    allow_student_organized_groups text,
    allow_student_wiki_edits text,
    conclude_at text,
    course_code text,
    created_at text,
    default_view text,
    default_wiki_editing_roles text,
    grade_passback_setting text,
    group_weighting_scheme text,
    home_page_announcement_limit text,
    homeroom_course text,
    indexed text,
    integration_id text,
    is_public text,
    latest_outcome_import_id text,
    license text,
    locale text,
    lti_context_id text,
    "name" text,
    open_enrollment text,
    public_description text,
    restrict_enrollments_to_course_dates text,
    self_enrollment text,
    self_enrollment_code text,
    self_enrollment_limit text,
    settings_allow_student_discussion_editing text,
    settings_allow_student_discussion_topics text,
    settings_allow_student_forum_attachments text,
    settings_filter_speed_grader_by_student_group text,
    settings_hide_distribution_graphs text,
    settings_hide_final_grade text,
    settings_is_public_to_auth_users text,
    settings_lock_all_announcements text,
    settings_restrict_student_future_view text,
    settings_restrict_student_past_view text,
    settings_usage_rights_required text,
    show_announcements_on_home_page text,
    sis_batch_id text,
    sis_source_id text,
    start_at text,
    storage_quota text,
    syllabus_body text,
    sync_enrollments_from_homeroom text,
    tab_configuration text,
    template text,
    time_zone text,
    turnitin_comments text,
    turnitin_id text,
    updated_at text,
    uuid text,
    wiki_id text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (enrollment_term_id) REFERENCES enrollment_term(id),
    FOREIGN KEY (grading_standard_id) REFERENCES grading_standard(id),
    FOREIGN KEY (homeroom_course_id) REFERENCES course(id),
    FOREIGN KEY (replacement_course_id) REFERENCES course(id),
    FOREIGN KEY (template_course_id) REFERENCES course(id)
);

CREATE TABLE quiz (
    id text,
    assignment_group_id text,
    assignment_id text,
    access_code text,
    allowed_attempts text,
    anonymous_submissions text,
    cant_go_back text,
    context_id text,
    context_type text,
    could_be_locked text,
    created_at text,
    deleted_at text,
    description text,
    due_at text,
    hide_correct_answers_at text,
    hide_results text,
    ip_filter text,
    lock_at text,
    migration_id text,
    one_question_at_a_time text,
    one_time_results text,
    only_visible_to_overrides text,
    points_possible text,
    published_at text,
    question_count text,
    quiz_type text,
    require_lockdown_browser text,
    require_lockdown_browser_for_results text,
    require_lockdown_browser_monitor text,
    scoring_policy text,
    show_correct_answers text,
    show_correct_answers_at text,
    show_correct_answers_last_attempt text,
    shuffle_answers text,
    time_limit text,
    title text,
    unlock_at text,
    unpublished_question_count text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_group_id) REFERENCES assignment_group(id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id)
);

CREATE TABLE lti_line_item (
    id text,
    assignment_id text,
    lti_resource_link_id text,
    client_id text,
    coupled text,
    created_at text,
    extensions text,
    label text,
    resource_id text,
    score_maximum text,
    tags text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id),
    FOREIGN KEY (lti_resource_link_id) REFERENCES lti_resource_link(id)
);

CREATE TABLE learning_outcome (
    id text,
    calculation_int text,
    calculation_method text,
    context_code text,
    context_id text,
    context_type text,
    created_at text,
    data text,
    description text,
    display_name text,
    migration_id text,
    outcome_import_id text,
    short_description text,
    updated_at text,
    vendor_guid text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE assignment_submission (
    "index" text,
    assignment_id text,
    submission_type text,
    PRIMARY KEY ("index", assignment_id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id)
);

CREATE TABLE assignment (
    id text,
    assignment_group_id text,
    duplicate_of_id text,
    final_grader_id text,
    grader_section_id text,
    grading_standard_id text,
    all_day text,
    all_day_date text,
    allowed_attempts text,
    allowed_extensions text,
    annotatable_attachment_id text,
    anonymous_grading text,
    anonymous_instructor_annotations text,
    anonymous_peer_reviews text,
    automatic_peer_reviews text,
    context_id text,
    context_type text,
    could_be_locked text,
    created_at text,
    description text,
    due_at text,
    freeze_on_copy text,
    grade_group_students_individually text,
    grader_comments_visible_to_graders text,
    grader_count text,
    grader_names_visible_to_final_grader text,
    graders_anonymous_to_graders text,
    grades_published_at text,
    grading_type text,
    group_category_id text,
    important_dates text,
    intra_group_peer_reviews text,
    lock_at text,
    lti_context_id text,
    migration_id text,
    moderated_grading text,
    omit_from_final_grade text,
    only_visible_to_overrides text,
    peer_review_count text,
    peer_reviews text,
    peer_reviews_assigned text,
    peer_reviews_due_at text,
    points_possible text,
    "position" text,
    post_to_sis text,
    sis_source_id text,
    submission_downloads text,
    title text,
    turnitin_enabled text,
    turnitin_settings text,
    unlock_at text,
    updated_at text,
    vericite_enabled text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_group_id) REFERENCES assignment_group(id),
    FOREIGN KEY (duplicate_of_id) REFERENCES assignment(id),
    FOREIGN KEY (final_grader_id) REFERENCES users(id),
    FOREIGN KEY (grader_section_id) REFERENCES course_section(id),
    FOREIGN KEY (grading_standard_id) REFERENCES grading_standard(id)
);

CREATE TABLE groups (
    id text,
    account_id text,
    leader_id text,
    avatar_attachment_id text,
    context_id text,
    context_type text,
    created_at text,
    default_view text,
    deleted_at text,
    description text,
    group_category_id text,
    is_public text,
    join_level text,
    lti_context_id text,
    max_membership text,
    migration_id text,
    "name" text,
    sis_batch_id text,
    sis_source_id text,
    storage_quota text,
    updated_at text,
    uuid text,
    wiki_id text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (leader_id) REFERENCES users(id)
);

CREATE TABLE content_participation (
    id text,
    user_id text,
    content_id text,
    content_type text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE web_conference (
    id text,
    user_id text,
    conference_key text,
    conference_type text,
    context_code text,
    context_id text,
    context_type text,
    created_at text,
    description text,
    duration text,
    end_at text,
    ended_at text,
    recording_ready text,
    settings jsonb,
    start_at text,
    started_at text,
    title text,
    updated_at text,
    user_ids jsonb,
    uuid text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE enrollment (
    id text,
    course_id text,
    course_section_id text,
    user_id text,
    associated_user_id text,
    completed_at text,
    created_at text,
    end_at text,
    grade_publishing_status text,
    last_activity_at text,
    last_attended_at text,
    limit_privileges_to_course_section text,
    role_id text,
    self_enrolled text,
    sis_batch_id text,
    sis_pseudonym_id text,
    start_at text,
    total_activity_time text,
    "type" text,
    updated_at text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (course_section_id) REFERENCES course_section(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE content_shares (
    id text,
    sender_id text,
    user_id text,
    content_export_id text,
    created_at text,
    "name" text,
    read_state text,
    "type" text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (sender_id) REFERENCES users(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE learning_outcome_question_result (
    id text,
    learning_outcome_id text,
    learning_outcome_result_id text,
    assessed_at text,
    associated_asset_id text,
    associated_asset_type text,
    attempt text,
    created_at text,
    mastery text,
    original_mastery text,
    original_possible text,
    original_score text,
    possible text,
    result_percent text,
    score text,
    submitted_at text,
    title text,
    updated_at text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (learning_outcome_id) REFERENCES learning_outcome(id),
    FOREIGN KEY (learning_outcome_result_id) REFERENCES learning_outcome_result(id)
);

CREATE TABLE submission (
    id text,
    assignment_id text,
    course_id text,
    grader_id text,
    grading_period_id text,
    group_id text,
    quiz_submission_id text,
    user_id text,
    anonymous_id text,
    attachment_ids jsonb,
    attempt text,
    body text,
    cached_due_date text,
    cached_quiz_lti text,
    cached_tardiness text,
    created_at text,
    excused text,
    extra_attempts text,
    grade text,
    grade_matches_current_submission text,
    graded_anonymously text,
    graded_at text,
    last_comment_at text,
    late_policy_status text,
    lti_user_id text,
    media_comment_id text,
    media_comment_type text,
    media_object_id text,
    points_deducted text,
    posted_at text,
    processed text,
    published_grade text,
    published_score text,
    redo_request text,
    resource_link_lookup_uuid text,
    score text,
    seconds_late_override text,
    student_entered_score text,
    submission_comments_count text,
    submission_type text,
    submitted_at text,
    turnitin_data text,
    updated_at text,
    url text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignment_id) REFERENCES assignment(id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (grader_id) REFERENCES users(id),
    FOREIGN KEY (grading_period_id) REFERENCES grading_period(id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (quiz_submission_id) REFERENCES quiz_submission(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE account (
    id text,
    parent_account_id text,
    consortium_parent_account_id text,
    course_template_id text,
    created_at text,
    current_sis_batch_id text,
    default_group_storage_quota text,
    default_locale text,
    default_storage_quota text,
    default_time_zone text,
    default_user_storage_quota text,
    deleted_at text,
    integration_id text,
    lti_context_id text,
    "name" text,
    sis_source_id text,
    storage_quota text,
    updated_at text,
    uuid text,
    workflow_state text,
    -- meta_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (parent_account_id) REFERENCES account(id)
);
