CREATE TABLE gift_timeline (
    "index" text,
    gift_id text,
    occurred_at text,
    "status" text,
    PRIMARY KEY ("index", gift_id),
    FOREIGN KEY (gift_id) REFERENCES gift(id)
);

CREATE TABLE gift (
    id text,
    gift_receiver_customer_id text,
    gift_receiver_subscription_id text,
    gifter_customer_id text,
    gifter_invoice_id text,
    auto_claim text,
    claim_expiry_date text,
    gift_receiver_email text,
    gift_receiver_first_name text,
    gift_receiver_last_name text,
    gift_timelines text,
    gifter_object text,
    gifter_signature text,
    no_expiry text,
    object text,
    resource_version text,
    scheduled_at text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (gift_receiver_customer_id) REFERENCES customer(id),
    FOREIGN KEY (gift_receiver_subscription_id) REFERENCES subscription(id),
    FOREIGN KEY (gifter_customer_id) REFERENCES customer(id),
    FOREIGN KEY (gifter_invoice_id) REFERENCES invoice(id)
);

CREATE TABLE credit_note_invoice_allocation (
    invoice_id text,
    credit_note_id text,
    allocated_amount text,
    allocated_at text,
    invoice_date text,
    invoice_status text,
    PRIMARY KEY (invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id)
);

CREATE TABLE credit_note_line_item (
    id text,
    credit_note_id text,
    customer_id text,
    reference_line_item_id text,
    subscription_id text,
    amount text,
    amount_in_decimal text,
    date_from text,
    date_to text,
    description text,
    discount_amount text,
    entity_description text,
    entity_id text,
    entity_type text,
    is_taxed text,
    item_level_discount_amount text,
    object text,
    pricing_model text,
    quantity text,
    quantity_in_decimal text,
    tax_amount text,
    tax_exempt_reason text,
    tax_rate text,
    unit_amount text,
    unit_amount_in_decimal text,
    PRIMARY KEY (id, credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (reference_line_item_id) REFERENCES credit_note_line_item(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE credit_note_line_item_tax (
    "index" text,
    credit_note_id text,
    line_item_id text,
    is_non_compliance_tax text,
    is_partial_tax_applied text,
    local_currency_code text,
    tax_amount text,
    tax_amount_in_local_currency text,
    tax_juris_code text,
    tax_juris_name text,
    tax_juris_type text,
    tax_name text,
    tax_rate text,
    taxable_amount text,
    PRIMARY KEY ("index", credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id),
    FOREIGN KEY (line_item_id) REFERENCES credit_note_line_item(id)
);

CREATE TABLE credit_note_line_item_discount (
    "index" text,
    credit_note_id text,
    coupon_id text,
    line_item_id text,
    discount_amount text,
    discount_type text,
    PRIMARY KEY ("index", credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (line_item_id) REFERENCES credit_note_line_item(id)
);

CREATE TABLE credit_note_line_item_tier (
    "index" text,
    credit_note_id text,
    line_item_id text,
    ending_unit text,
    ending_unit_in_decimal text,
    quantity_used text,
    quantity_used_in_decimal text,
    starting_unit text,
    starting_unit_in_decimal text,
    unit_amount text,
    unit_amount_in_decimal text,
    PRIMARY KEY ("index", credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id),
    FOREIGN KEY (line_item_id) REFERENCES credit_note_line_item(id)
);

CREATE TABLE credit_note_discount (
    "index" text,
    credit_note_id text,
    line_item_id text,
    amount text,
    coupon_set_code text,
    description text,
    discount_percentage text,
    discount_type text,
    entity_id text,
    entity_type text,
    PRIMARY KEY ("index", credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id),
    FOREIGN KEY (line_item_id) REFERENCES credit_note_line_item(id)
);

CREATE TABLE credit_note_tax (
    "index" text,
    credit_note_id text,
    amount text,
    description text,
    "name" text,
    PRIMARY KEY ("index", credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id)
);

CREATE TABLE credit_note_linked_refund (
    txn_id text,
    credit_note_id text,
    applied_amount text,
    applied_at text,
    refund_reason_code text,
    txn_amount text,
    txn_date text,
    txn_status text,
    PRIMARY KEY (txn_id, credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id)
);

CREATE TABLE credit_note_linked_tax_withheld_refund (
    id text,
    credit_note_id text,
    amount text,
    "date" text,
    description text,
    reference_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id)
);

CREATE TABLE credit_note (
    id text,
    customer_id text,
    reference_invoice_id text,
    subscription_id text,
    amount_allocated text,
    amount_available text,
    amount_refunded text,
    base_currency_code text,
    business_entity_id text,
    channel text,
    create_reason_code text,
    credit_note_billing_address_city text,
    credit_note_billing_address_company text,
    credit_note_billing_address_country text,
    credit_note_billing_address_email text,
    credit_note_billing_address_first_name text,
    credit_note_billing_address_last_name text,
    credit_note_billing_address_line_1 text,
    credit_note_billing_address_line_2 text,
    credit_note_billing_address_line_3 text,
    credit_note_billing_address_object text,
    credit_note_billing_address_phone text,
    credit_note_billing_address_state text,
    credit_note_billing_address_state_code text,
    credit_note_billing_address_validation_status text,
    credit_note_billing_address_zip text,
    credit_note_shipping_address_city text,
    credit_note_shipping_address_company text,
    credit_note_shipping_address_country text,
    credit_note_shipping_address_email text,
    credit_note_shipping_address_first_name text,
    credit_note_shipping_address_index text,
    credit_note_shipping_address_last_name text,
    credit_note_shipping_address_line_1 text,
    credit_note_shipping_address_line_2 text,
    credit_note_shipping_address_line_3 text,
    credit_note_shipping_address_object text,
    credit_note_shipping_address_phone text,
    credit_note_shipping_address_state text,
    credit_note_shipping_address_state_code text,
    credit_note_shipping_address_validation_status text,
    credit_note_shipping_address_zip text,
    currency_code text,
    "date" text,
    deleted text,
    discounts text,
    e_invoice_id text,
    e_invoice_message text,
    e_invoice_status text,
    exchange_rate text,
    fractional_correction text,
    generated_at text,
    local_currency_code text,
    object text,
    price_type text,
    reason_code text,
    refunded_at text,
    resource_version text,
    round_off_amount text,
    "status" text,
    sub_total text,
    sub_total_in_local_currency text,
    taxes text,
    total text,
    total_in_local_currency text,
    "type" text,
    updated_at text,
    vat_number text,
    vat_number_prefix text,
    voided_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (reference_invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE coupon_set_metadata (
    "name" text,
    coupon_set_id text,
    "value" text,
    PRIMARY KEY ("name", coupon_set_id),
    FOREIGN KEY (coupon_set_id) REFERENCES coupon_set(id)
);

CREATE TABLE coupon_set (
    id text,
    coupon_id text,
    archived_count text,
    "name" text,
    redeemed_count text,
    total_count text,
    PRIMARY KEY (id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE quote_line_item (
    id text,
    quote_id text,
    customer_id text,
    reference_line_item_id text,
    subscription_id text,
    amount text,
    amount_in_decimal text,
    date_from text,
    date_to text,
    description text,
    discount_amount text,
    entity_description text,
    entity_id text,
    entity_type text,
    is_taxed text,
    item_level_discount_amount text,
    object text,
    pricing_model text,
    quantity text,
    quantity_in_decimal text,
    tax_amount text,
    tax_exempt_reason text,
    tax_rate text,
    unit_amount text,
    unit_amount_in_decimal text,
    PRIMARY KEY (id, quote_id),
    FOREIGN KEY (quote_id) REFERENCES quote(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (reference_line_item_id) REFERENCES quote_line_item(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE quote_discount (
    "index" text,
    quote_id text,
    line_item_id text,
    amount text,
    coupon_set_code text,
    description text,
    entity_id text,
    entity_type text,
    PRIMARY KEY ("index", quote_id),
    FOREIGN KEY (quote_id) REFERENCES quote(id),
    FOREIGN KEY (line_item_id) REFERENCES quote_line_item(id)
);

CREATE TABLE quote_line_item_tax (
    "index" text,
    quote_id text,
    line_item_id text,
    is_non_compliance_tax text,
    is_partial_tax_applied text,
    local_currency_code text,
    tax_amount text,
    tax_amount_in_local_currency text,
    tax_juris_code text,
    tax_juris_name text,
    tax_juris_type text,
    tax_name text,
    tax_rate text,
    taxable_amount text,
    PRIMARY KEY ("index", quote_id),
    FOREIGN KEY (quote_id) REFERENCES quote(id),
    FOREIGN KEY (line_item_id) REFERENCES quote_line_item(id)
);

CREATE TABLE quote_line_item_discount (
    "index" text,
    quote_id text,
    coupon_id text,
    line_item_id text,
    discount_amount text,
    discount_type text,
    PRIMARY KEY ("index", quote_id),
    FOREIGN KEY (quote_id) REFERENCES quote(id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (line_item_id) REFERENCES quote_line_item(id)
);

CREATE TABLE quote_line_item_tier (
    "index" text,
    quote_id text,
    line_item_id text,
    ending_unit text,
    ending_unit_in_decimal text,
    quantity_used text,
    quantity_used_in_decimal text,
    starting_unit text,
    starting_unit_in_decimal text,
    unit_amount text,
    unit_amount_in_decimal text,
    PRIMARY KEY ("index", quote_id),
    FOREIGN KEY (quote_id) REFERENCES quote(id),
    FOREIGN KEY (line_item_id) REFERENCES quote_line_item(id)
);

CREATE TABLE quote_tax (
    "index" text,
    quote_id text,
    amount text,
    description text,
    "name" text,
    PRIMARY KEY ("index", quote_id),
    FOREIGN KEY (quote_id) REFERENCES quote(id)
);

CREATE TABLE quote (
    id text,
    customer_id text,
    invoice_id text,
    subscription_id text,
    amount_due text,
    amount_paid text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country text,
    billing_address_email text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    billing_address_line_3 text,
    billing_address_object text,
    billing_address_phone text,
    billing_address_state text,
    billing_address_state_code text,
    billing_address_validation_status text,
    billing_address_zip text,
    charge_on_acceptance text,
    contract_term_end text,
    contract_term_start text,
    contract_term_termination_fee text,
    credits_applied text,
    currency_code text,
    "date" text,
    deleted text,
    discounts text,
    "name" text,
    notes text,
    object text,
    operation_type text,
    po_number text,
    price_type text,
    resource_version text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country text,
    shipping_address_email text,
    shipping_address_first_name text,
    shipping_address_index text,
    shipping_address_last_name text,
    shipping_address_line_1 text,
    shipping_address_line_2 text,
    shipping_address_line_3 text,
    shipping_address_phone text,
    shipping_address_state text,
    shipping_address_state_code text,
    shipping_address_validation_status text,
    shipping_address_zip text,
    "status" text,
    sub_total text,
    taxes text,
    total text,
    total_payable text,
    updated_at text,
    valid_till text,
    vat_number text,
    vat_number_prefix text,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_renewal_invoice_line_item (
    id text,
    customer_id text,
    subscription_estimate_id text,
    subscription_id text,
    amount text,
    date_from text,
    date_to text,
    description text,
    discount_amount text,
    entity_id text,
    entity_type text,
    is_taxed text,
    item_level_discount_amount text,
    object text,
    pricing_model text,
    quantity text,
    tax_amount text,
    unit_amount text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_estimate_id) REFERENCES subscription_renewal_estimate(subscription_estimate_id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_estimate (
    id text,
    subscription_estimate_id text,
    PRIMARY KEY (id, subscription_estimate_id),
    FOREIGN KEY (id) REFERENCES subscription(id),
    FOREIGN KEY (subscription_estimate_id) REFERENCES subscription_renewal_estimate(subscription_estimate_id)
);

CREATE TABLE subscription_renewal_invoice_estimate (
    customer_id text,
    subscription_estimate_id text,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_estimate_id) REFERENCES subscription_renewal_estimate(subscription_estimate_id)
);

CREATE TABLE subscription_renewal_credit_note_estimate (
    customer_id text,
    subscription_estimate_id text,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_estimate_id) REFERENCES subscription_renewal_estimate(subscription_estimate_id)
);

CREATE TABLE subscription_renewal_unbilled_charge_estimate (
    customer_id text,
    subscription_estimate_id text,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_estimate_id) REFERENCES subscription_renewal_estimate(subscription_estimate_id)
);

CREATE TABLE subscription_renewal_estimate (
    subscription_estimate_id text,
    customer_id text,
    created_at text,
    invoice_estimate_amount_due text,
    invoice_estimate_amount_paid text,
    invoice_estimate_credits_applied text,
    invoice_estimate_currency_code text,
    invoice_estimate_line_item_discounts jsonb,
    invoice_estimate_line_item_taxes jsonb,
    invoice_estimate_object text,
    invoice_estimate_price_type text,
    invoice_estimate_recurring text,
    invoice_estimate_round_off_amount text,
    invoice_estimate_sub_total text,
    invoice_estimate_taxes jsonb,
    invoice_estimate_total text,
    object text,
    subscription_estimate_currency_code text,
    subscription_estimate_next_billing_at text,
    subscription_estimate_object text,
    subscription_estimate_pause_date text,
    subscription_estimate_resume_date text,
    subscription_estimate_status text,
    subscription_estimate_trial_end_action text,
    PRIMARY KEY (subscription_estimate_id),
    FOREIGN KEY (subscription_estimate_id) REFERENCES subscription(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE payment_source_mandate (
    id text,
    payment_source_id text,
    subscription_id text,
    created_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (payment_source_id) REFERENCES payment_source(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE payment_source (
    id text,
    customer_id text,
    amazon_payment_agreement_id text,
    amazon_payment_email text,
    bank_account_bank_name text,
    bank_account_direct_debit_scheme text,
    bank_account_echeck_type text,
    bank_account_email text,
    bank_account_first_name text,
    bank_account_holder_type text,
    bank_account_last_4 text,
    bank_account_last_name text,
    bank_account_mandate_id text,
    bank_account_name_on_account text,
    bank_account_type text,
    boleto_email text,
    boleto_first_name text,
    boleto_last_4 text,
    boleto_last_name text,
    business_entity_id text,
    card_billing_addr_1 text,
    card_billing_addr_2 text,
    card_billing_city text,
    card_billing_country text,
    card_billing_state text,
    card_billing_state_code text,
    card_billing_zip text,
    card_brand text,
    card_expiry_month text,
    card_expiry_year text,
    card_first_name text,
    card_funding_type text,
    card_iin text,
    card_last_4 text,
    card_last_name text,
    card_masked_number text,
    card_object text,
    created_at text,
    deleted text,
    gateway text,
    gateway_account_id text,
    ip_address text,
    issuing_country text,
    klarna_pay_now_email text,
    object text,
    paypal_agreement_id text,
    paypal_email text,
    reference_id text,
    resource_version text,
    "status" text,
    "type" text,
    updated_at text,
    upi_vpa text,
    venmo_user_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE plan_applicable_addon (
    addon_id text,
    plan_id text,
    PRIMARY KEY (addon_id, plan_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan_event_based_addon (
    addon_id text,
    plan_id text,
    charge_once text,
    on_event text,
    quantity text,
    quantity_in_decimal text,
    PRIMARY KEY (addon_id, plan_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan_attached_addon (
    addon_id text,
    plan_id text,
    billing_cycles text,
    quantity text,
    quantity_in_decimal text,
    "type" text,
    PRIMARY KEY (addon_id, plan_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan_tax_provider_field (
    "index" text,
    plan_id text,
    field_id text,
    field_value text,
    provider_name text,
    PRIMARY KEY ("index", plan_id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan_tier (
    "index" text,
    plan_id text,
    ending_unit text,
    ending_unit_in_decimal text,
    price text,
    price_in_decimal text,
    starting_unit text,
    starting_unit_in_decimal text,
    PRIMARY KEY ("index", plan_id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan_metadata (
    "name" text,
    plan_id text,
    "value" text,
    PRIMARY KEY ("name", plan_id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan (
    id text,
    accounting_category_1 text,
    accounting_category_2 text,
    accounting_category_3 text,
    accounting_category_4 text,
    accounting_code text,
    addon_applicability text,
    archived_at text,
    avalara_sale_type text,
    avalara_service_type text,
    avalara_transaction_type text,
    billing_cycles text,
    channel text,
    charge_model text,
    claim_url text,
    currency_code text,
    description text,
    enabled_in_hosted_pages text,
    enabled_in_portal text,
    ending_unit text,
    free_quantity text,
    free_quantity_in_decimal text,
    giftable text,
    hsn_code text,
    invoice_name text,
    invoice_notes text,
    is_shippable text,
    "name" text,
    object text,
    period text,
    period_unit text,
    price text,
    price_in_decimal text,
    pricing_model text,
    quantity text,
    redirect_url text,
    resource_version text,
    setup_cost text,
    shipping_frequency_period text,
    shipping_frequency_period_unit text,
    show_description_in_invoices text,
    show_description_in_quotes text,
    sku text,
    starting_unit text,
    "status" text,
    tax_code text,
    tax_profile_id text,
    taxable text,
    taxjar_product_code text,
    trial_end_action text,
    trial_period text,
    trial_period_unit text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE site_migration_detail (
    entity_id text,
    entity_id_at_other_site text,
    entity_type text,
    migrated_at text,
    other_site_name text,
    "status" text,
    PRIMARY KEY (entity_id)
);

CREATE TABLE resent_order (
    order_id text,
    resent_order_id text,
    amount text,
    reason text,
    PRIMARY KEY (order_id, resent_order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (resent_order_id) REFERENCES orders(id)
);

CREATE TABLE order_line_item (
    id text,
    order_id text,
    invoice_id text,
    invoice_line_item_id text,
    amount text,
    amount_adjusted text,
    amount_paid text,
    description text,
    discount_amount text,
    entity_id text,
    entity_type text,
    fulfillment_amount text,
    fulfillment_quantity text,
    is_shippable text,
    item_level_discount_amount text,
    refundable_credits text,
    refundable_credits_issued text,
    sku text,
    "status" text,
    tax_amount text,
    unit_price text,
    PRIMARY KEY (id, order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (invoice_line_item_id) REFERENCES invoice_line_item(id)
);

CREATE TABLE order_line_item_tax (
    "index" text,
    credit_note_id text,
    line_item_id text,
    is_non_compliance_tax text,
    is_partial_tax_applied text,
    local_currency_code text,
    prorated_taxable_amount text,
    tax_amount text,
    tax_amount_in_local_currency text,
    tax_juris_code text,
    tax_juris_name text,
    tax_juris_type text,
    tax_name text,
    tax_rate text,
    taxable_amount text,
    PRIMARY KEY ("index", credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id),
    FOREIGN KEY (line_item_id) REFERENCES order_line_item(id)
);

CREATE TABLE order_line_item_discount (
    "index" text,
    order_id text,
    line_item_id text,
    discount_amount text,
    discount_type text,
    PRIMARY KEY ("index", order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (line_item_id) REFERENCES order_line_item(id)
);

CREATE TABLE order_linked_credit_note (
    id text,
    order_id text,
    amount text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES credit_note(id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE orders (
    id text,
    customer_id text,
    gift_id text,
    invoice_id text,
    original_order_id text,
    subscription_id text,
    amount_adjusted text,
    amount_paid text,
    batch_id text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country text,
    billing_address_email text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    billing_address_line_3 text,
    billing_address_phone text,
    billing_address_state text,
    billing_address_state_code text,
    billing_address_validation_status text,
    billing_address_zip text,
    cancellation_reason text,
    cancelled_at text,
    created_at text,
    created_by text,
    currency_code text,
    deleted text,
    delivered_at text,
    discount text,
    document_number text,
    fulfillment_status text,
    gift_note text,
    invoice_round_off_amount text,
    is_gifted text,
    is_resent text,
    note text,
    order_date text,
    order_type text,
    paid_on text,
    payment_status text,
    price_type text,
    reference_id text,
    refundable_credits text,
    refundable_credits_issued text,
    resend_reason text,
    resent_status text,
    resource_version text,
    rounding_adjustement text,
    shipment_carrier text,
    shipped_at text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country text,
    shipping_address_email text,
    shipping_address_first_name text,
    shipping_address_index text,
    shipping_address_last_name text,
    shipping_address_line_1 text,
    shipping_address_line_2 text,
    shipping_address_line_3 text,
    shipping_address_phone text,
    shipping_address_state text,
    shipping_address_state_code text,
    shipping_address_validation_status text,
    shipping_address_zip text,
    shipping_cut_off_date text,
    shipping_date text,
    "status" text,
    status_update_at text,
    sub_total text,
    tax text,
    total text,
    tracking_id text,
    tracking_url text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (gift_id) REFERENCES gift(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (original_order_id) REFERENCES orders(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE virtual_bank_account (
    id text,
    customer_id text,
    account_number text,
    bank_name text,
    created_at text,
    deleted text,
    email text,
    gateway text,
    gateway_account_id text,
    object text,
    reference_id text,
    resource_version text,
    routing_number text,
    scheme text,
    swift_code text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE addon_tier (
    "index" text,
    addon_id text,
    ending_unit text,
    ending_unit_in_decimal text,
    price text,
    price_in_decimal text,
    starting_unit text,
    starting_unit_in_decimal text,
    PRIMARY KEY ("index", addon_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id)
);

CREATE TABLE addon_tax_provider_field (
    "index" text,
    addon_id text,
    field_id text,
    field_value text,
    provider_name text,
    PRIMARY KEY ("index", addon_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id)
);

CREATE TABLE addon_metadata (
    "name" text,
    addon_id text,
    "value" text,
    PRIMARY KEY ("name", addon_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id)
);

CREATE TABLE addon (
    id text,
    accounting_category_1 text,
    accounting_category_2 text,
    accounting_category_3 text,
    accounting_category_4 text,
    accounting_code text,
    archived_at text,
    avalara_sale_type text,
    avalara_service_type text,
    avalara_transaction_type text,
    channel text,
    charge_type text,
    currency_code text,
    description text,
    enabled_in_portal text,
    ending_unit text,
    hsn_code text,
    included_in_mrr text,
    invoice_name text,
    invoice_notes text,
    is_shippable text,
    "name" text,
    object text,
    period text,
    period_unit text,
    price text,
    price_in_decimal text,
    pricing_model text,
    proration_type text,
    resource_version text,
    shipping_frequency_period text,
    shipping_frequency_period_unit text,
    show_description_in_invoices text,
    show_description_in_quotes text,
    sku text,
    starting_unit text,
    "status" text,
    tax_code text,
    tax_profile_id text,
    taxable text,
    taxjar_product_code text,
    unit text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE subscription_addon (
    addon_id text,
    subscription_id text,
    amount text,
    amount_in_decimal text,
    quantity text,
    quantity_in_decimal text,
    remaining_billing_cycles text,
    trial_end text,
    unit_price text,
    unit_price_in_decimal text,
    PRIMARY KEY (addon_id, subscription_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_event_based_addon (
    addon_id text,
    subscription_id text,
    charge_once text,
    on_event text,
    quantity text,
    quantity_in_decimal text,
    unit_price text,
    unit_price_in_decimal text,
    PRIMARY KEY (addon_id, subscription_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_charged_event_based_addon (
    addon_id text,
    subscription_id text,
    last_charged_at text,
    PRIMARY KEY (addon_id, subscription_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_coupon (
    coupon_id text,
    subscription_id text,
    applied_count text,
    apply_till text,
    coupon_code text,
    PRIMARY KEY (coupon_id, subscription_id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_metadata (
    "name" text,
    subscription_id text,
    "value" text,
    PRIMARY KEY ("name", subscription_id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription (
    id text,
    customer_id text,
    gift_id text,
    payment_source_id text,
    plan_id text,
    activated_at text,
    affiliate_token text,
    auto_close_invoices text,
    auto_collection text,
    base_currency_code text,
    billing_period text,
    billing_period_unit text,
    business_entity_id text,
    cancel_reason text,
    cancel_reason_code text,
    cancel_schedule_created_at text,
    cancelled_at text,
    changes_scheduled_at text,
    channel text,
    contract_term_action_at_term_end text,
    contract_term_billing_cycle text,
    contract_term_billing_cycle_on_renewal text,
    contract_term_cancellation_cutoff_period text,
    contract_term_contract_end text,
    contract_term_contract_start text,
    contract_term_created_at text,
    contract_term_id text,
    contract_term_remaining_billing_cycles text,
    contract_term_status text,
    contract_term_total_contract_value text,
    contract_term_total_contract_value_before_tax text,
    create_pending_invoices text,
    created_at text,
    created_from_ip text,
    currency_code text,
    current_term_end text,
    current_term_start text,
    deleted text,
    due_invoices_count text,
    due_since text,
    exchange_rate text,
    free_period text,
    free_period_unit text,
    has_scheduled_advance_invoices text,
    has_scheduled_changes text,
    invoice_notes text,
    mrr text,
    next_billing_at text,
    offline_payment_method text,
    override_relationship text,
    pause_date text,
    plan_amount text,
    plan_amount_in_decimal text,
    plan_free_quantity text,
    plan_free_quantity_in_decimal text,
    plan_quantity text,
    plan_quantity_in_decimal text,
    plan_unit_price text,
    plan_unit_price_in_decimal text,
    po_number text,
    referral_info_account_id text,
    referral_info_campaign_id text,
    referral_info_coupon_code text,
    referral_info_destination_url text,
    referral_info_external_campaign_id text,
    referral_info_external_reference_id text,
    referral_info_friend_offer_type text,
    referral_info_notify_referral_system text,
    referral_info_post_purchase_widget_enabled text,
    referral_info_referral_code text,
    referral_info_referral_system text,
    referral_info_referrer_id text,
    referral_info_referrer_reward_type text,
    referral_info_reward_status text,
    remaining_billing_cycles text,
    resource_version text,
    resume_date text,
    setup_fee text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country text,
    shipping_address_email text,
    shipping_address_first_name text,
    shipping_address_last_name text,
    shipping_address_line_1 text,
    shipping_address_line_2 text,
    shipping_address_line_3 text,
    shipping_address_phone text,
    shipping_address_state text,
    shipping_address_state_code text,
    shipping_address_validation_status text,
    shipping_address_zip text,
    start_date text,
    started_at text,
    "status" text,
    total_dues text,
    trial_end text,
    trial_end_action text,
    trial_start text,
    updated_at text,
    -- meta_data_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (gift_id) REFERENCES gift(id),
    FOREIGN KEY (payment_source_id) REFERENCES payment_source(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE promotional_credit (
    id text,
    customer_id text,
    amount text,
    amount_in_decimal text,
    closing_balance text,
    created_at text,
    credit_type text,
    currency_code text,
    description text,
    done_by text,
    object text,
    reference text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE event_webhook (
    id text,
    event_id text,
    "status" text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_metadata (
    "name" text,
    event_id text,
    "value" text,
    PRIMARY KEY ("name", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    api_version text,
    event_type text,
    occurred_at text,
    origin_user text,
    "source" text,
    users text,
    webhook_status text,
    PRIMARY KEY (id)
);

CREATE TABLE coupon_code (
    code text,
    coupon_id text,
    coupon_set_id text,
    coupon_set_name text,
    "status" text,
    PRIMARY KEY (code),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (coupon_set_id) REFERENCES coupon_set(id)
);

CREATE TABLE coupon_plan (
    coupon_id text,
    plan_id text,
    PRIMARY KEY (coupon_id, plan_id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE coupon_addon (
    addon_id text,
    coupon_id text,
    PRIMARY KEY (addon_id, coupon_id),
    FOREIGN KEY (addon_id) REFERENCES addon(id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE coupon_metadata (
    "name" text,
    coupon_id text,
    "value" text,
    PRIMARY KEY ("name", coupon_id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE coupon (
    id text,
    addon_constraint text,
    apply_on text,
    archived_at text,
    created_at text,
    currency_code text,
    discount_amount text,
    discount_percentage text,
    discount_type text,
    duration_type text,
    included_in_mrr text,
    invoice_name text,
    invoice_notes text,
    max_redemptions text,
    "name" text,
    period text,
    period_unit text,
    plan_constraint text,
    redemptions text,
    resource_version text,
    "status" text,
    updated_at text,
    valid_till text,
    PRIMARY KEY (id)
);

CREATE TABLE hosted_page (
    id text,
    business_entity_id text,
    checkout_info text,
    content text,
    created_at text,
    embed text,
    expires_at text,
    object text,
    pass_thru_content text,
    resource_version text,
    "state" text,
    "type" text,
    updated_at text,
    url text,
    PRIMARY KEY (id)
);

CREATE TABLE unbilled_charge_tier (
    "index" text,
    unbilled_charge_id text,
    ending_unit text,
    ending_unit_in_decimal text,
    quantity_used text,
    quantity_used_in_decimal text,
    starting_unit text,
    starting_unit_in_decimal text,
    unit_amount text,
    unit_amount_in_decimal text,
    PRIMARY KEY ("index", unbilled_charge_id),
    FOREIGN KEY (unbilled_charge_id) REFERENCES unbilled_charge(id)
);

CREATE TABLE unbilled_charge (
    id text,
    customer_id text,
    subscription_id text,
    amount text,
    amount_in_decimal text,
    currency_code text,
    date_from text,
    date_to text,
    deleted text,
    description text,
    discount_amount text,
    entity_id text,
    entity_type text,
    is_advance_charge text,
    is_voided text,
    object text,
    pricing_model text,
    quantity text,
    quantity_in_decimal text,
    unit_amount text,
    unit_amount_in_decimal text,
    updated_at text,
    voided_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE "comment" (
    id text,
    added_by text,
    created_at text,
    entity_id text,
    entity_type text,
    notes text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE invoice_issued_credit_note (
    cn_id text,
    invoice_id text,
    PRIMARY KEY (cn_id),
    FOREIGN KEY (cn_id) REFERENCES credit_note(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_adjustment_credit_note (
    cn_id text,
    invoice_id text,
    PRIMARY KEY (cn_id),
    FOREIGN KEY (cn_id) REFERENCES credit_note(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_dunning_attempt (
    "index" text,
    invoice_id text,
    transaction_id text,
    attempt text,
    created_at text,
    dunning_type text,
    txn_amount text,
    txn_status text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE invoice_applied_credit (
    cn_id text,
    invoice_id text,
    applied_amount text,
    applied_at text,
    cn_create_reason_code text,
    cn_date text,
    cn_reason_code text,
    cn_status text,
    PRIMARY KEY (cn_id),
    FOREIGN KEY (cn_id) REFERENCES credit_note(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_line_item (
    id text,
    invoice_id text,
    customer_id text,
    subscription_id text,
    amount text,
    amount_in_decimal text,
    date_from text,
    date_to text,
    description text,
    discount_amount text,
    entity_description text,
    entity_id text,
    entity_type text,
    is_taxed text,
    item_level_discount_amount text,
    object text,
    pricing_model text,
    quantity text,
    quantity_in_decimal text,
    tax_amount text,
    tax_exempt_reason text,
    tax_rate text,
    unit_amount text,
    unit_amount_in_decimal text,
    PRIMARY KEY (id, invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE invoice_line_item_tax (
    "index" text,
    invoice_id text,
    line_item_id text,
    is_non_compliance_tax text,
    is_partial_tax_applied text,
    local_currency_code text,
    prorated_taxable_amount text,
    tax_amount text,
    tax_amount_in_local_currency text,
    tax_juris_code text,
    tax_juris_name text,
    tax_juris_type text,
    tax_name text,
    tax_rate text,
    taxable_amount text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (line_item_id) REFERENCES invoice_line_item(id)
);

CREATE TABLE invoice_tax (
    "index" text,
    invoice_id text,
    amount text,
    description text,
    "name" text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_line_item_discount (
    "index" text,
    invoice_id text,
    coupon_id text,
    line_item_id text,
    discount_amount text,
    discount_type text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (line_item_id) REFERENCES invoice_line_item(id)
);

CREATE TABLE invoice_line_item_tier (
    line_item_id text,
    invoice_id text,
    ending_unit text,
    ending_unit_in_decimal text,
    quantity_used text,
    quantity_used_in_decimal text,
    starting_unit text,
    starting_unit_in_decimal text,
    unit_amount text,
    unit_amount_in_decimal text,
    PRIMARY KEY (line_item_id),
    FOREIGN KEY (line_item_id) REFERENCES invoice_line_item(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_discount (
    "index" text,
    invoice_id text,
    line_item_id text,
    amount text,
    coupon_set_code text,
    description text,
    entity_id text,
    entity_type text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (line_item_id) REFERENCES invoice_line_item(id)
);

CREATE TABLE invoice_linked_payment (
    txn_id text,
    invoice_id text,
    applied_amount text,
    applied_at text,
    txn_amount text,
    txn_date text,
    txn_status text,
    PRIMARY KEY (txn_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_linked_order (
    id text,
    invoice_id text,
    batch_id text,
    created_at text,
    document_number text,
    fulfillment_status text,
    order_type text,
    reference_id text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES orders(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_note (
    "index" text,
    invoice_id text,
    entity_id text,
    entity_type text,
    note text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_linked_taxes_withheld (
    id text,
    invoice_id text,
    amount text,
    "date" text,
    description text,
    reference_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice (
    id text,
    customer_id text,
    subscription_id text,
    amount_adjusted text,
    amount_due text,
    amount_paid text,
    amount_to_collect text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country text,
    billing_address_email text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    billing_address_line_3 text,
    billing_address_object text,
    billing_address_phone text,
    billing_address_state text,
    billing_address_state_code text,
    billing_address_validation_status text,
    billing_address_zip text,
    channel text,
    credits_applied text,
    currency_code text,
    "date" text,
    deleted text,
    due_date text,
    dunning_status text,
    einvoice_id text,
    einvoice_message text,
    einvoice_reference_number text,
    einvoice_status text,
    exchange_rate text,
    expected_payment_date text,
    first_invoice text,
    generated_at text,
    has_advance_charges text,
    is_gifted text,
    is_written_off text,
    local_currency_code text,
    local_currency_exchange_rate text,
    net_term_days text,
    new_sales_amount text,
    next_retry_at text,
    notes text,
    paid_at text,
    payment_owner text,
    po_number text,
    price_type text,
    recurring text,
    resource_version text,
    round_off_amount text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country text,
    shipping_address_email text,
    shipping_address_first_name text,
    shipping_address_index text,
    shipping_address_last_name text,
    shipping_address_line_1 text,
    shipping_address_line_2 text,
    shipping_address_line_3 text,
    shipping_address_object text,
    shipping_address_phone text,
    shipping_address_state text,
    shipping_address_state_code text,
    shipping_address_validation_status text,
    shipping_address_zip text,
    site_details_at_creation_organization_address_city text,
    site_details_at_creation_organization_address_country_code text,
    site_details_at_creation_organization_address_line_1 text,
    site_details_at_creation_organization_address_state text,
    site_details_at_creation_organization_address_zip text,
    site_details_at_creation_organization_email text,
    site_details_at_creation_organization_name text,
    site_details_at_creation_organization_phone text,
    site_details_at_creation_organization_website text,
    site_details_at_creation_timezone text,
    statement_descriptor text,
    statement_descriptor_id text,
    "status" text,
    sub_total text,
    sub_total_in_local_currency text,
    tax text,
    tax_category text,
    tax_origin_country text,
    tax_origin_registration_number text,
    tax_override_reason text,
    term_finalized text,
    total text,
    total_in_local_currency text,
    updated_at text,
    use_for_proration text,
    vat_number text,
    vat_number_prefix text,
    void_reason_code text,
    voided_at text,
    write_off_amount text,
    write_off_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE transaction_refund (
    refund_transaction_id text,
    transaction_id text,
    PRIMARY KEY (refund_transaction_id, transaction_id),
    FOREIGN KEY (refund_transaction_id) REFERENCES "transaction"(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE transaction_linked_payment (
    linked_payments_id text,
    transaction_id text,
    PRIMARY KEY (linked_payments_id, transaction_id),
    FOREIGN KEY (linked_payments_id) REFERENCES "transaction"(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE transaction_invoice (
    invoice_id text,
    transaction_id text,
    applied_amount text,
    applied_at text,
    PRIMARY KEY (invoice_id, transaction_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE transaction_linked_credit_note (
    cn_id text,
    transaction_id text,
    applied_amount text,
    applied_at text,
    cn_reason_code text,
    PRIMARY KEY (cn_id, transaction_id),
    FOREIGN KEY (cn_id) REFERENCES credit_note(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE "transaction" (
    id text,
    customer_id text,
    payment_source_id text,
    reference_authorization_id text,
    reference_transaction_id text,
    refunded_txn_id text,
    reversal_transaction_id text,
    subscription_id text,
    amount text,
    amount_capturable text,
    amount_unused text,
    authorization_reason text,
    currency_code text,
    custom_payment_method_id text,
    custom_payment_method_name text,
    "date" text,
    deleted text,
    error_cause_customer_message text,
    error_cause_id text,
    error_cause_merchant_message text,
    error_code text,
    error_detail_decline_code text,
    error_detail_decline_message text,
    error_detail_error_category text,
    error_detail_error_code text,
    error_detail_error_field text,
    error_detail_error_message text,
    error_detail_network_error_code text,
    error_detail_network_error_message text,
    error_detail_processor_error_code text,
    error_detail_processor_error_message text,
    error_detail_recommendation_code text,
    error_detail_recommendation_message text,
    error_detail_request_id text,
    error_text text,
    exchange_rate text,
    fraud_flag text,
    fraud_reason text,
    gateway text,
    gateway_account_id text,
    id_at_gateway text,
    iin text,
    initiator_type text,
    last_4 text,
    masked_card_number text,
    merchant_reference_id text,
    payment_method text,
    payment_method_details text,
    reference_number text,
    resource_version text,
    settled_at text,
    "status" text,
    three_d_secure text,
    "type" text,
    updated_at text,
    voided_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (payment_source_id) REFERENCES payment_source(id),
    FOREIGN KEY (reference_authorization_id) REFERENCES "transaction"(id),
    FOREIGN KEY (reference_transaction_id) REFERENCES "transaction"(id),
    FOREIGN KEY (refunded_txn_id) REFERENCES "transaction"(id),
    FOREIGN KEY (reversal_transaction_id) REFERENCES "transaction"(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE customer_referral_url (
    customer_id text,
    created_at text,
    referral_account_id text,
    referral_campaign_id text,
    referral_external_campaign_id text,
    referral_sharing_url text,
    referral_system text,
    updated_at text,
    PRIMARY KEY (customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_contact (
    id text,
    customer_id text,
    email text,
    enabled text,
    first_name text,
    label text,
    last_name text,
    phone text,
    send_account_email text,
    send_billing_email text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_balance (
    "index" text,
    customer_id text,
    currency_code text,
    excess_payments text,
    promotional_credits text,
    refundable_credits text,
    unbilled_charges text,
    PRIMARY KEY ("index", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_tax_provider_field (
    "index" text,
    customer_id text,
    field_id text,
    field_value text,
    provider_name text,
    PRIMARY KEY ("index", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_entity_identifier (
    id text,
    customer_id text,
    scheme text,
    standard text,
    "value" text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_metadata (
    "name" text,
    customer_id text,
    "value" text,
    PRIMARY KEY ("name", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer (
    id text,
    backup_payment_source_id text,
    primary_payment_source_id text,
    allow_direct_debit text,
    auto_close_invoices text,
    auto_collection text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country text,
    billing_address_email text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    billing_address_line_3 text,
    billing_address_object text,
    billing_address_phone text,
    billing_address_state text,
    billing_address_state_code text,
    billing_address_validation_status text,
    billing_address_zip text,
    billing_date text,
    billing_date_mode text,
    billing_day_of_week text,
    billing_day_of_week_mode text,
    billing_month text,
    business_customer_without_vat_number text,
    business_entity_id text,
    channel text,
    child_account_access_portal_download_invoices text,
    child_account_access_portal_edit_subscriptions text,
    child_account_access_send_invoice_emails text,
    child_account_access_send_payment_emails text,
    child_account_access_send_subscription_emails text,
    client_profile_id text,
    company text,
    consolidated_invoicing text,
    created_at text,
    created_from_ip text,
    customer_type text,
    deleted text,
    einvoicing_method text,
    email text,
    entity_code text,
    entity_identifier_scheme text,
    entity_identifier_standard text,
    excess_payments text,
    exempt_number text,
    exemption_details text,
    first_name text,
    fraud_flag text,
    invoice_notes text,
    is_einvoice_enabled text,
    is_location_valid text,
    last_name text,
    locale text,
    net_term_days text,
    offline_payment_method text,
    parent_account_access_portal_download_child_invoices text,
    parent_account_access_portal_edit_child_subscriptions text,
    parent_account_access_send_invoice_emails text,
    parent_account_access_send_payment_emails text,
    parent_account_access_send_subscription_emails text,
    phone text,
    pii_cleared text,
    preferred_currency_code text,
    promotional_credits text,
    refundable_credits text,
    registered_for_gst text,
    relationship_invoice_owner_id text,
    relationship_parent_id text,
    relationship_payment_owner_id text,
    resource_version text,
    taxability text,
    unbilled_charges text,
    updated_at text,
    use_default_hierarchy_settings text,
    vat_number text,
    vat_number_prefix text,
    vat_number_status text,
    vat_number_validated_time text,
    -- meta_data_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (backup_payment_source_id) REFERENCES payment_source(id),
    FOREIGN KEY (primary_payment_source_id) REFERENCES payment_source(id)
);
