CREATE TABLE quote_line_item (
    id text,
    product_id text,
    product_option_id text,
    transaction_id text,
    barcode text,
    code text,
    created_date text,
    discount double precision,
    holding_qty double precision,
    integration_ref text,
    line_comments text,
    "name" text,
    option_1 text,
    option_2 text,
    option_3 text,
    parent_id text,
    qty double precision,
    qty_shipped double precision,
    size_codes text,
    sort text,
    style_code text,
    unit_cost double precision,
    unit_price double precision,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id),
    FOREIGN KEY (transaction_id) REFERENCES quote(id)
);

CREATE TABLE quote (
    id text,
    branch_id text,
    acceptance_date text,
    alternative_tax_rate text,
    billing_address_1 text,
    billing_address_2 text,
    billing_city text,
    billing_company text,
    billing_country text,
    billing_first_name text,
    billing_last_name text,
    billing_postal_code text,
    billing_state text,
    company text,
    cost_center text,
    created_by text,
    created_date text,
    currency_code text,
    currency_rate double precision,
    currency_symbol text,
    customer_order_no text,
    delivery_address_1 text,
    delivery_address_2 text,
    delivery_city text,
    delivery_company text,
    delivery_country text,
    delivery_first_name text,
    delivery_instructions text,
    delivery_last_name text,
    delivery_postal_code text,
    delivery_state text,
    discount_description text,
    discount_total double precision,
    email text,
    estimated_delivery_date text,
    expected_order_date text,
    fax text,
    first_name text,
    freight_description text,
    freight_total double precision,
    internal_comments text,
    is_approved boolean,
    last_name text,
    member_alternative_tax_rate text,
    member_cost_center text,
    member_email text,
    member_id text,
    mobile text,
    modified_date text,
    payment_terms text,
    phone text,
    probability double precision,
    processed_by text,
    product_total double precision,
    project_name text,
    reference text,
    sales_person_email text,
    sales_person_id text,
    "source" text,
    stage text,
    "status" text,
    surcharge double precision,
    surcharge_description text,
    tax_rate double precision,
    tax_status text,
    total double precision,
    tracking_code text,
    voucher_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id)
);

CREATE TABLE payment (
    id text,
    branch_id text,
    order_id text,
    amount double precision,
    batch_reference text,
    comments text,
    created_date text,
    is_authorized boolean,
    method text,
    modified_date text,
    order_ref text,
    order_type text,
    payment_date text,
    payment_imported_ref text,
    reconcile_date text,
    transaction_ref text,
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (order_id) REFERENCES sales_order(id)
);

CREATE TABLE secondary_contact (
    id text,
    contact_id text,
    company text,
    email text,
    first_name text,
    job_title text,
    last_name text,
    mobile text,
    phone text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact_id) REFERENCES contact(id)
);

CREATE TABLE contact (
    id text,
    account_number text,
    accounting_integration_id_quick_books_desktop text,
    accounting_integration_id_quick_books_online text,
    accounting_integration_id_xero text,
    accounts_first_name text,
    accounts_last_name text,
    accounts_phone text,
    address_1 text,
    address_2 text,
    balance_owing double precision,
    billing_company text,
    billing_cost_center text,
    billing_email text,
    billing_id text,
    city text,
    company text,
    cost_center text,
    country text,
    created_date text,
    credit_limit double precision,
    email text,
    fax text,
    first_name text,
    groups text,
    integration_ref text,
    is_active boolean,
    job_title text,
    last_name text,
    mobile text,
    modified_date text,
    notes text,
    on_hold boolean,
    payment_terms text,
    percentage_off double precision,
    phone text,
    post_code text,
    postal_address_1 text,
    postal_address_2 text,
    postal_city text,
    postal_country text,
    postal_post_code text,
    postal_state text,
    price_column text,
    sales_person_id text,
    stages text,
    "state" text,
    sub_group text,
    tax_number text,
    tax_status text,
    "type" text,
    website text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE stock (
    _fivetran_id text,
    branch_id text,
    product_id text,
    product_option_id text,
    available double precision,
    barcode text,
    branch_name text,
    code text,
    holding double precision,
    incoming double precision,
    modified_date text,
    open_sales double precision,
    option_1 text,
    option_2 text,
    option_3 text,
    product_name text,
    "size" text,
    stock_on_hand double precision,
    style_code text,
    virtual double precision,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id)
);

CREATE TABLE branch_transfer_line_item_size (
    _fivetran_id text,
    branch_transfer_line_item_id text,
    barcode text,
    code text,
    "name" text,
    qty double precision,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (branch_transfer_line_item_id) REFERENCES branch_transfer_line_item(id)
);

CREATE TABLE branch_transfer_line_item (
    id text,
    branch_transfer_id text,
    product_id text,
    product_option_id text,
    transaction_id text,
    code text,
    created_date text,
    integration_ref text,
    "name" text,
    option_1 text,
    option_2 text,
    option_3 text,
    parent_id text,
    qty double precision,
    qty_transferred text,
    sort text,
    unit_cost double precision,
    PRIMARY KEY (id, branch_transfer_id),
    FOREIGN KEY (branch_transfer_id) REFERENCES branch_transfer(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id),
    FOREIGN KEY (transaction_id) REFERENCES purchase_order(id)
);

CREATE TABLE branch_transfer (
    id text,
    approved_by text,
    created_by text,
    destination_branch_id text,
    processed_by text,
    source_branch_id text,
    approval_date text,
    branch_email text,
    company text,
    created_date text,
    delivery_instructions text,
    dispatched_date text,
    email text,
    fax text,
    first_name text,
    internal_comments text,
    is_approved text,
    last_name text,
    mobile text,
    modified_date text,
    phone text,
    product_total text,
    project_name text,
    received_date text,
    reference text,
    "source" text,
    stage text,
    tracking_code text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (approved_by) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (destination_branch_id) REFERENCES branch(id),
    FOREIGN KEY (processed_by) REFERENCES users(id),
    FOREIGN KEY (source_branch_id) REFERENCES branch(id)
);

CREATE TABLE serial_number (
    id text,
    branch_id text,
    product_id text,
    product_option_id text,
    available double precision,
    code text,
    holding_group text,
    line_item_id text,
    serial_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id)
);

CREATE TABLE sales_order_line_item (
    id text,
    product_id text,
    product_option_id text,
    transaction_id text,
    account_code text,
    barcode text,
    code text,
    created_date text,
    discount double precision,
    holding_qty double precision,
    integration_ref text,
    line_comments text,
    "name" text,
    option_1 text,
    option_2 text,
    option_3 text,
    parent_id text,
    qty double precision,
    qty_shipped double precision,
    size_codes text,
    sizes jsonb,
    sort text,
    stock_control text,
    style_code text,
    unit_cost double precision,
    unit_price double precision,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id),
    FOREIGN KEY (transaction_id) REFERENCES sales_order(id)
);

CREATE TABLE sales_order (
    id text,
    branch_id text,
    created_by text,
    processed_by text,
    accounting_attribute_accounting_import_status text,
    accounting_attribute_import_date text,
    alternative_tax_rate text,
    billing_address_1 text,
    billing_address_2 text,
    billing_city text,
    billing_company text,
    billing_country text,
    billing_first_name text,
    billing_last_name text,
    billing_postal_code text,
    billing_state text,
    branch_email text,
    company text,
    cost_center text,
    created_date text,
    currency_code text,
    currency_rate double precision,
    currency_symbol text,
    customer_order_no text,
    delivery_address_1 text,
    delivery_address_2 text,
    delivery_city text,
    delivery_company text,
    delivery_country text,
    delivery_first_name text,
    delivery_instructions text,
    delivery_last_name text,
    delivery_postal_code text,
    delivery_state text,
    department_number text,
    discount_description text,
    discount_total double precision,
    dispatched_date text,
    distribution_branch_id text,
    distribution_center text,
    edi_status text,
    email text,
    estimated_delivery_date text,
    fax text,
    first_name text,
    freight_description text,
    freight_total double precision,
    internal_comments text,
    invoice_date text,
    invoice_number text,
    is_approved boolean,
    is_void boolean,
    last_name text,
    logistics_carrier text,
    logistics_status text,
    member_alternative_tax_rate text,
    member_cost_center text,
    member_email text,
    member_id text,
    mobile text,
    modified_date text,
    payment_terms text,
    phone text,
    product_total double precision,
    project_name text,
    reference text,
    sales_person_email text,
    sales_person_id text,
    "source" text,
    stage text,
    "status" text,
    store_location_number text,
    surcharge double precision,
    surcharge_description text,
    tax_rate double precision,
    tax_status text,
    total double precision,
    tracking_code text,
    voucher_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (processed_by) REFERENCES users(id)
);

CREATE TABLE product_image (
    _fivetran_id text,
    product_id text,
    link text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_category_ids (
    category_id text,
    product_id text,
    PRIMARY KEY (category_id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_option (
    id text,
    product_id text,
    barcode text,
    code text,
    created_date text,
    image text,
    modified_date text,
    option_1 text,
    option_2 text,
    option_3 text,
    option_weight double precision,
    price_columns_cost_cad text,
    price_columns_cost_eur text,
    price_columns_cost_usd text,
    price_columns_price_aud text,
    price_columns_price_cad text,
    price_columns_retail_usd text,
    price_columns_special_price text,
    price_columns_vip_usd text,
    price_columns_wholesale_usd text,
    product_option_barcode text,
    product_option_code text,
    product_option_size_barcode text,
    product_option_size_code text,
    retail_price double precision,
    "size" text,
    special_days text,
    special_price double precision,
    specials_start_date text,
    "status" text,
    stock_available double precision,
    stock_on_hand double precision,
    supplier_code text,
    vip_price double precision,
    wholesale_price double precision,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    brand text,
    category text,
    category_id_array jsonb,
    channels text,
    created_date text,
    description text,
    height double precision,
    import_customs_duty text,
    length double precision,
    modified_date text,
    "name" text,
    option_label_1 text,
    option_label_2 text,
    option_label_3 text,
    order_type text,
    pdf_description text,
    pdf_upload text,
    product_subtype text,
    product_type text,
    project_name text,
    purchases_account text,
    sales_account text,
    "status" text,
    stock_control text,
    style_code text,
    sub_category text,
    supplier_id text,
    volume double precision,
    weight double precision,
    width double precision,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE branch_location_bin (
    "index" text,
    branch_id text,
    branch_location_zone text,
    bin text,
    PRIMARY KEY ("index", branch_id, branch_location_zone),
    FOREIGN KEY (branch_id) REFERENCES branch_location(branch_id),
    FOREIGN KEY (branch_location_zone) REFERENCES branch_location("zone")
);

CREATE TABLE branch_location (
    "zone" text,
    branch_id text,
    PRIMARY KEY ("zone", branch_id),
    FOREIGN KEY (branch_id) REFERENCES branch(id)
);

CREATE TABLE branch (
    id text,
    account_number text,
    address_1 text,
    address_2 text,
    branch_type text,
    city text,
    company text,
    country text,
    created_date text,
    email text,
    fax text,
    first_name text,
    integration_ref text,
    is_active boolean,
    job_title text,
    last_name text,
    mobile text,
    modified_date text,
    notes text,
    phone text,
    post_code text,
    postal_address_1 text,
    postal_address_2 text,
    postal_city text,
    postal_country text,
    postal_post_code text,
    postal_state text,
    "state" text,
    stock_control_options text,
    tax_status text,
    website text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE production_job (
    id text,
    branch_id text,
    completed_by text,
    created_by text,
    company text,
    completed_date text,
    created_date text,
    due_date text,
    is_approved boolean,
    modified_date text,
    production_notes text,
    project_name text,
    reference text,
    "source" text,
    total_cost double precision,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (completed_by) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE adjustment_line_item (
    id text,
    adjustment_id text,
    product_id text,
    product_option_id text,
    transaction_id text,
    account text,
    code text,
    created_date text,
    holding_qty double precision,
    integration_ref text,
    "name" text,
    option_1 text,
    option_2 text,
    option_3 text,
    parent_id text,
    qty double precision,
    qty_adjusted double precision,
    sort text,
    unit_cost double precision,
    PRIMARY KEY (id),
    FOREIGN KEY (adjustment_id) REFERENCES adjustment(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id),
    FOREIGN KEY (transaction_id) REFERENCES sales_order(id)
);

CREATE TABLE adjustment (
    id text,
    branch_id text,
    created_by_user_id text,
    processed_by_user_id text,
    adjust_in_accounting_system text,
    adjustment_reason text,
    alternative_account_code text,
    completed_date text,
    created_date text,
    is_approved boolean,
    modified_date text,
    product_total double precision,
    reference text,
    "source" text,
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (processed_by_user_id) REFERENCES users(id)
);

CREATE TABLE purchase_order_line_item (
    id text,
    product_id text,
    product_option_id text,
    transaction_id text,
    account_code text,
    barcode text,
    code text,
    created_date text,
    discount double precision,
    holding_qty double precision,
    integration_ref text,
    line_comments text,
    "name" text,
    option_1 text,
    option_2 text,
    option_3 text,
    parent_id text,
    qty double precision,
    qty_shipped double precision,
    size_codes text,
    sort text,
    style_code text,
    unit_price double precision,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id),
    FOREIGN KEY (transaction_id) REFERENCES purchase_order(id)
);

CREATE TABLE purchase_order (
    id text,
    branch_id text,
    accounting_attribute_accounting_import_status text,
    accounting_attribute_import_date text,
    alternative_tax_rate text,
    billing_address_1 text,
    billing_address_2 text,
    billing_city text,
    billing_company text,
    billing_country text,
    billing_first_name text,
    billing_last_name text,
    billing_postal_code text,
    billing_state text,
    branch_email text,
    company text,
    cost_center text,
    created_by text,
    created_date text,
    currency_code text,
    currency_rate double precision,
    currency_symbol text,
    customer_order_no text,
    delivery_address_1 text,
    delivery_address_2 text,
    delivery_city text,
    delivery_company text,
    delivery_country text,
    delivery_first_name text,
    delivery_instructions text,
    delivery_last_name text,
    delivery_postal_code text,
    delivery_state text,
    discount_description text,
    discount_total double precision,
    email text,
    estimated_arrival_date text,
    estimated_delivery_date text,
    fax text,
    first_name text,
    freight_description text,
    freight_total double precision,
    fully_received_date text,
    internal_comments text,
    invoice_date text,
    is_approved boolean,
    is_void boolean,
    last_name text,
    logistics_carrier text,
    logistics_status text,
    member_alternative_tax_rate text,
    member_cost_center text,
    member_email text,
    member_id text,
    mobile text,
    modified_date text,
    payment_terms text,
    phone text,
    port text,
    processed_by text,
    product_total double precision,
    project_name text,
    reference text,
    sales_person_email text,
    sales_person_id text,
    "source" text,
    stage text,
    "status" text,
    supplier_acceptance_date text,
    supplier_invoice_reference text,
    surcharge double precision,
    surcharge_description text,
    tax_rate double precision,
    tax_status text,
    total double precision,
    tracking_code text,
    voucher_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id)
);

CREATE TABLE product_category (
    id text,
    description text,
    image text,
    is_active boolean,
    "name" text,
    parent_id text,
    sort text,
    PRIMARY KEY (id)
);

CREATE TABLE credit_note_line_item (
    id text,
    credit_note_id text,
    product_id text,
    product_option_id text,
    transaction_id text,
    account_code text,
    barcode text,
    code text,
    created_date text,
    discount double precision,
    integration_ref text,
    line_comments text,
    "name" text,
    option_1 text,
    option_2 text,
    option_3 text,
    parent_id text,
    qty double precision,
    qty_shipped double precision,
    size_codes text,
    sort text,
    style_code text,
    unit_cost double precision,
    unit_price double precision,
    PRIMARY KEY (id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id),
    FOREIGN KEY (transaction_id) REFERENCES sales_order(id)
);

CREATE TABLE credit_note (
    id text,
    branch_id text,
    created_by text,
    processed_by text,
    accounting_attribute_accounting_import_status text,
    accounting_attribute_import_date text,
    alternative_account_code text,
    billing_address_1 text,
    billing_address_2 text,
    billing_city text,
    billing_company text,
    billing_country text,
    billing_first_name text,
    billing_last_name text,
    billing_postal_code text,
    billing_state text,
    company text,
    completed_date text,
    created_date text,
    credit_note_date text,
    credit_note_number text,
    currency_code text,
    currency_rate double precision,
    currency_symbol text,
    customer_report text,
    delivery_address_1 text,
    delivery_address_2 text,
    delivery_city text,
    delivery_company text,
    delivery_country text,
    delivery_first_name text,
    delivery_last_name text,
    delivery_postal_code text,
    delivery_state text,
    discount_description text,
    discount_total double precision,
    email text,
    fax text,
    first_name text,
    freight_description text,
    freight_total double precision,
    internal_comments text,
    is_approved boolean,
    last_name text,
    logistics_carrier text,
    logistics_status text,
    member_email text,
    member_id text,
    mobile text,
    modified_date text,
    phone text,
    product_total double precision,
    project_name text,
    reference text,
    sales_person_id text,
    sales_reference text,
    "source" text,
    "status" text,
    surcharge double precision,
    surcharge_description text,
    tax_rate double precision,
    tax_status text,
    total double precision,
    tracking_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (processed_by) REFERENCES users(id)
);

CREATE TABLE bom_master_component (
    id text,
    bom_master_id text,
    product_id text,
    product_option_id text,
    code text,
    quantity text,
    sort text,
    unit_cost text,
    PRIMARY KEY (id, bom_master_id),
    FOREIGN KEY (bom_master_id) REFERENCES bom_master(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id)
);

CREATE TABLE bom_master (
    id text,
    created_by text,
    modified_by text,
    product_id text,
    product_option_id text,
    created_date text,
    modified_date text,
    product_code text,
    product_notes text,
    product_quantity text,
    product_sort text,
    product_unit_cost text,
    product_uu_id text,
    production_note text,
    reference text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (modified_by) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_option_id) REFERENCES product_option(id)
);

CREATE TABLE voucher (
    _fivetran_id text,
    amount double precision,
    code text,
    created_date text,
    customer_email text,
    customer_id text,
    description text,
    expiry_date text,
    redeemed_amount double precision,
    redeemed_count text,
    redeemed_count_limit text,
    "status" text,
    "type" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE users (
    id bigint,
    email text,
    first_name text,
    is_active boolean,
    job_title text,
    last_name text,
    PRIMARY KEY (id)
);
