CREATE TABLE new_stock_line (
    product_id text,
    stock_adjustment_id text,
    stock_take_number text,
    batch_sn text,
    "comment" text,
    expiry_date text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    received_date text,
    unit_cost text,
    PRIMARY KEY (product_id, stock_adjustment_id, stock_take_number),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (stock_adjustment_id) REFERENCES stock_adjustment(id),
    FOREIGN KEY (stock_take_number) REFERENCES stock_adjustment(stock_take_number)
);

CREATE TABLE stock_adjustment_transaction (
    stock_adjustment_id text,
    stock_take_number text,
    transaction_id text,
    PRIMARY KEY (stock_adjustment_id, stock_take_number, transaction_id),
    FOREIGN KEY (stock_adjustment_id) REFERENCES stock_adjustment(id),
    FOREIGN KEY (stock_take_number) REFERENCES stock_adjustment(stock_take_number),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE stock_adjustment (
    id text,
    stock_take_number text,
    account text,
    effective_date text,
    existing_stock_line jsonb,
    reference text,
    "status" text,
    PRIMARY KEY (id, stock_take_number),
    FOREIGN KEY (stock_take_number) REFERENCES stock_take(stock_take_number)
);

CREATE TABLE chart_of_account (
    code text,
    bank_account_number text,
    class text,
    description text,
    display_name text,
    for_payments text,
    "name" text,
    old_code text,
    "status" text,
    system_account text,
    system_account_code text,
    "type" text,
    PRIMARY KEY (code)
);

CREATE TABLE supplier_contacts (
    id text,
    supplier_id text,
    "comment" text,
    defaults text,
    email text,
    fax text,
    include_in_email text,
    mobile_phone text,
    "name" text,
    phone text,
    website text,
    PRIMARY KEY (id, supplier_id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE supplier_address (
    id text,
    supplier_id text,
    city text,
    country text,
    default_for_type text,
    line_1 text,
    line_2 text,
    postcode text,
    "state" text,
    "type" text,
    PRIMARY KEY (id, supplier_id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE supplier (
    id text,
    account_payable text,
    additional_attribute_1 text,
    additional_attribute_10 text,
    additional_attribute_2 text,
    additional_attribute_3 text,
    additional_attribute_4 text,
    additional_attribute_5 text,
    additional_attribute_6 text,
    additional_attribute_7 text,
    additional_attribute_8 text,
    additional_attribute_9 text,
    attribute_set text,
    comments text,
    currency text,
    discount text,
    last_modified_on text,
    "name" text,
    payment_term text,
    "status" text,
    tax_number text,
    tax_rule text,
    PRIMARY KEY (id)
);

CREATE TABLE stock_transfer_line (
    product_id text,
    stock_transfer_number text,
    stock_transfer_task_id text,
    batch_sn text,
    "comment" text,
    expiry_date text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity_available text,
    quantity_on_hand text,
    transfer_quantity text,
    PRIMARY KEY (product_id, stock_transfer_number, stock_transfer_task_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (stock_transfer_number) REFERENCES stock_transfer(number),
    FOREIGN KEY (stock_transfer_task_id) REFERENCES stock_transfer(task_id)
);

CREATE TABLE stock_transfer_order_line (
    product_id text,
    stock_transfer_number text,
    stock_transfer_task_id text,
    batch_sn text,
    "comment" text,
    expiry_date text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity_available text,
    quantity_on_hand text,
    transfer_quantity text,
    PRIMARY KEY (product_id, stock_transfer_number, stock_transfer_task_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (stock_transfer_number) REFERENCES stock_transfer(number),
    FOREIGN KEY (stock_transfer_task_id) REFERENCES stock_transfer(task_id)
);

CREATE TABLE stock_transfer (
    number text,
    task_id text,
    completion_date text,
    cost_distribution_type text,
    departure_date text,
    destination text,
    from_location text,
    in_transit_account text,
    manual_journal jsonb,
    reference text,
    required_by_date text,
    skip_order text,
    "source" text,
    "status" text,
    to_location text,
    PRIMARY KEY (number, task_id)
);

CREATE TABLE non_zero_stock_on_hand_product (
    product_id text,
    stock_take_number text,
    stock_take_task_id text,
    adjustment text,
    available text,
    batch_sn text,
    "comment" text,
    expiry_date text,
    image_content_type text,
    image_download_url text,
    image_file_name text,
    image_id text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity_on_hand text,
    unit text,
    PRIMARY KEY (product_id, stock_take_number, stock_take_task_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (stock_take_number) REFERENCES stock_take(stock_take_number),
    FOREIGN KEY (stock_take_task_id) REFERENCES stock_take(task_id)
);

CREATE TABLE zero_stock_on_hand_product (
    product_id text,
    stock_take_number text,
    stock_take_task_id text,
    adjustment text,
    available text,
    batch_sn text,
    "comment" text,
    expiry_date text,
    image_content_type text,
    image_download_url text,
    image_file_name text,
    image_id text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity_on_hand text,
    unit text,
    PRIMARY KEY (product_id, stock_take_number, stock_take_task_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (stock_take_number) REFERENCES stock_take(stock_take_number),
    FOREIGN KEY (stock_take_task_id) REFERENCES stock_take(task_id)
);

CREATE TABLE stock_take_transaction (
    stock_take_number text,
    stock_take_task_id text,
    transaction_id text,
    PRIMARY KEY (stock_take_number, stock_take_task_id, transaction_id),
    FOREIGN KEY (stock_take_number) REFERENCES stock_take(stock_take_number),
    FOREIGN KEY (stock_take_task_id) REFERENCES stock_take(task_id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE stock_take (
    stock_take_number text,
    task_id text,
    account text,
    bin jsonb,
    brands jsonb,
    effective_date text,
    pick_zone jsonb,
    reference text,
    "status" text,
    stock_locators jsonb,
    PRIMARY KEY (stock_take_number, task_id)
);

CREATE TABLE opportunity_line (
    id text,
    opportunity_id text,
    product_id text,
    "comment" text,
    discount text,
    price text,
    quantity text,
    tax text,
    tax_percent text,
    tax_rule text,
    total text,
    PRIMARY KEY (id, opportunity_id),
    FOREIGN KEY (opportunity_id) REFERENCES opportunity(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE opportunity_additional_charge (
    id text,
    opportunity_id text,
    amount text,
    "comment" text,
    description text,
    discount text,
    quantity text,
    tax text,
    tax_percent text,
    tax_rule text,
    total text,
    PRIMARY KEY (id, opportunity_id),
    FOREIGN KEY (opportunity_id) REFERENCES opportunity(id)
);

CREATE TABLE opportunity (
    id text,
    customer_id text,
    lead_id text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    contact text,
    currency text,
    currency_conversion_rate text,
    custom_field_1 text,
    custom_field_10 text,
    custom_field_2 text,
    custom_field_3 text,
    custom_field_4 text,
    custom_field_5 text,
    custom_field_6 text,
    custom_field_7 text,
    custom_field_8 text,
    custom_field_9 text,
    customer_currency text,
    customer_name text,
    customer_reference text,
    default_account text,
    opportunity_comment text,
    opportunity_date text,
    opportunity_location text,
    opportunity_memo text,
    opportunity_number text,
    phone text,
    price_tier text,
    sales_representative text,
    ship_to_address_1 text,
    ship_to_address_2 text,
    ship_to_city text,
    ship_to_company text,
    ship_to_contact text,
    ship_to_country text,
    ship_to_other text,
    ship_to_post_code text,
    ship_to_state text,
    shipping_address_line_1 text,
    shipping_address_line_2 text,
    tax_inclusive text,
    tax_percent text,
    tax_rule text,
    tax_total text,
    term text,
    term_day text,
    term_due_next_month text,
    term_method text,
    total text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (lead_id) REFERENCES lead(id)
);

CREATE TABLE task (
    id text,
    assigned_by text,
    assigned_to text,
    category text,
    completed_date text,
    description text,
    end_date text,
    entity_id text,
    entity_type text,
    is_all_day text,
    is_important text,
    "name" text,
    start_date text,
    task_status text,
    void_date text,
    workflow_name text,
    PRIMARY KEY (id)
);

CREATE TABLE journal_attachment (
    id text,
    journal_number text,
    purchase_id text,
    content_type text,
    download_url text,
    file_name text,
    PRIMARY KEY (id, journal_number, purchase_id),
    FOREIGN KEY (journal_number) REFERENCES journal(journal_number),
    FOREIGN KEY (purchase_id) REFERENCES journal(purchase_id)
);

CREATE TABLE journal_line (
    _fivetran_id text,
    journal_number text,
    purchase_id text,
    amount text,
    base_amount text,
    credit text,
    debit text,
    reference text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (journal_number) REFERENCES journal(journal_number),
    FOREIGN KEY (purchase_id) REFERENCES journal(purchase_id)
);

CREATE TABLE journal (
    journal_number text,
    purchase_id text,
    currency text,
    currency_conversion_rate text,
    effective_date text,
    narration text,
    notes text,
    "status" text,
    task_id text,
    PRIMARY KEY (journal_number, purchase_id)
);

CREATE TABLE product_availability (
    product_id text,
    allocated text,
    available text,
    batch text,
    bin text,
    expiry_date text,
    in_transit text,
    location text,
    next_delivery_date text,
    on_hand text,
    on_order text,
    stock_on_hand text,
    PRIMARY KEY (product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_family_attachment (
    id text,
    object_id text,
    content_type text,
    file_name text,
    is_default text,
    "type" text,
    PRIMARY KEY (id, object_id),
    FOREIGN KEY (object_id) REFERENCES product_family(id)
);

CREATE TABLE family_product (
    product_family_id text,
    product_id text,
    PRIMARY KEY (product_family_id, product_id),
    FOREIGN KEY (product_family_id) REFERENCES product_family(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_family (
    id text,
    cogs_account text,
    revenue_account text,
    attribute_set text,
    brand text,
    category text,
    costing_method text,
    default_location text,
    description text,
    discount_rule text,
    drop_ship_mode text,
    inventory_account text,
    last_modified_on text,
    minimum_before_reorder text,
    "name" text,
    option_1_name text,
    option_1_values text,
    option_2_name text,
    option_2_values text,
    option_3_name text,
    option_3_values text,
    price_tier_1 text,
    price_tier_10 text,
    price_tier_2 text,
    price_tier_3 text,
    price_tier_4 text,
    price_tier_5 text,
    price_tier_6 text,
    price_tier_7 text,
    price_tier_8 text,
    price_tier_9 text,
    purchase_tax_rule text,
    reorder_quantity text,
    sale_tax_rule text,
    sku text,
    tags text,
    uom text,
    warranty_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (cogs_account) REFERENCES chart_of_account(code),
    FOREIGN KEY (revenue_account) REFERENCES chart_of_account(code)
);

CREATE TABLE product_reorder_level (
    location_id text,
    product_id text,
    minimum_before_reorder text,
    pick_zones text,
    reorder_quantity text,
    stock_locator text,
    PRIMARY KEY (location_id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE bill_of_material_product (
    component_product_id text,
    product_id text,
    cost_percentage text,
    "name" text,
    product_code text,
    quantity text,
    wastage_quantity text,
    PRIMARY KEY (component_product_id, product_id),
    FOREIGN KEY (component_product_id) REFERENCES product(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE bill_of_material_service (
    component_product_id text,
    product_id text,
    expense_account text,
    "name" text,
    price_tier text,
    quantity text,
    PRIMARY KEY (component_product_id, product_id),
    FOREIGN KEY (component_product_id) REFERENCES product(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (expense_account) REFERENCES chart_of_account(code)
);

CREATE TABLE product_movement (
    "index" text,
    product_id text,
    amount text,
    batch_sn text,
    "date" text,
    expiry_date text,
    from_to text,
    location text,
    number text,
    quantity text,
    task_id text,
    "type" text,
    PRIMARY KEY ("index", product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_attachment (
    id text,
    product_id text,
    content_type text,
    file_name text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_custom_price (
    _fivetran_id text,
    customer_id text,
    product_id text,
    price text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    category_id text,
    cogs_account text,
    default_location text,
    expense_account text,
    revenue_account text,
    additional_attribute_1 text,
    additional_attribute_10 text,
    additional_attribute_2 text,
    additional_attribute_3 text,
    additional_attribute_4 text,
    additional_attribute_5 text,
    additional_attribute_6 text,
    additional_attribute_7 text,
    additional_attribute_8 text,
    additional_attribute_9 text,
    assembly_cost_estimation_method text,
    attribute_set text,
    auto_assembly text,
    auto_disassembly text,
    average_cost text,
    barcode text,
    bill_of_material text,
    bom_type text,
    brand text,
    carton_height text,
    carton_inner_quantity text,
    carton_length text,
    carton_quantity text,
    carton_width text,
    costing_method text,
    description text,
    dimension_units text,
    discount_rule text,
    drop_ship_mode text,
    height text,
    internal_note text,
    inventory_account text,
    last_modified_on text,
    length text,
    minimum_before_reorder text,
    "name" text,
    pick_zones text,
    price_tier_1 text,
    price_tier_10 text,
    price_tier_2 text,
    price_tier_3 text,
    price_tier_4 text,
    price_tier_5 text,
    price_tier_6 text,
    price_tier_7 text,
    price_tier_8 text,
    price_tier_9 text,
    price_tiers_tier_1 text,
    price_tiers_tier_10 text,
    price_tiers_tier_2 text,
    price_tiers_tier_3 text,
    price_tiers_tier_4 text,
    price_tiers_tier_5 text,
    price_tiers_tier_6 text,
    price_tiers_tier_7 text,
    price_tiers_tier_8 text,
    price_tiers_tier_9 text,
    purchase_tax_rule text,
    quantity_to_produce text,
    reorder_quantity text,
    sale_tax_rule text,
    sellable text,
    short_description text,
    sku text,
    "status" text,
    stock_locator text,
    suppliers jsonb,
    tags text,
    "type" text,
    uom text,
    warranty_name text,
    weight text,
    weight_units text,
    width text,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES product_category(id),
    FOREIGN KEY (cogs_account) REFERENCES chart_of_account(code),
    FOREIGN KEY (default_location) REFERENCES location(id),
    FOREIGN KEY (expense_account) REFERENCES chart_of_account(code),
    FOREIGN KEY (revenue_account) REFERENCES chart_of_account(code)
);

CREATE TABLE product_markup_price (
    tier_number text,
    product_id text,
    markup_type text,
    markup_value text,
    use_price_type text,
    PRIMARY KEY (tier_number),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE purchase_inventory_movement (
    product_id text,
    purchase_id text,
    cogs text,
    "date" text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    task_id text,
    PRIMARY KEY (product_id, purchase_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id)
);

CREATE TABLE purchase_credit_note_line (
    "index" text,
    purchase_credit_not_task_id text,
    purchase_id text,
    product_id text,
    account text,
    "comment" text,
    discount text,
    price text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY ("index", purchase_credit_not_task_id, purchase_id),
    FOREIGN KEY (purchase_credit_not_task_id) REFERENCES purchase_credit_note(task_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase_credit_note(purchase_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE purchase_credit_note_refund (
    id text,
    purchase_credit_not_task_id text,
    purchase_id text,
    account text,
    amount text,
    currency_rate text,
    date_created text,
    date_paid text,
    reference text,
    PRIMARY KEY (id, purchase_credit_not_task_id, purchase_id),
    FOREIGN KEY (purchase_credit_not_task_id) REFERENCES purchase_credit_note(task_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase_credit_note(purchase_id)
);

CREATE TABLE purchase_credit_note_unstock (
    card_id text,
    product_id text,
    purchase_credit_not_task_id text,
    purchase_id text,
    batch_sn text,
    "date" text,
    expiry_date text,
    location text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    PRIMARY KEY (card_id, product_id, purchase_credit_not_task_id, purchase_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (purchase_credit_not_task_id) REFERENCES purchase_credit_note(task_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase_credit_note(purchase_id)
);

CREATE TABLE purchase_credit_note (
    task_id text,
    purchase_id text,
    additional_charges jsonb,
    credit_note_date text,
    credit_note_invoice_number text,
    credit_note_number text,
    currency_rate text,
    "status" text,
    tax text,
    PRIMARY KEY (task_id, purchase_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id)
);

CREATE TABLE purchase_invoice_line (
    "index" text,
    purchase_id text,
    purchase_invoice_task_id text,
    product_id text,
    account text,
    "comment" text,
    discount text,
    non_inventory text,
    price text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY ("index", purchase_id, purchase_invoice_task_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase_invoice(purchase_id),
    FOREIGN KEY (purchase_invoice_task_id) REFERENCES purchase_invoice(task_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE purchase_invoice_payment (
    id text,
    purchase_id text,
    purchase_invoice_task_id text,
    account text,
    amount text,
    currency_rate text,
    date_created text,
    date_paid text,
    reference text,
    PRIMARY KEY (id, purchase_id, purchase_invoice_task_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase_invoice(purchase_id),
    FOREIGN KEY (purchase_invoice_task_id) REFERENCES purchase_invoice(task_id)
);

CREATE TABLE purchase_invoice_additional_charge (
    _fivetran_id text,
    purchase_id text,
    purchase_invoice_task_id text,
    account text,
    description text,
    discount text,
    price text,
    quantity text,
    reference text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase_invoice(purchase_id),
    FOREIGN KEY (purchase_invoice_task_id) REFERENCES purchase_invoice(task_id)
);

CREATE TABLE purchase_invoice (
    task_id text,
    purchase_id text,
    currency_rate text,
    invoice_date text,
    invoice_due_date text,
    invoice_number text,
    invoicing_and_receiving_number text,
    paid text,
    "status" text,
    PRIMARY KEY (task_id, purchase_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id)
);

CREATE TABLE put_away_line (
    "index" text,
    object_task_id text,
    purchase_id text,
    product_id text,
    batch_sn text,
    card_id text,
    "date" text,
    expiry_date text,
    location text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    received text,
    supplier_sku text,
    "type" text,
    PRIMARY KEY ("index", object_task_id, purchase_id),
    FOREIGN KEY (object_task_id) REFERENCES put_away(task_id),
    FOREIGN KEY (purchase_id) REFERENCES put_away(purchase_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE put_away (
    task_id text,
    purchase_id text,
    invoicing_and_receiving_number text,
    "status" text,
    "type" text,
    PRIMARY KEY (task_id, purchase_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id)
);

CREATE TABLE stock_received_line (
    "index" text,
    object_task_id text,
    purchase_id text,
    product_id text,
    batch_sn text,
    card_id text,
    "date" text,
    expiry_date text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    received text,
    supplier_sku text,
    "type" text,
    PRIMARY KEY ("index", object_task_id, purchase_id),
    FOREIGN KEY (object_task_id) REFERENCES stock_received(task_id),
    FOREIGN KEY (purchase_id) REFERENCES stock_received(purchase_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE stock_received (
    task_id text,
    purchase_id text,
    invoicing_and_receiving_number text,
    "status" text,
    "type" text,
    PRIMARY KEY (task_id, purchase_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id)
);

CREATE TABLE purchase_order_line (
    product_id text,
    purchase_id text,
    "comment" text,
    dimensions_unit text,
    discount text,
    price text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    supplier_sku text,
    tax_rule text,
    PRIMARY KEY (product_id, purchase_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id)
);

CREATE TABLE purchase (
    id text,
    related_drop_ship_sale_task text,
    supplier_id text,
    approach text,
    attachments jsonb,
    billing_address_city text,
    billing_address_country text,
    billing_address_display_address_line_1 text,
    billing_address_display_address_line_2 text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    billing_address_postcode text,
    billing_address_state text,
    blind_receipt text,
    combined_invoice_status text,
    combined_payment_status text,
    combined_receiving_status text,
    contact text,
    currency_rate text,
    inventory_account text,
    is_service_only text,
    last_updated_date text,
    location text,
    note text,
    order_additional_charges jsonb,
    order_date text,
    order_memo text,
    order_number text,
    order_prepayments jsonb,
    order_status text,
    order_tax text,
    order_total_before_tax text,
    phone text,
    required_by text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country text,
    shipping_address_display_address_line_1 text,
    shipping_address_display_address_line_2 text,
    shipping_address_line_1 text,
    shipping_address_line_2 text,
    shipping_address_postcode text,
    shipping_address_ship_to_other text,
    shipping_address_state text,
    "status" text,
    tax_calculation text,
    tax_rule text,
    terms text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (related_drop_ship_sale_task) REFERENCES task(id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE lead_contact (
    id text,
    lead_id text,
    "comment" text,
    defaults text,
    email text,
    fax text,
    include_in_email text,
    job_title text,
    mobile_phone text,
    "name" text,
    phone text,
    website text,
    PRIMARY KEY (id, lead_id),
    FOREIGN KEY (lead_id) REFERENCES lead(id)
);

CREATE TABLE lead_address (
    id text,
    lead_id text,
    city text,
    country text,
    default_for_type text,
    line_1 text,
    line_2 text,
    postcode text,
    "state" text,
    "type" text,
    PRIMARY KEY (id, lead_id),
    FOREIGN KEY (lead_id) REFERENCES lead(id)
);

CREATE TABLE lead (
    id text,
    amount text,
    close_chance text,
    close_date text,
    "comment" text,
    currency text,
    lead_status text,
    "name" text,
    payment_term text,
    price_tier text,
    sales_representative text,
    tax_rule text,
    PRIMARY KEY (id)
);

CREATE TABLE sale_quote_line (
    "index" text,
    sale_id text,
    product_id text,
    account text,
    "comment" text,
    dimensions_units text,
    discount text,
    "name" text,
    price text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    sku text,
    tax text,
    tax_rule text,
    weight_units text,
    PRIMARY KEY ("index", sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_quote_additional_charge (
    _fivetran_id text,
    sale_id text,
    "comment" text,
    description text,
    discount text,
    price text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_order_line (
    "index" text,
    sale_id text,
    product_id text,
    average_cost text,
    backorder text,
    backorder_quantity text,
    "comment" text,
    discount text,
    dropship text,
    price text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY ("index", sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_order_additional_charge (
    _fivetran_id text,
    sale_id text,
    "comment" text,
    description text,
    discount text,
    price text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_invoice_line (
    "index" text,
    sale_id text,
    sale_invoice_task_id text,
    product_id text,
    account text,
    average_cost text,
    "comment" text,
    discount text,
    price text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY ("index", sale_id, sale_invoice_task_id),
    FOREIGN KEY (sale_id) REFERENCES sale_invoice(sale_id),
    FOREIGN KEY (sale_invoice_task_id) REFERENCES sale_invoice(task_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_invoice_additional_charge (
    _fivetran_id text,
    sale_id text,
    sale_invoice_task_id text,
    account text,
    description text,
    discount text,
    price text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (sale_id) REFERENCES sale_invoice(sale_id),
    FOREIGN KEY (sale_invoice_task_id) REFERENCES sale_invoice(task_id)
);

CREATE TABLE sale_invoice (
    task_id text,
    sale_id text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    currency_conversion_rate text,
    invoice_date text,
    invoice_due_date text,
    invoice_number text,
    linked_fulfillment_number text,
    memo text,
    paid text,
    payment jsonb,
    "status" text,
    tax text,
    total text,
    total_before_tax text,
    PRIMARY KEY (task_id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_credit_note_line (
    "index" text,
    sale_credit_note_task_id text,
    sale_id text,
    product_id text,
    account text,
    "comment" text,
    discount text,
    price text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY ("index", sale_credit_note_task_id, sale_id),
    FOREIGN KEY (sale_credit_note_task_id) REFERENCES sale_credit_note(task_id),
    FOREIGN KEY (sale_id) REFERENCES sale_credit_note(sale_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_credit_note_refund (
    id text,
    sale_credit_note_task_id text,
    sale_id text,
    account text,
    amount text,
    currency_rate text,
    date_created text,
    date_paid text,
    reference text,
    PRIMARY KEY (id, sale_credit_note_task_id, sale_id),
    FOREIGN KEY (sale_credit_note_task_id) REFERENCES sale_credit_note(task_id),
    FOREIGN KEY (sale_id) REFERENCES sale_credit_note(sale_id)
);

CREATE TABLE sale_credit_note_restock (
    "index" text,
    sale_credit_note_task_id text,
    sale_id text,
    product_id text,
    batch_sn text,
    expiry_date text,
    location text,
    "name" text,
    quantity text,
    sku text,
    PRIMARY KEY ("index", sale_credit_note_task_id, sale_id),
    FOREIGN KEY (sale_credit_note_task_id) REFERENCES sale_credit_note(task_id),
    FOREIGN KEY (sale_id) REFERENCES sale_credit_note(sale_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_credit_note_additional_charge (
    _fivetran_id text,
    sale_credit_note_task_id text,
    sale_id text,
    account text,
    "comment" text,
    description text,
    discount text,
    price text,
    quantity text,
    tax text,
    tax_rule text,
    total text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (sale_credit_note_task_id) REFERENCES sale_credit_note(task_id),
    FOREIGN KEY (sale_id) REFERENCES sale_credit_note(sale_id)
);

CREATE TABLE sale_credit_note (
    task_id text,
    sale_id text,
    credit_note_conversion_rate text,
    credit_note_date text,
    credit_note_invoice_number text,
    credit_note_number text,
    memo text,
    "status" text,
    tax text,
    total text,
    total_before_tax text,
    PRIMARY KEY (task_id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_attachment (
    id text,
    sale_id text,
    content_type text,
    download_url text,
    file_name text,
    PRIMARY KEY (id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_fullfillment_pick_line (
    "index" text,
    fulfillment_number text,
    sale_id text,
    product_id text,
    batch_sn text,
    expiry_date text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    PRIMARY KEY ("index", fulfillment_number, sale_id),
    FOREIGN KEY (fulfillment_number) REFERENCES sale_fullfillment(fulfillment_number),
    FOREIGN KEY (sale_id) REFERENCES sale_fullfillment(sale_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_fullfillment_pack_line (
    "index" text,
    fulfillment_number text,
    sale_id text,
    product_id text,
    batch_sn text,
    box text,
    expiry_date text,
    location text,
    location_id text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    quantity text,
    PRIMARY KEY ("index", fulfillment_number, sale_id),
    FOREIGN KEY (fulfillment_number) REFERENCES sale_fullfillment(fulfillment_number),
    FOREIGN KEY (sale_id) REFERENCES sale_fullfillment(sale_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_fullfillment_ship_line (
    id text,
    fulfillment_number text,
    sale_id text,
    boxes text,
    carrier text,
    is_shipped text,
    shipment_date text,
    tracking_number text,
    tracking_url text,
    PRIMARY KEY (id, fulfillment_number, sale_id),
    FOREIGN KEY (fulfillment_number) REFERENCES sale_fullfillment(fulfillment_number),
    FOREIGN KEY (sale_id) REFERENCES sale_fullfillment(sale_id)
);

CREATE TABLE sale_fullfillment (
    fulfillment_number text,
    task_id text,
    sale_id text,
    fulfilment_status text,
    linked_invoice_number text,
    pack_status text,
    pick_status text,
    ship_required_by text,
    ship_shipping_address_city text,
    ship_shipping_address_company text,
    ship_shipping_address_contact text,
    ship_shipping_address_country text,
    ship_shipping_address_display_address_line_1 text,
    ship_shipping_address_display_address_line_2 text,
    ship_shipping_address_line_1 text,
    ship_shipping_address_line_2 text,
    ship_shipping_address_postcode text,
    ship_shipping_address_ship_to_other text,
    ship_shipping_address_state text,
    ship_shipping_note text,
    ship_status text,
    PRIMARY KEY (fulfillment_number, task_id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_inventory_movement (
    "index" text,
    sale_id text,
    product_id text,
    cogs text,
    "date" text,
    product_custom_field_1 text,
    product_custom_field_10 text,
    product_custom_field_2 text,
    product_custom_field_3 text,
    product_custom_field_4 text,
    product_custom_field_5 text,
    product_custom_field_6 text,
    product_custom_field_7 text,
    product_custom_field_8 text,
    product_custom_field_9 text,
    task_id text,
    PRIMARY KEY ("index", sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_transaction (
    sale_id text,
    transaction_id text,
    task_id text,
    PRIMARY KEY (sale_id, transaction_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE sale (
    id text,
    customer_id text,
    additional_attribute_1 text,
    additional_attribute_10 text,
    additional_attribute_2 text,
    additional_attribute_3 text,
    additional_attribute_4 text,
    additional_attribute_5 text,
    additional_attribute_6 text,
    additional_attribute_7 text,
    additional_attribute_8 text,
    additional_attribute_9 text,
    base_currency text,
    carrier text,
    cogs_amount text,
    combined_invoice_status text,
    combined_packing_status text,
    combined_payment_status text,
    combined_picking_status text,
    combined_shipping_status text,
    combined_tracking_numbers text,
    customer_reference text,
    default_account text,
    external_id text,
    fulfilment_status text,
    last_modified_on text,
    location text,
    manual_journal_line jsonb,
    manual_journal_status text,
    note text,
    order_date text,
    order_memo text,
    order_number text,
    order_status text,
    order_tax text,
    order_total text,
    order_total_before_tax text,
    price_tier text,
    quote_memo text,
    quote_prepayment jsonb,
    quote_status text,
    quote_tax text,
    quote_total text,
    quote_total_before_tax text,
    sales_representative text,
    service_only text,
    ship_by text,
    shipping_note text,
    skip_quote text,
    source_channel text,
    "status" text,
    tax_calculation text,
    tax_rule text,
    term text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE location_bin (
    id text,
    location_id text,
    is_deprecated text,
    is_staging text,
    "name" text,
    PRIMARY KEY (id, location_id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE location (
    id text,
    address_city_suburb text,
    address_country text,
    address_line_1 text,
    address_line_2 text,
    address_state_province text,
    address_zip_postcode text,
    fixed_assets_location text,
    is_co_man text,
    is_default text,
    is_deprecated text,
    is_shop_floor text,
    is_staging text,
    "name" text,
    parent_id text,
    parent_name text,
    pick_zone text,
    reference_count text,
    PRIMARY KEY (id)
);

CREATE TABLE "transaction" (
    id text,
    task_id text,
    amount text,
    credit_account_code text,
    currency_rate text,
    debit_account_code text,
    effective_date text,
    original_amount text,
    reference text,
    "transaction" text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (task_id) REFERENCES task(id)
);

CREATE TABLE product_category (
    id text,
    "name" text,
    PRIMARY KEY (id)
);

CREATE TABLE customer_product_price (
    customer_id text,
    product_id text,
    price text,
    PRIMARY KEY (customer_id, product_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE customer_contacts (
    id text,
    customer_id text,
    "comment" text,
    defaults text,
    email text,
    fax text,
    include_in_email text,
    job_title text,
    mobile_phone text,
    "name" text,
    phone text,
    website text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_address (
    id text,
    customer_id text,
    city text,
    country text,
    default_for_type text,
    line_1 text,
    line_2 text,
    post_code text,
    "state" text,
    "type" text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer (
    id text,
    revenue_account text,
    account_receivable text,
    additional_attribute_1 text,
    additional_attribute_10 text,
    additional_attribute_2 text,
    additional_attribute_3 text,
    additional_attribute_4 text,
    additional_attribute_5 text,
    additional_attribute_6 text,
    additional_attribute_7 text,
    additional_attribute_8 text,
    additional_attribute_9 text,
    attribute_set text,
    carrier text,
    comments text,
    credit_limit text,
    currency text,
    discount text,
    is_on_credit_hold text,
    last_modified_on text,
    location text,
    "name" text,
    payment_term text,
    price_tier text,
    sales_representative text,
    "status" text,
    tags text,
    tax_number text,
    tax_rule text,
    PRIMARY KEY (id),
    FOREIGN KEY (revenue_account) REFERENCES chart_of_account(code)
);
