CREATE TABLE publisher_commission_item_situation_detail (
    id text,
    publisher_commission_id text,
    publisher_commission_item_id text,
    "name" text,
    PRIMARY KEY (id, publisher_commission_id, publisher_commission_item_id),
    FOREIGN KEY (publisher_commission_id) REFERENCES publisher_commission_item(publisher_commission_id),
    FOREIGN KEY (publisher_commission_item_id) REFERENCES publisher_commission_item(id)
);

CREATE TABLE publisher_commission_item (
    id text,
    publisher_commission_id text,
    discount_adv_currency text,
    discount_pub_currency text,
    discount_usd text,
    item_list_id text,
    per_item_sale_amount_adv_currency text,
    per_item_sale_amount_pub_currency text,
    per_item_sale_amount_usd text,
    quantity text,
    sku text,
    total_commission_adv_currency text,
    total_commission_pub_currency text,
    total_commission_usd text,
    PRIMARY KEY (id, publisher_commission_id),
    FOREIGN KEY (publisher_commission_id) REFERENCES publisher_commission(id)
);

CREATE TABLE publisher_commission_situation_detail (
    id text,
    publisher_commission_id text,
    "name" text,
    PRIMARY KEY (id, publisher_commission_id),
    FOREIGN KEY (publisher_commission_id) REFERENCES publisher_commission(id)
);

CREATE TABLE publisher_commission (
    id text,
    action_status text,
    action_tracker_id text,
    action_tracker_name text,
    action_type text,
    advertiser_id text,
    advertiser_name text,
    aid text,
    click_date text,
    click_referring_url text,
    concluding_browser text,
    concluding_device_name text,
    concluding_device_type text,
    correction_reason text,
    country text,
    coupon text,
    event_date text,
    initiating_browser text,
    initiating_device_name text,
    initiating_device_type text,
    is_cross_device text,
    locking_date text,
    locking_method text,
    order_discount_adv_currency text,
    order_discount_orig_currency text,
    order_discount_pub_currency text,
    order_discount_usd text,
    order_id text,
    original text,
    original_action_id text,
    posting_date text,
    pub_commission_amount_currency text,
    pub_commission_amount_usd text,
    publisher_id text,
    publisher_name text,
    reviewed_status text,
    sale_amount_pub_currency text,
    sale_amount_usd text,
    shopper_id text,
    site_to_store_offer text,
    "source" text,
    validation_status text,
    vertical_attribute_annual_fee text,
    vertical_attribute_application_status text,
    vertical_attribute_apr text,
    vertical_attribute_apr_transfer text,
    vertical_attribute_apr_transfer_time text,
    vertical_attribute_booking_date text,
    vertical_attribute_booking_status text,
    vertical_attribute_booking_value_post_tax text,
    vertical_attribute_booking_value_pre_tax text,
    vertical_attribute_brand text,
    vertical_attribute_brand_id text,
    vertical_attribute_business_unit text,
    vertical_attribute_campaign_id text,
    vertical_attribute_campaign_name text,
    vertical_attribute_car_options text,
    vertical_attribute_card_category text,
    vertical_attribute_cash_advance_fee text,
    vertical_attribute_category text,
    vertical_attribute_city text,
    vertical_attribute_class text,
    vertical_attribute_confirmation_number text,
    vertical_attribute_contract_length text,
    vertical_attribute_contract_type text,
    vertical_attribute_country_code text,
    vertical_attribute_coupon_discount text,
    vertical_attribute_coupon_type text,
    vertical_attribute_credit_line text,
    vertical_attribute_credit_quality text,
    vertical_attribute_credit_report text,
    vertical_attribute_cruise_type text,
    vertical_attribute_cust_country text,
    vertical_attribute_cust_segment text,
    vertical_attribute_cust_status text,
    vertical_attribute_cust_type text,
    vertical_attribute_customer_location text,
    vertical_attribute_delivery text,
    vertical_attribute_description text,
    vertical_attribute_dest_city text,
    vertical_attribute_dest_country text,
    vertical_attribute_dest_state text,
    vertical_attribute_destination_id text,
    vertical_attribute_domestic text,
    vertical_attribute_dropoff_iata text,
    vertical_attribute_dropoff_id text,
    vertical_attribute_duration text,
    vertical_attribute_end_date_time text,
    vertical_attribute_flight_fare_type text,
    vertical_attribute_flight_options text,
    vertical_attribute_flight_type text,
    vertical_attribute_flyer_miles text,
    vertical_attribute_funded_amount text,
    vertical_attribute_funded_currency text,
    vertical_attribute_genre text,
    vertical_attribute_guests text,
    vertical_attribute_iata text,
    vertical_attribute_introductory_apr text,
    vertical_attribute_introductory_apr_time text,
    vertical_attribute_item_id text,
    vertical_attribute_item_name text,
    vertical_attribute_item_type text,
    vertical_attribute_itinerary_id text,
    vertical_attribute_lifestage text,
    vertical_attribute_location text,
    vertical_attribute_loyalty_earned text,
    vertical_attribute_loyalty_first_time_signup text,
    vertical_attribute_loyalty_level text,
    vertical_attribute_loyalty_redeemed text,
    vertical_attribute_loyalty_status text,
    vertical_attribute_min_balance text,
    vertical_attribute_min_deposit text,
    vertical_attribute_min_stay_duration text,
    vertical_attribute_no_cancellation text,
    vertical_attribute_or_country text,
    vertical_attribute_or_state text,
    vertical_attribute_paid_at_booking_post_tax text,
    vertical_attribute_paid_at_booking_pre_tax text,
    vertical_attribute_payment_method text,
    vertical_attribute_payment_model text,
    vertical_attribute_pickup_iata text,
    vertical_attribute_pickup_id text,
    vertical_attribute_platform_id text,
    vertical_attribute_point_of_sale text,
    vertical_attribute_port text,
    vertical_attribute_preorder text,
    vertical_attribute_prepaid text,
    vertical_attribute_prequalify text,
    vertical_attribute_promotion text,
    vertical_attribute_promotion_amount text,
    vertical_attribute_promotion_condition_threshold text,
    vertical_attribute_promotion_condition_type text,
    vertical_attribute_promotion_ends text,
    vertical_attribute_promotion_starts text,
    vertical_attribute_promotion_type text,
    vertical_attribute_quantity text,
    vertical_attribute_rating text,
    vertical_attribute_room_type text,
    vertical_attribute_rooms text,
    vertical_attribute_service_type text,
    vertical_attribute_ship_name text,
    vertical_attribute_start_date_time text,
    vertical_attribute_state text,
    vertical_attribute_subscription_fee text,
    vertical_attribute_subscription_length text,
    vertical_attribute_tax_amount text,
    vertical_attribute_tax_type text,
    vertical_attribute_transfer_fee text,
    vertical_attribute_travel_type text,
    vertical_attribute_trip_type text,
    vertical_attribute_upsell text,
    website_id text,
    website_name text,
    PRIMARY KEY (id)
);

CREATE TABLE advertiser_commission_item_situation_detail (
    id text,
    advertiser_commission_id text,
    advertiser_commission_item_id text,
    "name" text,
    PRIMARY KEY (id, advertiser_commission_id, advertiser_commission_item_id),
    FOREIGN KEY (advertiser_commission_id) REFERENCES advertiser_commission_item(advertiser_commission_id),
    FOREIGN KEY (advertiser_commission_item_id) REFERENCES advertiser_commission_item(id)
);

CREATE TABLE advertiser_commission_item (
    id text,
    advertiser_commission_id text,
    discount_adv_currency text,
    discount_pub_currency text,
    discount_usd text,
    item_list_id text,
    per_item_sale_amount_adv_currency text,
    per_item_sale_amount_pub_currency text,
    per_item_sale_amount_usd text,
    quantity text,
    sku text,
    total_commission_adv_currency text,
    total_commission_pub_currency text,
    PRIMARY KEY (id, advertiser_commission_id),
    FOREIGN KEY (advertiser_commission_id) REFERENCES advertiser_commission(id)
);

CREATE TABLE advertiser_commission_situation_detail (
    id text,
    advertiser_commission_id text,
    "name" text,
    PRIMARY KEY (id, advertiser_commission_id),
    FOREIGN KEY (advertiser_commission_id) REFERENCES advertiser_commission(id)
);

CREATE TABLE advertiser_commission (
    id text,
    action_status text,
    action_tracker_id text,
    action_tracker_name text,
    action_type text,
    ad_owner text,
    adv_commission_amount_adv_currency text,
    adv_commission_amount_usd text,
    advertiser_id text,
    advertiser_name text,
    aid text,
    cj_fee_adv_currency text,
    cj_fee_usd text,
    click_date text,
    click_referring_url text,
    concluding_browser text,
    concluding_device_name text,
    concluding_device_type text,
    correction_reason text,
    country text,
    coupon text,
    event_date text,
    initiating_browser text,
    initiating_device_name text,
    initiating_device_type text,
    is_cross_device text,
    locking_date text,
    locking_method text,
    new_to_file text,
    order_discount_adv_currency text,
    order_discount_orig_currency text,
    order_discount_pub_currency text,
    order_discount_usd text,
    order_id text,
    original text,
    original_action_id text,
    posting_date text,
    pub_commission_amount_pub_currency text,
    pub_commission_amount_usd text,
    publisher_id text,
    publisher_name text,
    reviewed_status text,
    sale_amount_adv_currency text,
    sale_amount_pub_currency text,
    sale_amount_usd text,
    site_to_store_offer text,
    "source" text,
    validation_status text,
    vertical_attribute_ancillary_spend text,
    vertical_attribute_annual_fee text,
    vertical_attribute_application_status text,
    vertical_attribute_apr text,
    vertical_attribute_apr_transfer text,
    vertical_attribute_apr_transfer_time text,
    vertical_attribute_booking_date text,
    vertical_attribute_booking_status text,
    vertical_attribute_booking_value_post_tax text,
    vertical_attribute_booking_value_pre_tax text,
    vertical_attribute_brand text,
    vertical_attribute_brand_id text,
    vertical_attribute_business_unit text,
    vertical_attribute_campaign_id text,
    vertical_attribute_campaign_name text,
    vertical_attribute_car_options text,
    vertical_attribute_card_category text,
    vertical_attribute_cash_advance_fee text,
    vertical_attribute_category text,
    vertical_attribute_city text,
    vertical_attribute_class text,
    vertical_attribute_confirmation_number text,
    vertical_attribute_contract_length text,
    vertical_attribute_contract_type text,
    vertical_attribute_country_code text,
    vertical_attribute_coupon_discount text,
    vertical_attribute_coupon_type text,
    vertical_attribute_credit_line text,
    vertical_attribute_credit_quality text,
    vertical_attribute_credit_report text,
    vertical_attribute_cruise_type text,
    vertical_attribute_cust_country text,
    vertical_attribute_cust_segment text,
    vertical_attribute_cust_status text,
    vertical_attribute_cust_type text,
    vertical_attribute_customer_location text,
    vertical_attribute_delivery text,
    vertical_attribute_description text,
    vertical_attribute_dest_city text,
    vertical_attribute_dest_country text,
    vertical_attribute_dest_state text,
    vertical_attribute_destination_id text,
    vertical_attribute_domestic text,
    vertical_attribute_dropoff_iata text,
    vertical_attribute_dropoff_id text,
    vertical_attribute_duration text,
    vertical_attribute_end_date_time text,
    vertical_attribute_flight_fare_type text,
    vertical_attribute_flight_option text,
    vertical_attribute_flight_type text,
    vertical_attribute_flyer_miles text,
    vertical_attribute_funded_amount text,
    vertical_attribute_funded_currency text,
    vertical_attribute_genre text,
    vertical_attribute_guest text,
    vertical_attribute_iata text,
    vertical_attribute_introductory_apr text,
    vertical_attribute_introductory_apr_time text,
    vertical_attribute_item_id text,
    vertical_attribute_item_name text,
    vertical_attribute_item_type text,
    vertical_attribute_itinerary_id text,
    vertical_attribute_lifestage text,
    vertical_attribute_location text,
    vertical_attribute_loyalty_earned text,
    vertical_attribute_loyalty_first_time_signup text,
    vertical_attribute_loyalty_level text,
    vertical_attribute_loyalty_redeemed text,
    vertical_attribute_loyalty_status text,
    vertical_attribute_margin text,
    vertical_attribute_marketing_channel text,
    vertical_attribute_min_balance text,
    vertical_attribute_min_deposit text,
    vertical_attribute_min_stay_duration text,
    vertical_attribute_no_cancellation text,
    vertical_attribute_or_city text,
    vertical_attribute_or_country text,
    vertical_attribute_or_state text,
    vertical_attribute_paid_at_booking_post_tax text,
    vertical_attribute_paid_at_booking_pre_tax text,
    vertical_attribute_payment_method text,
    vertical_attribute_payment_model text,
    vertical_attribute_pickup_iata text,
    vertical_attribute_pickup_id text,
    vertical_attribute_platform_id text,
    vertical_attribute_point_of_sale text,
    vertical_attribute_port text,
    vertical_attribute_preorder text,
    vertical_attribute_prepaid text,
    vertical_attribute_prequalify text,
    vertical_attribute_promotion text,
    vertical_attribute_promotion_amount text,
    vertical_attribute_promotion_condition_threshold text,
    vertical_attribute_promotion_condition_type text,
    vertical_attribute_promotion_ends text,
    vertical_attribute_promotion_starts text,
    vertical_attribute_promotion_type text,
    vertical_attribute_quantity text,
    vertical_attribute_rating text,
    vertical_attribute_room_type text,
    vertical_attribute_rooms text,
    vertical_attribute_service_type text,
    vertical_attribute_ship_name text,
    vertical_attribute_start_date_time text,
    vertical_attribute_state text,
    vertical_attribute_subscription_fee text,
    vertical_attribute_subscription_length text,
    vertical_attribute_tax_amount text,
    vertical_attribute_tax_type text,
    vertical_attribute_transfer_fee text,
    vertical_attribute_travel_type text,
    vertical_attribute_trip_type text,
    vertical_attribute_upsell text,
    website_id text,
    website_name text,
    PRIMARY KEY (id)
);
