CREATE TABLE gcp_marketplace_incremental_monthly_insight (
    _fivetran_id text,
    abandoned text,
    account_id text,
    billing_frequency text,
    channel text,
    charges text,
    company text,
    country text,
    currency text,
    "date" text,
    domain text,
    ds text,
    due_vendor text,
    earliest text,
    end_date text,
    entitlement_id text,
    external_account_id text,
    final_installment_date text,
    first_installment_date text,
    gpu_types text,
    installment_count text,
    internal_note text,
    latest text,
    machine_spec_sum text,
    num_cpus text,
    num_gpus text,
    num_vms text,
    offer_title text,
    order_end_date text,
    order_start_date text,
    parent_account_id text,
    payment_schedule text,
    payment_type text,
    postal_code text,
    postpay_credits text,
    prepay_credits text,
    private_offer_acceptance_date text,
    private_offer_total_contract_value text,
    probation_end text,
    probation_start text,
    quote_creator text,
    quote_id text,
    ram_mb text,
    released text,
    report_date text,
    reseller_discount text,
    sku_description text,
    sku_id text,
    solution_name text,
    start_date text,
    state_or_province text,
    transaction_type text,
    trial_use text,
    unit text,
    usage text,
    wholesale_charges text,
    withheld text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE gcp_marketplace_charge_and_usage_analytics (
    _fivetran_id text,
    abandoned text,
    account_id text,
    billing_frequency text,
    charges text,
    currency text,
    ds text,
    due_partner text,
    google_entity text,
    insights_account_id text,
    location text,
    payment_schedule text,
    payment_type text,
    postpay_credits text,
    prepay_credits text,
    probation_end text,
    probation_start text,
    refund_balance_deducted_this_month text,
    refund_balance_outstanding text,
    refund_period_end text,
    refund_period_start text,
    refund_reason text,
    released text,
    resource text,
    sku text,
    trial_use text,
    units text,
    usage text,
    used_by text,
    withheld text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE gcp_marketplace_monthly_insight (
    _fivetran_id text,
    abandoned text,
    account_id text,
    billing_frequency text,
    channel text,
    charges text,
    company text,
    country text,
    currency text,
    "date" text,
    domain text,
    ds text,
    due_vendor text,
    earliest text,
    end_date text,
    entitlement_id text,
    external_account_id text,
    final_installment_date text,
    first_installment_date text,
    gpu_types text,
    installment_count text,
    internal_note text,
    latest text,
    machine_spec_sum text,
    num_cpus text,
    num_gpus text,
    num_vms text,
    offer_title text,
    order_end_date text,
    order_start_date text,
    parent_account_id text,
    payment_schedule text,
    payment_type text,
    postal_code text,
    postpay_credits text,
    prepay_credits text,
    private_offer_acceptance_date text,
    private_offer_total_contract_value text,
    probation_end text,
    probation_start text,
    quote_creator text,
    quote_id text,
    ram_mb text,
    released text,
    reseller_discount text,
    sku_description text,
    sku_id text,
    solution_name text,
    start_date text,
    state_or_province text,
    transaction_type text,
    trial_use text,
    unit text,
    usage text,
    wholesale_charges text,
    withheld text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE aws_marketplace_revenue_analytics (
    _fivetran_id text,
    agreement_acceptance_date text,
    agreement_end_date text,
    agreement_id text,
    agreement_start_date text,
    aws_seller_of_record text,
    aws_tax_share text,
    aws_tax_share_listing_fee text,
    aws_tax_share_refund text,
    aws_tax_share_refund_listing_fee text,
    currency text,
    customer_reference_id text,
    disburse_bank_trace_id text,
    disbursement_date text,
    disbursement_status text,
    gross_refund text,
    gross_revenue text,
    invoice_date text,
    invoice_id text,
    isv_account_id text,
    isv_company_name text,
    legacy_product_id text,
    listing_fee text,
    listing_fee_invoice_id text,
    listing_fee_percentage text,
    listing_fee_refund text,
    offer_id text,
    offer_name text,
    offer_visibility text,
    payer_address_id text,
    payer_aws_account_id text,
    payer_city text,
    payer_company_name text,
    payer_country text,
    payer_email_domain text,
    payer_postal_code text,
    payer_state_or_region text,
    payment_due_date text,
    payment_terms text,
    product_code text,
    product_id text,
    product_title text,
    resale_authorization_description text,
    resale_authorization_id text,
    resale_authorization_name text,
    reseller_aws_account_id text,
    reseller_company_name text,
    seller_net_revenue text,
    seller_tax_share text,
    seller_tax_share_refund text,
    subscriber_address_id text,
    subscriber_aws_account_id text,
    subscriber_city text,
    subscriber_company_name text,
    subscriber_country text,
    subscriber_email_domain text,
    subscriber_postal_code text,
    subscriber_state_or_region text,
    transaction_reference_id text,
    usage_period_end_date text,
    usage_period_start_date text,
    wholesale_cost text,
    wholesale_cost_refund text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE azure_marketplace_customer_analytics (
    _fivetran_id text,
    address_line_1 text,
    azure_license_type text,
    billing_account_id text,
    billing_id text,
    commerce_root_customer text,
    customer_city text,
    customer_company_name text,
    customer_country_region text,
    customer_id text,
    customer_postal_code text,
    customer_state text,
    customer_type text,
    dataset_month text,
    date_acquired text,
    date_lost text,
    email text,
    first_name text,
    is_active text,
    is_private_plan text,
    last_modified_at text,
    last_name text,
    marketplace_subscription_id text,
    multi_party text,
    offer_id text,
    offer_name text,
    offer_type text,
    plan_id text,
    plan_visibility text,
    private_offer_id text,
    private_offer_name text,
    promotional_customers text,
    provider_email text,
    provider_name text,
    purchaser_email text,
    reference_id text,
    sku text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE aws_marketplace_disbursement_analytics (
    _fivetran_id text,
    agreement_acceptance_date text,
    agreement_end_date text,
    agreement_id text,
    agreement_start_date text,
    aws_seller_of_record text,
    aws_tax_share_listing_fee text,
    aws_tax_share_refund_listing_fee text,
    currency text,
    customer_reference_id text,
    disburse_bank_trace_id text,
    disbursed_net_revenue text,
    disbursement_date text,
    disbursement_period text,
    disbursement_status text,
    disbursement_time_in_days text,
    gross_refund text,
    gross_revenue text,
    invoice_date text,
    invoice_id text,
    isv_account_id text,
    isv_company_name text,
    legacy_product_id text,
    listing_fee text,
    listing_fee_invoice_id text,
    listing_fee_percentage text,
    listing_fee_refund text,
    offer_id text,
    offer_name text,
    offer_visibility text,
    payer_address_id text,
    payer_aws_account_id text,
    payer_city text,
    payer_company_name text,
    payer_country text,
    payer_email_domain text,
    payer_postal_code text,
    payer_state_or_region text,
    payment_due_date text,
    payment_terms text,
    product_code text,
    product_id text,
    product_title text,
    resale_authorization_description text,
    resale_authorization_id text,
    resale_authorization_name text,
    reseller_aws_account_id text,
    reseller_company_name text,
    seller_net_revenue text,
    seller_tax_share text,
    seller_tax_share_refund text,
    subscriber_address_id text,
    subscriber_aws_account_id text,
    subscriber_city text,
    subscriber_company_name text,
    subscriber_country text,
    subscriber_email_domain text,
    subscriber_postal_code text,
    subscriber_state_or_region text,
    transaction_reference_id text,
    undisbursed_net_revenue text,
    usage_period_end_date text,
    usage_period_start_date text,
    wholesale_cost text,
    wholesale_cost_refund text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE gcp_marketplace_daily_insight (
    _fivetran_id text,
    abandoned text,
    account_id text,
    billing_frequency text,
    channel text,
    charges text,
    company text,
    country text,
    currency text,
    "date" text,
    domain text,
    ds text,
    due_vendor text,
    earliest text,
    end_date text,
    entitlement_id text,
    external_account_id text,
    final_installment_date text,
    first_installment_date text,
    gpu_types text,
    installment_count text,
    internal_note text,
    latest text,
    machine_spec_sum text,
    num_cpus text,
    num_gpus text,
    num_vms text,
    offer_title text,
    order_end_date text,
    order_start_date text,
    parent_account_id text,
    payment_schedule text,
    payment_type text,
    postal_code text,
    postpay_credits text,
    prepay_credits text,
    private_offer_acceptance_date text,
    private_offer_total_contract_value text,
    probation_end text,
    probation_start text,
    quote_creator text,
    quote_id text,
    ram_mb text,
    released text,
    reseller_discount text,
    sku_description text,
    sku_id text,
    solution_name text,
    start_date text,
    state_or_province text,
    term_total_contract_value text,
    transaction_type text,
    trial_use text,
    unit text,
    usage text,
    wholesale_charges text,
    withheld text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE azure_cosell_opportunity_customer_contact (
    "index" text,
    fivetran_id text,
    email text,
    first_name text,
    last_name text,
    phone_number text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES azure_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE azure_cosell_opportunity_target (
    id text,
    fivetran_id text,
    "name" text,
    "type" text,
    PRIMARY KEY (id, fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES azure_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE azure_cosell_opportunity_partner_contact (
    "index" text,
    fivetran_id text,
    defaults text,
    email text,
    first_name text,
    last_name text,
    phone_number text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES azure_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE azure_cosell_opportunity_microsoft_sales_rep (
    "index" text,
    fivetran_id text,
    email text,
    first_name text,
    last_name text,
    phone_number text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES azure_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE azure_cosell_opportunity_tag (
    "index" text,
    fivetran_id text,
    tags text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES azure_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE azure_cosell_opportunity_analytics (
    _fivetran_id text,
    accepted_date_time text,
    address text,
    assistance_type text,
    azure_seller_id text,
    city text,
    closed_date_time text,
    closing_date_time text,
    cloud text,
    cloud_created_at text,
    cloud_status text,
    consent_to_contact text,
    consent_to_share_referral_with_microsoft_sellers text,
    consent_to_to_share_info_with_others text,
    country text,
    created_by_id text,
    created_date_time text,
    currency text,
    customer_company_name text,
    customer_duns_number text,
    customer_website text,
    deal_name text,
    deal_type text,
    deal_value text,
    direction text,
    domain_info_category text,
    engagement_id text,
    expiration_date_time text,
    external_id text,
    external_status text,
    id text,
    is_macc_eligible text,
    is_matching_complete text,
    is_spam text,
    metadata jsonb,
    microsoft_account_id text,
    microsoft_duns_number text,
    microsoft_sales_rep_1_id text,
    microsoft_sales_rep_2_id text,
    microsoft_sales_rep_3_id text,
    microsoft_sales_rep_4_id text,
    microsoft_sales_rep_id text,
    notes text,
    organization_id text,
    organization_name text,
    postal_code text,
    qualification text,
    referral_id text,
    referral_source text,
    row_number text,
    sales_stage text,
    seller_created_at text,
    solutions jsonb,
    "state" text,
    "status" text,
    status_reason text,
    sub_status text,
    sync_error jsonb,
    updated_date_time text,
    uuid text,
    -- shared_referral_* (dynamic column),
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics_sales_activity (
    "index" text,
    fivetran_id text,
    sales_activity text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES aws_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics_next_step_detail (
    "index" text,
    fivetran_id text,
    next_step_author text,
    next_step_date text,
    next_step_value text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES aws_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics_delivery_model (
    "index" text,
    fivetran_id text,
    delivery_model text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES aws_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics_offer (
    "index" text,
    fivetran_id text,
    offer text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES aws_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics_campaign_name (
    "index" text,
    fivetran_id text,
    campaign_name text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES aws_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics_aws_product (
    "index" text,
    fivetran_id text,
    aws_product text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES aws_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics_solution_offered (
    "index" text,
    fivetran_id text,
    solution_offered text,
    PRIMARY KEY ("index", fivetran_id),
    FOREIGN KEY (fivetran_id) REFERENCES aws_cosell_opportunity_analytics(_fivetran_id)
);

CREATE TABLE aws_cosell_opportunity_analytics (
    _fivetran_id text,
    accept_by text,
    additional_comments text,
    apn_crm_unique_identifier text,
    apn_disqualified_reason text,
    apn_reviewer_comments text,
    aws_account_owner_email text,
    aws_account_owner_name text,
    aws_close_date text,
    aws_isv_success_manager_email text,
    aws_isv_success_manager_name text,
    aws_marketplace_engagement_score text,
    aws_partner_success_manager_email text,
    aws_partner_success_manager_name text,
    aws_sales_rep_email text,
    aws_sales_rep_name text,
    aws_stage text,
    business_unit text,
    closed_lost_reason text,
    cloud_created_date text,
    contract_end_date text,
    contract_start_date text,
    country text,
    customer_company_name text,
    customer_email text,
    customer_first_name text,
    customer_last_name text,
    customer_phone text,
    customer_software_value text,
    customer_website text,
    expected_monthly_aws_revenue text,
    geo text,
    industry text,
    is_greenfield text,
    is_marketing_development_funded text,
    is_opp_from_marketing_activity text,
    last_modified_date text,
    next_step text,
    opportunity_owner_email text,
    opportunity_ownership text,
    opportunity_type text,
    other_solution_offered text,
    partner_acceptance_status text,
    partner_developer_manager_email text,
    partner_developer_manager_name text,
    partner_primary_need_from_aws jsonb,
    partner_project_title text,
    postal_code text,
    primary_contact_email text,
    primary_contact_first_name text,
    primary_contact_last_name text,
    primary_contact_phone text,
    procurement_type text,
    project_description text,
    recommended_next_best_actions text,
    region text,
    rejection_reason text,
    sale_stage text,
    segment text,
    "state" text,
    "status" text,
    target_close_date text,
    use_case text,
    uuid text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE metering (
    id text,
    contract_id text,
    cloud text,
    dimemsion text,
    end_time text,
    quantity text,
    start_time timestamp,
    "status" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (contract_id) REFERENCES contract(id)
);

CREATE TABLE gcp_marketplace_disbursement_summary (
    _fivetran_id text,
    amount text,
    currency text,
    customer_refund text,
    ds text,
    entity text,
    notes text,
    payment_type text,
    total text,
    withholding text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE gcp_marketplace_incremental_daily_insight (
    _fivetran_id text,
    abandoned text,
    account_id text,
    billing_frequency text,
    channel text,
    charges text,
    company text,
    country text,
    currency text,
    "date" text,
    domain text,
    ds text,
    due_vendor text,
    earliest text,
    end_date text,
    entitlement_id text,
    external_account_id text,
    final_installment_date text,
    first_installment_date text,
    gpu_types text,
    installment_count text,
    internal_note text,
    latest text,
    machine_spec_sum text,
    num_cpus text,
    num_gpus text,
    num_vms text,
    offer_title text,
    order_end_date text,
    order_start_date text,
    parent_account_id text,
    payment_schedule text,
    payment_type text,
    postal_code text,
    postpay_credits text,
    prepay_credits text,
    private_offer_acceptance_date text,
    private_offer_total_contract_value text,
    probation_end text,
    probation_start text,
    quote_creator text,
    quote_id text,
    ram_mb text,
    released text,
    report_date text,
    reseller_discount text,
    sku_description text,
    sku_id text,
    solution_name text,
    start_date text,
    state_or_province text,
    term_total_contract_value text,
    transaction_type text,
    trial_use text,
    unit text,
    usage text,
    wholesale_charges text,
    withheld text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE azure_marketplace_order_analytics (
    _fivetran_id text,
    asset_id text,
    auto_renew text,
    azure_license_type text,
    billed_revenue text,
    billing_account_id text,
    billing_id text,
    billing_plan text,
    billing_term text,
    cloud_instance_name text,
    currency text,
    customer_company_name text,
    customer_country text,
    customer_id text,
    dataset_month text,
    discount_price_usd text,
    event_timestamp text,
    has_trial text,
    is_new_customer text,
    is_preview_sku text,
    is_private_offer text,
    is_private_plan text,
    is_trial text,
    list_price_usd text,
    marketplace_license_type text,
    marketplace_subscription_id text,
    month_start_date text,
    multi_party text,
    offer_id text,
    offer_name text,
    offer_type text,
    offer_visibility text,
    order_action text,
    order_cancel_date text,
    order_purchase_date text,
    order_status text,
    order_version text,
    plan_id text,
    plan_visibility text,
    private_offer_id text,
    private_offer_name text,
    purchase_record_id text,
    purchase_record_line_item_id text,
    quantity text,
    quantity_changed text,
    reference_id text,
    sku text,
    term_end_date text,
    term_start_date text,
    trial_end_date text,
    version text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE azure_marketplace_revenue_analytics (
    _fivetran_id text,
    adjustment_reason_code text,
    adjustment_type text,
    asset_id text,
    billing_account_id text,
    billing_id text,
    billing_model text,
    customer_city text,
    customer_company_name text,
    customer_country text,
    customer_email text,
    customer_id text,
    customer_name text,
    customer_postal_code text,
    customer_state text,
    dataset_month text,
    days_uncollected text,
    discounted_price_usd text,
    earning_amount_cc text,
    earning_amount_pc text,
    earning_amount_usd text,
    earning_currency_code text,
    earning_exchange_rate_pc text,
    earning_id text,
    estimated_payout_month text,
    estimated_revenue_pc text,
    estimated_revenue_usd text,
    event_time_stamp text,
    exchange_rate_date text,
    exchange_rate_pc text,
    exchange_rate_usd text,
    incentive_rate text,
    invoice_date text,
    invoice_due_date text,
    invoice_id text,
    is_invoiced text,
    is_private_offer text,
    is_private_plan text,
    line_item_id text,
    list_price_usd text,
    month_start_date text,
    multi_party text,
    offer_id text,
    offer_name text,
    offer_type text,
    offer_visibility text,
    payment_instrument_type text,
    payment_sent_date text,
    payout_currency text,
    payout_status text,
    plan_id text,
    plan_visibility text,
    private_offer_id text,
    private_offer_name text,
    purchase_record_id text,
    quantity text,
    reseller_city text,
    reseller_company text,
    reseller_country text,
    reseller_email text,
    reseller_id text,
    reseller_postal_code text,
    reseller_state text,
    revenue text,
    sales_channel text,
    sku text,
    term_end_date text,
    term_start_date text,
    transaction_amount_cc text,
    transaction_amount_pc text,
    transaction_amount_usd text,
    transaction_currency text,
    trial_deployment text,
    units text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE gcp_marketplace_disbursement_analytics (
    _fivetran_id text,
    abandoned_amount text,
    account_id text,
    aggregated_payout text,
    billing_frequency text,
    c_u_account_id text,
    channel text,
    country text,
    cud_credits_used text,
    cust_charges text,
    cust_identity text,
    cust_organization text,
    cust_remaining_commit text,
    disbursement_entity text,
    discount_offered text,
    domain text,
    ds text,
    entitlement_end_date text,
    entitlement_id text,
    entitlement_start_date text,
    final_installment_date text,
    first_installment_date text,
    first_refund_date text,
    insights_account_id text,
    installment_count text,
    last_refund_date text,
    marketplace_fee_amount text,
    marketplace_fee_percent text,
    max_usage_start_time text,
    min_usage_start_time text,
    offer_title text,
    order_end_date text,
    order_start_date text,
    organization_id text,
    partner_testing_credit text,
    payment_schedule text,
    postal_code text,
    private_offer_acceptance_date text,
    private_offer_creator text,
    private_offer_id text,
    private_offer_notes text,
    probation_start_date text,
    refund_processed_date text,
    refund_reason text,
    released_amount text,
    replaced_private_offer_id text,
    report_creation_date text,
    report_timezone text,
    reseller_discount text,
    sku_description text,
    sku_id text,
    solution_id text,
    solution_name text,
    state_or_province text,
    term_total_contract_value text,
    total_contract_value text,
    total_deductions text,
    transaction_type text,
    trial_credits_used text,
    usage_quantity text,
    usage_unit text,
    wholesale_charges text,
    withheld_amount text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE azure_marketplace_metered_usage_analytics (
    _fivetran_id text,
    asset_id text,
    azure_license_type text,
    billing_account_id text,
    billing_id text,
    cloud_instance_name text,
    core_size text,
    customer_company_name text,
    customer_country text,
    customer_currency_cc text,
    customer_id text,
    customer_name text,
    dataset_month text,
    deployment_method text,
    discounted_price_usd text,
    estimated_extended_charge_cc text,
    estimated_extended_charge_pc text,
    estimated_financial_impact_usd text,
    estimated_price_pc text,
    is_custom_meter text,
    is_multisolution text,
    is_new_customer text,
    is_preview_sku text,
    is_private_offer text,
    is_private_plan text,
    list_price_usd text,
    marketplace_license_type text,
    marketplace_subscription_id text,
    meter_dimension text,
    meter_id text,
    metered_usage text,
    month_start_date text,
    multi_party text,
    normalized_usage text,
    offer_id text,
    offer_name text,
    offer_type text,
    offer_visibility text,
    partner_center_detected_anomaly text,
    payout_currency_pc text,
    plan_id text,
    plan_visibility text,
    price_cc text,
    private_offer_id text,
    private_offer_name text,
    raw_usage text,
    reference_id text,
    sku text,
    skubilling_type text,
    usage_date text,
    usage_reference text,
    usage_unit text,
    vmsize text,
    vmsubscription text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE listing (
    id text,
    cloud text,
    cloud_id text,
    cloud_url text,
    eula_type text,
    eula_url text,
    last_modified_at text,
    long_description text,
    metadata jsonb,
    short_description text,
    "status" text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE private_offer (
    id text,
    listing_id text,
    accepted_at text,
    archived text,
    buyer_cloud_id text,
    buyer_company_name text,
    cloud text,
    cloud_id text,
    cloud_url text,
    duration text,
    end_date text,
    eula_type text,
    expiration_at text,
    last_modified_at text,
    metadata jsonb,
    "name" text,
    offer_type text,
    published_at text,
    salesforce_mapped_object_id text,
    salesforce_mapped_object_name text,
    salesforce_mapped_object_type text,
    salesforce_mapped_object_url text,
    salesforce_writeback_object_clazar_created text,
    salesforce_writeback_object_id text,
    salesforce_writeback_object_last_writeback_at text,
    salesforce_writeback_object_type text,
    salesforce_writeback_object_url text,
    start_date text,
    "status" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (listing_id) REFERENCES listing(id)
);

CREATE TABLE contract (
    id text,
    buyer_id text,
    latest_offer_id text,
    listing_id text,
    accepted_at text,
    auto_renew text,
    cloud text,
    cloud_id text,
    cloud_url text,
    duration text,
    end_at text,
    last_modified_at text,
    metadata jsonb,
    offer_type text,
    orb_mapped_object jsonb,
    salesforce_writeback_object_clazar_created text,
    salesforce_writeback_object_id text,
    salesforce_writeback_object_last_writeback_at text,
    salesforce_writeback_object_type text,
    salesforce_writeback_object_url text,
    start_at text,
    "status" text,
    total_contract_value text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (buyer_id) REFERENCES buyer(id),
    FOREIGN KEY (latest_offer_id) REFERENCES private_offer(id),
    FOREIGN KEY (listing_id) REFERENCES listing(id)
);

CREATE TABLE buyer_registration_detail (
    "index" text,
    buyer_id text,
    field text,
    "value" text,
    PRIMARY KEY ("index", buyer_id),
    FOREIGN KEY (buyer_id) REFERENCES buyer(id)
);

CREATE TABLE buyer (
    id text,
    latest_contract_id text,
    listing_id text,
    cloud text,
    cloud_account_id text,
    domain text,
    last_modified_at text,
    metadata jsonb,
    "name" text,
    orb_mapped_object jsonb,
    salesforce_writeback_object_clazar_created text,
    salesforce_writeback_object_id text,
    salesforce_writeback_object_last_writeback_at text,
    salesforce_writeback_object_type text,
    salesforce_writeback_object_url text,
    "status" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (latest_contract_id) REFERENCES contract(id),
    FOREIGN KEY (listing_id) REFERENCES listing(id)
);

CREATE TABLE opportunity (
    id text,
    accept_by text,
    cloud text,
    cloud_id text,
    cloud_url text,
    created_at text,
    customer_company text,
    customer_website text,
    last_modified_at text,
    metadata jsonb,
    salesforce_mapped_object_id text,
    salesforce_mapped_object_name text,
    salesforce_mapped_object_type text,
    salesforce_mapped_object_url text,
    salesforce_writeback_object_clazar_created text,
    salesforce_writeback_object_id text,
    salesforce_writeback_object_last_writeback_at text,
    salesforce_writeback_object_type text,
    salesforce_writeback_object_url text,
    stage text,
    "status" text,
    target_close_date text,
    title text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);
