CREATE TABLE source_node_hashed_column (
    environment_id text,
    id text,
    source_node_id text,
    PRIMARY KEY (environment_id, id, source_node_id),
    FOREIGN KEY (environment_id) REFERENCES source_node_column(environment_id),
    FOREIGN KEY (id) REFERENCES source_node_column(id),
    FOREIGN KEY (source_node_id) REFERENCES source_node_column(source_node_id)
);

CREATE TABLE source_node_column (
    id text,
    environment_id text,
    source_node_id text,
    applied_column_tests jsonb,
    column_references jsonb,
    config jsonb,
    data_type text,
    default_value text,
    description text,
    hash_algorithm text,
    hash_type text,
    hub_hashes jsonb,
    is_business_key text,
    is_change_tracking text,
    is_surrogate_key text,
    key_column_type text,
    "name" text,
    nullable text,
    primary_key text,
    sources jsonb,
    system_column_type text,
    transform text,
    unique_key text,
    PRIMARY KEY (id, environment_id, source_node_id),
    FOREIGN KEY (environment_id) REFERENCES source_node(environment_id),
    FOREIGN KEY (source_node_id) REFERENCES source_node(id)
);

CREATE TABLE source_node (
    id text,
    environment_id text,
    database text,
    description text,
    join_condition text,
    location_name text,
    "name" text,
    node_type jsonb,
    "schema" text,
    source_mapping jsonb,
    table_name text,
    PRIMARY KEY (id, environment_id),
    FOREIGN KEY (environment_id) REFERENCES environment(id)
);

CREATE TABLE sql_node_hashed_column (
    environment_id text,
    id text,
    sql_node_id text,
    PRIMARY KEY (environment_id, id, sql_node_id),
    FOREIGN KEY (environment_id) REFERENCES sql_node_column(environment_id),
    FOREIGN KEY (id) REFERENCES sql_node_column(id),
    FOREIGN KEY (sql_node_id) REFERENCES sql_node_column(sql_node_id)
);

CREATE TABLE sql_node_column (
    id text,
    environment_id text,
    sql_node_id text,
    applied_column_tests jsonb,
    column_references jsonb,
    config jsonb,
    data_type text,
    default_value text,
    description text,
    hash_algorithm text,
    hash_type text,
    hub_hashes jsonb,
    is_business_key text,
    is_change_tracking text,
    is_surrogate_key text,
    key_column_type text,
    "name" text,
    nullable text,
    primary_key text,
    sources jsonb,
    system_column_type text,
    transform text,
    unique_key text,
    PRIMARY KEY (id, environment_id, sql_node_id),
    FOREIGN KEY (environment_id) REFERENCES sql_node(environment_id),
    FOREIGN KEY (sql_node_id) REFERENCES sql_node(id)
);

CREATE TABLE sql_node_applied_test (
    "index" text,
    environment_id text,
    sql_node_id text,
    continue_on_failure text,
    description text,
    "name" text,
    run_order text,
    template_string text,
    PRIMARY KEY ("index", environment_id, sql_node_id),
    FOREIGN KEY (environment_id) REFERENCES sql_node(environment_id),
    FOREIGN KEY (sql_node_id) REFERENCES sql_node(id)
);

CREATE TABLE sql_node (
    id text,
    environment_id text,
    config jsonb,
    database text,
    description text,
    is_multisource text,
    join_condition text,
    location_name text,
    materialization_type text,
    metadata_cte_string text,
    metadata_description text,
    metadata_destination_name text,
    metadata_enabled_column_test_ids jsonb,
    metadata_mapping jsonb,
    metadata_materialization_option text,
    "name" text,
    node_type jsonb,
    override_sql text,
    "schema" text,
    source_mapping jsonb,
    table_name text,
    PRIMARY KEY (id, environment_id),
    FOREIGN KEY (environment_id) REFERENCES environment(id)
);

CREATE TABLE environment (
    id text,
    connection_account text,
    created_at text,
    created_by_first_name text,
    created_by_id text,
    created_by_last_name text,
    current_git_branch text,
    current_git_commit text,
    current_mappings jsonb,
    currently_running_jobs jsonb,
    default_storage_mapping text,
    deployed_commit text,
    description text,
    "name" text,
    oauth_enabled text,
    project_id text,
    run_time_parameters jsonb,
    "status" text,
    tag_background_color text,
    tag_text_color text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE run (
    id text,
    project_id text,
    run_environment_id text,
    canceled text,
    deploy_commit text,
    deploy_commit_message text,
    end_time text,
    environment_id text,
    exclude_nodes_selector text,
    executor text,
    force_ignore_environment_status text,
    history text,
    include_nodes_selector text,
    job_id text,
    nodes_for_refresh text,
    nodes_in_run text,
    parallelism text,
    re_run_id text,
    refresh_description text,
    start_time timestamp,
    "status" text,
    time_parameters jsonb,
    "type" text,
    user_credential_snowflake_account text,
    user_credential_snowflake_auth_type text,
    user_credential_snowflake_role text,
    user_credential_snowflake_username text,
    user_credential_snowflake_warehouse text,
    user_id text,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES environment(project_id),
    FOREIGN KEY (run_environment_id) REFERENCES environment(id)
);

CREATE TABLE run_query_result (
    "index" text,
    run_id text,
    run_result_node_id text,
    end_time text,
    error_detail text,
    error_string text,
    is_running text,
    "name" text,
    query_id text,
    row_deleted text,
    row_inserted text,
    row_updated text,
    sql text,
    start_time text,
    "status" text,
    success text,
    warehouse text,
    PRIMARY KEY ("index", run_id, run_result_node_id),
    FOREIGN KEY (run_id) REFERENCES run_result(run_id),
    FOREIGN KEY (run_result_node_id) REFERENCES run_result(node_id)
);

CREATE TABLE run_result (
    node_id text,
    run_id text,
    end_time text,
    error_detail text,
    error_string text,
    is_running text,
    "name" text,
    origin text,
    query_id text,
    row_deleted text,
    row_inserted text,
    row_updated text,
    run_state text,
    sql text,
    start_time text,
    "status" text,
    success text,
    warehouse text,
    PRIMARY KEY (node_id, run_id),
    FOREIGN KEY (run_id) REFERENCES run(id)
);
