CREATE TABLE learner_progress_card (
    id text,
    learner_id text,
    category_id text,
    group_id text,
    card_image text,
    card_image_alt_text text,
    card_image_mode text,
    card_image_offset text,
    code text,
    commenced text,
    completed text,
    due_date text,
    duration text,
    end_date text,
    enrolled text,
    grading_in_progress text,
    group_type text,
    image text,
    options jsonb,
    overview text,
    prerequisites jsonb,
    progress_percent text,
    "sequence" text,
    starred text,
    start_date text,
    study text,
    title text,
    updated text,
    PRIMARY KEY (id, learner_id),
    FOREIGN KEY (learner_id) REFERENCES learner(id),
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE learner_action (
    "action" text,
    learner_id text,
    PRIMARY KEY ("action", learner_id),
    FOREIGN KEY (learner_id) REFERENCES learner(id)
);

CREATE TABLE learner (
    id text,
    active text,
    avatar text,
    courses text,
    email text,
    first_name text,
    groups text,
    invitation_sent text,
    last_login text,
    last_name text,
    "name" text,
    removed text,
    user_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES users(id)
);

CREATE TABLE groups (
    id text,
    caps_admin text,
    caps_copy text,
    caps_create text,
    caps_delete text,
    caps_disenroll text,
    caps_edit text,
    caps_enrol text,
    caps_finance text,
    caps_invite text,
    caps_manage_enrolment text,
    caps_preview text,
    caps_publish_grades text,
    caps_remove_mirror text,
    caps_report text,
    caps_study text,
    caps_teach text,
    caps_view text,
    created text,
    "name" text,
    updated text,
    PRIMARY KEY (id)
);

CREATE TABLE enrolment_permission (
    permission text,
    enrolment_id text,
    PRIMARY KEY (permission, enrolment_id),
    FOREIGN KEY (enrolment_id) REFERENCES enrolment(id)
);

CREATE TABLE enrolment (
    id text,
    course_id text,
    group_id text,
    initiator text,
    user_id text,
    "action" text,
    catalog_active text,
    catalog_caps_admin text,
    catalog_caps_copy text,
    catalog_caps_create text,
    catalog_caps_delete text,
    catalog_caps_disenroll text,
    catalog_caps_edit text,
    catalog_caps_enrol text,
    catalog_caps_finance text,
    catalog_caps_invite text,
    catalog_caps_manage_enrolment text,
    catalog_caps_preview text,
    catalog_caps_publish_grades text,
    catalog_caps_remove_mirror text,
    catalog_caps_report text,
    catalog_caps_study text,
    catalog_caps_teach text,
    catalog_caps_view text,
    catalog_created text,
    catalog_draft_only text,
    catalog_id text,
    catalog_invited text,
    catalog_public text,
    catalog_published text,
    catalog_published_copy text,
    catalog_published_diff text,
    catalog_revision text,
    catalog_securable_identity jsonb,
    catalog_slug text,
    catalog_title text,
    catalog_updated text,
    "date" text,
    dtype text,
    group_students_count text,
    group_teachers_count text,
    group_type text,
    initiator_timezone text,
    user_timezone text,
    PRIMARY KEY (id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (initiator) REFERENCES users(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE course (
    id text,
    category_id text,
    trainer_id text,
    card_image text,
    card_image_mode text,
    card_image_offset_x text,
    card_image_offset_y text,
    code text,
    cover_image text,
    cover_image_alt_text text,
    cover_image_mode text,
    cover_image_offset text,
    default_cover_image text,
    duration text,
    groups_count text,
    overview_content text,
    title text,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (trainer_id) REFERENCES users(id)
);

CREATE TABLE learner_course (
    course_id text,
    learner_id text,
    PRIMARY KEY (course_id, learner_id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (learner_id) REFERENCES learner(id)
);

CREATE TABLE category (
    id text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE assignment (
    id text,
    description text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE user_role (
    role_id text,
    users_id text,
    "name" text,
    "role" text,
    PRIMARY KEY (role_id, users_id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    accreditable_id text,
    active text,
    avatar text,
    created text,
    custom_value text,
    disable_course_enrolment_notification text,
    email text,
    email_verified text,
    first_name text,
    last_login text,
    last_name text,
    last_sent text,
    local text,
    number_of_logins text,
    timezone text,
    user_name text,
    PRIMARY KEY (id)
);

CREATE TABLE "result" (
    id text,
    course_id text,
    group_id text,
    user_id text,
    accreditable_user_custom_value text,
    children jsonb,
    commenced text,
    completed text,
    passed text,
    progress_percent text,
    score_percent text,
    total_time text,
    updated text,
    PRIMARY KEY (id),
    FOREIGN KEY (course_id) REFERENCES course(id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE module_result (
    id text,
    parent_id text,
    user_id text,
    accreditable_identity_custom_value text,
    accreditable_identity_dtype text,
    commenced text,
    completed text,
    feedback text,
    lms_id text,
    module_access text,
    module_entity_type text,
    module_id text,
    module_launch text,
    module_module_type text,
    module_path text,
    module_required text,
    module_scorm_version text,
    module_title text,
    parent_access text,
    parent_commenced text,
    parent_completed text,
    parent_course_trainer text,
    parent_deleted text,
    parent_fresh text,
    parent_group_dtype text,
    parent_identifier text,
    parent_login_count text,
    parent_only_non_deleted text,
    parent_passed text,
    parent_progress_percent text,
    parent_report_url text,
    parent_score_max text,
    parent_score_percent text,
    parent_score_percentage text,
    parent_score_percentage_string text,
    parent_score_raw text,
    parent_starred text,
    parent_student_name text,
    parent_total_time text,
    parent_user_active text,
    parent_user_created text,
    parent_user_email_verified text,
    passed text,
    progress_percent text,
    score_max text,
    score_percent text,
    score_percentage text,
    score_percentage_string text,
    score_raw text,
    student_name text,
    total_time text,
    trainer text,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES "result"(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
