CREATE TABLE business_detail_beneficial_owner (
    "index" text,
    business_detail_id text,
    address_city text,
    address_country_code text,
    address_line_1 text,
    address_line_2 text,
    address_postal_code text,
    address_state text,
    date_of_birth text,
    drivers_license text,
    email text,
    first_name text,
    last_name text,
    middle_name text,
    national_id text,
    passport jsonb,
    ssn text,
    PRIMARY KEY ("index", business_detail_id),
    FOREIGN KEY (business_detail_id) REFERENCES business_detail(id)
);

CREATE TABLE business_detail (
    id text,
    address_city text,
    address_country_code text,
    address_line_1 text,
    address_line_2 text,
    address_postal_code text,
    address_state text,
    business_name text,
    ein text,
    industry text,
    legal_type text,
    registration_id_country_code text,
    registration_id_number text,
    website text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES entity(id)
);

CREATE TABLE payment (
    id text,
    account_id text,
    bank_account_id text,
    loan_id text,
    created_at text,
    currency text,
    description text,
    principal_amount text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id),
    FOREIGN KEY (loan_id) REFERENCES loan(id)
);

CREATE TABLE event (
    id text,
    created_at text,
    data jsonb,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE counter_party (
    id text,
    local_account_number text,
    account_number text,
    account_type text,
    address_city text,
    address_country_code text,
    address_line_1 text,
    address_line_2 text,
    address_postal_code text,
    address_state text,
    beneficiary_address_city text,
    beneficiary_address_country_code text,
    beneficiary_address_line_1 text,
    beneficiary_address_line_2 text,
    beneficiary_address_postal_code text,
    beneficiary_address_state text,
    created_at text,
    description text,
    email text,
    is_column_account text,
    legal_id text,
    legal_type text,
    local_bank_code text,
    local_bank_country_code text,
    local_bank_name text,
    "name" text,
    phone text,
    routing_number text,
    routing_number_type text,
    updated_at text,
    wire_beneficiary_email text,
    wire_beneficiary_legal_id text,
    wire_beneficiary_name text,
    wire_beneficiary_phone text,
    wire_beneficiary_type text,
    wire_drawdown_allowed text,
    wire_local_account_number text,
    wire_local_bank_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (local_account_number) REFERENCES account(id)
);

CREATE TABLE disbursement (
    id text,
    account_id text,
    bank_account_id text,
    loan_id text,
    amount text,
    created_at text,
    currency text,
    description text,
    effective_at text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id),
    FOREIGN KEY (loan_id) REFERENCES loan(id)
);

CREATE TABLE account (
    id text,
    bank_account_id text,
    account_number text,
    created_at text,
    description text,
    routing_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id)
);

CREATE TABLE loan (
    id text,
    primary_signer_entity_id text,
    balances_principal_charged_off text,
    balances_principal_holding text,
    balances_principal_outstanding text,
    balances_principal_paid text,
    canceled_at text,
    charged_off_at text,
    created_at text,
    currency text,
    delinquent_at text,
    description text,
    disputed_at text,
    is_revolving text,
    maturity_date text,
    max_principal_balance text,
    paid_off_at text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (primary_signer_entity_id) REFERENCES entity(id)
);

CREATE TABLE entity (
    id text,
    document jsonb,
    is_root text,
    "name" text,
    review_reason jsonb,
    "type" text,
    verification_status text,
    PRIMARY KEY (id)
);

CREATE TABLE book_transfer (
    id text,
    receiver_account_id text,
    receiver_bank_account_id text,
    sender_account_id text,
    sender_bank_account_id text,
    allow_overdraft text,
    amount text,
    created_at text,
    currency_code text,
    description text,
    idempotency_key text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (receiver_account_id) REFERENCES account(id),
    FOREIGN KEY (receiver_bank_account_id) REFERENCES bank_account(id),
    FOREIGN KEY (sender_account_id) REFERENCES account(id),
    FOREIGN KEY (sender_bank_account_id) REFERENCES bank_account(id)
);

CREATE TABLE transfer (
    id text,
    account_id text,
    counterparty_id text,
    sender_bank_account_id text,
    amount text,
    completed_at text,
    created_at text,
    currency_code text,
    description text,
    external_source_bank_name text,
    external_source_sender_name text,
    idempotency_key text,
    is_incoming text,
    receiver_internal_account_account_number_id text,
    receiver_internal_account_bank_account_id text,
    sender_account_id text,
    "status" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (counterparty_id) REFERENCES counter_party(id),
    FOREIGN KEY (sender_bank_account_id) REFERENCES bank_account(id)
);

CREATE TABLE wire_draw_down (
    id text,
    account_id text,
    bank_account_id text,
    amount text,
    beneficiary_account_number text,
    beneficiary_counterparty_id text,
    beneficiary_name text,
    currency_code text,
    imad text,
    is_incoming text,
    message_identifier text,
    originator_account_number text,
    originator_name text,
    originator_to_beneficiary_information text,
    received_at text,
    receiver_di_name text,
    receiver_di_routing_number text,
    sender_di_name text,
    sender_di_routing_number text,
    "status" text,
    wire_transfer_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id)
);

CREATE TABLE ach_return_detail (
    _fivetran_id text,
    ach_return_id text,
    addenda text,
    created_at text,
    description text,
    return_code text,
    "status" text,
    updated_at text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (ach_return_id) REFERENCES ach_return(id)
);

CREATE TABLE ach_return (
    id text,
    ach_transfer_id text,
    created_at text,
    is_incoming text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (ach_transfer_id) REFERENCES ach_transfer(id)
);

CREATE TABLE international_wire_charge (
    _fivetran_id text,
    international_wire_id text,
    agent text,
    amount text,
    currency_code text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (international_wire_id) REFERENCES international_wire(id)
);

CREATE TABLE international_wire (
    id text,
    account_number_id text,
    bank_account_id text,
    account_id text,
    allow_overdraft text,
    amount text,
    beneficiary_account_number text,
    beneficiary_address_city text,
    beneficiary_address_country_code text,
    beneficiary_address_line_1 text,
    beneficiary_address_line_2 text,
    beneficiary_address_postal_code text,
    beneficiary_address_state text,
    beneficiary_fi text,
    beneficiary_name text,
    charge_bearer text,
    charges jsonb,
    completed_at text,
    counterparty_id text,
    created_at text,
    currency_code text,
    description text,
    end_to_end_id text,
    fx_quota_id text,
    fx_rate text,
    idempotency_key text,
    initiated_at text,
    instructed_amount text,
    instructed_currency_code text,
    instruction_id text,
    instruction_to_beneficiary_fi text,
    is_incoming text,
    manual_review_at text,
    originator_account_number text,
    originator_address_city text,
    originator_address_country_code text,
    originator_address_line_1 text,
    originator_address_line_2 text,
    originator_address_postal_code text,
    originator_address_state text,
    originator_fi text,
    originator_name text,
    pending_submission_at text,
    raw_message text,
    remittance_info_general_info text,
    return_reason text,
    returned_amount text,
    returned_at text,
    returned_currency_code text,
    settled_amount text,
    settled_currency_code text,
    settlement_date text,
    "status" text,
    submitted_at text,
    uetr text,
    ultimate_beneficiary_address text,
    ultimate_beneficiary_name text,
    ultimate_originator_address text,
    ultimate_originator_name text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_number_id) REFERENCES account(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id)
);

CREATE TABLE ach_transfer (
    id text,
    account_id text,
    bank_account_id text,
    counterparty_id text,
    acknowledged_at text,
    allow_overdraft text,
    amount text,
    cancelled_at text,
    company_discretionary_data text,
    company_entry_description text,
    company_id text,
    company_name text,
    completed_at text,
    created_at text,
    currency_code text,
    description text,
    effective_on text,
    entry_class_code text,
    iat_foreign_correspondent_bank_info jsonb,
    iat_foreign_payment_amount text,
    iat_foreign_trace_number text,
    iat_odfi_branch_country_code text,
    iat_odfi_identification text,
    iat_odfi_identification_number_qualifier text,
    iat_odfi_name text,
    iat_originator_city_state_province text,
    iat_originator_country_postal_code text,
    iat_originator_name text,
    iat_originator_street_address text,
    iat_payment_related_info text,
    iat_rdfi_branch_country_code text,
    iat_rdfi_identification text,
    iat_rdfi_identification_number_qualifier text,
    iat_rdfi_name text,
    iat_receiver_city_state_province text,
    iat_receiver_country_postal_code text,
    iat_receiver_identification_number text,
    iat_receiver_street_address text,
    iat_receiving_company_or_individual_name text,
    iat_transaction_type_code text,
    idempotency_key text,
    initiated_at text,
    intermediary_financial_institutions text,
    is_incoming text,
    is_on_us text,
    manual_review_at text,
    notification_of_changes text,
    nsf_deadline text,
    odfi_routing_number text,
    payment_related_info text,
    receiver_id text,
    receiver_name text,
    return_contested_at text,
    return_detail jsonb,
    return_dishonored_at text,
    returned_at text,
    reversal_pair_transfer_id text,
    same_day text,
    settled_at text,
    "status" text,
    submitted_at text,
    trace_number text,
    "type" text,
    ultimate_beneficiary_counterparty_id text,
    ultimate_originator_counterparty_id text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id),
    FOREIGN KEY (counterparty_id) REFERENCES counter_party(id)
);

CREATE TABLE check_return (
    id text,
    check_transfer_id text,
    created_at text,
    return_reason text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (check_transfer_id) REFERENCES check_transfer(id)
);

CREATE TABLE check_transfer (
    id text,
    account_number_id text,
    bank_account_id text,
    account_id text,
    back_image text,
    check_number text,
    created_at text,
    currency_code text,
    delivered_by_column text,
    delivery_status text,
    deposited_amount text,
    deposited_at text,
    description text,
    external_routing_number text,
    first_return_at text,
    front_image text,
    idempotency_key text,
    is_preview_pdf_available text,
    issued_at text,
    manual_review_at text,
    memo text,
    message text,
    micr_line_amount_field text,
    micr_line_auxiliary_on_us text,
    micr_line_external_processing_code text,
    micr_line_on_us text,
    micr_line_payor_bank_routing_number text,
    payee_address text,
    payee_name text,
    pending_deposit_at text,
    pending_first_return_at text,
    pending_stop_at text,
    pending_user_initiated_return_at text,
    positive_pay_amount text,
    reclear_at text,
    rejected_at text,
    second_return_at text,
    settled_at text,
    "status" text,
    stopped_at text,
    "type" text,
    updated_at text,
    user_initiated_return_dishonored_at text,
    user_initiated_return_submitted_at text,
    user_initiated_returned_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_number_id) REFERENCES account(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id)
);

CREATE TABLE person_detail (
    id text,
    address_city text,
    address_country_code text,
    address_line_1 text,
    address_line_2 text,
    address_postal_code text,
    address_state text,
    date_of_birth text,
    email text,
    first_name text,
    last_name text,
    middle_name text,
    passport jsonb,
    ssn text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES entity(id)
);

CREATE TABLE bank_account_owner (
    bank_account_id text,
    owner_id text,
    PRIMARY KEY (bank_account_id, owner_id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id),
    FOREIGN KEY (owner_id) REFERENCES entity(id)
);

CREATE TABLE bank_account (
    id text,
    default_account_id text,
    balances_available_amount text,
    balances_holding_amount text,
    balances_locked_amount text,
    balances_pending_amount text,
    created_at text,
    currency_code text,
    default_account_number text,
    description text,
    is_overdraftable text,
    overdraft_reserve_account_id text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (default_account_id) REFERENCES account(id)
);

CREATE TABLE wire_transfer (
    id text,
    account_id text,
    bank_account_id text,
    counterparty_id text,
    allow_overdraft text,
    amount text,
    completed_at text,
    created_at text,
    currency_code text,
    description text,
    idempotency_key text,
    initiated_at text,
    is_incoming text,
    is_on_us text,
    pending_submission_at text,
    platform_id text,
    rejected_at text,
    "status" text,
    submitted_at text,
    updated_at text,
    wire_drawdown_request_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_account(id),
    FOREIGN KEY (counterparty_id) REFERENCES counter_party(id)
);
