CREATE TABLE track_demo_board_demo_uuid (
    "index" text,
    track_demo_board_id text,
    demo_uuid text,
    PRIMARY KEY ("index", track_demo_board_id),
    FOREIGN KEY (track_demo_board_id) REFERENCES track_demo_board(id),
    FOREIGN KEY (demo_uuid) REFERENCES demo_search(id)
);

CREATE TABLE track_demo_board_invite_view_data_feature (
    "index" text,
    track_demo_board_id text,
    track_demo_board_invite_view_data_index text,
    title text,
    uuid text,
    "value" text,
    PRIMARY KEY ("index", track_demo_board_id, track_demo_board_invite_view_data_index),
    FOREIGN KEY (track_demo_board_id) REFERENCES track_demo_board_invite_view_data(track_demo_board_id),
    FOREIGN KEY (track_demo_board_invite_view_data_index) REFERENCES track_demo_board_invite_view_data("index")
);

CREATE TABLE track_demo_board_invite_view_data (
    "index" text,
    track_demo_board_id text,
    track_demo_board_invite_index text,
    demo_uuid text,
    answer_index text,
    answer_name text,
    date_view text,
    demo_title text,
    duration text,
    features jsonb,
    files text,
    is_replay text,
    link_uuid text,
    selected_demo_uuid text,
    view_id text,
    PRIMARY KEY ("index", track_demo_board_id, track_demo_board_invite_index),
    FOREIGN KEY (track_demo_board_id) REFERENCES track_demo_board_invite(track_demo_board_id),
    FOREIGN KEY (track_demo_board_invite_index) REFERENCES track_demo_board_invite("index"),
    FOREIGN KEY (demo_uuid) REFERENCES demo_search(id)
);

CREATE TABLE track_demo_board_invite (
    "index" text,
    track_demo_board_id text,
    contact_uuid text,
    email text,
    first_name text,
    hash text,
    invite_status text,
    invite_uuid text,
    last_name text,
    "name" text,
    primaries text,
    shared_by_name text,
    shared_by_uuid text,
    shares text,
    "source" text,
    source_hr text,
    title text,
    total_duration text,
    total_hotspot_opened text,
    total_page_view text,
    total_tour_view text,
    PRIMARY KEY ("index", track_demo_board_id),
    FOREIGN KEY (track_demo_board_id) REFERENCES track_demo_board(id)
);

CREATE TABLE track_demo_board (
    id text,
    demo_uuid text,
    creation_date text,
    creation_source text,
    external_account_id text,
    external_account_name text,
    external_oppurtunity_id text,
    external_oppurtunity_name text,
    is_test text,
    "name" text,
    organization text,
    owner_name text,
    owner_uuid text,
    parent_demo_uuid jsonb,
    send_demo_hash text,
    shared_count text,
    time_last_view text,
    total_hotspot_opened text,
    total_page_views text,
    total_tour_views text,
    view_count text,
    view_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (demo_uuid) REFERENCES demo_search(id)
);

CREATE TABLE sales_by_customer_detailed (
    id text,
    demo_uuid text,
    branching_response text,
    created_by text,
    creation_source text,
    date_created text,
    date_invited text,
    days_from_last_activity text,
    demo_creator_email text,
    demo_title text,
    email text,
    invited_by text,
    not_important_selected text,
    organization text,
    recipient text,
    shares_by_viewer text,
    some_what_important_selected text,
    sub_demo_title text,
    time_diff text,
    very_important_selected text,
    view_date text,
    view_location text,
    view_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (demo_uuid) REFERENCES demo_search(id)
);

CREATE TABLE search_lead_feature (
    "index" text,
    search_lead_id text,
    title text,
    uuid text,
    "value" text,
    PRIMARY KEY ("index", search_lead_id),
    FOREIGN KEY (search_lead_id) REFERENCES search_lead(id)
);

CREATE TABLE search_lead_custom_field (
    "name" text,
    search_lead_id text,
    "value" text,
    PRIMARY KEY ("name", search_lead_id),
    FOREIGN KEY (search_lead_id) REFERENCES search_lead(id)
);

CREATE TABLE search_lead (
    id text,
    demo_uuid text,
    view_id text,
    answer_index text,
    answer_name text,
    answer_parent_demo_title text,
    answer_parent_demo_uuid text,
    answer_selected_demo_title text,
    answer_selected_demo_uuid text,
    answer_selected_index text,
    answer_selected_title text,
    creation_date text,
    date_view text,
    demo_title text,
    doc_download text,
    email text,
    first_name text,
    form_comments text,
    form_country text,
    form_email text,
    form_first_name text,
    form_last_name text,
    form_organization text,
    form_phone_number text,
    form_session_eu text,
    form_session_i text,
    form_session_nostat text,
    form_session_organization_id text,
    form_session_u text,
    form_session_v text,
    form_state text,
    form_title text,
    geo_data_location_name text,
    geo_data_time_zone text,
    last_name text,
    lead_owner_group text,
    organization text,
    utm jsonb,
    view_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (demo_uuid) REFERENCES demo_search(id),
    FOREIGN KEY (view_id) REFERENCES track_demo_board(id)
);

CREATE TABLE user_info (
    id text,
    active text,
    creator_uuid text,
    date_format text,
    display_name text,
    email text,
    first_name text,
    group_creator_full_name text,
    group_creator_uuid text,
    group_description text,
    group_expiry_date text,
    group_level text,
    group_name text,
    group_parent_uuid text,
    group_status text,
    group_time_updated text,
    group_type text,
    group_uuid text,
    languages text,
    last_name text,
    notifications jsonb,
    phone_number text,
    "status" text,
    time_created text,
    time_updated text,
    time_zone text,
    title text,
    we_chat text,
    whats_app text,
    PRIMARY KEY (id)
);

CREATE TABLE mail_merge_list (
    id text,
    contact_info_uuids text,
    combine text,
    contact_info_uuid text,
    created_at timestamp,
    demo_internal_title text,
    demo_title text,
    demo_uuid text,
    exclude_owner text,
    hash text,
    owner_name text,
    owner_phone text,
    owner_uuid text,
    platform_id text,
    platform_name text,
    riv_source text,
    riv_uuid text,
    show_user_contact_info text,
    skip_way text,
    title text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact_info_uuids) REFERENCES demo_search_permission(permission_id)
);

CREATE TABLE demo_search_permission (
    permission_id text,
    demo_search_id text,
    display_name text,
    group_level text,
    shared_below text,
    "type" text,
    "value" jsonb,
    PRIMARY KEY (permission_id, demo_search_id),
    FOREIGN KEY (demo_search_id) REFERENCES demo_search(id)
);

CREATE TABLE demo_search_tour (
    "index" text,
    demo_search_id text,
    feature_uuid text,
    thumbs_default jsonb,
    tour_id text,
    PRIMARY KEY ("index", demo_search_id),
    FOREIGN KEY (demo_search_id) REFERENCES demo_search(id)
);

CREATE TABLE demo_search_folder_permission (
    "index" text,
    demo_search_id text,
    display_name text,
    folder_name text,
    folder_permission_id text,
    folder_uuid text,
    group_level text,
    shared_below text,
    "type" text,
    "value" jsonb,
    PRIMARY KEY ("index", demo_search_id),
    FOREIGN KEY (demo_search_id) REFERENCES demo_search(id)
);

CREATE TABLE demo_search (
    id text,
    created_at text,
    creator_email text,
    creator_first_name text,
    creator_last_name text,
    creator_uuid text,
    description text,
    draft text,
    folder_name text,
    folder_uuid text,
    highspot_is_published text,
    highspot_published_date text,
    internal_title text,
    is_archived text,
    is_public text,
    is_published text,
    language_code text,
    language_title text,
    title text,
    "type" text,
    uuid_type text,
    PRIMARY KEY (id)
);
