CREATE TABLE user_status (
    id text,
    active text,
    "status" text,
    PRIMARY KEY (id)
);

CREATE TABLE transcript_status (
    id text,
    "status" text,
    PRIMARY KEY (id)
);

CREATE TABLE goal (
    id text,
    user_id text,
    active_flag text,
    aligned_with text,
    categories_list text,
    created_by_id text,
    created_by_name text,
    created_date text,
    deleted_flag text,
    description text,
    difficulty_to_achieve text,
    difficulty_to_achieve_title text,
    marked_as_final text,
    marked_as_final_date text,
    num_attachment text,
    parent_goal_title text,
    perspective_id text,
    perspective_title text,
    progress text,
    start_date text,
    status_id text,
    status_title text,
    target_date text,
    title text,
    visible_to_others text,
    weight text,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE requisition_cf (
    id text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES requisition(ats_req_id)
);

CREATE TABLE requisition_location (
    ats_multi_loc_req_loc_id text,
    ats_multi_loc_req_id text,
    ats_multi_loc_city text,
    ats_multi_loc_country text,
    ats_multi_loc_is_primary text,
    ats_multi_loc_line_1 text,
    ats_multi_loc_line_2 text,
    ats_multi_loc_req_ref text,
    ats_multi_loc_state text,
    ats_multi_loc_zip text,
    PRIMARY KEY (ats_multi_loc_req_loc_id, ats_multi_loc_req_id),
    FOREIGN KEY (ats_multi_loc_req_id) REFERENCES requisition(ats_req_id)
);

CREATE TABLE transcript_status_group (
    user_lo_status_group_id text,
    user_lo_status_group text,
    PRIMARY KEY (user_lo_status_group_id)
);

CREATE TABLE training_curricula (
    _fivetran_id text,
    child_object_id text,
    object_id text,
    section_object_id text,
    version text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE training_assignment_user (
    pu_proxy_id text,
    pu_user_id text,
    pu_object_id text,
    pu_is_dymanic_remove text,
    PRIMARY KEY (pu_proxy_id, pu_user_id),
    FOREIGN KEY (pu_user_id) REFERENCES users(id),
    FOREIGN KEY (pu_object_id) REFERENCES training(id)
);

CREATE TABLE test (
    eval_attempt_number text,
    eval_question_id text,
    eval_lo_id text,
    eval_reg_num text,
    eval_user_id text,
    eval_attempt_complete_date text,
    eval_attempt_date text,
    eval_attempt_score text,
    eval_lo_active text,
    eval_lo_description text,
    eval_lo_version_comment text,
    eval_lo_version_effective_dt text,
    eval_max_attempt text,
    eval_question_active_id text,
    eval_question_category_id text,
    eval_question_correct text,
    eval_question_text_id text,
    eval_question_type_id text,
    eval_response_item_id text,
    eval_section_text_id text,
    eval_status_id text,
    question_type_id text,
    score text,
    user_response_id text,
    PRIMARY KEY (eval_attempt_number, eval_question_id, eval_lo_id, eval_reg_num, eval_user_id),
    FOREIGN KEY (eval_lo_id) REFERENCES training(id),
    FOREIGN KEY (eval_reg_num) REFERENCES transcript(reg_num),
    FOREIGN KEY (eval_user_id) REFERENCES users(id)
);

CREATE TABLE requisition (
    ats_req_id text,
    ats_req_primary_owner_id text,
    ats_req_request_creator_id text,
    ats_contact_phone text,
    ats_req_app_wfl_template text,
    ats_req_app_wfl_template_id text,
    ats_req_attached_documents text,
    ats_req_bonus_amount text,
    ats_req_can_apply text,
    ats_req_candidates_number text,
    ats_req_closed_date text,
    ats_req_compensation_high text,
    ats_req_compensation_low text,
    ats_req_compensation_type text,
    ats_req_compensation_type_id text,
    ats_req_cost_center_ref text,
    ats_req_created_date text,
    ats_req_currency text,
    ats_req_currency_id text,
    ats_req_days_open text,
    ats_req_div_id text,
    ats_req_division_ref text,
    ats_req_eeo_cat text,
    ats_req_eeo_cat_id text,
    ats_req_empl_type_id text,
    ats_req_filled_date text,
    ats_req_full_part text,
    ats_req_full_part_id text,
    ats_req_grade_id text,
    ats_req_grade_ref text,
    ats_req_hiring_manager_id text,
    ats_req_id_pk text,
    ats_req_jb_show_salary_external text,
    ats_req_ongoing text,
    ats_req_opened_date text,
    ats_req_openings_org text,
    ats_req_openings_outstanding text,
    ats_req_parent_req_ref text,
    ats_req_position_id text,
    ats_req_position_ref text,
    ats_req_posting_career_center text,
    ats_req_postings_number text,
    ats_req_priority text,
    ats_req_priority_id text,
    ats_req_ref text,
    ats_req_request_created_date text,
    ats_req_request_review_date text,
    ats_req_status text,
    ats_req_status_id text,
    ats_req_submission_number text,
    ats_req_suggested_referrals_number text,
    ats_req_target_hire_date text,
    ats_req_template_ref text,
    ats_req_time_to_fill text,
    ats_req_type_id text,
    ats_requisition_template_id text,
    cost_center_id text,
    PRIMARY KEY (ats_req_id),
    FOREIGN KEY (ats_req_primary_owner_id) REFERENCES users(id),
    FOREIGN KEY (ats_req_request_creator_id) REFERENCES users(id)
);

CREATE TABLE performance_review (
    user_task_id text,
    user_id text,
    task_active_flag text,
    task_end_date text,
    task_name text,
    task_start_date text,
    task_user_completion_date text,
    task_user_expiration_date text,
    task_user_id text,
    task_user_is_active text,
    task_user_override text,
    task_user_override_adjusted text,
    task_user_override_text text,
    task_user_rating text,
    task_user_rating_adjusted text,
    task_user_rating_text text,
    task_user_recurrance text,
    task_user_start_date text,
    task_user_status text,
    task_user_status_id text,
    task_user_title text,
    task_user_user_id text,
    warehouse_performance_custom_fields_reccurance text,
    warehouse_performance_custom_fields_task_id text,
    warehouse_performance_custom_fields_user_id text,
    PRIMARY KEY (user_task_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_customer_field (
    user_id text,
    last_touched_date_utc text,
    warehouse_user_custom_field_user_id text,
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE training (
    id text,
    lo_modified_by_user_id text,
    browser_compatibility_mode text,
    classification text,
    classification_id text,
    course_code text,
    deactivation_date text,
    electronic_signature_required text,
    event_max_enrollment text,
    event_min_enrollment text,
    is_available_offline text,
    is_available_offline_network text,
    is_excluded_from_recommendation text,
    is_latest_training_version text,
    is_ojt_enabled text,
    keywords text,
    last_touched_date_utc text,
    latest_version text,
    lo_active text,
    lo_admin_session_selection_allowed text,
    lo_adv_reg_deadline text,
    lo_billing_entity text,
    lo_billing_entity_name text,
    lo_connect_item_type_id text,
    lo_contact text,
    lo_contact_user_ref text,
    lo_create_dt text,
    lo_created_by text,
    lo_created_by_fullname text,
    lo_created_by_user_id text,
    lo_created_by_user_ref text,
    lo_credit text,
    lo_currency_code text,
    lo_currency_id text,
    lo_currency_symbol text,
    lo_email_option_id text,
    lo_end_dt text,
    lo_end_registration text,
    lo_eval_01 text,
    lo_eval_01_override text,
    lo_eval_02 text,
    lo_eval_02_override text,
    lo_eval_03 text,
    lo_eval_03_override text,
    lo_hours text,
    lo_instructor text,
    lo_instructor_id text,
    lo_interest_tracking_allowed text,
    lo_is_mobile_compatible text,
    lo_is_part_of_curriculum text,
    lo_language text,
    lo_language_id text,
    lo_location_id text,
    lo_locator text,
    lo_mastery_score text,
    lo_material_status text,
    lo_material_type_active text,
    lo_material_type_id text,
    lo_max_score text,
    lo_min_parts text,
    lo_modified_date text,
    lo_multiple_sessions_allowed text,
    lo_no_show text,
    lo_object_id text,
    lo_object_type text,
    lo_owner_names text,
    lo_owners_ids text,
    lo_postwork_titles text,
    lo_prework_titles text,
    lo_price text,
    lo_product_code text,
    lo_provider text,
    lo_provider_active text,
    lo_provider_address_1 text,
    lo_provider_address_2 text,
    lo_provider_city text,
    lo_provider_id text,
    lo_provider_mailstop text,
    lo_provider_state text,
    lo_provider_zip text,
    lo_publication_created_by text,
    lo_publication_created_date text,
    lo_publication_id text,
    lo_publication_published text,
    lo_ref text,
    lo_reg_max text,
    lo_reg_min text,
    lo_root_id text,
    lo_root_ref text,
    lo_root_title text,
    lo_seats_available text,
    lo_seats_taken text,
    lo_seats_total text,
    lo_secondary_training_provider text,
    lo_secondary_training_provider_id text,
    lo_session_selection_allowed text,
    lo_size text,
    lo_skills text,
    lo_start_date text,
    lo_status text,
    lo_status_type text,
    lo_test_attempts_allowed text,
    lo_test_graders_ids text,
    lo_test_max_entries text,
    lo_test_max_time_allowed text,
    lo_timezone_code text,
    lo_timezone_id text,
    lo_title text,
    lo_total_cost text,
    lo_total_users_requests text,
    lo_training_ref text,
    lo_type text,
    lo_type_id text,
    lo_version text,
    lo_waitlist_allowed text,
    lo_waitlist_auto_manage text,
    lo_waitlist_auto_register text,
    lo_withdraw_date text,
    lo_withdrawal_penalty text,
    object_type text,
    online_course_protocol_id text,
    related_lo_id text,
    total_sco text,
    version_effective_date text,
    version_end_date text,
    version_start_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (lo_modified_by_user_id) REFERENCES users(id)
);

CREATE TABLE curriculum (
    id text,
    active text,
    course_code text,
    created_by_name text,
    created_by_user_id text,
    deactivation_date text,
    is_latest_training_version text,
    modified_by_name text,
    modified_by_user_id text,
    modified_date text,
    object_type text,
    "status" text,
    status_type text,
    training_version_effective_date text,
    "type" text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id text,
    status_id text,
    activation_date text,
    address_1 text,
    address_2 text,
    allow_reconcile text,
    applicant_archived_flag text,
    appr_id text,
    appr_mailstop text,
    appr_name_first text,
    appr_name_last text,
    appr_ref text,
    approval text,
    birth_date text,
    category_id text,
    city text,
    company_no text,
    country text,
    create_date text,
    deactivation_date text,
    eligible_for_rehire text,
    email text,
    employment_status_id text,
    ethnicity text,
    exempt text,
    gender text,
    guid text,
    has_photo text,
    hire_date_last text,
    hire_date_orig text,
    i_mgr_email text,
    i_mgr_id text,
    i_mgr_name_first text,
    i_mgr_name_last text,
    indirect_manager_name text,
    indirect_manager_ref text,
    is_rehired_employee text,
    is_user_absent text,
    language_id text,
    last_login text,
    last_touched_date_utc text,
    leave_reason_id text,
    local_system_id text,
    login text,
    mailstop text,
    mgr_email text,
    mgr_id text,
    mgr_mailstop text,
    mgr_name_first text,
    mgr_name_last text,
    mgr_ref text,
    modify_date text,
    name_first text,
    name_last text,
    name_middle text,
    name_prefix text,
    name_suffix text,
    personal_email text,
    phone_fax text,
    phone_home text,
    phone_mobile text,
    phone_work text,
    ref text,
    "state" text,
    sub_category_id text,
    tax_override text,
    tax_override_unit text,
    tenure_month text,
    termination_date text,
    termination_reason_id text,
    termination_type text,
    timezone_id text,
    "type" text,
    vat_number text,
    zip text,
    PRIMARY KEY (id),
    FOREIGN KEY (status_id) REFERENCES user_status(id)
);

CREATE TABLE certification (
    id text,
    user_id text,
    contact_user_id text,
    created_by text,
    approval_comments text,
    assign_date text,
    carryover_credits text,
    category_id text,
    course_code text,
    create_date text,
    denial_comments text,
    family_id text,
    first_period_completion_date text,
    is_active text,
    is_current_period text,
    is_on_hold text,
    language_id text,
    latest_onhold_comments text,
    latest_onhold_date text,
    latest_reinstate_comments text,
    latest_reinstate_date text,
    lo_acquired_credit text,
    lo_possible_credit text,
    min_credit_completion_req text,
    modify_date text,
    object_id text,
    owner_approval_warning text,
    owner_denial_warning text,
    period_acquired_credit text,
    period_due_date text,
    period_expiration_date text,
    period_id text,
    period_type text,
    period_type_id text,
    reg_num text,
    required_period_credit text,
    revoke_comments text,
    section_acquired_credit text,
    section_id text,
    section_item_id text,
    section_max_credit text,
    section_min_credit text,
    section_parent_id text,
    status_change_date text,
    user_cert_is_archived text,
    user_cert_period_id text,
    user_cert_section_item_id text,
    user_cert_status text,
    user_cert_status_id text,
    user_lo_active text,
    user_period_completion_date text,
    version text,
    PRIMARY KEY (id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (contact_user_id) REFERENCES users(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE transcript (
    reg_num text,
    transc_object_id text,
    transc_user_id text,
    exemptor_id text,
    user_lo_assignor_id text,
    user_lo_equivalent_object_id text,
    user_lo_remover_id text,
    user_lo_status_group_id text,
    user_lo_status_id text,
    approver_exempt_comment text,
    archived text,
    badge_id text,
    badge_point text,
    completed_sco text,
    exempt_approver_reason text,
    exempt_approver_reason_id text,
    exempt_comment text,
    exempt_dt text,
    exempt_reason text,
    exempt_reason_id text,
    is_archive text,
    is_assigned text,
    is_express_class text,
    is_latest_reg_num text,
    is_latest_version_on_transcript text,
    is_removed text,
    is_required text,
    is_standalone text,
    is_suggested text,
    last_touched_dt_utc text,
    training_point text,
    training_purpose text,
    training_purpose_category text,
    user_lo_assigned_comment text,
    user_lo_assigned_dt text,
    user_lo_assignor text,
    user_lo_assignor_ref text,
    user_lo_available_dt text,
    user_lo_cancellation_reason text,
    user_lo_cancellation_reason_id text,
    user_lo_comment text,
    user_lo_comp_dt text,
    user_lo_create_dt text,
    user_lo_delivery_method_id text,
    user_lo_equivalency_type text,
    user_lo_from_training_plan text,
    user_lo_last_access_dt text,
    user_lo_last_action_dt text,
    user_lo_last_modified_dt text,
    user_lo_min_due_date text,
    user_lo_minutes_participated text,
    user_lo_num_attempts text,
    user_lo_pass text,
    user_lo_pct_complete text,
    user_lo_reg_dt text,
    user_lo_removed_comment text,
    user_lo_removed_dt text,
    user_lo_removed_reason_id text,
    user_lo_score text,
    user_lo_start_dt text,
    user_lo_timezone_code text,
    user_lo_training_link_expiration_date text,
    user_lo_withdrawal_date text,
    user_lo_withdrawal_reason text,
    user_lo_withdrawal_reason_id text,
    PRIMARY KEY (reg_num, transc_object_id, transc_user_id),
    FOREIGN KEY (transc_object_id) REFERENCES training(id),
    FOREIGN KEY (transc_user_id) REFERENCES users(id),
    FOREIGN KEY (exemptor_id) REFERENCES users(id),
    FOREIGN KEY (user_lo_assignor_id) REFERENCES users(id),
    FOREIGN KEY (user_lo_equivalent_object_id) REFERENCES training(id),
    FOREIGN KEY (user_lo_remover_id) REFERENCES users(id),
    FOREIGN KEY (user_lo_status_group_id) REFERENCES transcript_status_group(user_lo_status_group_id),
    FOREIGN KEY (user_lo_status_id) REFERENCES transcript_status(id)
);

CREATE TABLE recruiting (
    ats_req_id text,
    ats_req_primary_owner_id text,
    ats_req_request_creator_id text,
    ats_contact_phone text,
    ats_req_app_wfl_template text,
    ats_req_app_wfl_template_id text,
    ats_req_attached_documents text,
    ats_req_bonus_amount text,
    ats_req_can_apply text,
    ats_req_candidates_number text,
    ats_req_closed_date text,
    ats_req_compensation_high text,
    ats_req_compensation_low text,
    ats_req_compensation_type text,
    ats_req_compensation_type_id text,
    ats_req_cost_center_ref text,
    ats_req_created_date text,
    ats_req_currency text,
    ats_req_currency_id text,
    ats_req_days_open text,
    ats_req_div_id text,
    ats_req_division_ref text,
    ats_req_eeo_cat text,
    ats_req_eeo_cat_id text,
    ats_req_empl_type_id text,
    ats_req_filled_date text,
    ats_req_full_part text,
    ats_req_full_part_id text,
    ats_req_grade_id text,
    ats_req_grade_ref text,
    ats_req_hiring_manager text,
    ats_req_hiring_manager_email text,
    ats_req_hiring_manager_id text,
    ats_req_hiring_manager_ref text,
    ats_req_jb_show_salary_external text,
    ats_req_ongoing text,
    ats_req_opened_date text,
    ats_req_openings_org text,
    ats_req_openings_outstanding text,
    ats_req_parent_req_ref text,
    ats_req_position_id text,
    ats_req_position_ref text,
    ats_req_posting_career_center text,
    ats_req_postings_number text,
    ats_req_priority text,
    ats_req_priority_id text,
    ats_req_ref text,
    ats_req_request_created_dt text,
    ats_req_request_review_dt text,
    ats_req_status text,
    ats_req_status_id text,
    ats_req_submission_number text,
    ats_req_suggested_referrals_number text,
    ats_req_target_hire_date text,
    ats_req_template_ref text,
    ats_req_time_to_fill text,
    ats_req_type_id text,
    ats_requisition_template_id text,
    cost_center_id text,
    PRIMARY KEY (ats_req_id),
    FOREIGN KEY (ats_req_primary_owner_id) REFERENCES users(id),
    FOREIGN KEY (ats_req_request_creator_id) REFERENCES users(id)
);
