CREATE TABLE recommendation (
    id text,
    organization_id text,
    activity_url text,
    badge_templates_count text,
    title text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE employee (
    id text,
    organization_id text,
    country text,
    created_at text,
    department text,
    email text,
    employee_state text,
    employee_state_updated_at text,
    external_id text,
    first_name text,
    full_name text,
    job_family text,
    last_invitation_sent_at text,
    last_name text,
    location text,
    manager_external_id text,
    manager_first_name text,
    manager_last_name text,
    organization_level_1 text,
    organization_level_2 text,
    organization_level_3 text,
    photo_url text,
    position_title text,
    state_or_province text,
    team text,
    zip_code text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE recommendation_badge_template (
    id text,
    organization_id text,
    recommendation_id text,
    image_id text,
    image_url text,
    "name" text,
    owner_id text,
    owner_name text,
    public text,
    updated_at text,
    PRIMARY KEY (id, organization_id, recommendation_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (recommendation_id) REFERENCES recommendation(id)
);

CREATE TABLE organization_allowed_webhook (
    "index" text,
    organization_id text,
    allowed_webhook text,
    PRIMARY KEY ("index", organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE organization (
    id text,
    address text,
    allow_saml_debug text,
    bio text,
    city text,
    contact_email text,
    country text,
    created_at text,
    default_page text,
    display_logo_as_circle_in_emails text,
    enable_blockchain text,
    facebook_url text,
    featured_badge_templates jsonb,
    has_employees text,
    hide_subscription text,
    industry_id text,
    integrated_with_faethm text,
    internationalize_badge_templates text,
    is_trial text,
    legal_contact_email text,
    linked_in_name text,
    linked_in_org_id text,
    linked_in_url text,
    linkedin_a_2_p_url text,
    location text,
    missing_required_info text,
    "name" text,
    organization_type text,
    pdf_id text,
    photo_id text,
    photo_url text,
    primary_hex_color text,
    print_method text,
    require_template_detail_attributes text,
    state_or_province text,
    support_email text,
    support_url text,
    technical_contact_email text,
    twitter_url text,
    updated_at text,
    url text,
    vanity_slug text,
    vanity_url text,
    verified text,
    verified_at text,
    webhook_url text,
    website_url text,
    workforce_enabled text,
    zip_or_postal_code text,
    PRIMARY KEY (id)
);

CREATE TABLE badge_template_alignment (
    id text,
    badge_template_id text,
    description text,
    "name" text,
    url text,
    PRIMARY KEY (id, badge_template_id),
    FOREIGN KEY (badge_template_id) REFERENCES badge_template(id)
);

CREATE TABLE badge_template_recommendation (
    id text,
    badge_template_id text,
    activity_url text,
    recommended_badge_template_id text,
    recommended_badge_template_name text,
    recommended_badge_template_url text,
    title text,
    "type" text,
    PRIMARY KEY (id, badge_template_id),
    FOREIGN KEY (badge_template_id) REFERENCES badge_template(id)
);

CREATE TABLE badge_template_endorsement (
    id text,
    badge_template_id text,
    description text,
    endorser_id text,
    url text,
    PRIMARY KEY (id, badge_template_id),
    FOREIGN KEY (badge_template_id) REFERENCES badge_template(id)
);

CREATE TABLE badge_template_activities (
    id text,
    badge_template_id text,
    activity_type text,
    activity_url text,
    recommended_badge_template_id text,
    recommended_badge_template_name text,
    recommended_badge_template_url text,
    title text,
    PRIMARY KEY (id, badge_template_id),
    FOREIGN KEY (badge_template_id) REFERENCES badge_template(id)
);

CREATE TABLE badge_template (
    id text,
    organization_id text,
    allow_archive text,
    allow_delete text,
    allow_duplicate_badges text,
    available_locales jsonb,
    badges_count text,
    certification text,
    cost text,
    created_at text,
    criteria_url text,
    criteria_url_name text,
    default_expires_at text,
    default_expires_at_date text,
    default_expires_at_type text,
    description text,
    earn_this_badge_url text,
    enable_detail_attribute_visibility text,
    enable_earn_this_badge text,
    get_issue_count text,
    get_variants_issue_count text,
    global_activity_url text,
    image_id text,
    image_url text,
    job_board_url text,
    "level" text,
    linkedin_share_default_message text,
    lock_badge_state text,
    "name" text,
    only_one_skill_required text,
    owner_id text,
    primary_badge_template_id text,
    printing_disabled text,
    public text,
    recipient_type text,
    record_to_blockchain text,
    reporting_tags jsonb,
    required_badge_templates jsonb,
    send_expiring_badge_notifications text,
    settings_enable_related_badges text,
    show_badge_lmi text,
    show_lmi_jobs text,
    show_skill_tag_links text,
    show_template_settings text,
    skills jsonb,
    "state" text,
    state_updated_at text,
    time_to_earn text,
    translatable text,
    type_category text,
    updated_at text,
    vanity_slug text,
    variant_name text,
    variant_type text,
    variants_allowed text,
    visibility text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE employee_skill_evidence (
    badge_id text,
    employee_skill_employee_id text,
    "type" text,
    PRIMARY KEY (badge_id, employee_skill_employee_id),
    FOREIGN KEY (badge_id) REFERENCES issued_badge(id),
    FOREIGN KEY (employee_skill_employee_id) REFERENCES employee_skill(employee_id)
);

CREATE TABLE employee_skill (
    employee_id text,
    organization_id text,
    external_id text,
    skill text,
    PRIMARY KEY (employee_id, organization_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE issued_badge_issuer_entity (
    id text,
    issued_badge_id text,
    label text,
    "name" text,
    primary_boolean text,
    "type" text,
    PRIMARY KEY (id, issued_badge_id),
    FOREIGN KEY (issued_badge_id) REFERENCES issued_badge(id)
);

CREATE TABLE issued_badge (
    id text,
    organization_id text,
    badge_template_id text,
    badge_url text,
    created_at text,
    created_by_id text,
    created_by_type text,
    expires_at text,
    expires_at_date text,
    issued_at text,
    issued_at_date text,
    issued_to text,
    issued_to_first_name text,
    issued_to_last_name text,
    issued_to_middle_name text,
    issuer_earner_id text,
    issuer_summary text,
    locale text,
    public text,
    recipient_email text,
    replacement_badge_id text,
    revocation_reason text,
    "state" text,
    state_updated_at text,
    suppress_badge_notification_email text,
    updated_at text,
    user_id text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (badge_template_id) REFERENCES badge_template(id)
);
