CREATE TABLE call_to_action (
    _fivetran_id text,
    creative_id bigint,
    text text,
    "type" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE html_tag (
    _fivetran_id text,
    creative_id bigint,
    height integer,
    html_tag text,
    width integer,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE audience (
    id bigint,
    advertiser_id bigint,
    created_at timestamp,
    description text,
    "name" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE image (
    _fivetran_id text,
    image_set_id text,
    shape text,
    url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (image_set_id) REFERENCES image_set(_fivetran_id)
);

CREATE TABLE image_url (
    _fivetran_id text,
    creative_id bigint,
    url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE adset_statistics_hourly_report (
    _fivetran_id text,
    adset_id bigint,
    advertiser_id bigint,
    adset_name text,
    advertiser_all_value double precision,
    advertiser_cost double precision,
    advertiser_value double precision,
    app_installs integer,
    audience double precision,
    average_cart_all_client_attribution double precision,
    average_cart_all_pc_1_d double precision,
    average_cart_all_pc_30_d double precision,
    average_cart_all_pc_30_d_pv_24_h double precision,
    average_cart_all_pc_7_d double precision,
    average_cart_all_pv_24_h double precision,
    average_cart_client_attribution double precision,
    average_cart_pc_1_d double precision,
    average_cart_pc_30_d double precision,
    average_cart_pc_30_d_pv_24_h double precision,
    average_cart_pc_7_d double precision,
    average_cart_pv_24_h double precision,
    bounce_rate double precision,
    category_id bigint,
    category_name text,
    click_through_rate double precision,
    clicks integer,
    conversion_rate_all_client_attribution double precision,
    conversion_rate_all_pc_1_d double precision,
    conversion_rate_all_pc_30_d double precision,
    conversion_rate_all_pc_30_d_pv_24_h double precision,
    conversion_rate_all_pc_7_d double precision,
    conversion_rate_all_pv_24_h double precision,
    conversion_rate_client_attribution double precision,
    conversion_rate_pc_1_d double precision,
    conversion_rate_pc_30_d double precision,
    conversion_rate_pc_30_d_pv_24_h double precision,
    conversion_rate_pc_7_d double precision,
    conversion_rate_pv_24_h double precision,
    cost_of_advertiser_value double precision,
    cost_of_advertiser_value_all double precision,
    cost_per_install double precision,
    cost_per_order_all_client_attribution double precision,
    cost_per_order_all_pc_1_d double precision,
    cost_per_order_all_pc_30_d double precision,
    cost_per_order_all_pc_30_d_pv_24_h double precision,
    cost_per_order_all_pc_7_d double precision,
    cost_per_order_all_pv_24_h double precision,
    cost_per_order_client_attribution double precision,
    cost_per_order_pc_1_d double precision,
    cost_per_order_pc_30_d double precision,
    cost_per_order_pc_30_d_pv_24_h double precision,
    cost_per_order_pc_7_d double precision,
    cost_per_order_pv_24_h double precision,
    cost_per_visit double precision,
    cpc double precision,
    currency text,
    "date" timestamp,
    displays integer,
    ecos_all_client_attribution double precision,
    ecos_all_pc_1_d double precision,
    ecos_all_pc_30_d double precision,
    ecos_all_pc_30_d_pv_24_h double precision,
    ecos_all_pc_7_d double precision,
    ecos_all_pv_24_h double precision,
    ecos_client_attribution double precision,
    ecos_pc_1_d double precision,
    ecos_pc_30_d double precision,
    ecos_pc_30_d_pv_24_h double precision,
    ecos_pc_7_d double precision,
    ecos_pv_24_h double precision,
    ecpm double precision,
    exposed_users double precision,
    install_rate double precision,
    non_viewable_displays integer,
    omnichannel_revenue_all_pc_30_d double precision,
    omnichannel_revenue_all_pv_24_h double precision,
    omnichannel_revenue_client_attribution double precision,
    omnichannel_revenue_pc_30_d double precision,
    omnichannel_revenue_pv_24_h double precision,
    omnichannel_roas_all_pc_30_d double precision,
    omnichannel_roas_all_pv_24_h double precision,
    omnichannel_roas_client_attribution double precision,
    omnichannel_roas_pc_30_d double precision,
    omnichannel_roas_pv_24_h double precision,
    omnichannel_sales_all_pc_30_d integer,
    omnichannel_sales_all_pv_24_h integer,
    omnichannel_sales_pc_30_d integer,
    omnichannel_sales_pv_24_h integer,
    omnichannelsales_client_attribution integer,
    overall_competition_win double precision,
    post_install_conversion_rate double precision,
    post_install_cost_of_sale double precision,
    post_install_cost_per_order double precision,
    post_install_order_value double precision,
    post_install_roas text,
    post_install_sales integer,
    potential_displays bigint,
    qualified_visits integer,
    reach double precision,
    revenue_generated_all_client_attribution double precision,
    revenue_generated_all_pc_1_d double precision,
    revenue_generated_all_pc_30_d double precision,
    revenue_generated_all_pc_30_d_pv_24_h double precision,
    revenue_generated_all_pc_7_d double precision,
    revenue_generated_all_pv_24_h double precision,
    revenue_generated_client_attribution double precision,
    revenue_generated_offline_pc_30_d double precision,
    revenue_generated_offline_pv_24_h double precision,
    revenue_generated_pc_1_d double precision,
    revenue_generated_pc_30_d double precision,
    revenue_generated_pc_30_d_pv_24_h double precision,
    revenue_generated_pc_7_d double precision,
    revenue_generated_pv_24_h double precision,
    roas_all_client_attribution double precision,
    roas_all_pc_1_d double precision,
    roas_all_pc_30_d double precision,
    roas_all_pc_30_d_pv_24_h double precision,
    roas_all_pc_7_d double precision,
    roas_all_pv_24_h double precision,
    roas_client_attribution double precision,
    roas_offline_pc_30_d double precision,
    roas_offline_pv_24_h double precision,
    roas_pc_1_d double precision,
    roas_pc_30_d double precision,
    roas_pc_30_d_pv_24_h double precision,
    roas_pc_7_d double precision,
    roas_pv_24_h double precision,
    sales_all_client_attribution integer,
    sales_all_pc_1_d integer,
    sales_all_pc_30_d integer,
    sales_all_pc_30_d_pv_24_h integer,
    sales_all_pc_7_d integer,
    sales_all_pv_24_h integer,
    sales_client_attribution integer,
    sales_offline_pc_30_d integer,
    sales_offline_pv_24_h integer,
    sales_pc_1_d integer,
    sales_pc_30_d integer,
    sales_pc_30_d_pv_24_h integer,
    sales_pc_7_d integer,
    sales_pv_24_h integer,
    untrackable_displays integer,
    viewable_displays integer,
    visits integer,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE delivery_limitations_environment (
    _fivetran_id text,
    adset_id bigint,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id)
);

CREATE TABLE audience_adset (
    ad_set_id bigint,
    audience_id bigint,
    PRIMARY KEY (ad_set_id, audience_id),
    FOREIGN KEY (ad_set_id) REFERENCES adset(id),
    FOREIGN KEY (audience_id) REFERENCES audience(id)
);

CREATE TABLE geolocation_country (
    _fivetran_id text,
    adset_id bigint,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id)
);

CREATE TABLE image_set (
    _fivetran_id text,
    creative_id bigint,
    headline_text text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE ad (
    id bigint,
    ad_set_id bigint,
    creative_id bigint,
    description text,
    end_date timestamp,
    "name" text,
    start_date timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (ad_set_id) REFERENCES adset(id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE campaign (
    id bigint,
    advertiser_id bigint,
    "name" text,
    objective text,
    spend_limit_amount double precision,
    spend_limit_renewal text,
    spend_limit_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE ad_statistics_daily_report (
    _fivetran_id text,
    advertiser_id bigint,
    ad_id bigint,
    ad_name text,
    advertiser_all_value double precision,
    advertiser_cost double precision,
    advertiser_value double precision,
    app_installs integer,
    audience double precision,
    average_cart_all_client_attribution double precision,
    average_cart_all_pc_1_d double precision,
    average_cart_all_pc_30_d double precision,
    average_cart_all_pc_30_d_pv_24_h double precision,
    average_cart_all_pc_7_d double precision,
    average_cart_all_pv_24_h double precision,
    average_cart_client_attribution double precision,
    average_cart_pc_1_d double precision,
    average_cart_pc_30_d double precision,
    average_cart_pc_30_d_pv_24_h double precision,
    average_cart_pc_7_d double precision,
    average_cart_pv_24_h double precision,
    bounce_rate double precision,
    click_through_rate double precision,
    clicks integer,
    conversion_rate_all_client_attribution double precision,
    conversion_rate_all_pc_1_d double precision,
    conversion_rate_all_pc_30_d double precision,
    conversion_rate_all_pc_30_d_pv_24_h double precision,
    conversion_rate_all_pc_7_d double precision,
    conversion_rate_all_pv_24_h double precision,
    conversion_rate_client_attribution double precision,
    conversion_rate_pc_1_d double precision,
    conversion_rate_pc_30_d double precision,
    conversion_rate_pc_30_d_pv_24_h double precision,
    conversion_rate_pc_7_d double precision,
    conversion_rate_pv_24_h double precision,
    cost_of_advertiser_value double precision,
    cost_of_advertiser_value_all double precision,
    cost_per_install double precision,
    cost_per_order_all_client_attribution double precision,
    cost_per_order_all_pc_1_d double precision,
    cost_per_order_all_pc_30_d double precision,
    cost_per_order_all_pc_30_d_pv_24_h double precision,
    cost_per_order_all_pc_7_d double precision,
    cost_per_order_all_pv_24_h double precision,
    cost_per_order_client_attribution double precision,
    cost_per_order_pc_1_d double precision,
    cost_per_order_pc_30_d double precision,
    cost_per_order_pc_30_d_pv_24_h double precision,
    cost_per_order_pc_7_d double precision,
    cost_per_order_pv_24_h double precision,
    cost_per_visit double precision,
    cpc double precision,
    currency text,
    "day" text,
    displays integer,
    ecos_all_client_attribution double precision,
    ecos_all_pc_1_d double precision,
    ecos_all_pc_30_d double precision,
    ecos_all_pc_30_d_pv_24_h double precision,
    ecos_all_pc_7_d double precision,
    ecos_all_pv_24_h double precision,
    ecos_client_attribution double precision,
    ecos_pc_1_d double precision,
    ecos_pc_30_d double precision,
    ecos_pc_30_d_pv_24_h double precision,
    ecos_pc_7_d double precision,
    ecos_pv_24_h double precision,
    ecpm double precision,
    exposed_users double precision,
    install_rate double precision,
    non_viewable_displays integer,
    omnichannel_revenue_all_pc_30_d double precision,
    omnichannel_revenue_all_pv_24_h double precision,
    omnichannel_revenue_client_attribution double precision,
    omnichannel_revenue_pc_30_d double precision,
    omnichannel_revenue_pv_24_h double precision,
    omnichannel_roas_all_pc_30_d double precision,
    omnichannel_roas_all_pv_24_h double precision,
    omnichannel_roas_client_attribution double precision,
    omnichannel_roas_pc_30_d double precision,
    omnichannel_roas_pv_24_h double precision,
    omnichannel_sales_all_pc_30_d integer,
    omnichannel_sales_all_pv_24_h integer,
    omnichannel_sales_pc_30_d integer,
    omnichannel_sales_pv_24_h integer,
    omnichannelsales_client_attribution integer,
    overall_competition_win double precision,
    post_install_conversion_rate double precision,
    post_install_cost_of_sale double precision,
    post_install_cost_per_order double precision,
    post_install_order_value double precision,
    post_install_roas text,
    post_install_sales integer,
    potential_displays bigint,
    qualified_visits integer,
    reach double precision,
    revenue_generated_all_client_attribution double precision,
    revenue_generated_all_pc_1_d double precision,
    revenue_generated_all_pc_30_d double precision,
    revenue_generated_all_pc_30_d_pv_24_h double precision,
    revenue_generated_all_pc_7_d double precision,
    revenue_generated_all_pv_24_h double precision,
    revenue_generated_client_attribution double precision,
    revenue_generated_offline_pc_30_d double precision,
    revenue_generated_offline_pv_24_h double precision,
    revenue_generated_pc_1_d double precision,
    revenue_generated_pc_30_d double precision,
    revenue_generated_pc_30_d_pv_24_h double precision,
    revenue_generated_pc_7_d double precision,
    revenue_generated_pv_24_h double precision,
    roas_all_client_attribution double precision,
    roas_all_pc_1_d double precision,
    roas_all_pc_30_d double precision,
    roas_all_pc_30_d_pv_24_h double precision,
    roas_all_pc_7_d double precision,
    roas_all_pv_24_h double precision,
    roas_client_attribution double precision,
    roas_offline_pc_30_d double precision,
    roas_offline_pv_24_h double precision,
    roas_pc_1_d double precision,
    roas_pc_30_d double precision,
    roas_pc_30_d_pv_24_h double precision,
    roas_pc_7_d double precision,
    roas_pv_24_h double precision,
    sales_all_client_attribution integer,
    sales_all_pc_1_d integer,
    sales_all_pc_30_d integer,
    sales_all_pc_30_d_pv_24_h integer,
    sales_all_pc_7_d integer,
    sales_all_pv_24_h integer,
    sales_client_attribution integer,
    sales_offline_pc_30_d integer,
    sales_offline_pv_24_h integer,
    sales_pc_1_d integer,
    sales_pc_30_d integer,
    sales_pc_30_d_pv_24_h integer,
    sales_pc_7_d integer,
    sales_pv_24_h integer,
    untrackable_displays integer,
    viewable_displays integer,
    visits integer,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE campaign_statistics_daily_report (
    _fivetran_id text,
    advertiser_id bigint,
    advertiser_all_value double precision,
    advertiser_cost double precision,
    advertiser_value double precision,
    app_installs integer,
    audience double precision,
    average_cart_all_client_attribution double precision,
    average_cart_all_pc_1_d double precision,
    average_cart_all_pc_30_d double precision,
    average_cart_all_pc_30_d_pv_24_h double precision,
    average_cart_all_pc_7_d double precision,
    average_cart_all_pv_24_h double precision,
    average_cart_client_attribution double precision,
    average_cart_pc_1_d double precision,
    average_cart_pc_30_d double precision,
    average_cart_pc_30_d_pv_24_h double precision,
    average_cart_pc_7_d double precision,
    average_cart_pv_24_h double precision,
    bounce_rate double precision,
    campaign_id bigint,
    campaign_name text,
    click_through_rate double precision,
    clicks integer,
    conversion_rate_all_client_attribution double precision,
    conversion_rate_all_pc_1_d double precision,
    conversion_rate_all_pc_30_d double precision,
    conversion_rate_all_pc_30_d_pv_24_h double precision,
    conversion_rate_all_pc_7_d double precision,
    conversion_rate_all_pv_24_h double precision,
    conversion_rate_client_attribution double precision,
    conversion_rate_pc_1_d double precision,
    conversion_rate_pc_30_d double precision,
    conversion_rate_pc_30_d_pv_24_h double precision,
    conversion_rate_pc_7_d double precision,
    conversion_rate_pv_24_h double precision,
    cost_of_advertiser_value double precision,
    cost_of_advertiser_value_all double precision,
    cost_per_install double precision,
    cost_per_order_all_client_attribution double precision,
    cost_per_order_all_pc_1_d double precision,
    cost_per_order_all_pc_30_d double precision,
    cost_per_order_all_pc_30_d_pv_24_h double precision,
    cost_per_order_all_pc_7_d double precision,
    cost_per_order_all_pv_24_h double precision,
    cost_per_order_client_attribution double precision,
    cost_per_order_pc_1_d double precision,
    cost_per_order_pc_30_d double precision,
    cost_per_order_pc_30_d_pv_24_h double precision,
    cost_per_order_pc_7_d double precision,
    cost_per_order_pv_24_h double precision,
    cost_per_visit double precision,
    cpc double precision,
    currency text,
    "day" text,
    displays integer,
    ecos_all_client_attribution double precision,
    ecos_all_pc_1_d double precision,
    ecos_all_pc_30_d double precision,
    ecos_all_pc_30_d_pv_24_h double precision,
    ecos_all_pc_7_d double precision,
    ecos_all_pv_24_h double precision,
    ecos_client_attribution double precision,
    ecos_pc_1_d double precision,
    ecos_pc_30_d double precision,
    ecos_pc_30_d_pv_24_h double precision,
    ecos_pc_7_d double precision,
    ecos_pv_24_h double precision,
    ecpm double precision,
    exposed_users double precision,
    install_rate double precision,
    non_viewable_displays integer,
    omnichannel_revenue_all_pc_30_d double precision,
    omnichannel_revenue_all_pv_24_h double precision,
    omnichannel_revenue_client_attribution double precision,
    omnichannel_revenue_pc_30_d double precision,
    omnichannel_revenue_pv_24_h double precision,
    omnichannel_roas_all_pc_30_d double precision,
    omnichannel_roas_all_pv_24_h double precision,
    omnichannel_roas_client_attribution double precision,
    omnichannel_roas_pc_30_d double precision,
    omnichannel_roas_pv_24_h double precision,
    omnichannel_sales_all_pc_30_d integer,
    omnichannel_sales_all_pv_24_h integer,
    omnichannel_sales_pc_30_d integer,
    omnichannel_sales_pv_24_h integer,
    omnichannelsales_client_attribution integer,
    overall_competition_win double precision,
    post_install_conversion_rate double precision,
    post_install_cost_of_sale double precision,
    post_install_cost_per_order double precision,
    post_install_order_value double precision,
    post_install_roas text,
    post_install_sales integer,
    potential_displays bigint,
    qualified_visits integer,
    reach double precision,
    revenue_generated_all_client_attribution double precision,
    revenue_generated_all_pc_1_d double precision,
    revenue_generated_all_pc_30_d double precision,
    revenue_generated_all_pc_30_d_pv_24_h double precision,
    revenue_generated_all_pc_7_d double precision,
    revenue_generated_all_pv_24_h double precision,
    revenue_generated_client_attribution double precision,
    revenue_generated_offline_pc_30_d double precision,
    revenue_generated_offline_pv_24_h double precision,
    revenue_generated_pc_1_d double precision,
    revenue_generated_pc_30_d double precision,
    revenue_generated_pc_30_d_pv_24_h double precision,
    revenue_generated_pc_7_d double precision,
    revenue_generated_pv_24_h double precision,
    roas_all_client_attribution double precision,
    roas_all_pc_1_d double precision,
    roas_all_pc_30_d double precision,
    roas_all_pc_30_d_pv_24_h double precision,
    roas_all_pc_7_d double precision,
    roas_all_pv_24_h double precision,
    roas_client_attribution double precision,
    roas_offline_pc_30_d double precision,
    roas_offline_pv_24_h double precision,
    roas_pc_1_d double precision,
    roas_pc_30_d double precision,
    roas_pc_30_d_pv_24_h double precision,
    roas_pc_7_d double precision,
    roas_pv_24_h double precision,
    sales_all_client_attribution integer,
    sales_all_pc_1_d integer,
    sales_all_pc_30_d integer,
    sales_all_pc_30_d_pv_24_h integer,
    sales_all_pc_7_d integer,
    sales_all_pv_24_h integer,
    sales_client_attribution integer,
    sales_offline_pc_30_d integer,
    sales_offline_pv_24_h integer,
    sales_pc_1_d integer,
    sales_pc_30_d integer,
    sales_pc_30_d_pv_24_h integer,
    sales_pc_7_d integer,
    sales_pv_24_h integer,
    untrackable_displays integer,
    viewable_displays integer,
    visits integer,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE adset_transaction_report (
    _fivetran_id text,
    advertiser_id bigint,
    adset_name text,
    advertiser_name text,
    amount double precision,
    attributed_transaction boolean,
    cross_device_transaction text,
    currency text,
    event_date timestamp,
    event_type text,
    transaction_date timestamp,
    transaction_id text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE creative (
    id bigint,
    advertiser_id bigint,
    adaptive_background_color text,
    adaptive_cta_background_color text,
    adaptive_cta_text_color text,
    adaptive_description_font text,
    adaptive_description_text text,
    adaptive_headline_font text,
    adaptive_headline_text text,
    adaptive_image_display text,
    adaptive_landing_page_url text,
    adaptive_logo_area_and_title_color text,
    adaptive_text_1_color text,
    adaptive_text_2_color text,
    author text,
    dataset_id text,
    description text,
    dynamic_body_text_color text,
    dynamic_creative_background_color text,
    dynamic_prices_color text,
    dynamic_primary_font text,
    dynamic_product_image_display text,
    format text,
    image_landing_page_url text,
    "name" text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE advertiser (
    advertiser_id bigint,
    advertiser_name text,
    PRIMARY KEY (advertiser_id)
);

CREATE TABLE adset (
    id bigint,
    advertiser_id bigint,
    campaign_id bigint,
    attribution_configuration_lookback_window text,
    attribution_configuration_method text,
    bidding_bid_amount double precision,
    bidding_bid_strategy text,
    bidding_cost_controller text,
    budget_amount double precision,
    budget_delivery_smoothing text,
    budget_delivery_week text,
    budget_renewal text,
    budget_strategy text,
    dataset_id bigint,
    destination_environment text,
    frequency_capping_frequency text,
    frequency_capping_maximum_impressions integer,
    frequency_capping_mode text,
    geolocation_countries_operand text,
    geolocation_subdivisions_operand text,
    geolocation_zip_codes_operand text,
    media_type text,
    "name" text,
    objective text,
    schedule_activation_status text,
    schedule_delivery_status text,
    schedule_end_date timestamp,
    schedule_start_date timestamp,
    video_channel text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE geolocation_subdivision (
    _fivetran_id text,
    adset_id bigint,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id)
);

CREATE TABLE geolocation_zip_code (
    _fivetran_id text,
    adset_id bigint,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id)
);

CREATE TABLE layout (
    _fivetran_id text,
    creative_id bigint,
    text text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE delivery_limitations_operation_system (
    _fivetran_id text,
    adset_id bigint,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id)
);

CREATE TABLE video (
    _fivetran_id text,
    creative_id bigint,
    duration double precision,
    shape text,
    url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE adset_statistics_report (
    _fivetran_id text,
    adset_id bigint,
    advertiser_id bigint,
    adset_name text,
    advertiser_all_value double precision,
    advertiser_cost double precision,
    advertiser_value double precision,
    app_installs integer,
    audience double precision,
    average_cart_all_client_attribution double precision,
    average_cart_all_pc_1_d double precision,
    average_cart_all_pc_30_d double precision,
    average_cart_all_pc_30_d_pv_24_h double precision,
    average_cart_all_pc_7_d double precision,
    average_cart_all_pv_24_h double precision,
    average_cart_client_attribution double precision,
    average_cart_pc_1_d double precision,
    average_cart_pc_30_d double precision,
    average_cart_pc_30_d_pv_24_h double precision,
    average_cart_pc_7_d double precision,
    average_cart_pv_24_h double precision,
    bounce_rate double precision,
    category_id bigint,
    category_name text,
    click_through_rate double precision,
    clicks integer,
    conversion_rate_all_client_attribution double precision,
    conversion_rate_all_pc_1_d double precision,
    conversion_rate_all_pc_30_d double precision,
    conversion_rate_all_pc_30_d_pv_24_h double precision,
    conversion_rate_all_pc_7_d double precision,
    conversion_rate_all_pv_24_h double precision,
    conversion_rate_client_attribution double precision,
    conversion_rate_pc_1_d double precision,
    conversion_rate_pc_30_d double precision,
    conversion_rate_pc_30_d_pv_24_h double precision,
    conversion_rate_pc_7_d double precision,
    conversion_rate_pv_24_h double precision,
    cost_of_advertiser_value double precision,
    cost_of_advertiser_value_all double precision,
    cost_per_install double precision,
    cost_per_order_all_client_attribution double precision,
    cost_per_order_all_pc_1_d double precision,
    cost_per_order_all_pc_30_d double precision,
    cost_per_order_all_pc_30_d_pv_24_h double precision,
    cost_per_order_all_pc_7_d double precision,
    cost_per_order_all_pv_24_h double precision,
    cost_per_order_client_attribution double precision,
    cost_per_order_pc_1_d double precision,
    cost_per_order_pc_30_d double precision,
    cost_per_order_pc_30_d_pv_24_h double precision,
    cost_per_order_pc_7_d double precision,
    cost_per_order_pv_24_h double precision,
    cost_per_visit double precision,
    cpc double precision,
    currency text,
    "day" text,
    displays integer,
    ecos_all_client_attribution double precision,
    ecos_all_pc_1_d double precision,
    ecos_all_pc_30_d double precision,
    ecos_all_pc_30_d_pv_24_h double precision,
    ecos_all_pc_7_d double precision,
    ecos_all_pv_24_h double precision,
    ecos_client_attribution double precision,
    ecos_pc_1_d double precision,
    ecos_pc_30_d double precision,
    ecos_pc_30_d_pv_24_h double precision,
    ecos_pc_7_d double precision,
    ecos_pv_24_h double precision,
    ecpm double precision,
    exposed_users double precision,
    install_rate double precision,
    non_viewable_displays integer,
    omnichannel_revenue_all_pc_30_d double precision,
    omnichannel_revenue_all_pv_24_h double precision,
    omnichannel_revenue_client_attribution double precision,
    omnichannel_revenue_pc_30_d double precision,
    omnichannel_revenue_pv_24_h double precision,
    omnichannel_roas_all_pc_30_d double precision,
    omnichannel_roas_all_pv_24_h double precision,
    omnichannel_roas_client_attribution double precision,
    omnichannel_roas_pc_30_d double precision,
    omnichannel_roas_pv_24_h double precision,
    omnichannel_sales_all_pc_30_d integer,
    omnichannel_sales_all_pv_24_h integer,
    omnichannel_sales_pc_30_d integer,
    omnichannel_sales_pv_24_h integer,
    omnichannelsales_client_attribution integer,
    overall_competition_win double precision,
    post_install_conversion_rate double precision,
    post_install_cost_of_sale double precision,
    post_install_cost_per_order double precision,
    post_install_order_value double precision,
    post_install_roas text,
    post_install_sales integer,
    potential_displays bigint,
    qualified_visits integer,
    reach double precision,
    revenue_generated_all_client_attribution double precision,
    revenue_generated_all_pc_1_d double precision,
    revenue_generated_all_pc_30_d double precision,
    revenue_generated_all_pc_30_d_pv_24_h double precision,
    revenue_generated_all_pc_7_d double precision,
    revenue_generated_all_pv_24_h double precision,
    revenue_generated_client_attribution double precision,
    revenue_generated_offline_pc_30_d double precision,
    revenue_generated_offline_pv_24_h double precision,
    revenue_generated_pc_1_d double precision,
    revenue_generated_pc_30_d double precision,
    revenue_generated_pc_30_d_pv_24_h double precision,
    revenue_generated_pc_7_d double precision,
    revenue_generated_pv_24_h double precision,
    roas_all_client_attribution double precision,
    roas_all_pc_1_d double precision,
    roas_all_pc_30_d double precision,
    roas_all_pc_30_d_pv_24_h double precision,
    roas_all_pc_7_d double precision,
    roas_all_pv_24_h double precision,
    roas_client_attribution double precision,
    roas_offline_pc_30_d double precision,
    roas_offline_pv_24_h double precision,
    roas_pc_1_d double precision,
    roas_pc_30_d double precision,
    roas_pc_30_d_pv_24_h double precision,
    roas_pc_7_d double precision,
    roas_pv_24_h double precision,
    sales_all_client_attribution integer,
    sales_all_pc_1_d integer,
    sales_all_pc_30_d integer,
    sales_all_pc_30_d_pv_24_h integer,
    sales_all_pc_7_d integer,
    sales_all_pv_24_h integer,
    sales_client_attribution integer,
    sales_offline_pc_30_d integer,
    sales_offline_pv_24_h integer,
    sales_pc_1_d integer,
    sales_pc_30_d integer,
    sales_pc_30_d_pv_24_h integer,
    sales_pc_7_d integer,
    sales_pv_24_h integer,
    untrackable_displays integer,
    viewable_displays integer,
    visits integer,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(advertiser_id)
);

CREATE TABLE placement_report (
    "day" text,
    environment text,
    placement text,
    adset_id bigint,
    clicks integer,
    cos_pc_30_d double precision,
    cos_pv_1_d double precision,
    cost double precision,
    cpo_pc_30_d double precision,
    cpo_pv_1_d double precision,
    currency text,
    cvr_pc_30_d double precision,
    cvr_pv_1_d double precision,
    displays integer,
    revenue_pc_30_d double precision,
    revenue_pv_1_d double precision,
    roas_pc_30_d double precision,
    roas_pv_1_d double precision,
    sales_pc_30_d integer,
    sales_pv_1_d integer,
    PRIMARY KEY ("day", environment, placement, adset_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id)
);

CREATE TABLE delivery_limitations_device (
    _fivetran_id text,
    adset_id bigint,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (adset_id) REFERENCES adset(id)
);

CREATE TABLE logo (
    _fivetran_id text,
    creative_id bigint,
    shape text,
    "type" text,
    url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);
