CREATE TABLE dimension_mapping (
    source_dimension_id text,
    dimension_id text,
    dimension_tld_id text,
    automapped text,
    created_at text,
    modified_at text,
    modified_by_created_at text,
    modified_by_first_name text,
    modified_by_id text,
    modified_by_is_cube_staff text,
    modified_by_is_staff text,
    modified_by_last_name text,
    modified_by_timezone text,
    sign_flip text,
    source_dimension_active text,
    source_dimension_date text,
    source_dimension_formula text,
    source_dimension_has_children text,
    source_dimension_metadata jsonb,
    source_dimension_name text,
    source_dimension_parent_id text,
    source_dimension_position text,
    source_dimension_rollup_type text,
    source_dimension_special_case_id text,
    source_dimension_status text,
    source_dimension_tld_active text,
    source_dimension_tld_date text,
    source_dimension_tld_formula text,
    source_dimension_tld_has_children text,
    source_dimension_tld_id text,
    source_dimension_tld_metadata jsonb,
    source_dimension_tld_name text,
    source_dimension_tld_parent_id text,
    source_dimension_tld_position text,
    source_dimension_tld_rollup_type text,
    source_dimension_tld_special_case_id text,
    source_dimension_tld_status text,
    source_dimension_tld_type text,
    source_dimension_tld_write_block_reason text,
    source_dimension_tld_write_protection text,
    source_dimension_type text,
    source_dimension_write_block_reason text,
    source_dimension_write_protection text,
    PRIMARY KEY (source_dimension_id, dimension_id),
    FOREIGN KEY (dimension_id) REFERENCES dimension(id),
    FOREIGN KEY (dimension_tld_id) REFERENCES dimension(id)
);

CREATE TABLE drilldown (
    _fivetran_id text,
    account text,
    account_number text,
    application_of_origin text,
    batch text,
    data_warehouse_account_name text,
    data_warehouse_entity_name text,
    data_warehouse_location_name text,
    data_warehouse_memo text,
    data_warehouse_product_line_name text,
    data_warehouse_service_line_name text,
    department text,
    entity text,
    forecast_as_of text,
    job text,
    location text,
    product_line text,
    reference_1 text,
    reference_2 text,
    scenario text,
    service_line text,
    "time" text,
    transaction_description text,
    "value" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE dimension (
    id text,
    parent_id text,
    active text,
    "date" text,
    formula text,
    has_children text,
    metadata jsonb,
    "name" text,
    "position" text,
    rollup_type text,
    special_case_id text,
    "status" text,
    "type" text,
    write_block_reason text,
    write_protection text,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES dimension(id)
);
