CREATE TABLE inventory (
    item_number text,
    facility_inventory jsonb,
    PRIMARY KEY (item_number)
);

CREATE TABLE receipt_line (
    number text,
    item_number text,
    order_number text,
    create_item text,
    create_po text,
    expiration_date text,
    line_number text,
    lot_number text,
    order_type text,
    pack_qty text,
    pack_type text,
    quantity text,
    received_date text,
    receiving_container text,
    receiving_container_type text,
    receiving_facility text,
    receiving_location text,
    "status" text,
    PRIMARY KEY (number),
    FOREIGN KEY (item_number) REFERENCES inventory(item_number),
    FOREIGN KEY (order_number) REFERENCES purchase_order(id)
);

CREATE TABLE billable_transaction (
    _fivetran_id text,
    billable_transaction_config_active text,
    billable_transaction_config_business_unit text,
    billable_transaction_config_cost text,
    billable_transaction_config_custom_field_1 text,
    billable_transaction_config_custom_field_10 text,
    billable_transaction_config_custom_field_2 text,
    billable_transaction_config_custom_field_3 text,
    billable_transaction_config_custom_field_4 text,
    billable_transaction_config_custom_field_5 text,
    billable_transaction_config_custom_field_6 text,
    billable_transaction_config_custom_field_7 text,
    billable_transaction_config_custom_field_8 text,
    billable_transaction_config_custom_field_9 text,
    billable_transaction_config_custom_value_3 text,
    billable_transaction_config_description text,
    billable_transaction_config_generated_by text,
    billable_transaction_config_percent text,
    billable_transaction_config_price text,
    billable_transaction_config_profile_name text,
    billable_transaction_config_quantity text,
    billable_transaction_config_type text,
    business_unit text,
    created_by text,
    created_date_time text,
    description text,
    facility_number text,
    order_header_number text,
    quantity text,
    total_cost text,
    total_price text,
    transaction_type text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE purchase_order_line (
    "index" text,
    purchase_order_id text,
    item_number text,
    allocated_quantity text,
    canceled_pack_quantity text,
    catch_weight text,
    created_by text,
    created_date_time text,
    custom_field jsonb,
    custom_mapping_nil text,
    discount_amount text,
    extended_total text,
    line_number text,
    line_status text,
    line_total text,
    note jsonb,
    order_number text,
    order_pack_quantity text,
    pack_custom_mapping_nil text,
    pack_dimension_nil text,
    pack_quantity text,
    pack_type text,
    pack_upcs_nil text,
    picked_pack_quantity text,
    received_damaged_pack_quantity text,
    received_pack_quantity text,
    shipped_pack_quantity text,
    shipping_amount text,
    shortage_pack_quantity text,
    sold_pack_quantity text,
    sort_order text,
    tax_cost text,
    unit_cost text,
    unit_price text,
    untaxable_total text,
    updated_by text,
    updated_date_time text,
    PRIMARY KEY ("index", purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (item_number) REFERENCES inventory(item_number)
);

CREATE TABLE purchase_order (
    id text,
    actual_arrival_date text,
    bill_to_address jsonb,
    business_unit text,
    created_by text,
    created_date_time text,
    custom_mapping_nil text,
    drop_ship text,
    facility text,
    freight_bill_to_address jsonb,
    insurance_required text,
    number text,
    on_time text,
    order_discount_subtotal text,
    order_priority text,
    order_ship_total text,
    order_shipping_total text,
    order_sub_total text,
    order_tax_total text,
    order_taxable_total text,
    order_total text,
    order_untaxable_total text,
    return_required text,
    saturday_delivery text,
    send_asn text,
    ship_from_address jsonb,
    ship_to text,
    ship_to_address jsonb,
    shipping_status text,
    shipping_tax_total text,
    "status" text,
    taxable text,
    "type" text,
    updated_by text,
    updated_date_time text,
    PRIMARY KEY (id)
);

CREATE TABLE shipment (
    id text,
    line_item_number text,
    actual_ship_date text,
    bill_to_address_attention text,
    bill_to_address_city text,
    bill_to_address_contact_name text,
    bill_to_address_country_code text,
    bill_to_address_line_1 text,
    bill_to_address_line_2 text,
    bill_to_address_line_3 text,
    bill_to_address_line_4 text,
    bill_to_address_name text,
    bill_to_address_phone text,
    bill_to_address_postal_code text,
    bill_to_address_state_province_code text,
    business_unit text,
    cod_amount text,
    container_depth_uom text,
    container_description text,
    container_lpn text,
    container_number text,
    container_status text,
    container_total_charge text,
    container_tracking_number text,
    container_type text,
    created_by text,
    dimension_height text,
    dimension_length text,
    dimension_unit text,
    dimension_volume text,
    dimension_width text,
    drop_ship text,
    extended_shipping_cost_nil text,
    facility text,
    insurance_required text,
    line_customer_number text,
    line_expiration_date text,
    line_lot_number text,
    line_number text,
    line_order_pack_quantity text,
    line_shipment_number text,
    line_shipped_pack_quantity text,
    line_status text,
    line_tracking_number text,
    note_body text,
    note_title text,
    notification_code_1 text,
    order_customer_number text,
    order_number text,
    order_other_reference_number text,
    order_shipping_status text,
    order_source text,
    order_status text,
    order_type text,
    pack_custom_mapping_nil text,
    pack_dimension_nil text,
    pack_quantity text,
    pack_type text,
    pack_upcs_nil text,
    planned_ship_date text,
    rate_zone text,
    residential text,
    saturday_delivery text,
    ship_from_address_attention text,
    ship_from_address_city text,
    ship_from_address_country_code text,
    ship_from_address_line_1 text,
    ship_from_address_phone text,
    ship_from_address_postal_code text,
    ship_from_address_state_province_code text,
    ship_to_address_attention text,
    ship_to_address_city text,
    ship_to_address_contact_name text,
    ship_to_address_country_code text,
    ship_to_address_email text,
    ship_to_address_line_1 text,
    ship_to_address_line_2 text,
    ship_to_address_line_3 text,
    ship_to_address_line_4 text,
    ship_to_address_name text,
    ship_to_address_phone text,
    ship_to_address_postal_code text,
    ship_to_address_state_province_code text,
    ship_vendor text,
    ship_via text,
    shipment_number text,
    shipment_status text,
    shipping_cost text,
    tax_cost text,
    tracking_number text,
    tracking_url text,
    trading_partner text,
    "type" text,
    unit text,
    weight text,
    PRIMARY KEY (id),
    FOREIGN KEY (line_item_number) REFERENCES inventory(item_number)
);

CREATE TABLE sales_order_line (
    "index" text,
    sales_order_id text,
    item_number text,
    allocated_quantity text,
    canceled_pack_quantity text,
    catch_weight text,
    created_by text,
    created_date_time text,
    custom_field jsonb,
    custom_mapping_nil text,
    customer_line_number text,
    discount_amount text,
    export_reference text,
    extended_total text,
    line_number text,
    line_status text,
    line_total text,
    note jsonb,
    order_number text,
    order_pack_quantity text,
    pack_custom_mapping_nil text,
    pack_dimension_nil text,
    pack_quantity text,
    pack_type text,
    pack_upcs_nil text,
    picked_pack_quantity text,
    received_damaged_pack_quantity text,
    received_pack_quantity text,
    ship_from text,
    shipped_pack_quantity text,
    shipping_amount text,
    shortage_pack_quantity text,
    sold_pack_quantity text,
    sort_order text,
    tax_cost text,
    unit_cost text,
    unit_price text,
    untaxable_total text,
    updated_by text,
    updated_date_time text,
    zone_number text,
    PRIMARY KEY ("index", sales_order_id),
    FOREIGN KEY (sales_order_id) REFERENCES sales_order(id),
    FOREIGN KEY (item_number) REFERENCES inventory(item_number)
);

CREATE TABLE sales_order (
    id text,
    actual_ship_date text,
    bill_to_address_attention text,
    bill_to_address_city text,
    bill_to_address_contact_name text,
    bill_to_address_country_code text,
    bill_to_address_email text,
    bill_to_address_line_1 text,
    bill_to_address_line_2 text,
    bill_to_address_name text,
    bill_to_address_phone text,
    bill_to_address_postal_code text,
    bill_to_address_state_province_code text,
    business_unit text,
    cancel_by_arrival_date text,
    cancel_by_ship_date text,
    created_by text,
    created_date_time text,
    custom_attribute_1 text,
    custom_attribute_2 text,
    custom_attribute_3 text,
    custom_attribute_4 text,
    custom_attribute_5 text,
    custom_mapping_nil text,
    customer_order_number text,
    drop_ship text,
    facility text,
    freight_bill_to_address text,
    freight_term_type text,
    import_type text,
    insurance_required text,
    note_body text,
    note_title text,
    notification_code_1 text,
    number text,
    on_time text,
    order_discount_subtotal text,
    order_priority text,
    order_ship_total text,
    order_shipping_total text,
    order_source text,
    order_sub_total text,
    order_tax_total text,
    order_taxable_total text,
    order_total text,
    order_untaxable_total text,
    other_reference_number text,
    other_reference_number_2 text,
    placed_date text,
    planned_ship_date text,
    related_order_number text,
    return_required text,
    saturday_delivery text,
    send_asn text,
    ship_from_address text,
    ship_to_address_attention text,
    ship_to_address_city text,
    ship_to_address_contact_name text,
    ship_to_address_country_code text,
    ship_to_address_email text,
    ship_to_address_line_1 text,
    ship_to_address_line_2 text,
    ship_to_address_name text,
    ship_to_address_phone text,
    ship_to_address_postal_code text,
    ship_to_address_state_province_code text,
    ship_to_email text,
    ship_vendor text,
    ship_via text,
    shipping_status text,
    shipping_tax_total text,
    "status" text,
    taxable text,
    trading_partner text,
    "type" text,
    updated_by text,
    updated_date_time text,
    PRIMARY KEY (id)
);

CREATE TABLE billing_invoice_line (
    "index" text,
    invoice_number text,
    billing_transaction_type text,
    business_unit text,
    created_by text,
    created_date_time text,
    line_number text,
    quantity text,
    total_price text,
    updated_by text,
    updated_date_time text,
    PRIMARY KEY ("index", invoice_number),
    FOREIGN KEY (invoice_number) REFERENCES billing_invoice(number)
);

CREATE TABLE billing_invoice (
    number text,
    billing_end_date_time text,
    billing_start_date_time text,
    business_unit text,
    created_by text,
    created_date_time text,
    "status" text,
    updated_by text,
    updated_date_time text,
    PRIMARY KEY (number)
);
