CREATE TABLE contact (
    id text,
    creator_id text,
    created text,
    email text,
    email_1 text,
    email_1_type text,
    email_2 text,
    email_2_type text,
    fax text,
    im_1 text,
    im_1_type text,
    im_2 text,
    im_2_type text,
    mobile text,
    modified timestamp,
    note text,
    phone_1 text,
    phone_1_type text,
    phone_2 text,
    phone_2_type text,
    phone_3 text,
    phone_3_type text,
    primary_email text,
    primary_phone text,
    saved text,
    web text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE employment_condition (
    id text,
    creator_id text,
    avg_hours_per_day text,
    award_level text,
    created text,
    description text,
    employment_basis text,
    employment_category text,
    employment_period text,
    employment_status text,
    min_hours_for_leave text,
    min_hours_per_day text,
    modified timestamp,
    "name" text,
    probationary_period text,
    usual_finish_time text,
    usual_meal_break text,
    usual_start_time text,
    working_days_per_period text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE agreed_hour (
    _fivetran_id text,
    employee_id text,
    apply_threshold text,
    threshold text,
    work_period_cycle text,
    work_period_day_of_week text,
    work_period_end_cycle_date text,
    work_period_start_cycle_date text,
    work_period_start_date text,
    working_days_per_cycle text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE news_feed (
    id text,
    creator_id text,
    active text,
    confirm_text text,
    content text,
    created text,
    disable_comment text,
    file text,
    keyword text,
    modified text,
    show_from text,
    show_till text,
    title text,
    "type" text,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE "comment" (
    id text,
    creator_id text,
    "comment" text,
    created text,
    file text,
    ignore_permission text,
    in_feed text,
    modified timestamp,
    orm text,
    rec_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE employee_history (
    id text,
    company_id text,
    creator_id text,
    emergency_address text,
    employee_id text,
    main_address_id text,
    postal_address text,
    role_id text,
    active text,
    created text,
    date_of_birth text,
    display_name text,
    first_name text,
    gender text,
    job_app_id text,
    last_name text,
    modified timestamp,
    other_name text,
    photo text,
    "position" text,
    salutation text,
    start_date text,
    termination_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (emergency_address) REFERENCES address(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (main_address_id) REFERENCES address(id),
    FOREIGN KEY (postal_address) REFERENCES address(id),
    FOREIGN KEY (role_id) REFERENCES employee_role(id)
);

CREATE TABLE category (
    id text,
    creator_id text,
    category text,
    created text,
    groups text,
    modified timestamp,
    sort_order text,
    staff_log text,
    systems text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE pay_period (
    id text,
    creator_id text,
    active text,
    created text,
    cycle text,
    modified timestamp,
    "name" text,
    start_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE employee_availability (
    id text,
    creator_id text,
    employee_id text,
    "comment" text,
    created text,
    "date" text,
    end_time text,
    end_time_localized text,
    max_date_recurring_generated text,
    modified timestamp,
    schedule text,
    start_time text,
    start_time_localized text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE operational_unit (
    id text,
    address_id text,
    company_id text,
    contact_id text,
    creator_id text,
    parent_operational_unit text,
    active text,
    colour text,
    created text,
    daily_roster_budget text,
    modified timestamp,
    operational_unit_name text,
    operational_unit_type text,
    payroll_export_name text,
    roster_active_hours_schedule text,
    roster_sort_order text,
    show_on_roster text,
    work_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (parent_operational_unit) REFERENCES operational_unit(id)
);

CREATE TABLE stress_profile (
    id text,
    creator_id text,
    created text,
    custom_rules text,
    gap_hours_between_shifts text,
    max_days_per_period text,
    max_hours_per_day text,
    max_hours_per_period text,
    max_hours_per_shift text,
    modified timestamp,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE employee_workplace (
    id text,
    company_id text,
    creator_id text,
    employee_id text,
    agreement_1 text,
    agreement_2 text,
    agreement_3 text,
    created text,
    modified text,
    sort_order text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_leave_accrual (
    id text,
    employee_id text,
    "comment" text,
    days text,
    hours text,
    leave_rule_id text,
    transaction_date text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE contract_pay_rule (
    id text,
    creator_id text,
    employee_id text,
    advanced_calculation text,
    annual_salary text,
    "comment" text,
    config text,
    cr_id text,
    created text,
    ct_id text,
    dexml_script text,
    dexml_script_param text,
    hourly_rate text,
    is_exported text,
    is_multiplier text,
    maximum_shift_length text,
    maximum_type text,
    maximum_value text,
    minimum_shift_length text,
    minimum_type text,
    minimum_value text,
    modified text,
    multiplier_base_rate text,
    multiplier_value text,
    pay_portion_rule text,
    pay_title text,
    payroll_category text,
    period_type text,
    rate_tag text,
    rate_type text,
    recommend_with text,
    remuneration_by text,
    remuneration_type text,
    schedule text,
    unit_value text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE contract_leave_rule (
    id text,
    creator_id text,
    employee_id text,
    base_pay_rule text,
    contract_id text,
    created text,
    leave_rule_id text,
    loading_pay_rule_1 text,
    loading_pay_rule_2 text,
    loading_pay_rule_3 text,
    modified text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee (
    id text,
    contact_id text,
    contract_stress_profile_id text,
    history_id text,
    stress_profile_id text,
    user_id text,
    allow_appraisal text,
    allow_log_in text,
    analytics_id text,
    can_ask_to_show_pin text,
    contract_award text,
    contract_award_start_date text,
    contract_base_pay_rule text,
    contract_code text,
    contract_country_id text,
    contract_created text,
    contract_creator_id text,
    contract_description text,
    contract_employment_basis text,
    contract_employment_category text,
    contract_employment_condition text,
    contract_employment_status text,
    contract_employment_sub_type text,
    contract_end_date text,
    contract_file text,
    contract_id text,
    contract_migrate_to text,
    contract_modified text,
    contract_name text,
    contract_period_type text,
    contract_pp_id text,
    contract_start_date text,
    contract_strict_leave_approval text,
    contract_third_party_sync text,
    created text,
    custom_field_data text,
    custom_pronouns text,
    email text,
    employee_hourly_rate text,
    has_android_token text,
    has_enabled_2_fa text,
    has_iphone_token text,
    higher_duty text,
    image text,
    is_subordinate text,
    mobile text,
    modified timestamp,
    onboarding_id text,
    payroll_id text,
    photo_link_id text,
    pronouns text,
    salary_distribution_config text,
    "status" text,
    training_array jsonb,
    training_file_array jsonb,
    user_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (contract_stress_profile_id) REFERENCES stress_profile(id),
    FOREIGN KEY (history_id) REFERENCES employee_history(id),
    FOREIGN KEY (stress_profile_id) REFERENCES stress_profile(id),
    FOREIGN KEY (user_id) REFERENCES employee(id)
);

CREATE TABLE roster_slot (
    _fivetran_id text,
    roster_id text,
    bln_empty_slot text,
    int_end text,
    int_start text,
    int_unix_end text,
    int_unix_start text,
    mixed_activity_bln_can_end_early text,
    mixed_activity_bln_can_start_early text,
    mixed_activity_bln_is_mandatory text,
    mixed_activity_int_state text,
    mixed_activity_str_break_type text,
    str_state text,
    str_type text,
    str_type_name text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (roster_id) REFERENCES roster(id)
);

CREATE TABLE roster (
    id text,
    confirm_by text,
    creator_id text,
    employee_id text,
    matched_by_timesheet text,
    operational_unit_id text,
    approval_required text,
    bids_count text,
    "comment" text,
    confirm_comment text,
    confirm_status text,
    confirm_time text,
    connect_creator text,
    connect_status text,
    cost text,
    created text,
    custom_field_data text,
    "date" text,
    end_time text,
    end_time_localized text,
    external_id text,
    meal_break text,
    modified text,
    on_cost text,
    opens text,
    parent_id text,
    published text,
    shift_template text,
    start_time text,
    start_time_localized text,
    swap_manage_by text,
    swap_status text,
    total_time text,
    warning text,
    warning_override_comment text,
    PRIMARY KEY (id),
    FOREIGN KEY (confirm_by) REFERENCES employee(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (matched_by_timesheet) REFERENCES resource_timesheet(id),
    FOREIGN KEY (operational_unit_id) REFERENCES operational_unit(id)
);

CREATE TABLE timesheet_pay_retrun (
    id text,
    creator_id text,
    pay_rule_id text,
    timesheet_id text,
    cost text,
    created text,
    event_ids jsonb,
    modified timestamp,
    overridden text,
    override_comment text,
    "value" text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (pay_rule_id) REFERENCES contract_pay_rule(id),
    FOREIGN KEY (timesheet_id) REFERENCES resource_timesheet(id)
);

CREATE TABLE employee_agreement_history (
    id text,
    agreement_id text,
    creator_id text,
    active text,
    company_name text,
    contract_file text,
    contract_id text,
    created text,
    emp_type text,
    modified timestamp,
    pay_period text,
    pay_point text,
    payroll_id text,
    salary_pay_rule text,
    start_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (agreement_id) REFERENCES employee_agreement(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE company_period (
    id text,
    company_id text,
    creator_id text,
    pay_period text,
    created text,
    date_end text,
    date_start text,
    ends text,
    modified timestamp,
    "start" text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (pay_period) REFERENCES pay_period(id)
);

CREATE TABLE company (
    id text,
    address_id text,
    contact_id text,
    creator_id text,
    parent_company text,
    active text,
    business_number text,
    code text,
    company_name text,
    company_number text,
    created text,
    is_payroll_entity text,
    is_workplace text,
    modified timestamp,
    payroll_export_code text,
    portfolio text,
    trading_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (parent_company) REFERENCES company(id)
);

CREATE TABLE employee_agreement (
    id text,
    employee_id text,
    history_id text,
    base_rate text,
    config jsonb,
    created text,
    end_date text,
    modified timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (history_id) REFERENCES employee_agreement_history(id)
);

CREATE TABLE notification (
    id text,
    creator_id text,
    created text,
    expiry_date text,
    link text,
    message text,
    modified text,
    orm text,
    recid text,
    ts_created text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE award_library (
    _fivetran_id text,
    award_code text,
    country_code text,
    employment_term text,
    "name" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE address (
    id text,
    creator_id text,
    city text,
    contact_name text,
    country text,
    created text,
    format text,
    modified timestamp,
    note text,
    phone text,
    po_box text,
    post_code text,
    print text,
    saved text,
    "state" text,
    street_1 text,
    street_2 text,
    street_number text,
    suite_number text,
    unit_no text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);

CREATE TABLE leave_pay_line (
    id text,
    leave_id text,
    employee_agreement_id text,
    timesheet_id text,
    "comment" text,
    cost text,
    created text,
    creator text,
    "date" text,
    end_time text,
    end_time_localized text,
    hours text,
    leave_rule text,
    modified text,
    recalculate_with_reference_period text,
    start_time text,
    start_time_localized text,
    timezone text,
    PRIMARY KEY (id, leave_id),
    FOREIGN KEY (leave_id) REFERENCES employee_leave(id),
    FOREIGN KEY (employee_agreement_id) REFERENCES employee_agreement(id),
    FOREIGN KEY (timesheet_id) REFERENCES resource_timesheet(id)
);

CREATE TABLE employee_leave (
    id text,
    approver_pay text,
    company_id text,
    creator_id text,
    employee_history_id text,
    employee_id text,
    approval_comment text,
    approver_time text,
    "comment" text,
    created text,
    date_end text,
    date_end_all_day text,
    date_start text,
    date_start_all_day text,
    days text,
    end_time_localized text,
    ends text,
    external_id text,
    leave_rule_id text,
    modified timestamp,
    notify_manager jsonb,
    "start" text,
    start_time_localized text,
    "status" text,
    timezone text,
    total_hours text,
    PRIMARY KEY (id),
    FOREIGN KEY (approver_pay) REFERENCES employee(id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (employee_history_id) REFERENCES employee_history(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE timesheet_slot (
    _fivetran_id text,
    resource_timesheet_id text,
    bln_empty_slot text,
    int_end text,
    int_start text,
    int_unix_end text,
    int_unix_start text,
    mixed_activity_bln_can_end_early text,
    mixed_activity_bln_can_start_early text,
    mixed_activity_bln_is_mandatory text,
    mixed_activity_int_state text,
    mixed_activity_str_break_type text,
    str_state text,
    str_type text,
    str_type_name text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (resource_timesheet_id) REFERENCES resource_timesheet(id)
);

CREATE TABLE resource_timesheet (
    id text,
    agreement_id text,
    creator_id text,
    employee_id text,
    history_id text,
    leave_id text,
    parent_id text,
    roster_id text,
    accrual_attempts text,
    accrual_state text,
    accrual_state_changed_at text,
    auto_pay_rule_approved text,
    auto_processed text,
    auto_rounded text,
    auto_time_approved text,
    cost text,
    created text,
    custom_field_data jsonb,
    "date" text,
    discarded text,
    disputed text,
    employee_comment text,
    end_time text,
    end_time_localized text,
    exported text,
    file text,
    invoice_comment text,
    invoiced text,
    is_in_progress text,
    is_leave text,
    leave_rule_id text,
    marked_paid_unpaid_at text,
    meal_break text,
    meal_break_slots jsonb,
    metadata jsonb,
    modified timestamp,
    on_cost text,
    operational_unit text,
    pay_cycle_id text,
    pay_rule_approved text,
    pay_staged text,
    real_time text,
    staging_id text,
    start_time text,
    start_time_localized text,
    supervisor text,
    supervisor_comment text,
    time_approved text,
    time_approver text,
    total_time text,
    total_time_inv text,
    validation_flag text,
    PRIMARY KEY (id),
    FOREIGN KEY (agreement_id) REFERENCES employee_agreement(id),
    FOREIGN KEY (creator_id) REFERENCES employee(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (history_id) REFERENCES employee_history(id),
    FOREIGN KEY (leave_id) REFERENCES employee_leave(id),
    FOREIGN KEY (parent_id) REFERENCES resource_timesheet(id),
    FOREIGN KEY (roster_id) REFERENCES roster(id)
);

CREATE TABLE employee_role (
    id text,
    creator_id text,
    created text,
    modified timestamp,
    permission text,
    ranking text,
    report_to text,
    require_2_fa text,
    "role" text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES employee(id)
);
