CREATE TABLE users (
    id text,
    user_name text,
    active text,
    "admin" text,
    avatar_template text,
    can_be_deleted text,
    created_at text,
    created_at_age text,
    days_visited text,
    email text,
    last_emailed_age text,
    last_emailed_at text,
    last_seen_age text,
    last_seen_at text,
    manual_locked_trust_level text,
    moderator text,
    "name" text,
    post_count text,
    posts_read_count text,
    secondary_emails jsonb,
    silence_reason text,
    staged text,
    suspended_at text,
    suspended_till text,
    time_read text,
    title text,
    topics_entered text,
    trust_level text,
    PRIMARY KEY (id, user_name)
);

CREATE TABLE post_mentioned_user (
    id text,
    post_id text,
    avatar_template text,
    "name" text,
    user_name text,
    PRIMARY KEY (id, post_id),
    FOREIGN KEY (post_id) REFERENCES post(id)
);

CREATE TABLE post_action_summary (
    id text,
    post_id text,
    can_act text,
    PRIMARY KEY (id, post_id),
    FOREIGN KEY (post_id) REFERENCES post(id)
);

CREATE TABLE post (
    id text,
    category_id text,
    reply_to_user_id text,
    topic_id text,
    user_id text,
    accepted_answer text,
    "admin" text,
    avatar_template text,
    badges_granted jsonb,
    bookmarked text,
    can_accept_answer text,
    can_delete text,
    can_edit text,
    can_recover text,
    can_see_hidden_post text,
    can_unaccept_answer text,
    can_view_edit_history text,
    can_vote text,
    can_wiki text,
    cooked text,
    count text,
    created_at text,
    current_user_reaction text,
    current_user_used_main_reaction text,
    deleted_at text,
    deleted_by_avatar_template text,
    deleted_by_id text,
    deleted_by_name text,
    deleted_by_username text,
    display_username text,
    edit_reason text,
    excerpt text,
    flair_bg_color text,
    flair_color text,
    flair_group_id text,
    flair_name text,
    flair_url text,
    hidden text,
    incoming_link_count text,
    moderator text,
    "name" text,
    number text,
    primary_group_name text,
    quote_count text,
    raws text,
    reaction_users_count text,
    reactions jsonb,
    readers_count text,
    reads text,
    reply_count text,
    reply_to_post_number text,
    reviewable_id text,
    reviewable_score_count text,
    reviewable_score_pending_count text,
    score text,
    staff text,
    title_is_group text,
    topic_accepted_answer text,
    topic_html_title text,
    truncated text,
    trust_level text,
    "type" text,
    updated_at text,
    url text,
    user_birthdate text,
    user_cakedate text,
    user_deleted text,
    user_status_description text,
    user_status_emoji text,
    user_status_ends_at text,
    user_status_message_bus_last_id text,
    version text,
    wiki text,
    yours text,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (reply_to_user_id) REFERENCES users(id),
    FOREIGN KEY (topic_id) REFERENCES topic(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE group_member (
    id text,
    group_name text,
    user_name text,
    added_at text,
    "admin" text,
    avatar_template text,
    flair_group_id text,
    flair_name text,
    flair_url text,
    last_posted_at text,
    last_seen_at text,
    "name" text,
    primary_group_name text,
    temp_group_member_group_name text,
    timezone text,
    title text,
    trust_level text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_name) REFERENCES groups("name"),
    FOREIGN KEY (user_name) REFERENCES users(user_name)
);

CREATE TABLE group_owner (
    id text,
    group_name text,
    added_at text,
    avatar_template text,
    last_posted_at text,
    last_seen_at text,
    "name" text,
    temp_group_member_group_name text,
    timezone text,
    title text,
    user_name text,
    PRIMARY KEY (id, group_name),
    FOREIGN KEY (group_name) REFERENCES groups("name")
);

CREATE TABLE badge (
    id text,
    badge_grouping_id text,
    badge_type_id text,
    allow_title text,
    auto_revoke text,
    description text,
    enabled text,
    grant_count text,
    i_18_n_name text,
    icon text,
    image_upload_id text,
    image_url text,
    listable text,
    long_description text,
    manually_grantable text,
    multiple_grant text,
    "name" text,
    query text,
    show_in_post_header text,
    show_posts text,
    slug text,
    systems text,
    target_posts text,
    "trigger" text,
    PRIMARY KEY (id),
    FOREIGN KEY (badge_grouping_id) REFERENCES badge_grouping(id),
    FOREIGN KEY (badge_type_id) REFERENCES badge_type(id)
);

CREATE TABLE badge_type (
    id text,
    "name" text,
    sort_order text,
    PRIMARY KEY (id)
);

CREATE TABLE badge_grouping (
    id text,
    description text,
    "name" text,
    "position" text,
    systems text,
    PRIMARY KEY (id)
);

CREATE TABLE user_badge (
    id text,
    user_name text,
    badge_id text,
    badge_grouping_id text,
    badge_type_id text,
    granted_by_id text,
    can_favorite text,
    granted_at text,
    grouping_position text,
    is_favorite text,
    PRIMARY KEY (id, user_name, badge_id),
    FOREIGN KEY (badge_id) REFERENCES badge(id),
    FOREIGN KEY (badge_grouping_id) REFERENCES badge_grouping(id),
    FOREIGN KEY (badge_type_id) REFERENCES badge_type(id),
    FOREIGN KEY (granted_by_id) REFERENCES granted_bies(id)
);

CREATE TABLE granted_bies (
    id text,
    user_name text,
    "admin" text,
    avatar_template text,
    moderator text,
    "name" text,
    trust_level text,
    PRIMARY KEY (id, user_name)
);

CREATE TABLE groups (
    id text,
    "name" text,
    allow_membership_requests text,
    automatic text,
    bio_cooked text,
    bio_excerpt text,
    bio_raw text,
    can_admin_group text,
    can_edit_group text,
    can_see_members text,
    default_notification_level text,
    display_name text,
    flair_bg_color text,
    flair_color text,
    flair_url text,
    full_name text,
    grant_trust_level text,
    has_messages text,
    incoming_email text,
    is_group_owner text,
    is_group_user text,
    members_visibility_level text,
    membership_request_template text,
    mentionable_level text,
    messageable_level text,
    primary_group text,
    public_admission text,
    public_exit text,
    publish_read_state text,
    title text,
    user_count text,
    visibility_level text,
    PRIMARY KEY (id, "name")
);

CREATE TABLE tags (
    id text,
    count text,
    description text,
    "name" text,
    pm_only text,
    target_tag text,
    text text,
    PRIMARY KEY (id)
);

CREATE TABLE topic_poster (
    "index" text,
    topic_id text,
    user_id text,
    description text,
    extras text,
    flair_group_id text,
    primary_group_id text,
    PRIMARY KEY ("index", topic_id),
    FOREIGN KEY (topic_id) REFERENCES topic(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE topic (
    id text,
    category_id text,
    archetype text,
    archived text,
    bookmarked text,
    bumped text,
    bumped_at text,
    can_vote text,
    closed text,
    created_at text,
    excerpt text,
    fancy_title text,
    featured_link text,
    has_accepted_answer text,
    has_summary text,
    highest_post_number text,
    image_url text,
    last_posted_at text,
    last_poster_username text,
    like_count text,
    liked text,
    pinned text,
    pinned_globally text,
    posts_count text,
    reply_count text,
    slug text,
    tags jsonb,
    tags_descriptions jsonb,
    title text,
    unpinned text,
    unseen text,
    views text,
    visible text,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE subcategory_list (
    id text,
    category_id text,
    can_edit text,
    color text,
    count text,
    default_list_filter text,
    default_top_period text,
    default_view text,
    description text,
    description_excerpt text,
    description_text text,
    has_children text,
    icon text,
    list_style text,
    minimum_required_tags text,
    "name" text,
    navigate_to_first_post_after_read text,
    notification_level text,
    num_featured_topics text,
    permission text,
    "position" text,
    post_count text,
    read_restricted text,
    show_subcategory_list text,
    slug text,
    sort_ascending text,
    sort_order text,
    style_type text,
    text_color text,
    topic_count text,
    topic_template text,
    topic_url text,
    uploaded_background text,
    uploaded_background_dark text,
    uploaded_logo text,
    uploaded_logo_dark text,
    PRIMARY KEY (id, category_id),
    FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE category (
    id text,
    can_edit text,
    color text,
    default_list_filter text,
    default_top_period text,
    default_view text,
    description text,
    description_excerpt text,
    description_text text,
    has_children text,
    icon text,
    is_uncategorized text,
    minimum_required_tags text,
    "name" text,
    navigate_to_first_post_after_read text,
    notification_level text,
    num_featured_topics text,
    permission text,
    "position" text,
    post_count text,
    read_restricted text,
    show_subcategory_list text,
    slug text,
    sort_ascending text,
    sort_order text,
    style_type text,
    subcategory_count text,
    subcategory_list_style text,
    text_color text,
    topic_count text,
    topic_template text,
    topic_url text,
    topics_all_time text,
    topics_day text,
    topics_month text,
    topics_week text,
    topics_year text,
    uploaded_background text,
    uploaded_background_dark text,
    uploaded_logo text,
    uploaded_logo_dark text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);
