CREATE TABLE affiliate_user (
    id text,
    affiliate_id text,
    account_status text,
    cell_phone text,
    currency_id text,
    email text,
    first_name text,
    instant_messaging_id text,
    instant_messaging_identifier text,
    language_id text,
    last_name text,
    relationship_affiliate_account_status text,
    time_created text,
    time_saved text,
    timezone_id text,
    title text,
    work_phone text,
    PRIMARY KEY (id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id)
);

CREATE TABLE offer_ruleset_postal_code (
    network_id text,
    network_targeting_postal_code_id text,
    offer_id text,
    label text,
    match_type text,
    postal_code text,
    targeting_type text,
    PRIMARY KEY (network_id, network_targeting_postal_code_id, offer_id),
    FOREIGN KEY (offer_id) REFERENCES offer(id)
);

CREATE TABLE offer (
    id text,
    advertiser_id text,
    network_offer_group_id text,
    category text,
    channels text,
    currency_id text,
    daily_click_cap text,
    daily_conversion_cap text,
    daily_payout_cap text,
    daily_revenue_cap text,
    destination_url text,
    encoded_value text,
    global_click_cap text,
    global_conversion_cap text,
    global_payout_cap text,
    global_revenue_cap text,
    is_force_terms_and_conditions text,
    labels jsonb,
    monthly_click_cap text,
    monthly_conversion_cap text,
    monthly_payout_cap text,
    monthly_revenue_cap text,
    "name" text,
    network_advertiser_name text,
    network_id text,
    offer_status text,
    optimized_thumbnail_url text,
    payout text,
    payout_amount text,
    payout_percentage text,
    payout_type text,
    project_id text,
    remaining_daily_click_cap text,
    remaining_daily_conversion_cap text,
    remaining_daily_payout_cap text,
    remaining_daily_revenue_cap text,
    remaining_global_click_cap text,
    remaining_global_conversion_cap text,
    remaining_global_payout_cap text,
    remaining_global_revenue_cap text,
    remaining_monthly_click_cap text,
    remaining_monthly_conversion_cap text,
    remaining_monthly_payout_cap text,
    remaining_monthly_revenue_cap text,
    remaining_weekly_click_cap text,
    remaining_weekly_conversion_cap text,
    remaining_weekly_payout_cap text,
    remaining_weekly_revenue_cap text,
    revenue text,
    revenue_amount text,
    revenue_percentage text,
    revenue_type text,
    ruleset_brands jsonb,
    ruleset_browsers jsonb,
    ruleset_cities jsonb,
    ruleset_connection_types jsonb,
    ruleset_countries jsonb,
    ruleset_day_parting_apply_to text,
    ruleset_day_parting_timezone_id text,
    ruleset_days_parting jsonb,
    ruleset_device_types jsonb,
    ruleset_dmas jsonb,
    ruleset_ips jsonb,
    ruleset_is_block_proxy text,
    ruleset_is_use_day_parting text,
    ruleset_isps jsonb,
    ruleset_languages jsonb,
    ruleset_mobile_carriers jsonb,
    ruleset_network_id text,
    ruleset_network_ruleset_id text,
    ruleset_os_versions jsonb,
    ruleset_platforms jsonb,
    ruleset_regions jsonb,
    ruleset_time_created text,
    ruleset_time_saved text,
    thumbnail_url text,
    time_created text,
    time_saved text,
    today_clicks text,
    today_payout_amount text,
    today_revenue text,
    today_revenue_amount text,
    visibility text,
    weekly_click_cap text,
    weekly_conversion_cap text,
    weekly_payout_cap text,
    weekly_revenue_cap text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (network_offer_group_id) REFERENCES offer_group(id)
);

CREATE TABLE creative (
    id text,
    network_offer_id text,
    creative_status text,
    creative_type text,
    email_from text,
    email_from_line text,
    email_subject text,
    email_subject_line text,
    height text,
    html_code text,
    is_private text,
    "name" text,
    optimized_thumbnail_url text,
    resource_url text,
    time_created text,
    time_saved text,
    width text,
    PRIMARY KEY (id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE traffic_control_affiliate (
    "index" text,
    traffic_control_id text,
    affiliate_id text,
    PRIMARY KEY ("index", traffic_control_id),
    FOREIGN KEY (traffic_control_id) REFERENCES traffic_control(id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id)
);

CREATE TABLE traffic_control_advertiser (
    "index" text,
    traffic_control_id text,
    advertiser_id text,
    PRIMARY KEY ("index", traffic_control_id),
    FOREIGN KEY (traffic_control_id) REFERENCES traffic_control(id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE traffic_control_offer (
    "index" text,
    traffic_control_id text,
    network_offer_id text,
    PRIMARY KEY ("index", traffic_control_id),
    FOREIGN KEY (traffic_control_id) REFERENCES traffic_control(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE traffic_control (
    id text,
    comparison_method text,
    control_type text,
    date_valid_from text,
    date_valid_to text,
    is_apply_all_affiliate text,
    is_apply_all_offer text,
    "name" text,
    network_id text,
    "status" text,
    targeting_action text,
    time_created text,
    time_saved text,
    variables jsonb,
    PRIMARY KEY (id)
);

CREATE TABLE conversion_report (
    conversion_id text,
    advertiser_id text,
    affiliate_id text,
    network_offer_id text,
    network_offer_url_id text,
    account_manager_account_status text,
    account_manager_employee_id text,
    account_manager_first_name text,
    account_manager_full_name text,
    account_manager_last_name text,
    account_manager_network_id text,
    adv_1 text,
    adv_2 text,
    adv_3 text,
    adv_4 text,
    adv_5 text,
    affiliate_manager_account_status text,
    affiliate_manager_employee_id text,
    affiliate_manager_first_name text,
    affiliate_manager_full_name text,
    affiliate_manager_last_name text,
    affiliate_manager_network_id text,
    android_id text,
    android_id_md_5 text,
    android_id_sha_1 text,
    app_id text,
    brand text,
    browser text,
    carrier text,
    city text,
    click_unix_timestamp text,
    conversion_unix_timestamp text,
    conversion_user_ip text,
    country text,
    coupon_code text,
    currency_id text,
    device_model text,
    device_type text,
    dma text,
    email text,
    error_code text,
    error_message text,
    event text,
    google_ad_id text,
    google_ad_id_md_5 text,
    google_ad_id_sha_1 text,
    http_user_agent text,
    idfa text,
    idfa_md_5 text,
    idfa_sha_1 text,
    is_event text,
    is_scrub text,
    is_view_through text,
    isp text,
    languages text,
    network_offer_payout_revenue_id text,
    notes text,
    order_id text,
    os_version text,
    payout text,
    payout_type text,
    platform text,
    previous_network_offer_id text,
    referer text,
    region text,
    relationship_attribution_method text,
    relationship_query_parameters text,
    relationship_usm_data text,
    revenue text,
    revenue_type text,
    sale_amount text,
    session_user_ip text,
    source_id text,
    "status" text,
    sub_1 text,
    sub_2 text,
    sub_3 text,
    sub_4 text,
    sub_5 text,
    transaction_id text,
    url text,
    PRIMARY KEY (conversion_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id),
    FOREIGN KEY (network_offer_url_id) REFERENCES offer_url(id)
);

CREATE TABLE custom_cap (
    id text,
    affiliate_id text,
    network_offer_id text,
    daily_click_cap text,
    daily_conversion_cap text,
    daily_payout_cap text,
    daily_revenue_cap text,
    global_click_cap text,
    global_conversion_cap text,
    global_payout_cap text,
    global_revenue_cap text,
    is_soft_cap text,
    monthly_click_cap text,
    monthly_conversion_cap text,
    monthly_payout_cap text,
    monthly_revenue_cap text,
    "name" text,
    time_created text,
    time_saved text,
    weekly_click_cap text,
    weekly_conversion_cap text,
    weekly_payout_cap text,
    weekly_revenue_cap text,
    PRIMARY KEY (id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE affiliate_tracking (
    id text,
    affiliate_id text,
    network_offer_id text,
    domain_status text,
    html_static_redirect text,
    is_apply_all_offer text,
    is_primary_domain text,
    is_ssl_enabled text,
    network_tracking_domain_id text,
    ownership text,
    time_created text,
    time_saved text,
    url text,
    url_redirect text,
    PRIMARY KEY (id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE advertiser_user (
    id text,
    advertiser_id text,
    account_status text,
    cell_phone text,
    currency_id text,
    email text,
    first_name text,
    instant_messaging_id text,
    instant_messaging_identifier text,
    language_id text,
    last_name text,
    relationship jsonb,
    time_created text,
    time_saved text,
    timezone_id text,
    title text,
    work_phone text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE custom_scrubrate (
    id text,
    affiliate_id text,
    network_offer_id text,
    custom_setting_status text,
    "name" text,
    ruleset_brands jsonb,
    ruleset_browsers jsonb,
    ruleset_cities jsonb,
    ruleset_connection_types jsonb,
    ruleset_countries jsonb,
    ruleset_day_parting_apply_to text,
    ruleset_day_parting_timezone_id text,
    ruleset_days_parting jsonb,
    ruleset_device_types jsonb,
    ruleset_dmas jsonb,
    ruleset_ips jsonb,
    ruleset_is_block_proxy text,
    ruleset_is_use_day_parting text,
    ruleset_isps jsonb,
    ruleset_languages jsonb,
    ruleset_mobile_carriers jsonb,
    ruleset_network_id text,
    ruleset_network_ruleset_id text,
    ruleset_os_versions jsonb,
    ruleset_platforms jsonb,
    ruleset_postal_codes jsonb,
    ruleset_regions jsonb,
    ruleset_time_created text,
    ruleset_time_saved text,
    scrub_rate_percentage text,
    scrub_rate_status text,
    time_created text,
    time_saved text,
    PRIMARY KEY (id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE offer_application (
    id text,
    advertiser_id text,
    affiliate_id text,
    network_affiliate_user_id text,
    network_offer_id text,
    application_status text,
    relationship_employee_account_status text,
    relationship_employee_first_name text,
    relationship_employee_full_name text,
    relationship_employee_last_name text,
    relationship_employee_network_employee_id text,
    relationship_employee_network_id text,
    time_created text,
    time_saved text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (network_affiliate_user_id) REFERENCES affiliate_user(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE advertiser_relationship_entry (
    "index" text,
    advertiser_id text,
    entry text,
    PRIMARY KEY ("index", advertiser_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE advertiser (
    id text,
    account_manager_cell_phone text,
    account_manager_email text,
    account_manager_first_name text,
    account_manager_instant_messaging_id text,
    account_manager_instant_messaging_identifier text,
    account_manager_last_name text,
    account_manager_work_phone text,
    account_status text,
    accounting_contact_email text,
    address_id text,
    affiliate_id_macro text,
    attribution_method text,
    contact_address_1 text,
    contact_address_2 text,
    contact_address_id text,
    contact_city text,
    contact_country_code text,
    contact_country_id text,
    contact_region_code text,
    contact_zip_postal_code text,
    default_currency_id text,
    email_attribution_method text,
    integration_advertiser_demand_partner text,
    integration_optizmo text,
    internal_note text,
    is_contact_address_enabled text,
    is_expose_publisher_reporting_data text,
    "name" text,
    network_employee_id text,
    network_id text,
    offer_id_macro text,
    platform_name text,
    platform_url text,
    platform_username text,
    reporting_timezone_id text,
    sale_manager_cell_phone text,
    sale_manager_email text,
    sale_manager_first_name text,
    sale_manager_instant_messaging_id text,
    sale_manager_instant_messaging_identifier text,
    sale_manager_last_name text,
    sale_manager_work_phone text,
    sales_manager_id text,
    time_created text,
    time_saved text,
    verification_token text,
    PRIMARY KEY (id)
);

CREATE TABLE offer_url (
    id text,
    network_offer_id text,
    destination_url text,
    is_apply_specific_affiliate text,
    is_hidden_affiliate text,
    "name" text,
    network_affiliate_ids jsonb,
    preview_url text,
    remote_json_config text,
    remote_json_data text,
    remote_last_value_md_5 text,
    remote_network_id text,
    remote_network_offer_id text,
    remote_remote_resource_id text,
    remote_resource_id text,
    remote_resource_type text,
    remote_time_created text,
    remote_time_saved text,
    time_created text,
    time_saved text,
    url_status text,
    PRIMARY KEY (id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE affiliate_tier_network_affiliate (
    "index" text,
    affiliate_tier_id text,
    affiliate_id text,
    PRIMARY KEY ("index", affiliate_tier_id),
    FOREIGN KEY (affiliate_tier_id) REFERENCES affiliate_tier(id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id)
);

CREATE TABLE affiliate_tier (
    id text,
    description text,
    is_default_tier text,
    "name" text,
    network_id text,
    payout_margin text,
    "status" text,
    time_created text,
    time_saved text,
    PRIMARY KEY (id)
);

CREATE TABLE affiliate_label (
    "index" text,
    affiliate_id text,
    label text,
    PRIMARY KEY ("index", affiliate_id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id)
);

CREATE TABLE affiliate (
    id text,
    account_executive_id text,
    account_executive_name text,
    account_manager_id text,
    account_manager_name text,
    account_status text,
    balance text,
    global_tracking_domain_url text,
    is_payable text,
    last_login text,
    "name" text,
    network_country_code text,
    network_id text,
    network_traffic_source_id text,
    payment_term text,
    payment_type text,
    time_created text,
    time_saved text,
    today_revenue text,
    PRIMARY KEY (id)
);

CREATE TABLE offer_group_network_offer (
    "index" text,
    offer_group_id text,
    network_offer_id text,
    PRIMARY KEY ("index", offer_group_id),
    FOREIGN KEY (offer_group_id) REFERENCES offer_group(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE offer_group (
    id text,
    advertiser_id text,
    daily_click_cap text,
    daily_conversion_cap text,
    daily_payout_cap text,
    daily_revenue_cap text,
    entries jsonb,
    global_click_cap text,
    global_conversion_cap text,
    global_payout_cap text,
    global_revenue_cap text,
    internal_note text,
    is_caps_enabled text,
    is_soft_cap text,
    monthly_click_cap text,
    monthly_conversion_cap text,
    monthly_payout_cap text,
    monthly_revenue_cap text,
    "name" text,
    offer_group_status text,
    remaining_daily_click_cap text,
    remaining_daily_conversion_cap text,
    remaining_daily_payout_cap text,
    remaining_daily_revenue_cap text,
    remaining_global_click_cap text,
    remaining_global_conversion_cap text,
    remaining_global_payout_cap text,
    remaining_global_revenue_cap text,
    remaining_monthly_click_cap text,
    remaining_monthly_conversion_cap text,
    remaining_monthly_payout_cap text,
    remaining_monthly_revenue_cap text,
    remaining_weekly_click_cap text,
    remaining_weekly_conversion_cap text,
    remaining_weekly_payout_cap text,
    remaining_weekly_revenue_cap text,
    time_created text,
    time_saved text,
    weekly_click_cap text,
    weekly_conversion_cap text,
    weekly_payout_cap text,
    weekly_revenue_cap text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE smart_link_campaign (
    id text,
    campaign_name text,
    campaign_status text,
    catch_all_network_offer_id text,
    data_collection_threshold text,
    data_lookback_window text,
    encoded_value text,
    is_open_to_affiliate text,
    is_use_secure_link text,
    metric text,
    network_id text,
    network_tracking_domain_id text,
    optimization_goal text,
    redirect_routing_type text,
    relationship_label_entries jsonb,
    relationship_label_total text,
    run_frequency text,
    time_created text,
    time_saved text,
    PRIMARY KEY (id)
);

CREATE TABLE business_unit (
    id text,
    "name" text,
    network_id text,
    time_created text,
    time_saved text,
    PRIMARY KEY (id)
);

CREATE TABLE invoice (
    id text,
    affiliate_id text,
    affiliate_invoice_status text,
    balance text,
    billed text,
    currency_id text,
    end_time text,
    internal_note text,
    is_hidden_affiliate text,
    is_payable text,
    network_affiliate_name text,
    paid text,
    paid_date text,
    payment_status text,
    payment_term text,
    payment_type text,
    public_note text,
    start_time text,
    time_created text,
    time_saved text,
    timezone_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id)
);

CREATE TABLE custom_payout_revenue_affiliate (
    "index" text,
    custom_payout_revenue_id text,
    affiliate_id text,
    PRIMARY KEY ("index", custom_payout_revenue_id),
    FOREIGN KEY (custom_payout_revenue_id) REFERENCES custom_payout_revenue(id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id)
);

CREATE TABLE custom_payout_revenue_entry (
    affiliate_id text,
    custom_payout_revenue_id text,
    account_executive_id text,
    account_status text,
    adress_id text,
    default_currency_id text,
    enable_media_cost_tracking_link text,
    has_notifications text,
    internal_note text,
    is_contact_address_enabled text,
    "name" text,
    network_employee_id text,
    network_traffic_source_id text,
    referrer_id text,
    time_created text,
    time_saved text,
    PRIMARY KEY (affiliate_id, custom_payout_revenue_id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (custom_payout_revenue_id) REFERENCES custom_payout_revenue(id)
);

CREATE TABLE custom_payout_revenue (
    id text,
    network_offer_id text,
    custom_setting_status text,
    date_valid_from text,
    date_valid_to text,
    description text,
    is_apply_all_affiliate text,
    is_apply_specific_offer_url text,
    is_custom_payout_enabled text,
    is_custom_revenue_enabled text,
    is_postback_disabled text,
    "name" text,
    network_offer_payout_revenue_id text,
    network_offer_url_ids text,
    payout_amount text,
    payout_percentage text,
    payout_type text,
    public_description text,
    relationship_entry_name text,
    relationship_global_advertiser_event_id text,
    relationship_is_allow_duplicate_conversion text,
    relationship_is_default text,
    relationship_is_email_attribution_default_event text,
    relationship_is_enforce_cap text,
    relationship_is_must_approve_conversion text,
    relationship_is_postback_disabled text,
    relationship_is_private text,
    relationship_network_offer_payout_revenue_id text,
    relationship_payout_amount text,
    relationship_payout_percentage text,
    relationship_payout_type text,
    relationship_remote_offer_resource jsonb,
    relationship_revenue_amount text,
    relationship_revenue_percentage text,
    relationship_revenue_type text,
    relationship_time_created text,
    revenue_amount text,
    revenue_percentage text,
    revenue_type text,
    time_created text,
    time_saved text,
    PRIMARY KEY (id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE partner_postback (
    network_pixel_id text,
    affiliate_id text,
    network_offer_id text,
    delay_ms text,
    delivery_method text,
    description text,
    network_offer_payout_revenue_id text,
    pixel_level text,
    pixel_status text,
    pixel_type text,
    postback_url text,
    relationship jsonb,
    time_created text,
    time_saved text,
    PRIMARY KEY (network_pixel_id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);

CREATE TABLE coupon_code (
    id text,
    affiliate_id text,
    network_offer_id text,
    coupon_code text,
    coupon_status text,
    description text,
    end_date text,
    internal_note text,
    is_description_plain_text text,
    start_date text,
    time_created text,
    time_saved text,
    PRIMARY KEY (id),
    FOREIGN KEY (affiliate_id) REFERENCES affiliate(id),
    FOREIGN KEY (network_offer_id) REFERENCES offer(id)
);
