CREATE TABLE location (
    id text,
    parent_id text,
    city text,
    comments_count text,
    country text,
    created_at text,
    deltas text,
    description text,
    documents_count text,
    hidden_on_web_store text,
    identification_number text,
    latitude text,
    longitude text,
    manual_lat_long text,
    "name" text,
    secure_code text,
    sequence_num text,
    "state" text,
    "status" text,
    street_1 text,
    street_2 text,
    updated_at text,
    visible_on_web_store text,
    zipcode text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES location(id)
);

CREATE TABLE group_depreciation_rate (
    id text,
    groups_id text,
    created_at text,
    depreciation_method_id text,
    depreciation_method_name text,
    rate text,
    updated_at text,
    useful_life text,
    PRIMARY KEY (id, groups_id),
    FOREIGN KEY (groups_id) REFERENCES groups(id)
);

CREATE TABLE groups (
    id text,
    allow_staff_to_set_checkout_duration text,
    asset_depreciation_mode text,
    assets_count text,
    comments_count text,
    company_id text,
    created_at text,
    deltas text,
    description text,
    document jsonb,
    documents_count text,
    enable_service_triage text,
    hidden_on_web_store text,
    indefinite_triage_completion_period text,
    "name" text,
    pricing_bracket_interval text,
    staff_checkout_duration_day text,
    staff_checkout_duration_hour text,
    staff_checkout_duration_minute text,
    staff_checkout_duration_month text,
    staff_checkout_duration_week text,
    triage_completion_period text,
    triage_completion_period_basis text,
    updated_at text,
    visible_on_web_store text,
    PRIMARY KEY (id)
);

CREATE TABLE asset_stock_history (
    _fivetran_id text,
    asset_stock_id text,
    basket_asset_id text,
    basket_id text,
    purchase_order_id text,
    retire_reason_id text,
    service_id text,
    vendor_id text,
    action_source text,
    agreement_accepted text,
    agreement_document_id text,
    asset_name text,
    check_out_to_asset_id text,
    checked_in_from_location_id text,
    checked_out_to_location_id text,
    checkin_due_on text,
    checkin_on text,
    checkout_line_item_id text,
    checkout_on text,
    "comment" text,
    company_id text,
    cost_price text,
    cost_valuation_method text,
    created_at text,
    created_by_id text,
    deleted_at text,
    deleted_by_id text,
    for_retiring_checked_out_stock text,
    hidden_at text,
    hidden_by_id text,
    is_custody_transfer text,
    is_transfer text,
    item_audit_id text,
    order_type text,
    original_quantity text,
    paired_transfer_line_item_id text,
    price text,
    project_id text,
    purchased_on text,
    quantity text,
    quantity_after_transaction text,
    remaining_quantity text,
    retire_reason text,
    signature_image_id text,
    signed_by_name text,
    task_id text,
    transfer_from_location_id text,
    transition_from_substate_id text,
    transition_to_substate_id text,
    unit_cost_price text,
    updated_at text,
    user_full_name text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (asset_stock_id) REFERENCES asset_stock(id),
    FOREIGN KEY (basket_asset_id) REFERENCES cart_order_line_item(id),
    FOREIGN KEY (basket_id) REFERENCES cart(id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (retire_reason_id) REFERENCES retire_reason(id),
    FOREIGN KEY (service_id) REFERENCES asset_service_detail(service_id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE member (
    id text,
    account_name text,
    address text,
    address_line_2 text,
    address_name text,
    alert_type text,
    already_rated text,
    attach_invoice_with_order_alert text,
    auto_sync_with_ldap text,
    automation_user text,
    billing_address_id text,
    business_id text,
    category_id text,
    cc_business_in_alert text,
    cc_secondary_emails_in_alert text,
    city text,
    collect_tax text,
    comments_count text,
    compact_view text,
    company_default_payment_term text,
    consumed_timestep text,
    contact_owner text,
    contact_type text,
    country text,
    created_at text,
    created_by_id text,
    created_by_scim text,
    creation_source text,
    credit_memo_amount text,
    customer_category_id text,
    deactivated_at text,
    default_address_id text,
    default_triage_setting_id text,
    deleted_at text,
    department text,
    description text,
    display_picture_content_type text,
    display_picture_file_name text,
    display_picture_file_size text,
    display_picture_updated_at text,
    documents_count text,
    email text,
    employee_id text,
    employee_identification_number text,
    external_id text,
    fax text,
    first_name text,
    full_name text,
    guest_user text,
    hourly_rate text,
    iframe_request_sign_in_time text,
    inactive_by_id text,
    is_gsuite_user text,
    is_ldap_user text,
    jira_account_id text,
    last_name text,
    last_sync_date text,
    last_sync_source text,
    last_used_ffos_at text,
    manager_id text,
    offboarding_date text,
    otp_required_for_login text,
    password_changed_at text,
    payment_term_id text,
    payment_term_same_as_business text,
    phone_number text,
    role_id text,
    salesforce_id text,
    saml_session_index_id text,
    saml_user text,
    scim_action text,
    secure_code text,
    services_count text,
    settings_access text,
    show_announcement text,
    show_app_update text,
    signature text,
    single_step_addresses_qr_printing text,
    single_step_baskets_qr_printing text,
    single_step_bundles_qr_printing text,
    single_step_contacts_qr_printing text,
    single_step_customers_qr_printing text,
    single_step_locations_qr_printing text,
    single_step_members_qr_printing text,
    "state" text,
    "status" text,
    stock_asset_current_checkout_view text,
    stock_asset_group_by_column text,
    subscribed_to_email text,
    team_id text,
    transaction_started_at text,
    unseen_app_updates_count text,
    unsubscribed_by_id text,
    updated_at text,
    use_business_contact_detail text,
    user_listing_id text,
    web_store_sign_up_privacy_policy_agreed_on text,
    web_store_sign_up_terms_agreed_on text,
    web_store_signup text,
    webstore_authentication_token text,
    zendesk_account_id text,
    zip_code text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE retire_reason (
    id text,
    created_at text,
    "name" text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE inventory_line_item (
    id text,
    inventory_id text,
    "comment" text,
    created_at text,
    order_type text,
    price text,
    quantity text,
    quantity_after_transaction text,
    remaining_quantity text,
    updated_at text,
    PRIMARY KEY (id, inventory_id),
    FOREIGN KEY (inventory_id) REFERENCES inventory(id)
);

CREATE TABLE inventory (
    id text,
    group_id text,
    location_id text,
    purchase_order_id text,
    retire_reason_id text,
    sub_group_id text,
    vendor_id text,
    "action" text,
    advanced_pricing text,
    arbitration text,
    asset_type text,
    assigned_to_user_email text,
    audit_pending text,
    available_for_sale text,
    average_cost_per_unit text,
    bulk_import_id text,
    candidate_email text,
    checkin_due_on text,
    checkout_on text,
    clone_from_asset_id text,
    comments_count text,
    created_at text,
    created_by_itam text,
    current_meter_reading text,
    default_excess_location_threshold text,
    depreciation_calculation_required text,
    description text,
    display_image text,
    document jsonb,
    document_url jsonb,
    documents_count text,
    external_asset text,
    featured_item text,
    group_rule_provisioned text,
    hidden_on_web_store text,
    holder_id text,
    identifier text,
    image_url jsonb,
    initial_stock_quantity text,
    inventory_threshold text,
    is_processed text,
    it_asset_source text,
    itam_hardware_id text,
    item_audit_id text,
    last_assigned_to_id text,
    last_checked_in_at text,
    last_checked_out_at text,
    last_history_id text,
    latest_contract_id text,
    location_based_threshold text,
    location_name text,
    location_rule_provisioned text,
    merge_date text,
    "name" text,
    net_quantity text,
    network_asset text,
    package_id text,
    pending_verification text,
    price text,
    product_changed_manually text,
    product_id text,
    product_identity text,
    product_model_number text,
    purchased_on text,
    qbd_item_name text,
    quickbooks_item_id text,
    rent_collected text,
    rental_meter text,
    rental_meter_threshold text,
    retire_comment text,
    retire_reason text,
    retired_by_id text,
    retired_on text,
    sale_price text,
    salvage_value text,
    send_usage_meter_threshold_recurring_alert text,
    services_count text,
    "state" text,
    sub_checked_out_to_id text,
    sunshine_id text,
    synced_with_jira_at text,
    tax_free text,
    update_counter text,
    updated_at text,
    usage_meter_threshold text,
    visible_on_web_store text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (retire_reason_id) REFERENCES retire_reason(id),
    FOREIGN KEY (sub_group_id) REFERENCES subgroup(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE asset (
    id text,
    group_id text,
    location_id text,
    purchase_order_id text,
    retire_reason_id text,
    sub_group_id text,
    vendor_id text,
    "action" text,
    active_sub_checkout text,
    advanced_pricing text,
    arbitration text,
    asset_type text,
    assigned_to_user_email text,
    assigned_to_user_name text,
    audit_pending text,
    available_for_sale text,
    average_cost_per_unit text,
    bulk_import_id text,
    candidate_email text,
    checkin_due_on text,
    checkout_on text,
    clone_from_asset_id text,
    comments_count text,
    created_at text,
    created_by_itam text,
    current_meter_reading text,
    custom_substate_id text,
    default_excess_location_threshold text,
    depreciated_value_straight_line text,
    depreciation_calculation_required text,
    description text,
    display_image text,
    document jsonb,
    document_url jsonb,
    documents_count text,
    external_asset text,
    featured_item text,
    group_rule_provisioned text,
    hidden_on_web_store text,
    holder_id text,
    identifier text,
    image_url jsonb,
    initial_stock_quantity text,
    inventory_threshold text,
    is_processed text,
    it_asset_source text,
    itam_hardware_id text,
    item_audit_id text,
    last_assigned_to_id text,
    last_checked_in_at text,
    last_checked_out_at text,
    last_history_id text,
    latest_contract_id text,
    location_based_threshold text,
    location_name text,
    location_number text,
    location_rule_provisioned text,
    merge_date text,
    "name" text,
    net_quantity text,
    network_asset text,
    package_id text,
    pending_verification text,
    price text,
    product_changed_manually text,
    product_id text,
    product_identity text,
    product_model_number text,
    purchased_on text,
    qbd_item_name text,
    quickbooks_item_id text,
    rent_collected text,
    rental_meter text,
    rental_meter_threshold text,
    retire_comment text,
    retire_reason text,
    retired_by_id text,
    retired_on text,
    sale_price text,
    salvage_value text,
    send_usage_meter_threshold_recurring_alert text,
    services_count text,
    "state" text,
    sub_checked_out_to_full_name text,
    sub_checked_out_to_id text,
    sunshine_id text,
    synced_with_jira_at text,
    tax_free text,
    update_counter text,
    updated_at text,
    usage_meter_threshold text,
    visible_on_web_store text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (retire_reason_id) REFERENCES retire_reason(id),
    FOREIGN KEY (sub_group_id) REFERENCES subgroup(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE asset_depreciation_rate (
    id text,
    asset_id text,
    group_id text,
    created_at text,
    depreciation_method_id text,
    depreciation_method_name text,
    rate text,
    updated_at text,
    useful_life text,
    PRIMARY KEY (id, asset_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE asset_history (
    id text,
    asset_id text,
    basket_asset_id text,
    basket_id text,
    location_id text,
    action_source text,
    actual_checkin_on text,
    agreement_accepted text,
    agreement_document_id text,
    assigned_asset text,
    assigned_to_id text,
    assigned_to_name text,
    assigned_to_type text,
    checked_out_duration_in_seconds text,
    checkin_due_on text,
    checkin_on text,
    checkout_on text,
    comments_count text,
    company_id text,
    created_at text,
    created_by_id text,
    is_checkout text,
    is_transfer text,
    package_id text,
    past_checkout text,
    project_id text,
    rent_collected text,
    signature_image_id text,
    signed_by_name text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (basket_asset_id) REFERENCES cart_order_line_item(id),
    FOREIGN KEY (basket_id) REFERENCES cart(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE member_default_address (
    _fivetran_id text,
    member_id text,
    default_address jsonb,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE subgroup (
    id text,
    group_id text,
    allow_staff_to_set_checkout_duration text,
    assets_count text,
    created_at text,
    description text,
    enable_service_triage text,
    hidden_on_web_store text,
    indefinite_triage_completion_period text,
    lft text,
    "name" text,
    parent_id text,
    rgt text,
    staff_checkout_duration_day text,
    staff_checkout_duration_hour text,
    staff_checkout_duration_minute text,
    staff_checkout_duration_month text,
    staff_checkout_duration_week text,
    subgroup_path text,
    triage_completion_period text,
    triage_completion_period_basis text,
    triage_same_as_group text,
    updated_at text,
    visible_on_web_store text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE asset_stock_line_item (
    id text,
    asset_stock_id text,
    "comment" text,
    created_at text,
    order_type text,
    price text,
    quantity text,
    quantity_after_transaction text,
    remaining_quantity text,
    updated_at text,
    PRIMARY KEY (id, asset_stock_id),
    FOREIGN KEY (asset_stock_id) REFERENCES asset_stock(id)
);

CREATE TABLE asset_stock (
    id text,
    group_id text,
    location_id text,
    purchase_order_id text,
    retire_reason_id text,
    sub_group_id text,
    vendor_id text,
    "action" text,
    advanced_pricing text,
    arbitration text,
    asset_type text,
    assigned_to_user_email text,
    audit_pending text,
    available_for_sale text,
    available_quantity text,
    average_cost_per_unit text,
    bulk_import_id text,
    candidate_email text,
    checkin_due_on text,
    checkout_on text,
    clone_from_asset_id text,
    comments_count text,
    created_at text,
    created_by_itam text,
    current_meter_reading text,
    default_excess_location_threshold text,
    depreciation_calculation_required text,
    description text,
    display_image text,
    document jsonb,
    document_url jsonb,
    documents_count text,
    external_asset text,
    featured_item text,
    group_rule_provisioned text,
    hidden_on_web_store text,
    holder_id text,
    identifier text,
    image_url jsonb,
    initial_stock_quantity text,
    inventory_threshold text,
    is_processed text,
    it_asset_source text,
    itam_hardware_id text,
    item_audit_id text,
    last_assigned_to_id text,
    last_checked_in_at text,
    last_checked_out_at text,
    last_history_id text,
    latest_contract_id text,
    location_based_threshold text,
    location_name text,
    location_rule_provisioned text,
    merge_date text,
    "name" text,
    net_quantity text,
    network_asset text,
    package_id text,
    pending_verification text,
    price text,
    product_changed_manually text,
    product_id text,
    product_identity text,
    product_model_number text,
    purchased_on text,
    qbd_item_name text,
    quickbooks_item_id text,
    rent_collected text,
    rental_meter text,
    rental_meter_threshold text,
    retire_comment text,
    retire_reason text,
    retired_by_id text,
    retired_on text,
    sale_price text,
    salvage_value text,
    send_usage_meter_threshold_recurring_alert text,
    services_count text,
    "state" text,
    sub_checked_out_to_id text,
    sunshine_id text,
    synced_with_jira_at text,
    tax_free text,
    update_counter text,
    updated_at text,
    usage_meter_threshold text,
    visible_on_web_store text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (retire_reason_id) REFERENCES retire_reason(id),
    FOREIGN KEY (sub_group_id) REFERENCES subgroup(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE inventory_history (
    _fivetran_id text,
    basket_asset_id text,
    basket_id text,
    inventory_id text,
    purchase_order_id text,
    retire_reason_id text,
    service_id text,
    vendor_id text,
    action_source text,
    asset_name text,
    check_out_to_asset_id text,
    checked_in_from_location_id text,
    checked_out_to_location_id text,
    checkin_due_on text,
    checkin_on text,
    checkout_line_item_id text,
    checkout_on text,
    "comment" text,
    company_id text,
    cost_price text,
    cost_valuation_method text,
    created_at text,
    created_by_id text,
    deleted_at text,
    deleted_by_id text,
    for_retiring_checked_out_stock text,
    hidden_at text,
    hidden_by_id text,
    is_custody_transfer text,
    is_transfer text,
    item_audit_id text,
    order_type text,
    original_quantity text,
    paired_transfer_line_item_id text,
    price text,
    project_id text,
    purchased_on text,
    quantity text,
    quantity_after_transaction text,
    remaining_quantity text,
    retire_reason text,
    signature_image_id text,
    signed_by_name text,
    task_id text,
    transfer_from_location_id text,
    transition_from_substate_id text,
    transition_to_substate_id text,
    unit_cost_price text,
    updated_at text,
    user_full_name text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (basket_asset_id) REFERENCES cart_order_line_item(id),
    FOREIGN KEY (basket_id) REFERENCES cart(id),
    FOREIGN KEY (inventory_id) REFERENCES inventory(id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (retire_reason_id) REFERENCES retire_reason(id),
    FOREIGN KEY (service_id) REFERENCES asset_service_detail(service_id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE member_check_in_out_history (
    id text,
    basket_asset_id text,
    basket_id text,
    location_id text,
    member_id text,
    action_source text,
    actual_checkin_on text,
    agreement_accepted text,
    agreement_document_id text,
    assigned_asset text,
    assigned_to_id text,
    assigned_to_name text,
    assigned_to_type text,
    checked_out_duration_in_second text,
    checkin_due_on text,
    checkin_on text,
    checkout_on text,
    comments_count text,
    company_id text,
    created_at text,
    created_by_id text,
    is_checkout text,
    is_transfer text,
    package_id text,
    past_checkout text,
    project_id text,
    rent_collected text,
    signature_image_id text,
    signed_by_name text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (basket_asset_id) REFERENCES cart_order_line_item(id),
    FOREIGN KEY (basket_id) REFERENCES cart(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE asset_service_detail (
    service_id text,
    asset_sequence_num text,
    actual_end_date text,
    actual_start_date text,
    cost text,
    created_by text,
    end_date text,
    linked_inventory_item text,
    services_by text,
    start_date text,
    PRIMARY KEY (service_id),
    FOREIGN KEY (asset_sequence_num) REFERENCES asset(id)
);

CREATE TABLE purchase_order (
    id text,
    vendor_id text,
    approved_by_id text,
    approver_id text,
    approver_type text,
    comments_count text,
    company_id text,
    completed_on text,
    contract_id text,
    created_at text,
    created_by_id text,
    delivery_date text,
    delivery_location_id text,
    deltas text,
    description text,
    documents_count text,
    identification_number text,
    invoice_number text,
    net_amount text,
    note text,
    paid_amount text,
    parent_id text,
    payable_amount text,
    payment_term text,
    po_type text,
    project_id text,
    purchase_orders_asset jsonb,
    receiving_note text,
    requested_by_id text,
    sequence_num text,
    shipment_term text,
    "state" text,
    stock_request_id text,
    tax_amount text,
    title text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE location_item_quantity (
    _fivetran_id text,
    asset_num text,
    location_sequence_num text,
    total_quantity text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (asset_num) REFERENCES asset(id)
);

CREATE TABLE vendor (
    id text,
    address text,
    assets_count text,
    bulk_import_id text,
    comments_count text,
    company_id text,
    contact_person_name text,
    created_at text,
    deleted_at text,
    deltas text,
    description text,
    documents_count text,
    email text,
    fax text,
    "name" text,
    phone text,
    services_count text,
    "status" text,
    updated_at text,
    website text,
    PRIMARY KEY (id)
);

CREATE TABLE work_order_type (
    id text,
    category text,
    description text,
    "name" text,
    PRIMARY KEY (id)
);

CREATE TABLE cart_order_line_item (
    id text,
    cart_id text,
    asset_sequence_num text,
    asset_name text,
    PRIMARY KEY (id, cart_id),
    FOREIGN KEY (cart_id) REFERENCES cart(id),
    FOREIGN KEY (asset_sequence_num) REFERENCES asset(id)
);

CREATE TABLE cart (
    id text,
    location_id text,
    applied_taxes_on_line_item text,
    assigned_to_id text,
    associated_customer text,
    basket_payment_history jsonb,
    basket_recurring_line_item jsonb,
    basket_state text,
    baskets_sub_rent_item jsonb,
    best_pricing_applies text,
    bill_duration text,
    bill_from text,
    bill_to text,
    billing_address_id text,
    billing_contact_id text,
    bundle_price text,
    bundle_pricing_adjustment jsonb,
    bundle_snapshot_applied text,
    bundle_tax_amount text,
    cancelled_by_id text,
    checked_out_by_id text,
    checked_out_on text,
    checked_out_to_id text,
    clone_from_basket_id text,
    comments_count text,
    comments_on_damage text,
    comments_on_pre_payment text,
    comments_on_refund text,
    completed_by_id text,
    completed_on text,
    consistency_qb_tax_run_at text,
    contact_person_id text,
    coupon_to_apply text,
    coupons_applied text,
    coupons_discounts_detail text,
    created_at text,
    custom_attribute jsonb,
    custom_entry jsonb,
    custom_substate_id text,
    customer_collect_tax text,
    damage_amount text,
    delivery_cost text,
    delivery_date text,
    delivery_note text,
    delivery_person_id text,
    delivery_status text,
    delivery_time text,
    deltas text,
    description text,
    documents_count text,
    drop_off_location_id text,
    due_date text,
    duration text,
    dynamic_line_item jsonb,
    enable_customers_pricing text,
    enable_working_day text,
    expected_checkedout_date text,
    fixed_asset_rent jsonb,
    frozen_state text,
    gross_amount text,
    hide_time text,
    identification_number text,
    identification_number_last_updated_at text,
    inclusive_time_order text,
    inventory_price jsonb,
    invoice_heading text,
    is_negative_tax text,
    is_sold text,
    item_level_charge text,
    item_level_discount text,
    item_level_discount_applied text,
    last_action text,
    last_sync_at text,
    last_synced_with_qbd text,
    last_synced_with_quickbooks text,
    last_synced_with_xero text,
    late_due_date text,
    late_fee jsonb,
    late_fee_amount text,
    late_fee_applied text,
    line_item_damages_applied text,
    line_item_total_price text,
    location_for_delivery text,
    location_for_pickup text,
    marked_void_by_id text,
    max_verification_count text,
    net_amount text,
    net_amount_modified text,
    net_order_discount text,
    no_of_days_in_month text,
    occurrence_number text,
    order_discount text,
    order_state text,
    order_type text,
    overage_charge text,
    overridden_tax_amount text,
    payable_amount text,
    payment_completed_on text,
    payment_method_for_pre_payment text,
    payment_method_for_return text,
    payment_note text,
    payment_start_time text,
    payment_term_date text,
    payment_term_due_date_updated_at text,
    payment_term_due_date_updated_by_id text,
    payment_term_edited text,
    persist_items_present_in_order_location text,
    persist_location_based_searching text,
    persist_only_available_assets_check text,
    persist_show_only_available_bundle text,
    pick_up_address_id text,
    pick_up_location_id text,
    pickup_cost text,
    pickup_date text,
    pickup_note text,
    pickup_person_id text,
    pickup_status text,
    pickup_time text,
    pre_paid_amount text,
    prices_calculated_by_snapshot text,
    pricing_coupon_discount text,
    pricing_model text,
    pricing_updated_at text,
    project_id text,
    promotional_discount text,
    qb_tax_amount text,
    qbd_due_date text,
    qbd_txn_date text,
    quantity text,
    quickbooks_invoice_id text,
    quickbooks_last_sync_order_status text,
    quickbooks_last_sync_payment_status text,
    quickbooks_sync_failed_count text,
    quickbooks_tax_sync_failed_at text,
    recurrence_due_date text,
    recurrence_id text,
    refund_amount text,
    rental_tax text,
    reserved_by_id text,
    reserved_for_id text,
    reserved_on text,
    resource_id text,
    resource_type text,
    rules_and_coupons_enabled text,
    sales_tax text,
    secure_code text,
    service_offering_price jsonb,
    shipping_address_id text,
    shipping_contact_id text,
    skip_auto_accounting_syncing text,
    "state" text,
    stock_asset_rent jsonb,
    sync_qbd_discount_as_service text,
    tax text,
    tax_amount jsonb,
    taxable_amount text,
    time_zone text,
    total_expenses text,
    transaction_started_at text,
    unvoided_by_id text,
    unvoided_on text,
    updated_at text,
    usage_charge text,
    user_id text,
    user_listing_id text,
    working_day text,
    xero_invoice_id text,
    xero_last_sync_order_status text,
    xero_last_sync_payment_status text,
    xero_sync_failed_count text,
    PRIMARY KEY (id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);
