CREATE TABLE sensor_stop_cause_meta (
    "index" text,
    device_id text,
    sensor_id text,
    sensor_stop_cause_id text,
    stop_cause_category_id text,
    description text,
    language_code text,
    "name" text,
    PRIMARY KEY ("index", device_id, sensor_id, sensor_stop_cause_id, stop_cause_category_id),
    FOREIGN KEY (device_id) REFERENCES sensor_stop_cause(device_id),
    FOREIGN KEY (sensor_id) REFERENCES sensor_stop_cause(sensor_id),
    FOREIGN KEY (sensor_stop_cause_id) REFERENCES sensor_stop_cause(id),
    FOREIGN KEY (stop_cause_category_id) REFERENCES sensor_stop_cause(stop_cause_category_id)
);

CREATE TABLE sensor_stop_cause (
    id text,
    device_id text,
    sensor_id text,
    stop_cause_category_id text,
    deleted text,
    description text,
    enable_counter_measure text,
    legacy_stop_cause_id text,
    "name" text,
    orders text,
    require_comment text,
    require_initial text,
    stop_type text,
    PRIMARY KEY (id, device_id, sensor_id, stop_cause_category_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (sensor_id) REFERENCES sensor(id),
    FOREIGN KEY (stop_cause_category_id) REFERENCES sensor_stop_cause_category(id)
);

CREATE TABLE changeover_stop (
    id text,
    target_next_batch_batch_id text,
    target_previous_batch_batch_id text,
    target_shift_targetline_id text,
    "comment" text,
    counter_measur_initials text,
    counter_measure text,
    duration text,
    initials text,
    is_automatic_registration text,
    is_micro_stop text,
    ongoing text,
    registered_time text,
    standalone_exclude_production text,
    stop_cause_category_name text,
    stop_cause_deleted text,
    stop_cause_description text,
    stop_cause_enable_counter_measure text,
    stop_cause_id text,
    stop_cause_language_code text,
    stop_cause_legacy_stop_cause_id text,
    stop_cause_name text,
    stop_cause_order text,
    stop_cause_require_comment text,
    stop_cause_require_initials text,
    stop_cause_stop_type text,
    target text,
    target_next_batch_actual_start text,
    target_next_batch_actual_stop text,
    target_next_batch_batch_number text,
    target_next_batch_name text,
    target_next_batch_planned_start text,
    target_next_batch_product_id text,
    target_previous_batch_actual_start text,
    target_previous_batch_actual_stop text,
    target_previous_batch_batch_number text,
    target_previous_batch_name text,
    target_previous_batch_planned_start text,
    target_previous_batch_product_id text,
    target_shift_description text,
    target_shift_from_day text,
    target_shift_from_hour text,
    target_shift_from_minute text,
    target_shift_id text,
    target_shift_name text,
    target_shift_target_id text,
    target_shift_target_line_id text,
    target_shift_target_main_oee_type text,
    target_shift_target_number_of_batches text,
    target_shift_target_oee text,
    target_shift_target_oee_2 text,
    target_shift_target_oee_3 text,
    target_shift_target_produced text,
    target_shift_target_tcu text,
    target_shift_target_valid_from_week text,
    target_shift_target_valid_from_year text,
    target_shift_to_day text,
    target_shift_to_hour text,
    target_shift_to_minute text,
    time_range_from text,
    time_range_to text,
    PRIMARY KEY (id),
    FOREIGN KEY (target_next_batch_batch_id) REFERENCES batch(id),
    FOREIGN KEY (target_previous_batch_batch_id) REFERENCES batch(id),
    FOREIGN KEY (target_shift_targetline_id) REFERENCES line(id)
);

CREATE TABLE product (
    product_id text,
    attached_control_receipt_entry_field_sensor_id text,
    line_id text,
    attached_control_receipt_attached_product_id text,
    attached_control_receipt_control_receipt_id text,
    attached_control_receipt_deleted text,
    attached_control_receipt_description text,
    attached_control_receipt_entry_entry_id text,
    attached_control_receipt_entry_field_derivation_setting_fields text,
    attached_control_receipt_entry_field_derivation_setting_formula text,
    attached_control_receipt_entry_field_description text,
    attached_control_receipt_entry_field_field_id text,
    attached_control_receipt_entry_field_label text,
    attached_control_receipt_entry_field_lower_limit text,
    attached_control_receipt_entry_field_type text,
    attached_control_receipt_entry_field_upper_limit text,
    attached_control_receipt_entry_follow_up_delay_ms text,
    attached_control_receipt_entry_follow_up_enabled text,
    attached_control_receipt_entry_initial_setting text,
    attached_control_receipt_entry_title text,
    attached_control_receipt_entry_trigger_delay_when_stopped text,
    attached_control_receipt_entry_trigger_payload_millis text,
    attached_control_receipt_entry_trigger_type text,
    attached_control_receipt_name text,
    attached_control_receipt_user_pool_id text,
    "comment" text,
    data_multiplier text,
    expected_average_speed text,
    item_number text,
    "name" text,
    overwritten_by_batch text,
    packaging_comment text,
    packaging_line_id text,
    packaging_name text,
    packaging_packaging_id text,
    packaging_packaging_number text,
    packaging_unit text,
    parameters_alarm_id text,
    parameters_key text,
    parameters_setpoint_peripheral_id text,
    parameters_setpoint_value text,
    parameters_value text,
    validated_line_speed text,
    PRIMARY KEY (product_id),
    FOREIGN KEY (attached_control_receipt_entry_field_sensor_id) REFERENCES sensor(id),
    FOREIGN KEY (line_id) REFERENCES line(id)
);

CREATE TABLE batch_stop_cause_meta (
    "index" text,
    batch_id text,
    batch_stop_cause_index text,
    line_id text,
    description text,
    language_code text,
    "name" text,
    PRIMARY KEY ("index", batch_id, batch_stop_cause_index, line_id),
    FOREIGN KEY (batch_id) REFERENCES batch_stop_cause(batch_id),
    FOREIGN KEY (batch_stop_cause_index) REFERENCES batch_stop_cause("index"),
    FOREIGN KEY (line_id) REFERENCES batch_stop_cause(line_id)
);

CREATE TABLE batch_stop_cause (
    "index" text,
    batch_id text,
    line_id text,
    stop_id text,
    category_id text,
    category_name text,
    deleted text,
    description text,
    enable_counter_measure text,
    language_code text,
    legacy_stop_cause_id text,
    "name" text,
    orders text,
    require_comment text,
    require_initial text,
    stop_cause_id text,
    stop_type text,
    target_setup_constant_time text,
    PRIMARY KEY ("index", batch_id, line_id),
    FOREIGN KEY (batch_id) REFERENCES batch(id),
    FOREIGN KEY (line_id) REFERENCES line(id),
    FOREIGN KEY (stop_id) REFERENCES stop(id)
);

CREATE TABLE line (
    id text,
    company_id text,
    description text,
    language_code text,
    main_peripheral_id text,
    "name" text,
    owner text,
    "time" jsonb,
    time_zone text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE line_stop (
    id text,
    line_id text,
    "comment" text,
    counter_measure text,
    counter_measure_initial text,
    duration text,
    initials jsonb,
    is_automatic_registration text,
    is_micro_stop text,
    ongoing text,
    original_start text,
    registered_time text,
    time_range_from text,
    time_range_to text,
    PRIMARY KEY (id, line_id),
    FOREIGN KEY (line_id) REFERENCES line(id)
);

CREATE TABLE stop (
    id text,
    batch_id text,
    "comment" text,
    counter_measure text,
    counter_measure_initial text,
    duration text,
    initials text,
    is_automatic_registration text,
    is_micro_stop text,
    ongoing text,
    original_start text,
    registered_time text,
    standalone_exclude_production text,
    target text,
    target_current_shift text,
    target_next_batch text,
    target_previous_batch text,
    time_range_from text,
    time_range_to text,
    PRIMARY KEY (id, batch_id),
    FOREIGN KEY (batch_id) REFERENCES batch(id)
);

CREATE TABLE stop_cause_stats (
    batch_id text,
    id text,
    acc_duration text,
    acc_target text,
    is_micro_stop text,
    number_of_stops text,
    stop_category_name text,
    stop_cause_description text,
    stop_cause_name text,
    "type" text,
    PRIMARY KEY (batch_id, id),
    FOREIGN KEY (batch_id) REFERENCES batch(id),
    FOREIGN KEY (id) REFERENCES sensor_stop_cause(id)
);

CREATE TABLE batch (
    id text,
    line_id text,
    product_id text,
    actual_etc text,
    actual_start text,
    actual_stop text,
    amount text,
    batch_number text,
    "comment" text,
    last_stop_comment text,
    last_stop_counter_measure text,
    last_stop_counter_measure_initial text,
    last_stop_duration text,
    last_stop_id text,
    last_stop_initials text,
    last_stop_is_automatic_registration text,
    last_stop_is_micro_stop text,
    last_stop_ongoing text,
    last_stop_registered_time text,
    longest_non_stop text,
    manual_scrap text,
    planned_etc text,
    planned_start text,
    produced text,
    sorting text,
    "state" text,
    tags jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (line_id) REFERENCES line(id),
    FOREIGN KEY (product_id) REFERENCES product(product_id)
);

CREATE TABLE sensor_stop_cause_category (
    id text,
    sensor_device_id text,
    sensor_id text,
    deleted text,
    language_code text,
    legacy_category_id text,
    "name" text,
    orders text,
    owner_type text,
    PRIMARY KEY (id, sensor_device_id, sensor_id),
    FOREIGN KEY (sensor_device_id) REFERENCES sensor(device_id),
    FOREIGN KEY (sensor_id) REFERENCES sensor(id)
);

CREATE TABLE sensor_group_peripheral (
    peripheral_id text,
    sensor_group_device_id text,
    sensor_group_id text,
    sensor_id text,
    PRIMARY KEY (peripheral_id, sensor_group_device_id, sensor_group_id, sensor_id),
    FOREIGN KEY (sensor_group_device_id) REFERENCES sensor_group(sensor_device_id),
    FOREIGN KEY (sensor_group_id) REFERENCES sensor_group(id),
    FOREIGN KEY (sensor_id) REFERENCES sensor_group(sensor_id)
);

CREATE TABLE sensor_group_line (
    line_id text,
    sensor_group_device_id text,
    sensor_group_id text,
    sensor_id text,
    PRIMARY KEY (line_id, sensor_group_device_id, sensor_group_id, sensor_id),
    FOREIGN KEY (line_id) REFERENCES line(id),
    FOREIGN KEY (sensor_group_device_id) REFERENCES sensor_group(sensor_device_id),
    FOREIGN KEY (sensor_group_id) REFERENCES sensor_group(id),
    FOREIGN KEY (sensor_id) REFERENCES sensor_group(sensor_id)
);

CREATE TABLE sensor_group (
    id text,
    sensor_device_id text,
    sensor_id text,
    default_group text,
    description text,
    "name" text,
    node_id text,
    PRIMARY KEY (id, sensor_device_id, sensor_id),
    FOREIGN KEY (sensor_device_id) REFERENCES sensor(device_id),
    FOREIGN KEY (sensor_id) REFERENCES sensor(id)
);

CREATE TABLE sensor (
    id text,
    device_id text,
    peripheral_line_id text,
    alarms jsonb,
    camera jsonb,
    config_analog_input_range text,
    config_analog_offset text,
    config_chart_time_scale text,
    config_data_multiplier text,
    config_energy_meter text,
    config_expected_speed text,
    config_extra_multiplier_for_frontend text,
    config_find_stops text,
    config_publish_rate text,
    config_sample_rate text,
    config_stop_register_threshold text,
    config_stop_threshold text,
    config_stop_value_threshold text,
    config_subtract_cycle_time text,
    config_trigger_index text,
    config_type text,
    config_validated_speed text,
    custom_kpi jsonb,
    description text,
    hardware_id text,
    horizontal_annotation jsonb,
    "index" text,
    "name" text,
    offline_status_expiration text,
    offline_status_last_received text,
    owner text,
    peripheral_type text,
    scheduled_report jsonb,
    stop_cause_mapping jsonb,
    PRIMARY KEY (id, device_id),
    FOREIGN KEY (device_id) REFERENCES device(id),
    FOREIGN KEY (peripheral_line_id) REFERENCES line(id)
);

CREATE TABLE device (
    id text,
    hardware_id text,
    "name" text,
    num_input_port text,
    owner text,
    "type" text,
    uuid text,
    PRIMARY KEY (id)
);

CREATE TABLE oee (
    _fivetran_id text,
    line_id text,
    consolidated_time_from text,
    consolidated_time_to text,
    manned_time text,
    oee_1 text,
    oee_2 text,
    oee_3 text,
    operating_time text,
    production_time text,
    scrap_loss text,
    speed_loss text,
    tcu text,
    total_equipment_time text,
    valued_operating_time text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (line_id) REFERENCES line(id)
);

CREATE TABLE company (
    id text,
    "name" text,
    PRIMARY KEY (id)
);
