CREATE TABLE online_store_search_result (
    "index" text,
    report_date text,
    search_term_id text,
    market text,
    online_store text,
    search_result_link text,
    PRIMARY KEY ("index", report_date, search_term_id),
    FOREIGN KEY (report_date) REFERENCES search_term(report_date),
    FOREIGN KEY (search_term_id) REFERENCES search_term(id)
);

CREATE TABLE search_term (
    id text,
    report_date text,
    region text,
    search_term text,
    search_term_priority_status text,
    "type" text,
    PRIMARY KEY (id, report_date)
);

CREATE TABLE product_promotion (
    "index" text,
    product_id text,
    report_date text,
    discount_amount integer,
    discount_percent integer,
    discounted_price integer,
    listed_price integer,
    net_diff_from_min text,
    net_diff_from_min_percent text,
    non_discounted_price integer,
    promotion_type text,
    text jsonb,
    PRIMARY KEY ("index", product_id, report_date),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (report_date) REFERENCES product(report_date)
);

CREATE TABLE product (
    id text,
    report_date text,
    availability_complaint text,
    availability_status text,
    average_sales text,
    brand text,
    category text,
    content_compliant text,
    content_milestone_10_compliant boolean,
    content_milestone_1_compliant boolean,
    content_milestone_2_compliant boolean,
    content_milestone_3_compliant boolean,
    content_milestone_4_compliant boolean,
    content_milestone_5_compliant boolean,
    content_milestone_6_compliant boolean,
    content_milestone_7_compliant boolean,
    content_milestone_8_compliant boolean,
    content_milestone_9_compliant boolean,
    dimension_1 text,
    dimension_2 text,
    dimension_3 text,
    dimension_4 text,
    dimension_5 text,
    dimension_6 text,
    dimension_7 text,
    dimension_8 text,
    harvested_additional_description text,
    harvested_duplicate_image_count text,
    harvested_gallery_video_count text,
    harvested_image_alt_text text,
    harvested_image_count text,
    harvested_ingredients_list text,
    harvested_product_description text,
    harvested_product_image_url text,
    harvested_size_information text,
    harvested_url text,
    harvested_variant_information text,
    harvested_video_count text,
    imaging_compliance jsonb,
    imaging_compliant text,
    imaging_status text,
    is_competitor text,
    is_on_promotion text,
    manufacturer text,
    menu_compliant text,
    menu_position text,
    online_store text,
    overall_rating text,
    pricing_currency_symbol text,
    pricing_diff_from_min_max text,
    pricing_diff_from_min_max_percent text,
    pricing_diff_from_msrp text,
    pricing_diff_from_msrp_compliant text,
    pricing_diff_from_msrp_percent text,
    pricing_diff_from_previous_observed_price text,
    pricing_diff_from_previous_observed_price_percent text,
    pricing_max_price text,
    pricing_min_price text,
    pricing_msrp text,
    pricing_net_diff_from_min text,
    pricing_net_diff_from_min_compliant text,
    pricing_net_diff_from_min_percent text,
    pricing_non_discounted_price text,
    pricing_observed_price text,
    pricing_previous_observed_price text,
    pricing_price_compliant text,
    pricing_subheading text,
    rating_compliant text,
    region text,
    review_compliant text,
    review_count text,
    sales_currency_symbol text,
    search_score_compliant text,
    traffic_page_views text,
    traffic_rank text,
    trusted_mpc text,
    trusted_product_description text,
    trusted_rpc text,
    trusted_upc text,
    "type" text,
    PRIMARY KEY (id, report_date)
);

CREATE TABLE content_result (
    harvested_rpc text,
    id text,
    report_date text,
    brand text,
    category text,
    dimension_1 text,
    dimension_2 text,
    dimension_3 text,
    dimension_4 text,
    dimension_5 text,
    dimension_6 text,
    dimension_7 text,
    dimension_8 text,
    harvested text,
    harvested_url text,
    is_competitor text,
    manufacturer text,
    milestone text,
    online_store text,
    region text,
    rule_error_message text,
    rule_name text,
    trusted_mpc text,
    trusted_product_description text,
    trusted_upc text,
    "type" text,
    PRIMARY KEY (harvested_rpc, id, report_date)
);

CREATE TABLE search_term_result (
    id text,
    online_store text,
    search_result_rank text,
    report_date text,
    search_term text,
    search_term_id text,
    brand text,
    category text,
    dimension_1 text,
    dimension_2 text,
    dimension_3 text,
    dimension_4 text,
    dimension_5 text,
    dimension_6 text,
    dimension_7 text,
    dimension_8 text,
    harvested_product_description text,
    harvested_product_image_url text,
    harvested_url text,
    is_competitor text,
    is_priority_search_term text,
    manufacturer text,
    region text,
    results_per_page text,
    search_result_basic_score text,
    search_result_is_paid text,
    search_result_max_rank text,
    search_result_priority_score text,
    search_result_segment text,
    search_result_segment_value text,
    search_result_weighted_score text,
    trusted_mpc text,
    trusted_product_description text,
    trusted_rpc text,
    trusted_upc text,
    "type" text,
    PRIMARY KEY (id, online_store, search_result_rank, report_date, search_term, search_term_id),
    FOREIGN KEY (report_date) REFERENCES search_term(report_date),
    FOREIGN KEY (search_term) REFERENCES search_term(search_term),
    FOREIGN KEY (search_term_id) REFERENCES search_term(id)
);
