CREATE TABLE shipment_item (
    _fivetran_id text,
    shipment_id text,
    description text,
    freight_class double precision,
    hazard_class text,
    hazard_hazmat_id text,
    hazard_packing_group text,
    hazard_special_permit text,
    hazard_sub_class_1 text,
    hazard_sub_class_2 text,
    hazardous boolean,
    height bigint,
    length bigint,
    nmfc text,
    package text,
    pieces bigint,
    said_to_contain bigint,
    said_to_contain_packaging_type text,
    stackable boolean,
    weight bigint,
    width bigint,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_rate_charge (
    "index" text,
    shipment_id text,
    amount double precision,
    code text,
    "name" text,
    provider_detail text,
    PRIMARY KEY ("index", shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_accessorial (
    accessorial text,
    shipment_id text,
    PRIMARY KEY (accessorial, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_file (
    _fivetran_id text,
    shipment_id text,
    subtype text,
    "type" text,
    upload_date timestamp,
    url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_share_shipment_email (
    email text,
    shipment_id text,
    PRIMARY KEY (email, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_invoice_payment (
    "index" text,
    shipment_id text,
    amount double precision,
    remitted boolean,
    PRIMARY KEY ("index", shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_tracking_history (
    "index" text,
    shipment_id text,
    created_date timestamp,
    event_date timestamp,
    "status" text,
    summary text,
    PRIMARY KEY ("index", shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment (
    id text,
    archived boolean,
    bill_to_address text,
    bill_to_address_2 text,
    bill_to_city text,
    bill_to_company text,
    bill_to_contact_email text,
    bill_to_contact_name text,
    bill_to_contact_phone text,
    bill_to_country text,
    bill_to_postal_code text,
    bill_to_state text,
    bol_num text,
    booked_by text,
    created_date timestamp,
    destination_address text,
    destination_address_2 text,
    destination_city text,
    destination_company text,
    destination_contact_email text,
    destination_contact_name text,
    destination_contact_phone text,
    destination_country text,
    destination_dock_hours_end text,
    destination_dock_hours_start text,
    destination_instructions text,
    destination_postal_code text,
    destination_reference_number text,
    destination_ship_type text,
    destination_state text,
    direction text,
    dispatch_bol_status text,
    dispatch_carrier text,
    dispatch_carrier_code text,
    dispatch_carrier_id text,
    dispatch_pickup_num text,
    dispatch_pro_num text,
    dispatch_schedule_pickup boolean,
    dispatch_tracking_num text,
    invoice_amount double precision,
    invoice_created_date timestamp,
    invoice_disputed_amount double precision,
    invoice_number text,
    origin_address text,
    origin_address_2 text,
    origin_city text,
    origin_company text,
    origin_contact_email text,
    origin_contact_name text,
    origin_contact_phone text,
    origin_country text,
    origin_dock_hours_end text,
    origin_dock_hours_start text,
    origin_instructions text,
    origin_postal_code text,
    origin_reference_number text,
    origin_ship_type text,
    origin_state text,
    payment_terms text,
    pickup_date timestamp,
    quoted_by text,
    rate_carrier text,
    rate_carrier_code text,
    rate_carrier_id text,
    rate_created_date timestamp,
    rate_days_plus boolean,
    rate_guaranteed boolean,
    rate_interline boolean,
    rate_mode text,
    rate_payment_terms text,
    rate_provider text,
    rate_provider_code text,
    rate_quote_num text,
    rate_service_description text,
    rate_service_option text,
    rate_service_type text,
    rate_total double precision,
    rate_transit_days bigint,
    "status" text,
    tracking_delivery_date_actual timestamp,
    tracking_delivery_date_estimate timestamp,
    tracking_last_updated_date timestamp,
    tracking_pickup_date_actual timestamp,
    tracking_status text,
    tracking_summary text,
    PRIMARY KEY (id)
);
