CREATE TABLE payment (
    id text,
    account_id text,
    client_id text,
    credit_id text,
    invoice_id text,
    amount text,
    amount_currecy_code text,
    bulk_payment_id text,
    "date" text,
    from_credit text,
    gateway text,
    note text,
    order_id text,
    overpayment_id text,
    send_client_notification text,
    "type" text,
    updated text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES user_business(account_id),
    FOREIGN KEY (client_id) REFERENCES client(id),
    FOREIGN KEY (credit_id) REFERENCES credit(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE credit (
    id text,
    account_id text,
    client_id text,
    amount text,
    city text,
    code text,
    country text,
    create_date text,
    credit_number text,
    credit_type text,
    currency_code text,
    current_organization text,
    description text,
    display_status text,
    dispute_status text,
    ext_archive text,
    first_name text,
    languages text,
    last_name text,
    last_order_status text,
    organization text,
    paid_amount text,
    paid_currency_code text,
    payment_status text,
    payment_type text,
    province text,
    sent_id text,
    "status" text,
    street text,
    street_2 text,
    template text,
    term text,
    vat_name text,
    vat_number text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES user_business(account_id),
    FOREIGN KEY (client_id) REFERENCES client(id)
);

CREATE TABLE project_service (
    project_id text,
    service_id text,
    PRIMARY KEY (project_id, service_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (service_id) REFERENCES service(id)
);

CREATE TABLE project_group_member (
    id text,
    project_id text,
    identity_id text,
    active text,
    comapny text,
    email text,
    first_name text,
    last_name text,
    "role" text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (identity_id) REFERENCES users(id)
);

CREATE TABLE project (
    id text,
    client_id text,
    active text,
    billed_amount text,
    billed_status text,
    billing_method text,
    budget text,
    business_id text,
    complete text,
    created_at text,
    description text,
    due_date text,
    expense_markup text,
    fixed_price text,
    group_id text,
    group_pending_invitation jsonb,
    internal text,
    logged_duration text,
    project_manager_id text,
    project_type text,
    rate text,
    retainer_id text,
    sample text,
    service_estimate_type text,
    title text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES client(id)
);

CREATE TABLE tax (
    id text,
    account_id text,
    amount text,
    compound text,
    "name" text,
    number text,
    updated text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES user_business(account_id)
);

CREATE TABLE invoice (
    id text,
    account_id text,
    client_id text,
    estimate_id text,
    project_id jsonb,
    address text,
    allowed_gateway jsonb,
    allowed_gateway_id jsonb,
    attachment jsonb,
    audit_log jsonb,
    auto_bill text,
    autobill_status text,
    basecamp_id text,
    city text,
    client_audit jsonb,
    code text,
    "comment" jsonb,
    contact jsonb,
    country text,
    create_date text,
    created_at text,
    currency_code text,
    current_organization text,
    date_paid text,
    deposit_amount text,
    deposit_amount_currency_code text,
    deposit_percentage text,
    deposit_status text,
    description text,
    direct_link jsonb,
    discount_description text,
    discount_total_amount text,
    discount_total_currency_code text,
    discount_value text,
    display_status text,
    dispute_status text,
    due_date text,
    due_offset_day text,
    email_recipient jsonb,
    first_name text,
    fulfillment_date text,
    generation_date text,
    gmail text,
    invoice_number text,
    languages text,
    last_name text,
    last_order_status text,
    late_reminder jsonb,
    line jsonb,
    net_paid_amount text,
    net_paid_amount_currency_code text,
    note text,
    organization text,
    outstanding_amount text,
    outstanding_currency_code text,
    owner_id text,
    paid_amount text,
    paid_code text,
    parent text,
    payment_detail text,
    payment_schedule jsonb,
    payment_status text,
    po_number text,
    project_total_amount jsonb,
    province text,
    sent_id text,
    show_attachment text,
    "status" text,
    store_client_preference text,
    street text,
    street_2 text,
    support_id jsonb,
    term text,
    total_amount text,
    updated timestamp,
    use_default_presentation text,
    uuid text,
    v_3_status text,
    vat_name text,
    vat_number text,
    version text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES user_business(account_id),
    FOREIGN KEY (client_id) REFERENCES client(id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE client (
    id text,
    account_id text,
    allow_email_include_pdf text,
    billing_city text,
    billing_code text,
    billing_country text,
    billing_province text,
    billing_street text,
    billing_street_2 text,
    bus_phone text,
    company_industry text,
    company_size text,
    contact jsonb,
    credit_balance jsonb,
    currency_code text,
    direct_link_token text,
    draft_balance jsonb,
    email text,
    exceeds_client_limit text,
    fax text,
    first_name text,
    grand_total_balance jsonb,
    has_retainer text,
    home_phone text,
    languages text,
    last_activity text,
    last_login text,
    last_name text,
    late_reminder jsonb,
    mobile_phone text,
    note text,
    number_login text,
    organization text,
    outstanding_balance jsonb,
    overdue_balance jsonb,
    preferred_contact jsonb,
    preferred_gateway jsonb,
    prefers_email text,
    prefers_gmail text,
    recent_contact jsonb,
    retainer_id text,
    "role" text,
    shipping_city text,
    shipping_code text,
    shipping_country text,
    shipping_province text,
    shipping_street text,
    shipping_street_2 text,
    signup_date text,
    subdomain text,
    updated text,
    username text,
    uuid text,
    vat_name text,
    vat_number text,
    visibility_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES user_business(account_id)
);

CREATE TABLE time_entry (
    id text,
    client_id text,
    identity_id text,
    project_id text,
    service_id text,
    active text,
    billable text,
    billed text,
    business_id text,
    created_at timestamp,
    duration text,
    internal text,
    is_logged text,
    local_started_at text,
    local_timezone text,
    note text,
    pending_client text,
    pending_project text,
    pending_task text,
    retainer_id text,
    started_at text,
    task_id text,
    timer_id text,
    timer_is_running text,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES client(id),
    FOREIGN KEY (identity_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (service_id) REFERENCES service(id)
);

CREATE TABLE expense (
    id text,
    account_id text,
    category_id text,
    client_id text,
    invoice_id text,
    project_id text,
    account_name text,
    amount text,
    amount_currency_code text,
    background_job_id text,
    bank_name text,
    bill_match jsonb,
    billable text,
    "date" text,
    expense_account_id text,
    ext_account_id text,
    ext_invoice_id text,
    ext_system_id text,
    from_bulk_import text,
    has_receipt text,
    include_receipt text,
    is_cog text,
    is_duplicate text,
    markup_percent text,
    note text,
    potential_bill_payment text,
    profile_id text,
    staff_id text,
    "status" text,
    tax_amount_1 text,
    tax_amount_1_currency_code text,
    tax_amount_2 text,
    tax_name_1 text,
    tax_name_2 text,
    tax_percent_1 text,
    tax_percent_2 text,
    transaction_id text,
    updated timestamp,
    vendor text,
    version text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES user_business(account_id),
    FOREIGN KEY (category_id) REFERENCES expense_category(id),
    FOREIGN KEY (client_id) REFERENCES client(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE expense_category (
    id text,
    parent_id text,
    account_id text,
    category text,
    created_at text,
    is_cog text,
    is_editable text,
    transaction_posted text,
    updated_at text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_id) REFERENCES expense_category(id)
);

CREATE TABLE service (
    id text,
    business_id text,
    billable text,
    "name" text,
    project_default text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES user_business(business_id)
);

CREATE TABLE other_income_tax (
    _fivetran_id text,
    other_income_id text,
    amount text,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (other_income_id) REFERENCES other_income(id)
);

CREATE TABLE other_income (
    id text,
    client_id text,
    account_id text,
    amount text,
    category_name text,
    created_at text,
    currency_code text,
    "date" text,
    net_paid_amount text,
    net_paid_amount_code text,
    note text,
    payment_type text,
    "source" text,
    source_id text,
    updated_at text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (client_id) REFERENCES client(id)
);

CREATE TABLE business_client (
    id text,
    membership_id text,
    user_id text,
    client_account text,
    client_business_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (membership_id) REFERENCES user_business(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_business (
    id text,
    users_id text,
    account_id text,
    active text,
    address_city text,
    address_country text,
    address_id text,
    address_postal_code text,
    address_province text,
    address_street text,
    address_street_2 text,
    advanced_accounting_enabled text,
    business_id text,
    date_format text,
    fasttrack_token text,
    first_day_of_week text,
    "name" text,
    phone_number text,
    phone_number_id text,
    "role" text,
    "status" text,
    timezone text,
    unacknowledged_change text,
    uuid text,
    PRIMARY KEY (id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    confirmed_at text,
    created_at text,
    email text,
    first_name text,
    identity_origin text,
    identity_uuid text,
    languages text,
    last_name text,
    profession_company text,
    profession_designation text,
    profession_id text,
    profession_title text,
    setup_complete text,
    timezone text,
    unconfirmed_email text,
    PRIMARY KEY (id)
);

CREATE TABLE estimate (
    id text,
    account_id text,
    client_id text,
    accepted text,
    address text,
    amount_currency_code text,
    city text,
    code text,
    country text,
    create_date text,
    created_at text,
    current_organization text,
    description text,
    discount_total_amount text,
    discount_total_currency_code text,
    discount_value text,
    display_status text,
    estimate_number text,
    first_name text,
    invoiced text,
    languages text,
    last_name text,
    modern_project_id text,
    note text,
    organization text,
    owner_id text,
    po_number text,
    province text,
    require_client_signature text,
    rich_proposal text,
    sent_id text,
    "status" text,
    street text,
    street_2 text,
    term text,
    total_amount text,
    ui_status text,
    updated text,
    vat_name text,
    vat_number text,
    vis_state text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES user_business(account_id),
    FOREIGN KEY (client_id) REFERENCES client(id)
);
