CREATE TABLE product_user (
    user_id text,
    account_id text,
    contact_user_id text,
    email text,
    first_name text,
    is_active boolean,
    last_name text,
    lead_source text,
    mailing_city text,
    mailing_country text,
    mailing_postal_code text,
    mailing_state text,
    mailing_street text,
    phone text,
    product_join_date timestamp,
    "role" text,
    salutation text,
    title text,
    -- value_* (dynamic column),
    PRIMARY KEY (user_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE invoice_statement_line_item (
    _fivetran_id text,
    invoice_statement_invoice_id text,
    amount integer,
    description text,
    is_recurring boolean,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (invoice_statement_invoice_id) REFERENCES invoice_statement(invoice_id)
);

CREATE TABLE invoice_statement (
    invoice_id text,
    account_id text,
    is_failed boolean,
    non_recurring integer,
    paid_date timestamp,
    start_date timestamp,
    PRIMARY KEY (invoice_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE subscription_record (
    _fivetran_id text,
    subscription_id text,
    cycle_length integer,
    cycle_unit text,
    end_date timestamp,
    expiration_date timestamp,
    is_end boolean,
    is_renewal boolean,
    plan_code text,
    start_date timestamp,
    total_revenue integer,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(subscription_id)
);

CREATE TABLE subscription (
    subscription_id text,
    account_id text,
    PRIMARY KEY (subscription_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE interaction (
    id integer,
    account_id text,
    user_id text,
    create_time timestamp,
    crm_account_id text,
    details text,
    external_id text,
    is_html boolean,
    modify_time timestamp,
    rep_email text,
    rep_first_name text,
    rep_last_name text,
    "source" text,
    subject text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(account_id),
    FOREIGN KEY (user_id) REFERENCES product_user(contact_user_id)
);

CREATE TABLE subscription_history (
    subscription_id text,
    account_id text,
    subscription_subscription_id text,
    cycle_length integer,
    cycle_unit text,
    end_date timestamp,
    expiration_date timestamp,
    plan_code text,
    revenue integer,
    start_date timestamp,
    units integer,
    PRIMARY KEY (subscription_id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id),
    FOREIGN KEY (subscription_subscription_id) REFERENCES subscription(subscription_id)
);

CREATE TABLE account (
    account_id text,
    billing_account_id text,
    billing_city text,
    billing_country text,
    billing_postal_code text,
    billing_state text,
    billing_street text,
    churn_likelihood text,
    churn_reason_category text,
    churn_reason_item text,
    churn_reason_subcategory text,
    crm_account_id text,
    csm_score integer,
    current_health_score integer,
    current_mrr integer,
    current_nps_score text,
    current_stage text,
    description text,
    employees integer,
    hierarchy_label text,
    hierarchy_level integer,
    id integer,
    inactive_reason text,
    inactive_time text,
    industry text,
    is_active boolean,
    is_churned boolean,
    join_date timestamp,
    latest_status_date text,
    latest_status_details text,
    latest_status_title text,
    modify_time timestamp,
    "name" text,
    natero_url text,
    parent_account_id text,
    phone text,
    product text,
    projected_churn_date text,
    projected_churn_mrr text,
    region text,
    renewal_date text,
    sales_rep_email text,
    sales_rep_name text,
    "source" text,
    support_account_id text,
    tier text,
    "type" text,
    website text,
    PRIMARY KEY (account_id)
);

CREATE TABLE goal_task (
    task_id integer,
    goal_goal_id integer,
    completion_date timestamp,
    create_date timestamp,
    due_date timestamp,
    modify_time timestamp,
    owner_email text,
    start_date timestamp,
    "status" text,
    target_days_due integer,
    task_name text,
    PRIMARY KEY (task_id),
    FOREIGN KEY (goal_goal_id) REFERENCES goal(goal_id)
);

CREATE TABLE goal (
    goal_id integer,
    account_id text,
    category text,
    completion_date timestamp,
    create_date timestamp,
    due_date timestamp,
    goal_name text,
    goal_template_id text,
    is_measured boolean,
    modify_time timestamp,
    owner_email text,
    priority text,
    start_date timestamp,
    "status" text,
    target_date timestamp,
    target_days_due integer,
    tasks_completed integer,
    tasks_total integer,
    was_auto_deployed text,
    PRIMARY KEY (goal_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE deal (
    id integer,
    account_id text,
    amount integer,
    close_time timestamp,
    create_time timestamp,
    creator_email text,
    creator_name text,
    description text,
    expected_close_time timestamp,
    external_id text,
    external_sync_time timestamp,
    "name" text,
    owner_email text,
    owner_name text,
    pipeline text,
    product text,
    "source" text,
    source_created text,
    stage text,
    url text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE support_ticket (
    ticket_id text,
    account_id text,
    assignee_email text,
    assignee_id text,
    close_time timestamp,
    create_time timestamp,
    csat_label text,
    csat_value text,
    description text,
    due_by_time text,
    fr_due_by_time text,
    is_spam boolean,
    last_update_time timestamp,
    modify_time timestamp,
    priority text,
    "source" text,
    "state" text,
    subject text,
    tags text,
    "type" text,
    url text,
    PRIMARY KEY (ticket_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE document (
    account_id text,
    description text,
    "name" text,
    url text,
    PRIMARY KEY (account_id),
    FOREIGN KEY (account_id) REFERENCES account(account_id)
);

CREATE TABLE account_contact (
    id integer,
    account_id text,
    user_id text,
    email text,
    email_opt_out boolean,
    first_name text,
    is_active boolean,
    is_primary boolean,
    last_name text,
    lead_source text,
    mailing_city text,
    mailing_country text,
    mailing_postal_code text,
    mailing_state text,
    mailing_street text,
    mobile_phone text,
    modify_time timestamp,
    phone text,
    "role" text,
    salutation text,
    "source" text,
    title text,
    -- value_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(account_id),
    FOREIGN KEY (user_id) REFERENCES product_user(user_id)
);
