CREATE TABLE shipment_move (
    move_id text,
    shipment_id text,
    PRIMARY KEY (move_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_package (
    package_id text,
    shipment_id text,
    PRIMARY KEY (package_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_available_carrier_service (
    available_carrier_service_id text,
    shipment_id text,
    PRIMARY KEY (available_carrier_service_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_channel (
    channel_id text,
    shipment_id text,
    PRIMARY KEY (channel_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_inventory_moves (
    inventory_moves_id text,
    shipment_id text,
    PRIMARY KEY (inventory_moves_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_outgoing_moves (
    outgoing_moves_id text,
    shipment_id text,
    PRIMARY KEY (outgoing_moves_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_invoice (
    invoice_id text,
    shipment_id text,
    PRIMARY KEY (invoice_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_metafield (
    id text,
    shipment_id text,
    field_code text,
    field_id text,
    field_type text,
    value_code text,
    value_id text,
    value_type text,
    PRIMARY KEY (id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_root_pacakage (
    root_packages_id text,
    shipment_id text,
    PRIMARY KEY (root_packages_id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_sale (
    sale_id text,
    shipment_id text,
    PRIMARY KEY (sale_id, shipment_id),
    FOREIGN KEY (sale_id) REFERENCES sales_order(id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment (
    id text,
    acknowledged_at text,
    acknowledged_by text,
    acknowledged_by_3_p_l_at text,
    aes_itn text,
    assigned_by text,
    assigned_time jsonb,
    attachments jsonb,
    avg_cycle_time jsonb,
    avg_cycle_time_cache text,
    bin_transfers jsonb,
    carrier text,
    carrier_billing_account text,
    carrier_cost_method text,
    carrier_duties_account text,
    carrier_service text,
    channel_carrier_service_code text,
    channel_logo_url text,
    company text,
    consumable_moves text,
    consumables_cost jsonb,
    consumables_cost_cache jsonb,
    contact_categories jsonb,
    contents_explanation text,
    contents_type text,
    cost text,
    cost_currency text,
    cost_currency_digits text,
    cost_invoice_line text,
    create_date jsonb,
    create_return_label text,
    create_uid text,
    customer text,
    customer_location text,
    customs_items jsonb,
    default_box_type text,
    delivery_address text,
    delivery_mode text,
    done_by text,
    duties_tax_id text,
    duties_tax_id_type text,
    eel_pfc text,
    effective_date jsonb,
    eori_number text,
    fedex_saturday_delivery text,
    full_delivery_address text,
    gift_message text,
    has_gift_message text,
    hold_reason text,
    importer_of_record_address text,
    importer_of_record_contact text,
    importer_of_record_tax_identifiers jsonb,
    incoterm text,
    insurance_amount text,
    is_international_shipping text,
    is_shippo text,
    last_modification jsonb,
    license_plates jsonb,
    messages jsonb,
    metadata text,
    non_delivery_option text,
    number text,
    on_hold text,
    on_hold_until text,
    order_confirmation_time jsonb,
    order_numbers text,
    order_references text,
    origins text,
    override_sscc text,
    packed_at jsonb,
    packed_by text,
    packer text,
    payment_status text,
    payment_transactions jsonb,
    picked_at jsonb,
    picked_date text,
    picker text,
    picking_started_at text,
    picking_status text,
    picking_zones jsonb,
    planned_date jsonb,
    planned_datetime jsonb,
    planned_time text,
    priority text,
    private_notes jsonb,
    productions text,
    public_notes jsonb,
    rec_blurb_description text,
    rec_blurb_fields jsonb,
    rec_blurb_subtitle jsonb,
    rec_blurb_thumbnail_url text,
    rec_blurb_title text,
    rec_name text,
    reference text,
    request_confirmation text,
    requested_delivery_date text,
    requested_shipping_service text,
    require_customs text,
    sale_date jsonb,
    sent_to_3_p_l_at text,
    shipped_at jsonb,
    shipper text,
    shipping_batch text,
    shipping_instructions text,
    shipping_label_date text,
    shipping_label_printed text,
    shipping_manifest text,
    sscc_code text,
    "state" text,
    subtitle jsonb,
    tasks jsonb,
    tax_id text,
    title text,
    total_amount_ccy jsonb,
    total_cost jsonb,
    total_customs_value text,
    total_item_cost_ccy jsonb,
    total_quantity text,
    tpl text,
    tpl_reference text,
    tpl_status text,
    tracking_export_status text,
    tracking_number text,
    trading_partner text,
    tsv text,
    ups_saturday_delivery text,
    warehouse text,
    warehouse_output text,
    warehouse_storage text,
    weight text,
    weight_digits text,
    weight_uom text,
    weight_uom_symbol text,
    workflow text,
    workstation text,
    write_date jsonb,
    write_uid text,
    PRIMARY KEY (id)
);

CREATE TABLE shipment_return_move (
    move_id text,
    shipment_return_id text,
    PRIMARY KEY (move_id, shipment_return_id),
    FOREIGN KEY (shipment_return_id) REFERENCES shipment_return(id)
);

CREATE TABLE shipment_return (
    id text,
    assigned_by text,
    attachments jsonb,
    company text,
    create_date jsonb,
    create_uid text,
    delivery_address text,
    done_by text,
    effective_date jsonb,
    from_location text,
    license_plates jsonb,
    messages jsonb,
    metadata text,
    metafields jsonb,
    number text,
    origins text,
    planned_date text,
    private_notes jsonb,
    public_notes jsonb,
    rec_blurb_description text,
    rec_blurb_field jsonb,
    rec_blurb_subtitle jsonb,
    rec_blurb_thumbnail_url text,
    rec_blurb_title text,
    rec_name text,
    reference text,
    "state" text,
    supplier text,
    to_location text,
    write_date jsonb,
    write_uid text,
    PRIMARY KEY (id)
);

CREATE TABLE sales_order_message_button (
    id text,
    sales_order_id text,
    sales_order_message_index text,
    "action" text,
    active text,
    context text,
    create_uid text,
    email text,
    groups jsonb,
    icon text,
    icon_rec_name text,
    keywords jsonb,
    model text,
    "name" text,
    rec_name text,
    string text,
    "type" text,
    usage text,
    window text,
    wiz_name text,
    write_uid text,
    PRIMARY KEY (id, sales_order_id, sales_order_message_index),
    FOREIGN KEY (sales_order_id) REFERENCES sales_order_message(sales_order_id),
    FOREIGN KEY (sales_order_message_index) REFERENCES sales_order_message("index")
);

CREATE TABLE sales_order_message (
    "index" text,
    sales_order_id text,
    description text,
    title text,
    "type" text,
    PRIMARY KEY ("index", sales_order_id),
    FOREIGN KEY (sales_order_id) REFERENCES sales_order(id)
);

CREATE TABLE sales_order_line (
    line_id text,
    sales_order_id text,
    PRIMARY KEY (line_id, sales_order_id),
    FOREIGN KEY (sales_order_id) REFERENCES sales_order(id)
);

CREATE TABLE sales_order_payment (
    payment_id text,
    sales_order_id text,
    PRIMARY KEY (payment_id, sales_order_id),
    FOREIGN KEY (sales_order_id) REFERENCES sales_order(id)
);

CREATE TABLE sales_order (
    id text,
    access_token text,
    account_class_allocation_template text,
    acknowledged_at text,
    acknowledgement_status text,
    amount_invoiced jsonb,
    attachments jsonb,
    available_carrier_services jsonb,
    bundle_explosion_method text,
    carrier text,
    carrier_cost_method text,
    carrier_service text,
    channel text,
    channel_identifier text,
    channel_segment text,
    channel_tax_amount text,
    channel_type text,
    cogs_account text,
    "comment" text,
    company text,
    company_currency_digits text,
    confirmation_time text,
    cost_center_allocation_template text,
    create_date jsonb,
    create_uid text,
    credit jsonb,
    currency text,
    currency_digits text,
    currency_symbol text,
    description text,
    drop_location text,
    drop_shipments jsonb,
    dropship_order_reference text,
    edi_attributes text,
    end_customer_order_reference text,
    error_message text,
    exceptions jsonb,
    exchange_rate text,
    external_url text,
    gateway_transactions jsonb,
    gift_card_method text,
    gift_message text,
    guest_access_code text,
    has_channel_exception text,
    has_line_with_discount text,
    has_return text,
    integration text,
    invoice_address text,
    invoice_method text,
    invoice_state text,
    invoices jsonb,
    invoices_ignored jsonb,
    invoices_recreated jsonb,
    is_cart text,
    is_international_shipping text,
    is_recently_active text,
    last_modification jsonb,
    manual_account_class text,
    manual_cost_center text,
    metafields jsonb,
    moves jsonb,
    number text,
    origin text,
    party text,
    party_lang text,
    payment_authorize_on text,
    payment_authorized jsonb,
    payment_available jsonb,
    payment_capture_on text,
    payment_captured jsonb,
    payment_collected jsonb,
    payment_processing_state text,
    payment_term text,
    payment_total jsonb,
    price_list text,
    priority text,
    private_notes jsonb,
    promotion text,
    public_notes jsonb,
    rec_blurb_description text,
    rec_blurb_field jsonb,
    rec_blurb_subtitle jsonb,
    rec_blurb_thumbnail_url text,
    rec_blurb_title text,
    reference text,
    requested_shipping_service text,
    sale_date text,
    sales_person text,
    shipment_address text,
    shipment_cost_markup text,
    shipment_cost_method text,
    shipment_method text,
    shipment_party text,
    shipment_returns jsonb,
    shipment_state text,
    shipments jsonb,
    shipping_account text,
    shipping_cost_computation text,
    shipping_end_date text,
    shipping_instructions text,
    shipping_start_date text,
    "state" text,
    tax_amount_cache text,
    tax_amount_cpny_ccy_cache text,
    tax_identifiers jsonb,
    taxability_status text,
    total_amount_cache text,
    total_amount_cpny_ccy_cache text,
    total_quantity text,
    total_quantity_uom text,
    trading_partner text,
    tsv text,
    untaxed_amount_cache text,
    untaxed_amount_cpny_ccy_cache text,
    warehouse text,
    weight text,
    weight_digits text,
    weight_uom text,
    weight_uom_symbol text,
    write_date jsonb,
    write_uid text,
    PRIMARY KEY (id)
);
