CREATE TABLE survey_merge_key (
    "index" text,
    survey_id text,
    merge_key text,
    PRIMARY KEY ("index", survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE survey_enabled_language (
    "index" text,
    survey_id text,
    languages text,
    PRIMARY KEY ("index", survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE users (
    id text,
    card_expiration_date text,
    default_tab text,
    email text,
    has_invalid_card text,
    is_team_owner text,
    "name" text,
    permission text,
    "source" text,
    "status" text,
    team_id text,
    time_zone text,
    uuid text,
    PRIMARY KEY (id)
);

CREATE TABLE theme (
    id text,
    survey_id text,
    answer_color text,
    background_color text,
    background_display text,
    background_image_brightness text,
    background_image_bucket_type text,
    background_image_id text,
    background_image_uploaded text,
    background_image_url text,
    background_image_url_256 text,
    background_image_url_512 text,
    background_image_url_768 text,
    background_type text,
    button_color text,
    category text,
    font text,
    "name" text,
    question_color text,
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE component_choice_stats (
    choice_id text,
    component_id text,
    survey_id text,
    answer_count text,
    PRIMARY KEY (choice_id, component_id, survey_id),
    FOREIGN KEY (choice_id) REFERENCES choice(id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (survey_id) REFERENCES component(survey_id)
);

CREATE TABLE component_map_field (
    "index" text,
    component_id text,
    survey_id text,
    "type" text,
    PRIMARY KEY ("index", component_id, survey_id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (survey_id) REFERENCES component(survey_id)
);

CREATE TABLE translation (
    id text,
    "index" text,
    choice_id text,
    component_id text,
    grid_item_id text,
    label_path text,
    languages text,
    text text,
    PRIMARY KEY (id, "index"),
    FOREIGN KEY (choice_id) REFERENCES choice(id),
    FOREIGN KEY (component_id) REFERENCES component(id)
);

CREATE TABLE choice (
    id text,
    component_id text,
    survey_id text,
    cm_list_key text,
    comment_enabled text,
    custom_dropdown_list text,
    form_field_type text,
    has_matching_rule_criteria text,
    is_other text,
    list_type text,
    mappable_field_type jsonb,
    media_object text,
    pardot_value text,
    "position" text,
    required text,
    should_hide_merge_field text,
    text text,
    "value" text,
    PRIMARY KEY (id, component_id, survey_id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (survey_id) REFERENCES component(survey_id)
);

CREATE TABLE component (
    id text,
    survey_id text,
    alignment text,
    answers_count text,
    button_text text,
    button_url text,
    can_hide_merge_field text,
    comment_enabled text,
    comment_header text,
    commentable text,
    description text,
    embedded_answer_key text,
    grid_item jsonb,
    has_grid_item text,
    include_not_applicable text,
    is_email_embeddable text,
    is_embedded_answerable text,
    is_embedded_auto text,
    is_question text,
    lhs_condition_id jsonb,
    markup text,
    max_answer text,
    maximum_label text,
    media_object text,
    min_answer text,
    minimum_label text,
    multiline text,
    multiple_answer text,
    number text,
    ordered_rule jsonb,
    randomize text,
    randomize_grid_item text,
    required text,
    shape text,
    should_hide_merge_field text,
    show_description text,
    show_media text,
    show_top_media text,
    start_at text,
    stats_average text,
    target_action_id jsonb,
    title text,
    top_media_object text,
    "type" text,
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE campaign (
    id text,
    survey_id text,
    autoclose_timing_second text,
    custom_url jsonb,
    ended_at text,
    expiry_period text,
    icon text,
    icon_color text,
    label text,
    logo_media_object text,
    percent_visitor text,
    placement text,
    scroll_position text,
    show_mobile text,
    show_tab text,
    style text,
    tab_color text,
    timing_second text,
    token text,
    trigger_once text,
    "type" text,
    url jsonb,
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);

CREATE TABLE rule_action (
    id text,
    rule_id text,
    survey_id text,
    component_id text,
    email jsonb,
    email_subject text,
    field_mapping_token text,
    grid_item_id text,
    include_response text,
    parameter text,
    pardot_field_mapping_id text,
    pardot_object_mapping_id text,
    salesforce_field_mapping_id text,
    salesforce_object_mapping_id text,
    slack_conversation_id text,
    slack_message text,
    slack_team_id text,
    "type" text,
    "value" text,
    PRIMARY KEY (id, rule_id, survey_id),
    FOREIGN KEY (rule_id) REFERENCES rule(id),
    FOREIGN KEY (survey_id) REFERENCES rule(survey_id),
    FOREIGN KEY (component_id) REFERENCES component(id)
);

CREATE TABLE rule (
    id text,
    survey_id text,
    component_id text,
    active text,
    "condition" jsonb,
    condition_operator text,
    created_at text,
    label text,
    purpose text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id),
    FOREIGN KEY (component_id) REFERENCES component(id)
);

CREATE TABLE survey (
    id text,
    user_id text,
    answer_color_override text,
    automagic_salesforce_sync text,
    background_color_override text,
    background_display_override text,
    background_image_brightness text,
    background_image_override_bucket_type text,
    background_image_override_id text,
    background_image_override_uploaded text,
    background_image_override_url text,
    background_image_override_url_256 text,
    background_image_override_url_512 text,
    background_image_override_url_768 text,
    background_type_override text,
    button_color_override text,
    completed_response_count text,
    created_at text,
    custom_domain text,
    defined_merge_key jsonb,
    discard_invalid_value text,
    draft_differ text,
    draft_id text,
    draft_pardot_credential_id text,
    draft_salesforce_credential_id text,
    embedded_answer_key_error jsonb,
    financial_data_field text,
    financial_data_path jsonb,
    folder_id text,
    font_override text,
    languages text,
    last_published text,
    limited_response_count text,
    locale text,
    logo_media_object text,
    merge_field_encryption text,
    multi_language text,
    "name" text,
    notification_level text,
    only_defined_merge_key text,
    pardot_credential text,
    pardot_object_mapping jsonb,
    public_setting_host text,
    public_setting_protocol text,
    publish_to_id text,
    publishing text,
    push_incomplete_response_status text,
    question_color_override text,
    question_count text,
    response_graph_token text,
    salesforce_activity_mapping jsonb,
    salesforce_credential text,
    salesforce_mapping_failure_strategy_email_notifications_enabled text,
    salesforce_mapping_failure_strategy_email_summaries_enabled text,
    salesforce_mapping_failure_strategy_email_summaries_sent_count text,
    salesforce_mapping_failure_strategy_email_summary_scheduled_for text,
    salesforce_mapping_failure_strategy_id text,
    salesforce_object_mapping jsonb,
    send_incomplete_response text,
    server_held_change_count text,
    share jsonb,
    share_token text,
    show_incomplete_response text,
    started_response_count text,
    store_ipdata text,
    survey_share jsonb,
    survey_url text,
    updated_at text,
    use_rich_text text,
    walkthrough text,
    white_labeled text,
    zendesk_connection_vox_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE answer_choice (
    answer_id text,
    choice_id text,
    response_id text,
    PRIMARY KEY (answer_id, choice_id, response_id),
    FOREIGN KEY (answer_id) REFERENCES answer(id),
    FOREIGN KEY (choice_id) REFERENCES choice(id),
    FOREIGN KEY (response_id) REFERENCES answer(response_id)
);

CREATE TABLE answer (
    id text,
    response_id text,
    component_id text,
    "comment" text,
    created_at text,
    embedded text,
    grid_item text,
    not_applicable text,
    number text,
    scale text,
    text text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, response_id),
    FOREIGN KEY (response_id) REFERENCES response(id),
    FOREIGN KEY (component_id) REFERENCES component(id)
);

CREATE TABLE response (
    id text,
    survey_id text,
    browser text,
    completed_at text,
    country_code_with_emoji text,
    created_at text,
    languages text,
    limited text,
    platform text,
    "status" text,
    token text,
    updated_at text,
    -- merge_map_* (dynamic column),
    PRIMARY KEY (id, survey_id),
    FOREIGN KEY (survey_id) REFERENCES survey(id)
);
