CREATE TABLE project_milestone (
    id text,
    project_id text,
    created_at timestamp,
    description text,
    due_date text,
    expired boolean,
    iid bigint,
    start_date text,
    "state" text,
    title text,
    updated_at timestamp,
    web_url text,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_member (
    id text,
    project_id text,
    created_by_id text,
    access_level bigint,
    avatar_url text,
    created_at timestamp,
    expires_at text,
    group_saml_identity_extern_uid text,
    group_saml_identity_provider text,
    group_saml_identity_saml_provider_id text,
    membership_state text,
    "name" text,
    "state" text,
    username text,
    web_url text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (created_by_id) REFERENCES project_user(id)
);

CREATE TABLE project_topic (
    topic text,
    project_id text,
    PRIMARY KEY (topic, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_compliance_framework (
    compliance_framework text,
    project_id text,
    PRIMARY KEY (compliance_framework, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_shared_with_group (
    _fivetran_id text,
    project_id text,
    compliance_frameworks text,
    group_access_level text,
    group_full_path text,
    group_name text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project (
    id text,
    namespace_id text,
    _links_cluster_agents text,
    _links_events text,
    _links_issues text,
    _links_labels text,
    _links_members text,
    _links_merge_requests text,
    _links_repo_branches text,
    _links_self text,
    allow_merge_on_skipped_pipeline boolean,
    analytics_access_level text,
    archived text,
    auto_cancel_pending_pipelines text,
    auto_devops_deploy_strategy text,
    auto_devops_enabled text,
    autoclose_referenced_issues boolean,
    avatar_url text,
    build_coverage_regex text,
    build_timeout text,
    builds_access_level text,
    can_create_merge_request_in boolean,
    ci_config_path text,
    ci_default_git_depth text,
    ci_forward_deployment_enabled boolean,
    ci_job_token_scope_enabled boolean,
    ci_separated_caches boolean,
    container_expiration_policy_cadence text,
    container_expiration_policy_enabled text,
    container_expiration_policy_keep_n text,
    container_expiration_policy_name_regex text,
    container_expiration_policy_name_regex_keep text,
    container_expiration_policy_next_run_at text,
    container_expiration_policy_older_than text,
    container_registry_access_level text,
    container_registry_image_prefix text,
    created_at timestamp,
    creator_id text,
    default_branch text,
    description text,
    emails_disabled text,
    empty_repo text,
    enforce_auth_checks_on_uploads boolean,
    external_authorization_classification_label text,
    forking_access_level text,
    forks_count text,
    http_url_to_repo text,
    import_status text,
    import_type text,
    import_url text,
    issues_access_level text,
    issues_enabled boolean,
    jobs_enabled boolean,
    keep_latest_artifact boolean,
    last_activity_at timestamp,
    lfs_enabled boolean,
    marked_for_deletion_on text,
    merge_commit_template text,
    merge_method text,
    merge_requests_access_level text,
    merge_requests_enabled boolean,
    "name" text,
    name_with_namespace text,
    namespace_avatar_url text,
    namespace_full_path text,
    namespace_kind text,
    namespace_name text,
    namespace_parent_id text,
    namespace_path text,
    namespace_web_url text,
    only_allow_merge_if_all_discussions_are_resolved boolean,
    only_allow_merge_if_pipeline_succeeds boolean,
    open_issues_count text,
    operations_access_level text,
    owner_created_at timestamp,
    owner_id text,
    owner_name text,
    packages_enabled text,
    pages_access_level text,
    "path" text,
    path_with_namespace text,
    permissions_group_access_access_level text,
    permissions_group_access_notification_level text,
    permissions_project_access_access_level text,
    permissions_project_access_notification_level text,
    printing_merge_request_link_enabled boolean,
    public_jobs boolean,
    readme_url text,
    remove_source_branch_after_merge boolean,
    repository_access_level text,
    request_access_enabled boolean,
    requirements_access_level text,
    requirements_enabled boolean,
    resolve_outdated_diff_discussions text,
    restrict_user_defined_variables boolean,
    runner_token_expiration_interval text,
    runners_token text,
    security_and_compliance_access_level text,
    security_and_compliance_enabled boolean,
    service_desk_address text,
    service_desk_enabled boolean,
    shared_runners_enabled boolean,
    snippets_access_level text,
    snippets_enabled boolean,
    squash_commit_template text,
    squash_option text,
    ssh_url_to_repo text,
    star_count text,
    statistics_commit_count bigint,
    statistics_job_artifacts_size bigint,
    statistics_lfs_objects_size bigint,
    statistics_packages_size bigint,
    statistics_pipeline_artifacts_size bigint,
    statistics_repository_size bigint,
    statistics_snippets_size bigint,
    statistics_storage_size bigint,
    statistics_uploads_size bigint,
    statistics_wiki_size bigint,
    suggestion_commit_message text,
    visibility text,
    web_url text,
    wiki_access_level text,
    wiki_enabled boolean,
    PRIMARY KEY (id),
    FOREIGN KEY (namespace_id) REFERENCES groups(id)
);

CREATE TABLE groups_label (
    id text,
    groups_id text,
    closed_issues_count bigint,
    color text,
    description text,
    description_html text,
    "name" text,
    open_issues_count bigint,
    open_merge_requests_count bigint,
    subscribed boolean,
    text_color text,
    PRIMARY KEY (id, groups_id),
    FOREIGN KEY (groups_id) REFERENCES groups(id)
);

CREATE TABLE project_vulnerability (
    id text,
    author_id text,
    project_id text,
    confidence text,
    created_at timestamp,
    description text,
    dismissed_at text,
    dismissed_by_id text,
    finding_confidence text,
    finding_created_at text,
    finding_id text,
    finding_location_fingerprint text,
    finding_metadata_version text,
    finding_name text,
    finding_primary_identifier_id text,
    finding_project_id text,
    finding_raw_metadata text,
    finding_report_type text,
    finding_scanner_id text,
    finding_severity text,
    finding_updated_at text,
    finding_uuid text,
    finding_vulnerability_id text,
    project_default_branch text,
    report_type text,
    resolved_at text,
    resolved_by_id text,
    resolved_on_default_branch text,
    severity text,
    "state" text,
    title text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES project_user(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_repo_tag_parent_id (
    parent_id text,
    project_repo_tag_fivetran_id text,
    PRIMARY KEY (parent_id, project_repo_tag_fivetran_id),
    FOREIGN KEY (project_repo_tag_fivetran_id) REFERENCES project_repo_tag(_fivetran_id)
);

CREATE TABLE project_repo_tag (
    _fivetran_id text,
    commit_id text,
    project_id text,
    message text,
    "name" text,
    protected text,
    release_description text,
    release_tag_name text,
    target text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (commit_id) REFERENCES project_commit(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_commit_parent_id (
    parent_id text,
    project_commit_id text,
    project_id text,
    PRIMARY KEY (parent_id, project_commit_id, project_id),
    FOREIGN KEY (project_commit_id) REFERENCES project_commit(id),
    FOREIGN KEY (project_id) REFERENCES project_commit(project_id)
);

CREATE TABLE project_commit (
    id text,
    project_id text,
    author_email text,
    author_name text,
    authored_date timestamp,
    committed_date timestamp,
    committer_email text,
    committer_name text,
    created_at timestamp,
    extended_trailers jsonb,
    message text,
    short_id text,
    stats_addition text,
    stats_deletion text,
    stats_total text,
    title text,
    trailers jsonb,
    web_url text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_job_tag_list (
    tag_list text,
    project_job_id text,
    PRIMARY KEY (tag_list, project_job_id),
    FOREIGN KEY (project_job_id) REFERENCES project_job(id)
);

CREATE TABLE project_job_artifact (
    _fivetran_id text,
    project_job_id text,
    file_format text,
    file_type text,
    filename text,
    "size" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (project_job_id) REFERENCES project_job(id)
);

CREATE TABLE project_job (
    id text,
    project_id text,
    commit_id text,
    user_id text,
    allow_failure boolean,
    artifacts_expire_at timestamp,
    artifacts_file_filename text,
    artifacts_file_size text,
    coverage text,
    created_at timestamp,
    duration text,
    failure_reason text,
    finished_at timestamp,
    "name" text,
    pipeline_id text,
    pipeline_project_id text,
    pipeline_ref text,
    pipeline_sha text,
    pipeline_status text,
    queued_duration text,
    ref text,
    runner_active boolean,
    runner_description text,
    runner_id text,
    runner_ip_address text,
    runner_is_shared boolean,
    runner_name text,
    runner_online boolean,
    runner_paused boolean,
    runner_runner_type text,
    runner_status text,
    stage text,
    started_at timestamp,
    "status" text,
    tags boolean,
    web_url text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (commit_id) REFERENCES project_commit(id),
    FOREIGN KEY (user_id) REFERENCES project_user(id)
);

CREATE TABLE groups (
    id text,
    auto_devops_enabled boolean,
    avatar_url text,
    created_at timestamp,
    default_branch_protection bigint,
    description text,
    emails_disabled text,
    file_template_project_id bigint,
    full_name text,
    full_path text,
    ldap_access text,
    ldap_cn text,
    lfs_enabled boolean,
    mentions_disabled text,
    "name" text,
    parent_id text,
    "path" text,
    project_creation_level text,
    request_access_enabled boolean,
    require_two_factor_authentication boolean,
    share_with_group_lock boolean,
    statistics_job_artifacts_size bigint,
    statistics_lfs_objects_size bigint,
    statistics_packages_size bigint,
    statistics_pipeline_artifacts_size bigint,
    statistics_repository_size bigint,
    statistics_snippets_size bigint,
    statistics_storage_size bigint,
    statistics_uploads_size bigint,
    statistics_wiki_size bigint,
    subgroup_creation_level text,
    two_factor_grace_period bigint,
    visibility text,
    web_url text,
    PRIMARY KEY (id)
);

CREATE TABLE project_merge_request_assignee (
    id text,
    project_merge_request_id text,
    avatar_url text,
    "name" text,
    "state" text,
    username text,
    web_url text,
    PRIMARY KEY (id, project_merge_request_id),
    FOREIGN KEY (project_merge_request_id) REFERENCES project_merge_request(id)
);

CREATE TABLE project_merge_request_reviewer (
    id text,
    project_merge_request_id text,
    avatar_url text,
    "name" text,
    "state" text,
    username text,
    web_url text,
    PRIMARY KEY (id, project_merge_request_id),
    FOREIGN KEY (project_merge_request_id) REFERENCES project_merge_request(id)
);

CREATE TABLE project_merge_request_label (
    label text,
    project_merge_request_id text,
    PRIMARY KEY (label, project_merge_request_id),
    FOREIGN KEY (project_merge_request_id) REFERENCES project_merge_request(id)
);

CREATE TABLE project_merge_request (
    id text,
    author_id text,
    milestone_id text,
    project_id text,
    allow_collaboration text,
    allow_maintainer_to_push text,
    assignee_avatar_url text,
    assignee_id text,
    assignee_name text,
    assignee_state text,
    assignee_username text,
    assignee_web_url text,
    blocking_discussions_resolved text,
    closed_at timestamp,
    closed_by text,
    created_at timestamp,
    description text,
    discussion_locked text,
    downvotes text,
    draft text,
    force_remove_source_branch text,
    has_conflicts text,
    iid bigint,
    merge_commit_sha text,
    merge_status text,
    merge_user_avatar_url text,
    merge_user_id text,
    merge_user_name text,
    merge_user_state text,
    merge_user_username text,
    merge_user_web_url text,
    merge_when_pipeline_succeeds text,
    merged_at text,
    merged_by_avatar_url text,
    merged_by_id text,
    merged_by_name text,
    merged_by_state text,
    merged_by_username text,
    merged_by_web_url text,
    references_full text,
    references_relative text,
    references_short text,
    sha text,
    should_remove_source_branch text,
    source_branch text,
    source_project_id text,
    squash text,
    squash_commit_sha text,
    "state" text,
    target_branch text,
    target_project_id text,
    task_completion_status_completed_count text,
    task_completion_status_count text,
    time_stats_human_time_estimate text,
    time_stats_human_total_time_spent text,
    time_stats_time_estimate text,
    time_stats_total_time_spent text,
    title text,
    updated_at timestamp,
    upvotes text,
    user_notes_count text,
    web_url text,
    work_in_progress text,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES project_user(id),
    FOREIGN KEY (milestone_id) REFERENCES project_milestone(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_label (
    id text,
    project_id text,
    color text,
    description text,
    description_html text,
    is_project_label boolean,
    "name" text,
    priority text,
    subscribed boolean,
    text_color text,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE groups_milestone (
    id text,
    group_id text,
    created_at timestamp,
    description text,
    due_date text,
    expired boolean,
    iid bigint,
    start_date text,
    "state" text,
    title text,
    updated_at timestamp,
    web_url text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE project_user_identity (
    extern_uid text,
    project_user_id text,
    provider text,
    PRIMARY KEY (extern_uid, project_user_id),
    FOREIGN KEY (project_user_id) REFERENCES project_user(id)
);

CREATE TABLE project_user (
    id text,
    project_id text,
    avatar_url text,
    bio text,
    can_create_group boolean,
    can_create_project boolean,
    color_scheme_id text,
    confirmed_at timestamp,
    created_at timestamp,
    current_sign_in_at timestamp,
    current_sign_in_ip text,
    email text,
    external boolean,
    is_admin boolean,
    job_title text,
    last_activity_on text,
    last_sign_in_at timestamp,
    last_sign_in_ip text,
    linkedin text,
    location text,
    "name" text,
    namespace_id text,
    note text,
    organization text,
    private_profile boolean,
    projects_limit bigint,
    skype text,
    "state" text,
    theme_id bigint,
    twitter text,
    two_factor_enabled boolean,
    username text,
    web_url text,
    website_url text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_issue_assignee (
    id text,
    project_issue_id text,
    avatar_url text,
    "name" text,
    "state" text,
    username text,
    web_url text,
    PRIMARY KEY (id, project_issue_id),
    FOREIGN KEY (project_issue_id) REFERENCES project_issue(id)
);

CREATE TABLE project_issue_label (
    label text,
    project_issue_id text,
    PRIMARY KEY (label, project_issue_id),
    FOREIGN KEY (project_issue_id) REFERENCES project_issue(id)
);

CREATE TABLE project_issue (
    id text,
    author_id text,
    milestone_id text,
    project_id text,
    _links_award_emoji text,
    _links_notes text,
    _links_project text,
    _links_self text,
    assignee_avatar_url text,
    assignee_id text,
    assignee_name text,
    assignee_state text,
    assignee_username text,
    assignee_web_url text,
    closed_at timestamp,
    closed_by_avatar_url text,
    closed_by_id text,
    closed_by_name text,
    closed_by_state text,
    closed_by_username text,
    closed_by_web_url text,
    confidential text,
    created_at timestamp,
    description text,
    discussion_locked text,
    downvotes text,
    due_date text,
    has_tasks boolean,
    iid bigint,
    issue_type text,
    merge_requests_count text,
    references_full text,
    references_relative text,
    references_short text,
    severity text,
    "state" text,
    task_completion_status_completed_count text,
    task_completion_status_count text,
    task_status text,
    time_stats_human_time_estimate text,
    time_stats_human_total_time_spent text,
    time_stats_time_estimate text,
    time_stats_total_time_spent text,
    title text,
    "type" text,
    updated_at timestamp,
    upvotes text,
    user_notes_count text,
    web_url text,
    weight text,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES project_user(id),
    FOREIGN KEY (milestone_id) REFERENCES project_milestone(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_release_parent_id (
    parent_id text,
    project_release_fivetran_id text,
    PRIMARY KEY (parent_id, project_release_fivetran_id),
    FOREIGN KEY (project_release_fivetran_id) REFERENCES project_release(_fivetran_id)
);

CREATE TABLE project_release_asset_source (
    _fivetran_id text,
    project_release_fivetran_id text,
    format text,
    url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (project_release_fivetran_id) REFERENCES project_release(_fivetran_id)
);

CREATE TABLE project_release_asset_link (
    id text,
    project_release_fivetran_id text,
    external text,
    link_type text,
    "name" text,
    url text,
    PRIMARY KEY (id, project_release_fivetran_id),
    FOREIGN KEY (project_release_fivetran_id) REFERENCES project_release(_fivetran_id)
);

CREATE TABLE project_release_evidence (
    _fivetran_id text,
    project_release_fivetran_id text,
    collected_at text,
    filepath text,
    sha text,
    PRIMARY KEY (_fivetran_id, project_release_fivetran_id),
    FOREIGN KEY (project_release_fivetran_id) REFERENCES project_release(_fivetran_id)
);

CREATE TABLE project_release_milestone (
    id text,
    project_release_fivetran_id text,
    created_at timestamp,
    description text,
    due_date text,
    iid bigint,
    issue_stats_closed text,
    issue_stats_total text,
    project_id text,
    start_date text,
    "state" text,
    title text,
    updated_at timestamp,
    web_url text,
    PRIMARY KEY (id, project_release_fivetran_id),
    FOREIGN KEY (project_release_fivetran_id) REFERENCES project_release(_fivetran_id)
);

CREATE TABLE project_release (
    _fivetran_id text,
    project_id text,
    author_id text,
    commit_id text,
    assets_count text,
    assets_evidence_file_path text,
    commit_path text,
    created_at text,
    description text,
    "name" text,
    released_at timestamp,
    tag_name text,
    tag_path text,
    PRIMARY KEY (_fivetran_id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (author_id) REFERENCES project_user(id),
    FOREIGN KEY (commit_id) REFERENCES project_commit(id)
);

CREATE TABLE epic_issue_label (
    label text,
    epic_issue_id text,
    PRIMARY KEY (label, epic_issue_id),
    FOREIGN KEY (epic_issue_id) REFERENCES epic_issue(id)
);

CREATE TABLE epic_issue (
    id text,
    author_id text,
    group_id text,
    _links_epic_issues text,
    _links_group text,
    _links_parent text,
    _links_self text,
    closed_at timestamp,
    color text,
    confidential text,
    created_at timestamp,
    description text,
    downvotes bigint,
    due_date text,
    due_date_fixed text,
    due_date_from_inherited_source text,
    due_date_from_milestones text,
    due_date_is_fixed boolean,
    end_date text,
    iid bigint,
    parent_id text,
    parent_iid bigint,
    reference text,
    references_full text,
    references_relative text,
    references_short text,
    start_date text,
    start_date_fixed text,
    start_date_from_inherited_source text,
    start_date_from_milestones text,
    start_date_is_fixed boolean,
    "state" text,
    text_color text,
    title text,
    updated_at timestamp,
    upvotes bigint,
    web_edit_url text,
    web_url text,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES project_user(id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE project_branch_parent_id (
    parent_id text,
    project_branch_fivetran_id text,
    PRIMARY KEY (parent_id, project_branch_fivetran_id),
    FOREIGN KEY (project_branch_fivetran_id) REFERENCES project_branch(_fivetran_id)
);

CREATE TABLE project_branch (
    _fivetran_id text,
    commit_id text,
    project_id text,
    can_push boolean,
    defaults boolean,
    developers_can_merge boolean,
    developers_can_push boolean,
    merged boolean,
    "name" text,
    protected boolean,
    web_url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (commit_id) REFERENCES project_commit(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE group_member (
    id text,
    groups_id text,
    created_by_id text,
    access_level bigint,
    avatar_url text,
    created_at timestamp,
    expires_at text,
    group_saml_identity_extern_uid text,
    group_saml_identity_provider text,
    group_saml_identity_saml_provider_id bigint,
    membership_state text,
    "name" text,
    "state" text,
    username text,
    web_url text,
    PRIMARY KEY (id, groups_id),
    FOREIGN KEY (groups_id) REFERENCES groups(id),
    FOREIGN KEY (created_by_id) REFERENCES project_user(id)
);

CREATE TABLE project_merge_request_discussion_note (
    id text,
    project_id text,
    project_merge_request_iid bigint,
    project_merge_request_discussion_id text,
    author_id text,
    attachment text,
    author_avatar_url text,
    author_name text,
    author_state text,
    author_username text,
    author_web_url text,
    body text,
    created_at timestamp,
    is_system boolean,
    noteable_id text,
    noteable_iid text,
    noteable_type text,
    position_base_sha text,
    position_head_sha text,
    position_line_range jsonb,
    position_new_line text,
    position_new_path text,
    position_old_line text,
    position_old_path text,
    position_position_type text,
    position_start_sha text,
    resolvable boolean,
    resolved boolean,
    resolved_at timestamp,
    resolved_by jsonb,
    suggestions jsonb,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id, project_id, project_merge_request_iid, project_merge_request_discussion_id),
    FOREIGN KEY (project_merge_request_discussion_id) REFERENCES project_merge_request_discussion(id),
    FOREIGN KEY (author_id) REFERENCES project_user(id)
);

CREATE TABLE project_merge_request_discussion (
    id text,
    project_id text,
    project_merge_request_iid bigint,
    individual_note boolean,
    PRIMARY KEY (id, project_id, project_merge_request_iid),
    FOREIGN KEY (project_id) REFERENCES project_merge_request(project_id),
    FOREIGN KEY (project_merge_request_iid) REFERENCES project_merge_request(iid)
);

CREATE TABLE project_pipeline (
    id text,
    project_id text,
    created_at timestamp,
    iid bigint,
    ref text,
    sha text,
    "source" text,
    "status" text,
    updated_at timestamp,
    web_url text,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);
