CREATE TABLE event_report (
    _fivetran_id text,
    event_id text,
    address_1 text,
    address_2 text,
    answer_1 text,
    answer_2 text,
    answer_3 text,
    business_email text,
    business_phone text,
    campaign_id text,
    certificate_link text,
    city text,
    company text,
    cost_center text,
    country text,
    duration text,
    event_title text,
    fax_number text,
    first_name text,
    hidden_field text,
    ip_address text,
    iqvia_expert_contact text,
    iqvia_opt_in text,
    last_name text,
    live_duration text,
    live_session text,
    media text,
    mobile_number text,
    on_demand_duration text,
    on_demand_session text,
    pass_fail text,
    postal_code text,
    question_1 text,
    question_2 text,
    question_3 text,
    referrer text,
    registered_on text,
    simlive_duration text,
    simlive_session text,
    state_or_province_region text,
    time_in text,
    time_out text,
    title text,
    total_duration text,
    total_session text,
    "type" text,
    unsubscribed text,
    user_agent text,
    -- survey_* (dynamic column),
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    content text,
    cost_center text,
    event_expiry text,
    folder_id text,
    is_expired text,
    latest_registration text,
    latest_session text,
    sched_end text,
    sched_start text,
    tp_key text,
    PRIMARY KEY (id)
);
