CREATE TABLE ticket_type (
    id text,
    campaign_id text,
    organization_id text,
    commitment_deadline text,
    commitment_id text,
    commitment_value text,
    created_at text,
    deductible_amount text,
    deductible_percent text,
    description text,
    ended_at text,
    entries_per_ticket text,
    is_active text,
    is_classy_mode text,
    max_per_transaction text,
    min_per_transaction text,
    "name" text,
    org_percent text,
    price text,
    quantity_available text,
    quantity_reserved text,
    quantity_sold text,
    started_at text,
    updated_at text,
    weight text,
    PRIMARY KEY (id, campaign_id, organization_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE organization (
    id text,
    address text,
    allow_download_annual_receipts text,
    are_activity_feeds_disabled text,
    background_color text,
    background_image text,
    background_image_asset_id text,
    background_image_style text,
    billing_provider_name text,
    canceled_at text,
    city text,
    classy_fee_percent text,
    classy_subscription_plan_id text,
    contact_first_name text,
    contact_last_name text,
    contact_phone text,
    country text,
    created_at text,
    currency text,
    currency_code text,
    description text,
    ein text,
    email_address text,
    facebook text,
    favicon text,
    favicon_asset_id text,
    fixed_fot_percent text,
    flex_rate_percent text,
    gfm_charity_community_id text,
    gfm_connect_banner_count text,
    gfm_connect_banner_dismissed_at text,
    gfm_npo_page_slug text,
    has_double_the_donation_employer_match text,
    has_double_the_donation_enployer_match text,
    has_employer_match text,
    has_gfm_npo_transactions text,
    header_background_image text,
    header_background_image_asset_id text,
    header_color text,
    header_footer_color text,
    header_image text,
    header_image_asset_id text,
    header_image_height text,
    header_image_style text,
    hero_image_asset_id text,
    hide_classy_logo text,
    is_gfm_npo_page_claimed text,
    is_gift_aid_available text,
    logo_id text,
    mission text,
    "name" text,
    opt_in_wording text,
    past_due_at text,
    payment_provider_id text,
    payment_provider_name text,
    plan_name text,
    plan_type text,
    postal_code text,
    primary_color text,
    resend_receipt_flag text,
    restricted_country_information text,
    secondary_color text,
    show_donation_stats_on_home_page text,
    show_donation_stats_on_rgp text,
    signature_id text,
    signature_name text,
    signature_title text,
    "state" text,
    "status" text,
    tax_identifier text,
    thumbnail text,
    timezone_identifier text,
    twitter text,
    "type" text,
    updated_at text,
    url text,
    welcome_message text,
    PRIMARY KEY (id)
);

CREATE TABLE question (
    id text,
    campaign_id text,
    organization_id text,
    created_at text,
    deleted_at text,
    is_required text,
    label text,
    location text,
    product_id text,
    tags text,
    "type" text,
    updated_at text,
    weight text,
    PRIMARY KEY (id, campaign_id, organization_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE fundraising_team (
    id text,
    campaign_id text,
    designation_id text,
    organization_id text,
    parent_id text,
    city text,
    country text,
    cover_photo text,
    cover_photo_id text,
    created_at text,
    currency_code text,
    description text,
    goal text,
    logo_id text,
    "name" text,
    postal_code text,
    raw_currency_code text,
    raw_goal text,
    root_id text,
    "state" text,
    "status" text,
    team_lead_id text,
    team_lead_supporter_id text,
    team_policy_id text,
    thank_you_text text,
    updated_at text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (designation_id) REFERENCES designation(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (parent_id) REFERENCES fundraising_team(id)
);

CREATE TABLE dedication (
    id text,
    organization_id text,
    ecard_campaign_id text,
    transaction_id text,
    address text,
    city text,
    country text,
    ecard_asset_id text,
    ecard_id text,
    ecard_is_deleted text,
    ecard_message text,
    ecard_order text,
    email_address text,
    first_name text,
    honoree_first_name text,
    honoree_last_name text,
    honoree_name text,
    is_gift_amount_msg_included text,
    last_name text,
    "name" text,
    postal_code text,
    "state" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (ecard_campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE channel (
    id text,
    organization_id text,
    additional_configurations jsonb,
    channel_integration_details_id text,
    channel_name text,
    disabled_at text,
    feature_tier text,
    "status" text,
    step_status_authorize_granted text,
    step_status_granted_fundraiser_permission text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE recurring_donation_plan_schedule (
    "index" text,
    recurring_donation_plan_id text,
    "day" text,
    mmdd text,
    "month" text,
    PRIMARY KEY ("index", recurring_donation_plan_id),
    FOREIGN KEY (recurring_donation_plan_id) REFERENCES recurring_donation_plan(id)
);

CREATE TABLE recurring_donation_plan (
    id text,
    campaign_id text,
    designation_id text,
    fundraising_page_id text,
    fundraising_team_id text,
    organization_id text,
    supporter_id text,
    ach_last_four text,
    address text,
    address_2 text,
    applied_application_fee_percent text,
    applied_flex_rate_percent text,
    applied_fot_percent text,
    applied_processor_fee_percent text,
    applied_raw_processor_fee_flat text,
    cancel_by text,
    cancel_reason_code text,
    cancel_reason_text text,
    canceled_at text,
    cc_card_exp text,
    cc_last_four text,
    cc_type text,
    city text,
    classy_mode_enabled text,
    classy_pay_app_id text,
    classy_pay_recurring_amount text,
    classy_pay_recurring_created_date text,
    classy_pay_recurring_currency text,
    classy_pay_recurring_descriptor text,
    classy_pay_recurring_fot text,
    classy_pay_recurring_history_created_date text,
    classy_pay_recurring_history_id text,
    classy_pay_recurring_history_state text,
    classy_pay_recurring_history_state_detail_action text,
    classy_pay_recurring_history_state_detail_by text,
    classy_pay_recurring_history_state_detail_should_process_date text,
    classy_pay_recurring_id text,
    classy_pay_recurring_last_modified_date text,
    classy_pay_recurring_migrated text,
    classy_pay_recurring_next_processing_date text,
    classy_pay_recurring_recur_until text,
    classy_pay_recurring_recurring_start_date text,
    classy_pay_recurring_recurring_time_zone text,
    classy_pay_recurring_recurring_unit text,
    company_name text,
    country text,
    created_at text,
    currency_code text,
    dcf_allowed text,
    dcf_enabled text,
    donation_amount text,
    effective_fixed_fot_percent text,
    failed_at text,
    fee_on_top text,
    first_name text,
    frequency text,
    hide_amount text,
    is_anonymous text,
    is_donor_covered_fee text,
    is_gift_aid text,
    is_paused text,
    last_name text,
    member_id text,
    migrated text,
    migration_date text,
    next_processing_date text,
    pause_until text,
    payer_address_1 text,
    payer_city text,
    payer_country text,
    payer_email text,
    payer_first_name text,
    payer_id text,
    payer_last_name text,
    payer_state text,
    payer_zip text,
    payment_gateway text,
    payment_provider_configuration_name text,
    payment_token_detail_expiration_month text,
    payment_token_detail_expiration_year text,
    payment_token_detail_source text,
    payment_token_id text,
    payment_token_name text,
    payment_token_type text,
    payment_type text,
    plan_paused_on_date text,
    postal_code text,
    pp_plan_id text,
    raw_adjustment_amount text,
    raw_application_fee_amount text,
    raw_currency_code text,
    raw_donation_amount text,
    raw_flex_rate_amount text,
    raw_initial_gross_amount text,
    raw_processor_fee_amount text,
    recur_until text,
    started_at text,
    "state" text,
    "status" text,
    timezone_identifier text,
    updated_at text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (designation_id) REFERENCES designation(id),
    FOREIGN KEY (fundraising_page_id) REFERENCES fundraising_page(id),
    FOREIGN KEY (fundraising_team_id) REFERENCES fundraising_team(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (supporter_id) REFERENCES supporter(id)
);

CREATE TABLE supporter (
    id text,
    source_campaign_id text,
    source_fundraising_page_id text,
    source_organization_id text,
    address_1 text,
    address_2 text,
    city text,
    country text,
    created_at text,
    email_address text,
    first_name text,
    gender text,
    last_email_consent_decision_date text,
    last_emailed_at text,
    last_name text,
    last_sms_consent_decision_date text,
    location text,
    member_id text,
    metadata jsonb,
    nickname text,
    opt_in text,
    origin text,
    phone text,
    postal_code text,
    sms_opt_in text,
    source_member_id text,
    "state" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (source_campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (source_fundraising_page_id) REFERENCES fundraising_page(id),
    FOREIGN KEY (source_organization_id) REFERENCES organization(id)
);

CREATE TABLE paypal_stripe_payout (
    id text,
    organization_id text,
    classy_transaction_id text,
    payout_amount text,
    payout_amount_currency text,
    payout_created_at text,
    payout_date text,
    payout_id text,
    payout_updated_at text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (classy_transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE source_tracking_code (
    id text,
    organization_id text,
    c_src text,
    c_src_2 text,
    created_at text,
    event_type text,
    referrer text,
    trackable_id text,
    trackable_type text,
    updated_at text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE answer (
    id text,
    campaign_id text,
    organization_id text,
    question_id text,
    answer text,
    answerable_id text,
    answerable_type text,
    created_at text,
    member_id text,
    updated_at text,
    PRIMARY KEY (id, campaign_id, organization_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (question_id) REFERENCES question(id)
);

CREATE TABLE fundraising_page (
    id text,
    campaign_id text,
    designation_id text,
    fundraising_team_id text,
    organization_id text,
    parent_id text,
    question_id text,
    supporter_id text,
    alias text,
    commitment_id text,
    cover_photo_id text,
    created_at text,
    currency_code text,
    ended_at text,
    goal text,
    intro_text text,
    is_primary text,
    is_tribute text,
    logo_id text,
    member_email_text text,
    member_id text,
    raw_currency_code text,
    raw_goal text,
    started_at text,
    "status" text,
    team_role text,
    thank_you_email_text text,
    thank_you_text text,
    title text,
    updated_at text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (designation_id) REFERENCES designation(id),
    FOREIGN KEY (fundraising_team_id) REFERENCES fundraising_team(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (parent_id) REFERENCES fundraising_page(id),
    FOREIGN KEY (question_id) REFERENCES question(id),
    FOREIGN KEY (supporter_id) REFERENCES supporter(id)
);

CREATE TABLE campaign (
    id text,
    channel_id text,
    designation_id text,
    organization_id text,
    add_registration_fee text,
    address_1 text,
    allow_duplicate_fundraiser text,
    allow_ecard text,
    allow_fundraising_page text,
    allow_team_fundraising text,
    campaign_template_id text,
    category_id text,
    channel_keyword text,
    city text,
    classy_live_event_id text,
    classy_mode_appeal text,
    classy_mode_checked_by_default text,
    classy_mode_enabled text,
    contact_email text,
    contact_phone text,
    corporate_donation_enabled text,
    country text,
    created_at text,
    created_with text,
    crypto_giving text,
    currency_code text,
    dcf_allowed text,
    dcf_enabled text,
    default_page_appeal text,
    default_page_appeal_email text,
    default_page_goal text,
    default_page_post_asset_id text,
    default_page_post_body text,
    default_page_post_title text,
    default_page_thank_you_email text,
    default_team_appeal text,
    default_team_appeal_email text,
    default_team_goal text,
    default_team_post_asset_id text,
    default_team_post_body text,
    default_team_post_title text,
    default_team_thank_you_email text,
    default_thank_you_text text,
    disable_donation_attribution text,
    display_group_name text,
    effective_fixed_fot_percent text,
    effective_flex_rate_percent text,
    effective_recaptcha_setting text,
    embedded_giving text,
    ended_at text,
    exit_modal text,
    fixed_fot_percent text,
    flex_rate_percent text,
    goal text,
    hide_anonymous_donation text,
    hide_contact_opt_in text,
    hide_dedication text,
    hide_donation_amount text,
    hide_donation_comment text,
    hide_from_profile text,
    hide_recurring_end_date text,
    internal_name text,
    is_billing_address_required text,
    is_ended_at_hidden text,
    is_fees_free text,
    is_general text,
    is_started_at_hidden text,
    location_detail text,
    logo_id text,
    minimum_donation_amount text,
    "name" text,
    offer_dedication_postal_notification text,
    opt_in_checked_by_default text,
    pages_can_set_appeal text,
    pages_can_set_goal text,
    postal_code text,
    raw_currency_code text,
    raw_goal text,
    send_dedication_email text,
    sort_designation_by text,
    started_at text,
    "state" text,
    "status" text,
    team_cover_photo_id text,
    team_membership_policy text,
    teams_can_set_appeal text,
    teams_can_set_goal text,
    ticket_pass_on_fee text,
    timezone_identifier text,
    "type" text,
    updated_at text,
    use_intelligent_ask_onetime text,
    use_intelligent_ask_recurring text,
    venue text,
    PRIMARY KEY (id),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (designation_id) REFERENCES designation(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE registration (
    id text,
    campaign_id text,
    organization_id text,
    fundraising_page_id text,
    fundraising_team_id text,
    supporter_id text,
    transaction_id text,
    transaction_item_id text,
    address_1 text,
    address_2 text,
    attendee_id text,
    blog text,
    cell text,
    city text,
    commitment_id text,
    company text,
    country text,
    created_at text,
    date_of_birth text,
    email text,
    first_name text,
    gender text,
    last_name text,
    member_id text,
    phone text,
    postal_code text,
    product_commitment_deadline text,
    product_commitment_value text,
    product_name text,
    "state" text,
    "status" text,
    t_shirt_size text,
    transaction_last_four text,
    transaction_payment_type text,
    updated_at text,
    website text,
    PRIMARY KEY (id, campaign_id, organization_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (fundraising_page_id) REFERENCES fundraising_page(id),
    FOREIGN KEY (fundraising_team_id) REFERENCES fundraising_team(id),
    FOREIGN KEY (supporter_id) REFERENCES supporter(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id),
    FOREIGN KEY (transaction_item_id) REFERENCES transaction_item(id)
);

CREATE TABLE designation (
    id text,
    organization_id text,
    city text,
    created_at text,
    description text,
    end_time text,
    external_reference_id text,
    goal text,
    is_active text,
    is_complete text,
    is_default text,
    "name" text,
    postal_code text,
    start_time text,
    "state" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE transaction_item (
    id text,
    transaction_id text,
    charged_fees_amount text,
    charged_final_price text,
    commerce_order_item_id text,
    created_at text,
    currency_code text,
    donation_gross_amount text,
    donation_net_amount text,
    fees_amount text,
    final_price text,
    organization_id text,
    overhead_amount text,
    price text,
    product_id text,
    product_name text,
    promo_code_id text,
    quantity text,
    raw_currency_code text,
    raw_donation_gross_amount text,
    raw_final_price text,
    raw_overhead_amount text,
    raw_price text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, transaction_id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE "transaction" (
    id text,
    campaign_id text,
    designation_id text,
    fundraising_page_id text,
    fundraising_team_id text,
    organization_id text,
    parent_transaction_id text,
    recurring_donation_plan_id text,
    supporter_id text,
    account_number text,
    account_type text,
    acknowledgements_count text,
    adjustment_amount text,
    app_id text,
    application_fee_amount text,
    applied_application_fee_percent text,
    applied_flex_rate_percent text,
    applied_fot_percent text,
    applied_processor_fee_percent text,
    applied_raw_processor_fee_flat text,
    billing_address_1 text,
    billing_address_2 text,
    billing_city text,
    billing_country text,
    billing_first_name text,
    billing_last_name text,
    billing_postal_code text,
    billing_state text,
    browser_info text,
    card_expiration text,
    card_last_four text,
    card_type text,
    channel_transaction text,
    charged_at text,
    charged_classy_fees_amount text,
    charged_currency_code text,
    charged_fees_amount text,
    charged_pp_fees_amount text,
    charged_total_gross_amount text,
    classy_fees_amount text,
    classy_pay_latest_transaction_history_created_date text,
    classy_pay_latest_transaction_history_state text,
    classy_pay_latest_transaction_history_state_detail_balance_transaction_id text,
    classy_pay_latest_transaction_history_state_detail_customer_id text,
    classy_pay_latest_transaction_history_state_detail_processor_tx_status text,
    classy_pay_latest_transaction_history_state_detail_transfer_id text,
    classy_pay_payer_address_1 text,
    classy_pay_payer_city text,
    classy_pay_payer_country text,
    classy_pay_payer_email text,
    classy_pay_payer_first_name text,
    classy_pay_payer_id text,
    classy_pay_payer_last_name text,
    classy_pay_payer_state text,
    classy_pay_payer_zip text,
    classy_pay_payment_token_detail_expiration_month text,
    classy_pay_payment_token_detail_expiration_year text,
    classy_pay_payment_token_detail_source text,
    classy_pay_payment_token_id text,
    classy_pay_payment_token_name text,
    classy_pay_payment_token_type text,
    classy_pay_processor_id text,
    classy_pay_processor_name text,
    classy_pay_processor_status text,
    classy_pay_transaction_amount text,
    classy_pay_transaction_charge_amount text,
    classy_pay_transaction_created_date text,
    classy_pay_transaction_currency text,
    classy_pay_transaction_id text,
    classy_pay_transaction_processor_object_id text,
    classy_pay_transaction_statement_descriptor text,
    classy_pay_transaction_type text,
    "comment" text,
    company_name text,
    context_application_fee_campaign_category text,
    context_application_fee_platform_fee_type text,
    context_commerce_confirmation_id text,
    context_commerce_order_id text,
    context_created_by text,
    context_is_passport text,
    context_platform_tip text,
    context_source_campaign_id text,
    context_source_campaign_type text,
    context_vendor_batch_number text,
    context_vendor_batch_sequence text,
    context_vendor_name text,
    created_at text,
    currency_code text,
    dedication text,
    donation_gross_amount text,
    donation_matching_plan_id text,
    donation_net_amount text,
    fee_on_top text,
    fees_amount text,
    flex_rate_amount text,
    frequency text,
    hide_amount text,
    in_honor_of text,
    initial_gross_amount text,
    institution text,
    is_anonymous text,
    is_donor_covered_fee text,
    is_gift_aid text,
    is_reprocess text,
    member_country text,
    member_email_address text,
    member_id text,
    member_name text,
    member_phone text,
    offline_payment_info_check_number text,
    offline_payment_info_description text,
    offline_payment_info_payment_type text,
    offline_payment_info_sync_third_party text,
    opted_into_payment_sync text,
    order_donation_match_amount text,
    order_donation_match_employee_email text,
    order_donation_match_employee_id text,
    order_donation_match_employer_address text,
    order_donation_match_employer_id text,
    order_donation_match_employer_name text,
    order_donation_match_first_name text,
    order_donation_match_id text,
    order_donation_match_last_name text,
    order_donation_match_promise_status text,
    order_donation_match_transaction_id text,
    order_donation_match_type text,
    overhead_net_amount text,
    payment_gateway text,
    payment_method text,
    payment_source text,
    payment_type text,
    pp_fees_amount text,
    pp_reference_id text,
    pp_response text,
    pp_transaction_id text,
    processor_decline_code text,
    processor_fee_amount text,
    promo_code_code text,
    purchased_at text,
    raw_adjustment_amount text,
    raw_application_fee_amount text,
    raw_currency_code text,
    raw_donation_gross_amount text,
    raw_flex_rate_amount text,
    raw_initial_gross_amount text,
    raw_overhead_net_amount text,
    raw_processor_fee_amount text,
    raw_total_gross_amount text,
    receipt_serial text,
    refunded_at text,
    reprocess_attempt_info text,
    reprocess_attempts text,
    reprocess_status text,
    "status" text,
    tax_entity_id text,
    total_gross_amount text,
    updated_at text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (designation_id) REFERENCES designation(id),
    FOREIGN KEY (fundraising_page_id) REFERENCES fundraising_page(id),
    FOREIGN KEY (fundraising_team_id) REFERENCES fundraising_team(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (parent_transaction_id) REFERENCES "transaction"(id),
    FOREIGN KEY (recurring_donation_plan_id) REFERENCES recurring_donation_plan(id),
    FOREIGN KEY (supporter_id) REFERENCES supporter(id)
);
