CREATE TABLE event_speaker (
    id text,
    event_id text,
    company text,
    description text,
    first_name text,
    last_name text,
    linkedin_url text,
    profile_picture_url text,
    title text,
    twitter_url text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_public_agenda_session_speaker (
    event_id text,
    id text,
    session_id text,
    PRIMARY KEY (event_id, id, session_id),
    FOREIGN KEY (event_id) REFERENCES event_public_agenda(event_id),
    FOREIGN KEY (id) REFERENCES event_speaker(id),
    FOREIGN KEY (session_id) REFERENCES event_public_agenda(session_id)
);

CREATE TABLE event_public_agenda (
    session_id text,
    event_id text,
    session_description text,
    session_end_time text,
    session_location text,
    session_name text,
    session_start_time text,
    session_type text,
    PRIMARY KEY (session_id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE ticket_type (
    id text,
    event_id text,
    allow_all_tracks text,
    category_name text,
    category_ref_id text,
    code text,
    created_at text,
    label text,
    member_count text,
    ticket_type_id text,
    updated_at text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE agenda_item (
    id text,
    event_id text,
    allowed_end_time text,
    allowed_start_time text,
    description text,
    end_time text,
    expected_end_time text,
    is_live text,
    kind text,
    live_end_time text,
    live_start_time text,
    start_time text,
    title text,
    PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_supported_language (
    "index" text,
    event_id text,
    code text,
    "name" text,
    native_name text,
    PRIMARY KEY ("index", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_form_field (
    id text,
    event_id text,
    checked text,
    custom_validation_regex text,
    error text,
    error_message text,
    is_standard text,
    mapped_title text,
    optional text,
    title text,
    "type" text,
    "value" text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    organization text,
    broadcast_filler_image_s_3_path text,
    broadcast_filler_video_s_3_path text,
    broadcast_type text,
    created_at text,
    created_by text,
    created_by_user_first_name text,
    created_by_user_id text,
    created_by_user_last_name text,
    created_by_user_organization text,
    created_by_user_profile_picture_url text,
    created_by_user_role text,
    default_language_dropdown_enabled text,
    deleted text,
    deleted_by_cascade text,
    end_time text,
    event_type text,
    integration_config_updated_salesforce text,
    is_blueprint text,
    is_hybrid text,
    manual_breakout text,
    meta_tag jsonb,
    owner text,
    recording_state text,
    registrant_count text,
    registration_cta_link text,
    registration_form_form_type text,
    registration_form_id text,
    registration_form_is_default text,
    registration_form_is_global_form text,
    registration_form_is_one_click_enabled text,
    registration_form_name text,
    registration_form_organization text,
    registration_form_schema_url text,
    series_attendee_count text,
    series_blueprint_event text,
    series_builder_html text,
    series_builder_raw_json text,
    series_contains_waitlist_event text,
    series_created_at text,
    series_created_by text,
    series_description text,
    series_email_alias_name text,
    series_end_date_threshold text,
    series_favicon text,
    series_frequency text,
    series_id text,
    series_initial_event_generated text,
    series_initial_event_generation_count text,
    series_last_synced_at text,
    series_marketing_tags text,
    series_marketo_base_program_id text,
    series_marketo_program_folder_id text,
    series_marketo_program_folder_name text,
    series_marketo_settings text,
    series_marketo_status text,
    series_name text,
    series_next_event_generation_time text,
    series_organization text,
    series_parent text,
    series_registrant_count text,
    series_registration_form text,
    series_registration_form_data text,
    series_registration_form_form_type text,
    series_registration_form_id text,
    series_registration_form_is_default text,
    series_registration_form_is_global_form text,
    series_registration_form_is_one_click_enabled text,
    series_registration_form_name text,
    series_registration_form_organization text,
    series_registration_form_schema_url text,
    series_registration_form_url text,
    series_repeating_event_sync_allowed text,
    series_schedule text,
    series_schedule_status jsonb,
    series_social_media_image text,
    series_sync_id text,
    series_sync_status text,
    series_tags jsonb,
    series_total_event_threshold text,
    series_type text,
    series_unit text,
    series_upcoming_event_count text,
    series_updated_at text,
    series_updated_by text,
    series_url text,
    series_workspace text,
    short_id text,
    splash_tracking_pixel_snippet_body_section_script text,
    splash_tracking_pixel_snippet_created_at text,
    splash_tracking_pixel_snippet_created_by text,
    splash_tracking_pixel_snippet_custom_event_script text,
    splash_tracking_pixel_snippet_head_section_script text,
    splash_tracking_pixel_snippet_id text,
    splash_tracking_pixel_snippet_updated_at text,
    splash_tracking_pixel_snippet_updated_by text,
    start_time text,
    supported_captions_languages jsonb,
    theme_alt_primary_background_shade text,
    theme_auth_theme text,
    theme_ctrl_bar_shade_alpha text,
    theme_event_background text,
    theme_font_link text,
    theme_font_name text,
    theme_font_src text,
    theme_font_type text,
    theme_logos text,
    theme_lower_third_background text,
    theme_lower_third_text_color text,
    theme_mobile_event_background text,
    theme_mobile_splash_page_hero text,
    theme_mobile_stage_background text,
    theme_name_card_background text,
    theme_name_card_radius text,
    theme_name_card_text_color text,
    theme_name_card_title_display text,
    theme_p_2_p_panel_shade_alpha text,
    theme_page_item_alpha text,
    theme_primary_background_shade text,
    theme_primary_color text,
    theme_primary_text_color text,
    theme_screen_saver_background text,
    theme_screen_saver_text_color text,
    theme_secondary_color text,
    theme_secondary_text_color text,
    theme_show_borders text,
    theme_sidebar_alpha text,
    theme_sidebar_blur text,
    theme_splash_background_color text,
    theme_splash_background_shade text,
    theme_splash_font_link text,
    theme_splash_font_name text,
    theme_splash_font_src text,
    theme_splash_font_type text,
    theme_splash_gradient_height text,
    theme_splash_page_hero text,
    theme_splash_shade_alpha text,
    theme_splash_text_color text,
    theme_splash_text_onimage_color text,
    theme_stage_background text,
    theme_stage_text_color text,
    theme_type text,
    theme_virtual_backgrounds text,
    timezone text,
    title text,
    updated_at timestamp,
    updated_by text,
    updated_by_user_email text,
    updated_by_user_first_name text,
    updated_by_user_id text,
    updated_by_user_last_name text,
    updated_by_user_organization text,
    updated_by_user_profile_picture_url text,
    updated_by_user_role text,
    vivenu_event_url text,
    workspace_color text,
    workspace_icon text,
    workspace_id text,
    workspace_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization) REFERENCES organization(id)
);

CREATE TABLE track_allowed_ticket_type (
    ticket_type_id text,
    track_id text,
    PRIMARY KEY (ticket_type_id, track_id),
    FOREIGN KEY (ticket_type_id) REFERENCES ticket_type(id),
    FOREIGN KEY (track_id) REFERENCES track(id)
);

CREATE TABLE track (
    id text,
    event_id text,
    agenda_items text,
    channel_mmid text,
    created_at text,
    custom text,
    sort_priority text,
    title text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE organization (
    id text,
    allow_hybrid_events text,
    can_add_track text,
    can_change_event_length text,
    can_create_rtmp_broadcast text,
    content_clips_count text,
    content_lab_enabled text,
    content_video_duration text,
    created_at text,
    enable_live_captions text,
    enable_old_reg_pages text,
    enabled_rtmp_out text,
    in_person_events_enabled text,
    is_booths_tab_enabled text,
    is_content_lab_standalone text,
    is_kudo_enabled text,
    is_ux_translation_enabled text,
    is_webhook_enabled text,
    "name" text,
    no_of_organizer_seats text,
    owner text,
    short_name text,
    show_advanced_branding_tab text,
    show_forms text,
    show_secondary_booth_tab text,
    tier text,
    updated_at text,
    use_new_studio_app text,
    workspace_settings_count text,
    PRIMARY KEY (id)
);

CREATE TABLE booth_discussion_group (
    id text,
    booth_id text,
    event_id text,
    capacity text,
    created_at text,
    "current" text,
    deleted text,
    deleted_by_cascade text,
    description text,
    ends_at text,
    is_booth text,
    is_breakout text,
    is_live text,
    mmid text,
    moderator jsonb,
    owner text,
    participants jsonb,
    rank text,
    recording_directory text,
    recording_resourceid text,
    recording_sid text,
    shadow_mmid text,
    sponsor_image text,
    starts_at text,
    title text,
    updated_at text,
    video_quality text,
    PRIMARY KEY (id, booth_id),
    FOREIGN KEY (booth_id) REFERENCES booth(id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE booth_resource (
    id text,
    booth_id text,
    event_id text,
    content_object text,
    content_type text,
    created_at text,
    key_or_url text,
    "name" text,
    object_id text,
    s_3_hosted text,
    updated_at text,
    PRIMARY KEY (id, booth_id),
    FOREIGN KEY (booth_id) REFERENCES booth(id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE booth (
    id text,
    event_id text,
    booth_type text,
    cover_image text,
    description text,
    hyperlink text,
    logo text,
    title text,
    PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE broadcast_speaker (
    broadcast_id text,
    event_id text,
    speaker_id text,
    PRIMARY KEY (broadcast_id, event_id, speaker_id),
    FOREIGN KEY (broadcast_id) REFERENCES broadcast(id),
    FOREIGN KEY (event_id) REFERENCES broadcast(event_id),
    FOREIGN KEY (speaker_id) REFERENCES event_speaker(id)
);

CREATE TABLE broadcast_video_asset (
    id text,
    broadcast_id text,
    event_id text,
    asset_type text,
    client_hls_path text,
    created_at text,
    created_by_email text,
    created_by_first_name text,
    created_by_id text,
    created_by_last_name text,
    created_by_organization text,
    created_by_profile_picture_url text,
    created_by_role text,
    creation_type text,
    deleted text,
    deleted_by_cascade text,
    duration text,
    embedded_url text,
    fallback_hls_path text,
    hls_path text,
    hls_url jsonb,
    metadata jsonb,
    "name" text,
    onedrive_file_id text,
    onedrive_upload_state text,
    organization text,
    "path" text,
    "source" text,
    thumbnail text,
    transcode_finish_time text,
    transcode_status text,
    transcoder_error jsonb,
    transcoder_warning jsonb,
    transcript_path jsonb,
    updated_at text,
    updated_by_email text,
    updated_by_first_name text,
    updated_by_id text,
    updated_by_last_name text,
    updated_by_organization text,
    updated_by_profile_picture_url text,
    updated_by_role text,
    uploaded text,
    video_usage_count text,
    workspace text,
    PRIMARY KEY (id, broadcast_id, event_id),
    FOREIGN KEY (broadcast_id) REFERENCES broadcast(id),
    FOREIGN KEY (event_id) REFERENCES broadcast(event_id)
);

CREATE TABLE broadcast (
    event_id text,
    id text,
    organization text,
    allowed_end_time text,
    allowed_start_time text,
    created_at text,
    deleted text,
    deleted_by_cascade text,
    end_time text,
    expected_end_time text,
    have_polls text,
    manual_redirection_enabled text,
    medialive_rtmp_input_channel_id text,
    medialive_rtmp_input_channel_states text,
    medialive_rtmp_input_created_at text,
    medialive_rtmp_input_event_id text,
    medialive_rtmp_input_failover_in_stream_key text,
    medialive_rtmp_input_failover_input_url text,
    medialive_rtmp_input_id text,
    medialive_rtmp_input_in_stream_key text,
    medialive_rtmp_input_input_frame_rate_alarm_state text,
    medialive_rtmp_input_input_frame_rate_alert_sent text,
    medialive_rtmp_input_input_url text,
    medialive_rtmp_input_name text,
    medialive_rtmp_input_network_in_alarm_state text,
    medialive_rtmp_input_network_in_alert_sent text,
    medialive_rtmp_input_output_url text,
    medialive_rtmp_input_test_run_end_time text,
    medialive_rtmp_input_updated_at text,
    mmid text,
    on_demand_asset_asset_type text,
    on_demand_asset_client_hls_path text,
    on_demand_asset_created_at text,
    on_demand_asset_created_by text,
    on_demand_asset_creation_type text,
    on_demand_asset_deleted text,
    on_demand_asset_deleted_by_cascade text,
    on_demand_asset_duration text,
    on_demand_asset_embedded_url text,
    on_demand_asset_fallback_hls_path text,
    on_demand_asset_hls_path text,
    on_demand_asset_id text,
    on_demand_asset_metadata jsonb,
    on_demand_asset_name text,
    on_demand_asset_onedrive_file_id text,
    on_demand_asset_onedrive_upload_state text,
    on_demand_asset_organization text,
    on_demand_asset_path text,
    on_demand_asset_source text,
    on_demand_asset_thumbnail text,
    on_demand_asset_transcode_finish_time text,
    on_demand_asset_transcode_status text,
    on_demand_asset_transcoder_errors jsonb,
    on_demand_asset_transcoder_type text,
    on_demand_asset_transcoder_warnings jsonb,
    on_demand_asset_transcript_path text,
    on_demand_asset_updated_at text,
    on_demand_asset_updated_by text,
    on_demand_asset_uploaded text,
    on_demand_asset_urls text,
    on_demand_asset_video_usage_count text,
    on_demand_asset_workspace text,
    recording_individual_directory text,
    recording_individual_resource_id text,
    recording_individual_sid text,
    recording_mix_directory text,
    recording_mix_resource_id text,
    recording_mix_sid text,
    recording_video_asset_asset_type text,
    recording_video_asset_client_hls_path text,
    recording_video_asset_created_at text,
    recording_video_asset_created_by text,
    recording_video_asset_creation_type text,
    recording_video_asset_deleted text,
    recording_video_asset_deleted_by_cascade text,
    recording_video_asset_duration text,
    recording_video_asset_embedded_url text,
    recording_video_asset_fallback_hls_path text,
    recording_video_asset_hls_path text,
    recording_video_asset_id text,
    recording_video_asset_metadata jsonb,
    recording_video_asset_name text,
    recording_video_asset_onedrive_file_id text,
    recording_video_asset_onedrive_upload_state text,
    recording_video_asset_organization text,
    recording_video_asset_path text,
    recording_video_asset_source text,
    recording_video_asset_thumbnail text,
    recording_video_asset_transcode_finish_time text,
    recording_video_asset_transcode_status text,
    recording_video_asset_transcoder_errors jsonb,
    recording_video_asset_transcoder_type text,
    recording_video_asset_transcoder_warnings jsonb,
    recording_video_asset_transcript_path text,
    recording_video_asset_updated_at text,
    recording_video_asset_updated_by text,
    recording_video_asset_uploaded text,
    recording_video_asset_urls text,
    recording_video_asset_video_usage_count text,
    recording_video_asset_workspace text,
    resources jsonb,
    staffs jsonb,
    start_time text,
    surveys jsonb,
    ticker_url text,
    title text,
    updated_at text,
    PRIMARY KEY (event_id, id),
    FOREIGN KEY (organization) REFERENCES organization(id)
);

CREATE TABLE tag_library (
    id text,
    organization text,
    created_at text,
    created_by text,
    tag_name text,
    updated_by text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization) REFERENCES organization(id)
);

CREATE TABLE event_member (
    id text,
    event_id text,
    track_id text,
    created_at text,
    event_role text,
    event_role_list jsonb,
    external_demo_requested text,
    external_demo_requested_at text,
    kind jsonb,
    magic_link text,
    marketo_lead_id text,
    organization_user_address_line_2 text,
    organization_user_age text,
    organization_user_allow_admin_panel_notifications text,
    organization_user_city text,
    organization_user_company text,
    organization_user_country text,
    organization_user_created_at text,
    organization_user_description text,
    organization_user_extra_data jsonb,
    organization_user_first_name text,
    organization_user_id text,
    organization_user_industry text,
    organization_user_last_name text,
    organization_user_linkedin_url text,
    organization_user_location text,
    organization_user_organization text,
    organization_user_phone_number text,
    organization_user_profile_picture_url text,
    organization_user_state text,
    organization_user_street_address text,
    organization_user_title text,
    organization_user_twitter_url text,
    organization_user_updated_at text,
    organization_user_user text,
    organization_user_zip_code text,
    qrcode text,
    qrcode_encoding text,
    salesforce_member_id text,
    updated_at text,
    user_address_line_2 text,
    user_age text,
    user_allow_admin_panel_notifications text,
    user_city text,
    user_company text,
    user_country text,
    user_description text,
    user_display_email text,
    user_email text,
    user_extra_data text,
    user_first_name text,
    user_id text,
    user_industry text,
    user_is_admin text,
    user_is_content_lab_standalone text,
    user_is_registered text,
    user_last_name text,
    user_linkedin_url text,
    user_location text,
    user_mmid text,
    user_organization text,
    user_phone_number text,
    user_profile_picture_url text,
    user_requester_role text,
    user_role text,
    user_state text,
    user_street_address text,
    user_title text,
    user_twitter_url text,
    user_zip_code text,
    uuid text,
    vivenu_ticket_url text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id),
    FOREIGN KEY (track_id) REFERENCES track(id)
);

CREATE TABLE resource (
    id text,
    event_id text,
    content_object text,
    content_type text,
    created_at text,
    key_or_url text,
    "name" text,
    object_id text,
    s_3_hosted text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);
