CREATE TABLE customer_conversion_action_and_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    all_conversions double precision,
    all_conversions_value double precision,
    conversion_action_name text,
    cross_device_conversions double precision,
    cross_device_conversions_value double precision,
    customer_engine_id text,
    device text,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE ad_group_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    content_impression_share double precision,
    content_rank_lost_impression_share double precision,
    historical_quality_score bigint,
    search_impression_share double precision,
    search_rank_lost_impression_share double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE ad_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    ad_id bigint,
    campaign_id bigint,
    ad_group_ad_engine_id text,
    average_cpc double precision,
    average_cpm double precision,
    clicks bigint,
    client_account_conversions double precision,
    client_account_conversions_value double precision,
    client_account_view_through_conversions bigint,
    cost_micros bigint,
    ctr double precision,
    impressions bigint,
    visits double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (ad_id) REFERENCES ad(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE keyword_conversion_action_and_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    ad_group_criterion_criterion_id bigint,
    ad_group_criterion_engine_id text,
    all_conversions double precision,
    all_conversions_value double precision,
    conversion_action_name text,
    cross_device_conversions double precision,
    cross_device_conversions_value double precision,
    device text,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign (
    id bigint,
    customer_id bigint,
    bidding_strategy_id bigint,
    advertising_channel_sub_type text,
    advertising_channel_type text,
    creation_time text,
    end_date text,
    engine_id text,
    labels text,
    last_modified_time text,
    "name" text,
    network_settings_target_content_network boolean,
    network_settings_target_google_search boolean,
    network_settings_target_partner_search_network boolean,
    network_settings_target_search_network boolean,
    start_date text,
    "status" text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id)
);

CREATE TABLE ad (
    id bigint,
    customer_id bigint,
    ad_group_id bigint,
    campaign_id bigint,
    creation_time text,
    display_url text,
    engine_id text,
    engine_status text,
    expanded_dynamic_search_ad_description1 text,
    expanded_dynamic_search_ad_description2 text,
    expanded_text_ad_description1 text,
    expanded_text_ad_description2 text,
    expanded_text_ad_headline text,
    expanded_text_ad_headline2 text,
    expanded_text_ad_headline3 text,
    final_urls text,
    labels text,
    last_modified_time text,
    "name" text,
    "status" text,
    text_ad_description1 text,
    text_ad_description2 text,
    text_ad_headline text,
    "type" text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE ad_group_conversion_action_and_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    all_conversions double precision,
    all_conversions_value double precision,
    conversion_action_name text,
    cross_device_conversions double precision,
    cross_device_conversions_value double precision,
    device text,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE customer_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    average_cpc double precision,
    average_cpm double precision,
    clicks bigint,
    client_account_conversions double precision,
    client_account_conversions_value double precision,
    client_account_view_through_conversions bigint,
    cost_micros bigint,
    ctr double precision,
    customer_engine_id text,
    device text,
    impressions bigint,
    visits double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer (
    id bigint,
    account_type text,
    creation_time text,
    currency_code text,
    descriptive_name text,
    engine_id text,
    last_modified_time text,
    "status" text,
    time_zone text,
    PRIMARY KEY (id)
);

CREATE TABLE ad_conversion_action_and_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    ad_id bigint,
    campaign_id bigint,
    ad_group_ad_engine_id text,
    all_conversions double precision,
    all_conversions_value double precision,
    conversion_action_name text,
    cross_device_conversions double precision,
    cross_device_conversions_value double precision,
    device text,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (ad_id) REFERENCES ad(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    average_cpc double precision,
    average_cpm double precision,
    clicks bigint,
    client_account_conversions double precision,
    client_account_conversions_value double precision,
    client_account_view_through_conversions bigint,
    cost_micros bigint,
    ctr double precision,
    device text,
    impressions bigint,
    visits double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE customer_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    content_budget_lost_impression_share double precision,
    content_impression_share double precision,
    content_rank_lost_impression_share double precision,
    customer_engine_id text,
    historical_quality_score bigint,
    search_budget_lost_impression_share double precision,
    search_impression_share double precision,
    search_rank_lost_impression_share double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE keyword_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    ad_group_criterion_criterion_id bigint,
    historical_quality_score bigint,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE keyword_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    ad_group_criterion_criterion_id bigint,
    ad_group_criterion_engine_id text,
    average_cpc double precision,
    average_cpm double precision,
    clicks bigint,
    client_account_conversions double precision,
    client_account_conversions_value double precision,
    client_account_view_through_conversions bigint,
    cost_micros bigint,
    ctr double precision,
    device text,
    impressions bigint,
    visits double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign_conversion_action_and_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    all_conversions double precision,
    all_conversions_value double precision,
    conversion_action_name text,
    cross_device_conversions double precision,
    cross_device_conversions_value double precision,
    device text,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE ad_group_device_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    ad_group_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    average_cpc double precision,
    average_cpm double precision,
    clicks bigint,
    client_account_conversions double precision,
    client_account_conversions_value double precision,
    client_account_view_through_conversions bigint,
    cost_micros bigint,
    ctr double precision,
    impressions bigint,
    visits double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE ad_group (
    id bigint,
    customer_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    ad_group_bid_modifier_bid_modifier double precision,
    ad_group_bid_modifier_device_type text,
    cpc_bid_micros bigint,
    creation_time text,
    end_date text,
    engine_id text,
    engine_status text,
    labels text,
    language_code text,
    last_modified_time text,
    "name" text,
    start_date text,
    "status" text,
    targeting_setting_target_restrictions text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE bidding_strategy (
    id bigint,
    customer_id bigint,
    "name" text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE campaign_report (
    _fivetran_id text,
    "date" text,
    customer_id bigint,
    bidding_strategy_id bigint,
    campaign_id bigint,
    all_conversions double precision,
    all_conversions_value double precision,
    average_cpc double precision,
    average_cpm double precision,
    clicks bigint,
    client_account_conversions double precision,
    client_account_conversions_value double precision,
    client_account_view_through_conversions bigint,
    content_budget_lost_impression_share double precision,
    content_impression_share double precision,
    content_rank_lost_impression_share double precision,
    conversions double precision,
    conversions_value double precision,
    cost_micros bigint,
    ctr double precision,
    historical_quality_score bigint,
    impressions bigint,
    search_budget_lost_impression_share double precision,
    search_impression_share double precision,
    search_rank_lost_impression_share double precision,
    visits double precision,
    PRIMARY KEY (_fivetran_id, "date", customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (bidding_strategy_id) REFERENCES bidding_strategy(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);
