CREATE TABLE zip_code (
    "index" integer,
    contact_info_index integer,
    first_party_and_partner_audience_id text,
    zip_code text,
    PRIMARY KEY ("index", contact_info_index, first_party_and_partner_audience_id),
    FOREIGN KEY (contact_info_index) REFERENCES contact_info("index"),
    FOREIGN KEY (first_party_and_partner_audience_id) REFERENCES contact_info(first_party_and_partner_audience_id)
);

CREATE TABLE contact_info (
    "index" integer,
    first_party_and_partner_audience_id text,
    country_code text,
    hashed_first_name text,
    hashed_last_name text,
    PRIMARY KEY ("index", first_party_and_partner_audience_id),
    FOREIGN KEY (first_party_and_partner_audience_id) REFERENCES first_party_and_partner_audience(id)
);

CREATE TABLE advertiser (
    id text,
    partner_id text,
    ad_server_config_cm_hybrid_config_cm_account_id text,
    ad_server_config_cm_hybrid_config_cm_floodlight_config_id text,
    ad_server_config_cm_hybrid_config_cm_floodlight_linking_authorized boolean,
    ad_server_config_cm_hybrid_config_dv_360_to_cm_cost_reporting_enabled boolean,
    ad_server_config_cm_hybrid_config_dv_360_to_cm_data_sharing_enabled boolean,
    ad_server_config_third_party_only_config_pixel_order_id_reporting_enabled boolean,
    billing_profile_id text,
    creative_config_dynamic_creative_enabled boolean,
    creative_config_ias_client_id text,
    creative_config_oba_compliance_disabled boolean,
    creative_config_video_creative_data_sharing_authorized boolean,
    data_access_config_override_partner_sdf_config boolean,
    data_access_config_sdf_config_admin_email text,
    data_access_config_sdf_config_version text,
    display_name text,
    entity_status text,
    general_config_currency_code text,
    general_config_domain_url text,
    general_config_time_zone text,
    integration_details text,
    integration_details_code text,
    "name" text,
    prisma_enabled boolean,
    serving_config_exempt_tv_from_viewability_targeting boolean,
    update_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (partner_id) REFERENCES partner(id)
);

CREATE TABLE hashed_email (
    "index" integer,
    contact_info_index integer,
    first_party_and_partner_audience_id text,
    hashed_email text,
    PRIMARY KEY ("index", contact_info_index, first_party_and_partner_audience_id),
    FOREIGN KEY (contact_info_index) REFERENCES contact_info("index"),
    FOREIGN KEY (first_party_and_partner_audience_id) REFERENCES contact_info(first_party_and_partner_audience_id)
);

CREATE TABLE campaign_budget (
    id text,
    campaign_id text,
    budget_amount_micros text,
    budget_unit text,
    date_range_end_date text,
    date_range_start_date text,
    display_name text,
    external_budget_id text,
    external_budget_source text,
    invoice_grouping_id text,
    prisma_config_prisma_cpe_code_prisma_client_code text,
    prisma_config_prisma_cpe_code_prisma_estimate_code text,
    prisma_config_prisma_cpe_code_prisma_product_code text,
    prisma_config_prisma_type text,
    prisma_config_supplier text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE ad_url (
    _fivetran_id text,
    ad_group_ad_id text,
    "type" text,
    url text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (ad_group_ad_id) REFERENCES ad_group_ad(id)
);

CREATE TABLE assigned_first_party_and_partner_audience (
    recency text,
    ad_group_assigned_targeting_option_id text,
    ad_group_id text,
    first_party_and_partner_audience_id text,
    is_included boolean,
    PRIMARY KEY (recency, ad_group_assigned_targeting_option_id, ad_group_id, first_party_and_partner_audience_id),
    FOREIGN KEY (ad_group_assigned_targeting_option_id) REFERENCES ad_group_assigned_targeting_option(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group_assigned_targeting_option(ad_group_id),
    FOREIGN KEY (first_party_and_partner_audience_id) REFERENCES first_party_and_partner_audience(id)
);

CREATE TABLE creative (
    id text,
    advertiser_id text,
    appended_tag text,
    cm_placement_id text,
    cm_tracking_ad_cm_ad_id text,
    cm_tracking_ad_cm_creative_id text,
    cm_tracking_ad_cm_placement_id text,
    create_time text,
    creative_type text,
    dimensions_height_pixels integer,
    dimensions_width_pixels integer,
    display_name text,
    dynamic boolean,
    entity_status text,
    expand_on_hover boolean,
    expanding_direction text,
    hosting_source text,
    html_5_video boolean,
    ias_campaign_monitoring boolean,
    integration_code text,
    js_tracker_url text,
    media_duration text,
    mp_3_audio boolean,
    "name" text,
    notes text,
    oba_icon_click_tracking_url text,
    oba_icon_dimensions_height_pixels integer,
    oba_icon_dimensions_width_pixels integer,
    oba_icon_landing_page_url text,
    oba_icon_position text,
    oba_icon_program text,
    oba_icon_resource_mime_type text,
    oba_icon_resource_url text,
    oba_icon_view_tracking_url text,
    ogg_audio boolean,
    progress_offset_percentage text,
    progress_offset_seconds text,
    require_html_5 boolean,
    require_mraid boolean,
    require_ping_for_attribution boolean,
    review_status_approval_status text,
    review_status_content_and_policy_review_status text,
    review_status_creative_and_landing_page_review_status text,
    skip_offset_percentage text,
    skip_offset_seconds text,
    skippable boolean,
    third_party_tag text,
    universal_ad_id text,
    universal_ad_id_registry text,
    update_time text,
    vast_tag_url text,
    vpaid boolean,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE ad_group (
    id text,
    advertiser_id text,
    ad_group_format text,
    bid_strategy_fixed_bid_bid_amount_micros text,
    bid_strategy_maximize_spend_auto_bid_custom_bidding_algorithm_id text,
    bid_strategy_maximize_spend_auto_bid_max_average_cpm_bid_amount_micros text,
    bid_strategy_maximize_spend_auto_bid_performance_goal_type text,
    bid_strategy_maximize_spend_auto_bid_raise_bid_for_deals boolean,
    bid_strategy_performance_goal_auto_bid_custom_bidding_algorithm_id text,
    bid_strategy_performance_goal_auto_bid_max_average_cpm_bid_amount_micros text,
    bid_strategy_performance_goal_auto_bid_performance_goal_amount_micros text,
    bid_strategy_performance_goal_auto_bid_performance_goal_type text,
    bid_strategy_youtube_and_partners_bid_ad_group_effective_target_cpa_source text,
    bid_strategy_youtube_and_partners_bid_ad_group_effective_target_cpa_value text,
    bid_strategy_youtube_and_partners_bid_type text,
    bid_strategy_youtube_and_partners_bid_value text,
    display_name text,
    entity_status text,
    line_item_id text,
    "name" text,
    product_feed_data_is_feed_disabled boolean,
    product_feed_data_product_match_type text,
    targeting_expansion_audience_expansion_level text,
    targeting_expansion_audience_expansion_seed_list_excluded boolean,
    targeting_expansion_enable_optimized_targeting boolean,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE ad_group_ad (
    id text,
    ad_group_id text,
    advertiser_id text,
    display_video_source_ad_creative_id text,
    audio_ad_display_url text,
    audio_ad_final_url text,
    audio_ad_tracking_url text,
    audio_ad_video_id text,
    audio_ad_video_unavailable_reason text,
    bumper_ad_common_in_stream_attribute_action_button_label text,
    bumper_ad_common_in_stream_attribute_action_headline text,
    bumper_ad_common_in_stream_attribute_companion_banner_file_size text,
    bumper_ad_common_in_stream_attribute_companion_banner_full_size_height_pixels integer,
    bumper_ad_common_in_stream_attribute_companion_banner_full_size_width_pixels integer,
    bumper_ad_common_in_stream_attribute_companion_banner_mime_type text,
    bumper_ad_common_in_stream_attribute_display_url text,
    bumper_ad_common_in_stream_attribute_final_url text,
    bumper_ad_common_in_stream_attribute_tracking_url text,
    bumper_ad_common_in_stream_attribute_video_id text,
    bumper_ad_common_in_stream_attribute_video_unavailable_reason text,
    display_name text,
    entity_status text,
    in_stream_ad_common_in_stream_attribute_action_button_label text,
    in_stream_ad_common_in_stream_attribute_action_headline text,
    in_stream_ad_common_in_stream_attribute_companion_banner_file_size text,
    in_stream_ad_common_in_stream_attribute_companion_banner_full_size_height_pixels integer,
    in_stream_ad_common_in_stream_attribute_companion_banner_full_size_width_pixels integer,
    in_stream_ad_common_in_stream_attribute_companion_banner_mime_type text,
    in_stream_ad_common_in_stream_attribute_display_url text,
    in_stream_ad_common_in_stream_attribute_final_url text,
    in_stream_ad_common_in_stream_attribute_tracking_url text,
    in_stream_ad_common_in_stream_attribute_video_id text,
    in_stream_ad_common_in_stream_attribute_video_unavailable_reason text,
    masthead_ad_autoplay_video_duration text,
    masthead_ad_autoplay_video_start_millisecond text,
    masthead_ad_call_to_action_button_label text,
    masthead_ad_call_to_action_final_url text,
    masthead_ad_call_to_action_tracking_url text,
    masthead_ad_description text,
    masthead_ad_headline text,
    masthead_ad_show_channel_art boolean,
    masthead_ad_video_aspect_ratio text,
    masthead_ad_video_id text,
    masthead_ad_video_unavailable_reason text,
    "name" text,
    non_skippable_ad_common_in_stream_attribute_action_button_label text,
    non_skippable_ad_common_in_stream_attribute_action_headline text,
    non_skippable_ad_common_in_stream_attribute_companion_banner_file_size text,
    non_skippable_ad_common_in_stream_attribute_companion_banner_full_size_height_pixels integer,
    non_skippable_ad_common_in_stream_attribute_companion_banner_full_size_width_pixels integer,
    non_skippable_ad_common_in_stream_attribute_companion_banner_mime_type text,
    non_skippable_ad_common_in_stream_attribute_display_url text,
    non_skippable_ad_common_in_stream_attribute_final_url text,
    non_skippable_ad_common_in_stream_attribute_tracking_url text,
    non_skippable_ad_common_in_stream_attribute_video_id text,
    non_skippable_ad_common_in_stream_attribute_video_unavailable_reason text,
    video_discover_ad_description_1 text,
    video_discover_ad_description_2 text,
    video_discover_ad_headline text,
    video_discover_ad_thumbnail text,
    video_discover_ad_video_id text,
    video_discover_ad_video_unavailable_reason text,
    video_performance_ad_display_url_breadcrumb_1 text,
    video_performance_ad_display_url_breadcrumb_2 text,
    video_performance_ad_domain text,
    video_performance_ad_final_url text,
    video_performance_ad_tracking_url text,
    PRIMARY KEY (id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (display_video_source_ad_creative_id) REFERENCES creative(id)
);

CREATE TABLE partner (
    id text,
    ad_server_config_measurement_config_dv_360_to_cm_cost_reporting_enabled boolean,
    ad_server_config_measurement_config_dv_360_to_cm_data_sharing_enabled boolean,
    billing_profile_id text,
    data_access_config_sdf_config_admin_email text,
    data_access_config_sdf_config_version text,
    display_name text,
    entity_status text,
    general_config_currency_code text,
    general_config_time_zone text,
    "name" text,
    update_time text,
    PRIMARY KEY (id)
);

CREATE TABLE campaign (
    id text,
    advertiser_id text,
    campaign_flight_planned_dates_end_date text,
    campaign_flight_planned_dates_start_date text,
    campaign_flight_planned_spend_amount_micros text,
    campaign_goal_performance_goal_amount_micros text,
    campaign_goal_performance_goal_percentage_micros text,
    campaign_goal_performance_goal_string text,
    campaign_goal_performance_goal_type text,
    campaign_goal_type text,
    display_name text,
    entity_status text,
    frequency_cap_max_impressions integer,
    frequency_cap_max_views integer,
    frequency_cap_time_unit text,
    frequency_cap_time_unit_count integer,
    frequency_cap_unlimited boolean,
    "name" text,
    update_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE hashed_phone_number (
    "index" integer,
    contact_info_index integer,
    first_party_and_partner_audience_id text,
    hashed_phone_number text,
    PRIMARY KEY ("index", contact_info_index, first_party_and_partner_audience_id),
    FOREIGN KEY (contact_info_index) REFERENCES contact_info("index"),
    FOREIGN KEY (first_party_and_partner_audience_id) REFERENCES contact_info(first_party_and_partner_audience_id)
);

CREATE TABLE first_party_and_partner_audience (
    id text,
    active_display_audience_size text,
    app_id text,
    audience_source text,
    audience_type text,
    contact_info_list_consent_ad_personalization text,
    contact_info_list_consent_ad_user_data text,
    description text,
    display_audience_size text,
    display_desktop_audience_size text,
    display_mobile_app_audience_size text,
    display_mobile_web_audience_size text,
    display_name text,
    first_party_and_patner_audience_type text,
    gmail_audience_size text,
    membership_duration_days text,
    mobile_device_id_list_consent_ad_personalization text,
    mobile_device_id_list_consent_ad_user_data text,
    "name" text,
    youtube_audience_size text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES first_party_and_partner_audience(id)
);

CREATE TABLE ad_group_assigned_targeting_option (
    id text,
    ad_group_id text,
    age_range_details_age_range text,
    app_category_details_display_name text,
    app_category_details_negative boolean,
    app_category_details_targeting_option_id text,
    app_details_app_id text,
    app_details_app_platform text,
    app_details_display_name text,
    app_details_negative boolean,
    assigned_targeting_option_id_alias text,
    audio_content_type_details_audio_content_type text,
    authorized_seller_status_details_authorized_seller_status text,
    authorized_seller_status_details_targeting_option_id text,
    browser_details_display_name text,
    browser_details_negative boolean,
    browser_details_targeting_option_id text,
    business_chain_details_display_name text,
    business_chain_details_proximity_radius_amount double precision,
    business_chain_details_proximity_radius_unit text,
    business_chain_details_targeting_option_id text,
    carrier_and_isp_details_display_name text,
    carrier_and_isp_details_negative boolean,
    carrier_and_isp_details_targeting_option_id text,
    category_details_display_name text,
    category_details_negative boolean,
    category_details_targeting_option_id text,
    channel_details_channel_id text,
    channel_details_negative boolean,
    content_duration_details_content_duration text,
    content_duration_details_targeting_option_id text,
    content_genre_details_display_name text,
    content_genre_details_negative boolean,
    content_genre_details_targeting_option_id text,
    content_instream_position_details_ad_type text,
    content_instream_position_details_content_instream_position text,
    content_outstream_position_details_ad_type text,
    content_outstream_position_details_content_outstream_position text,
    content_stream_type_details_content_stream_type text,
    content_stream_type_details_targeting_option_id text,
    content_theme_exclusion_details_content_theme text,
    content_theme_exclusion_details_excluded_content_theme text,
    content_theme_exclusion_details_excluded_targeting_option_id text,
    day_and_time_details_day_of_week text,
    day_and_time_details_end_hour integer,
    day_and_time_details_start_hour integer,
    day_and_time_details_time_zone_resolution text,
    device_make_model_details_display_name text,
    device_make_model_details_negative boolean,
    device_make_model_details_targeting_option_id text,
    device_type_details_device_type text,
    device_type_details_youtube_and_partners_bid_multiplier double precision,
    digital_content_label_exclusion_details_excluded_content_rating_tier text,
    environment_details_environment text,
    exchange_details_exchange text,
    gender_details_gender text,
    geo_region_details_display_name text,
    geo_region_details_geo_region_type text,
    geo_region_details_negative boolean,
    geo_region_details_targeting_option_id text,
    household_income_details_household_income text,
    inheritance text,
    inventory_source_details_inventory_source_id text,
    inventory_source_group_details_inventory_source_group_id text,
    keyword_details_keyword text,
    keyword_details_negative boolean,
    language_details_display_name text,
    language_details_negative boolean,
    language_details_targeting_option_id text,
    "name" text,
    native_content_position_details_content_position text,
    negative_keyword_list_details_negative_keyword_list_id text,
    omid_details_omid text,
    on_screen_position_details_ad_type text,
    on_screen_position_details_on_screen_position text,
    on_screen_position_details_targeting_option_id text,
    operating_system_details_display_name text,
    operating_system_details_negative boolean,
    operating_system_details_targeting_option_id text,
    parental_status_details_parental_status text,
    poi_details_display_name text,
    poi_details_latitude double precision,
    poi_details_longitude double precision,
    poi_details_proximity_radius_amount double precision,
    poi_details_proximity_radius_unit text,
    poi_details_targeting_option_id text,
    proximity_location_list_details_proximity_location_list_id text,
    proximity_location_list_details_proximity_radius double precision,
    proximity_location_list_details_proximity_radius_unit text,
    regional_location_list_details_negative boolean,
    regional_location_list_details_regional_location_list_id text,
    sensitive_category_exclusion_details_excluded_sensitive_category text,
    session_position_details_session_position text,
    sub_exchange_details_targeting_option_id text,
    targeting_type text,
    third_party_verifier_details_adloox_adult_explicit_sexual_content text,
    third_party_verifier_details_adloox_arms_ammunition_content text,
    third_party_verifier_details_adloox_crime_harmful_acts_individuals_society_human_rights_violations_content text,
    third_party_verifier_details_adloox_death_injury_military_conflict_content text,
    third_party_verifier_details_adloox_debated_sensitive_social_issue_content text,
    third_party_verifier_details_adloox_display_iab_viewability text,
    third_party_verifier_details_adloox_hate_speech_acts_aggression_content text,
    third_party_verifier_details_adloox_illegal_drugs_tobacco_ecigarettes_vaping_alcohol_content text,
    third_party_verifier_details_adloox_misinformation_content text,
    third_party_verifier_details_adloox_obscenity_profanity_content text,
    third_party_verifier_details_adloox_online_piracy_content text,
    third_party_verifier_details_adloox_spam_harmful_content text,
    third_party_verifier_details_adloox_terrorism_content text,
    third_party_verifier_details_adloox_video_iab_viewability text,
    third_party_verifier_details_double_verify_app_star_rating_avoid_insufficient_star_rating boolean,
    third_party_verifier_details_double_verify_app_star_rating_avoided_star_rating text,
    third_party_verifier_details_double_verify_brand_safety_categories_avoid_unknown_brand_safety_category boolean,
    third_party_verifier_details_double_verify_custom_segment_id text,
    third_party_verifier_details_double_verify_display_viewability_iab text,
    third_party_verifier_details_double_verify_display_viewability_viewable_during text,
    third_party_verifier_details_double_verify_fraud_invalid_traffic_avoid_insufficient_option boolean,
    third_party_verifier_details_double_verify_fraud_invalid_traffic_avoided_fraud_option text,
    third_party_verifier_details_double_verify_video_viewability_player_impression_rate text,
    third_party_verifier_details_double_verify_video_viewability_video_iab text,
    third_party_verifier_details_double_verify_video_viewability_video_viewable_rate text,
    third_party_verifier_details_integral_ad_science_display_viewability text,
    third_party_verifier_details_integral_ad_science_exclude_unrateable boolean,
    third_party_verifier_details_integral_ad_science_excluded_ad_fraud_risk text,
    third_party_verifier_details_integral_ad_science_excluded_adult_risk text,
    third_party_verifier_details_integral_ad_science_excluded_alcohol_risk text,
    third_party_verifier_details_integral_ad_science_excluded_drugs_risk text,
    third_party_verifier_details_integral_ad_science_excluded_gambling_risk text,
    third_party_verifier_details_integral_ad_science_excluded_hate_speech_risk text,
    third_party_verifier_details_integral_ad_science_excluded_illegal_downloads_risk text,
    third_party_verifier_details_integral_ad_science_excluded_offensive_language_risk text,
    third_party_verifier_details_integral_ad_science_excluded_violence_risk text,
    third_party_verifier_details_integral_ad_science_traq_score_option text,
    third_party_verifier_details_integral_ad_science_video_viewability text,
    url_details_negative boolean,
    url_details_url text,
    user_rewarded_content_details_targeting_option_id text,
    user_rewarded_content_details_user_rewarded_content text,
    video_player_size_details_video_player_size text,
    viewability_details_viewability text,
    youtube_channel_details_channel_id text,
    youtube_channel_details_negative boolean,
    youtube_video_details_negative boolean,
    youtube_video_details_video_id text,
    PRIMARY KEY (id, ad_group_id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id)
);
