CREATE TABLE purchase_vendor (
    id text,
    active text,
    address_id text,
    contact_id text,
    created_at text,
    import_set_id text,
    "name" text,
    public_id text,
    sort_key text,
    updated_at timestamp,
    uuid text,
    vendor_import_batch_id text,
    PRIMARY KEY (id)
);

CREATE TABLE location (
    id text,
    created_by_user_id text,
    updated_by_user_id text,
    active text,
    address_id text,
    address_revision_id text,
    cash_discount_item_conditions text,
    cash_discount_rate text,
    created_at text,
    credit_cards_configured text,
    internal text,
    metadata jsonb,
    metadata_private text,
    "name" text,
    price_list_id text,
    public_id text,
    settings jsonb,
    timezone_identifier_id text,
    updated_at timestamp,
    uuid text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE TABLE purchase_order_line (
    id text,
    purchase_order_id text,
    item_id text,
    allocation jsonb,
    created_at text,
    extended_cost text,
    item_vendor_detail_custom text,
    line_display_id text,
    "name" text,
    open_cost text,
    original_cost text,
    po_line_import_batch_id text,
    qty text,
    qty_expected text,
    qty_received text,
    received_cost text,
    sort_key text,
    "status" text,
    unit_cost text,
    updated_at timestamp,
    vendor_item_public_id text,
    PRIMARY KEY (id, purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE grid_controlled_item_field (
    "index" text,
    item_grid_id text,
    grid_controlled_item_field text,
    PRIMARY KEY ("index", item_grid_id),
    FOREIGN KEY (item_grid_id) REFERENCES item_grid(id)
);

CREATE TABLE item_grid_image (
    id text,
    item_grid_dimension_value_id text,
    item_grid_id text,
    created_at text,
    is_primary text,
    kind text,
    metadata_private text,
    new_thumbnail_url text,
    new_url text,
    old_thumbnail_url text,
    old_url text,
    url text,
    variant_thumbnail_url text,
    PRIMARY KEY (id),
    FOREIGN KEY (item_grid_dimension_value_id) REFERENCES item_grid_image_dimension_filter_value(id),
    FOREIGN KEY (item_grid_id) REFERENCES item_grid(id)
);

CREATE TABLE item_grid_image_dimension_filter_value (
    id text,
    item_grid_id text,
    dimension_id text,
    primary_image_id text,
    "value" text,
    PRIMARY KEY (id, item_grid_id),
    FOREIGN KEY (item_grid_id) REFERENCES item_grid(id)
);

CREATE TABLE item_grid (
    id text,
    created_by_user_id text,
    updated_by_user_id text,
    active text,
    created_at text,
    default_lookup_id text,
    default_price_list_id text,
    description text,
    has_empty_cells text,
    has_images text,
    image_dimension_custom_field_id text,
    image_dimension_id text,
    image_dimension_name text,
    import_set_id text,
    item_available_online text,
    long_description text,
    metadata text,
    metadata_private text,
    primary_image_id text,
    public_id text,
    sort_key text,
    updated_at timestamp,
    updating text,
    uuid text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE TABLE inventory_value_search (
    item_id text,
    location_id text,
    qty text,
    qty_available text,
    qty_committed text,
    qty_contributed_to_unit_cost text,
    qty_in_transit text,
    qty_on_hand text,
    qty_on_po text,
    qty_with_customer text,
    unit_cost text,
    PRIMARY KEY (item_id, location_id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE purchase_receipt_line (
    id text,
    purchase_receipt_id text,
    item_id text,
    created_at text,
    extended_cost text,
    order_line_id text,
    qty text,
    qty_expected text,
    qty_unauthorized text,
    unit_cost text,
    updated_at timestamp,
    vendor_item_public_id text,
    PRIMARY KEY (id, purchase_receipt_id),
    FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_receipt(id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item (
    id text,
    created_by_user_id text,
    grid_id text,
    updated_by_user_id text,
    active text,
    add_on_for_items_matching_filter text,
    add_on_item_filter text,
    allow_fractional_qty text,
    available_online text,
    cost text,
    created_at text,
    default_lookup_id text,
    default_price_list_id text,
    depth text,
    depth_unit text,
    description text,
    dynamic_margin text,
    financial_class_id text,
    has_images text,
    height text,
    height_unit text,
    import_batch_id text,
    import_set_id text,
    long_description text,
    metadata jsonb,
    metadata_private text,
    original_price text,
    price text,
    primary_barcode text,
    primary_image_id text,
    primary_vendor_id text,
    product_type text,
    prompt_for_description text,
    prompt_for_price text,
    public_id text,
    sort_key text,
    track_inventory text,
    "type" text,
    updated_at timestamp,
    use_dynamic_margin text,
    uuid text,
    weight text,
    weight_unit text,
    width text,
    width_unit text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (grid_id) REFERENCES item_grid(id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE TABLE purchase_order (
    id text,
    created_by_user_id text,
    first_emailed_by_user_id text,
    last_emailed_by_user_id text,
    purchase_vendor_id text,
    receive_at_location_id text,
    allocated text,
    allocated_location_ids jsonb,
    created_at text,
    description text,
    end_shipment_at text,
    export_email text,
    first_emailed_at text,
    freight_cost text,
    import_set_id text,
    initial_margin_ratio text,
    last_emailed_at text,
    location_ids jsonb,
    nuorder_id text,
    overdue text,
    po_import_batch_id text,
    public_id text,
    sort_key text,
    start_shipment_at text,
    "status" text,
    total_cost text,
    total_open_cost text,
    total_open_price text,
    total_open_qty text,
    total_price text,
    total_qty text,
    total_received_cost text,
    total_received_price text,
    total_received_qty text,
    total_unauthorized_cost text,
    total_unauthorized_qty text,
    updated_at timestamp,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (first_emailed_by_user_id) REFERENCES users(id),
    FOREIGN KEY (last_emailed_by_user_id) REFERENCES users(id),
    FOREIGN KEY (purchase_vendor_id) REFERENCES purchase_vendor(id),
    FOREIGN KEY (receive_at_location_id) REFERENCES location(id)
);

CREATE TABLE purchase_receipt (
    id text,
    purchase_order_id text,
    receive_at_location_id text,
    completed_at text,
    created_at text,
    freight_cost text,
    items_cost text,
    local_completed_at text,
    local_created_at text,
    local_updated_at text,
    public_id text,
    require_unauthorized_quantities_acknowledgement text,
    "status" text,
    total_cost text,
    total_cost_unauthorized text,
    total_qty text,
    total_qty_expected text,
    total_qty_unauthorized text,
    updated_at timestamp,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (receive_at_location_id) REFERENCES location(id)
);

CREATE TABLE purchase_return_line (
    id text,
    purchase_return_id text,
    item_id text,
    created_at text,
    extended_cost text,
    qty text,
    unit_cost text,
    updated_at timestamp,
    vendor_item_public_id text,
    PRIMARY KEY (id, purchase_return_id),
    FOREIGN KEY (purchase_return_id) REFERENCES purchase_return(id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE sale_ticket_line (
    id text,
    created_by_user_id text,
    customer_id text,
    item_id text,
    sales_transaction_id text,
    updated_by_user_id text,
    action_id text,
    add_on_item_lines jsonb,
    address_id text,
    address_revision_id text,
    adjusted_unit_price text,
    allowable_custom_field_keys jsonb,
    bundle_id text,
    bundle_item_id text,
    cash_discounted_value text,
    created_at text,
    current_unit_price text,
    deleted text,
    deleted_add_on_item_lines jsonb,
    deposit_item_tracking_number_id text,
    description text,
    discount_value text,
    final_unit_price text,
    gift_card_balance_loaded text,
    gift_card_id text,
    image_thumbnail_url text,
    image_url text,
    item_line_id text,
    item_metadata_private text,
    item_public_id text,
    lookup_id text,
    loyalty_point text,
    manually_added text,
    metadata_private text,
    order_discount_id text,
    order_line_id text,
    original_unit_price text,
    original_value text,
    permanent text,
    possible_add_ons jsonb,
    price_adjustments jsonb,
    price_list_id text,
    prompt_for_missing_fields jsonb,
    prompt_for_missing_reason_codes jsonb,
    public_id text,
    qty text,
    reason_codes jsonb,
    removal_reason text,
    sales_rep text,
    sales_rep_ids jsonb,
    sales_transaction_line_id text,
    shipping_line_id text,
    shipping_method_id text,
    source_id text,
    source_type text,
    tax_rule_id text,
    ticket_level_discount text,
    ticket_level_discounted_value text,
    "type" text,
    unit_cost text,
    unit_price text,
    updated_at timestamp,
    "value" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (sales_transaction_id) REFERENCES sale_ticket(id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE TABLE customer (
    id text,
    active text,
    address_city text,
    address_country text,
    address_current_revision_hash text,
    address_current_revision_id text,
    address_full_address text,
    address_id text,
    address_line_1 text,
    address_line_2 text,
    address_metadata jsonb,
    address_metadata_private text,
    address_phone text,
    address_postal_code text,
    address_revision_hash text,
    address_square_feet text,
    address_state text,
    address_street_address text,
    address_type text,
    address_uuid text,
    billing_address_id text,
    created_at text,
    customer_import_batch_id text,
    default_lookup_id text,
    deleted_at text,
    email text,
    first_name text,
    import_set_id text,
    last_name text,
    loyalty_points_balance text,
    loyalty_points_total text,
    metadata jsonb,
    metadata_private text,
    "name" text,
    phone_number text,
    promotional_email text,
    promotional_message text,
    public_id text,
    shipping_address_id text,
    sort_key text,
    "type" text,
    updated_at timestamp,
    uuid text,
    -- address_custom_* (dynamic column),
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE purchase_return (
    id text,
    created_by_user_id text,
    purchase_vendor_id text,
    return_from_location_id text,
    updated_by_user_id text,
    completed_at text,
    created_at text,
    local_completed_at text,
    local_created_at text,
    local_updated_at text,
    public_id text,
    "status" text,
    total_cost text,
    total_qty text,
    updated_at timestamp,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (purchase_vendor_id) REFERENCES purchase_vendor(id),
    FOREIGN KEY (return_from_location_id) REFERENCES location(id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    active text,
    all_location text,
    created_at text,
    email text,
    email_verification_sent_at text,
    email_verified_at text,
    eula_accepted text,
    eula_last_reviewed_at text,
    external text,
    failed_auth_attempt text,
    failed_pin_attempt text,
    first_name text,
    has_pincode text,
    internal text,
    is_account_admin text,
    is_account_owner text,
    is_admin text,
    last_name text,
    locked_at text,
    login text,
    mfa_liability_accepted text,
    mfa_liability_accepted_at text,
    mfa_required text,
    "name" text,
    phone text,
    public_id text,
    roles_name jsonb,
    sales_rep text,
    sso_id text,
    updated_at timestamp,
    uuid text,
    PRIMARY KEY (id)
);

CREATE TABLE sale_ticket_rep (
    sales_rep_id text,
    sale_ticket_id text,
    PRIMARY KEY (sales_rep_id, sale_ticket_id),
    FOREIGN KEY (sale_ticket_id) REFERENCES sale_ticket(id)
);

CREATE TABLE sale_ticket (
    id text,
    created_by_user_id text,
    customer_id text,
    order_id text,
    source_location_id text,
    updated_by_user_id text,
    balance text,
    billing_address_id text,
    cash_balance text,
    cash_discount_rate text,
    cash_discount_tax_lines jsonb,
    cash_round text,
    cash_total text,
    change text,
    completed text,
    completed_at text,
    coupon_id text,
    created_at text,
    local_completed_at text,
    local_created_at text,
    local_updated_at text,
    metadata jsonb,
    metadata_private text,
    minimum_deposit_value text,
    original_subtotal text,
    parent_transaction_id text,
    payment_exception text,
    penny_rounded_balance text,
    penny_rounded_cash_balance text,
    penny_rounded_cash_total text,
    penny_rounded_change text,
    promotion_state_coupon_id jsonb,
    public_id text,
    read_only text,
    recalculate text,
    sales_rep text,
    search_vector text,
    signatures_required text,
    station_id text,
    "status" text,
    total text,
    total_discount text,
    total_item_qty text,
    total_paid text,
    "type" text,
    updated_at timestamp,
    value_of_all_added_item_discount_lines text,
    voided text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (source_location_id) REFERENCES location(id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);
