CREATE TABLE action_update (
    id text,
    action_id text,
    action_date text,
    action_tracker_id text,
    action_uri text,
    ad_id text,
    campaign_id text,
    catalog_category text,
    catalog_description text,
    catalog_manufacturer text,
    catalog_name text,
    catalog_original_format_category text,
    catalog_sub_category text,
    category text,
    clearing_date text,
    contract_id text,
    currency text,
    default_payout text,
    default_payout_currency text,
    delta_amount text,
    delta_payout text,
    event_code text,
    event_type_id text,
    event_type_name text,
    locking_date text,
    o_id text,
    payout_level text,
    paystub_id text,
    quantity text,
    reporting_state text,
    shared_id text,
    sku text,
    "state" text,
    state_detail text,
    state_detail_description text,
    sub_category text,
    sub_id_1 text,
    sub_id_2 text,
    sub_id_3 text,
    update_date text,
    uri text,
    PRIMARY KEY (id, action_id),
    FOREIGN KEY (action_id) REFERENCES "action"(id)
);

CREATE TABLE catalog_item_promotion (
    catalog_id text,
    catalog_item_id text,
    promotion_id text,
    PRIMARY KEY (catalog_id, catalog_item_id, promotion_id),
    FOREIGN KEY (catalog_id) REFERENCES catalog_item(catalog_id),
    FOREIGN KEY (catalog_item_id) REFERENCES catalog_item(id),
    FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE catalog_item_advertiser_format_categorogies (
    "index" text,
    catalog_id text,
    catalog_item_id text,
    advertiser_format_categories text,
    PRIMARY KEY ("index", catalog_id, catalog_item_id),
    FOREIGN KEY (catalog_id) REFERENCES catalog_item(catalog_id),
    FOREIGN KEY (catalog_item_id) REFERENCES catalog_item(id)
);

CREATE TABLE catalog_item_color (
    "index" text,
    catalog_id text,
    catalog_item_id text,
    colors text,
    PRIMARY KEY ("index", catalog_id, catalog_item_id),
    FOREIGN KEY (catalog_id) REFERENCES catalog_item(catalog_id),
    FOREIGN KEY (catalog_item_id) REFERENCES catalog_item(id)
);

CREATE TABLE catalog_item (
    id text,
    catalog_id text,
    additional_image_url jsonb,
    adult text,
    age_group text,
    age_range_max text,
    age_range_min text,
    age_range_unit text,
    asin text,
    bullet jsonb,
    campaign_id text,
    campaign_name text,
    catalog_item_id text,
    category text,
    "condition" text,
    currency text,
    current_price text,
    description text,
    discount_percentage text,
    estimated_ship_date text,
    expiration_date text,
    gender text,
    gtin text,
    gtin_type text,
    image_url text,
    is_parent text,
    item_group_id text,
    label jsonb,
    launch_date text,
    manufacturer text,
    material text,
    mobile_url text,
    money_1 text,
    money_2 text,
    money_3 text,
    mpn text,
    multi_pack text,
    "name" text,
    numeric_1 text,
    numeric_2 text,
    numeric_3 text,
    original_format_category text,
    original_format_category_id text,
    original_price text,
    parent_name text,
    parent_sku text,
    pattern text,
    product_bid text,
    shipping_height text,
    shipping_label text,
    shipping_length text,
    shipping_length_unit text,
    shipping_rate text,
    shipping_weight text,
    shipping_weight_unit text,
    shipping_width text,
    "size" text,
    size_unit text,
    stock_availability text,
    sub_category text,
    text_1 text,
    text_2 text,
    text_3 text,
    uri text,
    url text,
    weight text,
    weight_unit text,
    PRIMARY KEY (id, catalog_id),
    FOREIGN KEY (catalog_id) REFERENCES catalog(id)
);

CREATE TABLE catalog_service_area (
    "index" text,
    catalog_id text,
    service_area text,
    PRIMARY KEY ("index", catalog_id),
    FOREIGN KEY (catalog_id) REFERENCES catalog(id)
);

CREATE TABLE catalog_location (
    "index" text,
    catalog_id text,
    location text,
    PRIMARY KEY ("index", catalog_id),
    FOREIGN KEY (catalog_id) REFERENCES catalog(id)
);

CREATE TABLE catalog (
    id text,
    advertiser_id text,
    advertiser_location text,
    advertiser_name text,
    campaign_id text,
    campaign_name text,
    currency text,
    date_last_updated text,
    ftp_locations jsonb,
    items_uri text,
    languages text,
    "name" text,
    number_of_item text,
    uri text,
    PRIMARY KEY (id)
);

CREATE TABLE "action" (
    action_tracker_id text,
    ad_id text,
    campaign_id text,
    id text,
    action_tracker_name text,
    amount text,
    campaign_name text,
    cleared_date text,
    creation_date text,
    currency text,
    customer_area text,
    customer_city text,
    customer_country text,
    customer_region text,
    delta_amount text,
    delta_payout text,
    event_code text,
    event_date text,
    intended_amount text,
    intended_payout text,
    locking_date text,
    order_id text,
    payout text,
    promo_code text,
    referring_date text,
    referring_domain text,
    referring_type text,
    shared_id text,
    "state" text,
    sub_id_1 text,
    sub_id_2 text,
    sub_id_3 text,
    uri text,
    PRIMARY KEY (action_tracker_id, ad_id, campaign_id, id)
);

CREATE TABLE promotion (
    id text,
    advertiser_id text,
    advertiser_location text,
    advertiser_name text,
    effective_date text,
    file_id text,
    generic_redemption_code text,
    item_uri text,
    title text,
    uri text,
    PRIMARY KEY (id)
);

CREATE TABLE user_access_right_permission (
    "index" text,
    access_right_role text,
    user_id text,
    permission text,
    PRIMARY KEY ("index", access_right_role, user_id),
    FOREIGN KEY (access_right_role) REFERENCES user_access_right("role"),
    FOREIGN KEY (user_id) REFERENCES user_access_right(user_id)
);

CREATE TABLE user_access_right (
    "role" text,
    user_id text,
    PRIMARY KEY ("role", user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    created_by text,
    date_last_updated text,
    first_name text,
    invitee_name text,
    joined_date text,
    languages text,
    last_name text,
    last_updated_by text,
    "state" text,
    "type" text,
    uri text,
    username text,
    PRIMARY KEY (id)
);

CREATE TABLE click_brand_related (
    "index" text,
    click_id text,
    ad_campaign text,
    ad_group text,
    channel text,
    keyword text,
    match_type text,
    PRIMARY KEY ("index", click_id),
    FOREIGN KEY (click_id) REFERENCES click(id)
);

CREATE TABLE click_partner_related (
    "index" text,
    click_id text,
    sub_id_1 text,
    sub_id_2 text,
    sub_id_3 text,
    PRIMARY KEY ("index", click_id),
    FOREIGN KEY (click_id) REFERENCES click(id)
);

CREATE TABLE click (
    id text,
    ad_id text,
    ad_name text,
    ad_type text,
    bid_keyword text,
    browser text,
    campaign_id text,
    campaign_name text,
    cpc_bid text,
    customer_area text,
    customer_city text,
    customer_country text,
    customer_region text,
    deal_name text,
    deal_scope text,
    deal_type text,
    device_family text,
    device_type text,
    event_date text,
    ip_address text,
    landing_page_url text,
    media_id text,
    media_name text,
    os text,
    payout text,
    product_sku text,
    profile_id text,
    referring_domain text,
    referring_url text,
    search_text text,
    shared_id text,
    traffic_category text,
    traffic_source text,
    unique_click text,
    PRIMARY KEY (id)
);
