CREATE TABLE payment (
    id text,
    charge_customer_id text,
    charge_payment_source_customer_id text,
    customer_id text,
    ach_sender_id text,
    amount text,
    applied_to jsonb,
    balance text,
    charge_amount text,
    charge_amount_refunded text,
    charge_created_at text,
    charge_currency text,
    charge_disputed text,
    charge_failure_message text,
    charge_gateway text,
    charge_gateway_id text,
    charge_id text,
    charge_payment_source_account_holder_name text,
    charge_payment_source_account_holder_type text,
    charge_payment_source_bank_name text,
    charge_payment_source_chargeable text,
    charge_payment_source_country text,
    charge_payment_source_created_at text,
    charge_payment_source_currency text,
    charge_payment_source_failure_reason text,
    charge_payment_source_gateway text,
    charge_payment_source_gateway_customer text,
    charge_payment_source_gateway_id text,
    charge_payment_source_id text,
    charge_payment_source_last_4_card_digits text,
    charge_payment_source_merchant_account text,
    charge_payment_source_receipt_email text,
    charge_payment_source_routing_number text,
    charge_payment_source_type text,
    charge_payment_source_updated_at text,
    charge_payment_source_verified text,
    charge_receipt_email text,
    charge_refund jsonb,
    charge_refunded text,
    charge_status text,
    charge_updated_at text,
    created_at text,
    currency text,
    "date" text,
    matched text,
    method text,
    note text,
    pdf_url text,
    reference text,
    "source" text,
    updated_at text,
    voided text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (charge_customer_id) REFERENCES customer(id),
    FOREIGN KEY (charge_payment_source_customer_id) REFERENCES customer(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE contact (
    id text,
    customer_id text,
    address_1 text,
    address_2 text,
    city text,
    country text,
    created_at text,
    department text,
    email text,
    is_primary text,
    "name" text,
    phone text,
    postal_code text,
    "role" text,
    send_new_invoice text,
    sms_enabled text,
    "state" text,
    title text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE credit_note_attachment (
    id text,
    credit_note_id text,
    created_at text,
    file_created_at text,
    file_id text,
    file_name text,
    file_size text,
    file_type text,
    file_updated_at text,
    file_url text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id)
);

CREATE TABLE plan_tier (
    "index" text,
    plan_id text,
    max_qty text,
    min_qty text,
    unit_cost text,
    PRIMARY KEY ("index", plan_id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan (
    id text,
    amount text,
    catalog_item text,
    created_at text,
    currency text,
    "interval" text,
    interval_count text,
    "name" text,
    pricing_mode text,
    quantity_type text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE credit_balance_adjustment (
    id text,
    customer_id text,
    amount text,
    created_at text,
    currency text,
    "date" text,
    note text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE event (
    id text,
    timestamps text,
    "type" text,
    -- custom_* (dynamic column),
    -- previous_* (dynamic column),
    -- user_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE note (
    id text,
    customer_id text,
    invoice_id text,
    created_at text,
    note text,
    updated_at timestamp,
    user_created_at text,
    user_email text,
    user_first_name text,
    user_id text,
    user_last_name text,
    user_registered text,
    user_two_factor_enabled text,
    user_updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE customer (
    id text,
    parent_customer text,
    payment_source_id text,
    ach_gateway text,
    ach_gateway_id text,
    active text,
    address_1 text,
    address_2 text,
    attention_to text,
    autopay text,
    autopay_delay_days text,
    avalara_entity_use_code text,
    avalara_exemption_number text,
    bill_to_parent text,
    cc_gateway text,
    cc_gateway_id text,
    chase text,
    chasing_cadence text,
    city text,
    consolidated text,
    convenience_fee text,
    country text,
    created_at text,
    credit_hold text,
    credit_limit text,
    currency text,
    email text,
    languages text,
    late_fee_schedule text,
    late_fee_schedule_id text,
    "name" text,
    network_connection text,
    network_connection_id text,
    next_chase_step text,
    note text,
    number text,
    owner text,
    payment_term text,
    phone text,
    postal_code text,
    sign_up_page text,
    sign_up_url text,
    "state" text,
    statement_pdf_url text,
    statement_url text,
    tax jsonb,
    tax_id text,
    taxable text,
    "type" text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (parent_customer) REFERENCES customer(id),
    FOREIGN KEY (payment_source_id) REFERENCES payment_source(id)
);

CREATE TABLE current_balance_history (
    "index" text,
    _fivetran_id text,
    balance text,
    currency text,
    timestamps text,
    PRIMARY KEY ("index", _fivetran_id),
    FOREIGN KEY (_fivetran_id) REFERENCES current_balance(_fivetran_id)
);

CREATE TABLE current_balance (
    _fivetran_id text,
    customer_id text,
    available_credit text,
    currency text,
    due_now text,
    open_credit_note text,
    past_due text,
    total_outstanding text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE task (
    id text,
    customer_id text,
    "action" text,
    chase_step_id text,
    complete text,
    completed_by_user_id text,
    completed_date text,
    created_at text,
    due_date text,
    "name" text,
    updated_at timestamp,
    user_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE payment_plan_installment (
    id text,
    payment_plan_id text,
    amount text,
    balance text,
    "date" text,
    PRIMARY KEY (id, payment_plan_id),
    FOREIGN KEY (payment_plan_id) REFERENCES payment_plan(id)
);

CREATE TABLE payment_plan (
    id text,
    invoice_id text,
    approval_id text,
    approval_ip text,
    approval_timestamps text,
    approval_user_agent text,
    created_at text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE estimate_attachment (
    id text,
    estimate_id text,
    created_at text,
    file_created_at text,
    file_id text,
    file_name text,
    file_size text,
    file_type text,
    file_updated_at text,
    file_url text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id)
);

CREATE TABLE subscription_addon (
    id text,
    subscription_id text,
    created_at text,
    description text,
    plan text,
    quantity text,
    updated_at text,
    PRIMARY KEY (id, subscription_id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription (
    id text,
    customer_id text,
    plan_id text,
    bill_in text,
    bill_in_advance_day text,
    cancel_at_period_end text,
    canceled_at text,
    contract_period_end text,
    contract_period_start text,
    contract_renewal_cycle text,
    contract_renewal_mode text,
    created_at text,
    cycle text,
    discount jsonb,
    mrr text,
    paused text,
    period_end text,
    period_start text,
    quantity text,
    recurring_total text,
    ship_to jsonb,
    start_date text,
    "status" text,
    taxes jsonb,
    updated_at text,
    url text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE pending_line_item (
    id text,
    customer_id text,
    amount text,
    catalog_item text,
    description text,
    discount jsonb,
    discountable text,
    metadata jsonb,
    "name" text,
    quantity text,
    taxable text,
    taxes jsonb,
    "type" text,
    unit_cost text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE invoice_item (
    id text,
    invoice_id text,
    amount text,
    catalog_item text,
    created_at text,
    description text,
    discount jsonb,
    discountable text,
    plan_id text,
    quantity text,
    taxable text,
    taxes jsonb,
    "type" text,
    unit_cost text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_tax (
    id text,
    invoice_id text,
    amount text,
    tax_rate jsonb,
    updated_at text,
    PRIMARY KEY (id, invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_discount (
    id text,
    invoice_id text,
    amount text,
    coupon jsonb,
    expire text,
    from_payment_term text,
    updated_at text,
    PRIMARY KEY (id, invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_shipping (
    "index" text,
    invoice_id text,
    address_1 text,
    address_2 text,
    attention_to text,
    city text,
    country text,
    created_at text,
    "name" text,
    postal_code text,
    "state" text,
    updated_at text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice (
    id text,
    customer_id text,
    payment_plan_id text,
    subscription_id text,
    attempt_count text,
    autopay text,
    balance text,
    chase text,
    closed text,
    created_at text,
    csv_url text,
    currency text,
    "date" text,
    draft text,
    due_date text,
    late_fees text,
    "name" text,
    needs_attention text,
    network_document text,
    network_document_id text,
    next_chase_on text,
    next_payment_attempt text,
    note text,
    number text,
    paid text,
    payment_source text,
    payment_term text,
    payment_url text,
    pdf_url text,
    purchase_order text,
    ship_to_address_1 text,
    ship_to_address_2 text,
    ship_to_attention_to text,
    ship_to_city text,
    ship_to_country text,
    ship_to_created_at text,
    ship_to_name text,
    ship_to_postal_code text,
    ship_to_state text,
    ship_to_updated_at text,
    "status" text,
    subscription text,
    subtotal text,
    total text,
    updated_at text,
    url text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (payment_plan_id) REFERENCES payment_plan(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE invoice_attachment (
    id text,
    invoice_id text,
    created_at text,
    file_created_at text,
    file_id text,
    file_name text,
    file_size text,
    file_type text,
    file_updated_at text,
    file_url text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE payment_source (
    id text,
    customer_id text,
    bank_name text,
    brand text,
    currency text,
    expiry_month text,
    expiry_year text,
    funding text,
    last_4_card_digits text,
    object text,
    routing_number text,
    updated_at text,
    verified text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE item (
    id text,
    avalara_location_code text,
    avalara_tax_code text,
    created_at text,
    currency text,
    description text,
    discountable text,
    gl_account text,
    "name" text,
    taxable text,
    "type" text,
    unit_cost text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE coupon (
    id text,
    created_at text,
    currency text,
    duration text,
    exclusive text,
    expiration_date text,
    is_percent text,
    max_redemption text,
    "name" text,
    updated_at text,
    "value" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE tax_rate (
    id text,
    created_at text,
    currency text,
    inclusive text,
    is_percent text,
    "name" text,
    updated_at text,
    "value" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE credit_note_item (
    id text,
    credit_note_id text,
    amount text,
    catalog_item text,
    created_at text,
    description text,
    discount jsonb,
    discountable text,
    "name" text,
    quantity text,
    taxable text,
    taxes jsonb,
    "type" text,
    unit_cost text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id)
);

CREATE TABLE credit_note_tax (
    id text,
    credit_note_id text,
    amount text,
    tax_rate jsonb,
    PRIMARY KEY (id, credit_note_id),
    FOREIGN KEY (credit_note_id) REFERENCES credit_note(id)
);

CREATE TABLE credit_note (
    id text,
    customer_id text,
    invoice_id text,
    balance text,
    closed text,
    created_at text,
    currency text,
    "date" text,
    discount jsonb,
    draft text,
    "name" text,
    network_document text,
    network_document_id text,
    note text,
    number text,
    paid text,
    pdf_url text,
    purchase_order text,
    shipping jsonb,
    "status" text,
    subtotal text,
    total text,
    updated_at text,
    url text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE estimate_item (
    id text,
    estimate_id text,
    amount text,
    catalog_item text,
    created_at text,
    description text,
    discount jsonb,
    discountable text,
    "name" text,
    quantity text,
    taxable text,
    "type" text,
    unit_cost text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id)
);

CREATE TABLE estimate_tax (
    id text,
    estimate_id text,
    amount text,
    tax_rate jsonb,
    PRIMARY KEY (id, estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id)
);

CREATE TABLE estimate (
    id text,
    customer_id text,
    invoice_id text,
    approval text,
    approved text,
    closed text,
    created_at text,
    currency text,
    "date" text,
    deposit text,
    deposit_paid text,
    discount jsonb,
    draft text,
    expiration_date text,
    "name" text,
    network_document text,
    network_document_id text,
    note text,
    number text,
    payment_terms text,
    pdf_url text,
    purchase_order text,
    ship_to jsonb,
    shipping jsonb,
    "status" text,
    subtotal text,
    total text,
    updated_at text,
    url text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);
