CREATE TABLE app_store_app_version_review (
    app_version_id text,
    review_id text,
    PRIMARY KEY (app_version_id, review_id),
    FOREIGN KEY (app_version_id) REFERENCES app_store_app_version(id),
    FOREIGN KEY (review_id) REFERENCES app_store_review(id)
);

CREATE TABLE app_store_discovery_and_engagement_detailed_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    campaign text,
    counts integer,
    device text,
    engagement_type text,
    event text,
    page_title text,
    page_type text,
    platform_version text,
    source_info text,
    source_type text,
    territory text,
    unique_counts integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_first_annual_detailed (
    _fivetran_id text,
    vendor_number integer,
    app_id bigint,
    app_name text,
    channel text,
    first_annual_installs integer,
    install_type text,
    os_version text,
    requested_report_date text,
    territory text,
    total_installs integer,
    PRIMARY KEY (_fivetran_id, vendor_number, app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_subscription_offer_code_redemption (
    _fivetran_id text,
    vendor_number integer,
    app_apple_id bigint,
    app_name text,
    "date" text,
    offer_code text,
    offer_reference_name text,
    redemptions integer,
    requested_report_date text,
    subscription_apple_id bigint,
    subscription_name text,
    territory text,
    PRIMARY KEY (_fivetran_id, vendor_number, app_apple_id),
    FOREIGN KEY (app_apple_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_app (
    id bigint,
    content_rights_declaration text,
    "name" text,
    primary_locale text,
    subscription_status_url text,
    subscription_status_url_for_sandbox text,
    subscription_status_url_version text,
    subscription_status_url_version_for_sandbox text,
    was_made_for_kids boolean,
    PRIMARY KEY (id)
);

CREATE TABLE app_session_standard_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_download_date text,
    app_version text,
    device text,
    page_type text,
    platform_version text,
    sessions integer,
    source_type text,
    territory text,
    total_session_duration integer,
    unique_devices integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_purchase_standard_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_download_date text,
    content_apple_identifier text,
    content_name text,
    device text,
    page_type text,
    paying_users integer,
    payment_method text,
    platform_version text,
    pre_order text,
    proceeds_in_usd double precision,
    purchase_type text,
    purchases integer,
    sales_in_usd double precision,
    source_type text,
    territory text,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_download_standard_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_version text,
    counts integer,
    device text,
    download_type text,
    page_type text,
    platform_version text,
    pre_order text,
    source_type text,
    territory text,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_subscription_event_summary (
    _fivetran_id text,
    vendor_number integer,
    app_apple_id bigint,
    app_name text,
    cancellation_reason text,
    client text,
    consecutive_paid_periods integer,
    country text,
    days_before_canceling integer,
    days_canceled integer,
    device text,
    event text,
    event_date text,
    marketing_opt_in text,
    marketing_opt_in_duration text,
    original_start_date text,
    paid_service_days_recovered integer,
    preserved_pricing text,
    previous_subscription_apple_id bigint,
    previous_subscription_name text,
    proceeds_reason text,
    promotional_offer_id text,
    promotional_offer_name text,
    quantity integer,
    requested_report_date text,
    standard_subscription_duration text,
    "state" text,
    subscription_apple_id bigint,
    subscription_group_id bigint,
    subscription_name text,
    subscription_offer_duration text,
    subscription_offer_type text,
    PRIMARY KEY (_fivetran_id, vendor_number)
);

CREATE TABLE financial_detail (
    _fivetran_id text,
    country_code text,
    vendor_number integer,
    app_id bigint,
    country_of_sale text,
    customer_currency text,
    customer_price double precision,
    developer_name text,
    end_date text,
    extended_partner_share double precision,
    filename text,
    order_type text,
    partner_share double precision,
    partner_share_currency text,
    product_type_identifier text,
    promo_code text,
    quantity integer,
    region text,
    requested_report_date text,
    sale_or_return text,
    settlement_date text,
    sku text,
    start_date text,
    title text,
    transaction_date text,
    PRIMARY KEY (_fivetran_id, country_code, vendor_number, app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_installation_and_deletion_detailed_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_download_date text,
    app_version text,
    campaign text,
    counts integer,
    device text,
    download_type text,
    event text,
    page_title text,
    page_type text,
    platform_version text,
    source_info text,
    source_type text,
    territory text,
    unique_devices integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_summary_daily (
    _fivetran_id text,
    vendor_number integer,
    app_id bigint,
    begin_date text,
    category text,
    client text,
    cmb text,
    country_code text,
    currency_of_proceeds text,
    customer_currency text,
    customer_price double precision,
    developer text,
    developer_proceeds double precision,
    device text,
    end_date text,
    order_type text,
    parent_identifier text,
    period text,
    preserved_pricing text,
    proceeds_reason text,
    product_type_identifier text,
    promo_code text,
    provider text,
    provider_country text,
    requested_report_date text,
    sku text,
    subscription text,
    supported_platforms text,
    title text,
    units double precision,
    version text,
    PRIMARY KEY (_fivetran_id, vendor_number, app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_subscription_summary (
    _fivetran_id text,
    vendor_number integer,
    active_free_trial_introductory_offer_subscriptions integer,
    active_pay_as_you_go_introductory_offer_subscriptions integer,
    active_pay_up_front_introductory_offer_subscriptions integer,
    active_standard_price_subscriptions integer,
    app_apple_id bigint,
    app_name text,
    billing_retry integer,
    client text,
    country text,
    customer_currency text,
    customer_price double precision,
    "date" text,
    developer_proceeds double precision,
    device text,
    free_trial_offer_code_subscriptions integer,
    free_trial_promotional_offer_subscriptions integer,
    free_trial_win_back_offers integer,
    grace_period integer,
    marketing_opt_ins integer,
    pay_as_you_go_offer_code_subscriptions integer,
    pay_as_you_go_promotional_offer_subscriptions integer,
    pay_as_you_go_win_back_offers integer,
    pay_up_front_offer_code_subscriptions integer,
    pay_up_front_promotional_offer_subscriptions integer,
    pay_up_front_win_back_offers integer,
    preserved_pricing text,
    proceeds_currency text,
    proceeds_reason text,
    promotional_offer_id text,
    requested_report_date text,
    standard_subscription_duration text,
    "state" text,
    subscribers integer,
    subscription_apple_id bigint,
    subscription_group_id bigint,
    subscription_name text,
    subscription_offer_name text,
    PRIMARY KEY (_fivetran_id, vendor_number)
);

CREATE TABLE app_session_detailed_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_download_date text,
    app_version text,
    campaign text,
    device text,
    page_title text,
    page_type text,
    platform_version text,
    sessions integer,
    source_info text,
    source_type text,
    territory text,
    total_session_duration integer,
    unique_devices integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_win_back_eligibility (
    _fivetran_id text,
    vendor_number integer,
    app_apple_id bigint,
    app_name text,
    churned_subscription_count integer,
    has_previously_redeemed_win_back_offer text,
    paid_subscription_tenure integer,
    requested_report_date text,
    standard_subscription_duration text,
    subscription_apple_id bigint,
    subscription_group_id bigint,
    subscription_name text,
    territory text,
    time_since_last_subscribed integer,
    time_since_last_win_back_offer integer,
    PRIMARY KEY (_fivetran_id, vendor_number, app_apple_id),
    FOREIGN KEY (app_apple_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_download_detailed_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_version text,
    campaign text,
    counts integer,
    device text,
    download_type text,
    page_title text,
    page_type text,
    platform_version text,
    pre_order text,
    source_info text,
    source_type text,
    territory text,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_installation_and_deletion_standard_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_download_date text,
    app_version text,
    counts integer,
    device text,
    download_type text,
    event text,
    page_type text,
    platform_version text,
    source_type text,
    territory text,
    unique_devices integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_purchase_detailed_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_download_date text,
    campaign text,
    content_apple_identifier text,
    content_name text,
    device text,
    page_title text,
    page_type text,
    paying_users integer,
    payment_method text,
    platform_version text,
    pre_order text,
    proceeds_in_usd double precision,
    purchase_type text,
    purchases integer,
    sales_in_usd double precision,
    source_info text,
    source_type text,
    territory text,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_pre_order_summary (
    _fivetran_id text,
    vendor_number integer,
    app_id bigint,
    canceled double precision,
    category text,
    client text,
    country_code text,
    cumulative_canceled double precision,
    cumulative_ordered double precision,
    developer text,
    device text,
    end_date text,
    ordered double precision,
    pre_order_end_date text,
    pre_order_start_date text,
    provider text,
    provider_country text,
    requested_report_date text,
    sku text,
    start_date text,
    supported_platforms text,
    title text,
    PRIMARY KEY (_fivetran_id, vendor_number, app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_browser_choice_screen_engagement_report (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    counts integer,
    device text,
    event text,
    platform_version text,
    territory text,
    unique_devices integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE financial (
    _fivetran_id text,
    country_code text,
    vendor_number integer,
    app_id bigint,
    artist_show_developer_author text,
    country_of_sale text,
    customer_currency text,
    customer_price double precision,
    end_date text,
    extended_partner_share double precision,
    filename text,
    grid text,
    isan_other_identifier text,
    isrc_isbn text,
    label_studio_network_developer_publisher text,
    partner_share double precision,
    partner_share_currency text,
    pre_order_flag text,
    product_type_identifier text,
    promo_code text,
    quantity integer,
    requested_report_date text,
    sale_or_return text,
    start_date text,
    title text,
    upc text,
    vendor_identifier text,
    PRIMARY KEY (_fivetran_id, country_code, vendor_number, app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_review (
    id text,
    app_id bigint,
    body text,
    created_date timestamp,
    rating integer,
    reviewer_nickname text,
    territory text,
    title text,
    PRIMARY KEY (id, app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_app_version (
    id text,
    app_id bigint,
    app_store_state text,
    app_version_state text,
    copyright text,
    created_date timestamp,
    downloadable boolean,
    earliest_release_date timestamp,
    platform text,
    release_type text,
    review_type text,
    uses_idfa text,
    version_string text,
    PRIMARY KEY (id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_discovery_and_engagement_standard_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    counts integer,
    device text,
    engagement_type text,
    event text,
    page_type text,
    platform_version text,
    source_type text,
    territory text,
    unique_counts integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_crash_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    app_version text,
    crashes integer,
    device text,
    platform_version text,
    unique_devices integer,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE app_store_pre_order_detailed_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    campaign text,
    device text,
    page_title text,
    page_type text,
    platform_version text,
    pre_order_canceled integer,
    pre_order_end_date text,
    pre_order_placed integer,
    pre_order_start_date text,
    source_info text,
    source_type text,
    territory text,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);

CREATE TABLE sales_subscriber_detailed (
    _fivetran_id text,
    vendor_number integer,
    app_apple_id bigint,
    app_name text,
    client text,
    country text,
    customer_currency text,
    customer_price double precision,
    developer_proceeds double precision,
    device text,
    event_date text,
    introductory_price_type text,
    marketing_opt_in_duration text,
    preserved_pricing text,
    proceeds_currency text,
    proceeds_reason text,
    promotional_offer_id text,
    purchase_date text,
    refund text,
    requested_report_date text,
    standard_subscription_duration text,
    subscriber_id bigint,
    subscriber_id_reset text,
    subscription_apple_id bigint,
    subscription_group_id bigint,
    subscription_name text,
    subscription_offer_duration text,
    subscription_offer_name text,
    units integer,
    PRIMARY KEY (_fivetran_id, vendor_number)
);

CREATE TABLE app_store_pre_order_standard_daily (
    _fivetran_id text,
    "date" text,
    app_id bigint,
    device text,
    page_type text,
    platform_version text,
    pre_order_canceled integer,
    pre_order_end_date text,
    pre_order_placed integer,
    pre_order_start_date text,
    source_type text,
    territory text,
    PRIMARY KEY (_fivetran_id, "date", app_id),
    FOREIGN KEY (app_id) REFERENCES app_store_app(id)
);
