CREATE TABLE location (
    id text,
    address text,
    code text,
    coordinates_latitude text,
    coordinates_longitude text,
    geo_fence_radius text,
    geo_fence_units text,
    "name" text,
    odata_etag text,
    PRIMARY KEY (id)
);

CREATE TABLE member_overridden_property (
    overridden_property text,
    member_id text,
    PRIMARY KEY (overridden_property, member_id),
    FOREIGN KEY (member_id) REFERENCES member(id)
);

CREATE TABLE member (
    id text,
    group_id text,
    organization_id text,
    schedule_id text,
    calendar_id text,
    code text,
    country_code text,
    created_at text,
    email text,
    full_name text,
    has_embedding text,
    invited_at text,
    join_date text,
    kiosk jsonb,
    latest_time_entry_time text,
    managed_unit jsonb,
    manager jsonb,
    nfc_token text,
    odata_etag text,
    phone_number text,
    picture text,
    pin_code text,
    position_id text,
    preferred_name text,
    project jsonb,
    removed_at text,
    "role" text,
    "status" text,
    unit_time_off_policies jsonb,
    updated_at timestamp,
    user_id text,
    work_start_date text,
    work_types jsonb,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);

CREATE TABLE organization (
    id text,
    created_at text,
    face_recognition_model_id text,
    "name" text,
    odata_etag text,
    "status" text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE "role" (
    id text,
    organization_id text,
    description text,
    do_propagate_name text,
    "name" text,
    orders text,
    organization_role_policy jsonb,
    role_policies jsonb,
    user_roles jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE time_off_holiday (
    "date" text,
    time_off_overview_id text,
    is_short_day text,
    "name" text,
    rule jsonb,
    PRIMARY KEY ("date", time_off_overview_id),
    FOREIGN KEY (time_off_overview_id) REFERENCES time_off_overview(id)
);

CREATE TABLE time_off_overview (
    id text,
    person_id text,
    duration text,
    end_date text,
    end_time text,
    kind text,
    note text,
    part_day_leave_duration text,
    part_of_day text,
    policy_id text,
    start_date timestamp,
    start_time text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (person_id) REFERENCES member(id)
);

CREATE TABLE groups (
    id text,
    organization_id text,
    schedule_id text,
    activity jsonb,
    calendar_id text,
    created_at text,
    first_approver jsonb,
    kiosk jsonb,
    manager jsonb,
    "name" text,
    odata_etag text,
    overridden_property jsonb,
    project jsonb,
    second_approvers jsonb,
    "status" text,
    unit_time_off_policy jsonb,
    updated_at timestamp,
    work_type jsonb,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);

CREATE TABLE timesheet_auto_deduction (
    "index" text,
    "date" text,
    timesheet_id text,
    duration text,
    "name" text,
    threshold text,
    PRIMARY KEY ("index", "date", timesheet_id),
    FOREIGN KEY ("date") REFERENCES timesheet_daily("date"),
    FOREIGN KEY (timesheet_id) REFERENCES timesheet_daily(timesheet_id)
);

CREATE TABLE timesheet_daily (
    "date" text,
    timesheet_id text,
    daily_double_overtime_is_edited text,
    daily_double_overtime_payroll_hour_id text,
    daily_double_overtime_time text,
    daily_overtime_is_edited text,
    daily_overtime_payroll_hour_id text,
    daily_overtime_time text,
    end_offset text,
    end_time text,
    first_in text,
    first_in_location_id text,
    first_in_offset text,
    first_in_timestamp text,
    has_archived_screenshots text,
    last_out text,
    last_out_location_id text,
    last_out_offset text,
    last_out_timestamp text,
    payroll_hours_billing text,
    payroll_hours_total text,
    public_holiday_overtime_is_edited text,
    public_holiday_overtime_payroll_hour_id text,
    public_holiday_overtime_time text,
    regular_is_edited text,
    regular_payroll_hour_id text,
    regular_time text,
    rest_day_overtime_is_edited text,
    rest_day_overtime_payroll_hour_id text,
    rest_day_overtime_time text,
    start_offset text,
    start_time text,
    time_off_holiday jsonb,
    time_off_is_rest_day text,
    time_off_paid_time_off text,
    time_off_short_day jsonb,
    time_off_type jsonb,
    time_off_unpaid_time_off text,
    tracked_hours_added text,
    tracked_hours_breaks jsonb,
    tracked_hours_paid_break_time text,
    tracked_hours_total text,
    tracked_hours_total_auto_deduction_time text,
    tracked_hours_total_break_time text,
    tracked_hours_unpaid_break_time text,
    tracked_hours_worked text,
    weekly_overtime_is_edited text,
    weekly_overtime_payroll_hour_id text,
    weekly_overtime_time text,
    PRIMARY KEY ("date", timesheet_id),
    FOREIGN KEY (timesheet_id) REFERENCES timesheet(id)
);

CREATE TABLE timesheet (
    id text,
    person_id text,
    summary_added text,
    summary_auto_deduction_time text,
    summary_break_time text,
    summary_daily_double_overtime text,
    summary_daily_overtime text,
    summary_paid_break_time text,
    summary_paid_time_off text,
    summary_payroll text,
    summary_public_holiday_overtime text,
    summary_regular text,
    summary_rest_day_overtime text,
    summary_tracked text,
    summary_unpaid_break_time text,
    summary_unpaid_time_off text,
    summary_weekly_overtime text,
    summary_worked text,
    total text,
    total_payroll text,
    total_tracked text,
    PRIMARY KEY (id),
    FOREIGN KEY (person_id) REFERENCES member(id)
);

CREATE TABLE time_entry (
    id text,
    activity_id text,
    location_id text,
    next_time_entry_id text,
    organization_id text,
    person_id text,
    previous_time_entry_id text,
    address text,
    auto_clock_out_time text,
    belongs_to_date text,
    break_id text,
    client_type text,
    clock_in_out_reminder_time text,
    coordinate text,
    created_at text,
    event_id text,
    face_similarity text,
    is_automatic text,
    is_end_of_day text,
    is_face_recognized text,
    is_from_speed_kiosk text,
    is_locked text,
    is_manual text,
    is_manual_location text,
    is_offline text,
    is_outside_geofence text,
    is_unusual text,
    kiosk_id text,
    local_time text,
    note text,
    offsets text,
    picture text,
    platform_client_version text,
    platform_device_id text,
    platform_device_model text,
    platform_device_name text,
    platform_os text,
    project_id text,
    "status" text,
    "time" text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (activity_id) REFERENCES activity(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (next_time_entry_id) REFERENCES time_entry(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (person_id) REFERENCES member(id),
    FOREIGN KEY (previous_time_entry_id) REFERENCES time_entry(id)
);

CREATE TABLE schedule_auto_deduction (
    "index" text,
    schedule_id text,
    duration text,
    "name" text,
    threshold text,
    PRIMARY KEY ("index", schedule_id),
    FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);

CREATE TABLE schedule_break (
    id text,
    schedule_id text,
    allow_to_be_taken_from_to text,
    duration text,
    from_time text,
    "name" text,
    to_time text,
    PRIMARY KEY (id, schedule_id),
    FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);

CREATE TABLE schedule_day (
    "index" text,
    schedule_id text,
    "day" text,
    duration text,
    from_time text,
    to_time text,
    PRIMARY KEY ("index", schedule_id),
    FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);

CREATE TABLE schedule (
    id text,
    organization_id text,
    breaks_type text,
    created_at text,
    daily_double_overtime_multiplier text,
    daily_overtime_multiplier text,
    defaults text,
    exclude_early_clock_in text,
    location jsonb,
    "name" text,
    odata_etag text,
    overtime_daily text,
    overtime_daily_double text,
    overtime_daily_double_duration text,
    overtime_daily_double_from text,
    overtime_daily_duration text,
    overtime_daily_from text,
    overtime_end_work_day_at text,
    overtime_public_holiday text,
    overtime_rest_day text,
    overtime_time_range_style text,
    overtime_weekly text,
    overtime_weekly_duration text,
    public_holiday_overtime_multiplier text,
    rest_day_overtime_multiplier text,
    updated_at timestamp,
    weekly_hours text,
    weekly_overtime_multiplier text,
    work_arrangement text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE activity (
    id text,
    organization_id text,
    assigned_group jsonb,
    code text,
    color text,
    created_at text,
    description text,
    "name" text,
    odata_etag text,
    "status" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);
