CREATE TABLE site (
    id text,
    is_deleted text,
    publisher_account_id text,
    title text,
    url text,
    PRIMARY KEY (id)
);

CREATE TABLE "zone" (
    id text,
    site_id text,
    is_deleted text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE creative (
    id text,
    ad_type_id text,
    advertiser_id text,
    alt text,
    body text,
    image_link text,
    image_name text,
    is_active text,
    is_deleted text,
    is_html_js text,
    is_network_ad text,
    is_no_track text,
    is_sync text,
    metadata text,
    script_body text,
    title text,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (ad_type_id) REFERENCES ad_type(id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE flight (
    id text,
    campaign_id text,
    can_passback text,
    cap_type text,
    created text,
    daily_cap_amount text,
    daily_cap_amount_decimal text,
    delivery_status text,
    dont_affect_parent_freq_cap text,
    end_date text,
    end_date_iso text,
    freq_cap text,
    freq_cap_duration text,
    freq_cap_type text,
    geo_distance_targeting text,
    goal_type text,
    impressions text,
    is_active text,
    is_companion text,
    is_deleted text,
    is_full_speed text,
    is_no_duplicates text,
    is_tracking_conversions text,
    is_unlimited text,
    last_modified text,
    "name" text,
    option_type text,
    price text,
    priority_id text,
    rate_type text,
    require_strict_location text,
    start_date text,
    start_date_iso text,
    time_zone text,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE channel_ad_type (
    "index" text,
    channel_id text,
    "type" text,
    PRIMARY KEY ("index", channel_id),
    FOREIGN KEY (channel_id) REFERENCES channel(id)
);

CREATE TABLE channel (
    id text,
    commission text,
    cpm text,
    created text,
    custom_targeting text,
    engine text,
    is_deleted text,
    last_modified text,
    title text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE ad_type (
    id text,
    height text,
    "name" text,
    width text,
    PRIMARY KEY (id)
);

CREATE TABLE campaign (
    id text,
    advertiser_id text,
    cap_type text,
    created text,
    daily_cap_amount text,
    flights jsonb,
    freq_cap text,
    freq_cap_duration text,
    freq_cap_type text,
    is_active text,
    is_archived text,
    is_deleted text,
    last_modified text,
    life_time_cap_amount text,
    "name" text,
    price text,
    salesperson_id text,
    start_date text,
    start_date_iso text,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE advertiser (
    id text,
    created text,
    freq_cap_type text,
    is_active text,
    is_deleted text,
    last_modified text,
    title text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE report_group (
    "index" text,
    report_id text,
    groups text,
    PRIMARY KEY ("index", report_id),
    FOREIGN KEY (report_id) REFERENCES report(id)
);

CREATE TABLE report_record_detail (
    _fivetran_id text,
    grouping_ad_type_id text,
    grouping_brand_id text,
    grouping_campaign_id text,
    grouping_channel_id text,
    grouping_creative_id text,
    grouping_option_id text,
    grouping_priority_id text,
    grouping_site_id text,
    grouping_zone_id text,
    "index" text,
    report_id text,
    _title text,
    bot_filtering_disabled_requests text,
    clicks text,
    ctr text,
    "date" text,
    date_type text,
    decision_requests text,
    details jsonb,
    duplicate_impression_bucket_clicks text,
    duplicate_ip_bucket_clicks text,
    ecpm text,
    events jsonb,
    fill_rate text,
    first_date text,
    gmv text,
    grouping_ad_id text,
    grouping_ad_type text,
    grouping_advertised_os text,
    grouping_advertiser text,
    grouping_brand_name text,
    grouping_browser text,
    grouping_browser_major_version text,
    grouping_browser_minor_version text,
    grouping_campaign text,
    grouping_channel text,
    grouping_city text,
    grouping_country_code text,
    grouping_creative text,
    grouping_date text,
    grouping_date_type text,
    grouping_flight text,
    grouping_form_factor text,
    grouping_keyword text,
    grouping_metro_code text,
    grouping_model_name text,
    grouping_os_major_version text,
    grouping_os_minor_version text,
    grouping_price text,
    grouping_priority text,
    grouping_product_brand_id text,
    grouping_product_brand_name text,
    grouping_product_main_category_id text,
    grouping_product_main_category_name text,
    grouping_product_merchant_id text,
    grouping_product_merchant_name text,
    grouping_product_sku_id text,
    grouping_product_sku_name text,
    grouping_publisher_account text,
    grouping_publisher_account_id text,
    grouping_rate_type_id text,
    grouping_region text,
    grouping_site text,
    grouping_zone text,
    impressions text,
    invalid_ua_bucket_clicks text,
    invalid_ua_impressions text,
    invalid_user_agent_requests text,
    last_date text,
    passback_requests text,
    raw_bucket_clicks text,
    requests text,
    revenue text,
    roas text,
    rtb_bid_requests text,
    rtb_matched_requests text,
    rtb_requests text,
    suspicious_bucket_clicks text,
    test_bucket_clicks text,
    title text,
    true_revenue text,
    unfiltered_impressions text,
    unique_bucket_clicks text,
    unique_ctr text,
    valid_user_agent_requests text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (grouping_ad_type_id) REFERENCES ad_type(id),
    FOREIGN KEY (grouping_brand_id) REFERENCES advertiser(id),
    FOREIGN KEY (grouping_campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (grouping_channel_id) REFERENCES channel(id),
    FOREIGN KEY (grouping_creative_id) REFERENCES creative(id),
    FOREIGN KEY (grouping_option_id) REFERENCES flight(id),
    FOREIGN KEY (grouping_priority_id) REFERENCES flight(priority_id),
    FOREIGN KEY (grouping_site_id) REFERENCES site(id),
    FOREIGN KEY (grouping_zone_id) REFERENCES "zone"(id),
    FOREIGN KEY ("index") REFERENCES report_record("index"),
    FOREIGN KEY (report_id) REFERENCES report_record(report_id)
);

CREATE TABLE report_record (
    "index" text,
    report_id text,
    _title text,
    bot_filtering_disabled_requests text,
    clicks text,
    ctr text,
    "date" text,
    date_type text,
    decision_requests text,
    ecpm text,
    events jsonb,
    fill_rate text,
    first_date text,
    gmv text,
    grouping text,
    impressions text,
    invalid_ua_impressions text,
    invalid_user_agent_requests text,
    last_date text,
    passback_requests text,
    raw_bucket_clicks text,
    requests text,
    revenue text,
    roas text,
    rtb_bid_requests text,
    rtb_matched_requests text,
    rtb_requests text,
    suspicious_bucket_clicks text,
    title text,
    true_revenue text,
    unfiltered_impressions text,
    unique_bucket_clicks text,
    unique_ctr text,
    valid_user_agent_requests text,
    PRIMARY KEY ("index", report_id),
    FOREIGN KEY (report_id) REFERENCES report(id)
);

CREATE TABLE report (
    id text,
    critiera jsonb,
    end_date text,
    end_date_iso text,
    is_total text,
    login_id text,
    option_records jsonb,
    record_title text,
    result_report_id text,
    start_date text,
    start_date_iso text,
    "status" text,
    title text,
    total_bot_filtering_disabled_requests text,
    total_clicks text,
    total_ctr text,
    total_decision_requests text,
    total_duplicate_impression_bucket_clicks text,
    total_duplicate_ip_bucket_clicks text,
    total_ecpm text,
    total_fill_rate text,
    total_gmv text,
    total_impressions text,
    total_invalid_ua_bucket_clicks text,
    total_invalid_ua_impressions text,
    total_invalid_user_agent_requests text,
    total_passback_requests text,
    total_raw_bucket_clicks text,
    total_requests text,
    total_revenue text,
    total_roas text,
    total_rtb_bid_requests text,
    total_rtb_matched_requests text,
    total_rtb_requests text,
    total_supicious_bucket_clicks text,
    total_test_bucket_clicks text,
    total_true_revenue text,
    total_unfiltered_impressions text,
    total_unique_bucket_clicks text,
    total_unique_ctr text,
    total_valid_user_agent_requests text,
    PRIMARY KEY (id)
);
