CREATE TABLE roster_shift_qualification (
    id text,
    roster_shift_id text,
    "name" text,
    PRIMARY KEY (id, roster_shift_id),
    FOREIGN KEY (id) REFERENCES qualification(qualification_id),
    FOREIGN KEY (roster_shift_id) REFERENCES roster_shift(id)
);

CREATE TABLE roster_shift_break (
    id text,
    roster_shift_id text,
    end_time text,
    is_paid_break text,
    start_time text,
    PRIMARY KEY (id, roster_shift_id),
    FOREIGN KEY (roster_shift_id) REFERENCES roster_shift(id)
);

CREATE TABLE roster_shift (
    id text,
    business_id text,
    employee_id text,
    location_id text,
    pending_swap_from_employee_id text,
    pending_swap_to_employee_id text,
    work_type_id text,
    accepted text,
    biddable text,
    classification_id text,
    classification_name text,
    date_published text,
    employee_name text,
    end_time text,
    note text,
    pending_swap_date_created text,
    pending_swap_from_employee text,
    pending_swap_id text,
    pending_swap_note text,
    pending_swap_rejected_reason text,
    pending_swap_status text,
    pending_swap_status_description text,
    pending_swap_to_employee text,
    published text,
    role_class_name text,
    role_hex_colour_code text,
    role_id text,
    role_name text,
    shift_assignment_status text,
    shift_swap_cutoff_time text,
    start_time text,
    token text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (pending_swap_from_employee_id) REFERENCES employee(id),
    FOREIGN KEY (pending_swap_to_employee_id) REFERENCES employee(id),
    FOREIGN KEY (work_type_id) REFERENCES work_type(id)
);

CREATE TABLE employee (
    id text,
    business_id text,
    employing_entity_id text,
    afs_debt text,
    anniversary_date text,
    australian_resident text,
    automatically_pay_employee text,
    bank_account_1_account_name text,
    bank_account_1_account_number text,
    bank_account_1_allocated_percentage text,
    bank_account_1_bsb text,
    bank_account_1_fixed_amount text,
    bank_account_2_account_name text,
    bank_account_2_account_number text,
    bank_account_2_allocated_percentage text,
    bank_account_2_bsb text,
    bank_account_2_fixed_amount text,
    bank_account_3_account_name text,
    bank_account_3_account_number text,
    bank_account_3_allocated_percentage text,
    bank_account_3_bsb text,
    bank_account_3_fixed_amount text,
    business_award_package text,
    claim_medicare_levy_reduction text,
    claim_tax_free_threshold text,
    closely_held_employee text,
    closely_held_reporting text,
    contractor_abn text,
    date_created text,
    date_of_birth text,
    date_tax_file_declaration_reported text,
    date_tax_file_declaration_signed text,
    dvl_pay_slip_description text,
    email_address text,
    emergency_contact_1_address text,
    emergency_contact_1_alternate_contact_number text,
    emergency_contact_1_contact_number text,
    emergency_contact_1_name text,
    emergency_contact_1_relationship text,
    emergency_contact_2_address text,
    emergency_contact_2_alternate_contact_number text,
    emergency_contact_2_contact_number text,
    emergency_contact_2_name text,
    emergency_contact_2_relationship text,
    employing_entity_a_b_n text,
    employment_agreement text,
    employment_type text,
    end_date text,
    external_id text,
    first_name text,
    full_time_equivalent text,
    gender text,
    has_approved_working_holiday_visa text,
    has_withholding_variation text,
    help_debt text,
    home_phone text,
    hours_per_day text,
    hours_per_week text,
    is_enabled_for_timesheet text,
    is_exempt_from_flood_levy text,
    is_exempt_from_payroll_tax text,
    is_seasonal_worker text,
    job_title text,
    leave_accrual_start_date_type text,
    leave_template text,
    leave_year_start text,
    location text,
    maximum_quarterly_super_contributions_base text,
    medicare_levy_exemption text,
    medicare_levy_reduction_dependent_count text,
    medicare_levy_reduction_spouse text,
    medicare_levy_surcharge_withholding_tier text,
    middle_name text,
    mobile_phone text,
    other_tax_offset text,
    override_template_rate text,
    pay_condition_rule_set text,
    pay_rate_template text,
    pay_schedule text,
    pay_slip_notification_type text,
    portable_long_service_leave_id text,
    postal_address_is_overseas text,
    postal_address_line_2 text,
    postal_country text,
    postal_post_code text,
    postal_state text,
    postal_street_address text,
    postal_suburb text,
    preferred_name text,
    previous_surname text,
    primary_location text,
    primary_pay_category text,
    rate text,
    rate_unit text,
    reporting_dimension_value text,
    residential_address_is_overseas text,
    residential_address_line_2 text,
    residential_country text,
    residential_post_code text,
    residential_state text,
    residential_street_address text,
    residential_suburb text,
    rostering_notification_choice text,
    seniors_tax_offset text,
    single_touch_payroll text,
    start_date text,
    "status" text,
    stsl_debt text,
    super_fund_1_allocated_percentage text,
    super_fund_1_employer_nominated_fund text,
    super_fund_1_fixed_amount text,
    super_fund_1_fund_name text,
    super_fund_1_member_number text,
    super_fund_1_product_code text,
    super_fund_2_allocated_percentage text,
    super_fund_2_employer_nominated_fund text,
    super_fund_2_fixed_amount text,
    super_fund_2_fund_name text,
    super_fund_2_member_number text,
    super_fund_2_product_code text,
    super_fund_3_allocated_percentage text,
    super_fund_3_employer_nominated_fund text,
    super_fund_3_fixed_amount text,
    super_fund_3_fund_name text,
    super_fund_3_member_number text,
    super_fund_3_product_code text,
    super_threshold_amount text,
    surname text,
    tags text,
    tax_category text,
    tax_file_number text,
    tax_variation text,
    termination_reason text,
    title text,
    work_phone text,
    work_type text,
    working_holiday_visa_country text,
    working_holiday_visa_start_date text,
    PRIMARY KEY (id, business_id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employing_entity_id) REFERENCES employing_entity(id)
);

CREATE TABLE employee_additional_earning (
    id text,
    business_id text,
    employee_id text,
    location_id text,
    pay_category_id text,
    amount double precision,
    expiration_type text,
    expiry_date text,
    is_active text,
    maximum_amount_paid double precision,
    "name" text,
    note text,
    override_super_rate text,
    start_date text,
    super_rate double precision,
    total_amount_paid double precision,
    unit double precision,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (pay_category_id) REFERENCES pay_category(id)
);

CREATE TABLE employee_tax_adjustment (
    id text,
    business_id text,
    employee_id text,
    adjustment_type text,
    amount double precision,
    expiry_date text,
    from_date text,
    is_active text,
    maximum_amount_paid double precision,
    note text,
    total_amount_paid double precision,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_portal_setting (
    _fivetran_id text,
    business_id text,
    allow_employee_bank_account_self_service text,
    allow_employee_expenses_self_service text,
    allow_employee_leave_self_service text,
    allow_employee_override_tax_code text,
    allow_employee_satisfaction_survey text,
    allow_employee_self_editing text,
    allow_employee_shift_selection text,
    allow_employee_super_fund_self_service text,
    allow_employee_to_set_unavailability text,
    allow_employees_to_upload_profile_picture text,
    allow_employees_to_view_all_approved_leave text,
    can_specify_higher_classification text,
    clock_off_reminder_notification_minute text,
    clock_off_window_minute text,
    clock_on_reminder_notification_minute text,
    clock_on_window_minute text,
    enable_work_zone_clock_on text,
    require_photo text,
    send_employee_details_update_notification text,
    show_pay_days_in_employee_calendar text,
    timesheet_setting text,
    unavailability_cut_off text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE business_qualification (
    id text,
    business_id text,
    "name" text,
    PRIMARY KEY (id, business_id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE super_fund (
    id text,
    employee_id text,
    business_id text,
    allocate_balance text,
    allocated_percentage double precision,
    can_be_deleted text,
    fixed_amount double precision,
    is_employer_nominated_fund text,
    member_number text,
    "name" text,
    super_product_abn text,
    super_product_account_name text,
    super_product_account_number text,
    super_product_bsb text,
    super_product_business_name text,
    super_product_code text,
    super_product_display_name text,
    super_product_electronic_service_address text,
    super_product_email text,
    super_product_external_reference_id text,
    super_product_id text,
    super_product_name text,
    super_product_source text,
    super_product_type text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id)
);

CREATE TABLE pay_slip_configuration (
    id text,
    business_id text,
    alphabetise_pay_category text,
    email_body_message text,
    email_from text,
    employees_must_login_to_download_payslip text,
    show_base_pay_rate text,
    show_classification text,
    show_employee_external_id text,
    show_employee_id text,
    show_leave_accrual text,
    show_line_note text,
    show_location_in_line_note text,
    show_rate_for_annual_earning text,
    super_contribution_processing_frequency_text_option text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE pay_rate_adjustment_schedule (
    id text,
    business_id text,
    employee_id text,
    commencement_date text,
    rate text,
    rate_unit text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE bank_account (
    id text,
    business_id text,
    employee_id text,
    account_name text,
    account_number text,
    account_type text,
    allocate_balance text,
    allocated_percentage text,
    bsb text,
    can_be_deleted text,
    external_reference_id text,
    fixed_amount text,
    is_employee_editable text,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE public_holiday_location (
    id text,
    public_holiday_fivetran_id text,
    PRIMARY KEY (id, public_holiday_fivetran_id),
    FOREIGN KEY (id) REFERENCES location(id),
    FOREIGN KEY (public_holiday_fivetran_id) REFERENCES public_holiday(_fivetran_id)
);

CREATE TABLE public_holiday (
    _fivetran_id text,
    business_id text,
    "date" text,
    description text,
    id text,
    is_system text,
    mondayised_alternative_to_id text,
    not_a_public_holiday text,
    note text,
    states jsonb,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE employment_agreement (
    id text,
    business_id text,
    award_name text,
    classification text,
    employment_type text,
    external_id text,
    "name" text,
    rank text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE employee_expense (
    id text,
    business_id text,
    employee_id text,
    expense_category_id text,
    location_id text,
    amount text,
    expiry_date text,
    from_date text,
    is_active text,
    maximum_amount_paid text,
    "name" text,
    notes text,
    tax_code text,
    tax_code_display_name text,
    tax_rate text,
    total_amount_paid text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (expense_category_id) REFERENCES employee_expense_category(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE work_type (
    id text,
    business_id text,
    leave_category_id text,
    pay_category_id text,
    accrues_leave text,
    award_package_id text,
    award_package_name text,
    employment_types jsonb,
    external_id text,
    mapping_type text,
    "name" text,
    short_code text,
    "source" text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (leave_category_id) REFERENCES leave_category(id),
    FOREIGN KEY (pay_category_id) REFERENCES pay_category(id)
);

CREATE TABLE employee_deduction (
    id text,
    business_id text,
    employee_id text,
    deduction_category_id text,
    paid_to_account_id text,
    additional_data text,
    amount double precision,
    carry_forward_unpaid_deduction text,
    carry_forward_unused_preserved_earning text,
    deduction_type text,
    deleted text,
    expiry_date text,
    external_reference_id text,
    from_date text,
    is_active text,
    maximum_amount_paid double precision,
    "name" text,
    note text,
    paid_to text,
    payment_reference text,
    preserved_earning text,
    preserved_earnings_amount double precision,
    preserved_earnings_amount_not_reached_action text,
    priority text,
    total_amount_paid double precision,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (deduction_category_id) REFERENCES deduction_category(id),
    FOREIGN KEY (paid_to_account_id) REFERENCES bank_account(id)
);

CREATE TABLE pay_schedule_location (
    id text,
    pay_schedule_id text,
    PRIMARY KEY (id, pay_schedule_id),
    FOREIGN KEY (id) REFERENCES location(id),
    FOREIGN KEY (pay_schedule_id) REFERENCES pay_schedule(id)
);

CREATE TABLE pay_schedule (
    id text,
    business_id text,
    aba_details_id text,
    auto_pay_configuration_adjust_date_paid_to_work_day text,
    auto_pay_configuration_adjust_run_date_to_work_day text,
    auto_pay_configuration_day_of_week text,
    auto_pay_configuration_enabled text,
    auto_pay_configuration_export_journal text,
    auto_pay_configuration_finalise text,
    auto_pay_configuration_initial_date_paid text,
    auto_pay_configuration_initial_pay_period_ending text,
    auto_pay_configuration_initial_pay_run_creation_date_time text,
    auto_pay_configuration_lodge_pay_run text,
    auto_pay_configuration_next_scheduled_creation_date_time_utc text,
    auto_pay_configuration_paused text,
    auto_pay_configuration_publish_pay_slip text,
    auto_pay_configuration_publish_pay_slips_hour text,
    auto_pay_configuration_report_packs_to_run jsonb,
    auto_pay_configuration_run_on_specific_day_of_month text,
    auto_pay_configuration_scheduled_end_date text,
    auto_pay_configuration_specific_day_of_month text,
    auto_pay_configuration_suppress_notification text,
    auto_pay_configuration_timesheet_import_option text,
    auto_pay_configuration_users_to_notify jsonb,
    auto_pay_configuration_week_of_month text,
    default_finalise_settings_export_journal text,
    default_finalise_settings_export_journals_day text,
    default_finalise_settings_export_journals_time_of_day text,
    default_finalise_settings_export_journals_timeline text,
    default_finalise_settings_lodge_pay_run text,
    default_finalise_settings_lodge_pay_run_day text,
    default_finalise_settings_lodge_pay_run_time_of_day text,
    default_finalise_settings_lodge_pay_run_timeline text,
    default_finalise_settings_publish_pay_slip text,
    default_finalise_settings_publish_pay_slips_day text,
    default_finalise_settings_publish_pay_slips_time_of_day text,
    default_finalise_settings_publish_pay_slips_timeline text,
    default_finalise_settings_report_packs_to_run jsonb,
    default_finalise_settings_run_report_pack text,
    default_finalise_settings_run_report_packs_day text,
    default_finalise_settings_run_report_packs_time_of_day text,
    default_finalise_settings_run_report_packs_timeline text,
    default_finalise_settings_submit_to_pension_sync text,
    default_finalise_settings_submit_to_pension_sync_day text,
    default_finalise_settings_submit_to_pension_sync_time_of_day text,
    default_finalise_settings_submit_to_pension_sync_timeline text,
    default_finalise_settings_super_payment text,
    default_finalise_settings_suppress_notification text,
    employee_selection_strategy text,
    equal_monthly_payment text,
    external_id text,
    frequency text,
    ignored_pay_run_warning jsonb,
    last_date_paid text,
    last_pay_run text,
    "name" text,
    pay_schedule_approval_settings_approvers_to_notify jsonb,
    pay_schedule_approval_settings_notification_subject text,
    pay_schedule_approval_settings_notification_template text,
    pay_schedule_approval_settings_reminder_day text,
    pay_schedule_approval_settings_reminder_subject text,
    pay_schedule_approval_settings_reminder_template text,
    pay_schedule_approval_settings_require_approval text,
    pay_schedule_approval_settings_send_reminder text,
    pay_schedule_payment_approval_settings_approvers_to_notify jsonb,
    pay_schedule_payment_approval_settings_notification_subject text,
    pay_schedule_payment_approval_settings_notification_template text,
    pay_schedule_payment_approval_settings_reminder_day text,
    pay_schedule_payment_approval_settings_reminder_subject text,
    pay_schedule_payment_approval_settings_reminder_template text,
    pay_schedule_payment_approval_settings_require_approval text,
    pay_schedule_payment_approval_settings_send_reminder text,
    payg_account_bsb text,
    payg_account_name text,
    payg_account_number text,
    payg_reference text,
    "source" text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE qualification_document (
    id text,
    qualification_qualification_id text,
    date_created text,
    "name" text,
    visible text,
    PRIMARY KEY (id, qualification_qualification_id),
    FOREIGN KEY (qualification_qualification_id) REFERENCES qualification(qualification_id)
);

CREATE TABLE qualification (
    qualification_id text,
    business_id text,
    employee_id text,
    expiry_date text,
    issue_date text,
    "name" text,
    reference_number text,
    PRIMARY KEY (qualification_id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE expense_request_attachment (
    id text,
    expense_request_id text,
    date_created text,
    date_scanned text,
    friendly_name text,
    is_infected text,
    url text,
    PRIMARY KEY (id, expense_request_id),
    FOREIGN KEY (expense_request_id) REFERENCES expense_request(id)
);

CREATE TABLE expense_request_line_item (
    id text,
    expense_request_id text,
    expense_category_id text,
    location_id text,
    amount text,
    date_incurred text,
    expense_category_name text,
    notes text,
    tax_code text,
    tax_code_display_name text,
    tax_rate text,
    PRIMARY KEY (id, expense_request_id),
    FOREIGN KEY (expense_request_id) REFERENCES expense_request(id),
    FOREIGN KEY (expense_category_id) REFERENCES employee_expense_category(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE expense_request (
    id text,
    business_id text,
    employee_id text,
    date_created text,
    date_status_updated text,
    description text,
    "status" text,
    status_update_note text,
    status_updated_by_user text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE leave_request (
    id text,
    business_id text,
    employee_id text,
    leave_category_id text,
    attachment_id text,
    from_date text,
    hours_applied text,
    note text,
    "status" text,
    to_date text,
    total_hour text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (leave_category_id) REFERENCES leave_category(id)
);

CREATE TABLE leave_liability_report (
    employee_id text,
    business_id text,
    accrued_amount text,
    accrued_amount_in_hour text,
    approved_leave_amount text,
    approved_leave_amount_in_hour text,
    calculated_week text,
    external_id text,
    last_paid_date text,
    last_pay_period_ending text,
    leave_category_name text,
    leave_loading_dollar_value text,
    leave_value text,
    location text,
    start_date text,
    unit_type text,
    PRIMARY KEY (employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE pay_rate (
    business_id text,
    employee_id text,
    pay_category_id text,
    accrues_leave text,
    calculated_rate double precision,
    has_super_rate_override text,
    is_primary_pay_category text,
    rate double precision,
    rate_unit text,
    super_rate text,
    PRIMARY KEY (business_id, employee_id, pay_category_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (pay_category_id) REFERENCES pay_category(id)
);

CREATE TABLE employer_liability (
    id text,
    business_id text,
    employee_id text,
    amount double precision,
    employer_liability_category_id text,
    employer_liability_category_name text,
    expiry_date text,
    external_reference_id text,
    from_date text,
    is_active text,
    liability_type text,
    maximum_amount_paid double precision,
    note text,
    "source" text,
    total_amount_paid double precision,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE pay_run_detail (
    id text,
    business_id text,
    pay_run_id text,
    employee_id text,
    earliest_termination_date text,
    employee_expenses_total text,
    employee_external_reference_id text,
    employer_contribution text,
    employer_contribution_adjustments_amount text,
    employer_liabilities_total text,
    is_complete text,
    is_employee_under_18 text,
    is_excluded text,
    is_termination text,
    member_voluntary_super_amount text,
    non_super_deduction_total text,
    pay_condition_rule_set_name text,
    payg_adjustments_amount text,
    payg_payment_total text,
    previous_termination_date text,
    salary_sacrifice_super_amount text,
    super_contributions_cap_applied text,
    termination_date text,
    PRIMARY KEY (id, business_id, pay_run_id),
    FOREIGN KEY (business_id) REFERENCES pay_run_detail_total(business_id),
    FOREIGN KEY (pay_run_id) REFERENCES pay_run_detail_total(pay_run_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE pay_run_detail_total (
    business_id text,
    pay_run_id text,
    grand_total_employee_expense_total double precision,
    grand_total_employer_contribution double precision,
    grand_total_employer_liability_total double precision,
    grand_total_gross_earning double precision,
    grand_total_help_amount double precision,
    grand_total_net_earning double precision,
    grand_total_number_of_employee text,
    grand_total_payg_withholding_amount double precision,
    grand_total_post_tax_deduction_amount double precision,
    grand_total_pre_tax_deduction_amount double precision,
    grand_total_sfss_amount double precision,
    grand_total_super_contribution double precision,
    grand_total_taxable_earning double precision,
    grand_total_total_hour double precision,
    PRIMARY KEY (business_id, pay_run_id),
    FOREIGN KEY (business_id) REFERENCES pay_run(business_id),
    FOREIGN KEY (pay_run_id) REFERENCES pay_run(id)
);

CREATE TABLE pay_category (
    id text,
    business_id text,
    parent_id text,
    accrues_leave text,
    allowance_description text,
    award_id text,
    award_name text,
    default_super_rate text,
    external_id text,
    general_ledger_mapping_code text,
    hide_units_on_pay_slip text,
    is_payroll_tax_exempt text,
    is_primary text,
    is_system_pay_category text,
    is_tax_exempt text,
    "name" text,
    number_of_decimal_place text,
    pay_category_type text,
    payment_summary_classification text,
    penalty_loading_percent text,
    rate_loading_percent text,
    rate_unit text,
    rounding_method text,
    "source" text,
    super_expense_mapping_code text,
    super_liability_mapping_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (parent_id) REFERENCES pay_category(id)
);

CREATE TABLE unavailability (
    id text,
    business_id text,
    employee_id text,
    end_date text,
    from_date text,
    is_all_day text,
    reason text,
    recurring text,
    recurring_day text,
    recurring_days text,
    recurring_days_csv text,
    to_date text,
    view_only text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES employee(id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE pay_run_summary (
    id text,
    business_id text,
    date_finalised text,
    date_paid text,
    external_id text,
    is_finalised text,
    notation text,
    pay_period_ending text,
    pay_period_starting text,
    pay_schedule_id text,
    pay_slips_published text,
    total_gross_wage text,
    total_hour text,
    total_net_wage text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE leave_allowance (
    _fivetran_id text,
    business_id text,
    employee_id text,
    leave_category_id text,
    automatically_accrue text,
    can_apply_for_leave text,
    hours_per_year text,
    leave_accrual_rule_accrue_in_advance text,
    leave_accrual_rule_cap_type text,
    leave_accrual_rule_carry_over_amount text,
    leave_accrual_rule_carry_over_behaviour text,
    leave_accrual_rule_id text,
    leave_accrual_rule_leave_year_offset_amount text,
    leave_accrual_rule_type text,
    leave_accrual_rule_unit_cap text,
    leave_loading text,
    leave_unit_type text,
    unit_type text,
    units text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (leave_category_id) REFERENCES leave_category(id)
);

CREATE TABLE leave_category (
    id text,
    business_id text,
    transfer_on_termination_to_pay_category_id text,
    transfer_to_pay_category_id text,
    accrues_first_pay_run_per_period_only text,
    automatically_accrue text,
    contingent_period text,
    deduct_from_pay_category_id text,
    deduct_from_primary_pay_category text,
    entitlement_period text,
    exclude_from_termination_payout text,
    external_id text,
    hide_accruals_on_payslip text,
    is_balance_untracked text,
    is_name_private text,
    is_private text,
    leave_accrual_rule jsonb,
    leave_category_type text,
    leave_loading text,
    leave_unit_type text,
    "name" text,
    payout_as_etp text,
    prevent_negative_balance_unpaid_leave_category_id text,
    "source" text,
    unit text,
    unit_type text,
    use_deduct_from_pay_category_rate text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (transfer_on_termination_to_pay_category_id) REFERENCES pay_category(id),
    FOREIGN KEY (transfer_to_pay_category_id) REFERENCES pay_category(id)
);

CREATE TABLE pay_slip_super_payment (
    "index" text,
    pay_slip_id text,
    amount text,
    fund_name text,
    member_number text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_bank_payment (
    "index" text,
    pay_slip_id text,
    account_name text,
    account_number text,
    amount text,
    bsb text,
    lodgement_reference text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_earnings_line (
    "index" text,
    pay_slip_id text,
    gross_earning text,
    is_fixed text,
    is_tax_exempt text,
    location_name text,
    note text,
    pay_category_name text,
    rate text,
    super_contribution text,
    taxable_earning text,
    unit text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_accrued_leave (
    "index" text,
    pay_slip_id text,
    amount text,
    leave_category text,
    note text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_gross_ytd_detail (
    "index" text,
    pay_slip_id text,
    gross_earning text,
    pay_category_name text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_deduction (
    "index" text,
    pay_slip_id text,
    amount text,
    "name" text,
    note text,
    tax_status text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_leave_taken (
    "index" text,
    pay_slip_id text,
    amount text,
    leave_category text,
    note text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_payg_adjustment (
    "index" text,
    pay_slip_id text,
    amount text,
    note text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip_super_adjustment (
    "index" text,
    pay_slip_id text,
    amount text,
    note text,
    PRIMARY KEY ("index", pay_slip_id),
    FOREIGN KEY (pay_slip_id) REFERENCES pay_slip(id)
);

CREATE TABLE pay_slip (
    id text,
    business_id text,
    employee_id text,
    pay_run_id text,
    abn text,
    employee_base_rate text,
    employee_base_rate_unit text,
    help_amount text,
    help_ytd text,
    hourly_rate text,
    is_published text,
    message text,
    net_earning text,
    net_ytd text,
    notation text,
    pay_period_ending text,
    pay_period_starting text,
    payg_withholding_amount text,
    payg_ytd text,
    post_tax_deduction_amount text,
    post_tax_deductions_ytd text,
    pre_tax_deduction_amount text,
    pre_tax_deductions_ytd text,
    sfss_amount text,
    sfss_ytd text,
    super_contribution text,
    super_ytd text,
    taxable_earning text,
    total_hour text,
    withholding_ytd text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES pay_run(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (pay_run_id) REFERENCES pay_run(id)
);

CREATE TABLE pay_rate_template_pay_category (
    pay_category_id text,
    pay_rate_template_id text,
    calculated_rate text,
    standard_weekly_hour text,
    user_supplied_rate text,
    PRIMARY KEY (pay_category_id, pay_rate_template_id),
    FOREIGN KEY (pay_category_id) REFERENCES pay_category(id),
    FOREIGN KEY (pay_rate_template_id) REFERENCES pay_rate_template(id)
);

CREATE TABLE pay_rate_template (
    id text,
    business_id text,
    primary_pay_category_id text,
    external_id text,
    maximum_quarterly_super_contribution_base text,
    "name" text,
    reapply_to_linked_employee text,
    "source" text,
    super_threshold_amount text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (primary_pay_category_id) REFERENCES pay_category(id)
);

CREATE TABLE employee_document (
    id text,
    business_id text,
    employee_id text,
    leave_request_id text,
    date_created text,
    friendly_name text,
    timesheet_line_id text,
    visible text,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (leave_request_id) REFERENCES leave_request(id)
);

CREATE TABLE aba (
    id text,
    business_id text,
    account_name text,
    account_number text,
    balance_additional_content text,
    balance_lodgement_reference text,
    bsb text,
    financial_institution_code text,
    include_self_balancing_transaction text,
    lodgement_reference text,
    merge_multiple_account_payment text,
    payment_additional_content text,
    user_id text,
    user_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE leave_balance (
    business_id text,
    employee_id text,
    leave_category_id text,
    accrued_amount double precision,
    unit_type text,
    PRIMARY KEY (business_id, employee_id, leave_category_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (leave_category_id) REFERENCES leave_category(id)
);

CREATE TABLE pay_run (
    id text,
    business_id text,
    pay_schedule_id text,
    date_finalised text,
    date_paid text,
    external_id text,
    is_finalised text,
    notation text,
    pay_period_ending text,
    pay_period_starting text,
    pay_slips_published text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (pay_schedule_id) REFERENCES pay_schedule(id)
);

CREATE TABLE business (
    id text,
    abn text,
    address_line_1 text,
    address_line_2 text,
    budget_entry_method text,
    budget_warning_percent text,
    contact_email_address text,
    contact_fax_number text,
    contact_name text,
    contact_phone_number text,
    date_created text,
    default_super_rate text,
    end_of_week text,
    external_id text,
    foreign_entity_country text,
    industry_name text,
    initial_financial_year_start text,
    is_foreign_entity text,
    journal_service text,
    leave_accrual_start_date_type text,
    leave_year_start text,
    legal_name text,
    management_software_id text,
    managers_can_edit_roster_budget text,
    "name" text,
    number_of_employees text,
    pay_cycle_frequency text,
    post_code text,
    promo_code text,
    region text,
    sbr_software_id text,
    sbr_software_provider text,
    "source" text,
    standard_hours_per_day text,
    "state" text,
    suburb text,
    white_label_id text,
    white_label_name text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_standard_hour_work_day (
    id text,
    business_id text,
    employee_id text,
    location_id text,
    work_type_id text,
    break_end_time text,
    break_start_time text,
    day_name text,
    day_of_week text,
    end_time text,
    hours text,
    start_time text,
    week text,
    work_day_type text,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee_standard_hour(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee_standard_hour(employee_id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (work_type_id) REFERENCES work_type(id)
);

CREATE TABLE employee_standard_hour (
    business_id text,
    employee_id text,
    advanced_work_week_configuration text,
    full_time_equivalent_hour text,
    standard_hours_per_day text,
    standard_hours_per_week text,
    standard_hours_reference_date text,
    use_advanced_work_week text,
    PRIMARY KEY (business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE business_tag (
    id text,
    business_id text,
    "name" text,
    PRIMARY KEY (id, business_id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE timesheet_break (
    "index" text,
    timesheet_id text,
    end_time text,
    is_paid_break text,
    start_time text,
    PRIMARY KEY ("index", timesheet_id),
    FOREIGN KEY (timesheet_id) REFERENCES timesheet(id)
);

CREATE TABLE timesheet_shift_condition (
    id text,
    timesheet_id text,
    "name" text,
    PRIMARY KEY (id, timesheet_id),
    FOREIGN KEY (timesheet_id) REFERENCES timesheet(id)
);

CREATE TABLE timesheet_dimension_value (
    id text,
    timesheet_id text,
    "name" text,
    reporting_dimension_id text,
    PRIMARY KEY (id, timesheet_id),
    FOREIGN KEY (timesheet_id) REFERENCES timesheet(id)
);

CREATE TABLE timesheet (
    id text,
    attachment_id text,
    business_id text,
    employee_id text,
    leave_category_id text,
    location_id text,
    pay_category_id text,
    work_type_id text,
    attachment_data text,
    attachment_date_created text,
    attachment_date_scanned text,
    attachment_friendly_name text,
    attachment_is_deleted text,
    attachment_is_infected text,
    attachment_url text,
    classification text,
    classification_id text,
    "comment" text,
    end_time text,
    external_id text,
    fully_qualified_location_name text,
    hidden_comment text,
    location_is_deleted text,
    rate text,
    shift_condition_ids jsonb,
    "source" text,
    start_time text,
    "status" text,
    submitted_by_user text,
    unit text,
    work_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (attachment_id) REFERENCES leave_request(attachment_id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (leave_category_id) REFERENCES leave_category(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (pay_category_id) REFERENCES pay_category(id),
    FOREIGN KEY (work_type_id) REFERENCES work_type(id)
);

CREATE TABLE employee_super_adjustment (
    id text,
    business_id text,
    employee_id text,
    adjustment_type text,
    amount double precision,
    contribution_type text,
    expiry_date text,
    from_date text,
    is_active text,
    maximum_amount_paid double precision,
    note text,
    total_amount_paid double precision,
    PRIMARY KEY (id, business_id, employee_id),
    FOREIGN KEY (business_id) REFERENCES employee(business_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_group_filter (
    _fivetran_id text,
    employee_group_id text,
    filter_type text,
    operator text,
    "value" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (employee_group_id) REFERENCES employee_group(id)
);

CREATE TABLE employee_group (
    id text,
    business_id text,
    filter_combination_strategy text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE location (
    id text,
    business_id text,
    parent_id text,
    country text,
    default_shift_condition_ids jsonb,
    external_accounting_location_id text,
    external_id text,
    fully_qualified_name text,
    general_ledger_mapping_code text,
    is_global text,
    is_rollup_reporting_location text,
    "name" text,
    "source" text,
    "state" text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (parent_id) REFERENCES location(id)
);

CREATE TABLE employing_entity (
    id text,
    business_id text,
    abn text,
    address_line_1 text,
    address_line_2 text,
    branch_code text,
    contact_email_address text,
    contact_fax_number text,
    contact_name text,
    contact_phone_number text,
    external_reference_id text,
    fbt_exempt_organisation_type text,
    foreign_entity_country text,
    has_separate_entertainment_fringe_benefits_cap text,
    is_exempt_from_fringe_benefits_tax text,
    is_foreign_entity text,
    "name" text,
    pay_slip_from_email_address text,
    postcode text,
    signatory_name text,
    "state" text,
    suburb text,
    PRIMARY KEY (id, business_id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE invoice_line_item_detail (
    _fivetran_id text,
    invoice_id text,
    invoice_line_item_index text,
    description text,
    group_name text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice_line_item(invoice_id),
    FOREIGN KEY (invoice_line_item_index) REFERENCES invoice_line_item("index")
);

CREATE TABLE invoice_line_item (
    "index" text,
    invoice_id text,
    business_id text,
    billing_plan text,
    brand_name text,
    business_number text,
    description text,
    quantity text,
    total_including_gst text,
    unit_price_including_gst text,
    white_label_name text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE invoice (
    id text,
    business_id text,
    culture_name text,
    currency text,
    "date" timestamp,
    gst text,
    invoice_number text,
    total_excluding_gst text,
    total_including_gst text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE deduction_category (
    id text,
    business_id text,
    expense_general_ledger_mapping_code text,
    external_id text,
    is_resc text,
    is_system text,
    liability_general_ledger_mapping_code text,
    "name" text,
    payment_summary_classification text,
    sgc_calculation_impact text,
    "source" text,
    tax_exempt text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);

CREATE TABLE leave_allowance_template_leave_category (
    leave_allowance_template_id text,
    leave_category_id text,
    accrual_rule_leave_year_offset_amount text,
    leave_accrual_rule_accrual_type text,
    leave_accrual_rule_accrue_in_advance text,
    leave_accrual_rule_cap_type text,
    leave_accrual_rule_carry_over_amount text,
    leave_accrual_rule_carry_over_behaviour text,
    leave_accrual_rule_unit_cap text,
    PRIMARY KEY (leave_allowance_template_id, leave_category_id),
    FOREIGN KEY (leave_allowance_template_id) REFERENCES leave_allowance_template(id),
    FOREIGN KEY (leave_category_id) REFERENCES leave_category(id)
);

CREATE TABLE leave_allowance_template (
    id text,
    business_id text,
    leave_loading_calculated_from_pay_category_id text,
    award_id text,
    award_name text,
    external_id text,
    leave_year_start text,
    "name" text,
    "source" text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id),
    FOREIGN KEY (leave_loading_calculated_from_pay_category_id) REFERENCES pay_category(id)
);

CREATE TABLE employee_expense_category (
    id text,
    business_id text,
    description text,
    external_id text,
    external_reference_id text,
    external_tax_code_id text,
    general_ledger_mapping_code text,
    "name" text,
    tax_code text,
    tax_rate text,
    PRIMARY KEY (id),
    FOREIGN KEY (business_id) REFERENCES business(id)
);
