CREATE TABLE export_community_label (
    "index" text,
    document_id text,
    label text,
    PRIMARY KEY ("index", document_id),
    FOREIGN KEY (document_id) REFERENCES export_community(document_id)
);

CREATE TABLE product_tag (
    "index" text,
    document_id text,
    product_tag text,
    PRIMARY KEY ("index", document_id),
    FOREIGN KEY (document_id) REFERENCES export_community(document_id)
);

CREATE TABLE request_header_referrer_url (
    "index" text,
    document_id text,
    request_header_referrer_url text,
    PRIMARY KEY ("index", document_id),
    FOREIGN KEY (document_id) REFERENCES export_community(document_id)
);

CREATE TABLE request_header_referrer_host (
    "index" text,
    document_id text,
    request_header_referrer_host text,
    PRIMARY KEY ("index", document_id),
    FOREIGN KEY (document_id) REFERENCES export_community(document_id)
);

CREATE TABLE export_community (
    document_id text,
    action_duration text,
    action_is_moderator_action text,
    action_is_solution_view text,
    action_key text,
    action_span_second text,
    action_weight text,
    badge_activation_date text,
    badge_is_retroactive text,
    badge_title text,
    badge_uid text,
    board_title text,
    board_uid text,
    community_app text,
    community_audit_board_com text,
    conversation_title text,
    conversation_uid text,
    event_time_ms text,
    group_hub_uid text,
    message_is_topic text,
    message_subject text,
    message_type text,
    message_uid text,
    node_ancestor_path text,
    occasion_end_time text,
    occasion_is_invited text,
    occasion_rsvp_response text,
    occasion_start_time text,
    parent_conversation_uid text,
    private_message_new_thread text,
    private_message_type text,
    product_is_product_page text,
    product_mention text,
    product_title text,
    product_uid text,
    request_device text,
    request_geo_city text,
    request_geo_country text,
    request_geo_country_code text,
    request_geo_geohash text,
    request_geo_latitude text,
    request_geo_longitude text,
    request_geo_postal text,
    request_geo_region text,
    request_geo_timezone text,
    request_headers_user_agent text,
    request_url_host text,
    search_entity_type text,
    search_filter text,
    search_has_result text,
    search_is_promoted_search_result text,
    search_location text,
    search_page_number text,
    search_result text,
    search_terms text,
    search_type text,
    "status" text,
    subscription_type text,
    survey_id text,
    survey_response text,
    survey_type text,
    tags text,
    target_user_community_rank_name text,
    target_user_community_role_name text,
    target_user_login text,
    target_user_registration_status text,
    target_user_sso_id text,
    target_user_uid text,
    user_community_rank_name text,
    user_community_role_name text,
    user_login text,
    user_registration_status text,
    user_sso_id text,
    user_uid text,
    visit_id text,
    visitor_id text,
    PRIMARY KEY (document_id)
);
