CREATE TABLE group_link (
    id text,
    group_id text,
    issued_by_id text,
    created_at text,
    email text,
    enabled text,
    last_used_at text,
    "name" text,
    phone text,
    quick_response_code_type text,
    updated_at text,
    valid_from text,
    valid_until text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (issued_by_id) REFERENCES member(user_id)
);

CREATE TABLE role_assignment (
    id text,
    issued_by_id text,
    organization_id text,
    role_id text,
    user_id text,
    created_at text,
    notify text,
    scope text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (issued_by_id) REFERENCES member(user_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (role_id) REFERENCES "role"(id),
    FOREIGN KEY (user_id) REFERENCES member(user_id)
);

CREATE TABLE groups (
    id text,
    place_id text,
    created_at text,
    description text,
    elevator_stops_count text,
    geofence_restriction_enabled text,
    geofence_restriction_radius text,
    login_enabled text,
    "name" text,
    primary_device_restriction_enabled text,
    reader_restriction_enabled text,
    time_restriction_enabled text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE controller_input (
    id text,
    controller_id text,
    controller_input_connection_id text,
    channel text,
    created_at text,
    "name" text,
    "status" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (controller_id) REFERENCES controller(id),
    FOREIGN KEY (controller_input_connection_id) REFERENCES controller_input_connection(id)
);

CREATE TABLE lock (
    id text,
    floor_id text,
    integration_id text,
    place_id text,
    configured text,
    created_at text,
    description text,
    favorite text,
    first_to_arrive_required_until text,
    first_to_arrive_satisfied text,
    first_to_arrive_valid_until text,
    geofence_restriction_enabled text,
    geofence_restriction_radius text,
    is_open text,
    "name" text,
    on_scheduled_unlock text,
    online text,
    order_id text,
    reader_restriction_enabled text,
    time_restriction_enabled text,
    time_restriction_time_zone text,
    unlocked text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (floor_id) REFERENCES floor(id),
    FOREIGN KEY (integration_id) REFERENCES integration(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE controller_wiegand (
    id text,
    controller_id text,
    controller_wiegand_connection_id text,
    channel text,
    PRIMARY KEY (id),
    FOREIGN KEY (controller_id) REFERENCES controller(id),
    FOREIGN KEY (controller_wiegand_connection_id) REFERENCES controller_wiegand_connection(id)
);

CREATE TABLE elevator (
    id text,
    integration_id text,
    place_id text,
    created_at text,
    description text,
    "name" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (integration_id) REFERENCES integration(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE elevator_stop (
    id text,
    elevator_id text,
    floor_id text,
    place_id text,
    created_at text,
    locked_down text,
    locked_down_since text,
    "name" text,
    on_scheduled_permit text,
    permitted text,
    time_restriction_enabled text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (elevator_id) REFERENCES elevator(id),
    FOREIGN KEY (floor_id) REFERENCES floor(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE member (
    id text,
    organization_id text,
    access_enabled text,
    card_assigned_by_id text,
    confirmed text,
    created_at text,
    image text,
    last_accessed_at text,
    login_last_used_at text,
    "name" text,
    notes text,
    password_flow_enabled text,
    scim_access_enabled text,
    shares_count text,
    updated_at text,
    user_email text,
    user_id text,
    user_name text,
    user_otp_required_for_login text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE card (
    id text,
    assigned text,
    card_id text,
    color text,
    facility_code text,
    form_factor text,
    frequency text,
    model text,
    number text,
    oem text,
    scanned_at text,
    send_two_factor_pin_notification text,
    sub_type text,
    third_party text,
    token text,
    two_factor_pin text,
    "type" text,
    uid text,
    PRIMARY KEY (id)
);

CREATE TABLE organization (
    id text,
    transfer_to_id text,
    user_id text,
    address text,
    description text,
    domain text,
    logo text,
    metadata text,
    "name" text,
    places_count text,
    scim_enabled text,
    send_emails text,
    sso_expiration_override text,
    sso_expiration_override_enabled text,
    sso_flow_enabled text,
    time_zone text,
    web_authentication_api_enabled text,
    PRIMARY KEY (id),
    FOREIGN KEY (transfer_to_id) REFERENCES member(user_id),
    FOREIGN KEY (user_id) REFERENCES member(user_id)
);

CREATE TABLE "role" (
    id text,
    permissions_alert_policy_read text,
    permissions_alert_policy_write text,
    permissions_analytic_read text,
    permissions_camera_read text,
    permissions_camera_snapshot_read text,
    permissions_camera_snapshot_write text,
    permissions_camera_write text,
    permissions_capacity_read text,
    permissions_capacity_write text,
    permissions_card_activate text,
    permissions_card_read text,
    permissions_card_write text,
    permissions_csv_card_import_read text,
    permissions_csv_card_import_write text,
    permissions_csv_user_import_read text,
    permissions_csv_user_import_write text,
    permissions_dashboards_read text,
    permissions_elevator_read text,
    permissions_elevator_stop_read text,
    permissions_elevator_stop_write text,
    permissions_elevator_write text,
    permissions_event_export_reporter_read text,
    permissions_event_export_reporter_write text,
    permissions_event_read text,
    permissions_floor_read text,
    permissions_floor_write text,
    permissions_group_elevator_stop_read text,
    permissions_group_elevator_stop_write text,
    permissions_group_link_read text,
    permissions_group_link_write text,
    permissions_group_lock_read text,
    permissions_group_lock_write text,
    permissions_group_read text,
    permissions_group_write text,
    permissions_hardware_read text,
    permissions_hardware_write text,
    permissions_integration_read text,
    permissions_integration_write text,
    permissions_lock_read text,
    permissions_lock_unlock text,
    permissions_lock_write text,
    permissions_marketplace_installation_read text,
    permissions_marketplace_installation_write text,
    permissions_member_export_reporter_read text,
    permissions_member_export_reporter_write text,
    permissions_member_read text,
    permissions_member_write text,
    permissions_place_analytics_reporter_read text,
    permissions_place_analytics_reporter_write text,
    permissions_place_read text,
    permissions_place_write text,
    permissions_presence_export_reporter_read text,
    permissions_presence_export_reporter_write text,
    permissions_report_read text,
    permissions_report_write text,
    permissions_role_assignment_read text,
    permissions_role_assignment_write text,
    permissions_scanned_card_read text,
    permissions_schedule_read text,
    permissions_schedule_write text,
    permissions_scheduled_report_read text,
    permissions_scheduled_report_write text,
    permissions_share_read text,
    permissions_share_write text,
    permissions_subscription_status_read text,
    permissions_unlock_export_reporter_read text,
    permissions_unlock_export_reporter_write text,
    permissions_zone_read text,
    permissions_zone_reset text,
    permissions_zone_write text,
    scope text,
    PRIMARY KEY (id)
);

CREATE TABLE group_lock (
    id text,
    group_id text,
    lock_id text,
    place_id text,
    created_at text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (lock_id) REFERENCES lock(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE floor (
    id text,
    place_id text,
    created_at text,
    description text,
    "name" text,
    number text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE login (
    id text,
    user_id text,
    created_at text,
    expire text,
    is_primary text,
    last_reauthenticated_at text,
    last_used_at text,
    "name" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES member(user_id)
);

CREATE TABLE reader (
    id text,
    elevator_id text,
    lock_id text,
    place_id text,
    buzzer_enabled text,
    cards_enabled text,
    checkout text,
    configured text,
    created_at text,
    description text,
    device_id text,
    device_unlock_restriction_enabled text,
    ethernet_mac text,
    held_open_alarm_enabled text,
    model text,
    "name" text,
    online text,
    revision text,
    tamper_enabled text,
    tampered text,
    token text,
    updated_at text,
    wave_to_unlock_enabled text,
    wifi_mac text,
    PRIMARY KEY (id),
    FOREIGN KEY (elevator_id) REFERENCES elevator(id),
    FOREIGN KEY (lock_id) REFERENCES lock(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE schedule_holiday (
    "date" text,
    schedule_id text,
    "name" text,
    PRIMARY KEY ("date", schedule_id),
    FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);

CREATE TABLE schedule (
    id text,
    integration_id text,
    place_id text,
    consequence text,
    created_at text,
    enabled text,
    ends_at_date text,
    ignored_holiday jsonb,
    "name" text,
    next_occurence_ends_at text,
    next_occurence_starts_at text,
    observed text,
    override text,
    region text,
    scheduleable_id text,
    scheduleable_name text,
    scheduleable_type text,
    starts_at_date text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (integration_id) REFERENCES integration(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE controller_wiegand_connection (
    id text,
    controller_id text,
    controller_wiegand_id text,
    elevator_id text,
    lock_id text,
    created_at text,
    "name" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, controller_id),
    FOREIGN KEY (controller_id) REFERENCES controller(id),
    FOREIGN KEY (controller_wiegand_id) REFERENCES controller_wiegand(id),
    FOREIGN KEY (elevator_id) REFERENCES elevator(id),
    FOREIGN KEY (lock_id) REFERENCES lock(id)
);

CREATE TABLE group_elevator_stop (
    id text,
    elevator_id text,
    elevator_stop_id text,
    floor_id text,
    group_id text,
    place_id text,
    created_at text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (elevator_id) REFERENCES elevator(id),
    FOREIGN KEY (elevator_stop_id) REFERENCES elevator_stop(id),
    FOREIGN KEY (floor_id) REFERENCES floor(id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE camera (
    id text,
    integration_id text,
    lock_id text,
    place_id text,
    clip_duration text,
    created_at text,
    description text,
    enabled text,
    "name" text,
    number_of_snapshot text,
    remote_id text,
    remote_organization_id text,
    snapshot_offset text,
    supports_clip text,
    supports_image text,
    supports_thumbnail text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (integration_id) REFERENCES integration(id),
    FOREIGN KEY (lock_id) REFERENCES lock(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE place (
    id text,
    organization_id text,
    transfer_to_id text,
    user_id text,
    address text,
    brand_color text,
    color text,
    created_at text,
    current_user_permissions_manage text,
    current_user_permissions_share text,
    description text,
    favorite text,
    geofence_restriction_enabled text,
    geofence_restriction_radius text,
    header_image text,
    header_image_url text,
    image text,
    latitude text,
    locked_down text,
    locked_down_since text,
    logo text,
    longitude text,
    "name" text,
    occupancy_rate text,
    primary_device_restriction_enabled text,
    reader_restriction_enabled text,
    restriction_enabled text,
    restriction_time_slots text,
    restriction_time_zone text,
    time_zone text,
    tz_time_zone text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (transfer_to_id) REFERENCES member(user_id),
    FOREIGN KEY (user_id) REFERENCES member(user_id)
);

CREATE TABLE controller_relay (
    id text,
    controller_id text,
    controller_input_connection_id text,
    aux text,
    channel text,
    created_at text,
    "name" text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (controller_id) REFERENCES controller(id),
    FOREIGN KEY (controller_input_connection_id) REFERENCES controller_input_connection(id)
);

CREATE TABLE integration (
    id text,
    organization_id text,
    place_id text,
    created_at text,
    disabled_due_to_error text,
    disabled_due_to_error_at text,
    enabled text,
    "name" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE controller (
    id text,
    place_id text,
    configured text,
    created_at text,
    description text,
    device_id text,
    ethernet_mac text,
    model text,
    "name" text,
    online text,
    revision text,
    tamper_enabled text,
    token text,
    updated_at text,
    wifi_mac text,
    "zone" text,
    PRIMARY KEY (id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE presence (
    actor_id text,
    place_id text,
    actor_email text,
    actor_name text,
    actor_type text,
    "date" text,
    first_unlock_at text,
    last_unlock_at text,
    last_unlocked_lock_id text,
    last_unlocked_lock_name text,
    "status" text,
    PRIMARY KEY (actor_id, place_id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);

CREATE TABLE controller_relay_connection (
    id text,
    controller_id text,
    controller_relay_id text,
    lock_id text,
    created_at text,
    duration text,
    "name" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, controller_id),
    FOREIGN KEY (controller_id) REFERENCES controller(id),
    FOREIGN KEY (controller_relay_id) REFERENCES controller_relay(id),
    FOREIGN KEY (lock_id) REFERENCES lock(id)
);

CREATE TABLE wireless_locks (
    id text,
    controller_id text,
    lock_id text,
    address text,
    battery_level text,
    channel text,
    created_at text,
    firmware_version text,
    gateway_id text,
    loss_of_rf text,
    loss_of_rs_485 text,
    model text,
    motor_stall text,
    "name" text,
    online text,
    opened text,
    serial_number text,
    unlocked text,
    updated_at text,
    wireless_lock_connection_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (controller_id) REFERENCES controller(id),
    FOREIGN KEY (lock_id) REFERENCES lock(id)
);

CREATE TABLE controller_input_connection (
    id text,
    controller_id text,
    controller_input_id text,
    lock_id text,
    created_at text,
    duration text,
    enabled text,
    end_of_line_main_resistor text,
    end_of_line_second_resistor text,
    end_of_line_type text,
    "name" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, controller_id),
    FOREIGN KEY (controller_id) REFERENCES controller(id),
    FOREIGN KEY (controller_input_id) REFERENCES controller_input(id),
    FOREIGN KEY (lock_id) REFERENCES lock(id)
);

CREATE TABLE event (
    uuid text,
    actor_id text,
    organization_id text,
    place_id text,
    actor_email text,
    actor_name text,
    actor_type text,
    authenticated_by_id text,
    authenticated_by_type text,
    camera_snapshots text,
    created_at text,
    error_code text,
    error_message text,
    object_id text,
    object_name text,
    object_type text,
    "sequence" text,
    success text,
    "type" text,
    via jsonb,
    PRIMARY KEY (uuid),
    FOREIGN KEY (actor_id) REFERENCES presence(actor_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (place_id) REFERENCES place(id)
);
