CREATE TABLE inventory (
    id text,
    outlet_id text,
    product_id text,
    average_cost text,
    current_amount text,
    deleted_at timestamp,
    inventory_level text,
    reorder_amount text,
    reorder_point text,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (outlet_id) REFERENCES outlet(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE supplier (
    id text,
    contact_company_name text,
    contact_email text,
    contact_fax text,
    contact_first_name text,
    contact_last_name text,
    contact_mobile text,
    contact_phone text,
    contact_physical_address_1 text,
    contact_physical_address_2 text,
    contact_physical_city text,
    contact_physical_country_id text,
    contact_physical_postcode text,
    contact_physical_state text,
    contact_physical_suburb text,
    contact_postal_address_1 text,
    contact_postal_address_2 text,
    contact_postal_city text,
    contact_postal_country_id text,
    contact_postal_postcode text,
    contact_postal_state text,
    contact_postal_suburb text,
    contact_twitter text,
    contact_website text,
    default_markup text,
    deleted_at timestamp,
    description text,
    "name" text,
    "source" text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE outlet (
    id text,
    attributes jsonb,
    currency text,
    currency_symbol text,
    deleted_at timestamp,
    display_price text,
    email text,
    latitude text,
    longitude text,
    "name" text,
    phone text,
    physical_address_1 text,
    physical_address_2 text,
    physical_city text,
    physical_country_id text,
    physical_postcode text,
    physical_state text,
    physical_suburb text,
    time_zone text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE brand (
    id text,
    deleted_at timestamp,
    description text,
    "name" text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE product_tag (
    id text,
    product_id text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (id) REFERENCES tags(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_category_tag (
    id text,
    product_id text,
    deleted_at text,
    "name" text,
    version text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (id) REFERENCES tags(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_variant_option (
    id text,
    product_id text,
    "name" text,
    values jsonb,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_supplier (
    id text,
    product_id text,
    supplier_id text,
    code text,
    price text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE product_code (
    "index" text,
    product_id text,
    code text,
    id text,
    "type" text,
    PRIMARY KEY ("index", product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    brand_id text,
    product_category_id text,
    supplier_id text,
    account_code text,
    account_code_purchase text,
    active text,
    attributes jsonb,
    button_order text,
    created_at timestamp,
    deleted_at timestamp,
    description text,
    dimensions_unit text,
    ecwid_enabled_webstore text,
    family_id text,
    handle text,
    has_inventory text,
    height text,
    image_thumbnail_url text,
    image_url text,
    images jsonb,
    is_active text,
    is_composite text,
    is_variant text,
    length text,
    loyalty_amount text,
    "name" text,
    packaging_breaks_into jsonb,
    packaging_made_from jsonb,
    price_excluding_tax text,
    price_including_tax text,
    sku text,
    sku_images jsonb,
    "source" text,
    source_id text,
    source_variant_id text,
    supplier_code text,
    supply_price text,
    type_deleted_at text,
    type_version text,
    updated_at timestamp,
    variant_count text,
    variant_name text,
    variant_parent_id text,
    version text,
    weight text,
    weight_unit text,
    width text,
    PRIMARY KEY (id),
    FOREIGN KEY (brand_id) REFERENCES brand(id),
    FOREIGN KEY (product_category_id) REFERENCES product_category(id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE retailer (
    id text,
    discount_product_id text,
    account_status text,
    account_type text,
    activated_at timestamp,
    country text,
    create_customer_by_email_receipt text,
    created_at timestamp,
    culture text,
    currency_code text,
    currency_symbol text,
    default_dimensions_unit text,
    default_tax_id text,
    default_weight_unit text,
    disable_onboarding_tour text,
    domain_prefix text,
    ecwid_onboarding_survey_state text,
    embedded_barcode_option text,
    enabled_integrations jsonb,
    enabled_platform_apps jsonb,
    gift_cards_enabled text,
    gift_cards_never_enabled text,
    has_web_register text,
    label_printer_format text,
    lightspeed_unique_id text,
    loyalty_claim_url text,
    loyalty_enabled text,
    loyalty_offer_signup_bonus text,
    loyalty_ratio text,
    loyalty_send_welcome_email text,
    loyalty_signup_bonus text,
    "name" text,
    no_tax_group_id text,
    on_account_default_limit text,
    register_migration_date text,
    require_password_on_user_switch text,
    restriction_state text,
    restriction_state_reason text,
    sku_sequence_enabled text,
    sku_sequence_value text,
    sso_enabled text,
    store_credit text,
    store_url text,
    subscription_plan_version text,
    subscription_state text,
    subscription_trial_expires_at text,
    tax_exclusive text,
    terms_and_conditions_accepted text,
    terms_and_conditions_effective_date text,
    terms_and_conditions_terms_version text,
    timezone jsonb,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (discount_product_id) REFERENCES product(id)
);

CREATE TABLE cosignment (
    id text,
    outlet_id text,
    source_outlet_id text,
    supplier_id text,
    consignment_date timestamp,
    created_at timestamp,
    deleted_at timestamp,
    due_at timestamp,
    "name" text,
    received_at timestamp,
    reference text,
    "status" text,
    supplier_invoice text,
    total_cost_gain text,
    total_cost_loss text,
    total_count_gain text,
    total_count_loss text,
    updated_at timestamp,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (outlet_id) REFERENCES outlet(id),
    FOREIGN KEY (source_outlet_id) REFERENCES outlet(id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id)
);

CREATE TABLE users_role (
    id text,
    users_id text,
    "name" text,
    system_role_id text,
    PRIMARY KEY (id, users_id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    account_type text,
    created_at timestamp,
    deleted_at timestamp,
    display_name text,
    email text,
    email_verified_at text,
    enabled text,
    enabled_mfa text,
    image_original text,
    image_sl text,
    image_sm text,
    image_source text,
    image_ss text,
    image_st text,
    image_standard text,
    image_thumb text,
    is_primary_user text,
    permission jsonb,
    require_password_change text,
    restricted_outlet_ids jsonb,
    rules jsonb,
    seen_at timestamp,
    switch_id text,
    target_daily text,
    target_monthly text,
    target_weekly text,
    time_until_deletion text,
    updated_at timestamp,
    username text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE tags (
    id text,
    deleted_at timestamp,
    "name" text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE sale_line_item (
    id text,
    sale_id text,
    product_id text,
    cost text,
    discount text,
    discount_total text,
    gift_card_number text,
    is_return text,
    loyalty_value text,
    note text,
    price text,
    price_set text,
    price_total text,
    promotions jsonb,
    quantity text,
    return_reason text,
    sales_person_id text,
    "sequence" text,
    "status" text,
    surcharges jsonb,
    tax text,
    tax_components jsonb,
    tax_id text,
    unit_cost text,
    unit_discount text,
    unit_loyalty_value text,
    unit_price text,
    unit_tax text,
    PRIMARY KEY (id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sale_payment (
    id text,
    sale_id text,
    outlet_id text,
    amount text,
    deleted_at timestamp,
    external_applications jsonb,
    external_attributes jsonb,
    "name" text,
    payment_date timestamp,
    register_id text,
    register_open_sequence_id text,
    retailer_payment_type_id text,
    source_id text,
    surcharge jsonb,
    PRIMARY KEY (id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id),
    FOREIGN KEY (outlet_id) REFERENCES outlet(id)
);

CREATE TABLE sale_adjustment (
    "index" text,
    sale_id text,
    adjustment_type text,
    "name" text,
    tax_components jsonb,
    "value" text,
    PRIMARY KEY ("index", sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_ecom_custom_charge (
    "index" text,
    sale_id text,
    "name" text,
    source_id text,
    tax_components jsonb,
    total text,
    total_incl text,
    total_tax text,
    PRIMARY KEY ("index", sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale_tax (
    id text,
    sale_id text,
    amount text,
    "name" text,
    rate text,
    PRIMARY KEY (id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sale (
    id text,
    customer_id text,
    outlet_id text,
    user_id text,
    accounts_transaction_id text,
    attributes jsonb,
    complete_open_sequence_id text,
    created_at timestamp,
    deleted_at timestamp,
    ecom_custom_charges_total text,
    ecom_custom_charges_total_incl text,
    ecom_custom_charges_total_tax text,
    external_applications jsonb,
    has_unsynced_on_account_payments text,
    invoice_number text,
    invoice_sequence text,
    note text,
    receipt_number text,
    register_id text,
    return_for text,
    return_ids jsonb,
    sale_date timestamp,
    short_code text,
    "source" text,
    source_id text,
    "state" text,
    "status" text,
    total_loyalty text,
    total_surcharge text,
    updated_at timestamp,
    version text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (outlet_id) REFERENCES outlet(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE customer_service_item (
    id text,
    customer_id text,
    created_at timestamp,
    created_by text,
    description text,
    initial_condition text,
    "name" text,
    serial_number text,
    updated_at timestamp,
    updated_by text,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE service_line_item (
    id text,
    service_id text,
    product_id text,
    fulfillment_type text,
    gift_card text,
    is_picklist_pickable text,
    note text,
    price_set text,
    promotions jsonb,
    quantity text,
    register_id text,
    register_sequence_id text,
    sales_person_id text,
    "sequence" text,
    sku text,
    "state" text,
    tax_components jsonb,
    unit_discount text,
    unit_loyalty text,
    unit_price text,
    PRIMARY KEY (id, service_id),
    FOREIGN KEY (service_id) REFERENCES service(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE service (
    id text,
    retailer_id text,
    sale_id text,
    agenda_date text,
    agenda_minutes_scheduled text,
    assigned_user_id text,
    created_at timestamp,
    is_sale_level_discount_percentage text,
    notes jsonb,
    sale_level_discount_value text,
    service_item_created_at timestamp,
    service_item_created_by text,
    service_item_detail_description text,
    service_item_detail_serial_number text,
    service_item_id text,
    service_item_initial_condition text,
    service_item_name text,
    service_item_updated_at timestamp,
    service_item_updated_by text,
    "status" text,
    sub_total text,
    total_amount text,
    total_promotion text,
    total_tax text,
    updated_at timestamp,
    updated_by text,
    PRIMARY KEY (id),
    FOREIGN KEY (retailer_id) REFERENCES retailer(id),
    FOREIGN KEY (sale_id) REFERENCES sale(id)
);

CREATE TABLE sales_fulfillment_line_item (
    id text,
    sale_id text,
    sales_fulfillment_id text,
    product_id text,
    quantity text,
    PRIMARY KEY (id, sale_id, sales_fulfillment_id),
    FOREIGN KEY (sale_id) REFERENCES sales_fulfillment(sale_id),
    FOREIGN KEY (sales_fulfillment_id) REFERENCES sales_fulfillment(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE sales_fulfillment (
    id text,
    sale_id text,
    outlet_id text,
    user_id text,
    created_at timestamp,
    "status" text,
    PRIMARY KEY (id, sale_id),
    FOREIGN KEY (sale_id) REFERENCES sale(id),
    FOREIGN KEY (outlet_id) REFERENCES outlet(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE product_category_path (
    id text,
    product_category_id text,
    "name" text,
    PRIMARY KEY (id, product_category_id),
    FOREIGN KEY (product_category_id) REFERENCES product_category(id)
);

CREATE TABLE product_category (
    id text,
    leaf_category text,
    "name" text,
    parent_category_id text,
    payload_id text,
    root_category_id text,
    PRIMARY KEY (id)
);

CREATE TABLE customer (
    id text,
    balance text,
    company_name text,
    created_at timestamp,
    custom_field_1 text,
    custom_field_2 text,
    custom_field_3 text,
    custom_field_4 text,
    customer_code text,
    customer_group_ids jsonb,
    date_of_birth text,
    deleted_at timestamp,
    do_not_email text,
    email text,
    enable_loyalty text,
    fax text,
    first_name text,
    gender text,
    last_name text,
    loyalty_balance text,
    loyalty_email_sent text,
    mobile text,
    note text,
    on_account_limit text,
    phone text,
    physical_address_1 text,
    physical_address_2 text,
    physical_city text,
    physical_country_id text,
    physical_postcode text,
    physical_state text,
    physical_suburb text,
    postal_address_1 text,
    postal_address_2 text,
    postal_city text,
    postal_country_id text,
    postal_postcode text,
    postal_state text,
    postal_suburb text,
    source_unique_id text,
    tax_id text,
    time_until_deletion text,
    twitter text,
    updated_at timestamp,
    version text,
    website text,
    year_to_date text,
    PRIMARY KEY (id)
);
