CREATE TABLE project_milestone (
    id text,
    project_id text,
    archived_at text,
    created_at text,
    description text,
    "name" text,
    sort_order text,
    target_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE customer_request (
    id text,
    attachment_id text,
    comment_id text,
    creator_id text,
    customer_id text,
    issue_id text,
    original_issue_id text,
    project_attachment_id text,
    project_id text,
    archived_at text,
    body text,
    body_data text,
    color text,
    created_at text,
    priority text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (attachment_id) REFERENCES attachment(id),
    FOREIGN KEY (comment_id) REFERENCES "comment"(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (issue_id) REFERENCES issue(id),
    FOREIGN KEY (original_issue_id) REFERENCES issue(id),
    FOREIGN KEY (project_attachment_id) REFERENCES attachment(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE document (
    id text,
    creator_id text,
    project_id text,
    updated_by text,
    archived_at text,
    color text,
    content text,
    created_at text,
    icon text,
    slug_id text,
    title text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE initiative_history (
    id text,
    initiative_id text,
    archived_at text,
    created_at text,
    entries jsonb,
    updated_at text,
    PRIMARY KEY (id, initiative_id),
    FOREIGN KEY (initiative_id) REFERENCES initiative(id)
);

CREATE TABLE project_status (
    id text,
    archived_at text,
    color text,
    created_at text,
    description text,
    indefinite text,
    "name" text,
    "position" text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE project_member (
    member_id text,
    project_id text,
    PRIMARY KEY (member_id, project_id),
    FOREIGN KEY (member_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_team (
    project_id text,
    team_id text,
    PRIMARY KEY (project_id, team_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE project (
    id text,
    converted_from_issue_id text,
    creator_id text,
    lead_id text,
    status_id text,
    archived_at text,
    auto_archived_at text,
    canceled_at text,
    color text,
    completed_at text,
    completed_scope_history jsonb,
    content text,
    created_at text,
    description text,
    icon text,
    in_progress_scope_history jsonb,
    "name" text,
    progress text,
    project_update_reminders_paused_until_at text,
    scope text,
    scope_history jsonb,
    slack_issue_comment text,
    slack_issue_status text,
    slack_new_issue text,
    slug_id text,
    sort_order text,
    start_date text,
    started_at text,
    target_date text,
    trashed text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (converted_from_issue_id) REFERENCES issue(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (lead_id) REFERENCES users(id),
    FOREIGN KEY (status_id) REFERENCES project_status(id)
);

CREATE TABLE team_membership (
    id text,
    team_id text,
    user_id text,
    archived_at text,
    created_at text,
    owner text,
    sort_order text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (team_id) REFERENCES team(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE roadmap (
    id text,
    creator_id text,
    organization_id text,
    owner_id text,
    archived_at text,
    color text,
    created_at text,
    description text,
    "name" text,
    slug_id text,
    sort_order text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE cycle_uncompleted_issue (
    cycle_id text,
    issue_id text,
    PRIMARY KEY (cycle_id, issue_id),
    FOREIGN KEY (cycle_id) REFERENCES cycle(id),
    FOREIGN KEY (issue_id) REFERENCES issue(id)
);

CREATE TABLE cycle (
    id text,
    team_id text,
    archived_at text,
    auto_archived_at text,
    completed_at text,
    completed_issue_count_history jsonb,
    completed_scope_history jsonb,
    created_at text,
    description text,
    ends_at text,
    in_progress_scope_history jsonb,
    issue_count_history jsonb,
    "name" text,
    number text,
    progress text,
    scope_history jsonb,
    starts_at text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE attachment_metadata (
    "name" text,
    attachment_id text,
    "value" text,
    PRIMARY KEY ("name", attachment_id),
    FOREIGN KEY (attachment_id) REFERENCES attachment(id)
);

CREATE TABLE attachment (
    id text,
    creator_id text,
    external_user_creator_id text,
    issue_id text,
    archived_at text,
    created_at text,
    group_by_source text,
    "source" text,
    source_type text,
    subtitle text,
    title text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (external_user_creator_id) REFERENCES external_user(id),
    FOREIGN KEY (issue_id) REFERENCES issue(id)
);

CREATE TABLE issue_history (
    id text,
    issue_id text,
    actor_id text,
    attachment_id text,
    from_assignee_id text,
    from_cycle_id text,
    from_parent_id text,
    from_project_id text,
    from_state_id text,
    from_team_id text,
    to_assignee_id text,
    to_converted_project_id text,
    to_cycle_id text,
    to_parent_id text,
    to_project_id text,
    to_state_id text,
    to_team_id text,
    added_label_ids jsonb,
    archived text,
    archived_at text,
    auto_archived text,
    auto_closed text,
    changes jsonb,
    created_at text,
    from_due_date text,
    from_estimate text,
    from_priority text,
    from_title text,
    removed_label_ids jsonb,
    to_due_date text,
    to_estimate text,
    to_priority text,
    to_title text,
    trashed text,
    updated_at text,
    updated_description text,
    PRIMARY KEY (id, issue_id),
    FOREIGN KEY (issue_id) REFERENCES issue(id),
    FOREIGN KEY (actor_id) REFERENCES users(id),
    FOREIGN KEY (attachment_id) REFERENCES attachment(id),
    FOREIGN KEY (from_assignee_id) REFERENCES users(id),
    FOREIGN KEY (from_cycle_id) REFERENCES cycle(id),
    FOREIGN KEY (from_parent_id) REFERENCES issue(id),
    FOREIGN KEY (from_project_id) REFERENCES project(id),
    FOREIGN KEY (from_state_id) REFERENCES workflow_state(id),
    FOREIGN KEY (from_team_id) REFERENCES team(id),
    FOREIGN KEY (to_assignee_id) REFERENCES users(id),
    FOREIGN KEY (to_converted_project_id) REFERENCES project(id),
    FOREIGN KEY (to_cycle_id) REFERENCES cycle(id),
    FOREIGN KEY (to_parent_id) REFERENCES issue(id),
    FOREIGN KEY (to_project_id) REFERENCES project(id),
    FOREIGN KEY (to_state_id) REFERENCES workflow_state(id),
    FOREIGN KEY (to_team_id) REFERENCES team(id)
);

CREATE TABLE workflow_state (
    id text,
    team_id text,
    archived_at text,
    color text,
    created_at text,
    description text,
    "name" text,
    "position" text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE initiative (
    id text,
    creator_id text,
    organization_id text,
    owner_id text,
    project_id text,
    team_id text,
    archived_at text,
    color text,
    completed_at text,
    content text,
    created_at text,
    description text,
    frequency_resolution text,
    health text,
    health_updated_at text,
    icon text,
    integration_setting_archived_at text,
    integration_setting_context_view_type text,
    integration_setting_created_at text,
    integration_setting_id text,
    integration_setting_project_id text,
    integration_setting_slack_initiative_update_created text,
    integration_setting_slack_issue_added_to_triage text,
    integration_setting_slack_issue_added_to_view text,
    integration_setting_slack_issue_created text,
    integration_setting_slack_issue_new_comment text,
    integration_setting_slack_issue_sla_breached text,
    integration_setting_slack_issue_sla_high_risk text,
    integration_setting_slack_issue_status_changed_all text,
    integration_setting_slack_issue_status_changed_done text,
    integration_setting_slack_project_update_created text,
    integration_setting_slack_project_update_created_to_team text,
    integration_setting_slack_project_update_created_to_workspace text,
    integration_setting_team_id text,
    integration_setting_updated_at text,
    last_update_id text,
    "name" text,
    slug_id text,
    sort_order text,
    started_at text,
    "status" text,
    target_date text,
    target_date_resolution text,
    trashed text,
    update_reminder_frequency text,
    update_reminder_frequency_in_weeks text,
    update_reminders_day text,
    update_reminders_hour text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE issue_subscriber (
    issue_id text,
    subscriber_id text,
    PRIMARY KEY (issue_id, subscriber_id),
    FOREIGN KEY (issue_id) REFERENCES issue(id),
    FOREIGN KEY (subscriber_id) REFERENCES users(id)
);

CREATE TABLE issue_label (
    "index" text,
    issue_id text,
    label_id text,
    PRIMARY KEY ("index", issue_id),
    FOREIGN KEY (issue_id) REFERENCES issue(id),
    FOREIGN KEY (label_id) REFERENCES label(id)
);

CREATE TABLE issue (
    id text,
    assignee_id text,
    creator_id text,
    cycle_id text,
    external_user_creator_id text,
    parent_id text,
    project_id text,
    project_milestone_id text,
    state_id text,
    team_id text,
    archived_at text,
    auto_archived_at text,
    auto_closed_at text,
    branch_name text,
    canceled_at text,
    completed_at text,
    created_at text,
    customer_ticket_count text,
    description text,
    due_date text,
    estimate text,
    identifier text,
    number text,
    priority text,
    priority_label text,
    sla_breaches_at text,
    sla_started_at text,
    snoozed_until_at text,
    sort_order text,
    started_at text,
    started_triage_at text,
    title text,
    trashed text,
    triaged_at text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (assignee_id) REFERENCES users(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (cycle_id) REFERENCES cycle(id),
    FOREIGN KEY (external_user_creator_id) REFERENCES external_user(id),
    FOREIGN KEY (parent_id) REFERENCES issue(id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (project_milestone_id) REFERENCES project_milestone(id),
    FOREIGN KEY (state_id) REFERENCES workflow_state(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE label_children (
    label_children_id text,
    label_id text,
    PRIMARY KEY (label_children_id, label_id),
    FOREIGN KEY (label_children_id) REFERENCES label(id),
    FOREIGN KEY (label_id) REFERENCES label(id)
);

CREATE TABLE label (
    id text,
    creator_id text,
    parent_id text,
    team_id text,
    archived_at text,
    color text,
    created_at text,
    description text,
    is_group text,
    "name" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (parent_id) REFERENCES label(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE team_member (
    member_id text,
    team_id text,
    PRIMARY KEY (member_id, team_id),
    FOREIGN KEY (member_id) REFERENCES users(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE team (
    id text,
    active_cycle_id text,
    auto_close_state_id text,
    organization_id text,
    start_workflow_state_id text,
    archived_at text,
    auto_archive_period text,
    auto_close_period text,
    color text,
    created_at text,
    cycle_calendar_url text,
    cycle_cooldown_time text,
    cycle_duration text,
    cycle_enabled text,
    cycle_issue_auto_assign_completed text,
    cycle_issue_auto_assign_started text,
    cycle_lock_to_active text,
    cycle_start_day text,
    default_issue_estimate text,
    description text,
    group_issue_history text,
    icon text,
    invite_hash text,
    issue_count text,
    issue_estimation_allow_zero text,
    issue_estimation_extended text,
    issue_estimation_type text,
    issue_ordering_no_priority_first text,
    issue_sort_order_default_to_bottom text,
    "key" text,
    "name" text,
    private text,
    require_priority_to_leave_triage text,
    slack_issue_comment text,
    slack_issue_status text,
    slack_new_issue text,
    timezone text,
    triage_enabled text,
    upcoming_cycle_count text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (active_cycle_id) REFERENCES cycle(id),
    FOREIGN KEY (auto_close_state_id) REFERENCES workflow_state(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (start_workflow_state_id) REFERENCES workflow_state(id)
);

CREATE TABLE project_update_comment (
    comment_id text,
    project_update_id text,
    PRIMARY KEY (comment_id, project_update_id),
    FOREIGN KEY (comment_id) REFERENCES "comment"(id),
    FOREIGN KEY (project_update_id) REFERENCES project_update(id)
);

CREATE TABLE project_update_reaction (
    id text,
    project_update_id text,
    comment_id text,
    external_user_id text,
    issue_id text,
    archived_at text,
    created_at text,
    emoji text,
    initiative_update_id text,
    post_id text,
    updated_at text,
    user_id text,
    PRIMARY KEY (id, project_update_id),
    FOREIGN KEY (project_update_id) REFERENCES project_update(id),
    FOREIGN KEY (comment_id) REFERENCES "comment"(id),
    FOREIGN KEY (external_user_id) REFERENCES external_user(id),
    FOREIGN KEY (issue_id) REFERENCES issue(id)
);

CREATE TABLE project_update (
    id text,
    project_id text,
    user_id text,
    archived_at text,
    body text,
    body_data text,
    created_at text,
    diff jsonb,
    diff_markdown text,
    edited_at text,
    health text,
    info_snapshot jsonb,
    is_diff_hidden text,
    is_stale text,
    reaction_data jsonb,
    slug_id text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE initiative_to_project (
    id text,
    initiative_id text,
    project_id text,
    archived_at text,
    created_at text,
    sort_order text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (initiative_id) REFERENCES initiative(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE users (
    id text,
    organization_id text,
    active text,
    "admin" text,
    archived_at text,
    avatar_url text,
    calendar_hash text,
    created_at text,
    created_issue_count text,
    description text,
    disable_reason text,
    display_name text,
    email text,
    guest text,
    invite_hash text,
    last_seen text,
    "name" text,
    status_emoji text,
    status_label text,
    status_until_at text,
    timezone text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE roadmap_to_project (
    id text,
    project_id text,
    roadmap_id text,
    archived_at text,
    created_at text,
    sort_order text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (roadmap_id) REFERENCES roadmap(id)
);

CREATE TABLE organization (
    id text,
    subscription_creator_id text,
    allow_members_to_invite text,
    archived_at text,
    created_at text,
    deletion_requested_at text,
    git_branch_format text,
    git_linkback_messages_enabled text,
    git_public_linkback_messages_enabled text,
    logo_url text,
    "name" text,
    period_upload_volume text,
    previous_url_key jsonb,
    project_update_reminders_day text,
    project_update_reminders_hour text,
    project_updates_reminder_frequency text,
    release_channel text,
    roadmap_enabled text,
    saml_enabled text,
    scim_enabled text,
    subscription_archived_at text,
    subscription_canceled_at text,
    subscription_created_at text,
    subscription_id text,
    subscription_next_billing_at text,
    subscription_pending_change_type text,
    subscription_seats text,
    subscription_seats_maximum text,
    subscription_seats_minimum text,
    subscription_type text,
    subscription_updated_at text,
    trial_ends_at text,
    updated_at text,
    url_key text,
    PRIMARY KEY (id),
    FOREIGN KEY (subscription_creator_id) REFERENCES users(id)
);

CREATE TABLE integration (
    id text,
    creator_id text,
    organization_id text,
    team_id text,
    archived_at text,
    created_at text,
    service text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE external_user (
    id text,
    organization_id text,
    archived_at text,
    avatar_url text,
    created_at text,
    display_name text,
    email text,
    last_seen text,
    "name" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE "comment" (
    id text,
    external_user_id text,
    issue_id text,
    parent_id text,
    user_id text,
    archived_at text,
    body text,
    body_data text,
    created_at text,
    edited_at text,
    reaction_data jsonb,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (external_user_id) REFERENCES external_user(id),
    FOREIGN KEY (issue_id) REFERENCES issue(id),
    FOREIGN KEY (parent_id) REFERENCES "comment"(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE customer (
    id text,
    integration_id text,
    owner_id text,
    status_id text,
    approximate_need_count text,
    archived_at text,
    created_at text,
    domains jsonb,
    external_ids jsonb,
    logo_url text,
    main_source_id text,
    "name" text,
    revenue text,
    "size" text,
    slack_channel_id text,
    slug_id text,
    tier_archived_at text,
    tier_color text,
    tier_created_at text,
    tier_description text,
    tier_display_name text,
    tier_id text,
    tier_name text,
    tier_position text,
    tier_updated_at text,
    updated_at timestamp,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (integration_id) REFERENCES integration(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (status_id) REFERENCES project_status(id)
);
