CREATE TABLE organization (
    id text,
    average_job_value text,
    city text,
    country text,
    created_at text,
    custom_choice_10_label text,
    custom_choice_1_label text,
    custom_choice_2_label text,
    custom_choice_3_label text,
    custom_choice_4_label text,
    custom_choice_5_label text,
    custom_choice_6_label text,
    custom_choice_7_label text,
    custom_choice_8_label text,
    custom_choice_9_label text,
    customer_lifetime text,
    customer_lifetime_interval text,
    email text,
    external_name text,
    franchise_royalty_percentage text,
    jobs_performed_per_interval text,
    latitude text,
    locale text,
    longitude text,
    marketing_radius_miles text,
    "name" text,
    net_promoter_score text,
    one_to_five_rating text,
    operating_radius_miles text,
    parent_id text,
    phone_number text,
    postal_code text,
    recurring_jobs_interval text,
    reference text,
    region text,
    root_id text,
    "status" text,
    street_address text,
    time_zone text,
    "type" text,
    updated_at text,
    website text,
    zero_to_ten_rating text,
    PRIMARY KEY (id)
);

CREATE TABLE membership (
    id text,
    organization_id text,
    accepted_at text,
    country text,
    created_at text,
    email text,
    first_name text,
    invited_by_id text,
    last_name text,
    mobile_phone_number text,
    revoked_at text,
    "role" text,
    "status" text,
    user_id text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE custom_attribute (
    _fivetran_id text,
    organization_id text,
    attach_to text,
    created_at text,
    mandatory text,
    "name" text,
    ordinal text,
    restrict_to_predefined_choices text,
    updated_at text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE review_note (
    "index" text,
    organization_id text,
    review_id text,
    author_name text,
    body text,
    created_at text,
    PRIMARY KEY ("index", organization_id, review_id),
    FOREIGN KEY (organization_id) REFERENCES review(organization_id),
    FOREIGN KEY (review_id) REFERENCES review(id)
);

CREATE TABLE review (
    id text,
    organization_id text,
    censored text,
    comments text,
    completed_at text,
    customer_full_name text,
    customer_reference text,
    customer_work_city text,
    customer_work_email text,
    customer_work_region text,
    flagged_for_follow_up text,
    has_notes text,
    initial text,
    invited_at text,
    job_reference text,
    net_promoter_label text,
    organization_reference text,
    public_display_comments text,
    public_display_customer_location text,
    public_response text,
    public_reviewer_name text,
    recommendation_likelihood text,
    updated_at text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE customer (
    id text,
    organization_id text,
    company_name text,
    created_at text,
    custom_choice_10_label text,
    custom_choice_1_label text,
    custom_choice_2_label text,
    custom_choice_3_label text,
    custom_choice_4_label text,
    custom_choice_5_label text,
    custom_choice_6_label text,
    custom_choice_7_label text,
    custom_choice_8_label text,
    custom_choice_9_label text,
    first_name text,
    full_name text,
    last_name text,
    last_survey_bounced text,
    mobile_phone_number text,
    "name" text,
    net_promoter_label text,
    permits_contact text,
    permits_email_contact text,
    permits_sms_contact text,
    reference text,
    "status" text,
    title text,
    updated_at text,
    work_city text,
    work_country text,
    work_email text,
    work_phone_number text,
    work_postal_code text,
    work_region text,
    work_street text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE job_performer (
    id text,
    job_id text,
    organization_id text,
    country text,
    created_at text,
    email text,
    mobile_phone_number text,
    "name" text,
    reference text,
    "status" text,
    PRIMARY KEY (id, job_id, organization_id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (organization_id) REFERENCES job(organization_id)
);

CREATE TABLE job (
    id text,
    organization_id text,
    customer_id text,
    commenced_at text,
    completed_at text,
    created_at text,
    currency text,
    custom_choice_10_label text,
    custom_choice_1_label text,
    custom_choice_2_label text,
    custom_choice_3_label text,
    custom_choice_4_label text,
    custom_choice_5_label text,
    custom_choice_6_label text,
    custom_choice_7_label text,
    custom_choice_8_label text,
    custom_choice_9_label text,
    reference text,
    "status" text,
    updated_at text,
    "value" text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE technician (
    id text,
    organization_id text,
    country text,
    created_at text,
    email text,
    mobile_phone_number text,
    "name" text,
    reference text,
    "status" text,
    PRIMARY KEY (id, organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);
