CREATE TABLE return_review_exchange (
    exchange_id text,
    return_review_id text,
    discount text,
    out_of_stock text,
    out_of_stock_resolution text,
    price text,
    product_id text,
    sku text,
    tax text,
    title text,
    total text,
    "type" text,
    variant_id text,
    PRIMARY KEY (exchange_id, return_review_id),
    FOREIGN KEY (return_review_id) REFERENCES return_review(id)
);

CREATE TABLE return_review_line_item (
    line_item_id text,
    return_review_id text,
    barcode text,
    discount text,
    exchange_variant text,
    outcome text,
    parent_return_reason text,
    price text,
    product_id text,
    provider_line_item_id text,
    refund text,
    return_comment text,
    return_reason text,
    returned_at text,
    sku text,
    tax text,
    title text,
    variant_id text,
    PRIMARY KEY (line_item_id, return_review_id),
    FOREIGN KEY (return_review_id) REFERENCES return_review(id)
);

CREATE TABLE return_review (
    id text,
    address_1 text,
    address_2 text,
    carrier text,
    city text,
    company text,
    country text,
    country_code text,
    created_at text,
    credit_total text,
    currency text,
    customer text,
    destination_id text,
    discount_total text,
    exchange_credit_total text,
    exchange_discount_total text,
    exchange_product_total text,
    exchange_tax_total text,
    exchange_total text,
    gift_card text,
    handling_fee text,
    label_rate text,
    label_status text,
    label_updated_at text,
    label_url text,
    latitude text,
    longitude text,
    method_state text,
    method_type text,
    multi_currency text,
    "name" text,
    order_id text,
    order_name text,
    order_number text,
    outcome text,
    package_reference text,
    phone text,
    product_total text,
    provider text,
    provider_order_id text,
    qr_code_url text,
    refund text,
    return_total text,
    rma_id text,
    scannable_id text,
    scheduled_at text,
    "state" text,
    state_address text,
    status_page_url text,
    tax_total text,
    total text,
    tracking_number text,
    updated_at text,
    upsell text,
    zip text,
    PRIMARY KEY (id)
);

CREATE TABLE return_cancelled_exchange (
    exchange_id text,
    return_cancelled_id text,
    discount text,
    out_of_stock text,
    out_of_stock_resolution text,
    price text,
    product_id text,
    sku text,
    tax text,
    title text,
    total text,
    "type" text,
    variant_id text,
    PRIMARY KEY (exchange_id, return_cancelled_id),
    FOREIGN KEY (return_cancelled_id) REFERENCES return_cancelled(id)
);

CREATE TABLE return_cancelled_line_item (
    line_item_id text,
    return_cancelled_id text,
    barcode text,
    discount text,
    exchange_variant text,
    outcome text,
    parent_return_reason text,
    price text,
    product_id text,
    provider_line_item_id text,
    refund text,
    return_comment text,
    return_reason text,
    returned_at text,
    sku text,
    tax text,
    title text,
    variant_id text,
    PRIMARY KEY (line_item_id, return_cancelled_id),
    FOREIGN KEY (return_cancelled_id) REFERENCES return_cancelled(id)
);

CREATE TABLE return_cancelled (
    id text,
    address_1 text,
    address_2 text,
    carrier text,
    city text,
    company text,
    country text,
    country_code text,
    created_at text,
    credit_total text,
    currency text,
    customer text,
    destination_id text,
    discount_total text,
    exchange_credit_total text,
    exchange_discount_total text,
    exchange_product_total text,
    exchange_tax_total text,
    exchange_total text,
    gift_card text,
    handling_fee text,
    label_rate text,
    label_status text,
    label_updated_at text,
    label_url text,
    latitude text,
    longitude text,
    method_state text,
    method_type text,
    multi_currency text,
    "name" text,
    order_id text,
    order_name text,
    order_number text,
    outcome text,
    package_reference text,
    phone text,
    product_total text,
    provider text,
    provider_order_id text,
    qr_code_url text,
    refund text,
    return_total text,
    rma_id text,
    scannable_id text,
    scheduled_at text,
    "state" text,
    state_address text,
    status_page_url text,
    tax_total text,
    total text,
    tracking_number text,
    updated_at text,
    upsell text,
    zip text,
    PRIMARY KEY (id)
);

CREATE TABLE return_open_closed_expired_exchange (
    exchange_id text,
    return_open_closed_expired_id text,
    discount text,
    out_of_stock text,
    out_of_stock_resolution text,
    price text,
    product_id text,
    sku text,
    tax text,
    title text,
    total text,
    "type" text,
    variant_id text,
    PRIMARY KEY (exchange_id, return_open_closed_expired_id),
    FOREIGN KEY (return_open_closed_expired_id) REFERENCES return_open_closed_expired(id)
);

CREATE TABLE return_open_closed_expired_line_item (
    line_item_id text,
    return_open_closed_expired_id text,
    barcode text,
    discount text,
    exchange_variant text,
    outcome text,
    parent_return_reason text,
    price text,
    product_id text,
    provider_line_item_id text,
    refund text,
    return_comment text,
    return_reason text,
    returned_at text,
    sku text,
    tax text,
    title text,
    variant_id text,
    PRIMARY KEY (line_item_id, return_open_closed_expired_id),
    FOREIGN KEY (return_open_closed_expired_id) REFERENCES return_open_closed_expired(id)
);

CREATE TABLE return_open_closed_expired (
    id text,
    address_1 text,
    address_2 text,
    carrier text,
    city text,
    company text,
    country text,
    country_code text,
    created_at text,
    credit_total text,
    currency text,
    customer text,
    destination_id text,
    discount_total text,
    exchange_credit_total text,
    exchange_discount_total text,
    exchange_product_total text,
    exchange_tax_total text,
    exchange_total text,
    gift_card text,
    handling_fee text,
    label_rate text,
    label_status text,
    label_updated_at text,
    label_url text,
    latitude text,
    longitude text,
    method_state text,
    method_type text,
    multi_currency text,
    "name" text,
    order_id text,
    order_name text,
    order_number text,
    outcome text,
    package_reference text,
    phone text,
    product_total text,
    provider text,
    provider_order_id text,
    qr_code_url text,
    refund text,
    return_total text,
    rma_id text,
    scannable_id text,
    scheduled_at text,
    "state" text,
    state_address text,
    status_page_url text,
    tax_total text,
    total text,
    tracking_number text,
    updated_at text,
    upsell text,
    zip text,
    PRIMARY KEY (id)
);

CREATE TABLE advanced_shipping_notice (
    _fivetran_id text,
    barcode text,
    closed_at text,
    created_at text,
    customer_email text,
    purchase_price text,
    restock_status text,
    return_line_item_id text,
    return_list_id text,
    sku text,
    title text,
    updated_at text,
    PRIMARY KEY (_fivetran_id)
);
