CREATE TABLE order_discount_code (
    customer_id text,
    "index" text,
    order_id text,
    amount text,
    code text,
    "type" text,
    PRIMARY KEY (customer_id, "index", order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE order_shopify_line_item_tag (
    customer_id text,
    "index" text,
    order_id text,
    order_shopify_line_item_id text,
    tags text,
    PRIMARY KEY (customer_id, "index", order_id, order_shopify_line_item_id),
    FOREIGN KEY (order_id) REFERENCES order_shopify_line_item(order_id),
    FOREIGN KEY (order_shopify_line_item_id) REFERENCES order_shopify_line_item(id)
);

CREATE TABLE order_shopify_line_item_property (
    customer_id text,
    "index" text,
    order_id text,
    order_shopify_line_item_id text,
    "name" text,
    "value" text,
    PRIMARY KEY (customer_id, "index", order_id, order_shopify_line_item_id),
    FOREIGN KEY (order_id) REFERENCES order_shopify_line_item(order_id),
    FOREIGN KEY (order_shopify_line_item_id) REFERENCES order_shopify_line_item(id)
);

CREATE TABLE order_shopify_line_item (
    customer_id text,
    id text,
    order_id text,
    admin_graphql_api_id text,
    current_quantity text,
    final_line_price text,
    final_price text,
    fulfillment_service text,
    line_item_featured_image_alt text,
    line_item_featured_image_id text,
    line_item_featured_image_src text,
    line_item_image_alt text,
    line_item_image_id text,
    line_item_image_src text,
    line_item_product_description text,
    line_item_product_id text,
    line_item_product_title text,
    line_item_product_type text,
    line_item_product_url text,
    line_item_product_vendor text,
    line_item_variant_barcode text,
    line_item_variant_compare_at_price text,
    line_item_variant_id text,
    line_item_variant_image_alt text,
    line_item_variant_image_id text,
    line_item_variant_image_src text,
    line_item_variant_inventory_policy text,
    line_item_variant_inventory_quantity text,
    line_item_variant_option_1 text,
    line_item_variant_option_2 text,
    line_item_variant_option_3 text,
    line_item_variant_price text,
    line_item_variant_require_shipping text,
    line_item_variant_sku text,
    line_item_variant_taxable text,
    line_item_variant_title text,
    line_item_variant_weight text,
    line_item_variant_weight_unit text,
    line_level_total_discount text,
    original_line_price text,
    original_price text,
    quantity text,
    require_shipping text,
    sku text,
    taxable text,
    title text,
    vendor text,
    PRIMARY KEY (customer_id, id, order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE order_line_item (
    customer_id text,
    "index" text,
    order_id text,
    final_line_price_amount text,
    final_line_price_currency text,
    fulfillable_quantity text,
    original_line_price_amount text,
    original_line_price_currency text,
    product_handle text,
    total_discount_amount text,
    total_discount_currency text,
    PRIMARY KEY (customer_id, "index", order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE order_shipment_scan_event (
    customer_id text,
    "index" text,
    order_id text,
    order_shipment_id text,
    carrier_code text,
    description text,
    location_city text,
    location_country text,
    location_postal_code text,
    location_state text,
    message text,
    scanned_at text,
    "source" text,
    "status" text,
    status_detail text,
    PRIMARY KEY (customer_id, "index", order_id, order_shipment_id),
    FOREIGN KEY (order_id) REFERENCES order_shipment(order_id),
    FOREIGN KEY (order_shipment_id) REFERENCES order_shipment(id)
);

CREATE TABLE order_shipment (
    customer_id text,
    id text,
    order_id text,
    alternative_carrier_identifier text,
    carrier text,
    carrier_name text,
    carrier_service text,
    carrier_url text,
    container_type text,
    delivered_at text,
    destination_city text,
    destination_country text,
    destination_postal_code text,
    destination_state text,
    estimated_delivered_at text,
    estimated_local_delivered_at text,
    estimated_local_delivered_on text,
    guaranteed_delivered_at text,
    initial_delivery_attempted_at text,
    is_return text,
    origin_city text,
    origin_country text,
    origin_postal_code text,
    origin_state text,
    original_estimated_delivered_at text,
    signed_by text,
    "status" text,
    tracking_code text,
    weight text,
    PRIMARY KEY (customer_id, id, order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE orders (
    id text,
    customer_id text,
    shopify_order_id text,
    alternate_id text,
    billing_address_address_1 text,
    billing_address_address_2 text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country text,
    billing_address_country_code text,
    billing_address_first_name text,
    billing_address_id text,
    billing_address_last_name text,
    billing_address_name text,
    billing_address_phone text,
    billing_address_province text,
    billing_address_province_code text,
    billing_address_zip text,
    cancelled_at text,
    created_at text,
    default_address_address_1 text,
    default_address_address_2 text,
    default_address_city text,
    default_address_company text,
    default_address_country text,
    default_address_country_code text,
    default_address_first_name text,
    default_address_id text,
    default_address_last_name text,
    default_address_name text,
    default_address_phone text,
    default_address_province text,
    default_address_province_code text,
    default_address_zip text,
    delivered_at text,
    email text,
    fulfilled_at text,
    "name" text,
    number text,
    placed_at text,
    presentment_current_subtotal_price_amount text,
    presentment_current_subtotal_price_currency text,
    presentment_current_total_discount_amount text,
    presentment_current_total_discount_currency text,
    presentment_current_total_price_amount text,
    presentment_current_total_price_currency text,
    presentment_current_total_tax_amount text,
    presentment_current_total_tax_currency text,
    presentment_total_shipping_price_amount text,
    presentment_total_shipping_price_currency text,
    require_shipping text,
    "return" jsonb,
    return_url text,
    shipping_address_address_1 text,
    shipping_address_address_2 text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country text,
    shipping_address_country_code text,
    shipping_address_first_name text,
    shipping_address_id text,
    shipping_address_last_name text,
    shipping_address_name text,
    shipping_address_phone text,
    shipping_address_province text,
    shipping_address_province_code text,
    shipping_address_updated_at text,
    shipping_address_zip text,
    shopify_order_cancel_reason text,
    shopify_order_cancelled_at text,
    shopify_order_created_at text,
    shopify_order_current_subtotal_price text,
    shopify_order_current_total_discount text,
    shopify_order_current_total_price text,
    shopify_order_current_total_tax text,
    shopify_order_customer_accept_marketing text,
    shopify_order_customer_address jsonb,
    shopify_order_customer_email text,
    shopify_order_customer_first_name text,
    shopify_order_customer_id text,
    shopify_order_customer_last_name text,
    shopify_order_customer_order_count text,
    shopify_order_customer_phone text,
    shopify_order_customer_tax_exempt text,
    shopify_order_customer_total_spent text,
    shopify_order_email text,
    shopify_order_financial_status text,
    shopify_order_fulfillment jsonb,
    shopify_order_fulfillment_status text,
    shopify_order_item_count text,
    shopify_order_line_item_count text,
    shopify_order_name text,
    shopify_order_note text,
    shopify_order_order_number text,
    shopify_order_order_status_url text,
    shopify_order_phone text,
    shopify_order_presentment_currency text,
    shopify_order_shipment_count text,
    shopify_order_shipping_price text,
    shopify_order_subtotal_price text,
    shopify_order_tax_price text,
    shopify_order_total_discount text,
    shopify_order_total_line_items_price text,
    shopify_order_total_net_amount text,
    shopify_order_total_price text,
    shopify_order_total_refunded_amount text,
    shopify_order_total_shipping_price text,
    updated_at text,
    url text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (shopify_order_id) REFERENCES orders(alternate_id)
);

CREATE TABLE customer (
    id text,
    created_at text,
    email text,
    first_name text,
    last_name text,
    phone_number text,
    updated_at text,
    PRIMARY KEY (id)
);
