CREATE TABLE group_address (
    encoded_key text,
    groups_encoded_key text,
    city text,
    country text,
    index_in_list text,
    latitude text,
    line_1 text,
    line_2 text,
    longitude text,
    parent_key text,
    postcode text,
    region text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (groups_encoded_key) REFERENCES groups(encoded_key)
);

CREATE TABLE group_members_role (
    encoded_key text,
    group_member_index text,
    groups_encoded_key text,
    group_role_name_key text,
    role_name text,
    role_name_id text,
    PRIMARY KEY (encoded_key, group_member_index, groups_encoded_key),
    FOREIGN KEY (group_member_index) REFERENCES group_member("index"),
    FOREIGN KEY (groups_encoded_key) REFERENCES group_member(groups_encoded_key)
);

CREATE TABLE group_member (
    "index" text,
    client_key text,
    groups_encoded_key text,
    PRIMARY KEY ("index"),
    FOREIGN KEY (client_key) REFERENCES client(encoded_key),
    FOREIGN KEY (groups_encoded_key) REFERENCES groups(encoded_key)
);

CREATE TABLE groups (
    encoded_key text,
    assigned_branch_key text,
    assigned_centre_key text,
    assigned_user_key text,
    creation_date text,
    email_address text,
    group_name text,
    group_role_key text,
    home_phone text,
    id text,
    last_modified_date timestamp,
    legal_form_type text,
    loan_cycle text,
    migration_event_key text,
    mobile_phone text,
    note text,
    preferred_language text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (assigned_branch_key) REFERENCES branch(encoded_key),
    FOREIGN KEY (assigned_centre_key) REFERENCES centre(encoded_key),
    FOREIGN KEY (assigned_user_key) REFERENCES users(encoded_key)
);

CREATE TABLE custom_field_usage (
    "index" text,
    custom_field_encoded_key text,
    defaults text,
    object_key text,
    required text,
    PRIMARY KEY ("index", custom_field_encoded_key),
    FOREIGN KEY (custom_field_encoded_key) REFERENCES custom_field(encoded_key)
);

CREATE TABLE custom_field_available_option (
    "index" text,
    custom_field_encoded_key text,
    custom_field_selection_option_index text,
    score text,
    selection_key text,
    "value" text,
    PRIMARY KEY ("index", custom_field_encoded_key, custom_field_selection_option_index),
    FOREIGN KEY (custom_field_encoded_key) REFERENCES custom_field_selection_option(custom_field_encoded_key),
    FOREIGN KEY (custom_field_selection_option_index) REFERENCES custom_field_selection_option("index")
);

CREATE TABLE custom_field_selection_option (
    "index" text,
    custom_field_encoded_key text,
    for_selection_key text,
    for_value text,
    PRIMARY KEY ("index", custom_field_encoded_key),
    FOREIGN KEY (custom_field_encoded_key) REFERENCES custom_field(encoded_key)
);

CREATE TABLE custom_field (
    encoded_key text,
    custom_field_set_custom_field_encoded_key text,
    available_for text,
    creation_date text,
    dependent_field_key text,
    display_settings_built_in_id text,
    display_settings_description text,
    display_settings_display_name text,
    display_settings_field_size text,
    display_settings_name text,
    display_settings_position text,
    edit_rights_all_user text,
    edit_rights_role jsonb,
    id text,
    last_modified_date text,
    "state" text,
    "type" text,
    uniques text,
    validation_pattern text,
    view_rights_all_user text,
    view_rights_role jsonb,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (custom_field_set_custom_field_encoded_key) REFERENCES custom_field_set_custom_field(encoded_key)
);

CREATE TABLE deposit_transaction_fee (
    "index" text,
    deposit_transaction_encoded_key text,
    amount text,
    "name" text,
    predefined_fee_key text,
    tax_amount text,
    "trigger" text,
    PRIMARY KEY ("index", deposit_transaction_encoded_key),
    FOREIGN KEY (deposit_transaction_encoded_key) REFERENCES deposit_transaction(encoded_key)
);

CREATE TABLE deposit_transaction (
    encoded_key text,
    deposit_account_encoded_key text,
    account_balances_total_balance text,
    adjustment_transaction_key text,
    affected_amounts_fees_amount text,
    affected_amounts_fraction_amount text,
    affected_amounts_funds_amount text,
    affected_amounts_interest_amount text,
    affected_amounts_overdraft_amount text,
    affected_amounts_overdraft_fees_amount text,
    affected_amounts_overdraft_interest_amount text,
    affected_amounts_technical_overdraft_amount text,
    affected_amounts_technical_overdraft_interest_amount text,
    amount text,
    block_id text,
    booking_date text,
    branch_key text,
    card_acceptor_city text,
    card_acceptor_country text,
    card_acceptor_mcc text,
    card_acceptor_name text,
    card_acceptor_state text,
    card_acceptor_street text,
    card_acceptor_zip text,
    card_transaction_advice text,
    card_transaction_amount text,
    card_transaction_card_token text,
    card_transaction_currency_code text,
    card_transaction_encoded_key text,
    card_transaction_external_authorization_reference_id text,
    card_transaction_external_reference_id text,
    card_transaction_user_transaction_time text,
    centre_key text,
    creation_date text,
    currency_code text,
    external_id text,
    hold_external_reference_id text,
    id text,
    interest_accrued_amounts_interest_accrued text,
    interest_accrued_amounts_negative_interest_accrued text,
    interest_accrued_amounts_overdraft_interest_accrued text,
    interest_accrued_amounts_technical_overdraft_interest_accrued text,
    linked_deposit_transaction_key text,
    linked_loan_transaction_key text,
    migration_event_key text,
    "name" text,
    note text,
    original_transaction_key text,
    parent_account_key text,
    payment_details_creditor_account_currency text,
    payment_details_creditor_account_identification_iban text,
    payment_details_creditor_account_identification_other_identification text,
    payment_details_creditor_account_identification_other_scheme text,
    payment_details_creditor_agent_financial_institution_identification_bic text,
    payment_details_creditor_name text,
    payment_details_debtor_account_currency text,
    payment_details_debtor_account_identification_iban text,
    payment_details_debtor_account_identification_other_identification text,
    payment_details_debtor_account_identification_other_scheme text,
    payment_details_debtor_agent_financial_institution_identification_bic text,
    payment_details_debtor_name text,
    payment_details_payment_identification_end_to_end_identification text,
    payment_details_payment_identification_instruction_identification text,
    payment_details_payment_identification_transaction_identification text,
    payment_details_payment_type_information_service_level_code text,
    payment_details_remittance_information_structured_creditor_reference_information_reference text,
    payment_details_remittance_information_structured_creditor_reference_information_reference_issuer text,
    payment_details_remittance_information_structured_creditor_reference_information_reference_type text,
    payment_details_remittance_information_unstructured text,
    payment_order_id text,
    taxes_tax_rate text,
    terms_interest_settings_index_interest_rate text,
    terms_interest_settings_interest_rate text,
    terms_overdraft_interest_settings_index_interest_rate text,
    terms_overdraft_interest_settings_interest_rate text,
    terms_overdraft_settings_overdraft_limit text,
    till_key text,
    transaction_channel_id text,
    transaction_channel_key text,
    "type" text,
    user_key text,
    value_date text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_account_encoded_key) REFERENCES deposit_account(encoded_key)
);

CREATE TABLE centre_address (
    encoded_key text,
    centre_encoded_key text,
    city text,
    country text,
    index_in_list text,
    latitude text,
    line_1 text,
    line_2 text,
    longitude text,
    parent_key text,
    postcode text,
    region text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (centre_encoded_key) REFERENCES centre(encoded_key)
);

CREATE TABLE centre (
    encoded_key text,
    assigned_branch_key text,
    creation_date text,
    id text,
    last_modified_date timestamp,
    meeting_day text,
    "name" text,
    note text,
    "state" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (assigned_branch_key) REFERENCES branch(encoded_key)
);

CREATE TABLE task (
    encoded_key text,
    assigned_user_key text,
    created_by_full_name text,
    created_by_user_key text,
    creation_date text,
    description text,
    due_date text,
    id text,
    last_modified_date text,
    "status" text,
    task_link_key text,
    task_link_type text,
    template_key text,
    title text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (assigned_user_key) REFERENCES users(encoded_key)
);

CREATE TABLE deposit_account_authorization_hold (
    encoded_key text,
    deposit_account_encoded_key text,
    account_id text,
    account_key text,
    advice text,
    amount text,
    available_balance text,
    balance_currency_code text,
    card_token text,
    card_type text,
    creation_date text,
    credit_debit_indicator text,
    credit_limit text,
    currency_code text,
    custom_expiration_period text,
    exchange_rate text,
    external_reference_id text,
    original_amount text,
    original_currency text,
    reference_date_for_expiration text,
    "source" text,
    "status" text,
    total_balance text,
    user_transaction_time text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_account_encoded_key) REFERENCES deposit_account(encoded_key)
);

CREATE TABLE loan_account_authorization_hold (
    encoded_key text,
    loan_account_encoded_key text,
    account_key text,
    advice text,
    amount text,
    balances_account_id text,
    balances_available_balance text,
    balances_card_type text,
    balances_credit_limit text,
    balances_currency_code text,
    balances_total_balance text,
    creation_date text,
    credit_debit_indicator text,
    currency_code text,
    custom_expiration_period text,
    exchange_rate text,
    external_reference_id text,
    original_currency text,
    reference_date_for_expiration text,
    "source" text,
    "status" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_card (
    _fivetran_id text,
    loan_account_encoded_key text,
    reference_token text,
    PRIMARY KEY (_fivetran_id, loan_account_encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE deposit_account_card (
    _fivetran_id text,
    deposit_account_encoded_key text,
    reference_token text,
    PRIMARY KEY (_fivetran_id, deposit_account_encoded_key),
    FOREIGN KEY (deposit_account_encoded_key) REFERENCES deposit_account(encoded_key)
);

CREATE TABLE loan_product_interest_rate_tier (
    encoded_key text,
    loan_product_index_rate_settings_encoded_key text,
    loan_product_encoded_key text,
    ending_balance text,
    interest_rate text,
    PRIMARY KEY (encoded_key, loan_product_index_rate_settings_encoded_key, loan_product_encoded_key),
    FOREIGN KEY (loan_product_encoded_key) REFERENCES loan_product(encoded_key)
);

CREATE TABLE loan_product_interest_rate_setting (
    encoded_key text,
    loan_product_encoded_key text,
    index_source_key text,
    interest_rate_ceiling_value text,
    interest_rate_default_value text,
    interest_rate_floor_value text,
    interest_rate_max_value text,
    interest_rate_min_value text,
    interest_rate_review_count text,
    interest_rate_review_unit text,
    interest_rate_source text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_product_encoded_key) REFERENCES loan_product(encoded_key)
);

CREATE TABLE loan_product_fee_settings_accounting_rule (
    encoded_key text,
    loan_product_encoded_key text,
    loan_product_fee_encoded_key text,
    financial_resource text,
    gl_account_key text,
    transaction_channel_key text,
    PRIMARY KEY (encoded_key, loan_product_encoded_key, loan_product_fee_encoded_key),
    FOREIGN KEY (loan_product_encoded_key) REFERENCES loan_product_fee(loan_product_encoded_key),
    FOREIGN KEY (loan_product_fee_encoded_key) REFERENCES loan_product_fee(encoded_key)
);

CREATE TABLE loan_product_fee (
    encoded_key text,
    loan_product_encoded_key text,
    amortization_settings_amortization_profile text,
    amortization_settings_encoded_key text,
    amortization_settings_fee_amortization_upon_reschedule_refinance_option text,
    amortization_settings_frequency text,
    amortization_settings_interval_count text,
    amortization_settings_interval_type text,
    amortization_settings_period_count text,
    amortization_settings_period_unit text,
    amount text,
    amount_calculation_function_name text,
    amount_calculation_method text,
    apply_date_method text,
    creation_date text,
    fee_application text,
    id text,
    last_modified_date text,
    "name" text,
    percentage_amount text,
    "state" text,
    tax_settings_taxable_calculation_method text,
    "trigger" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_product_encoded_key) REFERENCES loan_product(encoded_key)
);

CREATE TABLE loan_product_accounting_settings_rule (
    encoded_key text,
    loan_product_encoded_key text,
    financial_resource text,
    gl_account_key text,
    transaction_channel_key text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_product_encoded_key) REFERENCES loan_product(encoded_key)
);

CREATE TABLE loan_product_template (
    encoded_key text,
    loan_product_encoded_key text,
    creation_date text,
    last_modified_date text,
    "name" text,
    "type" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_product_encoded_key) REFERENCES loan_product(encoded_key)
);

CREATE TABLE loan_product (
    encoded_key text,
    account_link_settings_enabled text,
    account_link_settings_linkable_deposit_product_key text,
    account_link_settings_linked_account_option jsonb,
    account_link_settings_settlement_method text,
    accounting_settings_interest_accrual_calculation text,
    accounting_settings_interest_accrued_method text,
    accounting_settings_method text,
    accrue_late_interest text,
    adjust_interest_for_first_installment text,
    allow_custom_repayment_allocation text,
    arrears_settings_date_calculation_method text,
    arrears_settings_encoded_key text,
    arrears_settings_monthly_tolerance_day text,
    arrears_settings_non_working_days_method text,
    arrears_settings_tolerance_calculation_method text,
    arrears_settings_tolerance_floor_amount text,
    arrears_settings_tolerance_percentage_of_outstanding_principal_default_value text,
    arrears_settings_tolerance_percentage_of_outstanding_principal_max_value text,
    arrears_settings_tolerance_percentage_of_outstanding_principal_min_value text,
    arrears_settings_tolerance_period_default_value text,
    arrears_settings_tolerance_period_encoded_key text,
    arrears_settings_tolerance_period_max_value text,
    arrears_settings_tolerance_period_min_value text,
    availability_settings_available_for jsonb,
    billing_cycle_enabledschedule_settings_ text,
    billing_cycle_start_dayschedule_settings_ jsonb,
    branch_settings_available_product_branch jsonb,
    branch_settings_for_all_branch text,
    category text,
    compounding_frequency text,
    creation_date text,
    credit_arrangement_requirement text,
    currency_code text,
    days_in_year text,
    default_repayment_period_countschedule_settings_ text,
    due_dates_methodschedule_settings_ text,
    fee_settings_allow_arbitrary_fee text,
    first_repayment_due_date_offset_default_valueschedule_settings_ text,
    first_repayment_due_date_offset_encoded_keyschedule_settings_ text,
    first_repayment_due_date_offset_max_valueschedule_settings_ text,
    first_repayment_due_date_offset_min_valueschedule_settings_ text,
    fixed_days_of_monthschedule_settings_ jsonb,
    funding_settings_enabled text,
    funding_settings_funder_interest_commission_allocation_type text,
    funding_settings_funder_interest_commission_default_value text,
    funding_settings_funder_interest_commission_encoded_key text,
    funding_settings_funder_interest_commission_max_value text,
    funding_settings_funder_interest_commission_min_value text,
    funding_settings_lock_funds_at_approval text,
    funding_settings_organization_interest_commission_default_value text,
    funding_settings_organization_interest_commission_encoded_key text,
    funding_settings_organization_interest_commission_max_value text,
    funding_settings_organization_interest_commission_min_value text,
    funding_settings_required_fund text,
    grace_period_default_value text,
    grace_period_encoded_key text,
    grace_period_max_value text,
    grace_period_min_value text,
    grace_period_type text,
    id text,
    index_rate_settings_accrue_interest_after_maturity text,
    index_rate_settings_allow_negative_interest_rate text,
    index_rate_settings_encoded_key text,
    index_rate_settings_index_source_key text,
    index_rate_settings_interest_charge_frequency text,
    index_rate_settings_interest_charge_frequency_count text,
    index_rate_settings_interest_rate_ceiling_value text,
    index_rate_settings_interest_rate_floor_value text,
    index_rate_settings_interest_rate_review_count text,
    index_rate_settings_interest_rate_review_unit text,
    index_rate_settings_interest_rate_source text,
    index_rate_settings_interest_rate_term text,
    interest_accrual_sinceschedule_settings_ text,
    interest_application_method text,
    interest_balance_calculation_method text,
    interest_calculation_method text,
    interest_rate_default_value text,
    interest_rate_max_value text,
    interest_rate_min_value text,
    interest_rate_source text,
    interest_type text,
    internal_controls_dormancy_period_day text,
    internal_controls_four_eyes_principle_active_for_loan_approval text,
    internal_controls_lock_settings_capping_constraint_type text,
    internal_controls_lock_settings_capping_method text,
    internal_controls_lock_settings_capping_percentage text,
    internal_controls_lock_settings_lock_period_day text,
    last_modified_date timestamp,
    loan_amount_default_value text,
    loan_amount_encoded_key text,
    loan_amount_max_value text,
    loan_amount_min_value text,
    "name" text,
    new_account_settings_account_initial_state text,
    new_account_settings_id_generator_type text,
    new_account_settings_id_pattern text,
    note text,
    num_installment_default_valueschedule_settings_ text,
    num_installment_encoded_keyschedule_settings_ text,
    num_installment_max_valueschedule_settings_ text,
    num_installment_min_valueschedule_settings_ text,
    number_of_previewed_instalmentschedule_settings_ text,
    offset_settings_allow_offset text,
    payment_settings_amortization_method text,
    payment_settings_late_payments_recalculation_method text,
    payment_settings_payment_method text,
    payment_settings_repayment_allocation_order jsonb,
    penalty_settings_loan_penalty_calculation_method text,
    penalty_settings_loan_penalty_grace_period text,
    penalty_settings_penalty_rate_default_value text,
    penalty_settings_penalty_rate_encoded_key text,
    penalty_settings_penalty_rate_max_value text,
    penalty_settings_penalty_rate_min_value text,
    prepayment_settings_apply_interest_on_prepayment_method text,
    prepayment_settings_elements_recalculation_method text,
    prepayment_settings_future_payments_acceptance text,
    prepayment_settings_prepayment_acceptance text,
    prepayment_settings_prepayment_recalculation_method text,
    prepayment_settings_principal_paid_installment_status text,
    preview_schedule_enabledschedule_settings_ text,
    principal_payment_settings_amount_default_value text,
    principal_payment_settings_amount_encoded_key text,
    principal_payment_settings_amount_max_value text,
    principal_payment_settings_amount_min_value text,
    principal_payment_settings_default_principal_repayment_interval text,
    principal_payment_settings_encoded_key text,
    principal_payment_settings_include_fees_in_floor_amount text,
    principal_payment_settings_include_interest_in_floor_amount text,
    principal_payment_settings_percentage_default_value text,
    principal_payment_settings_percentage_encoded_key text,
    principal_payment_settings_percentage_max_value text,
    principal_payment_settings_percentage_min_value text,
    principal_payment_settings_principal_ceiling_value text,
    principal_payment_settings_principal_floor_value text,
    principal_payment_settings_principal_payment_method text,
    principal_payment_settings_total_due_amount_floor text,
    principal_payment_settings_total_due_payment text,
    redraw_settings_allow_redraw text,
    repayment_currency_roundingschedule_settings_ text,
    repayment_elements_rounding_methodschedule_settings_ text,
    repayment_methodschedule_settings_ text,
    repayment_period_unitschedule_settings_ text,
    repayment_rescheduling_methodschedule_settings_ text,
    repayment_schedule_edit_optionschedule_settings_ jsonb,
    repayment_schedule_methodschedule_settings_ text,
    rounding_repayment_schedule_methodschedule_settings_ text,
    schedule_interest_days_count_method text,
    security_settings_is_collateral_enabled text,
    security_settings_is_guarantors_enabled text,
    security_settings_required_guaranty text,
    short_month_handling_methodschedule_settings_ text,
    "state" text,
    tax_settings_tax_calculation_method text,
    tax_settings_tax_source_key text,
    tax_settings_taxes_on_fees_enabled text,
    tax_settings_taxes_on_interest_enabled text,
    tax_settings_taxes_on_penalty_enabled text,
    tranche_settings_max_number_of_tranche text,
    "type" text,
    PRIMARY KEY (encoded_key)
);

CREATE TABLE user_access_permission (
    "index" text,
    users_encoded_key text,
    permission text,
    PRIMARY KEY ("index", users_encoded_key),
    FOREIGN KEY (users_encoded_key) REFERENCES users(encoded_key)
);

CREATE TABLE user_managed_branch (
    branch_key text,
    users_encoded_key text,
    PRIMARY KEY (branch_key, users_encoded_key),
    FOREIGN KEY (users_encoded_key) REFERENCES users(encoded_key)
);

CREATE TABLE users (
    encoded_key text,
    assigned_branch_key text,
    role_id text,
    administrator_access text,
    api_access text,
    can_manage_all_branch text,
    can_manage_entities_assigned_to_other_officer text,
    creation_date text,
    credit_officer_access text,
    delivery_access text,
    email text,
    first_name text,
    home_phone text,
    id text,
    languages text,
    last_logged_in_date text,
    last_modified_date text,
    last_name text,
    mambu_access text,
    mobile_phone text,
    note text,
    role_encoded_key text,
    support_access text,
    teller_access text,
    title text,
    transaction_limits_property_1 text,
    transaction_limits_property_2 text,
    two_factor_authentication text,
    user_name text,
    user_state text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (assigned_branch_key) REFERENCES branch(encoded_key),
    FOREIGN KEY (role_id) REFERENCES user_role(id)
);

CREATE TABLE transaction_channel_usage_right (
    "index" text,
    transaction_channel_encoded_key text,
    usage_right text,
    PRIMARY KEY ("index", transaction_channel_encoded_key),
    FOREIGN KEY (transaction_channel_encoded_key) REFERENCES transaction_channel(encoded_key)
);

CREATE TABLE transaction_channel_deposit_constraint (
    _fivetran_id text,
    transaction_channel_encoded_key text,
    criteria text,
    operator text,
    second_value text,
    "value" text,
    values jsonb,
    PRIMARY KEY (_fivetran_id, transaction_channel_encoded_key),
    FOREIGN KEY (transaction_channel_encoded_key) REFERENCES transaction_channel(encoded_key)
);

CREATE TABLE transaction_channel_loan_constraint (
    _fivetran_id text,
    transaction_channel_encoded_key text,
    criteria text,
    operator text,
    second_value text,
    "value" text,
    values jsonb,
    PRIMARY KEY (_fivetran_id, transaction_channel_encoded_key),
    FOREIGN KEY (transaction_channel_encoded_key) REFERENCES transaction_channel(encoded_key)
);

CREATE TABLE transaction_channel (
    encoded_key text,
    available_for_all text,
    deposit_constraints_match_filters_option text,
    deposit_constraints_usage text,
    gl_account text,
    id text,
    is_default text,
    loan_constraints_match_filters_option text,
    loan_constraints_usage text,
    "name" text,
    "state" text,
    PRIMARY KEY (encoded_key)
);

CREATE TABLE journal_entry (
    encoded_key text,
    assigned_branch_key text,
    user_key text,
    account_key text,
    accounting_rate text,
    accounting_rate_encoded_key text,
    accounting_rate_end_date text,
    accounting_rate_from_currency_code text,
    accounting_rate_start_date text,
    accounting_rate_to_currency_code text,
    amount text,
    booking_date text,
    creation_date text,
    entry_id text,
    foreign_amount text,
    foreign_currency_code text,
    gl_account_activated text,
    gl_account_allow_manual_journal_entry text,
    gl_account_balance text,
    gl_account_code text,
    gl_account_creation_date text,
    gl_account_currency_code text,
    gl_account_description text,
    gl_account_encoded_key text,
    gl_account_last_modified_date text,
    gl_account_migration_event_key text,
    gl_account_name text,
    gl_account_strip_trailing_zero text,
    gl_account_type text,
    gl_account_usage text,
    note text,
    product_key text,
    product_type text,
    reversal_entry_key text,
    transaction_id text,
    "type" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (assigned_branch_key) REFERENCES branch(encoded_key),
    FOREIGN KEY (user_key) REFERENCES users(encoded_key)
);

CREATE TABLE loan_account_asset (
    encoded_key text,
    deposit_account_key text,
    loan_account_encoded_key text,
    amount text,
    asset_name text,
    currency_code text,
    guarantor_key text,
    guarantor_type text,
    original_amount text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_account_key) REFERENCES deposit_account(encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_disbursement_fee (
    disbursement_encoded_key text,
    encoded_key text,
    loan_account_encoded_key text,
    amount text,
    percentage text,
    pre_defined_fee_encoded_key text,
    PRIMARY KEY (disbursement_encoded_key, encoded_key, loan_account_encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_funding_source (
    encoded_key text,
    loan_account_encoded_key text,
    amount text,
    asset_name text,
    deposit_account_key text,
    guarantor_key text,
    guarantor_type text,
    id text,
    interest_commission text,
    share_percentage text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_guarantor (
    encoded_key text,
    deposit_account_key text,
    loan_account_encoded_key text,
    amount text,
    asset_name text,
    guarantor_key text,
    guarantor_type text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_account_key) REFERENCES deposit_account(encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_locked_operation (
    "index" text,
    loan_account_encoded_key text,
    locked_operation text,
    PRIMARY KEY ("index", loan_account_encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_planned_installment_fee (
    encoded_key text,
    installment_key text,
    loan_account_encoded_key text,
    amount text,
    apply_on_date text,
    installment_number text,
    pre_defined_fee_key text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (installment_key) REFERENCES loan_account_schedule(encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_payment_plan (
    encoded_key text,
    loan_account_encoded_key text,
    amount text,
    to_installment text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account_tranche_fee (
    encoded_key text,
    loan_account_encoded_key text,
    loan_account_tranche_encoded_key text,
    amount text,
    percentage text,
    pre_defined_fee_encoded_key text,
    PRIMARY KEY (encoded_key, loan_account_encoded_key, loan_account_tranche_encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account_tranche(loan_account_encoded_key),
    FOREIGN KEY (loan_account_tranche_encoded_key) REFERENCES loan_account_tranche(encoded_key)
);

CREATE TABLE loan_account_tranche (
    encoded_key text,
    loan_account_encoded_key text,
    amount text,
    disbursement_details_disbursement_transaction_key text,
    disbursement_details_expected_disbursement_date text,
    tranche_number text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_account_encoded_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_account (
    encoded_key text,
    assigned_branch_key text,
    assigned_centre_key text,
    assigned_user_key text,
    product_type_key text,
    account_holder_key text,
    account_holder_type text,
    account_state text,
    account_sub_state text,
    accrue_interest_after_maturity text,
    accrued_interest text,
    accrued_penalty text,
    activation_transaction_key text,
    allow_offset text,
    approved_date text,
    arrears_tolerance_period text,
    closed_date text,
    creation_date text,
    credit_arrangement_key text,
    days_in_arrear text,
    days_late text,
    disbursement_date text,
    disbursement_encoded_key text,
    disbursement_expected_date text,
    disbursement_first_repayment_date text,
    fees_balance text,
    fees_due_balance text,
    fees_paid_balance text,
    future_payments_acceptance text,
    has_custom_schedule text,
    hold_balance text,
    id text,
    interest_accrued_in_billing_cycle text,
    interest_balance text,
    interest_charge_frequency text,
    interest_commission text,
    interest_due_balance text,
    interest_from_arrears_accrued text,
    interest_from_arrears_balance text,
    interest_from_arrears_due_balance text,
    interest_from_arrears_paid_balance text,
    interest_paid_balance text,
    interest_rate_review_count text,
    interest_rate_review_unit text,
    interest_rate_source text,
    interest_spread text,
    last_account_appraisal_date text,
    last_interest_applied_date text,
    last_interest_review_date text,
    last_locked_date text,
    last_modified_date timestamp,
    last_set_to_arrears_date text,
    last_tax_rate_review_date text,
    late_payments_recalculation_method text,
    loan_amount text,
    loan_name text,
    locked_account_total_due_type text,
    migration_event_key text,
    modify_interest_for_first_installment text,
    note text,
    original_account_key text,
    payment_holidays_accrued_interest text,
    payment_method text,
    penalty_balance text,
    penalty_due_balance text,
    penalty_paid_balance text,
    periodic_payment text,
    principal_balance text,
    principal_due_balance text,
    principal_paid_balance text,
    redraw_balance text,
    redraw_restrict_next_due_withdrawal text,
    repayment_installments text,
    rescheduled_account_key text,
    settlement_account_key text,
    tax_rate text,
    termination_date text,
    transaction_channel_id text,
    transaction_channel_key text,
    transaction_encoded_key text,
    transaction_internal_transfer text,
    transaction_target_deposit_account_key text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (assigned_branch_key) REFERENCES branch(encoded_key),
    FOREIGN KEY (assigned_centre_key) REFERENCES centre(encoded_key),
    FOREIGN KEY (assigned_user_key) REFERENCES users(encoded_key),
    FOREIGN KEY (product_type_key) REFERENCES loan_product(encoded_key)
);

CREATE TABLE deposit_account_over_draft_interest_rate_tier (
    encoded_key text,
    deposit_account_encoded_key text,
    ending_day text,
    PRIMARY KEY (encoded_key, deposit_account_encoded_key),
    FOREIGN KEY (deposit_account_encoded_key) REFERENCES deposit_account(encoded_key)
);

CREATE TABLE deposit_account (
    encoded_key text,
    account_holder_key text,
    assigned_branch_key text,
    assigned_centre_key text,
    assigned_user_key text,
    product_type_key text,
    account_holder_type text,
    account_state text,
    account_type text,
    activation_date text,
    allow_over_draft text,
    approved_date text,
    available_balance text,
    blocked_balance text,
    closed_date text,
    creation_date text,
    credit_arrangement_key text,
    fees_due text,
    forward_available_balance text,
    hold_balance text,
    id text,
    interest_rate_settings_encoded_key text,
    interest_spread text,
    internal_controls_max_deposit_balance text,
    internal_controls_target_amount text,
    last_account_appraisal_date text,
    last_interest_calculation_date text,
    last_interest_review_date text,
    last_interest_stored_date text,
    last_modified_date text,
    last_over_draft_interest_review_date text,
    last_set_to_arrears_date text,
    linked_settlement_account_key jsonb,
    locked_balance text,
    locked_date text,
    maturity_date text,
    migration_event_key text,
    "name" text,
    note text,
    over_draft_amount text,
    over_draft_expiry_date text,
    over_draft_interest_due text,
    over_draft_interest_rate_encoded_key text,
    over_draft_interest_spread text,
    over_draft_limit text,
    technical_over_draft_amount text,
    technical_over_draft_interest_due text,
    total_balance text,
    with_holding_tax_source_key text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (account_holder_key) REFERENCES client(encoded_key),
    FOREIGN KEY (assigned_branch_key) REFERENCES branch(encoded_key),
    FOREIGN KEY (assigned_centre_key) REFERENCES centre(encoded_key),
    FOREIGN KEY (assigned_user_key) REFERENCES users(encoded_key),
    FOREIGN KEY (product_type_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product_fee_settings_accounting_rule (
    encoded_key text,
    deposit_product_encoded_key text,
    deposit_product_fee_encoded_key text,
    financial_resource text,
    gl_account_key text,
    PRIMARY KEY (encoded_key, deposit_product_encoded_key, deposit_product_fee_encoded_key),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product_fee(deposit_product_encoded_key),
    FOREIGN KEY (deposit_product_fee_encoded_key) REFERENCES deposit_product_fee(encoded_key)
);

CREATE TABLE deposit_product_fee (
    encoded_key text,
    deposit_product_encoded_key text,
    amount text,
    amount_calculation_function_name text,
    amount_calculation_method text,
    apply_date_method text,
    creation_date text,
    fee_application text,
    id text,
    last_modified_date text,
    "name" text,
    "state" text,
    "trigger" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product_currency (
    "index" text,
    deposit_product_encoded_key text,
    currency_code text,
    PRIMARY KEY ("index", deposit_product_encoded_key),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product_over_draft_interest_rate_settings_tier (
    encoded_key text,
    deposit_product_encoded_key text,
    ending_balance text,
    interest_rate text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product_template (
    encoded_key text,
    deposit_product_encoded_key text,
    creation_date text,
    last_modified_date text,
    "name" text,
    "type" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product_interest_payment_date (
    "index" text,
    deposit_product_encoded_key text,
    "day" text,
    "month" text,
    PRIMARY KEY ("index"),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product_interest_rate_tier (
    encoded_key text,
    deposit_product_encoded_key text,
    ending_balance text,
    ending_day text,
    interest_rate text,
    PRIMARY KEY (encoded_key, deposit_product_encoded_key),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product_accounting_settings_rule (
    encoded_key text,
    deposit_product_encoded_key text,
    financial_resource text,
    gl_account_key text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (deposit_product_encoded_key) REFERENCES deposit_product(encoded_key)
);

CREATE TABLE deposit_product (
    encoded_key text,
    accounting_settings_interest_accrued_method text,
    accounting_settings_method text,
    accrue_interest_rate_settings_after_maturity text,
    allow_negative_interest_rate_settings text,
    allow_technical_over_draft text,
    available_for jsonb,
    available_product_branch jsonb,
    category text,
    creation_date text,
    credit_arrangement_requirement text,
    fee_settings_allow_arbitrary_fee text,
    for_all_branch text,
    id text,
    interest_payment_settings_point text,
    interest_rate_default_value text,
    interest_rate_max_value text,
    interest_rate_min_value text,
    interest_rate_settings_charge_frequency text,
    interest_rate_settings_charge_frequency_count text,
    interest_rate_settings_encoded_key text,
    interest_rate_settings_index_source_key text,
    interest_rate_settings_review_count text,
    interest_rate_settings_review_unit text,
    interest_rate_settings_source text,
    interest_rate_settings_term text,
    interest_settings_calculation_balance text,
    interest_settings_collect_interest_when_locked text,
    interest_settings_days_in_year text,
    interest_settings_gains_provided_end_date text,
    interest_settings_gains_provided_start_date text,
    interest_settings_maximum_balance text,
    interest_settings_paid_into_account text,
    internal_controls_dormancy_period_day text,
    internal_controls_max_withdrawal_amount text,
    internal_controls_opening_balance_default_value text,
    internal_controls_opening_balance_max_value text,
    internal_controls_opening_balance_min_value text,
    internal_controls_recommended_deposit_amount text,
    last_modified_date text,
    maturity_period_default_value text,
    maturity_period_max_value text,
    maturity_period_min_value text,
    maturity_settings_period_unit text,
    "name" text,
    new_account_settings_id_generator_type text,
    new_account_settings_id_pattern text,
    note text,
    offset_settings_allow_offset text,
    over_draft_interest_rate_settings_charge_frequency text,
    over_draft_interest_rate_settings_charge_frequency_count text,
    over_draft_interest_rate_settings_default_value text,
    over_draft_interest_rate_settings_index_source_key text,
    over_draft_interest_rate_settings_max_value text,
    over_draft_interest_rate_settings_min_value text,
    over_draft_interest_rate_settings_review_count text,
    over_draft_interest_rate_settings_review_unit text,
    over_draft_interest_rate_settings_source text,
    over_draft_interest_rate_settings_term text,
    over_draft_interest_settings_days_in_year text,
    over_draft_interest_settings_interest_calculation_balance text,
    "state" text,
    "type" text,
    with_holding_tax_enabled text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key)
);

CREATE TABLE loan_account_schedule_fee_detail (
    encoded_key text,
    loan_account_schedule_encoded_key text,
    amount_reduced text,
    id text,
    "name" text,
    tax_reduced text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_account_schedule_encoded_key) REFERENCES loan_account_schedule(encoded_key)
);

CREATE TABLE loan_account_schedule (
    encoded_key text,
    loan_account_key text,
    due_date text,
    fee_amount_due text,
    fee_amount_expected text,
    fee_amount_paid text,
    fee_tax_due text,
    fee_tax_expected text,
    fee_tax_paid text,
    interest_amount_due text,
    interest_amount_expected text,
    interest_amount_paid text,
    interest_tax_due text,
    interest_tax_expected text,
    interest_tax_paid text,
    is_payment_holiday text,
    last_paid_date text,
    number text,
    penalty_amount_due text,
    penalty_amount_expected text,
    penalty_amount_paid text,
    penalty_tax_due text,
    penalty_tax_expected text,
    penalty_tax_paid text,
    principal_amount_due text,
    principal_amount_expected text,
    principal_amount_paid text,
    repaid_date text,
    "state" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (loan_account_key) REFERENCES loan_account(encoded_key)
);

CREATE TABLE loan_transaction_custom_payment_amount (
    "index" text,
    loan_transaction_encoded_key text,
    amount text,
    custom_payment_amount_type text,
    pre_defined_fee_key text,
    tax_on_amount text,
    PRIMARY KEY ("index", loan_transaction_encoded_key),
    FOREIGN KEY (loan_transaction_encoded_key) REFERENCES loan_transaction(encoded_key)
);

CREATE TABLE loan_transaction_fee (
    "index" text,
    loan_transaction_encoded_key text,
    amount text,
    "name" text,
    pre_defined_fee_key text,
    tax_amount text,
    "trigger" text,
    PRIMARY KEY ("index", loan_transaction_encoded_key),
    FOREIGN KEY (loan_transaction_encoded_key) REFERENCES loan_transaction(encoded_key)
);

CREATE TABLE loan_transaction (
    encoded_key text,
    branch_key text,
    centre_key text,
    installment_encoded_key text,
    loan_account_key text,
    transaction_channel_key text,
    user_key text,
    account_balances_advance_position text,
    account_balances_arrears_position text,
    account_balances_expected_principal_redraw text,
    account_balances_principal_balance text,
    account_balances_redraw_balance text,
    account_balances_total_balance text,
    adjustment_transaction_key text,
    affected_deferred_interest_amount text,
    affected_fees_amount text,
    affected_funders_interest_amount text,
    affected_interest_amount text,
    affected_interest_from_arrears_amount text,
    affected_organization_commission_amount text,
    affected_payment_holidays_interest_amount text,
    affected_penalty_amount text,
    affected_principal_amount text,
    amount text,
    booking_date text,
    card_acceptor_city text,
    card_acceptor_country text,
    card_acceptor_mcc text,
    card_acceptor_name text,
    card_acceptor_state text,
    card_acceptor_street text,
    card_acceptor_zip text,
    card_token text,
    card_transaction_advice text,
    card_transaction_amount text,
    card_transaction_currency_code text,
    card_transaction_encoded_key text,
    card_transaction_external_authorization_reference_id text,
    card_transaction_external_reference_id text,
    creation_date text,
    currency_code text,
    external_id text,
    id text,
    migration_event_key text,
    note text,
    original_amount text,
    original_currency_code text,
    original_transaction_key text,
    parent_loan_transaction_key text,
    pre_payment_recalculation_method text,
    taxes_deferred_tax_on_interest_amount text,
    taxes_tax_on_fees_amount text,
    taxes_tax_on_interest_amount text,
    taxes_tax_on_interest_from_arrears_amount text,
    taxes_tax_on_payment_holidays_interest text,
    taxes_tax_on_penalty_amount text,
    taxes_tax_rate text,
    terms_interest_settings_index_interest_rate text,
    terms_interest_settings_interest_rate text,
    terms_periodic_payment text,
    terms_principal_payment_amount text,
    terms_principal_payment_percentage text,
    till_key text,
    transaction_details_transaction_channel_id text,
    transaction_details_transaction_channel_key text,
    transfer_details_linked_deposit_transaction_key text,
    transfer_details_linked_loan_transaction_key text,
    "type" text,
    user_transaction_time text,
    value_date text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (branch_key) REFERENCES branch(encoded_key),
    FOREIGN KEY (centre_key) REFERENCES centre(encoded_key),
    FOREIGN KEY (installment_encoded_key) REFERENCES loan_account_schedule(encoded_key),
    FOREIGN KEY (loan_account_key) REFERENCES loan_account(encoded_key),
    FOREIGN KEY (transaction_channel_key) REFERENCES transaction_channel(encoded_key),
    FOREIGN KEY (user_key) REFERENCES users(encoded_key)
);

CREATE TABLE custom_field_set_custom_field (
    encoded_key text,
    custom_field_set_encoded_key text,
    id text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (custom_field_set_encoded_key) REFERENCES custom_field_set(encoded_key)
);

CREATE TABLE custom_field_set (
    encoded_key text,
    available_for text,
    built_in text,
    creation_date text,
    description text,
    display_name text,
    field_set_type text,
    id text,
    "position" text,
    PRIMARY KEY (encoded_key)
);

CREATE TABLE client_role (
    encoded_key text,
    client_encoded_key text,
    can_guarantee text,
    can_open_account text,
    client_type text,
    creation_date text,
    description text,
    id text,
    id_pattern text,
    "name" text,
    require_id text,
    use_default_address text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (client_encoded_key) REFERENCES client(encoded_key)
);

CREATE TABLE branch_address (
    encoded_key text,
    branch_encoded_key text,
    city text,
    country text,
    index_in_list text,
    latitude text,
    line_1 text,
    line_2 text,
    longitude text,
    postcode text,
    region text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (branch_encoded_key) REFERENCES branch(encoded_key)
);

CREATE TABLE branch_holiday (
    encoded_key text,
    branch_encoded_key text,
    creation_date text,
    "date" text,
    id text,
    is_annually_recurring text,
    "name" text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (branch_encoded_key) REFERENCES branch(encoded_key)
);

CREATE TABLE branch (
    encoded_key text,
    creation_date text,
    email_address text,
    id text,
    last_modified_date timestamp,
    "name" text,
    note text,
    phone_number text,
    "state" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key)
);

CREATE TABLE currency (
    _fivetran_id text,
    base_currency text,
    code text,
    creation_date text,
    currency_symbol_position text,
    digits_after_decimal text,
    last_modified_date text,
    "name" text,
    numeric_code text,
    symbol text,
    "type" text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE credit_arrangement (
    encoded_key text,
    holder_key text,
    amount text,
    approved_date text,
    available_credit_amount text,
    closed_date text,
    consumed_credit_amount text,
    creation_date text,
    currency_code text,
    expire_date text,
    exposure_limit_type text,
    holder_type text,
    id text,
    last_modified_date text,
    note text,
    start_date text,
    "state" text,
    sub_state text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (holder_key) REFERENCES groups(encoded_key)
);

CREATE TABLE client_address (
    encoded_key text,
    client_encoded_key text,
    city text,
    country text,
    index_in_list text,
    latitude text,
    line_1 text,
    line_2 text,
    longitude text,
    parent_key text,
    postcode text,
    region text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (client_encoded_key) REFERENCES client(encoded_key)
);

CREATE TABLE client_id_document_attachment (
    client_id_document_client_key text,
    encoded_key text,
    client_id_document_encoded_key text,
    creation_date text,
    file_name text,
    file_size text,
    id text,
    last_modified_date text,
    location text,
    "name" text,
    note text,
    owner_key text,
    owner_type text,
    "type" text,
    PRIMARY KEY (client_id_document_client_key, encoded_key, client_id_document_encoded_key),
    FOREIGN KEY (client_id_document_encoded_key) REFERENCES client_id_document(encoded_key)
);

CREATE TABLE client_id_document (
    encoded_key text,
    client_key text,
    document_id text,
    document_type text,
    identification_document_template_key text,
    index_in_list text,
    issuing_authority text,
    valid_until text,
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (client_key) REFERENCES client(encoded_key)
);

CREATE TABLE client (
    encoded_key text,
    assigned_branch_key text,
    assigned_centre_key text,
    assigned_user_key text,
    client_role_key text,
    activation_date text,
    approved_date text,
    birth_date text,
    closed_date text,
    creation_date text,
    email_address text,
    first_name text,
    gender text,
    group_keys jsonb,
    group_loan_cycle text,
    home_phone text,
    id text,
    last_modified_date timestamp,
    last_name text,
    loan_cycle text,
    middle_name text,
    migration_event_key text,
    mobile_phone text,
    mobile_phone_2 text,
    note text,
    portal_settings_encoded_key text,
    portal_settings_last_logged_in_date text,
    portal_state text,
    preferred_language text,
    profile_picture_key text,
    profile_signature_key text,
    "state" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (encoded_key),
    FOREIGN KEY (assigned_branch_key) REFERENCES branch(encoded_key),
    FOREIGN KEY (assigned_centre_key) REFERENCES centre(encoded_key),
    FOREIGN KEY (assigned_user_key) REFERENCES users(encoded_key),
    FOREIGN KEY (client_role_key) REFERENCES client_role(encoded_key)
);

CREATE TABLE user_role_access_permission (
    "index" text,
    user_role_id text,
    permission text,
    PRIMARY KEY ("index", user_role_id),
    FOREIGN KEY (user_role_id) REFERENCES user_role(id)
);

CREATE TABLE user_role (
    id text,
    administrator_access text,
    api_access text,
    creation_date text,
    credit_officer_access text,
    delivery_access text,
    encoded_key text,
    last_modified_date text,
    mambu_access text,
    "name" text,
    note text,
    support_access text,
    teller_access text,
    PRIMARY KEY (id)
);

CREATE TABLE accounting_report_item (
    encoded_key text,
    amounts_closing_balance text,
    amounts_credit text,
    amounts_debit text,
    amounts_net_change text,
    amounts_opening_balance text,
    foreign_amounts_closing_balance text,
    foreign_amounts_credit text,
    foreign_amounts_debit text,
    foreign_amounts_net_change text,
    foreign_amounts_opening_balance text,
    gl_account_activated text,
    gl_account_allow_manual_journal_entry text,
    gl_account_balance text,
    gl_account_code text,
    gl_account_creation_date text,
    gl_account_currency_code text,
    gl_account_description text,
    gl_account_last_modified_date text,
    gl_account_migration_event_key text,
    gl_account_name text,
    gl_account_strip_trailing_zero text,
    gl_account_type text,
    gl_account_usage text,
    PRIMARY KEY (encoded_key)
);
