CREATE TABLE component_price_point_price (
    id text,
    component_id text,
    price_point_id text,
    ending_quantity text,
    formatted_unit_price text,
    segment_id text,
    starting_quantity text,
    unit_price text,
    PRIMARY KEY (id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id)
);

CREATE TABLE component_price_point (
    id text,
    component_id text,
    archived_at text,
    created_at text,
    defaults text,
    handle text,
    "name" text,
    pricing_scheme text,
    tax_included text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (component_id) REFERENCES component(id)
);

CREATE TABLE customer (
    id text,
    default_subscription_group_uid text,
    parent_id text,
    address text,
    address_2 text,
    cc_emails text,
    city text,
    country text,
    country_name text,
    created_at text,
    email text,
    first_name text,
    last_name text,
    locale text,
    organization text,
    phone text,
    portal_customer_created_at text,
    portal_invite_last_accepted_at text,
    portal_invite_last_sent_at text,
    reference text,
    "state" text,
    state_name text,
    tax_exempt text,
    updated_at timestamp,
    vat_number text,
    verified text,
    zip text,
    PRIMARY KEY (id),
    FOREIGN KEY (default_subscription_group_uid) REFERENCES subscription_group(uid),
    FOREIGN KEY (parent_id) REFERENCES customer(id)
);

CREATE TABLE insight_site_stat (
    site_id text,
    seller_name text,
    site_currency text,
    site_name text,
    stats_revenue_this_month text,
    stats_revenue_this_year text,
    stats_revenue_today text,
    stats_subscriptions_today text,
    stats_total_revenue text,
    stats_total_subscriptions text,
    PRIMARY KEY (site_id),
    FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE group_subscription_id (
    group_subscription_id text,
    subscription_group_id text,
    PRIMARY KEY (group_subscription_id, subscription_group_id),
    FOREIGN KEY (group_subscription_id) REFERENCES subscription(id),
    FOREIGN KEY (subscription_group_id) REFERENCES subscription_group(uid)
);

CREATE TABLE subscription_group (
    uid text,
    customer_id text,
    primary_subscription_id text,
    cancel_at_end_of_period text,
    next_assessment_at text,
    payment_profile_id text,
    pending_discounts_balance_in_cents text,
    prepayments_balance_in_cents text,
    scheme text,
    service_credits_balance_in_cents text,
    "state" text,
    PRIMARY KEY (uid),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (primary_subscription_id) REFERENCES subscription(id)
);

CREATE TABLE coupon_usage (
    id text,
    coupon_id text,
    product_family_id text,
    "name" text,
    revenue text,
    revenue_in_cents text,
    savings text,
    savings_in_cents text,
    signups text,
    PRIMARY KEY (id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (product_family_id) REFERENCES product_family(id)
);

CREATE TABLE subscription_proforma_invoice_line_item (
    uid text,
    subscription_proforma_invoice_uid text,
    component_id text,
    price_point_id text,
    product_id text,
    product_price_point_id text,
    description text,
    discount_amount text,
    period_range_end text,
    period_range_start text,
    product_version text,
    quantity text,
    subtotal_amount text,
    tax_amount text,
    tiered_unit_price text,
    title text,
    total_amount text,
    unit_price text,
    PRIMARY KEY (uid, subscription_proforma_invoice_uid),
    FOREIGN KEY (subscription_proforma_invoice_uid) REFERENCES subscription_proforma_invoice(uid),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_price_point_id) REFERENCES products_price_point(id)
);

CREATE TABLE subscription_proforma_invoice (
    uid text,
    customer_id text,
    site_id text,
    subscription_id text,
    billing_address_city text,
    billing_address_country text,
    billing_address_line_2 text,
    billing_address_state text,
    billing_address_street text,
    billing_address_zip text,
    collection_method text,
    consolidation_level text,
    created_at text,
    credit_amount text,
    credits jsonb,
    currency text,
    custom_fields jsonb,
    delivery_date text,
    discount_amount text,
    discounts text,
    due_amount text,
    number text,
    paid_amount text,
    payment_instructions text,
    payments jsonb,
    product_family_name text,
    product_name text,
    refund_amount text,
    "role" text,
    seller_address_city text,
    seller_address_country text,
    seller_address_line_2 text,
    seller_address_state text,
    seller_address_street text,
    seller_address_zip text,
    seller_name text,
    seller_phone text,
    sequence_number text,
    shipping_address_city text,
    shipping_address_country text,
    shipping_address_line_2 text,
    shipping_address_state text,
    shipping_address_street text,
    shipping_address_zip text,
    "status" text,
    subtotal_amount text,
    tax_amount text,
    taxes jsonb,
    total_amount text,
    PRIMARY KEY (uid),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (site_id) REFERENCES site(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE invoice_event_data_payment (
    transaction_id text,
    invoice_event_id text,
    applied_amount text,
    memo text,
    original_amount text,
    payment_method_card_brand text,
    payment_method_card_expiration text,
    payment_method_last_four text,
    payment_method_masked_card_number text,
    payment_method_type text,
    prepayment text,
    transaction_time text,
    PRIMARY KEY (transaction_id, invoice_event_id),
    FOREIGN KEY (invoice_event_id) REFERENCES invoice_event(id)
);

CREATE TABLE invoice_event_data_taxes_line_item (
    uid text,
    invoice_event_data_taxes_uid text,
    tax_amount text,
    tax_exempt_amount text,
    taxable_amount text,
    PRIMARY KEY (uid, invoice_event_data_taxes_uid),
    FOREIGN KEY (invoice_event_data_taxes_uid) REFERENCES invoice_event_data_taxes(uid)
);

CREATE TABLE invoice_event_data_taxes (
    uid text,
    invoice_event_id text,
    description text,
    eu_vat text,
    percentage text,
    source_id text,
    source_type text,
    tax_amount text,
    tax_component_breakouts text,
    tax_exempt_amount text,
    taxable_amount text,
    title text,
    transaction_id text,
    PRIMARY KEY (uid, invoice_event_id),
    FOREIGN KEY (invoice_event_id) REFERENCES invoice_event(id)
);

CREATE TABLE invoice_event_data_line_item (
    uid text,
    invoice_event_id text,
    component_id text,
    price_point_id text,
    product_id text,
    product_price_point_id text,
    component_cost_data text,
    description text,
    discount_amount text,
    hide text,
    period_range_end text,
    period_range_start text,
    product_version text,
    quantity text,
    subtotal_amount text,
    tax_amount text,
    tax_code text,
    tax_exempt_amount text,
    tax_included text,
    tiered_unit_price text,
    title text,
    total_amount text,
    transaction_id text,
    unit_price text,
    PRIMARY KEY (uid, invoice_event_id),
    FOREIGN KEY (invoice_event_id) REFERENCES invoice_event(id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_price_point_id) REFERENCES products_price_point(id)
);

CREATE TABLE invoice_event (
    id text,
    customer_id text,
    invoice_uid text,
    parent_invoice_id text,
    payer_chargify_id text,
    site_id text,
    event_data_backported_at text,
    event_data_billing_address_city text,
    event_data_billing_address_country text,
    event_data_billing_address_line_2 text,
    event_data_billing_address_state text,
    event_data_billing_address_street text,
    event_data_billing_address_zip text,
    event_data_collection_method text,
    event_data_consolidation_level text,
    event_data_created_at text,
    event_data_credit_amount text,
    event_data_credits text,
    event_data_currency text,
    event_data_custom_fields text,
    event_data_customer_id text,
    event_data_discount_amount text,
    event_data_discounts text,
    event_data_display_settings_display_eu_vat_breakdown text,
    event_data_display_settings_display_introductory_offer text,
    event_data_display_settings_eu_vat_breakdown_exchange_rate text,
    event_data_display_settings_eu_vat_breakdown_exchange_rate_cached_at text,
    event_data_display_settings_eu_vat_breakdown_message_template text,
    event_data_display_settings_eu_vat_breakdown_total_in_eur text,
    event_data_display_settings_eu_vat_breakdown_vat_in_eur text,
    event_data_display_settings_hide_zero_subtotal_lines text,
    event_data_display_settings_include_discounts_on_lines text,
    event_data_display_settings_introductory_offer text,
    event_data_due_amount text,
    event_data_due_date text,
    event_data_id text,
    event_data_issue_date text,
    event_data_legacy_invoice_number text,
    event_data_memo text,
    event_data_net_terms text,
    event_data_number text,
    event_data_paid_amount text,
    event_data_paid_date text,
    event_data_parent_invoice_id text,
    event_data_parent_invoice_number text,
    event_data_payment_instructions text,
    event_data_prepaid_usage_details text,
    event_data_product_family_name text,
    event_data_product_name text,
    event_data_recipient_emails text,
    event_data_refund_amount text,
    event_data_refunds text,
    event_data_role text,
    event_data_seller_address_city text,
    event_data_seller_address_country text,
    event_data_seller_address_line_2 text,
    event_data_seller_address_state text,
    event_data_seller_address_street text,
    event_data_seller_address_zip text,
    event_data_seller_logo_url text,
    event_data_seller_name text,
    event_data_seller_phone text,
    event_data_sequence_number text,
    event_data_shipping_address_city text,
    event_data_shipping_address_country text,
    event_data_shipping_address_line_2 text,
    event_data_shipping_address_state text,
    event_data_shipping_address_street text,
    event_data_shipping_address_zip text,
    event_data_site_id text,
    event_data_statement_id text,
    event_data_status text,
    event_data_status_changed_at text,
    event_data_subscription_group_id text,
    event_data_subscription_id text,
    event_data_subtotal_amount text,
    event_data_tax_amount text,
    event_data_tax_exempt_amount text,
    event_data_total_amount text,
    event_data_transaction_time text,
    event_data_uid text,
    event_data_updated_at text,
    event_type text,
    invoice_id text,
    timestamps timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid),
    FOREIGN KEY (parent_invoice_id) REFERENCES subscription(id),
    FOREIGN KEY (payer_chargify_id) REFERENCES customer(id),
    FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE offer_signup_pages (
    id text,
    offer_id text,
    enabled text,
    nickname text,
    return_params text,
    return_url text,
    PRIMARY KEY (id, offer_id),
    FOREIGN KEY (offer_id) REFERENCES offer(id)
);

CREATE TABLE offer_discounts (
    coupon_id text,
    offer_id text,
    coupon_code text,
    coupon_name text,
    PRIMARY KEY (coupon_id, offer_id),
    FOREIGN KEY (offer_id) REFERENCES offer(id)
);

CREATE TABLE offer_items (
    component_id text,
    offer_id text,
    price_point_id text,
    component_name text,
    component_unit_price text,
    currency_prices text,
    editable text,
    price_point_name text,
    starting_quantity text,
    PRIMARY KEY (component_id, offer_id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (offer_id) REFERENCES offer(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id)
);

CREATE TABLE offer (
    id text,
    product_family_id text,
    product_id text,
    product_price_point_id text,
    site_id text,
    archived_at text,
    created_at text,
    description text,
    handle text,
    "name" text,
    product_family_name text,
    product_name text,
    product_price_in_cents text,
    product_price_point_name text,
    product_revisable_number text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (product_family_id) REFERENCES product_family(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_price_point_id) REFERENCES products_price_point(id),
    FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE site (
    id text,
    currency text,
    customer_hierarchy_enabled text,
    default_payment_collection_method text,
    "name" text,
    net_terms_automatic_net_terms text,
    net_terms_custom_net_terms_enabled text,
    net_terms_default_net_terms text,
    net_terms_net_terms_on_remittance_signups_enabled text,
    net_terms_remittance_net_terms text,
    non_primary_currencies jsonb,
    organization_address_city text,
    organization_address_country text,
    organization_address_line_2 text,
    organization_address_name text,
    organization_address_phone text,
    organization_address_state text,
    organization_address_street text,
    organization_address_zip text,
    relationship_invoicing_enabled text,
    seller_id text,
    subdomain text,
    tax_configuration_destination_address text,
    tax_configuration_fully_configured text,
    tax_configuration_kind text,
    test text,
    whopays_default_payer text,
    whopays_enabled text,
    PRIMARY KEY (id)
);

CREATE TABLE reason_code (
    id text,
    site_id text,
    code text,
    created_at text,
    description text,
    "position" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (site_id) REFERENCES site(id)
);

CREATE TABLE payment_profile (
    id text,
    customer_id text,
    bank_account_holder_type text,
    bank_account_type text,
    bank_name text,
    billing_address text,
    billing_address_2 text,
    billing_city text,
    billing_country text,
    billing_state text,
    billing_zip text,
    current_vault text,
    customer_vault_token text,
    first_name text,
    gateway_handle text,
    last_name text,
    masked_bank_account_number text,
    masked_bank_routing_number text,
    payment_type text,
    site_gateway_setting_id text,
    vault_token text,
    verified text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE coupon_restrictions (
    id text,
    coupon_id text,
    handle text,
    item_id text,
    item_type text,
    "name" text,
    PRIMARY KEY (id, coupon_id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE coupon (
    id text,
    product_family_id text,
    allow_negative_balance text,
    amount text,
    amount_in_cents text,
    apply_on_cancel_at_end_of_period text,
    archived_at text,
    code text,
    compounding_strategy text,
    conversion_limit text,
    created_at text,
    description text,
    discount_type text,
    duration_interval text,
    duration_interval_span text,
    duration_interval_unit text,
    duration_period_count text,
    end_date text,
    exclude_mid_period_allocations text,
    "name" text,
    percentage text,
    product_family_name text,
    recurring text,
    recurring_scheme text,
    stackable text,
    start_date text,
    updated_at timestamp,
    use_site_exchange_rate text,
    PRIMARY KEY (id),
    FOREIGN KEY (product_family_id) REFERENCES product_family(id)
);

CREATE TABLE product_family (
    id text,
    accounting_code text,
    created_at text,
    description text,
    handle text,
    "name" text,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE credit_note_refund (
    uid text,
    credit_note_uid text,
    applied_amount text,
    gateway_handle text,
    gateway_transaction_id text,
    gateway_used text,
    memo text,
    original_amount text,
    payment_id text,
    transaction_id text,
    transaction_time text,
    PRIMARY KEY (uid, credit_note_uid),
    FOREIGN KEY (credit_note_uid) REFERENCES credit_note(uid)
);

CREATE TABLE credit_note_application (
    uid text,
    credit_note_uid text,
    invoice_uid text,
    applied_amount text,
    memo text,
    transaction_time text,
    PRIMARY KEY (uid, credit_note_uid),
    FOREIGN KEY (credit_note_uid) REFERENCES credit_note(uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid)
);

CREATE TABLE credit_note_taxes_line_item (
    uid text,
    credit_note_taxes_uid text,
    tax_amount text,
    taxable_amount text,
    PRIMARY KEY (uid, credit_note_taxes_uid),
    FOREIGN KEY (credit_note_taxes_uid) REFERENCES credit_note_taxes(uid)
);

CREATE TABLE credit_note_taxes (
    uid text,
    credit_note_uid text,
    percentage text,
    source_id text,
    source_type text,
    tax_amount text,
    taxable_amount text,
    title text,
    PRIMARY KEY (uid, credit_note_uid),
    FOREIGN KEY (credit_note_uid) REFERENCES credit_note(uid)
);

CREATE TABLE credit_note_discount_line_item (
    uid text,
    credit_note_discount_uid text,
    discount_amount text,
    eligible_amount text,
    PRIMARY KEY (uid, credit_note_discount_uid),
    FOREIGN KEY (credit_note_discount_uid) REFERENCES credit_note_discount(uid)
);

CREATE TABLE credit_note_discount (
    uid text,
    credit_note_uid text,
    code text,
    discount_amount text,
    discount_type text,
    eligible_amount text,
    percentage text,
    source_id text,
    source_type text,
    title text,
    PRIMARY KEY (uid, credit_note_uid),
    FOREIGN KEY (credit_note_uid) REFERENCES credit_note(uid)
);

CREATE TABLE credit_note_line_item (
    uid text,
    credit_note_uid text,
    component_id text,
    price_point_id text,
    product_id text,
    description text,
    discount_amount text,
    period_range_end text,
    period_range_start text,
    product_version text,
    quantity text,
    subtotal_amount text,
    tax_amount text,
    tiered_unit_price text,
    title text,
    total_amount text,
    unit_price text,
    PRIMARY KEY (uid, credit_note_uid),
    FOREIGN KEY (credit_note_uid) REFERENCES credit_note(uid),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE credit_note (
    uid text,
    customer_id text,
    site_id text,
    subscription_id text,
    applied_amount text,
    applied_date text,
    billing_address_city text,
    billing_address_country text,
    billing_address_line_2 text,
    billing_address_state text,
    billing_address_street text,
    billing_address_zip text,
    currency text,
    customer_chargify_id text,
    customer_email text,
    customer_first_name text,
    customer_last_name text,
    customer_organization text,
    customer_reference text,
    discount_amount text,
    issue_date text,
    memo text,
    number text,
    remaining_amount text,
    seller_address_city text,
    seller_address_country text,
    seller_address_line_2 text,
    seller_address_state text,
    seller_address_street text,
    seller_address_zip text,
    seller_name text,
    seller_phone text,
    sequence_number text,
    shipping_address_city text,
    shipping_address_country text,
    shipping_address_line_2 text,
    shipping_address_state text,
    shipping_address_street text,
    shipping_address_zip text,
    "status" text,
    subtotal_amount text,
    tax_amount text,
    total_amount text,
    PRIMARY KEY (uid),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (site_id) REFERENCES site(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE component_price (
    id text,
    component_id text,
    price_point_id text,
    ending_quantity text,
    formatted_unit_price text,
    segment_id text,
    starting_quantity text,
    unit_price text,
    PRIMARY KEY (id, component_id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id)
);

CREATE TABLE component (
    id text,
    default_price_point_id text,
    product_family_id text,
    accounting_code text,
    allow_fractional_quantities text,
    archived text,
    archived_at text,
    created_at text,
    description text,
    downgrade_credit text,
    handle text,
    hide_date_range_on_invoice text,
    item_category text,
    kind text,
    "name" text,
    price_per_unit_in_cents text,
    price_points_url text,
    pricing_scheme text,
    recurring text,
    tax_code text,
    taxable text,
    unit_name text,
    unit_price text,
    updated_at timestamp,
    upgrade_charge text,
    use_site_exchange_rate text,
    PRIMARY KEY (id),
    FOREIGN KEY (default_price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (product_family_id) REFERENCES product_family(id)
);

CREATE TABLE products_price_point (
    id text,
    product_id text,
    subscription_id text,
    archived_at text,
    created_at text,
    expiration_interval text,
    expiration_interval_unit text,
    handle text,
    initial_charge_after_trial text,
    initial_charge_in_cents text,
    "interval" text,
    interval_unit text,
    introductory_offer text,
    "name" text,
    price_in_cents text,
    tax_included text,
    trial_interval text,
    trial_interval_unit text,
    trial_price_in_cents text,
    trial_type text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE event (
    id text,
    customer_id text,
    event_specific_data_component_id text,
    subscription_id text,
    created_at timestamp,
    event_specific_data_event_type text,
    event_specific_data_memo text,
    event_specific_data_metafield_id text,
    event_specific_data_metafield_name text,
    event_specific_data_new_subscription_state text,
    event_specific_data_new_unit_balance text,
    event_specific_data_new_value text,
    event_specific_data_old_value text,
    event_specific_data_previous_subscription_state text,
    event_specific_data_previous_unit_balance text,
    event_specific_data_resource_id text,
    event_specific_data_resource_type text,
    event_specific_data_usage_quantity text,
    "key" text,
    message text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (event_specific_data_component_id) REFERENCES component(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE product_public_signup_page (
    id text,
    product_id text,
    currency text,
    enabled text,
    nickname text,
    return_params text,
    return_url text,
    url text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    default_product_price_point_id text,
    product_family_id text,
    product_price_point_id text,
    accounting_code text,
    archived_at text,
    created_at text,
    description text,
    expiration_interval text,
    expiration_interval_unit text,
    handle text,
    initial_charge_after_trial text,
    initial_charge_in_cents text,
    "interval" text,
    interval_unit text,
    item_category text,
    "name" text,
    price_in_cents text,
    request_billing_address text,
    request_credit_card text,
    require_billing_address text,
    require_credit_card text,
    require_shipping_address text,
    return_params text,
    tax_code text,
    taxable text,
    trial_interval text,
    trial_interval_unit text,
    trial_price_in_cents text,
    update_return_params text,
    update_return_url text,
    updated_at timestamp,
    use_site_exchange_rate text,
    version_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (default_product_price_point_id) REFERENCES products_price_point(id),
    FOREIGN KEY (product_family_id) REFERENCES product_family(id),
    FOREIGN KEY (product_price_point_id) REFERENCES products_price_point(id)
);

CREATE TABLE invoice_payment (
    transaction_id text,
    invoice_uid text,
    applied_amount text,
    gateway_transaction_id text,
    memo text,
    original_amount text,
    payment_method_card_brand text,
    payment_method_card_expiration text,
    payment_method_details text,
    payment_method_kind text,
    payment_method_last_four text,
    payment_method_masked_card_number text,
    payment_method_memo text,
    payment_method_type text,
    prepayment text,
    transaction_time text,
    PRIMARY KEY (transaction_id, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid)
);

CREATE TABLE invoice_line_item (
    uid text,
    invoice_uid text,
    component_id text,
    price_point_id text,
    product_id text,
    component_cost_data jsonb,
    description text,
    discount_amount text,
    period_range_end text,
    period_range_start text,
    product_version text,
    quantity text,
    subtotal_amount text,
    tax_amount text,
    tiered_unit_price text,
    title text,
    total_amount text,
    unit_price text,
    PRIMARY KEY (uid, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE invoice_discount_line_item (
    uid text,
    invoice_discount_uid text,
    discount_amount text,
    eligible_amount text,
    PRIMARY KEY (uid, invoice_discount_uid),
    FOREIGN KEY (invoice_discount_uid) REFERENCES invoice_discount(uid)
);

CREATE TABLE invoice_discount (
    uid text,
    invoice_uid text,
    code text,
    discount_amount text,
    discount_type text,
    eligible_amount text,
    integer text,
    percentage text,
    source_id text,
    source_type text,
    title text,
    PRIMARY KEY (uid, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid),
    FOREIGN KEY (code) REFERENCES coupon(code)
);

CREATE TABLE invoice_taxes_line_item (
    uid text,
    invoice_taxes_uid text,
    tax_amount text,
    taxable_amount text,
    PRIMARY KEY (uid, invoice_taxes_uid),
    FOREIGN KEY (invoice_taxes_uid) REFERENCES invoice_taxes(uid)
);

CREATE TABLE invoice_taxes (
    uid text,
    invoice_uid text,
    code text,
    percentage text,
    source_id text,
    source_type text,
    tax_amount text,
    taxable_amount text,
    title text,
    PRIMARY KEY (uid, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid)
);

CREATE TABLE invoice_credit (
    uid text,
    invoice_uid text,
    credit_note_uid text,
    applied_amount text,
    credit_note_number text,
    memo text,
    original_amount text,
    transaction_time text,
    PRIMARY KEY (uid, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid),
    FOREIGN KEY (credit_note_uid) REFERENCES credit_note(uid)
);

CREATE TABLE invoice_refund (
    transaction_id text,
    invoice_uid text,
    applied_amount text,
    gateway_transaction_id text,
    memo text,
    original_amount text,
    payment_id text,
    PRIMARY KEY (transaction_id, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid)
);

CREATE TABLE invoice_custom_field (
    owner_id text,
    invoice_uid text,
    "name" text,
    owner_type text,
    "value" text,
    PRIMARY KEY (owner_id, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid)
);

CREATE TABLE previous_balance_data_invoice (
    previous_balance_data_invoice_uid text,
    invoice_uid text,
    number text,
    outstanding_amount text,
    PRIMARY KEY (previous_balance_data_invoice_uid, invoice_uid),
    FOREIGN KEY (invoice_uid) REFERENCES invoice(uid)
);

CREATE TABLE invoice (
    uid text,
    customer_id text,
    group_primary_subscription_id text,
    parent_invoice_uid text,
    site_id text,
    subscription_id text,
    billing_address_city text,
    billing_address_country text,
    billing_address_line_2 text,
    billing_address_state text,
    billing_address_street text,
    billing_address_zip text,
    collection_method text,
    consolidation_level text,
    created_at text,
    credit_amount text,
    currency text,
    discount_amount text,
    due_amount text,
    due_date text,
    issue_date text,
    memo text,
    number text,
    paid_amount text,
    paid_date text,
    parent_invoice_number text,
    payment_instructions text,
    previous_balance_data_capture_date text,
    product_family_name text,
    product_name text,
    public_url text,
    refund_amount text,
    seller_address_city text,
    seller_address_country text,
    seller_address_line_2 text,
    seller_address_state text,
    seller_address_street text,
    seller_address_zip text,
    seller_name text,
    seller_phone text,
    sequence_number text,
    shipping_address_city text,
    shipping_address_country text,
    shipping_address_line_2 text,
    shipping_address_state text,
    shipping_address_street text,
    shipping_address_zip text,
    "status" text,
    subtotal_amount text,
    tax_amount text,
    total_amount text,
    updated_at timestamp,
    PRIMARY KEY (uid),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (group_primary_subscription_id) REFERENCES subscription(id),
    FOREIGN KEY (parent_invoice_uid) REFERENCES invoice(uid),
    FOREIGN KEY (site_id) REFERENCES site(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_component (
    id text,
    component_id text,
    price_point_id text,
    product_family_id text,
    subscription_id text,
    currency text,
    display_on_hosted_page text,
    unit_balance text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (product_family_id) REFERENCES product_family(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_coupon (
    _fivetran_id text,
    code text,
    subscription_id text,
    amount_in_cents text,
    expires_at text,
    percentage text,
    recurring text,
    use_count text,
    uses_allowed text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (code) REFERENCES coupon(code),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription (
    id text,
    bank_account_customer_id text,
    credit_card_customer_id text,
    customer_id text,
    next_product_id text,
    next_product_price_point_id text,
    offer_id text,
    payer_id text,
    product_id text,
    product_price_point_id text,
    reason_code text,
    activated_at text,
    automatically_resume_at text,
    balance_in_cents text,
    bank_account_bank_name text,
    bank_account_billing_address text,
    bank_account_billing_address_2 text,
    bank_account_billing_city text,
    bank_account_billing_country text,
    bank_account_billing_state text,
    bank_account_billing_zip text,
    bank_account_chargify_token text,
    bank_account_current_vault text,
    bank_account_customer_vault_token text,
    bank_account_first_name text,
    bank_account_gateway_handle text,
    bank_account_holder_type text,
    bank_account_id text,
    bank_account_last_name text,
    bank_account_masked_bank_account_number text,
    bank_account_masked_bank_routing_number text,
    bank_account_site_gateway_setting_id text,
    bank_account_type text,
    bank_account_vault_token text,
    cancel_at_end_of_period text,
    canceled_at text,
    cancellation_message text,
    cancellation_method text,
    created_at text,
    credit_card_billing_address text,
    credit_card_billing_address_2 text,
    credit_card_billing_city text,
    credit_card_billing_country text,
    credit_card_billing_state text,
    credit_card_billing_zip text,
    credit_card_card_type text,
    credit_card_current_vault text,
    credit_card_customer_vault_token text,
    credit_card_expiration_month text,
    credit_card_expiration_year text,
    credit_card_first_name text,
    credit_card_gateway_handle text,
    credit_card_id text,
    credit_card_last_name text,
    credit_card_masked_card_number text,
    credit_card_payment_type text,
    credit_card_site_gateway_setting_id text,
    credit_card_vault_token text,
    current_billing_amount_in_cents text,
    current_period_ends_at text,
    current_period_started_at text,
    delayed_cancel_at text,
    dunning_communication_delay_enabled text,
    dunning_communication_delay_time_zone text,
    expires_at text,
    group_primarys text,
    group_uid text,
    net_terms text,
    next_assessment_at text,
    on_hold_at text,
    payment_collection_method text,
    payment_type text,
    prepaid_dunning text,
    previous_state text,
    reference text,
    referral_code text,
    signup_payment_id text,
    signup_revenue text,
    snap_day text,
    "state" text,
    stored_credential_transaction_id text,
    total_revenue_in_cents text,
    trial_ended_at text,
    trial_started_at text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (bank_account_customer_id) REFERENCES customer(id),
    FOREIGN KEY (credit_card_customer_id) REFERENCES customer(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (next_product_id) REFERENCES product(id),
    FOREIGN KEY (next_product_price_point_id) REFERENCES products_price_point(id),
    FOREIGN KEY (offer_id) REFERENCES offer(id),
    FOREIGN KEY (payer_id) REFERENCES customer(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_price_point_id) REFERENCES products_price_point(id),
    FOREIGN KEY (reason_code) REFERENCES reason_code(code)
);

CREATE TABLE allocation (
    _fivetran_id text,
    id text,
    component_id text,
    memo text,
    previous_quantity text,
    proration_downgrade_scheme text,
    proration_upgrade_scheme text,
    quantity text,
    subscription_id text,
    timestamps text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (id) REFERENCES subscription(id)
);

CREATE TABLE usage (
    id text,
    component_id text,
    price_point_id text,
    subscription_id text,
    created_at timestamp,
    memo text,
    quantity text,
    PRIMARY KEY (id),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription_note (
    id text,
    subscription_id text,
    body text,
    created_at text,
    sticky text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE prepayment (
    id text,
    subscription_id text,
    amount_in_cents text,
    created_at timestamp,
    details text,
    external text,
    memo text,
    payment_type text,
    remaining_amount_in_cents text,
    PRIMARY KEY (id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE preview_custom_field (
    owner_id text,
    preview_performa_invoice_uid text,
    metadatum_id text,
    "name" text,
    owner_type text,
    "value" text,
    PRIMARY KEY (owner_id, preview_performa_invoice_uid),
    FOREIGN KEY (preview_performa_invoice_uid) REFERENCES preview_performa_invoice(uid)
);

CREATE TABLE preview_payment (
    _fivetran_id text,
    preview_performa_invoice_uid text,
    applied_amount text,
    memo text,
    original_amount text,
    prepayment text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (preview_performa_invoice_uid) REFERENCES preview_performa_invoice(uid)
);

CREATE TABLE preview_credit (
    uid text,
    preview_performa_invoice_uid text,
    applied_amount text,
    memo text,
    original_amount text,
    PRIMARY KEY (uid, preview_performa_invoice_uid),
    FOREIGN KEY (preview_performa_invoice_uid) REFERENCES preview_performa_invoice(uid)
);

CREATE TABLE preview_taxes_line_item (
    _fivetran_id text,
    preview_taxes_uid text,
    tax_amount text,
    taxable_amount text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (preview_taxes_uid) REFERENCES preview_taxes(uid)
);

CREATE TABLE preview_taxes (
    uid text,
    preview_performa_invoice_uid text,
    percentage text,
    source_type text,
    tax_amount text,
    taxable_amount text,
    title text,
    PRIMARY KEY (uid, preview_performa_invoice_uid),
    FOREIGN KEY (preview_performa_invoice_uid) REFERENCES preview_performa_invoice(uid)
);

CREATE TABLE preview_discount_line_item (
    _fivetran_id text,
    preview_discount_index text,
    discount_amount text,
    eligible_amount text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (preview_discount_index) REFERENCES preview_discount("index")
);

CREATE TABLE preview_discount (
    "index" text,
    preview_performa_invoice_uid text,
    discount_amount text,
    discount_type text,
    eligible_amount text,
    source_type text,
    title text,
    PRIMARY KEY ("index", preview_performa_invoice_uid),
    FOREIGN KEY (preview_performa_invoice_uid) REFERENCES preview_performa_invoice(uid)
);

CREATE TABLE preview_line_item (
    uid text,
    preview_performa_invoice_uid text,
    component_id text,
    price_point_id text,
    product_id text,
    product_price_point_id text,
    description text,
    discount_amount text,
    period_range_end text,
    period_range_start text,
    quantity text,
    subtotal_amount text,
    tax_amount text,
    tiered_unit_price text,
    title text,
    total_amount text,
    unit_price text,
    PRIMARY KEY (uid, preview_performa_invoice_uid),
    FOREIGN KEY (preview_performa_invoice_uid) REFERENCES preview_performa_invoice(uid),
    FOREIGN KEY (component_id) REFERENCES component(id),
    FOREIGN KEY (price_point_id) REFERENCES component_price_point(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (product_price_point_id) REFERENCES products_price_point(id)
);

CREATE TABLE preview_performa_invoice (
    uid text,
    customer_chargify_id text,
    customer_id text,
    site_id text,
    subscription_id text,
    billing_address_city text,
    billing_address_country text,
    billing_address_line_2 text,
    billing_address_state text,
    billing_address_street text,
    billing_address_zip text,
    collection_method text,
    consolidation_level text,
    created_at text,
    credit_amount text,
    currency text,
    delivery_date text,
    discount_amount text,
    due_amount text,
    memo text,
    number text,
    paid_amount text,
    payment_instructions text,
    product_family_name text,
    refund_amount text,
    "role" text,
    seller_address_city text,
    seller_address_country text,
    seller_address_line_2 text,
    seller_address_state text,
    seller_address_street text,
    seller_address_zip text,
    seller_name text,
    seller_phone text,
    sequence_number text,
    shipping_address_city text,
    shipping_address_country text,
    shipping_address_line_2 text,
    shipping_address_state text,
    shipping_address_street text,
    shipping_address_zip text,
    "status" text,
    subtotal_amount text,
    tax_amount text,
    total_amount text,
    PRIMARY KEY (uid),
    FOREIGN KEY (customer_chargify_id) REFERENCES customer(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (site_id) REFERENCES site(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);
