CREATE TABLE "call" (
    id text,
    end_date_time text,
    join_web_url text,
    last_modified_date_time text,
    modalites jsonb,
    organizer_administrative_unit_information jsonb,
    organizer_data_context text,
    organizer_id text,
    organizer_idenity_acs_application_instance text,
    organizer_idenity_acs_user text,
    organizer_idenity_application text,
    organizer_idenity_application_instance text,
    organizer_idenity_asserted_identity text,
    organizer_idenity_azure_communication_service_user text,
    organizer_idenity_device text,
    organizer_idenity_encrypted text,
    organizer_idenity_endpoint_type text,
    organizer_idenity_guest text,
    organizer_idenity_on_premises text,
    organizer_idenity_spool_application_instance text,
    organizer_idenity_spool_user text,
    organizer_identity_phone_display_name text,
    organizer_identity_phone_id text,
    organizer_identity_phone_odata_type text,
    organizer_identity_phone_tenant_id text,
    organizer_identity_user_display_name text,
    organizer_identity_user_id text,
    organizer_identity_user_odata_type text,
    organizer_identity_user_principal_name text,
    organizer_identity_user_tenant_id text,
    start_date_time text,
    "type" text,
    version text,
    PRIMARY KEY (id)
);

CREATE TABLE participant (
    id text,
    call_id text,
    administrarive_unit_info jsonb,
    identity_acs_application_instance text,
    identity_acs_user text,
    identity_application text,
    identity_application_instance text,
    identity_asserted text,
    identity_azure_communication_service_user text,
    identity_device text,
    identity_encrypted text,
    identity_endpoint_type text,
    identity_guest text,
    identity_on_premises text,
    identity_phone_display_name text,
    identity_phone_id text,
    identity_phone_odata_type text,
    identity_phone_tenant_id text,
    identity_spool_application_instance text,
    identity_spool_user text,
    identity_user_display_name text,
    identity_user_id text,
    identity_user_odata_type text,
    identity_user_principal_name text,
    identity_user_tenant_id text,
    PRIMARY KEY (id, call_id),
    FOREIGN KEY (call_id) REFERENCES "call"(id)
);

CREATE TABLE pstn_call (
    id text,
    call_duration_source text,
    call_id text,
    call_type text,
    callee_number text,
    caller_number text,
    charge text,
    conference_id text,
    connection_charge text,
    currency text,
    destination_context text,
    destination_name text,
    duration text,
    end_date_time text,
    inventory_type text,
    license_capability text,
    operator text,
    start_date_time text,
    tenant_country_code text,
    usage_country_code text,
    user_display_name text,
    user_id text,
    user_principal_name text,
    PRIMARY KEY (id)
);

CREATE TABLE session_media_stream (
    id text,
    call_id text,
    session_id text,
    session_media_index text,
    audio_codec text,
    average_audio_degradation text,
    average_audio_network_jitter text,
    average_bandwidth_estimate text,
    average_freeze_duration text,
    average_jitter text,
    average_packet_loss_rate text,
    average_ratio_of_concealed_samples text,
    average_received_frame_rate text,
    average_round_trip_time text,
    average_video_frame_loss_percentage text,
    average_video_frame_rate text,
    average_video_packet_loss_rate text,
    end_date_time text,
    is_audio_forward_error_correction_used text,
    low_frame_rate_ratio text,
    low_video_processing_capability_ratio text,
    max_audio_network_jitter text,
    max_jitter text,
    max_packet_loss_rate text,
    max_ratio_of_concealed_samples text,
    max_round_trip_time text,
    packet_utilization text,
    post_forward_error_correction_packet_loss_rate text,
    rms_freeze_duration text,
    start_date_time text,
    stream_direction text,
    video_codec text,
    was_media_bypassed text,
    PRIMARY KEY (id, call_id, session_id, session_media_index),
    FOREIGN KEY (call_id) REFERENCES session_media(call_id),
    FOREIGN KEY (session_id) REFERENCES session_media(session_id),
    FOREIGN KEY (session_media_index) REFERENCES session_media("index")
);

CREATE TABLE session_media (
    "index" text,
    call_id text,
    session_id text,
    callee_device_capture_device_driver text,
    callee_device_capture_device_name text,
    callee_device_capture_not_functioning_event_ratio text,
    callee_device_clipping_event_ratio text,
    callee_device_cpu_insufficient_event_ratio text,
    callee_device_glitch_event_ratio text,
    callee_device_howling_event_count text,
    callee_device_initial_signal_level_rootmean_square text,
    callee_device_low_speech_level_event_ratio text,
    callee_device_low_speech_to_noise_event_ratio text,
    callee_device_mic_glitch_rate text,
    callee_device_received_noise_level text,
    callee_device_received_signal_level text,
    callee_device_render_device_driver text,
    callee_device_render_device_name text,
    callee_device_render_mute_event_ratio text,
    callee_device_render_not_functioning_event_ratio text,
    callee_device_render_zero_volume_event_ratio text,
    callee_device_sent_noise_level text,
    callee_device_sent_signal_level text,
    callee_device_speaker_glitch_rate text,
    callee_network_bandwidth_low_event_ratio text,
    callee_network_basic_service_set_identifier text,
    callee_network_connection_type text,
    callee_network_delay_event_ratio text,
    callee_network_dns_suffix text,
    callee_network_ip_address text,
    callee_network_link_speed text,
    callee_network_mac_address text,
    callee_network_port text,
    callee_network_received_quality_event_ratio text,
    callee_network_reflexive_ip_address text,
    callee_network_replay_ip_address text,
    callee_network_replay_port text,
    callee_network_sent_quality_event_ratio text,
    callee_network_subnet text,
    callee_network_trace_route_hops jsonb,
    callee_network_transport_protocol text,
    callee_network_wifi_band text,
    callee_network_wifi_battery_charge text,
    callee_network_wifi_channel text,
    callee_network_wifi_microsoft_driver text,
    callee_network_wifi_microsoft_driver_version text,
    callee_network_wifi_radio_type text,
    callee_network_wifi_signal_stength text,
    callee_network_wifi_vendor_driver text,
    callee_network_wifi_vendor_driver_version text,
    caller_device_capture_device_driver text,
    caller_device_capture_device_name text,
    caller_device_capture_not_functioning_event_ratio text,
    caller_device_clipping_event_ratio text,
    caller_device_cpu_insufficient_event_ratio text,
    caller_device_glitch_event_ratio text,
    caller_device_howling_event_count text,
    caller_device_initial_signal_level_rootmean_square text,
    caller_device_low_speech_level_event_ratio text,
    caller_device_low_speech_to_noise_event_ratio text,
    caller_device_mic_glitch_rate text,
    caller_device_received_noise_level text,
    caller_device_received_signal_level text,
    caller_device_render_device_driver text,
    caller_device_render_device_name text,
    caller_device_render_mute_event_ratio text,
    caller_device_render_not_functioning_event_ratio text,
    caller_device_render_zero_volume_event_ratio text,
    caller_device_sent_noise_level text,
    caller_device_sent_signal_level text,
    caller_device_speaker_glitch_rate text,
    caller_network_bandwidth_low_event_ratio text,
    caller_network_basic_service_set_identifier text,
    caller_network_connection_type text,
    caller_network_delay_event_ratio text,
    caller_network_dns_suffix text,
    caller_network_ip_address text,
    caller_network_link_speed text,
    caller_network_mac_address text,
    caller_network_port text,
    caller_network_received_quality_event_ratio text,
    caller_network_reflexive_ip_address text,
    caller_network_replay_ip_address text,
    caller_network_replay_port text,
    caller_network_sent_quality_event_ratio text,
    caller_network_subnet text,
    caller_network_trace_route_hops jsonb,
    caller_network_transport_protocol text,
    caller_network_wifi_band text,
    caller_network_wifi_battery_charge text,
    caller_network_wifi_channel text,
    caller_network_wifi_microsoft_driver text,
    caller_network_wifi_microsoft_driver_version text,
    caller_network_wifi_radio_type text,
    caller_network_wifi_signal_stength text,
    caller_network_wifi_vendor_driver text,
    caller_network_wifi_vendor_driver_version text,
    label text,
    PRIMARY KEY ("index", call_id, session_id),
    FOREIGN KEY (call_id) REFERENCES "session"(call_id),
    FOREIGN KEY (session_id) REFERENCES "session"(id)
);

CREATE TABLE "session" (
    id text,
    call_id text,
    callee_asssociated_identity_display_name text,
    callee_asssociated_identity_id text,
    callee_asssociated_identity_odata_type text,
    callee_asssociated_identity_tenant_id text,
    callee_cpu_cores_count text,
    callee_cpu_name text,
    callee_cpu_processor_spped_in_mhz text,
    callee_feedback_rating text,
    callee_identity_acs_application_instance text,
    callee_identity_acs_user text,
    callee_identity_application text,
    callee_identity_application_instance text,
    callee_identity_device text,
    callee_identity_encrypted text,
    callee_identity_guest text,
    callee_identity_on_premises text,
    callee_identity_phone_display_name text,
    callee_identity_phone_id text,
    callee_identity_phone_tenant_id text,
    callee_identity_spool_application_instance text,
    callee_identity_spool_user text,
    callee_identity_user text,
    callee_name text,
    callee_odata_type text,
    callee_user_agent_application_version text,
    callee_user_agent_azure_ad_app_id text,
    callee_user_agent_communication_service_id text,
    callee_user_agent_header_value text,
    callee_user_agent_odata_type text,
    callee_user_agent_platform text,
    callee_user_agent_product_family text,
    caller_asssociated_identity_display_name text,
    caller_asssociated_identity_id text,
    caller_asssociated_identity_odata_type text,
    caller_asssociated_identity_tenant_id text,
    caller_asssociated_identity_user_principal_name text,
    caller_cpu_cores_count text,
    caller_cpu_name text,
    caller_cpu_processor_spped_in_mhz text,
    caller_feedback_rating text,
    caller_identity_user_display_name text,
    caller_identity_user_id text,
    caller_identity_user_tenant_id text,
    caller_indentity_acs_application_instance text,
    caller_indentity_acs_user text,
    caller_indentity_application text,
    caller_indentity_application_instance text,
    caller_indentity_device text,
    caller_indentity_encrypted text,
    caller_indentity_guest text,
    caller_indentity_on_premises text,
    caller_indentity_phone text,
    caller_indentity_spool_application_instance text,
    caller_indentity_spool_user text,
    caller_name text,
    caller_odata_type text,
    caller_user_agent_application_version text,
    caller_user_agent_azure_ad_app_id text,
    caller_user_agent_communication_service_id text,
    caller_user_agent_header_value text,
    caller_user_agent_odata_type text,
    caller_user_agent_platform text,
    caller_user_agent_product_family text,
    end_date_time text,
    failure_information text,
    feedback_token_distorted_sound text,
    feedback_token_echo text,
    feedback_token_interruption text,
    feedback_token_low_value text,
    feedback_token_no_sound text,
    feedback_token_noisy text,
    feedback_token_other_no_sound text,
    feedback_token_stopped text,
    is_test text,
    modalities jsonb,
    segment_odata_context text,
    start_date_time text,
    PRIMARY KEY (id, call_id),
    FOREIGN KEY (call_id) REFERENCES "call"(id)
);

CREATE TABLE direct_routing_call (
    id text,
    call_end_sub_reason text,
    call_type text,
    callee_number text,
    caller_number text,
    correlation_id text,
    duration text,
    end_date_time text,
    failure_date_time text,
    final_sip_code text,
    final_sip_code_phrase text,
    invite_date_time text,
    media_bypass_enabled text,
    media_path_location text,
    signaling_location text,
    start_date_time text,
    successful_call text,
    trunk_fully_qualified_domain_name text,
    user_display_name text,
    user_id text,
    user_principal_name text,
    PRIMARY KEY (id)
);
