CREATE TABLE report_collection_run (
    id text,
    report_collection_id text,
    completed_at text,
    created_at text,
    form_fields jsonb,
    is_latest_report_run text,
    is_latest_successful_report_run text,
    parameters jsonb,
    purge_completed_at text,
    purge_started_at text,
    python_state text,
    report_has_failures_since_last_success text,
    "state" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (report_collection_id) REFERENCES report_collection(id)
);

CREATE TABLE collection (
    id text,
    default_access_level text,
    description text,
    free_default text,
    "name" text,
    restricted text,
    space_type text,
    "state" text,
    token text,
    viewable text,
    viewed text,
    PRIMARY KEY (id)
);

CREATE TABLE groups (
    id text,
    description text,
    managed text,
    "name" text,
    "state" text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE data_source_custom_attribute (
    "name" text,
    data_source_id text,
    "value" text,
    PRIMARY KEY ("name", data_source_id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id)
);

CREATE TABLE data_source (
    id text,
    account_id text,
    adapter text,
    adapter_version text,
    asleep text,
    bridged text,
    created_at text,
    database text,
    default_access_level text,
    description text,
    display_name text,
    has_expensive_schema_updates text,
    host text,
    ldap text,
    "name" text,
    organization_plan_code text,
    organization_token text,
    port text,
    provider text,
    public text,
    queryable text,
    soft_deleted text,
    ssl text,
    ssl_trusted_cert text,
    token text,
    updated_at text,
    username text,
    vendor text,
    warehouse text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE dataset (
    id text,
    account_id text,
    data_source_id text,
    archived text,
    color_mapping text,
    created_at text,
    description text,
    drill_anywhere_enabled text,
    drilldowns_enabled text,
    edited_at text,
    expected_runtime text,
    flamingo_signature text,
    full_width text,
    github_link text,
    imported_datasets text,
    is_embedded text,
    is_signed text,
    last_run_at text,
    last_saved_at text,
    last_successful_run_token text,
    last_successful_sync_at text,
    last_successfully_run_at text,
    layout text,
    manual_run_disabled text,
    "name" text,
    public text,
    published_at text,
    query_preview text,
    run_privately text,
    shared text,
    space_token text,
    theme_id text,
    token text,
    "type" text,
    updated_at text,
    view_count text,
    web_preview_image text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id)
);

CREATE TABLE report_data_source_schedule (
    id text,
    report_using_data_source_id text,
    created_at text,
    "hour" text,
    last_run_at text,
    last_scheduled_run text,
    last_succeeded_at text,
    "minute" text,
    "name" text,
    next_scheduled_run text,
    parameters jsonb,
    retry_state text,
    subscribed text,
    time_zone text,
    timeout text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (report_using_data_source_id) REFERENCES report_using_data_source(id)
);

CREATE TABLE report_collection_query (
    id text,
    data_source_id text,
    report_collection_id text,
    created_at text,
    dbt_metric_id text,
    dbt_metric_token text,
    explorations_count text,
    last_run_id text,
    mapping_id text,
    "name" text,
    raw_query text,
    token text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id),
    FOREIGN KEY (report_collection_id) REFERENCES report_collection(id)
);

CREATE TABLE collection_membership (
    id text,
    collection_id text,
    email text,
    member_token text,
    token text,
    "type" text,
    PRIMARY KEY (id, collection_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE account_avatar (
    "name" text,
    account_id text,
    "value" text,
    PRIMARY KEY ("name", account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    admin_data_source_connections_only text,
    authorized_domains jsonb,
    created_at text,
    dataset_size_limit_mb text,
    is_user text,
    membership_type text,
    "name" text,
    payment_method_confirmed text,
    plan_code text,
    private_definition_limit text,
    query_run_size_limit_mb text,
    token text,
    trial_state text,
    username text,
    PRIMARY KEY (id)
);

CREATE TABLE report_collection_schedule (
    id text,
    report_collection_id text,
    created_at text,
    "hour" text,
    last_run_at text,
    last_scheduled_run text,
    last_succeeded_at text,
    "minute" text,
    "name" text,
    next_scheduled_run text,
    parameters jsonb,
    retry_state text,
    subscribed text,
    time_zone text,
    timeout text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (report_collection_id) REFERENCES report_collection(id)
);

CREATE TABLE dataset_schedule (
    id text,
    dataset_id text,
    created_at text,
    "hour" text,
    last_run_at text,
    last_scheduled_run text,
    last_succeeded_at text,
    "minute" text,
    "name" text,
    next_scheduled_run text,
    parameters jsonb,
    retry_state text,
    subscribed text,
    time_zone text,
    timeout text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (dataset_id) REFERENCES dataset(id)
);

CREATE TABLE report_using_data_source (
    id text,
    account_id text,
    data_source_id text,
    account_username text,
    archived text,
    color_mapping text,
    created_at text,
    description text,
    drill_anywhere_enabled text,
    drilldowns_enabled text,
    edited_at text,
    expected_runtime text,
    full_width text,
    github_link text,
    imported_dataset text,
    is_embedded text,
    is_signed text,
    last_run_at text,
    last_saved_at text,
    last_successful_run_token text,
    last_successful_sync_at text,
    last_successfully_run_at text,
    layout text,
    manual_run_disabled text,
    "name" text,
    public text,
    published_at text,
    query_preview text,
    run_privately text,
    shared text,
    space_token text,
    theme_id text,
    token text,
    "type" text,
    updated_at text,
    view_count text,
    web_preview_image text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id)
);

CREATE TABLE definition (
    id text,
    data_source_id text,
    created_at text,
    description text,
    github_link text,
    last_saved_at text,
    last_successful_sync_at text,
    "name" text,
    "source" text,
    token text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id)
);

CREATE TABLE report_collection_query_chart (
    id text,
    report_collection_id text,
    report_collection_query_id text,
    color_palette_token text,
    created_at text,
    switch_view_token text,
    updated_at text,
    "view" jsonb,
    view_vegas jsonb,
    view_version text,
    PRIMARY KEY (id),
    FOREIGN KEY (report_collection_id) REFERENCES report_collection(id),
    FOREIGN KEY (report_collection_query_id) REFERENCES report_collection_query(id)
);

CREATE TABLE report_data_source_query_run (
    id text,
    data_source_id text,
    query_token text,
    report_data_source_run_id text,
    report_using_data_source_id text,
    completed_at text,
    created_at text,
    dbt_metric_id text,
    dbt_metric_token text,
    error_code text,
    error_message text,
    error_type text,
    help_url text,
    limits text,
    max_result_bytes text,
    parameters jsonb,
    raw_source text,
    rendered_source text,
    "state" text,
    statement_annotation text,
    token text,
    PRIMARY KEY (id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id),
    FOREIGN KEY (query_token) REFERENCES report_data_source_query(token),
    FOREIGN KEY (report_data_source_run_id) REFERENCES report_data_source_run(id),
    FOREIGN KEY (report_using_data_source_id) REFERENCES report_using_data_source(id)
);

CREATE TABLE report_data_source_query (
    id text,
    data_source_id text,
    report_using_data_source_id text,
    created_at text,
    dbt_metric_id text,
    dbt_metric_token text,
    explorations_count text,
    last_run_id text,
    mapping_id text,
    "name" text,
    raw_query text,
    token text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id),
    FOREIGN KEY (report_using_data_source_id) REFERENCES report_using_data_source(id)
);

CREATE TABLE report_data_source_run (
    id text,
    report_using_data_source_id text,
    completed_at text,
    created_at text,
    form_fields jsonb,
    is_latest_report_run text,
    is_latest_successful_report_run text,
    parameters jsonb,
    purge_completed_at text,
    purge_started_at text,
    python_state text,
    report_has_failures_since_last_success text,
    "state" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (report_using_data_source_id) REFERENCES report_using_data_source(id)
);

CREATE TABLE group_membership (
    id text,
    group_id text,
    member_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (member_id) REFERENCES workspace_membership(id)
);

CREATE TABLE workspace_membership (
    id text,
    activated_at text,
    "admin" text,
    invited text,
    managed_by_scim text,
    "state" text,
    username text,
    PRIMARY KEY (id)
);

CREATE TABLE dataset_run (
    id text,
    dataset_id text,
    created_at text,
    form_fields jsonb,
    is_latest_report_run text,
    is_latest_successful_report_run text,
    parameters jsonb,
    purge_completed_at text,
    purge_started_at text,
    python_state text,
    report_has_failures_since_last_success text,
    "state" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (dataset_id) REFERENCES dataset(id)
);

CREATE TABLE report_data_source_query_chart (
    id text,
    report_data_source_query_id text,
    report_using_data_source_id text,
    color_palette_token text,
    created_at text,
    switch_view_token text,
    updated_at text,
    "view" jsonb,
    view_vegas jsonb,
    view_version text,
    PRIMARY KEY (id),
    FOREIGN KEY (report_data_source_query_id) REFERENCES report_data_source_query(id),
    FOREIGN KEY (report_using_data_source_id) REFERENCES report_using_data_source(id)
);

CREATE TABLE report_collection_query_run (
    id text,
    data_source_id text,
    query_token text,
    report_collection_id text,
    report_collection_run_id text,
    completed_at text,
    created_at text,
    dbt_metric_id text,
    dbt_metric_token text,
    error_code text,
    error_message text,
    error_type text,
    help_url text,
    limits text,
    max_result_bytes text,
    parameters jsonb,
    raw_source text,
    rendered_source text,
    "state" text,
    statement_annotation text,
    token text,
    PRIMARY KEY (id),
    FOREIGN KEY (data_source_id) REFERENCES data_source(id),
    FOREIGN KEY (query_token) REFERENCES report_collection_query(token),
    FOREIGN KEY (report_collection_id) REFERENCES report_collection(id),
    FOREIGN KEY (report_collection_run_id) REFERENCES report_collection_run(id)
);

CREATE TABLE report_collection (
    id text,
    account_id text,
    collection_id text,
    account_username text,
    archived text,
    color_mapping text,
    created_at text,
    description text,
    drill_anywhere_enabled text,
    drilldowns_enabled text,
    edited_at text,
    expected_runtime text,
    full_width text,
    github_link text,
    imported_dataset text,
    is_embedded text,
    is_signed text,
    last_run_at text,
    last_saved_at text,
    last_successful_run_token text,
    last_successful_sync_at text,
    last_successfully_run_at text,
    layout text,
    manual_run_disabled text,
    "name" text,
    public text,
    published_at text,
    query_preview text,
    run_privately text,
    shared text,
    space_token text,
    theme_id text,
    token text,
    "type" text,
    updated_at text,
    view_count text,
    web_preview_image text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);
