CREATE TABLE segment_info (
    "day" text,
    segment_id text,
    description text,
    interest text,
    "name" text,
    PRIMARY KEY ("day", segment_id),
    FOREIGN KEY (segment_id) REFERENCES segment(id)
);

CREATE TABLE advertiser (
    "day" text,
    id text,
    average_order_value text,
    average_page_views_per_visitor text,
    completed_view_rate text,
    completed_views text,
    conversion_attribution_percentage text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    order_value_attribution_percentage text,
    page_views text,
    percentage_of_conversions text,
    percentage_of_order_value text,
    raw_average_order_value text,
    raw_conversion_rate text,
    raw_conversions text,
    raw_existing_site_visitors text,
    raw_new_site_visitors text,
    raw_order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id)
);

CREATE TABLE advertiser_info (
    "day" text,
    advertiser_id text,
    contact_email text,
    contact_first_name text,
    contact_last_name text,
    contact_mobile_phone text,
    contact_office_phone text,
    create_time text,
    "name" text,
    time_zone text,
    PRIMARY KEY ("day", advertiser_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE analytics_by_country (
    _fivetran_id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_acquisition text,
    cost_per_visit text,
    cpa text,
    "day" text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    iso_code text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    return_on_ad_spend text,
    return_on_investment text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    unique_code text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE creative_info (
    "day" text,
    creative_id text,
    active text,
    click_url text,
    "name" text,
    PRIMARY KEY ("day", creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative_group(id)
);

CREATE TABLE ad_info (
    "day" text,
    creative_id text,
    active text,
    ad_code text,
    approved text,
    create_time text,
    height text,
    "name" text,
    "status" text,
    width text,
    PRIMARY KEY ("day", creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE analytics_by_state (
    _fivetran_id text,
    average_order_value text,
    code text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_acquisition text,
    cost_per_visit text,
    cpa text,
    "day" text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    parent_code text,
    return_on_ad_spend text,
    return_on_investment text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    unique_code text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE channel (
    "day" text,
    id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id)
);

CREATE TABLE analytics_by_city (
    _fivetran_id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_visit text,
    cpa text,
    "day" text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE marketing_objective (
    "day" text,
    id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id)
);

CREATE TABLE creative (
    "day" text,
    id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    "size" text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id)
);

CREATE TABLE channel_info (
    "day" text,
    channel_id text,
    "name" text,
    PRIMARY KEY ("day", channel_id),
    FOREIGN KEY (channel_id) REFERENCES channel(id)
);

CREATE TABLE analytics_by_network (
    _fivetran_id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    "day" text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE campaign_info (
    "day" text,
    campaign_id text,
    end_time text,
    flight_end_time text,
    flight_start_time text,
    "name" text,
    start_time text,
    "status" text,
    PRIMARY KEY ("day", campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign_group(id)
);

CREATE TABLE campaign_group (
    "day" text,
    id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id)
);

CREATE TABLE segment (
    "day" text,
    id text,
    "name" text,
    average_order_value text,
    conversion_rate text,
    conversions text,
    cost_per_acquisition text,
    cost_per_visit text,
    cpa text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    order_value text,
    return_on_ad_spend text,
    return_on_investment text,
    roas text,
    roi text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id, "name")
);

CREATE TABLE dma (
    "day" text,
    id text,
    average_order_value text,
    code text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    unique_code text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id)
);

CREATE TABLE publisher (
    "day" text,
    "name" text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", "name")
);

CREATE TABLE dma_info (
    "day" text,
    dma_id text,
    "name" text,
    PRIMARY KEY ("day", dma_id),
    FOREIGN KEY (dma_id) REFERENCES dma(id)
);

CREATE TABLE creative_group (
    "day" text,
    id text,
    average_order_value text,
    completed_view_rate text,
    completed_views text,
    conversion_rate text,
    conversions text,
    cost_per_completed_view text,
    cost_per_visit text,
    cpa text,
    existing_site_visitors text,
    existing_users_reached text,
    frequency text,
    impression_conversion_rate text,
    impression_visit_rate text,
    impressions text,
    multi_touch_impressions text,
    multi_touch_spend text,
    "name" text,
    new_site_visitors text,
    new_users_reached text,
    order_value text,
    roas text,
    roi text,
    site_visitors text,
    spend text,
    tv_commercials_aired text,
    tv_spend text,
    user_conversion_rate text,
    user_visit_rate text,
    users_reached text,
    viewable_impression_rate text,
    viewable_impressions text,
    visit_conversion_rate text,
    visit_rate text,
    visits text,
    PRIMARY KEY ("day", id)
);

CREATE TABLE marketing_objective_info (
    "day" text,
    marketing_id text,
    "name" text,
    PRIMARY KEY ("day", marketing_id),
    FOREIGN KEY (marketing_id) REFERENCES marketing_objective(id)
);

CREATE TABLE conversion (
    order_id text,
    publisher text,
    conversion_point text,
    conversion_time text,
    currency text,
    event_time text,
    last_touch text,
    order_amount text,
    raw_domain text,
    sub_domain text,
    PRIMARY KEY (order_id, publisher),
    FOREIGN KEY (publisher) REFERENCES publisher("name")
);
