CREATE TABLE vehicle_component_set_controller_item (
    vehicle_component_id text,
    vehicle_component_set_controller_id text,
    PRIMARY KEY (vehicle_component_id, vehicle_component_set_controller_id),
    FOREIGN KEY (vehicle_component_id) REFERENCES vehicle_component_controller(id),
    FOREIGN KEY (vehicle_component_set_controller_id) REFERENCES vehicle_component_set_controller(id)
);

CREATE TABLE vehicle_component_set_controller (
    id text,
    vehicle_component_set_type_id text,
    archived text,
    archived_2 text,
    code text,
    component_fixed_from text,
    ends text,
    "name" text,
    operation_account_id text,
    short_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (vehicle_component_set_type_id) REFERENCES arat_ref_vehicle_controller(vehicle_component_set_type_id)
);

CREATE TABLE access_instrument_controller_file_list (
    "index" text,
    access_instrument_controller_id text,
    file_group_id text,
    "name" text,
    note text,
    prefix text,
    "size" text,
    "type" text,
    uploaded text,
    uploaded_by text,
    version text,
    PRIMARY KEY ("index", access_instrument_controller_id),
    FOREIGN KEY (access_instrument_controller_id) REFERENCES access_instrument_controller(id)
);

CREATE TABLE access_instrument_controller_condition_template_config (
    id text,
    access_instrument_controller_condition_id text,
    access_instrument_controller_id text,
    example_value text,
    field_type text,
    help text,
    label text,
    list text,
    max text,
    min text,
    numeric_value text,
    uom text,
    "value" text,
    PRIMARY KEY (id, access_instrument_controller_condition_id, access_instrument_controller_id),
    FOREIGN KEY (access_instrument_controller_condition_id) REFERENCES access_instrument_controller_condition(id),
    FOREIGN KEY (access_instrument_controller_id) REFERENCES access_instrument_controller_condition(access_instrument_controller_id)
);

CREATE TABLE access_instrument_controller_condition (
    id text,
    access_instrument_controller_id text,
    account_name text,
    asset_detail_id text,
    category text,
    code text,
    concerns text,
    condition_group_id text,
    condition_header text,
    groups text,
    is_auto_applied text,
    "name" text,
    partner_account_id text,
    permit_partner_condition_id text,
    permit_standard_condition_id text,
    reason text,
    reasons text,
    risk_mitigation jsonb,
    segment_ids jsonb,
    "status" text,
    template text,
    PRIMARY KEY (id, access_instrument_controller_id),
    FOREIGN KEY (access_instrument_controller_id) REFERENCES access_instrument_controller(id)
);

CREATE TABLE access_instrument_controller (
    id text,
    actual_expiry_date timestamp,
    approval text,
    carriage text,
    com_law_ref_num text,
    created timestamp,
    created_by text,
    deactivated text,
    description text,
    exemption_types jsonb,
    expiry_date timestamp,
    guide text,
    guide_alert text,
    ip text,
    modified timestamp,
    modified_by text,
    modified_offline timestamp,
    "name" text,
    network_tag text,
    notes text,
    operation_account_id text,
    policy_type text,
    revokes text,
    start_date timestamp,
    "status" text,
    transitional text,
    PRIMARY KEY (id)
);

CREATE TABLE vehicle_combination_type_controller (
    id text,
    archived text,
    body_types jsonb,
    description text,
    hauling_units jsonb,
    "name" text,
    operation_account_id text,
    orders text,
    towed_units jsonb,
    PRIMARY KEY (id)
);

CREATE TABLE access_network_category_mapping_controller_map_state_map_view_layer (
    "index" text,
    access_network_category_mapping_controller_id text,
    filter_condition jsonb,
    is_etl text,
    layer_id text,
    visibility text,
    PRIMARY KEY ("index", access_network_category_mapping_controller_id),
    FOREIGN KEY (access_network_category_mapping_controller_id) REFERENCES access_network_category_mapping_controller(id)
);

CREATE TABLE access_network_category_mapping_controller_network (
    network_id text,
    access_network_category_mapping_controller_id text,
    created timestamp,
    created_by text,
    created_partner_account_id text,
    date_updated text,
    description text,
    guide_alert text,
    ip text,
    modified timestamp,
    modified_by text,
    modified_offline timestamp,
    network_display_name text,
    network_name text,
    network_type text,
    non_osm_network_flag text,
    related_access_product_document_id text,
    related_network_id text,
    rich_description text,
    "status" text,
    w_kid text,
    PRIMARY KEY (network_id, access_network_category_mapping_controller_id),
    FOREIGN KEY (access_network_category_mapping_controller_id) REFERENCES access_network_category_mapping_controller(id)
);

CREATE TABLE access_network_category_mapping_controller_vehicle_component_detail_product (
    id text,
    access_network_category_mapping_controller_access_network_category_id text,
    access_network_category_mapping_controller_vehicle_component_detail_index text,
    generic text,
    make text,
    model text,
    note text,
    pbs_approval_vehicle_mapping_ids jsonb,
    PRIMARY KEY (id, access_network_category_mapping_controller_access_network_category_id, access_network_category_mapping_controller_vehicle_component_detail_index),
    FOREIGN KEY (access_network_category_mapping_controller_access_network_category_id) REFERENCES access_network_category_mapping_controller_vehicle_component_detail(access_network_category_mapping_controller_access_network_category_id),
    FOREIGN KEY (access_network_category_mapping_controller_vehicle_component_detail_index) REFERENCES access_network_category_mapping_controller_vehicle_component_detail("index")
);

CREATE TABLE access_network_category_mapping_controller_vehicle_component_detail_param_engine_product (
    id text,
    access_network_category_mapping_controller_access_network_category_id text,
    access_network_category_mapping_controller_vehicle_component_detail_index text,
    engine_power text,
    engine_power_2 text,
    engine_torque text,
    engine_torque_2 text,
    PRIMARY KEY (id, access_network_category_mapping_controller_access_network_category_id, access_network_category_mapping_controller_vehicle_component_detail_index),
    FOREIGN KEY (access_network_category_mapping_controller_access_network_category_id) REFERENCES access_network_category_mapping_controller_vehicle_component_detail(access_network_category_mapping_controller_access_network_category_id),
    FOREIGN KEY (access_network_category_mapping_controller_vehicle_component_detail_index) REFERENCES access_network_category_mapping_controller_vehicle_component_detail("index")
);

CREATE TABLE access_network_category_mapping_controller_vehicle_component_detail (
    "index" text,
    access_network_category_mapping_controller_access_network_category_id text,
    access_network_category_mapping_controller_id text,
    certification_method jsonb,
    drive_ratios text,
    gearbox_ratios text,
    param_brake jsonb,
    param_com_or_elig jsonb,
    param_coupling jsonb,
    param_driveline_auto jsonb,
    param_driveline_manual jsonb,
    param_driveline_peak_engine_torque jsonb,
    param_mass jsonb,
    param_other jsonb,
    param_steer_axle_mass jsonb,
    param_suspension jsonb,
    param_tare jsonb,
    param_tyre jsonb,
    param_wheels_axles jsonb,
    PRIMARY KEY ("index", access_network_category_mapping_controller_access_network_category_id, access_network_category_mapping_controller_id),
    FOREIGN KEY (access_network_category_mapping_controller_access_network_category_id) REFERENCES access_network_category_mapping_controller_access_network_category(id),
    FOREIGN KEY (access_network_category_mapping_controller_id) REFERENCES access_network_category_mapping_controller_access_network_category(access_network_category_mapping_controller_id)
);

CREATE TABLE access_network_category_mapping_controller_customer_vehicle (
    id text,
    access_network_category_mapping_controller_access_network_category_id text,
    access_network_category_mapping_controller_id text,
    a_id_maint text,
    a_id_mass text,
    a_label_maint text,
    a_label_mass text,
    a_vm_id_maint text,
    a_vm_id_mass text,
    amend text,
    axle_detail_locked text,
    code text,
    description text,
    ext_vehicle_component_id text,
    gross_combination_mass text,
    gross_trailer_mass text,
    gross_vehicle_mass text,
    idx text,
    inspected text,
    last_refreshed text,
    make text,
    model text,
    "name" text,
    registered_owner text,
    registration text,
    registration_end_date timestamp,
    registration_start_date timestamp,
    registration_status text,
    "state" text,
    "status" text,
    vehicle_component_id text,
    vehicle_id text,
    vin text,
    PRIMARY KEY (id, access_network_category_mapping_controller_access_network_category_id, access_network_category_mapping_controller_id),
    FOREIGN KEY (access_network_category_mapping_controller_access_network_category_id) REFERENCES access_network_category_mapping_controller_access_network_category(id),
    FOREIGN KEY (access_network_category_mapping_controller_id) REFERENCES access_network_category_mapping_controller_access_network_category(access_network_category_mapping_controller_id)
);

CREATE TABLE access_network_category_mapping_controller_mass_limit_axle_group_mass_limit (
    "index" text,
    access_network_category_mapping_controller_access_network_category_id text,
    access_network_category_mapping_controller_mass_limit_index text,
    cml text,
    foot_note text,
    from_axle_group text,
    gml text,
    hml text,
    "name" text,
    qml text,
    to_axle_group text,
    PRIMARY KEY ("index", access_network_category_mapping_controller_access_network_category_id, access_network_category_mapping_controller_mass_limit_index),
    FOREIGN KEY (access_network_category_mapping_controller_access_network_category_id) REFERENCES access_network_category_mapping_controller_mass_limit(access_network_category_mapping_controller_access_network_category_id),
    FOREIGN KEY (access_network_category_mapping_controller_mass_limit_index) REFERENCES access_network_category_mapping_controller_mass_limit("index")
);

CREATE TABLE access_network_category_mapping_controller_mass_limit_spacing_mass_limit (
    "index" text,
    access_network_category_mapping_controller_access_network_category_id text,
    access_network_category_mapping_controller_mass_limit_index text,
    cml text,
    foot_note text,
    from_axle_group text,
    gml text,
    hml text,
    "name" text,
    qml text,
    to_axle_group text,
    PRIMARY KEY ("index", access_network_category_mapping_controller_access_network_category_id, access_network_category_mapping_controller_mass_limit_index),
    FOREIGN KEY (access_network_category_mapping_controller_access_network_category_id) REFERENCES access_network_category_mapping_controller_mass_limit(access_network_category_mapping_controller_access_network_category_id),
    FOREIGN KEY (access_network_category_mapping_controller_mass_limit_index) REFERENCES access_network_category_mapping_controller_mass_limit("index")
);

CREATE TABLE access_network_category_mapping_controller_mass_limit (
    "index" text,
    access_network_category_mapping_controller_access_network_category_id text,
    config_mass_limits_cml text,
    config_mass_limits_foot_note text,
    config_mass_limits_from_axle_group text,
    config_mass_limits_gml text,
    config_mass_limits_hml text,
    config_mass_limits_name text,
    config_mass_limits_qml text,
    config_mass_limits_to_axle_group text,
    "name" text,
    PRIMARY KEY ("index", access_network_category_mapping_controller_access_network_category_id),
    FOREIGN KEY (access_network_category_mapping_controller_access_network_category_id) REFERENCES access_network_category_mapping_controller_access_network_category(id)
);

CREATE TABLE access_network_category_mapping_controller_access_network_category (
    id text,
    access_network_category_mapping_controller_id text,
    adf text,
    alert text,
    archived text,
    code text,
    configuration_compliances jsonb,
    configuration_eligibilities jsonb,
    configuration_forward_projection text,
    configuration_has_euro_vi_mass_transfer_allowance text,
    configuration_height text,
    configuration_height_unladen text,
    configuration_id text,
    configuration_length text,
    configuration_length_unladen text,
    configuration_rear_overhang text,
    configuration_safer_freight_vehicles text,
    configuration_tare_mass text,
    configuration_total_mass text,
    configuration_wheelbase text,
    configuration_width text,
    configuration_width_unladen text,
    description text,
    filter_fields jsonb,
    filter_keywords jsonb,
    "name" text,
    operation_account_id text,
    parent text,
    states jsonb,
    vehicle_component_set_archived text,
    vehicle_component_set_archived_2 text,
    vehicle_component_set_code text,
    vehicle_component_set_component_fixed_from text,
    vehicle_component_set_ends text,
    vehicle_component_set_id text,
    vehicle_component_set_name text,
    vehicle_component_set_operation_account_id text,
    vehicle_component_set_short_name text,
    vehicle_component_set_type_application_type jsonb,
    vehicle_component_set_type_archived text,
    vehicle_component_set_type_archived_2 text,
    vehicle_component_set_type_body_type text,
    vehicle_component_set_type_code text,
    vehicle_component_set_type_example text,
    vehicle_component_set_type_hierarchy text,
    vehicle_component_set_type_id text,
    vehicle_component_set_type_is_pbs text,
    vehicle_component_set_type_name text,
    vehicle_component_set_type_operation_account_id text,
    vehicle_component_set_type_order_num text,
    vehicle_component_set_type_parent text,
    vehicle_component_set_type_short_name text,
    PRIMARY KEY (id, access_network_category_mapping_controller_id),
    FOREIGN KEY (access_network_category_mapping_controller_id) REFERENCES access_network_category_mapping_controller(id)
);

CREATE TABLE access_network_category_mapping_controller (
    id text,
    vehicle_component_id text,
    created timestamp,
    created_by text,
    draft text,
    ip text,
    map_state_basemap text,
    map_state_network_layers jsonb,
    map_state_r_avoid_ferries text,
    map_state_r_avoid_intelligent_routing text,
    map_state_r_avoid_limited_access_road text,
    map_state_r_avoid_private_road text,
    map_state_r_avoid_toll_road text,
    map_state_r_avoid_unpaved_road text,
    map_state_r_driving text,
    map_state_r_oneway text,
    map_state_r_prefer_b_double text,
    map_state_r_through_traffic_prohibited text,
    map_state_r_turns text,
    modified timestamp,
    modified_by text,
    modified_offline timestamp,
    order_num text,
    PRIMARY KEY (id),
    FOREIGN KEY (vehicle_component_id) REFERENCES vehicle_component_controller(id)
);

CREATE TABLE registration_share_vehicle_controller (
    id text,
    created timestamp,
    created_by text,
    customer_account_id text,
    description text,
    ip text,
    modified timestamp,
    modified_by text,
    modified_offline timestamp,
    "name" text,
    registration_share_id text,
    vehicle_id text,
    PRIMARY KEY (id)
);

CREATE TABLE registration_account_mapping_controller (
    id text,
    created timestamp,
    created_by text,
    customer_account_id text,
    entity_type_basic text,
    garage_address_postcode text,
    individual_date_of_birth text,
    ip text,
    modified timestamp,
    modified_by text,
    modified_offline timestamp,
    organisation_abn text,
    organisation_acn text,
    registration_id text,
    registration_individual_id text,
    registration_jurisdiction text,
    registration_organisation_id text,
    registration_plate_number text,
    PRIMARY KEY (id)
);

CREATE TABLE vehicle_component_type_controller (
    id text,
    archived text,
    code text,
    coupling_front text,
    coupling_rear text,
    example text,
    hierarchy text,
    is_modifiable text,
    "name" text,
    operation_account_id text,
    order_num text,
    osom text,
    parent text,
    short_name text,
    PRIMARY KEY (id)
);

CREATE TABLE vehicle_component_controller_spec_axle (
    "index" text,
    vehicle_component_controller_id text,
    vehicle_component_controller_spec_axle_group_index text,
    drive text,
    liftable text,
    liftable_optional text,
    spacing text,
    steer_optional text,
    tyre text,
    PRIMARY KEY ("index", vehicle_component_controller_id, vehicle_component_controller_spec_axle_group_index),
    FOREIGN KEY (vehicle_component_controller_id) REFERENCES vehicle_component_controller_spec_axle_group(vehicle_component_controller_id),
    FOREIGN KEY (vehicle_component_controller_spec_axle_group_index) REFERENCES vehicle_component_controller_spec_axle_group("index")
);

CREATE TABLE vehicle_component_controller_spec_axle_group (
    "index" text,
    vehicle_component_controller_id text,
    axle_mass text,
    axle_mass_unladen text,
    axle_spread text,
    certified_rf_suspension text,
    contact_width text,
    dual_tyre_spacing text,
    groups text,
    hydro_pneumatic text,
    load_sharing text,
    max_axle_mass text,
    max_suspension_axle_mass text,
    nsw_tonne_steer text,
    steer text,
    track_width text,
    tractive_effort_dist text,
    tyre_size text,
    tyre_size_txt text,
    PRIMARY KEY ("index", vehicle_component_controller_id),
    FOREIGN KEY (vehicle_component_controller_id) REFERENCES vehicle_component_controller(id)
);

CREATE TABLE vehicle_component_controller (
    id text,
    vehicle_component_type_id text,
    archived text,
    axle_group text,
    axles text,
    code text,
    component_type text,
    ends text,
    image_offset text,
    image_rear_offset text,
    motorised text,
    "name" text,
    operation_account_id text,
    short_name text,
    spec_body_type text,
    spec_can_reduce_total_mass text,
    spec_drawbar_length text,
    spec_fifth_wheel_offset text,
    spec_forward_overhang text,
    spec_forward_overhang_radius text,
    spec_gross_combination_mass text,
    spec_height_drawbar text,
    spec_height_front text,
    spec_height_front_floor text,
    spec_height_rear text,
    spec_height_rear_floor text,
    spec_length text,
    spec_loads jsonb,
    spec_name text,
    spec_number_of_deck text,
    spec_rear_overhang text,
    spec_s_dimension text,
    spec_tare_mass text,
    spec_total_mass text,
    spec_tow_rear_overhang text,
    spec_volumetric text,
    spec_wheelbase text,
    spec_width text,
    "start" text,
    PRIMARY KEY (id),
    FOREIGN KEY (vehicle_component_type_id) REFERENCES vehicle_component_type_controller(id)
);

CREATE TABLE accreditation_activity_template_controller_checklist (
    "index" text,
    accreditation_activity_template_controller_id text,
    description text,
    label text,
    "name" text,
    options jsonb,
    selected_option text,
    sub_label text,
    PRIMARY KEY ("index", accreditation_activity_template_controller_id),
    FOREIGN KEY (accreditation_activity_template_controller_id) REFERENCES accreditation_activity_template_controller(id)
);

CREATE TABLE accreditation_activity_template_controller_outcome_config (
    "index" text,
    accreditation_activity_template_controller_id text,
    available_fields jsonb,
    description text,
    event text,
    label text,
    outcome text,
    "type" text,
    PRIMARY KEY ("index", accreditation_activity_template_controller_id),
    FOREIGN KEY (accreditation_activity_template_controller_id) REFERENCES accreditation_activity_template_controller(id)
);

CREATE TABLE accreditation_activity_template_controller (
    id text,
    activity_fields jsonb,
    activity_state text,
    activity_type text,
    application_type text,
    archived text,
    created timestamp,
    created_by text,
    ip text,
    "key" text,
    model_type text,
    modified timestamp,
    modified_by text,
    modified_offline timestamp,
    "name" text,
    notes text,
    notes_modifiable text,
    operations_account_id text,
    previous_workflow_state text,
    request_from text,
    request_to text,
    "status" text,
    subject text,
    subject_modifiable text,
    system_sub_type text,
    system_type text,
    "type" text,
    workflow_state text,
    PRIMARY KEY (id)
);

CREATE TABLE vehicle_component_connection_controller (
    id text,
    vehicle_component_type_id text,
    archived text,
    can_attach text,
    operation_account_id text,
    vehicle_component_type_attach_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (vehicle_component_type_id) REFERENCES vehicle_component_type_controller(id)
);

CREATE TABLE arat_ref_vehicle_controller_file_list (
    "index" text,
    arat_ref_vehicle_controller_id text,
    file_group_id text,
    "name" text,
    note text,
    original_file_name text,
    prefix text,
    "size" text,
    "type" text,
    uploaded text,
    uploaded_by text,
    version text,
    PRIMARY KEY ("index", arat_ref_vehicle_controller_id),
    FOREIGN KEY (arat_ref_vehicle_controller_id) REFERENCES arat_ref_vehicle_controller(id)
);

CREATE TABLE arat_ref_vehicle_controller (
    id text,
    network_id text,
    created timestamp,
    created_by text,
    design_vehicle text,
    ip text,
    load_parameter_combine_load text,
    load_parameter_concentrated_load_m text,
    load_parameter_concentrated_load_v text,
    load_parameter_contact_width text,
    load_parameter_lane_load_udl text,
    load_parameter_loading text,
    locked_vehicle text,
    modified timestamp,
    modified_by text,
    modified_offline timestamp,
    "name" text,
    operation_account_id text,
    partner_account_id text,
    ratio_parameter_negative_moment_ratio text,
    ratio_parameter_overall_ratio text,
    ratio_parameter_pier_reaction_ratio text,
    ratio_parameter_positive_moment_ratio text,
    ratio_parameter_shear_ratio text,
    use_load_parameter text,
    vehicle_component_set_type_id text,
    vehicle_description text,
    vehicle_parameters_d_la text,
    vehicle_parameters_l_lf text,
    vehicle_parameters_lane_type text,
    vehicle_parameters_note text,
    PRIMARY KEY (id),
    FOREIGN KEY (network_id) REFERENCES access_network_category_mapping_controller_network(network_id)
);
