CREATE TABLE agent_soft_phone_web_rtc_url (
    "index" text,
    agent_id text,
    url_name text,
    weight text,
    PRIMARY KEY ("index", agent_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id)
);

CREATE TABLE agent (
    id text,
    team_id text,
    address_1 text,
    address_2 text,
    agent_chat_threshold text,
    agent_contact_auto_focus text,
    agent_cxa_client_version text,
    agent_cxa_release_previous text,
    agent_delivery_mode text,
    agent_email_threshold text,
    agent_integration text,
    agent_max_version text,
    agent_phone_timeout text,
    agent_phone_timeout_seconds text,
    agent_request_contact text,
    agent_total_contact_count text,
    agent_voice_threshold text,
    agent_work_item_threshold text,
    api_key text,
    at_home text,
    chat_refusal_timeout text,
    chat_threshold text,
    city text,
    combined_user_name_domain text,
    contact_auto_focus text,
    country text,
    country_name text,
    create_date text,
    crm_user_name text,
    customer_card text,
    default_dialing_pattern text,
    default_dialing_pattern_name text,
    delivery_mode text,
    digital_refusal_timeout text,
    digital_threshold text,
    email_address text,
    email_refusal_timeout text,
    email_threshold text,
    employment_type text,
    employment_type_name text,
    federated_id text,
    first_name text,
    hire_date text,
    hiring_source text,
    hourly_cost text,
    inactive_date text,
    internal_id text,
    is_active text,
    is_billable text,
    is_open_id_profile_complete text,
    is_supervisor text,
    is_what_if_agent text,
    issuer text,
    last_login text,
    last_name text,
    last_updated timestamp,
    location text,
    locked text,
    login_authenticator_id text,
    max_concurrent_chats text,
    max_email_auto_parking_limit text,
    max_preview text,
    middle_name text,
    no_fixed_address text,
    notes text,
    nt_login_name text,
    phone_refusal_timeout text,
    profile_id text,
    profile_name text,
    recording_numbers jsonb,
    referral text,
    rehire_status text,
    report_to_id text,
    report_to_name text,
    request_contact text,
    row_number text,
    schedule_notification text,
    send_email_notifications text,
    sip_user text,
    sms_refusal_timeout text,
    sms_threshold text,
    "state" text,
    state_code text,
    subject text,
    system_domain text,
    system_user text,
    telephone_1 text,
    telephone_2 text,
    termination_date text,
    time_display_format text,
    time_zone text,
    time_zone_offset text,
    total_contact_count text,
    use_agent_time_zone text,
    use_team_chat_threshold text,
    use_team_contact_auto_focus text,
    use_team_delivery_mode_settings text,
    use_team_digital_threshold text,
    use_team_email_auto_parking_limit text,
    use_team_email_threshold text,
    use_team_max_concurrent_chats text,
    use_team_request_contact text,
    use_team_sms_threshold text,
    use_team_voice_threshold text,
    use_team_work_item_threshold text,
    user_id text,
    user_name text,
    user_name_domain text,
    user_type text,
    voice_threshold text,
    voicemail_refusal_timeout text,
    work_item_refusal_timeout text,
    work_item_threshold text,
    zip_code text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE agent_extend (
    id text,
    report_to text,
    address_pidflo jsonb,
    agent_dialing_pattern_id text,
    agent_phone_home text,
    agent_phone_other text,
    at_home_worker text,
    auto_attendant_access_type text,
    display_24_hour text,
    email text,
    external_identity text,
    group_ids text,
    hiring_source_desc text,
    hiring_source_id text,
    integrated_soft_phone_web_rtc_urls text,
    is_address_911_validated text,
    location_name text,
    location_no text,
    max_email_inbox_count text,
    mch_channel_lock text,
    mch_chat text,
    mch_contact_auto_focus text,
    mch_email text,
    mch_request_contact text,
    mch_sms text,
    mch_social text,
    mch_voice text,
    mch_work_item text,
    no_fixed_address text,
    phone text,
    phone_call_refusal_timeout text,
    routing_attribute_info text,
    sch_request_contact text,
    secondary_id text,
    security_profile_id text,
    shift_time text,
    sip_user_id text,
    skill_info text,
    system_user_name text,
    team_no text,
    termination_date text,
    use_default_request_contact text,
    use_team_max_email_inbox_count text,
    use_team_mch_channel_lock text,
    use_team_mch_chat text,
    use_team_mch_contact_auto_focus text,
    use_team_mch_digital text,
    use_team_mch_email text,
    use_team_mch_request_contact text,
    use_team_mch_sms text,
    use_team_mch_work_item text,
    wfm_notification_enabled text,
    wfm_notification_interval text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES agent(id),
    FOREIGN KEY (report_to) REFERENCES agent(id)
);

CREATE TABLE interaction_analytics_segment_enlighten_metrics (
    "index" text,
    interaction_id text,
    behavior_name text,
    enlighten_package_models jsonb,
    index_score text,
    raw_score text,
    PRIMARY KEY ("index", interaction_id),
    FOREIGN KEY (interaction_id) REFERENCES interaction_analytics_segment(id)
);

CREATE TABLE interaction_analytics_segment_channel (
    "index" text,
    interaction_id text,
    begin_sentiment jsonb,
    end_sentiment jsonb,
    frustration jsonb,
    "name" text,
    sentiment jsonb,
    PRIMARY KEY ("index", interaction_id),
    FOREIGN KEY (interaction_id) REFERENCES interaction_analytics_segment(id)
);

CREATE TABLE interaction_analytics_segment_entities (
    "index" text,
    interaction_id text,
    channel_name text,
    custom text,
    display_text text,
    sentiment_value text,
    "type" text,
    PRIMARY KEY ("index", interaction_id),
    FOREIGN KEY (interaction_id) REFERENCES interaction_analytics_segment(id)
);

CREATE TABLE interaction_analytics_segment (
    id text,
    tenant_id text,
    acd_contact_id text,
    category_matches jsonb,
    contact_end_reason text,
    contact_no jsonb,
    disposition_code text,
    end_time timestamp,
    enlighten_sentiment_index_score text,
    enlighten_sentiment_raw_score text,
    first_annotated_at timestamp,
    hold_count text,
    hold_seconds text,
    lang text,
    media_type text,
    non_hold_notable_silence_seconds text,
    notable_silence_percentage text,
    notable_silence_seconds text,
    published_at timestamp,
    resolved text,
    segment_id text,
    segment_summary_action jsonb,
    segment_summary_outcome jsonb,
    segment_summary_primary_intent_category text,
    segment_summary_primary_intent_name text,
    segment_summary_primary_intent_topic text,
    start_time timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (tenant_id) REFERENCES skill(id)
);

CREATE TABLE contact_tag (
    contact_id text,
    id text,
    "name" text,
    PRIMARY KEY (contact_id, id)
);

CREATE TABLE contact (
    id text,
    agent_id text,
    campaign_id text,
    master_contact_id text,
    skill_id text,
    team_id text,
    abandon_seconds text,
    abandoned text,
    acw_seconds text,
    agent_seconds text,
    analytics_processed_date text,
    callback_time text,
    conference_seconds text,
    date_a_c_w_warehoused text,
    date_contact_warehoused text,
    digital_contact_state_id text,
    digital_contact_state_name text,
    disposition_notes text,
    end_reason text,
    first_name text,
    from_address text,
    high_proficiency text,
    hold_count text,
    hold_seconds text,
    in_queue_seconds text,
    is_active text,
    is_analytics_processed text,
    is_logged text,
    is_outbound text,
    is_refused text,
    is_short_abandon text,
    is_takeover text,
    is_warehoused text,
    last_name text,
    last_update_time text,
    low_proficiency text,
    media_sub_type_id text,
    media_sub_type_name text,
    media_type_id text,
    media_type_name text,
    point_of_contact_id text,
    point_of_contact_name text,
    post_queue_seconds text,
    pre_queue_seconds text,
    primary_disposition_id text,
    refuse_reason text,
    refuse_time text,
    release_seconds text,
    routing_attribute text,
    routing_time text,
    secondary_disposition_id text,
    service_level_flag text,
    start_date text,
    state_id text,
    state_name text,
    to_address text,
    total_duration_seconds text,
    transfer_indicator_id text,
    transfer_indicator_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (master_contact_id) REFERENCES contact(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE skill_disposition (
    disposition_id text,
    skill_id text,
    is_preview_disposition text,
    priority text,
    PRIMARY KEY (disposition_id, skill_id),
    FOREIGN KEY (disposition_id) REFERENCES disposition(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE skill (
    id text,
    campaign_id text,
    acceleration text,
    acw_post_timeout_state_id text,
    acw_post_timeout_state_name text,
    acw_type_id text,
    agent_first_response_time text,
    agent_follow_on_response_time text,
    agent_response_enabled text,
    agent_rest_time text,
    agent_typing_indicator text,
    agentless text,
    agentless_ports text,
    allow_secondary_disposition text,
    call_suppression_script_id text,
    caller_id_override text,
    chat_warning_threshold text,
    count_reskill_hours text,
    count_short_abandons text,
    cradle_to_grave text,
    customer_idle_time text,
    customer_response_enabled text,
    deliver_multiple_numbers_serially text,
    display_thankyou text,
    email_bcc_address text,
    email_from_address text,
    email_from_editable text,
    email_parking text,
    enable_short_abandon text,
    equity_level text,
    evaluation_criteria text,
    fallback_time text,
    focus_lock text,
    focus_metric text,
    initial_priority text,
    interruptible text,
    is_active text,
    is_outbound text,
    is_running text,
    is_sub_skill text,
    make_transcript_available text,
    max_priority text,
    max_seconds_acw text,
    media_type_id text,
    media_type_name text,
    message_template_id text,
    min_wfi_agents text,
    min_wfi_available_agents text,
    min_working_time text,
    "name" text,
    notes text,
    outbound_strategy text,
    outbound_telecom_route_id text,
    patron_typing_preview text,
    pop_thank_you text,
    pop_thank_you_url text,
    present_accept_reject text,
    priority_blending text,
    priority_interrupt text,
    require_disposition text,
    require_manual_accept text,
    reskill_hours text,
    reskill_hours_name text,
    routing_queue_id text,
    screen_pop_detail text,
    screen_pop_trigger_event text,
    script_id text,
    script_name text,
    service_level_goal text,
    service_level_threshold text,
    short_abandon_threshold text,
    sms_transport_code text,
    sms_transport_code_id text,
    state_id_acw text,
    state_name_acw text,
    tenant_id text,
    thank_you_link text,
    time_extension_enabled text,
    transcript_from_address text,
    use_custom_screen_pops text,
    use_screen_pops text,
    work_item_queue_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE groups (
    id text,
    is_active text,
    last_updated text,
    "name" text,
    notes text,
    PRIMARY KEY (id)
);

CREATE TABLE team (
    id text,
    analytics_enabled text,
    chat_threshold text,
    contact_auto_focus text,
    cxone_customer_authentication_enabled text,
    delivery_mode text,
    description text,
    digital_threshold text,
    email_threshold text,
    in_view_chat_enabled text,
    in_view_enabled text,
    in_view_gamification_enabled text,
    in_view_l_m_s_enabled text,
    in_view_wallboard_enabled text,
    is_active text,
    last_update_time timestamp,
    lead_id text,
    max_concurrent_chats text,
    max_email_auto_parking_limit text,
    "name" text,
    nice_analytics_enabled text,
    nice_audio_recording_enabled text,
    nice_coaching_enabled text,
    nice_desktop_analytics_enabled text,
    nice_lesson_management_enabled text,
    nice_performance_management_enabled text,
    nice_qm_enabled text,
    nice_quality_optimization_enabled text,
    nice_screen_recording_enabled text,
    nice_shift_bidding_enabled text,
    nice_speech_analytics_enabled text,
    nice_strategic_planner_enabled text,
    nice_survey_customer_enabled text,
    nice_wfm_enabled text,
    nice_wfo_advanced_enabled text,
    nice_wfo_essentials_enabled text,
    notes text,
    qm_2_enabled text,
    request_contact text,
    sms_threshold text,
    social_threshold text,
    total_contact_count text,
    uuid text,
    voice_threshold text,
    wfm_2_enabled text,
    wfo_enabled text,
    work_item_threshold text,
    PRIMARY KEY (id)
);

CREATE TABLE group_agent (
    agent_id text,
    group_id text,
    PRIMARY KEY (agent_id, group_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE campaign (
    id text,
    description text,
    is_active text,
    last_update_time text,
    "name" text,
    notes text,
    PRIMARY KEY (id)
);

CREATE TABLE agent_skill (
    agent_id text,
    skill_id text,
    campaign_id text,
    team_id text,
    last_poll_time text,
    last_update_time text,
    notes text,
    PRIMARY KEY (agent_id, skill_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE wfm_data_performance (
    end_date text,
    start_date text,
    agent_id text,
    skill_id text,
    business_unit_id text,
    business_unit_name text,
    half_hour text,
    total_acw_time text,
    total_handled text,
    total_handled_time text,
    PRIMARY KEY (end_date, start_date, agent_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE wfm_data_scorecard (
    end_date text,
    start_date text,
    agent_id text,
    skill_id text,
    abandoned_calls text,
    actual_calls text,
    acw_time text,
    agent_session_id text,
    agent_state_id text,
    aux_in_time text,
    aux_out_time text,
    aux_time text,
    business_unit_id text,
    business_unit_name text,
    duration text,
    hold_time text,
    idle_time text,
    out_state_description text,
    out_state_id text,
    state_index text,
    talk_time text,
    total_calls text,
    total_time text,
    PRIMARY KEY (end_date, start_date, agent_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE agent_performance (
    end_date text,
    start_date text,
    agent_id text,
    team_id text,
    acw_time text,
    agent_offered text,
    available_time text,
    consult_time text,
    inbound_avg_talk_time text,
    inbound_handled text,
    inbound_talk_time text,
    inbound_time text,
    login_time text,
    occupancy text,
    outbound_avg_talk_time text,
    outbound_handled text,
    outbound_talk_time text,
    outbound_time text,
    percent_refused text,
    refused text,
    total_avg_handle_time text,
    total_avg_talk_time text,
    total_handled text,
    total_talk_time text,
    unavailable_time text,
    working_rate text,
    PRIMARY KEY (end_date, start_date, agent_id, team_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE wfm_data_adherence (
    end_date text,
    start_date text,
    agent_id text,
    skill_id text,
    agent_session_id text,
    agent_state_id text,
    business_unit_id text,
    business_unit_name text,
    duration text,
    out_state_description text,
    out_state_id text,
    state_index text,
    PRIMARY KEY (end_date, start_date, agent_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE skill_summary (
    business_unit_id text,
    end_date text,
    start_date text,
    campaign_id text,
    skill_id text,
    abandon_count text,
    abandon_rate text,
    agents_acw text,
    agents_available text,
    agents_idle text,
    agents_logged_in text,
    agents_unavailable text,
    agents_working text,
    average_handle_time text,
    average_inqueue_time text,
    average_speed_to_answer text,
    average_talk_time text,
    average_wrap_time text,
    business_unit_name text,
    connects text,
    connects_aht text,
    contacts_active text,
    contacts_handled text,
    contacts_offered text,
    contacts_out_of_sla text,
    contacts_queued text,
    contacts_within_sla text,
    dials text,
    hold_time text,
    is_outbound text,
    longest_queue_dur text,
    media_type_id text,
    media_type_name text,
    queue_count text,
    right_party_connects text,
    right_party_connects_aht text,
    service_level text,
    service_level_goal text,
    service_level_threshold text,
    total_contact_time text,
    PRIMARY KEY (business_unit_id, end_date, start_date, campaign_id, skill_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE disposition (
    id text,
    classification_id text,
    is_preview_disposition text,
    last_updated timestamp,
    "name" text,
    notes text,
    system_outcome text,
    PRIMARY KEY (id)
);

CREATE TABLE sla_summary (
    business_unit_id text,
    end_date text,
    start_date text,
    skill_id text,
    contacts_out_of_sla text,
    contacts_within_sla text,
    service_level text,
    total_contacts text,
    PRIMARY KEY (business_unit_id, end_date, start_date, skill_id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE skill_call_data (
    end_date text,
    start_date text,
    skill_id text,
    abandoned_contacts text,
    abandoned_time text,
    answered_contacts text,
    answered_service_level_contacts text,
    average_abandoned_time text,
    average_acd_time text,
    average_handle_time text,
    average_speed_answer_time text,
    business_unit_id text,
    business_unit_name text,
    entered_queue_contacts text,
    offered_contacts text,
    PRIMARY KEY (end_date, start_date, skill_id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE contact_state_history (
    start_date text,
    state_index text,
    contact_id text,
    agent_id text,
    skill_id text,
    contact_state_id text,
    contact_state_name text,
    digital_contact_state_id text,
    digital_contact_state_name text,
    duration text,
    end_date text,
    is_warehoused text,
    PRIMARY KEY (start_date, state_index, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE interaction_history (
    last_update_time text,
    contact_id text,
    agent_id text,
    campaign_id text,
    skill_id text,
    team_id text,
    start_date text,
    PRIMARY KEY (last_update_time, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE wfm_data_contact (
    interval_start_date text,
    skill_id text,
    abandon_count text,
    average_handle_time text,
    average_speed_of_answer text,
    business_unit_id text,
    business_unit_name text,
    end_date text,
    is_outbound text,
    media_type_id text,
    media_type_name text,
    service_level text,
    total_contact_time text,
    total_contacts text,
    total_handled text,
    PRIMARY KEY (interval_start_date, skill_id),
    FOREIGN KEY (skill_id) REFERENCES skill(id)
);

CREATE TABLE state_history (
    start_date text,
    state_index text,
    agent_id text,
    contact_id text,
    skill_id text,
    team_id text,
    agent_session_id text,
    agent_state_id text,
    agent_state_name text,
    duration text,
    end_date text,
    from_address text,
    is_natural_calling text,
    is_outbound text,
    media_type_id text,
    media_type_name text,
    out_state_description text,
    out_state_id text,
    station_id text,
    station_name text,
    to_address text,
    PRIMARY KEY (start_date, state_index, agent_id),
    FOREIGN KEY (agent_id) REFERENCES agent(id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (skill_id) REFERENCES skill(id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);
