CREATE TABLE crash_in_dc_coordinate (
    "index" text,
    crash_in_dc_crime_id text,
    coordinate double precision,
    PRIMARY KEY ("index", crash_in_dc_crime_id),
    FOREIGN KEY (crash_in_dc_crime_id) REFERENCES crash_in_dc(crime_id)
);

CREATE TABLE crash_in_dc (
    crime_id text,
    address text,
    bicyclists_impaired integer,
    ccn text,
    drivers_impaired integer,
    event_id text,
    fatal_bicyclist integer,
    fatal_driver integer,
    fatal_passenger integer,
    fatal_pedestrian integer,
    from_date timestamp,
    geometry_type text,
    id bigint,
    int_approach_direction text,
    last_update_date timestamp,
    latitude double precision,
    location_error text,
    longitude double precision,
    major_injuries_bicyclist integer,
    major_injuries_driver integer,
    major_injuries_passenger integer,
    major_injuries_pedestrian integer,
    mar_address text,
    mar_id integer,
    mar_score double precision,
    measure double precision,
    minor_injuries_bicyclist integer,
    minor_injuries_driver integer,
    minor_injuries_passenger integer,
    minor_injuries_pedestrian integer,
    mpd_latitude double precision,
    mpd_longitude double precision,
    mpdgeox double precision,
    mpdgeoy double precision,
    nearest_int_route_id text,
    nearest_int_street_name text,
    offintersection double precision,
    offsets double precision,
    pedestrians_impaired integer,
    report_date timestamp,
    roadways_egid integer,
    route_id text,
    speeding_involved integer,
    streets_egid integer,
    to_date timestamp,
    total_bicycles integer,
    total_government integer,
    total_pedestrians integer,
    total_taxis integer,
    total_vehicles integer,
    "type" text,
    unknown_injuries_bicyclist integer,
    unknown_injuries_driver integer,
    unknown_injuries_passenger integer,
    unknown_injuries_pedestrian integer,
    ward text,
    x_coord double precision,
    y_coord double precision,
    PRIMARY KEY (crime_id)
);

CREATE TABLE crash_in_dc_detail (
    person_id text,
    crime_id text,
    age integer,
    ccn text,
    fatal text,
    impaired text,
    in_vehicle_type text,
    license_plate_state text,
    major_injury text,
    minor_injury text,
    object_id bigint,
    person_type text,
    speeding text,
    ticket_issued text,
    vehicle_id text,
    PRIMARY KEY (person_id, crime_id),
    FOREIGN KEY (crime_id) REFERENCES crash_in_dc(crime_id)
);
