CREATE TABLE price_unit_price_override (
    "index" text,
    price_id text,
    amount text,
    country_code text,
    currency_code text,
    PRIMARY KEY ("index", price_id),
    FOREIGN KEY (price_id) REFERENCES price(id)
);

CREATE TABLE price (
    id text,
    product_id text,
    billing_cycle_frequency text,
    billing_cycle_interval text,
    created_at text,
    description text,
    import_meta_external_id text,
    import_meta_imported_from text,
    "name" text,
    quantity_maximum text,
    quantity_minimum text,
    "status" text,
    tax_mode text,
    trial_period_frequency text,
    trial_period_interval text,
    "type" text,
    unit_price_amount text,
    unit_price_currency_code text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE customer_business_contact (
    "index" text,
    customer_business_id text,
    email text,
    "name" text,
    PRIMARY KEY ("index", customer_business_id),
    FOREIGN KEY (customer_business_id) REFERENCES customer_business(id)
);

CREATE TABLE customer_business (
    id text,
    customer_id text,
    company_number text,
    created_at text,
    import_meta_external_id text,
    import_meta_imported_from text,
    "name" text,
    "status" text,
    tax_identifier text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE subscription_item (
    "index" text,
    subscription_id text,
    price_id text,
    product_id text,
    created_at text,
    next_billed_at text,
    previously_billed_at text,
    quantity text,
    recurring text,
    "status" text,
    trial_date_ends_at text,
    trial_date_starts_at text,
    updated_at text,
    PRIMARY KEY ("index", subscription_id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id),
    FOREIGN KEY (price_id) REFERENCES price(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE subscription (
    id text,
    address_id text,
    business_id text,
    customer_id text,
    billing_cycle_frequency text,
    billing_cycle_interval text,
    billing_details_additional_information text,
    billing_details_enable_checkout text,
    billing_details_purchase_order_number text,
    canceled_at text,
    collection_mode text,
    created_at text,
    currency_code text,
    current_billing_period_ends_at text,
    current_billing_period_starts_at text,
    discount_ends_at text,
    discount_id text,
    discount_starts_at text,
    first_billed_at text,
    import_meta_external_id text,
    import_meta_imported_from text,
    management_url_cancel text,
    management_url_update_payment_method text,
    next_billed_at text,
    paused_at text,
    payment_term_frequency text,
    payment_term_interval text,
    scheduled_change_action text,
    scheduled_change_effective_at text,
    scheduled_change_resume_at text,
    started_at text,
    "status" text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES "transaction"(id),
    FOREIGN KEY (business_id) REFERENCES customer_business(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE adjustment_item (
    id text,
    adjustment_id text,
    item_id text,
    amount text,
    "type" text,
    PRIMARY KEY (id, adjustment_id),
    FOREIGN KEY (adjustment_id) REFERENCES adjustment(id),
    FOREIGN KEY (item_id) REFERENCES transaction_detail_line_item(id)
);

CREATE TABLE adjustment_tax_rates_used (
    "index" text,
    adjustment_id text,
    tax_rate text,
    PRIMARY KEY ("index", adjustment_id),
    FOREIGN KEY (adjustment_id) REFERENCES adjustment(id)
);

CREATE TABLE adjustment (
    id text,
    customer_id text,
    subscription_id text,
    transaction_id text,
    "action" text,
    created_at text,
    credit_applied_to_balance text,
    currency_code text,
    payout_total_chargeback_fee_amount text,
    payout_total_currency_code text,
    payout_total_earning text,
    payout_total_fee text,
    reason text,
    "status" text,
    total_currency_code text,
    total_earning text,
    total_fee text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE product (
    id text,
    price_id text,
    created_at text,
    description text,
    image_url text,
    import_meta_external_id text,
    import_meta_imported_from text,
    "name" text,
    "status" text,
    tax_category text,
    "type" text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (price_id) REFERENCES price(id)
);

CREATE TABLE customer (
    id text,
    created_at text,
    email text,
    import_meta_external_id text,
    import_meta_imported_from text,
    locale text,
    marketing_consent text,
    "name" text,
    "status" text,
    updated_at text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE transaction_payment (
    payment_attempt_id text,
    transaction_id text,
    amount text,
    captured_at text,
    created_at text,
    error_code text,
    method_card_cardholder_name text,
    method_card_expiry_month text,
    method_card_expiry_year text,
    method_card_last_4 text,
    method_card_type text,
    method_detail_type text,
    payment_method_id text,
    "status" text,
    PRIMARY KEY (payment_attempt_id, transaction_id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE transaction_detail_line_item (
    id text,
    transaction_id text,
    price_id text,
    product_id text,
    proration_billing_period_ends_at text,
    proration_billing_period_starts_at text,
    proration_rate text,
    quantity text,
    tax_rate text,
    PRIMARY KEY (id, transaction_id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id),
    FOREIGN KEY (price_id) REFERENCES price(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE "transaction" (
    id text,
    adjustment_id text,
    business_id text,
    customer_id text,
    subscription_id text,
    address_city text,
    address_country_code text,
    address_created_at text,
    address_customer_id text,
    address_description text,
    address_first_line text,
    address_id text,
    address_import_meta_external_id text,
    address_import_meta_imported_from text,
    address_postal_code text,
    address_region text,
    address_second_line text,
    address_status text,
    address_updated_at text,
    adjusted_payout_total_chargeback_fee_amount text,
    adjusted_payout_total_earning text,
    adjusted_payout_total_fee text,
    adjusted_payout_total_original_amount text,
    adjusted_payout_total_original_currency_code text,
    adjusted_total_currency_code text,
    adjusted_total_earning text,
    adjusted_total_fee text,
    available_payment_methods jsonb,
    billed_at text,
    billing_details_additional_information text,
    billing_details_enable_checkout text,
    billing_details_payment_frequency text,
    billing_details_payment_interval text,
    billing_details_purchase_order_number text,
    billing_period_ends_at text,
    billing_period_starts_at text,
    checkout_url text,
    collection_mode text,
    created_at text,
    currency_code text,
    discount_id text,
    invoice_id text,
    invoice_number text,
    origin text,
    payout_total_balance text,
    payout_total_credit text,
    payout_total_credit_to_balance text,
    payout_total_discount text,
    payout_total_earnings text,
    payout_total_fee text,
    receipt_data text,
    revised_at text,
    "status" text,
    total_balance text,
    total_credit text,
    total_discount text,
    total_earnings text,
    total_fee text,
    updated_at text,
    -- address_custom_* (dynamic column),
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (adjustment_id) REFERENCES adjustment(id),
    FOREIGN KEY (business_id) REFERENCES customer_business(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);
