CREATE TABLE employee_deduction_cost_center (
    "index" text,
    employee_deduction_id text,
    employee_id text,
    additional_prop text,
    code text,
    "level" text,
    PRIMARY KEY ("index", employee_deduction_id, employee_id),
    FOREIGN KEY (employee_deduction_id) REFERENCES employee_deduction(id),
    FOREIGN KEY (employee_id) REFERENCES employee_deduction(employee_id)
);

CREATE TABLE employee_deduction (
    id text,
    employee_id text,
    agency_code text,
    arrear text,
    begin_check_date text,
    calculation_code text,
    code text,
    effective_date text,
    end_check_date text,
    frequency text,
    limits_annual_maximum text,
    limits_goal text,
    limits_paid_to_date text,
    limits_paid_year_to_date text,
    limits_pay_period_maximum text,
    limits_pay_period_minimum text,
    loan_additional_prop text,
    loan_first_payment_date text,
    loan_issue_date text,
    loan_number text,
    miscellaneous_info text,
    note text,
    priority text,
    rate text,
    record_type text,
    self_insured text,
    "type" text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_future_pay_rate (
    "index" text,
    employee_id text,
    additional_prop jsonb,
    annual_salary text,
    begin_check_date text,
    change_reason text,
    effective_date text,
    is_auto_pay text,
    pay_frequency text,
    pay_rate_description text,
    pay_type text,
    salary text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_position_family (
    "index" text,
    employee_id text,
    additional_prop jsonb,
    code text,
    description text,
    "name" text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee (
    id text,
    address_1 text,
    address_2 text,
    adjusted_seniority_date text,
    city text,
    clock_badge text,
    country text,
    county text,
    current_pay_rate_annual_salary text,
    current_pay_rate_base_rate text,
    current_pay_rate_begin_check_date text,
    current_pay_rate_default_hours text,
    current_pay_rate_effective_date text,
    current_pay_rate_frequency text,
    current_pay_rate_grade text,
    current_pay_rate_is_auto_pay text,
    current_pay_rate_per text,
    current_pay_rate_salary text,
    current_pay_rate_type text,
    current_status_additional_prop jsonb,
    current_status_change_reason text,
    current_status_change_reason_code text,
    current_status_effective_date text,
    date_of_birth text,
    display_name text,
    eeo_class text,
    eligible_for_rehire text,
    ethnicity_race text,
    first_name text,
    gender text,
    hire_date text,
    home_phone text,
    info_additional_prop jsonb,
    info_address_additional_prop jsonb,
    is_supervisor text,
    job_title text,
    last_name text,
    marital_status text,
    middle_name text,
    min_wage_exempt text,
    mobile_phone text,
    ot_exempt text,
    pay_group text,
    personal_email text,
    position_additional_prop jsonb,
    position_career_level_code text,
    position_career_level_description text,
    position_change_reason text,
    position_code text,
    position_cost_center_1 text,
    position_cost_center_2 text,
    position_cost_center_3 text,
    position_description text,
    position_effective_date text,
    position_employee_type text,
    postal_code text,
    preferred_name text,
    relationship_id text,
    reviewer text,
    reviewer_co text,
    shift text,
    ssn text,
    "state" text,
    "status" text,
    status_type text,
    suffix text,
    supervisor text,
    supervisor_co text,
    tipped text,
    wcc text,
    work_location_additional_prop jsonb,
    work_location_address_1 text,
    work_location_address_2 text,
    work_location_address_additional_prop jsonb,
    work_location_city text,
    work_location_country text,
    work_location_county text,
    work_location_email text,
    work_location_mobile_phone text,
    work_location_phone text,
    work_location_phone_ext text,
    work_location_postal_code text,
    work_location_state text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_punch_details_segments_costcenter (
    id text,
    employee_id text,
    punch_date text,
    punch_type text,
    code text,
    cost_center_id text,
    is_active text,
    "level" text,
    "name" text,
    PRIMARY KEY (id, employee_id, punch_date, punch_type),
    FOREIGN KEY (employee_id) REFERENCES employee_punch_details_segment(employee_id),
    FOREIGN KEY (punch_date) REFERENCES employee_punch_details_segment("date"),
    FOREIGN KEY (punch_type) REFERENCES employee_punch_details_segment(punch_type)
);

CREATE TABLE employee_punch_details_segment (
    "date" text,
    punch_type text,
    employee_id text,
    duration_seconds text,
    earnings text,
    origin text,
    punch_id text,
    relative_end text,
    relative_original_end text,
    relative_original_start text,
    relative_start text,
    PRIMARY KEY ("date", punch_type, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_punch_detail(employee_id)
);

CREATE TABLE employee_punch_detail (
    employee_id text,
    badge_number text,
    relative_end text,
    relative_start text,
    PRIMARY KEY (employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_earning_cost_center (
    "index" text,
    employee_earning_id text,
    employee_id text,
    additional_prop jsonb,
    code text,
    "level" text,
    PRIMARY KEY ("index", employee_earning_id, employee_id),
    FOREIGN KEY (employee_earning_id) REFERENCES employee_earning(id),
    FOREIGN KEY (employee_id) REFERENCES employee_earning(employee_id)
);

CREATE TABLE employee_earning (
    id text,
    employee_id text,
    additional_prop jsonb,
    agency text,
    amount text,
    begin_check_date text,
    calculation_code text,
    code text,
    distribution_additional_prop jsonb,
    distribution_job_code text,
    effective_date text,
    end_check_date text,
    frequency text,
    limits_additional_prop jsonb,
    limits_annual_maximum text,
    limits_goal text,
    limits_paid_to_date text,
    limits_paid_year_to_date text,
    limits_pay_period_maximum text,
    limits_pay_period_minimum text,
    miscellaneous_info text,
    rate text,
    rate_code text,
    record_type text,
    self_insured text,
    units text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);
