CREATE TABLE transaction_item_checkout_option (
    "index" integer,
    item_detail_index integer,
    transaction_id text,
    "name" text,
    "value" text,
    PRIMARY KEY ("index", item_detail_index, transaction_id),
    FOREIGN KEY (item_detail_index) REFERENCES transaction_item_detail("index"),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE transaction_item_tax_amount (
    "index" integer,
    item_detail_index integer,
    transaction_id text,
    amount text,
    currency_code text,
    PRIMARY KEY ("index", item_detail_index, transaction_id),
    FOREIGN KEY (item_detail_index) REFERENCES transaction_item_detail("index"),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE transaction_item_detail (
    "index" integer,
    transaction_event_code text,
    transaction_id text,
    adjustment_amount text,
    adjustment_currency_code text,
    amount text,
    basic_shipping_amount text,
    basic_shipping_currency_code text,
    code text,
    currency_code text,
    description text,
    discount_amount text,
    discount_currency_code text,
    extra_shipping_amount text,
    extra_shipping_currency_code text,
    gift_wrap_amount text,
    gift_wrap_currency_code text,
    handling_amount text,
    handling_currency_code text,
    insurance_amount text,
    insurance_currency_code text,
    invoice_number text,
    "name" text,
    options text,
    quantity text,
    tax_percentage text,
    unit_price_amount text,
    unit_price_currency_code text,
    PRIMARY KEY ("index", transaction_event_code, transaction_id),
    FOREIGN KEY (transaction_event_code) REFERENCES "transaction"(event_code),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE incentive (
    "index" integer,
    transaction_event_code text,
    transaction_id text,
    amount text,
    code text,
    currency_code text,
    program_code text,
    "type" text,
    PRIMARY KEY ("index", transaction_event_code, transaction_id),
    FOREIGN KEY (transaction_event_code) REFERENCES "transaction"(event_code),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE "transaction" (
    event_code text,
    id text,
    amount text,
    annual_percentage_rate text,
    auction_buyer_id text,
    auction_closing_date timestamp,
    auction_item_site text,
    auction_site text,
    available_balance_currency_code text,
    available_balance_value text,
    bank_reference_id text,
    credit_promotional_fee_amount text,
    credit_promotional_fee_currency_code text,
    credit_term text,
    credit_transactional_fee_amount text,
    credit_transactional_fee_currency_code text,
    currency_code text,
    custom_field text,
    discount_amount text,
    discount_currency_code text,
    ending_balance_amount text,
    ending_balance_currency_code text,
    fee_amount text,
    fee_currency_code text,
    initiation_date timestamp,
    instrument_sub_type text,
    instrument_type text,
    insurance_amount text,
    insurance_currency_code text,
    invoice_id text,
    note text,
    other_amount text,
    other_currency_code text,
    payer_account_id text,
    payer_address_city text,
    payer_address_country_code text,
    payer_address_line_1 text,
    payer_address_line_2 text,
    payer_address_postal_code text,
    payer_address_state text,
    payer_country_code text,
    payer_email_address text,
    payer_full_name text,
    payer_given_name text,
    payer_middle_name text,
    payer_phone_country_code text,
    payer_phone_extension_number text,
    payer_phone_national_number text,
    payer_prefix text,
    payer_status text,
    payer_suffix text,
    payer_surname text,
    payment_method_type text,
    payment_tracking_id text,
    paypal_account_id text,
    paypal_invoice_id text,
    paypal_reference_id text,
    paypal_reference_id_type text,
    protection_eligibility text,
    sales_tax_amount text,
    sales_tax_currency_code text,
    shipping_amount text,
    shipping_currency_code text,
    shipping_discount_amount text,
    shipping_discount_currency_code text,
    shipping_info_address_city text,
    shipping_info_address_country_code text,
    shipping_info_address_line_1 text,
    shipping_info_address_line_2 text,
    shipping_info_address_postal_code text,
    shipping_info_method text,
    shipping_info_name text,
    shipping_info_secondary_address_city text,
    shipping_info_secondary_address_country_code text,
    shipping_info_secondary_address_line_1 text,
    shipping_info_secondary_address_line_2 text,
    shipping_info_secondary_address_postal_code text,
    shipping_info_secondary_address_state text,
    shipping_tax_amount text,
    shipping_tax_currency_code text,
    "status" text,
    store_info_id text,
    store_info_terminal_id text,
    subject text,
    tax_inclusive boolean,
    tip_amount text,
    tip_currency_code text,
    updated_date timestamp,
    PRIMARY KEY (event_code, id)
);

CREATE TABLE pricing_tier (
    "index" integer,
    billing_cycle_index integer,
    billing_plan_id text,
    amount text,
    currency_code text,
    ending_quantity text,
    starting_quantity text,
    PRIMARY KEY ("index", billing_cycle_index, billing_plan_id),
    FOREIGN KEY (billing_cycle_index) REFERENCES billing_cycle("index"),
    FOREIGN KEY (billing_plan_id) REFERENCES billing_plan(id)
);

CREATE TABLE billing_cycle (
    "index" integer,
    billing_plan_id text,
    frequency_interval_count integer,
    frequency_interval_unit text,
    pricing_scheme_create_time timestamp,
    pricing_scheme_fixed_price_amount text,
    pricing_scheme_fixed_price_currency_code text,
    pricing_scheme_pricing_model text,
    pricing_scheme_update_time timestamp,
    pricing_scheme_version integer,
    "sequence" integer,
    tenure_type text,
    total_cycles integer,
    PRIMARY KEY ("index", billing_plan_id),
    FOREIGN KEY (billing_plan_id) REFERENCES billing_plan(id)
);

CREATE TABLE billing_plan (
    id text,
    create_time timestamp,
    description text,
    "name" text,
    payment_preferences_auto_bill_outstanding boolean,
    payment_preferences_payment_failure_threshold integer,
    payment_preferences_setup_fee_amount text,
    payment_preferences_setup_fee_currency_code text,
    payment_preferences_setup_fee_failure_action text,
    product_id text,
    quantity_supported boolean,
    "status" text,
    taxes_inclusive boolean,
    taxes_percentage text,
    updated_time timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE disputed_transaction_item_service_details_sub_reason (
    "index" integer,
    dispute_id text,
    disputed_transaction_item_index integer,
    "name" text,
    PRIMARY KEY ("index", dispute_id, disputed_transaction_item_index),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id),
    FOREIGN KEY (disputed_transaction_item_index) REFERENCES disputed_transaction_item("index")
);

CREATE TABLE disputed_transaction_item (
    "index" integer,
    dispute_id text,
    disputed_transaction_index integer,
    agreed_refund_details_merchant_agreed_refund boolean,
    agreed_refund_details_merchant_agreed_refund_time timestamp,
    cancellation_date text,
    cancellation_mode text,
    cancellation_number text,
    cancelled boolean,
    description text,
    dispute_amount text,
    dispute_currency_code text,
    id text,
    "name" text,
    notes text,
    partner_transaction_id text,
    quantity text,
    reason text,
    "type" text,
    PRIMARY KEY ("index", dispute_id, disputed_transaction_index),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id),
    FOREIGN KEY (disputed_transaction_index) REFERENCES disputed_transaction("index")
);

CREATE TABLE disputed_transaction (
    "index" integer,
    dispute_id text,
    buyer_name text,
    buyer_transaction_id text,
    create_time timestamp,
    custom text,
    gross_amount text,
    gross_currency_code text,
    gross_quantity text,
    gross_symbol text,
    invoice_number text,
    reference_id text,
    seller_email text,
    seller_merchant_id text,
    seller_name text,
    seller_transaction_id text,
    transaction_status text,
    PRIMARY KEY ("index", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE dispute_message (
    "index" integer,
    dispute_id text,
    content text,
    posted_by text,
    time_posted timestamp,
    PRIMARY KEY ("index", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE money_movement (
    "index" integer,
    dispute_id text,
    affected_party text,
    amount text,
    currency_code text,
    initiated_time timestamp,
    quantity text,
    reason text,
    symbol text,
    "type" text,
    PRIMARY KEY ("index", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE tracking_info (
    "index" integer,
    dispute_id text,
    evidence_index integer,
    carrier_name text,
    carrier_name_other text,
    tracking_number text,
    tracking_url text,
    PRIMARY KEY ("index", dispute_id, evidence_index),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id),
    FOREIGN KEY (evidence_index) REFERENCES evidence("index")
);

CREATE TABLE evidence_info_refund (
    "index" integer,
    dispute_id text,
    evidence_index integer,
    id text,
    PRIMARY KEY ("index", dispute_id, evidence_index),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id),
    FOREIGN KEY (evidence_index) REFERENCES evidence("index")
);

CREATE TABLE evidence (
    "index" integer,
    dispute_id text,
    action_info_action text,
    action_info_mandatory boolean,
    action_info_response_option text,
    "date" text,
    dispute_life_cycle_stage text,
    evidence_type text,
    item_id text,
    item_type text,
    notes text,
    "source" text,
    PRIMARY KEY ("index", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE offer_history (
    "index" integer,
    dispute_id text,
    actor text,
    amount text,
    currency_code text,
    dispute_life_cycle_stage text,
    event_type text,
    notes text,
    "time" timestamp,
    "type" text,
    PRIMARY KEY ("index", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE supporting_info (
    "index" integer,
    dispute_id text,
    dispute_life_cycle_stage text,
    notes text,
    provided_time timestamp,
    "source" text,
    PRIMARY KEY ("index", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE adjudication (
    "index" integer,
    dispute_id text,
    adjudication_time timestamp,
    dispute_life_cycle_stage text,
    reason text,
    "type" text,
    PRIMARY KEY ("index", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE dispute (
    id text,
    amount text,
    asset_quantity text,
    asset_symbol text,
    buyer_contacted_channel text,
    buyer_contacted_time timestamp,
    buyer_response_due_date timestamp,
    canceled_recurring_billing_cancellation_details_cancellation_date text,
    canceled_recurring_billing_cancellation_details_cancellation_mode text,
    canceled_recurring_billing_cancellation_details_cancellation_number text,
    canceled_recurring_billing_cancellation_details_cancelled boolean,
    canceled_recurring_billing_expected_refund_amount text,
    canceled_recurring_billing_expected_refund_currency_code text,
    cancellation_details_cancellation_date text,
    cancellation_details_cancellation_mode text,
    cancellation_details_cancellation_number text,
    cancellation_details_cancelled boolean,
    channel text,
    create_time timestamp,
    credit_not_processed_agreed_refund_details_merchant_agreed_refund boolean,
    credit_not_processed_agreed_refund_details_merchant_agreed_refund_time timestamp,
    credit_not_processed_amount text,
    credit_not_processed_cancellation_details_cancellation_date text,
    credit_not_processed_cancellation_details_cancellation_mode text,
    credit_not_processed_cancellation_details_cancellation_number text,
    credit_not_processed_cancellation_details_cancelled boolean,
    credit_not_processed_currency_code text,
    credit_not_processed_issue_type text,
    credit_not_processed_product_details_description text,
    credit_not_processed_product_details_expected_delivery_date text,
    credit_not_processed_product_details_product_received text,
    credit_not_processed_product_details_product_received_time text,
    credit_not_processed_product_details_purchase_url text,
    credit_not_processed_product_details_return_details_mode text,
    credit_not_processed_product_details_return_details_receipt boolean,
    credit_not_processed_product_details_return_details_return_confirmation_number text,
    credit_not_processed_product_details_return_details_return_time timestamp,
    credit_not_processed_product_details_returned boolean,
    currency_code text,
    duplicate_transaction_original_buyer_transaction_id text,
    duplicate_transaction_original_seller_transaction_id text,
    duplicate_transaction_received_duplicate boolean,
    email text,
    external_reason_code text,
    incorrect_transaction_amount_correct_transaction_amount text,
    incorrect_transaction_amount_correct_transaction_asset_quantity text,
    incorrect_transaction_amount_correct_transaction_asset_symbol text,
    incorrect_transaction_amount_correct_transaction_currency_code text,
    incorrect_transaction_amount_correct_transaction_time timestamp,
    issue_type text,
    life_cycle_stage text,
    merchant_contacted boolean,
    merchant_contacted_mode text,
    merchant_contacted_outcome text,
    merchant_contacted_time timestamp,
    note text,
    offer_buyer_requested_amount text,
    offer_buyer_requested_currency_code text,
    offer_seller_offered_amount text,
    offer_seller_offered_currency_code text,
    offer_type text,
    outcome_asset_refunded_quantity text,
    outcome_asset_refunded_symbol text,
    outcome_code text,
    outcome_refunded_amount text,
    outcome_refunded_currency_code text,
    payment_by_other_means_charge_different_from_original boolean,
    payment_by_other_means_payment_instrument_suffix text,
    payment_by_other_means_payment_method text,
    payment_by_other_means_received_duplicate boolean,
    product_details_description text,
    product_details_expected_delivery_date text,
    product_details_product_received text,
    product_details_product_received_time text,
    product_details_purchase_url text,
    product_details_return_details_mode text,
    product_details_return_details_receipt boolean,
    product_details_return_details_return_confirmation_number text,
    product_details_return_details_return_time timestamp,
    product_details_returned boolean,
    reason text,
    refund_details_allowed_refund_amount text,
    refund_details_allowed_refund_currency_code text,
    return_shipping_address_address_line_1 text,
    return_shipping_address_address_line_2 text,
    return_shipping_address_address_line_3 text,
    return_shipping_address_admin_area_1 text,
    return_shipping_address_admin_area_2 text,
    return_shipping_address_admin_area_3 text,
    return_shipping_address_admin_area_4 text,
    return_shipping_address_country_code text,
    return_shipping_address_details_building_name text,
    return_shipping_address_details_delivery_service text,
    return_shipping_address_details_street_name text,
    return_shipping_address_details_street_number text,
    return_shipping_address_details_street_type text,
    return_shipping_address_details_sub_building text,
    return_shipping_address_postal_code text,
    seller_response_due_date text,
    service_details_description text,
    service_details_note text,
    service_details_purchase_url text,
    service_details_service_started text,
    "status" text,
    time_posted timestamp,
    update_time timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE dispute_sub_reason (
    "index" integer,
    "type" text,
    dispute_id text,
    "name" text,
    PRIMARY KEY ("index", "type", dispute_id),
    FOREIGN KEY (dispute_id) REFERENCES dispute(id)
);

CREATE TABLE product (
    id text,
    category text,
    create_time timestamp,
    description text,
    "name" text,
    "type" text,
    update_time timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE payment_detail (
    "index" integer,
    invoice_id text,
    amount text,
    currency_code text,
    "date" text,
    id text,
    method text,
    note text,
    shipping_info_address_city text,
    shipping_info_address_country_code text,
    shipping_info_address_line_1 text,
    shipping_info_address_line_2 text,
    shipping_info_address_postal_code text,
    shipping_info_address_state text,
    shipping_info_method text,
    shipping_info_name text,
    shipping_info_secondary_address_city text,
    shipping_info_secondary_address_country_code text,
    shipping_info_secondary_address_line_1 text,
    shipping_info_secondary_address_line_2 text,
    shipping_info_secondary_address_postal_code text,
    shipping_info_secondary_address_state text,
    "type" text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_item (
    "index" integer,
    invoice_id text,
    "date" timestamp,
    description text,
    discount_amount text,
    discount_currency_code text,
    discount_percent text,
    id text,
    "name" text,
    quantity text,
    tax_amount text,
    tax_currency_code text,
    tax_name text,
    tax_percent text,
    unit_amount text,
    unit_currency_code text,
    unit_of_measure text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE refund_detail (
    "index" integer,
    invoice_id text,
    amount text,
    currency_code text,
    "date" text,
    id text,
    method text,
    "type" text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoicer_info_phone (
    "index" integer,
    invoice_id text,
    country_code text,
    extension_number text,
    national_number text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE additional_recipient (
    "index" integer,
    invoice_id text,
    email_address text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE billing_info_phone (
    "index" integer,
    invoice_id text,
    primary_recipient_index integer,
    country_code text,
    extension_number text,
    national_number text,
    PRIMARY KEY ("index", invoice_id, primary_recipient_index),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (primary_recipient_index) REFERENCES primary_recipient("index")
);

CREATE TABLE primary_recipient (
    "index" integer,
    invoice_id text,
    billing_info_additional_info text,
    billing_info_email_address text,
    billing_info_language text,
    billing_info_name text,
    shipping_info_address_city text,
    shipping_info_address_country_code text,
    shipping_info_address_line_1 text,
    shipping_info_address_line_2 text,
    shipping_info_address_postal_code text,
    shipping_info_address_state text,
    shipping_info_method text,
    shipping_info_name text,
    shipping_info_secondary_address_city text,
    shipping_info_secondary_address_country_code text,
    shipping_info_secondary_address_line_1 text,
    shipping_info_secondary_address_line_2 text,
    shipping_info_secondary_address_postal_code text,
    shipping_info_secondary_address_state text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice (
    id text,
    allow_tip boolean,
    amount text,
    currency_code text,
    "date" text,
    due_amount text,
    due_currency_code text,
    gratuity_amount text,
    gratuity_currency_code text,
    invoicer_info_additional_notes text,
    invoicer_info_email_address text,
    invoicer_info_logo_url text,
    invoicer_info_tax_id text,
    invoicer_info_website text,
    memo text,
    note text,
    number text,
    parent_id text,
    partial_payment_allow_partial_payment boolean,
    partial_payment_minimal_amount_due_amount text,
    partial_payment_minimal_amount_due_currency_code text,
    payment_term_due_date text,
    payment_term_type text,
    reference text,
    "status" text,
    tax_calculated_after_discount boolean,
    tax_inclusive boolean,
    template_id text,
    term text,
    terms_and_conditions text,
    PRIMARY KEY (id)
);

CREATE TABLE balance_detail (
    "index" integer,
    account_id text,
    as_of_time timestamp,
    available_balance_amount text,
    available_balance_currency_code text,
    currency text,
    is_primary boolean,
    withheld_balance_amount text,
    withheld_balance_currency_code text,
    PRIMARY KEY ("index", account_id, as_of_time),
    FOREIGN KEY (account_id) REFERENCES balance(account_id),
    FOREIGN KEY (as_of_time) REFERENCES balance(as_of_time)
);

CREATE TABLE balance (
    account_id text,
    as_of_time timestamp,
    PRIMARY KEY (account_id, as_of_time)
);
