CREATE TABLE user_audit_log (
    id text,
    created_at text,
    get_params jsonb,
    impersonator_email_address text,
    ip_address text,
    method text,
    "path" text,
    post_params jsonb,
    relationships_user_data_id text,
    relationships_user_data_type text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE transaction_relationship_object (
    id text,
    transaction_id text,
    "type" text,
    PRIMARY KEY (id, transaction_id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE "transaction" (
    id text,
    reviewer_id text,
    back_photo_byte_size text,
    back_photo_filename text,
    back_photo_mime_type text,
    back_photo_type text,
    back_photo_url text,
    country text,
    created_at text,
    front_photo_byte_size text,
    front_photo_filename text,
    front_photo_mime_type text,
    front_photo_type text,
    front_photo_url text,
    name_first text,
    name_last text,
    reference_id text,
    reviewer_type text,
    selected_id_class text,
    "status" text,
    tags jsonb,
    transaction_label_data jsonb,
    transaction_type text,
    transaction_type_id text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (reviewer_id) REFERENCES inquiry(reviewer_id)
);

CREATE TABLE report (
    id text,
    relationships_account_data_id text,
    relationships_inquiry_data_id text,
    address_city text,
    address_postal_code text,
    address_postal_code_abbr text,
    address_street_1 text,
    address_street_2 text,
    address_subdivision text,
    address_subdivision_abbr text,
    birthdate text,
    completed_at text,
    created_at text,
    has_match text,
    name_first text,
    name_last text,
    phone_number text,
    redacted_at text,
    relationships_account_data_type text,
    relationships_inquiry_data_type text,
    relationships_report_template_data_id text,
    relationships_report_template_data_type text,
    report_template_version_name text,
    social_security_number text,
    "status" text,
    tags jsonb,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (relationships_account_data_id) REFERENCES account(id),
    FOREIGN KEY (relationships_inquiry_data_id) REFERENCES inquiry(id)
);

CREATE TABLE case_account (
    case_id text,
    id text,
    PRIMARY KEY (case_id, id),
    FOREIGN KEY (case_id) REFERENCES cases(id),
    FOREIGN KEY (id) REFERENCES account(id)
);

CREATE TABLE case_inquiry (
    case_id text,
    id text,
    PRIMARY KEY (case_id, id),
    FOREIGN KEY (case_id) REFERENCES cases(id),
    FOREIGN KEY (id) REFERENCES inquiry(id)
);

CREATE TABLE cases (
    id text,
    assigned_at text,
    assignee_id text,
    created_at text,
    creator_id text,
    creator_type text,
    fields jsonb,
    "name" text,
    redacted_at text,
    relationships_case_comments_data jsonb,
    relationships_case_template_data_id text,
    relationships_case_template_data_type text,
    relationships_reports_data jsonb,
    relationships_txns_data jsonb,
    relationships_verifications_data jsonb,
    resolution text,
    resolved_at text,
    resolver_id text,
    resolver_type text,
    "status" text,
    tags jsonb,
    "type" text,
    updated_at text,
    updater_id text,
    updater_type text,
    PRIMARY KEY (id)
);

CREATE TABLE inquiry_relationship_verification (
    inquiry_id text,
    id text,
    "type" text,
    PRIMARY KEY (inquiry_id, id),
    FOREIGN KEY (id) REFERENCES verification(id)
);

CREATE TABLE inquiry_document (
    inquiry_id text,
    id text,
    "type" text,
    PRIMARY KEY (inquiry_id, id),
    FOREIGN KEY (id) REFERENCES inquiry(id)
);

CREATE TABLE identification_number (
    "index" text,
    account_id text,
    identification_class text,
    identification_number text,
    issuing_country text,
    "type" text,
    PRIMARY KEY ("index", account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    account_status text,
    address_city text,
    address_country_code text,
    address_postal_code text,
    address_street_1 text,
    address_street_2 text,
    address_subdivision text,
    birthdate text,
    created_at text,
    email_address text,
    identification_number_type text,
    name_first text,
    name_last text,
    name_middle text,
    phone_number text,
    redacted_at text,
    reference_id text,
    selfie_phototype text,
    selfie_photovalue text,
    social_security_number text,
    tags jsonb,
    "type" text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE inquiry_session (
    id text,
    relationships_inquiry_data_id text,
    browser_full_version text,
    browser_name text,
    country_code text,
    country_name text,
    created_at text,
    device_name text,
    device_type text,
    ip_address text,
    is_datacenter text,
    is_proxy text,
    is_tor text,
    latitude text,
    longitude text,
    mobile_sdk_full_version text,
    mobile_sdk_name text,
    os_full_version text,
    os_name text,
    region_code text,
    region_name text,
    relationships_inquiry_data_type text,
    "status" text,
    threat_level text,
    "type" text,
    user_agent text,
    PRIMARY KEY (id),
    FOREIGN KEY (relationships_inquiry_data_id) REFERENCES inquiry(id)
);

CREATE TABLE file (
    "index" text,
    document_id text,
    filename text,
    url text,
    PRIMARY KEY ("index", document_id),
    FOREIGN KEY (document_id) REFERENCES document(id)
);

CREATE TABLE document (
    id text,
    inquiry_id text,
    address_city text,
    address_postal_code text,
    address_street_1 text,
    address_street_2 text,
    address_subdivision text,
    back_photo_byte_size text,
    back_photo_filename text,
    back_photo_url text,
    birthdate text,
    created_at text,
    designations jsonb,
    document_files_data jsonb,
    document_type text,
    endorsements text,
    front_photo_byte_size text,
    front_photo_filename text,
    front_photo_url text,
    id_class text,
    inquiry_template_id text,
    inquiry_template_version_id text,
    ip_address text,
    kind text,
    name_first text,
    name_last text,
    processed_at text,
    processed_at_ts text,
    relationships_template_data text,
    restrictions text,
    "status" text,
    "type" text,
    vehicle_class text,
    PRIMARY KEY (id),
    FOREIGN KEY (inquiry_id) REFERENCES inquiry(id)
);

CREATE TABLE inquiry (
    id text,
    reference_id text,
    relationships_account_data_id text,
    account_id text,
    account_type text,
    address_city text,
    address_postal_code text,
    address_postal_code_abbr text,
    address_street_1 text,
    address_street_2 text,
    address_subdivision text,
    address_subdivision_abbr text,
    autofill_cancels text,
    autofill_starts text,
    behavior_threat_level text,
    birthdate text,
    completed_at text,
    completion_time text,
    created_at text,
    creator text,
    decisioned_at text,
    devtools_open text,
    distraction_event text,
    email_address text,
    expired_at text,
    failed_at text,
    hesitation_baseline text,
    hesitation_count text,
    hesitation_percentage text,
    hesitation_time text,
    inquiry_template_id text,
    inquiry_template_type text,
    inquiry_template_version_id text,
    inquiry_template_version_type text,
    marked_for_review_at text,
    name_first text,
    name_last text,
    next_step_name text,
    note text,
    phone_number text,
    previous_step_name text,
    redacted_at text,
    relationships_selfies_data jsonb,
    request_spoof_attempt text,
    reviewer_comment text,
    reviewer_id text,
    reviewer_type text,
    shortcut_copies text,
    shortcut_pastes text,
    social_security_number text,
    started_at text,
    "status" text,
    tags jsonb,
    template_data text,
    "type" text,
    user_agent_spoof_attempt text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (reference_id) REFERENCES account(reference_id),
    FOREIGN KEY (relationships_account_data_id) REFERENCES account(id)
);

CREATE TABLE list_item_data (
    id text,
    list_id text,
    "type" text,
    PRIMARY KEY (id, list_id),
    FOREIGN KEY (list_id) REFERENCES list(id)
);

CREATE TABLE list (
    id text,
    archived_at text,
    created_at text,
    "name" text,
    "status" text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE verification (
    id text,
    inquiry_id text,
    address_city text,
    address_postal_code text,
    address_street_1 text,
    address_street_2 text,
    address_subdivision text,
    back_photo_url text,
    birth_date text,
    capture_method text,
    checks jsonb,
    completed_at text,
    completed_at_ts text,
    confirmation_code text,
    country_code text,
    created_at text,
    created_at_ts text,
    document_similarity_score text,
    email_address text,
    endorsement text,
    entity_confidence_reason jsonb,
    entity_confidence_score text,
    expiration_date text,
    front_photo_url text,
    height text,
    id_class text,
    identification_number text,
    inquiry_type text,
    issue_date text,
    issuing_authority text,
    name_first text,
    name_last text,
    name_middle text,
    normalized_address_city text,
    normalized_address_postal_code text,
    normalized_address_street_1 text,
    normalized_address_street_2 text,
    normalized_address_subdivision text,
    phone_number text,
    restriction text,
    selfie_photo_url text,
    selfie_similarity_score_left text,
    selfie_similarity_score_right text,
    sex text,
    "status" text,
    submitted_at text,
    submitted_at_ts text,
    "type" text,
    vehicle_class text,
    PRIMARY KEY (id),
    FOREIGN KEY (inquiry_id) REFERENCES inquiry(id)
);
