CREATE TABLE user_account_top_pin_analytics (
    _fivetran_id text,
    pin_id text,
    clickthrough text,
    clickthrough_rate text,
    closeup text,
    closeup_rate text,
    engagement text,
    engagement_rate text,
    full_screen_play text,
    full_screen_playtime text,
    impression text,
    metrics_clickthrough text,
    metrics_clickthrough_rate text,
    metrics_closeup text,
    metrics_closeup_rate text,
    metrics_engagement text,
    metrics_engagement_rate text,
    metrics_full_screen_play text,
    metrics_full_screen_playtime text,
    metrics_impression text,
    metrics_outbound_click text,
    metrics_outbound_click_rate text,
    metrics_pin_click text,
    metrics_pin_click_rate text,
    metrics_quartile_95_percent_view text,
    metrics_save text,
    metrics_save_rate text,
    metrics_video_10_s_view text,
    metrics_video_avg_watch_time text,
    metrics_video_mrc_view text,
    metrics_video_start text,
    metrics_video_v_50_watch_time text,
    outbound_click text,
    outbound_click_rate text,
    pin_click text,
    pin_click_rate text,
    quartile_95_percent_view text,
    save text,
    save_rate text,
    sort_by text,
    video_10_s_view text,
    video_avg_watch_time text,
    video_mrc_view text,
    video_start text,
    video_v_50_watch_time text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (pin_id) REFERENCES pin(id)
);

CREATE TABLE pin_analytic_web_daily_metric (
    "date" text,
    end_date text,
    pin_id text,
    start_date text,
    app_types text,
    data_status text,
    metrics_clickthrough text,
    metrics_clickthrough_rate text,
    metrics_closeup text,
    metrics_full_screen_play text,
    metrics_full_screen_playtime text,
    metrics_impression text,
    metrics_outbound_click text,
    metrics_pin_click text,
    metrics_profile_visit text,
    metrics_quartile_95_percent_view text,
    metrics_save text,
    metrics_save_rate text,
    metrics_user_follow text,
    metrics_video_10_s_view text,
    metrics_video_avg_watch_time text,
    metrics_video_mrc_view text,
    metrics_video_start text,
    metrics_video_v_50_watch_time text,
    PRIMARY KEY ("date", end_date, pin_id, start_date),
    FOREIGN KEY (end_date) REFERENCES pin_analytics_web(end_date),
    FOREIGN KEY (pin_id) REFERENCES pin_analytics_web(pin_id),
    FOREIGN KEY (start_date) REFERENCES pin_analytics_web(start_date)
);

CREATE TABLE pin_analytics_web (
    end_date text,
    start_date text,
    pin_id text,
    app_types text,
    lifetime_metrics_total_comments text,
    lifetime_metrics_total_reactions text,
    summary_metrics_clickthrough text,
    summary_metrics_clickthrough_rate text,
    summary_metrics_closeup text,
    summary_metrics_full_screen_play text,
    summary_metrics_full_screen_playtime text,
    summary_metrics_impression text,
    summary_metrics_outbound_click text,
    summary_metrics_pin_click text,
    summary_metrics_profile_visit text,
    summary_metrics_quartile_95_percent_view text,
    summary_metrics_save text,
    summary_metrics_save_rate text,
    summary_metrics_user_follow text,
    summary_metrics_video_10_s_view text,
    summary_metrics_video_avg_watch_time text,
    summary_metrics_video_mrc_view text,
    summary_metrics_video_start text,
    summary_metrics_video_v_50_watch_time text,
    PRIMARY KEY (end_date, start_date, pin_id),
    FOREIGN KEY (pin_id) REFERENCES pin(id)
);

CREATE TABLE pin_analytic_tablet_daily_metric (
    "date" text,
    end_date text,
    pin_id text,
    start_date text,
    app_types text,
    data_status text,
    metrics_clickthrough text,
    metrics_clickthrough_rate text,
    metrics_closeup text,
    metrics_full_screen_play text,
    metrics_full_screen_playtime text,
    metrics_impression text,
    metrics_outbound_click text,
    metrics_pin_click text,
    metrics_profile_visit text,
    metrics_quartile_95_percent_view text,
    metrics_save text,
    metrics_save_rate text,
    metrics_user_follow text,
    metrics_video_10_s_view text,
    metrics_video_avg_watch_time text,
    metrics_video_mrc_view text,
    metrics_video_start text,
    metrics_video_v_50_watch_time text,
    PRIMARY KEY ("date", end_date, pin_id, start_date),
    FOREIGN KEY (end_date) REFERENCES pin_analytics_tablet(end_date),
    FOREIGN KEY (pin_id) REFERENCES pin_analytics_tablet(pin_id),
    FOREIGN KEY (start_date) REFERENCES pin_analytics_tablet(start_date)
);

CREATE TABLE pin_analytics_tablet (
    end_date text,
    start_date text,
    pin_id text,
    app_type text,
    lifetime_metrics_total_comments text,
    lifetime_metrics_total_reactions text,
    summary_metrics_clickthrough text,
    summary_metrics_clickthrough_rate text,
    summary_metrics_closeup text,
    summary_metrics_full_screen_play text,
    summary_metrics_full_screen_playtime text,
    summary_metrics_impression text,
    summary_metrics_outbound_click text,
    summary_metrics_pin_click text,
    summary_metrics_profile_visit text,
    summary_metrics_quartile_95_percent_view text,
    summary_metrics_save text,
    summary_metrics_save_rate text,
    summary_metrics_user_follow text,
    summary_metrics_video_10_s_view text,
    summary_metrics_video_avg_watch_time text,
    summary_metrics_video_mrc_view text,
    summary_metrics_video_start text,
    summary_metrics_video_v_50_watch_time text,
    PRIMARY KEY (end_date, start_date, pin_id),
    FOREIGN KEY (pin_id) REFERENCES pin(id)
);

CREATE TABLE user_account_analytic_daily_metric (
    "date" text,
    end_date text,
    start_date text,
    user_account_id text,
    data_status text,
    metrics_clickthrough text,
    metrics_clickthrough_rate text,
    metrics_closeup text,
    metrics_closeup_rate text,
    metrics_engagement text,
    metrics_engagement_rate text,
    metrics_full_screen_play text,
    metrics_full_screen_playtime text,
    metrics_impression text,
    metrics_outbound_click text,
    metrics_outbound_click_rate text,
    metrics_pin_click text,
    metrics_pin_click_rate text,
    metrics_quartile_95_percent_view text,
    metrics_save text,
    metrics_save_rate text,
    metrics_video_10_s_view text,
    metrics_video_avg_watch_time text,
    metrics_video_mrc_view text,
    metrics_video_start text,
    metrics_video_v_50_watch_time text,
    PRIMARY KEY ("date", end_date, start_date, user_account_id),
    FOREIGN KEY (end_date) REFERENCES user_account_analytics_organic(end_date),
    FOREIGN KEY (start_date) REFERENCES user_account_analytics_organic(start_date),
    FOREIGN KEY (user_account_id) REFERENCES user_account_analytics_organic(user_account_id)
);

CREATE TABLE user_account_analytics_organic (
    end_date text,
    start_date text,
    user_account_id text,
    summary_metrics_clickthrough text,
    summary_metrics_clickthrough_rate text,
    summary_metrics_closeup text,
    summary_metrics_closeup_rate text,
    summary_metrics_engagement text,
    summary_metrics_engagement_rate text,
    summary_metrics_full_screen_play text,
    summary_metrics_full_screen_playtime text,
    summary_metrics_impression text,
    summary_metrics_outbound_click text,
    summary_metrics_outbound_click_rate text,
    summary_metrics_pin_click text,
    summary_metrics_pin_click_rate text,
    summary_metrics_quartile_95_percent_view text,
    summary_metrics_save text,
    summary_metrics_save_rate text,
    summary_metrics_video_10_s_view text,
    summary_metrics_video_avg_watch_time text,
    summary_metrics_video_mrc_view text,
    summary_metrics_video_start text,
    summary_metrics_video_v_50_watch_time text,
    PRIMARY KEY (end_date, start_date, user_account_id),
    FOREIGN KEY (user_account_id) REFERENCES user_account(id)
);

CREATE TABLE pin_analytic_mobile_daily_metric (
    "date" text,
    end_date text,
    pin_id text,
    start_date text,
    app_types text,
    data_status text,
    metrics_clickthrough text,
    metrics_clickthrough_rate text,
    metrics_closeup text,
    metrics_full_screen_play text,
    metrics_full_screen_playtime text,
    metrics_impression text,
    metrics_outbound_click text,
    metrics_pin_click text,
    metrics_profile_visit text,
    metrics_quartile_95_percent_view text,
    metrics_save text,
    metrics_save_rate text,
    metrics_user_follow text,
    metrics_video_10_s_view text,
    metrics_video_avg_watch_time text,
    metrics_video_mrc_view text,
    metrics_video_start text,
    metrics_video_v_50_watch_time text,
    PRIMARY KEY ("date", end_date, pin_id, start_date),
    FOREIGN KEY (end_date) REFERENCES pin_analytics_mobile(end_date),
    FOREIGN KEY (pin_id) REFERENCES pin_analytics_mobile(pin_id),
    FOREIGN KEY (start_date) REFERENCES pin_analytics_mobile(start_date)
);

CREATE TABLE pin_analytics_mobile (
    end_date text,
    start_date text,
    pin_id text,
    app_types text,
    lifetime_metrics_total_comments text,
    lifetime_metrics_total_reactions text,
    summary_metrics_clickthrough text,
    summary_metrics_clickthrough_rate text,
    summary_metrics_closeup text,
    summary_metrics_full_screen_play text,
    summary_metrics_full_screen_playtime text,
    summary_metrics_impression text,
    summary_metrics_outbound_click text,
    summary_metrics_pin_click text,
    summary_metrics_profile_visit text,
    summary_metrics_quartile_95_percent_view text,
    summary_metrics_save text,
    summary_metrics_save_rate text,
    summary_metrics_user_follow text,
    summary_metrics_video_10_s_view text,
    summary_metrics_video_avg_watch_time text,
    summary_metrics_video_mrc_view text,
    summary_metrics_video_start text,
    summary_metrics_video_v_50_watch_time text,
    PRIMARY KEY (end_date, start_date, pin_id),
    FOREIGN KEY (pin_id) REFERENCES pin(id)
);

CREATE TABLE pin (
    id text,
    parent_pin_id text,
    alt_text text,
    board_id text,
    board_owner_username text,
    board_section_id text,
    created_at text,
    creative_type text,
    description text,
    dominant_color text,
    has_been_promoted text,
    is_owner text,
    is_standard text,
    link text,
    media_images jsonb,
    media_type text,
    note text,
    pin_metrics jsonb,
    product_tags jsonb,
    title text,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_pin_id) REFERENCES pin(id)
);

CREATE TABLE user_account_top_video_pin_analytics (
    _fivetran_id text,
    pin_id text,
    metrics_impression text,
    metrics_outbound_click text,
    metrics_quartile_95_percent_view text,
    metrics_save text,
    metrics_video_10_s_view text,
    metrics_video_avg_watch_time text,
    metrics_video_mrc_view text,
    metrics_video_start text,
    metrics_video_v_50_watch_time text,
    -- custom_* (dynamic column),
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (pin_id) REFERENCES pin(id)
);

CREATE TABLE user_account (
    id text,
    about text,
    account_type text,
    board_count text,
    business_name text,
    follower_count text,
    following_count text,
    monthly_views text,
    pin_count text,
    profile_image text,
    username text,
    website_url text,
    PRIMARY KEY (id)
);

CREATE TABLE user_account_analytic_daily_metric_paid (
    "date" text,
    end_date text,
    start_date text,
    user_account_id text,
    data_status text,
    metrics_clickthrough text,
    metrics_clickthrough_rate text,
    metrics_closeup text,
    metrics_closeup_rate text,
    metrics_engagement text,
    metrics_engagement_rate text,
    metrics_full_screen_play text,
    metrics_full_screen_playtime text,
    metrics_impression text,
    metrics_outbound_click text,
    metrics_outbound_click_rate text,
    metrics_pin_click text,
    metrics_pin_click_rate text,
    metrics_quartile_95_percent_view text,
    metrics_save text,
    metrics_save_rate text,
    metrics_video_10_s_view text,
    metrics_video_avg_watch_time text,
    metrics_video_mrc_view text,
    metrics_video_start text,
    metrics_video_v_50_watch_time text,
    PRIMARY KEY ("date", end_date, start_date, user_account_id),
    FOREIGN KEY (end_date) REFERENCES user_account_analytics_paid(end_date),
    FOREIGN KEY (start_date) REFERENCES user_account_analytics_paid(start_date),
    FOREIGN KEY (user_account_id) REFERENCES user_account_analytics_paid(user_account_id)
);

CREATE TABLE user_account_analytics_paid (
    end_date text,
    start_date text,
    user_account_id text,
    summary_metrics_clickthrough text,
    summary_metrics_clickthrough_rate text,
    summary_metrics_closeup text,
    summary_metrics_closeup_rate text,
    summary_metrics_engagement text,
    summary_metrics_engagement_rate text,
    summary_metrics_full_screen_play text,
    summary_metrics_full_screen_playtime text,
    summary_metrics_impression text,
    summary_metrics_outbound_click text,
    summary_metrics_outbound_click_rate text,
    summary_metrics_pin_click text,
    summary_metrics_pin_click_rate text,
    summary_metrics_quartile_95_percent_view text,
    summary_metrics_save text,
    summary_metrics_save_rate text,
    summary_metrics_video_10_s_view text,
    summary_metrics_video_avg_watch_time text,
    summary_metrics_video_mrc_view text,
    summary_metrics_video_start text,
    summary_metrics_video_v_50_watch_time text,
    PRIMARY KEY (end_date, start_date, user_account_id),
    FOREIGN KEY (user_account_id) REFERENCES user_account(id)
);
