CREATE TABLE contact_address (
    "index" text,
    contact_profile_id text,
    address text,
    PRIMARY KEY ("index", contact_profile_id),
    FOREIGN KEY (contact_profile_id) REFERENCES contact(profile_id)
);

CREATE TABLE contact_location (
    "index" text,
    contact_profile_id text,
    location text,
    PRIMARY KEY ("index", contact_profile_id),
    FOREIGN KEY (contact_profile_id) REFERENCES contact(profile_id)
);

CREATE TABLE contact_right (
    "index" text,
    contact_profile_id text,
    rights text,
    PRIMARY KEY ("index", contact_profile_id),
    FOREIGN KEY (contact_profile_id) REFERENCES contact(profile_id)
);

CREATE TABLE contact_phone (
    "index" text,
    contact_profile_id text,
    phone text,
    PRIMARY KEY ("index", contact_profile_id),
    FOREIGN KEY (contact_profile_id) REFERENCES contact(profile_id)
);

CREATE TABLE contact_skill (
    "index" text,
    contact_profile_id text,
    skill text,
    PRIMARY KEY ("index", contact_profile_id),
    FOREIGN KEY (contact_profile_id) REFERENCES contact(profile_id)
);

CREATE TABLE contact_mail (
    "index" text,
    contact_profile_id text,
    mail text,
    PRIMARY KEY ("index", contact_profile_id),
    FOREIGN KEY (contact_profile_id) REFERENCES contact(profile_id)
);

CREATE TABLE contact (
    profile_id text,
    org_id text,
    space_id text,
    user_id text,
    avatar text,
    city text,
    country text,
    external_id text,
    image jsonb,
    last_seen_on text,
    link text,
    "name" text,
    skype text,
    "state" text,
    "type" text,
    zip text,
    PRIMARY KEY (profile_id),
    FOREIGN KEY (org_id) REFERENCES organization(id),
    FOREIGN KEY (space_id) REFERENCES space(id),
    FOREIGN KEY (user_id) REFERENCES user_status(user_id)
);

CREATE TABLE user_status_phone (
    "index" text,
    user_id text,
    phone text,
    PRIMARY KEY ("index", user_id),
    FOREIGN KEY (user_id) REFERENCES user_status(user_id)
);

CREATE TABLE user_status_mail (
    "index" text,
    user_id text,
    disabled text,
    is_primary text,
    mail text,
    verified text,
    PRIMARY KEY ("index", user_id),
    FOREIGN KEY (user_id) REFERENCES user_status(user_id)
);

CREATE TABLE user_status (
    user_id text,
    org_id text,
    profile_id text,
    space_id text,
    betas jsonb,
    calendar_code text,
    flags jsonb,
    inbox text,
    inbox_new text,
    mailbox text,
    message_unread_count text,
    presence_ref_id text,
    presence_ref_type text,
    presence_signature text,
    presence_user_id text,
    profile_external_id text,
    profile_image text,
    profile_last_seen_on text,
    profile_link text,
    profile_mail text,
    profile_name text,
    profile_org_id text,
    profile_phone text,
    profile_push text,
    profile_space_id text,
    profile_type text,
    profile_user_id text,
    push_channel text,
    push_expires_in text,
    push_signature text,
    push_timestamp text,
    referral_code text,
    referral_status text,
    user_activated_on text,
    user_created_on text,
    user_domain text,
    user_flags jsonb,
    user_from_sharefile text,
    user_is_partner text,
    user_locale text,
    user_sf_mail text,
    user_status text,
    user_timezone text,
    PRIMARY KEY (user_id),
    FOREIGN KEY (org_id) REFERENCES organization(id),
    FOREIGN KEY (profile_id) REFERENCES contact(profile_id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE application (
    id text,
    space_id text,
    accounting_info_org_id text,
    accounting_info_count text,
    accounting_info_limit text,
    accounting_info_percent text,
    config_allow_create text,
    config_allow_edit text,
    config_description text,
    config_external_id text,
    config_icon text,
    config_icon_id text,
    config_item_name text,
    config_name text,
    config_type text,
    config_usage text,
    current_revision text,
    default_view_id text,
    is_default text,
    link text,
    link_add text,
    original text,
    share_file_vault_url text,
    "status" text,
    url text,
    url_add text,
    url_label text,
    PRIMARY KEY (id, space_id),
    FOREIGN KEY (space_id) REFERENCES space(id),
    FOREIGN KEY (accounting_info_org_id) REFERENCES organization(id)
);

CREATE TABLE organization_domain (
    "index" text,
    organization_id text,
    domain text,
    PRIMARY KEY ("index", organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE organization_right (
    "index" text,
    organization_id text,
    rights text,
    PRIMARY KEY ("index", organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE organization_space (
    organization_id text,
    space_id text,
    archived text,
    tops text,
    PRIMARY KEY (organization_id, space_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE organization (
    id text,
    contract_status text,
    grants_count text,
    image text,
    logo text,
    "name" text,
    premium text,
    rank text,
    "role" text,
    sales_agent_id text,
    segment text,
    segment_size text,
    "status" text,
    tier text,
    trial_expired_on text,
    "type" text,
    url text,
    url_label text,
    user_limit text,
    PRIMARY KEY (id)
);

CREATE TABLE space_right (
    "index" text,
    org_id text,
    space_id text,
    rights text,
    PRIMARY KEY ("index", org_id, space_id),
    FOREIGN KEY (org_id) REFERENCES space(org_id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE space (
    id text,
    org_id text,
    profile_id text,
    user_id text,
    auto_join text,
    created_by_avatar text,
    created_by_image text,
    created_by_last_seen_on text,
    created_by_link text,
    created_by_name text,
    created_by_profile_id text,
    created_by_space_id text,
    created_by_type text,
    created_by_user_id text,
    created_on text,
    description text,
    is_overdue text,
    item_accounting_info text,
    "name" text,
    owner_id text,
    owner_type text,
    post_on_new_app text,
    post_on_new_member text,
    premium text,
    privacy text,
    push_channel text,
    push_expires_in text,
    push_signature text,
    push_timestamp text,
    "role" text,
    sharefile_vault_url text,
    subscribed text,
    tier text,
    "type" text,
    url text,
    url_label text,
    video text,
    PRIMARY KEY (id, org_id),
    FOREIGN KEY (org_id) REFERENCES organization(id),
    FOREIGN KEY (profile_id) REFERENCES contact(profile_id),
    FOREIGN KEY (user_id) REFERENCES user_status(user_id)
);

CREATE TABLE item_field (
    field_id text,
    item_id text,
    config_label text,
    config_mapping text,
    config_setting jsonb,
    external_id text,
    field_value jsonb,
    label text,
    "type" text,
    PRIMARY KEY (field_id, item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item_right (
    "index" text,
    item_id text,
    rights text,
    PRIMARY KEY ("index", item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item (
    id text,
    app_item_id text,
    app_item_id_formatted text,
    comment_count text,
    created_by_avatar text,
    created_by_avatar_id text,
    created_by_avatar_type text,
    created_by_id text,
    created_by_image text,
    created_by_last_seen_on text,
    created_by_name text,
    created_by_type text,
    created_by_url text,
    created_by_user_id text,
    created_on text,
    created_via_auth_client_id text,
    created_via_display text,
    created_via_id text,
    created_via_name text,
    created_via_url text,
    current_revision_avatar text,
    current_revision_created_by_avatar text,
    current_revision_created_by_avatar_id text,
    current_revision_created_by_avatar_type text,
    current_revision_created_by_id text,
    current_revision_created_by_image text,
    current_revision_created_by_type text,
    current_revision_created_by_url text,
    current_revision_created_by_user_id text,
    current_revision_created_on text,
    current_revision_created_via_auth_client_id text,
    current_revision_created_via_display text,
    current_revision_created_via_id text,
    current_revision_created_via_name text,
    current_revision_created_via_url text,
    current_revision_item_revision_id text,
    current_revision_revision text,
    current_revision_type text,
    current_revision_user_avatar text,
    current_revision_user_avatar_id text,
    current_revision_user_avatar_type text,
    current_revision_user_id text,
    current_revision_user_image text,
    current_revision_user_last_seen_on text,
    current_revision_user_name text,
    current_revision_user_type text,
    current_revision_user_url text,
    current_revision_user_user_id text,
    external_id text,
    file_count text,
    initial_revision_created_by_avatar text,
    initial_revision_created_by_avatar_id text,
    initial_revision_created_by_avatar_type text,
    initial_revision_created_by_id text,
    initial_revision_created_by_image text,
    initial_revision_created_by_last_seen_on text,
    initial_revision_created_by_name text,
    initial_revision_created_by_type text,
    initial_revision_created_by_url text,
    initial_revision_created_by_user_id text,
    initial_revision_created_on text,
    initial_revision_created_via_auth_client_id text,
    initial_revision_created_via_display text,
    initial_revision_created_via_id text,
    initial_revision_created_via_name text,
    initial_revision_created_via_url text,
    initial_revision_item_revision_id text,
    initial_revision_revision text,
    initial_revision_type text,
    initial_revision_user_avatar text,
    initial_revision_user_avatar_id text,
    initial_revision_user_avatar_type text,
    initial_revision_user_id text,
    initial_revision_user_image text,
    initial_revision_user_last_seen_on text,
    initial_revision_user_name text,
    initial_revision_user_type text,
    initial_revision_user_url text,
    initial_revision_user_user_id text,
    last_event_on text,
    link text,
    priority text,
    rating jsonb,
    revision text,
    sharefile_vault_folder_id text,
    sharefile_vault_url text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE file_right (
    "index" text,
    file_id text,
    rights text,
    PRIMARY KEY ("index", file_id),
    FOREIGN KEY (file_id) REFERENCES file(id)
);

CREATE TABLE file (
    id text,
    app_id text,
    item_id text,
    context_created_on text,
    context_data_app_item_id text,
    context_data_created_on text,
    context_data_created_via text,
    context_data_excerpt text,
    context_data_link text,
    context_data_revision text,
    context_data_sharefile_vault_folder_id text,
    context_data_sharefile_vault_url text,
    context_data_title text,
    context_excerpt_label text,
    context_excerpt_text text,
    context_id text,
    context_link text,
    context_title text,
    context_type text,
    context_type_name text,
    created_by_avatar text,
    created_by_avatar_id text,
    created_by_avatar_type text,
    created_by_id text,
    created_by_image text,
    created_by_last_seen_on text,
    created_by_name text,
    created_by_type text,
    created_by_url text,
    created_by_user_id text,
    created_on text,
    created_via_auth_client_id text,
    created_via_display text,
    created_via_id text,
    created_via_name text,
    created_via_url text,
    description text,
    external_file_id text,
    hosted_by text,
    hosted_by_humanized_name text,
    initial_revision_created_by_avatar text,
    initial_revision_created_by_avatar_id text,
    initial_revision_created_by_avatar_type text,
    initial_revision_created_by_id text,
    initial_revision_created_by_image text,
    initial_revision_created_by_last_seen_on text,
    initial_revision_created_by_name text,
    initial_revision_created_by_type text,
    initial_revision_created_by_url text,
    initial_revision_created_by_user_id text,
    initial_revision_created_on text,
    initial_revision_created_via_auth_client_id text,
    initial_revision_created_via_display text,
    initial_revision_created_via_id text,
    initial_revision_created_via_name text,
    initial_revision_created_via_url text,
    initial_revision_item_revision_id text,
    initial_revision_revision text,
    initial_revision_type text,
    link text,
    link_target text,
    mimetype text,
    "name" text,
    perma_link text,
    presence text,
    push text,
    replaces jsonb,
    "size" text,
    thumbnail_link text,
    PRIMARY KEY (id, app_id),
    FOREIGN KEY (app_id) REFERENCES application(id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);
