CREATE TABLE question_answer (
    id text,
    _fivetran_id text,
    merchant_group_id text,
    merchant_id text,
    question_id text,
    answer text,
    author_type text,
    client_publication_status text,
    created_date text,
    email text,
    helpful_votes text,
    is_expert text,
    is_verified_buyer text,
    locale text,
    location text,
    nickname text,
    not_helpful_votes text,
    originating_product_page_id text,
    product_page_id text,
    profile_id text,
    pwr_publication_status text,
    "source" text,
    "type" text,
    updated_date text,
    PRIMARY KEY (id, _fivetran_id),
    FOREIGN KEY (_fivetran_id) REFERENCES question(_fivetran_id),
    FOREIGN KEY (merchant_group_id) REFERENCES question(merchant_group_id),
    FOREIGN KEY (merchant_id) REFERENCES question(merchant_id),
    FOREIGN KEY (question_id) REFERENCES question(id)
);

CREATE TABLE question (
    _fivetran_id text,
    merchant_id text,
    product_page_id text,
    product_page_id_variant text,
    category text,
    client_publication_status text,
    created_date text,
    device_id text,
    email text,
    helpful_votes text,
    id text,
    locale text,
    location text,
    merchant_group_id text,
    nickname text,
    not_helpful_votes text,
    originating_product_page_id text,
    pwr_publication_status text,
    question text,
    question_type text,
    "type" text,
    updated_date timestamp,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (merchant_id) REFERENCES product(merchant_id),
    FOREIGN KEY (product_page_id) REFERENCES product(product_page_id),
    FOREIGN KEY (product_page_id_variant) REFERENCES product(product_page_id_variant)
);

CREATE TABLE specific_moderation_question_observation (
    observation_id text,
    id text,
    code text,
    created_date text,
    merchant_group_id text,
    merchant_id text,
    updated_date text,
    PRIMARY KEY (observation_id, id),
    FOREIGN KEY (id) REFERENCES question(id)
);

CREATE TABLE specific_moderation_review_observation (
    observation_id text,
    id text,
    code text,
    created_date text,
    merchant_group_id text,
    merchant_id text,
    updated_date text,
    PRIMARY KEY (observation_id, id),
    FOREIGN KEY (id) REFERENCES review(id)
);

CREATE TABLE product (
    id text,
    add_to_cart_url text,
    asin text,
    brand text,
    category text,
    created_date text,
    description text,
    image_url text,
    in_stock text,
    manufacturer_id text,
    merchant_id text,
    "name" text,
    price text,
    product_page_id text,
    product_page_id_variant text,
    product_url text,
    upc text,
    updated_date timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE orders (
    id text,
    merchant_id text,
    product_page_id text,
    product_page_id_variant text,
    created_date text,
    email text,
    first_name text,
    last_name text,
    locale text,
    order_date text,
    updated_date timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (merchant_id) REFERENCES product(merchant_id),
    FOREIGN KEY (product_page_id) REFERENCES product(product_page_id),
    FOREIGN KEY (product_page_id_variant) REFERENCES product(product_page_id_variant)
);

CREATE TABLE review_badge (
    badge text,
    _fivetran_id text,
    PRIMARY KEY (badge, _fivetran_id),
    FOREIGN KEY (_fivetran_id) REFERENCES review(_fivetran_id)
);

CREATE TABLE review_media (
    id text,
    _fivetran_id text,
    merchant_group_id text,
    merchant_id text,
    review_id text,
    bytes text,
    caption text,
    client_publication_status text,
    created_date text,
    featured text,
    height text,
    helpful_votes text,
    locale text,
    location text,
    nickname text,
    not_helpful_votes text,
    originating_product_page_id text,
    product_page_id text,
    pwr_publication_status text,
    thumbnail_uri text,
    "type" text,
    updated_date text,
    uri text,
    width text,
    PRIMARY KEY (id, _fivetran_id),
    FOREIGN KEY (_fivetran_id) REFERENCES review(_fivetran_id),
    FOREIGN KEY (merchant_group_id) REFERENCES review(merchant_group_id),
    FOREIGN KEY (merchant_id) REFERENCES review(merchant_id),
    FOREIGN KEY (review_id) REFERENCES review(id)
);

CREATE TABLE review_merchant_response (
    id text,
    _fivetran_id text,
    merchant_group_id text,
    merchant_id text,
    review_id text,
    client_publication_status text,
    created_date text,
    email text,
    helpful_votes text,
    locale text,
    location text,
    nickname text,
    not_helpful_votes text,
    originating_product_page_id text,
    product_page_id text,
    profile_id text,
    pwr_publication_status text,
    response text,
    "type" text,
    updated_date text,
    PRIMARY KEY (id, _fivetran_id),
    FOREIGN KEY (_fivetran_id) REFERENCES review(_fivetran_id),
    FOREIGN KEY (merchant_group_id) REFERENCES review(merchant_group_id),
    FOREIGN KEY (merchant_id) REFERENCES review(merchant_id),
    FOREIGN KEY (review_id) REFERENCES review(id)
);

CREATE TABLE review_custom_question_name (
    "name" text,
    _fivetran_id text,
    "value" text,
    PRIMARY KEY ("name", _fivetran_id),
    FOREIGN KEY (_fivetran_id) REFERENCES review(_fivetran_id)
);

CREATE TABLE review (
    _fivetran_id text,
    order_id text,
    product_page_id text,
    bottom_line text,
    campaign_id text,
    client_publication_status text,
    comments text,
    created_date text,
    device_id text,
    disclosure_code text,
    email text,
    headline text,
    helpful_score text,
    helpful_votes text,
    id text,
    locale text,
    location text,
    merchant_group_id text,
    merchant_id text,
    nickname text,
    not_helpful_votes text,
    originating_product_page_id text,
    product_page_id_variant text,
    promo_code text,
    pwr_publication_status text,
    rating text,
    review_source text,
    service_comments text,
    sub_ratings text,
    submission_id text,
    syndicated text,
    syndicated_date text,
    syndicating_client text,
    syndicating_client_logo text,
    syndicating_client_url text,
    tags_cons_choice jsonb,
    tags_cons_selected jsonb,
    tags_pros_choice jsonb,
    tags_pros_selected jsonb,
    "type" text,
    updated_date timestamp,
    user_id text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_page_id) REFERENCES product(product_page_id)
);

CREATE TABLE moderation_observation (
    _fivetran_id text,
    custom text,
    description text,
    merchant_group_id text,
    merchant_postable text,
    "name" text,
    observation text,
    PRIMARY KEY (_fivetran_id)
);
