CREATE TABLE host_binary (
    "index" text,
    host_id text,
    cve_count text,
    file_mode text,
    md_5 text,
    missing_pkg text,
    "name" text,
    "path" text,
    services text,
    version text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_startup_binary (
    "index" text,
    host_id text,
    altered text,
    cve_count text,
    deps jsonb,
    file_mode text,
    function_layer text,
    md_5 text,
    missing_pkg text,
    "name" text,
    "path" text,
    pkg_root_dir text,
    services jsonb,
    version text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_package_pkgs (
    "index" text,
    host_package_host_id text,
    host_package_index text,
    binary_idx jsonb,
    binary_pkgs jsonb,
    cve_count text,
    layer_time text,
    license text,
    "name" text,
    origin_package_name text,
    purl text,
    version text,
    PRIMARY KEY ("index", host_package_host_id, host_package_index),
    FOREIGN KEY (host_package_host_id) REFERENCES host_package(host_id),
    FOREIGN KEY (host_package_index) REFERENCES host_package("index")
);

CREATE TABLE host_package (
    "index" text,
    host_id text,
    pkgs_type text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_file (
    "index" text,
    host_id text,
    md_5 text,
    "path" text,
    sha_1 text,
    sha_256 text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_application (
    "index" text,
    host_id text,
    installed_from_package text,
    known_vulnerabilities text,
    layer_time text,
    "name" text,
    origin_package_name text,
    "path" text,
    service text,
    version text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_found_secret (
    "index" text,
    host_id text,
    location_in_file text,
    modified_time text,
    "path" text,
    secret_id text,
    snippet text,
    "type" jsonb,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_history_vulnerability_exploit (
    "index" text,
    host_history_index text,
    host_history_vulnerability_index text,
    host_id text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", host_history_index, host_history_vulnerability_index, host_id),
    FOREIGN KEY (host_history_index) REFERENCES host_history_vulnerability(host_history_index),
    FOREIGN KEY (host_history_vulnerability_index) REFERENCES host_history_vulnerability("index"),
    FOREIGN KEY (host_id) REFERENCES host_history_vulnerability(host_id)
);

CREATE TABLE host_history_vulnerability_tag_info (
    "index" text,
    host_history_index text,
    host_history_vulnerability_index text,
    host_id text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", host_history_index, host_history_vulnerability_index, host_id),
    FOREIGN KEY (host_history_index) REFERENCES host_history_vulnerability(host_history_index),
    FOREIGN KEY (host_history_vulnerability_index) REFERENCES host_history_vulnerability("index"),
    FOREIGN KEY (host_id) REFERENCES host_history_vulnerability(host_id)
);

CREATE TABLE host_history_vulnerability (
    "index" text,
    host_history_index text,
    host_id text,
    applicable_rule text,
    binary_pkgs jsonb,
    cause text,
    cri text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    function_layer text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factor jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" text,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", host_history_index, host_id),
    FOREIGN KEY (host_history_index) REFERENCES host_history("index"),
    FOREIGN KEY (host_id) REFERENCES host_history(host_id)
);

CREATE TABLE host_history (
    "index" text,
    host_id text,
    base_layer text,
    created text,
    empty_layer text,
    id text,
    instruction text,
    size_bytes text,
    tags jsonb,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_compliance_issue_exploit (
    "index" text,
    host_compliance_issue_index text,
    host_id text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", host_compliance_issue_index, host_id),
    FOREIGN KEY (host_compliance_issue_index) REFERENCES host_compliance_issue("index"),
    FOREIGN KEY (host_id) REFERENCES host_compliance_issue(host_id)
);

CREATE TABLE host_compliance_issue_vulnerability_tag_info (
    "index" text,
    host_compliance_issue_index text,
    host_id text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", host_compliance_issue_index, host_id),
    FOREIGN KEY (host_compliance_issue_index) REFERENCES host_compliance_issue("index"),
    FOREIGN KEY (host_id) REFERENCES host_compliance_issue(host_id)
);

CREATE TABLE host_compliance_issue (
    "index" text,
    host_id text,
    cause text,
    cri text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    function_layer text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factor jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates text,
    text text,
    title text,
    twistlock text,
    "type" text,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_all_compliance_exploit (
    "index" text,
    host_all_compliance_index text,
    host_id text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", host_all_compliance_index, host_id),
    FOREIGN KEY (host_all_compliance_index) REFERENCES host_all_compliance("index"),
    FOREIGN KEY (host_id) REFERENCES host_all_compliance(host_id)
);

CREATE TABLE host_all_compliance_vulnerability_tag_info (
    "index" text,
    host_all_compliance_index text,
    host_id text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", host_all_compliance_index, host_id),
    FOREIGN KEY (host_all_compliance_index) REFERENCES host_all_compliance("index"),
    FOREIGN KEY (host_id) REFERENCES host_all_compliance(host_id)
);

CREATE TABLE host_all_compliance (
    "index" text,
    host_id text,
    applicable_rules jsonb,
    binary_pkgs jsonb,
    block text,
    cause text,
    cri text,
    custom text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    fix_link text,
    function_layer text,
    grace_period_days text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factors jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" jsonb,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_vulnerability_exploit (
    "index" text,
    host_id text,
    host_vulnerability_index text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", host_id, host_vulnerability_index),
    FOREIGN KEY (host_id) REFERENCES host_vulnerability(host_id),
    FOREIGN KEY (host_vulnerability_index) REFERENCES host_vulnerability("index")
);

CREATE TABLE host_vulnerability_tag_info (
    "index" text,
    host_id text,
    host_vulnerability_index text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", host_id, host_vulnerability_index),
    FOREIGN KEY (host_id) REFERENCES host_vulnerability(host_id),
    FOREIGN KEY (host_vulnerability_index) REFERENCES host_vulnerability("index")
);

CREATE TABLE host_vulnerability (
    "index" text,
    host_id text,
    applicable_rule jsonb,
    binary_pkgs jsonb,
    cause text,
    cri text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    function_layer text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factor jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" jsonb,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_tag (
    "index" text,
    host_id text,
    digest text,
    id text,
    registry text,
    repo text,
    tags text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_device (
    "index" text,
    host_id text,
    ip text,
    "name" text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host_instance (
    "index" text,
    host_id text,
    host text,
    image text,
    modified text,
    registry text,
    repo text,
    tags text,
    PRIMARY KEY ("index", host_id),
    FOREIGN KEY (host_id) REFERENCES host(id)
);

CREATE TABLE host (
    id text,
    agentless text,
    ais_uuid text,
    all_compliance_enabled text,
    app_embedded text,
    base_image text,
    cloud_metadata_account_id text,
    cloud_metadata_image text,
    cloud_metadata_name text,
    cloud_metadata_provider jsonb,
    cloud_metadata_region text,
    cloud_metadata_resource_id text,
    cluster_type text,
    collections jsonb,
    compliance_distribution_critical text,
    compliance_distribution_high text,
    compliance_distribution_low text,
    compliance_distribution_medium text,
    compliance_distribution_total text,
    compliance_issues_count text,
    compliance_risk_score text,
    compressed text,
    creation_time text,
    csa text,
    distro text,
    ecs_cluster_name text,
    err text,
    err_code text,
    firewall_protection_enabled text,
    firewall_protection_out_of_band_mode jsonb,
    firewall_protection_supported text,
    first_scan_time text,
    host_runtime_enabled text,
    hostname text,
    hosts jsonb,
    image_created text,
    installed_products_has_package_manager text,
    installed_products_os_distro text,
    is_arm_64 text,
    k_8_s_cluster_addr text,
    labels jsonb,
    malware_analyzed_time text,
    missing_distro_vuln_coverage text,
    os_distro text,
    os_distro_release text,
    os_distro_version text,
    package_manager text,
    pull_duration text,
    push_time text,
    red_hat_non_rpm_image text,
    registry_namespace text,
    registry_type text,
    repo text,
    repo_digest text,
    repo_digests jsonb,
    repo_id text,
    repo_registry text,
    repo_tag text,
    risk_factor jsonb,
    scan_build_date text,
    scan_duration text,
    scan_id text,
    scan_time timestamp,
    scan_version text,
    secret_scan_metrics_failed_scans text,
    secret_scan_metrics_found_secrets text,
    secret_scan_metrics_scan_time text,
    secret_scan_metrics_scan_timeout text,
    secret_scan_metrics_scanned_file_size text,
    secret_scan_metrics_scanned_files text,
    secret_scan_metrics_total_bytes text,
    secret_scan_metrics_total_files text,
    secret_scan_metrics_total_time text,
    secret_scan_metrics_types_count jsonb,
    secrets jsonb,
    stopped text,
    top_layer text,
    trust_status text,
    twistlock_image text,
    "type" text,
    vulnerabilities_count text,
    vulnerability_distribution_critical text,
    vulnerability_distribution_high text,
    vulnerability_distribution_low text,
    vulnerability_distribution_medium text,
    vulnerability_distribution_total text,
    vulnerability_risk_score text,
    wild_fire_usage_bytes text,
    wild_fire_usage_queries text,
    wild_fire_usage_uploads text,
    PRIMARY KEY (id)
);

CREATE TABLE image_binary (
    "index" text,
    image_id text,
    cve_count text,
    file_mode text,
    md_5 text,
    missing_pkg text,
    "name" text,
    "path" text,
    version text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_startup_binary (
    "index" text,
    image_id text,
    cve_count text,
    file_mode text,
    md_5 text,
    "name" text,
    "path" text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_package_pkgs (
    "index" text,
    image_id text,
    image_package_index text,
    binary_idx jsonb,
    binary_pkgs jsonb,
    cve_count text,
    layer_time text,
    license text,
    "name" text,
    origin_package_name text,
    purl text,
    version text,
    PRIMARY KEY ("index", image_id, image_package_index),
    FOREIGN KEY (image_id) REFERENCES image_package(image_id),
    FOREIGN KEY (image_package_index) REFERENCES image_package("index")
);

CREATE TABLE image_package (
    "index" text,
    image_id text,
    pkgs_type text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_file (
    "index" text,
    image_id text,
    md_5 text,
    "path" text,
    sha_1 text,
    sha_256 text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_application (
    "index" text,
    image_id text,
    installed_from_package text,
    known_vulnerabilities text,
    layer_time text,
    "name" text,
    origin_package_name text,
    "path" text,
    version text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_found_secret (
    "index" text,
    image_id text,
    location_in_file text,
    modified_time text,
    "path" text,
    secret_id text,
    snippet text,
    "type" jsonb,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_history_vulnerability_exploit (
    "index" text,
    image_history_index text,
    image_history_vulnerability_index text,
    image_id text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", image_history_index, image_history_vulnerability_index, image_id),
    FOREIGN KEY (image_history_index) REFERENCES image_history_vulnerability(image_history_index),
    FOREIGN KEY (image_history_vulnerability_index) REFERENCES image_history_vulnerability("index"),
    FOREIGN KEY (image_id) REFERENCES image_history_vulnerability(image_id)
);

CREATE TABLE image_history_vulnerability_tag_info (
    "index" text,
    image_history_index text,
    image_history_vulnerability_index text,
    image_id text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", image_history_index, image_history_vulnerability_index, image_id),
    FOREIGN KEY (image_history_index) REFERENCES image_history_vulnerability(image_history_index),
    FOREIGN KEY (image_history_vulnerability_index) REFERENCES image_history_vulnerability("index"),
    FOREIGN KEY (image_id) REFERENCES image_history_vulnerability(image_id)
);

CREATE TABLE image_history_vulnerability (
    "index" text,
    image_history_index text,
    image_id text,
    applicable_rule text,
    binary_pkgs jsonb,
    cause text,
    cri text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    function_layer text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factor jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" jsonb,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", image_history_index, image_id),
    FOREIGN KEY (image_history_index) REFERENCES image_history("index"),
    FOREIGN KEY (image_id) REFERENCES image_history(image_id)
);

CREATE TABLE image_history (
    "index" text,
    image_id text,
    created text,
    empty_layer text,
    id text,
    instruction text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_compliance_issue_exploit (
    "index" text,
    image_compliance_issue_index text,
    image_id text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", image_compliance_issue_index, image_id),
    FOREIGN KEY (image_compliance_issue_index) REFERENCES image_compliance_issue("index"),
    FOREIGN KEY (image_id) REFERENCES image_compliance_issue(image_id)
);

CREATE TABLE image_compliance_issue_vulnerability_tag_info (
    "index" text,
    image_compliance_issue_index text,
    image_id text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", image_compliance_issue_index, image_id),
    FOREIGN KEY (image_compliance_issue_index) REFERENCES image_compliance_issue("index"),
    FOREIGN KEY (image_id) REFERENCES image_compliance_issue(image_id)
);

CREATE TABLE image_compliance_issue (
    "index" text,
    image_id text,
    cause text,
    cri text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    function_layer text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factors jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" jsonb,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_all_compliance_exploit (
    "index" text,
    image_all_compliance_index text,
    image_id text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", image_all_compliance_index, image_id),
    FOREIGN KEY (image_all_compliance_index) REFERENCES image_all_compliance("index"),
    FOREIGN KEY (image_id) REFERENCES image_all_compliance(image_id)
);

CREATE TABLE image_all_compliance_vulnerability_tag_info (
    "index" text,
    image_all_compliance_index text,
    image_id text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", image_all_compliance_index, image_id),
    FOREIGN KEY (image_all_compliance_index) REFERENCES image_all_compliance("index"),
    FOREIGN KEY (image_id) REFERENCES image_all_compliance(image_id)
);

CREATE TABLE image_all_compliance (
    "index" text,
    image_id text,
    applicable_rules jsonb,
    binary_pkgs jsonb,
    block text,
    cause text,
    cri text,
    custom text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    fix_link text,
    function_layer text,
    grace_period_days text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factors jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" jsonb,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_vulnerability_exploit (
    "index" text,
    image_id text,
    image_vulnerability_index text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", image_id, image_vulnerability_index),
    FOREIGN KEY (image_id) REFERENCES image_vulnerability(image_id),
    FOREIGN KEY (image_vulnerability_index) REFERENCES image_vulnerability("index")
);

CREATE TABLE image_vulnerability_tag_info (
    "index" text,
    image_id text,
    image_vulnerability_index text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", image_id, image_vulnerability_index),
    FOREIGN KEY (image_id) REFERENCES image_vulnerability(image_id),
    FOREIGN KEY (image_vulnerability_index) REFERENCES image_vulnerability("index")
);

CREATE TABLE image_vulnerability (
    "index" text,
    image_id text,
    applicable_rule text,
    binary_pkgs jsonb,
    cause text,
    cri text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    function_layer text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factors jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" jsonb,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_tag (
    "index" text,
    image_id text,
    registry text,
    repo text,
    tags text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image_instance (
    "index" text,
    image_id text,
    host text,
    image text,
    modified text,
    registry text,
    repo text,
    tags text,
    PRIMARY KEY ("index", image_id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);

CREATE TABLE image (
    id text,
    hostname text,
    agentless text,
    ais_uuid text,
    app_embedded text,
    base_image text,
    cloud_metadata_account_id text,
    cloud_metadata_image text,
    cloud_metadata_name text,
    cloud_metadata_provider jsonb,
    cloud_metadata_region text,
    cloud_metadata_resource_id text,
    cluster_type text,
    clusters jsonb,
    collections jsonb,
    compliance_distribution_critical text,
    compliance_distribution_high text,
    compliance_distribution_low text,
    compliance_distribution_medium text,
    compliance_distribution_total text,
    compliance_issues_count text,
    compliance_risk_score text,
    compressed text,
    creation_time text,
    csa text,
    distro text,
    ecs_cluster_name text,
    err text,
    err_code text,
    firewall_protection_enabled text,
    firewall_protection_out_of_band_mode jsonb,
    firewall_protection_supported text,
    first_scan_time text,
    host_runtime_enabled text,
    hosts jsonb,
    image_created text,
    image_entry_point jsonb,
    installed_products_crio text,
    installed_products_has_package_manager text,
    installed_products_os_distro text,
    is_arm_64 text,
    k_8_s_cluster_addr text,
    layers jsonb,
    malware_analyzed_time text,
    missing_distro_vuln_coverage text,
    namespaces jsonb,
    os_distro text,
    os_distro_release text,
    os_distro_version text,
    package_manager text,
    pull_duration text,
    push_time text,
    red_hat_non_rpm_image text,
    registry_namespace text,
    registry_type text,
    repo text,
    repo_digests jsonb,
    repo_registry text,
    repo_tag text,
    risk_factors jsonb,
    scan_build_date text,
    scan_duration text,
    scan_id text,
    scan_time timestamp,
    scan_version text,
    secret_scan_metrics_failed_scans text,
    secret_scan_metrics_found_secrets text,
    secret_scan_metrics_scan_time text,
    secret_scan_metrics_scan_timeout text,
    secret_scan_metrics_scanned_file_size text,
    secret_scan_metrics_scanned_files text,
    secret_scan_metrics_total_bytes text,
    secret_scan_metrics_total_iles text,
    secret_scan_metrics_total_time text,
    secret_scan_metrics_types_count jsonb,
    secrets jsonb,
    stopped text,
    top_layer text,
    trust_status text,
    twistlock_image text,
    "type" text,
    vulnerabilities_count text,
    vulnerability_distribution_critical text,
    vulnerability_distribution_high text,
    vulnerability_distribution_low text,
    vulnerability_distribution_medium text,
    vulnerability_distribution_total text,
    vulnerability_risk_score text,
    wild_fire_usage_bytes text,
    wild_fire_usage_queries text,
    wild_fire_usage_uploads text,
    PRIMARY KEY (id),
    FOREIGN KEY (hostname) REFERENCES host(id)
);

CREATE TABLE container_all_compliance_exploit (
    "index" text,
    container_all_compliance_index text,
    container_id text,
    kind jsonb,
    link text,
    "source" jsonb,
    PRIMARY KEY ("index", container_all_compliance_index, container_id),
    FOREIGN KEY (container_all_compliance_index) REFERENCES container_all_compliance("index"),
    FOREIGN KEY (container_id) REFERENCES container_all_compliance(container_id)
);

CREATE TABLE container_all_compliance_vulnerability_tag_info (
    "index" text,
    container_all_compliance_index text,
    container_id text,
    color text,
    "comment" text,
    "name" text,
    PRIMARY KEY ("index", container_all_compliance_index, container_id),
    FOREIGN KEY (container_all_compliance_index) REFERENCES container_all_compliance("index"),
    FOREIGN KEY (container_id) REFERENCES container_all_compliance(container_id)
);

CREATE TABLE container_all_compliance (
    "index" text,
    container_id text,
    applicable_rules jsonb,
    binary_pkgs jsonb,
    block text,
    cause text,
    cri text,
    custom text,
    cve text,
    cvss text,
    description text,
    discovered text,
    exploit jsonb,
    fix_date text,
    fix_link text,
    function_layer text,
    grace_period_days text,
    layer_time text,
    link text,
    package_name text,
    package_type jsonb,
    package_version text,
    published text,
    risk_factor jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    secret_type jsonb,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    "type" jsonb,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", container_id),
    FOREIGN KEY (container_id) REFERENCES container(id)
);

CREATE TABLE container_info_compliance_issue (
    "index" text,
    container_id text,
    block text,
    cause text,
    cri text,
    custom text,
    cve text,
    cvss text,
    description text,
    discovered text,
    fix_date text,
    fix_link text,
    function_layer text,
    grace_period_days text,
    layer_time text,
    link text,
    package_name text,
    package_version text,
    published text,
    risk_factors jsonb,
    secret_id text,
    secret_location_in_file text,
    secret_modified_time text,
    secret_path text,
    secret_snippet text,
    severity text,
    "status" text,
    templates jsonb,
    text text,
    title text,
    twistlock text,
    vec_str text,
    violation_id text,
    wildfire_malware_md_5 text,
    wildfire_malware_path text,
    wildfire_malware_verdict text,
    PRIMARY KEY ("index", container_id),
    FOREIGN KEY (container_id) REFERENCES container(id)
);

CREATE TABLE container_info_network_port (
    "index" text,
    container_id text,
    container text,
    host text,
    host_ip text,
    listening text,
    nat text,
    PRIMARY KEY ("index", container_id),
    FOREIGN KEY (container_id) REFERENCES container(id)
);

CREATE TABLE container_process (
    "index" text,
    container_id text,
    "name" text,
    PRIMARY KEY ("index", container_id),
    FOREIGN KEY (container_id) REFERENCES container(id)
);

CREATE TABLE container (
    id text,
    hostname text,
    image_id text,
    agent_less text,
    agent_less_scan_id text,
    ais text,
    cloud_metadata_account_id text,
    cloud_metadata_image text,
    cloud_metadata_name text,
    cloud_metadata_provider jsonb,
    cloud_metadata_region text,
    cloud_metadata_resource_id text,
    collections jsonb,
    compliance_distribution_critical text,
    compliance_distribution_high text,
    compliance_distribution_low text,
    compliance_distribution_medium text,
    compliance_distribution_total text,
    csa text,
    firewall_protection_enabled text,
    firewall_protection_out_of_band_mode jsonb,
    firewall_protection_ports jsonb,
    firewall_protection_supported text,
    firewall_protection_tls_ports jsonb,
    info_all_compliance_enabled text,
    info_app text,
    info_cluster text,
    info_cluster_type text,
    info_compliance_issues_count text,
    info_compliance_risk_score text,
    info_image text,
    info_image_name text,
    info_infra text,
    info_labels jsonb,
    info_name text,
    info_namespace text,
    info_profile_id text,
    info_size_byte text,
    info_start_time text,
    installed_products_agentless text,
    installed_products_apache text,
    installed_products_aws_cloud text,
    installed_products_cluster_type text,
    installed_products_crio text,
    installed_products_docker text,
    installed_products_docker_enterprise text,
    installed_products_has_package_manager text,
    installed_products_k_8_s_api_server text,
    installed_products_k_8_s_controller_manager text,
    installed_products_k_8_s_etcd text,
    installed_products_k_8_s_federation_api_server text,
    installed_products_k_8_s_federation_controller_manager text,
    installed_products_k_8_s_kubelet text,
    installed_products_k_8_s_proxy text,
    installed_products_k_8_s_scheduler text,
    installed_products_kubernetes text,
    installed_products_managed_cluster_version text,
    installed_products_openshift text,
    installed_products_openshift_version text,
    installed_products_os_distro text,
    installed_products_serverless text,
    installed_products_swarm_manager text,
    installed_products_swarm_node text,
    runtime_enabled text,
    scan_time timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (hostname) REFERENCES host(id),
    FOREIGN KEY (image_id) REFERENCES image(id)
);
