CREATE TABLE budget_modification (
    id text,
    company_id text,
    project_id text,
    created_at text,
    from_budget_line_item_id text,
    notes text,
    origin_data text,
    origin_id text,
    to_budget_line_item_id text,
    transfer_amount text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project (
    id text,
    company_id text,
    owners_project_id text,
    project_stage_id text,
    accounting_project_number text,
    active text,
    address_street text,
    city text,
    completion_date text,
    country_code text,
    county text,
    created_at text,
    custom_fields jsonb,
    designated_market_area text,
    display_name text,
    estimated_value text,
    is_demo text,
    latitude text,
    longitude text,
    "name" text,
    origin_code text,
    origin_data text,
    origin_id text,
    parent_job_id text,
    phone text,
    photo_id text,
    project_bid_type_id text,
    project_number text,
    project_owner_type_id text,
    project_region_id text,
    project_template_id text,
    project_template_name text,
    stage text,
    start_date text,
    state_code text,
    store_number text,
    time_zone text,
    total_value text,
    updated_at timestamp,
    zip text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (owners_project_id) REFERENCES project(id),
    FOREIGN KEY (project_stage_id) REFERENCES project_stage(id)
);

CREATE TABLE project_membership (
    id text,
    company_id text,
    project_id text,
    party_id text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_vendor (
    company_id text,
    project_id text,
    vendor_id text,
    PRIMARY KEY (company_id, project_id, vendor_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (vendor_id) REFERENCES company_vendor(id)
);

CREATE TABLE project_people (
    id text,
    company_id text,
    project_id text,
    user_uuid text,
    user_id text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (user_uuid) REFERENCES project_user(id)
);

CREATE TABLE timecard_entry_crew_employee (
    id text,
    timecard_entry_id text,
    login text,
    "name" text,
    PRIMARY KEY (id, timecard_entry_id),
    FOREIGN KEY (timecard_entry_id) REFERENCES timecard_entry(id)
);

CREATE TABLE timecard_entry (
    id text,
    company_id text,
    project_id text,
    cost_code_id text,
    approval_status text,
    billable text,
    created_at text,
    crew_company_id text,
    crew_created_at text,
    crew_created_by_id text,
    crew_created_by_login text,
    crew_created_by_name text,
    crew_id text,
    crew_lead_id text,
    crew_lead_login text,
    crew_lead_name text,
    crew_name text,
    crew_project_id text,
    crew_updated_at text,
    custom_fields jsonb,
    "date" text,
    datetime text,
    deleted_at text,
    description text,
    hours text,
    injured text,
    line_item_type_id text,
    location_created_at text,
    location_id text,
    location_name text,
    location_node_name text,
    location_parent_id text,
    location_updated_at text,
    login_information_id text,
    login_information_login text,
    login_information_name text,
    lunch_time text,
    origin_data text,
    origin_id text,
    party_id text,
    party_name text,
    procore_signature_created_by text,
    procore_signature_created_by_id text,
    procore_signature_created_by_login text,
    procore_signature_created_by_name text,
    procore_signature_file_name text,
    procore_signature_id text,
    procore_signature_large_thumbnail_url text,
    procore_signature_medium_thumbnail_url text,
    procore_signature_signature_text text,
    procore_signature_url text,
    signed text,
    sub_job_code text,
    sub_job_id text,
    sub_job_name text,
    time_in text,
    time_out text,
    timecard_time_type_abbreviated_time_type text,
    timecard_time_type_company_id text,
    timecard_time_type_global text,
    timecard_time_type_id text,
    timecard_time_type_time_type text,
    timesheet_created_at text,
    timesheet_created_by_id text,
    timesheet_created_by_login text,
    timesheet_created_by_name text,
    timesheet_date text,
    timesheet_id text,
    timesheet_name text,
    timesheet_number text,
    timesheet_status text,
    timesheet_updated_at text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (cost_code_id) REFERENCES cost_code(id)
);

CREATE TABLE budget_segment_item_path_name (
    path_name text,
    budget_detail_id text,
    budget_detail_segment_item_id text,
    PRIMARY KEY (path_name, budget_detail_id, budget_detail_segment_item_id),
    FOREIGN KEY (budget_detail_id) REFERENCES budget_detail_segment_item(budget_detail_id),
    FOREIGN KEY (budget_detail_segment_item_id) REFERENCES budget_detail_segment_item(id)
);

CREATE TABLE budget_segment_item_path_code (
    path_code text,
    budget_detail_id text,
    budget_detail_segment_item_id text,
    PRIMARY KEY (path_code, budget_detail_id, budget_detail_segment_item_id),
    FOREIGN KEY (budget_detail_id) REFERENCES budget_detail_segment_item(budget_detail_id),
    FOREIGN KEY (budget_detail_segment_item_id) REFERENCES budget_detail_segment_item(id)
);

CREATE TABLE budget_segment_item_path (
    path_id text,
    budget_detail_id text,
    budget_detail_segment_item_id text,
    PRIMARY KEY (path_id, budget_detail_id, budget_detail_segment_item_id),
    FOREIGN KEY (budget_detail_id) REFERENCES budget_detail_segment_item(budget_detail_id),
    FOREIGN KEY (budget_detail_segment_item_id) REFERENCES budget_detail_segment_item(id)
);

CREATE TABLE budget_detail_segment_item (
    id text,
    budget_detail_id text,
    code text,
    created_at text,
    is_parent text,
    "name" text,
    parent_id text,
    path_code text,
    segment_created_at text,
    segment_delimiter text,
    segment_id text,
    segment_name text,
    segment_position text,
    segment_project_can_delete_origin_company text,
    segment_project_can_modify_origin_project text,
    segment_required text,
    segment_segment_items_count text,
    segment_structure text,
    segment_type text,
    segment_updated_at text,
    segment_wbs_pattern_id text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id, budget_detail_id),
    FOREIGN KEY (budget_detail_id) REFERENCES budget_detail(id)
);

CREATE TABLE budget_detail (
    id text,
    budget_view_id text,
    company_id text,
    cost_code_id text,
    root_cost_code_id text,
    vendor_id text,
    contract_id text,
    contract_name text,
    cost_type_id text,
    cost_type_name text,
    detail_type_id text,
    detail_type_name text,
    item text,
    link text,
    root_cost_code_name text,
    wbs_code_description text,
    wbs_code_flat_code text,
    wbs_code_flat_name text,
    wbs_code_id text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, budget_view_id, company_id),
    FOREIGN KEY (budget_view_id) REFERENCES budget_view(id),
    FOREIGN KEY (company_id) REFERENCES budget_view(company_id),
    FOREIGN KEY (cost_code_id) REFERENCES cost_code(id),
    FOREIGN KEY (root_cost_code_id) REFERENCES cost_code(parent_id),
    FOREIGN KEY (vendor_id) REFERENCES company_vendor(id)
);

CREATE TABLE sub_job (
    id text,
    company_id text,
    project_id text,
    code text,
    created_at text,
    "name" text,
    origin_data text,
    origin_id text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_role (
    id text,
    company_id text,
    project_id text,
    user_id text,
    created_at text,
    is_active text,
    "name" text,
    "role" text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (user_id) REFERENCES project_user(id)
);

CREATE TABLE checklist_item_type (
    id text,
    company_id text,
    project_id text,
    category text,
    "name" text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE company_office (
    id text,
    company_id text,
    address text,
    city text,
    country_code text,
    division text,
    fax text,
    logo_filename text,
    logo_id text,
    logo_name text,
    logo_url text,
    "name" text,
    phone text,
    state_code text,
    zip text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE project_date (
    id text,
    schedule_date_fivetran_id text,
    "date" text,
    "name" text,
    project_membership_id text,
    PRIMARY KEY (id, schedule_date_fivetran_id),
    FOREIGN KEY (schedule_date_fivetran_id) REFERENCES schedule_date(_fivetran_id)
);

CREATE TABLE schedule_date (
    _fivetran_id text,
    company_id text,
    project_id text,
    finish_variance text,
    percentage_complete text,
    substantial_completion_date text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE budget_view_summary_row_line_item (
    budget_line_item_id text,
    budget_view_summary_row_id text,
    PRIMARY KEY (budget_line_item_id, budget_view_summary_row_id),
    FOREIGN KEY (budget_view_summary_row_id) REFERENCES budget_view_summary_row(id)
);

CREATE TABLE budget_view_summary_row (
    id text,
    budget_view_id text,
    company_id text,
    project_id text,
    biller_type text,
    budget_forecast_amount text,
    budget_modifications text,
    currency_configuration_iso_code text,
    "name" text,
    original_budget_amount text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, budget_view_id, company_id, project_id),
    FOREIGN KEY (budget_view_id) REFERENCES budget_view(id),
    FOREIGN KEY (company_id) REFERENCES budget_view(company_id),
    FOREIGN KEY (project_id) REFERENCES budget_view(project_id)
);

CREATE TABLE project_user (
    company_id text,
    id text,
    project_id text,
    company_permission_template_id text,
    company_permission_template_name text,
    company_permission_template_project_specific text,
    company_permission_template_type text,
    created_at text,
    email_signature text,
    last_login_at text,
    notes text,
    origin_data text,
    permission_template_id text,
    permission_template_name text,
    permission_template_project_specific text,
    permission_template_type text,
    updated_at text,
    welcome_email_sent_at text,
    PRIMARY KEY (company_id, id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (id) REFERENCES company_user(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE company_checklist_template (
    id text,
    company_id text,
    inspection_type_id text,
    created_at text,
    description text,
    "name" text,
    trade_active text,
    trade_id text,
    trade_name text,
    trade_updated_at text,
    updated_at text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (inspection_type_id) REFERENCES inspection_type(id)
);

CREATE TABLE project_injury_body_part (
    id text,
    project_injury_id text,
    created_at text,
    "name" text,
    parent_id text,
    selectable text,
    updated_at text,
    PRIMARY KEY (id, project_injury_id),
    FOREIGN KEY (project_injury_id) REFERENCES project_injury(id)
);

CREATE TABLE project_injury_affliction (
    id text,
    project_injury_id text,
    affected_body_part text,
    affliction_type_active text,
    affliction_type_created_at text,
    affliction_type_global text,
    affliction_type_id text,
    affliction_type_name text,
    affliction_type_updated_at text,
    PRIMARY KEY (id, project_injury_id),
    FOREIGN KEY (project_injury_id) REFERENCES project_injury(id)
);

CREATE TABLE project_injury_affected_body_part (
    "index" text,
    project_injury_id text,
    affected_body_part text,
    PRIMARY KEY ("index", project_injury_id),
    FOREIGN KEY (project_injury_id) REFERENCES project_injury(id)
);

CREATE TABLE project_injury (
    id text,
    company_id text,
    project_id text,
    affected_body_part text,
    affected_company_id text,
    affected_company_name text,
    affected_party_id text,
    affected_party_name text,
    affected_person_id text,
    affected_person_login text,
    affected_person_name text,
    affliction_type_active text,
    affliction_type_created_at text,
    affliction_type_global text,
    affliction_type_id text,
    affliction_type_name text,
    affliction_type_updated_at text,
    body_diagram_type text,
    created_at text,
    custom_fields jsonb,
    date_of_death text,
    date_returned_to_work text,
    deleted_at text,
    description text,
    description_plain_text text,
    filing_type text,
    full_number text,
    harm_source_active text,
    harm_source_created_at text,
    harm_source_global text,
    harm_source_id text,
    harm_source_name text,
    harm_source_updated_at text,
    hospitalized_overnight text,
    incident_created_by_id text,
    incident_created_by_login text,
    incident_created_by_name text,
    incident_id text,
    incident_private text,
    incident_title text,
    managed_equipment_id text,
    managed_equipment_name text,
    number text,
    recordable text,
    summary text,
    treated_in_er text,
    treatment_facility text,
    treatment_facility_address text,
    treatment_provider text,
    "type" text,
    updated_at text,
    work_activity_active text,
    work_activity_created_at text,
    work_activity_global text,
    work_activity_id text,
    work_activity_name text,
    work_activity_updated_at text,
    work_days_absent text,
    work_days_restricted text,
    work_days_transferred text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE checklist_item_response_set (
    id text,
    checklist_item_id text,
    item_status_id text,
    "name" text,
    "status" text,
    PRIMARY KEY (id, checklist_item_id),
    FOREIGN KEY (checklist_item_id) REFERENCES checklist_item(id)
);

CREATE TABLE checklist_item (
    id text,
    company_id text,
    project_id text,
    item_responder_id text,
    type_id text,
    company_template_item_details text,
    details text,
    item_response_item_id text,
    item_response_item_type_category text,
    item_response_item_type_id text,
    item_response_item_type_name text,
    item_response_payload_date_value text,
    item_response_payload_number_value text,
    item_response_payload_response_option_id text,
    item_response_payload_response_option_name text,
    item_response_payload_text_value text,
    item_response_responded_at text,
    item_response_status text,
    list_id text,
    "name" text,
    "position" text,
    responded_with text,
    response_corresponding_status text,
    response_id text,
    response_name text,
    response_set_active text,
    response_set_created_at text,
    response_set_deletable text,
    response_set_id text,
    response_set_name text,
    response_set_procore_standard text,
    response_set_updated_at text,
    response_type_id text,
    section_id text,
    "status" text,
    template_item_id text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (item_responder_id) REFERENCES project_user(id),
    FOREIGN KEY (type_id) REFERENCES checklist_item_type(id)
);

CREATE TABLE task (
    id text,
    company_id text,
    project_id text,
    created_by_id text,
    parent_id text,
    updated_by_id text,
    activity_id text,
    actual_finish text,
    actual_start text,
    baseline_finish text,
    baseline_start text,
    color text,
    created_at text,
    critical_path text,
    finish_datetime text,
    finish_variance text,
    full_outline_path text,
    has_children text,
    "key" text,
    manually_edited text,
    milestone text,
    "name" text,
    notes text,
    pending text,
    percentage text,
    resource_ids jsonb,
    resource_name text,
    row_number text,
    schedule_activity_id text,
    schedule_duration text,
    source_uid text,
    start_datetime text,
    start_variance text,
    updated_at text,
    wbs text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (created_by_id) REFERENCES project_user(id),
    FOREIGN KEY (parent_id) REFERENCES task(id),
    FOREIGN KEY (updated_by_id) REFERENCES project_user(id)
);

CREATE TABLE company_vendor_trade (
    id text,
    company_vendor_id text,
    active text,
    "name" text,
    updated_at text,
    PRIMARY KEY (id, company_vendor_id),
    FOREIGN KEY (company_vendor_id) REFERENCES company_vendor(id)
);

CREATE TABLE company_vendor_standard_cost_code (
    id text,
    company_vendor_id text,
    code text,
    full_code text,
    "name" text,
    origin_data text,
    origin_id text,
    parent_id text,
    standard_cost_code_list_id text,
    PRIMARY KEY (id, company_vendor_id),
    FOREIGN KEY (company_vendor_id) REFERENCES company_vendor(id)
);

CREATE TABLE company_vendor_bidding_distribution (
    id text,
    company_vendor_id text,
    company_name text,
    login text,
    "name" text,
    PRIMARY KEY (id, company_vendor_id),
    FOREIGN KEY (company_vendor_id) REFERENCES company_vendor(id)
);

CREATE TABLE company_vendor_attachment (
    id text,
    company_vendor_id text,
    filename text,
    url text,
    PRIMARY KEY (id, company_vendor_id),
    FOREIGN KEY (company_vendor_id) REFERENCES company_vendor(id)
);

CREATE TABLE company_vendor_project (
    company_vendor_id text,
    project_id text,
    PRIMARY KEY (company_vendor_id, project_id),
    FOREIGN KEY (company_vendor_id) REFERENCES company_vendor(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE company_vendor (
    id text,
    company_id text,
    abbreviated_name text,
    address text,
    authorized_bidder text,
    bidding_affirmative_action text,
    bidding_african_american_business text,
    bidding_asian_american_business text,
    bidding_certified_business_enterprise text,
    bidding_disadvantaged_business text,
    bidding_eight_a_business text,
    bidding_hispanic_business text,
    bidding_historically_underutilized_business text,
    bidding_minority_business_enterprise text,
    bidding_native_american_business text,
    bidding_sdvo_business text,
    bidding_small_business text,
    bidding_womens_business text,
    business_id text,
    business_phone text,
    business_register_id text,
    business_register_identifier text,
    business_register_type text,
    business_register_verification_status text,
    business_register_verified_at text,
    children_count text,
    city text,
    company_vendor text,
    contact_count text,
    country_code text,
    created_at text,
    email_address text,
    fax_number text,
    is_active text,
    is_connected text,
    labor_union text,
    legal_name text,
    logo text,
    mobile_phone text,
    "name" text,
    non_union_prevailing_wage text,
    notes text,
    origin_code text,
    origin_id text,
    parent_id text,
    parent_name text,
    prequalified text,
    primary_contact_business_phone text,
    primary_contact_business_phone_extension text,
    primary_contact_created_at text,
    primary_contact_email_address text,
    primary_contact_fax_number text,
    primary_contact_first_name text,
    primary_contact_id text,
    primary_contact_last_name text,
    primary_contact_mobile_phone text,
    primary_contact_updated_at text,
    state_code text,
    synced_to_erp text,
    trade_name text,
    union_member text,
    updated_at text,
    vendor_group_id text,
    vendor_group_name text,
    website text,
    zip text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE submittal_status (
    id text,
    company_id text,
    "name" text,
    "status" text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE checklist_comment (
    id text,
    company_id text,
    project_id text,
    created_by_id text,
    item_id text,
    body text,
    created_at text,
    created_by_login text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (created_by_id) REFERENCES project_user(id),
    FOREIGN KEY (item_id) REFERENCES checklist_item(id)
);

CREATE TABLE budget_view_snapshot (
    id text,
    company_id text,
    project_id text,
    budget_view_id text,
    created_at text,
    created_by_id text,
    created_by_login text,
    created_by_name text,
    description text,
    "name" text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (budget_view_id) REFERENCES budget_view(id)
);

CREATE TABLE budget_view_detail_row (
    id text,
    budget_view_id text,
    company_id text,
    project_id text,
    cost_code_id text,
    wbs_code_id text,
    budget_forecast_amount text,
    budget_forecast_automatic_amount text,
    budget_forecast_automatically_calculated text,
    budget_forecast_calculation_strategy text,
    budget_forecast_id text,
    budget_forecast_manual_amount text,
    budget_forecast_notes text,
    budget_modifications text,
    budget_row_id text,
    category text,
    category_id text,
    cost_code text,
    cost_code_origin_id text,
    currency_configuration_iso_code text,
    deletable text,
    original_budget_amount text,
    root_cost_code_id text,
    unbudgeted_reason text,
    uom text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, budget_view_id, company_id, project_id),
    FOREIGN KEY (budget_view_id) REFERENCES budget_view(id),
    FOREIGN KEY (company_id) REFERENCES budget_view(company_id),
    FOREIGN KEY (project_id) REFERENCES budget_view(project_id),
    FOREIGN KEY (cost_code_id) REFERENCES cost_code(id),
    FOREIGN KEY (wbs_code_id) REFERENCES budget_detail(wbs_code_id)
);

CREATE TABLE task_item (
    id text,
    company_id text,
    project_id text,
    assignee_id text,
    created_at text,
    date_notified text,
    description text,
    due_date text,
    number text,
    private text,
    "status" text,
    task_item_category_id text,
    task_item_category_name text,
    title text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (assignee_id) REFERENCES project_user(id)
);

CREATE TABLE budget_view_snapshot_detail_segment_item_path (
    "index" text,
    budget_view_snapshot_detail_row_fivetran_id text,
    budget_view_snapshot_detail_segment_item_index text,
    path_id text,
    PRIMARY KEY ("index", budget_view_snapshot_detail_row_fivetran_id, budget_view_snapshot_detail_segment_item_index),
    FOREIGN KEY (budget_view_snapshot_detail_row_fivetran_id) REFERENCES budget_view_snapshot_detail_segment_item(budget_view_snapshot_detail_row_fivetran_id),
    FOREIGN KEY (budget_view_snapshot_detail_segment_item_index) REFERENCES budget_view_snapshot_detail_segment_item("index")
);

CREATE TABLE budget_view_snapshot_detail_segment_item_path_code (
    "index" text,
    budget_view_snapshot_detail_row_fivetran_id text,
    budget_view_snapshot_detail_segment_item_index text,
    path_code text,
    PRIMARY KEY ("index", budget_view_snapshot_detail_row_fivetran_id, budget_view_snapshot_detail_segment_item_index),
    FOREIGN KEY (budget_view_snapshot_detail_row_fivetran_id) REFERENCES budget_view_snapshot_detail_segment_item(budget_view_snapshot_detail_row_fivetran_id),
    FOREIGN KEY (budget_view_snapshot_detail_segment_item_index) REFERENCES budget_view_snapshot_detail_segment_item("index")
);

CREATE TABLE budget_view_snapshot_detail_segment_item (
    "index" text,
    budget_view_snapshot_detail_row_fivetran_id text,
    code text,
    id text,
    is_parent text,
    "name" text,
    segment_id text,
    segment_name text,
    segment_structure text,
    segment_type text,
    PRIMARY KEY ("index", budget_view_snapshot_detail_row_fivetran_id),
    FOREIGN KEY (budget_view_snapshot_detail_row_fivetran_id) REFERENCES budget_view_snapshot_detail_row(_fivetran_id)
);

CREATE TABLE budget_view_snapshot_detail_row (
    _fivetran_id text,
    budget_view_snapshot_id text,
    company_id text,
    project_id text,
    biller_id text,
    budget_modifications text,
    budget_row_id text,
    category text,
    category_id text,
    cost_code text,
    cost_code_id text,
    cost_code_origin_id text,
    currency_configuration_iso_code text,
    deletable text,
    id text,
    original_budget_amount text,
    quantity text,
    root_cost_code text,
    root_cost_code_id text,
    unbudgeted_reason text,
    unit_cost text,
    wbs_code_id text,
    -- custom_* (dynamic column),
    PRIMARY KEY (_fivetran_id, budget_view_snapshot_id, company_id, project_id),
    FOREIGN KEY (budget_view_snapshot_id) REFERENCES budget_view_snapshot(id),
    FOREIGN KEY (company_id) REFERENCES budget_view_snapshot(company_id),
    FOREIGN KEY (project_id) REFERENCES budget_view_snapshot(project_id),
    FOREIGN KEY (biller_id) REFERENCES project(id)
);

CREATE TABLE project_stage (
    id text,
    company_id text,
    category text,
    is_bidding_stage text,
    "name" text,
    read_only text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company (
    id text,
    company_home_url text,
    is_active text,
    logo_url text,
    my_company text,
    "name" text,
    pcn_business_experience text,
    PRIMARY KEY (id)
);

CREATE TABLE task_item_comment (
    id text,
    company_id text,
    project_id text,
    task_item_id text,
    attachment_filename text,
    attachment_id text,
    attachment_url text,
    "comment" text,
    created_at text,
    created_by_id text,
    created_by_login text,
    created_by_name text,
    "status" text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (task_item_id) REFERENCES task_item(id)
);

CREATE TABLE observation (
    id text,
    company_id text,
    project_id text,
    assignee_id text,
    checklist_item_id text,
    vendor_id text,
    closed_at text,
    created_at text,
    created_by text,
    custom_fields jsonb,
    date_notified text,
    deleted_at text,
    description text,
    description_rich_text text,
    due_date text,
    location_created_at text,
    location_id text,
    location_name text,
    location_node_name text,
    location_parent_id text,
    location_updated_at text,
    "name" text,
    number text,
    observation_type_active text,
    observation_type_category text,
    observation_type_category_id text,
    observation_type_category_key text,
    observation_type_company_active text,
    observation_type_id text,
    observation_type_in_use text,
    observation_type_kind text,
    observation_type_localized_name text,
    observation_type_name text,
    observation_type_name_translations jsonb,
    observation_type_parent_inactive text,
    origin_bim_model_id text,
    origin_bim_model_name text,
    origin_checklist_item_id text,
    origin_coordination_issue_id text,
    origin_coordination_issue_number text,
    origin_incident_action_id text,
    origin_incident_id text,
    origin_type text,
    personal text,
    priority text,
    specification_section_description text,
    specification_section_id text,
    specification_section_latest_revision_url text,
    specification_section_number text,
    "status" text,
    trade_active text,
    trade_id text,
    trade_name text,
    trade_updated_at text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (assignee_id) REFERENCES company_user(id),
    FOREIGN KEY (checklist_item_id) REFERENCES checklist_item(id),
    FOREIGN KEY (vendor_id) REFERENCES company_vendor(id)
);

CREATE TABLE checklist_schedule_assignee (
    assignee_id text,
    checklist_schedule_id text,
    PRIMARY KEY (assignee_id, checklist_schedule_id),
    FOREIGN KEY (checklist_schedule_id) REFERENCES checklist_schedule(id)
);

CREATE TABLE checklist_schedule (
    id text,
    company_id text,
    project_id text,
    created_at text,
    ends_at text,
    first_inspection_due_at text,
    frequency text,
    inspection_template_description text,
    inspection_template_id text,
    inspection_template_name text,
    inspection_template_trade_id text,
    inspection_template_type_id text,
    inspection_template_type_name text,
    inspections_created text,
    location_id text,
    "name" text,
    next_due_at text,
    point_of_contact_id text,
    responsible_contractor_id text,
    total_inspections_scheduled text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_incident (
    id text,
    company_id text,
    project_id text,
    actions_count text,
    attachments_count text,
    closed_observations_count text,
    contributing_behavior_active text,
    contributing_behavior_created_at text,
    contributing_behavior_global text,
    contributing_behavior_id text,
    contributing_behavior_name text,
    contributing_behavior_updated_at text,
    contributing_condition_active text,
    contributing_condition_created_at text,
    contributing_condition_global text,
    contributing_condition_id text,
    contributing_condition_name text,
    contributing_condition_updated_at text,
    created_at text,
    created_by_id text,
    created_by_login text,
    created_by_name text,
    custom_fields jsonb,
    deleted_at text,
    description text,
    event_date text,
    hazard_active text,
    hazard_created_at text,
    hazard_global text,
    hazard_id text,
    hazard_name text,
    hazard_updated_at text,
    location_created_at text,
    location_id text,
    location_name text,
    location_node_name text,
    location_parent_id text,
    location_updated_at text,
    open_observations_count text,
    private text,
    recordable text,
    records_count text,
    "status" text,
    time_unknown text,
    title text,
    updated_at text,
    witness_statements_count text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE company_user (
    id text,
    company_id text,
    vendor_id text,
    work_classification_id text,
    address text,
    avatar text,
    bid_contact text,
    business_id text,
    business_phone text,
    business_phone_extension text,
    city text,
    contact_id text,
    country_code text,
    email_address text,
    employee_id text,
    erp_integrated_accountant text,
    fax_number text,
    first_name text,
    initials text,
    is_active text,
    is_employee text,
    job_title text,
    last_name text,
    mobile_phone text,
    "name" text,
    origin_id text,
    "role" text,
    state_code text,
    verified_employee text,
    zip text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (vendor_id) REFERENCES project_vendor(vendor_id),
    FOREIGN KEY (work_classification_id) REFERENCES project_level_work_classification(id)
);

CREATE TABLE work_classification_project (
    project_id text,
    project_level_work_classification_id text,
    PRIMARY KEY (project_id, project_level_work_classification_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (project_level_work_classification_id) REFERENCES project_level_work_classification(id)
);

CREATE TABLE project_level_work_classification (
    id text,
    company_id text,
    project_id text,
    abbreviation text,
    company_visible text,
    created_at text,
    created_by_id text,
    "name" text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE checklist_schedule_attachment (
    id text,
    checklist_schedule_id text,
    project_id text,
    attachment_file_name text,
    attachment_name text,
    attachment_url text,
    content_type text,
    created_at text,
    file_id text,
    schedule_id text,
    thumbnail_url text,
    viewable_document_id text,
    PRIMARY KEY (id, checklist_schedule_id, project_id),
    FOREIGN KEY (checklist_schedule_id) REFERENCES checklist_schedule(id),
    FOREIGN KEY (project_id) REFERENCES checklist_schedule(project_id)
);

CREATE TABLE budget_view (
    id text,
    company_id text,
    project_id text,
    created_at text,
    created_by_id text,
    created_by_login text,
    created_by_name text,
    description text,
    "name" text,
    "role" text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE submittal_type (
    id text,
    company_id text,
    "name" text,
    translated_name text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company_schedule_project (
    company_id text,
    company_schedule_date text,
    id text,
    tasks_count text,
    PRIMARY KEY (company_id, company_schedule_date, id),
    FOREIGN KEY (company_id) REFERENCES company_schedule(company_id),
    FOREIGN KEY (company_schedule_date) REFERENCES company_schedule("date"),
    FOREIGN KEY (id) REFERENCES project(id)
);

CREATE TABLE company_schedule (
    "date" text,
    company_id text,
    PRIMARY KEY ("date", company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE inspection_type (
    id text,
    company_id text,
    created_at text,
    deleted_at text,
    "name" text,
    source_id text,
    updated_at text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE project_tool (
    id text,
    company_id text,
    project_id text,
    engine_name text,
    is_active text,
    "position" text,
    required text,
    title text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE cost_code_line_item_type (
    id text,
    cost_code_id text,
    base_type text,
    code text,
    "name" text,
    origin_id text,
    PRIMARY KEY (id, cost_code_id),
    FOREIGN KEY (cost_code_id) REFERENCES cost_code(id)
);

CREATE TABLE cost_code (
    id text,
    company_id text,
    project_id text,
    parent_id text,
    budgeted text,
    code text,
    created_at text,
    deleted_at text,
    full_code text,
    "name" text,
    origin_data text,
    origin_id text,
    "position" text,
    sortable_code text,
    standard_cost_code_id text,
    updated_at text,
    PRIMARY KEY (id, company_id, project_id),
    FOREIGN KEY (company_id) REFERENCES project(company_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (parent_id) REFERENCES cost_code(id)
);
