CREATE TABLE board (
    id text,
    organization_id text,
    project_id text,
    archived_at text,
    "name" text,
    placement text,
    "position" text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE payment (
    id text,
    invoice_id text,
    organization_id text,
    amount text,
    amount_default text,
    amount_normalized text,
    currency text,
    currency_default text,
    currency_normalized text,
    external_id text,
    note text,
    paid_on text,
    written_off_on text,
    PRIMARY KEY (id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE task_list (
    id text,
    board_id text,
    organization_id text,
    project_id text,
    archived_at text,
    email_key text,
    "name" text,
    placement text,
    "position" text,
    PRIMARY KEY (id),
    FOREIGN KEY (board_id) REFERENCES board(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE custom_field (
    id text,
    organization_id text,
    project_id text,
    aggregation_type_id text,
    archived_at text,
    created_at text,
    custom_field_attachment jsonb,
    custom_field_people jsonb,
    customizable_type text,
    data_type_id text,
    description text,
    formatting_type_id text,
    global text,
    "name" text,
    pipeline_id text,
    required text,
    sensitive text,
    show_in_add_edit_views text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE custom_field_option (
    id text,
    custom_field_id text,
    organization_id text,
    archived_at text,
    color_id text,
    "name" text,
    "position" text,
    PRIMARY KEY (id),
    FOREIGN KEY (custom_field_id) REFERENCES custom_field(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE event (
    id text,
    organization_id text,
    archived_at text,
    color_id text,
    description text,
    event_type_id text,
    half_day_bookings text,
    icon_id text,
    limitation_type_id text,
    "name" text,
    sync_personal_integrations text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE time_entry (
    id text,
    approver_id text,
    creator_id text,
    last_actor_id text,
    organization_id text,
    person_id text,
    rejecter_id text,
    service_id text,
    task_id text,
    updater_id text,
    approved text,
    approved_at text,
    billable_time text,
    calendar_event_id text,
    cost text,
    cost_default text,
    cost_normalized text,
    created_at text,
    currency text,
    currency_default text,
    currency_normalized text,
    "date" text,
    facility_overhead_cost text,
    facility_overhead_cost_default text,
    facility_overhead_cost_normalized text,
    internal_overhead_cost text,
    internal_overhead_cost_default text,
    internal_overhead_cost_normalized text,
    invoice_attribution_id text,
    invoiced text,
    note text,
    overhead text,
    overhead_cost text,
    overhead_cost_default text,
    overhead_cost_normalized text,
    rejected text,
    rejected_at text,
    rejected_reason text,
    started_at text,
    "time" text,
    timer_started_at text,
    timer_stopped_at text,
    track_method_id text,
    updated_at text,
    work_cost text,
    work_cost_default text,
    work_cost_normalized text,
    PRIMARY KEY (id),
    FOREIGN KEY (approver_id) REFERENCES people(id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (last_actor_id) REFERENCES people(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (rejecter_id) REFERENCES people(id),
    FOREIGN KEY (service_id) REFERENCES service(id),
    FOREIGN KEY (task_id) REFERENCES task(id),
    FOREIGN KEY (updater_id) REFERENCES people(id)
);

CREATE TABLE service (
    id text,
    deal_id text,
    initial_service_id text,
    organization_id text,
    origin_service_id text,
    person_id text,
    service_type_id text,
    billable text,
    billable_time text,
    billing_type_id text,
    booked_time text,
    booking_tracking_enabled text,
    budget_cap_enabled text,
    budget_total text,
    budget_total_default text,
    budget_total_normalized text,
    budget_used text,
    budget_used_default text,
    budget_used_normalized text,
    budgeted_time text,
    cost text,
    cost_default text,
    cost_normalized text,
    currency text,
    currency_default text,
    currency_normalized text,
    custom_field_attachment jsonb,
    custom_field_people jsonb,
    deleted_at text,
    description text,
    discount text,
    discount_amount text,
    discount_amount_default text,
    discount_amount_normalized text,
    editor_config jsonb,
    estimated_time text,
    expense_amount text,
    expense_amount_default text,
    expense_amount_normalized text,
    expense_billable_amount text,
    expense_billable_amount_default text,
    expense_billable_amount_normalized text,
    expense_tracking_enabled text,
    future_booked_time text,
    future_budget_used text,
    future_budget_used_default text,
    future_budget_used_normalized text,
    future_cost text,
    future_cost_default text,
    future_cost_normalized text,
    future_revenue text,
    future_revenue_default text,
    future_revenue_normalized text,
    markup text,
    markup_amount text,
    markup_amount_default text,
    markup_amount_normalized text,
    "name" text,
    "position" text,
    price text,
    price_default text,
    price_normalized text,
    pricing_type_id text,
    profit text,
    profit_default text,
    profit_margin text,
    profit_normalized text,
    projected_revenue text,
    projected_revenue_default text,
    projected_revenue_normalized text,
    quantity text,
    revenue text,
    revenue_default text,
    revenue_normalized text,
    section_id text,
    time_tracking_enabled text,
    unapproved_time text,
    unit_id text,
    work_cost text,
    work_cost_default text,
    work_cost_normalized text,
    worked_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (initial_service_id) REFERENCES service(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (origin_service_id) REFERENCES service(id),
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (service_type_id) REFERENCES service_type(id)
);

CREATE TABLE contact_entry (
    id text,
    company_id text,
    invoice_id text,
    organization_id text,
    person_id text,
    subsidiary_id text,
    address text,
    billing_address text,
    city text,
    contactable_type text,
    country text,
    email text,
    "name" text,
    phone text,
    purchase_order_id text,
    "state" text,
    vat text,
    website text,
    zipcode text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (subsidiary_id) REFERENCES subsidiary(id)
);

CREATE TABLE booking (
    id text,
    approver_id text,
    canceler_id text,
    creator_id text,
    event_id text,
    organization_id text,
    origin_id text,
    person_id text,
    rejecter_id text,
    service_id text,
    updater_id text,
    approval_status jsonb,
    approved text,
    approved_at text,
    autotracking text,
    booking_method_id text,
    canceled text,
    canceled_at text,
    created_at text,
    draft text,
    ended_on text,
    external_id text,
    hours text,
    last_activity_at text,
    note text,
    percentage text,
    rejected text,
    rejected_at text,
    rejected_reason text,
    stage_type text,
    started_on text,
    "time" text,
    total_time text,
    total_working_days text,
    updated_at text,
    -- custom_* (dynamic column),
    -- people_custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (approver_id) REFERENCES people(id),
    FOREIGN KEY (canceler_id) REFERENCES people(id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (event_id) REFERENCES event(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (origin_id) REFERENCES booking(id),
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (rejecter_id) REFERENCES people(id),
    FOREIGN KEY (service_id) REFERENCES service(id),
    FOREIGN KEY (updater_id) REFERENCES people(id)
);

CREATE TABLE task_todo_assignee (
    "index" text,
    task_id text,
    todo_assignee_id text,
    PRIMARY KEY ("index", task_id),
    FOREIGN KEY (task_id) REFERENCES task(id),
    FOREIGN KEY (todo_assignee_id) REFERENCES people(id)
);

CREATE TABLE task_repeat_on_weekday (
    "index" text,
    task_id text,
    repeat_on_weekday text,
    PRIMARY KEY ("index", task_id),
    FOREIGN KEY (task_id) REFERENCES task(id)
);

CREATE TABLE task_attachment (
    id text,
    task_id text,
    PRIMARY KEY (id, task_id),
    FOREIGN KEY (task_id) REFERENCES task(id)
);

CREATE TABLE task_tag (
    "index" text,
    task_id text,
    tag_name text,
    PRIMARY KEY ("index", task_id),
    FOREIGN KEY (task_id) REFERENCES task(id)
);

CREATE TABLE task (
    id text,
    assignee_id text,
    creator_id text,
    last_actor_id text,
    organization_id text,
    parent_task_id text,
    project_id text,
    repeated_task_id text,
    task_list_id text,
    workflow_status_id text,
    billable_time text,
    blocking_dependency_count text,
    closed text,
    closed_at text,
    created_at text,
    creation_method_id text,
    deleted_at text,
    description text,
    due_date text,
    due_time text,
    email_key text,
    initial_estimate text,
    last_activity_at text,
    linked_dependency_count text,
    number text,
    open_subtask_count text,
    open_todo_count text,
    placement text,
    private text,
    remaining_time text,
    repeat_on_date text,
    repeat_on_interval text,
    repeat_on_monthday text,
    repeat_origin_id text,
    repeat_schedule_id text,
    start_date text,
    subtask_count text,
    subtask_placement text,
    task_dependency_count text,
    task_number text,
    title text,
    todo_count text,
    type_id text,
    updated_at text,
    waiting_on_dependency_count text,
    worked_time text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assignee_id) REFERENCES people(id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (last_actor_id) REFERENCES people(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (parent_task_id) REFERENCES task(id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (repeated_task_id) REFERENCES task(id),
    FOREIGN KEY (task_list_id) REFERENCES task_list(id),
    FOREIGN KEY (workflow_status_id) REFERENCES workflow_status(id)
);

CREATE TABLE project (
    id text,
    company_id text,
    last_actor_id text,
    organization_id text,
    project_manager_id text,
    workflow_id text,
    archived_at text,
    created_at text,
    last_activity_at text,
    "name" text,
    number text,
    project_color_id text,
    project_number text,
    project_type_id text,
    public_access text,
    sample_data text,
    tag_colors jsonb,
    template text,
    template_object_data jsonb,
    time_on_tasks text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (last_actor_id) REFERENCES people(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (project_manager_id) REFERENCES people(id),
    FOREIGN KEY (workflow_id) REFERENCES workflow(id)
);

CREATE TABLE workflow_status (
    id text,
    organization_id text,
    workflow_id text,
    category_id text,
    color_id text,
    "name" text,
    "position" text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (workflow_id) REFERENCES workflow(id)
);

CREATE TABLE invoice_tag (
    "index" text,
    invoice_id text,
    tag_name text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_attribution (
    invoice_attribution_id text,
    invoice_id text,
    PRIMARY KEY (invoice_attribution_id, invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice (
    id text,
    bill_from_id text,
    bill_to_id text,
    company_id text,
    creator_id text,
    document_type_id text,
    organization_id text,
    parent_invoice_id text,
    subsidiary_id text,
    amount text,
    amount_credited text,
    amount_credited_default text,
    amount_credited_normalized text,
    amount_credited_with_tax text,
    amount_credited_with_tax_default text,
    amount_credited_with_tax_normalized text,
    amount_default text,
    amount_normalized text,
    amount_paid text,
    amount_paid_default text,
    amount_paid_normalized text,
    amount_tax text,
    amount_tax_default text,
    amount_tax_normalized text,
    amount_unpaid text,
    amount_unpaid_default text,
    amount_unpaid_normalized text,
    amount_with_tax text,
    amount_with_tax_default text,
    amount_with_tax_normalized text,
    amount_written_off text,
    amount_written_off_default text,
    amount_written_off_normalized text,
    attachment_id text,
    company_reference_id text,
    created_at text,
    credited text,
    currency text,
    currency_default text,
    currency_normalized text,
    custom_field_attachment jsonb,
    custom_field_people jsonb,
    custom_fields text,
    deleted_at text,
    delivery_on text,
    discount text,
    email_key text,
    exchange_date text,
    exchange_rate text,
    export_id text,
    export_integration_type_id text,
    export_invoice_url text,
    exported text,
    exported_at text,
    finalized_on text,
    invoice_type_id text,
    invoiced_on text,
    last_activity_at text,
    line_item_tax text,
    note text,
    note_interpolated text,
    number text,
    paid_on text,
    pay_on text,
    pay_on_relative text,
    purchase_order_number text,
    sample_data text,
    sent_on text,
    subject text,
    tax_1_name text,
    tax_1_value text,
    tax_2_name text,
    tax_2_value text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (bill_from_id) REFERENCES contact_entry(id),
    FOREIGN KEY (bill_to_id) REFERENCES contact_entry(id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (document_type_id) REFERENCES document_type(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (parent_invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (subsidiary_id) REFERENCES subsidiary(id)
);

CREATE TABLE company_invoice_email_recipient_to (
    "index" text,
    company_id text,
    invoice_email_recipients_to text,
    PRIMARY KEY ("index", company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company_invoice_email_recipient_cc (
    "index" text,
    company_id text,
    invoice_email_recipients_cc text,
    PRIMARY KEY ("index", company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company_invoice_email_recipient_bcc (
    "index" text,
    company_id text,
    invoice_email_recipients_bcc text,
    PRIMARY KEY ("index", company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company_tag (
    "index" text,
    company_id text,
    tag_name text,
    PRIMARY KEY ("index", company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company_contact_phone (
    contact_datum_id text,
    company_id text,
    "name" text,
    phone text,
    PRIMARY KEY (contact_datum_id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company_contact_website (
    contact_datum_id text,
    company_id text,
    "name" text,
    website text,
    PRIMARY KEY (contact_datum_id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company_contact_address (
    contact_datum_id text,
    company_id text,
    address text,
    billing_address text,
    city text,
    country text,
    "name" text,
    "state" text,
    zipcode text,
    PRIMARY KEY (contact_datum_id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company (
    id text,
    organization_id text,
    archived_at text,
    avatar_url text,
    billing_name text,
    company_code text,
    created_at text,
    default_currency text,
    description text,
    domain text,
    due_day text,
    external_id text,
    external_sync text,
    invoice_setting_budget_display_format text,
    invoice_setting_date_interval_id text,
    invoice_setting_document_type_id text,
    invoice_setting_end_date text,
    invoice_setting_expenses_display_format text,
    invoice_setting_invoicing_method text,
    invoice_setting_percentage text,
    invoice_setting_services_display_format text,
    invoice_setting_start_date text,
    invoice_setting_subsidiary_id text,
    invoice_setting_time_display_format text,
    last_activity_at text,
    "name" text,
    projectless_budget text,
    sample_data text,
    setting_exporter_option_tax_code_id text,
    vat text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE deal_status (
    id text,
    organization_id text,
    pipeline_id text,
    archived_at text,
    booking_tracking_enabled text,
    color_id text,
    expense_tracking_enabled text,
    lost_reason_enabled text,
    "name" text,
    "position" text,
    probability_enabled text,
    status_id text,
    time_tracking_enabled text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (pipeline_id) REFERENCES pipeline(id)
);

CREATE TABLE line_item (
    id text,
    expense_id text,
    invoice_id text,
    organization_id text,
    service_id text,
    service_type_id text,
    adjustment text,
    amount text,
    amount_default text,
    amount_normalized text,
    amount_tax text,
    amount_tax_default text,
    amount_tax_normalized text,
    amount_with_tax text,
    amount_with_tax_default text,
    amount_with_tax_normalized text,
    currency text,
    currency_default text,
    currency_normalized text,
    description text,
    discount text,
    "position" text,
    quantity text,
    tax_name text,
    tax_rate_id text,
    tax_value text,
    unit_id text,
    unit_price text,
    unit_price_default text,
    unit_price_normalized text,
    PRIMARY KEY (id),
    FOREIGN KEY (expense_id) REFERENCES expense(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (service_id) REFERENCES service(id),
    FOREIGN KEY (service_type_id) REFERENCES service_type(id)
);

CREATE TABLE user_beta_feature (
    "index" text,
    users_id text,
    beta_feature text,
    PRIMARY KEY ("index", users_id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    account_access_expires_at text,
    attributes_sysadmin_permissions jsonb,
    avatar_url text,
    default_organization_id text,
    default_organization_slug text,
    email text,
    first_name text,
    ical_token text,
    intercom_hash text,
    last_name text,
    newsletter_consent text,
    newsletter_consent_at text,
    preferences text,
    sso_provision text,
    sysadmin text,
    sysadmin_permissions text,
    time_zone text,
    two_factor_auth text,
    PRIMARY KEY (id)
);

CREATE TABLE subsidiary (
    id text,
    bill_from_id text,
    organization_id text,
    archived_at text,
    custom_domain jsonb,
    export_integration_type_id text,
    facility_costs text,
    facility_costs_default text,
    facility_costs_normalized text,
    integration_id text,
    invoice_logo_url text,
    invoice_number_format text,
    invoice_number_scope text,
    "name" text,
    overhead_amortization_period text,
    overhead_per_subsidiary text,
    overhead_recalculation_day text,
    show_delivery_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (bill_from_id) REFERENCES contact_entry(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE comment_attachment (
    id text,
    comment_id text,
    PRIMARY KEY (id, comment_id),
    FOREIGN KEY (comment_id) REFERENCES "comment"(id)
);

CREATE TABLE "comment" (
    id text,
    company_id text,
    creator_id text,
    deal_id text,
    invoice_id text,
    organization_id text,
    person_id text,
    task_id text,
    body text,
    commentable_type text,
    created_at text,
    deleted_at text,
    discussion_id text,
    draft text,
    edited_at text,
    hidden text,
    pinned_at text,
    pinned_by_id text,
    purchase_order_id text,
    reactions jsonb,
    updated_at text,
    version_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (task_id) REFERENCES task(id)
);

CREATE TABLE organization_addon (
    "index" text,
    organization_id text,
    addon text,
    PRIMARY KEY ("index", organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE organization_working_hour (
    "index" text,
    organization_id text,
    working_hour text,
    PRIMARY KEY ("index", organization_id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE organization (
    id text,
    company_id text,
    owner_id text,
    ai_enabled text,
    allow_user_email text,
    analytics_uid text,
    avatar_url text,
    billing_email text,
    booked_demo text,
    conflict_resolver_active text,
    currency text,
    currency_default text,
    currency_format_id text,
    currency_normalized text,
    customer_success_specialist_id text,
    date_format_id text,
    deal_probability text,
    deal_settings_advanced_mode text,
    deal_settings_budget_warning text,
    deal_settings_client_access text,
    deal_settings_create_open_hours_open_expenses text,
    deal_settings_deal_probability text,
    deal_settings_expense_approval text,
    deal_settings_time_approval text,
    deal_settings_tracking_type_id text,
    decimal_places_id text,
    delivered_budget_recognition_date_id text,
    domain_verified text,
    due_days text,
    email_domain_name text,
    email_key text,
    email_local_name text,
    email_sender_name text,
    email_type_id text,
    erector_id text,
    exchange_rate_provider_id text,
    expense_markup text,
    expense_settings_markup text,
    expense_settings_payment text,
    expense_settings_reimbursement text,
    facility_costs text,
    facility_costs_breakdown jsonb,
    facility_costs_default text,
    facility_costs_normalized text,
    force_single_sign_on text,
    force_two_factor_auth text,
    invitation_token text,
    limited_service_types text,
    man_day_minutes text,
    metrics text,
    "name" text,
    number_format_id text,
    numbering_format_settings_budget_format text,
    numbering_format_settings_budget_scope text,
    numbering_format_settings_project_format text,
    numbering_format_settings_project_scope text,
    numbering_format_settings_purchase_order_format text,
    numbering_format_settings_purchase_order_scope text,
    numbering_format_settings_task_format text,
    numbering_format_settings_task_scope text,
    onboarding_progress text,
    open_budget_recognition_date_id text,
    organization_subscription_id text,
    organization_type_id text,
    overhead_amortization_period text,
    overhead_recalculation_day text,
    remove_branding text,
    revenue_recognition_type_id text,
    rounding_interval_id text,
    rounding_method_id text,
    sample_data_imported_at text,
    sample_data_reverted_at text,
    single_sign_on text,
    time_display_id text,
    time_format_id text,
    time_locking text,
    time_locking_interval text,
    time_locking_period_id text,
    time_locking_reminders text,
    time_reminder_at text,
    time_reminder_condition text,
    time_reminder_id text,
    time_reminders text,
    time_zone text,
    verified_at text,
    week_start_day_id text,
    weight text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (owner_id) REFERENCES people(id)
);

CREATE TABLE lost_reason (
    id text,
    organization_id text,
    archived_at text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE pipeline (
    id text,
    creator_id text,
    organization_id text,
    updater_id text,
    created_at text,
    icon_id text,
    "name" text,
    pipeline_type_id text,
    "position" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (updater_id) REFERENCES people(id)
);

CREATE TABLE document_type (
    id text,
    organization_id text,
    subsidiary_id text,
    archived_at text,
    attachments jsonb,
    body_template text,
    document_style_id text,
    document_template_id text,
    dual_currency text,
    email_data jsonb,
    email_subject text,
    email_template text,
    exportable_type_id text,
    exporter_options jsonb,
    footer text,
    footer_template text,
    header_template text,
    line_item_tax text,
    locale text,
    "name" text,
    note text,
    scss_template text,
    tax_1_name text,
    tax_1_value text,
    tax_2_name text,
    tax_2_value text,
    template_options jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (subsidiary_id) REFERENCES subsidiary(id)
);

CREATE TABLE time_entry_version_date (
    "index" text,
    time_entry_version_id text,
    "date" text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_time (
    "index" text,
    time_entry_version_id text,
    "time" text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_person (
    "index" text,
    time_entry_version_id text,
    person_id text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id),
    FOREIGN KEY (person_id) REFERENCES people(id)
);

CREATE TABLE time_entry_version_creator (
    creator_id text,
    time_entry_version_id text,
    PRIMARY KEY (creator_id, time_entry_version_id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_approved_at (
    "index" text,
    time_entry_version_id text,
    approved_at text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_billing_point (
    billing_point_id text,
    time_entry_version_id text,
    PRIMARY KEY (billing_point_id, time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_correction (
    "index" text,
    time_entry_version_id text,
    correction text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_started_at (
    "index" text,
    time_entry_version_id text,
    started_at text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_approver (
    approver_id text,
    time_entry_version_id text,
    PRIMARY KEY (approver_id, time_entry_version_id),
    FOREIGN KEY (approver_id) REFERENCES people(id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_rejected_at (
    "index" text,
    time_entry_version_id text,
    rejected_at text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_rejector (
    rejector_id text,
    time_entry_version_id text,
    PRIMARY KEY (rejector_id, time_entry_version_id),
    FOREIGN KEY (rejector_id) REFERENCES people(id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version_rejected_reason (
    "index" text,
    time_entry_version_id text,
    rejected_reason text,
    PRIMARY KEY ("index", time_entry_version_id),
    FOREIGN KEY (time_entry_version_id) REFERENCES time_entry_version(id)
);

CREATE TABLE time_entry_version (
    id text,
    creator_id text,
    organization_id text,
    created_at text,
    event text,
    item_id text,
    item_type text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE deal_membership (
    membership_id text,
    deal_id text,
    PRIMARY KEY (membership_id, deal_id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal_tag (
    "index" text,
    deal_id text,
    tag_name text,
    PRIMARY KEY ("index", deal_id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal (
    id text,
    company_id text,
    contact_id text,
    creator_id text,
    deal_status_id text,
    document_type_id text,
    lost_reason_id text,
    organization_id text,
    project_id text,
    responsible_id text,
    subsidiary_id text,
    amount_credited text,
    amount_credited_default text,
    amount_credited_normalized text,
    billable_time text,
    budget text,
    budget_total text,
    budget_total_default text,
    budget_total_normalized text,
    budget_used text,
    budget_used_default text,
    budget_used_normalized text,
    budget_warning text,
    budgeted_time text,
    client_access text,
    closed_at text,
    contract_id text,
    cost text,
    cost_default text,
    cost_normalized text,
    created_at text,
    currency text,
    currency_default text,
    currency_normalized text,
    "date" text,
    deal_number text,
    deal_type_id text,
    deleted_at text,
    delivered_on text,
    discount text,
    draft_invoiced text,
    draft_invoiced_default text,
    draft_invoiced_normalized text,
    editor_config jsonb,
    email_key text,
    end_date text,
    estimated_time text,
    exchange_date text,
    exchange_rate text,
    expense text,
    expense_approval text,
    expense_default text,
    expense_normalized text,
    external_id text,
    external_sync text,
    invoiced text,
    invoiced_default text,
    invoiced_normalized text,
    last_activity_at text,
    lost_comment text,
    man_day_minutes text,
    "name" text,
    note text,
    note_interpolated text,
    number text,
    origin_deal_id text,
    pending_invoicing text,
    pending_invoicing_default text,
    pending_invoicing_normalized text,
    "position" text,
    probability text,
    profit text,
    profit_default text,
    profit_margin text,
    profit_normalized text,
    projected_revenue text,
    projected_revenue_default text,
    projected_revenue_normalized text,
    purchase_order_number text,
    rejected_entries_count text,
    revenue text,
    revenue_default text,
    revenue_normalized text,
    rounding_interval_id text,
    rounding_method_id text,
    sales_closed_at text,
    sales_closed_on text,
    sales_status_id text,
    sales_status_updated_at text,
    sample_data text,
    service_type_restricted_tracking text,
    services_revenue text,
    services_revenue_default text,
    services_revenue_normalized text,
    suffix text,
    tax_rate_id text,
    template_id text,
    time_approval text,
    time_to_close text,
    todo_count text,
    todo_due_date text,
    tracking_type_id text,
    unapproved_entries_count text,
    worked_time text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (contact_id) REFERENCES people(id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (deal_status_id) REFERENCES deal_status(id),
    FOREIGN KEY (document_type_id) REFERENCES document_type(id),
    FOREIGN KEY (lost_reason_id) REFERENCES lost_reason(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (responsible_id) REFERENCES people(id),
    FOREIGN KEY (subsidiary_id) REFERENCES subsidiary(id)
);

CREATE TABLE expense (
    id text,
    approver_id text,
    creator_id text,
    deal_id text,
    organization_id text,
    person_id text,
    rejecter_id text,
    service_id text,
    service_type_id text,
    amount text,
    amount_default text,
    amount_normalized text,
    approved text,
    approved_at text,
    attachment_id text,
    billable_amount text,
    billable_amount_default text,
    billable_amount_normalized text,
    created_at text,
    currency text,
    currency_default text,
    currency_normalized text,
    custom_field_attachment jsonb,
    custom_field_people jsonb,
    custom_fields text,
    "date" text,
    deleted_at text,
    draft text,
    exchange_date text,
    exchange_rate text,
    invoiced text,
    "name" text,
    paid_on text,
    pay_on text,
    "position" text,
    profit text,
    profit_default text,
    profit_normalized text,
    purchase_order_id text,
    quantity text,
    quantity_received text,
    recognized_revenue text,
    recognized_revenue_default text,
    recognized_revenue_normalized text,
    reimbursable text,
    reimbursed_on text,
    rejected text,
    rejected_at text,
    rejected_reason text,
    total_amount text,
    total_amount_default text,
    total_amount_normalized text,
    vendor_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (approver_id) REFERENCES people(id),
    FOREIGN KEY (creator_id) REFERENCES people(id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (person_id) REFERENCES people(id),
    FOREIGN KEY (rejecter_id) REFERENCES people(id),
    FOREIGN KEY (service_id) REFERENCES service(id),
    FOREIGN KEY (service_type_id) REFERENCES service_type(id)
);

CREATE TABLE people_tag (
    "index" text,
    people_id text,
    tag_name text,
    PRIMARY KEY ("index", people_id),
    FOREIGN KEY (people_id) REFERENCES people(id)
);

CREATE TABLE people_contact_phone (
    contact_datum_id text,
    people_id text,
    "name" text,
    phone text,
    PRIMARY KEY (contact_datum_id, people_id),
    FOREIGN KEY (people_id) REFERENCES people(id)
);

CREATE TABLE people_contact_email (
    contact_datum_id text,
    people_id text,
    email text,
    "name" text,
    PRIMARY KEY (contact_datum_id, people_id),
    FOREIGN KEY (people_id) REFERENCES people(id)
);

CREATE TABLE people_contact_address (
    contact_datum_id text,
    people_id text,
    address text,
    billing_address text,
    city text,
    country text,
    "name" text,
    "state" text,
    zipcode text,
    PRIMARY KEY (contact_datum_id, people_id),
    FOREIGN KEY (people_id) REFERENCES people(id)
);

CREATE TABLE people (
    id text,
    company_id text,
    manager_id text,
    organization_id text,
    subsidiary_id text,
    archived_at text,
    autotracking text,
    availabilities text,
    avatar_url text,
    color_id text,
    created_at text,
    deactivated_at text,
    email text,
    external_id text,
    external_sync text,
    first_name text,
    holiday_calendar_id text,
    hrm_type_id text,
    invited_at text,
    is_user text,
    joined_at text,
    last_activity_at text,
    last_name text,
    last_seen_at text,
    nickname text,
    placeholder text,
    role_id text,
    sample_data text,
    status_emoji text,
    status_expires_at text,
    status_text text,
    team_data jsonb,
    time_unlocked text,
    time_unlocked_end_date text,
    time_unlocked_interval text,
    time_unlocked_on text,
    time_unlocked_period_id text,
    time_unlocked_start_date text,
    title text,
    two_factor_auth text,
    user_id text,
    virtual text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (manager_id) REFERENCES people(id),
    FOREIGN KEY (organization_id) REFERENCES organization(id),
    FOREIGN KEY (subsidiary_id) REFERENCES subsidiary(id)
);

CREATE TABLE service_type_assignee (
    assignee_id text,
    service_type_id text,
    PRIMARY KEY (assignee_id, service_type_id),
    FOREIGN KEY (assignee_id) REFERENCES people(id),
    FOREIGN KEY (service_type_id) REFERENCES service_type(id)
);

CREATE TABLE service_type (
    id text,
    organization_id text,
    archived_at text,
    description text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);

CREATE TABLE workflow (
    id text,
    organization_id text,
    archived_at text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (organization_id) REFERENCES organization(id)
);
