CREATE TABLE training_enrollment (
    id text,
    email_address text,
    assignment_creation text,
    assignment_due_date text,
    assignment_id text,
    assignment_name text,
    assignment_start_date text,
    assignment_type text,
    enrollment_removal_date text,
    enrollment_removal_reason text,
    is_auto_enroll text,
    manager_emailaddress text,
    module_attempt_status text,
    module_due_date text,
    module_enrollment_date text,
    module_id text,
    module_name_admin text,
    module_name_user text,
    user_assignment_completion_date_time text,
    user_assignment_status text,
    user_module_completion_date_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (email_address) REFERENCES users(email_address)
);

CREATE TABLE phish_alarm (
    _fivetran_id text,
    email_address text,
    "action" text,
    assessment_soft_deleted_date text,
    campaign_name text,
    elapsed_hour text,
    email_client_version text,
    emailtype text,
    id text,
    os text,
    received_date text,
    reported_date text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (email_address) REFERENCES users(email_address)
);

CREATE TABLE knowledge_assessment (
    _fivetran_id text,
    email_address text,
    assessment_name text,
    assessment_status text,
    assessment_type text,
    assignment_average_score text,
    assignment_deleted_date text,
    assignment_due_date text,
    assignment_name text,
    assignment_start_date text,
    assignment_status text,
    attempt_date text,
    category text,
    category_benchmark_all text,
    category_benchmark_industry text,
    company_average_score text,
    correct text,
    id text,
    is_ae_enabled text,
    is_custom_question text,
    question_date text,
    question_id text,
    question_latency text,
    question_text text,
    question_type text,
    questions_in_category text,
    seconds_in_attempt text,
    selected_answer text,
    user_answered_on_assignment text,
    user_assignment_status text,
    user_correcton_assignment text,
    user_removed_from_assignment text,
    user_score_on_assignment text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (email_address) REFERENCES users(email_address)
);

CREATE TABLE phishing_extended (
    _fivetran_id text,
    email_address text,
    afr text,
    assessment_is_archived text,
    auto_enrollment text,
    browser text,
    browser_version text,
    campaign_end_date text,
    campaign_guid text,
    campaign_name text,
    campaign_start_date text,
    campaign_status text,
    campaign_type text,
    event_timestamp text,
    event_type text,
    id text,
    ip_address text,
    mobile_device_used text,
    os text,
    os_version text,
    sent_timestamp text,
    template_name text,
    template_subject text,
    user_agent text,
    user_guid text,
    who_is_city text,
    who_is_continent text,
    who_is_country text,
    who_is_domain text,
    who_is_isp text,
    who_is_latitude text,
    who_is_longitude text,
    who_is_organization text,
    who_is_state text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (email_address) REFERENCES users(email_address)
);

CREATE TABLE users (
    email_address text,
    activeflag text,
    data_last_updated text,
    deleted_date text,
    first_name text,
    id text,
    last_name text,
    locale text,
    sso_id text,
    tags text,
    timezone text,
    PRIMARY KEY (email_address)
);

CREATE TABLE phishing (
    _fivetran_id text,
    email_address text,
    assessment_is_archived text,
    auto_enrollment text,
    campaign_end_date text,
    campaign_name text,
    campaign_start_date text,
    campaign_status text,
    campaign_type text,
    event_timestamp text,
    event_type text,
    id text,
    sent_timestamp text,
    template_name text,
    template_subject text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (email_address) REFERENCES users(email_address)
);

CREATE TABLE training (
    _fivetran_id text,
    email_address text,
    assignment_deleted text,
    assignment_deleted_date text,
    assignment_due_date text,
    assignment_method text,
    assignment_name text,
    assignment_start_date text,
    assignment_status text,
    duration text,
    force_completed_date text,
    id text,
    is_auto_enroll text,
    is_free_play text,
    module_attempt_date text,
    module_attempt_end_status text,
    module_attempt_score text,
    module_attempt_score_answered text,
    module_attempt_score_correct text,
    module_attempt_status text,
    module_last_action text,
    module_name_admin text,
    module_name_user text,
    module_type text,
    seconds_in_module_attempt text,
    user_assignment_status text,
    user_removed_from_assignment text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (email_address) REFERENCES users(email_address)
);
