CREATE TABLE sales_receipt_line (
    "index" bigint,
    sales_receipt_id text,
    bundle_id text,
    description_tax_code_id text,
    discount_account_id text,
    discount_class_id text,
    discount_tax_code_id text,
    sales_item_account_id text,
    sales_item_class_id text,
    sales_item_item_id text,
    sales_item_tax_code_id text,
    sub_total_item_id text,
    amount numeric,
    bundle_quantity numeric,
    description text,
    description_service_date text,
    discount_discount_percent numeric,
    discount_percent_based boolean,
    sales_item_discount_amount numeric,
    sales_item_discount_rate numeric,
    sales_item_quantity numeric,
    sales_item_service_date text,
    sales_item_unit_price numeric,
    PRIMARY KEY ("index", sales_receipt_id),
    FOREIGN KEY (sales_receipt_id) REFERENCES sales_receipt(id),
    FOREIGN KEY (bundle_id) REFERENCES bundle(id),
    FOREIGN KEY (description_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (discount_account_id) REFERENCES account(id),
    FOREIGN KEY (discount_class_id) REFERENCES class(id),
    FOREIGN KEY (discount_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sales_item_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_item_class_id) REFERENCES class(id),
    FOREIGN KEY (sales_item_item_id) REFERENCES item(id),
    FOREIGN KEY (sales_item_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sub_total_item_id) REFERENCES item(id)
);

CREATE TABLE payment_method (
    id text,
    active boolean,
    created_at timestamp,
    "name" text,
    sync_token text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id)
);

-- Note:
-- CURRENCY is populated from
--   - account
--   - bill
--   - bill_payment
--   - credit_card_payment_txn
--   - credit_memo
--   - customer
--   - deposit
--   - estimate
--   - invoice
--   - journal_entry
--   - payment
--   - purchase
--   - purchase_order
--   - refund_receipt
--   - sales_receipt
--   - vendor
--   - vendor_credit
CREATE TABLE currency (
    id text,
    "name" text,
    PRIMARY KEY (id)
);

CREATE TABLE bill_payment (
    id text,
    check_bank_account_id text,
    credit_card_account_id text,
    currency_id text,
    department_id text,
    payable_account_id text,
    vendor_id text,
    check_print_status text,
    created_at timestamp,
    doc_number text,
    exchange_rate numeric,
    pay_type text,
    private_note text,
    process_bill_payment boolean,
    sync_token text,
    total_amount numeric,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (check_bank_account_id) REFERENCES account(id),
    FOREIGN KEY (credit_card_account_id) REFERENCES account(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (payable_account_id) REFERENCES account(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE bundle (
    id text,
    active boolean,
    created_at timestamp,
    description text,
    fully_qualified_name text,
    "name" text,
    print_grouped_items boolean,
    purchase_cost numeric,
    sync_token text,
    taxable boolean,
    unit_price numeric,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE payment (
    id text,
    currency_id text,
    customer_id text,
    deposit_to_account_id text,
    payment_method_id text,
    receivable_account_id text,
    created_at timestamp,
    credit_card_amount numeric,
    credit_card_auth_code text,
    credit_card_billing_address_street text,
    credit_card_cc_expiry_month bigint,
    credit_card_cc_expiry_year bigint,
    credit_card_cctrans_id text,
    credit_card_name_on_account text,
    credit_card_postal_code text,
    credit_card_process_payment boolean,
    credit_card_status text,
    credit_card_transaction_authorization_time text,
    credit_card_type text,
    exchange_rate numeric,
    private_note text,
    process_payment boolean,
    reference_number text,
    sync_token text,
    total_amount numeric,
    transaction_date text,
    transaction_source text,
    transaction_status text,
    unapplied_amount numeric,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (deposit_to_account_id) REFERENCES account(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_method(id),
    FOREIGN KEY (receivable_account_id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    currency_id text,
    parent_account_id text,
    tax_code_id text,
    account_number text,
    account_sub_type text,
    account_type text,
    active boolean,
    balance numeric,
    balance_with_sub_accounts numeric,
    classification text,
    created_at timestamp,
    description text,
    fully_qualified_name text,
    "name" text,
    sub_account boolean,
    sync_token text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (parent_account_id) REFERENCES account(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE journal_entry_tax_line (
    "index" bigint,
    journal_entry_id text,
    tax_rate_id text,
    amount numeric,
    net_amount_taxable numeric,
    override_delta_amount numeric,
    percent_based boolean,
    tax_inclusive_amount numeric,
    tax_percent numeric,
    PRIMARY KEY ("index", journal_entry_id),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE sales_receipt_line_bundle (
    "index" bigint,
    sales_receipt_id text,
    sales_receipt_line_index bigint,
    account_id text,
    class_id text,
    item_id text,
    tax_code_id text,
    amount numeric,
    description text,
    discount_amount numeric,
    discount_rate numeric,
    line_num bigint,
    quantity numeric,
    service_date text,
    unit_price numeric,
    PRIMARY KEY ("index", sales_receipt_id, sales_receipt_line_index),
    FOREIGN KEY (sales_receipt_id) REFERENCES sales_receipt(id),
    FOREIGN KEY (sales_receipt_line_index) REFERENCES sales_receipt_line(sales_receipt_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE estimate_tax_line (
    "index" bigint,
    estimate_id text,
    tax_rate_id text,
    amount numeric,
    net_amount_taxable numeric,
    override_delta_amount numeric,
    percent_based boolean,
    tax_inclusive_amount numeric,
    tax_percent numeric,
    PRIMARY KEY ("index", estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE deposit (
    id text,
    account_id text,
    cash_back_account_id text,
    currency_id text,
    department_id text,
    cash_back_amount numeric,
    cash_back_memo text,
    created_at timestamp,
    global_tax_calculation text,
    home_total_amount numeric,
    private_note text,
    sync_token text,
    total_amount numeric,
    transaction_date text,
    transaction_source text,
    transaction_status text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (cash_back_account_id) REFERENCES account(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (department_id) REFERENCES department(id)
);

CREATE TABLE invoice (
    id text,
    billing_address_id text,
    class_id text,
    currency_id text,
    customer_id text,
    department_id text,
    deposit_to_account_id text,
    sales_term_id text,
    shipping_address_id text,
    tax_code_id text,
    allow_ipnpayment boolean,
    allow_online_achpayment boolean,
    allow_online_credit_card_payment boolean,
    allow_online_payment boolean,
    apply_tax_after_discount boolean,
    balance numeric,
    billing_bcc_email text,
    billing_cc_email text,
    billing_email text,
    created_at timestamp,
    customer_memo text,
    delivery_time text,
    delivery_type text,
    deposit numeric,
    doc_number text,
    due_date text,
    email_status text,
    exchange_rate numeric,
    global_tax_calculation text,
    home_balance numeric,
    home_total_amount numeric,
    print_status text,
    private_note text,
    ship_date text,
    sync_token text,
    total_amount numeric,
    total_tax numeric,
    tracking_number text,
    transaction_date text,
    transaction_source text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_address_id) REFERENCES address(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (deposit_to_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_term_id) REFERENCES term(id),
    FOREIGN KEY (shipping_address_id) REFERENCES address(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE sales_receipt (
    id text,
    billing_address_id text,
    class_id text,
    currency_id text,
    customer_id text,
    department_id text,
    deposit_to_account_id text,
    payment_method_id text,
    payment_reference_number text,
    shipping_address_id text,
    tax_code_id text,
    apply_tax_after_discount boolean,
    balance numeric,
    bill_email text,
    created_at timestamp,
    credit_card_amount numeric,
    credit_card_auth_code text,
    credit_card_billing_address_street text,
    credit_card_cc_expiry_month bigint,
    credit_card_cc_expiry_year bigint,
    credit_card_cctrans_id text,
    credit_card_name_on_account text,
    credit_card_postal_code text,
    credit_card_process_payment boolean,
    credit_card_status text,
    credit_card_transaction_authorization_time text,
    credit_card_type text,
    customer_memo text,
    delivery_time text,
    delivery_type text,
    doc_number text,
    email_status text,
    exchange_rate numeric,
    global_tax_calculation text,
    home_balance numeric,
    home_total_amount numeric,
    print_status text,
    private_note text,
    ship_date text,
    sync_token text,
    total_amount numeric,
    total_tax numeric,
    tracking_number text,
    transaction_date text,
    transaction_source text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_address_id) REFERENCES address(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (deposit_to_account_id) REFERENCES account(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_method(id),
    FOREIGN KEY (payment_reference_number) REFERENCES payment(id),
    FOREIGN KEY (shipping_address_id) REFERENCES address(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE tax_rate_detail (
    tax_code_id text,
    tax_rate_id text,
    tax_order bigint,
    tax_type_applicable text,
    "type" text,
    PRIMARY KEY (tax_code_id, tax_rate_id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE bill_linked_txn (
    "index" bigint,
    bill_id text,
    bill_payment_id text,
    PRIMARY KEY ("index", bill_id),
    FOREIGN KEY (bill_id) REFERENCES bill(id),
    FOREIGN KEY (bill_payment_id) REFERENCES bill_payment(id)
);

CREATE TABLE credit_card_payment_txn (
    id text,
    bank_account_id text,
    credit_card_account_id text,
    currency_id text,
    amount numeric,
    created_at timestamp,
    exchange_rate numeric,
    sync_token text,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (bank_account_id) REFERENCES account(id),
    FOREIGN KEY (credit_card_account_id) REFERENCES account(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id)
);

CREATE TABLE invoice_line (
    "index" bigint,
    invoice_id text,
    bundle_id text,
    description_tax_code_id text,
    discount_account_id text,
    discount_class_id text,
    discount_tax_code_id text,
    sales_item_account_id text,
    sales_item_class_id text,
    sales_item_item_id text,
    sales_item_tax_code_id text,
    sub_total_item_id text,
    amount numeric,
    bundle_quantity numeric,
    description text,
    description_service_date text,
    detail_type text,
    discount_discount_percent numeric,
    discount_percent_based boolean,
    id text,
    line_num bigint,
    sales_item_discount_amount numeric,
    sales_item_discount_rate numeric,
    sales_item_quantity numeric,
    sales_item_service_date text,
    sales_item_unit_price numeric,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (bundle_id) REFERENCES bundle(id),
    FOREIGN KEY (description_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (discount_account_id) REFERENCES account(id),
    FOREIGN KEY (discount_class_id) REFERENCES class(id),
    FOREIGN KEY (discount_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sales_item_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_item_class_id) REFERENCES class(id),
    FOREIGN KEY (sales_item_item_id) REFERENCES item(id),
    FOREIGN KEY (sales_item_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sub_total_item_id) REFERENCES item(id)
);

CREATE TABLE vendor (
    id text,
    billing_address_id text,
    currency_id text,
    term_id text,
    account_number text,
    active boolean,
    alternate_phone text,
    balance numeric,
    company_name text,
    created_at timestamp,
    display_name text,
    email text,
    family_name text,
    fax_number text,
    given_name text,
    middle_name text,
    mobile_phone text,
    other_contacts jsonb,
    primary_phone text,
    print_on_check_name text,
    suffix text,
    sync_token text,
    tax_identifier text,
    title text,
    updated_at timestamp,
    vendor_1099 boolean,
    web_url text,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_address_id) REFERENCES address(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (term_id) REFERENCES term(id)
);

-- Note:
-- ADDRESS is populated from:
--   - credit_memo
--   - customer
--   - employee
--   - estimate
--   - invoice
--   - purchase
--   - purchase_order
--   - refund_receipt
--   - sales_receipt
--   - vendor
CREATE TABLE address (
    id text,
    city text,
    country text,
    country_sub_division_code text,
    latitude text,
    line_1 text,
    line_2 text,
    line_3 text,
    line_4 text,
    line_5 text,
    longitude text,
    postal_code text,
    PRIMARY KEY (id)
);

CREATE TABLE customer (
    id text,
    ar_account_id text,
    bill_address_id text,
    currency_id text,
    default_tax_code_id text,
    parent_customer_id text,
    payment_method_id text,
    sales_term_id text,
    shipping_address_id text,
    active boolean,
    alternate_phone_number text,
    balance numeric,
    balance_with_jobs numeric,
    bill_with_parent boolean,
    company_name text,
    created_at timestamp,
    customer_type_id text,
    display_name text,
    email text,
    family_name text,
    fax_number text,
    fully_qualified_name text,
    given_name text,
    job boolean,
    "level" bigint,
    middle_name text,
    mobile_number text,
    notes text,
    open_balance_date text,
    phone_number text,
    preferred_delivery_method text,
    print_on_check_name text,
    resale_number text,
    suffix text,
    sync_token text,
    tax_exemption_reason_id text,
    taxable boolean,
    title text,
    updated_at timestamp,
    website text,
    PRIMARY KEY (id),
    FOREIGN KEY (ar_account_id) REFERENCES account(id),
    FOREIGN KEY (bill_address_id) REFERENCES address(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (default_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (parent_customer_id) REFERENCES customer(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_method(id),
    FOREIGN KEY (sales_term_id) REFERENCES term(id),
    FOREIGN KEY (shipping_address_id) REFERENCES address(id)
);

CREATE TABLE vendor_credit (
    id text,
    currency_id text,
    department_id text,
    payable_account_id text,
    vendor_id text,
    balance numeric,
    created_at timestamp,
    doc_number text,
    exchange_rate numeric,
    global_tax_calculation text,
    private_note text,
    sync_token text,
    total_amount numeric,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (payable_account_id) REFERENCES account(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE purchase_line (
    "index" bigint,
    purchase_id text,
    account_expense_account_id text,
    account_expense_class_id text,
    account_expense_customer_id text,
    account_expense_tax_code_id text,
    item_expense_class_id text,
    item_expense_customer_id text,
    item_expense_item_id text,
    item_expense_tax_code_id text,
    account_expense_billable_status text,
    account_expense_tax_amount numeric,
    amount numeric,
    description text,
    item_expense_billable_status text,
    item_expense_quantity numeric,
    item_expense_unit_price numeric,
    PRIMARY KEY ("index", purchase_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id),
    FOREIGN KEY (account_expense_account_id) REFERENCES account(id),
    FOREIGN KEY (account_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (account_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (account_expense_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (item_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (item_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (item_expense_item_id) REFERENCES item(id),
    FOREIGN KEY (item_expense_tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE estimate_line (
    "index" bigint,
    estimate_id text,
    bundle_id text,
    description_tax_code_id text,
    discount_account_id text,
    discount_class_id text,
    discount_tax_code_id text,
    sales_item_account_id text,
    sales_item_class_id text,
    sales_item_item_id text,
    sales_item_tax_code_id text,
    sub_total_item_id text,
    amount numeric,
    bundle_quantity numeric,
    description text,
    description_service_date text,
    discount_discount_percent numeric,
    discount_percent_based boolean,
    sales_item_discount_amount numeric,
    sales_item_discount_rate numeric,
    sales_item_quantity numeric,
    sales_item_service_date text,
    sales_item_unit_price numeric,
    PRIMARY KEY ("index", estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id),
    FOREIGN KEY (bundle_id) REFERENCES bundle(id),
    FOREIGN KEY (description_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (discount_account_id) REFERENCES account(id),
    FOREIGN KEY (discount_class_id) REFERENCES class(id),
    FOREIGN KEY (discount_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sales_item_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_item_class_id) REFERENCES class(id),
    FOREIGN KEY (sales_item_item_id) REFERENCES item(id),
    FOREIGN KEY (sales_item_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sub_total_item_id) REFERENCES item(id)
);

CREATE TABLE estimate_line_bundle (
    "index" bigint,
    estimate_id text,
    estimate_line_index bigint,
    account_id text,
    class_id text,
    item_id text,
    tax_code_id text,
    amount numeric,
    description text,
    discount_amount numeric,
    discount_rate numeric,
    line_num bigint,
    quantity numeric,
    service_date text,
    unit_price numeric,
    PRIMARY KEY ("index", estimate_id, estimate_line_index),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id),
    FOREIGN KEY (estimate_line_index) REFERENCES estimate_line(estimate_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE purchase_order_tax_line (
    "index" bigint,
    purchase_order_id text,
    tax_rate_id text,
    amount numeric,
    net_amount_taxable numeric,
    override_delta_amount numeric,
    percent_based boolean,
    tax_inclusive_amount numeric,
    tax_percent numeric,
    PRIMARY KEY ("index", purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE budget_detail (
    "index" bigint,
    budget_id text,
    account_id text,
    class_id text,
    customer_id text,
    department_id text,
    amount numeric,
    budget_date text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id)
);

CREATE TABLE class (
    id text,
    parent_class_id text,
    active boolean,
    created_at timestamp,
    fully_qualified_name text,
    "name" text,
    sub_class boolean,
    sync_token text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_class_id) REFERENCES class(id)
);

CREATE TABLE time_activity (
    id text,
    class_id text,
    customer_id text,
    department_id text,
    employee_id text,
    item_id text,
    vendor_id text,
    billable_status text,
    break_hours double precision,
    break_minutes double precision,
    created_at timestamp,
    description text,
    end_time timestamp,
    hourly_rate numeric,
    hours double precision,
    minutes double precision,
    name_of text,
    start_time timestamp,
    sync_token text,
    taxable boolean,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE department (
    id text,
    parent_department_id text,
    active boolean,
    created_at timestamp,
    fully_qualified_name text,
    "name" text,
    sub_department boolean,
    sync_token text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_department_id) REFERENCES department(id)
);

CREATE TABLE bill_line (
    "index" bigint,
    bill_id text,
    account_expense_account_id text,
    account_expense_class_id text,
    account_expense_customer_id text,
    account_expense_tax_code_id text,
    item_expense_class_id text,
    item_expense_customer_id text,
    item_expense_item_id text,
    item_expense_tax_code_id text,
    account_expense_billable_status text,
    account_expense_tax_amount numeric,
    amount numeric,
    description text,
    item_expense_billable_status text,
    item_expense_quantity numeric,
    item_expense_unit_price numeric,
    PRIMARY KEY ("index", bill_id),
    FOREIGN KEY (bill_id) REFERENCES bill(id),
    FOREIGN KEY (account_expense_account_id) REFERENCES account(id),
    FOREIGN KEY (account_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (account_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (account_expense_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (item_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (item_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (item_expense_item_id) REFERENCES item(id),
    FOREIGN KEY (item_expense_tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE payment_line (
    "index" bigint,
    payment_id text,
    credit_memo_id text,
    deposit_id text,
    invoice_id text,
    journal_entry_id text,
    amount numeric,
    check_id text,
    credit_card_charge_id text,
    credit_card_credit_id text,
    expense_id text,
    PRIMARY KEY ("index", payment_id),
    FOREIGN KEY (payment_id) REFERENCES payment(id),
    FOREIGN KEY (credit_memo_id) REFERENCES credit_memo(id),
    FOREIGN KEY (deposit_id) REFERENCES deposit(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id)
);

CREATE TABLE deposit_line (
    "index" bigint,
    deposit_id text,
    bill_id text,
    deposit_account_id text,
    deposit_class_id text,
    deposit_customer_id text,
    deposit_payment_method_id text,
    deposit_tax_code_id text,
    invoice_id text,
    journal_entry_id text,
    payment_id text,
    purchase_id text,
    refund_receipt_id text,
    sales_receipt_id text,
    transfer_id text,
    vendor_credit_id text,
    amount numeric,
    deposit_check_number text,
    deposit_tax_applicable_on text,
    deposit_transaction_type text,
    description text,
    detail_type text,
    expense_id text,
    PRIMARY KEY ("index", deposit_id),
    FOREIGN KEY (deposit_id) REFERENCES deposit(id),
    FOREIGN KEY (bill_id) REFERENCES bill(id),
    FOREIGN KEY (deposit_account_id) REFERENCES account(id),
    FOREIGN KEY (deposit_class_id) REFERENCES class(id),
    FOREIGN KEY (deposit_customer_id) REFERENCES customer(id),
    FOREIGN KEY (deposit_payment_method_id) REFERENCES payment_method(id),
    FOREIGN KEY (deposit_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id),
    FOREIGN KEY (payment_id) REFERENCES payment(id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id),
    FOREIGN KEY (refund_receipt_id) REFERENCES refund_receipt(id),
    FOREIGN KEY (sales_receipt_id) REFERENCES sales_receipt(id),
    FOREIGN KEY (transfer_id) REFERENCES transfer(id),
    FOREIGN KEY (vendor_credit_id) REFERENCES vendor_credit(id)
);

CREATE TABLE refund_receipt_line (
    "index" bigint,
    refund_id text,
    bundle_id text,
    description_tax_code_id text,
    discount_account_id text,
    discount_class_id text,
    discount_tax_code_id text,
    sales_item_account_id text,
    sales_item_class_id text,
    sales_item_item_id text,
    sales_item_tax_code_id text,
    sub_total_item_id text,
    amount numeric,
    bundle_quantity numeric,
    description text,
    description_service_date text,
    discount_discount_percent numeric,
    discount_percent_based boolean,
    sales_item_discount_amount numeric,
    sales_item_discount_rate numeric,
    sales_item_quantity numeric,
    sales_item_service_date text,
    sales_item_unit_price numeric,
    PRIMARY KEY ("index", refund_id),
    FOREIGN KEY (refund_id) REFERENCES refund_receipt(id),
    FOREIGN KEY (bundle_id) REFERENCES bundle(id),
    FOREIGN KEY (description_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (discount_account_id) REFERENCES account(id),
    FOREIGN KEY (discount_class_id) REFERENCES class(id),
    FOREIGN KEY (discount_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sales_item_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_item_class_id) REFERENCES class(id),
    FOREIGN KEY (sales_item_item_id) REFERENCES item(id),
    FOREIGN KEY (sales_item_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sub_total_item_id) REFERENCES item(id)
);

CREATE TABLE bundle_item (
    bundle_id text,
    item_id text,
    item_quantity numeric,
    PRIMARY KEY (bundle_id, item_id),
    FOREIGN KEY (bundle_id) REFERENCES bundle(id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE sales_receipt_tax_line (
    "index" bigint,
    sales_receipt_id text,
    tax_rate_id text,
    amount numeric,
    net_amount_taxable numeric,
    override_delta_amount numeric,
    percent_based boolean,
    tax_inclusive_amount numeric,
    tax_percent numeric,
    PRIMARY KEY ("index", sales_receipt_id),
    FOREIGN KEY (sales_receipt_id) REFERENCES sales_receipt(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE purchase_order (
    id text,
    class_id text,
    currency_id text,
    payable_account_id text,
    sales_term_id text,
    shipping_address_id text,
    tax_code_id text,
    vendor_address_id text,
    vendor_id text,
    created_at timestamp,
    doc_number text,
    due_date text,
    exchange_rate numeric,
    global_tax_calculation text,
    memo text,
    private_note text,
    "status" text,
    sync_token text,
    total_amount numeric,
    total_tax numeric,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (payable_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_term_id) REFERENCES term(id),
    FOREIGN KEY (shipping_address_id) REFERENCES address(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (vendor_address_id) REFERENCES address(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE journal_entry_line (
    "index" bigint,
    journal_entry_id text,
    account_id text,
    class_id text,
    customer_id text,
    department_id text,
    description_tax_code_id text,
    employee_id text,
    tax_code_id text,
    vendor_id text,
    amount numeric,
    billable_status text,
    description text,
    description_service_date text,
    posting_type text,
    tax_amount numeric,
    tax_applicable_on text,
    PRIMARY KEY ("index", journal_entry_id),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (description_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE credit_memo_line (
    "index" bigint,
    credit_memo_id text,
    bundle_id text,
    description_tax_code_id text,
    discount_account_id text,
    discount_class_id text,
    discount_tax_code_id text,
    sales_item_account_id text,
    sales_item_class_id text,
    sales_item_item_id text,
    sales_item_tax_code_id text,
    sub_total_item_id text,
    amount numeric,
    bundle_quantity numeric,
    description text,
    description_service_date text,
    discount_discount_percent numeric,
    discount_percent_based boolean,
    sales_item_discount_amount numeric,
    sales_item_discount_rate numeric,
    sales_item_quantity numeric,
    sales_item_service_date text,
    sales_item_unit_price numeric,
    PRIMARY KEY ("index", credit_memo_id),
    FOREIGN KEY (credit_memo_id) REFERENCES credit_memo(id),
    FOREIGN KEY (bundle_id) REFERENCES bundle(id),
    FOREIGN KEY (description_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (discount_account_id) REFERENCES account(id),
    FOREIGN KEY (discount_class_id) REFERENCES class(id),
    FOREIGN KEY (discount_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sales_item_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_item_class_id) REFERENCES class(id),
    FOREIGN KEY (sales_item_item_id) REFERENCES item(id),
    FOREIGN KEY (sales_item_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sub_total_item_id) REFERENCES item(id)
);

CREATE TABLE invoice_tax_line (
    "index" bigint,
    invoice_id text,
    tax_rate_id text,
    amount numeric,
    net_amount_taxable numeric,
    override_delta_amount numeric,
    percent_based boolean,
    tax_inclusive_amount numeric,
    tax_percent numeric,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE tax_agency (
    id text,
    created_at timestamp,
    display_name text,
    sync_token text,
    tax_registration_number text,
    tax_tracked_on_purchases boolean,
    tax_tracked_on_sales boolean,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE tax_code (
    id text,
    active boolean,
    created_at timestamp,
    description text,
    "name" text,
    sync_token text,
    tax_group boolean,
    taxable boolean,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE purchase_tax_line (
    "index" bigint,
    purchase_id text,
    tax_rate_id text,
    amount numeric,
    net_amount_taxable numeric,
    override_delta_amount numeric,
    percent_based boolean,
    tax_inclusive_amount numeric,
    tax_percent numeric,
    PRIMARY KEY ("index", purchase_id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE credit_memo_line_bundle (
    "index" bigint,
    credit_memo_id text,
    credit_memo_line_index bigint,
    account_id text,
    class_id text,
    item_id text,
    tax_code_id text,
    amount numeric,
    description text,
    discount_amount numeric,
    discount_rate numeric,
    line_num bigint,
    quantity numeric,
    service_date text,
    unit_price numeric,
    PRIMARY KEY ("index", credit_memo_id, credit_memo_line_index),
    FOREIGN KEY (credit_memo_id) REFERENCES credit_memo(id),
    FOREIGN KEY (credit_memo_line_index) REFERENCES credit_memo_line(credit_memo_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE employee (
    id text,
    address_id text,
    active boolean,
    bill_rate numeric,
    billable_time boolean,
    birth_date text,
    created_at timestamp,
    display_name text,
    email text,
    employee_number text,
    family_name text,
    gender text,
    given_name text,
    hired_date text,
    middle_name text,
    mobile_phone text,
    organization boolean,
    phone_number text,
    print_on_check_name text,
    released_date text,
    social_security_number text,
    suffix text,
    sync_token text,
    title text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE refund_receipt_tax_line (
    "index" bigint,
    refund_receipt_id text,
    tax_rate_id text,
    amount numeric,
    net_amount_taxable numeric,
    override_delta_amount numeric,
    percent_based boolean,
    tax_inclusive_amount numeric,
    tax_percent numeric,
    PRIMARY KEY ("index", refund_receipt_id),
    FOREIGN KEY (refund_receipt_id) REFERENCES refund_receipt(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE invoice_line_bundle (
    "index" bigint,
    invoice_id text,
    invoice_line_index bigint,
    account_id text,
    class_id text,
    item_id text,
    tax_code_id text,
    amount numeric,
    description text,
    discount_amount numeric,
    discount_rate numeric,
    line_num bigint,
    quantity numeric,
    service_date text,
    unit_price numeric,
    PRIMARY KEY ("index", invoice_id, invoice_line_index),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (invoice_line_index) REFERENCES invoice_line(invoice_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE budget (
    id text,
    active boolean,
    budget_entry_type text,
    budget_type text,
    created_at timestamp,
    end_date text,
    "name" text,
    start_date text,
    sync_token text,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE tax_rate (
    id text,
    tax_agency_id text,
    active boolean,
    created_at timestamp,
    description text,
    display_type text,
    effective_tax_rate jsonb,
    "name" text,
    rate_value numeric,
    special_tax_type text,
    sync_token text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (tax_agency_id) REFERENCES tax_agency(id)
);

CREATE TABLE item (
    id text,
    asset_account_id text,
    expense_account_id text,
    income_account_id text,
    parent_item_id text,
    purchase_tax_code_id text,
    sales_tax_code_id text,
    active boolean,
    created_at timestamp,
    description text,
    fully_qualified_name text,
    inventory_start_date text,
    "level" bigint,
    "name" text,
    purchase_cost numeric,
    purchase_description text,
    purchase_tax_included boolean,
    quantity_on_hand numeric,
    sales_tax_included boolean,
    stock_keeping_unit text,
    sub_item boolean,
    sync_token text,
    taxable boolean,
    track_quantity_on_hand boolean,
    "type" text,
    unit_price numeric,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_account_id) REFERENCES account(id),
    FOREIGN KEY (expense_account_id) REFERENCES account(id),
    FOREIGN KEY (income_account_id) REFERENCES account(id),
    FOREIGN KEY (parent_item_id) REFERENCES item(id),
    FOREIGN KEY (purchase_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (sales_tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE bill (
    id text,
    currency_id text,
    department_id text,
    payable_account_id text,
    sales_term_id text,
    vendor_id text,
    balance numeric,
    created_at timestamp,
    doc_number text,
    due_date text,
    exchange_rate numeric,
    global_tax_calculation text,
    home_balance numeric,
    private_note text,
    sync_token text,
    total_amount numeric,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (payable_account_id) REFERENCES account(id),
    FOREIGN KEY (sales_term_id) REFERENCES term(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE credit_memo_custom_field (
    definition_id text,
    "index" bigint,
    credit_memo_id text,
    "name" text,
    PRIMARY KEY (definition_id, "index", credit_memo_id),
    FOREIGN KEY (credit_memo_id) REFERENCES credit_memo(id)
);

CREATE TABLE transfer (
    id text,
    currency_id text,
    from_account_id text,
    to_account_id text,
    amount numeric,
    created_at timestamp,
    exchange_rate numeric,
    private_note text,
    sync_token text,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (from_account_id) REFERENCES account(id),
    FOREIGN KEY (to_account_id) REFERENCES account(id)
);

CREATE TABLE estimate_linked_txn (
    "index" bigint,
    estimate_id text,
    invoice_id text,
    PRIMARY KEY ("index", estimate_id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);

CREATE TABLE invoice_linked_txn (
    "index" bigint,
    invoice_id text,
    estimate_id text,
    payment_id text,
    time_activity_id text,
    charge_credit_id text,
    reimburse_charge_id text,
    statement_charge_id text,
    PRIMARY KEY ("index", invoice_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (estimate_id) REFERENCES estimate(id),
    FOREIGN KEY (payment_id) REFERENCES payment(id),
    FOREIGN KEY (time_activity_id) REFERENCES time_activity(id)
);

CREATE TABLE credit_memo (
    id text,
    billing_address_id text,
    class_id text,
    currency_id text,
    customer_id text,
    department_id text,
    payment_method_id text,
    sales_term_id text,
    shipping_address_id text,
    apply_tax_after_discount boolean,
    balance numeric,
    bill_email text,
    created_at timestamp,
    customer_memo text,
    doc_number text,
    email_status text,
    exchange_rate numeric,
    global_tax_calculation text,
    home_balance numeric,
    home_total_amount numeric,
    print_status text,
    private_note text,
    remaining_credit numeric,
    sync_token text,
    total_amount numeric,
    total_tax text,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_address_id) REFERENCES address(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_method(id),
    FOREIGN KEY (sales_term_id) REFERENCES term(id),
    FOREIGN KEY (shipping_address_id) REFERENCES address(id)
);

CREATE TABLE refund_receipt (
    id text,
    billing_address_id text,
    class_id text,
    currency_id text,
    customer_id text,
    department_id text,
    deposit_to_account_id text,
    payment_method_id text,
    payment_reference_number text,
    shipping_address_id text,
    tax_code_id text,
    apply_tax_after_discount boolean,
    balance numeric,
    bill_email text,
    created_at timestamp,
    credit_card_amount numeric,
    credit_card_auth_code text,
    credit_card_billing_address_street text,
    credit_card_cc_expiry_month bigint,
    credit_card_cc_expiry_year bigint,
    credit_card_cctrans_id text,
    credit_card_name_on_account text,
    credit_card_postal_code text,
    credit_card_process_payment boolean,
    credit_card_status text,
    credit_card_transaction_authorization_time text,
    credit_card_type text,
    customer_memo text,
    doc_number text,
    exchange_rate numeric,
    global_tax_calculation text,
    home_balance numeric,
    home_total_amount numeric,
    payment_type text,
    print_status text,
    private_note text,
    sync_token text,
    total_amount numeric,
    total_tax numeric,
    transaction_date text,
    transaction_source text,
    updated_at timestamp,
    -- check_payment_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (billing_address_id) REFERENCES address(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (deposit_to_account_id) REFERENCES account(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_method(id),
    FOREIGN KEY (payment_reference_number) REFERENCES payment(id),
    FOREIGN KEY (shipping_address_id) REFERENCES address(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE vendor_credit_line (
    "index" bigint,
    vendor_credit_id text,
    account_expense_account_id text,
    account_expense_class_id text,
    account_expense_customer_id text,
    account_expense_tax_code_id text,
    item_expense_class_id text,
    item_expense_customer_id text,
    item_expense_item_id text,
    item_expense_tax_code_id text,
    account_expense_billable_status text,
    account_expense_tax_amount numeric,
    amount numeric,
    description text,
    item_expense_billable_status text,
    item_expense_quantity numeric,
    item_expense_unit_price numeric,
    private_note text,
    PRIMARY KEY ("index", vendor_credit_id),
    FOREIGN KEY (vendor_credit_id) REFERENCES vendor_credit(id),
    FOREIGN KEY (account_expense_account_id) REFERENCES account(id),
    FOREIGN KEY (account_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (account_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (account_expense_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (item_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (item_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (item_expense_item_id) REFERENCES item(id),
    FOREIGN KEY (item_expense_tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE purchase_order_linked_txn (
    "index" bigint,
    purchase_order_id text,
    bill_id text,
    purchase_id text,
    vendor_credit_id text,
    PRIMARY KEY ("index", purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (bill_id) REFERENCES bill(id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id),
    FOREIGN KEY (vendor_credit_id) REFERENCES vendor_credit(id)
);

CREATE TABLE estimate (
    id text,
    billing_address_id text,
    class_id text,
    currency_id text,
    customer_id text,
    department_id text,
    sales_term_id text,
    shipping_address_id text,
    tax_code_id text,
    accepted_by text,
    accepted_date text,
    apply_tax_after_discount boolean,
    bill_email text,
    created_at timestamp,
    customer_memo text,
    delivery_type text,
    doc_number text,
    due_date text,
    email_status text,
    exchange_rate numeric,
    expiration_date text,
    global_tax_calculation text,
    home_total_amount numeric,
    print_status text,
    private_note text,
    ship_date text,
    sync_token text,
    total_amount numeric,
    total_tax numeric,
    transaction_date text,
    transaction_status text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (billing_address_id) REFERENCES address(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (sales_term_id) REFERENCES term(id),
    FOREIGN KEY (shipping_address_id) REFERENCES address(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE purchase (
    id text,
    account_id text,
    currency_id text,
    customer_id text,
    department_id text,
    employee_id text,
    payment_method_id text,
    remit_to_address_id text,
    tax_code_id text,
    vendor_id text,
    created_at timestamp,
    credit boolean,
    doc_number text,
    exchange_rate numeric,
    global_tax_calculation text,
    payment_type text,
    print_status text,
    private_note text,
    sync_token text,
    total_amount numeric,
    total_tax numeric,
    transaction_date text,
    transaction_source text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (department_id) REFERENCES department(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_method(id),
    FOREIGN KEY (remit_to_address_id) REFERENCES address(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE purchase_order_line (
    "index" bigint,
    purchase_order_id text,
    account_expense_account_id text,
    account_expense_class_id text,
    account_expense_customer_id text,
    account_expense_tax_code_id text,
    item_expense_class_id text,
    item_expense_customer_id text,
    item_expense_item_id text,
    item_expense_tax_code_id text,
    account_expense_billable_status text,
    account_expense_tax_amount numeric,
    amount numeric,
    description text,
    item_expense_billable_status text,
    item_expense_quantity numeric,
    item_expense_unit_price numeric,
    PRIMARY KEY ("index", purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (account_expense_account_id) REFERENCES account(id),
    FOREIGN KEY (account_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (account_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (account_expense_tax_code_id) REFERENCES tax_code(id),
    FOREIGN KEY (item_expense_class_id) REFERENCES class(id),
    FOREIGN KEY (item_expense_customer_id) REFERENCES customer(id),
    FOREIGN KEY (item_expense_item_id) REFERENCES item(id),
    FOREIGN KEY (item_expense_tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE term (
    id text,
    active boolean,
    created_at timestamp,
    day_of_month_due bigint,
    discount_day_of_month bigint,
    discount_days bigint,
    discount_percent numeric,
    due_days bigint,
    due_next_month_days bigint,
    "name" text,
    sync_token text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE journal_entry (
    id text,
    currency_id text,
    tax_code_id text,
    adjustment boolean,
    created_at timestamp,
    doc_number text,
    exchange_rate numeric,
    home_total_amount numeric,
    private_note text,
    sync_token text,
    total_amount numeric,
    total_tax numeric,
    transaction_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (currency_id) REFERENCES currency(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);

CREATE TABLE bill_payment_line (
    "index" bigint,
    bill_payment_id text,
    bill_id text,
    deposit_id text,
    journal_entry_id text,
    linked_bill_payment_id text,
    purchase_id text,
    vendor_credit_id text,
    amount numeric,
    bill_payment_credit_card_id text,
    check_id text,
    credit_card_charge_id text,
    credit_card_credit_id text,
    expense_id text,
    PRIMARY KEY ("index", bill_payment_id),
    FOREIGN KEY (bill_payment_id) REFERENCES bill_payment(id),
    FOREIGN KEY (bill_id) REFERENCES bill(id),
    FOREIGN KEY (deposit_id) REFERENCES deposit(id),
    FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id),
    FOREIGN KEY (linked_bill_payment_id) REFERENCES bill_payment(id),
    FOREIGN KEY (purchase_id) REFERENCES purchase(id),
    FOREIGN KEY (vendor_credit_id) REFERENCES vendor_credit(id)
);

CREATE TABLE refund_receipt_line_bundle (
    "index" bigint,
    refund_receipt_id text,
    refund_receipt_line_index bigint,
    account_id text,
    class_id text,
    item_id text,
    tax_code_id text,
    amount numeric,
    description text,
    discount_amount numeric,
    discount_rate numeric,
    line_num bigint,
    quantity numeric,
    service_date text,
    unit_price numeric,
    PRIMARY KEY ("index", refund_receipt_id, refund_receipt_line_index),
    FOREIGN KEY (refund_receipt_id) REFERENCES refund_receipt(id),
    FOREIGN KEY (refund_receipt_line_index) REFERENCES refund_receipt_line(refund_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (class_id) REFERENCES class(id),
    FOREIGN KEY (item_id) REFERENCES item(id),
    FOREIGN KEY (tax_code_id) REFERENCES tax_code(id)
);
