CREATE TABLE lead_gen_form (
    id text,
    account_id text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account_detail(id)
);

CREATE TABLE ad_set (
    end_date text,
    id text,
    start_date text,
    account_id text,
    campagin_id text,
    bid_amount text,
    campaign_id text,
    click text,
    cost_per_lead text,
    cpc text,
    ctr text,
    form_completion_rate text,
    impression text,
    leads_generated text,
    "name" text,
    spend text,
    "status" text,
    PRIMARY KEY (end_date, id, start_date),
    FOREIGN KEY (account_id) REFERENCES account_detail(id),
    FOREIGN KEY (campagin_id) REFERENCES campaign(id)
);

CREATE TABLE ad (
    end_date text,
    id text,
    start_date text,
    account_id text,
    ad_set_id text,
    campaign_id text,
    bid_amount text,
    click text,
    cost_per_lead text,
    form_completion_rate text,
    impression text,
    leads_generated text,
    "name" text,
    spend text,
    "status" text,
    PRIMARY KEY (end_date, id, start_date),
    FOREIGN KEY (account_id) REFERENCES account_detail(id),
    FOREIGN KEY (ad_set_id) REFERENCES ad_set(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE recent_leads_collected_for_lead_gen_form (
    id text,
    account_id text,
    ad_id text,
    form_id text,
    creation_time text,
    field_data_business_email text,
    field_data_city text,
    field_data_company_name text,
    field_data_company_size text,
    field_data_country text,
    field_data_first_name text,
    field_data_job_title text,
    field_data_last_name text,
    field_data_phone_number text,
    field_data_state text,
    field_data_user_email text,
    field_data_zipcode text,
    form_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account_detail(id),
    FOREIGN KEY (ad_id) REFERENCES ad(id),
    FOREIGN KEY (form_id) REFERENCES lead_gen_form(id)
);

CREATE TABLE account_detail (
    end_date text,
    id text,
    start_date text,
    account_currency text,
    account_name text,
    click text,
    conversion_add_payment_info text,
    conversion_add_to_cart text,
    conversion_add_to_wishlist text,
    conversion_app_install text,
    conversion_complete_registration text,
    conversion_generate_lead text,
    conversion_generic text,
    conversion_initiate_checkout text,
    conversion_purchase text,
    conversion_rate_add_payment_info text,
    conversion_rate_add_to_cart text,
    conversion_rate_add_to_wishlist text,
    conversion_rate_app_install text,
    conversion_rate_complete_registration text,
    conversion_rate_generate_lead text,
    conversion_rate_generic text,
    conversion_rate_initiate_checkout text,
    conversion_rate_purchase text,
    conversion_rate_search text,
    conversion_search text,
    cost_per_lead text,
    cpc text,
    ctr text,
    form_completion_rate text,
    impression text,
    leads_generated text,
    spend text,
    PRIMARY KEY (end_date, id, start_date)
);

CREATE TABLE campaign (
    end_date text,
    id text,
    start_date text,
    account_id text,
    campaign_name text,
    click text,
    conversion_add_payment_info text,
    conversion_add_to_cart text,
    conversion_add_to_wishlist text,
    conversion_app_install text,
    conversion_complete_registration text,
    conversion_generate_lead text,
    conversion_generic text,
    conversion_initiate_checkout text,
    conversion_purchase text,
    conversion_rate_add_payment_info text,
    conversion_rate_add_to_cart text,
    conversion_rate_add_to_wishlist text,
    conversion_rate_app_install text,
    conversion_rate_complete_registration text,
    conversion_rate_generate_lead text,
    conversion_rate_generic text,
    conversion_rate_initiate_checkout text,
    conversion_rate_purchase text,
    conversion_rate_search text,
    conversion_search text,
    cost_per_lead text,
    cpc text,
    daily_budget text,
    form_completion_rate text,
    impression text,
    leads_generated text,
    lifetime_budget text,
    spend text,
    "status" text,
    PRIMARY KEY (end_date, id, start_date),
    FOREIGN KEY (account_id) REFERENCES account_detail(id)
);
