CREATE TABLE collection_feature (
    feature text,
    collection_id text,
    PRIMARY KEY (feature, collection_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE collection_tag (
    tags text,
    collection_id text,
    PRIMARY KEY (tags, collection_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE collection_genre (
    genre text,
    collection_id text,
    PRIMARY KEY (genre, collection_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE collection_content (
    _fivetran_id text,
    collection_id text,
    file_name text,
    height bigint,
    mime_type text,
    representation text,
    "size" bigint,
    "type" text,
    url text,
    width bigint,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE collection_minter (
    minter text,
    collection_id text,
    PRIMARY KEY (minter, collection_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE collection_volume (
    _fivetran_id text,
    collection_id text,
    change_percent double precision,
    period text,
    "value" double precision,
    value_usd double precision,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE collection_origin_order (
    origin text,
    collection_id text,
    best_bid_order_cancelled boolean,
    best_bid_order_created_at timestamp,
    best_bid_order_data_fee double precision,
    best_bid_order_data_type text,
    best_bid_order_db_updated_at timestamp,
    best_bid_order_ended_at timestamp,
    best_bid_order_fill double precision,
    best_bid_order_id text,
    best_bid_order_last_updated_at timestamp,
    best_bid_order_make_price double precision,
    best_bid_order_make_price_usd double precision,
    best_bid_order_make_stock double precision,
    best_bid_order_make_type_contract text,
    best_bid_order_make_type_token_id text,
    best_bid_order_make_type_type text,
    best_bid_order_make_value double precision,
    best_bid_order_maker text,
    best_bid_order_platform text,
    best_bid_order_salt text,
    best_bid_order_signature text,
    best_bid_order_started_at timestamp,
    best_bid_order_status text,
    best_bid_order_take_price double precision,
    best_bid_order_take_price_usd double precision,
    best_bid_order_take_type_contract text,
    best_bid_order_take_type_token_id text,
    best_bid_order_take_type_type text,
    best_bid_order_take_value double precision,
    best_bid_order_taker text,
    best_sell_order_cancelled boolean,
    best_sell_order_created_at timestamp,
    best_sell_order_data_fee double precision,
    best_sell_order_data_type text,
    best_sell_order_db_updated_at timestamp,
    best_sell_order_ended_at timestamp,
    best_sell_order_fill double precision,
    best_sell_order_id text,
    best_sell_order_last_updated_at timestamp,
    best_sell_order_make_price double precision,
    best_sell_order_make_price_usd double precision,
    best_sell_order_make_stock double precision,
    best_sell_order_make_type_contract text,
    best_sell_order_make_type_token_id text,
    best_sell_order_make_type_type text,
    best_sell_order_make_value double precision,
    best_sell_order_maker text,
    best_sell_order_platform text,
    best_sell_order_salt text,
    best_sell_order_signature text,
    best_sell_order_started_at timestamp,
    best_sell_order_status text,
    best_sell_order_take_price double precision,
    best_sell_order_take_price_usd double precision,
    best_sell_order_take_type_contract text,
    best_sell_order_take_type_token_id text,
    best_sell_order_take_type_type text,
    best_sell_order_take_value double precision,
    best_sell_order_taker text,
    PRIMARY KEY (origin, collection_id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE collection (
    id text,
    best_bid_order_cancelled boolean,
    best_bid_order_created_at timestamp,
    best_bid_order_data_fee double precision,
    best_bid_order_data_type text,
    best_bid_order_db_updated_at timestamp,
    best_bid_order_ended_at timestamp,
    best_bid_order_fill double precision,
    best_bid_order_id text,
    best_bid_order_last_updated_at timestamp,
    best_bid_order_make_price double precision,
    best_bid_order_make_price_usd double precision,
    best_bid_order_make_stock double precision,
    best_bid_order_make_type_contract text,
    best_bid_order_make_type_token_id text,
    best_bid_order_make_type_type text,
    best_bid_order_make_value double precision,
    best_bid_order_maker text,
    best_bid_order_platform text,
    best_bid_order_salt text,
    best_bid_order_signature text,
    best_bid_order_started_at timestamp,
    best_bid_order_status text,
    best_bid_order_take_price double precision,
    best_bid_order_take_price_usd double precision,
    best_bid_order_take_type_contract text,
    best_bid_order_take_type_token_id text,
    best_bid_order_take_type_type text,
    best_bid_order_take_value double precision,
    best_bid_order_taker text,
    best_sell_order_cancelled boolean,
    best_sell_order_created_at timestamp,
    best_sell_order_data_fee double precision,
    best_sell_order_data_type text,
    best_sell_order_db_updated_at timestamp,
    best_sell_order_ended_at timestamp,
    best_sell_order_fill double precision,
    best_sell_order_id text,
    best_sell_order_last_updated_at timestamp,
    best_sell_order_make_price double precision,
    best_sell_order_make_price_usd double precision,
    best_sell_order_make_stock double precision,
    best_sell_order_make_type_contract text,
    best_sell_order_make_type_token_id text,
    best_sell_order_make_type_type text,
    best_sell_order_make_value double precision,
    best_sell_order_maker text,
    best_sell_order_platform text,
    best_sell_order_salt text,
    best_sell_order_signature text,
    best_sell_order_started_at timestamp,
    best_sell_order_status text,
    best_sell_order_take_price double precision,
    best_sell_order_take_price_usd double precision,
    best_sell_order_take_type_contract text,
    best_sell_order_take_type_token_id text,
    best_sell_order_take_type_type text,
    best_sell_order_take_value double precision,
    best_sell_order_taker text,
    blockchain text,
    meta_created_at timestamp,
    meta_description text,
    meta_external_link text,
    meta_external_uri text,
    meta_fee_recipient text,
    meta_language text,
    meta_name text,
    meta_original_meta_uri text,
    meta_rights text,
    meta_rights_uri text,
    meta_seller_fee_basis_points double precision,
    "name" text,
    owner text,
    parent text,
    self boolean,
    statistics_floor_price_value double precision,
    statistics_floor_price_value_usd double precision,
    statistics_highest_sale_value double precision,
    statistics_highest_sale_value_usd double precision,
    statistics_item_count bigint,
    statistics_owner_count bigint,
    statistics_total_volume_value double precision,
    statistics_total_volume_value_usd double precision,
    symbol text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE item_creator (
    account text,
    item_id text,
    "value" double precision,
    PRIMARY KEY (account, item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item_attribute (
    "key" text,
    item_id text,
    format text,
    "type" text,
    "value" text,
    PRIMARY KEY ("key", item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item_content (
    _fivetran_id text,
    item_id text,
    available boolean,
    file_name text,
    height bigint,
    mime_type text,
    representation text,
    "size" bigint,
    "type" text,
    url text,
    width bigint,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item_tag (
    tags text,
    item_id text,
    PRIMARY KEY (tags, item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item_genre (
    genre text,
    item_id text,
    PRIMARY KEY (genre, item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item_restriction (
    restriction text,
    item_id text,
    PRIMARY KEY (restriction, item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item_origin_order (
    origin text,
    item_id text,
    best_bid_order_cancelled boolean,
    best_bid_order_created_at timestamp,
    best_bid_order_data_fee double precision,
    best_bid_order_data_type text,
    best_bid_order_db_updated_at timestamp,
    best_bid_order_ended_at timestamp,
    best_bid_order_fill double precision,
    best_bid_order_id text,
    best_bid_order_last_updated_at timestamp,
    best_bid_order_make_price double precision,
    best_bid_order_make_price_usd double precision,
    best_bid_order_make_stock double precision,
    best_bid_order_make_type_contract text,
    best_bid_order_make_type_token_id text,
    best_bid_order_make_type_type text,
    best_bid_order_make_value double precision,
    best_bid_order_maker text,
    best_bid_order_platform text,
    best_bid_order_salt text,
    best_bid_order_signature text,
    best_bid_order_started_at timestamp,
    best_bid_order_status text,
    best_bid_order_take_price double precision,
    best_bid_order_take_price_usd double precision,
    best_bid_order_take_type_contract text,
    best_bid_order_take_type_token_id text,
    best_bid_order_take_type_type text,
    best_bid_order_take_value double precision,
    best_bid_order_taker text,
    best_sell_order_cancelled boolean,
    best_sell_order_created_at timestamp,
    best_sell_order_data_fee double precision,
    best_sell_order_data_type text,
    best_sell_order_db_updated_at timestamp,
    best_sell_order_ended_at timestamp,
    best_sell_order_fill double precision,
    best_sell_order_id text,
    best_sell_order_last_updated_at timestamp,
    best_sell_order_make_price double precision,
    best_sell_order_make_price_usd double precision,
    best_sell_order_make_stock double precision,
    best_sell_order_make_type_contract text,
    best_sell_order_make_type_token_id text,
    best_sell_order_make_type_type text,
    best_sell_order_make_value double precision,
    best_sell_order_maker text,
    best_sell_order_platform text,
    best_sell_order_salt text,
    best_sell_order_signature text,
    best_sell_order_started_at timestamp,
    best_sell_order_status text,
    best_sell_order_take_price double precision,
    best_sell_order_take_price_usd double precision,
    best_sell_order_take_type_contract text,
    best_sell_order_take_type_token_id text,
    best_sell_order_take_type_type text,
    best_sell_order_take_value double precision,
    best_sell_order_taker text,
    PRIMARY KEY (origin, item_id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);

CREATE TABLE item (
    id text,
    collection_id text,
    best_bid_order_cancelled boolean,
    best_bid_order_created_at timestamp,
    best_bid_order_data_fee double precision,
    best_bid_order_data_type text,
    best_bid_order_db_updated_at timestamp,
    best_bid_order_ended_at timestamp,
    best_bid_order_fill double precision,
    best_bid_order_id text,
    best_bid_order_last_updated_at timestamp,
    best_bid_order_make_price double precision,
    best_bid_order_make_price_usd double precision,
    best_bid_order_make_stock double precision,
    best_bid_order_make_type_contract text,
    best_bid_order_make_type_token_id text,
    best_bid_order_make_type_type text,
    best_bid_order_make_value double precision,
    best_bid_order_maker text,
    best_bid_order_platform text,
    best_bid_order_salt text,
    best_bid_order_signature text,
    best_bid_order_started_at timestamp,
    best_bid_order_status text,
    best_bid_order_take_price double precision,
    best_bid_order_take_price_usd double precision,
    best_bid_order_take_type_blockchain text,
    best_bid_order_take_type_contract text,
    best_bid_order_take_type_token_id text,
    best_bid_order_take_type_type text,
    best_bid_order_take_value double precision,
    best_bid_order_taker text,
    best_sell_order_cancelled boolean,
    best_sell_order_created_at timestamp,
    best_sell_order_data_fee double precision,
    best_sell_order_data_type text,
    best_sell_order_db_updated_at timestamp,
    best_sell_order_ended_at timestamp,
    best_sell_order_fill double precision,
    best_sell_order_id text,
    best_sell_order_last_updated_at timestamp,
    best_sell_order_make_price double precision,
    best_sell_order_make_price_usd double precision,
    best_sell_order_make_stock double precision,
    best_sell_order_make_type_contract text,
    best_sell_order_make_type_token_id text,
    best_sell_order_make_type_type text,
    best_sell_order_make_value double precision,
    best_sell_order_maker text,
    best_sell_order_platform text,
    best_sell_order_salt text,
    best_sell_order_signature text,
    best_sell_order_started_at timestamp,
    best_sell_order_status text,
    best_sell_order_take_price double precision,
    best_sell_order_take_price_usd double precision,
    best_sell_order_take_type_blockchain text,
    best_sell_order_take_type_contract text,
    best_sell_order_take_type_token_id text,
    best_sell_order_take_type_type text,
    best_sell_order_take_value double precision,
    best_sell_order_taker text,
    blockchain text,
    collection text,
    contract text,
    deleted boolean,
    last_sale_buyer text,
    last_sale_currency_contract text,
    last_sale_currency_token_id text,
    last_sale_currency_type text,
    last_sale_date timestamp,
    last_sale_price double precision,
    last_sale_seller text,
    last_sale_value double precision,
    last_updated_at timestamp,
    lazy_supply bigint,
    meta_created_at timestamp,
    meta_description text,
    meta_external_uri text,
    meta_language text,
    meta_name text,
    meta_original_meta_uri text,
    meta_rights text,
    meta_rights_uri text,
    minted_at timestamp,
    self boolean,
    sellers bigint,
    supply text,
    token_id text,
    total_stock bigint,
    PRIMARY KEY (id),
    FOREIGN KEY (collection_id) REFERENCES collection(id)
);

CREATE TABLE activity (
    id text,
    collection_id text,
    item_id text,
    amount_usd double precision,
    blockchain_info_block_hash text,
    blockchain_info_block_number bigint,
    blockchain_info_log_index bigint,
    blockchain_info_transaction_hash text,
    buyer text,
    buyer_order_hash text,
    contract text,
    "date" timestamp,
    from_source text,
    hash text,
    last_updated_at timestamp,
    make_contract text,
    make_token_id text,
    make_type text,
    make_type_contract text,
    make_type_token_id text,
    make_type_type text,
    make_value double precision,
    maker text,
    nft_type_contract text,
    nft_type_token_id text,
    nft_type_type text,
    nft_value double precision,
    owner text,
    payment_type_contract text,
    payment_type_token_id text,
    payment_type_type text,
    payment_value double precision,
    price double precision,
    price_usd double precision,
    reverted boolean,
    sell_type text,
    seller text,
    seller_order_hash text,
    "source" text,
    take_blockchain text,
    take_contract text,
    take_token_id text,
    take_type text,
    take_type_blockchain text,
    take_type_contract text,
    take_type_token_id text,
    take_type_type text,
    take_value double precision,
    token_id text,
    transaction_hash text,
    "type" text,
    "value" text,
    PRIMARY KEY (id),
    FOREIGN KEY (collection_id) REFERENCES collection(id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);
