CREATE TABLE return_item_reason (
    "index" text,
    return_id text,
    return_item_sku_code text,
    "action" text,
    additional_title text,
    additional_value text,
    reason text,
    wish text,
    PRIMARY KEY ("index", return_id, return_item_sku_code),
    FOREIGN KEY (return_id) REFERENCES return_item(return_id),
    FOREIGN KEY (return_item_sku_code) REFERENCES return_item(sku_code)
);

CREATE TABLE return_item (
    sku_code text,
    return_id text,
    cost_price text,
    cost_price_currency text,
    country_code text,
    dangerous_goods text,
    days_for_return text,
    dimensions_uom text,
    export_awb text,
    export_carrier_name text,
    export_date text,
    final_dest_addr_1 text,
    final_dest_addr_2 text,
    final_dest_addr_3 text,
    final_dest_city text,
    final_dest_company_name text,
    final_dest_country text,
    final_dest_id text,
    final_dest_name text,
    final_dest_neighborhood text,
    final_dest_state text,
    final_dest_suburb text,
    final_dest_zip text,
    final_disposition text,
    height text,
    hs_code text,
    img_path text,
    length text,
    non_returnable text,
    non_returnable_message text,
    price text,
    quantity text,
    sku_desc text,
    tracking text,
    verification_entity text,
    weight text,
    weight_uom text,
    width text,
    -- custom_* (dynamic column),
    PRIMARY KEY (sku_code, return_id),
    FOREIGN KEY (return_id) REFERENCES "return"(id)
);

CREATE TABLE "return" (
    id text,
    tracking text,
    addr_1 text,
    addr_2 text,
    addr_3 text,
    barcode_number text,
    carrier text,
    city text,
    company_name text,
    country text,
    current_tracking_status text,
    customer_name text,
    date_added text,
    display_id text,
    email text,
    external_id text,
    final_dest_addr_1 text,
    final_dest_addr_2 text,
    final_dest_addr_3 text,
    final_dest_city text,
    final_dest_company_name text,
    final_dest_country text,
    final_dest_id text,
    final_dest_name text,
    final_dest_state text,
    final_dest_zip text,
    label text,
    order_reference text,
    phone text,
    "state" text,
    tracking_last_update text,
    verification_entity text,
    zip text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (tracking) REFERENCES tracking(tracking_number)
);

CREATE TABLE tracking_event (
    dt text,
    tracking_number text,
    location_city text,
    location_country text,
    location_state text,
    "status" text,
    PRIMARY KEY (dt, tracking_number),
    FOREIGN KEY (tracking_number) REFERENCES tracking(tracking_number)
);

CREATE TABLE tracking (
    tracking_number text,
    carrier_name text,
    external_id text,
    order_reference text,
    pallet_number text,
    service_id text,
    source_country text,
    PRIMARY KEY (tracking_number)
);
