CREATE TABLE one_time_product (
    id bigint,
    address_id bigint,
    customer_id bigint,
    created_at timestamp,
    external_product_id_ecommerce text,
    external_variant_id_ecommerce text,
    next_charge_scheduled_at text,
    price text,
    product_title text,
    quantity bigint,
    sku text,
    updated_at timestamp,
    variant_title text,
    -- property_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE metafield (
    id bigint,
    created_at timestamp,
    description text,
    "key" text,
    namespace text,
    owner_id text,
    owner_resource text,
    updated_at timestamp,
    "value" jsonb,
    value_type text,
    PRIMARY KEY (id)
);

CREATE TABLE plan (
    id bigint,
    channel_settings_api_display boolean,
    channel_settings_checkout_page_display boolean,
    channel_settings_customer_portal_display boolean,
    channel_settings_merchant_portal_display boolean,
    created_at timestamp,
    deleted_at timestamp,
    discount_amount text,
    discount_type text,
    product_id_ecommerce text,
    sort_order bigint,
    subscription_preference_charge_interval_frequency bigint,
    subscription_preference_cutoff_day_of_month bigint,
    subscription_preference_cutoff_day_of_week bigint,
    subscription_preference_expire_after_specific_number_of_charges bigint,
    subscription_preference_interval_unit text,
    subscription_preference_order_day_of_month bigint,
    subscription_preference_order_day_of_week bigint,
    subscription_preference_order_interval_frequency bigint,
    title text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE order_line_item (
    "index" integer,
    orders_id bigint,
    external_product_id_ecommerce text,
    external_variant_id_ecommerce text,
    grams double precision,
    product_title text,
    purchase_item_id bigint,
    purchase_item_type text,
    quantity bigint,
    sku text,
    tax_due text,
    taxable boolean,
    taxable_amount text,
    title text,
    total_price text,
    unit_price text,
    unit_price_includes_tax boolean,
    variant_title text,
    -- property_* (dynamic column),
    PRIMARY KEY ("index", orders_id),
    FOREIGN KEY (orders_id) REFERENCES orders(id)
);

CREATE TABLE orders (
    id bigint,
    address_id bigint,
    charge_id bigint,
    customer_id bigint,
    billing_address_address_1 text,
    billing_address_address_2 text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country_code text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_phone text,
    billing_address_province text,
    billing_address_zip text,
    charge_status text,
    created_at timestamp,
    email text,
    external_cart_token text,
    external_order_id_ecommerce text,
    external_order_number_ecommerce text,
    is_prepaid boolean,
    processed_at timestamp,
    scheduled_at timestamp,
    shipped_date timestamp,
    shipping_address_address_1 text,
    shipping_address_address_2 text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country_code text,
    shipping_address_first_name text,
    shipping_address_last_name text,
    shipping_address_phone text,
    shipping_address_province text,
    shipping_address_zip text,
    "status" text,
    total_price text,
    transaction_id text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (charge_id) REFERENCES charge(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_utm_tag (
    _fivetran_id text,
    customer_id bigint,
    campaign text,
    content text,
    data_source text,
    medium text,
    "source" text,
    term text,
    time_stamp timestamp,
    PRIMARY KEY (_fivetran_id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE payment_method (
    id bigint,
    customer_id bigint,
    billing_address_address_1 text,
    billing_address_address_2 text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country_code text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_phone text,
    billing_address_province text,
    billing_address_zip text,
    created_at timestamp,
    default_payment_method boolean,
    payment_details_brand text,
    payment_details_exp_month text,
    payment_details_exp_year text,
    payment_details_last_4 text,
    payment_type text,
    processor_customer_token text,
    processor_name text,
    processor_payment_method_token text,
    "status" text,
    status_reason text,
    updated_at timestamp,
    PRIMARY KEY (id, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer (
    id bigint,
    created_at timestamp,
    email text,
    external_customer_id_ecommerce text,
    first_charge_processed_at timestamp,
    first_name text,
    has_payment_method_in_dunning boolean,
    has_valid_payment_method boolean,
    hash text,
    last_name text,
    subscriptions_active_count integer,
    subscriptions_total_count integer,
    tax_exempt boolean,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE charge_tax_line (
    "index" integer,
    charge_id bigint,
    price text,
    rate text,
    title text,
    PRIMARY KEY ("index", charge_id),
    FOREIGN KEY (charge_id) REFERENCES charge(id)
);

CREATE TABLE charge_shipping_line (
    "index" integer,
    charge_id bigint,
    code text,
    price double precision,
    title text,
    PRIMARY KEY ("index", charge_id),
    FOREIGN KEY (charge_id) REFERENCES charge(id)
);

CREATE TABLE charge_order_attribute (
    "index" integer,
    charge_id bigint,
    order_attribute jsonb,
    PRIMARY KEY ("index", charge_id),
    FOREIGN KEY (charge_id) REFERENCES charge(id)
);

CREATE TABLE charge_line_item (
    "index" integer,
    charge_id bigint,
    external_product_id_ecommerce text,
    external_variant_id_ecommerce text,
    grams double precision,
    purchase_item_id bigint,
    purchase_item_type text,
    quantity bigint,
    sku text,
    tax_due text,
    taxable boolean,
    taxable_amount text,
    title text,
    total_price text,
    unit_price text,
    unit_price_includes_tax boolean,
    variant_title text,
    vendor text,
    -- property_* (dynamic column),
    PRIMARY KEY ("index", charge_id),
    FOREIGN KEY (charge_id) REFERENCES charge(id)
);

CREATE TABLE charge_discount (
    "index" integer,
    charge_id bigint,
    id text,
    code text,
    "value" double precision,
    value_type text,
    PRIMARY KEY ("index", charge_id),
    FOREIGN KEY (charge_id) REFERENCES charge(id),
    FOREIGN KEY (id) REFERENCES discount(id)
);

CREATE TABLE charge_utm_tag (
    _fivetran_id text,
    charge_id bigint,
    campaign text,
    content text,
    data_source text,
    medium text,
    "source" text,
    term text,
    time_stamp timestamp,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (charge_id) REFERENCES charge(id)
);

CREATE TABLE charge (
    id bigint,
    address_id bigint,
    customer_id bigint,
    billing_address_address_1 text,
    billing_address_address_2 text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country_code text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_phone text,
    billing_address_province text,
    billing_address_zip text,
    charge_attempts double precision,
    client_details_browser_ip text,
    client_details_user_agent text,
    created_at timestamp,
    customer_hash text,
    email text,
    error text,
    error_type text,
    external_order_id_ecommerce text,
    external_transaction_id_payment_processor text,
    external_variant_id_not_found boolean,
    has_uncommited_changes boolean,
    note text,
    orders_count bigint,
    payment_processor text,
    processed_at timestamp,
    retry_date timestamp,
    scheduled_at text,
    shipping_address_address_1 text,
    shipping_address_address_2 text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country_code text,
    shipping_address_first_name text,
    shipping_address_last_name text,
    shipping_address_phone text,
    shipping_address_province text,
    shipping_address_zip text,
    "status" text,
    subtotal_price double precision,
    tags text,
    tax_lines double precision,
    total_discounts double precision,
    total_line_items_price double precision,
    total_price double precision,
    total_refunds double precision,
    total_tax double precision,
    total_weight_grams double precision,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE subscription_utm_tag (
    _fivetran_id text,
    subscription_id bigint,
    campaign text,
    content text,
    data_source text,
    medium text,
    "source" text,
    term text,
    time_stamp timestamp,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id)
);

CREATE TABLE subscription (
    id bigint,
    address_id bigint,
    customer_id bigint,
    cancellation_reason text,
    cancellation_reason_comments text,
    cancelled_at timestamp,
    charge_interval_frequency bigint,
    created_at timestamp,
    expire_after_specific_number_of_charges integer,
    external_product_id_ecommerce text,
    external_variant_id_ecommerce text,
    next_charge_scheduled_at text,
    number_charges_until_expiration integer,
    order_day_of_month integer,
    order_day_of_week integer,
    order_interval_frequency bigint,
    order_interval_unit text,
    price text,
    product_title text,
    quantity integer,
    shopify_product_id bigint,
    shopify_variant_id bigint,
    sku text,
    "status" text,
    updated_at timestamp,
    variant_title text,
    -- property_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE subscription_history (
    id bigint,
    updated_at timestamp,
    address_id text,
    customer_id text,
    cancellation_reason text,
    cancellation_reason_comments text,
    cancelled_at timestamp,
    charge_interval_frequency bigint,
    created_at timestamp,
    expire_after_specific_number_of_charges integer,
    external_product_id_ecommerce text,
    external_variant_id_ecommerce text,
    next_charge_scheduled_at text,
    number_charges_until_expiration integer,
    order_day_of_month integer,
    order_day_of_week integer,
    order_interval_frequency bigint,
    order_interval_unit text,
    price text,
    product_title text,
    quantity integer,
    shopify_product_id bigint,
    shopify_variant_id bigint,
    sku text,
    "status" text,
    variant_title text,
    -- property_* (dynamic column),
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (address_id) REFERENCES address(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE discount (
    id bigint,
    applies_once boolean,
    applies_to_id jsonb,
    applies_to_product_type text,
    applies_to_resource text,
    automatic_redemptions_per_customer bigint,
    code text,
    created_at timestamp,
    ends_at timestamp,
    minimum_order_amount bigint,
    starts_at timestamp,
    "status" text,
    updated_at timestamp,
    usage_limit bigint,
    usage_limits_first_time_customer_restriction boolean,
    usage_limits_max_subsequent_redemptions bigint,
    usage_limits_one_application_per_customer boolean,
    usage_limits_redemptions bigint,
    "value" double precision,
    value_type text,
    PRIMARY KEY (id)
);

CREATE TABLE address_discounts (
    "index" integer,
    address_id bigint,
    id bigint,
    PRIMARY KEY ("index", address_id),
    FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE address (
    id bigint,
    customer_id bigint,
    payment_method_id bigint,
    address_1 text,
    address_2 text,
    city text,
    company text,
    country_code text,
    created_at timestamp,
    first_name text,
    last_name text,
    order_note text,
    phone text,
    province text,
    updated_at timestamp,
    zip text,
    -- cart_attribute_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (payment_method_id) REFERENCES payment_method(id)
);

CREATE TABLE address_shipping_line (
    "index" integer,
    address_id bigint,
    code text,
    price text,
    title text,
    PRIMARY KEY ("index", address_id),
    FOREIGN KEY (address_id) REFERENCES address(id)
);

CREATE TABLE checkout_line_item (
    "index" integer,
    checkout_token text,
    charge_interval_frequency bigint,
    cutoff_day_of_month text,
    cutoff_day_of_week text,
    expire_after_specific_number_of_charges text,
    first_recurring_charge_delay text,
    fulfillment_service text,
    grams integer,
    image text,
    line_price text,
    order_day_of_month text,
    order_day_of_week text,
    order_interval_frequency bigint,
    order_interval_unit text,
    order_interval_unit_type text,
    original_price text,
    price text,
    product_id bigint,
    product_type text,
    properties jsonb,
    quantity integer,
    recurring_price text,
    requires_shipping boolean,
    sku text,
    tax_code text,
    taxable boolean,
    title text,
    "type" text,
    variant_id bigint,
    variant_title text,
    vendor text,
    PRIMARY KEY ("index", checkout_token),
    FOREIGN KEY (checkout_token) REFERENCES checkout(token)
);

CREATE TABLE checkout_utm_tag (
    _fivetran_id text,
    checkout_token text,
    campaign text,
    content text,
    data_source text,
    medium text,
    "source" text,
    term text,
    time_stamp timestamp,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (checkout_token) REFERENCES checkout(token)
);

CREATE TABLE checkout (
    token text,
    charge_id bigint,
    applied_discounts jsonb,
    billing_address_address_1 text,
    billing_address_address_2 text,
    billing_address_city text,
    billing_address_company text,
    billing_address_country_code text,
    billing_address_first_name text,
    billing_address_last_name text,
    billing_address_phone text,
    billing_address_province text,
    billing_address_zip text,
    buyer_accepts_marketing boolean,
    completed_at timestamp,
    created_at timestamp,
    currency text,
    discount_code text,
    email text,
    external_checkout_id text,
    external_checkout_source text,
    external_transaction_id_payment_processor text,
    order_attributes jsonb,
    phone text,
    requires_shipping boolean,
    shipping_address_address_1 text,
    shipping_address_address_2 text,
    shipping_address_city text,
    shipping_address_company text,
    shipping_address_country_code text,
    shipping_address_first_name text,
    shipping_address_last_name text,
    shipping_address_phone text,
    shipping_address_province text,
    shipping_address_validations_country_is_supported boolean,
    shipping_address_validations_ups boolean,
    shipping_address_zip text,
    subtotal_price text,
    taxes_included boolean,
    total_price text,
    total_tax text,
    updated_at timestamp,
    PRIMARY KEY (token),
    FOREIGN KEY (charge_id) REFERENCES charge(id)
);
