CREATE TABLE line_item_history (
    id text,
    updated_at timestamp,
    account_id text,
    add_on_id text,
    invoice_id text,
    original_line_item_invoice_id text,
    plan_id text,
    previous_line_item_id text,
    subscription_id text,
    accounting_code text,
    add_on_code text,
    amount text,
    created_at text,
    credit_applied text,
    credit_reason_code text,
    currency text,
    description text,
    discount text,
    end_date text,
    invoice_number text,
    legacy_category text,
    origin text,
    plan_code text,
    product_code text,
    proration_rate text,
    quantity text,
    refund text,
    refunded_quantity text,
    start_date text,
    "state" text,
    subtotal text,
    tax text,
    tax_code text,
    tax_exempt text,
    tax_rate text,
    tax_region text,
    tax_type text,
    taxable text,
    "type" text,
    unit_amount text,
    uuid text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (account_id) REFERENCES account_history(id),
    FOREIGN KEY (add_on_id) REFERENCES plan_add_on_history(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice_history(id),
    FOREIGN KEY (original_line_item_invoice_id) REFERENCES invoice_history(id),
    FOREIGN KEY (plan_id) REFERENCES plan_history(id),
    FOREIGN KEY (previous_line_item_id) REFERENCES line_item_history(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription_history(id)
);

CREATE TABLE account_note_history (
    id text,
    account_id text,
    account_updated_at timestamp,
    created_at text,
    message text,
    object text,
    user_email text,
    user_id text,
    PRIMARY KEY (id, account_id, account_updated_at),
    FOREIGN KEY (account_id) REFERENCES account_history(id),
    FOREIGN KEY (account_updated_at) REFERENCES account_history(updated_at)
);

CREATE TABLE transaction_subscription (
    subscription_id text,
    transaction_id text,
    PRIMARY KEY (subscription_id, transaction_id),
    FOREIGN KEY (subscription_id) REFERENCES subscription_history(id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE "transaction" (
    id text,
    account_id text,
    original_transaction_id text,
    amount text,
    avs_check text,
    billing_city text,
    billing_country text,
    billing_first_name text,
    billing_last_name text,
    billing_phone text,
    billing_postal_code text,
    billing_region text,
    billing_street_1 text,
    billing_street_2 text,
    collected_at text,
    collection_method text,
    created_at text,
    currency text,
    customer_message text,
    customer_message_locale text,
    cvv_check text,
    gateway_approval_code text,
    gateway_message text,
    gateway_reference text,
    gateway_response_code text,
    gateway_response_time text,
    gateway_response_values text,
    invoice_id text,
    ip_address_country text,
    ip_address_v_4 text,
    origin text,
    payment_gateway_id text,
    payment_gateway_name text,
    payment_gateway_type text,
    payment_method_card_type text,
    payment_method_exp_month text,
    payment_method_exp_year text,
    payment_method_first_six text,
    payment_method_last_four text,
    payment_method_object text,
    refunded text,
    "status" text,
    status_code text,
    status_message text,
    success text,
    "type" text,
    updated_at timestamp,
    uuid text,
    voided_at text,
    voided_by_invoice_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account_history(id),
    FOREIGN KEY (original_transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE account_acquisition_history (
    id text,
    updated_at timestamp,
    account_id text,
    campaign text,
    channel text,
    cost_account text,
    cost_currency text,
    created_at text,
    subchannel text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (account_id) REFERENCES account_history(id)
);

CREATE TABLE account_balance_history (
    account_id text,
    account_updated_at timestamp,
    currency text,
    amount text,
    past_due text,
    PRIMARY KEY (account_id, account_updated_at, currency)
);

CREATE TABLE coupon_redemption_history (
    id text,
    updated_at timestamp,
    account_id text,
    coupon_id text,
    created_at text,
    currency text,
    discounted text,
    removed_at text,
    "state" text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (account_id) REFERENCES account_history(id),
    FOREIGN KEY (coupon_id) REFERENCES coupon_history(id)
);

CREATE TABLE coupon_discount (
    _fivetran_id text,
    coupon_id text,
    amount text,
    currency text,
    percentage text,
    trial_length text,
    trial_unit text,
    "type" text,
    PRIMARY KEY (_fivetran_id, coupon_id)
);

CREATE TABLE coupon_plan_history (
    coupon_id text,
    coupon_updated_at timestamp,
    plan_id text,
    PRIMARY KEY (coupon_id, coupon_updated_at, plan_id),
    FOREIGN KEY (coupon_id) REFERENCES coupon_history(id),
    FOREIGN KEY (coupon_updated_at) REFERENCES coupon_history(updated_at),
    FOREIGN KEY (plan_id) REFERENCES plan_history(id)
);

CREATE TABLE coupon_history (
    id text,
    updated_at timestamp,
    applies_to_all_plans text,
    applies_to_non_plan_charges text,
    code text,
    coupon_type text,
    created_at text,
    duration text,
    expired_at text,
    free_trial_amount text,
    free_trial_unit text,
    hosted_page_description text,
    invoice_description text,
    max_redemptions text,
    max_redemptions_per_account text,
    "name" text,
    redeem_by text,
    redemption_resource text,
    "state" text,
    temporal_amount text,
    temporal_unit text,
    unique_code_template text,
    unique_coupon_codes_count text,
    PRIMARY KEY (id, updated_at)
);

CREATE TABLE bulk_unique_code (
    id text,
    bulk_code text,
    code text,
    created_at text,
    expired_at text,
    object text,
    redeemed_at text,
    "state" text,
    updated_at timestamp,
    PRIMARY KEY (id, bulk_code),
    FOREIGN KEY (bulk_code) REFERENCES coupon_history(id)
);

CREATE TABLE subscription_gift_card_mapping (
    updated_at text,
    uuid text,
    converted_at text,
    started_with_gift text,
    PRIMARY KEY (updated_at, uuid),
    FOREIGN KEY (updated_at) REFERENCES subscription_history(updated_at),
    FOREIGN KEY (uuid) REFERENCES subscription_history(uuid)
);

CREATE TABLE invoice_coupon_redemption_history (
    coupon_redemption_id text,
    invoice_id text,
    invoice_updated_at timestamp,
    PRIMARY KEY (coupon_redemption_id, invoice_id, invoice_updated_at),
    FOREIGN KEY (coupon_redemption_id) REFERENCES coupon_redemption_history(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice_history(id),
    FOREIGN KEY (invoice_updated_at) REFERENCES invoice_history(updated_at)
);

CREATE TABLE credit_payment_history (
    id text,
    updated_at timestamp,
    account_id text,
    applied_to_invoice_id text,
    original_credit_payment_id text,
    original_invoice_id text,
    refund_transaction_id text,
    "action" text,
    amount text,
    created_at text,
    currency text,
    uuid text,
    voided_at text,
    PRIMARY KEY (id, updated_at, account_id),
    FOREIGN KEY (account_id) REFERENCES account_history(id),
    FOREIGN KEY (applied_to_invoice_id) REFERENCES invoice_history(id),
    FOREIGN KEY (original_credit_payment_id) REFERENCES "transaction"(id),
    FOREIGN KEY (original_invoice_id) REFERENCES invoice_history(id),
    FOREIGN KEY (refund_transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE plan_currency_history (
    currency text,
    plan_id text,
    plan_updated_at timestamp,
    setup_fees text,
    unit_amount text,
    PRIMARY KEY (currency, plan_id, plan_updated_at),
    FOREIGN KEY (plan_id) REFERENCES plan_history(id),
    FOREIGN KEY (plan_updated_at) REFERENCES plan_history(updated_at)
);

CREATE TABLE plan_history (
    id text,
    updated_at timestamp,
    accounting_code text,
    auto_renew text,
    code text,
    created_at text,
    deleted_at text,
    description text,
    hosted_pages_bypass_confirmation text,
    hosted_pages_cancel_url text,
    hosted_pages_display_quantity text,
    hosted_pages_success_url text,
    interval_length text,
    interval_unit text,
    "name" text,
    setup_fee_accounting_code text,
    "state" text,
    tax_code text,
    tax_exempt text,
    total_billing_cycles text,
    trial_length text,
    trial_unit text,
    PRIMARY KEY (id, updated_at)
);

CREATE TABLE gift_card (
    id text,
    balance_in_cents text,
    canceled_at text,
    created_at text,
    currency text,
    delivered_at text,
    delivery_address_address_1 text,
    delivery_address_address_2 text,
    delivery_address_city text,
    delivery_address_country text,
    delivery_address_phone text,
    delivery_address_state text,
    delivery_address_zip text,
    delivery_deliver_at text,
    delivery_email_address text,
    delivery_first_name text,
    delivery_gifter_name text,
    delivery_last_name text,
    delivery_method text,
    delivery_personal_message text,
    gifter_account text,
    product_code text,
    purchase_invoice text,
    recipient_account text,
    redeemed_at text,
    redemption_code text,
    redemption_invoice text,
    unit_amount_in_cents text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE subscription_add_on_history (
    id text,
    updated_at text,
    plan_add_on_id text,
    subscription_id text,
    created_at text,
    expired_at text,
    object text,
    quantity text,
    unit_amount text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (plan_add_on_id) REFERENCES plan_add_on_history(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription_history(id)
);

CREATE TABLE subscription_change_history (
    id text,
    updated_at text,
    plan_id text,
    subscription_id text,
    activate_at text,
    activated text,
    created_at text,
    deleted_at text,
    object text,
    quantity text,
    unit_amount text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (plan_id) REFERENCES plan_history(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription_history(id)
);

CREATE TABLE subscription_coupon_redemption_history (
    coupon_redemption_id text,
    subscription_history_id text,
    subscription_updated_at text,
    PRIMARY KEY (coupon_redemption_id, subscription_history_id, subscription_updated_at),
    FOREIGN KEY (coupon_redemption_id) REFERENCES coupon_redemption_history(id),
    FOREIGN KEY (subscription_history_id) REFERENCES subscription_history(id),
    FOREIGN KEY (subscription_updated_at) REFERENCES subscription_history(updated_at)
);

CREATE TABLE subscription_history (
    id text,
    updated_at text,
    account_id text,
    plan_id text,
    shipping_address_id text,
    activated_at text,
    add_ons_total text,
    auto_renew text,
    bank_account_authorized_at text,
    canceled_at text,
    collection_method text,
    created_at text,
    currency text,
    current_period_ends_at text,
    current_period_started_at text,
    current_term_ends_at text,
    current_term_started_at text,
    customer_notes text,
    expiration_reason text,
    expires_at text,
    net_terms text,
    object text,
    paused_at text,
    po_number text,
    quantity text,
    remaining_billing_cycles text,
    remaining_pause_cycles text,
    renewal_billing_cycles text,
    "state" text,
    subtotal text,
    terms_and_conditions text,
    total_billing_cycles text,
    trial_ends_at text,
    trial_started_at text,
    unit_amount text,
    uuid text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (account_id) REFERENCES account_history(id),
    FOREIGN KEY (plan_id) REFERENCES plan_history(id),
    FOREIGN KEY (shipping_address_id) REFERENCES shipping_address_history(id)
);

CREATE TABLE plan_add_on_currency_history (
    currency text,
    plan_add_on_id text,
    plan_add_on_updated_at timestamp,
    unit_amount text,
    PRIMARY KEY (currency, plan_add_on_id, plan_add_on_updated_at),
    FOREIGN KEY (plan_add_on_id) REFERENCES plan_add_on_history(id),
    FOREIGN KEY (plan_add_on_updated_at) REFERENCES plan_add_on_history(updated_at)
);

CREATE TABLE plan_add_on_history (
    id text,
    updated_at timestamp,
    plan_id text,
    accounting_code text,
    code text,
    created_at text,
    default_quantity text,
    deleted_at text,
    display_quantity text,
    "name" text,
    object text,
    "state" text,
    tax_code text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (plan_id) REFERENCES plan_history(id)
);

CREATE TABLE invoice_subscription_history (
    invoice_id text,
    invoice_updated_at timestamp,
    subscription_id text,
    PRIMARY KEY (invoice_id, invoice_updated_at, subscription_id),
    FOREIGN KEY (invoice_id) REFERENCES invoice_history(id),
    FOREIGN KEY (invoice_updated_at) REFERENCES invoice_history(updated_at),
    FOREIGN KEY (subscription_id) REFERENCES subscription_history(id)
);

CREATE TABLE invoice_history (
    id text,
    updated_at timestamp,
    account_id text,
    previous_invoice_id text,
    balance text,
    closed_at text,
    collection_method text,
    created_at text,
    currency text,
    customer_notes text,
    discount text,
    due_at text,
    invoice_city text,
    invoice_country text,
    invoice_first_name text,
    invoice_last_name text,
    invoice_name_on_account text,
    invoice_phone text,
    invoice_postal_code text,
    invoice_region text,
    invoice_street_1 text,
    invoice_street_2 text,
    net_terms text,
    number text,
    origin text,
    paid text,
    po_number text,
    refundable_amount text,
    "state" text,
    subtotal text,
    tax text,
    tax_rate text,
    tax_region text,
    tax_type text,
    terms_and_conditions text,
    total text,
    "type" text,
    vat_reverse_charge_notes text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (account_id) REFERENCES account_history(id),
    FOREIGN KEY (previous_invoice_id) REFERENCES invoice_history(id)
);

CREATE TABLE billing_info_history (
    id text,
    updated_at text,
    account_id text,
    billing_city text,
    billing_country text,
    billing_first_name text,
    billing_last_name text,
    billing_phone text,
    billing_postal_code text,
    billing_region text,
    billing_street_1 text,
    billing_street_2 text,
    company text,
    created_at text,
    first_name text,
    fraud_decision text,
    fraud_risk_rules_triggered jsonb,
    fraud_score text,
    last_name text,
    payment_method_card_type text,
    payment_method_exp_month text,
    payment_method_exp_year text,
    payment_method_first_six text,
    payment_method_last_four text,
    payment_method_object text,
    updated_by_country text,
    updated_by_ip text,
    valid text,
    vat_number text,
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (account_id) REFERENCES account_history(id)
);

CREATE TABLE shipping_address_history (
    id text,
    updated_at text,
    account_id text,
    city text,
    company text,
    country text,
    created_at text,
    email text,
    first_name text,
    last_name text,
    nickname text,
    phone text,
    postal_code text,
    region text,
    street_1 text,
    street_2 text,
    vat_number text,
    PRIMARY KEY (id, updated_at, account_id),
    FOREIGN KEY (account_id) REFERENCES account_history(id)
);

CREATE TABLE account_history (
    id text,
    updated_at timestamp,
    parent_account_id text,
    account_city text,
    account_country text,
    account_first_name text,
    account_last_name text,
    account_phone text,
    account_postal_code text,
    account_region text,
    account_street_1 text,
    account_street_2 text,
    bill_to text,
    cc_emails text,
    code text,
    company text,
    created_at text,
    deleted_at text,
    email text,
    exemption_certificate text,
    first_name text,
    hosted_login_token text,
    last_name text,
    preferred_locale text,
    "state" text,
    tax_exempt text,
    username text,
    vat_number text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, updated_at),
    FOREIGN KEY (parent_account_id) REFERENCES account_history(id)
);
