CREATE TABLE tax_tax_rate (
    tax_id text,
    tax_rate_id text,
    PRIMARY KEY (tax_id, tax_rate_id),
    FOREIGN KEY (tax_id) REFERENCES tax(id),
    FOREIGN KEY (tax_rate_id) REFERENCES tax_rate(id)
);

CREATE TABLE tax (
    id text,
    created_by text,
    updated_by text,
    active text,
    agency text,
    created_date text,
    dining_options text,
    establishment text,
    fiscal_rate text,
    maximum_quantity_threshold text,
    maximum_threshold text,
    min_quantity_threshold text,
    min_threshold text,
    "name" text,
    rounding_type text,
    tax_type text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE inventory (
    id text,
    product text,
    cost text,
    quantity_in_hand text,
    quantity_in_layaway text,
    threshold text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (product) REFERENCES product(uri)
);

CREATE TABLE store_address (
    id text,
    created_by text,
    updated_by text,
    active text,
    alias text,
    building_number text,
    city_name text,
    country text,
    county text,
    created_date text,
    district text,
    door text,
    is_external text,
    latitude text,
    line_1 text,
    line_2 text,
    longitude text,
    province text,
    "state" text,
    updated_date text,
    uri text,
    uuid text,
    zip_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE product_product_group (
    product_group text,
    product_id text,
    PRIMARY KEY (product_group, product_id),
    FOREIGN KEY (product_group) REFERENCES product_group(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_printer (
    printer text,
    product_id text,
    PRIMARY KEY (printer, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_list_printer (
    list_printer text,
    product_id text,
    PRIMARY KEY (list_printer, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE combo_discount_product (
    combo_discount_product text,
    product_id text,
    PRIMARY KEY (combo_discount_product, product_id),
    FOREIGN KEY (combo_discount_product) REFERENCES product(uri),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_combo_set (
    combo_product_set_id text,
    product_id text,
    PRIMARY KEY (combo_product_set_id, product_id),
    FOREIGN KEY (combo_product_set_id) REFERENCES combo_product_set(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_product_category (
    category text,
    product_id text,
    PRIMARY KEY (category, product_id),
    FOREIGN KEY (category) REFERENCES product_category(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    category text,
    created_by text,
    parent_product text,
    product_class text,
    tax_id text,
    updated_by text,
    active text,
    allow_price_override text,
    attribute_1 text,
    attribute_1_name text,
    attribute_2 text,
    attribute_2_name text,
    attribute_parent text,
    attribute_type text,
    attribute_value_1 text,
    attribute_value_2 text,
    barcode text,
    bin_value text,
    color_code text,
    combo_product_1 text,
    combo_product_2 text,
    combo_product_3 text,
    combo_product_4 text,
    combo_product_5 text,
    combo_product_6 text,
    combo_product_7 text,
    combo_product_8 text,
    combo_saving_productset text,
    combo_upcharge text,
    comments text,
    commission text,
    commission_type text,
    conv_ordering_disp text,
    conv_ordering_sort_order text,
    cost text,
    course_number text,
    created_date text,
    crv_enabled text,
    crv_label text,
    crv_value text,
    default_inventory text,
    delivery_method text,
    dept text,
    description text,
    disable_modifier_popup text,
    discountable text,
    display_on_kiosk text,
    display_online text,
    dynamic_combo text,
    ebt_no text,
    eligible_for_purchase_rewards text,
    end_date text,
    establishment text,
    export text,
    flat_tax_units text,
    happy_hour_price text,
    image text,
    increase_group_combo_price_based_on_upcharge text,
    is_cold text,
    is_combo text,
    is_drink text,
    is_food text,
    item_no text,
    kitchen_description text,
    kitchen_print_name text,
    label_date text,
    limit_type text,
    limit_value text,
    manufacturer text,
    maximum_price text,
    maximum_threshold_price text,
    min_price text,
    msrp text,
    "name" text,
    negative_sales_restricted text,
    not_returnable text,
    original_price text,
    parent_dynamic_combo text,
    percent_markup text,
    point_redeem text,
    point_value text,
    pos_column_width text,
    prep_recipe text,
    prep_yield text,
    preparation_time text,
    prevent_sales text,
    price text,
    price_embedded text,
    print_tags text,
    product_brand text,
    product_height text,
    product_height_unit text,
    product_length text,
    product_length_unit text,
    product_price_in_combo text,
    product_weight text,
    product_weight_unit text,
    product_width text,
    product_width_unit text,
    promotional_product text,
    prompt_for_quantity text,
    prompt_for_upsell text,
    purchase_product_age text,
    purchase_product_age_msg text,
    purchase_reward_multiplier text,
    quick_pick_group text,
    receipt_text text,
    redemption_level text,
    require_serial_number text,
    retail text,
    rti_combo text,
    seasonal_item text,
    service_duration text,
    set_price_per_group_for_combo text,
    shelf_label_quantity text,
    shopify_sku text,
    show_on_pos text,
    size_chart text,
    sku text,
    sold_by_weight text,
    sorting text,
    start_date text,
    surcharge text,
    tare text,
    tax_class text,
    tax_included text,
    third_party_id text,
    track_in_inventory text,
    track_recipe text,
    "type" text,
    unit_size text,
    uom text,
    updated_date text,
    upsell_combo_price text,
    uri text,
    uuid text,
    variable_pricing text,
    variable_pricing_by text,
    PRIMARY KEY (id),
    FOREIGN KEY (category) REFERENCES product_category(uri),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (parent_product) REFERENCES product(uri),
    FOREIGN KEY (product_class) REFERENCES product_class(uri),
    FOREIGN KEY (tax_id) REFERENCES tax(id),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE order_package (
    package text,
    order_id text,
    PRIMARY KEY (package, order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE order_history (
    order_history text,
    order_id text,
    PRIMARY KEY (order_history, order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE orders (
    id text,
    bill_parent text,
    created_by text,
    customer text,
    delivery_employee text,
    discounted_by text,
    table_owner text,
    tax text,
    updated_by text,
    asap text,
    auto_grat_pct text,
    bill_number text,
    billing_address text,
    billing_zip_code text,
    bills_info text,
    bills_type text,
    call_name text,
    call_number text,
    check_sum text,
    closed text,
    created_at text,
    created_date text,
    crv_taxed text,
    crv_value text,
    customer_address_distance text,
    customer_birthdate text,
    deleted text,
    deleted_discounts text,
    delivery_active text,
    delivery_city text,
    delivery_clock_in text,
    delivery_clock_out text,
    delivery_company_name text,
    delivery_country text,
    delivery_distance text,
    delivery_duration text,
    delivery_email text,
    delivery_estimated_distance text,
    delivery_id text,
    delivery_instruction text,
    delivery_latitude text,
    delivery_longitude text,
    delivery_name text,
    delivery_phone_number text,
    delivery_primary_billing text,
    delivery_primary_shipping text,
    delivery_state text,
    delivery_street_1 text,
    delivery_uuid text,
    delivery_zip_code text,
    device_id text,
    dining_option text,
    discount_code text,
    discount_nontaxable_surcharge_included text,
    discount_reason text,
    discount_rule_type text,
    drive_through_data text,
    establishment text,
    exchange_discount text,
    exchanged text,
    external_sync text,
    final_total text,
    fleet_service_data text,
    gift_reward_data text,
    gratuity text,
    gratuity_type text,
    has_delivery_info text,
    has_history text,
    has_items text,
    house_account_applied text,
    invoice_date text,
    is_discounted text,
    is_invoice text,
    is_readonly text,
    is_unpaid text,
    kitchen_status text,
    last_updated_at text,
    local_id text,
    loyalty_account_id text,
    notes text,
    notification_email_sent text,
    notification_text_sent text,
    number_of_people text,
    pickup_call_name text,
    pickup_customer_arrived text,
    pickup_email text,
    pickup_phone_number text,
    pickup_pickup_type text,
    pickup_send_confirmation text,
    pickup_status text,
    pickup_vehicle_color text,
    pickup_vehicle_make text,
    pickup_vehicle_type text,
    points_added text,
    points_redeemed text,
    pos_mode text,
    prevailing_surcharge text,
    prevailing_tax text,
    printed text,
    registry_coo_counter text,
    registry_custom_data text,
    registry_fiscale_sale_id text,
    registry_id text,
    registry_printer_serial text,
    registry_uri text,
    remaining_due text,
    reporting_id text,
    rounding_delta text,
    running_tax_number text,
    sent text,
    service_fee_tax text,
    service_fee_taxed text,
    service_fee_untaxed text,
    smart_order text,
    smartpay_gratuity text,
    smartpay_tip text,
    subtotal text,
    surcharge text,
    surcharge_excluded text,
    tables text,
    tax_country text,
    tax_excluded_amount text,
    tax_rebate text,
    tax_rounding_model text,
    taxable_surcharge text,
    taxable_surcharge_excluded text,
    updated_date text,
    uri text,
    uuid text,
    vehicle text,
    version text,
    virtual_delivery_track_link text,
    virtual_order_status text,
    virtual_third_party_order_id text,
    web_order text,
    PRIMARY KEY (id),
    FOREIGN KEY (bill_parent) REFERENCES orders(uri),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (customer) REFERENCES customer(uri),
    FOREIGN KEY (delivery_employee) REFERENCES users(uri),
    FOREIGN KEY (discounted_by) REFERENCES users(uri),
    FOREIGN KEY (table_owner) REFERENCES users(uri),
    FOREIGN KEY (tax) REFERENCES tax(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE applied_discount (
    id text,
    order_id text,
    order_item_id text,
    discount text,
    "name" text,
    quantity text,
    rule_amount text,
    rule_type text,
    stackable_type text,
    tax_amount_included text,
    taxed text,
    "type" text,
    uri text,
    uuid text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (order_item_id) REFERENCES order_item(id)
);

CREATE TABLE order_item_applied_tax (
    "type" text,
    applied_tax_order_id text,
    order_item_id text,
    PRIMARY KEY ("type", applied_tax_order_id),
    FOREIGN KEY (applied_tax_order_id) REFERENCES applied_tax_order(id),
    FOREIGN KEY (order_item_id) REFERENCES order_item(id)
);

CREATE TABLE order_item_applied_service_fee (
    "type" text,
    applied_service_fee_id text,
    parent_id text,
    PRIMARY KEY ("type", applied_service_fee_id, parent_id),
    FOREIGN KEY (applied_service_fee_id) REFERENCES applied_service_fee(id),
    FOREIGN KEY (parent_id) REFERENCES order_item(id)
);

CREATE TABLE customer_vehicle (
    id text,
    customer_id text,
    active text,
    created_date text,
    manufacturer text,
    model text,
    odometer text,
    owner text,
    plate text,
    "state" text,
    updated_date text,
    uuid text,
    vin text,
    "year" text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_reward_card_number (
    reward_card_number text,
    customer_id text,
    PRIMARY KEY (reward_card_number, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_gift_card_number (
    gift_card_number text,
    customer_id text,
    PRIMARY KEY (gift_card_number, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_group (
    customer_group text,
    customer_id text,
    PRIMARY KEY (customer_group, customer_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer_customer_address (
    address_id text,
    customer_id text,
    PRIMARY KEY (address_id, customer_id),
    FOREIGN KEY (address_id) REFERENCES customer_address(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE customer (
    id text,
    created_by text,
    updated_by text,
    accept_check text,
    active text,
    birth_date text,
    company_name text,
    contract_expiration text,
    created_date text,
    credit_card_exp text,
    credit_card_first_name text,
    credit_card_last_4_digits text,
    credit_card_last_name text,
    deleted text,
    discount text,
    email text,
    email_opt_in text,
    exp_date text,
    expensify_account text,
    first_name text,
    gender text,
    image_resource_uri text,
    image_url text,
    is_visitor text,
    last_name text,
    lic_number text,
    loyalty_number text,
    loyalty_ref_id text,
    notes text,
    ok_to_email text,
    past_due text,
    phone_number text,
    phone_opt_in text,
    picture text,
    pin text,
    post_opt_in text,
    ref_number text,
    "source" text,
    tax_exempt text,
    tax_location text,
    third_party_id text,
    title text,
    track_as_company text,
    "type" text,
    updated_date text,
    uri text,
    uuid text,
    version_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE applied_service_fee (
    id text,
    orders text,
    parent_uuid text,
    amount text,
    application_type text,
    apply_to text,
    created_date text,
    deleted text,
    include_employee_pass_through_fee_in text,
    invoice_document_uuid text,
    item text,
    local_service_fee_id text,
    "name" text,
    pass_through_amount text,
    pass_through_fee_type text,
    pass_through_type text,
    post_tax text,
    sort text,
    tax_amount text,
    taxed text,
    total_amount text,
    "type" text,
    updated_date text,
    uri text,
    uuid text,
    PRIMARY KEY (id),
    FOREIGN KEY (orders) REFERENCES orders(uri),
    FOREIGN KEY (parent_uuid) REFERENCES applied_service_fee(uuid)
);

CREATE TABLE product_group (
    id text,
    created_by text,
    discount text,
    updated_by text,
    active text,
    display text,
    establishment text,
    "name" text,
    sorting text,
    tax_rule text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (discount) REFERENCES discount(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE applied_tax_order (
    id text,
    local_tax_id text,
    orders text,
    dining_options text,
    fiscal_rate text,
    is_prevailing text,
    maximum_quantity_threshold text,
    maximum_threshold text,
    min_quantity_threshold text,
    min_threshold text,
    "name" text,
    on_full_price text,
    rounding_type text,
    tax_rate text,
    tax_table text,
    tax_type text,
    uri text,
    uuid text,
    PRIMARY KEY (id),
    FOREIGN KEY (local_tax_id) REFERENCES tax(id),
    FOREIGN KEY (orders) REFERENCES orders(uri)
);

CREATE TABLE discount_timetable (
    id text,
    discount_id text,
    created_by text,
    updated_by text,
    close_time text,
    created_date text,
    day_of_week text,
    open_time text,
    timetable text,
    updated_date text,
    PRIMARY KEY (id, discount_id),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE discount_product_class (
    discount_id text,
    product_class text,
    PRIMARY KEY (discount_id, product_class),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    FOREIGN KEY (product_class) REFERENCES product_class(id)
);

CREATE TABLE discount_volume_product_group (
    discount_id text,
    volume_product_group text,
    PRIMARY KEY (discount_id, volume_product_group),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    FOREIGN KEY (volume_product_group) REFERENCES product_group(id)
);

CREATE TABLE discount_volume_product_class (
    discount_id text,
    volume_product_class text,
    PRIMARY KEY (discount_id, volume_product_class),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    FOREIGN KEY (volume_product_class) REFERENCES product_class(id)
);

CREATE TABLE discount_volume_modifier_class (
    volume_modifier_class text,
    discount_id text,
    PRIMARY KEY (volume_modifier_class, discount_id),
    FOREIGN KEY (discount_id) REFERENCES discount(id)
);

CREATE TABLE discount_product_group_price (
    discount_id text,
    product_group text,
    price text,
    PRIMARY KEY (discount_id, product_group),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    FOREIGN KEY (product_group) REFERENCES product_group(id)
);

CREATE TABLE discount_modifier_class (
    modifier_class text,
    discount_id text,
    PRIMARY KEY (modifier_class, discount_id),
    FOREIGN KEY (discount_id) REFERENCES discount(id)
);

CREATE TABLE discount_product_group (
    discount_id text,
    product_group text,
    PRIMARY KEY (discount_id, product_group),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    FOREIGN KEY (product_group) REFERENCES product_group(id)
);

CREATE TABLE discount_product_class_price (
    discount_id text,
    product_class text,
    price text,
    PRIMARY KEY (discount_id, product_class),
    FOREIGN KEY (discount_id) REFERENCES discount(id),
    FOREIGN KEY (product_class) REFERENCES product_class(id)
);

CREATE TABLE discount (
    id text,
    category text,
    created_by text,
    gift text,
    modifier text,
    product text,
    product_class text,
    timetable_created_by text,
    timetable_updated_by text,
    updated_by text,
    action_code text,
    active text,
    admin_key text,
    alt_price_tier text,
    amount text,
    application_type text,
    apply_multiple_times text,
    apply_reprice_to_sum_of_products text,
    apply_to_all_qualifying_products text,
    apply_to_base_product_only text,
    apply_to_entire_application_type text,
    apply_to_weighted_products text,
    at_item_level text,
    auto_apply text,
    awarding text,
    barcode text,
    code text,
    created_date text,
    dining_options text,
    display_on_ipad text,
    dummy_pan text,
    effective_from text,
    effective_to text,
    establishment text,
    exclude_upsell_from_discount text,
    floor text,
    "function" text,
    how_often_apply text,
    is_repeating_cash_off text,
    is_variable text,
    is_wholesale text,
    loyalty_code text,
    maximum_limit double precision,
    maximum_off text,
    method text,
    minimum_amount text,
    minimum_amount_to_entire_order text,
    minimum_limit double precision,
    modifier_class text,
    "name" text,
    old_taxed_flag text,
    ovs_validation text,
    password_required text,
    points_needed_for_redemption text,
    product_from_each_cls_grp text,
    qualification_subtype text,
    qualification_type text,
    receipt_text text,
    reduce_by_product_upcharge_value text,
    restricted_payment_methods_array text,
    rewards_type text,
    scheme_code text,
    stackable_discount_type text,
    tally text,
    target_volume text,
    taxed text,
    tier text,
    timetable_active text,
    timetable_created_date text,
    timetable_establishment text,
    timetable_from_date text,
    timetable_id text,
    timetable_to_date text,
    timetable_type text,
    timetable_updated_date text,
    "type" text,
    updated_date text,
    uri text,
    volume text,
    volume_modifier text,
    volume_modifier_class text,
    volume_product text,
    volume_type text,
    weborder_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (category) REFERENCES product_category(uri),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (gift) REFERENCES product(uri),
    FOREIGN KEY (modifier) REFERENCES modifier_item(uri),
    FOREIGN KEY (product) REFERENCES product(uri),
    FOREIGN KEY (product_class) REFERENCES product_class(uri),
    FOREIGN KEY (timetable_created_by) REFERENCES users(uri),
    FOREIGN KEY (timetable_updated_by) REFERENCES users(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE order_item_modifier (
    item_modifier_id text,
    order_item_id text,
    PRIMARY KEY (item_modifier_id, order_item_id),
    FOREIGN KEY (item_modifier_id) REFERENCES modifier_item(id),
    FOREIGN KEY (order_item_id) REFERENCES order_item(id)
);

CREATE TABLE order_item_ingredient (
    ingredient_item text,
    order_item_id text,
    PRIMARY KEY (ingredient_item, order_item_id),
    FOREIGN KEY (order_item_id) REFERENCES order_item(id)
);

CREATE TABLE order_item_commission_commission (
    commission_id text,
    order_item_id text,
    PRIMARY KEY (commission_id, order_item_id),
    FOREIGN KEY (commission_id) REFERENCES order_item_commission(id),
    FOREIGN KEY (order_item_id) REFERENCES order_item(id)
);

CREATE TABLE order_item (
    id text,
    bill_parent text,
    created_by text,
    discounted_by text,
    gift_card_number text,
    orders text,
    parent_combo_uuid text,
    parent_uuid text,
    product text,
    updated_by text,
    appointment text,
    appointment_ref_uuid text,
    catering_complete text,
    catering_delivery_date text,
    combo_fraction_part text,
    combo_product_set text,
    combo_saving_amount text,
    combo_type text,
    combo_used text,
    combo_uuid text,
    commission_amount text,
    cost text,
    course_number text,
    created_date text,
    crv_value text,
    cup_quantity text,
    cup_weight text,
    date_paid text,
    deleted text,
    deleted_date text,
    dining_option text,
    discount_reason text,
    dynamic_combo text,
    dynamic_combo_slot text,
    ervc_type text,
    event_date text,
    exchange_discount text,
    exchanged text,
    exclude_from_discount text,
    expedited text,
    external_shipping_address text,
    initial_price text,
    invoice_document_uuid text,
    is_cold text,
    is_discounted text,
    is_layaway text,
    is_store_credit text,
    item_type text,
    kitchen_completed text,
    manual_unit_price_adjustment text,
    modifier_amount text,
    modifier_cost text,
    not_returnable text,
    on_hold text,
    on_layaway text,
    order_local_id text,
    package text,
    package_uuid text,
    price text,
    price_to_display text,
    printed text,
    product_name_override text,
    pump_date text,
    pump_number text,
    pure_sales text,
    quantity text,
    reference_discount text,
    reference_discounts text,
    returned_establishment text,
    sales_tax_exemption_reason text,
    scanned_barcode text,
    seat_number text,
    sent text,
    serial_number text,
    service_provider text,
    shared text,
    sold_by_weight text,
    special_request text,
    split_parts text,
    split_type text,
    split_with_seat text,
    start_time text,
    station text,
    tax_amount text,
    tax_included text,
    tax_rate text,
    tax_rebate text,
    taxed_flag text,
    temp_sort text,
    uom text,
    updated_date text,
    uri text,
    uuid text,
    void_ref_uuid text,
    voided_by text,
    voided_date text,
    voided_reason text,
    weight text,
    wholesale_saving_amount text,
    PRIMARY KEY (id),
    FOREIGN KEY (bill_parent) REFERENCES order_item(uri),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (discounted_by) REFERENCES users(uri),
    FOREIGN KEY (gift_card_number) REFERENCES customer_gift_card_number(gift_card_number),
    FOREIGN KEY (orders) REFERENCES orders(uri),
    FOREIGN KEY (parent_combo_uuid) REFERENCES order_item(combo_uuid),
    FOREIGN KEY (parent_uuid) REFERENCES order_item(uuid),
    FOREIGN KEY (product) REFERENCES product(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE users (
    id text,
    additional_data jsonb,
    auth_0_id text,
    date_joined text,
    first_name text,
    google_id text,
    has_ems_access text,
    has_mc_access text,
    is_active text,
    is_bill_to text,
    is_global_super_user text,
    is_reseller text,
    is_sold_to text,
    is_staff text,
    last_login text,
    last_name text,
    ruid text,
    uri text,
    username text,
    PRIMARY KEY (id)
);

CREATE TABLE order_item_commission (
    id text,
    commission_user text,
    created_by text,
    order_item text,
    updated_by text,
    commission_amount text,
    commission_pct text,
    created_date text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (commission_user) REFERENCES users(uri),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (order_item) REFERENCES order_item(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE customer_address (
    id text,
    customer text,
    active text,
    city text,
    company_name text,
    country text,
    created_date text,
    delivery_instructions text,
    email text,
    latitude text,
    longitude text,
    "name" text,
    phone_number text,
    primary_billing text,
    primary_shipping text,
    "state" text,
    street_1 text,
    street_2 text,
    updated_date text,
    uuid text,
    zip_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (customer) REFERENCES customer(uri)
);

CREATE TABLE timesheet (
    id text,
    created_by text,
    employee text,
    parent text,
    updated_by text,
    break_length text,
    break_type text,
    clock_in text,
    clock_out text,
    created_date text,
    department_name text,
    establishment text,
    exempt_salaried text,
    is_auto_clock_out text,
    remarks text,
    returned_date text,
    role_name text,
    role_wage text,
    stage text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (employee) REFERENCES employee(uri),
    FOREIGN KEY (parent) REFERENCES timesheet(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE modifier_item_split_combo (
    "name" text,
    modifier_item_id text,
    "value" text,
    PRIMARY KEY ("name", modifier_item_id),
    FOREIGN KEY (modifier_item_id) REFERENCES modifier_item(id)
);

CREATE TABLE modifier_item (
    id text,
    order_item text,
    conditional_of text,
    is_discounted text,
    is_substituted text,
    mod_type text,
    modifier text,
    modifier_cost text,
    modifier_price text,
    no_modifier_substitute text,
    quantity text,
    quantity_type text,
    substitution_of text,
    uri text,
    uuid text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_item) REFERENCES order_item(uri)
);

CREATE TABLE time_schedule (
    id text,
    created_by text,
    employee text,
    updated_by text,
    break_type text,
    created_date text,
    department text,
    establishment text,
    exempt_salaried text,
    "role" text,
    role_wage text,
    shift_begin_time text,
    shift_end_time text,
    stage text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (employee) REFERENCES employee(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE business_day (
    id text,
    closed text,
    "date" text,
    establishment text,
    opened text,
    third_party_id text,
    uri text,
    uuid text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_role (
    "role" text,
    employee_id text,
    PRIMARY KEY ("role", employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee (
    id text,
    created_by text,
    updated_by text,
    users text,
    active text,
    card text,
    created_date text,
    email text,
    "end" text,
    exempt text,
    external_id text,
    failed_login_attempts text,
    first_name text,
    internal_employee_id text,
    last_login text,
    last_name text,
    last_timesheet_entry text,
    locked_account text,
    locked_account_timestamp text,
    mileage_reimbursement text,
    phone_number text,
    picture text,
    pin text,
    pplc_notification text,
    "start" text,
    updated_date text,
    uri text,
    weekly_wage text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri),
    FOREIGN KEY (users) REFERENCES users(uri)
);

CREATE TABLE tax_rate (
    id text,
    created_by text,
    tax text,
    updated_by text,
    created_date text,
    effective_from text,
    effective_to text,
    tax_rate text,
    tax_table text,
    updated_date text,
    uri text,
    use_tax_table text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (tax) REFERENCES tax(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE product_sub_category (
    product_sub_category_id text,
    product_category_id text,
    PRIMARY KEY (product_sub_category_id, product_category_id),
    FOREIGN KEY (product_category_id) REFERENCES product_category(id)
);

CREATE TABLE product_category (
    id text,
    created_by text,
    parent text,
    updated_by text,
    active text,
    color_code text,
    conv_ordering_disp text,
    conv_ordering_sort_order text,
    created_date text,
    description text,
    establishment text,
    event_info text,
    img_url text,
    is_service text,
    lock_add_product text,
    lock_add_subcategory text,
    "name" text,
    sorting text,
    third_party_id text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (parent) REFERENCES product_category(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE product_class (
    id text,
    created_by text,
    parent text,
    updated_by text,
    active text,
    admin_class_key text,
    created_date text,
    deleted text,
    exclude_from_discount text,
    is_admin_class text,
    "name" text,
    sorting text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (parent) REFERENCES product_class(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);

CREATE TABLE combo_product_set_combo_set (
    _fivetran_id text,
    combo_product_set_id text,
    product text,
    default_qty text,
    sorting text,
    upcharge_price text,
    uri text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (combo_product_set_id) REFERENCES combo_product_set(id),
    FOREIGN KEY (product) REFERENCES product(uri)
);

CREATE TABLE combo_product_set (
    id text,
    created_by text,
    product text,
    updated_by text,
    active text,
    barcode text,
    base_price_on text,
    charge_full_price text,
    combo_type text,
    created_date text,
    is_combo_saving text,
    is_upsell text,
    "name" text,
    pos_column_width text,
    price_in_combo text,
    quantity text,
    surcharge text,
    updated_date text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by) REFERENCES users(uri),
    FOREIGN KEY (product) REFERENCES product(uri),
    FOREIGN KEY (updated_by) REFERENCES users(uri)
);
