CREATE TABLE review_other_attribute (
    "index" text,
    review_id text,
    other_attribute text,
    PRIMARY KEY ("index", review_id),
    FOREIGN KEY (review_id) REFERENCES review(id)
);

CREATE TABLE review (
    id text,
    asin text,
    asin_reviews_link text,
    brand text,
    category text,
    color text,
    competitor text,
    "date" text,
    displayed_rating text,
    edition text,
    helpful_votes text,
    incentive_program text,
    internal_comments text,
    keyword_tagging text,
    media text,
    model text,
    negative_topic_category text,
    nps text,
    perma_link text,
    positive_topic_category text,
    price text,
    product_id text,
    product_name text,
    rating text,
    replied_date text,
    replied_to text,
    replied_user text,
    review text,
    review_id text,
    review_posted_date text,
    review_status text,
    review_status_date text,
    review_translated text,
    reviewer_id text,
    reviewer_name text,
    sentiment_magnitude text,
    sentiment_score text,
    "size" text,
    sku text,
    "source" text,
    "status" text,
    style text,
    syndicated text,
    syndicated_from text,
    system_id text,
    tags text,
    title text,
    top_contributor text,
    verified_review text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);
