CREATE TABLE invoice (
    id text,
    account_id text,
    plan_id text,
    amount_due text,
    amount_paid text,
    amount_remaining text,
    amount_total text,
    application_fee_amount text,
    auto_advance boolean,
    billed_period text,
    billed_usage_filename text,
    charge_automatically boolean,
    contract_id text,
    contract_url text,
    currency text,
    days_until_due integer,
    detailed_usage_url text,
    end_date text,
    event_logs_url text,
    invoice_due_date timestamp,
    invoice_due_date_timestamp integer,
    invoice_number text,
    invoice_paid_date timestamp,
    invoice_paid_date_timestamp integer,
    invoice_pdf_url text,
    invoice_sent_date timestamp,
    invoice_sent_date_timestamp integer,
    paid_out_of_band boolean,
    payment_term text,
    plan_type text,
    provider text,
    provider_id text,
    recognition_amount text,
    recognition_end_date text,
    recognition_start_date text,
    start_date text,
    "status" text,
    uri text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan_tag (
    id text,
    plan_id text,
    date_created timestamp,
    date_updated timestamp,
    description text,
    icon text,
    "name" text,
    organization_id text,
    "status" text,
    "type" text,
    PRIMARY KEY (id, plan_id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE term (
    internal_id text,
    plan_id text,
    id text,
    creator_id text,
    crm_object text,
    crm_object_field text,
    date_created timestamp,
    date_updated timestamp,
    default_value text,
    description text,
    hide_label boolean,
    icon text,
    internal boolean,
    is_required boolean,
    is_standard boolean,
    label text,
    label_content text,
    "name" text,
    options_text text,
    options_value text,
    orders integer,
    organization_id text,
    placeholder text,
    renewal_behavior text,
    show_in_proposal_body boolean,
    show_in_proposal_header boolean,
    term_category text,
    "type" text,
    "value" text,
    PRIMARY KEY (internal_id, plan_id),
    FOREIGN KEY (plan_id) REFERENCES plan(id),
    FOREIGN KEY (id) REFERENCES sku(id)
);

CREATE TABLE rate_metric (
    id text,
    rate_id text,
    divisor double precision,
    end_date_offset integer,
    end_date_offset_period text,
    friendly_name text,
    metric_name text,
    operator text,
    organization_id text,
    product text,
    rounding_behavior text,
    usage_period text,
    PRIMARY KEY (id, rate_id),
    FOREIGN KEY (rate_id) REFERENCES rate(id)
);

CREATE TABLE rate_rate_table (
    id text,
    rate_id text,
    amount text,
    monthly_rate text,
    percentage double precision,
    quantity text,
    quantity_max text,
    quantity_min text,
    rate text,
    PRIMARY KEY (id),
    FOREIGN KEY (rate_id) REFERENCES rate(id)
);

CREATE TABLE rate (
    id text,
    sku_id text,
    end_date_offset integer,
    end_date_offset_period text,
    is_default boolean,
    "name" text,
    usage_period text,
    PRIMARY KEY (id, sku_id),
    FOREIGN KEY (sku_id) REFERENCES sku(id)
);

CREATE TABLE custom_property (
    id text,
    sku_id text,
    enabled boolean,
    friendly_name text,
    mode text,
    "value" text,
    PRIMARY KEY (id, sku_id),
    FOREIGN KEY (sku_id) REFERENCES sku(id)
);

CREATE TABLE sku (
    id text,
    plan_id text,
    adjusted_annual_price text,
    adjusted_monthly_price text,
    adjusted_net_price text,
    adjusted_price text,
    annual_price text,
    billing_end_date text,
    billing_provider_month_plan_id text,
    billing_provider_plan_id text,
    billing_provider_product_id text,
    billing_provider_year_plan_id text,
    billing_start_date text,
    color text,
    contract_length integer,
    creator_id text,
    crm_id text,
    crm_pricebook_2_id text,
    crm_product_2_id text,
    currency text,
    default_quantity integer,
    fraction_digits integer,
    icon text,
    is_discount boolean,
    ledger_code text,
    line_item_description text,
    line_item_title text,
    list_price text,
    monthly_price text,
    "name" text,
    net_price text,
    orders integer,
    organization_id text,
    product_code text,
    quantity integer,
    show_public_discount boolean,
    sku_group text,
    "status" text,
    tax text,
    tiering_model text,
    tiering_model_type text,
    tiering_type text,
    "type" text,
    unit_name text,
    unit_pricing_schedule text,
    updated_line_item_description text,
    PRIMARY KEY (id, plan_id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE plan_group (
    id text,
    date_created timestamp,
    date_updated timestamp,
    description text,
    icon text,
    "name" text,
    organization_id text,
    "status" text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE plan (
    id text,
    plan_group_id text,
    billing_provider_subscription_id text,
    cpq boolean,
    date_created timestamp,
    date_updated timestamp,
    friendly_name text,
    "interval" text,
    interval_count integer,
    is_default boolean,
    public text,
    "status" text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (plan_group_id) REFERENCES plan_group(id)
);

CREATE TABLE account (
    id text,
    parent_account_id text,
    plan_id text,
    account_id text,
    auto_billing text,
    base_contract_id text,
    billing_contact_address text,
    billing_contact_address_2 text,
    billing_contact_bank_account_holder_name text,
    billing_contact_bank_account_holder_type text,
    billing_contact_bank_account_number text,
    billing_contact_bank_country text,
    billing_contact_bank_name text,
    billing_contact_bank_routing_number text,
    billing_contact_city text,
    billing_contact_country text,
    billing_contact_email text,
    billing_contact_first_name text,
    billing_contact_hubspot_contact_id text,
    billing_contact_id text,
    billing_contact_last_name text,
    billing_contact_middle_name text,
    billing_contact_payment_method text,
    billing_contact_phone text,
    billing_contact_postal_code text,
    billing_contact_province text,
    billing_contact_salesforce_contact_id text,
    billing_contact_state text,
    billing_contact_stripe_customer_id text,
    billing_contact_title text,
    blocked boolean,
    date_created timestamp,
    date_updated timestamp,
    email text,
    in_contract boolean,
    "name" text,
    payable boolean,
    primary_instrument_id text,
    "status" text,
    stripe_customer_id text,
    uri text,
    verified boolean,
    PRIMARY KEY (id),
    FOREIGN KEY (parent_account_id) REFERENCES account(id),
    FOREIGN KEY (plan_id) REFERENCES plan(id)
);

CREATE TABLE cost_rate_table (
    id text,
    cost_invoice_id text,
    amount text,
    monthly_rate text,
    percentage double precision,
    quantity text,
    quantity_max text,
    quantity_min text,
    rate text,
    PRIMARY KEY (id),
    FOREIGN KEY (cost_invoice_id) REFERENCES cost(invoice_id)
);

CREATE TABLE usage_object (
    _fivetran_id text,
    cost_invoice_id text,
    amount text,
    cumulative_sum text,
    quantity text,
    resource text,
    time_stamp text,
    unit_rate text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (cost_invoice_id) REFERENCES cost(invoice_id)
);

CREATE TABLE cost (
    account_id text,
    invoice_id text,
    aggregate_amount text,
    aggregate_quantity text,
    currency text,
    date_created timestamp,
    date_updated timestamp,
    description text,
    end_date timestamp,
    is_lifetime boolean,
    pricing_schedule text,
    provider_id text,
    sku_type text,
    start_date timestamp,
    "status" text,
    PRIMARY KEY (account_id, invoice_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id)
);
