CREATE TABLE lead_status_related_status (
    "index" text,
    lead_status_id text,
    related_status text,
    PRIMARY KEY ("index", lead_status_id),
    FOREIGN KEY (lead_status_id) REFERENCES lead_status(id)
);

CREATE TABLE lead_status_rule (
    "index" text,
    lead_status_id text,
    rule text,
    PRIMARY KEY ("index", lead_status_id),
    FOREIGN KEY (lead_status_id) REFERENCES lead_status(id)
);

CREATE TABLE lead_status (
    id text,
    active text,
    all_teams text,
    assign_to_user_in_external_crm text,
    company_id text,
    created_at text,
    deal text,
    do_not_call text,
    email_notification text,
    expiration_event_id text,
    expiration_rules text,
    expiration_status_id text,
    expiration_time text,
    external_id text,
    hotkey text,
    in_big_data text,
    internal text,
    lead_types_excluded_from_expiration jsonb,
    lock_lead_owner text,
    "name" text,
    override_global_statusing_webhook text,
    phone_numbers_ivr_id text,
    popup text,
    prevent_double_statusing text,
    rulecreated_at text,
    ruledefault text,
    rulefrom_status_id text,
    ruleid text,
    rulerules text,
    ruleto_status_id text,
    ruleupdated_at text,
    stop_email text,
    stop_post text,
    team_ids jsonb,
    unassign text,
    update_status_in_external_crm text,
    updated_at text,
    webhook_id text,
    PRIMARY KEY (id)
);

CREATE TABLE event (
    id text,
    lead_id text,
    task_id text,
    user_id text,
    children jsonb,
    company_id text,
    completed text,
    created_at text,
    deleted_at text,
    description text,
    event_id text,
    first_scheduled_for_st text,
    first_scheduled_for_ut text,
    foreign_id text,
    internal text,
    next_scheduled_for_st text,
    next_scheduled_for_ut text,
    notify_mail text,
    notify_popup text,
    on_rabbit text,
    parent_id text,
    repeat_interval text,
    title text,
    updated_at text,
    url text,
    PRIMARY KEY (id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (task_id) REFERENCES general_task(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE call_type (
    id text,
    contact_type_id text,
    created_at text,
    is_queue text,
    label text,
    outbound text,
    priority text,
    "type" text,
    updated_at text,
    visible text,
    PRIMARY KEY (id)
);

CREATE TABLE lead_campaign (
    id text,
    description text,
    eligible_users jsonb,
    "name" text,
    private text,
    tags text,
    vendor_id text,
    PRIMARY KEY (id)
);

CREATE TABLE user_call_type (
    "index" text,
    id text,
    user_id text,
    PRIMARY KEY ("index", id, user_id),
    FOREIGN KEY (id) REFERENCES call_type(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_role (
    id text,
    user_id text,
    flag text,
    label text,
    PRIMARY KEY (id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_custom_field (
    _fivetran_id text,
    user_id text,
    label text,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_team (
    id text,
    user_id text,
    call_type_id text,
    all_users text,
    block_lead_assignment text,
    company_id text,
    created_at text,
    deleted_at text,
    "name" text,
    show_on_call_transfers text,
    state_licensing_for_transfers text,
    updated_at text,
    PRIMARY KEY (id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (call_type_id) REFERENCES call_type(id)
);

CREATE TABLE user_agent_call_type (
    agent_call_type text,
    user_id text,
    PRIMARY KEY (agent_call_type, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    address text,
    assigned_phone text,
    cam_q_state_eligibility text,
    chat_chime text,
    city text,
    company_id text,
    created_at text,
    daily_ricochets text,
    default_email_client text,
    default_signature text,
    default_smtp_credentials_id text,
    deleted_at text,
    disable_call_recording text,
    email text,
    email_custom text,
    email_custom_2 text,
    email_custom_3 text,
    email_from_name text,
    enable_access_to_support_pages_in_ahoy text,
    enable_local_caller_id_on_manual_calls text,
    enable_sms_chime_notification text,
    enable_sms_desktop_notification text,
    enable_tone_on_ivr text,
    enable_vm_notification text,
    enabled_for_dm text,
    enabled_for_predictive_calls text,
    enabled_for_public_campaigns text,
    enabled_for_queue_calls text,
    enabled_for_state_routed_calls text,
    external_crm_id text,
    external_crm_password text,
    first_name text,
    fishbowl_ui_locked_height text,
    fishbowl_ui_locked_state text,
    fishbowl_ui_sticky text,
    gravatar text,
    inbound_caps text,
    is_admin text,
    is_super_admin text,
    last_name text,
    last_status_change_at text,
    lead_managament_action_position text,
    lead_managament_bold_text text,
    lead_management_new_interface_settings_alert text,
    lead_pull_cap text,
    "name" text,
    notified_about_chatbot text,
    office_id text,
    phone text,
    phone_1 text,
    plivo_sip text,
    plivo_user text,
    restrict_calls_to_tagged_leads text,
    ringtone_inbound text,
    ringtone_loop_on_inbound text,
    ringtone_outbound text,
    service_created_at text,
    service_id text,
    service_name text,
    service_title text,
    service_updated_at text,
    show_inbound_dashboard text,
    signature text,
    softphone text,
    "state" text,
    states text,
    "status" text,
    team_member_status text,
    twilio_sip_pass text,
    twilio_sip_user text,
    use_ip_restrictions text,
    view_company_vm text,
    volume_inbound text,
    volume_outbound text,
    zip text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE general_task (
    id text,
    event_id text,
    foreign_id text,
    lead_id text,
    user_id text,
    address jsonb,
    appointment_type_id text,
    card_type text,
    category text,
    company_id text,
    completed text,
    conference_number text,
    created_at text,
    created_at_military text,
    deleted_at text,
    description text,
    end_date text,
    end_time text,
    event_calendars text,
    first_scheduled_for_st text,
    first_scheduled_for_ut text,
    follow text,
    img_url text,
    internal text,
    invitees text,
    lead_key text,
    mail text,
    next_scheduled_for_st text,
    next_scheduled_for_ut text,
    note text,
    on_rabbit text,
    owner text,
    parameters jsonb,
    parent_id text,
    phone_to_call text,
    popup text,
    priority text,
    remind_time text,
    reminder_type text,
    repeat_days text,
    repeat_interval text,
    repeat_quantity text,
    repeat_stop text,
    repeat_type text,
    secret_code text,
    start_date text,
    start_time text,
    "status" text,
    sync_calendar text,
    tags text,
    task_date text,
    task_name text,
    task_owner text,
    task_type text,
    time_without_call text,
    title text,
    updated_at text,
    updated_at_military text,
    PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES event(id),
    FOREIGN KEY (foreign_id) REFERENCES general_task(id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE lead_overview (
    _fivetran_id text,
    lead_id text,
    owner_id text,
    status_id text,
    calls_campaign_queue text,
    calls_dripdial_queue text,
    calls_inbound text,
    calls_real_time text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (status_id) REFERENCES lead_status(id)
);

CREATE TABLE lead_tag (
    id text,
    lead_id text,
    label text,
    manual_created text,
    routing text,
    PRIMARY KEY (id, lead_id),
    FOREIGN KEY (lead_id) REFERENCES lead(id)
);

CREATE TABLE lead (
    id text,
    company_campaign_id text,
    currentowner_id text,
    currentstatus_id text,
    additional_cash text,
    additional_notes text,
    address_1 text,
    address_2 text,
    application_taken text,
    areacode_id text,
    areacode_state_id text,
    bankruptcy text,
    best_time_to_call text,
    bid_price text,
    birth_date text,
    campaign_id text,
    city text,
    close_date text,
    closing_date text,
    co_borrower_first_name text,
    co_borrower_last_name text,
    company_id text,
    company_name text,
    completed_drip_dial text,
    connection text,
    consumer_comments text,
    country text,
    created_at text,
    credit_profile text,
    credit_range text,
    cur_interest_rate text,
    current_loan_amount text,
    current_loan_type text,
    current_rate text,
    current_term text,
    currentowner_email text,
    currentowner_first_name text,
    currentowner_last_name text,
    deleted_at text,
    department text,
    description text,
    division text,
    do_not_call text,
    down_payment text,
    email text,
    email_opt_out text,
    employer text,
    employment_length text,
    environment text,
    external_crm_lead_id text,
    facebook text,
    fax text,
    first_mortgage_balance text,
    first_name text,
    follow text,
    ftc_end text,
    ftc_start text,
    g_plus text,
    gross_monthly_income text,
    has_restricted_tags text,
    hoa_fee text,
    home_value text,
    img_url text,
    income text,
    industry text,
    intended_property_use text,
    ip_address text,
    is_being_called text,
    is_inbound text,
    is_outbound text,
    is_test text,
    l_user_id text,
    landing_page text,
    languages text,
    last_called_at text,
    last_name text,
    last_statused_at text,
    lead_id text,
    lead_import_id text,
    lead_key text,
    lead_source text,
    lead_type text,
    linkedin text,
    lmb_lead_id text,
    loan_purpose text,
    loan_to_value text,
    main_state text,
    main_state_id text,
    manager_name text,
    marital_status text,
    military_eligibility text,
    minimum_payment text,
    modified_by text,
    monthly_debt_payments text,
    mortgage_one_interest text,
    mortgage_two text,
    mortgage_two_interest text,
    no_employees text,
    notes text,
    notified text,
    occupational_status text,
    office_id text,
    office_phone text,
    order_number text,
    owner text,
    phone text,
    phone_1 text,
    phone_2 text,
    phone_3 text,
    pref_call_time text,
    product text,
    property_address text,
    property_city text,
    property_description text,
    property_state text,
    property_state_id text,
    property_type text,
    property_value text,
    property_zip text,
    prospect_id text,
    pulled_timestamp text,
    purchase_price text,
    purchase_year text,
    reference_id text,
    refinance_expectation text,
    revenue text,
    sale_made text,
    second_mortgage_balance text,
    secondary_email text,
    simplybook text,
    skype_id text,
    sms text,
    spouse_first_name text,
    spouse_last_name text,
    ssn text,
    stage text,
    stand text,
    stars text,
    "state" text,
    state_id text,
    stoppost text,
    time_without_call text,
    title text,
    twitter text,
    updated_at text,
    uuid text,
    va_status text,
    velocify_lead_id text,
    vendor_id text,
    vendor_name text,
    website text,
    whisper_message text,
    zip text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (company_campaign_id) REFERENCES lead_campaign(id),
    FOREIGN KEY (currentowner_id) REFERENCES users(id),
    FOREIGN KEY (currentstatus_id) REFERENCES lead_status(id)
);

CREATE TABLE lead_status_history (
    id text,
    lead_id text,
    status_id text,
    user_id text,
    created_at text,
    created_at_military text,
    deleted_at text,
    external text,
    in_big_data text,
    previous_status_id text,
    updated_at text,
    updated_at_military text,
    PRIMARY KEY (id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (status_id) REFERENCES lead_status(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE lead_call_history (
    id text,
    call_type_id text,
    lead_id text,
    user_id text,
    call_queue_id text,
    call_recordings jsonb,
    call_status text,
    call_uuid text,
    caller_id text,
    campaign_id text,
    campaign_name text,
    created_at text,
    created_at_military text,
    duration text,
    hangup_cause text,
    hijacked_a_call text,
    hijacked_by_call_id text,
    ivr_phone_description text,
    ivr_phone_name text,
    phone text,
    record_url text,
    ricochet_number text,
    spam_likely text,
    spam_score text,
    state_routed text,
    to_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (call_type_id) REFERENCES call_type(id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE note_collection (
    id text,
    lead_id text,
    user_id text,
    created_at text,
    note text,
    PRIMARY KEY (id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
