CREATE TABLE campaign_metadata (
    account_id text,
    campaign_id text,
    campaign_objective text,
    campaign_type text,
    country_code text,
    "status" text,
    PRIMARY KEY (account_id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES account_campaign_breakdown(group_by_value)
);

CREATE TABLE campaign_breakdown_subvertical (
    account_id text,
    group_by_value text,
    account_campaign_breakdown_value text,
    acquisitions_by_conversion_date text,
    acquisitions_by_referral_date text,
    audiences text,
    campaign_countries text,
    campaigns text,
    creatives text,
    currency text,
    date_end text,
    date_start text,
    gross_cost text,
    impressions text,
    net_cost text,
    referrals text,
    results_grouped_by text,
    time_zone_variation text,
    PRIMARY KEY (account_id, group_by_value, account_campaign_breakdown_value),
    FOREIGN KEY (account_campaign_breakdown_value) REFERENCES account_campaign_breakdown(group_by_value)
);

CREATE TABLE campaign_breakdown_country (
    account_id text,
    group_by_value text,
    account_campaign_breakdown_value text,
    acquisitions_by_conversion_date text,
    acquisitions_by_referral_date text,
    audiences text,
    campaign_countries text,
    campaigns text,
    creative_name text,
    creatives text,
    currency text,
    date_end text,
    date_start text,
    gross_cost text,
    impressions text,
    net_cost text,
    referrals text,
    results_grouped_by text,
    time_zone_variation text,
    PRIMARY KEY (account_id, group_by_value, account_campaign_breakdown_value),
    FOREIGN KEY (account_campaign_breakdown_value) REFERENCES account_campaign_breakdown(group_by_value)
);

CREATE TABLE account_campaign_breakdown (
    account_id text,
    group_by_value text,
    acquisitions_by_conversion_date text,
    acquisitions_by_referral_date text,
    audiences text,
    campaign_countries text,
    campaign_name text,
    campaigns text,
    creatives text,
    currency text,
    date_end text,
    date_start text,
    gross_cost text,
    impressions text,
    net_cost text,
    referrals text,
    time_zone_variation text,
    PRIMARY KEY (account_id, group_by_value)
);

CREATE TABLE campaign_histogram (
    account_id text,
    date_end text,
    date_start text,
    interval_timestamp text,
    account_campaign_breakdown_value text,
    acquisitions_by_conversion_date text,
    acquisitions_by_referral_date text,
    audiences text,
    campaign_countries text,
    campaigns text,
    creatives text,
    currency text,
    gross_cost text,
    impressions text,
    net_cost text,
    referrals text,
    time_zone_variation text,
    PRIMARY KEY (account_id, date_end, date_start, interval_timestamp, account_campaign_breakdown_value),
    FOREIGN KEY (account_campaign_breakdown_value) REFERENCES account_campaign_breakdown(group_by_value)
);

CREATE TABLE campaign_breakdown_creative (
    account_id text,
    group_by_value text,
    account_campaign_breakdown_value text,
    acquisitions_by_conversion_date text,
    acquisitions_by_referral_date text,
    audiences text,
    campaign_countries text,
    campaigns text,
    creative_name text,
    creatives text,
    currency text,
    date_end text,
    date_start text,
    gross_cost text,
    impressions text,
    net_cost text,
    referrals text,
    results_grouped_by text,
    time_zone_variation text,
    PRIMARY KEY (account_id, group_by_value, account_campaign_breakdown_value),
    FOREIGN KEY (account_campaign_breakdown_value) REFERENCES account_campaign_breakdown(group_by_value)
);

CREATE TABLE campaign_breakdown_audience (
    account_id text,
    group_by_value text,
    account_campaign_breakdown_value text,
    acquisitions_by_conversion_date text,
    acquisitions_by_referral_date text,
    audiences text,
    campaign_countries text,
    campaigns text,
    creative_name text,
    creatives text,
    currency text,
    date_end text,
    date_start text,
    gross_cost text,
    impressions text,
    net_cost text,
    referrals text,
    time_zone_variation text,
    PRIMARY KEY (account_id, group_by_value, account_campaign_breakdown_value),
    FOREIGN KEY (account_campaign_breakdown_value) REFERENCES account_campaign_breakdown(group_by_value)
);

CREATE TABLE account_summary (
    account_id text,
    date_end text,
    date_start text,
    campaign_summary_acquisitions_by_conversion_date text,
    campaign_summary_acquisitions_by_referral_date text,
    campaign_summary_audiences text,
    campaign_summary_campaign_countries text,
    campaign_summary_campaigns text,
    campaign_summary_creatives text,
    campaign_summary_gross_cost text,
    campaign_summary_impressions text,
    campaign_summary_net_cost text,
    campaign_summary_referrals text,
    currency text,
    time_zone_variation text,
    transaction_summary_impressions text,
    transaction_summary_placement_impressions text,
    transaction_summary_positive_placement_engagements text,
    transaction_summary_purchases text,
    transaction_summary_referrals text,
    transaction_summary_revenue text,
    transaction_summary_rpm text,
    transaction_summary_rpt text,
    transaction_summary_transactions text,
    PRIMARY KEY (account_id, date_end, date_start)
);

CREATE TABLE account_transaction_overview (
    account_id text,
    date_end text,
    date_start text,
    currency text,
    impressions text,
    placement_impression text,
    positive_placement_engagement text,
    purchases text,
    referrals text,
    revenue text,
    rpm text,
    rpt text,
    time_zone_variation text,
    transactions text,
    PRIMARY KEY (account_id, date_end, date_start)
);

CREATE TABLE account_transaction_breakdown (
    _fivetran_id text,
    account_id text,
    currency text,
    date_end text,
    date_start text,
    group_by_value text,
    impressions text,
    placement_impressions text,
    positive_placement_engagements text,
    purchases text,
    referrals text,
    revenue text,
    rpm text,
    rpt text,
    time_zone_variation text,
    transactions text,
    PRIMARY KEY (_fivetran_id)
);
