CREATE TABLE invoice_recurrence_item (
    id text,
    invoice_recurrence_id text,
    cost text,
    description text,
    price text,
    quantity text,
    uri text,
    PRIMARY KEY (id, invoice_recurrence_id),
    FOREIGN KEY (id) REFERENCES lib_item(id),
    FOREIGN KEY (invoice_recurrence_id) REFERENCES invoice_recurrence(id)
);

CREATE TABLE invoice_recurrence (
    id text,
    contract_id text,
    location_id text,
    service_line_id text,
    created text,
    customer_id text,
    customer_name text,
    customer_status text,
    customer_uri text,
    description text,
    ends_on text,
    frequency text,
    "interval" text,
    next_due text,
    uri text,
    vendor_id text,
    vendor_name text,
    vendor_status text,
    vendor_uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE service_line (
    id text,
    abbr text,
    icon text,
    "name" text,
    trade text,
    PRIMARY KEY (id)
);

CREATE TABLE account (
    id text,
    company_id text,
    "name" text,
    timezone text,
    uri text,
    -- feature_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE appointment_office (
    id text,
    appointment_id text,
    city text,
    email text,
    lat text,
    legacy_id text,
    lon text,
    "name" text,
    phone_number text,
    postal_code text,
    primary_contact text,
    ref_number text,
    "state" text,
    "status" text,
    street text,
    taxable text,
    uri text,
    PRIMARY KEY (id, appointment_id),
    FOREIGN KEY (appointment_id) REFERENCES appointment(id)
);

CREATE TABLE appointment_service_request (
    appointment_id text,
    id text,
    PRIMARY KEY (appointment_id, id),
    FOREIGN KEY (appointment_id) REFERENCES appointment(id),
    FOREIGN KEY (id) REFERENCES service_request(id)
);

CREATE TABLE appointment_tech (
    id text,
    appointment_id text,
    avatar jsonb,
    email text,
    is_helper text,
    is_tech text,
    "name" text,
    "status" text,
    uri text,
    PRIMARY KEY (id, appointment_id),
    FOREIGN KEY (appointment_id) REFERENCES appointment(id)
);

CREATE TABLE appointment (
    id text,
    job_id text,
    location_id text,
    created text,
    due_by text,
    "name" text,
    released text,
    "status" text,
    updated text,
    uri text,
    vendor_id text,
    vendor_name text,
    vendor_status text,
    vendor_uri text,
    window_end text,
    window_start text,
    PRIMARY KEY (id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE quote_job (
    id text,
    quote_id text,
    PRIMARY KEY (id, quote_id),
    FOREIGN KEY (id) REFERENCES job(id),
    FOREIGN KEY (quote_id) REFERENCES quote(id)
);

CREATE TABLE quote_line (
    id text,
    quote_id text,
    PRIMARY KEY (id, quote_id),
    FOREIGN KEY (id) REFERENCES service_line(id),
    FOREIGN KEY (quote_id) REFERENCES quote(id)
);

CREATE TABLE quote_tag (
    id text,
    quote_id text,
    "name" text,
    uri text,
    PRIMARY KEY (id, quote_id),
    FOREIGN KEY (quote_id) REFERENCES quote(id)
);

CREATE TABLE quote_service_request (
    id text,
    quote_id text,
    PRIMARY KEY (id, quote_id),
    FOREIGN KEY (id) REFERENCES service_request(id),
    FOREIGN KEY (quote_id) REFERENCES quote(id)
);

CREATE TABLE quote_deficiency_job (
    id text,
    quote_id text,
    PRIMARY KEY (id, quote_id),
    FOREIGN KEY (id) REFERENCES job(id),
    FOREIGN KEY (quote_id) REFERENCES quote(id)
);

CREATE TABLE quote (
    id text,
    assigned_office_id text,
    assigned_to_id text,
    contract_id text,
    location_id text,
    owner_id text,
    quote_item_id text,
    created text,
    customer_id text,
    customer_name text,
    customer_po text,
    customer_po_required text,
    customer_status text,
    customer_uri text,
    deficiency_severity text,
    description text,
    expires_on text,
    external_ids jsonb,
    job_type text,
    latest_accepted text,
    latest_submission text,
    "name" text,
    notes text,
    quote_link_attachment_visibility text,
    quote_link_comment_visibility text,
    quote_request_id text,
    quote_request_name text,
    quote_request_status text,
    quote_request_type text,
    quote_request_uri text,
    ref_number text,
    respond_by text,
    sales_avatar jsonb,
    sales_email text,
    sales_id text,
    sales_is_helper text,
    sales_is_tech text,
    sales_name text,
    sales_status text,
    sales_uri text,
    section_visibilities text,
    "status" text,
    sub_status text,
    tasking_detail_level text,
    term_id text,
    term_name text,
    term_uri text,
    updated text,
    uri text,
    vendor_id text,
    vendor_name text,
    vendor_status text,
    vendor_uri text,
    visibility jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (assigned_office_id) REFERENCES location(id),
    FOREIGN KEY (assigned_to_id) REFERENCES users(id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (quote_item_id) REFERENCES quote_item(id)
);

CREATE TABLE contact (
    id text,
    company_id text,
    location_id text,
    address_city text,
    address_postal_code text,
    address_state text,
    address_street text,
    alternate_phone text,
    created text,
    email text,
    external_id_device_magic text,
    external_id_master_company text,
    external_id_migration text,
    external_id_new_partner_id text,
    external_id_sage text,
    external_id_sage_employee_id text,
    external_id_sage_test text,
    first_name text,
    last_name text,
    mobile text,
    phone text,
    "status" text,
    "type" text,
    updated text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE user_role (
    id text,
    users_id text,
    "name" text,
    PRIMARY KEY (id, users_id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE user_service_line (
    id text,
    users_id text,
    PRIMARY KEY (id, users_id),
    FOREIGN KEY (id) REFERENCES service_line(id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE user_activity (
    "index" text,
    users_id text,
    activity text,
    PRIMARY KEY ("index", users_id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    account_id text,
    company_id text,
    location_id text,
    manager_id text,
    service_line_id text,
    avatar jsonb,
    created text,
    details text,
    email text,
    external_id jsonb,
    first_name text,
    is_helper text,
    is_sales text,
    is_tech text,
    last_name text,
    mfa_required text,
    "name" text,
    phone text,
    "status" text,
    time_zone text,
    updated text,
    uri text,
    user_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (manager_id) REFERENCES users(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE job_office (
    id text,
    job_id text,
    PRIMARY KEY (id, job_id),
    FOREIGN KEY (id) REFERENCES location(id),
    FOREIGN KEY (job_id) REFERENCES job(id)
);

CREATE TABLE job_tag (
    id text,
    job_id text,
    "name" text,
    uri text,
    PRIMARY KEY (id, job_id),
    FOREIGN KEY (job_id) REFERENCES job(id)
);

CREATE TABLE job_appointment (
    id text,
    job_id text,
    PRIMARY KEY (id, job_id),
    FOREIGN KEY (id) REFERENCES appointment(id),
    FOREIGN KEY (job_id) REFERENCES job(id)
);

CREATE TABLE job (
    id text,
    assigned_office_id text,
    contract_id text,
    current_appointment_id text,
    location_id text,
    owner_id text,
    budgeted text,
    completed_on text,
    created text,
    custom_name text,
    customer_email text,
    customer_id text,
    customer_name text,
    customer_po text,
    customer_status text,
    customer_uri text,
    description text,
    display_status text,
    display_sub_status text,
    due_after text,
    due_by text,
    estimated_price text,
    external_id jsonb,
    is_project text,
    ivr_activity text,
    ivr_open text,
    job_type_weight text,
    latest_clock_in text,
    "name" text,
    number text,
    percent_complete text,
    primary_contact text,
    project text,
    ref_number text,
    sales_avatar jsonb,
    sales_email text,
    sales_id text,
    sales_is_helper text,
    sales_is_tech text,
    sales_name text,
    sales_status text,
    sales_uri text,
    scheduled_date text,
    section_visibilities text,
    service_line text,
    service_link_attachment_category_visibility text,
    service_link_attachment_visibility text,
    service_link_comment_visibility text,
    "status" text,
    sub_status text,
    terms text,
    "type" text,
    updated text,
    uri text,
    vendor_id text,
    vendor_name text,
    vendor_status text,
    vendor_uri text,
    visibility jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (assigned_office_id) REFERENCES location(id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (current_appointment_id) REFERENCES appointment(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE service_recurrence_item (
    id text,
    service_recurrence_id text,
    description text,
    uri text,
    PRIMARY KEY (id, service_recurrence_id),
    FOREIGN KEY (service_recurrence_id) REFERENCES service_recurrence(id)
);

CREATE TABLE service_recurrence_preferred_tech (
    id text,
    service_recurrence_id text,
    avatar jsonb,
    email text,
    is_helper text,
    is_tech text,
    "name" text,
    "status" text,
    uri text,
    PRIMARY KEY (id, service_recurrence_id),
    FOREIGN KEY (service_recurrence_id) REFERENCES service_recurrence(id)
);

CREATE TABLE service_recurrence (
    id text,
    asset_id text,
    contract_id text,
    location_id text,
    service_line_id text,
    created text,
    description text,
    duration text,
    ends_on text,
    estimated_price text,
    first_end text,
    first_start text,
    frequency text,
    frequency_category text,
    "interval" text,
    parent text,
    preferred_start_time text,
    preferred_vendor text,
    repeat_weekday text,
    scheduling_type text,
    tasking_duration text,
    updated text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE lib_item (
    id text,
    company_id text,
    service_line_id text,
    active text,
    code text,
    cost text,
    created text,
    external_id jsonb,
    is_generic text,
    "name" text,
    price text,
    price_rule_type text,
    taxable text,
    "type" text,
    type_id text,
    updated text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE company_service_line_provided (
    id text,
    company_id text,
    abbr text,
    icon text,
    "name" text,
    trade text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE company (
    id text,
    address_city text,
    address_postal_code text,
    address_state text,
    address_street text,
    created text,
    customer text,
    default_brand text,
    external_id_device_magic text,
    external_id_master_company text,
    external_id_migration text,
    external_id_new_partner_id text,
    external_id_sage text,
    external_id_sage_employee_id text,
    external_id_sage_test text,
    logo_aspect text,
    logo_content_url text,
    logo_id text,
    logo_uri text,
    managing_account text,
    "name" text,
    parts_vendor text,
    phone_number text,
    prime_contractor text,
    ref_number text,
    share_id text,
    "status" text,
    tags jsonb,
    updated text,
    uri text,
    vendor text,
    PRIMARY KEY (id)
);

CREATE TABLE service_request_preferred_vendor (
    id text,
    service_request_id text,
    PRIMARY KEY (id, service_request_id),
    FOREIGN KEY (id) REFERENCES company(id),
    FOREIGN KEY (service_request_id) REFERENCES service_request(id)
);

CREATE TABLE service_request_preferred_tech (
    id text,
    service_request_id text,
    PRIMARY KEY (id, service_request_id),
    FOREIGN KEY (id) REFERENCES users(id),
    FOREIGN KEY (service_request_id) REFERENCES service_request(id)
);

CREATE TABLE service_request (
    id text,
    asset_id text,
    contract_id text,
    deficiency_id text,
    job_id text,
    location_id text,
    service_line_id text,
    service_recurrence_id text,
    budget text,
    change_order text,
    change_order_id text,
    change_order_reference_number text,
    change_order_status text,
    change_order_type text,
    change_order_uri text,
    closed_on text,
    created text,
    description text,
    duration text,
    estimated_price text,
    original_window_end text,
    original_window_start text,
    preferred_start_time text,
    quote_link_attachment_visibility text,
    quote_link_comment_visibility text,
    quote_requests jsonb,
    service_link_attachment_category_visibility text,
    service_link_attachment_visibility text,
    service_link_comment_visibility text,
    "status" text,
    task_instances jsonb,
    task_lists jsonb,
    updated text,
    uri text,
    visibility jsonb,
    window_end text,
    window_start text,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (deficiency_id) REFERENCES deficiency(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id),
    FOREIGN KEY (service_recurrence_id) REFERENCES service_recurrence(id)
);

CREATE TABLE deficiency (
    id text,
    asset_id text,
    job_id text,
    location_id text,
    owner_id text,
    service_line_id text,
    created text,
    description text,
    external_id jsonb,
    last_reported_status text,
    proposed_fix text,
    ref_number text,
    report_source text,
    reported_on text,
    reporter_avatar jsonb,
    reporter_email text,
    reporter_id text,
    reporter_is_helper text,
    reporter_is_tech text,
    reporter_name text,
    reporter_status text,
    reporter_uri text,
    resolution text,
    sales_avatar jsonb,
    sales_email text,
    sales_id text,
    sales_is_helper text,
    sales_is_tech text,
    sales_name text,
    sales_status text,
    sales_uri text,
    severity text,
    "status" text,
    title text,
    updated text,
    uri text,
    visibility jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE location_tag (
    id text,
    location_id text,
    "name" text,
    uri text,
    PRIMARY KEY (id, location_id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE location_office (
    id text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES location(id)
);

CREATE TABLE location (
    id text,
    company_id text,
    primary_contact_id text,
    address_city text,
    address_postal_code text,
    address_state text,
    address_street text,
    brand text,
    created text,
    distance text,
    email text,
    external_id jsonb,
    general_manager text,
    geo_code_quality text,
    lat text,
    legacy_id text,
    lon text,
    "name" text,
    phone_number text,
    ref_number text,
    remit_to_address_city text,
    remit_to_address_email text,
    remit_to_address_phone text,
    remit_to_address_postal_code text,
    remit_to_address_state text,
    remit_to_address_street text,
    remit_to_source text,
    "status" text,
    store_number text,
    tax_group_code text,
    tax_group_combined_rate text,
    tax_group_id text,
    tax_group_name text,
    tax_group_state text,
    tax_group_uri text,
    taxable text,
    updated text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (primary_contact_id) REFERENCES contact(id)
);

CREATE TABLE invoice (
    id text,
    job_id text,
    location_id text,
    assigned_office_city text,
    assigned_office_id text,
    assigned_office_lat text,
    assigned_office_legacy_id text,
    assigned_office_lon text,
    assigned_office_name text,
    assigned_office_phone_number text,
    assigned_office_postal_code text,
    assigned_office_primary_contact text,
    assigned_office_ref_number text,
    assigned_office_state text,
    assigned_office_status text,
    assigned_office_street text,
    assigned_office_taxable text,
    assigned_office_uri text,
    assigned_user text,
    contract text,
    created text,
    customer_external_id jsonb,
    customer_id text,
    customer_name text,
    customer_po text,
    customer_status text,
    customer_uri text,
    due_date text,
    invoice_number text,
    "name" text,
    notes text,
    paid text,
    partial text,
    payment_terms text,
    ref_number text,
    sent text,
    "status" text,
    sub_status text,
    tags jsonb,
    tax_amount text,
    term_id text,
    term_name text,
    term_uri text,
    transaction_date text,
    "type" text,
    updated text,
    uri text,
    vendor_id text,
    vendor_name text,
    vendor_status text,
    vendor_uri text,
    visibility jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE contract_rule_lib_item (
    contract_rule_id text,
    id text,
    PRIMARY KEY (contract_rule_id, id),
    FOREIGN KEY (contract_rule_id) REFERENCES contract_rule(id),
    FOREIGN KEY (id) REFERENCES lib_item(id)
);

CREATE TABLE contract_rule (
    id text,
    contract_id text,
    service_line_id text,
    created text,
    "name" text,
    price text,
    threshold text,
    "type" text,
    updated text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (contract_id) REFERENCES contract(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE asset (
    id text,
    location_id text,
    service_line_id text,
    asset_definition_display text,
    asset_definition_id text,
    asset_definition_type text,
    asset_definition_uri text,
    created text,
    display text,
    external_id_device_magic text,
    external_id_master_company text,
    external_id_migration text,
    external_id_new_partner_id text,
    external_id_sage text,
    external_id_sage_employee_id text,
    external_id_sage_test text,
    has_active_task_list text,
    is_abstract_group text,
    legacy_id text,
    "name" text,
    order_index text,
    parent_id text,
    parent_name text,
    parent_type text,
    parent_uri text,
    properties_area text,
    properties_barcode text,
    properties_device_manufacturer text,
    properties_device_model text,
    properties_device_number text,
    properties_device_range text,
    properties_device_type text,
    properties_device_zone_address text,
    properties_location_in_site text,
    properties_serial text,
    properties_system_name text,
    "status" text,
    task_list text,
    "type" text,
    updated text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE quote_item (
    id text,
    lib_item_id text,
    quote_id text,
    service_line_id text,
    service_request_id text,
    cost text,
    description text,
    price text,
    quantity text,
    tax_rate text,
    tax_rate_details jsonb,
    uri text,
    visibility jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (lib_item_id) REFERENCES lib_item(id),
    FOREIGN KEY (quote_id) REFERENCES quote(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id),
    FOREIGN KEY (service_request_id) REFERENCES service_request(id)
);

CREATE TABLE clock_event_unpaired_event (
    id text,
    clock_event_id text,
    appointment_id text,
    job_id text,
    user_id text,
    activity text,
    caller_id_name text,
    caller_id_num text,
    completed text,
    deficiency text,
    event_time text,
    event_type text,
    lat text,
    lon text,
    other_trade_deficiency text,
    red_tag text,
    "source" text,
    started text,
    uri text,
    PRIMARY KEY (id, clock_event_id),
    FOREIGN KEY (clock_event_id) REFERENCES clock_event(id),
    FOREIGN KEY (appointment_id) REFERENCES appointment(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE clock_event (
    id text,
    appointment_id text,
    end_job_id text,
    end_user_id text,
    job_id text,
    user_id text,
    activity text,
    caller_id_name text,
    caller_id_num text,
    completed text,
    created text,
    deficiency text,
    elapsed_time text,
    end_activity text,
    end_appointment jsonb,
    end_caller_id_name text,
    end_caller_id_num text,
    end_completed text,
    end_deficiency text,
    end_event_time text,
    end_event_type text,
    end_id text,
    end_lat text,
    end_lon text,
    end_other_trade_deficiency text,
    end_red_tag text,
    end_source text,
    end_started text,
    end_uri text,
    event_time text,
    event_type text,
    lat text,
    lon text,
    other_trade_deficiency text,
    red_tag text,
    "source" text,
    started text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (appointment_id) REFERENCES appointment(id),
    FOREIGN KEY (end_job_id) REFERENCES job(id),
    FOREIGN KEY (end_user_id) REFERENCES users(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE contract_tag (
    id text,
    contract_id text,
    "name" text,
    uri text,
    PRIMARY KEY (id, contract_id),
    FOREIGN KEY (contract_id) REFERENCES contract(id)
);

CREATE TABLE contract (
    id text,
    owner_id text,
    active text,
    actual_margin text,
    agreement_type text,
    all_items_have_costs text,
    complexity text,
    created text,
    customer text,
    customer_po text,
    description text,
    entity_filter text,
    expected_margin text,
    expected_revenue text,
    expires_on text,
    external_id jsonb,
    invoice_detail_level text,
    invoice_notes text,
    invoice_terms text,
    job_terms text,
    job_type text,
    location text,
    location_context text,
    "name" text,
    office text,
    owner text,
    parent text,
    payment_terms_id text,
    payment_terms_name text,
    payment_terms_order_index text,
    payment_terms_uri text,
    quote_detail_level text,
    quote_terms text,
    region text,
    revenue text,
    revenue_as_of text,
    review_on text,
    sales text,
    starts_on text,
    "type" text,
    updated text,
    uri text,
    vendor_id text,
    vendor_name text,
    vendor_status text,
    vendor_uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE job_item (
    id text,
    job_id text,
    lib_item_id text,
    quote_item_id text,
    service_line_id text,
    service_request_id text,
    cost text,
    created text,
    external_id jsonb,
    "name" text,
    quantity text,
    "source" text,
    time_used text,
    updated text,
    uri text,
    used_on text,
    visibility jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (lib_item_id) REFERENCES lib_item(id),
    FOREIGN KEY (quote_item_id) REFERENCES quote_item(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id),
    FOREIGN KEY (service_request_id) REFERENCES service_request(id)
);

CREATE TABLE service_request_item (
    id text,
    lib_item_id text,
    service_line_id text,
    service_recurrence_id text,
    service_request_id text,
    description text,
    price text,
    quantity text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (lib_item_id) REFERENCES lib_item(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id),
    FOREIGN KEY (service_recurrence_id) REFERENCES service_recurrence(id),
    FOREIGN KEY (service_request_id) REFERENCES service_request(id)
);

CREATE TABLE invoice_item (
    id text,
    invoice_id text,
    invoice_recurrence_id text,
    job_item_id text,
    lib_item_id text,
    service_line_id text,
    created text,
    description text,
    job_item text,
    order_index text,
    price text,
    quantity text,
    service_request text,
    sub_total text,
    tax_amount text,
    tax_group text,
    tax_rate text,
    tax_rate_detail jsonb,
    total_price text,
    updated text,
    uri text,
    window_end text,
    window_start text,
    PRIMARY KEY (id),
    FOREIGN KEY (invoice_id) REFERENCES invoice(id),
    FOREIGN KEY (invoice_recurrence_id) REFERENCES invoice_recurrence(id),
    FOREIGN KEY (job_item_id) REFERENCES job_item(id),
    FOREIGN KEY (lib_item_id) REFERENCES lib_item(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);

CREATE TABLE deficiency_report (
    id text,
    asset_id text,
    deficiency_id text,
    job_id text,
    service_line_id text,
    created text,
    description text,
    proposed_fix text,
    report_source text,
    reporter_avatar jsonb,
    reporter_email text,
    reporter_id text,
    reporter_is_helper text,
    reporter_is_tech text,
    reporter_name text,
    reporter_status text,
    reporter_uri text,
    severity text,
    "status" text,
    updated text,
    uri text,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (deficiency_id) REFERENCES deficiency(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (service_line_id) REFERENCES service_line(id)
);
