CREATE TABLE warehouse (
    id text,
    create_date text,
    ext_inventory_identity text,
    is_default text,
    origin_address_address_verified text,
    origin_address_city text,
    origin_address_company text,
    origin_address_country text,
    origin_address_name text,
    origin_address_phone text,
    origin_address_postal_code text,
    origin_address_residential text,
    origin_address_state text,
    origin_address_street_1 text,
    origin_address_street_2 text,
    origin_address_street_3 text,
    register_fedex_meter text,
    return_address_address_verified text,
    return_address_city text,
    return_address_company text,
    return_address_country text,
    return_address_name text,
    return_address_phone text,
    return_address_postal_code text,
    return_address_residential text,
    return_address_state text,
    return_address_street_1 text,
    return_address_street_2 text,
    return_address_street_3 text,
    seller_integration_id text,
    warehouse_name text,
    PRIMARY KEY (id)
);

CREATE TABLE shipment_item (
    order_item_id text,
    product_id text,
    shipment_id text,
    fulfillment_sku text,
    image_url text,
    line_item_key text,
    "name" text,
    options text,
    quantity text,
    sku text,
    unit_price text,
    warehouse_location text,
    weight text,
    PRIMARY KEY (order_item_id),
    FOREIGN KEY (order_item_id) REFERENCES order_item(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment (
    id text,
    order_id text,
    package_code text,
    service_code text,
    user_id text,
    warehouse_id text,
    advanced_options text,
    batch_number text,
    confirmation text,
    create_date text,
    dimensions text,
    form_data text,
    insurance_cost text,
    insurance_options_insure_shipment text,
    insurance_options_insured_value text,
    insurance_options_provider text,
    is_return_label text,
    label_data text,
    marketplace_notified text,
    notify_error_message text,
    order_key text,
    order_number text,
    ship_date text,
    ship_to_city text,
    ship_to_company text,
    ship_to_country text,
    ship_to_name text,
    ship_to_phone text,
    ship_to_postal_code text,
    ship_to_residential text,
    ship_to_state text,
    ship_to_street_1 text,
    ship_to_street_2 text,
    ship_to_street_3 text,
    shipment_cost text,
    shipping_provider_code text,
    tracking_number text,
    void_date text,
    voided text,
    weight_units text,
    weight_value text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (package_code) REFERENCES package(code),
    FOREIGN KEY (service_code) REFERENCES service(code),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse(id)
);

CREATE TABLE fulfillment (
    id text,
    order_id text,
    user_id text,
    create_date text,
    customer_email text,
    delivery_date text,
    fulfillment_fee text,
    fulfillment_provider_code text,
    fulfillment_service_code text,
    marketplace_notified text,
    notify_error_message text,
    order_number text,
    seller_fill_provider_id text,
    seller_fill_provider_name text,
    ship_date text,
    ship_to_address_verified text,
    ship_to_city text,
    ship_to_company text,
    ship_to_country text,
    ship_to_name text,
    ship_to_phone text,
    ship_to_postal_code text,
    ship_to_residential text,
    ship_to_state text,
    ship_to_street_1 text,
    ship_to_street_2 text,
    ship_to_street_3 text,
    shipping_provider_code text,
    tracking_number text,
    void_date text,
    void_requested text,
    voided text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE marketplace (
    id text,
    can_confirm_shipments text,
    can_refresh text,
    "name" text,
    supports_custom_mappings text,
    supports_custom_statuses text,
    PRIMARY KEY (id)
);

CREATE TABLE shipping_provider (
    id text,
    account_number text,
    balance text,
    code text,
    is_primary text,
    "name" text,
    nickname text,
    requires_funded_account text,
    PRIMARY KEY (id)
);

CREATE TABLE package (
    code text,
    shipping_provider_id text,
    carrier_code text,
    domestic text,
    international text,
    "name" text,
    PRIMARY KEY (code),
    FOREIGN KEY (shipping_provider_id) REFERENCES shipping_provider(id)
);

CREATE TABLE product (
    id text,
    default_intl_package_code text,
    default_intl_service_code text,
    default_package_code text,
    default_service_code text,
    active text,
    aliases text,
    create_date text,
    customs_country_code text,
    customs_description text,
    customs_tariff_number text,
    customs_value text,
    default_confirmation text,
    default_cost text,
    default_intl_confirmation text,
    fulfillment_sku text,
    height text,
    internal_note text,
    length text,
    modify_date text,
    "name" text,
    no_customs text,
    price text,
    product_category_category_id text,
    product_category_name text,
    product_type text,
    sku text,
    warehouse_location text,
    weight_oz text,
    width text,
    PRIMARY KEY (id),
    FOREIGN KEY (default_intl_package_code) REFERENCES package(code),
    FOREIGN KEY (default_intl_service_code) REFERENCES service(code),
    FOREIGN KEY (default_package_code) REFERENCES package(code),
    FOREIGN KEY (default_service_code) REFERENCES service(code)
);

CREATE TABLE order_item (
    id text,
    order_id text,
    product_id text,
    adjustment text,
    create_date text,
    fulfillment_sku text,
    image_url text,
    line_item_key text,
    modify_date text,
    "name" text,
    options jsonb,
    quantity text,
    shipping_amount text,
    sku text,
    tax_amount text,
    unit_price text,
    upc text,
    warehouse_location text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE order_tag (
    order_id text,
    tag_id text,
    PRIMARY KEY (order_id, tag_id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE order_merged (
    merged_order_id text,
    order_id text,
    PRIMARY KEY (merged_order_id, order_id),
    FOREIGN KEY (merged_order_id) REFERENCES orders(id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE orders (
    id text,
    advanced_options_store_id text,
    advanced_options_warehouse_id text,
    customer_id text,
    package_code text,
    service_code text,
    user_id text,
    advanced_options_bill_to_account text,
    advanced_options_bill_to_country_code text,
    advanced_options_bill_to_my_other_account text,
    advanced_options_bill_to_party text,
    advanced_options_bill_to_postal_code text,
    advanced_options_contains_alcohol text,
    advanced_options_custom_field_1 text,
    advanced_options_custom_field_2 text,
    advanced_options_custom_field_3 text,
    advanced_options_merged_or_split text,
    advanced_options_non_machinable text,
    advanced_options_parent_id text,
    advanced_options_saturday_delivery text,
    advanced_options_source text,
    amount_paid text,
    bill_to_address_verified text,
    bill_to_city text,
    bill_to_company text,
    bill_to_country text,
    bill_to_name text,
    bill_to_phone text,
    bill_to_postal_code text,
    bill_to_residential text,
    bill_to_state text,
    bill_to_street_1 text,
    bill_to_street_2 text,
    bill_to_street_3 text,
    confirmation text,
    create_date text,
    customer_email text,
    customer_notes text,
    customer_username text,
    dimensions_height text,
    dimensions_length text,
    dimensions_units text,
    dimensions_width text,
    externally_fulfilled text,
    externally_fulfilled_by text,
    externally_fulfilled_by_id text,
    externally_fulfilled_by_name text,
    gift text,
    gift_message text,
    hold_until_date text,
    insurance_options_insure_shipment text,
    insurance_options_insured_value text,
    insurance_options_provider text,
    internal_notes text,
    international_options_contents text,
    international_options_customs_items text,
    international_options_non_delivery text,
    label_messages text,
    modify_date text,
    order_date text,
    order_key text,
    order_number text,
    order_status text,
    order_total text,
    payment_date text,
    payment_method text,
    requested_shipping_service text,
    ship_by_date text,
    ship_date text,
    ship_to_address_verified text,
    ship_to_city text,
    ship_to_company text,
    ship_to_country text,
    ship_to_name text,
    ship_to_phone text,
    ship_to_postal_code text,
    ship_to_residential text,
    ship_to_state text,
    ship_to_street_1 text,
    ship_to_street_2 text,
    ship_to_street_3 text,
    shipping_amount text,
    shipping_provider_code text,
    tax_amount text,
    weight_units_of_measurement text,
    weight_value text,
    weight_weight_units text,
    PRIMARY KEY (id),
    FOREIGN KEY (advanced_options_store_id) REFERENCES store(id),
    FOREIGN KEY (advanced_options_warehouse_id) REFERENCES warehouse(id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (package_code) REFERENCES package(code),
    FOREIGN KEY (service_code) REFERENCES service(code),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE store (
    id text,
    marketplace_id text,
    account_name text,
    active text,
    auto_refresh text,
    company_name text,
    create_date text,
    email text,
    integration_url text,
    last_refresh_attempt text,
    marketplace_name text,
    modify_date text,
    phone text,
    public_email text,
    refresh_date text,
    store_name text,
    website text,
    PRIMARY KEY (id),
    FOREIGN KEY (marketplace_id) REFERENCES marketplace(id)
);

CREATE TABLE customer_tag (
    _fivetran_id text,
    customer_id text,
    tag_id text,
    "name" text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE marketplace_username (
    customer_user_id text,
    customer_id text,
    marketplace_id text,
    create_date text,
    marketplace text,
    modify_date text,
    username text,
    PRIMARY KEY (customer_user_id),
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (marketplace_id) REFERENCES marketplace(id)
);

CREATE TABLE customer (
    id text,
    address_verified text,
    city text,
    company text,
    country_code text,
    create_date text,
    email text,
    modify_date text,
    "name" text,
    phone text,
    postal_code text,
    "state" text,
    street_1 text,
    street_2 text,
    PRIMARY KEY (id)
);

CREATE TABLE service (
    code text,
    shipping_provider_id text,
    carrier_code text,
    domestic text,
    international text,
    "name" text,
    PRIMARY KEY (code),
    FOREIGN KEY (shipping_provider_id) REFERENCES shipping_provider(id)
);

CREATE TABLE users (
    id text,
    "name" text,
    user_name text,
    PRIMARY KEY (id)
);

CREATE TABLE tags (
    id text,
    color text,
    "name" text,
    PRIMARY KEY (id)
);
