CREATE TABLE warehouse_product_inventory_metric (
    id text,
    warehouse_id text,
    warehouse_product_product_id text,
    account_id text,
    active text,
    allocated text,
    available text,
    backorder text,
    created_at timestamp,
    custom text,
    customs_value text,
    in_tote text,
    inventory_bin text,
    inventory_overstock_bin text,
    legacy_id text,
    non_sellable_quantity text,
    on_hand text,
    price text,
    reorder_amount text,
    reorder_level text,
    replenishment_level text,
    reserve_inventory text,
    sell_ahead text,
    sku text,
    updated_at timestamp,
    "value" text,
    value_currency text,
    warehouse_identifier text,
    PRIMARY KEY (id, warehouse_id, warehouse_product_product_id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id),
    FOREIGN KEY (warehouse_product_product_id) REFERENCES warehouse_product(product_id)
);

CREATE TABLE vendor (
    id text,
    account_id text,
    account_number text,
    address_address_1 text,
    address_address_2 text,
    address_city text,
    address_country text,
    address_name text,
    address_phone text,
    address_state text,
    address_zip text,
    created_at text,
    currency text,
    default_po_note text,
    email text,
    internal_note text,
    legacy_id text,
    logo text,
    "name" text,
    partner_vendor_id text,
    PRIMARY KEY (id)
);

CREATE TABLE purchase_order_line_item (
    "index" text,
    purchase_order_line_item_id text,
    vendor_id text,
    warehouse_id text,
    account_id text,
    barcode text,
    created_at timestamp,
    expected_weight_in_lbs text,
    fulfillment_status text,
    legacy_id text,
    node_id text,
    note text,
    option_title text,
    partner_line_item_id text,
    po_id text,
    po_number text,
    price text,
    product_id text,
    product_name text,
    quantity text,
    quantity_received text,
    quantity_rejected text,
    sell_ahead text,
    sku text,
    updated_at timestamp,
    variant_id text,
    vendor_sku text,
    PRIMARY KEY ("index", purchase_order_line_item_id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE browse_order_history (
    id text,
    order_id text,
    account_id text,
    information text,
    order_email text,
    order_fulfillment_status text,
    order_number text,
    order_order_date text,
    order_packing_note text,
    order_profile text,
    order_required_ship_date text,
    order_shipping_address_address_1 text,
    order_shipping_address_address_2 text,
    order_shipping_address_city text,
    order_shipping_address_company text,
    order_shipping_address_country text,
    order_shipping_address_country_code text,
    order_shipping_address_email text,
    order_shipping_address_first_name text,
    order_shipping_address_last_name text,
    order_shipping_address_phone text,
    order_shipping_address_state text,
    order_shipping_address_state_code text,
    order_shipping_address_zip text,
    order_shop_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE warehouse_product (
    warehouse_id text,
    product_id text,
    on_hand text,
    PRIMARY KEY (warehouse_id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_image (
    src text,
    product_id text,
    PRIMARY KEY (src, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_kit_component (
    sku text,
    product_id text,
    quantity text,
    PRIMARY KEY (sku, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_tag (
    "index" text,
    product_id text,
    tags text,
    PRIMARY KEY ("index", product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    account_id text,
    active text,
    barcode text,
    country_of_manufacture text,
    created_at text,
    customs_description text,
    customs_value text,
    dimensions_height text,
    dimensions_length text,
    dimensions_weight text,
    dimensions_width text,
    dropship text,
    final_sale text,
    ignore_on_customs text,
    ignore_on_invoice text,
    kit text,
    kit_build text,
    large_thumbnail text,
    legacy_id text,
    "name" text,
    needs_serial_number text,
    no_air text,
    not_owned text,
    product_note text,
    sku text,
    tariff_code text,
    thumbnail text,
    updated_at text,
    virtual text,
    PRIMARY KEY (id)
);

CREATE TABLE warehouse_product_detail (
    id text,
    product_id text,
    warehouse_id text,
    account_id text,
    custom text,
    inventory_bin text,
    on_hand text,
    product_name text,
    product_sku text,
    reorder_amount text,
    reorder_level text,
    reserve_inventory text,
    warehouse_dynamic_slotting text,
    warehouse_profile text,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE shipment_line_item (
    id text,
    shipment_id text,
    quantity text,
    PRIMARY KEY (id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment_shipping_label (
    id text,
    shipment_id text,
    account_id text,
    carrier text,
    carrier_account_id text,
    cost text,
    created_date text,
    insurance_amount text,
    legacy_id text,
    packing_slip text,
    profile text,
    shipping_method text,
    shipping_name text,
    "source" text,
    "status" text,
    tracking_number text,
    warehouse text,
    PRIMARY KEY (id, shipment_id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id)
);

CREATE TABLE shipment (
    id text,
    order_id text,
    warehouse_id text,
    address_address_1 text,
    address_address_2 text,
    address_city text,
    address_country text,
    address_name text,
    address_phone text,
    address_state text,
    address_zip text,
    created_date text,
    dropshipment text,
    legacy_id text,
    pending_shipment_id text,
    shipped_off_shiphero text,
    user_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE order_history (
    _fivetran_id text,
    order_id text,
    created_at text,
    information text,
    user_id text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE order_line_item (
    sku text,
    order_id text,
    backorder_quantity text,
    price text,
    promotion_discount text,
    quantity text,
    quantity_allocated text,
    quantity_pending_fulfillment text,
    PRIMARY KEY (sku, order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE orders (
    id text,
    account_id text,
    adult_signature_required text,
    alcohol text,
    allocation_priority text,
    allow_partial text,
    allow_split text,
    auto_print_return_label text,
    currency text,
    custom_invoice_url text,
    email text,
    expected_weight_in_oz text,
    flagged text,
    fulfillment_status text,
    gift_invoice text,
    has_dry_ice text,
    ignore_address_validation_errors text,
    insurance text,
    insurance_amount text,
    legacy_id text,
    order_date text,
    order_number text,
    packing_note text,
    partner_order_id text,
    priority_flag text,
    profile text,
    require_signature text,
    required_ship_date text,
    saturday_delivery text,
    shop_name text,
    "source" text,
    subtotal text,
    third_party_shipper_account_number text,
    third_party_shipper_country text,
    third_party_shipper_zip text,
    total_discounts text,
    total_price text,
    total_tax text,
    PRIMARY KEY (id)
);

CREATE TABLE pack_per_day (
    id text,
    order_id text,
    shipment_id text,
    warehouse_id text,
    barcodes_scanned text,
    created_at timestamp,
    order_number text,
    total_items text,
    unique_items text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (shipment_id) REFERENCES shipment(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE shipping_plan (
    id text,
    purchase_order_id text,
    warehouse_id text,
    origin_of_shipment text,
    pdf_location text,
    vendor_po_number text,
    warehouse_note text,
    PRIMARY KEY (id, purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE purchase_order (
    id text,
    vendor_id text,
    warehouse_id text,
    account_id text,
    created_at text,
    date_closed text,
    description text,
    discount text,
    fulfillment_status text,
    images text,
    legacy_id text,
    locked_by_user_id text,
    locking text,
    packing_note text,
    payment_due_by text,
    payment_method text,
    payment_note text,
    pdf text,
    po_date timestamp,
    po_note text,
    po_number text,
    shipping_carrier text,
    shipping_method text,
    shipping_name text,
    shipping_price text,
    subtotal text,
    tax text,
    total_price text,
    tracking_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES orders(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE shipping_plan_line_item (
    id text,
    purchase_order_id text,
    warehouse_id text,
    account_id text,
    barcode text,
    created_at timestamp,
    expected_weight_in_lbs text,
    fulfillment_status text,
    legacy_id text,
    note text,
    option_title text,
    partner_line_item_id text,
    price text,
    product_id text,
    product_name text,
    quantity text,
    quantity_received text,
    quantity_rejected text,
    sell_ahead text,
    sku text,
    updated_at timestamp,
    variant_id text,
    vendor_sku text,
    PRIMARY KEY (id, purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE inventory_change (
    _fivetran_id text,
    warehouse_id text,
    account_id text,
    change_in_on_hand text,
    created_at timestamp,
    cycle_counted text,
    location_account_id text,
    location_created_at text,
    location_id text,
    location_is_cart text,
    location_last_counted text,
    location_legacy_id text,
    location_name text,
    location_pickable text,
    location_sellable text,
    location_temperature text,
    location_warehouse_id text,
    location_zone text,
    previous_on_hand text,
    reason text,
    sku text,
    user_id text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE return_line_item_detail (
    id text,
    return_id text,
    return_line_item_id text,
    warehouse_id text,
    backorder_quantity text,
    barcode text,
    created_at text,
    custom_barcode text,
    custom_options text,
    customs_value text,
    eligible_for_return text,
    fulfillment_status text,
    legacy_id text,
    locked_to_warehouse_id text,
    option_title text,
    partner_line_item_id text,
    price text,
    product_name text,
    quantity text,
    quantity_allocated text,
    quantity_pending_fulfillment text,
    quantity_shipped text,
    sku text,
    subtotal text,
    updated_at text,
    warehouse text,
    PRIMARY KEY (id, return_id, return_line_item_id),
    FOREIGN KEY (return_id) REFERENCES return_line_item(return_id),
    FOREIGN KEY (return_line_item_id) REFERENCES return_line_item(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE return_line_item (
    id text,
    return_id text,
    warehouse_id text,
    account_id text,
    "condition" text,
    created_at text,
    is_component text,
    legacy_id text,
    line_item_id text,
    product_id text,
    quantity text,
    reason text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id, return_id),
    FOREIGN KEY (return_id) REFERENCES "return"(id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouse_product(warehouse_id)
);

CREATE TABLE "return" (
    id text,
    order_id text,
    account_id text,
    cost_to_customer text,
    created_at timestamp,
    display_issue_refund text,
    label_cost text,
    label_type text,
    legacy_id text,
    partner_id text,
    reason text,
    shipping_carrier text,
    shipping_method text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE line_item_pick (
    id text,
    order_id text,
    barcode_scanned text,
    created_at timestamp,
    inventory_bin text,
    line_item_id text,
    location_id text,
    order_number text,
    pick_type text,
    picked_quantity text,
    quantity text,
    sku text,
    tote_id text,
    user_first_name text,
    user_id text,
    user_last_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (order_id) REFERENCES orders(id)
);
