CREATE TABLE bad_event (
    id text,
    event text,
    reason text,
    PRIMARY KEY (id)
);

-- Note
-- This is a dynamic table and will be based on your custom objects. Please review more details here.
CREATE TABLE custom_context (
    collector_tstamp timestamp,
    event_id text,
    PRIMARY KEY (collector_tstamp, event_id),
    FOREIGN KEY (collector_tstamp) REFERENCES event(collector_tstamp),
    FOREIGN KEY (event_id) REFERENCES event(collector_tstamp)
);

CREATE TABLE event (
    collector_tstamp timestamp,
    event_id text,
    app_id text,
    br_colordepth integer,
    br_cookies boolean,
    br_family text,
    br_features_director boolean,
    br_features_flash boolean,
    br_features_gears boolean,
    br_features_java boolean,
    br_features_pdf boolean,
    br_features_quicktime boolean,
    br_features_realplayer boolean,
    br_features_silverlight boolean,
    br_features_windowsmedia boolean,
    br_lang text,
    br_name text,
    br_renderengine text,
    br_type text,
    br_version text,
    br_viewheight text,
    data text,
    derived_tstamp timestamp,
    doc_charset text,
    doc_height integer,
    doc_width integer,
    domain_sessionid text,
    domain_sessionidx text,
    domain_userid text,
    dvce_created_tstamp timestamp,
    dvce_ismobile boolean,
    dvce_screenheight text,
    dvce_sent_tstamp timestamp,
    dvce_type text,
    event text,
    event_format text,
    event_name text,
    event_vendor text,
    event_version text,
    geo_city text,
    geo_country text,
    geo_latitude double precision,
    geo_longitude double precision,
    geo_region text,
    geo_region_name text,
    geo_timezone text,
    geo_zipcode text,
    mac_address text,
    mkt_campaign text,
    mkt_clickid text,
    mkt_content text,
    mkt_medium text,
    mkt_network text,
    mkt_source text,
    mkt_term text,
    name_tracker text,
    network_userid text,
    os_family text,
    os_manufacturer text,
    os_name text,
    os_timezone text,
    page_referrer text,
    page_title text,
    page_url text,
    page_urlfragment text,
    page_urlhost text,
    page_urlpath text,
    page_urlport integer,
    page_urlquery text,
    page_urlscheme text,
    platform text,
    pp_xoffset_max integer,
    pp_xoffset_min integer,
    pp_yoffset_max integer,
    pp_yoffset_min integer,
    refr_domain_user_id text,
    refr_dvce_tstamp timestamp,
    refr_medium text,
    refr_source text,
    refr_term text,
    refr_urlfragment text,
    refr_urlhost text,
    refr_urlpath text,
    refr_urlport integer,
    refr_urlquery text,
    refr_urlscheme text,
    se_action text,
    se_category text,
    se_label text,
    se_property text,
    se_value text,
    sequence_number text,
    ti_category text,
    ti_currency text,
    ti_name text,
    ti_orderid text,
    ti_price text,
    ti_quantity double precision,
    ti_sku text,
    tr_affiliation text,
    tr_city text,
    tr_country text,
    tr_currency text,
    tr_orderid text,
    tr_shipping text,
    tr_state text,
    tr_tax text,
    tr_total text,
    true_tstamp timestamp,
    txn_id text,
    user_fingerprint text,
    user_id text,
    user_ipaddress text,
    useragent text,
    v_collector text,
    v_tracker text,
    PRIMARY KEY (collector_tstamp, event_id)
);

CREATE TABLE ua_parser_context (
    collector_tstamp timestamp,
    event_id text,
    device_family text,
    os_family text,
    os_major text,
    os_minor text,
    os_patch text,
    os_patch_minor text,
    os_version text,
    useragent_family text,
    useragent_major text,
    useragent_minor text,
    useragent_patch text,
    useragent_version text,
    PRIMARY KEY (collector_tstamp, event_id),
    FOREIGN KEY (collector_tstamp) REFERENCES event(collector_tstamp),
    FOREIGN KEY (event_id) REFERENCES event(collector_tstamp)
);
