CREATE TABLE contact (
    id text,
    avatar_url text,
    birthday text,
    bounced text,
    city text,
    create_date text,
    deleted text,
    facebook_display_name text,
    facebook_url text,
    first_name text,
    gender text,
    instagram_display_name text,
    instagram_url text,
    invalid_email text,
    last_name text,
    linkedin_display_name text,
    linkedin_url text,
    middle_name text,
    modify_date text,
    notes text,
    organization_name text,
    phone text,
    pinterest_display_name text,
    pinterest_url text,
    primary_email text,
    profile_image text,
    salesforce_id text,
    "state" text,
    street text,
    title text,
    twitter_display_name text,
    twitter_url text,
    unsubscribed text,
    vip text,
    website text,
    zip text,
    PRIMARY KEY (id)
);

CREATE TABLE event_stats (
    "index" text,
    event_id text,
    count text,
    "name" text,
    PRIMARY KEY ("index", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_group (
    "index" text,
    event_id text,
    group_id text,
    PRIMARY KEY ("index", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_attendance_type (
    "index" text,
    event_id text,
    event_attendance_type text,
    PRIMARY KEY ("index", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_custom_question (
    "index" text,
    event_id text,
    column_name text,
    custom_question_id text,
    deleted text,
    external_link text,
    "name" text,
    protected text,
    required text,
    selected_value jsonb,
    "type" text,
    values jsonb,
    PRIMARY KEY ("index", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_triggered_email (
    "index" text,
    event_id text,
    active text,
    content text,
    event_message_id text,
    event_message_linked_to_theme text,
    event_ticket_type_id text,
    include_calendar_attachment text,
    include_pdf_attachment text,
    pdf_content text,
    subject text,
    "trigger" text,
    use_default_confirmation text,
    PRIMARY KEY ("index", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE group_contact_answer (
    question_id text,
    group_contact_id text,
    answer text,
    PRIMARY KEY (question_id, group_contact_id),
    FOREIGN KEY (group_contact_id) REFERENCES group_contact(id)
);

CREATE TABLE group_contact (
    id text,
    contact_id text,
    event_id text,
    event_rsvp_contact_id text,
    created text,
    deleted text,
    event_list text,
    event_rsvp_id text,
    modified text,
    salesforce_campaign_member_id text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (event_id) REFERENCES event(id),
    FOREIGN KEY (event_rsvp_contact_id) REFERENCES contact(id)
);

CREATE TABLE organization_group (
    id text,
    child_group_id text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE event_multi_currency_option (
    id text,
    event_id text,
    code text,
    "name" text,
    PRIMARY KEY (id, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_locale (
    code text,
    event_id text,
    "name" text,
    PRIMARY KEY (code, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    type_id text,
    allow_vep_url_sharing text,
    autosave text,
    button_closed_message text,
    cached_maps_square text,
    cached_maps_wide text,
    card text,
    created_at text,
    currency text,
    custom_domain text,
    deleted text,
    description text,
    description_text text,
    domain text,
    email_settings_google_map_url text,
    email_white_label_key text,
    "end" text,
    end_time text,
    facebook_description text,
    facebook_title text,
    favicon_url text,
    form_email_domain_restriction text,
    form_is_in_library text,
    fq_url text,
    has_event_sold_or_pending_tickets text,
    has_event_sold_tickets text,
    has_virtual text,
    hashtag text,
    header_image text,
    hide_event_time text,
    hide_footer text,
    host text,
    hub text,
    invite_link_privacy_bypass text,
    is_invite_only text,
    is_rsvp_open text,
    lat text,
    limit_one_order_per_email text,
    limit_one_per_email text,
    limit_one_ticket_type_per_email text,
    linkedin_description text,
    linkedin_title text,
    lng text,
    locale text,
    meta_calendar_description text,
    meta_description text,
    meta_robots_txt text,
    meta_sitemap_xml text,
    meta_title text,
    mobile_check_in_url text,
    mobility_account_id text,
    mobility_wholesaler_id text,
    modified_at text,
    multisession text,
    no_index text,
    organization text,
    owner_email text,
    owner_first_name text,
    owner_last_name text,
    page_action text,
    page_password text,
    page_privacy_type text,
    paid_for_domain text,
    published text,
    redirect_to text,
    registration_updating_deadline text,
    registration_updating_enabled text,
    require_captcha text,
    rsvp_closed_at text,
    rsvp_closed_state text,
    rsvp_closed_team_notified text,
    rsvp_guest_display text,
    rsvp_max text,
    rsvp_method text,
    rsvp_open text,
    salesforce_campaign_id text,
    send_guest_confirmation text,
    sessions_overlap text,
    setting_id text,
    share_image_url text,
    splash_hub_auto_subscribe text,
    splash_theme_abbr text,
    splash_theme_active text,
    splash_theme_created text,
    splash_theme_id text,
    splash_theme_image_url text,
    splash_theme_name text,
    splash_theme_sort text,
    splash_theme_thumbnail_url text,
    stages text,
    "start" text,
    start_time text,
    "state" text,
    statistics text,
    "status" text,
    tags text,
    ticket_types text,
    time_zone text,
    time_zone_id text,
    title text,
    twitter_default text,
    "type" text,
    users text,
    vat_setting text,
    venue_address text,
    venue_city text,
    venue_country text,
    venue_lat text,
    venue_lon text,
    venue_name text,
    venue_postal_code text,
    venue_region text,
    venue_tbd text,
    wait_list text,
    waitlist_settings text,
    white_label text,
    workflow text,
    zip_code text,
    PRIMARY KEY (id, type_id)
);
