CREATE TABLE input (
    "name" text,
    "index" text,
    disabled boolean,
    host text,
    "source" text,
    source_type text,
    updated timestamp,
    PRIMARY KEY ("name"),
    FOREIGN KEY ("index") REFERENCES "index"("name")
);

CREATE TABLE event (
    _fivetran_id text,
    "index" text,
    host text,
    line_count bigint,
    "source" text,
    source_type text,
    "time" timestamp,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY ("index") REFERENCES "index"("name")
);

CREATE TABLE "index" (
    "name" text,
    block_sign_size bigint,
    cold_path text,
    cold_path_expanded text,
    cold_to_frozen_dir text,
    cold_to_frozen_script text,
    current_dbsize_mb bigint,
    datatype text,
    default_database text,
    disabled boolean,
    enable_realtime_search boolean,
    frozen_time_period_in_secs bigint,
    home_path text,
    home_path_expanded text,
    is_internal boolean,
    is_ready boolean,
    max_concurrent_optimizes bigint,
    max_data_size text,
    max_hot_buckets text,
    max_hot_idle_secs bigint,
    max_hot_span_secs bigint,
    max_meta_entries bigint,
    max_time timestamp,
    max_total_data_size_mb bigint,
    max_warm_db_count bigint,
    mim_raw_file_sync_secs text,
    min_time timestamp,
    partial_service_meta_period bigint,
    quarantine_future_secs bigint,
    quarantine_past_secs bigint,
    raw_chunk_size_bytes bigint,
    rotate_period_in_secs bigint,
    service_meta_period bigint,
    summarize boolean,
    sync_meta boolean,
    thawed_path text,
    thawed_path_expanded text,
    throttle_check_period bigint,
    total_event_count bigint,
    updated timestamp,
    PRIMARY KEY ("name")
);
