CREATE TABLE case_message (
    cases_id text,
    message_guid text,
    anchor text,
    case_message_direction text,
    PRIMARY KEY (cases_id, message_guid),
    FOREIGN KEY (cases_id) REFERENCES cases(id),
    FOREIGN KEY (message_guid) REFERENCES message(guid)
);

CREATE TABLE case_tag (
    cases_id text,
    tag_id text,
    updated_by text,
    updated_on text,
    PRIMARY KEY (cases_id, tag_id),
    FOREIGN KEY (cases_id) REFERENCES cases(id),
    FOREIGN KEY (tag_id) REFERENCES tag(id)
);

CREATE TABLE cases (
    id text,
    assigned_by text,
    assignees text,
    closed_time text,
    created_by text,
    created_time text,
    group_id text,
    priority text,
    queue_id text,
    "status" text,
    "type" text,
    updated_time text,
    PRIMARY KEY (id)
);

CREATE TABLE instagram_profile_analytic (
    _fivetran_id text,
    comments_count integer,
    customer_id text,
    customer_profile_id bigint,
    "date" text,
    email_contacts integer,
    followers_count integer,
    followers_gained integer,
    followers_lost integer,
    get_directions_clicks integer,
    impressions integer,
    impressions_unique integer,
    likes integer,
    net_follower_growth integer,
    phone_call_clicks integer,
    posts_sent_by_content_type jsonb,
    posts_sent_by_post_type jsonb,
    posts_sent_count integer,
    profile_views_unique integer,
    reactions bigint,
    saves integer,
    shares_count integer,
    story_replies integer,
    text_message_clicks integer,
    video_views bigint,
    website_clicks integer,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE facebook_profile_analytic (
    _fivetran_id text,
    comments_count integer,
    cta_clicks_login integer,
    customer_id text,
    customer_profile_id bigint,
    "date" text,
    event_rsvps integer,
    followers_count integer,
    followers_gained integer,
    followers_gained_organic integer,
    followers_gained_paid integer,
    followers_lost integer,
    impressions integer,
    impressions_nonviral integer,
    impressions_nonviral_unique integer,
    impressions_organic integer,
    impressions_organic_unique integer,
    impressions_paid integer,
    impressions_paid_unique integer,
    impressions_unique integer,
    impressions_viral integer,
    impressions_viral_unique integer,
    likes integer,
    negative_feedback integer,
    net_follower_growth integer,
    offer_claims integer,
    place_checkins integer,
    positive_feedback_other integer,
    post_content_clicks_other integer,
    post_engagements integer,
    post_impressions integer,
    post_impressions_nonviral integer,
    post_impressions_organic integer,
    post_impressions_paid integer,
    post_impressions_viral integer,
    post_link_clicks integer,
    post_photo_view_clicks integer,
    post_video_play_clicks integer,
    posts_sent_by_content_type jsonb,
    posts_sent_by_post_type jsonb,
    posts_sent_count integer,
    profile_actions integer,
    profile_views integer,
    question_answers jsonb,
    reactions integer,
    reactions_angry integer,
    reactions_haha integer,
    reactions_love integer,
    reactions_sad integer,
    reactions_wow integer,
    shares_count integer,
    tab_views integer,
    tab_views_login integer,
    tab_views_logout integer,
    video_view_time double precision,
    video_views bigint,
    video_views_10_s bigint,
    video_views_10_s_autoplay bigint,
    video_views_10_s_click_to_play bigint,
    video_views_10_s_organic bigint,
    video_views_10_s_paid bigint,
    video_views_10_s_repeat bigint,
    video_views_10_s_unique bigint,
    video_views_30_s_complete bigint,
    video_views_30_s_complete_autoplay bigint,
    video_views_30_s_complete_click_to_play bigint,
    video_views_30_s_complete_organic bigint,
    video_views_30_s_complete_paid bigint,
    video_views_30_s_complete_repeat bigint,
    video_views_30_s_complete_unique bigint,
    video_views_autoplay bigint,
    video_views_click_to_play bigint,
    video_views_organic bigint,
    video_views_paid bigint,
    video_views_partial bigint,
    video_views_partial_autoplay bigint,
    video_views_partial_click_to_play bigint,
    video_views_partial_organic bigint,
    video_views_partial_paid bigint,
    video_views_partial_repeat bigint,
    video_views_repeat bigint,
    video_views_unique bigint,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE tiktok_profile_analytic (
    _fivetran_id text,
    comments_count_total integer,
    customer_id text,
    customer_profile_id bigint,
    "date" text,
    followers_by_gender jsonb,
    followers_count integer,
    followers_online integer,
    likes_total integer,
    net_follower_growth integer,
    posts_sent_by_post_type jsonb,
    posts_sent_count integer,
    profile_views_total integer,
    shares_count_total integer,
    video_views_total bigint,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE tiktok_profile_post (
    _fivetran_id text,
    clickthrough_link jsonb,
    comments_count integer,
    content_category text,
    created_time timestamp,
    customer_id text,
    customer_profile_id bigint,
    "from" jsonb,
    guid text,
    impression_source_follow integer,
    impression_source_for_you integer,
    impression_source_hashtag integer,
    impression_source_personal_profile integer,
    impression_source_sound integer,
    impression_source_unspecified integer,
    impressions_unique integer,
    internal jsonb,
    likes integer,
    perma_link text,
    post_category text,
    post_type text,
    reactions integer,
    sent boolean,
    shares_count integer,
    text text,
    video_length bigint,
    video_view_time double precision,
    video_view_time_per_view double precision,
    video_views bigint,
    video_views_p_100_per_view text,
    visual_media jsonb,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE instagram_profile_post (
    _fivetran_id text,
    clickthrough_link jsonb,
    comments_count integer,
    content_category text,
    created_time timestamp,
    customer_id text,
    customer_profile_id bigint,
    "from" jsonb,
    guid text,
    hashtags jsonb,
    impressions integer,
    impressions_unique integer,
    internal jsonb,
    likes integer,
    perma_link text,
    post_category text,
    post_type text,
    profile_guid text,
    reactions integer,
    saves integer,
    sent boolean,
    shares_count integer,
    story_exits integer,
    story_taps_back integer,
    story_taps_forward integer,
    text text,
    video_views bigint,
    visual_media jsonb,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE pinterest_profile_analytic (
    _fivetran_id text,
    customer_id text,
    customer_profile_id bigint,
    "date" text,
    followers_count integer,
    followers_gained integer,
    followers_lost integer,
    inbox_counts_sent jsonb,
    inbox_received_sent jsonb,
    net_follower_growth integer,
    net_following_growth integer,
    pin_count integer,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE twitter_profile_post (
    _fivetran_id text,
    clickthrough_link jsonb,
    comments_count integer,
    content_category text,
    created_time timestamp,
    customer_id text,
    customer_profile_id bigint,
    engagements_other integer,
    "from" jsonb,
    guid text,
    hashtags jsonb,
    impressions integer,
    internal jsonb,
    likes integer,
    perma_link text,
    post_app_engagements integer,
    post_app_installs integer,
    post_app_opens integer,
    post_category text,
    post_content_clicks integer,
    post_content_clicks_other integer,
    post_detail_expand_clicks integer,
    post_followers_gained integer,
    post_followers_lost integer,
    post_hashtag_clicks integer,
    post_link_clicks integer,
    post_media_clicks integer,
    post_media_views integer,
    post_profile_clicks integer,
    post_type text,
    profile_guid text,
    reactions integer,
    sent boolean,
    shares_count integer,
    text text,
    title text,
    video_views bigint,
    visual_media jsonb,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE tag_group (
    id integer,
    tag_id integer,
    PRIMARY KEY (id, tag_id),
    FOREIGN KEY (tag_id) REFERENCES tag(id)
);

CREATE TABLE tag (
    customer_id integer,
    id integer,
    active boolean,
    any_group boolean,
    text text,
    PRIMARY KEY (customer_id, id)
);

CREATE TABLE "group" (
    customer_id integer,
    id integer,
    "name" text,
    PRIMARY KEY (customer_id, id)
);

CREATE TABLE linkedin_profile_post (
    _fivetran_id text,
    clickthrough_link jsonb,
    comments_count integer,
    content_category text,
    created_time timestamp,
    customer_id text,
    customer_profile_id bigint,
    "from" jsonb,
    guid text,
    impressions integer,
    internal jsonb,
    perma_link text,
    post_category text,
    post_content_clicks integer,
    post_type text,
    profile_guid text,
    reactions integer,
    sent boolean,
    shares_count integer,
    text text,
    title text,
    video_views bigint,
    visual_media jsonb,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE pinterest_profile_post (
    _fivetran_id text,
    board_name text,
    clickthrough_link jsonb,
    comments_count integer,
    content_category text,
    created_time timestamp,
    customer_id text,
    customer_profile_id bigint,
    "from" jsonb,
    guid text,
    internal jsonb,
    perma_link text,
    post_category text,
    post_type text,
    saves integer,
    visual_media jsonb,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE profile_group (
    id integer,
    customer_id integer,
    profile_id integer,
    PRIMARY KEY (id, customer_id, profile_id),
    FOREIGN KEY (customer_id) REFERENCES profile(customer_id),
    FOREIGN KEY (profile_id) REFERENCES profile(id)
);

CREATE TABLE profile (
    customer_id integer,
    id integer,
    "name" text,
    native_id text,
    native_name text,
    network_type text,
    PRIMARY KEY (customer_id, id)
);

CREATE TABLE twitter_profile_analytic (
    _fivetran_id text,
    comments_count integer,
    customer_id text,
    customer_profile_id bigint,
    "date" text,
    engagements_other integer,
    followers_count integer,
    impressions integer,
    likes integer,
    net_follower_growth integer,
    post_app_engagements integer,
    post_app_installs integer,
    post_app_opens integer,
    post_content_clicks integer,
    post_content_clicks_other integer,
    post_detail_expand_clicks integer,
    post_hashtag_clicks integer,
    post_link_clicks integer,
    post_media_clicks integer,
    post_media_views integer,
    post_profile_clicks integer,
    posts_sent_by_content_type jsonb,
    posts_sent_by_post_type jsonb,
    posts_sent_count integer,
    reactions integer,
    shares_count integer,
    video_views bigint,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE message (
    guid text,
    case_id text,
    clickthrough_link_long text,
    clickthrough_link_name text,
    clickthrough_link_short text,
    content_category text,
    created_time text,
    customer_profile_id text,
    from_guid text,
    from_name text,
    from_profile_picture text,
    from_screen_name text,
    hashtags text,
    inbox_permalink text,
    internal_tags text,
    network text,
    perma_link text,
    post_category text,
    post_type text,
    profile_guid text,
    sent text,
    sent_by_email text,
    sent_by_first_name text,
    sent_by_id text,
    sent_by_image text,
    sent_by_last_name text,
    text text,
    title text,
    visual_media text,
    -- custom_* (dynamic column),
    PRIMARY KEY (guid)
);

CREATE TABLE youtube_profile_post (
    _fivetran_id text,
    annotation_click_through_rate integer,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate integer,
    annotation_closes integer,
    annotation_impressions integer,
    card_click_rate integer,
    card_clicks integer,
    card_impressions integer,
    card_teaser_click_rate integer,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    clickthrough_link jsonb,
    comments_count integer,
    content_category text,
    created_time timestamp,
    customer_id text,
    customer_profile_id bigint,
    dislikes integer,
    estimated_minutes_watched integer,
    estimated_red_minutes_watched integer,
    "from" jsonb,
    guid text,
    internal jsonb,
    likes integer,
    perma_link text,
    post_category text,
    post_content_clicks_other integer,
    post_type text,
    profile_guid text,
    reactions integer,
    red_video_views bigint,
    sent boolean,
    shares_count integer,
    subscribers_gained integer,
    subscribers_lost integer,
    text text,
    title text,
    video_view_percentage integer,
    video_view_time_per_view double precision,
    video_views bigint,
    videos_added_to_playlist integer,
    videos_removed_from_playlist integer,
    visual_media jsonb,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE facebook_profile_post (
    _fivetran_id text,
    clickthrough_link jsonb,
    comments_count integer,
    content_category text,
    created_time timestamp,
    customer_id text,
    customer_profile_id bigint,
    engagements_follower_unique integer,
    engagements_unique integer,
    "from" jsonb,
    guid text,
    hashtags jsonb,
    impressions integer,
    impressions_follower integer,
    impressions_follower_unique integer,
    impressions_nonfollower integer,
    impressions_nonviral integer,
    impressions_nonviral_unique integer,
    impressions_organic_unique integer,
    impressions_paid integer,
    impressions_paid_unique integer,
    impressions_unique integer,
    impressions_viral integer,
    impressions_viral_unique integer,
    internal jsonb,
    likes integer,
    negative_feedback integer,
    negative_feedback_unique integer,
    perma_link text,
    post_category text,
    post_content_clicks integer,
    post_content_clicks_other integer,
    post_content_clicks_unique integer,
    post_link_clicks integer,
    post_link_clicks_unique integer,
    post_other_clicks_unique integer,
    post_photo_view_clicks integer,
    post_photo_view_clicks_unique integer,
    post_type text,
    post_video_play_clicks bigint,
    post_video_play_clicks_unique bigint,
    profile_guid text,
    question_answers jsonb,
    reactions integer,
    reactions_angry integer,
    reactions_haha integer,
    reactions_love integer,
    reactions_sad integer,
    reactions_wow integer,
    sent boolean,
    shares_count integer,
    text text,
    title text,
    video_ad_break_cost_per_impression integer,
    video_ad_break_earnings integer,
    video_ad_break_impressions integer,
    video_length bigint,
    video_view_time double precision,
    video_view_time_organic bigint,
    video_view_time_paid bigint,
    video_view_time_per_view double precision,
    video_views bigint,
    video_views_10_s bigint,
    video_views_10_s_autoplay bigint,
    video_views_10_s_click_to_play bigint,
    video_views_10_s_organic bigint,
    video_views_10_s_paid bigint,
    video_views_10_s_sound_off bigint,
    video_views_10_s_sound_on bigint,
    video_views_10_s_unique bigint,
    video_views_30_s_complete bigint,
    video_views_30_s_complete_autoplay bigint,
    video_views_30_s_complete_click_to_play bigint,
    video_views_30_s_complete_organic bigint,
    video_views_30_s_complete_paid bigint,
    video_views_30_s_complete_unique bigint,
    video_views_autoplay bigint,
    video_views_click_to_play bigint,
    video_views_organic bigint,
    video_views_organic_unique bigint,
    video_views_p_95 bigint,
    video_views_p_95_organic bigint,
    video_views_p_95_organic_unique bigint,
    video_views_p_95_paid bigint,
    video_views_p_95_paid_unique bigint,
    video_views_paid bigint,
    video_views_paid_unique bigint,
    video_views_partial bigint,
    video_views_partial_autoplay bigint,
    video_views_partial_click_to_play bigint,
    video_views_partial_organic bigint,
    video_views_partial_paid bigint,
    video_views_sound_off bigint,
    video_views_sound_on bigint,
    video_views_unique bigint,
    visual_media jsonb,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE linkedin_profile_analytic (
    _fivetran_id text,
    comments_count integer,
    customer_id text,
    customer_profile_id bigint,
    "date" text,
    followers_count integer,
    followers_gained integer,
    followers_gained_organic integer,
    followers_gained_paid integer,
    followers_lost integer,
    impressions integer,
    impressions_unique integer,
    net_follower_growth integer,
    post_content_clicks integer,
    posts_sent_by_content_type jsonb,
    posts_sent_by_post_type jsonb,
    posts_sent_count integer,
    reactions integer,
    shares_count integer,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE "user" (
    customer_id integer,
    id integer,
    "name" text,
    PRIMARY KEY (customer_id, id)
);

CREATE TABLE youtube_profile_analytic (
    _fivetran_id text,
    customer_id text,
    customer_profile_id bigint,
    "date" text,
    followers_count integer,
    followers_gained integer,
    followers_lost integer,
    net_follower_growth integer,
    PRIMARY KEY (_fivetran_id)
);
