CREATE TABLE stats_delivery_native_ad (
    _fivetran_id text,
    advertiser_id text,
    campaign_id text,
    conversion_tracker_id text,
    line_item_id text,
    native_ad_id text,
    advertiser text,
    app_name text,
    atos text,
    atos_units text,
    banned text,
    campaign_custom_fields jsonb,
    channel text,
    click text,
    click_url text,
    conv text,
    conv_click text,
    conv_click_time_avg text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    conversion_tracker text,
    cost text,
    creatives_img_url text,
    creatives_size text,
    ctr text,
    cvr text,
    "date" text,
    display text,
    domain text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    end_date text,
    full_domain text,
    heading text,
    imp text,
    ios_id text,
    is_android text,
    is_ios text,
    line_item text,
    ltr text,
    measure_ias text,
    native_ad text,
    nativead text,
    page_time text,
    page_time_15_s text,
    page_time_units text,
    profit text,
    rcpa text,
    rcpc text,
    rcpcl text,
    rcpe text,
    rcpm text,
    revenue text,
    s_conv text,
    sconv_imp text,
    seller text,
    "source" text,
    start_date text,
    stats_50_v_2_s_ias text,
    sub_advertiser text,
    sub_advertiser_id text,
    superbanned text,
    tagline text,
    tp_cpc_cost text,
    tp_cpm_cost text,
    uniq_conv text,
    uniq_imp text,
    unique_imp text,
    unique_imp_inverse_rate text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id),
    FOREIGN KEY (line_item_id) REFERENCES campaign_group(id),
    FOREIGN KEY (native_ad_id) REFERENCES creative(id)
);

CREATE TABLE insight_campaign_supply_source (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE insight_campaign_demographic (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE insight_campaign_group_category (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE creative_imp_tracker_url (
    imp_tracker_url text,
    creative_id text,
    PRIMARY KEY (imp_tracker_url, creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE creative_vast_tracker (
    "index" text,
    creative_id text,
    event_type text,
    url text,
    PRIMARY KEY ("index", creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE creative_data (
    id text,
    creative_id text,
    file_name text,
    height text,
    url text,
    width text,
    PRIMARY KEY (id, creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE creative_icon (
    id text,
    creative_id text,
    file_name text,
    height text,
    url text,
    width text,
    PRIMARY KEY (id, creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE creative_display_js (
    "index" text,
    creative_id text,
    height text,
    img_url text,
    is_expandable text,
    js_code text,
    js_code_macro text,
    width text,
    PRIMARY KEY ("index", creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE creative_input_data_video (
    "index" text,
    creative_id text,
    bitrate text,
    duration text,
    file_type text,
    height text,
    s_3_url text,
    width text,
    PRIMARY KEY ("index", creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE creative_input_data_audio (
    "index" text,
    creative_id text,
    bitrate text,
    duration text,
    file_type text,
    height text,
    s_3_url text,
    width text,
    PRIMARY KEY ("index", creative_id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE creative (
    id text,
    api_frameworks jsonb,
    audit_status text,
    brandname text,
    channel text,
    click_url text,
    created_at text,
    cta_text text,
    input_heading text,
    input_landing_url text,
    input_tagline text,
    input_vast_xml text,
    "name" text,
    "state" text,
    status_code text,
    status_description text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE insight_campaign_deal (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE insight_campaign_creative_tactic (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE supply_source_option (
    id text,
    "name" text,
    PRIMARY KEY (id, "name")
);

CREATE TABLE insight_campaign_group_device (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE custom_segment_option (
    identifier text,
    "name" text,
    PRIMARY KEY (identifier, "name")
);

CREATE TABLE insight_campaign_group_supply_source (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE insight_campaign_group_bid_factor (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE insight_campaign_audience_ab (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE advertiser_line_item (
    advertiser_id text,
    line_item_id text,
    PRIMARY KEY (advertiser_id, line_item_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (line_item_id) REFERENCES campaign_group(id)
);

CREATE TABLE advertiser (
    id text,
    description text,
    "name" text,
    PRIMARY KEY (id)
);

CREATE TABLE insight_campaign_group_creative_tactic (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE insight_campaign_group_geo (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE stats_delivery_advertiser (
    _fivetran_id text,
    advertiser_id text,
    campaign_id text,
    conversion_tracker_id text,
    line_item_id text,
    native_ad_id text,
    advertiser text,
    app_name text,
    atos text,
    atos_units text,
    banned text,
    campaign_custom_fields jsonb,
    channel text,
    click text,
    click_url text,
    conv text,
    conv_click text,
    conv_click_time_avg text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    conversion_tracker text,
    cost text,
    creatives_img_url text,
    creatives_size text,
    ctr text,
    cvr text,
    "date" text,
    display text,
    domain text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    end_date text,
    engage_rate text,
    full_domain text,
    heading text,
    imp text,
    ios_id text,
    is_android text,
    is_ios text,
    line_item text,
    ltr text,
    measure_ias text,
    native_ad text,
    nativead text,
    page_start text,
    page_time text,
    page_time_15_s text,
    page_time_units text,
    profit text,
    rcpa text,
    rcpc text,
    rcpcl text,
    rcpe text,
    rcpm text,
    revenue text,
    s_conv text,
    sconv_click text,
    sconv_imp text,
    seller text,
    "source" text,
    start_date text,
    stats_50_v_2_s_ias text,
    sub_advertiser text,
    sub_advertiser_id text,
    superbanned text,
    tagline text,
    tp_cpc_cost text,
    tp_cpm_cost text,
    uniq_conv text,
    uniq_ecpa text,
    uniq_imp text,
    unique_imp text,
    unique_imp_inverse_rate text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id),
    FOREIGN KEY (line_item_id) REFERENCES campaign_group(id),
    FOREIGN KEY (native_ad_id) REFERENCES creative(id)
);

CREATE TABLE insight_campaign_group_deal (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE insight_campaign_geo (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE insight_campaign_group_retargeting_segment (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE insight_campaign_category (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE insight_campaign_bid_factor (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE stats_delivery_campaign (
    _fivetran_id text,
    advertiser_id text,
    campaign_id text,
    conversion_tracker_id text,
    line_item_id text,
    native_ad_id text,
    advertiser text,
    app_name text,
    atos text,
    atos_units text,
    banned text,
    campaign_custom_fields jsonb,
    campaign_type text,
    channel text,
    click text,
    click_url text,
    conv text,
    conv_click text,
    conv_click_time_avg text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    conversion_tracker text,
    cost text,
    creatives_img_url text,
    creatives_size text,
    ctr text,
    cvr text,
    "date" text,
    display text,
    domain text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    end_date text,
    engage_rate text,
    full_domain text,
    heading text,
    imp text,
    ios_id text,
    is_android text,
    is_ios text,
    line_item text,
    ltr text,
    measure_ias text,
    native_ad text,
    nativead text,
    page_time text,
    page_time_15_s text,
    page_time_units text,
    profit text,
    rcpa text,
    rcpc text,
    rcpcl text,
    rcpe text,
    rcpm text,
    revenue text,
    s_conv text,
    sconv_imp text,
    seller text,
    "source" text,
    start_date text,
    stats_50_v_2_s_ias text,
    sub_advertiser text,
    sub_advertiser_id text,
    superbanned text,
    tagline text,
    tp_cpc_cost text,
    tp_cpm_cost text,
    uniq_conv text,
    uniq_imp text,
    unique_imp_inverse_rate text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id),
    FOREIGN KEY (line_item_id) REFERENCES campaign_group(id),
    FOREIGN KEY (native_ad_id) REFERENCES creative(id)
);

CREATE TABLE insight_campaign_group_audience_ab (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE audience_permitted_advertiser (
    audience_id text,
    permitted_advertiser_id text,
    PRIMARY KEY (audience_id, permitted_advertiser_id),
    FOREIGN KEY (audience_id) REFERENCES audience(id),
    FOREIGN KEY (permitted_advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE audience_file (
    id text,
    audience_id text,
    files_path text,
    "name" text,
    "size" text,
    url text,
    PRIMARY KEY (id, audience_id),
    FOREIGN KEY (audience_id) REFERENCES audience(id)
);

CREATE TABLE audience_geo_targets_file (
    id text,
    audience_id text,
    files_path text,
    "name" text,
    "size" text,
    url text,
    PRIMARY KEY (id, audience_id),
    FOREIGN KEY (audience_id) REFERENCES audience(id)
);

CREATE TABLE audience (
    id text,
    active text,
    advertiser_permission_restricted text,
    collection_window_explicit_date_ranges text,
    collection_window_mode text,
    collection_window_recurring_end_time text,
    collection_window_recurring_start_time text,
    collection_window_recurring_weekdays text,
    collection_window_timezone text,
    created_at text,
    expandable text,
    geo_targets_distance_units text,
    identifier text,
    "name" text,
    "size" text,
    time_window text,
    PRIMARY KEY (id)
);

CREATE TABLE group_all_campaign (
    campaign_group_id text,
    campaign_id text,
    PRIMARY KEY (campaign_group_id, campaign_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign_group (
    id text,
    advertiser_id text,
    black_list_options text,
    budget text,
    daily_cap text,
    end_date text,
    "name" text,
    pace_evenly text,
    purchase_order_number text,
    revenue_type text,
    revenue_value text,
    start_date text,
    "state" text,
    status_code text,
    status_description text,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id)
);

CREATE TABLE campaign_conversion_tracker (
    campaign_id text,
    conversion_tracker_id text,
    PRIMARY KEY (campaign_id, conversion_tracker_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id)
);

CREATE TABLE campaign_creative (
    campaign_id text,
    creative_id text,
    PRIMARY KEY (campaign_id, creative_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (creative_id) REFERENCES creative(id)
);

CREATE TABLE campaign_deal_group (
    campaign_id text,
    deal_group_id text,
    PRIMARY KEY (campaign_id, deal_group_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (deal_group_id) REFERENCES deal_group(id)
);

CREATE TABLE campaign_custom_segment (
    campaign_id text,
    custom_segment_id text,
    PRIMARY KEY (campaign_id, custom_segment_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (custom_segment_id) REFERENCES custom_segment_option(identifier)
);

CREATE TABLE campaign_supply_source_option (
    campaign_id text,
    supply_source_option_id text,
    PRIMARY KEY (campaign_id, supply_source_option_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (supply_source_option_id) REFERENCES supply_source_option(id)
);

CREATE TABLE campaign (
    id text,
    advertiser_id text,
    line_item_id text,
    allow_iframe_engagement text,
    bid_amount_total text,
    bid_type text,
    budget text,
    canada_province_options jsonb,
    category_options jsonb,
    city_options text,
    country_options jsonb,
    custom_segments_ids jsonb,
    custom_segments_list jsonb,
    daily_cap text,
    day_part_enabled text,
    day_part_end_hour text,
    day_part_start_hour text,
    day_part_timezone text,
    demo_and_interests_ids jsonb,
    demo_and_interests_list jsonb,
    device_type_options jsonb,
    domain_action text,
    domain_options jsonb,
    end_date text,
    engagement_tracking_type text,
    freq_cap_limit text,
    freq_cap_time text,
    goal text,
    is_deal_id_strict text,
    language_options jsonb,
    "name" text,
    optimize_type text,
    optimize_value text,
    other_state_options jsonb,
    pace_evenly text,
    start_date text,
    "state" text,
    status_code text,
    status_description text,
    supply_type_options jsonb,
    third_party_segments jsonb,
    "type" text,
    uk_county_options jsonb,
    us_state_options jsonb,
    use_dma text,
    weekday_budgets jsonb,
    weekday_enabled text,
    weekday_percents jsonb,
    PRIMARY KEY (id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (line_item_id) REFERENCES campaign_group(id)
);

CREATE TABLE conversion_tracker (
    id text,
    conv_type text,
    count_type text,
    description text,
    "name" text,
    post_time text,
    user_id text,
    PRIMARY KEY (id)
);

CREATE TABLE insight_campaign_device (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE insight_campaign_audience (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE retargeting_audience_advertiser (
    advertiser_id text,
    retargeting_audience_id text,
    PRIMARY KEY (advertiser_id, retargeting_audience_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (retargeting_audience_id) REFERENCES retargeting_audience(id)
);

CREATE TABLE retargeting_audience (
    id text,
    action_type text,
    advertiser_restricted text,
    description text,
    "name" text,
    post_time text,
    required_frequency text,
    PRIMARY KEY (id)
);

CREATE TABLE insight_campaign_group_audience (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE deal_group_supported_channel (
    supported_channel_type text,
    deal_group_id text,
    PRIMARY KEY (supported_channel_type, deal_group_id),
    FOREIGN KEY (deal_group_id) REFERENCES deal_group(id)
);

CREATE TABLE deal_group (
    id text,
    description text,
    "name" text,
    PRIMARY KEY (id)
);

CREATE TABLE stats_delivery_conversion_tracker (
    _fivetran_id text,
    advertiser_id text,
    campaign_id text,
    conversion_tracker_id text,
    line_item_id text,
    native_ad_id text,
    advertiser text,
    app_name text,
    atos text,
    atos_units text,
    banned text,
    campaign_custom_fields jsonb,
    channel text,
    click text,
    click_url text,
    conv text,
    conv_click text,
    conv_click_time_avg text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    conversion_tracker text,
    cost text,
    creatives_img_url text,
    creatives_size text,
    ctr text,
    cvr text,
    "date" text,
    display text,
    domain text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    end_date text,
    full_domain text,
    heading text,
    imp text,
    ios_id text,
    is_android text,
    is_ios text,
    line_item text,
    ltr text,
    native_ad text,
    nativead text,
    page_time text,
    page_time_15_s text,
    page_time_units text,
    profit text,
    rcpa text,
    rcpc text,
    rcpcl text,
    rcpe text,
    rcpm text,
    revenue text,
    s_conv text,
    sconv_click text,
    sconv_imp text,
    seller text,
    "source" text,
    start_date text,
    sub_advertiser text,
    sub_advertiser_id text,
    superbanned text,
    tagline text,
    tp_cpc_cost text,
    tp_cpm_cost text,
    tracker_conv text,
    uniq_conv text,
    uniq_imp text,
    unique_imp_inverse_rate text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id),
    FOREIGN KEY (line_item_id) REFERENCES campaign_group(id),
    FOREIGN KEY (native_ad_id) REFERENCES creative(id)
);

CREATE TABLE insight_campaign_retargeting_segment (
    _fivetran_id text,
    campaign_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE insight_campaign_group_demographic (
    _fivetran_id text,
    campaign_group_id text,
    acomp_0 text,
    acomp_25 text,
    acomp_50 text,
    acomp_75 text,
    acomp_95 text,
    atos text,
    avg_time_on_site_units text,
    campaign text,
    campaign_custom_fields jsonb,
    campaign_id text,
    categories text,
    conv text,
    conv_click text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    cost text,
    country text,
    ctr text,
    cvr text,
    demographics_segment text,
    devicetype text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    engage_rate text,
    imp text,
    line_item text,
    ltr text,
    merged_segments text,
    page_start text,
    page_time text,
    page_time_15_s text,
    programmatic_deal_group_id text,
    region text,
    retargeting_segment text,
    roas text,
    s_conv text,
    sub_advertiser text,
    supply_source text,
    tactic_bid_id text,
    tactic_native_ad_id text,
    time_on_site text,
    total_time_units text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (campaign_group_id) REFERENCES campaign_group(id)
);

CREATE TABLE stats_delivery_campaign_group (
    _fivetran_id text,
    advertiser_id text,
    campaign_id text,
    conversion_tracker_id text,
    line_item_id text,
    native_ad_id text,
    advertiser text,
    app_name text,
    atos text,
    atos_units text,
    banned text,
    campaign_custom_fields jsonb,
    channel text,
    click text,
    click_url text,
    conv text,
    conv_click text,
    conv_click_time_avg text,
    conv_cookie text,
    conv_imp_derived text,
    conv_imp_time_avg text,
    conv_ip text,
    conv_rev text,
    conversion_tracker text,
    cost text,
    creatives_img_url text,
    creatives_size text,
    ctr text,
    cvr text,
    "date" text,
    display text,
    domain text,
    ecpa text,
    ecpc text,
    ecpcl text,
    ecpe text,
    ecpm text,
    ecpv text,
    end_date text,
    engage_rate text,
    full_domain text,
    heading text,
    imp text,
    ios_id text,
    is_android text,
    is_ios text,
    line_item text,
    ltr text,
    measure_ias text,
    native_ad text,
    nativead text,
    page_start text,
    page_time text,
    page_time_15_s text,
    page_time_units text,
    profit text,
    rcpa text,
    rcpc text,
    rcpcl text,
    rcpe text,
    rcpm text,
    revenue text,
    s_conv text,
    sconv_click text,
    sconv_imp text,
    seller text,
    "source" text,
    start_date text,
    stats_50_v_2_s_ias text,
    sub_advertiser text,
    sub_advertiser_id text,
    superbanned text,
    tagline text,
    tp_cpc_cost text,
    tp_cpm_cost text,
    uniq_conv text,
    uniq_ecpa text,
    uniq_imp text,
    unique_imp text,
    unique_imp_inverse_rate text,
    vcomp_0 text,
    vcomp_25 text,
    vcomp_50 text,
    vcomp_75 text,
    vcomp_95 text,
    vcomp_rate text,
    view_percent text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (advertiser_id) REFERENCES advertiser(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id),
    FOREIGN KEY (line_item_id) REFERENCES campaign_group(id),
    FOREIGN KEY (native_ad_id) REFERENCES creative(id)
);
