CREATE TABLE inventory (
    id text,
    product_id text,
    warehouse_info_id text,
    allocated_quantity text,
    quantity text,
    sku text,
    variant_info_description text,
    variant_info_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (warehouse_info_id) REFERENCES warehouse(id)
);

CREATE TABLE offer_product (
    offer_id text,
    product_id text,
    PRIMARY KEY (offer_id, product_id),
    FOREIGN KEY (offer_id) REFERENCES offer(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE offer_billing_model (
    billing_model_id text,
    offer_id text,
    PRIMARY KEY (billing_model_id, offer_id),
    FOREIGN KEY (billing_model_id) REFERENCES billing_model(id),
    FOREIGN KEY (offer_id) REFERENCES offer(id)
);

CREATE TABLE offer (
    id text,
    terminating_product_id text,
    created_at_date text,
    created_at_timezone text,
    created_at_timezone_type text,
    cycle_products text,
    cycle_type_id text,
    cycle_type_name text,
    expire_cycles text,
    is_archived text,
    is_available_on_syncable text,
    is_immutable text,
    is_prepaid text,
    is_seasonal text,
    is_series text,
    is_store text,
    is_trial text,
    "name" text,
    prepaid_profile text,
    seasonal_products text,
    terminating_cycle_type_description text,
    terminating_cycle_type_id text,
    terminating_cycle_type_name text,
    trial jsonb,
    trial_days text,
    trial_is_custom_duration text,
    trial_is_custom_price text,
    trial_is_delayed_billing text,
    trial_workflows jsonb,
    type_active text,
    type_id text,
    type_name text,
    type_smc_active text,
    updated_at_date text,
    updated_at_timezone text,
    updated_at_timezone_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (terminating_product_id) REFERENCES product(id)
);

CREATE TABLE gateway_account (
    id text,
    "name" text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE product_image (
    id text,
    product_id text,
    alias text,
    created_at text,
    is_default text,
    is_default_email text,
    "path" text,
    updated_at text,
    uuid text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product (
    id text,
    category_description text,
    category_id text,
    category_name text,
    cost_of_goods text,
    created_at_date text,
    created_at_timezone text,
    created_at_timezone_type text,
    custom_fields jsonb,
    declared_value text,
    description text,
    is_bundle text,
    is_custom_bundle text,
    is_licensed text,
    is_shippable text,
    is_trial_product text,
    is_variant_enabled text,
    legacy_subscription_cycle text,
    legacy_subscription_next_product_id text,
    legacy_subscription_type text,
    max_items text,
    max_quantity text,
    "name" text,
    price text,
    restocking_fee text,
    sku text,
    taxable text,
    updated_at_date text,
    updated_at_timezone text,
    updated_at_timezone_type text,
    vertical_id text,
    vertical_name text,
    PRIMARY KEY (id)
);

CREATE TABLE coupon_promo_code (
    id text,
    coupon_id text,
    code text,
    created_at_date text,
    created_at_timezone text,
    created_at_timezone_type text,
    created_by text,
    is_active text,
    is_deleted text,
    use_count text,
    PRIMARY KEY (id, coupon_id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE coupon_product (
    "index" text,
    coupon_id text,
    product_id text,
    variant_id text,
    is_eligible text,
    PRIMARY KEY ("index", coupon_id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (variant_id) REFERENCES product_variant(id)
);

CREATE TABLE coupon (
    id text,
    creator_id text,
    updator_id text,
    created_at_date text,
    created_at_timezone text,
    created_at_timezone_type text,
    description text,
    discount_amount text,
    discount_amt text,
    discount_pct text,
    discount_percent text,
    expires_at text,
    is_active text,
    is_bogo text,
    is_buy_x_get_y text,
    is_free_shipping text,
    is_lifetime text,
    limits text,
    limits_per_code text,
    limits_per_code_per_customer text,
    limits_per_customer text,
    limits_total text,
    max_qty text,
    maximum_quantity text,
    min_qty text,
    minimum_purchase text,
    minimum_quantity text,
    "name" text,
    promo_code_count text,
    type_id text,
    updated_at_date text,
    updated_at_timezone text,
    updated_at_timezone_type text,
    use_count text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updator_id) REFERENCES users(id)
);

CREATE TABLE billing_model (
    id text,
    creator_id text,
    updator_id text,
    created_at_date text,
    created_at_timezone text,
    created_at_timezone_type text,
    "date" text,
    dates text,
    "day" text,
    days text,
    description text,
    expire_cycles text,
    frequency text,
    frequency_type_id text,
    is_archived text,
    is_default text,
    is_preserve_quantity text,
    "name" text,
    "type" text,
    type_id text,
    type_name text,
    updated_at text,
    updated_at_date text,
    updated_at_timezone text,
    updated_at_timezone_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updator_id) REFERENCES users(id)
);

CREATE TABLE product_variant_attribute (
    id text,
    product_id text,
    product_variant_id text,
    attribute_id text,
    attribute_name text,
    attribute_option_id text,
    attribute_option_name text,
    PRIMARY KEY (id, product_id, product_variant_id),
    FOREIGN KEY (product_id) REFERENCES product_variant(product_id),
    FOREIGN KEY (product_variant_id) REFERENCES product_variant(id)
);

CREATE TABLE product_variant (
    id text,
    product_id text,
    price text,
    quantity text,
    sku_num text,
    weight text,
    PRIMARY KEY (id, product_id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE warehouse (
    id text,
    created_by_id text,
    updated_by_id text,
    active text,
    address_1 text,
    address_2 text,
    city text,
    country_id text,
    description text,
    "name" text,
    "state" text,
    zip text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (updated_by_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    call_center_provider_id text,
    created_at text,
    department_id text,
    email text,
    is_active text,
    "name" text,
    timezone text,
    updated_at text,
    PRIMARY KEY (id)
);

CREATE TABLE gateway_profile (
    id text,
    gateway_account_id text,
    alias text,
    created_on text,
    currency_code text,
    currency_id text,
    currency_symbol_left text,
    currency_title text,
    current_monthly_amount text,
    processing_percent text,
    PRIMARY KEY (id, gateway_account_id),
    FOREIGN KEY (gateway_account_id) REFERENCES gateway_account(id)
);

CREATE TABLE campaign_country (
    id text,
    campaign_id text,
    calling_code text,
    iso_2 text,
    iso_3 text,
    iso_numeric text,
    "name" text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign_offer (
    campaign_id text,
    offer_id text,
    PRIMARY KEY (campaign_id, offer_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (offer_id) REFERENCES offer(id)
);

CREATE TABLE campaign_payment_method (
    "index" text,
    campaign_id text,
    label text,
    "value" text,
    PRIMARY KEY ("index", campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign_postback_profile_campaign (
    campaign_id text,
    campaign_postback_profile_id text,
    PRIMARY KEY (campaign_id, campaign_postback_profile_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (campaign_postback_profile_id) REFERENCES campaign_postback_profile(id)
);

CREATE TABLE campaign_postback_profile_header (
    id text,
    campaign_id text,
    campaign_postback_profile_id text,
    created_by_id text,
    updated_by_id text,
    created_at text,
    deleted_at text,
    "key" text,
    updated_at text,
    "value" text,
    PRIMARY KEY (id, campaign_id, campaign_postback_profile_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign_postback_profile(campaign_id),
    FOREIGN KEY (campaign_postback_profile_id) REFERENCES campaign_postback_profile(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (updated_by_id) REFERENCES users(id)
);

CREATE TABLE campaign_postback_profile (
    id text,
    campaign_id text,
    creator_id text,
    updator_id text,
    created_at text,
    http_method text,
    is_active text,
    is_global text,
    "name" text,
    trigger_type_id text,
    triggers jsonb,
    "type" text,
    type_id text,
    updated_at text,
    url text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updator_id) REFERENCES users(id)
);

CREATE TABLE campaign_shipping_profile (
    id text,
    campaign_id text,
    amount_recurring text,
    amount_trial text,
    created_at_date text,
    created_at_timezone text,
    created_at_timezone_type text,
    description text,
    freight_code text,
    "name" text,
    threshold_amount text,
    threshold_charge_amount text,
    type_code text,
    type_created_at_date text,
    type_created_at_timezone text,
    type_created_at_timezone_type text,
    type_id text,
    type_name text,
    type_updated_at text,
    PRIMARY KEY (id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign_product (
    campaign_id text,
    product_id text,
    is_trial_allowed text,
    PRIMARY KEY (campaign_id, product_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE campaign_coupon_profile (
    campaign_id text,
    coupon_id text,
    PRIMARY KEY (campaign_id, coupon_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE campaign_fraud_provider (
    fraud_providers_id text,
    campaign_id text,
    PRIMARY KEY (fraud_providers_id, campaign_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign (
    id text,
    creator_id text,
    updator_id text,
    alternative_payments jsonb,
    archived_at_date text,
    archived_at_timezone text,
    archived_at_timezone_type text,
    call_confirm_provider_id text,
    channel_id text,
    channel_name text,
    chargeback_provider_id text,
    check_provider_id text,
    created_at_date text,
    created_at_timezone text,
    created_at_timezone_type text,
    data_verification_provider_id text,
    description text,
    email_provider_id text,
    fulfillment_id text,
    gateway_id text,
    is_active text,
    is_archived text,
    is_avs_enabled text,
    is_collections_enabled text,
    is_custom_price_allowed text,
    is_prepaid_blocked text,
    max_grace_period text,
    membership_provider_id text,
    "name" text,
    pre_auth_amount text,
    prospect_provider_id text,
    return_profiles jsonb,
    site_url text,
    tax_provider_id text,
    updated_at_date text,
    updated_at_timezone text,
    updated_at_timezone_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (updator_id) REFERENCES users(id)
);

CREATE TABLE orders_product (
    orders_id text,
    product_id text,
    billing_model_id text,
    offer_id text,
    billing_model_discount text,
    forecasted_revenue text,
    hold_date text,
    is_add_on text,
    is_full_refund text,
    is_in_trial text,
    is_recurring text,
    is_shippable text,
    is_terminal text,
    next_subscription_product text,
    next_subscription_product_id text,
    next_subscription_product_price text,
    next_subscription_qty text,
    on_hold text,
    recurring_date text,
    refund_amount text,
    step_number text,
    subscription_id text,
    PRIMARY KEY (orders_id, product_id),
    FOREIGN KEY (orders_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (billing_model_id) REFERENCES billing_model(id),
    FOREIGN KEY (offer_id) REFERENCES offer(id)
);

CREATE TABLE orders_system_note (
    "index" text,
    orders_id text,
    system_note text,
    PRIMARY KEY ("index", orders_id),
    FOREIGN KEY (orders_id) REFERENCES orders(id)
);

CREATE TABLE orders (
    id text,
    campaign_id text,
    contact_id text,
    coupon_id text,
    acquisition_date text,
    affid text,
    affiliate text,
    afid text,
    aid text,
    amount_refunded text,
    amount_refunded_to_date text,
    ancestor_id text,
    auth_id text,
    billing_city text,
    billing_company_name text,
    billing_country text,
    billing_cycle text,
    billing_first_name text,
    billing_last_name text,
    billing_postcode text,
    billing_state text,
    billing_state_id text,
    billing_street_address text,
    billing_street_address_2 text,
    c_1 text,
    c_2 text,
    c_3 text,
    cc_expires text,
    cc_first_6 text,
    cc_last_4 text,
    cc_number text,
    cc_orig_first_6 text,
    cc_orig_last_4 text,
    cc_type text,
    chargeback_date text,
    check_account_last_4 text,
    check_routing_last_4 text,
    check_ssn_last_4 text,
    check_transitnum text,
    child_id text,
    click_id text,
    consent_received text,
    consent_required text,
    coupon_discount_amount text,
    created_by_employee_name text,
    created_by_user_name text,
    credit_applied text,
    credit_card_number text,
    current_rebill_discount_percent text,
    customer_id text,
    customers_telephone text,
    decline_reason text,
    decline_reason_details text,
    decline_salvage_discount_percent text,
    email_address text,
    first_name text,
    gateway_descriptor text,
    gateway_id text,
    hold_date text,
    ip_address text,
    ip_address_lookup text,
    is_3_d_protected text,
    is_any_product_recurring text,
    is_blacklisted text,
    is_cascaded text,
    is_chargeback text,
    is_fraud text,
    is_recurring text,
    is_refund text,
    is_rma text,
    is_test_cc text,
    is_void text,
    last_name text,
    main_product_id text,
    main_product_quantity text,
    next_subscription_product text,
    next_subscription_product_id text,
    on_hold text,
    on_hold_by text,
    opt text,
    order_confirmed text,
    order_confirmed_date text,
    order_customer_types jsonb,
    order_sales_tax text,
    order_sales_tax_amount text,
    order_status text,
    order_total text,
    parent_id text,
    prepaid_match text,
    preserve_gateway text,
    processor_id text,
    promo_code text,
    rebill_discount_percent text,
    recurring_date text,
    refund_amount text,
    refund_date text,
    refunded text,
    restocking_fee text,
    retry_attempt text,
    retry_date text,
    return_reason text,
    rma_number text,
    rma_reason text,
    shippable text,
    shipping text,
    shipping_amount text,
    shipping_city text,
    shipping_company_name text,
    shipping_country text,
    shipping_date text,
    shipping_first_name text,
    shipping_id text,
    shipping_last_name text,
    shipping_method_name text,
    shipping_postcode text,
    shipping_state text,
    shipping_state_id text,
    shipping_street_address text,
    shipping_street_address_2 text,
    sid text,
    stop_after_next_rebill text,
    sub_affiliate text,
    subtotal text,
    tax text,
    tax_pct text,
    time_stamp text,
    total text,
    tracking_number text,
    transaction_id text,
    upsell_product_id text,
    upsell_product_quantity text,
    utm_info_campaign text,
    utm_info_content text,
    utm_info_device_category text,
    utm_info_medium text,
    utm_info_source text,
    utm_info_term text,
    vat_tax text,
    vat_tax_pct text,
    void_amount text,
    void_date text,
    volume_discount text,
    website_received text,
    website_sent text,
    PRIMARY KEY (id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (coupon_id) REFERENCES coupon(id)
);

CREATE TABLE affiliate (
    id text,
    created_by_id text,
    updated_by_id text,
    created_at text,
    network text,
    type_active text,
    type_id text,
    type_name text,
    updated_at text,
    "value" text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (updated_by_id) REFERENCES users(id)
);

CREATE TABLE contact_address (
    id text,
    contact_id text,
    creator_id text,
    city text,
    country text,
    created_at text,
    deleted_at text,
    email text,
    first_name text,
    is_default text,
    last_name text,
    phone text,
    phone_key text,
    "state" text,
    street text,
    street_2 text,
    updated_at text,
    uuid text,
    zip text,
    PRIMARY KEY (id, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE contact_note (
    id text,
    contact_id text,
    creator_id text,
    created_at text,
    deleted_at text,
    updated_at text,
    updator text,
    "value" text,
    PRIMARY KEY (id, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE contact_custom_field_option (
    id text,
    contact_custom_field_id text,
    contact_id text,
    "value" text,
    PRIMARY KEY (id, contact_custom_field_id, contact_id),
    FOREIGN KEY (contact_custom_field_id) REFERENCES contact_custom_field(id),
    FOREIGN KEY (contact_id) REFERENCES contact_custom_field(contact_id)
);

CREATE TABLE contact_custom_field (
    id text,
    contact_id text,
    field_type_id text,
    is_multi text,
    "name" text,
    token_key text,
    type_id text,
    PRIMARY KEY (id, contact_id),
    FOREIGN KEY (contact_id) REFERENCES contact(id)
);

CREATE TABLE contact (
    id text,
    created_at text,
    email text,
    first_name text,
    is_member text,
    is_sms_communication_enabled text,
    last_name text,
    opted_communications text,
    origin_id text,
    phone text,
    phone_key text,
    PRIMARY KEY (id)
);
