CREATE TABLE business_snapshot_cost_stat (
    period_key text,
    cogs double precision,
    marketing double precision,
    sales double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE business_snapshot_revenue_stat (
    period_key text,
    amount_renewed_that_was_up_gross double precision,
    amount_renewed_that_was_up_net double precision,
    bookings double precision,
    churn double precision,
    downsell double precision,
    existing double precision,
    influx double precision,
    metered double precision,
    new_bookings double precision,
    new_count double precision,
    non_recurring double precision,
    non_renewal_upsell double precision,
    percent_recurring double precision,
    reactivated_bookings double precision,
    recurring_period_growth double precision,
    recurring_revenue_with_rolling_metered double precision,
    renewal_bookings double precision,
    rolling_metered double precision,
    total double precision,
    total_period_growth double precision,
    total_period_revenue double precision,
    up_for_renewal double precision,
    upsell double precision,
    upsell_bookings double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE business_snapshot_seat_stat (
    period_key text,
    churn double precision,
    downsell double precision,
    existing double precision,
    influx double precision,
    influx_movement double precision,
    new_count double precision,
    total double precision,
    upsell double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE business_snapshot_saas_stat (
    period_key text,
    all_cac_cost_marketing double precision,
    all_cac_cost_sales double precision,
    all_cac_customer_stats_new_all_customers double precision,
    all_cac_ttm_cost_marketing double precision,
    all_cac_ttm_cost_sales double precision,
    all_cac_ttm_customer_stats_new_all_customers double precision,
    all_cac_ttm_value double precision,
    all_cac_value double precision,
    arpa_customer_stats_total double precision,
    arpa_revenue_stats_total double precision,
    arpa_ttm_customer_stats_total double precision,
    arpa_ttm_revenue_stats_total double precision,
    arpa_ttm_value double precision,
    arpa_value double precision,
    burn_multiple_net_new_revenue double precision,
    burn_multiple_ttm_net_new_revenue double precision,
    burn_multiple_ttm_net_profit double precision,
    burn_multiple_ttm_value double precision,
    burn_multiple_value double precision,
    gross_customer_retention_churn_amount double precision,
    gross_customer_retention_churned_customers double precision,
    gross_customer_retention_customers_previous_total double precision,
    gross_customer_retention_downsell_amount double precision,
    gross_customer_retention_downsell_customers double precision,
    gross_customer_retention_existing_amount double precision,
    gross_customer_retention_existing_customers double precision,
    gross_customer_retention_new_amount double precision,
    gross_customer_retention_new_customers double precision,
    gross_customer_retention_ttm_churn_amount double precision,
    gross_customer_retention_ttm_churned_customers double precision,
    gross_customer_retention_ttm_customers_previous_total double precision,
    gross_customer_retention_ttm_downsell_amount double precision,
    gross_customer_retention_ttm_downsell_customers double precision,
    gross_customer_retention_ttm_existing_amount double precision,
    gross_customer_retention_ttm_existing_customers double precision,
    gross_customer_retention_ttm_new_amount double precision,
    gross_customer_retention_ttm_new_customers double precision,
    gross_customer_retention_ttm_upsell_amount double precision,
    gross_customer_retention_ttm_upsell_customers double precision,
    gross_customer_retention_ttm_value double precision,
    gross_customer_retention_upsell_amount double precision,
    gross_customer_retention_upsell_customers double precision,
    gross_customer_retention_value double precision,
    gross_margin_cost_cogs double precision,
    gross_margin_revenue_total_period double precision,
    gross_margin_value double precision,
    gross_revenue_churn_rate_gross_revenue_retention double precision,
    gross_revenue_churn_rate_ttm_gross_revenue_retention double precision,
    gross_revenue_churn_rate_ttm_value double precision,
    gross_revenue_churn_rate_value double precision,
    gross_revenue_retention_revenue_previous_total double precision,
    gross_revenue_retention_revenue_renewed double precision,
    gross_revenue_retention_ttm_revenue_previous_total double precision,
    gross_revenue_retention_ttm_revenue_renewed double precision,
    gross_revenue_retention_ttm_value double precision,
    gross_revenue_retention_value double precision,
    gross_up_for_renewal_retention_amount_renewed_that_was_up_gross double precision,
    gross_up_for_renewal_retention_up_for_renewal double precision,
    gross_up_for_renewal_retention_value double precision,
    ltv_arpa double precision,
    ltv_gross_customer_retention double precision,
    ltv_ttm_arpa_avg double precision,
    ltv_ttm_gross_customer_retention double precision,
    ltv_ttm_value double precision,
    ltv_value double precision,
    ltvcac_ratio_cac double precision,
    ltvcac_ratio_ltv double precision,
    ltvcac_ratio_ttm_cac double precision,
    ltvcac_ratio_ttm_ltv double precision,
    ltvcac_ratio_ttm_value double precision,
    ltvcac_ratio_value double precision,
    ltvgm_laden_arpa double precision,
    ltvgm_laden_gross_customer_retention double precision,
    ltvgm_laden_gross_margin double precision,
    ltvgm_laden_ttm_arpa_avg double precision,
    ltvgm_laden_ttm_gross_customer_retention double precision,
    ltvgm_laden_ttm_gross_margin double precision,
    ltvgm_laden_ttm_value double precision,
    ltvgm_laden_value double precision,
    net_new_revenue_churn_revenue double precision,
    net_new_revenue_downsell_revenue double precision,
    net_new_revenue_new_revenue double precision,
    net_new_revenue_upsell_revenue double precision,
    net_new_revenue_value double precision,
    net_revenue_retention_ending_revenue_from_starting double precision,
    net_revenue_retention_revenue_previous_total double precision,
    net_revenue_retention_ttm_ending_revenue_from_starting double precision,
    net_revenue_retention_ttm_revenue_previous_total double precision,
    net_revenue_retention_ttm_value double precision,
    net_revenue_retention_value double precision,
    net_up_for_renewal_retention_amount_renewed_that_was_up_net double precision,
    net_up_for_renewal_retention_non_renewal_upsell double precision,
    net_up_for_renewal_retention_up_for_renewal double precision,
    net_up_for_renewal_retention_value double precision,
    new_arpa_customer_stats_new double precision,
    new_arpa_revenue_stats_new double precision,
    new_arpa_ttm_customer_stats_new double precision,
    new_arpa_ttm_revenue_stats_new double precision,
    new_arpa_ttm_value double precision,
    new_arpa_value double precision,
    new_revenue_to_costs_ratio_cost_marketing double precision,
    new_revenue_to_costs_ratio_cost_sales double precision,
    new_revenue_to_costs_ratio_new_revenue double precision,
    new_revenue_to_costs_ratio_value double precision,
    payback_period_cost_marketing double precision,
    payback_period_cost_sales double precision,
    payback_period_gross_margin double precision,
    payback_period_revenue_stats_new double precision,
    payback_period_value double precision,
    recurring_arpu_recurring_revenue_total double precision,
    recurring_arpu_total_seats double precision,
    recurring_arpu_value double precision,
    recurring_cac_cost_marketing double precision,
    recurring_cac_cost_sales double precision,
    recurring_cac_customer_stats_new double precision,
    recurring_cac_ttm_cost_marketing double precision,
    recurring_cac_ttm_cost_sales double precision,
    recurring_cac_ttm_customer_stats_new double precision,
    recurring_cac_ttm_value double precision,
    recurring_cac_value double precision,
    rule_of_40_ttm_net_profit double precision,
    rule_of_40_ttm_recurring_period_growth double precision,
    rule_of_40_ttm_total_period_revenue double precision,
    rule_of_40_ttm_value double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE business_snapshot_customer_stat (
    period_key text,
    all_customers double precision,
    all_recurring_customers double precision,
    churn double precision,
    customers_renewed double precision,
    customers_up_for_renewal double precision,
    customers_with_open_contracts double precision,
    downsell double precision,
    existing double precision,
    influx double precision,
    influx_movement double precision,
    new_all_customers double precision,
    new_count double precision,
    total double precision,
    upsell double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE business_snapshot_summary_stat (
    period_key text,
    all_arpa_customer_stats_total double precision,
    all_arpa_revenue_stats_total double precision,
    all_arpa_ttm_customer_stats_total double precision,
    all_arpa_ttm_revenue_stats_total double precision,
    all_arpa_ttm_value double precision,
    all_arpa_value double precision,
    all_cac_cost_marketing double precision,
    all_cac_cost_sales double precision,
    all_cac_customer_stats_new_all_customers double precision,
    all_cac_ttm_cost_marketing double precision,
    all_cac_ttm_cost_sales double precision,
    all_cac_ttm_customer_stats_new_all_customers double precision,
    all_cac_ttm_value double precision,
    all_cac_value double precision,
    all_customers double precision,
    amount_renewed_that_was_up_gross double precision,
    amount_renewed_that_was_up_net double precision,
    bookings double precision,
    burn_multiple_net_new_revenue double precision,
    burn_multiple_net_profit double precision,
    burn_multiple_ttm_net_new_revenue double precision,
    burn_multiple_ttm_net_profit double precision,
    burn_multiple_ttm_value double precision,
    burn_multiple_value double precision,
    committed_customer_count double precision,
    committed_recurring double precision,
    customers_renewed double precision,
    customers_up_for_renewal double precision,
    customers_with_open_contracts double precision,
    gross_customer_retention_churn_amount double precision,
    gross_customer_retention_churned_customers double precision,
    gross_customer_retention_customers_previous_total double precision,
    gross_customer_retention_downsell_amount double precision,
    gross_customer_retention_downsell_customers double precision,
    gross_customer_retention_existing_amount double precision,
    gross_customer_retention_existing_customers double precision,
    gross_customer_retention_new_amount double precision,
    gross_customer_retention_new_customers double precision,
    gross_customer_retention_ttm_churn_amount double precision,
    gross_customer_retention_ttm_churned_customers double precision,
    gross_customer_retention_ttm_customers_previous_total double precision,
    gross_customer_retention_ttm_downsell_amount double precision,
    gross_customer_retention_ttm_downsell_customers double precision,
    gross_customer_retention_ttm_existing_amount double precision,
    gross_customer_retention_ttm_existing_customers double precision,
    gross_customer_retention_ttm_new_amount double precision,
    gross_customer_retention_ttm_new_customers double precision,
    gross_customer_retention_ttm_upsell_amount double precision,
    gross_customer_retention_ttm_upsell_customers double precision,
    gross_customer_retention_ttm_value double precision,
    gross_customer_retention_upsell_amount double precision,
    gross_customer_retention_upsell_customers double precision,
    gross_customer_retention_value double precision,
    gross_margin_cost_cogs double precision,
    gross_margin_revenue_total_period double precision,
    gross_margin_value double precision,
    gross_revenue_churn_rate_gross_revenue_retention double precision,
    gross_revenue_churn_rate_ttm_gross_revenue_retention double precision,
    gross_revenue_churn_rate_ttm_value double precision,
    gross_revenue_churn_rate_value double precision,
    gross_revenue_retention_revenue_previous_total double precision,
    gross_revenue_retention_revenue_renewed double precision,
    gross_revenue_retention_ttm_revenue_previous_total double precision,
    gross_revenue_retention_ttm_revenue_renewed double precision,
    gross_revenue_retention_ttm_value double precision,
    gross_revenue_retention_value double precision,
    gross_up_for_renewal_retention_amount_renewed_that_was_up_gross double precision,
    gross_up_for_renewal_retention_up_for_renewal double precision,
    gross_up_for_renewal_retention_value double precision,
    ltv_arpa_avg double precision,
    ltv_gross_customer_retention double precision,
    ltv_ttm_arpa_avg double precision,
    ltv_ttm_gross_customer_retention double precision,
    ltv_ttm_value double precision,
    ltv_value double precision,
    ltvcac_ratio_cac double precision,
    ltvcac_ratio_ltv double precision,
    ltvcac_ratio_ttm_cac double precision,
    ltvcac_ratio_ttm_ltv double precision,
    ltvcac_ratio_ttm_value double precision,
    ltvcac_ratio_value double precision,
    ltvgm_laden_arpa_avg double precision,
    ltvgm_laden_gross_customer_retention double precision,
    ltvgm_laden_gross_margin double precision,
    ltvgm_laden_ttm_arpa_avg double precision,
    ltvgm_laden_ttm_gross_customer_retention double precision,
    ltvgm_laden_ttm_gross_margin double precision,
    ltvgm_laden_ttm_value double precision,
    ltvgm_laden_value double precision,
    magic_number_cost_marketing_last_quarter double precision,
    magic_number_cost_sales_last_quarter double precision,
    magic_number_growth_in_arr double precision,
    magic_number_value double precision,
    metered double precision,
    net_new_revenue_churn_revenue double precision,
    net_new_revenue_downsell_revenue double precision,
    net_new_revenue_new_revenue double precision,
    net_new_revenue_upsell_revenue double precision,
    net_new_revenue_value double precision,
    net_revenue_retention_ending_revenue_from_starting double precision,
    net_revenue_retention_revenue_previous_total double precision,
    net_revenue_retention_ttm_ending_revenue_from_starting double precision,
    net_revenue_retention_ttm_revenue_previous_total double precision,
    net_revenue_retention_ttm_value double precision,
    net_revenue_retention_value double precision,
    net_up_for_renewal_retention_amount_renewed_that_was_up_net double precision,
    net_up_for_renewal_retention_non_renewal_upsell double precision,
    net_up_for_renewal_retention_up_for_renewal double precision,
    net_up_for_renewal_retention_value double precision,
    new_arpa_customer_stats_new double precision,
    new_arpa_revenue_stats_new double precision,
    new_arpa_ttm_customer_stats_new double precision,
    new_arpa_ttm_revenue_stats_new double precision,
    new_arpa_ttm_value double precision,
    new_arpa_value double precision,
    new_bookings double precision,
    new_count double precision,
    new_revenue_to_costs_ratio_cost_marketing double precision,
    new_revenue_to_costs_ratio_cost_sales double precision,
    new_revenue_to_costs_ratio_new_revenue double precision,
    new_revenue_to_costs_ratio_value double precision,
    non_recurring double precision,
    non_renewal_upsell double precision,
    payback_period_cost_marketing double precision,
    payback_period_cost_sales double precision,
    payback_period_gross_margin double precision,
    payback_period_revenue_stats_new double precision,
    payback_period_value double precision,
    percent_recurring double precision,
    reactivated_bookings double precision,
    recurring_arpu_recurring_revenue_total double precision,
    recurring_arpu_total_seats double precision,
    recurring_arpu_value double precision,
    recurring_cac_cost_marketing double precision,
    recurring_cac_cost_sales double precision,
    recurring_cac_customer_stats_new double precision,
    recurring_cac_ttm_cost_marketing double precision,
    recurring_cac_ttm_cost_sales double precision,
    recurring_cac_ttm_customer_stats_new double precision,
    recurring_cac_ttm_value double precision,
    recurring_cac_value double precision,
    recurring_customers double precision,
    recurring_period_growth double precision,
    recurring_revenue_total double precision,
    recurring_revenue_with_rolling_metered double precision,
    renewal_bookings double precision,
    rolling_metered double precision,
    rule_of_40_ttm_net_profit double precision,
    rule_of_40_ttm_recurring_period_growth double precision,
    rule_of_40_ttm_total_period_revenue double precision,
    rule_of_40_ttm_value double precision,
    sales_efficiency_ratio_cost_marketing_this_quarter double precision,
    sales_efficiency_ratio_cost_sales_this_quarter double precision,
    sales_efficiency_ratio_growth_in_arr double precision,
    sales_efficiency_ratio_value double precision,
    total_period_growth double precision,
    total_period_revenue double precision,
    total_seats double precision,
    up_for_renewal double precision,
    upsell_bookings double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE waterfall_revenue_stat (
    period_key text,
    churn double precision,
    downsell double precision,
    existing double precision,
    influx double precision,
    influx_movement double precision,
    new_count double precision,
    total double precision,
    upsell double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE waterfall_customer_stat (
    period_key text,
    churn double precision,
    downsell double precision,
    existing double precision,
    influx double precision,
    influx_movement double precision,
    new_count double precision,
    total double precision,
    upsell double precision,
    PRIMARY KEY (period_key)
);

CREATE TABLE spread (
    _fivetran_id text,
    amount text,
    created_at text,
    customer_external_id text,
    customer_id text,
    "date" text,
    id text,
    seats text,
    spread_external_id text,
    "status" text,
    transaction_external_id text,
    transaction_id text,
    "type" text,
    updated_at text,
    PRIMARY KEY (_fivetran_id)
);
