CREATE TABLE activity_tag (
    activity_id text,
    tag_id text,
    PRIMARY KEY (activity_id, tag_id),
    FOREIGN KEY (activity_id) REFERENCES activity(id),
    FOREIGN KEY (tag_id) REFERENCES account(id)
);

CREATE TABLE activity (
    id text,
    created_by_id text,
    modified_user_id text,
    parent_id text,
    activity_type text,
    comment_count text,
    created_by_name text,
    data_embed jsonb,
    data_value text,
    date_entered text,
    date_modified text,
    deleted text,
    description text,
    following text,
    last_comment_data jsonb,
    locked_fields jsonb,
    modified_by_name text,
    "name" text,
    parent_type text,
    preview_disabled_reason text,
    preview_enabled text,
    sync_key text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id),
    FOREIGN KEY (parent_id) REFERENCES account(id)
);

CREATE TABLE employee_license (
    "index" text,
    employee_id text,
    license_type text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_team (
    id text,
    employee_id text,
    "name" text,
    name_2 text,
    primary_team text,
    selected text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_email (
    email_address_id text,
    employee_id text,
    email_address text,
    invalid_email text,
    opt_out text,
    primary_address text,
    reply_to_address text,
    PRIMARY KEY (email_address_id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee (
    id text,
    created_by_id text,
    modified_user_id text,
    report_to_id text,
    accept_status_calls text,
    accept_status_id text,
    accept_status_meetings text,
    accept_status_messages text,
    accept_status_name text,
    acl_role_set_id text,
    address_city text,
    address_country text,
    address_postalcode text,
    address_state text,
    address_street text,
    appearance text,
    authenticate_id text,
    business_center_id text,
    business_center_name text,
    c_accept_status_fields text,
    calendar_ical_subscription_url text,
    calendar_publish_key text,
    calendar_publish_location text,
    calendar_search_location text,
    cookie_consent text,
    cookie_consent_received_on text,
    created_by_name text,
    currency text,
    currency_create_in_preferred text,
    currency_show_preferred text,
    customer_journey_access text,
    customer_journey_last_active text,
    date_entered text,
    date_modified text,
    dec_sep text,
    default_currency_significant_digits text,
    default_export_charset text,
    default_locale_name_format text,
    default_team text,
    deleted text,
    department text,
    description text,
    email_1 text,
    email_link_type text,
    email_reminder_time text,
    employee_status text,
    export_delimiter text,
    external_auth_only text,
    fdow text,
    field_name_placement text,
    first_name text,
    full_name text,
    is_admin text,
    is_group text,
    last_login text,
    last_name text,
    m_accept_status_fields text,
    mail_credentials text,
    messenger_id text,
    messenger_type text,
    modified_by_name text,
    num_grp_sep text,
    number_pinned_modules text,
    opportunities jsonb,
    phone_fax text,
    phone_home text,
    phone_mobile text,
    phone_other text,
    phone_work text,
    picture text,
    portal_only text,
    portal_user_password text,
    preferred_language text,
    pwd_last_changed text,
    receive_notification text,
    reminder_time text,
    reports_to_name text,
    send_email_on_mention text,
    show_on_employees text,
    site_url text,
    site_user_id text,
    "status" text,
    sugar_login text,
    sugarpdf_pdf_font_name_data text,
    sugarpdf_pdf_font_name_main text,
    sugarpdf_pdf_font_size_data text,
    sugarpdf_pdf_font_size_main text,
    sync_key text,
    system_generated_password text,
    team_count text,
    timezone text,
    title text,
    use_real_names text,
    user_hash text,
    user_name text,
    user_tabs text,
    user_type text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id),
    FOREIGN KEY (report_to_id) REFERENCES users(id)
);

CREATE TABLE currency (
    _fivetran_id text,
    created_by_id text,
    conversion_rate text,
    date_entered text,
    date_modified text,
    deleted text,
    id text,
    iso_4217 text,
    "name" text,
    "status" text,
    symbol text,
    sync_key text,
    -- custom_* (dynamic column),
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (created_by_id) REFERENCES users(id)
);

CREATE TABLE meeting_team (
    id text,
    meeting_id text,
    "name" text,
    name_2 text,
    primary_team text,
    selected text,
    PRIMARY KEY (id, meeting_id),
    FOREIGN KEY (meeting_id) REFERENCES meeting(id)
);

CREATE TABLE meeting_tag (
    meeting_id text,
    tag_id text,
    PRIMARY KEY (meeting_id, tag_id),
    FOREIGN KEY (meeting_id) REFERENCES meeting(id),
    FOREIGN KEY (tag_id) REFERENCES users(id)
);

CREATE TABLE meeting_objective (
    "index" text,
    meeting_id text,
    objectives text,
    PRIMARY KEY ("index", meeting_id),
    FOREIGN KEY (meeting_id) REFERENCES meeting(id)
);

CREATE TABLE meeting (
    id text,
    assigned_user_id text,
    created_by_id text,
    modified_user_id text,
    accept_status text,
    accept_status_users text,
    assigned_user_name text,
    base_rate text,
    cj_activity_tpl_id text,
    cj_activity_tpl_name text,
    cj_actual_sort_order text,
    cj_allow_activity_by text,
    cj_blocked_by_stage text,
    cj_momentum_end_date text,
    cj_momentum_points text,
    cj_momentum_ratio text,
    cj_momentum_score text,
    cj_momentum_start_date text,
    cj_parent_activity_id text,
    cj_parent_activity_type text,
    cj_url text,
    contact_id text,
    created_by_name text,
    creator text,
    currency_id text,
    customer_journey_blocked_by text,
    customer_journey_points text,
    customer_journey_progress text,
    customer_journey_score text,
    date_end text,
    date_entered text,
    date_modified text,
    date_start text,
    deleted text,
    description text,
    direction text,
    displayed_url text,
    dri_subworkflow_id text,
    dri_subworkflow_name text,
    dri_subworkflow_template_id text,
    dri_subworkflow_template_name text,
    dri_workflow_id text,
    dri_workflow_name text,
    dri_workflow_sort_order text,
    dri_workflow_task_template_id text,
    dri_workflow_template_id text,
    dri_workflow_template_name text,
    duration_hours text,
    duration_minutes text,
    email_reminder_checked text,
    email_reminder_sent text,
    email_reminder_time text,
    event_type text,
    external_id text,
    following text,
    host_url text,
    ical_uid text,
    internal_notes text,
    is_cj_parent_activity text,
    is_customer_journey_activity text,
    join_url text,
    location text,
    locked_fields jsonb,
    modified_by_name text,
    "name" text,
    original_start_date text,
    outlook_id text,
    parent_id text,
    parent_name text,
    parent_type text,
    password text,
    recurrence_id text,
    recurring_source text,
    reminder_checked text,
    reminder_time text,
    repeat_count text,
    repeat_days text,
    repeat_dow text,
    repeat_interval text,
    repeat_ordinal text,
    repeat_parent_id text,
    repeat_selector text,
    repeat_type text,
    repeat_unit text,
    repeat_until text,
    rset text,
    "sequence" text,
    set_accept_links text,
    start_next_journey_id text,
    "status" text,
    sync_key text,
    team_count text,
    "type" text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id)
);

CREATE TABLE pmse_case (
    id text,
    assigned_user_id text,
    created_by_id text,
    modified_user_id text,
    assigned_user_full_name text,
    cas_assigned_status text,
    cas_create_date text,
    cas_custom_status text,
    cas_finish_date text,
    cas_id text,
    cas_init_user text,
    cas_module text,
    cas_parent text,
    cas_pin text,
    cas_status text,
    cas_sugar_module text,
    cas_sugar_object_id text,
    cas_title text,
    cas_update_date text,
    cas_user_id_full_name text,
    date_entered text,
    date_modified text,
    deleted text,
    erased_field text,
    first_name text,
    is_a_person text,
    last_name text,
    modified_user_name text,
    "name" text,
    prj_created_by text,
    prj_deleted text,
    prj_id text,
    prj_module text,
    prj_run_order text,
    prj_user_id_full_name text,
    pro_id text,
    pro_title text,
    salutation text,
    team_id text,
    team_set_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id)
);

CREATE TABLE opportunity_team (
    id text,
    opportunity_id text,
    "name" text,
    name_2 text,
    primary_team text,
    selected text,
    PRIMARY KEY (id, opportunity_id),
    FOREIGN KEY (opportunity_id) REFERENCES opportunity(id)
);

CREATE TABLE opportunity (
    id text,
    account_id text,
    assigned_user_id text,
    created_by_id text,
    modified_user_id text,
    user_id text,
    ai_opp_close_week_scores text,
    ai_opp_conv_bin_accuracy text,
    ai_opp_conv_multiplier text,
    ai_opp_conv_score_absolute text,
    ai_opp_conv_score_enum text,
    amount text,
    amount_usdollar text,
    assigned_user_name text,
    base_rate text,
    best_case text,
    campaign_id text,
    campaign_name text,
    campaign_opportunity_id text,
    campaign_opportunity_name text,
    closed_revenue_line_items text,
    closed_won_revenue_line_items text,
    commit_stage text,
    commit_stage_cascade text,
    contact_role text,
    created_by_name text,
    currency_id text,
    currency_name text,
    currency_symbol text,
    date_closed text,
    date_closed_cascade text,
    date_closed_timestamp text,
    date_entered text,
    date_modified text,
    deleted text,
    denorm_account_name text,
    description text,
    dri_workflow_template_id text,
    dri_workflow_template_name text,
    following text,
    forecasted_likely text,
    geocode_status text,
    included_revenue_line_items text,
    is_escalated text,
    lead_source text,
    locked_fields jsonb,
    lost text,
    mkto_id text,
    mkto_sync text,
    modified_by_name text,
    "name" text,
    next_step text,
    opportunity_type text,
    parent jsonb,
    parent_id text,
    parent_name text,
    parent_type text,
    perform_sugar_action text,
    probability text,
    renewal text,
    renewal_parent_id text,
    renewal_parent_name text,
    sales_stage text,
    sales_stage_cascade text,
    sales_status text,
    service_duration_unit text,
    service_duration_unit_cascade text,
    service_duration_value text,
    service_duration_value_cascade text,
    service_open_flex_duration_rlis text,
    service_open_revenue_line_items text,
    service_start_date text,
    service_start_date_cascade text,
    sync_key text,
    tags jsonb,
    total_revenue_line_items text,
    widget_amount text,
    widget_date_closed text,
    widget_sales_stage text,
    worst_case text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE lead_web_email (
    email_address_id text,
    lead_id text,
    email_address text,
    invalid_email text,
    opt_out text,
    primary_address text,
    reply_to_address text,
    PRIMARY KEY (email_address_id, lead_id),
    FOREIGN KEY (lead_id) REFERENCES lead(id)
);

CREATE TABLE lead_tag (
    lead_id text,
    tag_id text,
    PRIMARY KEY (lead_id, tag_id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (tag_id) REFERENCES users(id)
);

CREATE TABLE lead_team (
    id text,
    lead_id text,
    "name" text,
    name_2 text,
    primary_team text,
    selected text,
    PRIMARY KEY (id, lead_id),
    FOREIGN KEY (lead_id) REFERENCES lead(id)
);

CREATE TABLE lead (
    id text,
    account_id text,
    assigned_user_id text,
    call_id text,
    created_by_id text,
    meeting_id text,
    modified_user_id text,
    opportunity_id text,
    report_to_id text,
    accept_status_call text,
    accept_status_id text,
    accept_status_meetings text,
    accept_status_messages text,
    accept_status_name text,
    account_description text,
    account_to_lead text,
    ai_conv_bin_accuracy text,
    ai_conv_multiplier text,
    ai_conv_score_absolute text,
    ai_conv_score_classification text,
    ai_icp_fit_bin_accuracy text,
    ai_icp_fit_multiplier text,
    ai_icp_fit_score_absolute text,
    ai_icp_fit_score_classification text,
    alt_address_city text,
    alt_address_country text,
    alt_address_postalcode text,
    alt_address_state text,
    alt_address_street text,
    alt_address_street_2 text,
    alt_address_street_3 text,
    assigned_user_name text,
    assistant text,
    assistant_phone text,
    birth_date text,
    business_center_id text,
    business_center_name text,
    c_accept_status_field text,
    campaign_id text,
    campaign_lead_id text,
    campaign_lead_name text,
    campaign_name text,
    contact_id text,
    converted text,
    converted_opp_name text,
    created_by_name text,
    date_entered text,
    date_modified text,
    deleted text,
    department text,
    description text,
    dnb_principal_id text,
    do_not_call text,
    do_not_email text,
    dp_business_purpose jsonb,
    dp_consent_last_updated text,
    dri_workflow_template_id text,
    dri_workflow_template_name text,
    email_2 text,
    email_addresses_non_primary text,
    email_opt_out text,
    external_user_id text,
    facebook text,
    first_name text,
    following text,
    full_name text,
    geocode_status text,
    googleplus text,
    hint_account_annual_revenue text,
    hint_account_description text,
    hint_account_sic_code_label text,
    hint_account_twitter_handle text,
    hint_account_website text,
    hint_contact_pic text,
    hint_education text,
    hint_education_2 text,
    hint_facebook text,
    hint_job_2 text,
    hint_phone_1 text,
    hint_phone_2 text,
    hint_photo text,
    hint_twitter text,
    invalid_email text,
    last_name text,
    lead_source text,
    lead_source_description text,
    locked_fields jsonb,
    m_accept_status_field text,
    market_interest_prediction_score text,
    market_score text,
    mkto_id text,
    mkto_lead_score text,
    mkto_sync text,
    modified_by_name text,
    "name" text,
    perform_sugar_action text,
    phone_fax text,
    phone_home text,
    phone_mobile text,
    phone_other text,
    phone_work text,
    picture text,
    portal_app text,
    portal_name text,
    preferred_language text,
    primary_address_city text,
    primary_address_country text,
    primary_address_postalcode text,
    primary_address_state text,
    primary_address_street text,
    primary_address_street_2 text,
    primary_address_street_3 text,
    refered_by text,
    report_to_name text,
    salutation text,
    "status" text,
    status_description text,
    sync_key text,
    title text,
    twitter text,
    web_to_lead_email_opt_out text,
    web_to_lead_invalid_email text,
    website text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    FOREIGN KEY (call_id) REFERENCES "call"(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (meeting_id) REFERENCES meeting(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id),
    FOREIGN KEY (opportunity_id) REFERENCES opportunity(id),
    FOREIGN KEY (report_to_id) REFERENCES users(id)
);

CREATE TABLE user_license_type (
    "index" text,
    user_id text,
    license_type text,
    PRIMARY KEY ("index", user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_team (
    id text,
    user_id text,
    "name" text,
    name_2 text,
    primary_team text,
    selected text,
    PRIMARY KEY (id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_email (
    email_address_id text,
    user_id text,
    email_address text,
    invalid_email text,
    opt_out text,
    primary_address text,
    reply_to_address text,
    PRIMARY KEY (email_address_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    call_id text,
    created_by_id text,
    meeting_id text,
    modified_user_id text,
    report_to_id text,
    accept_status_calls text,
    accept_status_id text,
    accept_status_meetings text,
    accept_status_messages text,
    accept_status_name text,
    acl_role_set_id text,
    address_city text,
    address_country text,
    address_postalcode text,
    address_state text,
    address_street text,
    appearance text,
    authenticate_id text,
    business_center_id text,
    business_center_name text,
    c_accept_status_fields text,
    calendar_ical_subscription_url text,
    calendar_publish_key text,
    calendar_publish_location text,
    calendar_search_location text,
    cookie_consent text,
    cookie_consent_received_on text,
    created_by_name text,
    currency text,
    currency_create_in_preferred text,
    currency_show_preferred text,
    customer_journey_access text,
    customer_journey_last_active text,
    date_entered text,
    date_modified text,
    dec_sep text,
    default_currency_significant_digits text,
    default_export_charset text,
    default_locale_name_format text,
    default_team text,
    deleted text,
    department text,
    description text,
    email_link_type text,
    email_reminder_time text,
    employee_status text,
    export_delimiter text,
    external_auth_only text,
    fdow text,
    field_name_placement text,
    first_name text,
    full_name text,
    hash text,
    is_admin text,
    is_group text,
    last_login text,
    last_name text,
    m_accept_status_fields text,
    mail_credentials text,
    messenger_id text,
    messenger_type text,
    modified_by_name text,
    num_grp_sep text,
    number_pinned_modules text,
    opportunities jsonb,
    phone_fax text,
    phone_home text,
    phone_mobile text,
    phone_other text,
    phone_work text,
    picture text,
    portal_only text,
    portal_user_password text,
    preferred_language text,
    pwd_last_changed text,
    receive_notification text,
    reminder_time text,
    report_to_name text,
    send_email_on_mention text,
    show_on_employees text,
    site_url text,
    site_user_id text,
    "status" text,
    sugar_login text,
    sugarpdf_pdf_font_name_data text,
    sugarpdf_pdf_font_name_main text,
    sugarpdf_pdf_font_size_data text,
    sugarpdf_pdf_font_size_main text,
    sync_key text,
    system_generated_password text,
    tab text,
    timezone text,
    title text,
    "type" text,
    user_name text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (call_id) REFERENCES "call"(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (meeting_id) REFERENCES lead(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id),
    FOREIGN KEY (report_to_id) REFERENCES users(id)
);

CREATE TABLE call_team (
    id text,
    call_id text,
    "name" text,
    name_2 text,
    primary_team text,
    selected text,
    PRIMARY KEY (id, call_id),
    FOREIGN KEY (call_id) REFERENCES "call"(id)
);

CREATE TABLE call_tag (
    tag_id text,
    call_id text,
    PRIMARY KEY (tag_id, call_id),
    FOREIGN KEY (call_id) REFERENCES "call"(id)
);

CREATE TABLE "call" (
    id text,
    assigned_user_id text,
    lead_id text,
    modified_user_id text,
    parent_id text,
    accept_status text,
    accept_status_users text,
    assigned_user_name text,
    aws_contact_id text,
    aws_lens_data text,
    call_recording text,
    call_recording_url text,
    cj_activity_tpl_name text,
    cj_actual_sort_order text,
    cj_allow_activity_by text,
    cj_momentum_end_date text,
    cj_momentum_points text,
    cj_momentum_ratio text,
    cj_momentum_score text,
    cj_momentum_start_date text,
    cj_parent_activity_id text,
    cj_parent_activity_type text,
    cj_url text,
    contact_id text,
    contact_name text,
    created_by_id text,
    created_by_name text,
    customer_journey_blocked_by text,
    customer_journey_points text,
    customer_journey_progress text,
    customer_journey_score text,
    date_end text,
    date_entered text,
    date_modified text,
    date_start text,
    deleted text,
    description text,
    direction text,
    dri_subworkflow_id text,
    dri_subworkflow_name text,
    dri_subworkflow_template_id text,
    dri_subworkflow_template_name text,
    dri_workflow_id text,
    dri_workflow_name text,
    dri_workflow_sort_order text,
    dri_workflow_task_template_id text,
    dri_workflow_template_id text,
    dri_workflow_template_name text,
    duration_hours text,
    duration_minutes text,
    email_reminder_checked text,
    email_reminder_sent text,
    email_reminder_time text,
    event_type text,
    following text,
    ical_uid text,
    internal_notes text,
    is_cj_parent_activity text,
    is_customer_journey_activity text,
    lead_name text,
    locked_fields jsonb,
    modified_by_name text,
    "name" text,
    original_start_date text,
    outlook_id text,
    parent_type text,
    recurrence_id text,
    recurring_source text,
    reminder_checked text,
    reminder_time text,
    repeat_count text,
    repeat_days text,
    repeat_dow text,
    repeat_interval text,
    repeat_ordinal text,
    repeat_parent_id text,
    repeat_selector text,
    repeat_type text,
    repeat_unit text,
    repeat_until text,
    rset text,
    sentiment_score_agent text,
    sentiment_score_agent_first_quarter text,
    sentiment_score_agent_fourth_quarter text,
    sentiment_score_agent_second_quarter text,
    sentiment_score_agent_string text,
    sentiment_score_agent_third_quarter text,
    sentiment_score_customer text,
    sentiment_score_customer_first_quarter text,
    sentiment_score_customer_fourth_quarter text,
    sentiment_score_customer_second_quarter text,
    sentiment_score_customer_string text,
    sentiment_score_customer_third_quarter text,
    set_accept_links text,
    start_next_journey_id text,
    "status" text,
    sync_key text,
    transcript text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    FOREIGN KEY (lead_id) REFERENCES lead(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id),
    FOREIGN KEY (parent_id) REFERENCES account(id)
);

CREATE TABLE account_team (
    id text,
    account_id text,
    "name" text,
    name_2 text,
    primary_team text,
    selected text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account_tag (
    tag_id text,
    account_id text,
    PRIMARY KEY (tag_id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    assigned_user_id text,
    modified_user_id text,
    accounts_w_020_account_reporting_teams_1_name text,
    accounts_w_4156_ng_teams_idb text,
    annual_revenue text,
    assigned_user_name text,
    base_rate text,
    billing_address_city text,
    billing_address_country text,
    billing_address_postalcode text,
    billing_address_state text,
    billing_address_street text,
    billing_address_street_2 text,
    billing_address_street_3 text,
    billing_address_street_4 text,
    business_center_id text,
    business_center_name text,
    campaign_id text,
    campaign_name text,
    cases_account_id text,
    cases_account_name text,
    cases_accounts_1_cases_ida text,
    cases_accounts_1_name text,
    created_by_id text,
    created_by_name text,
    currency_id text,
    date_entered text,
    date_modified text,
    deleted text,
    description text,
    dri_workflow_template_id text,
    dri_workflow_template_name text,
    duns_num text,
    email jsonb,
    email_1 text,
    email_2 text,
    email_addresses_non_primary text,
    email_opt_out text,
    employees text,
    facebook text,
    following text,
    geocode_status text,
    googleplus text,
    hint_account_facebook_handle text,
    hint_account_fiscal_year_end text,
    hint_account_founded_year text,
    hint_account_industry text,
    hint_account_industry_tags text,
    hint_account_location text,
    hint_account_logo text,
    hint_account_naics_code_lbl text,
    hint_account_pic text,
    hint_account_size text,
    industry text,
    invalid_email text,
    is_escalated text,
    locked_fields jsonb,
    main_contact text,
    member_of_id text,
    member_of_name text,
    modified_by_name text,
    "name" text,
    next_renewal_date text,
    ownership text,
    parent_id text,
    parent_name text,
    perform_sugar_action text,
    phone_alternate text,
    phone_fax text,
    phone_office text,
    rating text,
    service_level text,
    shipping_address_city text,
    shipping_address_country text,
    shipping_address_postalcode text,
    shipping_address_state text,
    shipping_address_street text,
    shipping_address_street_2 text,
    shipping_address_street_3 text,
    shipping_address_street_4 text,
    sic_code text,
    sync_key text,
    ticker_symbol text,
    twitter text,
    "type" text,
    website text,
    widget_next_renewal_date text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    FOREIGN KEY (modified_user_id) REFERENCES users(id)
);
