CREATE TABLE touchpoint_type (
    id text,
    created_at text,
    created_by text,
    display_name text,
    icon text,
    is_default text,
    non_editable text,
    updated_at text,
    updated_by text,
    used text,
    PRIMARY KEY (id)
);

CREATE TABLE poc_collection (
    id text,
    account_id text,
    additional_competitor text,
    external_id text,
    health_color text,
    health_message text,
    incumbent_competitor text,
    main_competitor text,
    named_account text,
    opportunity_closed_date text,
    opportunity_name text,
    other_additional_competitor text,
    other_incumbent_competitor text,
    other_main_competitor text,
    partner_on_poc text,
    poc_end_date text,
    poc_location text,
    poc_name text,
    poc_number text,
    poc_planned_end text,
    poc_planned_start text,
    poc_product_line text,
    poc_product_summary text,
    poc_stage text,
    poc_start_date text,
    poc_type text,
    se_on_poc text,
    second_se_on_poc text,
    success_project_url text,
    tenant_url text,
    third_se_on_poc text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE subscription (
    id text,
    account_id text,
    contract_end_date text,
    contract_start_date text,
    end_date text,
    external_id text,
    line_item_acv text,
    maintenance_status text,
    product_name text,
    start_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE touchpoint_collection (
    id text,
    account_id text,
    contacts text,
    created text,
    creator text,
    external_id text,
    internal_users text,
    last_updated text,
    participant_roles text,
    reasons text,
    success_flow text,
    touchpoint_subject text,
    touchpoint_type text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE task_collection (
    id text,
    account_id text,
    assignee text,
    assigner text,
    complete_date text,
    created text,
    due_date text,
    external_id text,
    flow text,
    last_updated text,
    objective_category text,
    objective_created_by text,
    objective_created_date text,
    objective_description text,
    objective_end_date text,
    objective_id text,
    objective_instance_id text,
    objective_last_updated_by text,
    objective_last_updated_date text,
    objective_name text,
    objective_start_date text,
    objective_status text,
    origin text,
    priority text,
    "status" text,
    successplay_description text,
    successplay_due_date text,
    successplay_flow text,
    successplay_id text,
    successplay_instance_id text,
    successplay_name text,
    successplay_owner text,
    successplay_team_id text,
    title text,
    updated_by text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE event_informed (
    informed text,
    event_id text,
    PRIMARY KEY (informed, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event_participant (
    participant text,
    event_id text,
    PRIMARY KEY (participant, event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    account_id text,
    properties_activity_type_id text,
    is_new text,
    note_content_note_id text,
    note_content_text text,
    note_content_totango_user_name text,
    properties_campaign_description text,
    properties_campaign_id text,
    properties_campaign_schedule_type text,
    properties_campaign_sent_by text,
    properties_campaign_template_image_uid text,
    properties_campaign_type text,
    properties_creation_time text,
    properties_customers_visibility text,
    properties_description text,
    properties_meeting_type text,
    properties_name text,
    properties_origin text,
    properties_parent_id text,
    properties_run_timestamp text,
    properties_send_to_internal text,
    properties_start_date text,
    properties_subject text,
    properties_targeted_users_count text,
    timestamps text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (properties_activity_type_id) REFERENCES activity_type(id)
);

CREATE TABLE account_assignment (
    id text,
    account_executive text,
    ace_service_manager_1 text,
    ace_service_manager_2 text,
    ace_service_manager_3 text,
    ace_service_named_consultant_1 text,
    ace_service_named_consultant_2 text,
    ace_service_named_consultant_3 text,
    customer_success_engineer text,
    customer_success_manager text,
    insight_frontline_contact_1 text,
    insight_frontline_contact_2 text,
    insight_frontline_contact_3 text,
    insight_manager_1 text,
    insight_manager_2 text,
    insight_manager_3 text,
    insight_named_consultant_1 text,
    insight_named_consultant_2 text,
    insight_named_consultant_3 text,
    "name" text,
    onboarding_specialist text,
    product_specialist text,
    renewal_rep text,
    totango_opportunity_created_by text,
    totango_opportunity_owner text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    account_type text,
    cancellation_date text,
    ci_360_url text,
    company_contract_value text,
    company_domain text,
    company_size text,
    contract_renewal_date text,
    contract_start_date text,
    contract_status text,
    create_date text,
    customer_portal_account_name text,
    eligible_success_plan_incentive_amount text,
    escalation_status text,
    first_activity_date text,
    forecast_amount text,
    forecast_by text,
    forecast_contract_value text,
    forecast_due_date text,
    forecast_period text,
    forecast_state text,
    health text,
    health_last_change text,
    health_rank text,
    industry text,
    last_activity_date text,
    last_contract_value_change_date text,
    last_payment_date text,
    licenses text,
    multidimensional_health_account_rank text,
    multidimensional_health_account_score text,
    "name" text,
    next_payment_due_date text,
    ofid text,
    outstanding_balance text,
    parent_id text,
    payment_method_expiration_date text,
    portal_shared_date text,
    previous_health_rank text,
    product_id text,
    risk_reason text,
    risk_status text,
    satisfaction_score text,
    ticket_volume text,
    tier text,
    top_priority_satisfaction_score text,
    top_priority_ticket_volume text,
    top_priority_unsolved_tickets text,
    totango_opportunity_close_date text,
    totango_opportunity_name text,
    totango_opportunity_stage text,
    totango_opportunity_type text,
    totango_opportunity_value text,
    trial_expiration_date text,
    unsolved_tickets text,
    PRIMARY KEY (id)
);

CREATE TABLE success_planning (
    id text,
    account_id text,
    comments text,
    critical_tickets text,
    entry_date text,
    external_id text,
    metric_label_1 text,
    metric_label_2 text,
    metric_value_1 text,
    metric_value_2 text,
    mttr text,
    uptime text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE support_ticket (
    id text,
    account_id text,
    account_name text,
    archived_by text,
    assignee text,
    channel text,
    created_date text,
    csat_score text,
    escalated text,
    external_id text,
    from_intercom text,
    missed_sla text,
    next_reply_target text,
    reporter text,
    severity text,
    "status" text,
    subject text,
    support_level text,
    support_team text,
    ticket_link text,
    time_to_resolution text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE activity_type (
    id text,
    calculate_metric text,
    default_type text,
    disabled text,
    display_name text,
    icon_class text,
    metric_name text,
    num_of_activities_assign_to text,
    system_type text,
    PRIMARY KEY (id)
);

CREATE TABLE touchpoint_event (
    id text,
    account_id text,
    properties_activity_type_id text,
    alert_content_description text,
    alert_content_duration text,
    alert_content_health text,
    alert_content_sentiment text,
    alert_content_type text,
    enriched_users jsonb,
    is_new text,
    properties_activity_type_id_is_modified text,
    properties_actual_effort_is_modified text,
    properties_automation_id text,
    properties_contain_formatting text,
    properties_customers_visibility text,
    properties_entity_id text,
    properties_entity_name text,
    properties_entity_type text,
    properties_estimated_effort_is_modified text,
    properties_form_id text,
    properties_is_associated_with_user text,
    properties_job_id text,
    properties_name text,
    properties_origin text,
    properties_request_type text,
    properties_request_url text,
    properties_status text,
    properties_title text,
    task_content_action text,
    task_content_assignee_current text,
    task_content_assignee_is_modified text,
    task_content_assigner_current text,
    task_content_assigner_is_modified text,
    task_content_description_current text,
    task_content_description_is_modified text,
    task_content_due_date_current text,
    task_content_due_date_is_modified text,
    task_content_last_updater_current text,
    task_content_last_updater_is_modified text,
    task_content_origin text,
    task_content_priority_current text,
    task_content_priority_is_modified text,
    task_content_status_current text,
    task_content_status_is_modified text,
    task_content_task_id text,
    timestamps text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (properties_activity_type_id) REFERENCES activity_type(id)
);

CREATE TABLE team_member (
    id text,
    team_id text,
    username text,
    homepage text,
    is_admin text,
    is_auto_generated text,
    is_default text,
    role_id text,
    PRIMARY KEY (id, team_id),
    FOREIGN KEY (team_id) REFERENCES team(id),
    FOREIGN KEY (username) REFERENCES users(id)
);

CREATE TABLE team_role_setting (
    id text,
    team_id text,
    can_edit_portfolio text,
    default_portfolio_account_types jsonb,
    default_portfolio_data jsonb,
    default_portfolio_selection text,
    role_id text,
    PRIMARY KEY (id, team_id),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE TABLE team (
    id text,
    color text,
    default_manager_role_id text,
    default_role_id text,
    description text,
    display_name text,
    extended_account_selection text,
    extended_search_enabled text,
    extended_terms jsonb,
    goal text,
    icon text,
    include_entire_hierarchy text,
    member_terms text,
    service_default_team text,
    service_id text,
    team_type_id text,
    terms jsonb,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id text,
    account_id text,
    ambassador_program_member text,
    bounced_campaign_date text,
    bounced_campaign_reason text,
    business_review_csat text,
    business_review_csat_comment text,
    business_review_csat_response_date text,
    campaign_custom text,
    campaign_onboarding_welcome text,
    campaign_outreach text,
    campaign_unsubscribe text,
    contact text,
    contact_account_role text,
    contact_address text,
    contact_organization text,
    contact_phone text,
    country text,
    crm_contact text,
    csat_score text,
    csat_score_comment text,
    csat_score_response_date text,
    device text,
    display_name text,
    email text,
    email_opt_out text,
    emergency text,
    first_activity_time text,
    first_name text,
    high_business_review_csat_reasons text,
    high_csat_score_reasons text,
    high_nps_response_reasons text,
    high_onboarding_completion_csat_survey_reasons text,
    high_onboarding_csat_score_reasons text,
    high_onboarding_midpoint_csat_survey_reasons text,
    high_relationship_nps_reasons text,
    high_training_csat_reasons text,
    in_app_welcome text,
    intercom_unsubscribe text,
    is_online text,
    key_contact text,
    language_preference_list text,
    last_activity_time text,
    last_campaign_sent text,
    last_name text,
    last_reference_date text,
    low_business_review_csat_reasons text,
    low_csat_score_reasons text,
    low_nps_response_reasons text,
    low_onboarding_completion_csat_survey_reasons text,
    low_onboarding_csat_score_reasons text,
    low_onboarding_midpoint_csat_survey_reasons text,
    low_relationship_nps_reasons text,
    low_training_csat_reasons text,
    marketing_unsubscribe text,
    "name" text,
    nps_feedback_category text,
    nps_response text,
    nps_response_comment text,
    nps_response_date text,
    onboarding_completion_csat_survey text,
    onboarding_completion_csat_survey_comment text,
    onboarding_completion_csat_survey_response_date text,
    onboarding_csat_score text,
    onboarding_csat_score_comment text,
    onboarding_csat_score_response_date text,
    onboarding_midpoint_csat_survey text,
    onboarding_midpoint_csat_survey_comment text,
    onboarding_midpoint_csat_survey_response_date text,
    os text,
    product_user text,
    reference text,
    referenceability text,
    region text,
    relationship_nps text,
    relationship_nps_comment text,
    relationship_nps_response_date text,
    sfdc_contact text,
    simple_first_activity_time text,
    simple_last_activity_time text,
    status_c text,
    sunco_external_id text,
    super_region_test text,
    timezone text,
    title text,
    training_csat text,
    training_csat_comment text,
    training_csat_response_date text,
    user_created_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE opportunity_collection (
    id text,
    account_id text,
    acv_amount_usd text,
    archived_by text,
    close_date text,
    collection_id text,
    contract_end_date text,
    contract_start_date text,
    d_1_assigned text,
    d_1_assigned_email text,
    d_1_created_opportunity text,
    d_1_qso_approved_date_stage_2 text,
    d_1_qso_approver_stage_2_email text,
    d_1_qso_approver_stage_2_name text,
    d_1_qso_comments text,
    d_1_qso_status_stage text,
    d_1_source text,
    end_user_account text,
    external_id text,
    is_closed text,
    maintenance_end_date text,
    opportunity_acv text,
    opportunity_name text,
    opportunity_product_acv text,
    opportunity_product_tcv text,
    opportunity_tcv text,
    opportunity_url text,
    owner_name text,
    partner_opportunity text,
    pdr_likely_procurement text,
    primary_partner_account text,
    product_acv_amount_usd text,
    product_tcv_amount_usd text,
    repeat_type text,
    risk_level text,
    stage_name text,
    tcv_amount_usd text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE touchpoint_reason (
    id text,
    created_at text,
    created_by text,
    display_name text,
    updated_at text,
    updated_by text,
    used text,
    PRIMARY KEY (id)
);
