CREATE TABLE device_group (
    id text,
    device_id text,
    "name" text,
    PRIMARY KEY (id, device_id),
    FOREIGN KEY (device_id) REFERENCES device(device_id)
);

CREATE TABLE balance (
    date_time text,
    id text,
    employee_id text,
    end_balance_amount text,
    is_changed text,
    "name" text,
    point_balance_type_decimal_place_num text,
    point_balance_type_id text,
    point_balance_type_max_balance_amount text,
    point_balance_type_min_balance_amount text,
    point_balance_type_qualifier text,
    point_balance_type_starting_balance_amount text,
    start_balance_amount text,
    type_display_name text,
    type_name text,
    PRIMARY KEY (date_time, id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE device (
    device_id text,
    access_granted text,
    adjust_for_dst text,
    communication_type text,
    description text,
    detail text,
    device_qualifier text,
    device_type_id text,
    device_type_qualifier text,
    enabled text,
    firmware text,
    grantor text,
    id text,
    ip_address_id text,
    ip_address_qualifier text,
    location text,
    mac_address text,
    profile_name_id text,
    profile_name_qualifier text,
    serial_number text,
    time_zone_id text,
    time_zone_qualifier text,
    PRIMARY KEY (device_id)
);

CREATE TABLE time_card_as_manager_activity_segment (
    id text,
    employee_id text,
    accepted text,
    approved text,
    approved_by_employee text,
    comment_notes jsonb,
    concurrent_with_previous text,
    created_date_time text,
    data_source_id text,
    direct text,
    duration_date text,
    duration_in_seconds text,
    duration_order text,
    edit_by_type_id text,
    empty_transfer text,
    end_date_time text,
    event_type_id text,
    has_comments text,
    labor_account_id text,
    labor_categories jsonb,
    mismatched_results text,
    missing_results text,
    org_job_id text,
    reordered text,
    result_segments jsonb,
    start_date_time text,
    unit_id text,
    updated_date_time text,
    weight_value_amount text,
    wfa_trans_id text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_punch_comment_note (
    id text,
    employee_id text,
    time_card_as_manager_punch_id text,
    categories jsonb,
    comment_id text,
    comment_name text,
    notes jsonb,
    PRIMARY KEY (id, employee_id, time_card_as_manager_punch_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_punch(employee_id),
    FOREIGN KEY (time_card_as_manager_punch_id) REFERENCES time_card_as_manager_punch(id)
);

CREATE TABLE time_card_as_manager_punch (
    id text,
    employee_id text,
    attestation_edit text,
    cancel_deduct text,
    datasource_display_name text,
    datasource_functional_area_name text,
    datasource_id text,
    datasource_name text,
    deduct_rule_id text,
    deduct_rule_name text,
    dtm text,
    edit_by_type_id text,
    edit_by_type_name text,
    editable text,
    entered_on_dtm text,
    exception_resolved text,
    exceptions jsonb,
    from_phantom_edited text,
    has_comments text,
    is_phantom text,
    is_scheduled text,
    mark_related_exceptions_as_reviewed text,
    rounded_dtm text,
    timezone_id text,
    timezone_name text,
    type_override_description text,
    type_override_id text,
    type_override_name text,
    updated_on_dtm text,
    validate_as_timestamp text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_worked_shift_worked_span (
    id text,
    employee_id text,
    time_card_as_manager_worked_shift_id text,
    end_punch_id text,
    start_punch_id text,
    approvable_by_manager text,
    end_date_time text,
    from_schedule text,
    item_id text,
    primary_org_job_id text,
    primary_org_job_name text,
    primary_work_rule_id text,
    primary_work_rule_name text,
    projected text,
    rounded_end_date_time text,
    rounded_start_date_time text,
    scheduled_org_job text,
    scheduled_work_rule text,
    span_id text,
    start_date_time text,
    transfer_org_job text,
    transfer_work_rule text,
    user_entered_org_job text,
    user_entered_work_rule text,
    work_rule_id text,
    work_rule_name text,
    PRIMARY KEY (id, employee_id, time_card_as_manager_worked_shift_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_worked_shift(employee_id),
    FOREIGN KEY (time_card_as_manager_worked_shift_id) REFERENCES time_card_as_manager_worked_shift(id),
    FOREIGN KEY (end_punch_id) REFERENCES time_card_as_manager_punch(id),
    FOREIGN KEY (start_punch_id) REFERENCES time_card_as_manager_punch(id)
);

CREATE TABLE time_card_as_manager_worked_shift (
    id text,
    employee_id text,
    consolidated_schedule_segments text,
    end_date_time text,
    end_timezone_id text,
    end_timezone_name text,
    from_schedule text,
    in_progress text,
    projected text,
    rounded_end_date_time text,
    rounded_end_timezone_id text,
    rounded_start_date_time text,
    rounded_start_timezone_id text,
    scheduled_shift_ids jsonb,
    shift_total_hours text,
    start_date_time text,
    start_timezone_id text,
    start_timezone_name text,
    transaction_date_time text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_activity_team_membership (
    "index" text,
    employee_id text,
    created_date_time text,
    data_source_id text,
    edit_by_type_id text,
    end_date_time text,
    end_timezone_id text,
    end_timezone_qualifier text,
    soft_closed text,
    start_date_time text,
    start_timezone_id text,
    start_timezone_qualifier text,
    system_generated_end text,
    system_generated_end_timezone_id text,
    system_generated_end_timezone_qualifier text,
    team_id text,
    team_qualifier text,
    updated_date_time text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_activity_shift_worked_span (
    "index" text,
    employee_id text,
    work_shift_id text,
    activity_processed_segments jsonb,
    activity_segment_accepted text,
    activity_segment_activity jsonb,
    activity_segment_approved text,
    activity_segment_approved_by_employee text,
    activity_segment_comment_notes jsonb,
    activity_segment_concurrent_with_previous text,
    activity_segment_cost_center jsonb,
    activity_segment_created_date_time text,
    activity_segment_data_source_id text,
    activity_segment_direct text,
    activity_segment_duration_date text,
    activity_segment_duration_in_seconds text,
    activity_segment_duration_order text,
    activity_segment_edit_by_type_id text,
    activity_segment_employee jsonb,
    activity_segment_empty_transfer text,
    activity_segment_end_date_time text,
    activity_segment_end_timezone jsonb,
    activity_segment_event_type_id text,
    activity_segment_has_comments text,
    activity_segment_hours_allocated_type jsonb,
    activity_segment_id text,
    activity_segment_labor_account_id text,
    activity_segment_labor_categories jsonb,
    activity_segment_mismatched_results text,
    activity_segment_missing_results text,
    activity_segment_org_job jsonb,
    activity_segment_org_job_id text,
    activity_segment_reordered text,
    activity_segment_result_segments jsonb,
    activity_segment_start_date_time text,
    activity_segment_start_timezone jsonb,
    activity_segment_transaction_type jsonb,
    activity_segment_unit_id text,
    activity_segment_updated_date_time text,
    activity_segment_weight_value_amount text,
    activity_segment_wfa_trans_id text,
    activity_segment_work_rule jsonb,
    efficiencies_earned_seconds text,
    efficiencies_efficiency text,
    efficiencies_efficiency_quantity text,
    PRIMARY KEY ("index", employee_id, work_shift_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_activity_shift(employee_id),
    FOREIGN KEY (work_shift_id) REFERENCES time_card_as_manager_activity_shift(work_shift_id)
);

CREATE TABLE time_card_as_manager_activity_shift (
    work_shift_id text,
    employee_id text,
    shift_total_actual text,
    shift_total_allocated text,
    shift_total_variance text,
    PRIMARY KEY (work_shift_id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_pay_code_edit_entry (
    "index" text,
    employee_id text,
    time_card_as_manager_pay_code_edit_id text,
    labor_category_entry_description text,
    labor_category_entry_id text,
    labor_category_entry_name text,
    labor_category_id text,
    labor_category_name text,
    labor_category_order_num text,
    PRIMARY KEY ("index", employee_id, time_card_as_manager_pay_code_edit_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_pay_code_edit(employee_id),
    FOREIGN KEY (time_card_as_manager_pay_code_edit_id) REFERENCES time_card_as_manager_pay_code_edit(id)
);

CREATE TABLE time_card_as_manager_pay_code_edit (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    approvable_by_manager text,
    comments_available text,
    comments_notes jsonb,
    duration_in_hours text,
    edit_by_type_id text,
    editable text,
    end_date_time text,
    item_id text,
    labor_categories_labor_string text,
    labor_categories_reference_id text,
    org_job_id text,
    org_job_name text,
    pay_code_id text,
    pay_code_name text,
    phantom_spans jsonb,
    schedule_amount_type text,
    scheduled_shift_ids jsonb,
    start_date_time text,
    system_generated text,
    update_date text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_exception (
    id text,
    employee_id text,
    punch_event_id text,
    worked_shift_id text,
    apply_date text,
    comment_notes jsonb,
    end_date_time text,
    end_exception text,
    end_time_zone_id text,
    event_date text,
    exception_type_category text,
    exception_type_description text,
    exception_type_display_name text,
    exception_type_id text,
    exception_type_name text,
    is_excused_absence text,
    is_un_excused_absence text,
    justifications jsonb,
    justified_times jsonb,
    missing_time_status_display_name text,
    missing_time_status_id text,
    org_job_id text,
    over_limit_in_hours text,
    reviewed text,
    schedule_item_id text,
    schedule_item_schedule_punch_dtm text,
    start_date_time text,
    start_exception text,
    start_time_zone_id text,
    transfer text,
    violation_in_hours text,
    work_rule_id text,
    work_rule_name text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id),
    FOREIGN KEY (punch_event_id) REFERENCES time_card_as_manager_punch(id),
    FOREIGN KEY (worked_shift_id) REFERENCES time_card_as_manager_worked_shift(id)
);

CREATE TABLE time_card_as_manager_extended_exception (
    id text,
    employee_id text,
    punch_event_id text,
    actual_date_time text,
    apply_date text,
    comment_notes jsonb,
    comments text,
    end_date_time text,
    end_exception text,
    end_time_zone_id text,
    event_date text,
    exception_type_category text,
    exception_type_description text,
    exception_type_display_name text,
    exception_type_id text,
    exception_type_name text,
    is_excused_absence text,
    is_un_excused_absence text,
    justifications jsonb,
    justified_times jsonb,
    missing_time_status_display_name text,
    missing_time_status_id text,
    org_job_id text,
    over_limit_in_hours text,
    reviewed text,
    schedule_item_id text,
    schedule_item_schedule_punch_dtm text,
    scheduled_date_time text,
    start_date_time text,
    start_exception text,
    start_time_zone_id text,
    transfer text,
    violation_in_hours text,
    work_rule_id text,
    work_rule_name text,
    worked_shift_id text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id),
    FOREIGN KEY (punch_event_id) REFERENCES time_card_as_manager_punch(id)
);

CREATE TABLE time_card_as_manager_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    duration_in_days text,
    duration_in_hours text,
    from_shift text,
    time_item_id text,
    total_type text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_aggregated_total (
    "index" text,
    employee_id text,
    time_card_as_manager_total_index text,
    amount text,
    amount_type text,
    approvable_by_manager text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_category_id text,
    labor_category_name text,
    labor_category_transfer text,
    location_id text,
    location_name text,
    pay_code_id text,
    pay_code_name text,
    rate text,
    time_item_type jsonb,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY ("index", employee_id, time_card_as_manager_total_index),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_total(employee_id),
    FOREIGN KEY (time_card_as_manager_total_index) REFERENCES time_card_as_manager_total("index")
);

CREATE TABLE time_card_as_manager_total (
    "index" text,
    employee_id text,
    employee_context_timezone_id text,
    employee_context_timezone_name text,
    total_context_aggregation_type text,
    total_context_group_by_type text,
    total_context_type text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_activity_aggregated_total (
    "index" text,
    employee_id text,
    time_card_as_manager_activity_total_index text,
    amount text,
    amount_type text,
    approvable_by_manager text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_category_id text,
    labor_category_name text,
    labor_category_transfer text,
    location_id text,
    location_name text,
    pay_code_id text,
    pay_code_name text,
    rate text,
    time_item_type jsonb,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY ("index", employee_id, time_card_as_manager_activity_total_index),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_activity_total(employee_id),
    FOREIGN KEY (time_card_as_manager_activity_total_index) REFERENCES time_card_as_manager_activity_total("index")
);

CREATE TABLE time_card_as_manager_activity_total (
    "index" text,
    employee_id text,
    employee_context_timezone_id text,
    employee_context_timezone_name text,
    time_item_type jsonb,
    total_context_aggregation_type text,
    total_context_group_by_type text,
    total_context_type text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_last_update (
    "index" text,
    employee_id text,
    is_edited_in_signed_off text,
    update_by_person_full_name text,
    update_date_time text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_ota_segment (
    effective_date text,
    employee_id text,
    time_card_as_manager_ota_index text,
    approved_amount text,
    comment_count text,
    denied_amount text,
    ot_state_indicator text,
    overtime_detail_segments jsonb,
    pending_amount text,
    PRIMARY KEY (effective_date, employee_id, time_card_as_manager_ota_index),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_ota(employee_id),
    FOREIGN KEY (time_card_as_manager_ota_index) REFERENCES time_card_as_manager_ota("index")
);

CREATE TABLE time_card_as_manager_ota (
    "index" text,
    employee_id text,
    overtime_summary_approvals_count text,
    overtime_summary_denials_count text,
    overtime_summary_has_comments text,
    overtime_summary_has_pending text,
    overtime_summary_pending_count text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_daily_total_hours_cost_summary (
    id text,
    apply_date text,
    employee_id text,
    amount_type text,
    duration_in_days text,
    duration_in_hours text,
    from_shift text,
    time_item_id text,
    total_type text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, apply_date, employee_id),
    FOREIGN KEY (apply_date) REFERENCES time_card_as_manager_daily_total_summary(apply_date),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_daily_total_summary(employee_id)
);

CREATE TABLE time_card_as_manager_daily_total_summary (
    apply_date text,
    employee_id text,
    cumulative_total text,
    daily_total_amount_hour text,
    PRIMARY KEY (apply_date, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_item_total_summary (
    end_apply_date text,
    start_apply_date text,
    employee_id text,
    item_hours text,
    item_id text,
    PRIMARY KEY (end_apply_date, start_apply_date, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_schedule_shift_segment (
    "index" text,
    employee_id text,
    time_card_as_manager_schedule_shift_id text,
    end_date_time text,
    id text,
    labor_categories_labor_entry jsonb,
    labor_categories_labor_string text,
    labor_categories_reference_id text,
    org_job_ref_id text,
    org_job_ref_qualifier text,
    primary_labor_categories_labor_entry jsonb,
    primary_labor_categories_labor_string text,
    primary_labor_categories_reference_id text,
    primary_org_job_ref_id text,
    primary_org_job_ref_qualifier text,
    primary_work_rule_qualifier text,
    primary_work_rule_ref_id text,
    segment_type_ref_id text,
    segment_type_ref_qualifier text,
    skill_cert_profile_refs jsonb,
    start_date_time text,
    transfer_cost_center text,
    transfer_labor_categories text,
    transfer_org_job text,
    transfer_work_rule text,
    "type" text,
    user_entered_cost_center text,
    user_entered_org_job text,
    user_entered_work_rule text,
    work_rule_ref_id text,
    work_rule_ref_qualifier text,
    PRIMARY KEY ("index", employee_id, time_card_as_manager_schedule_shift_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_schedule_shift(employee_id),
    FOREIGN KEY (time_card_as_manager_schedule_shift_id) REFERENCES time_card_as_manager_schedule_shift(id)
);

CREATE TABLE time_card_as_manager_schedule_shift (
    id text,
    employee_id text,
    allow_inactive_position text,
    by_pass_position_selection text,
    comment_notes jsonb,
    deleted text,
    element_type text,
    end_date_time text,
    event_date text,
    generated text,
    locked text,
    modified_date_time text,
    on_call_shift text,
    opens text,
    posted text,
    posted_notification_pending text,
    relations jsonb,
    self_serviced text,
    start_date_time text,
    version text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_processed_segment (
    id text,
    employee_id text,
    apply_date text,
    duration_in_days text,
    duration_in_seconds text,
    end_date_time text,
    in_progress text,
    item_id text,
    labor_account_id text,
    labor_categories_labor_entry jsonb,
    labor_categories_labor_string text,
    labor_categories_reference_id text,
    money_amount text,
    order_number text,
    org_job_apply_date text,
    org_job_id text,
    org_job_name text,
    pay_code_id text,
    pay_code_name text,
    projected text,
    rounded_end_date_time text,
    rounded_start_date_time text,
    segment_type_id text,
    start_date_time text,
    work_rule_id text,
    work_rule_name text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_scheduled_aggregated_total (
    "index" text,
    employee_id text,
    time_card_as_manager_scheduled_total_index text,
    amount text,
    amount_type text,
    approvable_by_manager text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_category_id text,
    labor_category_name text,
    labor_category_transfer text,
    location_id text,
    location_name text,
    pay_code_id text,
    pay_code_name text,
    rate text,
    time_item_type jsonb,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY ("index", employee_id, time_card_as_manager_scheduled_total_index),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_scheduled_total(employee_id),
    FOREIGN KEY (time_card_as_manager_scheduled_total_index) REFERENCES time_card_as_manager_scheduled_total("index")
);

CREATE TABLE time_card_as_manager_scheduled_total (
    "index" text,
    employee_id text,
    employee_context_timezone_id text,
    employee_context_timezone_name text,
    total_context_total_aggregation_type text,
    total_context_total_group_by_type text,
    total_context_total_type text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_work_holiday_credit (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    duration_in_hours text,
    editable text,
    end_date_time text,
    holiday_display_name text,
    schedule_amount_type text,
    start_date_time text,
    system_generated text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager_over_time_info_segment (
    "index" text,
    effective_date text,
    employee_id text,
    time_card_as_manager_over_time_info_index text,
    amount text,
    apply_date text,
    end_date_time text,
    overtime_detail_segments jsonb,
    start_date_time text,
    work_item_id text,
    PRIMARY KEY ("index", effective_date, employee_id, time_card_as_manager_over_time_info_index),
    FOREIGN KEY (effective_date) REFERENCES time_card_as_manager_over_time_info(effective_date),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager_over_time_info(employee_id),
    FOREIGN KEY (time_card_as_manager_over_time_info_index) REFERENCES time_card_as_manager_over_time_info("index")
);

CREATE TABLE time_card_as_manager_over_time_info (
    effective_date text,
    "index" text,
    employee_id text,
    approval_segments jsonb,
    approved_amount text,
    comment_count text,
    denied_amount text,
    ot_state_indicator text,
    pending_amount text,
    PRIMARY KEY (effective_date, "index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES time_card_as_manager(employee_id)
);

CREATE TABLE time_card_as_manager (
    employee_id text,
    employee_name text,
    has_move_amounts text,
    has_pending_changes text,
    historical_corrections jsonb,
    hours_worked jsonb,
    missing_time_groups jsonb,
    move_amounts jsonb,
    start_date timestamp,
    totalization_status text,
    PRIMARY KEY (employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE manager (
    person_number text,
    aoid text,
    badge_number text,
    coid text,
    effective_date text,
    effective_time text,
    employee_key text,
    global_id text,
    person_key text,
    request_item_id text,
    supervisor_number text,
    supervisor_person_number text,
    user_key text,
    username text,
    PRIMARY KEY (person_number)
);

CREATE TABLE employee (
    id text,
    employment_status text,
    first_name text,
    last_name text,
    number text,
    user_account_status text,
    PRIMARY KEY (id)
);

CREATE TABLE schedule_pattern_item_shift_template_comment_note (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    comment_active text,
    comment_id text,
    comment_name text,
    comment_scheduling_comment_id text,
    id text,
    notes jsonb,
    scheduling_comment_note_id text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item(id)
);

CREATE TABLE schedule_pattern_item_shift_template_segment_tag (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    schedule_pattern_item_shift_template_segment_id text,
    color text,
    id text,
    tag_definition_ref_id text,
    tag_definition_ref_localized_qualifier text,
    tag_definition_ref_qualifier text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id, schedule_pattern_item_shift_template_segment_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item_shift_template_segment(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item_shift_template_segment(schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_item_shift_template_segment_id) REFERENCES schedule_pattern_item_shift_template_segment(id)
);

CREATE TABLE schedule_pattern_item_shift_template_segment_labor_category_entry (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    schedule_pattern_item_shift_template_segment_id text,
    entry_id text,
    entry_localized_qualifier text,
    entry_qualifier text,
    labor_category_id text,
    labor_category_localized_qualifier text,
    labor_category_qualifier text,
    scheduling_labor_category_entry_id text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id, schedule_pattern_item_shift_template_segment_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item_shift_template_segment(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item_shift_template_segment(schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_item_shift_template_segment_id) REFERENCES schedule_pattern_item_shift_template_segment(id)
);

CREATE TABLE schedule_pattern_item_shift_template_segment_profile (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    schedule_pattern_item_shift_template_segment_id text,
    id text,
    localized_qualifier text,
    qualifier text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id, schedule_pattern_item_shift_template_segment_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item_shift_template_segment(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item_shift_template_segment(schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_item_shift_template_segment_id) REFERENCES schedule_pattern_item_shift_template_segment(id)
);

CREATE TABLE schedule_pattern_item_shift_template_segment (
    id text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    cost_center_id text,
    cost_center_localized_qualifier text,
    cost_center_qualifier text,
    cost_center_reference_id text,
    cost_center_scheduling_cost_center_reference_id text,
    end_date_time text,
    labor_categories_labor_string text,
    labor_categories_reference_id text,
    labor_categories_scheduling_labor_categories_id text,
    order_number text,
    org_node_id text,
    org_node_localized_qualifier text,
    org_node_qualifier text,
    segment_type_id text,
    segment_type_localized_qualifier text,
    segment_type_qualifier text,
    start_date_time text,
    transfer_string text,
    work_rule_id text,
    work_rule_localized_qualifier text,
    work_rule_qualifier text,
    PRIMARY KEY (id, schedule_pattern_id, schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item(id)
);

CREATE TABLE schedule_pattern_item_availability_template_segment (
    id text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    availability_type_id text,
    availability_type_localized_qualifier text,
    availability_type_qualifier text,
    end_time text,
    from_pcet_template text,
    start_time text,
    PRIMARY KEY (id, schedule_pattern_id, schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item(id)
);

CREATE TABLE schedule_pattern_item_schedule_tag_template_comment_note (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    comment_active text,
    comment_id text,
    comment_name text,
    comment_scheduling_comment_id text,
    id text,
    notes jsonb,
    scheduling_comment_note_id text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item(id)
);

CREATE TABLE schedule_pattern_item_schedule_tag_template_segment_labor_category_entry (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    schedule_pattern_item_schedule_tag_template_segment_id text,
    entry_id text,
    entry_localized_qualifier text,
    entry_qualifier text,
    labor_category_id text,
    labor_category_localized_qualifier text,
    labor_category_qualifier text,
    scheduling_labor_category_entry_id text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id, schedule_pattern_item_schedule_tag_template_segment_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item_schedule_tag_template_segment(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item_schedule_tag_template_segment(schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_item_schedule_tag_template_segment_id) REFERENCES schedule_pattern_item_schedule_tag_template_segment(id)
);

CREATE TABLE schedule_pattern_item_schedule_tag_template_segment (
    id text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    cost_center_id text,
    cost_center_localized_qualifier text,
    cost_center_qualifier text,
    cost_center_reference_id text,
    cost_center_scheduling_cost_center_reference_id text,
    labor_categories_labor_string text,
    labor_categories_reference_id text,
    labor_categories_scheduling_labor_categories_id text,
    org_job_id text,
    org_job_localized_qualifier text,
    org_job_qualifier text,
    schedule_tag_color text,
    segment_type_id text,
    segment_type_localized_qualifier text,
    segment_type_qualifier text,
    tag_definition_id text,
    tag_definition_localized_qualifier text,
    tag_definition_qualifier text,
    work_rule_id text,
    work_rule_localized_qualifier text,
    work_rule_qualifier text,
    PRIMARY KEY (id, schedule_pattern_id, schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item(id)
);

CREATE TABLE schedule_pattern_item_pay_code_edit_template_comment_note (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    comment_active text,
    comment_id text,
    comment_name text,
    comment_scheduling_comment_id text,
    id text,
    notes jsonb,
    scheduling_comment_note_id text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item(id)
);

CREATE TABLE schedule_pattern_item_pay_code_edit_template_labor_category_entry (
    "index" text,
    schedule_pattern_id text,
    schedule_pattern_item_id text,
    entry_id text,
    entry_localized_qualifier text,
    entry_qualifier text,
    labor_category_id text,
    labor_category_localized_qualifier text,
    labor_category_qualifier text,
    scheduling_labor_category_entry_id text,
    PRIMARY KEY ("index", schedule_pattern_id, schedule_pattern_item_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern_item(schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_item_id) REFERENCES schedule_pattern_item(id)
);

CREATE TABLE schedule_pattern_item (
    id text,
    schedule_pattern_id text,
    availability_template_deleted text,
    availability_template_id text,
    availability_template_system_generated text,
    availability_template_version text,
    "day" text,
    pay_code_edit_template_code_id text,
    pay_code_edit_template_code_localized_qualifier text,
    pay_code_edit_template_code_qualifier text,
    pay_code_edit_template_cost_center_id text,
    pay_code_edit_template_cost_center_localized_qualifier text,
    pay_code_edit_template_cost_center_qualifier text,
    pay_code_edit_template_cost_center_reference_id text,
    pay_code_edit_template_cost_center_scheduling_cost_center_reference_id text,
    pay_code_edit_template_deleted text,
    pay_code_edit_template_duration_in_days text,
    pay_code_edit_template_duration_in_time text,
    pay_code_edit_template_end_date_time text,
    pay_code_edit_template_id text,
    pay_code_edit_template_labor_categories_labor_string text,
    pay_code_edit_template_labor_categories_reference_id text,
    pay_code_edit_template_labor_categories_scheduling_labor_categories_id text,
    pay_code_edit_template_locked text,
    pay_code_edit_template_money_amount text,
    pay_code_edit_template_name text,
    pay_code_edit_template_org_job_id text,
    pay_code_edit_template_org_job_localized_qualifier text,
    pay_code_edit_template_org_job_qualifier text,
    pay_code_edit_template_override_accrual_amount text,
    pay_code_edit_template_start_date_time text,
    pay_code_edit_template_system_generated text,
    pay_code_edit_template_transfer_string text,
    pay_code_edit_template_version text,
    schedule_tag_template_deleted text,
    schedule_tag_template_end_date_time text,
    schedule_tag_template_id text,
    schedule_tag_template_start_date_time text,
    schedule_tag_template_system_generated text,
    schedule_tag_template_version text,
    shift_template_deleted text,
    shift_template_description text,
    shift_template_end_date_time text,
    shift_template_id text,
    shift_template_label text,
    shift_template_locked text,
    shift_template_name text,
    shift_template_start_date_time text,
    shift_template_system_generated text,
    shift_template_version text,
    PRIMARY KEY (id, schedule_pattern_id),
    FOREIGN KEY (schedule_pattern_id) REFERENCES schedule_pattern(id)
);

CREATE TABLE schedule_pattern (
    id text,
    anchor_start_day text,
    day_count text,
    deleted text,
    description text,
    modified_date_time text,
    "name" text,
    start_date text,
    system_generated text,
    time_period_type_id text,
    time_period_type_name text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_time_off_request_approval_period (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    pay_code_id text,
    duration text,
    end_date text,
    id text,
    overridden_shift_id text,
    start_date text,
    start_time text,
    symbolic_amount_id text,
    symbolic_amount_localized_qualifier text,
    symbolic_amount_qualifier text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request(id),
    FOREIGN KEY (pay_code_id) REFERENCES employee_accrual_remaining_balance(pay_code_id)
);

CREATE TABLE employee_time_off_request_comment_note (
    "index" text,
    create_date_time text,
    employee_time_off_request_comment_index text,
    employee_time_off_request_id text,
    data_source_display_name text,
    id text,
    text text,
    timestamps text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_comment_index, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request_comment(create_date_time),
    FOREIGN KEY (employee_time_off_request_comment_index) REFERENCES employee_time_off_request_comment("index"),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request_comment(employee_time_off_request_id)
);

CREATE TABLE employee_time_off_request_comment (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    comment_active text,
    comment_id text,
    comment_name text,
    id text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request(id)
);

CREATE TABLE employee_time_off_request_next_valid_status (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    id text,
    "name" text,
    symbolic_id text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request(id)
);

CREATE TABLE employee_time_off_request_period (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    pay_code_id text,
    duration text,
    end_date text,
    overridden_shift_id text,
    start_date text,
    start_time text,
    symbolic_amount_id text,
    symbolic_amount_localized_qualifier text,
    symbolic_amount_qualifier text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request(id),
    FOREIGN KEY (pay_code_id) REFERENCES employee_accrual_remaining_balance(pay_code_id)
);

CREATE TABLE employee_time_off_request_position_detail_primary_job (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    employee_time_off_request_position_detail_index text,
    effective_date text,
    expiration_date text,
    labor_account_id text,
    primary_job text,
    primary_job_color text,
    primary_labour_account text,
    primary_labour_category text,
    primary_organization_id text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id, employee_time_off_request_position_detail_index),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request_position_detail(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request_position_detail(employee_time_off_request_id),
    FOREIGN KEY (employee_time_off_request_position_detail_index) REFERENCES employee_time_off_request_position_detail("index")
);

CREATE TABLE employee_time_off_request_position_detail (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    accessible text,
    id text,
    "name" text,
    order_entry_order_number text,
    order_entry_primary text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request(id)
);

CREATE TABLE employee_time_off_request_request_status_change (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    change_date_time text,
    from_status_id text,
    from_status_name text,
    from_status_symbolic_id text,
    manager_comment_notes jsonb,
    person_name text,
    to_status_id text,
    to_status_name text,
    to_status_symbolic_id text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request(id)
);

CREATE TABLE employee_time_off_request_approval_history_reviewer (
    create_date_time text,
    employee_time_off_request_id text,
    "index" text,
    employee_id text,
    approval_step text,
    approver text,
    full_name text,
    PRIMARY KEY (create_date_time, employee_time_off_request_id, "index"),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_time_off_request_approval_info_current_reviewer (
    "index" text,
    create_date_time text,
    employee_time_off_request_id text,
    employee_id text,
    approver text,
    full_name text,
    PRIMARY KEY ("index", create_date_time, employee_time_off_request_id),
    FOREIGN KEY (create_date_time) REFERENCES employee_time_off_request(create_date_time),
    FOREIGN KEY (employee_time_off_request_id) REFERENCES employee_time_off_request(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_time_off_request (
    create_date_time text,
    id text,
    employee_id text,
    approval_info_current_reviewers_approval_step text,
    approval_info_pending_steps text,
    approval_info_request_id text,
    create_open_shifts_excluded_on jsonb,
    creator_id text,
    creator_localized_qualifier text,
    creator_qualifier text,
    current_status_id text,
    current_status_name text,
    current_status_symbolic_id text,
    employee_localized_qualifier text,
    historical text,
    overridden_shifts jsonb,
    position_id text,
    position_localized_qualifier text,
    position_qualifier text,
    recipient_id text,
    recipient_position_id text,
    request_description text,
    request_id text,
    request_localized_description text,
    request_localized_name text,
    request_name text,
    request_symbol text,
    PRIMARY KEY (create_date_time, id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE device_status (
    id text,
    device_id text,
    access_granted text,
    action_metrics_error_count text,
    action_metrics_pending_count text,
    action_metrics_success_count text,
    adjust_for_dst text,
    communication_type text,
    description text,
    device_metrics_punch_count text,
    device_metrics_punches_processed text,
    device_metrics_uncollected_biometric_templates text,
    device_metrics_uncollected_transactions text,
    enabled text,
    firmware text,
    grantor text,
    last_action_created_date_time text,
    last_action_error_message text,
    last_action_name text,
    last_action_status text,
    last_action_updated_date_time text,
    location text,
    serial_number text,
    status_details_firmware_status text,
    status_details_last_communication_time text,
    status_details_state text,
    status_details_status text,
    PRIMARY KEY (id),
    FOREIGN KEY (device_id) REFERENCES device(device_id)
);

CREATE TABLE time_off_request_manager_approval_info_reviewer (
    "index" text,
    time_off_request_manager_id text,
    approver text,
    employee_id text,
    full_name text,
    person_number text,
    PRIMARY KEY ("index", time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager(id)
);

CREATE TABLE time_off_request_manager_comment_note_detail (
    "index" text,
    time_off_request_manager_comment_note_index text,
    time_off_request_manager_id text,
    comment_note_id text,
    data_source_display_name text,
    id text,
    scheduling_note_id text,
    text text,
    time_stamp text,
    PRIMARY KEY ("index", time_off_request_manager_comment_note_index, time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_comment_note_index) REFERENCES time_off_request_manager_comment_note("index"),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager_comment_note(time_off_request_manager_id)
);

CREATE TABLE time_off_request_manager_comment_note (
    "index" text,
    time_off_request_manager_id text,
    comment_active text,
    comment_id text,
    id text,
    scheduling_comment_id text,
    scheduling_comment_note_id text,
    PRIMARY KEY ("index", time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager(id)
);

CREATE TABLE time_off_request_manager_position_detail_primary_job (
    "index" text,
    time_off_request_manager_id text,
    time_off_request_manager_position_detail_index text,
    effective_date text,
    expiration_date text,
    labor_account_id text,
    primary_job text,
    primary_job_color text,
    primary_labour_account text,
    primary_labour_category text,
    primary_organization_id text,
    PRIMARY KEY ("index", time_off_request_manager_id, time_off_request_manager_position_detail_index),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager_position_detail(time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_position_detail_index) REFERENCES time_off_request_manager_position_detail("index")
);

CREATE TABLE time_off_request_manager_position_detail (
    "index" text,
    time_off_request_manager_id text,
    id text,
    "name" text,
    order_entry_number text,
    order_entry_primary text,
    PRIMARY KEY ("index", time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager(id)
);

CREATE TABLE time_off_request_manager_valid_status (
    "index" text,
    time_off_request_manager_id text,
    id text,
    "name" text,
    symbolic_id text,
    PRIMARY KEY ("index", time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager(id)
);

CREATE TABLE time_off_request_manager_period (
    "index" text,
    time_off_request_manager_id text,
    duration text,
    end_date text,
    overridden_shifts jsonb,
    pay_code_id text,
    pay_code_localized_qualifier text,
    pay_code_qualifier text,
    start_date text,
    start_time text,
    symbolic_amount_id text,
    symbolic_amount_localized_qualifier text,
    symbolic_amount_qualifier text,
    PRIMARY KEY ("index", time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager(id)
);

CREATE TABLE time_off_request_manager_approval_period (
    "index" text,
    time_off_request_manager_id text,
    duration text,
    end_date text,
    overridden_shifts jsonb,
    pay_code_id text,
    pay_code_localized_qualifier text,
    pay_code_qualifier text,
    start_date text,
    start_time text,
    symbolic_amount_id text,
    symbolic_amount_localized_qualifier text,
    symbolic_amount_qualifier text,
    PRIMARY KEY ("index", time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager(id)
);

CREATE TABLE time_off_request_manager_request_change_comment_note (
    "index" text,
    time_off_request_manager_id text,
    time_off_request_manager_request_change_index text,
    comment_active text,
    comment_categories jsonb,
    comment_id text,
    comment_name text,
    id text,
    notes jsonb,
    PRIMARY KEY ("index", time_off_request_manager_id, time_off_request_manager_request_change_index),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager_request_change(time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_request_change_index) REFERENCES time_off_request_manager_request_change("index")
);

CREATE TABLE time_off_request_manager_request_change (
    "index" text,
    time_off_request_manager_id text,
    change_date_time text,
    from_status_id text,
    from_status_name text,
    from_status_symbolic_id text,
    person_name text,
    to_status_id text,
    to_status_name text,
    to_status_symbolic_id text,
    PRIMARY KEY ("index", time_off_request_manager_id),
    FOREIGN KEY (time_off_request_manager_id) REFERENCES time_off_request_manager(id)
);

CREATE TABLE time_off_request_manager (
    id text,
    employee_id text,
    approval_info_current_reviewers_approval_step text,
    approval_info_history jsonb,
    approval_info_modified_date_time text,
    approval_info_pending_steps text,
    approval_info_request_id text,
    create_date_time text,
    create_open_shifts_excluded_on jsonb,
    current_status_id text,
    current_status_name text,
    current_status_symbolic_id text,
    employee_localized_qualifier text,
    historical text,
    on_behalf_of_mgr_id text,
    overridden_shifts jsonb,
    position_id text,
    position_localized_qualifier text,
    position_qualifier text,
    recipient_position_id text,
    request_sub_type_description text,
    request_sub_type_id text,
    request_sub_type_localized_description text,
    request_sub_type_localized_name text,
    request_sub_type_name text,
    request_sub_type_symbol text,
    request_type_description text,
    request_type_id text,
    request_type_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_accrual_remaining_day_balance (
    balance_date text,
    "index" text,
    "date" text,
    employee_accrual_remaining_balance_index text,
    pay_code_id text,
    available_balance_in_days text,
    available_balance_in_money text,
    available_balance_in_seconds text,
    probationary_balance_in_days text,
    probationary_balance_in_money text,
    probationary_balance_in_seconds text,
    vested_balance_in_days text,
    vested_balance_in_money text,
    vested_balance_in_seconds text,
    PRIMARY KEY (balance_date, "index", "date", employee_accrual_remaining_balance_index, pay_code_id),
    FOREIGN KEY ("date") REFERENCES employee_accrual_remaining_balance("date"),
    FOREIGN KEY (employee_accrual_remaining_balance_index) REFERENCES employee_accrual_remaining_balance("index"),
    FOREIGN KEY (pay_code_id) REFERENCES employee_accrual_remaining_balance(pay_code_id)
);

CREATE TABLE employee_accrual_remaining_balance (
    "date" text,
    "index" text,
    pay_code_id text,
    accrual_code_id text,
    accrual_code_qualifier text,
    PRIMARY KEY ("date", "index", pay_code_id)
);

CREATE TABLE employee_time_card_muster_report_daily_data (
    id text,
    employee_id text,
    "date" text,
    error text,
    "status" text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_absence_exception (
    id text,
    employee_id text,
    is_excused_absence text,
    is_unexcused_absence text,
    position_id text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_contact_total (
    id text,
    employee_id text,
    actual_total_approval_status text,
    actual_total_approved_managers text,
    amount_type text,
    apply_date text,
    apply_work_week text,
    approving_manager_ids text,
    approving_manager_names text,
    approving_managers jsonb,
    combined text,
    contributing_days_of_week jsonb,
    cost_center_id text,
    cost_center_reference_id text,
    days_amount text,
    days_amount_1 text,
    end_date text,
    hours_amount text,
    hours_amount_1 text,
    is_from_correction text,
    job_id text,
    job_transfer text,
    labor_categories jsonb,
    labor_transfer text,
    manager_approval_needed text,
    pay_code_id text,
    pay_period_number text,
    pay_period_week text,
    position_id text,
    signed_off text,
    start_date text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_1 text,
    wages_1_amount text,
    wages_1_currency_code text,
    wages_amount text,
    wages_currency_code text,
    work_week_apply_date_time text,
    work_week_apply_short_date text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_averaging (
    id text,
    employee_id text,
    actual_amount text,
    actual_through_selected_day_hours text,
    actual_through_selected_day_hours_minus_averaging_target_hours text,
    amount text,
    amount_from text,
    averaging_target_hours_minus_actual_through_selected_day_hours text,
    avg_reporting_period text,
    date_pattern_type text,
    end_date text,
    include_in_averaging_dataview text,
    position_id text,
    projected_hours text,
    start_date text,
    target_amount text,
    target_through_selected_day_hours text,
    variance text,
    variance_actual_hours_minus_target_through_selected_day_hours text,
    variance_projected_hours_minus_target_hours text,
    variance_target_hours_minus_actual_through_selected_day_hours text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_exception_count (
    id text,
    employee_id text,
    count text,
    exception_type_category text,
    exception_type_description text,
    exception_type_display_name text,
    exception_type_id text,
    exception_type_name text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_exception_count_auto_resolved (
    id text,
    employee_id text,
    count text,
    exception_type_category text,
    exception_type_description text,
    exception_type_display_name text,
    exception_type_id text,
    exception_type_name text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_exception_count_manager_justified (
    id text,
    employee_id text,
    count text,
    exception_type_category text,
    exception_type_description text,
    exception_type_display_name text,
    exception_type_id text,
    exception_type_name text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_exception_count_employee_justified (
    id text,
    employee_id text,
    count text,
    exception_type_category text,
    exception_type_description text,
    exception_type_display_name text,
    exception_type_id text,
    exception_type_name text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_exception_count_unreviewed (
    id text,
    employee_id text,
    count text,
    exception_type_category text,
    exception_type_description text,
    exception_type_display_name text,
    exception_type_id text,
    exception_type_name text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_actual_total_correction (
    id text,
    employee_id text,
    actual_total_approval_status text,
    actual_total_approved_managers text,
    amount_type text,
    apply_date text,
    apply_work_week text,
    approving_manager_ids text,
    approving_manager_names text,
    approving_managers jsonb,
    combined text,
    contributing_days_of_week jsonb,
    cost_center_id text,
    cost_center_reference_id text,
    days_amount text,
    days_amount_1 text,
    end_date text,
    hours_amount text,
    hours_amount_1 text,
    is_from_correction text,
    job_id text,
    job_transfer text,
    labor_categories jsonb,
    labor_transfer text,
    manager_approval_needed text,
    pay_code_id text,
    pay_period_number text,
    pay_period_week text,
    position_id text,
    signed_off text,
    start_date text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_1 text,
    wages_1_amount text,
    wages_1_currency_code text,
    wages_amount text,
    wages_currency_code text,
    work_week_apply_date_time text,
    work_week_apply_short_date text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_muster_report_summary (
    id text,
    employee_id text,
    count text,
    description text,
    "status" text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_ftpt_all_data (
    "index" text,
    employee_id text,
    average_all_weekly_hours text,
    hours_worked text,
    number_of_all_weeks text,
    pay_code_id text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_ftpt_data (
    "index" text,
    employee_id text,
    average_all_weekly_hours text,
    average_worked_weekly_hours text,
    hours_worked text,
    number_of_all_weeks text,
    number_of_worked_weeks text,
    pay_code_id text,
    PRIMARY KEY ("index", employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_scheduled_total (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    hours_amount text,
    is_from_correction text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_categories_entry jsonb,
    labor_categories_reference_id text,
    labor_categories_string text,
    labor_transfer text,
    pay_code_id text,
    pay_code_name text,
    pay_period_number text,
    signed_off text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_projected_total (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    hours_amount text,
    is_from_correction text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_categories_entry jsonb,
    labor_categories_reference_id text,
    labor_categories_string text,
    labor_transfer text,
    pay_code_id text,
    pay_code_name text,
    pay_period_number text,
    signed_off text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_exclude_correction (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    hours_amount text,
    is_from_correction text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_categories_entry jsonb,
    labor_categories_reference_id text,
    labor_categories_string text,
    labor_transfer text,
    pay_code_id text,
    pay_code_name text,
    pay_period_number text,
    signed_off text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_project_total_correction (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    hours_amount text,
    is_from_correction text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_categories_entry jsonb,
    labor_categories_reference_id text,
    labor_categories_string text,
    labor_transfer text,
    pay_code_id text,
    pay_code_name text,
    pay_period_number text,
    signed_off text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_shift_contract_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    hours_amount text,
    is_from_correction text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_categories_entry jsonb,
    labor_categories_reference_id text,
    labor_categories_string text,
    labor_transfer text,
    pay_code_id text,
    pay_code_name text,
    pay_period_number text,
    signed_off text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_grouped_hours_total (
    id text,
    employee_id text,
    actual_total_approval_status text,
    actual_total_approved_managers text,
    amount_type text,
    apply_date text,
    apply_work_week text,
    approving_manager_ids text,
    approving_manager_names text,
    approving_managers jsonb,
    combined text,
    contributing_days_of_week jsonb,
    cost_center_id text,
    cost_center_reference_id text,
    days_amount text,
    days_amount_1 text,
    end_date text,
    hours_amount text,
    hours_amount_1 text,
    is_from_correction text,
    job_id text,
    job_transfer text,
    labor_categories jsonb,
    labor_transfer text,
    manager_approval_needed text,
    pay_code_id text,
    pay_period_number text,
    pay_period_week text,
    position_id text,
    signed_off text,
    start_date text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_1 text,
    wages_1_amount text,
    wages_1_currency_code text,
    wages_amount text,
    wages_currency_code text,
    work_week_apply_date_time text,
    work_week_apply_short_date text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_actual_total (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    hours_amount text,
    is_from_correction text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_categories_entry jsonb,
    labor_categories_reference_id text,
    labor_categories_string text,
    labor_transfer text,
    pay_code_id text,
    pay_code_name text,
    pay_period_number text,
    signed_off text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_actual_total_exclude_correction (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    hours_amount text,
    is_from_correction text,
    job_id text,
    job_name text,
    job_transfer text,
    labor_categories_entry jsonb,
    labor_categories_reference_id text,
    labor_categories_string text,
    labor_transfer text,
    pay_code_id text,
    pay_code_name text,
    pay_period_number text,
    signed_off text,
    wage_addition text,
    wage_multiplier text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_shift_scheduled_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    duration_in_hours text,
    job_id text,
    job_name text,
    pay_code_id text,
    pay_code_name text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_shift_projected_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    duration_in_hours text,
    job_id text,
    job_name text,
    pay_code_id text,
    pay_code_name text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_shift_actual_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    duration_in_hours text,
    job_id text,
    job_name text,
    pay_code_id text,
    pay_code_name text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_daily_scheduled_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    duration_in_hours text,
    job_id text,
    job_name text,
    pay_code_id text,
    pay_code_name text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_daily_projected_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    duration_in_hours text,
    job_id text,
    job_name text,
    pay_code_id text,
    pay_code_name text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_daily_actual_total_summary (
    id text,
    employee_id text,
    amount_type text,
    apply_date text,
    combined text,
    days_amount text,
    duration_in_hours text,
    job_id text,
    job_name text,
    pay_code_id text,
    pay_code_name text,
    wages text,
    wages_currency_amount text,
    wages_currency_code text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_accrual_transaction (
    id text,
    employee_id text,
    accrual_code_allow_edit text,
    accrual_code_amount_type text,
    accrual_code_hours_per_day_in_seconds text,
    accrual_code_id text,
    accrual_code_name text,
    accrual_code_shortname text,
    accrual_code_type_id text,
    accrual_code_type_name text,
    carry_forward_hours_amount text,
    disqualified text,
    effective_date text,
    excluded text,
    from_transition text,
    grant_hours_amount text,
    hours_amount text,
    limit_hours_amount text,
    original_hours_amount text,
    probation_hours_amount text,
    probation_seconds_amount text,
    seconds_amount text,
    spceded_by_reset text,
    suspended text,
    system_generated_num text,
    to_person_name text,
    to_person_qualifier text,
    "type" text,
    type_str text,
    update_datetm text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card_accrual_daily_summary (
    "index" text,
    employee_id text,
    employee_time_card_accrual_summary_id text,
    available_balance_days text,
    balance_date text,
    current_balance_date text,
    current_balance_probation_days_amount text,
    current_balance_vested_days_amount text,
    earned_to_date_days text,
    pending_grant_days text,
    planned_taking_days text,
    reporting_period text,
    taking_to_date_days text,
    PRIMARY KEY ("index", employee_id, employee_time_card_accrual_summary_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card_accrual_summary(employee_id),
    FOREIGN KEY (employee_time_card_accrual_summary_id) REFERENCES employee_time_card_accrual_summary(id)
);

CREATE TABLE employee_time_card_accrual_reporting_period_summary (
    "index" text,
    employee_id text,
    employee_time_card_accrual_summary_id text,
    ending_balance_date text,
    ending_balance_probation_days_amount text,
    ending_balance_vested_days_amount text,
    opening_balance_date text,
    opening_balance_probation_days_amount text,
    opening_balance_vested_days_amount text,
    prior_ending_balance_date text,
    prior_ending_balance_probation_days_amount text,
    prior_ending_balance_vested_days_amount text,
    reporting_period_span text,
    PRIMARY KEY ("index", employee_id, employee_time_card_accrual_summary_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card_accrual_summary(employee_id),
    FOREIGN KEY (employee_time_card_accrual_summary_id) REFERENCES employee_time_card_accrual_summary(id)
);

CREATE TABLE employee_time_card_accrual_summary (
    id text,
    employee_id text,
    accrual_code_allow_edit text,
    accrual_code_hours_per_day text,
    accrual_code_hours_per_day_in_seconds text,
    accrual_code_id text,
    accrual_code_name text,
    accrual_code_shortname text,
    accrual_code_typeid text,
    accrual_code_typename text,
    effective_date_range jsonb,
    end_date_time text,
    start_date_time text,
    starting_balance_for_period_balance_date text,
    starting_balance_for_period_probation_days_amount text,
    starting_balance_for_period_probation_duration_in_seconds text,
    starting_balance_for_period_probation_hours_amount text,
    starting_balance_for_period_vested_days_amount text,
    starting_balance_for_period_vested_duration_in_seconds text,
    starting_balance_for_period_vested_hours_amount text,
    PRIMARY KEY (id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee_time_card(employee_id)
);

CREATE TABLE employee_time_card (
    employee_id text,
    absence_exception_employee_id text,
    employee_name text,
    is_excused_absence text,
    is_unexcused_absence text,
    PRIMARY KEY (employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (absence_exception_employee_id) REFERENCES employee(id)
);

CREATE TABLE perfect_attendance_transaction (
    apply_date_time text,
    id text,
    employee_id text,
    point_transaction_employee_id text,
    "name" text,
    perfect_attendance_definition_id text,
    perfect_attendance_definition_qualifier text,
    point_transaction_apply_date_time text,
    point_transaction_balance_change text,
    point_transaction_decimal_place_num text,
    point_transaction_id text,
    point_transaction_name text,
    policy_definition_detail_label text,
    policy_definition_id text,
    policy_definition_qualifier text,
    type_display_name text,
    type_name text,
    PRIMARY KEY (apply_date_time, id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (point_transaction_employee_id) REFERENCES employee(id)
);
