CREATE TABLE education (
    id text,
    employee_id text,
    employment_id text,
    begin_date text,
    country text,
    end_date text,
    gpa text,
    is_graduate text,
    is_highest_level text,
    "level" text,
    major text,
    minor text,
    school text,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employment_id) REFERENCES employment(id)
);

CREATE TABLE employee_security_user (
    employee_id text,
    user_id text,
    last_logon text,
    password_last_changed text,
    PRIMARY KEY (employee_id, user_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id)
);

CREATE TABLE pay_register (
    id text,
    company_id text,
    employee_id text,
    employment_id text,
    location_id text,
    organization_level_1_id text,
    organization_level_2_id text,
    organization_level_3_id text,
    organization_level_4_id text,
    pay_group text,
    annual_salary double precision,
    auto_allocate text,
    bonus_total_hours text,
    bonus_total_ot_hours text,
    check_add_mode text,
    check_amount text,
    currency_code text,
    direct_deposit_amount text,
    document_number text,
    earning_tax_reporting_type text,
    employee_status text,
    hourly_pay_rate text,
    is_regular_pay_for_cumulative text,
    is_voided text,
    is_voiding_record text,
    job_code text,
    last_regular_pay_date text,
    name_first text,
    name_last text,
    name_middle text,
    name_suffix text,
    net_amount text,
    original_pay_period_frequency text,
    pay_date text,
    pay_period_frequency text,
    project text,
    reconcile_date text,
    reconciled text,
    sequence_number text,
    shift text,
    ssn text,
    state_sui text,
    sui_gross text,
    tax_calculation_group_id text,
    tax_calculation_sequence text,
    total_deduction_amount text,
    total_earnings_amount text,
    total_hours text,
    total_hours_worked text,
    total_shift_amount text,
    total_tax_amount text,
    void_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employment_id) REFERENCES employment(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (organization_level_1_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_2_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_3_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_4_id) REFERENCES organization_level(id),
    FOREIGN KEY (pay_group) REFERENCES pay_group(pay_group)
);

CREATE TABLE earning_history_base_element (
    _fivetran_id text,
    company_id text,
    earning_id text,
    employee_id text,
    employment_id text,
    job_id text,
    location_id text,
    pay_group text,
    accrual_code text,
    base_amount text,
    batch_id text,
    calculation_rule text,
    calculation_sequence text,
    current_amount text,
    current_hours text,
    gen_number text,
    gl_base_segment_id text,
    gl_follow_base_account_allocation text,
    gross_up text,
    gross_up_target text,
    gross_up_tax_calculation_method text,
    hourly_pay_rate text,
    include_in_deferred_compensation text,
    include_in_deferred_compensation_hours text,
    is_voided text,
    is_voiding_record text,
    job_premium_amount text,
    job_premium_rate_or_percent text,
    number_of_days text,
    number_of_games text,
    pay_date text,
    pay_rate text,
    pay_sheet_id text,
    payout_rate_type text,
    period_control text,
    period_pay_rate text,
    piece_count text,
    piece_pay_rate text,
    plan_year text,
    project text,
    report_category text,
    tax_calculation_group_id text,
    tax_category text,
    time_clock_code text,
    tip_credit text,
    tip_gross_receipts text,
    tip_type text,
    use_deduction_off_set text,
    ytd_amount text,
    ytd_shift_amount text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (earning_id) REFERENCES earning(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employment_id) REFERENCES employee(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (pay_group) REFERENCES pay_group(pay_group)
);

CREATE TABLE phone_number_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_phone_number(key_value)
);

CREATE TABLE platform_config_phone_number (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES employee(id)
);

CREATE TABLE contact (
    id text,
    employee_id text,
    home_phone_number text,
    address_id text,
    address_is_different_from_employee text,
    city text,
    cobra_notes text,
    country_code text,
    county text,
    death_date text,
    divorce_date text,
    gender text,
    health_care_id text,
    home_phone_id text,
    import_id text,
    is_active text,
    is_beneficiary text,
    is_dependent text,
    is_disabled text,
    is_emergency_contact text,
    is_smoker text,
    is_student text,
    marriage_date text,
    name_suffix text,
    national_id text,
    national_id_expiration_date text,
    notes text,
    occupation text,
    other_insurance text,
    other_phone_country_code text,
    other_phone_id text,
    other_phone_number text,
    other_phone_type text,
    person_id text,
    preferred_phone_number text,
    relationship_code text,
    relationship_description text,
    row_last_changed text,
    ssn text,
    "state" text,
    status_as_of_date text,
    user_defined_field_0_1 text,
    work_phone_extension text,
    work_phone_id text,
    work_phone_number text,
    zip_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (home_phone_number) REFERENCES phone_number(number)
);

CREATE TABLE person_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_person(key_value)
);

CREATE TABLE platform_config_person (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES employee(id)
);

CREATE TABLE employee_multiple_job (
    company_id text,
    employee_id text,
    job_id text,
    annual_pay_rate text,
    date_in_job text,
    hourly_pay_rate text,
    is_in_active text,
    is_primary_job text,
    other_rate_1 text,
    other_rate_2 text,
    other_rate_3 text,
    other_rate_4 text,
    piece_pay_rate text,
    PRIMARY KEY (company_id, employee_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (job_id) REFERENCES job(id)
);

CREATE TABLE employee_status (
    company_id text,
    employee_id text,
    as_of_date text,
    is_primary text,
    is_primary_effective_date text,
    original_hire_date text,
    "status" text,
    status_reason text,
    status_reason_desc text,
    status_start_date text,
    trigger_termination text,
    PRIMARY KEY (company_id, employee_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE job_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_job(key_value)
);

CREATE TABLE platform_config_job (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES job(id)
);

CREATE TABLE org_level_4_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_org_level_4(key_value)
);

CREATE TABLE platform_config_org_level_4 (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES organization_level(id)
);

CREATE TABLE org_level_3_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_org_level_3(key_value)
);

CREATE TABLE platform_config_org_level_3 (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES organization_level(id)
);

CREATE TABLE org_level_2_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_org_level_2(key_value)
);

CREATE TABLE platform_config_org_level_2 (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES organization_level(id)
);

CREATE TABLE org_level_1_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_org_level_1(key_value)
);

CREATE TABLE platform_config_org_level_1 (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES organization_level(id)
);

CREATE TABLE organization_reporting_category (
    id text,
    code text,
    description text,
    "level" text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_demographic (
    employee_id text,
    user_id text,
    integration_record_id text,
    PRIMARY KEY (employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id)
);

CREATE TABLE users (
    id text,
    employee_id text,
    user_last_logon_date text,
    user_last_password_change_date text,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employment_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_employment(key_value)
);

CREATE TABLE platform_config_employment (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value)
);

CREATE TABLE general_ledger (
    _fivetran_id text,
    company_code text,
    job_id text,
    organization_level_1_id text,
    organization_level_2_id text,
    organization_level_3_id text,
    organization_level_4_id text,
    pay_group text,
    account_type text,
    base_segment text,
    block_id text,
    co_id text,
    credit_amt text,
    debit_amt text,
    description text,
    general_ledger_account text,
    gl_json text,
    gl_run_date_time text,
    job_desc text,
    location text,
    pay_period_end_date text,
    pay_period_start_date text,
    period_end_date text,
    period_start_date text,
    position_code text,
    position_desc text,
    project text,
    run_id text,
    system_id text,
    total_nr_of_blocks text,
    user_who_ran_this_gl text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (company_code) REFERENCES company(code),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (organization_level_1_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_2_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_3_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_4_id) REFERENCES organization_level(id),
    FOREIGN KEY (pay_group) REFERENCES pay_group(pay_group)
);

CREATE TABLE national_document (
    id text,
    contact_id text,
    employee_id text,
    employment_id text,
    date_time_changed text,
    date_time_created text,
    description text,
    document_code text,
    document_number text,
    issue_date text,
    issuing_country_code text,
    issuing_place text,
    PRIMARY KEY (id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employment_id) REFERENCES employment(id)
);

CREATE TABLE pay_group (
    id text,
    allow_web_pyrl_after_ye_recon text,
    audit_key text,
    bring_in_payroll_batch_load text,
    bring_in_ppi_load text,
    bring_in_retro_pay_load text,
    combine_nacha_file_name text,
    combine_nacha_file_override text,
    date_time_changed text,
    date_time_created text,
    date_time_fiscal_end_done text,
    date_time_period_closed text,
    date_time_period_opened text,
    fiscal_year_end text,
    instant_check_move_rule text,
    is_active text,
    is_cts_created text,
    is_period_closed text,
    is_qtdob_per_control text,
    is_ytdob_per_control text,
    lmw_active text,
    monthly_pay_period_number text,
    mqy_end_flag text,
    notes text,
    ob_type text,
    pay_date text,
    pay_date_seq text,
    pay_group text,
    payroll_change_flags text,
    payroll_state_id text,
    payroll_transition_flags text,
    period_control text,
    period_end_date text,
    period_start_date text,
    period_type text,
    roe_pay_date text,
    susp_auto_pay text,
    susp_direct_deposit text,
    tax_arrears_collect_enabled text,
    tx_fil_app_date_time text,
    tx_fil_app_user_id text,
    user_id_changed text,
    user_id_created text,
    PRIMARY KEY (id)
);

CREATE TABLE phone_number (
    id text,
    employee_id text,
    audit_key text,
    country_code text,
    country_prefix text,
    extension text,
    is_private text,
    number text,
    type_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE dependent_deduction (
    id text,
    company_id text,
    contact_id text,
    employee_id text,
    benefit_amount text,
    benefit_start_date text,
    benefit_status text,
    benefit_status_date text,
    benefit_stop_date text,
    certificate_no text,
    code text,
    current_co_id text,
    date_time_changed text,
    date_time_created text,
    declined_by_carrier text,
    declined_by_carrier_date text,
    declined_by_carrier_reason text,
    dep_b_plan_tv_id text,
    eoi_date text,
    is_benefit_waived text,
    need_eoi text,
    notes text,
    primary_care_physician text,
    primary_care_physician_id text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (contact_id) REFERENCES contact(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE "position" (
    id text,
    company_id text,
    job_id text,
    location_id text,
    pay_group_id text,
    alternate_title text,
    date_time_changed text,
    date_time_created text,
    effective_start_date text,
    effective_stop_date text,
    employee_type text,
    fund_id text,
    integration_record_id text,
    is_approved text,
    is_eligible_for_benefits text,
    is_prorated text,
    notes text,
    organization_level_code_1 text,
    organization_level_code_2 text,
    organization_level_code_3 text,
    organization_level_code_4 text,
    overstaffing_allowed text,
    project_code text,
    shift_group_code text,
    status_as_of_date text,
    status_code text,
    user_defined_field_0_1 text,
    user_defined_field_0_2 text,
    user_defined_field_0_3 text,
    user_defined_field_0_4_is_null text,
    user_defined_field_0_4_value text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (pay_group_id) REFERENCES pay_group(id)
);

CREATE TABLE job (
    id text,
    country_code text,
    eeo_category text,
    flsa_type_code text,
    groups text,
    is_active text,
    job_family_code text,
    long_description text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_supervisor (
    employee_id text,
    employment_id text,
    company_id text,
    supervisor_company_id text,
    supervisor_employee_id text,
    supervisor_employment_id text,
    supervisor_job_id text,
    supervisor_position_id text,
    supervisor_person_id text,
    PRIMARY KEY (employee_id, employment_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employment_id) REFERENCES employment(id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (supervisor_company_id) REFERENCES company(id),
    FOREIGN KEY (supervisor_employee_id) REFERENCES employee(id),
    FOREIGN KEY (supervisor_employment_id) REFERENCES employee(id),
    FOREIGN KEY (supervisor_job_id) REFERENCES job(id),
    FOREIGN KEY (supervisor_position_id) REFERENCES "position"(id)
);

CREATE TABLE position_report (
    _fivetran_id text,
    position_id text,
    date_time_changed text,
    date_time_created text,
    effective_start_date text,
    effective_stop_date text,
    reports_to_position_code text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (position_id) REFERENCES "position"(id)
);

CREATE TABLE organization_level (
    id text,
    "level" text,
    budget_group text,
    current_year_budget_fte text,
    current_year_budget_salary text,
    description text,
    gl_segment text,
    is_active text,
    last_year_budget_fte text,
    last_year_budget_salary text,
    level_description text,
    reporting_category text,
    PRIMARY KEY (id, "level")
);

CREATE TABLE "role" (
    id text,
    default_role text,
    default_role_terminated text,
    description text,
    "name" text,
    rol_bi text,
    PRIMARY KEY (id)
);

CREATE TABLE location_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_location(key_value)
);

CREATE TABLE platform_config_location (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES location(id)
);

CREATE TABLE international_employee_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_international_employee(key_value)
);

CREATE TABLE platform_config_international_employee (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value)
);

CREATE TABLE user_profile (
    user_id text,
    company_id text,
    employee_id text,
    filter_company_id text,
    filter_job_id text,
    filter_location_id text,
    filter_organization_level_1_id text,
    filter_organization_level_2_id text,
    filter_organization_level_3_id text,
    filter_organization_level_4_id text,
    filter_pay_group_id text,
    filter_supervisor_id text,
    home_company_id text,
    master_company_id text,
    role_id text,
    email text,
    filter_deduction_group_code text,
    filter_employee_type text,
    filter_full_time_or_part_time text,
    filter_project_code text,
    filter_salary_or_hourly text,
    filter_shift_code text,
    filter_status text,
    filter_tax_calculation_group_id text,
    first_name text,
    integration_user_key text,
    last_name text,
    user_name text,
    user_status text,
    work_phone text,
    PRIMARY KEY (user_id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (filter_company_id) REFERENCES company(id),
    FOREIGN KEY (filter_job_id) REFERENCES job(id),
    FOREIGN KEY (filter_location_id) REFERENCES location(id),
    FOREIGN KEY (filter_organization_level_1_id) REFERENCES organization_level(id),
    FOREIGN KEY (filter_organization_level_2_id) REFERENCES organization_level(id),
    FOREIGN KEY (filter_organization_level_3_id) REFERENCES organization_level(id),
    FOREIGN KEY (filter_organization_level_4_id) REFERENCES organization_level(id),
    FOREIGN KEY (filter_pay_group_id) REFERENCES pay_group(id),
    FOREIGN KEY (filter_supervisor_id) REFERENCES employee(id),
    FOREIGN KEY (home_company_id) REFERENCES company(id),
    FOREIGN KEY (master_company_id) REFERENCES company(id),
    FOREIGN KEY (role_id) REFERENCES "role"(id)
);

CREATE TABLE option_rate (
    _fivetran_id text,
    deduction_code text,
    benefit_option text,
    effective_date text,
    employee_rate text,
    employer_rate text,
    pay_frequency text,
    rate_stop_date text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (deduction_code) REFERENCES dependent_deduction(code)
);

CREATE TABLE pto_plan (
    _fivetran_id text,
    company_id text,
    employee_id text,
    earned text,
    earned_through_date text,
    pending_balance text,
    pending_move_date text,
    pto_plan text,
    reset text,
    taken text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE address_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_address(key_value)
);

CREATE TABLE platform_config_address (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES employee(id)
);

CREATE TABLE tax_group (
    id text,
    code text,
    country_code text,
    date_final_wages_paid text,
    date_month_reset text,
    date_quarter_reset text,
    date_year_reset text,
    deposit_frequency_code text,
    deposit_frequency_description text,
    description text,
    is_inactive text,
    is_not_paying_wages text,
    is_not_subject_to_soc_med_tax text,
    report_id text,
    type_description text,
    PRIMARY KEY (id)
);

CREATE TABLE company (
    id text,
    master_company_id text,
    tax_group_id text,
    address_city text,
    address_country text,
    address_county text,
    address_line_1 text,
    address_line_2 text,
    address_state text,
    address_zip_code text,
    code text,
    contract_number text,
    currency_code text,
    date_of_business_closure text,
    doing_business_as_name text,
    federal_tax_id text,
    gl_segment text,
    integration_record_id text,
    is_master_company text,
    "name" text,
    organization_level_1_label text,
    organization_level_2_label text,
    organization_level_3_label text,
    organization_level_4_label text,
    other_federal_tax_id text,
    phone_number text,
    phone_number_extension text,
    use_multiple_job_groups text,
    use_position_management text,
    PRIMARY KEY (id),
    FOREIGN KEY (master_company_id) REFERENCES company(id),
    FOREIGN KEY (tax_group_id) REFERENCES tax_group(id)
);

CREATE TABLE earning (
    id text,
    amount text,
    block_federal_income_tax text,
    block_local_income_tax text,
    block_state_income_tax text,
    calculation_rule text,
    country_code text,
    display_in_pay_data_entry text,
    excel_in_total_hours text,
    exempt_from_earned_income_hours text,
    flat_hours text,
    include_flsa_average_pay_rate text,
    include_in_accruals text,
    include_in_allocations text,
    include_in_benefit_hours text,
    include_in_deferred_compensation text,
    include_in_deferred_compensation_hours text,
    include_in_earning_accumulation text,
    include_in_health_care_hours text,
    include_in_hours_accumulation text,
    include_in_manual_check text,
    include_in_miscellaneous_earning_1 text,
    include_in_miscellaneous_earning_2 text,
    include_in_miscellaneous_earning_3 text,
    include_in_miscellaneous_earning_4 text,
    include_in_miscellaneous_earning_5 text,
    include_in_miscellaneous_earning_6 text,
    include_in_pension_accumulation text,
    include_in_registered_pension_plan text,
    include_in_registered_retirement_savings_plan text,
    include_in_retro_pay text,
    include_in_shift_diffrential text,
    include_in_union_dues text,
    include_in_union_dues_hours text,
    is_productive_time text,
    is_supplimental_wages text,
    long_description text,
    monthly_pay_period_1 text,
    monthly_pay_period_2 text,
    monthly_pay_period_3 text,
    monthly_pay_period_4 text,
    monthly_pay_period_5 text,
    notes text,
    reduce_regular_dollars text,
    reduce_regular_hours text,
    report_category text,
    schedule_supplemental text,
    stub_description text,
    tax_calculation_rule text,
    tax_category text,
    time_clock_code text,
    use_deduction_offset text,
    verification_type_code text,
    verification_type_description text,
    PRIMARY KEY (id)
);

CREATE TABLE contact_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_contact(key_value)
);

CREATE TABLE platform_config_contact (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES phone_number(id)
);

CREATE TABLE job_group (
    id text,
    country_code text,
    description text,
    notes text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_field_row (
    field_name text,
    key_value text,
    field_value text,
    PRIMARY KEY (field_name, key_value),
    FOREIGN KEY (key_value) REFERENCES platform_config_employee(key_value)
);

CREATE TABLE platform_config_employee (
    key_value text,
    class_name text,
    key_name text,
    PRIMARY KEY (key_value),
    FOREIGN KEY (key_value) REFERENCES employee(id)
);

CREATE TABLE insurance_rate (
    _fivetran_id text,
    deduction_code text,
    effective_date text,
    employee_rate_non_smoker_female text,
    employee_rate_non_smoker_male text,
    employee_rate_non_smoker_not_specified text,
    employee_rate_smoker_female text,
    employee_rate_smoker_male text,
    employee_rate_smoker_not_specified text,
    employer_rate_non_smoker_female text,
    employer_rate_non_smoker_male text,
    employer_rate_non_smoker_not_specified text,
    employer_rate_smoker_female text,
    employer_rate_smoker_male text,
    employer_rate_smoker_not_specified text,
    maximum_age text,
    minimum_age text,
    pay_frequency text,
    stop_date text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (deduction_code) REFERENCES dependent_deduction(code)
);

CREATE TABLE payroll_deduction_history (
    record_id text,
    company_id text,
    employee_id text,
    allow_partial_deduction text,
    batch_id text,
    benefit_amount text,
    benefit_option text,
    benefit_provider text,
    check_id text,
    child_support_type text,
    current_arrears_amount text,
    custom_amount_1 text,
    custom_amount_2 text,
    custom_date text,
    deduction_calculation_basis_amt text,
    deduction_code text,
    deduction_for_bonus_only text,
    deduction_plan_type text,
    deduction_type text,
    deferred_compensation_cap text,
    deferred_compensation_regular_cap text,
    dependent_record_id text,
    employee_calculaiton_rule text,
    employee_calculation_rate_or_percent text,
    employee_current_amount text,
    employee_deduction_last_paid text,
    employee_goal_amount text,
    employee_goal_rule text,
    employee_goal_to_date_amount text,
    employee_number text,
    employee_original_amount text,
    employer_annual_cap_calculation_rule text,
    employer_calculation_rate_or_percent text,
    employer_calculation_rule text,
    employer_current_amount text,
    employer_period_cap_calculation_rule text,
    exclude_from_workers_compensation text,
    general_ledger_expense_account text,
    general_ledger_pay_account text,
    is_401_k text,
    is_403_b text,
    is_408_k text,
    is_408_p text,
    is_457 text,
    is_457_b text,
    is_457_f text,
    is_501_c text,
    is_d_125 text,
    is_deduction_off_set text,
    is_deferred_compensation text,
    is_dependent_care text,
    is_housing text,
    is_non_qualified_plan text,
    is_prorated text,
    is_public_employee_retirement text,
    is_section_125 text,
    is_voided text,
    is_voiding_record text,
    pay_date text,
    pay_group text,
    payee_id text,
    period_control text,
    tax_calculation_group_id text,
    tax_category text,
    timeclock_code text,
    vendor text,
    wage_garnishment_additional_arrearage_amount text,
    wage_garnishment_allocate_as_arrears text,
    wage_garnishment_amount_exempt text,
    wage_garnishment_amount_exempt_from_levy text,
    wage_garnishment_amount_exemt_from_garn text,
    wage_garnishment_amount_subject_to_cs text,
    wage_garnishment_amount_subject_to_garnishment text,
    wage_garnishment_deduction_tax_category text,
    wage_garnishment_disposable_income text,
    wage_garnishment_minimum_wage_factor text,
    wage_garnishment_wage_code text,
    year_to_date_deferred_compensation_combined_amount text,
    PRIMARY KEY (record_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE compensation (
    _fivetran_id text,
    company_id text,
    employee_id text,
    pay_group text,
    primary_job_id text,
    annual_salary text,
    avg_pay_rate_cur_per text,
    bonus_total_hrs text,
    bonus_total_ot_hrs text,
    currency_code text,
    date_in_job text,
    date_last_paid text,
    date_last_worked text,
    date_of_last_salary_review text,
    date_of_next_salayr_review text,
    date_paid_thru text,
    distribution_center_code text,
    empl_status text,
    full_time_or_part_time_code text,
    hourly_pay_rate text,
    is_auto_allocated text,
    is_auto_paid text,
    is_highly_compensated text,
    is_multiple_job text,
    is_seasonal_worker text,
    job_change_reason_code text,
    job_group_code text,
    job_salary_grade text,
    job_title text,
    number_of_payments text,
    other_rate_1 text,
    other_rate_2 text,
    other_rate_3 text,
    other_rate_4 text,
    pay_group_description text,
    pay_period text,
    pay_period_pay_rate text,
    pay_scale_code text,
    performance_review_rating text,
    performance_review_type text,
    piece_pay_rate text,
    primary_shift_code text,
    primary_shift_group_code text,
    salary_or_hourly_code text,
    scheduled_annual_work_hours text,
    scheduled_full_time_equivalency text,
    scheduled_period_work_hours text,
    total_ann_salary text,
    weekly_hours text,
    weekly_pay_rate text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (pay_group) REFERENCES pay_group(pay_group),
    FOREIGN KEY (primary_job_id) REFERENCES job(id)
);

CREATE TABLE location (
    id text,
    address_line_1 text,
    address_line_2 text,
    city text,
    country_code text,
    description text,
    is_active text,
    location_gl_segment text,
    "state" text,
    zip_or_postal_code text,
    PRIMARY KEY (id)
);

CREATE TABLE employee_job_history (
    id text,
    company_id text,
    employee_id text,
    home_company_id text,
    job_id text,
    location_id text,
    organization_level_1_id text,
    organization_level_2_id text,
    organization_level_3_id text,
    organization_level_4_id text,
    pay_group_id text,
    supervisor_id text,
    annual_salary double precision,
    created_by_user_id text,
    date_time_created text,
    employee_status text,
    employee_type text,
    flsa_category text,
    full_time_or_part_time text,
    hourly_pay_rate text,
    integration_effective_date text,
    is_job_change text,
    is_orgchange text,
    is_outside_guidelines text,
    is_outside_range text,
    is_promotion text,
    is_rate_change text,
    is_system text,
    is_transfer text,
    is_viewable_by_employee text,
    job_effective_date text,
    job_group_code text,
    job_title text,
    notes text,
    number_of_payments text,
    other_rate_1 text,
    other_rate_2 text,
    other_rate_3 text,
    other_rate_4 text,
    pay_period_code text,
    pay_scale_code text,
    percent_change text,
    period_pay_rate text,
    piece_pay_rate text,
    position_code text,
    project_code text,
    reason_code text,
    salary_grade text,
    salary_or_hourly text,
    scheduled_annual_hours text,
    scheduled_full_time_equivalency text,
    scheduled_work_hours text,
    shift_code text,
    shift_group_code text,
    step_number text,
    supervisor_name_first text,
    supervisor_name_last text,
    supervisor_name_suffix text,
    supervisor_not_in_list text,
    union_local text,
    union_national text,
    use_pay_scales text,
    weekly_hours text,
    weekly_pay_rate text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (home_company_id) REFERENCES company(id),
    FOREIGN KEY (job_id) REFERENCES job(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (organization_level_1_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_2_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_3_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_4_id) REFERENCES organization_level(id),
    FOREIGN KEY (pay_group_id) REFERENCES pay_group(id),
    FOREIGN KEY (supervisor_id) REFERENCES employee(id)
);

CREATE TABLE employee_global_bank (
    id text,
    company_id text,
    employee_id text,
    employment_id text,
    pay_group text,
    account_number text,
    account_type text,
    account_type_description text,
    address_line_1 text,
    address_line_2 text,
    address_line_3 text,
    beneficiary_name text,
    branch text,
    city text,
    country text,
    country_code text,
    currency_code text,
    date_modified text,
    funding_method text,
    funding_method_description text,
    iban text,
    "name" text,
    postal_code text,
    request_code_1 text,
    request_code_2 text,
    request_code_3 text,
    request_label_1 text,
    request_label_2 text,
    request_label_3 text,
    requirement_1 text,
    requirement_2 text,
    requirement_3 text,
    "state" text,
    swift_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employment_id) REFERENCES employment(id),
    FOREIGN KEY (pay_group) REFERENCES pay_group(pay_group)
);

CREATE TABLE employee_global_localization_element (
    _fivetran_id text,
    company_id text,
    employee_id text,
    boolean_value text,
    created text,
    date_time_value text,
    effective text,
    field_id text,
    field_name text,
    numeric_value text,
    string_value text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee (
    id text,
    company_id text,
    additional_name_1 text,
    additional_name_2 text,
    address_city text,
    address_country text,
    address_county text,
    address_id text,
    address_is_on_tax_boundary text,
    address_latitude text,
    address_line_1 text,
    address_line_2 text,
    address_line_3 text,
    address_line_4 text,
    address_longitude text,
    address_sms text,
    address_state text,
    address_zip_code text,
    chk_cashing_inst_code text,
    cobra_export text,
    cobra_is_active text,
    cobra_notes text,
    cobra_reason text,
    cobra_status text,
    cobra_status_date text,
    community_broadcast_sms_code text,
    consent_electronic_w_2 text,
    consent_electronicw_2_pr text,
    date_deceased text,
    date_of_birth text,
    date_of_cobra_event text,
    date_of_cobra_export text,
    date_of_cobra_letter text,
    date_of_i_9_expiration text,
    date_time_changed text,
    date_time_created text,
    disability_type text,
    email_address text,
    email_address_alternate text,
    ethnic_description text,
    ethnic_id_code text,
    first_name text,
    former_name text,
    gender text,
    health_blood_type text,
    health_eyes text,
    health_hair text,
    health_height_feet text,
    health_height_inches text,
    health_last_donate_date text,
    health_weight text,
    home_phone text,
    home_phone_country text,
    home_phone_is_private text,
    i_9_alien_number text,
    i_9_doc_a text,
    i_9_doc_b text,
    i_9_doc_c text,
    i_9_verified text,
    i_9_visa_expiration_date text,
    i_9_visa_type text,
    i_9_work_auth text,
    is_disabled text,
    is_multi_pay_group text,
    is_smoker text,
    last_name text,
    last_name_not_same_as_ss_card text,
    marital_status_code text,
    middle_name text,
    military_branch_served text,
    military_era text,
    military_is_active_wartime_vet text,
    military_is_disabled_vet text,
    military_is_medal_vet text,
    military_is_oth_elig_vet text,
    military_is_oth_elig_vet_basis text,
    military_separation_date text,
    military_service text,
    name_former text,
    name_prefix_code text,
    name_suffix_code text,
    national_id text,
    national_id_country text,
    nationality_1 text,
    nationality_2 text,
    nationality_3 text,
    origin_country text,
    origin_location text,
    person_id text,
    preferred_name text,
    previous_ssn text,
    sms_approvals text,
    sms_pay_notification text,
    ssn text,
    ssn_is_suppressed text,
    user_name text,
    w_2_is_deceased text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE direct_deposit (
    id text,
    company_id text,
    employee_id text,
    account_is_inactive text,
    account_record_id text,
    account_type text,
    amount_or_percent text,
    country_code text,
    date_time_changed text,
    deposit_rule text,
    description text,
    direct_deposit_or_prenote text,
    employee_bank_id text,
    employee_bank_name text,
    employee_bank_routing_number text,
    employee_institution_number text,
    first_prenote_pay_date text,
    foreign_account_number text,
    foreign_account_number_type text,
    sequence_number text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_change (
    company_id text,
    employee_id text,
    employee_number text,
    organization_level_1_id text,
    organization_level_2_id text,
    organization_level_3_id text,
    organization_level_4_id text,
    supervisor_id text,
    work_location_id text,
    address_1 text,
    address_2 text,
    alternate_email_address text,
    alternate_job_title text,
    date_in_job text,
    date_of_last_hire text,
    empl_status_start_date text,
    full_time_or_part_time text,
    gender text,
    hire_date text,
    is_active text,
    job_code text,
    job_group_code text,
    language_code text,
    prefix text,
    project_code text,
    salary_or_hourly text,
    "status" text,
    suffix text,
    supervisor_name text,
    termination_date text,
    "type" text,
    user_integration_key text,
    work_phone text,
    zip_code text,
    PRIMARY KEY (company_id, employee_id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employee_number) REFERENCES employment(id),
    FOREIGN KEY (organization_level_1_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_2_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_3_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_4_id) REFERENCES organization_level(id),
    FOREIGN KEY (supervisor_id) REFERENCES employee(id),
    FOREIGN KEY (work_location_id) REFERENCES location(id)
);

CREATE TABLE employee_contract (
    _fivetran_id text,
    company_id text,
    employee_id text,
    contract_type_code text,
    date_time_created text,
    effective_date text,
    row_last_changed text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);

CREATE TABLE employee_pay_deduction_element (
    id text,
    company_id text,
    employee_id text,
    employment_id text,
    pay_group text,
    amount text,
    country text,
    end_date text,
    modified_date text,
    notes text,
    pay_deduction_description text,
    pay_deduction_id text,
    pay_deduction_name text,
    payment_or_deduction_indicator text,
    period_end_id text,
    period_end_name text,
    period_start_id text,
    period_start_name text,
    project text,
    recurring text,
    start_date text,
    task text,
    PRIMARY KEY (id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (employment_id) REFERENCES employment(id),
    FOREIGN KEY (pay_group) REFERENCES pay_group(pay_group)
);

CREATE TABLE employment (
    id text,
    company_id text,
    employee_id text,
    organization_level_1_id text,
    organization_level_2_id text,
    organization_level_3_id text,
    organization_level_4_id text,
    pay_group text,
    primary_job_id text,
    primary_work_location_id text,
    supervisor_id text,
    auto_allocate text,
    clock_code text,
    date_in_job text,
    date_last_pay_date_paid text,
    date_last_worked text,
    date_of_benefit_seniority text,
    date_of_early_retirement text,
    date_of_local_union text,
    date_of_national_union text,
    date_of_retirement text,
    date_of_seniority text,
    date_of_suspension text,
    date_of_termination text,
    date_paid_thru text,
    date_time_changed text,
    date_time_created text,
    deduction_group_code text,
    earning_group_code text,
    employee_status_code text,
    employee_type_code text,
    full_time_or_part_time_code text,
    hire_source text,
    is_auto_allocated text,
    is_autopaid text,
    is_multiple_job text,
    job_change_reason_code text,
    job_description text,
    job_group_code text,
    job_title text,
    language_code text,
    last_hire_date text,
    leave_reason_code text,
    mailstop text,
    ok_to_rehire text,
    original_hire_date text,
    pay_group_description text,
    pay_period text,
    planned_leave_reason text,
    position_code text,
    primary_project_code text,
    salary_or_hourly text,
    scheduled_annual_hrs text,
    scheduled_fte text,
    scheduled_work_hrs text,
    shift text,
    shift_group text,
    status_start_date text,
    supervisor_co_id text,
    supervisor_company_code text,
    supervisor_first_name text,
    supervisor_last_name text,
    term_reason text,
    term_type text,
    termination_reason_description text,
    time_clock_id text,
    union_local text,
    union_national text,
    weekly_hours text,
    work_phone_country text,
    work_phone_extension text,
    work_phone_number text,
    PRIMARY KEY (id, company_id),
    FOREIGN KEY (company_id) REFERENCES company(id),
    FOREIGN KEY (employee_id) REFERENCES employee(id),
    FOREIGN KEY (organization_level_1_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_2_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_3_id) REFERENCES organization_level(id),
    FOREIGN KEY (organization_level_4_id) REFERENCES organization_level(id),
    FOREIGN KEY (pay_group) REFERENCES pay_group(pay_group),
    FOREIGN KEY (primary_job_id) REFERENCES job(id),
    FOREIGN KEY (primary_work_location_id) REFERENCES location(id),
    FOREIGN KEY (supervisor_id) REFERENCES employee(id)
);
