CREATE TABLE inflow_receipt_item (
    id text,
    grn_code text,
    item_sku text,
    purchase_order_item_id text,
    additional_cost text,
    batch_code text,
    batch_dto text,
    detailed_quantity text,
    determine_expiry_from text,
    discount text,
    discount_percentage text,
    expirable text,
    expiry text,
    grn_expiry_tolerance text,
    item_type_image_url text,
    item_type_name text,
    item_type_page_url text,
    items_labelled text,
    manufacturing_date text,
    max_retail_price text,
    pending_quantity text,
    quantity text,
    rejected_quantity text,
    rejection_comment text,
    scan_identifier text,
    shelf_life text,
    "status" text,
    unit_price text,
    vendor_sku_code text,
    PRIMARY KEY (id, grn_code),
    FOREIGN KEY (grn_code) REFERENCES grn(code),
    FOREIGN KEY (item_sku) REFERENCES gate_pass_item_dto(item_type_sku),
    FOREIGN KEY (purchase_order_item_id) REFERENCES purchase_order_item(id)
);

CREATE TABLE grn_custom_field_value (
    "index" text,
    grn_code text,
    display_name text,
    field_name text,
    field_value jsonb,
    possible_value jsonb,
    required text,
    value_type text,
    PRIMARY KEY ("index", grn_code),
    FOREIGN KEY (grn_code) REFERENCES grn(code)
);

CREATE TABLE grn (
    code text,
    purchase_order_code text,
    asn_code text,
    created text,
    created_by text,
    facility text,
    purchase_order_approved text,
    purchase_order_vendor_code text,
    status_code text,
    total_quantity text,
    total_received_amount text,
    total_rejected_amount text,
    total_rejected_quantity text,
    vendor_invoice_date text,
    vendor_invoice_number text,
    PRIMARY KEY (code),
    FOREIGN KEY (purchase_order_code) REFERENCES purchase_order(code)
);

CREATE TABLE sale_order_custom_field_value (
    "index" text,
    sale_order_code text,
    display_name text,
    field_name text,
    field_value text,
    possible_value text,
    required text,
    value_type text,
    PRIMARY KEY ("index", sale_order_code),
    FOREIGN KEY (sale_order_code) REFERENCES sale_order(code)
);

CREATE TABLE sale_order_return (
    code text,
    sale_order_code text,
    action_code text,
    putaway_code text,
    return_invoice_code text,
    return_invoice_display_code text,
    shipping_provider text,
    status_code text,
    tracking_number text,
    "type" text,
    PRIMARY KEY (code, sale_order_code),
    FOREIGN KEY (sale_order_code) REFERENCES sale_order(code)
);

CREATE TABLE sale_order_item (
    id text,
    sale_order_code text,
    reverse_pickup_code text,
    shipping_address_id text,
    shipping_package_code text,
    alternate_facility_code text,
    batch_dto text,
    brand text,
    bundle_sku_code text,
    cancellable text,
    cancellation_reason text,
    cancelled_by_seller text,
    cash_on_delivery_charge text,
    central_gst_percentage text,
    channel_expiry_date text,
    channel_mfd text,
    channel_mrp text,
    channel_sale_order_item_code text,
    channel_vendor_batch_number text,
    code text,
    color text,
    combination_description text,
    combination_identifier text,
    country_of_origin text,
    created text,
    custom_field_value text,
    discount text,
    edit_address text,
    effective_tolerance text,
    expected_delivery_date text,
    facility_code text,
    facility_name text,
    gift_message text,
    gift_wrap text,
    gift_wrap_charge text,
    hsn_code text,
    image_url text,
    integrated_gst_percentage text,
    item text,
    item_detail_field text,
    item_detail_field_dto_list text,
    item_name text,
    item_sku text,
    max_retail_price text,
    on_hold text,
    packet_configurable text,
    packet_number text,
    page_url text,
    prepaid_amount text,
    replacement_sale_order_code text,
    reverse_pickable text,
    sale_order_item_alternate_id text,
    selling_price text,
    selling_price_without_taxes_and_discount text,
    shelf_code text,
    shipping_charge text,
    shipping_charge_tax_percentage text,
    shipping_method_charge text,
    shipping_method_code text,
    shipping_package_status text,
    "size" text,
    state_gst_percentage text,
    status_code text,
    store_credit text,
    tax_percentage text,
    tcs text,
    total_central_gst text,
    total_integrated_gst text,
    total_price text,
    total_state_gst text,
    total_union_territory_gst text,
    "type" text,
    uc_batch_code text,
    union_territory_gst_percentage text,
    updated text,
    voucher_code text,
    voucher_value text,
    PRIMARY KEY (id, sale_order_code),
    FOREIGN KEY (sale_order_code) REFERENCES sale_order(code),
    FOREIGN KEY (reverse_pickup_code) REFERENCES sale_order_return(code),
    FOREIGN KEY (shipping_address_id) REFERENCES sale_order_address(id),
    FOREIGN KEY (shipping_package_code) REFERENCES sale_order_shipping_package(code)
);

CREATE TABLE shipping_package_item (
    item_sku text,
    sale_order_shipping_package_code text,
    item_name text,
    quantity text,
    PRIMARY KEY (item_sku, sale_order_shipping_package_code),
    FOREIGN KEY (sale_order_shipping_package_code) REFERENCES sale_order_shipping_package(code)
);

CREATE TABLE sale_order_shipping_package (
    code text,
    sale_order_code text,
    actual_weight text,
    channel text,
    channel_shipment_code text,
    city text,
    collectable_amount text,
    collected_amount text,
    courier_status text,
    created text,
    custom_field_value text,
    customer text,
    delivered text,
    dispatched text,
    estimated_weight text,
    invoice text,
    invoice_code text,
    invoice_date text,
    invoice_display_code text,
    irn text,
    no_of_item text,
    payment_reconciled text,
    pod_code text,
    shipping_courier text,
    shipping_label_link text,
    shipping_manifest_code text,
    shipping_method text,
    shipping_package_type text,
    shipping_provider text,
    "status" text,
    tracking_number text,
    tracking_status text,
    updated text,
    PRIMARY KEY (code),
    FOREIGN KEY (sale_order_code) REFERENCES sale_order(code)
);

CREATE TABLE sale_order_address (
    id text,
    sale_order_code text,
    address_line_1 text,
    address_line_2 text,
    city text,
    country text,
    district text,
    email text,
    "name" text,
    phone text,
    pincode text,
    "state" text,
    "type" text,
    PRIMARY KEY (id, sale_order_code),
    FOREIGN KEY (sale_order_code) REFERENCES sale_order(code)
);

CREATE TABLE sale_order (
    code text,
    additional_info text,
    amount_paid text,
    billing_address_city text,
    billing_address_country text,
    billing_address_district text,
    billing_address_email text,
    billing_address_id text,
    billing_address_line_1 text,
    billing_address_line_2 text,
    billing_address_name text,
    billing_address_phone text,
    billing_address_pincode text,
    billing_address_state text,
    billing_address_type text,
    c_form_provided text,
    cancellable text,
    channel text,
    channel_processing_time text,
    cod text,
    created text,
    currency_code text,
    customer_code text,
    customer_gstin text,
    display_order_code text,
    display_order_date_time text,
    fulfillment_tat text,
    notification_email text,
    notification_mobile text,
    packet_configurable text,
    payment_detail text,
    payment_instrument text,
    payment_mode text,
    priority text,
    reverse_pickable text,
    sale_order_metadata jsonb,
    "source" text,
    "status" text,
    third_party_shipping text,
    total_discount text,
    total_shipping_charge text,
    transaction_id text,
    updated text,
    PRIMARY KEY (code)
);

CREATE TABLE gate_pass_item_dto (
    item_type_sku text,
    gate_pass_code text,
    inflow_receipt_code text,
    batch_dto text,
    central_gst_percentage text,
    compensation_cess_percentage text,
    gate_pass_item_id text,
    gate_pass_item_status text,
    hsn_code text,
    integrated_gst_percentage text,
    inventory_type text,
    item_code text,
    item_condition text,
    item_status text,
    item_type_image_url text,
    item_type_name text,
    item_type_page_url text,
    pending_quantity text,
    quantity text,
    reason text,
    received_quantity text,
    shelf_code text,
    state_gst_percentage text,
    tax_percentage text,
    total text,
    union_territory_gst_percentage text,
    unit_price text,
    PRIMARY KEY (item_type_sku, gate_pass_code),
    FOREIGN KEY (gate_pass_code) REFERENCES gate_pass(code),
    FOREIGN KEY (inflow_receipt_code) REFERENCES grn(code)
);

CREATE TABLE gate_pass (
    code text,
    created text,
    custom_field_value jsonb,
    gate_pass_order_code text,
    id text,
    invoice_code text,
    invoice_display_code text,
    purpose text,
    reference text,
    return_invoice_code text,
    return_invoice_display_code text,
    status_code text,
    to_party_name text,
    "type" text,
    updated text,
    username text,
    PRIMARY KEY (code)
);

CREATE TABLE inventory_snapshot (
    item_type_sku text,
    inventory text,
    inventory_blocked text,
    open_purchase text,
    open_sale text,
    pending_inventory_assessment text,
    pending_stock_transfer text,
    putaway_pending text,
    vendor_inventory text,
    virtual_inventory text,
    PRIMARY KEY (item_type_sku)
);

CREATE TABLE rto_sale_order_item (
    sku_code text,
    shipment_code text,
    sale_order_code text,
    channel_product_id text,
    courier_status text,
    inventory_type text,
    item_name text,
    marketplace_return_reason text,
    putaway_qc_comment text,
    sale_order_item_code text,
    tracking_status text,
    PRIMARY KEY (sku_code, shipment_code),
    FOREIGN KEY (shipment_code) REFERENCES sale_order_return(code),
    FOREIGN KEY (sale_order_code) REFERENCES sale_order(code)
);

CREATE TABLE purchase_order_custom_field_value (
    "index" text,
    purchase_order_id text,
    display_name text,
    field_name text,
    field_value jsonb,
    possible_value jsonb,
    required text,
    value_type text,
    PRIMARY KEY ("index", purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id)
);

CREATE TABLE purchase_order_item (
    id text,
    purchase_order_id text,
    item_sku text,
    asn_pending_quantity text,
    batch_group_code text,
    central_gst_percentage text,
    custom_field_value jsonb,
    determine_expiry_from text,
    discount text,
    discount_percentage text,
    expirable text,
    grn_expiry_tolerance text,
    integrated_gst_percentage text,
    item_type_custom_field jsonb,
    item_type_id text,
    logistic_charge text,
    max_retail_price text,
    pending_quantity text,
    quantity text,
    rejected_quantity text,
    shelf_life text,
    state_gst_percentage text,
    sub_total text,
    tax text,
    tax_percentage text,
    tax_type text,
    total text,
    total_central_gst text,
    total_integrated_gst text,
    total_state_gst text,
    total_union_territory_gst text,
    union_territory_gst_percentage text,
    unit_price text,
    PRIMARY KEY (id, purchase_order_id),
    FOREIGN KEY (purchase_order_id) REFERENCES purchase_order(id),
    FOREIGN KEY (item_sku) REFERENCES inventory_snapshot(item_type_sku)
);

CREATE TABLE purchase_order (
    id text,
    amended_purchase_order_code text,
    amendment_purchase_order_code text,
    code text,
    created text,
    created_by text,
    delivery_date text,
    expiry_date text,
    from_party text,
    inflow_receipts_count text,
    logistic_charge text,
    logistic_charges_division_method text,
    "name" text,
    party_address_dto_address_line_1 text,
    party_address_dto_address_line_2 text,
    party_address_dto_address_type text,
    party_address_dto_address_type_name text,
    party_address_dto_city text,
    party_address_dto_country_code text,
    party_address_dto_email text,
    party_address_dto_enabled text,
    party_address_dto_phone text,
    party_address_dto_pincode text,
    party_address_dto_state_code text,
    party_address_dto_state_name text,
    price_summary_currency_code text,
    price_summary_discount text,
    price_summary_logistic_charge text,
    price_summary_sub_total_before_taxes_and_discount text,
    price_summary_tax_on_sale text,
    price_summary_tcs_amount text,
    price_summary_total_amount text,
    price_summary_total_item text,
    rejection_reason text,
    status_code text,
    tcs_addition_enabled text,
    tcs_amount text,
    "type" text,
    vendor_agreement_name text,
    vendor_code text,
    vendor_id text,
    vendor_name text,
    PRIMARY KEY (id)
);

CREATE TABLE cir_sale_order_item (
    sku_code text,
    reverse_pickup_code text,
    sale_order_code text,
    shipment_code text,
    channel_product_id text,
    courier_status text,
    inventory_type text,
    item_name text,
    marketplace_return_reason text,
    putaway_qc_comment text,
    sale_order_item_code text,
    tracking_status text,
    PRIMARY KEY (sku_code, reverse_pickup_code),
    FOREIGN KEY (reverse_pickup_code) REFERENCES sale_order_return(code),
    FOREIGN KEY (sale_order_code) REFERENCES sale_order(code),
    FOREIGN KEY (shipment_code) REFERENCES sale_order_shipping_package(code)
);
