CREATE TABLE partner_contact_address (
    "index" text,
    partner_id text,
    address text,
    city text,
    country text,
    house_number text,
    house_number_suffix text,
    "name" text,
    postal_code text,
    "state" text,
    "type" text,
    PRIMARY KEY ("index", partner_id),
    FOREIGN KEY (partner_id) REFERENCES partner(id)
);

CREATE TABLE partner_tag (
    "index" text,
    partner_id text,
    tag_name text,
    PRIMARY KEY ("index", partner_id),
    FOREIGN KEY (partner_id) REFERENCES partner(id)
);

CREATE TABLE partner (
    id text,
    expo_id text,
    booth_number text,
    booth_size text,
    contact_coc_number text,
    contact_comments text,
    contact_company text,
    contact_company_fax text,
    contact_company_name text,
    contact_company_phone text,
    contact_company_website text,
    contact_department text,
    contact_dob text,
    contact_email text,
    contact_fax text,
    contact_first_initials text,
    contact_first_name text,
    contact_gender text,
    contact_id text,
    contact_job_function text,
    contact_last_name text,
    contact_last_name_prefix text,
    contact_nationality text,
    contact_phone_1 text,
    contact_phone_2 text,
    contact_reference text,
    contact_social_security_number text,
    contact_suffix text,
    contact_title text,
    contact_vat_number text,
    contact_website text,
    deleted text,
    license_download_url text,
    licenses jsonb,
    "name" text,
    registration_type_id text,
    registration_type_level text,
    registration_type_name text,
    registration_type_reference text,
    registration_url text,
    revision text,
    translation_id text,
    translation_iso text,
    translation_language text,
    translation_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (expo_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    contact_email text,
    description text,
    ends text,
    "name" text,
    reference text,
    revision text,
    "start" text,
    timezone text,
    PRIMARY KEY (id)
);

CREATE TABLE visitor_contact_address (
    "index" text,
    visitor_id text,
    address text,
    city text,
    country text,
    house_number text,
    house_number_suffix text,
    "name" text,
    postal_code text,
    "state" text,
    "type" text,
    PRIMARY KEY ("index", visitor_id),
    FOREIGN KEY (visitor_id) REFERENCES visitor(id)
);

CREATE TABLE visitor_ordered_item (
    "index" text,
    visitor_id text,
    amount_name text,
    count text,
    "name" text,
    reference text,
    shop_item_id text,
    text text,
    total_amount text,
    total_amount_vat text,
    PRIMARY KEY ("index", visitor_id),
    FOREIGN KEY (visitor_id) REFERENCES visitor(id)
);

CREATE TABLE visitor_ordered_payment (
    "index" text,
    visitor_id text,
    amount text,
    code text,
    payment_method text,
    payment_method_info text,
    payment_state text,
    reference text,
    "time" text,
    PRIMARY KEY ("index", visitor_id),
    FOREIGN KEY (visitor_id) REFERENCES visitor(id)
);

CREATE TABLE visitor_policy (
    "index" text,
    visitor_id text,
    checked text,
    "type" text,
    PRIMARY KEY ("index", visitor_id),
    FOREIGN KEY (visitor_id) REFERENCES visitor(id)
);

CREATE TABLE visitor_activity (
    "index" text,
    content_id text,
    partner_id text,
    visitor_id text,
    "action" text,
    location_direction text,
    location_id text,
    location_name text,
    "time" text,
    "type" text,
    PRIMARY KEY ("index"),
    FOREIGN KEY (content_id) REFERENCES content(id),
    FOREIGN KEY (partner_id) REFERENCES partner(id),
    FOREIGN KEY (visitor_id) REFERENCES visitor(id)
);

CREATE TABLE visitor_question_answer (
    id text,
    question_id text,
    visitor_id text,
    reference text,
    "type" text,
    "value" text,
    PRIMARY KEY (id, question_id, visitor_id),
    FOREIGN KEY (question_id) REFERENCES visitor_question(id),
    FOREIGN KEY (visitor_id) REFERENCES visitor_question(visitor_id)
);

CREATE TABLE visitor_question (
    id text,
    visitor_id text,
    "level" text,
    "name" text,
    reference text,
    "type" text,
    PRIMARY KEY (id, visitor_id),
    FOREIGN KEY (visitor_id) REFERENCES visitor(id)
);

CREATE TABLE visitor (
    id text,
    expo_id text,
    action_code_name text,
    action_code_type text,
    action_code_value text,
    comments text,
    confirmation_document_url text,
    contact_coc_number text,
    contact_comments text,
    contact_company text,
    contact_company_fax text,
    contact_company_name text,
    contact_company_phone text,
    contact_company_website text,
    contact_department text,
    contact_dob text,
    contact_email text,
    contact_fax text,
    contact_first_initials text,
    contact_first_name text,
    contact_gender text,
    contact_id text,
    contact_job_function text,
    contact_last_name text,
    contact_last_name_prefix text,
    contact_nationality text,
    contact_phone_1 text,
    contact_phone_2 text,
    contact_reference text,
    contact_social_security_number text,
    contact_suffix text,
    contact_title text,
    contact_vat_number text,
    contact_website text,
    data_use_1 text,
    data_use_2 text,
    data_use_3 text,
    deleted text,
    dwelling_dwelling_time text,
    dwelling_first_entry_time text,
    dwelling_last_exit_time text,
    embedded_digital_badge_url text,
    form_id text,
    form_name text,
    form_url text,
    mailing text,
    master_visitor_id text,
    method text,
    ordered_code text,
    ordered_currency text,
    ordered_total text,
    ordered_total_due text,
    ordered_total_paid text,
    ordered_total_sub text,
    ordered_total_vat text,
    partner text,
    partner_association text,
    picture_url text,
    reference text,
    register_time text,
    registration_state text,
    registration_type_id text,
    registration_type_level text,
    registration_type_name text,
    registration_type_reference text,
    registration_url text,
    revision text,
    timeslots jsonb,
    tracking_utm_campaign text,
    tracking_utm_content text,
    tracking_utm_medium text,
    tracking_utm_source text,
    tracking_utm_term text,
    translation_id text,
    translation_iso text,
    translation_language text,
    translation_name text,
    visit_discover_url text,
    visit_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (expo_id) REFERENCES event(id)
);

CREATE TABLE content (
    id text,
    expo_id text,
    partner_id text,
    "name" text,
    revision text,
    "source" text,
    summary text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (expo_id) REFERENCES event(id),
    FOREIGN KEY (partner_id) REFERENCES partner(id)
);
