CREATE TABLE approval_approver (
    "index" text,
    approval_id text,
    approver_user_id text,
    "comment" text,
    description text,
    reviewed_at text,
    "status" text,
    step_number text,
    PRIMARY KEY ("index", approval_id),
    FOREIGN KEY (approval_id) REFERENCES approval(id),
    FOREIGN KEY (approver_user_id) REFERENCES users(id)
);

CREATE TABLE approval (
    id text,
    deal_id text,
    proposal_id text,
    requester_id text,
    active text,
    created_at text,
    requested_at text,
    requester_comment text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (proposal_id) REFERENCES proposal(id),
    FOREIGN KEY (requester_id) REFERENCES users(id)
);

CREATE TABLE proposal (
    id text,
    deal_id text,
    created_at text,
    description text,
    discount_rate text,
    entered_date text,
    latest text,
    ner_to_termination_area_unit text,
    ner_to_termination_magnitude text,
    ner_to_termination_money_unit text,
    ner_to_termination_period_unit text,
    ner_to_termination_type text,
    ner_to_termination_unit text,
    ner_vs_budget_magnitude text,
    ner_vs_budget_money_unit text,
    ner_vs_budget_type text,
    ner_vs_budget_unit text,
    ner_with_downtime_area_unit text,
    ner_with_downtime_magnitude text,
    ner_with_downtime_money_unit text,
    ner_with_downtime_period_unit text,
    ner_with_downtime_type text,
    ner_with_downtime_unit text,
    net_effective_rent_area_unit text,
    net_effective_rent_magnitude text,
    net_effective_rent_money_unit text,
    net_effective_rent_period_unit text,
    net_effective_rent_type text,
    net_effective_rent_unit text,
    net_rent_area_unit text,
    net_rent_magnitude text,
    net_rent_money_unit text,
    net_rent_period_unit text,
    net_rent_type text,
    net_rent_unit text,
    proposal_date text,
    proposal_label text,
    proposal_type text,
    total_base_rent_area_unit text,
    total_base_rent_magnitude text,
    total_base_rent_money_unit text,
    total_base_rent_period_unit text,
    total_base_rent_type text,
    total_base_rent_unit text,
    total_capital_magnitude text,
    total_capital_money_unit text,
    total_capital_type text,
    total_capital_unit text,
    total_net_cash_flow_magnitude text,
    total_net_cash_flow_money_unit text,
    total_net_cash_flow_type text,
    total_net_cash_flow_unit text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE tenant_update_contact (
    tenant_contact_id text,
    tenant_update_id text,
    PRIMARY KEY (tenant_contact_id, tenant_update_id),
    FOREIGN KEY (tenant_contact_id) REFERENCES tenant_contact(id),
    FOREIGN KEY (tenant_update_id) REFERENCES tenant_update(id)
);

CREATE TABLE tenant_update (
    id text,
    asset_id text,
    created_by_id text,
    owner_id text,
    tenant_id text,
    "comment" text,
    created_at text,
    important text,
    interaction_date text,
    interaction_type text,
    sentiment text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

CREATE TABLE coordination_project_milestone (
    id text,
    completed_by_id text,
    category_description text,
    completed_at text,
    completed_by_type text,
    created_at text,
    description text,
    notes text,
    target_date text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (completed_by_id) REFERENCES users(id)
);

CREATE TABLE appraisal_reimbursable_expense (
    "index" text,
    appraisal_id text,
    description text,
    expense_amount_area_unit text,
    expense_amount_magnitude text,
    expense_amount_money_unit text,
    expense_amount_period_unit text,
    expense_amount_type text,
    expense_amount_unit text,
    expense_growth_rate_magnitude text,
    expense_growth_rate_period_unit text,
    expense_growth_rate_type text,
    expense_growth_rate_unit text,
    expense_stop_area_unit text,
    expense_stop_magnitude text,
    expense_stop_money_unit text,
    expense_stop_period_unit text,
    expense_stop_type text,
    expense_stop_unit text,
    expense_type text,
    recovery_amount_area_unit text,
    recovery_amount_magnitude text,
    recovery_amount_money_unit text,
    recovery_amount_period_unit text,
    recovery_amount_type text,
    recovery_amount_unit text,
    recovery_method text,
    PRIMARY KEY ("index", appraisal_id),
    FOREIGN KEY (appraisal_id) REFERENCES appraisal(id)
);

CREATE TABLE appraisal_base_rent (
    "index" text,
    appraisal_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    start_month text,
    PRIMARY KEY ("index", appraisal_id),
    FOREIGN KEY (appraisal_id) REFERENCES appraisal(id)
);

CREATE TABLE appraisal_commission_period (
    "index" text,
    appraisal_commission_index text,
    appraisal_id text,
    amount_magnitude text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    start_date text,
    start_month text,
    PRIMARY KEY ("index", appraisal_commission_index, appraisal_id),
    FOREIGN KEY (appraisal_commission_index) REFERENCES appraisal_commission("index"),
    FOREIGN KEY (appraisal_id) REFERENCES appraisal_commission(appraisal_id)
);

CREATE TABLE appraisal_commission (
    "index" text,
    appraisal_id text,
    broker text,
    "date" text,
    description text,
    free_rent text,
    net_or_gross text,
    "type" text,
    PRIMARY KEY ("index", appraisal_id),
    FOREIGN KEY (appraisal_id) REFERENCES appraisal(id)
);

CREATE TABLE appraisal_cost (
    "index" text,
    appraisal_id text,
    amount_magnitude text,
    amount_money_unit text,
    amount_type text,
    amount_unit text,
    description text,
    occurrence_month text,
    "type" text,
    PRIMARY KEY ("index", appraisal_id),
    FOREIGN KEY (appraisal_id) REFERENCES appraisal(id)
);

CREATE TABLE appraisal_free_rent (
    "index" text,
    appraisal_id text,
    amount_magnitude text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    duration_iso_8601 text,
    duration_magnitude text,
    duration_period_unit text,
    duration_type text,
    duration_unit text,
    start_month text,
    "type" text,
    PRIMARY KEY ("index", appraisal_id),
    FOREIGN KEY (appraisal_id) REFERENCES appraisal(id)
);

CREATE TABLE appraisal_rent_escalation (
    "index" text,
    appraisal_id text,
    amount_magnitude text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    occurs text,
    start_month text,
    PRIMARY KEY ("index", appraisal_id),
    FOREIGN KEY (appraisal_id) REFERENCES appraisal(id)
);

CREATE TABLE appraisal (
    id text,
    analysis_type text,
    commencement_date text,
    concession text,
    created_at text,
    description text,
    entered_date text,
    internal_rate_of_return text,
    ner_override_area_unit text,
    ner_override_magnitude text,
    ner_override_money_unit text,
    ner_override_period_unit text,
    ner_override_type text,
    ner_override_unit text,
    net_effective_rent_area_unit text,
    net_effective_rent_magnitude text,
    net_effective_rent_money_unit text,
    net_effective_rent_period_unit text,
    net_effective_rent_type text,
    net_effective_rent_unit text,
    npv_discount_rate text,
    npv_per_area_magnitude text,
    npv_per_area_money_unit text,
    npv_per_area_type text,
    npv_per_area_unit text,
    payback text,
    rentable_size_area_unit text,
    rentable_size_magnitude text,
    rentable_size_type text,
    rentable_size_unit text,
    security_deposit_magnitude text,
    security_deposit_money_unit text,
    security_deposit_type text,
    security_deposit_unit text,
    structure text,
    total_deal_value_area_unit text,
    total_deal_value_magnitude text,
    total_deal_value_money_unit text,
    total_deal_value_period_unit text,
    total_deal_value_type text,
    total_deal_value_unit text,
    total_lease_term_iso_8601 text,
    total_lease_term_magnitude text,
    total_lease_term_period_unit text,
    total_lease_term_type text,
    total_lease_term_unit text,
    total_net_cash_flow_magnitude text,
    total_net_cash_flow_money_unit text,
    total_net_cash_flow_type text,
    total_net_cash_flow_unit text,
    total_rent_area_unit text,
    total_rent_magnitude text,
    total_rent_money_unit text,
    total_rent_period_unit text,
    total_rent_type text,
    total_rent_unit text,
    PRIMARY KEY (id)
);

CREATE TABLE blended_budget (
    id text,
    deal_id text,
    base_rent_area_unit text,
    base_rent_magnitude text,
    base_rent_money_unit text,
    base_rent_period_unit text,
    base_rent_type text,
    base_rent_unit text,
    building_improvement_area_unit text,
    building_improvement_magnitude text,
    building_improvement_money_unit text,
    building_improvement_type text,
    building_improvement_unit text,
    created_at text,
    net_effective_rent_area_unit text,
    net_effective_rent_magnitude text,
    net_effective_rent_money_unit text,
    net_effective_rent_period_unit text,
    net_effective_rent_type text,
    net_effective_rent_unit text,
    net_present_value_area_unit text,
    net_present_value_magnitude text,
    net_present_value_money_unit text,
    net_present_value_type text,
    net_present_value_unit text,
    recovered_income_area_unit text,
    recovered_income_magnitude text,
    recovered_income_money_unit text,
    recovered_income_period_unit text,
    recovered_income_type text,
    recovered_income_unit text,
    reimbrusable_expense_area_unit text,
    reimbrusable_expense_magnitude text,
    reimbrusable_expense_money_unit text,
    reimbrusable_expense_period_unit text,
    reimbrusable_expense_type text,
    reimbrusable_expense_unit text,
    rentable_size_area_unit text,
    rentable_size_magnitude text,
    rentable_size_type text,
    rentable_size_unit text,
    tenant_improvement_area_unit text,
    tenant_improvement_magnitude text,
    tenant_improvement_money_unit text,
    tenant_improvement_type text,
    tenant_improvement_unit text,
    total_commission_magnitude text,
    total_commission_money_unit text,
    total_commission_type text,
    total_commission_unit text,
    total_free_rent_magnitude text,
    total_free_rent_money_unit text,
    total_free_rent_type text,
    total_free_rent_unit text,
    total_other_revenue_area_unit text,
    total_other_revenue_magnitude text,
    total_other_revenue_money_unit text,
    total_other_revenue_period_unit text,
    total_other_revenue_type text,
    total_other_revenue_unit text,
    total_percentage_rent_magnitude text,
    total_percentage_rent_money_unit text,
    total_percentage_rent_type text,
    total_percentage_rent_unit text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal_task (
    id text,
    assignee_id text,
    completed_by_id text,
    deal_id text,
    completed text,
    completed_at text,
    created_at text,
    description text,
    required text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (assignee_id) REFERENCES users(id),
    FOREIGN KEY (completed_by_id) REFERENCES users(id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal_comment (
    id text,
    deal_id text,
    iteration_id text,
    user_id text,
    created_at text,
    latest text,
    occurred_at text,
    text text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (iteration_id) REFERENCES deal_iteration(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE option_target (
    option_id text,
    space_id text,
    "type" text,
    PRIMARY KEY (option_id, space_id),
    FOREIGN KEY (option_id) REFERENCES "option"(id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE "option" (
    id text,
    lease_term_id text,
    proposal_id text,
    created_at text,
    description text,
    effective_date text,
    minimum_size text,
    notice_end_date text,
    notice_start_date text,
    number_of_option text,
    option_type text,
    rate_note text,
    rate_type text,
    term_iso_8601 text,
    term_magnitude text,
    term_period_unit text,
    term_type text,
    term_unit text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id),
    FOREIGN KEY (proposal_id) REFERENCES proposal(id)
);

CREATE TABLE budget_commission_period (
    "index" text,
    budget_commission_index text,
    budget_id text,
    periods_area_unit text,
    periods_magnitude text,
    periods_money_unit text,
    periods_period_unit text,
    periods_type text,
    periods_unit text,
    start_date text,
    start_month text,
    PRIMARY KEY ("index", budget_commission_index, budget_id),
    FOREIGN KEY (budget_commission_index) REFERENCES budget_commission("index"),
    FOREIGN KEY (budget_id) REFERENCES budget_commission(budget_id)
);

CREATE TABLE budget_commission (
    "index" text,
    budget_id text,
    broker text,
    "date" text,
    description text,
    free_rent text,
    net_or_gross text,
    "type" text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_rent_escalation (
    "index" text,
    budget_id text,
    amount_magnitude text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    occurs text,
    start_month text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_base_rent (
    "index" text,
    budget_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    begin_in text,
    start_month text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_free_rent (
    "index" text,
    budget_id text,
    amount_free_magnitude text,
    amount_free_period_unit text,
    amount_free_type text,
    amount_free_unit text,
    duration text,
    duration_iso_8601 text,
    duration_magnitude text,
    duration_period_unit text,
    duration_type text,
    duration_unit text,
    precent_free text,
    recovery_type text,
    start_month text,
    "type" text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_percentage_rent_sales_overage_breakpoint (
    "index" text,
    budget_id text,
    budget_percentage_rent_index text,
    breakpoint_magnitude text,
    breakpoint_money_unit text,
    breakpoint_period_unit text,
    breakpoint_type text,
    breakpoint_unit text,
    percent_rent_magnitude text,
    percent_rent_period_unit text,
    percent_rent_type text,
    percent_rent_unit text,
    PRIMARY KEY ("index", budget_id, budget_percentage_rent_index),
    FOREIGN KEY (budget_id) REFERENCES budget_percentage_rent(budget_id),
    FOREIGN KEY (budget_percentage_rent_index) REFERENCES budget_percentage_rent("index")
);

CREATE TABLE budget_percentage_rent (
    "index" text,
    budget_id text,
    minimum_guarantee_area_unit text,
    minimum_guarantee_magnitude text,
    minimum_guarantee_money_unit text,
    minimum_guarantee_period_unit text,
    minimum_guarantee_type text,
    minimum_guarantee_unit text,
    sales_overage_breakpoints_type text,
    start_month text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_other_income (
    "index" text,
    budget_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    quantity text,
    start_month text,
    "type" text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_reimbursabl_expense (
    "index" text,
    budget_id text,
    description text,
    expense_amount_area_unit text,
    expense_amount_magnitude text,
    expense_amount_money_unit text,
    expense_amount_period_unit text,
    expense_amount_type text,
    expense_amount_unit text,
    expense_growth_rate_magnitude text,
    expense_growth_rate_period_unit text,
    expense_growth_rate_type text,
    expense_growth_rate_unit text,
    expense_stop_area_unit text,
    expense_stop_magnitude text,
    expense_stop_money_unit text,
    expense_stop_period_unit text,
    expense_stop_type text,
    expense_stop_unit text,
    expense_type text,
    recovery_amount_area_unit text,
    recovery_amount_magnitude text,
    recovery_amount_money_unit text,
    recovery_amount_period_unit text,
    recovery_amount_type text,
    recovery_amount_unit text,
    recovery_method text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_cost (
    "index" text,
    budget_id text,
    amount_magnitude text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    description text,
    occurrence_month text,
    typek text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget_rent_schedule (
    "index" text,
    budget_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    end_month text,
    start_month text,
    PRIMARY KEY ("index", budget_id),
    FOREIGN KEY (budget_id) REFERENCES budget(id)
);

CREATE TABLE budget (
    id text,
    asset_id text,
    blended_budget_id text,
    space_id text,
    budget_year text,
    commencement_date text,
    commission_month text,
    concession text,
    created_at text,
    description text,
    downtime_magnitude text,
    downtime_period_unit text,
    downtime_type text,
    downtime_unit text,
    entered_date text,
    execution_date text,
    gross_rent_area_unit text,
    gross_rent_magnitude text,
    gross_rent_money_unit text,
    gross_rent_period_unit text,
    gross_rent_type text,
    gross_rent_unit text,
    internal_rate_of_return text,
    label text,
    lock_in_end_date text,
    minimum_guarantee_area_unit text,
    minimum_guarantee_magnitude text,
    minimum_guarantee_money_unit text,
    minimum_guarantee_period_unit text,
    minimum_guarantee_type text,
    minimum_guarantee_unit text,
    ner_override_magnitude text,
    ner_override_money_unit text,
    ner_override_period_unit text,
    ner_override_type text,
    ner_override_unit text,
    net_cash_flow_magnitude text,
    net_cash_flow_money_unit text,
    net_cash_flow_type text,
    net_cash_flow_unit text,
    net_effective_rent_area_unit text,
    net_effective_rent_magnitude text,
    net_effective_rent_money_unit text,
    net_effective_rent_period_unit text,
    net_effective_rent_type text,
    net_effective_rent_unit text,
    net_rent_area_unit text,
    net_rent_magnitude text,
    net_rent_money_unit text,
    net_rent_period_unit text,
    net_rent_type text,
    net_rent_unit text,
    npv_discount_rate text,
    npv_per_area_magnitude text,
    npv_per_area_money_unit text,
    npv_per_area_type text,
    npv_per_area_unit text,
    other_fee jsonb,
    payback text,
    proposal_type text,
    rentable_size_area_unit text,
    rentable_size_magnitude text,
    rentable_size_type text,
    rentable_size_unit text,
    security_deposit_magnitude text,
    security_deposit_money_unit text,
    security_deposit_type text,
    security_deposit_unit text,
    structure text,
    tenant_risk_description text,
    total_deal_value_area_unit text,
    total_deal_value_magnitude text,
    total_deal_value_money_unit text,
    total_deal_value_period_unit text,
    total_deal_value_type text,
    total_deal_value_unit text,
    total_lease_term text,
    total_rent_area_unit text,
    total_rent_magnitude text,
    total_rent_money_unit text,
    total_rent_period_unit text,
    total_rent_type text,
    total_rent_unit text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (blended_budget_id) REFERENCES blended_budget(id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE deal_tour_space (
    deal_tour_id text,
    space_id text,
    PRIMARY KEY (deal_tour_id, space_id),
    FOREIGN KEY (deal_tour_id) REFERENCES deal_tour(id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE deal_tour (
    id text,
    deal_id text,
    user_id text,
    "comment" text,
    created_at text,
    tour_datetime text,
    updated_at timestamp,
    users_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE deal_iteration (
    id text,
    deal_id text,
    user_id text,
    created_at text,
    duration_in_days text,
    ended_at text,
    latest text,
    occurred_at text,
    reason text,
    stage text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE deal_term_commission_period (
    "index" text,
    deal_term_commission_index text,
    deal_term_id text,
    amount_measure_money_area_area_unit text,
    amount_measure_money_area_magnitude text,
    amount_measure_money_area_money_unit text,
    amount_measure_money_area_type text,
    amount_measure_money_area_unit text,
    amount_measure_money_magnitude text,
    amount_measure_money_money_unit text,
    amount_measure_money_period_magnitude text,
    amount_measure_money_period_money_unit text,
    amount_measure_money_period_period_unit text,
    amount_measure_money_period_type text,
    amount_measure_money_period_unit text,
    amount_measure_money_type text,
    amount_measure_money_unit text,
    amount_measure_percentage_magnitude text,
    amount_measure_percentage_period_unit text,
    amount_measure_percentage_type text,
    amount_measure_percentage_unit text,
    start_date text,
    start_month text,
    PRIMARY KEY ("index", deal_term_commission_index, deal_term_id),
    FOREIGN KEY (deal_term_commission_index) REFERENCES deal_term_commission("index"),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term_commission(deal_term_id)
);

CREATE TABLE deal_term_commission (
    "index" text,
    deal_term_id text,
    broker text,
    "date" text,
    description text,
    free_rent text,
    net_or_gross text,
    "type" text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_rent_escalation (
    "index" text,
    deal_term_id text,
    amount_magnitude text,
    amount_percentage text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    occur text,
    start_month text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_base_rent (
    "index" text,
    deal_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    start_month text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_free_rent (
    "index" text,
    deal_term_id text,
    amount_free_magnitude text,
    amount_free_percentage text,
    amount_free_period_unit text,
    amount_free_type text,
    amount_free_unit text,
    duration_iso_8601 text,
    duration_magnitude text,
    duration_period_unit text,
    duration_type text,
    duration_unit text,
    start_month text,
    "type" text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_cost (
    "index" text,
    deal_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_type text,
    amount_unit text,
    description text,
    occurrence_month text,
    "type" text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_rent_schedule (
    "index" text,
    deal_term_id text,
    end_month text,
    magnitude text,
    start_month text,
    unit text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_other_income (
    "index" text,
    deal_term_id text,
    measure_money_area_period_area_unit text,
    measure_money_area_period_magnitude text,
    measure_money_area_period_period_unit text,
    measure_money_area_period_type text,
    measure_money_area_period_unit text,
    measure_money_period_magnitude text,
    measure_money_period_money_unit text,
    measure_money_period_period_unit text,
    measure_money_period_type text,
    measure_money_period_unit text,
    quantity text,
    start_month text,
    "type" text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_remaining_lease_obligation (
    "index" text,
    deal_term_id text,
    duration_iso_8601 text,
    duration_magnitude text,
    duration_period_unit text,
    duration_type text,
    duration_unit text,
    measure_money_area_period_area_unit text,
    measure_money_area_period_magnitude text,
    measure_money_area_period_money_unit text,
    measure_money_area_period_period_unit text,
    measure_money_area_period_type text,
    measure_money_area_period_unit text,
    measure_money_period_magnitude text,
    measure_money_period_money_unit text,
    measure_money_period_period_unit text,
    measure_money_period_type text,
    measure_money_period_unit text,
    start_month text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term_reimbursabl_expense (
    "index" text,
    deal_term_id text,
    description text,
    expense_amount_area_unit text,
    expense_amount_magnitude text,
    expense_amount_money_unit text,
    expense_amount_period_unit text,
    expense_amount_type text,
    expense_amount_unit text,
    expense_amount_with_unit text,
    expense_growth_rate_magnitude text,
    expense_growth_rate_period_unit text,
    expense_growth_rate_type text,
    expense_growth_rate_unit text,
    expense_stop_area_unit text,
    expense_stop_magnitude text,
    expense_stop_money_unit text,
    expense_stop_period_unit text,
    expense_stop_type text,
    expense_stop_unit text,
    expense_type text,
    recovery_amount_area_unit text,
    recovery_amount_magnitude text,
    recovery_amount_money_unit text,
    recovery_amount_period_unit text,
    recovery_amount_type text,
    recovery_amount_unit text,
    recovery_method text,
    PRIMARY KEY ("index", deal_term_id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE deal_term (
    id text,
    deal_id text,
    proposal_id text,
    space_id text,
    calculated_metrics_internal_rate_of_return text,
    calculated_metrics_leasing_spread text,
    calculated_metrics_payback text,
    calculated_metrics_tenant_possession_date text,
    commencement_date text,
    created_at text,
    description text,
    downtime_iso_8609 text,
    downtime_magnitude text,
    downtime_period_unit text,
    downtime_type text,
    downtime_unit text,
    entered_date text,
    execution_date text,
    expiration_date text,
    gaap_rent_area_unit text,
    gaap_rent_magnitude text,
    gaap_rent_money_unit text,
    gaap_rent_period_unit text,
    gaap_rent_type text,
    gaap_rent_unit text,
    landlord_commission_magnitude text,
    landlord_commission_money_unit text,
    landlord_commission_type text,
    landlord_commission_unit text,
    ner_override_area_unit text,
    ner_override_magnitude text,
    ner_override_money_unit text,
    ner_override_period_unit text,
    ner_override_type text,
    ner_override_unit text,
    ner_to_termination_area_unit text,
    ner_to_termination_magnitude text,
    ner_to_termination_money_unit text,
    ner_to_termination_period_unit text,
    ner_to_termination_type text,
    ner_to_termination_unit text,
    ner_with_downtime_area_unit text,
    ner_with_downtime_magnitude text,
    ner_with_downtime_money_unit text,
    ner_with_downtime_period_unit text,
    ner_with_downtime_type text,
    ner_with_downtime_unit text,
    net_effective_rent_area_unit text,
    net_effective_rent_magnitude text,
    net_effective_rent_money_unit text,
    net_effective_rent_period_unit text,
    net_effective_rent_type text,
    net_effective_rent_unit text,
    net_present_value_magnitude text,
    net_present_value_money_unit text,
    net_present_value_type text,
    net_present_value_unit text,
    net_rent_area_unit text,
    net_rent_magnitude text,
    net_rent_money_unit text,
    net_rent_period_unit text,
    net_rent_type text,
    net_rent_unit text,
    npv_per_area_magnitude text,
    npv_per_area_money_unit text,
    npv_per_area_type text,
    npv_per_area_unit text,
    percentage_rents jsonb,
    rent_commencement_date text,
    rentable_size_area_unit text,
    rentable_size_magnitude text,
    rentable_size_type text,
    rentable_size_unit text,
    retail_decription text,
    retail_estimated_sales text,
    retail_growth_rate text,
    retail_percent_rent text,
    retail_unnatural_breakpoint text,
    straight_line_balance text,
    straight_line_balance_magnitude text,
    straight_line_balance_money_unit text,
    straight_line_balance_type text,
    straight_line_balance_unit text,
    structure text,
    tenant_buildout_period_iso_8609 text,
    tenant_buildout_period_magnitude text,
    tenant_buildout_period_period_unit text,
    tenant_buildout_period_type text,
    tenant_buildout_period_unit text,
    tenant_commission_magnitude text,
    tenant_commission_money_unit text,
    tenant_commission_type text,
    tenant_commission_unit text,
    term_duration_iso_8609 text,
    term_duration_magnitude text,
    term_duration_period_unit text,
    term_duration_type text,
    term_duration_unit text,
    term_type text,
    total_capital_magnitude text,
    total_capital_money_unit text,
    total_capital_per_size_area_unit text,
    total_capital_per_size_magnitude text,
    total_capital_per_size_money_unit text,
    total_capital_per_size_type text,
    total_capital_per_size_unit text,
    total_capital_type text,
    total_capital_unit text,
    total_commission_magnitude text,
    total_commission_money_unit text,
    total_commission_type text,
    total_commission_unit text,
    total_net_cash_flow_magnitude text,
    total_net_cash_flow_money_unit text,
    total_net_cash_flow_type text,
    total_net_cash_flow_unit text,
    total_net_rent_magnitude text,
    total_net_rent_money_unit text,
    total_net_rent_type text,
    total_net_rent_unit text,
    total_term_free_rent_magnitude text,
    total_term_free_rent_money_unit text,
    total_term_free_rent_type text,
    total_term_free_rent_unit text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (proposal_id) REFERENCES proposal(id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE users (
    id text,
    current_sign_in_at text,
    disabled text,
    email text,
    first_name text,
    is_account_user text,
    is_company_admin text,
    last_name text,
    phone text,
    phone_extension text,
    title text,
    PRIMARY KEY (id)
);

CREATE TABLE global_tenant (
    id text,
    globel_tenant_id text,
    address text,
    cap_iq_id text,
    created_at text,
    industry text,
    "name" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (globel_tenant_id) REFERENCES global_tenant(id)
);

CREATE TABLE tenant_contact_lease (
    lease_id text,
    tenant_contact_id text,
    PRIMARY KEY (lease_id, tenant_contact_id),
    FOREIGN KEY (lease_id) REFERENCES lease(id),
    FOREIGN KEY (tenant_contact_id) REFERENCES tenant_contact(id)
);

CREATE TABLE tenant_contact (
    id text,
    tenant_id text,
    company_name text,
    created_at text,
    email text,
    first_name text,
    last_name text,
    phone text,
    phone_extension text,
    title text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

CREATE TABLE space_external_system_info (
    "index" text,
    space_id text,
    id text,
    "name" text,
    PRIMARY KEY ("index", space_id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE space (
    id text,
    asset_id text,
    committed_lease_id text,
    in_place_lease_id text,
    last_expired_lease_id text,
    archived_date text,
    availability_date text,
    availability_type text,
    ceiling_height text,
    clear_height text,
    column_spacing text,
    created_at text,
    current_size_area_unit text,
    current_size_magnitude text,
    current_size_type text,
    current_size_unit text,
    depth text,
    description text,
    dock_height text,
    electrical text,
    floor text,
    floor_composition text,
    floor_name text,
    floor_position text,
    ground_level_door text,
    hvac text,
    hypothetical_space text,
    internal_note text,
    lease_type text,
    listing_date text,
    market_rent_magnitude text,
    market_rent_money_unit text,
    market_rent_type text,
    market_rent_unit text,
    maximum_contiguous_size_area_unit text,
    maximum_contiguous_size_magnitude text,
    maximum_contiguous_size_type text,
    maximum_contiguous_size_unit text,
    minimum_divisible_size_area_unit text,
    minimum_divisible_size_magnitude text,
    minimum_divisible_size_type text,
    minimum_divisible_size_unit text,
    occupancy_status text,
    office_portion text,
    parking text,
    "position" text,
    price_is_negotiable text,
    public text,
    remeasured_space_available text,
    rental_pay_type text,
    rental_rate_max_magnitude text,
    rental_rate_max_money_unit text,
    rental_rate_max_period_unit text,
    rental_rate_max_type text,
    rental_rate_max_unit text,
    rental_rate_min_magnitude text,
    rental_rate_min_money_unit text,
    rental_rate_min_period_unit text,
    rental_rate_min_type text,
    rental_rate_min_unit text,
    roof text,
    sale_price_magnitude text,
    sale_price_money_unit text,
    sale_price_type text,
    sale_price_unit text,
    source_id text,
    space_condition text,
    space_type text,
    sprinkler text,
    subtitle text,
    suite text,
    term_duration text,
    trailer_parking text,
    transaction_type text,
    "type" text,
    updated_at timestamp,
    vacant_on_date text,
    yard text,
    PRIMARY KEY (id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (committed_lease_id) REFERENCES lease(id),
    FOREIGN KEY (in_place_lease_id) REFERENCES lease(id),
    FOREIGN KEY (last_expired_lease_id) REFERENCES lease(id)
);

CREATE TABLE finance (
    id text,
    deal_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    created_at text,
    end_date text,
    end_duration text,
    start_date text,
    start_month text,
    "type" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (deal_term_id) REFERENCES deal_term(id)
);

CREATE TABLE coordination_project (
    id text,
    tenant_id text,
    created_at text,
    current_rent_commencement_date text,
    target_rent_commencement_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

CREATE TABLE lease_term_other_income (
    "index" text,
    lease_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    end_date text,
    start_date text,
    "type" text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id)
);

CREATE TABLE lease_term_free_rent (
    "index" text,
    lease_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    end_date text,
    start_date text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id)
);

CREATE TABLE lease_term_base_rent (
    "index" text,
    lease_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    end_date text,
    start_date text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id)
);

CREATE TABLE lease_term_commission_period (
    "index" text,
    lease_term_commission_index text,
    lease_term_id text,
    amount_magnitude text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    start_date text,
    start_month text,
    PRIMARY KEY ("index", lease_term_commission_index, lease_term_id),
    FOREIGN KEY (lease_term_commission_index) REFERENCES lease_term_commission("index"),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term_commission(lease_term_id)
);

CREATE TABLE lease_term_commission (
    "index" text,
    lease_term_id text,
    broker text,
    "date" text,
    description text,
    free_rent text,
    net_or_gross text,
    "type" text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id)
);

CREATE TABLE lease_term_cost (
    "index" text,
    lease_term_id text,
    amount_magnitude text,
    amount_money_unit text,
    amount_type text,
    amount_unit text,
    description text,
    occurrence_month text,
    "type" text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id)
);

CREATE TABLE lease_term_reimbursable_expense (
    "index" text,
    lease_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    end_date text,
    start_date text,
    "type" text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id)
);

CREATE TABLE lease_term_percentage_rent (
    "index" text,
    lease_term_id text,
    amount_area_unit text,
    amount_magnitude text,
    amount_money_unit text,
    amount_period_unit text,
    amount_type text,
    amount_unit text,
    end_date text,
    start_date text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id)
);

CREATE TABLE lease_term_space (
    "index" text,
    lease_term_id text,
    id text,
    space_id text,
    PRIMARY KEY ("index", lease_term_id),
    FOREIGN KEY (lease_term_id) REFERENCES lease_term(id),
    FOREIGN KEY (id) REFERENCES space(id)
);

CREATE TABLE lease_term (
    id text,
    lease_id text,
    commencement_date text,
    created_at text,
    deal_type text,
    description text,
    downtime_iso_8601 text,
    downtime_magnitude text,
    downtime_period_unit text,
    downtime_type text,
    downtime_unit text,
    entered_date text,
    estimated_sale_magnitude text,
    estimated_sale_money_unit text,
    estimated_sale_period_unit text,
    estimated_sale_type text,
    estimated_sale_unit text,
    execution_date text,
    expiration_date text,
    expiring_base_rent_area_unit text,
    expiring_base_rent_magnitude text,
    expiring_base_rent_money_unit text,
    expiring_base_rent_period_unit text,
    expiring_base_rent_type text,
    expiring_base_rent_unit text,
    expiring_gross_rent_area_unit text,
    expiring_gross_rent_magnitude text,
    expiring_gross_rent_money_unit text,
    expiring_gross_rent_period_unit text,
    expiring_gross_rent_type text,
    expiring_gross_rent_unit text,
    gaap_rent_magnitude text,
    gaap_rent_money_unit text,
    gaap_rent_type text,
    gaap_rent_unit text,
    in_place_base_rent_area_unit text,
    in_place_base_rent_magnitude text,
    in_place_base_rent_money_unit text,
    in_place_base_rent_period_unit text,
    in_place_base_rent_type text,
    in_place_base_rent_unit text,
    in_place_gross_rent_area_unit text,
    in_place_gross_rent_magnitude text,
    in_place_gross_rent_money_unit text,
    in_place_gross_rent_period_unit text,
    in_place_gross_rent_type text,
    in_place_gross_rent_unit text,
    is_month_to_month text,
    lease_type text,
    lock_in_end_date text,
    move_out_date text,
    natural_breakpoint_magnitude text,
    natural_breakpoint_money_unit text,
    natural_breakpoint_period_unit text,
    natural_breakpoint_type text,
    natural_breakpoint_unit text,
    possession_date text,
    rent_commencement_date text,
    rentable_size_area_unit text,
    rentable_size_magnitude text,
    rentable_size_type text,
    rentable_size_unit text,
    retail_description text,
    retail_growth_rate text,
    retail_percent_rent text,
    source_id text,
    structure text,
    tenant_buildout_period_iso_8601 text,
    tenant_buildout_period_magnitude text,
    tenant_buildout_period_period_unit text,
    tenant_buildout_period_type text,
    tenant_buildout_period_unit text,
    term_duration_iso_8601 text,
    term_duration_magnitude text,
    term_duration_period_unit text,
    term_duration_type text,
    term_duration_unit text,
    term_type text,
    unnatural_breakpoint_magnitude text,
    unnatural_breakpoint_money_unit text,
    unnatural_breakpoint_period_unit text,
    unnatural_breakpoint_type text,
    unnatural_breakpoint_unit text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (lease_id) REFERENCES lease(id)
);

CREATE TABLE retail_sale (
    id text,
    lease_id text,
    amount text,
    created_at text,
    end_date text,
    start_date text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (lease_id) REFERENCES lease(id)
);

CREATE TABLE tenant_industry (
    id text,
    created_at text,
    "name" text,
    sector text,
    updated_at timestamp,
    PRIMARY KEY (id)
);

CREATE TABLE asset_property_fund (
    "index" text,
    asset_id text,
    property_fund text,
    PRIMARY KEY ("index", asset_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id)
);

CREATE TABLE asset_external_system_info (
    "index" text,
    asset_id text,
    id text,
    "name" text,
    PRIMARY KEY ("index", asset_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id)
);

CREATE TABLE asset_year_renovated (
    "index" text,
    asset_id text,
    year_renovated text,
    PRIMARY KEY ("index", asset_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id)
);

CREATE TABLE asset_asset_manager (
    "index" text,
    asset_id text,
    asset_manager text,
    PRIMARY KEY ("index", asset_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id)
);

CREATE TABLE asset_jv_partner (
    "index" text,
    asset_id text,
    jv_partner text,
    PRIMARY KEY ("index", asset_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id)
);

CREATE TABLE asset_client (
    "index" text,
    asset_id text,
    client text,
    PRIMARY KEY ("index", asset_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id)
);

CREATE TABLE asset (
    id text,
    account_id text,
    account_name text,
    address_country text,
    address_formatted text,
    address_locality text,
    address_postal_code text,
    address_region text,
    address_street text,
    building_class text,
    building_region text,
    created_at text,
    currency text,
    description text,
    has_industrial_space text,
    has_office_space text,
    has_retail_space text,
    lease_roll text,
    lease_vacant_area_magnitude text,
    lease_vacant_area_type text,
    lease_vacant_area_unit text,
    leasing_company text,
    legal_entity text,
    managing_company text,
    market text,
    multi_building_asset_id text,
    multi_building_asset_type text,
    "name" text,
    notes text,
    number_of_floors text,
    owner text,
    owning_company text,
    photo_url text,
    rentable_building_area_magnitude text,
    rentable_building_area_type text,
    rentable_building_area_unit text,
    size_area_unit text,
    size_magnitude text,
    size_type text,
    size_unit text,
    source_id text,
    space_available_area_unit text,
    space_available_magnitude text,
    space_available_type text,
    space_available_unit text,
    sub_market text,
    updated_at timestamp,
    video_thumbnail text,
    year_built text,
    PRIMARY KEY (id)
);

CREATE TABLE tenant (
    id text,
    global_tenant_id text,
    primary_tenant_id text,
    tenant_industry_id text,
    created_at text,
    global_tenant_name text,
    "name" text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (global_tenant_id) REFERENCES global_tenant(id),
    FOREIGN KEY (primary_tenant_id) REFERENCES tenant(id),
    FOREIGN KEY (tenant_industry_id) REFERENCES tenant_industry(id)
);

CREATE TABLE delinquency (
    id text,
    lease_id text,
    charge_date text,
    charge_type text,
    created_at text,
    current_amount text,
    payment_date text,
    total_amount text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (lease_id) REFERENCES lease(id)
);

CREATE TABLE deal_asset (
    asset_id text,
    deal_id text,
    PRIMARY KEY (asset_id, deal_id),
    FOREIGN KEY (asset_id) REFERENCES asset(id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal_space (
    deal_id text,
    space_id text,
    PRIMARY KEY (deal_id, space_id),
    FOREIGN KEY (deal_id) REFERENCES deal(id),
    FOREIGN KEY (space_id) REFERENCES space(id)
);

CREATE TABLE deal_broker (
    id text,
    deal_id text,
    company text,
    email text,
    first_name text,
    last_name text,
    "name" text,
    phone text,
    phone_extension text,
    PRIMARY KEY (id, deal_id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal_contact (
    "index" text,
    deal_id text,
    company text,
    email text,
    "name" text,
    phone text,
    PRIMARY KEY ("index", deal_id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal_target_location (
    "index" text,
    deal_id text,
    country text,
    formatted text,
    locality text,
    postal_code text,
    region text,
    PRIMARY KEY ("index", deal_id),
    FOREIGN KEY (deal_id) REFERENCES deal(id)
);

CREATE TABLE deal (
    id text,
    comparative_lease_term_id text,
    coordination_project_id text,
    created_by_id text,
    latest_proposal_id text,
    tenant_id text,
    tenant_industry_id text,
    "comment" text,
    competitive_set text,
    created_at text,
    deal_type text,
    is_private text,
    probability text,
    requirement_commencement_date text,
    requirement_inquiry_type text,
    requirement_retail_deal_type text,
    requirement_size_area_unit text,
    requirement_size_maximum text,
    requirement_size_minimum text,
    requirement_size_type text,
    requirement_size_unit text,
    requirement_space_type text,
    stage text,
    target_rent_maximum text,
    target_rent_minimum text,
    target_rent_money_unit text,
    target_rent_type text,
    target_rent_unit text,
    total_size_area_unit text,
    total_size_magnitude text,
    total_size_type text,
    total_size_unit text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (comparative_lease_term_id) REFERENCES lease_term(id),
    FOREIGN KEY (coordination_project_id) REFERENCES coordination_project(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (latest_proposal_id) REFERENCES proposal(id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id),
    FOREIGN KEY (tenant_industry_id) REFERENCES tenant_industry(id)
);

CREATE TABLE lease (
    id text,
    tenant_id text,
    commencement_date text,
    created_at text,
    execution_date text,
    expiration_date text,
    industry text,
    renewal_status text,
    source_id text,
    structure text,
    updated_at timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);
