CREATE TABLE account_information (
    email text,
    first_name text,
    last_name text,
    page_credits integer,
    PRIMARY KEY (email)
);

CREATE TABLE sitemap (
    id bigint,
    cron_day text,
    cron_hour integer,
    cron_minute integer,
    cron_month text,
    cron_timezone text,
    cron_weekday text,
    driver text,
    "name" text,
    page_load_delay integer,
    proxy integer,
    request_interval integer,
    scheduler_enabled boolean,
    PRIMARY KEY (id)
);

CREATE TABLE scraping_job (
    id bigint,
    sitemap_id bigint,
    custom_id text,
    driver text,
    jobs_empty integer,
    jobs_executed integer,
    jobs_failed integer,
    jobs_scheduled integer,
    page_load_delay integer,
    request_interval integer,
    scheduled integer,
    scraping_duration integer,
    "status" text,
    stored_record_count integer,
    test_run integer,
    time_created timestamp,
    PRIMARY KEY (id),
    FOREIGN KEY (sitemap_id) REFERENCES sitemap(id)
);

CREATE TABLE data_quality (
    id bigint,
    max_empty_pages_percent_expected integer,
    max_empty_pages_percent_got integer,
    max_empty_pages_percent_success boolean,
    max_failed_pages_percent_expected integer,
    max_failed_pages_percent_got integer,
    max_failed_pages_percent_success boolean,
    min_column_records_category_link_expected integer,
    min_column_records_category_link_got integer,
    min_column_records_category_link_href_expected integer,
    min_column_records_category_link_href_got integer,
    min_column_records_category_link_href_success boolean,
    min_column_records_category_link_success boolean,
    min_column_records_description_expected integer,
    min_column_records_description_got integer,
    min_column_records_description_success boolean,
    min_column_records_name_expected integer,
    min_column_records_name_got integer,
    min_column_records_name_success boolean,
    min_column_records_pagination_expected integer,
    min_column_records_pagination_got integer,
    min_column_records_pagination_href_expected integer,
    min_column_records_pagination_href_got integer,
    min_column_records_pagination_href_success boolean,
    min_column_records_pagination_success boolean,
    min_column_records_price_expected integer,
    min_column_records_price_got integer,
    min_column_records_price_success boolean,
    min_column_records_product_link_expected integer,
    min_column_records_product_link_got integer,
    min_column_records_product_link_href_expected integer,
    min_column_records_product_link_href_got integer,
    min_column_records_product_link_href_success boolean,
    min_column_records_product_link_success boolean,
    min_column_records_reviews_expected integer,
    min_column_records_reviews_got integer,
    min_column_records_reviews_success boolean,
    min_column_records_subcategory_link_expected integer,
    min_column_records_subcategory_link_got integer,
    min_column_records_subcategory_link_href_expected integer,
    min_column_records_subcategory_link_href_got integer,
    min_column_records_subcategory_link_href_success boolean,
    min_column_records_subcategory_link_success boolean,
    min_record_count_expected integer,
    min_record_count_got integer,
    min_record_count_success boolean,
    overall_data_quality_success boolean,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES scraping_job(id)
);

CREATE TABLE problematic_url (
    url text,
    scraping_job_id bigint,
    "type" text,
    PRIMARY KEY (url, scraping_job_id),
    FOREIGN KEY (scraping_job_id) REFERENCES scraping_job(id)
);
