CREATE TABLE location (
    id text,
    account_id text,
    place_updated_by text,
    updated_by text,
    address text,
    created_at text,
    deleted_at text,
    ip_address text,
    is_default text,
    is_deleted text,
    max_hours text,
    "name" text,
    place_address text,
    place_business_name text,
    place_confirmed text,
    place_country text,
    place_formatted_phone_number text,
    place_id text,
    place_international_phone_number text,
    place_latitude text,
    place_locality text,
    place_longitude text,
    place_postal_code text,
    place_region text,
    place_street_name text,
    place_street_number text,
    place_sub_locality text,
    place_type text,
    place_unique_id text,
    place_updated_at text,
    place_website text,
    radius text,
    sort text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (place_updated_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE event (
    id text,
    account_id text,
    user_id text,
    all_day text,
    created_at text,
    end_time text,
    login_id text,
    notes text,
    recurrence text,
    recurrence_end text,
    start_time text,
    "type" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE time_off_request_message (
    id text,
    account_id text,
    request_id text,
    swap_id text,
    user_id text,
    actor text,
    content text,
    conversation_id text,
    created_at text,
    title text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (request_id) REFERENCES time_off_request(id),
    FOREIGN KEY (swap_id) REFERENCES shift_request_swap(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE time_off_request (
    id text,
    account_id text,
    creator_id text,
    type_id text,
    user_id text,
    created_at text,
    end_time text,
    hours text,
    paid text,
    start_time text,
    "status" text,
    updated_at text,
    user_status text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (type_id) REFERENCES time_off_request_type(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE "position" (
    id text,
    account_id text,
    color text,
    created_at text,
    "name" text,
    sort text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE shift (
    id text,
    account_id text,
    creator_id text,
    location_id text,
    openshift_approval_request_id text,
    site_id text,
    user_id text,
    acknowledged text,
    acknowledged_at text,
    alerted text,
    break_time text,
    color text,
    created_at text,
    end_time text,
    instances text,
    is_open text,
    is_shared text,
    linked_users text,
    notes text,
    notified_at text,
    position_id text,
    published text,
    published_date text,
    requires_openshift_approval text,
    shiftchain_key text,
    start_time text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (openshift_approval_request_id) REFERENCES open_shift_request(id),
    FOREIGN KEY (site_id) REFERENCES site(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE schedule_template (
    id text,
    account_id text,
    location_id text,
    user_id text,
    created_at text,
    description text,
    end_date text,
    "name" text,
    start_date text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE schedule_template_shift (
    id text,
    account_id text,
    block_id text,
    location_id text,
    openshift_approval_request_id text,
    position_id text,
    site_id text,
    template_id text,
    user_id text,
    end_time text,
    is_shared text,
    linked_user text,
    requires_openshift_approval text,
    start_time text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (block_id) REFERENCES shift_template_block(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (openshift_approval_request_id) REFERENCES open_shift_request(id),
    FOREIGN KEY (position_id) REFERENCES "position"(id),
    FOREIGN KEY (site_id) REFERENCES site(id),
    FOREIGN KEY (template_id) REFERENCES schedule_template(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE shift_break (
    id text,
    creator_id text,
    edited_by text,
    time_id text,
    end_time text,
    is_orphaned text,
    is_punched text,
    length text,
    rounded_end_time text,
    rounded_length text,
    rounded_start_time text,
    start_time text,
    "type" text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (edited_by) REFERENCES users(id),
    FOREIGN KEY (time_id) REFERENCES "time"(id)
);

CREATE TABLE account_feature (
    feature text,
    account_id text,
    PRIMARY KEY (feature, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    master_id text,
    owner_id text,
    place_id text,
    account_group text,
    additional_features text,
    agent_id text,
    attendance_alert_employee text,
    attendance_alert_manager text,
    attendance_freemium text,
    availability_migrated text,
    bad_credit_card text,
    billing_address text,
    billing_city text,
    billing_country text,
    billing_discount text,
    billing_engine text,
    billing_phone text,
    billing_state text,
    billing_type text,
    billing_zip text,
    business_id text,
    cancel_reason_feedback text,
    cancel_reason_id text,
    company text,
    converted_at text,
    country_dialing_code text,
    country_id text,
    country_is_deleted text,
    country_is_enabled text,
    country_iso_2 text,
    country_iso_3 text,
    country_name text,
    country_sms_cost text,
    country_sms_credit_cost text,
    country_updated_by text,
    created_at text,
    credit_attempts text,
    credit_balance text,
    credit_eft_number text,
    credit_email text,
    credit_exp text,
    credit_name text,
    credit_number text,
    credit_phone_number text,
    credit_recurring_day text,
    deactivated_at text,
    deleted_at text,
    employee_count text,
    enabled text,
    has_billing text,
    has_saml text,
    industry_id text,
    is_deactivated text,
    is_default_location_address text,
    is_deleted text,
    is_demo text,
    limited_features_shift_acknowledgement boolean,
    location_count text,
    logo text,
    master_plan_id text,
    organization_id text,
    owner_email text,
    owner_name text,
    payroll_date text,
    payroll_hours_max text,
    payroll_overtime_multiplier text,
    place_confirmed text,
    plan_custom text,
    plan_expires text,
    plan_id text,
    plan_texting text,
    plan_type text,
    plan_units text,
    previous_plan_id text,
    previous_plan_units text,
    previous_type text,
    primary_contact text,
    real_type text,
    ref_employees text,
    ref_plan_id text,
    ref_status text,
    referral_code text,
    referral_id text,
    required_features text,
    settings_attendance_billing_recurring text,
    settings_attendance_on_demand_pay_enabled text,
    settings_attendance_role_permissions_managers_can_manage_account_settings text,
    settings_attendance_role_permissions_managers_can_manage_workplace_objects text,
    settings_attendance_role_permissions_supervisors_can_approve_own_timesheet text,
    settings_attendance_role_permissions_supervisors_can_edit_all_shift_details text,
    settings_attendance_role_permissions_supervisors_can_edit_employee_timesheets text,
    settings_attendance_role_permissions_supervisors_can_manage_workplace_objects text,
    settings_attendance_role_permissions_supervisors_can_view_employee_wages text,
    settings_attendance_started_at text,
    settings_attendance_tasks_enabled text,
    settings_attendance_trial_activated text,
    settings_attendance_trial_enabled text,
    settings_attendance_trial_ended_at text,
    settings_attendance_trial_expires_at text,
    settings_attendance_trial_started_at text,
    settings_availability_days_notice text,
    settings_availability_enabled text,
    settings_availability_is_public text,
    settings_break_rules_enabled text,
    settings_break_rules_rules text,
    settings_breaks_paid_track_missed text,
    settings_breaks_unpaid_auto_deduct text,
    settings_breaks_unpaid_enabled text,
    settings_breaks_unpaid_enabled_at text,
    settings_breaks_unpaid_manually_record text,
    settings_clockin_enabled text,
    settings_clockin_mobile_enabled text,
    settings_clockin_mobile_radius text,
    settings_clockin_mobile_strict text,
    settings_clockin_mobile_strict_out text,
    settings_clockin_photo_enabled text,
    settings_clockin_window text,
    settings_clockin_work_enabled text,
    settings_clockin_work_radius text,
    settings_clockin_work_strict text,
    settings_clockin_work_strict_out text,
    settings_conversations_enabled text,
    settings_integrations_revel text,
    settings_integrations_square text,
    settings_marketing_attribution_id text,
    settings_marketing_funnel text,
    settings_payroll_adp_enabled text,
    settings_payroll_adp_viewable text,
    settings_payroll_dbl_multiplier text,
    settings_payroll_enabled text,
    settings_payroll_hours_dot_daily text,
    settings_payroll_hours_dot_daily_enabled text,
    settings_payroll_hours_max text,
    settings_payroll_hours_max_daily text,
    settings_payroll_hours_max_daily_enabled text,
    settings_payroll_hours_max_enabled text,
    settings_payroll_is_onboarded text,
    settings_payroll_max_enforcement_enabled text,
    settings_payroll_ot_alerts_clockin text,
    settings_payroll_ot_alerts_clockout text,
    settings_payroll_ot_alerts_within text,
    settings_payroll_ot_multiplier text,
    settings_payroll_reveal_attendance text,
    settings_payroll_rounding_enabled text,
    settings_payroll_rounding_minute_increment text,
    settings_payroll_start_date text,
    settings_payroll_timesheets text,
    settings_payroll_type text,
    settings_payroll_use_sow_for_ot text,
    settings_payroll_work_day_start text,
    settings_permissions_text_credit text,
    settings_privacy_enabled text,
    settings_schedule_currency text,
    settings_schedule_enabled text,
    settings_schedule_is_visible text,
    settings_schedule_open_scheduling text,
    settings_schedule_positions_only text,
    settings_schedule_preferred_hours text,
    settings_schedule_shared_openshifts text,
    settings_schedule_shift_acknowledgement text,
    settings_schedule_sort_employees text,
    settings_schedule_split_shifts text,
    settings_schedule_start_of_week text,
    settings_schedule_track_absences text,
    settings_schedule_twenty_four_hour text,
    settings_schedule_worktags text,
    settings_scheduling_rules_enabled text,
    settings_scheduling_rules_max_consecutive_days_enabled text,
    settings_scheduling_rules_max_consecutive_days_rule text,
    settings_scheduling_rules_max_days_in_week_enabled text,
    settings_scheduling_rules_max_days_in_week_rule text,
    settings_scheduling_rules_min_hours_between_shifts_diff_day_enabled text,
    settings_scheduling_rules_min_hours_between_shifts_diff_day_rule text,
    settings_scheduling_rules_min_hours_between_shifts_same_day_enabled text,
    settings_scheduling_rules_min_hours_between_shifts_same_day_rule text,
    settings_social_enabled text,
    settings_swaps_drop_hours_before text,
    settings_swaps_enable_drops text,
    settings_swaps_enable_partial_openshift text,
    settings_swaps_enable_releases text,
    settings_swaps_enable_swaps text,
    settings_swaps_enabled text,
    settings_swaps_manager_approval text,
    settings_swaps_partial_openshift_coverage text,
    settings_swaps_release_hours_before text,
    settings_swaps_swap_hours_before text,
    settings_timeoff_days_notice text,
    settings_timeoff_enabled text,
    settings_timeoff_is_public text,
    settings_timeoff_manager_approval text,
    settings_timeoff_max_hours_per_day text,
    settings_timeoff_supervisor_autoapprove text,
    settings_workchat_custom_channels_allowed text,
    settings_workchat_enabled text,
    settings_workchat_last_enabled_date text,
    settings_workchat_managed_channel_conversations_allowed text,
    settings_workchat_toggled text,
    split_shifts text,
    subscriptions text,
    tax_exemption text,
    text_credits text,
    time_format text,
    timezone_id text,
    timezone_name text,
    toggles text,
    trial_created_at text,
    trial_length text,
    "type" text,
    updated_at text,
    updated_by text,
    user_count text,
    user_count_local text,
    uses_features text,
    utm_campaign text,
    utm_content text,
    utm_medium text,
    utm_source text,
    utm_term text,
    wb_expires text,
    PRIMARY KEY (id),
    FOREIGN KEY (master_id) REFERENCES account(id),
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (place_id) REFERENCES location(place_id)
);

CREATE TABLE shift_template_block (
    id text,
    account_id text,
    location_id text,
    position_id text,
    updated_by text,
    break_time text,
    color text,
    created_at text,
    end_time text,
    is_shared text,
    notes text,
    requires_openshift_approval text,
    start_time text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (position_id) REFERENCES "position"(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE punch_state (
    _fivetran_id text,
    break_creator_id text,
    break_id text,
    punch_time_id text,
    shift_id text,
    available_shifts jsonb,
    break_is_punched text,
    can_clock_in text,
    can_clock_out text,
    can_end_break text,
    can_start_break text,
    error_code text,
    job_sites text,
    needs_break_confirmation text,
    positions text,
    punch_start_time text,
    schedules text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (break_creator_id) REFERENCES users(id),
    FOREIGN KEY (break_id) REFERENCES shift_break(id),
    FOREIGN KEY (punch_time_id) REFERENCES "time"(id),
    FOREIGN KEY (shift_id) REFERENCES shift(id)
);

CREATE TABLE annotation (
    id text,
    account_id text,
    creator_id text,
    all_location text,
    announcement text,
    business_closed text,
    color text,
    created_at text,
    end_date text,
    locations jsonb,
    message text,
    no_time_off text,
    relevant_at text,
    start_date text,
    title text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE "admin" (
    id text,
    account_id text,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES users(id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE shift_break_audit (
    id text,
    creator_id text,
    time_id text,
    note text,
    taken text,
    PRIMARY KEY (id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (time_id) REFERENCES "time"(id)
);

CREATE TABLE site (
    id text,
    account_id text,
    location_id text,
    place_id text,
    color text,
    created_at text,
    deleted_at text,
    description text,
    is_deleted text,
    "name" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (place_id) REFERENCES location(place_id)
);

CREATE TABLE time_off_request_type (
    id text,
    account_id text,
    allow_paid text,
    allow_unpaid text,
    built_in text,
    created_at text,
    deleted_at text,
    enabled text,
    is_deleted text,
    "name" text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE scheduled_shift_break (
    shift_id text,
    length text,
    "type" text,
    PRIMARY KEY (shift_id),
    FOREIGN KEY (shift_id) REFERENCES shift(id)
);

CREATE TABLE shift_request_messages (
    id text,
    account_id text,
    request_id text,
    swap_id text,
    user_id text,
    actor text,
    content text,
    created_at text,
    title text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (request_id) REFERENCES user_request(id),
    FOREIGN KEY (swap_id) REFERENCES shift_request_swap(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE swap_status (
    shift_id text,
    shift_request_swap_id text,
    user_id text,
    "status" text,
    user_status text,
    PRIMARY KEY (shift_id),
    FOREIGN KEY (shift_id) REFERENCES shift(id),
    FOREIGN KEY (shift_request_swap_id) REFERENCES shift_request_swap(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE shift_request_swap (
    id text,
    accepted_id text,
    account_id text,
    creator_id text,
    location_id text,
    shift_id text,
    updater_id text,
    user_id text,
    actionable text,
    allowed_statuses text,
    canceled_id text,
    completed_at text,
    created_at text,
    "status" text,
    "type" text,
    updated_at text,
    user_status text,
    PRIMARY KEY (id),
    FOREIGN KEY (accepted_id) REFERENCES users(id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (shift_id) REFERENCES shift(id),
    FOREIGN KEY (updater_id) REFERENCES users(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE "time" (
    id text,
    account_id text,
    creator_id text,
    location_id text,
    modified_by text,
    position_id text,
    shift_id text,
    site_id text,
    user_id text,
    alert_type text,
    created_at text,
    end_time text,
    hourly_rate text,
    is_alerted text,
    is_approved text,
    length text,
    notes text,
    rounded_end_time text,
    rounded_length text,
    rounded_start_time text,
    split_time text,
    start_time text,
    sync_hash text,
    sync_id text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (modified_by) REFERENCES users(id),
    FOREIGN KEY (position_id) REFERENCES "position"(id),
    FOREIGN KEY (shift_id) REFERENCES shift(id),
    FOREIGN KEY (site_id) REFERENCES site(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE payroll (
    id text,
    account_id text,
    creator_id text,
    created_at text,
    end_date text,
    is_closed text,
    offsets text,
    start_date text,
    updated_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE user_request (
    id text,
    open_shift_request_id text,
    user_id text,
    created_at text,
    deleted_at text,
    PRIMARY KEY (id),
    FOREIGN KEY (open_shift_request_id) REFERENCES open_shift_request(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE open_shift_request (
    id text,
    account_id text,
    creator_id text,
    shift_id text,
    updater_id text,
    created_at text,
    is_shared text,
    "status" text,
    updated_at text,
    user_status text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (creator_id) REFERENCES users(id),
    FOREIGN KEY (shift_id) REFERENCES shift(id),
    FOREIGN KEY (updater_id) REFERENCES users(id)
);

CREATE TABLE user_location (
    location_id text,
    user_id text,
    PRIMARY KEY (location_id, user_id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_position (
    position_id text,
    user_id text,
    PRIMARY KEY (position_id, user_id),
    FOREIGN KEY (position_id) REFERENCES "position"(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    account_id text,
    activated text,
    affiliate text,
    alert_settings_absences_email text,
    alert_settings_absences_sms text,
    alert_settings_attendance_email text,
    alert_settings_attendance_sms text,
    alert_settings_availability_email text,
    alert_settings_availability_sms text,
    alert_settings_hire_email text,
    alert_settings_hire_sms text,
    alert_settings_new_employee_email text,
    alert_settings_new_employee_sms text,
    alert_settings_ot_alerts_email text,
    alert_settings_ot_alerts_sms text,
    alert_settings_payroll_sms text,
    alert_settings_reminders_email text,
    alert_settings_reminders_sms text,
    alert_settings_reporting_email text,
    alert_settings_reporting_sms text,
    alert_settings_schedule_email text,
    alert_settings_schedule_sms text,
    alert_settings_shift_bidding_email text,
    alert_settings_shift_bidding_sms text,
    alert_settings_swaps_email text,
    alert_settings_swaps_sms text,
    alert_settings_timeoff_email text,
    alert_settings_timeoff_sms text,
    alert_settings_workchat_alerts text,
    alert_settings_workchat_badge_icon text,
    alert_settings_workchat_in_app text,
    alert_settings_workplace_alerts_email text,
    alert_settings_workplace_alerts_sms text,
    avatar_key text,
    country_code text,
    country_id text,
    created_at text,
    created_by text,
    delete_at text,
    delete_reason text,
    deleted_at text,
    deletion_queued text,
    dismissed_at text,
    email text,
    employee_code text,
    first_name text,
    hired_on text,
    hourly_rate text,
    hours_max text,
    hours_preferred text,
    infotip text,
    invited_at text,
    is_active text,
    is_deleted text,
    is_hidden text,
    is_internal_login text,
    is_onboarded text,
    is_payroll text,
    is_private text,
    is_trusted text,
    last_login text,
    last_name text,
    login_id text,
    migration_id text,
    my_position text,
    notes text,
    notified_at text,
    password text,
    phone_number text,
    position_quality text,
    position_rates text,
    queued_delete_type text,
    reminder_time text,
    "role" text,
    sleep_end text,
    sleep_start text,
    terminated_at text,
    timezone_id text,
    timezone_name text,
    "type" text,
    updated_at text,
    uuid text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);
