CREATE TABLE subscription_plan_price (
    "index" text,
    subscription_plan_id text,
    amount text,
    currency text,
    setup_fee text,
    PRIMARY KEY ("index", subscription_plan_id),
    FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan(id)
);

CREATE TABLE subscription_plan (
    id text,
    project_id text,
    active_period_date_end text,
    active_period_date_start text,
    billing_retry_value text,
    charge_amount text,
    charge_currency text,
    charge_period_type text,
    charge_period_value text,
    expiration_type text,
    expiration_value text,
    external_id text,
    grace_period_type text,
    grace_period_value text,
    group_id text,
    localized_name text,
    recurrent_bonus text,
    refund_period text,
    remind_days_before_charge text,
    remind_days_before_notify text,
    status_counter_active text,
    status_counter_canceled text,
    status_counter_frozen text,
    status_counter_non_renewing text,
    status_value text,
    tags jsonb,
    trial_type text,
    trial_value text,
    "type" text,
    -- description_* (dynamic column),
    -- name_* (dynamic column),
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE validity_period (
    id text,
    "index" text,
    promotion_id text,
    froms text,
    offsets text,
    tos text,
    PRIMARY KEY (id, "index", promotion_id),
    FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE "transaction" (
    id text,
    transaction_detail_user_id text,
    project_id text,
    project_payment_method_id text,
    checkout_amount text,
    checkout_currency text,
    customer_billing_address text,
    customer_bin text,
    customer_browser_language text,
    customer_id text,
    customer_paystation_country text,
    customer_timezone text,
    direct_account text,
    dry_run text,
    external_id text,
    finance_balance_sum_amount text,
    finance_balance_sum_currency text,
    finance_chargeback_penalty_amount text,
    finance_chargeback_penalty_currency text,
    finance_payment_amount text,
    finance_payment_currency text,
    finance_payment_method_fee_amount text,
    finance_payment_method_fee_currency text,
    finance_payment_method_sum_amount text,
    finance_payment_method_sum_currency text,
    finance_payout_amount text,
    finance_payout_currency text,
    finance_payout_currency_rate text,
    finance_refund_penalty_amount text,
    finance_refund_penalty_currency text,
    finance_repatriation_commission_amount text,
    finance_repatriation_commission_currency text,
    finance_sales_tax_amount text,
    finance_sales_tax_currency text,
    finance_vat_amount text,
    finance_vat_currency text,
    finance_xsolla_fee_amount text,
    finance_xsolla_fee_currency text,
    is_payment_from_subscription text,
    is_subscription_created text,
    payment_card_holder_name text,
    payment_card_issuer text,
    payment_card_month text,
    payment_card_number text,
    payment_card_scheme text,
    payment_card_year text,
    payment_customer_first_name text,
    payment_customer_last_name text,
    payment_detail_amount text,
    payment_detail_amount_from_ps text,
    payment_detail_chargeback_penalty_amount text,
    payment_detail_commission_agent_amount text,
    payment_detail_commission_agent_fixed text,
    payment_detail_commission_agent_percent text,
    payment_detail_commission_ps_amount text,
    payment_detail_commission_ps_fixed_amount text,
    payment_detail_commission_ps_percent text,
    payment_detail_commission_ps_vat_amount text,
    payment_detail_commission_user_amount text,
    payment_detail_commission_user_percent text,
    payment_detail_commission_xsolla_amount text,
    payment_detail_commission_xsolla_fixed_amount text,
    payment_detail_commission_xsolla_percent text,
    payment_detail_cpa_network_commission_amount text,
    payment_detail_cpa_network_commission_percent text,
    payment_detail_currency text,
    payment_detail_direct_wht_amount text,
    payment_detail_direct_wht_percent text,
    payment_detail_payout_amount text,
    payment_detail_payout_amount_from_ps text,
    payment_detail_payout_currency text,
    payment_detail_payout_fx_rate text,
    payment_detail_payout_percent text,
    payment_detail_refund_penalty_amount text,
    payment_detail_repatriation_cost_amount text,
    payment_detail_repatriation_cost_percent text,
    payment_detail_sales_tax_amount text,
    payment_detail_sales_tax_percent text,
    payment_detail_vat_amount text,
    payment_detail_vat_percent text,
    payment_detail_vat_user_amount text,
    payment_detail_vat_user_percent text,
    payment_enrollment text,
    payment_method_class text,
    payment_ps_account text,
    payment_zip_code text,
    purchase_amount text,
    purchase_friend_user_id text,
    purchase_items_amount text,
    purchase_order_id text,
    purchase_order_store_cart text,
    purchase_pin_code_amount text,
    purchase_pin_code_content text,
    purchase_pin_code_currency text,
    purchase_pin_code_drm text,
    purchase_pin_code_sku text,
    purchase_shipping_address text,
    purchase_simple_checkout_amount text,
    purchase_simple_checkout_currency text,
    purchase_subscription_id text,
    purchase_subscription_name text,
    purchase_subscription_plan_id text,
    purchase_subscription_product_id text,
    purchase_subscription_product_name text,
    purchase_virtual_currency text,
    purchase_virtual_currency_amount text,
    purchase_virtual_currency_name text,
    purchase_virtual_currency_quantity text,
    purchase_virtual_item_amount text,
    purchase_virtual_item_content text,
    purchase_virtual_item_currency text,
    purchase_virtual_items text,
    refund_reason_comment text,
    "status" text,
    total_amount text,
    total_currency text,
    transaction_detail_amount text,
    transaction_detail_cancellation_date text,
    transaction_detail_country text,
    transaction_detail_currency text,
    transaction_detail_custom_parameters jsonb,
    transaction_detail_foreign_invoice text,
    transaction_detail_gift_recipient_email text,
    transaction_detail_gift_recipient_id text,
    transaction_detail_payment_date text,
    transaction_detail_refund_comment text,
    transaction_detail_refund_reason text,
    transaction_detail_saved_payment_method text,
    transaction_detail_status text,
    transaction_purchase_virtual_currency_amount text,
    transfer_date text,
    user_balance_deduction_amount text,
    user_balance_payout_amount_from_balance text,
    user_balance_purchase_amount_from_balance text,
    user_country text,
    user_custom text,
    user_email text,
    user_id text,
    user_ip text,
    user_marketplace text,
    user_name text,
    user_phone text,
    PRIMARY KEY (id, transaction_detail_user_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (project_payment_method_id) REFERENCES project_payment_method(id)
);

CREATE TABLE ticket (
    id text,
    transaction_id text,
    author_name text,
    created_at text,
    is_audio text,
    requester_email text,
    sender text,
    "status" text,
    subject text,
    title text,
    "type" text,
    updated_at text,
    vote text,
    PRIMARY KEY (id),
    FOREIGN KEY (transaction_id) REFERENCES "transaction"(id)
);

CREATE TABLE reward_bonus (
    id text,
    promotion_id text,
    reward_id text,
    localized_name text,
    quantity text,
    sku text,
    PRIMARY KEY (id, promotion_id, reward_id),
    FOREIGN KEY (promotion_id) REFERENCES reward(promotion_id),
    FOREIGN KEY (reward_id) REFERENCES reward(id)
);

CREATE TABLE reward_discount (
    "index" text,
    promotion_id text,
    reward_id text,
    discount_percent text,
    localized_name text,
    max_amount text,
    sku text,
    PRIMARY KEY ("index", promotion_id, reward_id),
    FOREIGN KEY (promotion_id) REFERENCES reward(promotion_id),
    FOREIGN KEY (reward_id) REFERENCES reward(id)
);

CREATE TABLE reward (
    id text,
    promotion_id text,
    package_bonus_amount text,
    package_bonus_percent text,
    purchase_discount_percent text,
    subscription_trial_days text,
    PRIMARY KEY (id, promotion_id),
    FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE event_tag (
    "index" text,
    event_id text,
    tag_id text,
    PRIMARY KEY ("index", event_id),
    FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE event (
    id text,
    agent_id text,
    complete_description text,
    sender text,
    short_message text,
    PRIMARY KEY (id)
);

CREATE TABLE product_description (
    "index" text,
    product_id text,
    project_id text,
    description_id text,
    PRIMARY KEY ("index", product_id, project_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (project_id) REFERENCES product(project_id)
);

CREATE TABLE product (
    id text,
    project_id text,
    group_id text,
    "name" text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE subscription_payment (
    id text,
    project_id text,
    subscription_id text,
    subscription_plan_id text,
    subscription_product_id text,
    subscription_user_id text,
    date_payment text,
    id_payment text,
    "status" text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (subscription_id) REFERENCES subscription(id),
    FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plan(id),
    FOREIGN KEY (subscription_product_id) REFERENCES product(id),
    FOREIGN KEY (subscription_user_id) REFERENCES "transaction"(user_id)
);

CREATE TABLE project_payment_method_price (
    "index" text,
    project_id text,
    project_payment_method_id text,
    currencies text,
    description text,
    fee_fixed_currency text,
    fee_fixed_value text,
    fee_percent text,
    is_unknown_commission text,
    repatriation_cost text,
    transaction_limit_currency_iso text,
    transaction_limit_max text,
    transaction_limit_min text,
    PRIMARY KEY ("index", project_id, project_payment_method_id),
    FOREIGN KEY (project_id) REFERENCES project_payment_method(project_id),
    FOREIGN KEY (project_payment_method_id) REFERENCES project_payment_method(id)
);

CREATE TABLE project_payment_method (
    id text,
    project_id text,
    can_be_enabled text,
    categories text,
    countries text,
    enabled text,
    image_url text,
    market_shares jsonb,
    "name" text,
    region text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE payout_breakdown_in_currency (
    _fivetran_id text,
    direct_taxes_of_payments text,
    iso_currency text,
    payments_amount text,
    "status" text,
    sum_commission_agent text,
    sum_commission_user_taxes text,
    sum_items text,
    sum_nominal_sum text,
    sum_out_project text,
    sum_payout_sum text,
    taxes_of_payments text,
    PRIMARY KEY (_fivetran_id)
);

CREATE TABLE promotion_detail (
    id text,
    promotion_id text,
    project_id text,
    enabled text,
    read_only text,
    show_banner text,
    technical_name text,
    -- description_* (dynamic column),
    -- label_* (dynamic column),
    -- name_* (dynamic column),
    PRIMARY KEY (id, promotion_id),
    FOREIGN KEY (promotion_id) REFERENCES promotion(id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_monetization (
    id text,
    project_id text,
    "name" text,
    name_canonical text,
    order_position text,
    translation_label text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_platform (
    id text,
    project_id text,
    "name" text,
    name_canonical text,
    order_position text,
    translation_label text,
    PRIMARY KEY (id, project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project_locale (
    "index" text,
    "name" text,
    project_id text,
    PRIMARY KEY ("index", "name", project_id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE project (
    id text,
    auto_redirect_from_status_page text,
    auto_redirect_from_status_page_in_second text,
    card_recurring text,
    coupon_custom_name jsonb,
    coupon_enabled text,
    coupon_live text,
    coupon_status text,
    description text,
    descriptor text,
    enabled text,
    game_delivery_custom_name jsonb,
    game_delivery_enabled text,
    game_delivery_live text,
    game_delivery_status text,
    game_engine_other text,
    game_engines jsonb,
    img text,
    integration_type text,
    interface_logo text,
    ipn_enabled text,
    is_cancel_implemented text,
    is_external_id_required text,
    is_project_active text,
    is_sandbox_available text,
    is_send_email text,
    is_universal_item_enabled text,
    item_custom_name jsonb,
    item_enabled text,
    item_live text,
    item_status text,
    "key" text,
    keywords text,
    monetization_other text,
    offerwall_enabled text,
    payment_url text,
    payments_available text,
    physical_goods_custom_name jsonb,
    physical_goods_enabled text,
    physical_goods_live text,
    physical_goods_status text,
    product_anti_fraud_status text,
    product_funding_status text,
    product_launcher_status text,
    product_login_status text,
    product_partner_network_status text,
    product_pay_station_status text,
    product_payout_status text,
    product_site_builder_status text,
    product_store_status text,
    product_subscription_status text,
    release_date text,
    release_period_type_description text,
    release_period_type_id text,
    release_period_type_name text,
    return_url text,
    secondary_market jsonb,
    send_email_for_user_billing_purchase text,
    send_json_to_paystation text,
    show_user_in_paystation text,
    simple_checkout_custom_name jsonb,
    simple_checkout_enabled text,
    simple_checkout_live text,
    simple_checkout_status text,
    solution_game_sales text,
    solution_payment text,
    solution_web_shop text,
    status_page_return_to_game_link_name text,
    status_page_show_return_to_game_link text,
    subscription_custom_name jsonb,
    subscription_enabled text,
    subscription_live text,
    subscription_status text,
    temp_project_protocol_key text,
    url text,
    user_billing_enabled text,
    user_public_id_enabled text,
    users_count text,
    virtual_currency_custom_name jsonb,
    virtual_currency_enabled text,
    virtual_currency_live text,
    virtual_currency_status text,
    xsolla_tips_enabled text,
    xsolla_tips_settings jsonb,
    -- name_* (dynamic column),
    PRIMARY KEY (id)
);

CREATE TABLE payout (
    id text,
    agreement_document_id text,
    amount_in_draft_currency text,
    cancelled_transactions_amount text,
    "comment" text,
    date_created text,
    date_paid text,
    draft_currency text,
    draft_currency_precision text,
    draft_document_id text,
    legal_entity_id text,
    legal_entity_name text,
    payment_currency text,
    rate text,
    reporting_period text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (agreement_document_id) REFERENCES report(agreement_document_id)
);

CREATE TABLE subscription (
    id text,
    plan_id text,
    project_id text,
    user_id text,
    charge_amount text,
    "comment" text,
    country_iso text,
    currency text,
    date_create text,
    date_end text,
    date_last_charge text,
    date_next_charge text,
    product_id text,
    "status" text,
    PRIMARY KEY (id),
    FOREIGN KEY (plan_id) REFERENCES subscription_plan(id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (user_id) REFERENCES "transaction"(user_id)
);

CREATE TABLE report (
    id text,
    agreement_document_id text,
    currency text,
    is_direct_payout text,
    is_draft_by_agreement text,
    "month" text,
    "year" text,
    PRIMARY KEY (id)
);

CREATE TABLE ticket_comment (
    id text,
    ticket_id text,
    author_name text,
    body text,
    created_at text,
    public text,
    PRIMARY KEY (id, ticket_id),
    FOREIGN KEY (ticket_id) REFERENCES ticket(id)
);

CREATE TABLE promotion (
    id text,
    project_id text,
    datetime_from text,
    datetime_to text,
    is_active text,
    is_infinite text,
    project_localized_name text,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE subject_item (
    id text,
    promotion_id text,
    subject_id text,
    localized_name text,
    sku text,
    PRIMARY KEY (id, promotion_id, subject_id),
    FOREIGN KEY (promotion_id) REFERENCES subject(promotion_id),
    FOREIGN KEY (subject_id) REFERENCES subject(id)
);

CREATE TABLE subject_subscription_plan (
    plan_id text,
    promotion_id text,
    subject_id text,
    PRIMARY KEY (plan_id, promotion_id, subject_id),
    FOREIGN KEY (plan_id) REFERENCES subscription_plan_price(subscription_plan_id),
    FOREIGN KEY (promotion_id) REFERENCES subject(promotion_id),
    FOREIGN KEY (subject_id) REFERENCES subject(id)
);

CREATE TABLE subject_subscription_product (
    product_id text,
    promotion_id text,
    subject_id text,
    PRIMARY KEY (product_id, promotion_id, subject_id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (promotion_id) REFERENCES subject(promotion_id),
    FOREIGN KEY (subject_id) REFERENCES subject(id)
);

CREATE TABLE subject (
    id text,
    promotion_id text,
    digital_contents text,
    packages text,
    purchase text,
    subscription_max_charges_count text,
    subscriptions_plans jsonb,
    PRIMARY KEY (id, promotion_id),
    FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE payment_system (
    id text,
    payment_system_parent_id text,
    promotion_id text,
    "name" text,
    PRIMARY KEY (id, payment_system_parent_id, promotion_id)
);
