CREATE TABLE conversion_tracker (
    id text,
    account_id text,
    advanced_matching_enabled text,
    all_conversion text,
    all_conversion_value text,
    app_conversion_app_id text,
    app_conversion_platform text,
    base_account_id text,
    category text,
    compare_operator text,
    conversion text,
    conversion_value text,
    conversion_value_via_ad_click text,
    conversions_via_ad_click text,
    counting_type text,
    cross_device_conversion text,
    exclude_from_bidding text,
    is_previous_conversion text,
    measurement_period text,
    measurement_period_view text,
    most_recent_conversion_date text,
    "name" text,
    rule_type text,
    snippet_id text,
    "status" text,
    "type" text,
    url text,
    user_revenue_value text,
    view_through_conversion text,
    web_conversion jsonb,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE conversion_group_conversion (
    "index" text,
    account_id text,
    conversion_group_id text,
    conversion_tracker_id text,
    "status" text,
    tag_id text,
    tag_name text,
    tracker_id text,
    PRIMARY KEY ("index", account_id, conversion_group_id),
    FOREIGN KEY (account_id) REFERENCES conversion_group(account_id),
    FOREIGN KEY (conversion_group_id) REFERENCES conversion_group(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id)
);

CREATE TABLE conversion_group (
    id text,
    account_id text,
    base_account_id text,
    "name" text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE ad_group_ad_label (
    "index" text,
    account_id text,
    ad_group_ad_id text,
    color text,
    description text,
    id text,
    "name" text,
    PRIMARY KEY ("index", account_id, ad_group_ad_id),
    FOREIGN KEY (account_id) REFERENCES ad_group_ad(account_id),
    FOREIGN KEY (ad_group_ad_id) REFERENCES ad_group_ad(id)
);

CREATE TABLE ad_group_ad (
    id text,
    account_id text,
    ad_group_id text,
    campaign_id text,
    ad_type text,
    approval_status text,
    banner_ad jsonb,
    base_account_id text,
    carousel_ad jsonb,
    carousel_gain_friends_ad jsonb,
    created_date text,
    custom_parameters jsonb,
    disapproval_reason_codes text,
    disapproval_reason_description text,
    display_url text,
    display_url_level text,
    dynamic_display_ad jsonb,
    final_url text,
    impression_beacon_urls jsonb,
    is_remove_impression_beacon_url text,
    is_remove_smartphone_final_url text,
    is_remove_third_party_tracking_script_url text,
    is_remove_tracking_url text,
    is_remove_viewable_impression_beacon_url text,
    main_media_format text,
    media_id text,
    "name" text,
    responsive_ad jsonb,
    responsive_gain_friends_ad jsonb,
    smartphone_final_url text,
    text_ad jsonb,
    third_party_tracking_script_url text,
    third_party_tracking_vendor text,
    tracking_url text,
    updated_date text,
    user_status text,
    viewable_impression_beacon_urls jsonb,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign_label (
    "index" text,
    account_id text,
    campaign_id text,
    color text,
    description text,
    id text,
    "name" text,
    PRIMARY KEY ("index", account_id, campaign_id),
    FOREIGN KEY (account_id) REFERENCES campaign(account_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE campaign (
    id text,
    account_id text,
    ad_group_id text,
    conversion_tracker_id text,
    app_id text,
    app_name text,
    app_os_type text,
    base_account_id text,
    bidding_strategy_type text,
    budget_amount text,
    budget_id text,
    budget_name text,
    cpc_bidding_scheme text,
    cpf_bidding_scheme text,
    cpv_bidding_scheme text,
    created_date text,
    custom_parameters jsonb,
    delivery_type text,
    end_date text,
    end_time text,
    enhanced_cpc_enabled text,
    feed_id text,
    frequency_level text,
    frequency_time_unit text,
    goal text,
    is_remove_tracking_url text,
    maximize_conversion_target_roas text,
    maximize_conversions_target_cpa text,
    maximize_gaining_target_cpf text,
    "name" text,
    optimization_score text,
    optimizer_training_status text,
    serving_status text,
    skan_optimaize_ad_delivery_enabled text,
    skan_tcpa_target_type text,
    start_date text,
    start_time text,
    tracking_url text,
    updated_date text,
    user_status text,
    v_imps text,
    vcpm_bidding_scheme text,
    vendor_name text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (conversion_tracker_id) REFERENCES conversion_tracker(id)
);

CREATE TABLE ad_group_label (
    "index" text,
    account_id text,
    ad_group_id text,
    color text,
    description text,
    id text,
    "name" text,
    PRIMARY KEY ("index", account_id, ad_group_id),
    FOREIGN KEY (account_id) REFERENCES ad_group(account_id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id)
);

CREATE TABLE ad_group (
    id text,
    account_id text,
    base_account_id text,
    campaign_id text,
    cpc text,
    cpf text,
    cpv text,
    created_date text,
    custom_parameters jsonb,
    device jsonb,
    device_app jsonb,
    device_os jsonb,
    device_os_version text,
    enhanced_cpc_enabled text,
    exclude_line_oa_friend_audience_list_id text,
    feed_set_id text,
    is_remove_cpc text,
    is_remove_cpf text,
    is_remove_cpv text,
    is_remove_target_cpa text,
    is_remove_target_cpf text,
    is_remove_target_roas text,
    is_remove_tracking_url text,
    is_remove_vcpm text,
    "name" text,
    smart_targeting_enabled text,
    target_cpa text,
    target_cpf text,
    target_roas text,
    tracking_url text,
    updated_date text,
    user_status text,
    vcpm text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (base_account_id) REFERENCES account(base_account_id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE account (
    id text,
    auto_tagging_enabled text,
    base_account_id text,
    contact_biz_id text,
    delivery_status text,
    end_date text,
    is_mcc_account text,
    is_test_account text,
    "name" text,
    optimization_score text,
    start_date text,
    "status" text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE ad (
    _fivetran_id text,
    account_id text,
    ad_group_id text,
    ad_id text,
    campaign_id text,
    account_name text,
    ad_group_labels text,
    ad_group_name text,
    ad_group_user_status text,
    ad_labels text,
    ad_name text,
    ad_type text,
    ad_user_status text,
    age text,
    app text,
    app_id text,
    app_name text,
    app_os text,
    avg_cpc text,
    avg_cpm text,
    avg_cpv text,
    avg_duration_of_video_viewed text,
    avg_position text,
    avg_vcpm text,
    avg_video_view_rate text,
    campaign_buying_type text,
    campaign_delivery_type text,
    campaign_goals text,
    campaign_labels text,
    campaign_name text,
    campaign_type text,
    campaign_user_status text,
    city text,
    city_id text,
    clicks text,
    content_keyword text,
    content_keyword_id text,
    conv_rate text,
    conv_rate_all text,
    conv_rate_via_click text,
    conv_value text,
    conv_value_all text,
    conv_value_all_per_conv_all text,
    conv_value_all_per_cost text,
    conv_value_per_conv text,
    conv_value_per_cost text,
    conv_value_via_click text,
    conv_value_via_click_per_conv_via_click text,
    conv_value_via_click_per_cost text,
    conversions text,
    conversions_all text,
    conversions_via_click text,
    cost text,
    cost_per_conv text,
    cost_per_conv_all text,
    cost_per_conv_via_click text,
    cross_device_conv text,
    ctr text,
    "day" text,
    description_1 text,
    description_2 text,
    destination_url_campaign_banner text,
    device text,
    display_url text,
    file_name text,
    final_url text,
    gender text,
    hour_of_day text,
    impressions text,
    layout text,
    lifetime_budget text,
    main_media_format text,
    measured_impression_rate text,
    measured_impressions text,
    media_id text,
    media_name text,
    "month" text,
    os text,
    package_name text,
    paid_video_view_rate_cpv text,
    paid_video_views_cpv text,
    pixel_size text,
    prefecture_id text,
    prefectures text,
    responsive_ads_type text,
    search_keyword text,
    search_keyword_id text,
    title text,
    tracking_url text,
    video_view_through_rate text,
    video_views text,
    video_views_to_100_percentage text,
    video_views_to_10_sec text,
    video_views_to_25_percentage text,
    video_views_to_3_sec text,
    video_views_to_50_percentage text,
    video_views_to_75_percentage text,
    video_views_to_95_percentage text,
    view_through_conversions text,
    viewable_clicks text,
    viewable_ctr text,
    viewable_ctr_per_panel text,
    viewable_impression_rate text,
    viewable_impressions text,
    viewable_impressions_per_panel text,
    ward text,
    ward_id text,
    week text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (ad_id) REFERENCES ad_group_ad(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);

CREATE TABLE reach (
    _fivetran_id text,
    account_id text,
    ad_group_id text,
    ad_id text,
    campaign_id text,
    account_name text,
    ad_group_name text,
    ad_group_user_status text,
    ad_name text,
    ad_user_status text,
    avg_cpc text,
    avg_cpm text,
    avg_cpv text,
    avg_duration_of_video_viewed text,
    avg_frequency text,
    avg_vcpm text,
    avg_video_view_rate text,
    campaign_buying_type text,
    campaign_delivery_type text,
    campaign_end_date text,
    campaign_goals text,
    campaign_name text,
    campaign_start_date text,
    campaign_user_status text,
    clicks text,
    conv_rate text,
    conv_rate_all text,
    conv_rate_via_click text,
    conv_value_via_view_through text,
    conversions text,
    conversions_all text,
    conversions_via_click text,
    cost text,
    cost_per_conv text,
    cost_per_conv_all text,
    cost_per_conv_via_click text,
    cross_device_conv text,
    ctr text,
    "day" text,
    impressions text,
    lifetime_budget text,
    measured_impression_rate text,
    measured_impressions text,
    package_name text,
    paid_video_view_rate_cpv text,
    paid_video_views_cpv text,
    reaches text,
    video_view_through_rate text,
    video_views text,
    video_views_to_100_percentage text,
    video_views_to_10_sec text,
    video_views_to_25_percentage text,
    video_views_to_3_sec text,
    video_views_to_50_percentage text,
    video_views_to_75_percentage text,
    video_views_to_95_percentage text,
    viewable_clicks text,
    viewable_ctr text,
    viewable_impression_rate text,
    viewable_impressions text,
    PRIMARY KEY (_fivetran_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (ad_group_id) REFERENCES ad_group(id),
    FOREIGN KEY (ad_id) REFERENCES ad_group_ad(id),
    FOREIGN KEY (campaign_id) REFERENCES campaign(id)
);
