CREATE TABLE location_category (
    category_id text,
    account_id text,
    location_id text,
    PRIMARY KEY (category_id, account_id, location_id),
    FOREIGN KEY (account_id) REFERENCES location(account_id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE location_photo (
    "index" text,
    account_id text,
    location_id text,
    alternate_text text,
    derivative jsonb,
    description text,
    height text,
    url text,
    width text,
    PRIMARY KEY ("index", account_id, location_id),
    FOREIGN KEY (account_id) REFERENCES location(account_id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);

CREATE TABLE location (
    id text,
    account_id text,
    accepting_new_patient text,
    additional_hours_text text,
    address text,
    address_2 text,
    admitting_hospital jsonb,
    alternate_name jsonb,
    alternate_phone text,
    alternate_website jsonb,
    association text,
    attire text,
    bio_list_id jsonb,
    bio_list_label text,
    certification jsonb,
    city text,
    competitor jsonb,
    condition_treated jsonb,
    country_code text,
    degree jsonb,
    description text,
    display_address text,
    display_lat text,
    display_lng text,
    display_menu_url text,
    display_order_url text,
    display_reservation_url text,
    display_website_url text,
    dropoff_lat text,
    dropoff_lng text,
    education_list jsonb,
    email jsonb,
    event_list_id jsonb,
    event_list_label text,
    facebook_call_action_type text,
    facebook_call_action_value text,
    facebook_cover_photo_alternatetext text,
    facebook_cover_photo_height text,
    facebook_cover_photo_url text,
    facebook_cover_photo_width text,
    facebook_page_url text,
    facebook_profile_picture_derivative jsonb,
    facebook_profile_picture_height text,
    facebook_profile_picture_source_url text,
    facebook_profile_picture_url text,
    facebook_profile_picture_width text,
    fax_phone text,
    featured_message text,
    featured_message_url text,
    first_party_review_page text,
    folder_id text,
    gender text,
    google_attribute jsonb,
    google_cover_photo_alternate_text text,
    google_cover_photo_height text,
    google_cover_photo_url text,
    google_cover_photo_width text,
    google_profile_photo_height text,
    google_profile_photo_url text,
    google_profile_photo_width text,
    holiday_hour jsonb,
    holiday_hour_confirmation_enabled text,
    hours text,
    instagram_handle text,
    insurance_accepted jsonb,
    intelligent_search_tracking_enabled text,
    intelligent_search_tracking_frequency text,
    is_closed text,
    is_cluster_primary text,
    is_phone_tracked text,
    iso_region_code text,
    keyword text,
    label_id jsonb,
    languages text,
    local_phone text,
    located_in text,
    location_keyword jsonb,
    logo_derivative jsonb,
    logo_height text,
    logo_url text,
    logo_width text,
    meal_served jsonb,
    menu_id jsonb,
    menu_url text,
    menus_label text,
    mobile_phone text,
    "name" text,
    npi text,
    office_name jsonb,
    order_url text,
    payment_option jsonb,
    phone text,
    pickup_lat text,
    pickup_lng text,
    place jsonb,
    price_range text,
    primary_contact text,
    produc_list_id jsonb,
    product text,
    product_list_id jsonb,
    product_list_label text,
    query_template jsonb,
    radius text,
    reservation_url text,
    review_balancing_url text,
    review_response_conversation_enabled text,
    routable_lat text,
    routable_lng text,
    schema_type jsonb,
    service jsonb,
    speciality jsonb,
    "state" text,
    sublocality text,
    suppress_address text,
    timestamps text,
    timezone text,
    toll_free_phone text,
    tracking_site text,
    tty_phone text,
    twitter_handle text,
    "type" text,
    uber_embed_code text,
    uber_link text,
    uber_link_raw text,
    uber_link_text text,
    uber_link_type text,
    uber_trip_branding_description text,
    uber_trip_branding_text text,
    uber_trip_branding_url text,
    uid text,
    unit text,
    video_url jsonb,
    walkable_lat text,
    walkable_lng text,
    website_url text,
    year_established text,
    yext_display_lat text,
    yext_display_lng text,
    yext_dropoff_lat text,
    yext_dropoff_lng text,
    yext_pickup_lat text,
    yext_pickup_lng text,
    yext_routable_lat text,
    yext_routable_lng text,
    yext_walkable_lat text,
    yext_walkable_lng text,
    zip text,
    -- custom_* (dynamic column),
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE publisher_brand (
    "index" text,
    account_id text,
    publisher_id text,
    "name" text,
    url text,
    PRIMARY KEY ("index", account_id, publisher_id),
    FOREIGN KEY (account_id) REFERENCES publisher(account_id),
    FOREIGN KEY (publisher_id) REFERENCES publisher(id)
);

CREATE TABLE publisher_supported_country (
    supported_country text,
    account_id text,
    publisher_id text,
    PRIMARY KEY (supported_country, account_id, publisher_id),
    FOREIGN KEY (account_id) REFERENCES publisher(account_id),
    FOREIGN KEY (publisher_id) REFERENCES publisher(id)
);

CREATE TABLE publisher_supported_entity (
    supported_entity_type text,
    account_id text,
    publisher_id text,
    PRIMARY KEY (supported_entity_type, account_id, publisher_id),
    FOREIGN KEY (account_id) REFERENCES publisher(account_id),
    FOREIGN KEY (publisher_id) REFERENCES publisher(id)
);

CREATE TABLE publisher_feature (
    feature text,
    account_id text,
    publisher_id text,
    PRIMARY KEY (feature, account_id, publisher_id),
    FOREIGN KEY (account_id) REFERENCES publisher(account_id),
    FOREIGN KEY (publisher_id) REFERENCES publisher(id)
);

CREATE TABLE publisher (
    id text,
    account_id text,
    "name" text,
    url text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE account (
    id text,
    contact_email text,
    contact_first_name text,
    contact_last_name text,
    contact_phone text,
    "name" text,
    sub_account_count text,
    PRIMARY KEY (id)
);

CREATE TABLE review_comment (
    id text,
    account_id text,
    review_id text,
    author_email text,
    author_name text,
    author_role text,
    content text,
    "date" text,
    is_automatic_response text,
    publisher_date text,
    suppress_reviewer_contact text,
    visibility text,
    PRIMARY KEY (id, account_id, review_id),
    FOREIGN KEY (account_id) REFERENCES review(account_id),
    FOREIGN KEY (review_id) REFERENCES review(id)
);

CREATE TABLE review_label (
    id text,
    account_id text,
    review_id text,
    "name" text,
    PRIMARY KEY (id, account_id, review_id),
    FOREIGN KEY (account_id) REFERENCES review(account_id),
    FOREIGN KEY (review_id) REFERENCES review(id)
);

CREATE TABLE review (
    id text,
    account_id text,
    location_id text,
    publisher_id text,
    api_identifier text,
    author_email text,
    author_name text,
    content text,
    external_id text,
    flag_status text,
    invitation_id text,
    label_id jsonb,
    last_yext_update_time text,
    publisher_date text,
    rating text,
    recommendation text,
    review_language text,
    review_type text,
    "status" text,
    title text,
    transaction_id text,
    url text,
    PRIMARY KEY (id, account_id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (location_id) REFERENCES location(id),
    FOREIGN KEY (publisher_id) REFERENCES publisher(id)
);
