CREATE TABLE channel_annotations_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_id text,
    annotation_impressions integer,
    annotation_type integer,
    country_code text,
    live_or_on_demand text,
    subscribed_status text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel (
    id text,
    branding_settings text,
    content_details_likes text,
    content_details_uploads text,
    content_owner_details text,
    etag text,
    kind text,
    localizations text,
    snippet_country text,
    snippet_custom_url text,
    snippet_default_language text,
    snippet_description text,
    snippet_localized text,
    snippet_published_at text,
    snippet_thumbnails text,
    snippet_title text,
    statistics_hidden_subscriber_count boolean,
    statistics_subscriber_count bigint,
    statistics_video_count bigint,
    statistics_view_count bigint,
    "status" text,
    topic_details text,
    PRIMARY KEY (id)
);

CREATE TABLE playlist_playback_location_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    playlist_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playback_location_detail text,
    playback_location_type integer,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE caption (
    languages text,
    "start" double precision,
    video_id text,
    duration double precision,
    text text,
    PRIMARY KEY (languages, "start", video_id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE video (
    id text,
    snippet_channel_id text,
    content_details_caption text,
    content_details_definition text,
    content_details_dimension text,
    content_details_duration text,
    content_details_has_custom_thumbnail boolean,
    content_details_licensed_content boolean,
    content_details_projection text,
    content_details_region_restriction text,
    etag text,
    kind text,
    player_embed_height bigint,
    player_embed_html text,
    player_embed_width bigint,
    privacy_status text,
    snippet_category_id text,
    snippet_channel_title text,
    snippet_default_audio_language text,
    snippet_default_language text,
    snippet_description text,
    snippet_live_broadcast_content text,
    snippet_localized text,
    snippet_published_at text,
    snippet_tags text,
    snippet_thumbnails text,
    snippet_title text,
    statistics_comment_count text,
    statistics_dislike_count text,
    statistics_favorite_count text,
    statistics_like_count text,
    statistics_view_count text,
    status_embeddable boolean,
    status_failure_reason text,
    status_license text,
    status_made_for_kids boolean,
    status_public_stats_viewable boolean,
    status_publish_at text,
    status_rejection_reason text,
    status_self_declared_made_for_kids boolean,
    upload_status text,
    PRIMARY KEY (id),
    FOREIGN KEY (snippet_channel_id) REFERENCES channel(id)
);

CREATE TABLE content_owner_end_screens_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    claimed_status text,
    country_code text,
    end_screen_element_click_rate double precision,
    end_screen_element_clicks integer,
    end_screen_element_id text,
    end_screen_element_impressions integer,
    end_screen_element_type integer,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_playlist_basic_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playlist_id text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_combined_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    playback_location_type integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    traffic_source_type integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_demographics_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    age_group text,
    country_code text,
    gender text,
    live_or_on_demand text,
    subscribed_status text,
    views_percentage double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_combined_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    playback_location_type integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    traffic_source_type integer,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_sharing_service_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    country_code text,
    live_or_on_demand text,
    shares integer,
    sharing_service integer,
    subscribed_status text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_device_os_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_sharing_service_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    claimed_status text,
    country_code text,
    live_or_on_demand text,
    shares integer,
    sharing_service integer,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_demographics_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    age_group text,
    claimed_status text,
    country_code text,
    gender text,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    views_percentage double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_combined_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    playback_location_type integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    traffic_source_type integer,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_province_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_impressions integer,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    card_click_rate double precision,
    card_clicks integer,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    claimed_status text,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    province_code text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_end_screens_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    country_code text,
    end_screen_element_click_rate double precision,
    end_screen_element_clicks integer,
    end_screen_element_id text,
    end_screen_element_impressions integer,
    end_screen_element_type integer,
    live_or_on_demand text,
    subscribed_status text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_traffic_source_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    traffic_source_detail text,
    traffic_source_type integer,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_playback_location_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playback_location_detail text,
    playback_location_type integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_ad_rates_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    ad_impressions integer,
    ad_type integer,
    claimed_status text,
    country_code text,
    estimated_cpm double precision,
    estimated_youtube_ad_revenue double precision,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE playlist (
    id text,
    snippet_channel_id text,
    content_details_item_count integer,
    etag text,
    kind text,
    localizations text,
    player_embed_html text,
    privacy_status text,
    snippet_channel_title text,
    snippet_default_language text,
    snippet_description text,
    snippet_localized text,
    snippet_published_at text,
    snippet_thumbnails text,
    snippet_title text,
    PRIMARY KEY (id),
    FOREIGN KEY (snippet_channel_id) REFERENCES channel(id)
);

CREATE TABLE channel_traffic_source_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    traffic_source_detail text,
    traffic_source_type integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_playlist_province_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playlist_id text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    province_code text,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_basic_a_3_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_impressions integer,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    card_click_rate double precision,
    card_clicks integer,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    claimed_status text,
    comments integer,
    country_code text,
    dislikes integer,
    engaged_views integer,
    likes integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    shares integer,
    subscribed_status text,
    subscribers_gained integer,
    subscribers_lost integer,
    uploader_type text,
    videos_added_to_playlists integer,
    videos_removed_from_playlists integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE playlist_combined_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    playlist_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    playback_location_type integer,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    traffic_source_type integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE playlist_traffic_source_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    playlist_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    traffic_source_detail text,
    traffic_source_type integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_subtitles_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    subtitle_language text,
    subtitle_language_autotranslated text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_traffic_source_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    traffic_source_detail text,
    traffic_source_type integer,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_subtitles_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    subtitle_language text,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_demographics_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    age_group text,
    asset_id text,
    claimed_status text,
    country_code text,
    gender text,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    views_percentage double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE playlist_basic_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    playlist_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_sharing_service_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    claimed_status text,
    country_code text,
    live_or_on_demand text,
    shares integer,
    sharing_service integer,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_end_screens_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    claimed_status text,
    country_code text,
    end_screen_element_click_rate double precision,
    end_screen_element_clicks integer,
    end_screen_element_id text,
    end_screen_element_impressions integer,
    end_screen_element_type integer,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE "comment" (
    id text,
    snippet_channel_id text,
    video_id text,
    can_reply boolean,
    etag text,
    is_public boolean,
    kind text,
    snippet_author_channel_id text,
    snippet_author_channel_url text,
    snippet_author_display_name text,
    snippet_author_profile_image_url text,
    snippet_can_rate boolean,
    snippet_like_count integer,
    snippet_moderation_status text,
    snippet_parent_id text,
    snippet_published_at text,
    snippet_text_display text,
    snippet_text_original text,
    snippet_updated_at text,
    snippet_viewer_rating text,
    total_reply_count integer,
    PRIMARY KEY (id),
    FOREIGN KEY (snippet_channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_annotations_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_id text,
    annotation_impressions integer,
    annotation_type integer,
    claimed_status text,
    country_code text,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_playlist_traffic_source_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playlist_id text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    traffic_source_detail text,
    traffic_source_type integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_playback_location_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playback_location_detail text,
    playback_location_type integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_playlist_playback_location_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playback_location_detail text,
    playback_location_type integer,
    playlist_id text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_cards_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    card_click_rate double precision,
    card_clicks integer,
    card_id text,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    card_type integer,
    claimed_status text,
    country_code text,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE playlist_province_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    playlist_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    province_code text,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_estimated_revenue_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    ad_impressions integer,
    claimed_status text,
    country_code text,
    estimated_cpm double precision,
    estimated_monetized_playbacks double precision,
    estimated_partner_ad_auction_revenue double precision,
    estimated_partner_ad_reserved_revenue double precision,
    estimated_partner_ad_revenue double precision,
    estimated_partner_red_revenue double precision,
    estimated_partner_revenue double precision,
    estimated_partner_transaction_revenue double precision,
    estimated_playback_based_cpm double precision,
    estimated_youtube_ad_revenue double precision,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_playlist_device_os_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    playlist_id text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_device_os_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_playlist_combined_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    playback_location_type integer,
    playlist_id text,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    traffic_source_type integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_playback_location_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    playback_location_detail text,
    playback_location_type integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_device_os_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    claimed_status text,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_estimated_revenue_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    claimed_status text,
    country_code text,
    estimated_partner_ad_auction_revenue double precision,
    estimated_partner_ad_reserved_revenue double precision,
    estimated_partner_ad_revenue double precision,
    estimated_partner_red_revenue double precision,
    estimated_partner_revenue double precision,
    estimated_partner_transaction_revenue double precision,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_basic_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_impressions integer,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    card_click_rate double precision,
    card_clicks integer,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    comments integer,
    country_code text,
    dislikes integer,
    engaged_views integer,
    likes integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    shares integer,
    subscribed_status text,
    subscribers_gained integer,
    subscribers_lost integer,
    videos_added_to_playlists integer,
    videos_removed_from_playlists integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_cards_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    asset_id text,
    card_click_rate double precision,
    card_clicks integer,
    card_id text,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    card_type integer,
    claimed_status text,
    country_code text,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_province_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_impressions integer,
    asset_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    card_click_rate double precision,
    card_clicks integer,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    claimed_status text,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    province_code text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    uploader_type text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_cards_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    card_click_rate double precision,
    card_clicks integer,
    card_id text,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    card_type integer,
    country_code text,
    live_or_on_demand text,
    subscribed_status text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE audience_retention (
    "date" text,
    elapsed_video_time_ratio text,
    video_id text,
    audience_watch_ratio double precision,
    relative_retention_performance double precision,
    PRIMARY KEY ("date", elapsed_video_time_ratio, video_id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE channel_province_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_impressions integer,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    card_click_rate double precision,
    card_clicks integer,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    country_code text,
    engaged_views integer,
    live_or_on_demand text,
    province_code text,
    red_views integer,
    red_watch_time_minutes double precision,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_annotations_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_impressions integer,
    annotation_title text,
    annotation_type integer,
    asset_id text,
    claimed_status text,
    country_code text,
    live_or_on_demand text,
    subscribed_status text,
    uploader_type text,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE content_owner_asset_basic_a_2_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    video_id text,
    annotation_click_through_rate double precision,
    annotation_clickable_impressions integer,
    annotation_clicks integer,
    annotation_closable_impressions integer,
    annotation_close_rate double precision,
    annotation_closes integer,
    annotation_impressions integer,
    asset_id text,
    average_view_duration_percentage double precision,
    average_view_duration_seconds double precision,
    card_click_rate double precision,
    card_clicks integer,
    card_impressions integer,
    card_teaser_click_rate double precision,
    card_teaser_clicks integer,
    card_teaser_impressions integer,
    claimed_status text,
    comments integer,
    country_code text,
    dislikes integer,
    engaged_views integer,
    likes integer,
    live_or_on_demand text,
    red_views integer,
    red_watch_time_minutes double precision,
    shares integer,
    subscribed_status text,
    uploader_type text,
    videos_added_to_playlists integer,
    videos_removed_from_playlists integer,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);

CREATE TABLE playlist_device_os_a_1_report (
    _fivetran_id text,
    "date" text,
    channel_id text,
    playlist_id text,
    video_id text,
    average_view_duration_seconds double precision,
    country_code text,
    device_type integer,
    engaged_views integer,
    live_or_on_demand text,
    operating_system integer,
    playlist_saves_added integer,
    playlist_saves_removed integer,
    playlist_starts integer,
    subscribed_status text,
    views integer,
    watch_time_minutes double precision,
    PRIMARY KEY (_fivetran_id, "date"),
    FOREIGN KEY (channel_id) REFERENCES channel(id),
    FOREIGN KEY (playlist_id) REFERENCES playlist(id),
    FOREIGN KEY (video_id) REFERENCES video(id)
);
