CREATE TABLE account (
    id text,
    account_manger_id text,
    created_by_id text,
    modified_by_id text,
    approval_state text,
    approve text,
    approved text,
    created_time text,
    currency text,
    currency_symbol text,
    delegate text,
    department_name text,
    editable text,
    exchange_rate text,
    followed text,
    is_attachment_present text,
    last_activity_time text,
    last_mailed_time text,
    modified_time timestamp,
    process_flow text,
    reject text,
    resubmit text,
    "state" text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_manger_id) REFERENCES users(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id)
);

CREATE TABLE account_tag (
    account_id text,
    id text,
    PRIMARY KEY (account_id, id),
    FOREIGN KEY (account_id) REFERENCES account(id),
    FOREIGN KEY (id) REFERENCES tags(id)
);

CREATE TABLE tags (
    id text,
    created_by_id text,
    modified_by_id text,
    color_code text,
    created_time text,
    modified_time text,
    module text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id)
);

CREATE TABLE job_opening_assigned_recruiter (
    id text,
    job_opening_id text,
    photo_src text,
    PRIMARY KEY (id, job_opening_id),
    FOREIGN KEY (id) REFERENCES users(id),
    FOREIGN KEY (job_opening_id) REFERENCES job_opening(id)
);

CREATE TABLE job_opening_tag (
    id text,
    job_opening_id text,
    PRIMARY KEY (id, job_opening_id),
    FOREIGN KEY (id) REFERENCES tags(id),
    FOREIGN KEY (job_opening_id) REFERENCES job_opening(id)
);

CREATE TABLE job_opening (
    id text,
    account_manager_id text,
    created_by_id text,
    modified_by_id text,
    approval_state text,
    approve text,
    approved text,
    city text,
    company text,
    country text,
    created_time text,
    currency_symbol text,
    date_1 text,
    date_opened text,
    delegate text,
    department_id text,
    department_name text,
    editable text,
    followed text,
    industry text,
    is_attachment_present text,
    is_hot_job_opening text,
    is_locked text,
    job_description text,
    job_opening_id text,
    job_opening_name text,
    job_opening_status text,
    job_type text,
    keep_on_career_site text,
    last_activity_time text,
    modified_time timestamp,
    n_1_no_sati_automation text,
    no_of_candidates_associated text,
    no_of_candidates_hired text,
    number_of_positions text,
    opal_no_sat_automation text,
    posting_title text,
    process_flow text,
    publish text,
    reject text,
    remote_job text,
    resubmit text,
    salary text,
    sati text,
    "state" text,
    "status" text,
    tech_non_tech text,
    zip_code text,
    PRIMARY KEY (id),
    FOREIGN KEY (account_manager_id) REFERENCES users(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id)
);

CREATE TABLE interview_tag (
    id text,
    interview_id text,
    PRIMARY KEY (id, interview_id),
    FOREIGN KEY (id) REFERENCES tags(id),
    FOREIGN KEY (interview_id) REFERENCES interview(id)
);

CREATE TABLE interviewer (
    id text,
    interview_id text,
    photo_src text,
    "status" text,
    status_value text,
    "type" text,
    PRIMARY KEY (id, interview_id),
    FOREIGN KEY (id) REFERENCES users(id),
    FOREIGN KEY (interview_id) REFERENCES interview(id)
);

CREATE TABLE interview (
    id text,
    candidate_id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    approval_state text,
    approve text,
    approved text,
    cancellation_reason text,
    candidate_confirmed text,
    candidate_number text,
    created_time text,
    currency_symbol text,
    delegate text,
    department_id text,
    department_name text,
    editable text,
    end_date_time text,
    feedback text,
    followed text,
    ignore_under_construction text,
    interview_duration_days text,
    interview_duration_hrs text,
    interview_duration_mins text,
    interview_enableevaluation text,
    interview_evaluation_done text,
    interview_name text,
    interview_start_time text,
    interview_status text,
    interview_type text,
    interviewer text,
    is_attachment_present text,
    is_locked text,
    job_opening_name text,
    last_activity_time text,
    link text,
    meeting_provider text,
    modified_time timestamp,
    password_new text,
    posting_title text,
    process_flow text,
    questionnaire_name text,
    reject text,
    rejection_reason text,
    reminder text,
    resubmit text,
    reviewed_by text,
    reviewed_time text,
    "role" text,
    schedule_comments text,
    start_date_time text,
    "state" text,
    taxable text,
    video_interview_is_reviewed text,
    video_interview_is_submitted text,
    video_interview_stage text,
    PRIMARY KEY (id),
    FOREIGN KEY (candidate_id) REFERENCES candidate(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE vendor_tag (
    id text,
    vendor_id text,
    PRIMARY KEY (id, vendor_id),
    FOREIGN KEY (id) REFERENCES tags(id),
    FOREIGN KEY (vendor_id) REFERENCES vendor(id)
);

CREATE TABLE vendor (
    id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    approval_state text,
    approve text,
    approved text,
    city text,
    comments text,
    country text,
    created_time text,
    currency_symbol text,
    delegate text,
    editable text,
    email text,
    email_opt_out text,
    exchange_rate text,
    followed text,
    is_attachment_present text,
    login_status text,
    modified_time timestamp,
    phone text,
    process_flow text,
    reject text,
    resubmit text,
    "state" text,
    "status" text,
    street text,
    vendor_login_status text,
    vendor_name text,
    website text,
    zipcode text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE user_territory (
    id text,
    users_id text,
    is_manager text,
    "name" text,
    PRIMARY KEY (id, users_id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE users (
    id text,
    profile_id text,
    role_id text,
    active text,
    alias text,
    city text,
    confirm text,
    country text,
    country_locale text,
    date_format text,
    date_of_birth text,
    decimal_separator text,
    default_tab_group text,
    email text,
    fax text,
    first_name text,
    full_name text,
    languages text,
    last_name text,
    locale text,
    mobile text,
    name_format text,
    personal_account text,
    phone text,
    report_to text,
    signature text,
    "state" text,
    "status" text,
    street text,
    theme_background text,
    theme_new_background text,
    theme_normal_tab_background text,
    theme_normal_tab_font_color text,
    theme_screen text,
    theme_selected_tab_background text,
    theme_selected_tab_font_color text,
    theme_type text,
    time_format text,
    time_zone text,
    url text,
    website text,
    zip text,
    zuid text,
    PRIMARY KEY (id),
    FOREIGN KEY (profile_id) REFERENCES profile(id),
    FOREIGN KEY (role_id) REFERENCES "role"(id)
);

CREATE TABLE candidate (
    id text,
    created_by_id text,
    modified_by_id text,
    owner_id text,
    application_type text,
    applied_with_linkedin text,
    approval_state text,
    approve text,
    approved text,
    associated_any_social_profiles text,
    blueprint_trigger text,
    by_pre_screen_form text,
    candidate_id text,
    candidate_status text,
    career_page_invite_status text,
    city text,
    company_info_from_close text,
    converted text,
    country text,
    created_time text,
    currency text,
    currency_symbol text,
    data_processing_basis_details text,
    date_of_1_st_interview text,
    date_of_2_nd_hoo_interview text,
    date_of_final_interview text,
    date_sati_received text,
    delegate text,
    editable text,
    eligible_for_referral_bonus text,
    email text,
    email_opt_out text,
    experience_in_years text,
    facebook text,
    first_name text,
    followed text,
    full_name text,
    full_time_internship_graduate_program text,
    gdpr_eu_applicant text,
    github text,
    github_score text,
    have_you_worked_with_them_before text,
    highest_qualification_held_major text,
    how_do_you_know_this_person text,
    interviewer_1 text,
    interviewer_1_3 text,
    interviewer_2 text,
    interviewer_2_1 text,
    interviewer_2_2 text,
    interviewer_2_3 text,
    interviewer_f_1 text,
    interviewer_f_2 text,
    interviewer_f_3 text,
    is_attachment_present text,
    is_locked text,
    is_unqualified text,
    last_activity_time text,
    last_mailed_time text,
    last_name text,
    latest_job_title_in_sati text,
    latest_monthly_salary text,
    latest_monthly_salary_end text,
    linked_in text,
    linked_in_template text,
    military_status text,
    mobile text,
    mofidied_by_id text,
    nationality_new text,
    origin text,
    other_info text,
    plagiarism_checked text,
    portfolio text,
    position_dropdown text,
    privacy_policy text,
    process_flow text,
    rating text,
    reject text,
    resubmit text,
    salary_type text,
    salutation text,
    sati text,
    scheduled_email text,
    secondary_email text,
    skill_set text,
    skype_id text,
    social text,
    social_media_checked text,
    social_profiles text,
    "source" text,
    source_code_dropdown text,
    source_codes_close text,
    "state" text,
    "status" text,
    street text,
    temp_team_name text,
    university_institution_graduated text,
    updated_on timestamp,
    vendor_name text,
    website text,
    what_are_their_skills_capabilities_competencies text,
    what_position_do_you_think_he_she_would_fit text,
    whatsapp_available text,
    willing_to_relocate text,
    zipcode text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE candidate_tag (
    candidate_id text,
    id text,
    PRIMARY KEY (candidate_id, id),
    FOREIGN KEY (candidate_id) REFERENCES candidate(id),
    FOREIGN KEY (id) REFERENCES tags(id)
);

CREATE TABLE questionnary_question (
    id text,
    questionnary_id text,
    hint text,
    is_mandatory text,
    is_unassociate text,
    question text,
    section_name text,
    "sequence" text,
    "type" text,
    PRIMARY KEY (id, questionnary_id),
    FOREIGN KEY (questionnary_id) REFERENCES questionnary(id)
);

CREATE TABLE questionnary (
    id text,
    category text,
    "name" text,
    ori_category text,
    rating_type text,
    rating_type_info text,
    "type" text,
    PRIMARY KEY (id)
);

CREATE TABLE organization (
    id text,
    alias text,
    city text,
    company_name text,
    country text,
    country_code text,
    description text,
    editor_mode text,
    employee_count text,
    fax text,
    hipaa_compliance_enabled text,
    iam_portal_name text,
    is_portal_exist text,
    license_expiry text,
    license_no_of_users text,
    license_paid text,
    license_paid_type text,
    license_plan_type text,
    mc_status text,
    mobile text,
    phone text,
    primary_email text,
    primary_user_id text,
    staffing_type text,
    "state" text,
    street text,
    time_zone text,
    "type" text,
    website text,
    zip text,
    PRIMARY KEY (id)
);

CREATE TABLE "role" (
    id text,
    reporting_to_id text,
    display_label text,
    "name" text,
    reporting_to_name text,
    share_with_peer text,
    PRIMARY KEY (id),
    FOREIGN KEY (reporting_to_id) REFERENCES "role"(id)
);

CREATE TABLE profile (
    id text,
    created_by_id text,
    modified_by_id text,
    created_by text,
    created_time text,
    description text,
    is_custom text,
    modified_time text,
    "name" text,
    PRIMARY KEY (id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id)
);

CREATE TABLE note (
    id text,
    candidate_id text,
    created_by_id text,
    job_opening_id text,
    modified_by_id text,
    note_owner_id text,
    action_from_status text,
    action_is_system_action text,
    action_to_status text,
    attachment text,
    created_time text,
    editable text,
    is_delete_allowed text,
    is_edit_allowed text,
    is_shared_to_client text,
    modified_time timestamp,
    note_content text,
    note_title text,
    parent_id text,
    parent_module text,
    parent_name text,
    se_module text,
    "size" text,
    source_name text,
    source_type text,
    type_id text,
    voice_note text,
    PRIMARY KEY (id),
    FOREIGN KEY (candidate_id) REFERENCES candidate(id),
    FOREIGN KEY (created_by_id) REFERENCES users(id),
    FOREIGN KEY (job_opening_id) REFERENCES job_opening(id),
    FOREIGN KEY (modified_by_id) REFERENCES users(id),
    FOREIGN KEY (note_owner_id) REFERENCES users(id)
);

CREATE TABLE submission (
    id text,
    modified_by text,
    submission_owner text,
    submitted_by text,
    candidate_name text,
    client_name text,
    description text,
    medium text,
    modified_on timestamp,
    "name" text,
    posting_title text,
    rating text,
    reviewed_by text,
    reviewer_comments text,
    "status" text,
    submitted_on text,
    submitted_to text,
    PRIMARY KEY (id),
    FOREIGN KEY (modified_by) REFERENCES users(id),
    FOREIGN KEY (submission_owner) REFERENCES users(id),
    FOREIGN KEY (submitted_by) REFERENCES users(id)
);
